### ISSUE TITLE
[dev]xcatflowrequest is slow when updatenode <onenode>

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#100]
When I execute updatenode, xcatflowrequest sleep about 3~8 minutes, make updatenode take 3~8 minutes;
Reproduce steps:
1, In management node:
[root@c910f05c01bc06 ~]# lsdef -t site -i useflowcontrol
Object name: clustersite
    useflowcontrol=1
[root@c910f05c01bc06 xCAT_plugin]# time updatenode bybc0608 -P
bybc0608: xcatdsklspost: downloaded postscripts successfully
bybc0608: Wed Aug 19 06:35:46 EDT 2015 Running postscript: syslog
bybc0608: rsyslog start/running, process 27734
bybc0608: Postscript: syslog exited with code 0
bybc0608: Wed Aug 19 06:35:46 EDT 2015 Running postscript: remoteshell
bybc0608: + /xcatpost/xcatflowrequest 10.5.106.1 3001
bybc0608: + rc=0
bybc0608: + set +x
bybc0608:
bybc0608: ssh start/running, process 28015
bybc0608: root     21413  0.0  0.0 105628  4244 ?        Ss   06:26   0:00 sshd: root@pts/1
bybc0608: root     27599  0.0  0.0 105628  4148 ?        Ss   06:35   0:00 sshd: root@notty
bybc0608: root     28015  0.0  0.0  61364  3028 ?        Ss   06:35   0:00 /usr/sbin/sshd -D
bybc0608: Postscript: remoteshell exited with code 0
bybc0608: Wed Aug 19 06:38:47 EDT 2015 Running postscript: syncfiles
bybc0608: Postscript: syncfiles exited with code 0
bybc0608: Wed Aug 19 06:38:47 EDT 2015 Running postscript: otherpkgs
bybc0608: ./otherpkgs: no extra rpms to install
bybc0608: Postscript: otherpkgs exited with code 0
bybc0608: Running of postscripts has completed.

real    3m2.176s
user    0m0.207s
sys     0m0.039s

From compute node:
root@bybc0608:~# pstree -a
init
  |-cron
  |-dbus-daemon --system --fork
  |-dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
  |-getty -8 38400 tty4
  |-getty -8 38400 tty5
  |-getty -8 38400 tty2
  |-getty -8 38400 tty3
  |-getty -8 38400 tty6
  |-getty -8 38400 tty1
  |-getty -L ttyS0 115200 vt102
  |-ntpd -p /var/run/ntpd.pid -g -c /var/lib/ntp/ntp.conf.dhcp -u 103:109
  |-rpc.idmapd
  |-rpc.statd -L
  |-rpcbind -w
  |-rsyslogd
  |   `-3*[{rsyslogd}]
  |-snmpd -Lsd -Lf /dev/null -u snmp -g snmp -I -smux mteTrigger mteTriggerConf -p /var/run/snmpd.pid
  |-sshd
  |   `-bash
  |       `-pstree -a
  |-sshd
  |   `-bash -c...
  |       `-file7qYAG2.dsh /tmp/file7qYAG2.dsh 1 -m 10.5.106.1  --tftp /tftpboot --installdir /install --nfsv4 no -c -F
  |           `-file7qYAG2.dsh /tmp/file7qYAG2.dsh 1 -m 10.5.106.1  --tftp /tftpboot --installdir /install --nfsv4 no -c -F
  |               `-tee -a /var/log/xcat/xcat.log
  |-sshd -D
  |-systemd-logind
  |-systemd-udevd --daemon
  |-upstart-file-br --daemon
  |-upstart-socket- --daemon
  |-upstart-udev-br --daemon
  |-xcatflowrequest /xcatpost/xcatflowrequest 10.5.106.1 3001
  |   `-sleep 157.5
  |-xcatflowrequest /xcatpost/xcatflowrequest 10.5.106.1 3001
  |   `-sleep 124.16
  |-xcatflowrequest /xcatpost/xcatflowrequest 10.5.106.1 3001
  |   `-sleep 164.36
  |-xcatflowrequest /xcatpost/xcatflowrequest 10.5.106.1 3001
  |   `-sleep 120.45
  `-xcatflowrequest /xcatpost/xcatflowrequest 10.5.106.1 3001
      `-sleep 158.1

root@bybc0608:~# ls /tmp
fileOhYNQX.dsh  ntpE30vLs  postage  sed.tmp  wget.log

**Comment by daniceexi** [comment]
xCAT will rethink the flow control feature later.

**Comment by whowutwut** [comment]
Should we leave this open and tag as "future " to keep as placeholder Instead of bug ?

**Comment by daniceexi** [comment]
I am afraid that we will have tons issues in open status if we keep this kind topic that we don't plan to fix in short time.

So recommend to tag it as 'future' and close the issue.
