### ISSUE TITLE
Involve ipmitool-xcat 1.8.15 and higher

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1000]
Continue the discussion in #910 that we should update the ipmitool-xcat to 1.8.15 or higher for all the platforms. 
And update the requires in **xCAT/xCAT.spec** and **xCAT/xCATsn.spec** too.

**Comment by daniceexi** [comment]
Could you assign this to someone in FVT to verify?

**Comment by whowutwut** [comment]
@daniceexi  can we move this to 2.12.1?

**Comment by daniceexi** [comment]
@whowutwut I am OK to move it to 2.12.1.
Now we need to give a list in the release notes that which OS the 1.8.15 has been added.

**Comment by whowutwut** [comment]
Sure. I can add this today. 

If we are touching ipmi tool build for this issue. Maybe should look at moving to 1.8.16

**Comment by whowutwut** [comment]
Updated the release notes for 2.12, moving to 2.12.1 to keep tracking this issue

**Comment by tingtli** [comment]
@daniceexi  I see you add a testcase_requested label here.  I am not very sure what test case you think should verify this scenario.

**Comment by daniceexi** [comment]
I just want to make sure the high version of ipmitool has been added for each arch. But I think we can close it now.
