### ISSUE TITLE
lsvm command does not work for kvm VMs

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#1002]
lsvm command does not work for kvm VMs.

1. It appears to insist on some value from the hypervisor table. But rmvm or mkvm only care about nodehm. I think lsvm should do the same.

2. There is code already in kvm.pm to handle lsvm command, but it appears to fail. It should probably mimic rmvm code.

**Comment by daniceexi** [comment]
@gurevichmark I think there need some enhancement to support lsvm for both **kvmhost** and **VM**. So I set it to be a feature and move to 2.12.1

**Comment by gurevichmark** [comment]
Xiaopeng,

Currently, the man page for lsvm command states that lsvm only works for 
kvmhost, and I can see that code is there to handle that. With just a 
little change in kvm.pm, I can make lsvm work for kvmhost. The change is 
in handled_commands(), to make lsvm similar to the rscan:



With the change above, lsvm works for kvmhost:



Can I propose that we keep issue #1002 in 2.12 to fix lsvm for kvmhost and 
then open a separate issue for 2.12.1 to add new code to handle lsvm for 
an individual VM ?

Thank you,

Mark Gurevich
Poughkeepsie Development Lab
HPC Software Development - xCAT

"If we knew what it was we were doing, it would not be called research, 
would it?"
--Albert Einstein

**Comment by whowutwut** [comment]
![image](https://cloud.githubusercontent.com/assets/10049070/14923907/ea82491e-0e0d-11e6-9abe-3ee5b5677185.png)

**Comment by gurevichmark** [comment]
@daniceexi 

Currently, the man page for **lsvm** command states that **lsvm** only works for **kvmhost**, and I can see code there to handle that. With just a little change in **kvm.pm**, I can make **lsvm** work for **kvmhost**. The change is in **handled_commands()**, to make **lsvm** similar to the **rscan**: 

```
sub handled_commands {
    return {
        rpower   => 'nodehm:power,mgt',
        mkvm     => 'nodehm:power,mgt',
        clonevm  => 'nodehm:power,mgt',
        chvm     => 'nodehm:power,mgt',
        rmvm     => 'nodehm:power,mgt',
        rinv     => 'nodehm:power,mgt',
        rmigrate => 'nodehm:mgt',
        getcons  => 'nodehm:mgt',
 -->   rscan => 'nodehm:mgt=ipmi',
        #rvitals => 'nodehm:mgt',
        #rinv => 'nodehm:mgt',
        getrvidparms  => 'nodehm:mgt',
        #lsvm          => 'hypervisor:type',
-->    lsvm => 'nodehm:mgt=ipmi',
        rbeacon       => 'nodehm:mgt',
        revacuate     => 'hypervisor:type',
        vmstatenotify => 'hypervisor:type',
```

With the change above, **lsvm** works for **kvmhost**:

```
[root@fs2vm100 xcat]# lsvm fs2
fs2: fs2vm200
fs2: fs2vm100
fs2: fs2vm102
fs2: fs2vm151
fs2: fs2vm111
fs2: fs2vm101
fs2: fs2vm104
fs2: fs2vm103
fs2: fs2vm107
[root@fs2vm100 xcat]#
```
 Can I propose that we keep issue #1002 in 2.12 to fix **lsvm** for **kvmhost** and then open a separate issue for 2.12.1 to add new code to handle **lsvm** for an individual VM ?

**Comment by daniceexi** [comment]
@gurevichmark Thanks for the digging. The change for lsvm looks safe, I'd like to add them in 2.12 release if you can finish it.

**Comment by gurevichmark** [comment]
Pull request #1022 was used to enable lsvm for kvm hypervisor.
Issue #1023 was created to enhance lsvm command to work for an individual kvm VM.

**Comment by whowutwut** [comment]
@tingtli  I added a request for testcase here because I'm wondering whether we test the lsvm command for KVM....  and if so, how come it passed before??  Are we testing it for HMC only?
