### ISSUE TITLE
The issue of  strong package dependency 

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1005]
The xcat-core 2.12 depends "perl-HTTP-Async" and "perl-Net-HTTPS-NB" packages, we should remove the strong package dependency in build.

**Comment by daniceexi** [comment]
We can move the 'perl-Net-HTTPS-NB perl-HTTP-Async' to %notpcm part in ./xCAT-server/xCAT-server.spec

~~~~ 
%if %notpcm
%ifos linux
# ifarch/ifnarch does not work for noarch package
#%ifnarch s390x
# PCM does not use or ship grub2-xcat
Requires: grub2-xcat
#%endif
%endif
%endif
~~~~

**Comment by whowutwut** [comment]
@zet809  when you make those suggested changes, can we delete the code above in the snip that is commented out.

**Comment by fenggaobj** [comment]
Test in RHEL and passed
