### ISSUE TITLE
[FVT]: remove "chdef -t node -o $$CN vmstorage=dir:///var/lib/libvirt/images/ from provision case

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1006]
we have several cases which has "chdef -t node -o $$CN vmstorage=dir:///var/lib/libvirt/images/" to create vm . since defect #995  is fixed. we don't need to use chdef in the cases. Please remove that. 

The cases are 
Diskless_installation_flat_p8_le
reg_linux_diskfull_installation_flat
reg_linux_SN_installation_hierarchy
ubuntu_diskless_installation_vm
ubuntu_full_installation_vm_docker

**Comment by tingtli** [comment]
@junxiawang Do you have any updates for this ?

**Comment by junxiawang** [comment]
commit a9d29f2  
updated
