### ISSUE TITLE
[FVT]:restart xcatd get "Error happened when receiving data from DB access process Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /opt/xcat/lib/perl/xCAT/Table.pm line 127"

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1008]
rhels7.2 ppc64le  xcat 2.12

restart xcatd and get the following log message.
Apr 29 03:15:44 c910f03c05k23 xcat[29091]: INFO xcatd: 'Command log writer' process 29091 is terminated by TERM or INT signal
Apr 29 03:15:44 c910f03c05k23 xcat[29088]: xcatd udp service 29088 quiescing
Apr 29 03:15:44 c910f03c05k23 xcat[29089]: xcatd install monitor 29089 quiescing
Apr 29 03:15:44 c910f03c05k23 xcat[29088]: xcatd: Error happened when receiving data from DB access process Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /opt/xcat/lib/perl/xCAT/Table.pm line 127.
Apr 29 03:15:46 c910f03c05k23 xcat[29180]: INFO xcatd: command log process 29180 start

**Comment by chenglch** [comment]
This is a original defect that db process exist before udp process which runs populate_site_hash to fetch data from db process at regular intervals.

**Comment by tingtli** [comment]
@chenglch @daniceexi With today's build, i still get this error. But this is not always reproduced.
Jun 27 08:18:24 c910f03c04k05 xcat[6572]: xcatd: Error happened when receiving data from DB access process Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /opt/xcat/lib/perl/xCAT/Table.pm line 131.

**Comment by daniceexi** [comment]
Even we have fixed some issues related to this problem, but we still found something more need be fixed. Move it to next release.

**Comment by tingtli** [comment]
verified on rhels7.2 and ubutu14.04.4. There is no error message when restart xcatd. 
root@c910f04x27v02:~# lsxcatd -v
Version 2.12.2 (git commit d3eaa578d09462577ccd43039af8ac75be3a1606, built Wed Jul 27 06:16:57 EDT 2016)

**Comment by mteguhsat** [comment]
Hello, I'm having this error in xCAT 2.14. 
Anyone can advice for troubleshooting and resolve this ?

**Comment by cxhong** [comment]
can u run `ps -ef | grep xcatd` ?  

can u able to restart xCATd?    if you can,  stop the xcatd,  check the xcatd process, there may be some processes left over and didn't clean up.   use `kill` command to kill the remain xCATd process, then start xcatd again.
