### ISSUE TITLE
[FVT]: updatenode returns some strange error message 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#101]
xCAT 2.10 20150714 build.

[root@c910f04x35 postscripts]# updatenode c910f04x36 "confignics -s"
 c910f04x36: xcatdsklspost: downloaded postscripts successfully
 c910f04x36: chmod: cannot access 'exited': No such file or directory <== please remove it.
 c910f04x36: chmod: cannot access 'with': No such file or directory
 c910f04x36: chmod: cannot access 'code': No such file or directory
 c910f04x36: chmod: cannot access '0': No such file or directory
 c910f04x36: Wed Jul 15 02:10:37 EDT 2015 Running postscript: confignics -s
 c910f04x36: confignics on c910f04x36: config install nic:1, remove: 0, iba ports :
 c910f04x36: enp0s26u1u5u5!50.4.36.1
 c910f04x36: confignics on c910f04x36: call 'configeth enp0s26u1u5u5 50.4.36.1 50 _0_0_0-255_0_0_0|'
 c910f04x36: configeth on c910f04x36: os type: redhat
 c910f04x36: configeth on c910f04x36: old configuration: 2: enp0s26u1u5u5: <BROAD CAST,MULTICAST,UP,LOWER_UP=""> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
 c910f04x36: link/ether 36:40:b5:b9:11:19 brd ff:ff:ff:ff:ff:ff
 c910f04x36: inet 50.4.36.1/8 brd 50.255.255.255 scope global enp0s26u1u5u5
 c910f04x36: valid_lft forever preferred_lft forever
 c910f04x36: inet6 fe80::3440:b5ff:feb9:1119/64 scope link
 c910f04x36: valid_lft forever preferred_lft forever
 c910f04x36: configeth on c910f04x36: new configuration
 c910f04x36: 50.4.36.1, 50.0.0.0, 255.0.0.0, 50.0.0.103
 c910f04x36: 2: enp0s26u1u5u5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc p fifo_fast state UNKNOWN mode DEFAULT qlen 1000
 c910f04x36: enp0s26u1u5u5
 c910f04x36: configeth on c910f04x36: enp0s26u1u5u5 no changed, return directly.
 c910f04x36: confignics on c910f04x36: call 'configeth -s eno1
 c910f04x36: configeth on c910f04x36: os type: redhat
 c910f04x36: GATEWAY=10.0.0.103
 c910f04x36: HOSTNAME=c910f04x36
 c910f04x36: Postscript: confignics -s exited with code 0
 c910f04x36: Running of postscripts has completed.

**Comment by bybai** [comment]
This cannot be reproduced in the same environment.
