### ISSUE TITLE
[FVT]2.12: xcat command will hange after xcatd restart

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1011]
env: all platform
build:
lsdef - Version 2.12 (git commit 8bdfc11977a18713e02022ae73567731860c4406, built Thu Apr 28 21:50:44 EDT 2016)
Hot to reproduce:
```
yum install xCAT
then  chdef -t node -o c910f02fsp01 hwtype=cec serial=103A4EP mgt=hmc groups=cec hcp=c910hmc01 nodetype=ppc mtm=8233-E8B
------------------------------> Command will hang  
And after restart xcatd the xcat command will hang sometimes.
```

**Comment by chenglch** [comment]
I add some debug code in Table.pm around Line 2584

     if (!defined($self->{nodelist})) {
        use Data::Dumper;
        xCAT::MsgUtils->message("S","cltest nodelist error ".Dumper($self));
      }
      use Carp 'verbose';
      $SIG{ __DIE__ } = sub { Carp::confess( @_ ) };
      **my ($nodeghash) = $self->{nodelist}->getAttribs({node => $node}, 'groups');**

The debug message is like this, seems a race condition when starting xcatd and get node data from db at the same time.

xcatd: possible BUG encountered by xCAT DB worker Can't call method "getAttribs" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 2591.
 at /opt/xcat/lib/perl/xCAT/Table.pm line 2589.
        xCAT::Table::__ANON__('Can\'t call method "getAttribs" on an undefined value at /opt...') called at /opt/xcat/lib/perl/xCAT/Table.pm line 2591
        xCAT::Table::getNodeAttribs_nosub_returnany('xCAT::Table=HASH(0x10002886448)', 'c910f02fsp01', 'ARRAY(0x10001aebd50)') called at /opt/xcat/lib/perl/xCAT/Table.pm line 2290
        xCAT::Table::getNodeAttribs('xCAT::Table=HASH(0x10002886448)', 'c910f02fsp01', 'ARRAY(0x10001ad20d0)') called at /opt/xcat/lib/perl/xCAT/Table.pm line 2114
        xCAT::Table::getNodesAttribs('xCAT::Table=HASH(0x10002886448)', 'ARRAY(0x10002931878)', 'ARRAY(0x10002bd8a88)') called at /opt/xcat/lib/perl/xCAT/Table.pm line 346
        xCAT::Table::handle_dbc_request('HASH(0x10002c58118)') called at /opt/xcat/lib/perl/xCAT/Table.pm line 271
        xCAT::Table::handle_dbc_conn('IO::Socket::UNIX=GLOB(0x10002c6d170)', 'IO::Select=ARRAY(0x1000291b680)') called at /opt/xcat/lib/perl/xCAT/Table.pm line 219
        eval {...} called at /opt/xcat/lib/perl/xCAT/Table.pm line 218
        eval {...} called at /opt/xcat/lib/perl/xCAT/Table.pm line 209
        xCAT::Table::init_dbworker() called at /opt/xcat/sbin/xcatd line 888

**Comment by chenglch** [comment]
https://github.com/xcat2/xcat-core/blob/master/perl-xCAT/xCAT/Table.pm#L930
    if ($self->{tabname} eq 'nodelist')
    {
        weaken($self->{nodelist} = $self);
    }
    else
    {
        $self->{nodelist} = xCAT::Table->new('nodelist',-create=>1);
    }

 `$self->{nodelist}` for nodelist table ( `$self->{tabname} eq 'nodelist'` ) is recycled by the GC of perl, The `$self` object exists but the nodelist pointer is missing.

**Comment by whowutwut** [comment]
As per pull request #1026, that is a work around, please do not close this issue so we can track whether we need an additional pull request for fix this issue.  Setting to normal priority since we have a work around.
