### ISSUE TITLE
 [FVT]: switch based hardware discovery hangs on discovery process 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#102]
xCAT 2.10 20150609 build.

[root@c910f02c08v01 ~]# rpm -qa |grep -i xcat
 grub2-xcat-2.02-0.16.el7.snap201505140423.noarch
 perl-xCAT-2.10-snap201506090433.noarch
 xCAT-buildkit-2.10-snap201506090433.noarch
 conserver-xcat-8.1.16-10.ppc64
 xCAT-genesis-base-ppc64-2.10-snap201505172314.noarch
 xCAT-client-2.10-snap201506090433.noarch
 xCAT-genesis-scripts-ppc64-2.10-snap201506090433.noarch
 xCAT-2.10-snap201506090433.ppc64
 ipmitool-xcat-1.8.11-3.ppc64
 xCAT-server-2.10-snap201506090433.noarch

[root@c910f02c08v01 ~]# cat node001.def

<xCAT data="" object="" stanza="" file="">

node001:
 objtype=node
 arch=ppc64
 bmc=50.3.5.1
 bmcpassword=passw0rd
 cons=ipmi
 groups=pkvm,all
 installnic=mac
 ip=70.2.8.101
 mgt=ipmi
 mtm=8286-42A
 nodetype=mp
 os=rhels7.1
 primarynic=mac
 profile=compute
 serial=101102V
 status=booting
 statustime=06-08-2015 07:37:02
 supportedarchs=ppc64
 switch=switch1
 switchport=1
[root@c910f02c08v01 ~]# tabdump networks

netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable

"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","enP3p0s1f0","10.0.0.103",,"10.2.8.1",,,,,,,,,,,,
 "70_2_8_0-255_255_255_0","70.2.8.0","255.255.255.0","enP3p0s1f1","<xcatmaster>",,"70.2.8.100",,,,"70.2.8.1-70.2.8.100",,,,,,,,
[root@c910f02c08v01 ~]# tabdump switches

switch,snmpversion,username,password,privacy,auth,linkports,sshusername,sshpassword,protocol,switchtype,comments,disable

"switch1","3","admin","passw0rd",,"sha",,,,,,,

From console, we can see that hardware discovery hangs on Welcome to Petitboot.

Petitboot (dev.20141013) 8286-42A 101102V
 qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
[Network: eth3 / 6c:ae:8b:6a:d4:e5]
 xCAT

System information
 System configuration
 Language
 Rescan devices
 Retrieve config from URL
 *Exit to shell

qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
 Enter=accept, e=edit, n=new, x=exit, l=language, h=help
 Welcome to Petitboot

 zhao er tao   
 2015-07-01

Need to check with LTC team members for the OPAL machine hung at petitboot screen.
   
 zhao er tao   
 2015-07-02   
 

Have send out mail to LTC team but no response yet, and it is firmware issue, so move it to 2.11 to trace the petitboot hung issue.

**Comment by daniceexi** [comment]
Since we cannot recreate this issue and base our understanding that update firmware will fix this issue.
