### ISSUE TITLE
lsvm command should display information about individual kvm vm.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#1023]
Pull request #1022 enabled existing code displaying kvm VM information for a specified kvm hypervisor.
This issue is to enhance enhance lsvm to display information for an individual kvm VM. Perhaps similar to data gathered by rscan command.

**Comment by immarvin** [comment]
hi @gurevichmark , is this issue been fixed by your PR?

**Comment by gurevichmark** [comment]
No, the PR #1022 referenced above, only displays the list of VMs on a specified hypervisor. The idea for this issue is to display information about a specified individual vm, similar to what `rscan` command displays.

I have not looked at this issue yet. Some time ago @daniceexi felt that VM related issue should not be treated as high priority.

**Comment by gurevichmark** [comment]
Information for individual VM can be extracted from the output of `virsh dominfo <vm_name>` on hypervisor.

**Comment by gurevichmark** [comment]
Fixed by PR #2776
