### ISSUE TITLE
[FVT]2.12 switchdiscover could not get switch mac using snmp for Mellanox switch

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1036]
env:rhels
build:latest build
lsdef - Version 2.12 (git commit 6e2f230ae49477612dc94d533afca67962d8e33f, built Tue May  3 09:30:57 EDT 2016

How to reproduce:
```
[root@c910f04x30 ~]# switchdiscover  --range  10.0.0.131 -s snmp
Discovering switches using snmpwalk.....
ip          	name           	vendor                                  	mac         
------------	------------   	------------                            	------------
10.0.0.131  	c910ibsw01     	Mellanox SX6036,MLNX-OS,SWvSX_3.3.5006  	nomac_nmap_0
[root@c910f04x30 ~]# switchdiscover  --range 10.0.0.131
Discovering switches using nmap for 10.0.0.131. It may take long time...
ip          	name           	vendor                                  	mac         
------------	------------   	------------                            	------------
10.0.0.131  	switch-10-0-0-131	Mellanox Technologies                   	00:02:C9:63:39:16
--------------------------------> in fact I could find mac using nmap
```

**Comment by whowutwut** [comment]
Is nmap more consistent in getting the correct information back or snmp?

**Comment by cxhong** [comment]
Well, I couldn't find which scan method is more consistent. Sometimes nmap couldn't find host name but snmp could.  Same as MAC address in this case, snmp couldn't, but nmap could.  I think it's relate to switch how it configured.  Users have to decided which method is working better for them. 
Or we can redesign the switchdiscover command, combine nmap and snmp scan method, returned whatever we can from those two commands.

**Comment by daniceexi** [comment]
Generally mac address is not necessary for the management of a discovered switch, so it's fine to keep current code for 2.12.

But mac address is useful is we want to use switch-based discovery to discover a switch location. For how to get the mac address, I am thinking whether it easier that just getting it from arp or ping?

**Comment by cxhong** [comment]
we can get mac address from snmp scan.  User may need to try both scan to find better method.
