### ISSUE TITLE
[Customer]Makes xCAT support NetworkManager in CentOS7

### ISSUE THREAD

**Issue by onimsha** [xcat2/xcat-core#104]
From RHEL/CENTOS 7, NetworkManager was default, hence it makes some problems with xCAT:
1. setroute won't work if we add a routenames with net=0.0.0.0 (for setup default gw via setroute)
2. /etc/sysconfig/static-routes wont apply on boot

Workaround is disable NetworkManager, but is there any possibilities xCAT configure routes via Network Manager?

**Comment by daniceexi** [comment]
1. We considered that using networkManager to manage all the network configuration. But from some customers that networkManager is not stable too. So we are looking that if there issues that cannot be handled without NetworkManager, we will migrate to NetworkManager.

2. The NetworkManager is disabled by xCAT after node deployment. Could you check the status of it, and how about reboot your node?

**Comment by whowutwut** [comment]
Are you only trying to configure the default gateway for the machines OR trying to set up routing to different networks provided by multiple network interfaces? 
 i.e  eth0 -> 10.X network, eth1 -> 20.X network.. etc...

**Comment by onimsha** [comment]
@daniceexi : Actually i wrote a postscript for disabling NetworkManager
@whowutwut : Both, i manage default gateway and static routes via "setroute" and noderes.routenames

**Comment by daniceexi** [comment]
@immarvin 
Could you check why the NetworManager did not stop for CentOS7?

**Comment by whowutwut** [comment]
We are looking at NetworkManager in the next release.

**Comment by daniceexi** [comment]
We are working in the NetworkManager support for rh7. It will be ready in next release.

**Comment by immarvin** [comment]
NetworkManager should have been stopped in the following commit:

````
commit 52061dd6623a8bf81dd9145653759428c1b89fd5
Author: ertaozh <ertaozh@cn.ibm.com>
Date:   Mon Apr 25 03:08:59 2016 -0400

    Fix issue 942:[PCM] CN IP loss after 12 hours due to the dhcp.lease timeout value 43200

diff --git a/xCAT-server/share/xcat/install/scripts/post.rhels7 b/xCAT-server/share/xcat/install/scripts/post.rhels7
index b34d7d0..3b36dfe 100644
--- a/xCAT-server/share/xcat/install/scripts/post.rhels7
+++ b/xCAT-server/share/xcat/install/scripts/post.rhels7
@@ -20,3 +20,11 @@ do
   #nic name change during the install and first_reboot
   sed -i '/HWADDR/d' $i
 done
+
+# NetworkManager will conflict with the configuring xcat do later in postboot script, so disable it in postscript 
+
+# There are 2 other service related to NetworkManager: NetworkManager-dispatcher and NetworkManager-wait-online
+# Both of them are triggered by NetworkManager, so just disable NetworkManager here
+if [ -f "/usr/lib/systemd/system/NetworkManager.service" ]; then
+    systemctl disable NetworkManager
+fi
diff --git a/xCAT/postscripts/xcatinstallpost b/xCAT/postscripts/xcatinstallpost
index 0eee2be..83d9a8e 100755
--- a/xCAT/postscripts/xcatinstallpost
````

hi @onimsha , would you please try the latest xcat build?

**Comment by whowutwut** [comment]
@immarvin  i think @onimsha  is asking for xCAT team to support using NetworkManager to configure the network settings, instead of disabling it.

**Comment by immarvin** [comment]
Disabling NetworkManager introduced some problem in rh7 diskless(see https://github.com/xcat2/xcat-core/issues/1972), we should give this issue a higher priority

ping @whowutwut

**Comment by samveen** [comment]
@immarvin What are the issues caused by NetworkManager with xCAT that it needs to be disabled? I ask this as I have a some supermicro servers with `ixgbe` driven cards, that fail to work with the legacy `network` service, but work fine with `NetworkManager`.

**Comment by immarvin** [comment]
hi @samveen , seems this issue https://github.com/xcat2/xcat-core/issues/942
