### ISSUE TITLE
Resolve the Issue with xCAT-genesis-base and xCAT-genesis-scripts for 2.12

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1046]
A few issues have arisen with regards to changes in xCAT-genesis-base and xCAT-genesis-scripts.  I'm creating an issue to track the effort and hopefully outline the pain points to convince why we need to re-design this process.   

The original design for this is to provide the files that come with the O/S used as the base for the genesis kernel in the xCAT-genesis-base RPM and then for changes that xCAT team makes, we would ship it in the xCAT-genesis-scripts package.  

The question came up, for why we are shipping xCAT-genesis-base in xcat-dep instead of in xcat-core and automatically building this in xcat-core.  The only reason may be that the genesis base is 20-40MB and maybe at the time it was created, we did not want to build this daily into xcat-core? 

The problem here is that when we move files into the xCAT-genesis-scripts, we need to remove it first from the xCAT-genesis-base, otherwise RPM will have conflicts because two packages are shipping the same exactly file... 

For example:
```
Transaction check error:
  file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/etc/udev/rules.d/98-mlx.rules conflicts between attempted installs of xCAT-genesis-scripts-x86_64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-x86_64-1:2.9-snap201504212134.noarch
  file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/sbin/loadmlxeth conflicts between attempted installs of xCAT-genesis-scripts-x86_64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-x86_64-1:2.9-snap201504212134.noarch
``` 

The problem here is complicated further because xCAT-genesis-base is shipped with the `xcat-dep` package and the `xcat-dep` is process is NOT automated....    The following manual steps must occur in the following order **if we do not want to touch** the automated build process we have set in place.... Daily builds are done in-house and Weekly builds are uploaded to xcat.org. 

1. Make changes via Pull request only to xCAT-genesis-base to remove the file intended to be shipped with xCAT-genesis-scripts 
2. Someone review and merge in the changes to genesis-base
3. Then on some pre-defined system, clone the xCAT project and build the xCAT-genesis-base rpms for the architectures needed (x86_64, ppc64le, etc)
4. Place these packages into our staging area in GSA for xcat-deps 
5. Make changes via Pull request to add in the xCAT-genesis-scripts files 
6. Someone review and merge the pull request 
7. Allow the weekly Thurs morning build to occur which will upload to xcat.org
8. Using the same weekly build directory, execute the builddeps script that will repkg the xcat-dep changes and upload to xcat.org

Repeat for Ubuntu..... 

Lots of pain here....

**Comment by whowutwut** [comment]
For the 2.12 release, I merged @daniceexi  pull request and then packaged the xCAT-genesis-base-2.12 into the xcat-dep package

Linux: http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201605051601.tar.bz2
Ubuntu: http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-201605051614.tar.bz2

I think in order to allow for the ability to remove a file from the xCAT-genesis-base, we need to have the xCAT-genesis-base spec file list out all the files in the %files section.  Right now it's hard for the developers to know what files are shipped with the base.

**Comment by whowutwut** [comment]
@tingtli @caomengmeng @junxiawang @neo954  
I set this Issue to pending, we can discuss whether we need to redesign this in the next release, but the current build should have the changes to xcat-dep that @gurevichmark made.  We plan to run it tomorrow to try out the genesis kernel to make sure that it works.  Please use the new build for RC testing.

**Comment by whowutwut** [comment]
I need to correct the comment I made above.  I did not really know how the genesis builder worked until I tried it myself and looked at the results and reviewing the changes @daniceexi  made in #1040 

So we DO have a way to control the files going into the genesis base by modifying the install files in the xCAT-genesis-builder directory: 
* https://github.com/xcat2/xcat-core/blob/master/xCAT-genesis-builder/install
* https://github.com/xcat2/xcat-core/blob/master/xCAT-genesis-builder/install.ubuntu

So this is a little better than I had initially thought.

**Comment by junxiawang** [comment]
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xcat : Depends: xcat-genesis-scripts but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
----------------------> still errors for install ubuntu on x86_64

**Comment by whowutwut** [comment]
@junxiawang  is this still broken after the recent changes?

**Comment by whowutwut** [comment]
@junxiawang please put a comment in the issue when you close it. is the issue not seen anymore in the last build? Was anything verified?  The authors should close the issue so I was asking to make sure there was no more issue before closing
