### ISSUE TITLE
[DEV] Upgrading from xCAT 2.10 to 2.12 overwrites xcatsslversion TLS values

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#1047]
Opened on behalf of customer Ralph Bellofatto

Possibly related to issue #569 and pull request #576 ?

When updating from xCAT 2.10 to 2.12 development build the following ssl error is observed

```
[root@dccxcat yum.repos.d]# lsdef tulgb004
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: SSL connect attempt failed with unknown error error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure at /opt/xcat/lib/perl/xCAT/Client.pm line 265.
```

Work around was

```
XCATBYPASS=Y /opt/xcat/sbin/tabedit site
```

then change  `xcatsslversion` from `TLSv1` to `TLSv12`

**Comment by whowutwut** [comment]
@tingtli @daniceexi  maybe we should take some time doing migration testing before the last RC build..  I'm surprised that this happened again going from 2.10 -> 2.12..

**Comment by daniceexi** [comment]
@pdlun92 Could you confirm with Ralph that the issue was:

1. Before the migration (in xcat 2.10), the **xcatsslversion** was ``TLSv12``,
2. After migration from 2.10 to 2.12, the **xcatsslversion** was changed to ``TLSv1``

**Comment by tingtli** [comment]
@whowutwut @pdlun92 @daniceexi 
I just upgrade from 2.10 to 2.12 and found the TLSV1 is not modified.

**Comment by tingtli** [comment]
Before the migration, the xcatsslversion is TLSv1, after the migration the value is TLSv1
Not sure if customer's environment is the same.

**Comment by whowutwut** [comment]
@tingtli We need to first install xCAT 2.10 or an older version of xCAT, then update to xCAT 2.12, and the site values shold not change. The one you described above, you did not modify the value to TLSv12... and so we can't tell that xCAT overwrote customer configuration.  We should add this kind of verification checking to Autotest...    We should have a testcase that sets every variable in the site table to some user defined setting, update xCAT, then loop through our array and tabdump site and see that it still is OK .

**Comment by pdlun92** [comment]
@daniceexi customer is unable to confirm that xcatsslversion was set to TLSv12 prior to update, but given the content of the error message and the work around I think it's safe to assume that it was.

@tingtli I believe proper steps to test this particular issue would be
1) install xCAT 2.10
2) set xcatsslversion = TLSv**12**
3) upgrade to xCAT 2.12
4) confirm whether xcatsslversion is still set to TLSv**12** or overwritten to TLSv**1**

**Comment by tingtli** [comment]
@whowutwut, I just misunderstand this issue. 
Meng meng wrote a case for this upgrade. I didn't search that right now. I will ask meng meng on Monday morning.

**Comment by caomengmeng** [comment]
@tingtli @whowutwut 
1. Install xCAT 2.10 on ppc64 RH7.2
2. Set the "xcatsslversion" from "TLSv1" to "TLSv12".
```
[root@c910f02c04p09 ppc64]# date
Mon May  9 01:49:39 EDT 2016
[root@c910f02c04p09 ppc64]# lsxcatd -a
Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)
This is a Management Node
dbengine=SQLite
[root@c910f02c04p09 ppc64]# tabdump site | grep "xcatsslversion"
"xcatsslversion","TLSv1",,
[root@c910f02c04p09 ppc64]# chtab key=xcatsslversion site.value=TLSv12
[root@c910f02c04p09 ppc64]# tabdump site | grep "xcatsslversion"
"xcatsslversion","TLSv12",,

```
3. Update to xCAT2.12, then check xcatsslversion, it is still the "TLSv12"
```
[root@c910f02c04p09 ~]# lsxcatd -a
Version 2.12 (git commit cccd99d10331da69c74c6d7a69bd734595602abf, built S                                                                     at May  7 01:15:31 EDT 2016)
This is a Management Node
dbengine=SQLite
[root@c910f02c04p09 ~]# tabdump site | grep versi
"xcatsslversion","TLSv12",,
[root@c910f02c04p09 ~]# service xcatd restart
Restarting xcatd (via systemctl):  Warning: Unit file of xcatd.service changed on disk, 'systemctl daemon-reload' recommended.
                                                           [  OK  ]
[root@c910f02c04p09 ~]# service xcatd status
xcatd service is running
[root@c910f02c04p09 ~]# tabdump site | grep versi
"xcatsslversion","TLSv12",,

```

**Comment by pdlun92** [comment]
Reject this issue, unable to recreate

**Comment by cxhong** [comment]
I reopen this issue because it hits on research cluster again when they run "yum update xCAT", the workaround is change "TLSv1" to "TLSv12".  He didn't recall what was value for "xcatsslverison" before ran "yum update".  

but I found the system had two sets of xCAT repo,  2.10 was point to souceforge
`````
[root@dccxcat2 ~]# ls /etc/yum.repos.d/xcat2.10/xCAT-*
/etc/yum.repos.d/xcat2.10/xCAT-core.repo  /etc/yum.repos.d/xcat2.10/xCAT-dep.repo
[root@dccxcat2 ~]# cat /etc/yum.repos.d/xcat2.10/xCAT-*
[xcat-2-core]
name=xCAT 2 Core packages
baseurl=https://sourceforge.net/projects/xcat/files/yum/2.10/xcat-core
enabled=1
gpgcheck=1
gpgkey=https://sourceforge.net/projects/xcat/files/yum/2.10/xcat-core/repodata/repomd.xml.key
[xcat-dep]
name=xCAT 2 depedencies
baseurl=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh7/ppc64le
enabled=1
gpgcheck=1
gpgkey=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh7/ppc64le/repodata/repomd.xml.key
 ```````````
yum repolist and yum repoinfo are point to xCAT repo file at /etc/yum.repos.d
``````
root@dccxcat2 ~]# cat /etc/yum.repos.d/xCAT-*
[xcat-2-core]
name=xCAT 2 Core packages
#baseurl=http://xcat.org/files/xcat/repos/yum/2.11/xcat-core
baseurl=http://xcat.org/files/xcat/repos/yum/2.11/core-snap
enabled=1
gpgcheck=1
#gpgkey=http://xcat.org/files/xcat/repos/yum/2.11/xcat-core/repodata/repomd.xml.key
gpgkey=http://xcat.org/files/xcat/repos/yum/2.11/core-snap/repodata/repomd.xml.key
[xcat-dep]
name=xCAT 2 depedencies
baseurl=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
enabled=1
gpgcheck=1
gpgkey=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le/repodata/repomd.xml.key
````````

Do u think we should try to recreate it again? 
1) install 2.10 from souceforge
2) then update to 2.11 based on those repo files

**Comment by daniceexi** [comment]
@tingtli Please confirm whether the test case for this scenario is running every day and no problem.

**Comment by tingtli** [comment]
This is tested in autotest environment.  The case name is xcatconfig_u_check_xcatsslversion_rhels_sles
Close it
