### ISSUE TITLE
Resolve or clean up minor issues on getinstdisk from code review

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1048]
Opening this issue to discuss and track some comments I had in Issue #1037 to help make `getinstdisk` more intuitive and easier to debug. 

- is `set -x` automatically the default setting when we are doing xcatdebugmode=2? 
- the rm command has errors (We should not have un-intentional errors in the script, to avoid debugging something that is not a problem) 
- The name of `/tmp/xcat.install_disk` is my suggestion because it is not easy to quickly identify xCAT related files when inside anaconda debugging

**Comment by daniceexi** [comment]
I am thinking that we need consider to push the messages from get-install-disk to the xCAT MN, then we can easily debug the disk selection issue when real issue happens.

**Comment by whowutwut** [comment]
I agree, @gurevichmark may have some time next to look into the possibility of having rsyslog redirect automatically, but then we would need to have a good way to filter out the syslog messages into different log files under `/var/log/xcat`  coming from different stages in the xCAT provisioning process...  

for example...OS provisioning, hardware discovery...  if they are all going into the same file...  `/var/log/xcat/compute.log` it will be very difficult to filter through..   some ideas is ....

`/var/log/xcat/<computenode>.provisionig.log`
`/var/log/xcat/<computenode>.discovery.log`

**Comment by xuweibj** [comment]
@penguhyang Could you help answer the question about "set -x"?
@whowutwut I will check the rm command in the script.
@zet809 What's your comment about the name "/tmp/xcat.install_disk" instead of "/tmp/install_disk"?

**Comment by penguhyang** [comment]
@whowutwut @xuweibj Yes, set -x  is automatically the default setting when we are doing xcatdebugmode=2 and xcatdebugmode=1.

**Comment by xuweibj** [comment]
@whowutwut I tried to modified code to avoid errors from rm command, do you think it's better?#1058 
I add -f when rum file. All the files are created by the script, rm -f will be safe. And if all files are deleted, rmdir will be safe too.

**Comment by whowutwut** [comment]
Yes, i think using rm of the files first, then rmdir is the right way rather than `rm -rf <dir>` , I put my comments into #1058

**Comment by xuweibj** [comment]
@whowutwut "/tmp/install_disk" is used in many other scripts to get the disk's name. If change it, they need to be changed too. We don't hope change it.

**Comment by whowutwut** [comment]
@xuweibj What's wrong with changing the code?  It's not that many places, i worked on this a few days ago.   Please see pull request #1111.  

I am okay with the changes in this pull request..  My idea is that if you are in touching the code and there's something that we can change to make it better, i will review it and make the comment.  If it's too risky, we can make the change and plan for it to be put into the next release to have more time to test.  

For this pull request, I will merge after we GA 2.12.  Will merge into master and cherry pick into 2.12.

**Comment by xuweibj** [comment]
@whowutwut I agree with the pull request #1100. Could we merge #1100 and #1058, and then close this issue?

**Comment by whowutwut** [comment]
@xuweibj, I am out of office for a few days. Please go ahead and merge if you feel it is ok.

**Comment by whowutwut** [comment]
By the way, did you mean #1111 or #1100? I'm not able to check this week so please make sure you double check

**Comment by daniceexi** [comment]
I will try to help to review tomorrow.

**Comment by xuweibj** [comment]
hi @whowutwut , could this issue be closed?

**Comment by xuweibj** [comment]
Hi @whowutwut , the pull requests have been merged, I will close this issue. If there is anything want to modify, we could open a new issue.
