### ISSUE TITLE
[FVT]sles11.4 diskfull install failed on p8 ppc64  

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1060]
env:sles11.4 , p8 ppc64
build:
linux-z38a:~ # lsxcatd -v
Version 2.12 (git commit 9d4c8b9c09bf0afabad32110ab27ade6d4ca9c28, built Thu May  5 07:58:26 EDT 2016)
How to reproduce:
```
During diskfull provision:
[](url)
Loading Install kernel ...
Loading initial ramdisk ...

SuSE Linux zImage starting: loaded at 086d0000-0a7e7d30 (0/0/00c3da70; sp: 06a3fe10)
uncompressing ELF header done. (00000100 bytes)
Can't allocate memory for kernel image !

EXIT called ok

```

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1061

**Comment by immarvin** [comment]
duplicate with https://sourceforge.net/p/xcat/bugs/4420/
