### ISSUE TITLE
[DEV] xdsh exit code maxes out at 255

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#1067]
Opened on behalf of customer Alda Ohmacht

temp.sh script written as
```
#!/bin/bash
rc=255
echo "exit code is $rc"
exit $rc
```

xdsh will return:
```
[root@c910f02c05p03 ~]# xdsh fs1 -z -s -e temp.sh
fs1: exit code is 255
fs1: Remote_command_rc = 255
```

If rc in temp.sh is changed to 256, xdsh will return:
```
[root@c910f02c05p03 ~]# xdsh fs1 -z -s -e temp.sh
fs1: exit code is 256
fs1: Remote_command_rc = 0
```
any higher values of rc will return with Remote_command_rc = rc - 256.

According to man pages of xdsh, it seems like the exit code (indicated by Remote_command_rc in above example) should equal 0 if all commands were executed without errors.  Otherwise, the exit code will indicate the number of successive shell commands that do not exit successfully.  

Is this apparent cap of 255 intended by design, or a bug?

**Comment by daniceexi** [comment]
The valid range for exit code is 0-255. Refer to: http://tldp.org/LDP/abs/html/exit-status.html

Even run the the temp.sh locally (rc=256), the return code also is 0.

So this is not a bug of xdsh, it obeys the Linux standard.
