### ISSUE TITLE
[CUSTOMER] Update the Software RAID documentation in 2.12 and forward

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1081]
The latest documentation on RAID needs to be updated and caused confusion when Customer tried to set up software RAID. 

http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/raid_cfg.html

The samples provided are for rhels6 and for service nodes. This is misleading because we don't provide a specific raid configuration file after rhels6, we just provide a default template that has the RAID settings commented out.   Also, why are we describing a service node template and we don't mention anything about service nodes in this documentation 

So the instructions causes confusion to the customers reading this section

**Comment by whowutwut** [comment]
I took a look at this, it might be difficult to get this changed before 2.12 because it might be a larger change than I expected... but I will take this issue.

**Comment by daniceexi** [comment]
Then we should move this issue to 2.12.1.

**Comment by whowutwut** [comment]
@immarvin I think with your work in PR https://github.com/xcat2/xcat-core/pull/2211  we can close out this issue. The raid instructions are more clear now and should work with RH7 and higher.
