### ISSUE TITLE
"makedns" report failure in multiple domain case

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#1086]
Background:
The xCAT managed cluster has two network and is using two different domain for DNS resolution,  Customer want both the node.domain1 and node.domain2 could be resolved (whatever in DNS or /etc/hosts), here node is the short name.  

As xCAT can only generate node.domain1 and node-suffix.domain2 in /etc/hosts,  they modify the /etc/hosts to add node.domain2 manually, but it caused failure in  "makedns -n" and "makedns -a"

For example:
cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.100.1 bjpe820.private.dns.zone bjpe820 bjpe820-br0
172.20.7.136 bjpe820.hpc.example.com bjpe820-em1
192.168.100.100 vm1.private.dns.zone vm1

makedns -n
Handling localhost in /etc/hosts.
Handling localhost in /etc/hosts.
Handling bjpe820.hpc.example.com in /etc/hosts.
Handling bjpe820.private.dns.zone in /etc/hosts.
Handling vm1.private.dns.zone in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Error: Failure encountered updating hpc.example.com., error was NOTZONE. See more details in system log.
Completed updating DNS records. 

tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"provision","192.168.100.0","255.255.255.0","br0","<xcatmaster>",,"192.168.100.1",,,,"192.168.100.201-192.168.100.254","192.168.100.3-192.168.100.200","1",,,,"private.dns.zone",,
"public","172.20.7.0","255.255.255.0","em1","172.20.7.2",,"172.20.7.136",,,,,"172.20.7.136-172.20.7.254","1",,,,"hpc.example.com",,

tabdump site|grep domain
"domain","private.dns.zone",,

Are there some methods to make it work (or just ignore it in DNS DB, but for others, xcat can still put them in DNS DB)

**Comment by daniceexi** [comment]
@bybai CAT supports multiple domains. Could you try to recreate this issue locally?

**Comment by bybai** [comment]
@robin2008 , I cannot reproduce this issue in my env:
my steps:
1,
root@byrh04 named]# cat /etc/resolv.conf
# Generated by NetworkManager
search cluster.com test.com
nameserver 20.4.41.4
2.
[root@byrh04 named]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"semiprivate","10.32.64.0","255.255.192.0","ens1f0","10.32.127.254","10.32.64.2","10.32.64.2",,,,,,,,,,"test.com",,
"20_0_0_0-255_0_0_0","20.0.0.0","255.0.0.0","eth1","<xcatmaster>",,"20.4.41.4",,,,,,,,,,"cluster.com",,
3,
[root@byrh04 named]# cat /etc/hosts

20.4.41.4 byrh04.cluster.com byrh04
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
20.4.41.1 c910f04x41 c910f04x41.cluster.com
20.4.41.16 byomc2 byomc2.cluster.com
10.32.77.2 test1 test1.test.com
4,
[root@byrh04 named]# tabdump site|grep domain
"domain","cluster.com",,
5,
[root@byrh04 named]# makedns -n
Handling c910f04x41 in /etc/hosts.
Handling test1 in /etc/hosts.
Handling localhost in /etc/hosts.
Handling byomc2 in /etc/hosts.
Handling byrh04.cluster.com in /etc/hosts.
Handling localhost in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
6,
[root@byrh04 named]# nslookup byomc2
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   byomc2.cluster.com
Address: 20.4.41.16

[root@byrh04 named]# nslookup test1
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   test1.test.com
Address: 10.32.77.2

**Comment by robin2008** [comment]
Yuan,    
It need both byomc2.cluster.com and byomc2.test.com,  and using FQDNfirst in site table.
Could you try it again?

**Comment by robin2008** [comment]
Found that the "makedns" will fail in below case:
1.1.1.1   a.x.y.z a a-eth0
2.2.2.2   a.m.n.p a-eth1.m.n.p a-eth1

But it could work:
1.1.1.1   a.x.y.z a a-eth0
2.2.2.2   a.m.n.p

Note:  xCAT mkhosts can only generate such /etc/hosts
1.1.1.1   a.x.y.z a a-eth0
2.2.2.2   a-eth1.m.n.p a-eth1
"2.2.2.2    a.m.n.p" is appended by user manually.

As after the modification, the /etc/hosts is still valid,  "makedns" should work without error.
Of course, it is fine that xcat could support to generate "2.2.2.2    a.m.n.p" for non-provision nic.

**Comment by daniceexi** [comment]
@robin2008 Why does the customer want to set two hostname **a.m.n.p, a-eth1.m.n.p** for one IP 2.2.2.2?

**Comment by robin2008** [comment]
@daniceexi @bybai 
There is no mandatory for a-eth1.m.n.p,  a-eth1.m.n.p is auto-generated by xcat after the nic is defined in nics table. 
But customer don't want use a-eth1.m.n.p, or the hostname must be set to a-eth1 as some application running on the node has the limitation.
They don't like such hostname in cluster, they just want both **a.m.n.p** and **a.x.y.z** are valid in DNS. 

BTW: there is odd behavior in  "makedns",  after simple testing:
the below hosts file will cause makedns failure.
1.1.1.1 a.x.y.z  a  a-eth0 
2.2.2.2 a.m.n.p a-eth1

but after minor modification in the /etc/hosts, it works. for example:
1.1.1.1  a  a-eth0 a.x.y.z 
2.2.2.2 a-eth1 a.m.n.p 

or 
1.1.1.1 a.x.y.z  a  a-eth0  
2.2.2.2 a-eth.m.n.p a-eth1
2.2.2.2 a.m.n.p

or 
1.1.1.1 a.x.y.z  a  a-eth0  
2.2.2.2 a-eth.m.n.p a-eth1
2.2.2.2 a.m.n.p a-eth1

**Comment by AsirXing** [comment]
It should be a new requirement for xCAT, we want to xCAT can resolve the private and public FQDN for a node. For example, in my environment, there are 2 networks with domains as below:
...............
[root@db04b11 ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"**public**","9.21.54.0","255.255.255.0","eno1","9.21.54.2",,"9.21.54.31",,,,,"9.21.54.31-9.21.54.254","1",,,,"**eng.platformlab.ibm.com**",,
"**provision**","192.168.108.0","255.255.255.0","eno2",,,"192.168.108.80",,,,"192.168.108.201-192.168.108.254","192.168.108.3-192.168.108.200","1",,,,"**private.zone**",,
[root@db04b11 ~]#
...............

For node db04b11, we hope xCAT can support:
1. Add the public FQDN in the /etc/hosts file:
............... 
[root@db04b11 named]# cat /etc/hosts | grep db04b11
192.168.108.80 db04b11 db04b11.private.zone db04b11-eno2
9.21.54.31 db04b11-eno1 db04b11-eno1.eng.platformlab.ibm.com **db04b11.eng.platformlab.ibm.com**
[root@db04b11 named]# 
............... 

2. xCAT can resolve the (private and public) FQDN for db04b11:
............... 
[root@db04b11 named]# cat /etc/resolv.conf
**search private.zone eng.platformlab.ibm.com** <<< We can ensure private domain is the first search entry
nameserver 192.168.108.80
[root@db04b11 named]# nslookup db04b11  <<< Resolve the short name
Server:         192.168.108.80
Address:        192.168.108.80#53

Name:   db04b11.private.zone
**Address: 192.168.108.80**

[root@db04b11 named]# nslookup db04b11.eng.platformlab.ibm.com   <<< Resolve the public FQDN
Server:         192.168.108.80
Address:        192.168.108.80#53

Name:   db04b11.eng.platformlab.ibm.com
**Address: 9.21.54.31**

[root@db04b11 named]# nslookup db04b11.private.zone   <<< Resolve the private FQDN
Server:         192.168.108.80
Address:        192.168.108.80#53

Name:   db04b11.private.zone
**Address: 192.168.108.80**

[root@db04b11 named]#
...............

**Comment by daniceexi** [comment]
@AsirXing As you have made a clear requirement for the requirement, could you open an new issue and close this one?

@bybai Could you investigate how many effort we need to fix it?

**Comment by bybai** [comment]
I looked into you requirement,in your case, db04b11 is short name of db04b11.private.zone, but you want xcat resolve db04b11.eng.platformlab.ibm.com.

The 2 domains are for 2 different networks. As a result, the domain for db04b11 is confused, db04b11 is hard to choose which one is its domain name.

Current results are following:

[root@db04b11 ~]# cat /etc/hosts | grep db04b11
192.168.108.80 db04b11 db04b11.private.zone db04b11-eno2
9.21.54.31 db04b11-eno1 db04b11-eno1.eng.platformlab.ibm.com

[root@byrh04 ~]# nslookup db04b11-eno1
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11-eno1.eng.platformlab.ibm.com
Address: 9.21.54.31

[root@byrh04 ~]# nslookup db04b11
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11.private.zone
Address: 192.168.108.80

[root@byrh04 ~]# nslookup db04b11.private.zone
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11.private.zone
Address: 192.168.108.80

[root@byrh04 ~]# nslookup db04b11-eno2
Server:         20.4.41.4
Address:        20.4.41.4#53

db04b11-eno2.private.zone       canonical name = db04b11.private.zone.
Name:   db04b11.private.zone
Address: 192.168.108.80

[root@byrh04 ~]# nslookup db04b11-eno1
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11-eno1.eng.platformlab.ibm.com
Address: 9.21.54.31

[root@byrh04 ~]# nslookup db04b11-eno1.eng.platformlab.ibm.com
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11-eno1.eng.platformlab.ibm.com
Address: 9.21.54.31

I looked into your example. /etc/resolv.conf is important, but user enter domain name manually in /etc/resolv.conf.  db04b11 is still confused about domain name.

1, If private.zone is before eng.platformlab.ibm.com in /etc/resolv.conf, I can get your results.
[root@byrh04 ~]# nslookup db04b11
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11.private.zone
Address: 192.168.108.80

2, If eng.platformlab.ibm.com is before private.zone in /etc/resolv.conf, 
[root@byrh04 ~]# nslookup db04b11
Server:         20.4.41.4
Address:        20.4.41.4#53

Name:   db04b11.eng.platformlab.ibm.com
Address: 9.21.54.31

**Comment by kcgthb** [comment]
I guess the requirement here is to have:
```
192.168.108.80 db04b11.private.zone
9.21.54.31     db04b11.eng.platformlab.ibm.com
```
in `/etc/hosts`, ie. the same hostname (`db04b11`) without any suffix in 2 different domains (`.private.zone` and `.eng.platformlab.ibm.com`).

There wouldn't be any need to shortnames/aliases in `/etc/hosts` as the default domain would be determined by the `domain`/`search` directives in `/etc/resolv.conf`. 

As of xCAT 2.12.2, it doesn't seem possible to generate identical hostnames in different DNS zones. Would it be possible to implement such a feature?
