### ISSUE TITLE
[FVT]:update file linux.conf.template to make it easy to use xcattest

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1089]
@junxiawang 
Since we update a lot of test cases and use some customized variables in configuration file, please update linux.conf.template to make it user friendly.

**Comment by tingtli** [comment]
@junxiawang  especially the docker cases. We need a lot of variables which need to be added in configuration files. Please add and make comments.

**Comment by junxiawang** [comment]
I have modified the template according to :https://github.com/xcat2/xcat-core/pull/1580 ,so I will close the bug.
