### ISSUE TITLE
Need to clarify ESSL Kit setup when there are no GPU's in a P8LE node.

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1091]
We need a change to the xcat doc, we need to add a section for non-CUDA nodes:

In an environment without GPU's you do not want to install the CUDA drivers and
should use the following ESSL kit components. 

```
chdef -t osimage rhels7.2-ppc64le-install-compute \
    pkgdir=/install/rhels7.2/ppc64le,/install/cuda-7.5/ppc64le

addkitcomp -a -i rhels7.2-ppc64le-install-compute \
    essl-computenode-6464rte-5.4.0-0-rhels-7.2-ppc64le

addkitcomp -a -i rhels7.2-ppc64le-install-compute \
    essl-computenode-3264rte-5.4.0-0-rhels-7.2-ppc64le

addkitcomp -a -i rhels7.2-ppc64le-install-compute \
    essl-computenode-5.4.0-0-rhels-7.2-ppc64le

addkitcomp -a -i rhels7.2-ppc64le-install-compute \
    essl-loginnode-5.4.0-0-rhels-7.2-ppc64le

```

**Comment by cxhong** [comment]
move this to 2.12.1

**Comment by whowutwut** [comment]
I think we can put the documentation changes into 2.12, should not be a problem to get this in before we branch.

**Comment by daniceexi** [comment]
I agree, this kind of doc update is not related to 2.12 code Besides the 2.12, it's useful for 2.11 too.

**Comment by whowutwut** [comment]
Closing out this issue.  Was fixed with documentation changes
