### ISSUE TITLE
[FVT]Please unify the released xcat-core build name.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1104]
Just as below, we define the 2.10 and 2.11.1 Linux and Ubuntu xcat-core build name as below:

Linux:
http://xcat.org/files/xcat/xcat-core/2.10.x_Linux/xcat-core/xcat-core-2.10.tar.bz2
http://xcat.org/files/xcat/xcat-core/2.11.x_Linux/xcat-core/xcat-core-2.11.1-linux.tar.bz2

Ubuntu:
http://xcat.org/files/xcat/xcat-core/2.10.x_Ubuntu/xcat-core/xcat-core-2.10.tar.bz2
http://xcat.org/files/xcat/xcat-core/2.11.x_Ubuntu/xcat-core/xcat-core-2.11.1-ubuntu.tar.bz2

For xcat-dep, the name is unified.

**Comment by tingtli** [comment]
@caomengmeng  From 2.11, we name the tar ball with the os then we could easily know what the tar ball is for. We will continue to use this naming method in 2.12

**Comment by caomengmeng** [comment]
@tingtli 
OK, I just want to make sure we will using the unified name later. Because we write migration cases now, and will use the build name.

**Comment by whowutwut** [comment]
@caomengmeng  The xcat-dep package is not unified. 

Ubuntu:
http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-2.11.1.tar.bz2
Linux:
http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-2.11.1.tar.bz2

However,  xcat-core from the 2.11 release onwards does use `linux` and `ubuntu`.  We also have `linux` and `ubuntu` after the version, where in the deps package, it's before. 
 
But I think you do bring up a good point in that the naming is not consistent between xcat-core and xcat-deps..   I think it should be : 

Linux:
xcat-core-2.11.1-linux.tar.bz2
xcat-dep-2.11.1**-linux**.tar.bz2

Ubuntu:
xcat-core-2.11.1-ubuntu.tar.bz2
xcat-dep-~~ubuntu-~~2.11.1**-ubuntu**.tar.bz2

Or the other way around where we put the name in front of the number.....

**Comment by caomengmeng** [comment]
@whowutwut Thanks.　Ting Ting already explained me the history of then build name.
And why I point this issue is: when writing the migration test cases, because we support 2.10/2.11.1 upgrade to 2.12, so we found the 2.10 and 2.11.1 is not similar, but that doesn't matter now, we used URL directly to download the builds.
