### ISSUE TITLE
[FVT]2.12:switchdiscover return wrong information using snmp

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1106]
build:
[root@c910f02c01p13 tmp]# lsdef -v
lsdef - Version 2.12 (git commit 56cfba70babd342f63b17932b115f21040245033, built Thu May 12 09:30:47 EDT 2016)
env:
rhels7.2
How to reproduce:
```
[root@c910f02c01p13 tmp]# switchdiscover --range 10.2.3.0/24,192.168.3.0/24,11.5.6.7 -s snmp
Discovering switches using snmpwalk.....
 No switch found 
[root@c910f02c01p13 tmp]# switchdiscover --range 10.2.3.0/24,192.168.3.0/24,11.5.6.7
Discovering switches using nmap for 10.2.3.0/24 192.168.3.0/24 11.5.6.7. It may take long time...
ip          	name                	vendor                                            	mac         
------------	------------        	------------                                      	------------
10.2.3.1    	c910f02c03v01       	IBM                                               	00:21:5E:34:4E:2C

-----------------------------> could not switch info using -s snmp 
```

**Comment by junxiawang** [comment]
[root@c910f02c01p13 ~]# switchdiscover --range 10.5.24.1  -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1 | grep 'open port 161' 
 No switch found 
[root@c910f02c01p13 ~]#  switchdiscover --range 10.5.24.1
Discovering switches using nmap for 10.5.24.1. It may take long time...
ip          	name                	vendor                                            	mac         
------------	------------        	------------                                      	------------
10.5.24.1   	switch-10-5-24-1    	Juniper Networks                                  	5C:5E:AB:64:CA:7F
[root@c910f02c01p13 ~]# switchdiscover --range 10.5.24.1  -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1 | grep 'open port 161' 
 No switch found 
[root@c910f02c01p13 ~]#

**Comment by junxiawang** [comment]
10.2.3.1        c910f02c03v01           IBM
is viso server not switch

**Comment by daniceexi** [comment]
@cxhong The issue cause by the change in the commit 4488c24a300001dc7f9abbc476474a581982595a.

You added the following line in the %global_OID_model_metrix which caused all the device which vendor is IBM will be consider as a BNT switch. 

~~~~
IBM  => "BNT",
~~~~

Then I don't think it's safe to determine a device is a switch just through the vendor name like ``Cisco`` since ``Cisco`` also makes server. I recommend we should use ``nmap osscan`` to probe all the devices which have passed the %global_OID_model_metrix checking.

**Comment by penguhyang** [comment]
I take a quick investigation for this issue.
For the first scenario.
```
[root@c910f03c17k14 ~]# switchdiscover --range 10.5.24.1
Discovering switches using nmap for 10.5.24.1. It may take long time...
ip              name            vendor                                        mac
------------    ------------    ------------                                  ------------
10.5.24.1       switch-10-5-24-1        Juniper Networks                              5C:5E:AB:64:CA:7F

[root@c910f03c17k14 ~]# switchdiscover --range 10.5.24.1 -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1 | grep 'open port 161'
 No switch found
```
snmp discovery for 10.5.24.1 failed.
```
[root@c910f03c17k14 ~]# switchdiscover  --range 10.5.23.1
Discovering switches using nmap for 10.5.23.1. It may take long time...
ip              name            vendor                                        mac
------------    ------------    ------------                                  ------------
10.5.23.1       switch-10-5-23-1        IBM                                           A8:97:DC:05:2E:00

[root@c910f03c17k14 ~]# switchdiscover  --range 10.5.23.1 -s snmp
Discovering switches using snmpwalk.....
ip              name            vendor                                        mac
------------    ------------    ------------                                  ------------
10.5.23.1       switch-10-5-23-1        IBM Networking Operating System RackSwitch G8052      a8:97:dc:5:2e:0
```
snmp discovery for 10.5.23.1 success.
It seems that snmp service is not started in 10.5.24.1
```
[root@c910f03c17k14 ~]# /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1
...
PORT    STATE  SERVICE
161/udp closed snmp
...
[root@c910f03c17k14 ~]# /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.23.1
...
PORT    STATE SERVICE
161/udp open  snmp
...
```
The messages "Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan  10.5.24.1 | grep 'open port 161' " may not clear for user.
For the second scenario.
```
[root@c910f03c17k14 ~]# switchdiscover --range 10.2.3.1 -s snmp
Discovering switches using snmpwalk.....
 No switch found

[root@c910f03c17k14 ~]# switchdiscover --range 10.2.3.1
Discovering switches using nmap for 10.2.3.1. It may take long time...
ip              name            vendor                                        mac
------------    ------------    ------------                                  ------------
10.2.3.1        c910f02c03v01.pok.stglabs.ibm.com       IBM                                           00:21:5E:34:4E:2C
```
It seems that this device can't response to snmpwalk command.
```
[root@c910f03c17k14 ~]# snmpwalk -Os -v1 -c public 10.2.3.1 1.3.6.1.2.1.1.1
Timeout: No Response from 10.2.3.1
[root@c910f03c17k14 ~]# snmpwalk -Os -v1 -c public 10.5.23.1 1.3.6.1.2.1.1.1
sysDescr.0 = STRING: IBM Networking Operating System RackSwitch G8052
```

**Comment by cxhong** [comment]
Sorry, I missed this issue.

Yes, Snmpwalk will not work if snmp port number 161 is not open.  We can't stdout this message since we scan a range of IP address.

**Comment by cxhong** [comment]
Yes, I think I talked to you about the switch type before.  There is no clear way to determine if the switch is Cisco or BNT if vendor info only return IBM.  

If you think we should use nmap Osscan under snmp scan, then we really should combine those two scan method as one, then we don't have issues like snmp found certain info but nmap can't, and vice versa.

**Comment by cxhong** [comment]
@daniceexi , for better performance, can we only nmap osscan again if vendor info is not Juniper or Mellanox ?

**Comment by cxhong** [comment]
@daniceexi , I found nmap osscan command is very slow,  the vendor information return back even harder for us to match which switch type we are supported;
some of vendor info:
````
Nortel
HP
Cisco
Netopia
Allied Telesyn
IBM
Tyco
````
I think i have to remodify the code to use osmatch name as vendor info instead of vendor, 
````
<osmatch name="Nortel BNT Ethernet switch module" accuracy="98" line="62923">
<osclass type="switch" vendor="Nortel" osfamily="embedded" accuracy="98"/>
</osmatch>
````

**Comment by daniceexi** [comment]
@cxhong Yes, looks like the ``osmatch`` could give more detail info for the device OS.

**Comment by daniceexi** [comment]
@cxhong It's true that the ``nmap --osscan-guess`` takes about 4s for one ip, run nmap against multiple IPs in one run could save some time. This is the part that we can improve in our current code. 

I also found a terrible thing is the ``nmap --osscan-guess`` takes more than 2m to finish if the target ip is not response. We should make sure our code won't get into this situation.

**Comment by daniceexi** [comment]
@chenglch Another issue is our code is using the nmap flag ``-sP``, but this flag only works for early version of nmap. The new version nmap should use ``-sn``.

**Comment by daniceexi** [comment]
It's so close to the release, I think we need move this issue to 2.12.1.
@chenglch please summarize all the problems we discussed above and open another issue to track them.

**Comment by whowutwut** [comment]
I have a suggestion. What about if we provide and option to the command that allow the user to specify a vendor that we support. If specified then we can avoid the osscan process and just use the specified vendor. For example if the user know the vendor of the switch but want to get attributes of the switch defined into xCAT.. Thoughts?

**Comment by daniceexi** [comment]
This might do not work since vendor information could something like ``IBM``, we cannot assume a device is a switch if the vendor is ``IBM``. It could be a VIO server as we saw in this issue.
