### ISSUE TITLE
sequential/switch discovery woes

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#1110]
Is it me, or has the process significantly changed since xCAT 2.10

I have spent almost 2 days trying to understand the process of sequential discovery, and it is taking forever. 

I am using the following version of xCAT

```
# lsxcatd -v
Version 2.11.1 (git commit b6e4c8ca1847bf574d7e86687d74a7f2576d428a, built Thu Apr 14 09:32:27 EDT 2016)
```

The issues, I am finding is that during sequential discovery, I made some minor out-of-order discoveries, and I removed the node from the database, and they come back in as the same node again? how do we disable this process, and keep getting

```
xcatd: Processing discovery request from 10.28.5.6
Discovery Error: Could not find any node.
Discovery worker: fsp instance: nodediscover instance: Failed to notify 10.28.5.6 that it's actually <nodename>.
```

Is there a new method of doing sequential discovery, that isn't documented?

btw, trying to discover Nextscale nx360m5 nodes

**Comment by daniceexi** [comment]
@arif-ali If the mac for new discovered node has been defined in a pre-defined node, then the new discovered node will be updated to the pre-defined node. So you can take a look of the mac table.

For the issue you mentioned for 10.28.5.6, I need sometime to take a look.

**Comment by arif-ali** [comment]
I have tried doing doing `rmnodecfg` which I thought would remove all entries of the node, but I've had the same problem. 

I have since then shut the nodes down, ran `rmnodecfg`, and then restart xCAT, which somewhat helped

**Comment by daniceexi** [comment]
Since we have made significant change for the discovery framework (add a lot of debug messages), could you verify this issue base on the 2.12.1 GA (July 8) build? Or do you really want xcat to fix it in 2.10.x?

**Comment by arif-ali** [comment]
well, the system I am trying to discover now have gone, it would be very difficult to mimic the environment  again right now, until we have a new system.

On that note, I will close this case, as you said, you now have a new version of xCAT, and lots of debugging

**Comment by arif-ali** [comment]
@daniceexi, we had same issues when we did another recent installation, but discovery through switch.

After discovering a nextscale chassis, we kept getting same messages, and we could only resolve the issue by restarting the `xcatd` daemon after discovering those set of nodes

**Comment by zet809** [comment]
@arif-ali As you were using xCAT 2.12.1, will you pls send me the log file /var/log/xcat/cluster.log which include the keywords like "xcat.discovery"?
Within xcat2.12.1, we provide a tool called xcatprobe, will you pls run "xcatprobe switch-macmap <switch_node>" against the switch nodes and send the output to me?

**Comment by arif-ali** [comment]
Hi @zet809,

Below are the details to download the cluster.log from the machine we are installing

* Link: http://owncloud.ocf.co.uk/index.php/s/acZR7570A7iOe0O
* Password: eGXMXVrNcBg9

See below, on the command `xcatprobe`, which didn't work

```
[root@xcat01 ~]# xcatprobe switch-macmap
-bash: xcatprobe: command not found
[root@xcat01 ~]# rpm -qa | grep xCAT
xCAT-buildkit-2.12.1-snap201606230931.noarch
xCAT-genesis-scripts-x86_64-2.12.1-snap201606230931.noarch
xCAT-client-2.12.1-snap201606230930.noarch
xCAT-genesis-base-x86_64-2.12-snap201605051534.noarch
perl-xCAT-2.12.1-snap201606230930.noarch
xCAT-2.12.1-snap201606230931.x86_64
xCAT-server-2.12.1-snap201606230930.noarch
[root@xcat01 ~]# lsxcatd -a
Version 2.12.1 (git commit 93f20131dc8ebf4d8c4de47000bd631b7c7a9be7, built Thu Jun 23 09:30:44 EDT 2016)
This is a Management Node
dbengine=SQLite
```

**Comment by zet809** [comment]
@arif-ali Will you pls try the release version of xcat2.12.1 from http://xcat.org/files/xcat/xcat-core/2.12.x_Linux/xcat-core/xcat-core-2.12.1-linux.tar.bz2? It was built at July 8.
Then,  send the log file /var/log/xcat/cluster.log to me. Thx!
