### ISSUE TITLE
[DEV] Don't run rspconfig after hardware discovery finished for servers Other than S822L(TLT)

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#1115]
For S822L servers (Tuleta), the in-band ipmi operation is not supported (It use FSP to simulate the function of BMC such as supporting ipmi interface). In order to configure FSP ip, user account, we have to run 'rspconfig' to configure FSP out-of-band. 
But for later servers such as S822LC (Firestone), S812LC (Habanero) and even Garrison, there is full function of BMC is supported in-band from the host OS. We have bmcsetup to configuration BMC.

So, the purpose of this defect is:
1. For servers that support in-band BMC configuration, just remove the temp BMC node if there is.
2. If no in-band BMC configuration is supported, go to the original progress to use rspconfig to set BMC ip and user account.

**Comment by whowutwut** [comment]
@zet809  can you add some description for this issue and what the problem is when we run rspconfig after hardware discovery?  Should be S822L**C** right? what is TUT?  Tuletta?

**Comment by zet809** [comment]
@whowutwut Not S822LC, what I mean is S822L which is Tuleta servers.

**Comment by whowutwut** [comment]
Thanks for the clarification
