### ISSUE TITLE
[Customer]The '/dev' file system is changed to ready-only(ro) after install xcat-core 2.12

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1122]
The '/dev' file system is changed to ready-only(ro) after install xcat-core 2.12

[root@pcmrhelsmoke log]# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (**ro**,nosuid,size=3936960k,nr_inodes=984240,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)

[root@pcmrhelsmoke log]# lsxcatd -a
Version 2.12 (git commit a05c28c05ec91e47f68bfecad468a209fd962f21, built Thu May  5 01:43:04 EDT 2016)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=21.21.0.4|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=21.21.0.4
dbadmin=xcatadm

**Comment by tingtli** [comment]
@fenggaobj  what is the OS of the system?

**Comment by whowutwut** [comment]
@daniceexi  is this planned to be fixed for the GA?

**Comment by fenggaobj** [comment]
The OS is RHEL7.2 X86_64.

**Comment by tingtli** [comment]
@daniceexi @whowutwut 
I could reproduce this defect on our system.
Please take a look at this defect.

**Comment by daniceexi** [comment]
This issue happens on rh7.2 after the running the ``genimage`` command.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1131

**Comment by daniceexi** [comment]
The fix has been merged. But we still want to enhance this change, so move this issue to 2.12.1.

**Comment by whowutwut** [comment]
@daniceexi what is the enhancement that we want to do for the next release?

**Comment by daniceexi** [comment]
@whowutwut Use the ``cp`` to replace the ``cpio``, there's comment in the #1131.

**Comment by daniceexi** [comment]
Looks like cp has problem to handle the specific device files, so keep the original fix.
