### ISSUE TITLE
[FVT]Update customize_sleep_for_sn to get correct sn node name

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1125]
Need to update /opt/xcat/share/xcat/tools/autotest/testcase/installation/customize_sleep_for_sn to get correctly sn node name.
Following line will get wrong node names if there are several SN* attributes in configuration file. Please update that. 
my $snnodename = `cat $orgclusterconffile |grep SN|grep =|awk -F'=' '{print \$2}'`;

**Comment by hu-weihua** [comment]
@tingtli , fix this bug by pull request #1144 . Could you verify it ?thanks

**Comment by tingtli** [comment]
fixed with pull request #1092
