### ISSUE TITLE
[FVT]Delete nodes added by automation test cases.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1137]
There are two switch nodes added by automation test cases in MN: runcmdinstaller, will update code to delete them.

```
c910f03fs4:~ # lsdef
c910f03fsp03v05  (node)
switch-10-4-25-1  (node)
switch-10-5-24-1  (node)
```

**Comment by tingtli** [comment]
@caomengmeng  this is in component test. It is not test case requested.

**Comment by zet809** [comment]
@junxiawang Hi, jun xia, will you pls help to confirm the status right now?Thx!

**Comment by junxiawang** [comment]
pull requst 2180 and tingting please help review

**Comment by junxiawang** [comment]
Code modify has been merged
https://github.com/xcat2/xcat-core/pull/2180
modify switchdiscovery cases for issue 1137 #2180
