### ISSUE TITLE
[fvt]2.11:copycds failed using the latest build

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#114]
How to reproduce:
1.down load the latest build
2.c910f03c05k06:/ # lsdef -v
lsdef - Version 2.11 (git commit 4058f6b60af47a849ffaf36eda730ba3ca4bb949, built Mon Aug 24 04:34:29 EDT 2015)
3.c910f03c05k06:/ # copycds SLE-12-Server-DVD-ppc64le-GM-DVD1.iso 
Copying media to /install/sles12/ppc64le/1
Error: A fatal error was encountered, the following information may help identify a bug: Can't use string ("Copying media to /install/sles12"...) as an ARRAY ref while "strict refs" in use at /opt/xcat/sbin/xcatd line 3022.
ERROR/WARNING: communication with the xCAT server seems to have been ended prematurely

**Comment by hu-weihua** [comment]
This issue was caused by parsing copycds response format error.
