### ISSUE TITLE
addkitcomp  adds diskless genimage_postinstall  postcript into diskfull imageprofile

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1154]
The command "addkitcomp" will add diskless genimage_postinstall postcript into diskfull imageprofile. 
The right behavior should be the defined genimage_postinstall script in kit file will be added into diskless imageprofile, the "genimage_postinstall" key word should be forbidden for diskfull.
##Begin##############################################
The steps to reproduce it is following:
**1. Prepare the kit file and specify the "genimage_postinstall" define in the kit file for "component-pcm-monitoring-agent-4.2.2-1.rhels-7-ppc64le" component**
For example:
kitcomponent:
    _kitcompname=component-pcm-monitoring-agent-4.2.2-1.rhels-7-ppc64le
    description=IBM Spectrum Cluster Foundation node monitoring agent component
    kitname=kit-pcm-4.2.2
    kitreponame=kit-pcm-4.2.2-rhels-7-ppc64le
    basename=component-pcm-monitoring-agent
    version=4.2.2
    release=1
    serverroles=compute
    kitpkgdeps=gettext,pcm-ego
    #driverpacks=
    #kitcompdeps=
    postbootscripts=KIT_PCM_setupego,KIT_PCM_setupelk
    **genimage_postinstall**=KIT_PCM_genimage_egocore_post.sh_

**2. Run the "addkitcomp" command to add the component** 
For example:
_addkitcomp -i rhels7.2-ppc64le-stateful-compute component-pcm-base-node-4.2.2-1.rhels-7-ppc64le,component-pcm-monitoring-agent-4.2.2-1.rhels-7-ppc64le_

But this operation will generate postscript for "genimage_postinstall" in statefull imageprofile.

For example:
_[root@ppc803c ~]# lsdef -t osimage -o rhels7.2-ppc64le-stateful-compute
Object name: rhels7.2-ppc64le-stateful-compute
    addkcmdline=net.ifnames=0
    cfmdir=/install/osimages/rhels7.2-ppc64le-stateful-compute/cfmdir
    description=The rhels 7.2 ppc64le stateful compute image profile
    imagetype=linux
    isdeletable=0
    kitcomponents=component-pcm-monitoring-agent-4.2.2-1.rhels-7-ppc64le,component-pcm-base-node-4.2.2-1.rhels-7-ppc64le
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=linux
    osvers=rhels7.2
    otherpkgdir=/install/osimages/rhels7.2-ppc64le-stateful-compute/otherpkg
    otherpkglist=/install/osimages/rhels7.2-ppc64le-stateful-compute/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist,/install/osimages/rhels7.2-ppc64le-stateful-compute/custompkgs.pkglist,/install/osimages/rhels7.2-ppc64le-stateful-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist,/install/osimages/rhels7.2-ppc64le-stateful-compute/kits/KIT_RMPKGS.otherpkgs.pkglist
    pkgdir=/install/rhels7.2/ppc64le
    pkglist=/install/osimages/rhels7.2-ppc64le-stateful-compute/pkglist.cfm
    **postbootscripts=KIT_rhels7.2-ppc64le-stateful-compute.postbootscripts**,KIT_PCM_setupego,KIT_PCM_setupelk
    profile=compute
    provmethod=install
    serverrole=compute
    synclists=/install/osimages/rhels7.2-ppc64le-stateful-compute/synclist.cfm
    template=/install/osimages/rhels7.2-ppc64le-stateful-compute/compute.tmpl_

_[root@ppc803c ~]# cat /install/postscripts/KIT_rhels7.2-ppc64le-stateful-compute.postbootscripts
#!/bin/sh
otherpkgdir=/install/osimages/rhels7.2-ppc64le-stateful-compute/otherpkg KIT_PCM_genimage_egocore_post.sh_

**3. If these kit components are exist, please remove them first**
For example:
_rmkitcomp -i rhels7.2-ppc64le-stateful-compute component-pcm-base-node-4.2.2-1.rhels-7-ppc64le,component-pcm-monitoring-agent-4.2.2-1.rhels-7-ppc64le_ 
##End##############################################

**Comment by fenggaobj** [comment]
Another steps to reproduce:
1.buildkit create mytestkit
[root@ppc803c test]# buildkit create mytestkit
Kit template for mytestkit created in /root/test/mytestkit directory 

2.buildkit chkconfig
[root@ppc803c mytestkit]# buildkit chkconfig
No errors were found in Kit Build File /root/test/mytestkit/buildkit.conf. 

3.buildkit buildrepo all
[root@ppc803c mytestkit]# buildkit buildrepo all
Spawning worker 0 with 1 pkgs
Spawning worker 1 with 1 pkgs
Spawning worker 2 with 0 pkgs
Spawning worker 3 with 0 pkgs
Workers Finished
Saving Primary metadata
Saving file lists metadata
Saving other metadata
Generating sqlite DBs
Sqlite DBs complete

4.buildkit buildtar
[root@ppc803c mytestkit]# buildkit buildtar
Creating tar file /root/test/mytestkit/mytestkit-1.0-1.tar.bz2.
Kit tar file /root/test/mytestkit/mytestkit-1.0-1.tar.bz2 successfully built. 

5.addkitcomp
[root@ppc803c mytestkit-1.0-1]# addkitcomp -i rhels7.2-ppc64le-stateful-compute   mytestkit_compute-1.0-1-rhels-7.2-ppc64le
Assigning kit component mytestkit_compute-1.0-1-rhels-7.2-ppc64le to osimage rhels7.2-ppc64le-stateful-compute
Kit components mytestkit_compute-1.0-1-rhels-7.2-ppc64le were added to osimage rhels7.2-ppc64le-stateful-compute successfully

6. check the imageprofile
[root@ppc803c mytestkit]# lsdef -t osimage -o rhels7.2-ppc64le-stateful-compute
Object name: rhels7.2-ppc64le-stateful-compute
.....................................................
    postbootscripts=KIT_rhels7.2-ppc64le-stateful-compute.postbootscripts
    profile=compute
    provmethod=install
    serverrole=compute
    synclists=/install/osimages/rhels7.2-ppc64le-stateful-compute/synclist.cfm
    template=/install/osimages/rhels7.2-ppc64le-stateful-compute/compute.tmpl

7. check the postbootscripts
[root@ppc803c mytestkit]# cat /install/postscripts/KIT_rhels7.2-ppc64le-stateful-compute.postbootscripts
#!/bin/sh
otherpkgdir=/install/osimages/rhels7.2-ppc64le-stateful-compute/otherpkg KIT_mytestkit_compute-1.0-1-rhels-7.2-ppc64le_genimage_post.sh

**Comment by xyzcaoli** [comment]
PCM is waiting for this bug fixing because this blocked PCM diskless provision now. 
Could you please let us know when this can be fixed? We will run into Alpha this weekend, and the expectation is we can bundle the fix before our Alpha.  Thanks~

**Comment by daniceexi** [comment]
Talked with @xyzcaoli and @fenggaobj that this is not a valid defect. So close it now.
