### ISSUE TITLE
Older documentation inaccessible

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#1156]
The xCAT documentation on https://xcat-docs.readthedocs.io/ has only allows access to documentation of 2 versions of xCAT:
* [2.11](http://xcat-docs.readthedocs.io/en/2.11/)
* [Latest](http://xcat-docs.readthedocs.io/en/latest/)

I need access to older versions of the documentation (particularly, documentation for [v2.9.1](http://xcat-docs.readthedocs.io/en/2.9.1/)), but I get a `Permission Denied` error.

Documentation for all releases should be accessible (we're still using 2.9.1, and my team needs the 2.9.1 documentation for new members), atleast for those releases that have been made through Github.

**Comment by whowutwut** [comment]
Hi @samveen, we only just moved to readthedocs starting in the 2.11 branch after we moved the project to GitHub.  Instead of creating the docs in GitHub wiki, we put the documentation into `xcat-core/docs` directory and re-wrote to .rst format.  

So there's currently no version specific documentation for the 2.9 branch...

**Comment by samveen** [comment]
Does that mean that there is no official 2.9.x branch documentation available online?

**Comment by whowutwut** [comment]
Do you have specifics that you are looking for in terms of the xCAT documentation?  What architecture? We put a lot of focus on getting the content into the RTD but I think we still have some work in refining the content and verifying all the documentation is clear and correct....

I think the RTD documentation should be fairly similar in the 2.11 and 2.9.X.  (do you agree @daniceexi? ) There might be some new function documented in the latest that would not be avail.  
When we GA 2.12, the latest will be 2.12.   

In the past the documentation was just always on SourceForge wiki and we didn't have the ability to have branch specific versions so we had to write things like..."This function is supported in 2.X onwards"

**Comment by samveen** [comment]
I was looking for some VM management related documentation to give to my team ( `{mk,ch,rm}vm`, `rmigrate` etc.). The man pages give all the info I need, but I was hoping for web based docs to link into our internal wiki. 

As an aside, is it possible to generate man pages from each of the branches older release branches, to put on RTFD (under their respective doc trees)? I don't want the newbies access to even our devel environments until they've had atleast a little review of the required docs, and man pages as you can well imagine are on the xCAT server.

**Comment by whowutwut** [comment]
I'll talk to @gurevichmark next week. I think we can provide the man page and some basic docs for the earlier releases

**Comment by samveen** [comment]
Thank you.

**Comment by gurevichmark** [comment]
@samveen I verified that xCAT 2.9 man pages are now in RTD. Please close this issue once you verify that the documentation you wanted is there.

**Comment by samveen** [comment]
The 2.9 docs show up at http://xcat-docs.readthedocs.io/en/2.9/ prefectly now.

Thank you.
