### ISSUE TITLE
Failed to run syncfiles postscript against Ubuntu compute node

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1158]
We can see the following error message in the /var/log/xcat/xcat.log for a new installed ubuntu16.04 compute node.
~~~~
Thu May 19 08:09:48 EDT 2016 Running postscript: syncfiles
./syncfiles: 48: ./syncfiles: let: not found
./syncfiles: 49: ./syncfiles: let: not found
./syncfiles: 48: ./syncfiles: let: not found
./syncfiles: 49: ./syncfiles: let: not found
sleep: missing operand
Try 'sleep --help' for more information.
sleep: missing operand
~~~~

**Comment by daniceexi** [comment]
The root cause was the the script ``syncfiles`` use the ``/bin/sh`` as she-bang. This meant the ``dash`` instead of ``bash`` was used when run ``syncfiles`` in the ubuntu installer.  But the ``syncfiles`` was coded base on ``bash``. Then the syntax error happened.

The fix will be changing the sha-bang to /bin/bash from /bin/sh.

**Comment by daniceexi** [comment]
The workaround for this issue is to

* put the syncfiles postscript in the ``postbootscript`` attribute
* run the ``updatenode -F`` after node deployment

**Comment by tingtli** [comment]
@daniceexi will you fix this issue in 2.12?

**Comment by daniceexi** [comment]
No, will put it as a known issue.

**Comment by neo954** [comment]
Verified with xCAT 2.12-snap201605200311
