### ISSUE TITLE
[Customer] The postscript syncfiles does not work when enabled the xcatdebugmode for rh7.2

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1169]
A customer found the syncfiles postscript did not work for rh7.2 OS deployment when ``xcatdebugmode` was enabled.

The root cause should be the ``sshd`` was started by anaconda, then the ``restart of sshd`` in the remoteshell postscript failed.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1334/files

**Comment by daniceexi** [comment]
This has been verified on ``Red Hat Enterprise Linux Server release 7.2 (Maipo)``.
