### ISSUE TITLE
[FVT]:pping failed on Ubuntu16.04

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1171]
xCAT 2.12  on Ubuntu16.04
```
root@c910f03c17k27:~# lsxcatd -v
Version 2.12 (git commit 588076d19fdf219157690ce65299e92ca42f1398, built Fri May 20 03:12:19 EDT 2016)
root@c910f03c17k27:~# pping c910f03c17k29
Connection failure:
root@c910f03c17k27:~# echo $?
255
```

**Comment by neo954** [comment]
The same piece of code exist in the following command. They may also affected.

    $ grep -r 'my $client = IO::Socket::SSL->new(' .
    ./xCAT-client/bin/pasu:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pasu:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/piflash:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/piflash:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pping:	my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/ppping:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/prsync:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pscp:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/psh:  my $client = IO::Socket::SSL->new(

All these commands have the exactly same piece of code.

    $ grep -r -A 9 'my $client = IO::Socket::SSL->new(' .
    ./xCAT-client/bin/pasu:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pasu-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/pasu-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pasu-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pasu-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/pasu-                SSL_use_cert => 1,
    ./xCAT-client/bin/pasu-                SSL_verify_mode => 1,
    ./xCAT-client/bin/pasu-                %sslargs,
    ./xCAT-client/bin/pasu-             );
    ./xCAT-client/bin/pasu-  die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/pasu:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pasu-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/pasu-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pasu-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pasu-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/pasu-                SSL_use_cert => 1,
    ./xCAT-client/bin/pasu-                SSL_verify_mode => 1,
    ./xCAT-client/bin/pasu-                %sslargs,
    ./xCAT-client/bin/pasu-             );
    ./xCAT-client/bin/pasu-  die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/piflash:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/piflash-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/piflash-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/piflash-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/piflash-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/piflash-                SSL_use_cert => 1,
    ./xCAT-client/bin/piflash-                SSL_verify_mode => 1,
    ./xCAT-client/bin/piflash-                %sslargs,
    ./xCAT-client/bin/piflash-             );
    ./xCAT-client/bin/piflash-  die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/piflash:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/piflash-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/piflash-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/piflash-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/piflash-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/piflash-                SSL_use_cert => 1,
    ./xCAT-client/bin/piflash-                SSL_verify_mode => 1,
    ./xCAT-client/bin/piflash-                %sslargs,
    ./xCAT-client/bin/piflash-             );
    ./xCAT-client/bin/piflash-  die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/pping:	my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pping-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/pping-                SSL_key_file=> xCAT::Utils->getHomeDir()."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pping-                SSL_cert_file=> xCAT::Utils->getHomeDir()."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pping-                SSL_ca_file =>  xCAT::Utils->getHomeDir()."/.xcat/ca.pem",
    ./xCAT-client/bin/pping-                SSL_use_cert => 1,
    ./xCAT-client/bin/pping-                SSL_verify_mode => 1,
    ./xCAT-client/bin/pping-		%sslargs,
    ./xCAT-client/bin/pping-             );
    ./xCAT-client/bin/pping-	die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/ppping:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/ppping-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/ppping-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/ppping-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/ppping-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/ppping-                SSL_use_cert => 1,
    ./xCAT-client/bin/ppping-		%sslargs,
    ./xCAT-client/bin/ppping-                SSL_verify_mode => SSL_VERIFY_PEER,
    ./xCAT-client/bin/ppping-             );
    ./xCAT-client/bin/ppping-die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/prsync:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/prsync-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/prsync-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/prsync-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/prsync-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/prsync-                SSL_use_cert => 1,
    ./xCAT-client/bin/prsync-                SSL_verify_mode => 1,
    ./xCAT-client/bin/prsync-                %sslargs,
    ./xCAT-client/bin/prsync-             );
    ./xCAT-client/bin/prsync-die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/pscp:my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/pscp-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/pscp-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pscp-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/pscp-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/pscp-                SSL_use_cert => 1,
    ./xCAT-client/bin/pscp-                SSL_verify_mode => 1,
    ./xCAT-client/bin/pscp-                %sslargs,
    ./xCAT-client/bin/pscp-             );
    ./xCAT-client/bin/pscp-die "Connection failure: $!\n" unless ($client);
    --
    ./xCAT-client/bin/psh:  my $client = IO::Socket::SSL->new(
    ./xCAT-client/bin/psh-                PeerAddr=>$xcathost,
    ./xCAT-client/bin/psh-                SSL_key_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/psh-                SSL_cert_file=>$homedir."/.xcat/client-cred.pem",
    ./xCAT-client/bin/psh-                SSL_ca_file => $homedir."/.xcat/ca.pem",
    ./xCAT-client/bin/psh-                SSL_use_cert => 1,
    ./xCAT-client/bin/psh-                SSL_verify_mode => 1,
    ./xCAT-client/bin/psh-                %sslargs,
    ./xCAT-client/bin/psh-             );
    ./xCAT-client/bin/psh-  die "Connection failure: $!\n" unless ($client);

**Comment by daniceexi** [comment]
In the new version of **IO/Socket/SSL.pm** (At least on ubuntu 16.04: libio-socket-ssl-perl  2.024-1), it always try to verify the hostname of remote server to make sure it's same as the ``cn`` in the certificate of server. (Refer to the new() in the SSL.pm)

But in the old version, the hostname will only be verified when the SSL attribute ``SSL_verifycn_scheme`` is set. 

To avoid this issue, we need to set ``SSL_verifycn_scheme=none`` for SSL connection.

**Comment by daniceexi** [comment]
There's a tricky hole that ``verify hostname`` only happens when the remote server address is a hostname, the verification wont happen if the remote server is an IP address.

So the workaround is to set ``XCATHOST`` to be an IP address instead of hostname.

**Workaround**
~~~~
export XCATHOST=127.0.0.1:3001
~~~~

**Comment by daniceexi** [comment]
I have added a known issue in the 2.12 release notes. move this issue to 2.12.1

**Comment by tingtli** [comment]
@daniceexi  I verified your work around. It seems pping works but update node still error
```
root@c910f03c17k27:~# export XCATHOST=127.0.0.1:3001
root@c910f03c17k27:~# pping c910f03c17k29
c910f03c17k29: ping
root@c910f03c17k27:~# updatenode c910f03c17k29 -V
Running command on c910f03c17k27: /bin/hostname 2>&1

Running command on c910f03c17k27: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c17k27: /bin/hostname 2>&1

Running command on c910f03c17k27: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c17k27: chmod -R a+r /install/postscripts 2>&1

  c910f03c17k27: Internal call command: xdcp c910f03c17k29 --nodestatus -F /install/custom/netboot/ubuntu/compute.synclist
Running internal xCAT command: xdcp ...

Running command on c910f03c17k27: /bin/hostname 2>&1

Running command on c910f03c17k27: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

File synchronization has completed for nodes.
Performing software maintenance operations. This could take a while, if there are packages to install.

  c910f03c17k27: Internal call command: xdsh c910f03c17k29 --nodestatus -s -v -e /install/postscripts/xcatdsklspost 2 -m 10.3.17.27 'ospkgs,otherpkgs,syscloneimgupdate' --tftp /tftpboot --installdir /install --nfsv4 no -c -V
Running command on c910f03c17k27: /bin/hostname 2>&1
Running command on c910f03c17k27: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1
Running command on c910f03c17k27: hostname 2>&1
Running command on c910f03c17k27: /opt/xcat/bin/pping c910f03c17k29 2>&1
Error: Error from pping
c910f03c17k29: running /tmp/filepLWwID.dsh 2 -m 10.3.17.27 ospkgs,otherpkgs,syscloneimgupdate --tftp /tftpboot --installdir /install --nfsv4 no -c -V
c910f03c17k29: xcatdsklspost : trying to download postscripts from http://10.3.17.27/install/postscripts/
c910f03c17k29: /tmp/filepLWwID.dsh : download_postscripts return successfully
c910f03c17k29: xcatdsklspost: downloaded postscripts successfully
c910f03c17k29: /tmp/filepLWwID.dsh :  trying to download http://10.3.17.27/tftpboot/mypostscripts/mypostscript.c910f03c17k29
c910f03c17k29: /tmp/filepLWwID.dsh download_mypostscript return successfully
c910f03c17k29: running //xcatpost/mypostscript
c910f03c17k29: Fri May 20 10:03:27 EDT 2016 Running postscript: ospkgs
c910f03c17k29: NFSSERVER=10.3.17.27
c910f03c17k29: OSPKGDIR=/install/ubuntu16.04/ppc64el
c910f03c17k29: OSPKGS = bash,nfs-common,openssl,isc-dhcp-client,libc-bin,openssh-server,openssh-client,wget,vim,ntp,ntpdate,rsync,busybox-static,gawk,dnsutils
c910f03c17k29: pkgs= bash nfs-common openssl isc-dhcp-client libc-bin openssh-server openssh-client wget vim ntp ntpdate rsync busybox-static gawk dnsutils
c910f03c17k29: groups=
c910f03c17k29: remove groups=
c910f03c17k29: remove pkgs=
c910f03c17k29: deb http://10.3.17.27/install/ubuntu16.04/ppc64el xenial main restricted
c910f03c17k29: deb http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates main restricted
c910f03c17k29: Ign:1 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial InRelease
c910f03c17k29: Ign:2 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates InRelease
c910f03c17k29: Hit:3 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial Release
c910f03c17k29: Ign:4 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates Release
c910f03c17k29: Ign:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Ign:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Ign:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Ign:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Ign:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Ign:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Ign:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Ign:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Ign:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Ign:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Err:5 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main ppc64el Packages
c910f03c17k29:   404  Not Found
c910f03c17k29: Ign:6 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main all Packages
c910f03c17k29: Ign:7 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/main Translation-en
c910f03c17k29: Err:8 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted ppc64el Packages
c910f03c17k29:   404  Not Found
c910f03c17k29: Ign:9 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted all Packages
c910f03c17k29: Ign:10 http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates/restricted Translation-en
c910f03c17k29: Hit:12 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
c910f03c17k29: Reading package lists...
c910f03c17k29: W: The repository 'http://10.3.17.27/install/ubuntu16.04/ppc64el xenial-updates Release' does not have a Release file.
c910f03c17k29: E: Failed to fetch http://10.3.17.27/install/ubuntu16.04/ppc64el/dists/xenial-updates/main/binary-ppc64el/Packages  404  Not Found
c910f03c17k29: E: Failed to fetch http://10.3.17.27/install/ubuntu16.04/ppc64el/dists/xenial-updates/restricted/binary-ppc64el/Packages  404  Not Found
c910f03c17k29: E: Some index files failed to download. They have been ignored, or old ones used instead.
c910f03c17k29: === DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated --force-yes -o Dpkg::Options::='--force-confold' -o Dpkg::Options::='--force-confdef' upgrade
c910f03c17k29: Reading package lists...
c910f03c17k29: Building dependency tree...
c910f03c17k29: Reading state information...
c910f03c17k29: Calculating upgrade...
c910f03c17k29: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
c910f03c17k29: ===  apt-get -q -y --force-yes install --no-install-recommends  bash nfs-common openssl isc-dhcp-client libc-bin openssh-server openssh-client wget vim ntp ntpdate rsync busybox-static gawk dnsutils
c910f03c17k29: Reading package lists...
c910f03c17k29: Building dependency tree...
c910f03c17k29: Reading state information...
c910f03c17k29: bash is already the newest version (4.3-14ubuntu1).
c910f03c17k29: dnsutils is already the newest version (1:9.10.3.dfsg.P4-8).
c910f03c17k29: busybox-static is already the newest version (1:1.22.0-15ubuntu1).
c910f03c17k29: gawk is already the newest version (1:4.1.3+dfsg-0.1).
c910f03c17k29: nfs-common is already the newest version (1:1.2.8-9ubuntu12).
c910f03c17k29: ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5).
c910f03c17k29: ntpdate is already the newest version (1:4.2.8p4+dfsg-3ubuntu5).
c910f03c17k29: openssh-client is already the newest version (1:7.2p2-4).
c910f03c17k29: openssh-server is already the newest version (1:7.2p2-4).
c910f03c17k29: rsync is already the newest version (3.1.1-3ubuntu1).
c910f03c17k29: vim is already the newest version (2:7.4.1689-3ubuntu1).
c910f03c17k29: wget is already the newest version (1.17.1-1ubuntu1).
c910f03c17k29: openssl is already the newest version (1.0.2g-1ubuntu4.1).
c910f03c17k29: isc-dhcp-client is already the newest version (4.3.3-5ubuntu12).
c910f03c17k29: libc-bin is already the newest version (2.23-0ubuntu3).
c910f03c17k29: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
c910f03c17k29: Postscript: ospkgs exited with code 0
c910f03c17k29: Fri May 20 10:03:27 EDT 2016 Running postscript: otherpkgs
c910f03c17k29: ./otherpkgs: no extra rpms to install
c910f03c17k29: Postscript: otherpkgs exited with code 0
c910f03c17k29: Fri May 20 10:03:27 EDT 2016 Running postscript: syscloneimgupdate
c910f03c17k29: Postscript: syscloneimgupdate exited with code 0
c910f03c17k29: //xcatpost/mypostscript return with 0
c910f03c17k29: Running of Software Maintenance has completed.
  c910f03c17k27: Internal call command: xdsh c910f03c17k29 --nodestatus -s -v -e /install/postscripts/xcatdsklspost 1 -m 10.3.17.27 '' --tftp /tftpboot --installdir /install --nfsv4 no -c -V
Running command on c910f03c17k27: /bin/hostname 2>&1
Running command on c910f03c17k27: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1
Running command on c910f03c17k27: hostname 2>&1
Running command on c910f03c17k27: /opt/xcat/bin/pping c910f03c17k29 2>&1
Error: Error from pping
c910f03c17k29: running /tmp/filekj5H0g.dsh 1 -m 10.3.17.27  --tftp /tftpboot --installdir /install --nfsv4 no -c -V
c910f03c17k29: xcatdsklspost : trying to download postscripts from http://10.3.17.27/install/postscripts/
c910f03c17k29: /tmp/filekj5H0g.dsh : download_postscripts return successfully
c910f03c17k29: xcatdsklspost: downloaded postscripts successfully
c910f03c17k29: /tmp/filekj5H0g.dsh :  trying to download http://10.3.17.27/tftpboot/mypostscripts/mypostscript.c910f03c17k29
c910f03c17k29: /tmp/filekj5H0g.dsh download_mypostscript return successfully
c910f03c17k29: running //xcatpost/mypostscript
c910f03c17k29: Fri May 20 10:03:29 EDT 2016 Running postscript: syslog
c910f03c17k29: Postscript: syslog exited with code 0
c910f03c17k29: Fri May 20 10:03:29 EDT 2016 Running postscript: remoteshell
c910f03c17k29:
c910f03c17k29: root     11556  2.0  0.2  20992 14208 ?        Ss   10:03   0:00 sshd: root@notty
c910f03c17k29: root     11784  0.0  0.1  15360 10688 ?        Ss   10:03   0:00 /usr/sbin/sshd -D
c910f03c17k29: Postscript: remoteshell exited with code 0
c910f03c17k29: Fri May 20 10:03:31 EDT 2016 Running postscript: syncfiles
c910f03c17k29: Postscript: syncfiles exited with code 0
c910f03c17k29: Fri May 20 10:03:31 EDT 2016 Running postscript: otherpkgs
c910f03c17k29: ./otherpkgs: no extra rpms to install
c910f03c17k29: Postscript: otherpkgs exited with code 0
c910f03c17k29: //xcatpost/mypostscript return with 0
c910f03c17k29: Running of postscripts has completed.
```

**Comment by tingtli** [comment]
The autotest pping cases daily regression result shows the issue is fixed.
