### ISSUE TITLE
xcatd cannot start running immediately after upgrading to new version

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1173]
====================================================
[Date]       2016-05-20 11:19:20
[ClientType] cli
[Request]    xdsh c910f03fsp03v05 'zypper refresh;zypper -n update '\''*xCAT*'\'''
[Response]
c910f03fsp03v05: Repository 'SLES12-SP1-12.1-0' is up to date.
c910f03fsp03v05: Repository 'SuSE-Linux-pkg0' is up to date.
c910f03fsp03v05: Retrieving repository 'xCAT 2 Core packages' metadata [.done]
c910f03fsp03v05: Building repository 'xCAT 2 Core packages' cache [....done]
c910f03fsp03v05: Retrieving repository 'xCAT 2.0 depedencies' metadata [.done]
c910f03fsp03v05: Building repository 'xCAT 2.0 depedencies' cache [....done]
c910f03fsp03v05: All repositories have been refreshed.
c910f03fsp03v05: Loading repository data...
c910f03fsp03v05: Reading installed packages...
c910f03fsp03v05: No update candidate for 'grub2-xcat-2.02-0.16.el7.snap201506090204.noarch'. The highest available version is already installed.
c910f03fsp03v05: No update candidate for 'conserver-xcat-8.1.16-10.ppc64le'. The highest available version is already installed.
c910f03fsp03v05: Resolving package dependencies...
c910f03fsp03v05:
c910f03fsp03v05: The following 2 NEW packages are going to be installed:
c910f03fsp03v05:   perl-HTTP-Async perl-Net-HTTPS-NB
c910f03fsp03v05:
c910f03fsp03v05: The following 8 packages are going to be upgraded:
c910f03fsp03v05:   ipmitool-xcat perl-xCAT xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-scripts-ppc64 xCAT-server
c910f03fsp03v05:
c910f03fsp03v05: The following 10 packages are not supported by their vendor:
c910f03fsp03v05:   ipmitool-xcat perl-HTTP-Async perl-Net-HTTPS-NB perl-xCAT xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-scripts-ppc64 xCAT-server
c910f03fsp03v05:
c910f03fsp03v05: 8 packages to upgrade, 2 new.
c910f03fsp03v05: Overall download size: 44.4 MiB. Already cached: 0 B. After the operation, additional 49.5 MiB will be used.
c910f03fsp03v05: Continue? [y/n/? shows all options] (y): y
c910f03fsp03v05: Retrieving package xCAT-buildkit-4:2.12-snap201605200311.noarch (1/10),  67.7 KiB (299.0 KiB unpacked)
c910f03fsp03v05: Retrieving package perl-xCAT-4:2.12-snap201605200310.noarch (2/10), 609.9 KiB (  3.7 MiB unpacked)
c910f03fsp03v05: Retrieving package xCAT-client-4:2.12-snap201605200310.noarch (3/10), 508.5 KiB (  2.9 MiB unpacked)
c910f03fsp03v05: Retrieving package perl-HTTP-Async-0.30-2.noarch (4/10),  18.4 KiB ( 56.0 KiB unpacked)
c910f03fsp03v05: Retrieving package perl-Net-HTTPS-NB-0.14-2.noarch (5/10),   8.9 KiB ( 16.0 KiB unpacked)
c910f03fsp03v05: Retrieving package xCAT-genesis-base-ppc64-1:2.12-snap201605051443.noarch (6/10),  41.1 MiB (159.6 MiB unpacked)
c910f03fsp03v05: Retrieving package ipmitool-xcat-1.8.15-1.ppc64le (7/10), 242.8 KiB (814.0 KiB unpacked)
c910f03fsp03v05: Retrieving package xCAT-server-4:2.12-snap201605200310.noarch (8/10),   1.6 MiB (  8.0 MiB unpacked)
c910f03fsp03v05: Retrieving package xCAT-genesis-scripts-ppc64-1:2.12-snap201605200311.noarch (9/10),  60.5 KiB (218.4 KiB unpacked)
c910f03fsp03v05: Retrieving package xCAT-2.12-snap201605200311.ppc64le (10/10), 215.7 KiB (758.9 KiB unpacked)
c910f03fsp03v05: Checking for file conflicts: [........done]
c910f03fsp03v05: ( 1/10) Installing: xCAT-buildkit-4:2.12-snap201605200311 [..................done]
c910f03fsp03v05: ( 2/10) Installing: perl-xCAT-4:2.12-snap201605200310 [....................done]
c910f03fsp03v05: ( 3/10) Installing: xCAT-client-4:2.12-snap201605200310 [....................done]
c910f03fsp03v05: ( 4/10) Installing: perl-HTTP-Async-0.30-2 [......done]
c910f03fsp03v05: ( 5/10) Installing: perl-Net-HTTPS-NB-0.14-2 [.....done]
c910f03fsp03v05: ( 6/10) Installing: xCAT-genesis-base-ppc64-1:2.12-snap201605051443 [........................done]
c910f03fsp03v05: Additional rpm output:
c910f03fsp03v05: If you are installing/updating xCAT-genesis-base separately, not as part of installing/updating all of xCAT, run 'mknb <arch>' manually
c910f03fsp03v05: ( 7/10) Installing: ipmitool-xcat-1.8.15-1 [.........done]
c910f03fsp03v05: ( 8/10) Installing: xCAT-server-4:2.12-snap201605200310 [...................done]
c910f03fsp03v05: ( 9/10) Installing: xCAT-genesis-scripts-ppc64-1:2.12-snap201605200311 [................done]
c910f03fsp03v05: Additional rpm output:
c910f03fsp03v05: If you are installing/updating xCAT-genesis-base separately, not as part of installing/updating all of xCAT, run 'mknb <arch>' manually
c910f03fsp03v05:
c910f03fsp03v05:
c910f03fsp03v05: (10/10) Installing: xCAT-2.12-snap201605200311 [...................done]
c910f03fsp03v05: Additional rpm output:
c910f03fsp03v05: Running '/opt/xcat/sbin/mknb ppc64', triggered by the installation/update of xCAT-genesis-scripts-ppc64 ...
c910f03fsp03v05: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 238.
c910f03fsp03v05: Unable to open socket connection to xcatd daemon on localhost:3001.
c910f03fsp03v05: Verify that the xcatd daemon is running and that your SSL setup is correct.
c910f03fsp03v05: The 'mknb ppc64' command returned error code: 111.

---
[ClientType] cli
[Request]    xdsh c910f03fsp03v05 'service xcatd status'
[Response]
c910f03fsp03v05: xcatd.service - LSB: xcatd
c910f03fsp03v05:    Loaded: loaded (/etc/init.d/xcatd)
c910f03fsp03v05:    Active: active (running) since Fri 2016-05-20 11:20:33 EDT; 6s ago
c910f03fsp03v05:   Process: 5300 ExecStop=/etc/init.d/xcatd stop (code=exited, status=0/SUCCESS)
c910f03fsp03v05:   Process: 5381 ExecStart=/etc/init.d/xcatd start (code=exited, status=0/SUCCESS)
c910f03fsp03v05:    CGroup: /system.slice/xcatd.service
c910f03fsp03v05:            `-18300 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf
c910f03fsp03v05:
c910f03fsp03v05: May 20 11:20:33 c910f03fsp03v05 xcatd[5381]: xcatd already running  warning

---
[Date]       2016-05-20 11:20:40
[ClientType] cli
[Request]    xdsh c910f03fsp03v05 lsdef
[Response]
c910f03fsp03v05: Unable to open socket connection to xcatd daemon on localhost:3001.
c910f03fsp03v05: Verify that the xcatd daemon is running and that your SSL setup is correct.
c910f03fsp03v05: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 238.

**Comment by daniceexi** [comment]
We just saw this issue one time on ppc64 MN, it might be a timing issue. Will try to recreate it.

**Comment by daniceexi** [comment]
we should add action in migration test case to check whether mknb is run successfully during the xcat update process

**Comment by caomengmeng** [comment]
@daniceexi 
ppc64le, rh7.2, install xCAT 2.11.1, then upgrade to 2.12.1 successfully, but xCAT is not running.
Test ENV:
```
[root@c910f03fsp03v02 ~]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@c910f03fsp03v02 ~]# lsxcatd -a
Version 2.12.1 (git commit 15780386324e21e9b4a32bda10a8fdde5dfa8998, built Tue May 31 06:45:36 EDT 2016)
This is a Management Node
dbengine=SQLite

```

Upgrade to 2.12.1 successfully, but xCAT is not running.
```
[root@c910f03fsp03v03 oldxcat]# service xcatd status
xcatd service is not running
[root@c910f03fsp03v03 oldxcat]# lsxcatd -a
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 238.
[root@c910f03fsp03v03 oldxcat]# lsdef
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 238.
```

**Comment by daniceexi** [comment]
From the system log I saw following messages:

~~~~
May 31 14:51:15 c910f03fsp03v03 systemd: Stopping LSB: xCATd...
May 31 14:51:17 c910f03fsp03v03 xcatd: Stopping xcatd [FAILED]
May 31 14:51:17 c910f03fsp03v03 systemd: Starting LSB: xCATd...
May 31 14:51:17 c910f03fsp03v03 xcatd: xcatd already running [PASSED]
May 31 14:51:17 c910f03fsp03v03 systemd: Started LSB: xCATd.
~~~~

The message said: **Stopping xcatd [FAILED]**. This failure caused the start of xcatd failed too since the xcatd start program thought the xcatd was running.

My change is to make the stopping program waiting longer before failure.

Refer to the pull request #1137.

**Comment by daniceexi** [comment]
We are running the migration in everyday's automation but cannot recreate this issue. So close it now and will solve it when encounter again.
