### ISSUE TITLE
[FVT]:fix xfs issue on c910f03c17

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1175]
We hit file system issue on c910f03c17. Please help fix that.
c910f04x31:~ # rcons c910f03c17k30 -f

[Enter `^Ec?' for help]

[39648.163360] XFS (dm-0): xfs_log_force: error -5 returned.
[39678.242741] XFS (dm-0): xfs_log_force: error -5 returned.
[39708.322144] XFS (dm-0): xfs_log_force: error -5 returned.
[39738.401639] XFS (dm-0): xfs_log_force: error -5 returned.
[39768.481060] XFS (dm-0): xfs_log_force: error -5 returned.
[39798.560458] XFS (dm-0): xfs_log_force: error -5 returned.
[39828.639915] XFS (dm-0): xfs_log_force: error -5 returned.
[39858.719259] XFS (dm-0): xfs_log_force: error -5 returned.
[39888.798682] XFS (dm-0): xfs_log_force: error -5 returned.

**Comment by neo954** [comment]
I got the following kernel logs from the conserver log.

    [  272.419720] UDF-fs: warning (device loop0): udf_fill_super: No partition found (2)
    [  543.674222] sd 0:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
    [  543.674502] sd 0:0:0:0: [sda] Sense Key : Aborted Command [current]
    [  543.674656] sd 0:0:0:0: [sda] Add. Sense: I/O process terminated
    [  543.674813] sd 0:0:0:0: [sda] CDB: Write(10) 2a 00 01 b6 b7 e8 00 00 08 00
    [  543.674987] blk_update_request: I/O error, dev sda, sector 28751848
    [  543.676116] Buffer I/O error on device dm-0, logical block 2477053
    [  543.676180] lost page write due to I/O error on dm-0
    [  543.852048] sd 0:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
    [  543.852137] sd 0:0:0:0: [sda] Sense Key : Aborted Command [current]
    [  543.852190] sd 0:0:0:0: [sda] Add. Sense: I/O process terminated
    [  543.852248] sd 0:0:0:0: [sda] CDB: Read(10) 28 00 01 ab 8b b8 00 00 90 00
    [  543.852305] blk_update_request: I/O error, dev sda, sector 28019640
    [  543.954368] sd 0:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
    [  543.954475] sd 0:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
    [  543.954476] sd 0:0:0:0: [sda] Sense Key : Aborted Command [current]
    [  543.954478] sd 0:0:0:0: [sda] Add. Sense: I/O process terminated
    [  543.954480] sd 0:0:0:0: [sda] CDB: Read(10) 28 00 01 ab 8b b8 00 00 80 00
    [  543.954481] blk_update_request: I/O error, dev sda, sector 28019640
    [  543.954717] sd 0:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
    [  543.954719] sd 0:0:0:0: [sda] Sense Key : Aborted Command [current]
    [  543.954722] sd 0:0:0:0: [sda] Add. Sense: I/O process terminated
    [  543.954725] sd 0:0:0:0: [sda] CDB: Write(10) 2a 00 02 c4 4c d4 00 00 0b 00
    [  543.954728] blk_update_request: I/O error, dev sda, sector 46419156
    [  543.954732] blk_update_request: I/O error, dev sda, sector 46419156
    [  543.954752] XFS (dm-0): metadata I/O error: block 0x23bf4d4 ("xlog_iodone") error 5 numblks 64
    [  543.954756] XFS (dm-0): xfs_do_force_shutdown(0x2) called from line 1180 of file fs/xfs/xfs_log.c.  Return address = 0xd00000000200c208
    [  543.954831] XFS (dm-0): Log I/O Error Detected.  Shutting down filesystem
    [  543.954832] XFS (dm-0): Please umount the filesystem and rectify the problem(s)
    [  543.957804] sd 0:0:0:0: [sda] Sense Key : Aborted Command [current]
    [  543.957860] sd 0:0:0:0: [sda] Add. Sense: I/O process terminated
    [  543.957920] sd 0:0:0:0: [sda] CDB: Read(10) 28 00 01 b2 c3 50 00 00 10 00
    [  543.957984] blk_update_request: I/O error, dev sda, sector 28492624
    [  543.963943] XFS (dm-0): metadata I/O error: block 0x12a6b50 ("xfs_trans_read_buf_map") error 5 numblks 16
    [  543.964083] XFS (dm-0): xfs_imap_to_bp: xfs_trans_read_buf() returned error -5.
    [  573.912508] XFS (dm-0): xfs_log_force: error -5 returned.

**Comment by tingtli** [comment]
@neo954 I am debugging this issue. I review all the test cases. The only doubt is we use rmvm and mkvm commands in the test cases which probably cause the filesystem and i/o problem.

**Comment by immarvin** [comment]
hi @neo954 , you can open a ticket to LTC if it is a XFS problem

**Comment by daniceexi** [comment]
Will handle this issue when encounter again.

**Comment by neo954** [comment]
This problem was already solved. It is due to a PowerKVM bug.

https://bugzilla.linux.ibm.com/show_bug.cgi?id=135113

**Comment by neo954** [comment]
Will close this one.
