### ISSUE TITLE
[FVT]: Refine docker case to support in the daily regression.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1176]
We have some docker cases failed in autotest, after investigation, I found we have some attributes in docker support which has no correct values.

**Comment by daniceexi** [comment]
@junxiawang You need to give reasonable information that why this issue can be closed.

**Comment by junxiawang** [comment]
@daniceexi  I modify the test case and did pull request

**Comment by daniceexi** [comment]
please mention the issue number in your pull request, then the reader could see this issue has been fixed by certain pull request.

**Comment by tingtli** [comment]
Updated the docker attributes value on Jenkins environment.
