### ISSUE TITLE
[Customer]man makentp explains with wrong information. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1177]
in 2.12 xCAT version, when man makentp , I saw the wrong information  provided, 
see below:  <------------: 
EXAMPLES
       1. To setup NTP server on the management node:
           makentp

       2. To setup NTP servers on both management node and the service node:
           setupntp -a     <------------

FILES
       /opt/xcat/bin/setupntp    < -------------

**Comment by daniceexi** [comment]
@bybai Could you take a look of this issue?
