### ISSUE TITLE
rflash changes for GRS Hardware

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#1183]
As per the release notes on GRS firmware page, the instructions to install via ipmitool have changed.  Particularly, these two commands

```
ipmitool -H <BMC IP> -U ADMIN -I lanplus -P admin -z 15000 hpm upgrade <xxxxx.hpm>    component 1 force
#Wait 2 minutes for BMC to come back online
ipmitool -H <BMC IP> -U ADMIN -I lanplus -P admin -z 15000 hpm upgrade <xxxxx.hpm>    force
```
I have manually run these steps in our development environment and successfully updated the GRS firmware

This change appears to be due to a defect.  I think we will have to contact firmware team to determine if this procedure change will be permanent or is only a temporary fix.

**Comment by daniceexi** [comment]
@pdlun92 We need track this issue.

**Comment by pdlun92** [comment]
@daniceexi I agree.  Decided to wait until GA level firmware is available in case instructions change, but leave this issue open in the mean time

**Comment by whowutwut** [comment]
@pdlun92 let's send a note to the firmware team or have them comment here on the issue. If we can get this resolved and implement any code change earlier it will be better so we can get more testing

**Comment by pdlun92** [comment]
Per firmware team...
```
We have an issue with hpm upgrade on Garrison http://w3.rchland.ibm.com/projects/bestquest/?verb=view&defect=SW337174 . That was the reason we modified the install instructions. We are getting a fix for this in next AMI release. So, for Garrison GA install instructions will be same as Firestone 
```

ok to close this issue?

**Comment by pdlun92** [comment]
It seems that there is no timetable for fix to be implemented on firmware side, will begin working on a workaround in the mean time

**Comment by whowutwut** [comment]
Let's target this for the 2.12.2 release and make a code change to: 
* If the FW level is too early, stop rflash with a msg to ask Admin to manually update to the stable version
* Detect GRS server and update using the different buffer size 

Then the other teams can at least start running rflash at a larger scale
