### ISSUE TITLE
[Customer] bootloader is not grabbing the addkcmdline from osimage

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#1185]
I have updated my kickstart template to use #KICKSTARTBOOTLOADER#, but the values that have been added to the addkcmdline are not being added to this parameter. Any ideas on this would be great

Version of xCAT below
```
# lsxcatd -a
Version 2.12 (git commit 588076d19fdf219157690ce65299e92ca42f1398, built Fri May 20 03:10:38 EDT 2016)
This is a Management Node
dbengine=SQLite
```

**Comment by daniceexi** [comment]
@arif-ali In the 2.12, we are using the keyword ``R:<kernel param>`` to add specific kernel parameter to the kickstart bootloader attribute. The ``#KICKSTARTBOOTLOADER#`` won't be used any more since we need to customize the ``bootloader`` parameters in the pre-script.

Could you give me more information of your requirement?

**Comment by immarvin** [comment]
please try ``chdef -t osimage -o <osimage name> -p addkcmdline="R::<persistent kcmdline>"`` 

````
[root@c910f03c05k21 ~]# tabdump -d linuximage
...
addkcmdline:    User specified arguments to be passed to the kernel.  The user arguments are appended to xCAT.s default kernel arguments. For the kernel options need to be persistent after installation, specify them with prefix "R::".  This attribute is ignored if linuximage.boottarget is set.
````

#KICKSTARTBOOTLOADER# for redhat 7 has been obsoleted in xcat 2.12  
https://github.com/xcat2/xcat-core/pull/1118/files

**Comment by arif-ali** [comment]
Thanks, I have figured it out.

I updated the addkcmdline, and then added #KICKSTARTBOOTLOADER# into my custom partition file. I presume, this is the recommended way?

**Comment by whowutwut** [comment]
@immarvin  can you double check if our documentation reflected that change in xCAT 2.12?

**Comment by daniceexi** [comment]
@arif-ali In the 2.12, the ``#KICKSTARTBOOTLOADER#`` has been commented off, so user don't need to add it back manually. Is there any problem that why you added it back?

**Comment by arif-ali** [comment]
@daniceexi I have my own partitionfile, and therefore wouldn't be picked up in /tmp/partitioning, as I am not using the /tmp/partitioning. Or is there a new way of specifying the partition?

**Comment by arif-ali** [comment]
For info, below is my osimage definition. correct me, if I am wrong, but the `/tmp/partitionfile` action in the pre script will not come about, and therefore, you have to either comment out `#KICKSTARTBOOTLOADER#` in the template, or add it to the partitionfile definition, like have for my osimage

```
# lsdef -z -t osimage base-image
# <xCAT data object stanza file>

base-image:
    objtype=osimage
    addkcmdline=R::intel_pstate=disable
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.2-x86_64
    osname=Linux
    osvers=centos7.2
    otherpkgdir=/install/post/otherpkgs/repos
    otherpkglist=/install/templates/base/otherpkgs.pkglist
    partitionfile=/install/templates/base/partfile
    pkgdir=/install/centos7.2/x86_64,/install/post/otherpkgs/repos/updates-7
    pkglist=/install/templates/base/pkglist
    profile=compute
    provmethod=install
    synclists=/install/templates/base/synclist
    template=/install/templates/base/template
```

You have already got this in the pre.script

```
#specify "bootloader" configuration in "/tmp/partitioning" if there is no user customized partition file
BOOTLOADER="bootloader "

#specify the kernel options which will be persistent after installation
[ -n "#ENV:PERSKCMDLINE#" ] && BOOTLOADER=$BOOTLOADER" --append=#ENV:PERSKCMDLINE#"

#Specifies which drive the boot loader should be written to
#and therefore which drive the computer will boot from.
[ -n "$instdisk" ] && BOOTLOADER=$BOOTLOADER" --boot-drive=$(basename $instdisk)"

echo "$BOOTLOADER" >> /tmp/partitioning
```
which, therefore doesn't make sense. I think this should be consistent, and really, we shouldn't need to specify that manually anywhere, and xCAT should pick it up automatically. I think this may be a regression for those people using custom partitioning

**Comment by daniceexi** [comment]
@arif-ali The reason we moved the ``#KICKSTARTBOOTLOADER#`` to be done in the pre-script was the ``--boot-drive=$(basename $instdisk)`` need to get the ``$instdisk`` which comes from pre-script.

We can take back the ``#KICKSTARTBOOTLOADER#`` to make it take effect if customer's partitionfile is used.

But even with this change, if you are using the partitionfile, ``--boot-drive=$instdisk`` cannot be picked up by xcat automatically, since the $instdisk was generated by your partitionfile.

Refer to the issue #821. That will be fine for my proposal if this issue #821 is not an issue for you.

**Comment by arif-ali** [comment]
@daniceexi I have encountered the issue that you have in #821. But I am discovering these devices manually with an initial install now, and then adding to the partition file myself, like below. I.e. I am manually adding the `/dev/disk/by-path/...`

```
part /boot/efi --fstype vfat --size 100 --ondisk /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:2:0:0
part /boot --fstype xfs --size 500 --ondisk /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:2:0:0

part pv.0 --grow --size 1024 --ondisk /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:2:0:0

volgroup system --pesize=4096 pv.0

logvol / --fstype=xfs --name=root --vgname=system --size 20480
logvol swap --name=swap --vgname=system --size=8192
logvol /var --fstype=xfs --name=var --vgname=system --size=40960
logvol /var/log --fstype=xfs --name=varlog --vgname=system --size=40960
```

I agree, that if someone doesn't set the partition file, then you can do this automatically for them, but for those people doing this manually, then it makes sense, for the advanced users to set these manually

**Comment by daniceexi** [comment]
OK, xCAT will make the change as I proposed.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1393

**Comment by arif-ali** [comment]
I presume this will be cherry-picked for 2.12.1?

**Comment by daniceexi** [comment]
Yes, all the commits in master from 2.12 release will be merged back to 2.12.1

**Comment by arif-ali** [comment]
cool, thanks

**Comment by daniceexi** [comment]
@arif-ali  I'll close this issue now, please reopen it if you still have problem.
