### ISSUE TITLE
[FVT]Failed to install diskfull CN on ppc64le ubuntu14.04.4

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1188]
Description: After "nodeset; rpower CN boot", the CN is not successfully installed.
Below is the CN status.
```
root@c910f03f:/opt/xcat/share/xcat/tools/autotest/result# ping c910f03f
PING c910f03f.pok.stglabs.ibm.com (10.3.9.7) 56(84) bytes of data.
From c910f03f.pok.stglabs.ibm.com (10.3.9.6) icmp_seq=1 Destination Host Unreachable
From c910f03f.pok.stglabs.ibm.com (10.3.9.6) icmp_seq=2 Destination Host Unreachable
From c910f03f.pok.stglabs.ibm.com (10.3.9.6) icmp_seq=3 Destination Host Unreachable
^C
--- c910f03f.pok.stglabs.ibm.com ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4023ms
pipe 3
root@c910f03f:/opt/xcat/share/xcat/tools/autotest/result# rcons c910f03f
[Enter `^Ec?' for help]
Remove dead screens with 'screen -wipe'.
Clear screen capability required.
Connection to node-32030901 closed.
Remove dead screens with 'screen -wipe'.
Clear screen capability required.
Connection to node-32030901 closed.
Remove dead screens with 'screen -wipe'.
Clear screen capability required.

```
Test EVN:
```
root@c910f03fsp03v06:/opt/xcat/share/xcat/tools/autotest/result# lsxcatd -a
Version 2.13 (git commit e75ecf510b1606a7148912b7fd78ab37c7a49788, built Mon May 23 06:47:13 EDT 2016)
This is a Management Node
dbengine=SQLite
```

**Comment by daniceexi** [comment]
The mac of the compute node is: ``42:4a:0a:03:09:07``. From the dhcpd log on the xCAT MN, we can see the message **10.4.42.102 (10.4.42.100)**  from **DHCPREQUEST** packet. This error caused the compute node failed to net booting.


------

May 23 11:47:07 c910f03fsp03v06 dhcpd: DHCPDISCOVER from 42:4a:0a:03:09:07 via eth0
May 23 11:47:07 c910f03fsp03v06 dhcpd: DHCPOFFER on **10.3.9.7** to 42:4a:0a:03:09:07 via eth0
May 23 11:47:07 c910f03fsp03v06 dhcpd: DHCPREQUEST for **10.4.42.102 (10.4.42.100)**  from 42:4a:0a:03:09:07 via eth0: lease 10.4.42.102 unavailable.
May 23 11:47:07 c910f03fsp03v06 dhcpd: **DHCPNAK** on 10.4.42.102 to 42:4a:0a:03:09:07 via eth0

-----------
My first thought was the dhcpd on 10.4.42.100 gave an incorrect ip to the compute node. But from the log on 10.4.42.100, it said I don't  know this mac.

-----------
016-05-23T11:47:03.998014-04:00 c910f04x42vm100 dhcpd: **DHCPREQUEST for 10.4.42.102 (10.4.42.100) from 42:4a:0a:03:09:07 via eth0: unknown lease 10.4.42.102.**

**So I guess there's bug in the kvm firmware. I will try to update the kvmhost to latest version.**

**Comment by daniceexi** [comment]
I opened a bug to LTC: https://bugzilla.linux.ibm.com/show_bug.cgi?id=14232

**Comment by caomengmeng** [comment]
close this issue, and track it in: https://bugzilla.linux.ibm.com/show_bug.cgi?id=142326
