### ISSUE TITLE
[FVT]Diskful installation is failed, case is stopped by stop label but mail shows: out of 9 hours.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1189]
Description: Add stop:yes label to "Full_installation_flat_p8_le" case, and this case is failed for issue: https://github.com/xcat2/xcat-core/issues/1188, this ubuntu14.04.4 on ppc64le test environment is stopped, but the mail sent to group shows: 
```
[ubuntu14.04.4+PPC64LE] 
		 Time consumption: Out of 9 hours!!!!!!
```
It should be like this:
```
[sles12.1+PPC64LE] 
		 Time consumption: 3 hours 45 minutes 44 seconds
		 TotalCase 200 TotalRun 198 Failed 1
		 Failed cases:  sles_migration1, 
		 Final environment stop at sles_migration1
```

**Comment by hu-weihua** [comment]
@caomengmeng , after checking, I found ``xCATreg`` has been changed by someone for unknown reason, one loop black was removed, so when one test case stop then ``xCATreg`` is supposed to break out by ``last`` statement, but now,  a important pair ``{ }`` was removed, so sub process is broken when it run ``last`` statement.  so sub process didn't send information to main process as original plan, the main process though the sub process out of time after waiting 9 hours.

**Comment by caomengmeng** [comment]
Thanks @hu-weihua  for your effort and great help.
@junxiawang Will send a pull request to fix this issue.
Thanks.

**Comment by whowutwut** [comment]
Great Job! 👍  This should shorten the automation run!  Should we change the 9 hour timeout? Seems really really long....

**Comment by caomengmeng** [comment]
@whowutwut 
There are diskless, diskful, commands, statelite, SN, diskless hierarchy, diskful hierachy, statelite hierarchy by ramdisk and statelite hiearchy by nfs for ppc and x86 test environment, and the mails include the total run time, for example, the rh7.2 ppc64, please see below, the total hour is more than 7.
As experience, 9 hours is enough. But some times, maybe some case hang for some reason, so if it is more than 9 hours for one platform, this kind of message will be shown.
```
[rhels7.2+PPC64] 
		 Time consumption: 7 hours 11 minutes 11 seconds
		 TotalCase 305 TotalRun 305 Failed 0
		 Failed cases: 
		 Final environment stop at reg_linux_statelite_installation_hierarchy_by_nfs
```
Junxia  will make necessary changes to Git to make xCATreg file synced with local automation machine : https://github.com/xcat2/xcat-core/pull/1194, so close this  issue
So close this issue.
