### ISSUE TITLE
xCAT installation trashes customer's original ntp.conf

### ISSUE THREAD

**Issue by linggao** [xcat2/xcat-core#119]
A customer reported that /etc/ntp.conf file got totally replaced when installing xCAT on management node.
This is caused by xcatconfig script. We need to figure out what to do with it. Either not setting up ntp automatically. Let the customer manually setup ntp using makentp command after the xCAT is installed. Or save customer's original ntp.conf file.

**Comment by daniceexi** [comment]
The originator want to keep the original /etc/ntp.conf if it was there when install xcat. I am fine that remove the ntp config code from the xcatconfig when install xcat.

**Comment by whowutwut** [comment]
I think for system config files for the management node we should not assume we have full control on the files or starting with a clean system and can be destructive. We can for nodes that we provision and control  but mgmt node should not be considered one of those. Do we have other scripts doing similar destructive things?

**Comment by daniceexi** [comment]
During the install of xcat, the xcatconfig script will be run to initialize certain services. The config files like
~~~~
/etc/sysctl.conf
/root/.ssh/config
/etc/selinux/config
/etc/ntp.conf
~~~~
will be touched. 

But only the ntp.conf is changed in a disruptive way. So remove the ntp configure in xcatconfig should be ok now.

**Comment by whowutwut** [comment]
Sounds good

**Comment by daniceexi** [comment]
@cxhong Could you work with @linggao to skip the code logic of ntp configuration from xcatconfig script?
