### ISSUE TITLE
Request FVT autotest case created for provisioning multiple NICs and configure multiple subnets

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1199]
@tingtli  Can we add some FVT autotest cases that focus on configuration of a PowerKVM machine that has multiple ethernet adapters (You can give me your hardware requirements) and provision multiple NIC and set up the various networks on the compute VMS.. 

For example, if we have 3 nics on the PowerKVM hosts
1.  the 10.network used to provision
2. The 50.network for the mgmt VLAN , verify by lan print 1 to a active BMC 
3. The "data" network , verify by having multiple compute nodes ping each other after the "data" network is set up, for exampl, on a 192.168.X.X with 255.255.255.0 subnet.

**Comment by tingtli** [comment]
@whowutwut I create a task to trace this request.
@neo954 Please consider the test cases when you write the test cases for the new confignics and getadpater code

**Comment by immarvin** [comment]
hi @tingtli @hu-weihua , any update on this?

**Comment by hu-weihua** [comment]
Open a task for this requirement. Close this issue and added ``test:testcase_requested`` label. If test case will be added, will mark this issue by ``testcase_added`` label.
