### ISSUE TITLE
Missing doc label "confignics_label" from file domain_name_resolution.rst

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#1202]
File docs/source/advanced/domain_name_resolution/domain_name_resolution.rst on line 473 makes a link to label "confignics_label". But there is no such label in xCAT documentation.

**Comment by junxiawang** [comment]
@daniceexi @gurevichmark @immarvin  
could not find nics introduce in our new doc and will talk to yangsong later to modify this document next spring.

**Comment by whowutwut** [comment]
The links are not really that effective because we start get a lot of those duplicate label messages.  Maybe should just put the document in-place

**Comment by immarvin** [comment]
move to next release

**Comment by gurevichmark** [comment]
Verified. Fixed.
