### ISSUE TITLE
[Customer] /xcatpost not updated

### ISSUE THREAD

**Issue by dombrowa** [xcat2/xcat-core#1204]
I have found the following problem.
 When running a postscript which is supposed to source a file containing bash functions it fails on some nodes
fstgb019: ./custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox: line 27: source: ./custom/fstgb-rhel7.2-sf-c/postscripts.test/functions: is a directory
For unknown reason some nodes show a directory functions instead of a file named functions - This caused failure to execute the postscript.

```
[root@dccxcat2 ~]# xdsh fstgb-compute ls -ald /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb009: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb007: drwxr-xr-x 2 root root 6 Dec 11 16:34 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb008: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb001: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb019: drwxr-xr-x 2 root root 6 Dec 11 16:38 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb010: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb015: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb011: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb012: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb018: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb006: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb013: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb016: drwxr-xr-x 2 root root 6 Dec 11 16:34 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb014: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb017: drwxr-xr-x 2 root root 25 Dec 11 16:34 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb003: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb002: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb004: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb025: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb022: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb023: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb005: -rwxr-xr-x 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb024: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb026: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgbfen1: drwxr-xr-x 2 root root 6 Dec 11 16:35 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
fstgb020: -rwxr-xr-x. 1 root root 1768 Dec 12 08:26 /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions
```
I do not know if any admin ever created a directory instead of a file leading to this in the first place
Apparently the filesystem under /xcatpost on the nodes is not updated to match what is on the xcat server under /install 
Also postscripts which are removed from the /install are not removed from /xcatpost and could be executed

**Comment by whowutwut** [comment]
@dombrowa what version of xCAT is this on? 2.11.1? 2.12?

**Comment by dombrowa** [comment]
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)

**Comment by daniceexi** [comment]
* ``xcatpost`` will be updated for each run of ``updatenode`` command. You can check the httpd log on xCAT MN to see whether the files in the MN:/isntall/postscript have been downloaded to the CN:/xcatpost.
* How about manually run the ``./custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox`` on the CN?

**Comment by dombrowa** [comment]
xcat updates new files but it does not recognize if the file system has changed. I manually created a false dir:

[root@dccxcat2 ~]# xdsh fstgb023 ls -al /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test
fstgb023: total 44
fstgb023: drwxr-xr-x  2 root root 4096 May 24 20:59 .
fstgb023: drwxr-xr-x. 5 root root 4096 May 24 20:59 ..
fstgb023: -rwxr-xr-x  1 root root 1768 Dec 12 08:26 functions
fstgb023: -rwxr-xr-x  1 root root 2661 May  4 16:33 install-cuda8
fstgb023: -rwxr-xr-x  1 root root 1972 Dec 12 07:46 install-essl
fstgb023: -rwxr-xr-x  1 root root 1649 Apr 27 14:27 install-ibm-xlc
fstgb023: -rwxr-xr-x  1 root root 1666 Apr 27 14:46 install-ibm-xlf
fstgb023: -rwxr-xr-x  1 root root 2158 Apr 21 11:08 install-pgi
fstgb023: -rwxr-xr-x  1 root root 7361 Jan 18 17:52 mount-nvme
fstgb023: -rwxr-xr-x  1 root root 2660 May 24 15:15 update-mellanox

# Removing the file
[root@dccxcat2 ~]# xdsh fstgb023 rm  /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions

# Creating a dir instead of a file
[root@dccxcat2 ~]# xdsh fstgb023 mkdir /xcatpost/custom/fstgb-rhel7.2-sf-c/postscripts.test/functions

# running updatenode again
[root@dccxcat2 ~]# updatenode fstgb023 --scripts=custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox
fstgb023: xcatdsklspost: downloaded postscripts successfully
fstgb023: Tue May 24 21:00:29 EDT 2016 Running postscript: custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox
fstgb023: ./custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox: line 27: .: ./custom/fstgb-rhel7.2-sf-c/postscripts.test/functions: is a directory
fstgb023: Postscript: custom/fstgb-rhel7.2-sf-c/postscripts.test/update-mellanox exited with code 1
fstgb023: Running of postscripts has completed.

That said update does work but does not reflect a sync between the MN and the CN.  A smart sync should exit prematurely detecting that the CN is out of sync and may not be updated correctly to match the actual postscript structure on the MN

Manually running is surely always an option : ssh CN, mount -t nfs MN:/install /install ; execute /install/postscripts/... but really the intention.

**Comment by daniceexi** [comment]
@dombrowa So the problem was xCAT ``updatenode`` command does not copy all the files from /install/postscript by force. We need figure out a way to ensure the sync of /xcatpost dir.

**Comment by dombrowa** [comment]
@daniceexi : I think it is more complicated than that. updatenode seems to copy all files (good) but does not complain about invalid directory structure on the CN versus the MN

Shorter example:
if 'b' is a directory at some point but later becomes a file
/install/postcript/custom/a/b   (old: directory    newly becamea : file)

 the CN's dir structure looks like this
/xcatpost/custom/b/b.1
/xcatpost/custom/b/b.2
Old: b was retrieved/synced as directory and remains a dir
I assume wget tried to get the file b and sees that the target is not a file but a dir and places teh file b, b1. , b2. into dir b

I can see that this looks like a user inflicted problem but the fact remains that updatenode does not create an identical copy of what the MN contains - so the scripts get out of sync. At least in my case it was caught as a failure since directory b could not be sourced  as a script file

**Comment by daniceexi** [comment]
@dombrowa Yes, got it. So remove the whole dir ``/xcatpost`` before wget it should work.

**Comment by whowutwut** [comment]
Going to close this issue as a code change was delivered with xCAT 2.12.1 release.  @dombrowa, feel free to re-open if you see issues with the new code.
