### ISSUE TITLE
[Customer]Error when provisioning centos 7.1

### ISSUE THREAD

**Issue by mavscjb** [xcat2/xcat-core#1212]
When provisioning centos7.1, the os will create many repos under "/etc/yum.repos.d/" as follows:
CentOS-Base.repo  CentOS-CR.repo  CentOS-Debuginfo.repo  CentOS-fasttrack.repo  CentOS-Sources.repo  CentOS-Vault.repo.
These repos are created by the "centos-release" package.

If the CN cannot connect to the internet, the postscript ospkg will failed.
I think we should update the ospkg script to disable the centos repos.

**Comment by daniceexi** [comment]
From xCAT's perspective, it cannot easily make decision whether user would like to keep these repos or not. If you don't like it, you can add a postscript to disable them by yourself.

**Comment by robin2008** [comment]
@daniceexi 
I agree that it's user choice to enable/disable the default CentOS repo, but I would suggest to make the 'ospkgs' could control it (via options, parameters or plugins).  As it handle the OS repo creation and OS packages installation.

**Comment by daniceexi** [comment]
discussed with @chudegao that ``ospkgs`` postscript is designed to handle the xcat related repos, it should not be used to change the OS shipped repo. 
User should make an individual postscript to customize the OS shipped repo.

**Comment by arif-ali** [comment]
You could have something below in a postscript, this is what I have been doing

```
yum-config-manager --disable base,updates
```

**Comment by whowutwut** [comment]
Just some explanation about the close... 

@arif-ali  Thanks for the tip, @mavscjb  can you give that suggestion a try?
