### ISSUE TITLE
[fvt]2.12.1 switchdiscover -s snmp could not use port 161 by nmap way on rh env

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1252]
env:rh
build:latest build lsdef - Version 2.12.1 (git commit 2794ca51b4165ccd1353fc9f557b6f94974c6239, built Thu Jun  2 09:30:41 EDT 2016)
How to reproduce:
```
[root@c910f04x27v02 result]# switchdiscover  --range 10.5.24.1
Discovering switches using nmap for 10.5.24.1. It may take long time...
ip          	name                	vendor                                            	mac         
------------	------------        	------------                                      	------------
10.5.24.1  [root@c910f04x27v02 result]# switchdiscover  --range 10.5.24.1 -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1 | grep 'open port 161' 
 No switch found 
 	switch-10-5-24-1    	Juniper Networks                                  	5C:5E:AB:64:CA:7F
--------------------------------------------->
Questions:
 1) I do not know why snmp discover using nmap way
 2) I do not think all env could use port 161
```

**Comment by cxhong** [comment]
1) we used nmap for snmp discover to better parse the ip range.  
2) port 161 has to be open to allow snmpwalk command to communicate with switch
``````
# snmpwalk -Os -v1 -c public 10.5.24.1 1.3.6.1.2.1.1.1
Timeout: No Response from 10.5.24.1
````

**Comment by junxiawang** [comment]
@cxhong but I could get the switch using nmap but not snmp
 [root@c910f04x27v02 ~]#  switchdiscover  --range 10.5.24.1
Discovering switches using nmap for 10.5.24.1. It may take long time...
ip          	name                	vendor                                            	mac         
------------	------------        	------------                                      	------------
10.5.24.1   	switch-10-5-24-1    	Juniper Networks                                  	5C:5E:AB:64:CA:7F
[root@c910f04x27v02 ~]#

**Comment by cxhong** [comment]
switchdiscover command can't do anything if the device does not respond to SNMP queries for snmp based scan.  Any snmp command we sent out will return "Timeout" messages if snmp server is not enabled.

**Comment by daniceexi** [comment]
@cxhong That's ok to skip the switch if the snmp port is not opened. But we should make the message to be more reasonable instead of following:

~~~~
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.24.1 | grep 'open port 161' 
 No switch found 
~~~~

We may say: cannot find any device which enabled snmp port.

**Comment by cxhong** [comment]
Modified the message and will checked in PR #1244
