### ISSUE TITLE
xCAT man pages - auto creating to docs

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#126]
Creating an Issues that is the same as https://github.com/xcat2/xcat-doc/issues/21 since the docs have been moved here. 

@daniceexi @tingtli   I gave that Perl module a try , pod2rst..  It makes it easy to convert the existing pods to rst, but the formatting is not that great...  but it's quick and dirty. 

Take a look at this branch I have, I didn't issue a pull request because I'm not sure it's ready to be merged...  https://github.com/whowutwut/xcat-core/tree/pods

 It does add a TON of new pages to the docs

**Comment by daniceexi** [comment]
@whowutwut 
The new generated man page looks good for me! You said it's 'dirty', is there anything which is not good that I did not aware?

Two comments:
* Where to store the <manpage>.rst files. Since <manpage>.rst files are converted from <manpage>.pod files, <manpage>.rst files are duplicated data of <manpage>.pod. But we have to have the .rst files for RTD to load. Looks like we have not good way to avoid this duplicate. 
* When to update the <manpage>.rst files. I think we can make the .rst files when run **buildcore.sh PROMOTE=1** . Do we still need to run the builddoc manually on build server?

**Comment by whowutwut** [comment]
@daniceexi  Just an expression, maybe should not use "dirty" :-)  Just a quick way to convert pods to rst.  This is probably the way to go since it would be far too much work to re-write.  I think I did see some typos in the pods that would need to be fixed but maybe should fix it to test out some automated way to update the docs... 

Regarding your 2  comments, I agree..  

* We have duplicate code
* We may need to indicate that the man pages are "automatically generated" so those "editing on github" will have their changes replaced the next time we refresh
* How do we commit the changes when we make changes to the pods? We can run the script in the build, but would need someone to push the changes to the code for the docs..

Do we consider the other way around.. put the files in RST in the various components.  Create symlinks to the docs/guides../man/ .  This would require us to redo the man page packaging ... 

Another TODO is to get the pod2rst into out build? Is that just something we have a requirement on the build machine to install and provide?

**Comment by daniceexi** [comment]
@whowutwut 
An easier way is to just mentain the <manpage>.rst file and use .rst to genereate manpage. But looks like the .rst file for manpage is not easy to edit. So I prefer to keep .pod file.

For how to automate the manpage update, We can use the builddoc (which calls pod2rst) to convert .pod to .rst and auto check in the .rst to repository.

Maybe we can try to make a .rst file for manpage to see how difficute it is to make one from scratch.  I am afraid the converted one was added some unnecessary format syntax.

**Comment by whowutwut** [comment]
Yea, I tried to make a rst file for a manpage and it's too much work...  I think the cross reference is not a big deal, maybe no one is even looking up man page on the web :)

**Comment by daniceexi** [comment]
OK, then let's make the builddoc to help us to convert .pod to .rst and push to xcat-core

**Comment by whowutwut** [comment]
Addressed this issue in pull request #307 and #309
