### ISSUE TITLE
[Customer] makedhcp -n cannot start or restart dhcpd on ubuntu MN

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1264]
The ``makedhcp -n`` should restart the dhcpd on Ubuntu MN to make the change take effect.  Could we confirm this function works well?

**Comment by wwzhubj** [comment]
I added some more details for recalling: 
step 1. I changed the "dhcpinterfaces" in site table from "eth0, eth1" to "eth1". 
step 2. ran "makedhcp -n", here I didn't get any failed message. all I see is the command run successfully. 
step 3. ps -ef|grep dhcpd , I saw
dhcpd -user dhcpd -group dhcpd -f -q -4 -pf /run/dhcp-server/dhcpd.pid -cf /etc/dhcp/dhcpd.conf eth1 eth0
which means the " makedhcp -n " did not  change the dhcpinterfaces to "eth1".

**Comment by daniceexi** [comment]
Please be aware that in @wwzhubj 's env that even  the command ``/etc/init.d/isc-dhcp-server stop`` could not stop the dhcpd process.

**Comment by daniceexi** [comment]
@wwzhubj this issue cannot be recreated locally. 
As I mentioned before that when the issue happened on @wwzhubj 's env, that ``/etc/init.d/isc-dhcp-server stop`` even did not work. So I think the problem was caused by the dhcp-server itself.

**Comment by daniceexi** [comment]
move to next release to see whether we could recreate it.

**Comment by immarvin** [comment]
close this issue. please open it when recreate
