### ISSUE TITLE
Instructions to migrate an xCat Management node to new hardware

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#1267]
Our existing management node is starting to suffer from a hardware issue. As of now the problem is under control, but we would like to migrate the xCAT service to a new server before we start to face problems of a more permanent nature from the existing server.

I looked at the old documentation, but could not find anything that might point me in the right direction. Is it possible to get documentation about migrating the `xCAT` service from one node to another in such a way the the new management node maintains the same identity as the old one?

**Comment by daniceexi** [comment]
@samveen 

Following is a procedure. I did not really try that, please give me a feedback if you encounter any problem

1. Prepare the new backup server; ( It should have the same IP and hostname as the current MN)
2. Install xCAT on the backup server;
3. backup the xCAT DB from current MN:

    dumpxCATdb -p /tmp/xcatdb
    scp -r /tmp/xcatdb backup_mn:/tmp

4. restore DB on backup MN

    restorexCATdb -p /tmp/xcatdb 

5. copy directories from current MN to backup MN

    /etc/xcat
    /etc/hosts
    /etc/ssh
    /root/.xcat
    /root/.ssh
    /tftpboot
    /install

6. Update xCAT configurations

    makehosts
    makedns -n
    makeconservercf
    makedhcp -n
    makedhcp -a

**Comment by samveen** [comment]
@daniceexi I will try this over the week and let you know if it works. I'll also see if I can create a barebones doc for it (and submit a merge request).

**Comment by samveen** [comment]
@daniceexi This didn't work exactly as expected. There were a few minor issues, which we bypassed by migrating the server via rsync after shutting down all services. Things were complicated a little bit by the fact that we use mysql as our DB backend (but not much). I expect I'll have to dig into the xcat rpm `%post` scripts to figure out the minor details that I missed.

**Comment by zet809** [comment]
1. verify the steps for manually MN migration
2. update document on RTD

**Comment by bybai** [comment]
The sourceforge doc: https://sourceforge.net/p/xcat/wiki/XCAT_Documentation/

**Comment by bybai** [comment]
Hi @samveen , I added the doc pull request in #3646, could you take a look at it, and any advice is welcome.

**Comment by jeyarajsiddhu** [comment]
Hi Everyone,
I have installed xcat cluster (Version 2.16) on Centos 7.7 . but how to install the management node through PXE network..
 Please help anyone..

Regards,
Jeyaraj.M
