### ISSUE TITLE
compute node gets maste IP failed after reboot

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1268]
This issue is the compute node can not get the right master IP after rebooting, the root cause is "/opt/xcat/lib/perl/xCAT/Template.pm" master will firstly get the IP from node attribute, the second order is from OS ifconfig(there are two provisioning IP with one Ethernet, one is the virtual IP), the last order is from the table "site". 
The result is the compute node did not get the IP from "site" and gave the wrong IP from OS ifconfig.

**Comment by fenggaobj** [comment]
This issue is fixed by YangSong, and the code is submitted into 2.12 xcat-pcm.
Thanks

**Comment by immarvin** [comment]
the issue is fixed in the PR https://github.com/xcat2/xcat-core/pull/1273
