### ISSUE TITLE
Ran discovery without setting host information correctly

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1270]
Switch based discovery, I successfully setup a garrison node. 
When I ran the nodeset command and got the error:
[root@c712ems4 TRY3]# nodeset c712f7n04-pvt  osimage=test
c712f7n04-pvt: install rhels7.2-ppc64le-compute
Error: The c712f4n04-pvt can not be resolved

I found I did not have the /etc/hosts entry for the OS' private network. Added /etc/hosts entry and makedns, makedhcp, nodeset, reboot.

I then found the node booting into genesis and found the lease entry:
host c712f7n04-pvt-noip70e284140a5f {
  dynamic;
  hardware ethernet 70:e2:84:14:0a:5f;
        supersede server.allow-booting = 00;
}

Found the mac address from discovery had _NOIP_
mac=70:e2:84:14:0a:5f!_NOIP_

I removed the "!_NOIP_" from the mac and reran makedhcp/nodeset, the node installed.

I realize the problem was the result of an admin error, however how to recover was not clear. Is fixing resolution and changing the mac the best solution?

**Comment by daniceexi** [comment]
@markprez if you know the correct mac address, remove the ``!NOIP`` from the mac is OK to fix this.
Another way is to fix the configuration and do the discovery again.

xCAT team also is working on to tool which can be used to check the validity of predefined node.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/3995
