### ISSUE TITLE
nicips.enP5p7s0f1 can not removed from node definition. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1276]
Issue: After I set the nicips.enP5p7s0f1 to empty, nicips.enP5p7s0f1 is still there. 
chdef c712f7n07-pvt nicips.enP5p7s0f1=

[root@c712ems4 ~]# lsdef c712f7n07-pvt -i nicips
Object name: c712f7n07-pvt
    nicips.enP5p7s0f1=9.114.75.37

My env: 

[root@c712ems4 ~]# uname -a
Linux c712ems4 3.10.0-327.13.1.el7.openpower3.ppc64le #1 SMP Thu Apr 28 13:22:48 EDT 2016 ppc64le ppc64le ppc64le GNU/Linux
[root@c712ems4 ~]#

[root@c712ems4 ~]# lsxcatd -v
Version 2.12 (git commit 5df15f39216da9c64759d61b19fbabad1674727d, built Wed May 18 07:30:41 EDT 2016)

**Comment by wwzhubj** [comment]
I also  found nicips.ib0, nicnetworks.ib0, nictypes.ib0 can not be removed when I set them  to empty using chdef. 
But for ib1 , it can be removed.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1311

**Comment by immarvin** [comment]
ping @tingtli , a test case should be added on this bug

**Comment by wwzhubj** [comment]
I have verified it in below version
[root@c712ems4 build_input]# lsxcatd -v
Version 2.12.1 (git commit 0919bf649d99fc957236dbb42cfa3afc087ddad2, built Thu Jul  7 06:18:01 EDT 2016)
