### ISSUE TITLE
confignics -s failed, make the computer node can not ping 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1304]
I use updatenode  node "confignics -s" to set my installnic to static mode. But updatenode hanged and the computer node can not ping and ssh. 
when rcons it, we see in the config file for installnic, the netmask is 0.0.0.0, which is wrong. 

In my env:  route table is : 
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         v2199gw9-114-39 0.0.0.0         UG    0      0        0 eth0
9.114.39.0      *               255.255.255.0   U     0      0        0 eth0
10.128.128.0    *               255.255.255.0   U     0      0        0 eth1
link-local      *               255.255.0.0     U     1000   0        0 eth1

but in xCAT postscript configeth  476 line, will set the "0.0.0.0" as the netmask into network config file. 
str_inst_mask=`route |grep  ${inst_ip_pre}|awk '{print $3}'|head -1`

The issue can be fixed by change it like below:
str_inst_mask=`route |grep -E ^${inst_ip_pre}|awk '{print $3}'|head -1`

**Comment by daniceexi** [comment]
In @wwzhubj 's env, the  ``${inst_ip_pre} = 9.114.39.0``, when run the ``route |grep ${inst_ip_pre}|awk '{print $3}'|head -1``, the first line ``default v2199gw9-114-39 0.0.0.0 UG 0 0 0 eth0`` is matched, then it get the incorrect value. I suggest to use the ``^`` to match the route entry from beginning.

**Comment by daniceexi** [comment]
The fix has been verified by @wwzhubj, so close it.
