### ISSUE TITLE
[customer] lsdef and Rest API issues with regex on nicks

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#1308]
Just have seen an issue with the nickips, when we have regex

```
"virt","|eno1!10.28.9.($1+10),ipmi0!10.28.25.($1+10),bond0!10.28.41.($1+10)|","bond0!-10g",,,,,,"bond0!MTU=9000","bond0!ens1f0|ens1f1",,,
```

if you look at the outputs below, we have |eno1 as the interface name, which doesn't quite work out. Not sure the best resolution to this though. But some idea on resolving this would be great

```
[root@admin001 ~]# lsdef -t group virt
Object name: virt
    ip=|10.28.9.($1+10)|
    members=virt000,virt001,virt002,virt003,virt004,virt005,virt006,virt007
    nicdevices.bond0=ens1f0|ens1f1
    nicextraparams.bond0=MTU=9000
    nichostnamesuffixes.bond0=-10g
    nicips.|eno1=10.28.9.($1+10)
    nicips.ipmi0=10.28.25.($1+10)
    nicips.bond0=10.28.41.($1+10)|
    postbootscripts=configbond bond0 ens1f0@ens1f1,ocf/setup_extnw -n virt_10g
    provmethod=base-image.virt
[root@admin001 ~]# curl -k "https://admin001.<snip>/xcatws/groups/virt?userName=root&userPW=<snip>&pretty=1"
{
   "virt":{
      "provmethod":"base-image.virt",
      "nicips.bond0":"10.28.41.($1+10)|",
      "ip":"|10.28.9.($1+10)|",
      "members":"virt000,virt001,virt002,virt003,virt004,virt005,virt006,virt007",
      "nicextraparams.bond0":"MTU=9000",
      "nicips.ipmi0":"10.28.25.($1+10)",
      "nicips.|eno1":"10.28.9.($1+10)",
      "postbootscripts":"configbond bond0 ens1f0@ens1f1,ocf/setup_extnw -n virt_10g",
      "nicdevices.bond0":"ens1f0|ens1f1",
      "nichostnamesuffixes.bond0":"-10g"
   }
}
```

**Comment by daniceexi** [comment]
@arif-ali 
One thing to confirm is that the function works fine, but the ``lsdef/chdef`` have problem to list/change the group for nics table, am I right?

A potential solution is:
1. In the ``lsdef``, remove the ``^|`` and ``|$`` before displaying
2. In the ``chdef/mkdef``, user should set as following. Inside xCAT, we put all of them together as ``|eno1!10.28.9.($1+10),ipmi0!10.28.25.($1+10),bond0!10.28.41.($1+10)|`` and set it in DB.
~~~~
"nicips.ipmi0":"|10.28.25.($1+10)|",
"nicips.eno1":"|10.28.9.($1+10)|",
"nicips.bond0":"|10.28.41.($1+10)|",
~~~~

**Comment by arif-ali** [comment]
yes, functionally it is working ok

It's how it is being displayed that is the problem.

I am trying to use the data from the Rest API to import data somewhere else, fortunately, this shouldn't cause me major issues, as I am not really using this parameter for network. But it was something I noticed

**Comment by daniceexi** [comment]
So now you don't care about the ``chdef/mkdef`` so far, right? If just handle the ``lsdef``, it will be easier.

**Comment by arif-ali** [comment]
That's true, I don't really care about `chdef/mkdef`, as I set most of settings using `tabedit`. So, yes, all I need is the fix for `lsdef`

**Comment by daniceexi** [comment]
@arif-ali We are planning to release 2.12.1 at July 8, I'd like to close it now. If you it still has problem, please reopen it.
