### ISSUE TITLE
[FVT]Please update xcattest man page

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1310]
Two issues:
1.  for -b option, it should be shown that, the bundle files should be listed in /opt/xcat/share/xcat/tools/autotest/bundle, it is the defined bundle folder.

```

OPTIONS
       -b case bundle list
                 Comma separated list of test cases bundle files, each test cases bundle can
                 contain multiple lines and each line for one test case name.
```
1. in EXAMPLES, there are two error examples: 

```
EXAMPLES
       1.  To run all  test cases related command rpower:

             xcattest -c /tmp/config -c rpower

       2.  To run customized bundle:

             xcattest -l  > /tmp/custom.bundle
             Modify custom.bundle
             xcattest -b custom.bundle
```

2.1 for example 1, change the first "-c" to be "-f"
2.2 for example 2, change the bundle folder "/tmp" to be "/opt/xcat/share/xcat/tools/autotest/bundle"

```
EXAMPLES
       1.  To run all  test cases related command rpower:

             xcattest -f /tmp/config -c rpower

       2.  To run customized bundle:

             xcattest -l  >  /opt/xcat/share/xcat/tools/autotest/bundle/custom.bundle
             Modify custom.bundle to list cases names only
             xcattest -b custom.bundle
```

**Comment by caomengmeng** [comment]
Fixed now

**Comment by whowutwut** [comment]
@caomengmeng , from the comment in #1626, you need to modify the .pod file.  Going to re-open until you verify if we need another pull request...

**Comment by caomengmeng** [comment]
close this issue, docs and man page are both updated
