### ISSUE TITLE
On centos7.2, remoteshell failed as default xcat postinstallscript

### ISSUE THREAD

**Issue by chudegao** [xcat2/xcat-core#1312]
PCM use remoteshell as default xcat postinstallscript to make user can ssh CN from MN without password. But it does not work in centos7.2. There are some error message in xcat.log

[root@ip182mn ~]# tabdump postscripts
#node,postscripts,postbootscripts,comments,disable
"service","servicenode",,,
"xcatdefaults","syslog,remoteshell,syncfiles","syncfiles,setuppcm,ospkgs,otherpkgs,mountnfs",,

[root@ip182mn ~]# ssh pcmstdcn1
root@pcmstdcn1's password:
Last login: Wed Jun 15 06:03:33 2016 from pcmstdcn0.private.dns.zone
[root@pcmstdcn1 ~]# vi /var/log/xcat/xcat.log
Wed Jun 15 02:55:19 EDT 2016 Running postscript: syslog
Running in chroot, ignoring request.
Wed Jun 15 02:55:19 EDT 2016 postscript syslog return with 0
Wed Jun 15 02:55:19 EDT 2016 Running postscript: remoteshell

Running in chroot, ignoring request.
Could not load host key: /etc/ssh/ssh_host_ed25519_key^M
Wed Jun 15 02:55:22 EDT 2016 postscript remoteshell return with 0

MN's root public rsa key is not in CN's authorized_keys. It's a different key.
MN:
[root@ip182mn ~]# cat .ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6PqZ45ljdzD/uXkrTriMd9iQhwFnVWa6FL6EJRjTd+WTjycMTDKwkFhKqjOFtcz4+Dzq7uOAQGtO9L77k0BVnPMoODs+aW12RB2oZZBury12WqdCmOy7fP/FgMz8cvZI57Zh34xjrUTKYlDVmCD/LTnsMyrJcVErCmc/yCcS2YPD1WCds/rNj7tZgkzWvA+YUWH+NvcVNLy+5iOzonHWXC02HG28O9UENSaC8P1JcbIpEC++ehhIY7PfkyT9n4IdPSgZstAP8Th14E0AFoTJWgCPvgx5e+qFU389Yi1GR5WWlmalk3PspYz5uxqsdM3qG+l/mWKUb3uQ9MlacSxut root@ip182mn
[root@ip182mn ~]#

CN:
[root@pcmstdcn1 ~]# cat .ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHmdKLH7XY8OgIo33/GDBBskh6V9xyT9/wAWSngZhGWyQzx+w4FxGskaylbjXXNkhjjNMMAmVGyVd1EvdbP1MEx1Q2t2OqMwVpOMY8mCbm+9Gv9RIR2ch34JbdU4Rq5yYRkzMCWaQ6sJj0DhiRAwifEwy00QKRYf1b7nONnc/kTUuAfIrdwMGzcZaNTKZdLtjIxiich0rZGqEpIq7l21xKtt/B2a064OBXwO2x4JcAZKrj17FtJN9GHAFj/Ly5aAD1HHoy9RqdvKyxG506U1J2mKRdE057hn2yxrMHbkgppvhg6WDz0zJzEn3adh/QmkUqnzgpRckQK3HykjVod5u9 root@ip182mn
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBYEQxL51haAIpupVAYRate7zYwo1pHrAOtOINMWPjuy03hLZhtDH1V7xd1vfYOacigFNBWJ15gbQoAY/rrXo9fTggte2FXt5qApl/09Gp5sipxF06TLC0N+RwL+Po3j9HupKTSrEZ3eDrFAak/MVYL+J2CNS7IZRMl7CCqv4Xk2hOdRd7eifXGbSVg3EyfByd8TyVtPFQ7Gk7mFGgnAgl+bHlmxGaC57IqBDUI+T85X4W5ByodUbbdQJJS8D8Qg+o05re3S5Fb+crHvsgKgFichRf9gKVkx4nIpMc81aQ5uWCvgmxPd+GyZBdcIEdnkaJk9r9+/5JTHSfgRImyyJ3 root@ip182mn
[root@pcmstdcn1 ~]#

Run updatenode <node> -k. Paswordless SSH CN works. The script should only does not work at OS installing stage according to the message in xcat.log:
Wed Jun 15 02:55:19 EDT 2016 Running postscript: remoteshell

Running in chroot, ignoring request.
Could not load host key: /etc/ssh/ssh_host_ed25519_key^M

**Comment by daniceexi** [comment]
@chudegao 
On your MN:
#cat /root/.ssh/id_rsa.pub
#cat /install/postscripts/_ssh/authorized_keys

They should have same content.

**Comment by chudegao** [comment]
Yes, they do have same content.  But after provision CN(remoteshell is default postinstall script), CN's authorized_keys is different with this one. Run updatenode -k, the authorized_keys will be same with MN.   I think maybe 'remoteshell' script hit some error in os installing stage. See the message in xcat.log on CN:
Running in chroot, ignoring request.
Could not load host key: /etc/ssh/ssh_host_ed25519_key^M

**Comment by daniceexi** [comment]
@chudegao 
Could you also check the content in ``CN:/xcatpost/_ssh/authorized_keys`` has the same content?

I do like you can recreate this CN and check the keys again. I'd like to login the CN to take a look.

**Comment by chudegao** [comment]
CN has different key with MN.

MN:
[root@ip182mn ~]# cat /root/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6PqZ45ljdzD/uXkrTriMd9iQhwFnVWa6FL6EJRjTd+WTjycMTDKwkFhKqjOFtcz4+Dzq7uOAQGtO9L77k0BVnPMoODs+aW12RB2oZZBury12WqdCmOy7fP/FgMz8cvZI57Zh34xjrUTKYlDVmCD/LTnsMyrJcVErCmc/yCcS2YPD1WCds/rNj7tZgkzWvA+YUWH+NvcVNLy+5iOzonHWXC02HG28O9UENSaC8P1JcbIpEC++ehhIY7PfkyT9n4IdPSgZstAP8Th14E0AFoTJWgCPvgx5e+qFU389Yi1GR5WWlmalk3PspYz5uxqsdM3qG+l/mWKUb3uQ9MlacSxut root@ip182mn
[root@ip182mn ~]#
[root@ip182mn ~]# cat /install/postscripts/_ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6PqZ45ljdzD/uXkrTriMd9iQhwFnVWa6FL6EJRjTd+WTjycMTDKwkFhKqjOFtcz4+Dzq7uOAQGtO9L77k0BVnPMoODs+aW12RB2oZZBury12WqdCmOy7fP/FgMz8cvZI57Zh34xjrUTKYlDVmCD/LTnsMyrJcVErCmc/yCcS2YPD1WCds/rNj7tZgkzWvA+YUWH+NvcVNLy+5iOzonHWXC02HG28O9UENSaC8P1JcbIpEC++ehhIY7PfkyT9n4IdPSgZstAP8Th14E0AFoTJWgCPvgx5e+qFU389Yi1GR5WWlmalk3PspYz5uxqsdM3qG+l/mWKUb3uQ9MlacSxut root@ip182mn
[root@ip182mn ~]# 

CN:
[root@pcmstdcn1 ~]# cat /xcatpost/_ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHmdKLH7XY8OgIo33/GDBBskh6V9xyT9/wAWSngZhGWyQzx+w4FxGskaylbjXXNkhjjNMMAmVGyVd1EvdbP1MEx1Q2t2OqMwVpOMY8mCbm+9Gv9RIR2ch34JbdU4Rq5yYRkzMCWaQ6sJj0DhiRAwifEwy00QKRYf1b7nONnc/kTUuAfIrdwMGzcZaNTKZdLtjIxiich0rZGqEpIq7l21xKtt/B2a064OBXwO2x4JcAZKrj17FtJN9GHAFj/Ly5aAD1HHoy9RqdvKyxG506U1J2mKRdE057hn2yxrMHbkgppvhg6WDz0zJzEn3adh/QmkUqnzgpRckQK3HykjVod5u9 root@ip182mn


I provide my env to Song. Song is investigating.

**Comment by gurevichmark** [comment]
@daniceexi Could this be at all related to issue #1168 ?

**Comment by daniceexi** [comment]
@gurevichmark I think the error message ``Could not load host key: /etc/ssh/ssh_host_ed25519_key`` came from the sshd when starting.

**Comment by chudegao** [comment]
PCM do some manual step in our env. It should be not xCAT issue.

**Comment by daniceexi** [comment]
confirmed with @chudegao, this issue caused by the environment configuration.
