### ISSUE TITLE
building xCAT docs produces "no theme named 'sphinx_rtd_theme' found"  

### ISSUE THREAD

**Issue by ChristopherWalker** [xcat2/xcat-core#1314]
Building the xCAT docs on my (Debian) laptop, I get the following error:

$ make singlehtml
sphinx-build -b singlehtml -d build/doctrees   source build/singlehtml
Running Sphinx v1.2.3
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
Makefile:65: recipe for target 'singlehtml' failed
make: *** [singlehtml] Error 1

Googling the error reveals:
https://github.com/sphinx-doc/sphinx/issues/1636

And applying the following patch appears to fix it for me, but I don't know enough about sphinx to know if that's the right solution:
```
diff --git a/docs/source/conf.py b/docs/source/conf.py
index b5b6350..5d2ab81 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -151,7 +151,10 @@ if on_rtd:
     html_theme = 'default'
 else:
     # some of the popular themes: alabaster, sphinx_rtd_theme, classic, nature
+    import sphinx_rtd_theme
     html_theme = 'sphinx_rtd_theme'
+    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
+
 
 # Theme options are theme-specific and customize the look and feel of a theme
 # further.  For a list of options available for each theme, see the
```

**Comment by daniceexi** [comment]
@ChristopherWalker Thanks for the information. 
@gurevichmark Could you take a look of this issue?

**Comment by gurevichmark** [comment]
@ChristopherWalker In our doc build environment we use Sphinx v1.3.1
Any chance you can update your system to that version and see if the problem goes away ?

```
[gurevich@c910loginx01 docs]$ make singlehtml
sphinx-build -b singlehtml -d build/doctrees   source build/singlehtml
Running Sphinx v1.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [singlehtml]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
assembling single document... 
```

**Comment by gurevichmark** [comment]
Updated README file for documentation building using pull request #1525 
Added instructions to update sphinx to a newer version and how to install the ReadTheDocs theme file.
