### ISSUE TITLE
after pessl kitcomponents are removed from osimage, the INCLUDE env file for pessl are not cleaned up. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1327]
Issue: After pessl kitcomponents are removed from osimage, the INCLUDE files related with pessl are not cleaned up. 

<[root@c712ems4 pessl]# rmkitcomp -i rh72diskfull1621 pessl-loginnode-5.3.0-0-rhels-7.2-ppc64le,pessl-license-5.3.0-0-rhels-7.2-ppc64le
Removing kitcomponent pessl-loginnode-5.3.0-0-rhels-7.2-ppc64le from osimage rh72diskfull1621
Removing kitcomponent pessl-license-5.3.0-0-rhels-7.2-ppc64le from osimage rh72diskfull1621
kitcomponents pessl-loginnode-5.3.0-0-rhels-7.2-ppc64le,pessl-license-5.3.0-0-rhels-7.2-ppc64le were removed from osimage rh72diskfull1621 successfully

[root@c712ems4 pessl]# cat /install/osimages/rh72diskfull1621/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist
#INCLUDE:/install/kits/essl-5.5.0-0-ppc64le/other_files/essl-5.5.0-0-ppc64le_essl.env#
#INCLUDE:/install/kits/xlf-15.1.3-0-ppc64le/other_files/xlf-15.1.3-0-ppc64le_xlf.env#
#INCLUDE:/install/kits/xlc-13.1.3-0-ppc64le/other_files/xlc-13.1.3-0-ppc64le_xlc.env#
#INCLUDE:/install/kits/pessl-5.3.0-0-ppc64le/other_files/pessl-5.3.0-0-ppc64le_pessl.env#>

**Comment by wwzhubj** [comment]
[root@c712ems4 pessl]# lsxcatd -v
Version 2.12 (git commit 5df15f39216da9c64759d61b19fbabad1674727d, built Wed May 18 07:30:41 EDT 2016)

**Comment by bybai** [comment]
Hi @wwzhubj , I cannot reproduce it.

**Comment by wwzhubj** [comment]
How to recreate it: 
1. addkit pessl-5.2.0-0-ppc64le.tar.bz2  
2.

**Comment by wwzhubj** [comment]
2.addkitcomp -i test pessl-license-5.2.0-0-rhels-7.2-ppc64le,pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le -f
3.cat  /install/osimages/test/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist
will have 
#INCLUDE:/install/kits/pessl-5.2.0-0-ppc64le/other_files/pessl-5.2.0-0-ppc64le_pessl.env#
4. rmkit -f pessl-5.2.0-0-ppc64le.tar.bz2
5. cat  /install/osimages/test/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist
still have 
#INCLUDE:/install/kits/pessl-5.2.0-0-ppc64le/other_files/pessl-5.2.0-0-ppc64le_pessl.env#

**Comment by bybai** [comment]
When I use XCATBYPASS=1 before rmkitcomp, the issue is gone.
So xcatd cause the issue.

**Comment by wwzhubj** [comment]
I have verified it in below env: 
[root@c712ems4 build_input]# lsxcatd -v
Version 2.12.1 (git commit 0919bf649d99fc957236dbb42cfa3afc087ddad2, built Thu Jul  7 06:18:01 EDT 2016)
