### ISSUE TITLE
Need to define the size of the default block size

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1333]
When we deploy Diskless on PPC64LE, we found that the space is not enough.
But the same Diskless works well on X86_64 with the same size of memory.
Investigate it, we found that there are lots of small size file(maybe less than 1k).
and the default block size of the OS is 64k, which leads to the real size of these files 
much larger than they need. 

Could there be the variable or method to define the size of the default block size?

**Comment by neo954** [comment]
Based on the investigation on the Internet. The block size of the file system tmpfs is base on the memory page size. For Power System in OPAL mode, the default memory page size is 64KiB. I do not see any method to change the default page size. May need to do more investigation. Or maybe there is no way to do it at all.

**Comment by neo954** [comment]
This is not an xCAT related problem.

**Comment by neo954** [comment]
I will close this one.
