### ISSUE TITLE
[FVT]runcmdinstall hangs out of 8 hours when cn is not correctly configured.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1335]
xCAT 2.12.1 rhels6.8 
[root@c910f02c08p08 ~]# lsxcatd -v
Version 2.12.1 (git commit fddd78e1ec6a9d59bc921bef24e300e8d94f69e4, built Sun Jun 19 06:45:32 EDT 2016)
[root@c910f02c08p08 ~]# runcmdinstaller c910f02c08p10 "ls -al /tmp"
^C

**Comment by tingtli** [comment]
@immarvin  i think if runcmdinstall is not a command which is used by customer, we should remind customer and exit directly.
@junxiawang  I see we have a case for the runcmdinstaller, Let's discuss this test case and see if we need to put the command there.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1363

**Comment by tingtli** [comment]
With the daily regression result. It is fixed.
