### ISSUE TITLE
[FVT]:update test case Full_installation_flat_docker

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1336]
xCAT 2.12.1 ubuntu14.04.3  x86_64

RUN:if [[ "ubuntu14.04.4" =~ "ubuntu" ]];then ver=`cat /etc/*-release |grep "VERSION_ID"|  awk -F '"'  '{print $2}'| awk -F"." '{printf "%s%s\n",$1,$2}'` ; mkdir -p /install/custom/ubuntu$ver/ ;  chdef -t osimage -o --install-dockerhost otherpkglist="/install/custom/ubuntu$ver/ubuntu"$ver"_docker.pkglist"  pkglist="/install/custom/ubuntu$ver/ubuntu$ver.pkglist";fi

[if [[ "ubuntu14.04.4" =~ "ubuntu" ]];then ver=`cat /etc/*-release |grep "VERSION_ID"|  awk -F '"'  '{print $2}'| awk -F"." '{printf "%s%s\n",$1,$2}'` ; mkdir -p /install/custom/ubuntu$ver/ ;  chdef -t osimage -o --install-dockerhost otherpkglist="/install/custom/ubuntu$ver/ubuntu"$ver"_docker.pkglist"  pkglist="/install/custom/ubuntu$ver/ubuntu$ver.pkglist";fi] Running Time:1 sec
RETURN rc = 1
OUTPUT:
Error: Cannot set the attr='otherpkglist' attribute unless 'imagetype=linux'.
Error: Cannot set the attr='pkglist' attribute unless 'imagetype=linux'.
1 object definitions have been created or modified.
New object definitions '--install-dockerhost' have been created.
CHECK:rc == 0   [Failed]

@junxiawang   chdef -t osimage -o --install-dockerhost  is this correct? will you change the image install-dockerhost? I guess you will change the image ubuntu14.04.4-x86_64-install-dockerhost

**Comment by junxiawang** [comment]
root cause is the old issue on xcattest  __GETNODEATTR($$CN,os)__
could not get node attr :arch and os
I will modify this in testcase

**Comment by junxiawang** [comment]
@tingtli 
ref :https://github.com/xcat2/xcat-core/issues/1011

**Comment by tingtli** [comment]
@junxiawang 
chdef -t osimage -o __GETNODEATTR($$DOCKERHOST,os)__-__GETNODEATTR($$DOCKERHOST,arch)__-install-dockerhost

You should use 
chdef -t osimage -o __GETNODEATTR($$CN,os)__-__GETNODEATTR($$CN,arch)__-install-dockerhost

**Comment by tingtli** [comment]
According to the daily run result. I think this is fixed.
