### ISSUE TITLE
bmcdiscover using range is not working as expected

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1344]
For the bmcdiscover command, we allow a `--range` to be used:

```
--range   Specify one or more IP ranges acceptable to nmap.  \
          IP rance can be hostnames, IP addresses, networks, etc.  \
          A single IP address (10.1.2.3) or an IP range
```

However, running this to specify a range and IP address doesn't work as expected: 

1 Single IPs work

```
[root@fs1 discovery]# bmcdiscover --range  50.5.31.1
50.5.31.1,8335-GTB,100469A,,
[root@fs1 discovery]# bmcdiscover --range  192.168.5.165
192.168.5.165,8335-GTB,100464A,,
```

2 Using commas does not work 

```
[root@fs1 discovery]# bmcdiscover --range 192.168.5.165,50.5.31.1
Error: No bmc found.
```
3  Using space separated IP address does not return both BMCs

```
[root@fs1 discovery]# bmcdiscover --range 192.168.5.165 50.5.31.1
192.168.5.165,8335-GTB,100464A,,
[root@fs1 discovery]#
```

**Comment by pdlun92** [comment]
I've found that surrounding range in quotes will get better output, at least in cases 1 and 3.  For example:
```
[root@fs1 pat]# bmcdiscover --range "50.5.29.1"
50.5.29.1,8335-GTB,100464A,,
[root@fs1 pat]# bmcdiscover --range "50.5.31.1"
50.5.31.1,8335-GTB,100469A,,

[root@fs1 pat]# bmcdiscover --range "50.5.29.1 50.5.31.1"
50.5.29.1,8335-GTB,100464A,,
50.5.31.1,8335-GTB,100469A,,
```
case 2 however still does not produce desired output
```
[root@fs1 pat]# bmcdiscover --range "50.5.29.1,50.5.31.1"
Error: No bmc found.
```
Running the nmap call in `xCAT-server/lib/xcat/plugins/bmcdiscover.pm` directly from the command line, it appears that nmap itself does not support comma syntax
```
[root@fs1 pat]# nmap -sn -n 50.5.29.1,50.5.31.1 | grep -B1 up | grep "Nmap scan report" |cut -d ' ' -f5
Failed to resolve "50.5.29.1,50.5.31.1".
WARNING: No targets were specified, so 0 hosts scanned.
```
Is this ok? Or do we want to handle comma separated syntax?

**Comment by zet809** [comment]
@whowutwut @pdlun92 I think it is our code's responsibility to deal with the comma, and then pass them to nmap.

**Comment by whowutwut** [comment]
I also think we should explicitly mention in the man page to use quotes around the range. Even though the examples use quotes, I still missed that when trying to run the command.. :-)

**Comment by whowutwut** [comment]
Verified on the following build: 
```
Version 2.12.1 (git commit 777164c7dea2c13807f3f847ab6499c2a06f9849, \
built Wed Jun 29 06:45:46 EDT 2016)
```

Seems to cover the case where we are using the commas now, so that's good. The case where we have spaces without quotes I think is unsupported.  (Number 3 above) 

```
[root@fs1 discovery]# bmcdiscover --range 50.5.29.1,50.5.31.1
50.5.29.1,8335-GTB,100464A,,
50.5.31.1,8335-GTB,100469A,,
```
```
[root@fs1 discovery]# bmcdiscover --range "50.5.29.1 50.5.31.1"
50.5.29.1,8335-GTB,100464A,,
50.5.31.1,8335-GTB,100469A,,
```

Closing out issue
