### ISSUE TITLE
[FVT]"makedns -n" return value is also zero while there is an output error message 

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1347]
Test ENV： When there is an error message returned for ``makedns -n``, the return value is also zero just like it works well.
Please see details below:

```
RUN:makedns -n

[makedns -n] Running Time:0 sec
RETURN rc = 0
OUTPUT:
Error: Unsupported request
CHECK:rc == 0   [Pass]
```

**Comment by daniceexi** [comment]
@caomengmeng concerns why the return code is ``0`` even it fails.

**Comment by daniceexi** [comment]
Cannot recreate the issue easily. Will handle it in next release.

**Comment by caomengmeng** [comment]
Works well after that fixed till now, so close it
