### ISSUE TITLE
[FVT]No MN: /var/log/xcat/computes.log file generated on sles11.4 ppc64le, while xcatdebumode=1/2

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1353]
Description:
Using latest daily build on ppc64, MN is sles11.4 and CN is trying to be installed with rh7.2.
Set xcatdebugmode=1/2, then install CN with rh7.2, after CN is booted, no var/log/xcat/computes.log file generated 

Test ENV:
```
c910f02c01pxx:/var/log/xcat # lsxcatd -v
Version 2.12.1 (git commit fddd78e1ec6a9d59bc921bef24e300e8d94f69e4, built Sun Jun 19 06:45:32 EDT 2016)
c910f02c01pxx:/var/log/xcat # cat /etc/*release
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64"
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
SUSE Linux Enterprise Server 11 (ppc64)
VERSION = 11
PATCHLEVEL = 4
```
Files in MN /var/log/xcat folder:
```
c910f02c01pxx:/var/log/xcat # ls
autotest.log  commands.log  xcat.log

```

**Comment by neo954** [comment]
This feature is not supported. xCAT did not support ``/var/log/xcat/computes.log`` on SLES 11.4 currently.

**Comment by caomengmeng** [comment]
@neo954 if sles11.4 not supported @penguhyang, then please update https://github.com/xcat2/xcat-core/wiki/support%20new%20values%20for%20site.xcatdebugmode

**Comment by neo954** [comment]
@caomengmeng This is not related to the ``xcatdebugmode`` feature. The feature of ``xcatdebugmode`` just generate extra logs. On SLES 11.4, xCAT will not configure the log system to generate ``/var/log/xcat/computes.log``. But all the logs are still there. According to the configurations of the log system on SLES 11.4. It is ``syslog-ng``. xCAT just did not take effort on doing extra configuration for ``syslog-ng`` on SLES 11.

**Comment by caomengmeng** [comment]
@neo954, so that means the excepted sles11.4 logs for xcatdebugmode are written to syslog-ng, right?
If yes, the xcatdebugmode documentation should be updated to make it clearly, where the logs are, that is the point.

**Comment by penguhyang** [comment]
@caomengmeng xcatdebugmode can enable forwarding logs to mn. But xcatdebugmode attribute can't control whether logs can be written into ``computes.log`` file on MN. It's related to the logging configuration. @neo954 supports that.
I will update the xcatdebugmode documentation.
