### ISSUE TITLE
pkglist for CUDA8 requires grub2-tools

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1356]
When running genimage on base RH72 with CUDA8 repo we get the errors:
```
  Installing : 1:xorg-x11-drv-nvidia-361.62-1.el7.ppc64le                 41/58
/var/tmp/rpm-tmp.YOiQYC: line 8: grub2-mkconfig: command not found
error opening /etc/yaboot.conf for read: No such file or directory
ls: cannot access /boot/vmlinuz-*.el7.ppc64le*: No such file or directory
```
Adding grub2-tools to the pkglist fixed this issue.

**Comment by cxhong** [comment]
yeh, after we added grub2-tools to pkglist, the above message is fixed, but following issue is created:
````
/usr/sbin/grub2-probe: error: cannot find a device for / (is /dev mounted?).
error opening /boot/grub/grub.cfg for read: No such file or directory
`````
on our system, we had /boot/grub2/grub.cfg
````
# rpm -qf /boot/grub2/grub.cfg
grub2-2.02-0.29.el7.ppc64le
`````
so, even installed grub2  packages, those message will still show up.  

CUDA7.5 had same message during the genimage
````
/var/tmp/rpm-tmp.6hCJAI: line 8: grub2-mkconfig: command not found
error opening /etc/yaboot.conf for read: No such file or directory
`````
this message seems didn't cause anything, the image is generated successfully and diskless CUDA7.5 installation and verification worked fine.

**Comment by cxhong** [comment]
For cuda8 on rhel7.3,  addiing grub2 and grub2-tools to package list will get rid of the error messages on genimage.

**Comment by whowutwut** [comment]
Closing this issue, @markprez  please re-open or create another issue if the problem persists.
