### ISSUE TITLE
[FVT] Sort three tables in Jenkins report mail by arch or OS

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1359]
@neo954, please sort Report, and Failed Test Cases parts in Jenkins report mail by arch or OS just as the other parts to make them more readable.
For Top 50 Failed Test Cases table, please sort it by test case name to make a quick summary for the command level.
Thanks.

**Comment by neo954** [comment]
Okay, will do.

**Comment by neo954** [comment]
This issue is already solved by commit ``20f186e``. Please check the pull request #1278.

**Comment by whowutwut** [comment]
@caomengmeng  please verify and close out this issue so we can close the milestone.

**Comment by neo954** [comment]
Will close this one. @caomengmeng, please feel free to reopen this issue in case needed.
