### ISSUE TITLE
[FVT]Please update design doc for sles12.1 xcatdebugmode=2

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1367]
As failed to install sles12.1 according to https://github.com/xcat2/xcat-core/wiki/support-new-values-for-site.xcatdebugmode, and discussed with @penguhyang, this doc should be updated, so please update it, thanks.

**Comment by penguhyang** [comment]
@caomengmeng Thanks for review.
mini-design document for xcatdebugmode updated.
1. add diskless checkpoint.
2. add notes information.
https://github.com/xcat2/xcat-core/wiki/support-new-values-for-site.xcatdebugmode

**Comment by caomengmeng** [comment]
Reviewed and checkpoints are all added
