### ISSUE TITLE
[FVT] Failed to install MN or xCAT should be shown in report tables

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1376]
Can we collect failed issues on report table: Failed Test Cases 
For example, the install MN failed or xCAT failed?

Install MN failed email content:

```
======================================
  Test Result for Project sles11.4-ppc64-60
======================================

[sles11.4+ppc64]

         All time consumption: 0 hours 4 minutes 47 seconds

         Deploy MN result: install c910f02c01p13 failed
```

Install xCAT on MN failed email content:

```
======================================
  Test Result for Project rhels6.8-ppc64-32
======================================

[rhels6.8+ppc64]

         All time consumption: 0 hours 16 minutes 35 seconds

         Deploy MN result: install xcat on c910f02c08p08 failed
```

**Comment by daniceexi** [comment]
I logged in the MN and found the rcons does not work for c910f02c08p08, after restarted the conserver daemon, the rnetboot started working.

**Comment by neo954** [comment]
The long-term plan of xCAT Jenkins Test System is running the management node installation as a regular test case. In that situation, the failure of management node installation will be reported as a single test case failed. And all the remain test cases will be reported as `no run'.

**Comment by hu-weihua** [comment]
@neo954 , I think in the future plan,  **New xCAT package installation** will be treated as a regular test case. But **MN installation** belongs to one part of building test environment. so maybe you need to find some method to handle this.

**Comment by whowutwut** [comment]
Removed pending because the pull request is not yet merged...

**Comment by caomengmeng** [comment]
install xCAT is the first case in daily run now, and works well.
Except the sles11.4 OS, there is an issue: https://github.com/xcat2/xcat-core/issues/1976.
Add workaround in test case today, will track result tomorrow.

**Comment by caomengmeng** [comment]
Close this issue for the install_xCAT case  works well now
