### ISSUE TITLE
[fvt]2.12.1 SuSEfirewall2 check wrong on suse and ubuntu using "xcatprobe xcatmn"

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1378]
env:
sles12 ubuntu 14.03
build:
lsdef - Version 2.12.1 (git commit fddd78e1ec6a9d59bc921bef24e300e8d94f69e4, built Sun Jun 19 06:45:32 EDT 2016)
How to reproduce:
```c910f04x30v01:/opt/xcat/bin # ./xcatprobe xcatmn -n eth0
....
service: no such service SuSEfirewall2_setup
....

```
SuSEfirewall2: Firewall rules successfully set
c910f04x30v01:/opt/xcat/probe # SuSEfirewall2 status
### iptables filter ###
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
   13   920 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate ESTABLISHED
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED
    3   984 input_ext  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 5 LOG flags 6 level 4 prefix "SFW2-IN-ILL-TARGET "
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy DROP 0 packets, 0 bytes)
.....
.....
---------------------> In fact there are firewall opened on suse and

**Comment by hu-weihua** [comment]
This issue is fixed by pull request #1472 , @junxiawang , could you please verify it? thanks

**Comment by junxiawang** [comment]
@hu-weihua 
```
### iptables filter ###
Chain INPUT (policy DROP 0 packets, 0 bytes)
pkts bytes target prot opt in out source destination
746 224K ACCEPT all -- lo * 0.0.0.0/0 0.0.0.0/0
60 3376 ACCEPT all -- * * 0.0.0.0/0 0.0.0.0/0 ctstate ESTABLISHED
0 0 ACCEPT icmp -- * * 0.0.0.0/0 0.0.0.0/0 ctstate RELATED
43 13374 input_ext all -- * * 0.0.0.0/0 0.0.0.0/0
0 0 LOG all -- * * 0.0.0.0/0 0.0.0.0/0 limit: avg 3/min burst 5 LOG flags 6 level 4 prefix "SFW2-IN-ILL-TARGET "
0 0 DROP all -- * * 0.0.0.0/0 0.0.0.0/0

Chain FORWARD (policy DROP 0 packets, 0 bytes)
pkts bytes target prot opt in out source destination
0 0 LOG all -- * * 0.0.0.0/0 0.0.0 
```

**Comment by junxiawang** [comment]
verified
