### ISSUE TITLE
[fvt]2.11:offline trouble shooting time stamp wrong

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#140]
1.down load the latest build
2. [root@c910f02c01p13 ~]# date
Tue Sep  1 05:19:54 EDT 2015
[root@c910f02c01p13 ~]#
3.under commands log:
===================================================
[Date]       2015-7-31 5:59:24
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
====================================================
[Date]       2015-7-31 5:59:51
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
====================================================
[Date]       2015-7-31 6:0:55
[ClientType] cli
[Request]    lsdef -v
[Response]
--------------------------------> time stamp wrong  here

**Comment by whowutwut** [comment]
@junxiawang can you surround the output with three ``` to make it easier to read the above issue?
