### ISSUE TITLE
Include git commit number in xCAT daily autobuild

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1404]
Currently, xCAT has the version number plus a time tag in its package name. The package follows current scheme looks like ``xCAT-2.12.1-snap201606260648.ppc64.rpm``. I would like to have the git commit number be a part of the package name. Something like ``xCAT-2.12.1-snap201606260648-f203009.ppc64.rpm`` or similar would be fine.

**Comment by neo954** [comment]
The main reason I want this feature is due to the requirement of xCAT Jenkins Test Report. The xCAT Jenkins Test Report is based on the log analyzing of the xCAT auto-daily-test. But from the test log. There is no way to tell which branch or which git commit number the build is based. Or even worse, there is no way to tell if the build for Red Had and build for Ubuntu are on the same git commit number.

**Comment by daniceexi** [comment]
I prefer to add some messages by the automation framework to indicate the informations instead of doing that in the rpm itself.

**Comment by daniceexi** [comment]
As we discussed before, we might add a file named 'building' in the tar.bz2 file to include the version number, last commit id, build time, build server info. And also the commit id can be added in the tar file name.

Then user can have following three ways to get the version and commit id for a build:
* before downloading the tar: tar file name
* before install the packages: tar file name or the 'buildinfo' file
* after install: lsxcatd -a

**Comment by neo954** [comment]
Using a seperate file named ``building`` in the tarball may also acceptable. In the point of view of the Log Analyzer, it just need the git commit number appeared in the log file. Any place in the log file will do the work.

**Comment by whowutwut** [comment]
Sorry for the delay, I'm making a change and will create a pull request to address this

**Comment by neo954** [comment]
@tingtli, since this feature is already available. Please consider update our Jenkins test script, and include this git commit number in the xCAT Jenkins test log files.

**Comment by whowutwut** [comment]
I think we can close out this issue
