### ISSUE TITLE
[FVT]:mysqlsetup -i failed to setup database on sles12

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1413]
xcat 2.12.1 on sles12.
```
c910f03c04k04:/ # lsxcatd -v
Version 2.12.1 (git commit 93f20131dc8ebf4d8c4de47000bd631b7c7a9be7, built Thu Jun 23 09:30:44 EDT 2016)

After running mysqlsetup -i and input the root and xcatadmin password. The output shows the database is setup. But it seems it is not correctly setup.

c910f03c04k04:/ # /usr/bin/mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 144
Server version: 10.0.11-MariaDB openSUSE package

Copyright (c) 2000, 2014, Oracle, SkySQL Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
c910f03c04k04:/ # /usr/bin/mysql -u xcatadmin -p
Enter password:
ERROR 1045 (28000): Access denied for user 'xcatadmin'@'localhost' (using password: YES)
```

**Comment by tingtli** [comment]
@cxhong Please take a look at this issue. The environment is 10.3.4.4. The password is cluster. Thanks!

**Comment by cxhong** [comment]
the wildcard "%" seems didn't work here
`````
MariaDB [(none)]> SELECT host,user FROM mysql.user;
+---------------+-----------+
| host          | user      |
+---------------+-----------+
| %             | xcatadmin |
| 10.3.4.4      | xcatadmin |
| 127.0.0.1     | root      |
| ::1           | root      |
| c910f03c04k04 |           |
| c910f03c04k04 | root      |
| localhost     |           |
| localhost     | root      |
+---------------+-----------+
``````
Once I added 
````
 GRANT ALL on xcatdb.* To xcatadmin@localhost IDENTIFIED by 'cluster';
````

the xcatadmin user can access to database again.

I will look into more.

**Comment by cxhong** [comment]
The mysql docs have this to say: (from  http://dev.mysql.com/doc/refman/5.1/en/adding-users.html):
````


    Two of the accounts have a user name of monty and a password of some_pass. Both accounts are superuser accounts with full privileges to do anything. The 'monty'@'localhost' account can be used only when connecting from the local host. The 'monty'@'%' account uses the '%' wildcard for the host part, so it can be used to connect from any host.

    It is necessary to have both accounts for monty to be able to connect from anywhere as monty. Without the localhost account, the anonymous-user account for localhost that is created by mysql_install_db would take precedence when monty connects from the local host. As a result, monty would be treated as an anonymous user. The reason for this is that the anonymous-user account has a more specific Host column value than the 'monty'@'%' account and thus comes earlier in the user table sort order.
``````
so, to fix this issue, we need to create a 'xcatadmin'@'localhost' users with the same privileges

**Comment by tingtli** [comment]
it works on rh7.2 ppc64 an x64_64. but not on ppc64le

**Comment by daniceexi** [comment]
Inside of our code, we should use the IP/hostname of the database host (MN) to access the database, so  even we have problem to access mysql with cmd, but the xcatd should work to access DB.

**Comment by whowutwut** [comment]
@hu-weihua  can we have someone verify on behalf of Ting Ting and close out this issue?

**Comment by hu-weihua** [comment]
@junxiawang , Could you help to take look at this issue? thank you very much.

**Comment by junxiawang** [comment]
@daniceexi @cxhong @whowutwut 
Test results:
1.Test ok on:sles12.1  ppc64le xcatversion is 2.12.2
2.But sles12 on x86_64 still could not work
c910f04x30v01:/etc/zypp/repos.d # mysqlsetup -i
MySQL is running.  Database initialization will not take place.
Input the alpha-numberic  password for xcatadmin in the MySQL database: 
Input the password for root in the MySQL database: 
Backing up xCAT Database to /root/xcat-dbback.
This could take several minutes.
Shutting down the xcatd daemon during database migration.
Hostname resolution for  failed.
c910f04x30v01:/etc/zypp/repos.d # uname -a
Linux c910f04x30v01 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) x86_64 x86_64 x86_64 GNU/Linux
c910f04x30v01:/etc/zypp/repos.d # cat /etc/*-release
NAME="SLES"
VERSION="12"
VERSION_ID="12"
PRETTY_NAME="SUSE Linux Enterprise Server 12"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12"
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
c910f04x30v01:/etc/zypp/repos.d #

**Comment by daniceexi** [comment]
@junxiawang Please refine the format of your issue description.

Does the failure caused by the error ``Hostname resolution for failed.``? Could you make sure the name resolution is ok for your MN and SN?

**Comment by junxiawang** [comment]
@daniceexi  nslookup work

**Comment by cxhong** [comment]
@junxiawang , the problem is caused by you didn't define site.master.    mysqlsetup needs to get MN name from site.master in the backed up database during setup.
````
c910f04x30v01:~ # tabdump site | grep master
"master",,,
````

**Comment by immarvin** [comment]
hi @cxhong , according to the mysqlsetup code logic, if the "master" does not exist in site.master, it will try to get the hostname with command "hostname", seems there are some bugs, I tried to fix it in https://github.com/xcat2/xcat-core/pull/1600, please review
