### ISSUE TITLE
Ubuntu Xenial: apt.key uses weak digist algorithm.

### ISSUE THREAD

**Issue by torkelsson** [xcat2/xcat-core#1414]
I'm trying to install xcat on a Ubuntu Xenial system. After adding the apt-key (wget -O - "http://xcat.org/files/xcat/repos/apt/apt.key" | apt-key add -) to the keyring and running apt-get update I get:

W: https://xcat.org/files/xcat/repos/apt/2.12/core-snap/dists/xenial/InRelease: Signature by key F75B1BF678B644FDF3AACFC860A3E9ACC6565BC9 uses weak digest algorithm (SHA1)
W: https://xcat.org/files/xcat/repos/apt/xcat-dep/dists/xenial/InRelease: Signature by key F75B1BF678B644FDF3AACFC860A3E9ACC6565BC9 uses weak digest algorithm (SHA1)

Can you please update the apt-key to a more modern?

**Comment by daniceexi** [comment]
Thanks for the information, it will be fixed in next release.

**Comment by immarvin** [comment]
will take a look when supporting ubuntu 18.04

**Comment by neo954** [comment]
I will close this issue right here. The problem will be tracked though issue #5306.
