### ISSUE TITLE
Ubuntu Xenial: Repository does not support architecture i386

### ISSUE THREAD

**Issue by torkelsson** [xcat2/xcat-core#1416]
I'm trying to install xcat on Ubuntu Xenial, however when following the documentation and adding:

deb http://xcat.org/files/xcat/repos/apt/devel/core-snap trusty main

to sources.list (or sources.list.d/xcat.list) I get the following message:

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://xcat.org/files/xcat/repos/apt/2.12/core-snap xenial InRelease' doesn't support architecture 'i386'

Can you please make the archive multi arch? And/or update the documentation?

**Comment by immarvin** [comment]
need to evaluate whether to  support  i386, put off to 2.13

**Comment by zet809** [comment]
@torkelsson Do you mean you'd like to install xCAT on an i386 server?

**Comment by torkelsson** [comment]
@zet809 No, I'm installing xCAT on an amd64 server, which is multiarch enabled, i.e it looks for i386 packages too when running apt-get update. However as the repository does not provide the i386 archive (not even an empty one) I get the message from the initial report. 

Please, either provide a i386 archive (perhaps empty) or add to the documentation, how to set up  apt-sources to only look for amd64 packages. See https://wiki.debian.org/Multiarch/HOWTO#Setting_up_apt_sources

**Comment by zet809** [comment]
@torkelsson Thank you for point out this issue, we will modify our documentation like below:
deb [arch=amd64] http://xcat.org/files/xcat/repos/apt/devel/core-snap trusty main # for x86_64 server
deb [arch=ppc64el] http://xcat.org/files/xcat/repos/apt/devel/core-snap trusty main # for ppc64le server

**Comment by whowutwut** [comment]
@zet809  Is this target to be changed on the xcat.org download page?  or other places in our documentation? https://github.com/xcat2/xcat.org/blob/master/download.html

**Comment by zet809** [comment]
@whowutwut I think both of them needed to be updated. I tried to modify the readthedoc within pull request #1705.
And for the download page of xcat.org, I think it shall be like this, but can not modify the html file. Will you pls do the modification? Thx!

    For x86_64 servers: deb [arch=amd64] http://xcat.org/files/xcat/repos/apt/latest/xcat-core trusty main
    For ppc64el servers: deb [arch=ppc64el] http://xcat.org/files/xcat/repos/apt/latest/xcat-core trusty main

**Comment by whowutwut** [comment]
Created pull request: https://github.com/xcat2/xcat.org/pull/25  Can you please double check the changes?

**Comment by zet809** [comment]
@torkelsson We have updated the document, I think we can close the defect, right?
