### ISSUE TITLE
Ubuntu Xenial: xcat-server needs to depend on openssh-server

### ISSUE THREAD

**Issue by torkelsson** [xcat2/xcat-core#1419]
Trying to install xcat on Ubuntu Xenial (using core-snap) I ran into the problem that xcat-server is uninstallable because the xcatd init-script has a Required-Start: sshd, which means that the package installation of xcat-server fails unless openssh-server is already installed. However the xcat-server package does not depend on openssh-server.

**Comment by whowutwut** [comment]
@immarvin @penguhyang can you take a look at this issue?

**Comment by immarvin** [comment]
hi @whowutwut . I will try this in my env

**Comment by immarvin** [comment]
recreated:
the log:
````

Setting up libhttp-async-perl (0.30-1) ...
Setting up libxml-parser-perl (2.44-1build1) ...
Setting up libxml-sax-expat-perl (0.40-2) ...
update-perl-sax-parsers: Registering Perl SAX parser XML::SAX::Expat with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Setting up liblwp-protocol-https-perl (6.06-2) ...
Setting up libsoap-lite-perl (1.19-1) ...
Setting up libxmlrpc-lite-perl (0.717-1) ...
Setting up xcat-server (2.12-snap201605200311) ...
insserv: Service sshd has to be enabled to start service xcatd
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package xcat-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu4) ...
Errors were encountered while processing:
 xcat-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

**Comment by immarvin** [comment]
````

root@c910f03fsp03v120:~# update-rc.d xcatd defaults
insserv: Service sshd has to be enabled to start service xcatd
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
````

**Comment by immarvin** [comment]
hi @whowutwut , I talked with @daniceexi today, we do not see it's necessary for xcatd service to depend on sshd service. 

I will remove sshd from the xcatd sysvinit file

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1432

**Comment by immarvin** [comment]
verified on 

root@bybc0605:/opt# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
