### ISSUE TITLE
xcatprobe command is not being shipped with xCAT product

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1423]
Using the latest daily build....

```
[root@fs2vm111 ~]# lsxcatd -a
Version 2.12.1 (git commit cfc2fab85626b0ef2fe40357c847c59e37138af5, built Tue Jun 28 06:45:42 EDT 2016)
This is a Management Node
dbengine=SQLite
```
the xcatprobe function is not being shipped with the product. 
```
[root@fs2vm111 ~]# which xcatprobe
/usr/bin/which: no xcatprobe in (/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.local/bin:/root/bin)
```

We should figure out the packaging and get this into the xCAT product for 2.12 release. 
Then we can have more users running the probe commands to provide feedback and possibly refactor if needed.

**Comment by hu-weihua** [comment]
@whowutwut , I have pulled a request #1451  to do probe package stuff, if that pull request is merged and work, I think xcat probe tools can be used in xcat build

**Comment by hu-weihua** [comment]
@whowutwut , I think this issue has been fixed and verified. Could you close this issue? thanks.

**Comment by daniceexi** [comment]
Yes, this issue can be closed now.

**Comment by whowutwut** [comment]
Thanks, looks good. I see xCAT-probe now being shippped.
