### ISSUE TITLE
[FVT]:go-xcat should provide meaningful message and exit gracefully when there is some dependecny issue.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1425]
xCAT 2.12.1 6/28 build.
When I run go-xcat on a new installed rhels7.2 node. I found following error.
The go-xcat hangs and give some warning message. but the message is not meaningful to users.
```
[root@c910f03c04k03 /]# ./go-xcat -x 2.11
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.2

Reading repositories ...... done
go-xcat: get_package_list: unsupported function
go-xcat: get_package_list: unsupported function

xCAT Core Packages
==================

Package Name                Installed                      In Repository
------------                ---------                      -------------
go-xcat: check_repo_version: unsupported function
perl-xCAT                   (not installed)
xCAT                        (not installed)
xCAT-SoftLayer              (not installed)
xCAT-buildkit               (not installed)
xCAT-client                 (not installed)
xCAT-confluent              (not installed)
xCAT-genesis-scripts-ppc64  (not installed)
xCAT-genesis-scripts-x86_64 (not installed)
xCAT-server                 (not installed)
xCAT-test                   (not installed)
xCAT-vlan                   (not installed)
xCATsn                      (not installed)

xCAT Dependency Packages
========================

Package Name                Installed                      In Repository
------------                ---------                      -------------
[root@c910f03c04k03 /]# go-xcat: check_repo_version: unsupported function

```
Then After debug, there is because yum-utils is not installed. After yum-utils is installed. The scripts works well. I think since we know this issue, we need to refine our script to give more meaningful message.

**Comment by neo954** [comment]
Please use pull request #1426 as the patch.

**Comment by tingtli** [comment]
Verified with 7/6 build.

[root@c910f03c04k03 /]# ./go-xcat -x 2.11
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.2

Reading repositories ...... done

xCAT Core Packages
==================

Package Name                Installed                      In Repository
------------                ---------                      -------------
perl-xCAT                   (not installed)                2.11.1-snap201604140932
xCAT                        (not installed)                2.11.1-snap201604140932
xCAT-SoftLayer              (not installed)                2.11.1-snap201604140932
xCAT-buildkit               (not installed)                2.11.1-snap201604140932
xCAT-client                 (not installed)                2.11.1-snap201604140932
xCAT-confluent              (not installed)                2.11.1-snap201604140932
xCAT-genesis-scripts-ppc64  (not installed)                2.11.1-snap201604140932
xCAT-genesis-scripts-x86_64 (not installed)                2.11.1-snap201604140932
xCAT-server                 (not installed)                2.11.1-snap201604140932
xCAT-test                   (not installed)                2.11.1-snap201604140932
xCAT-vlan                   (not installed)                2.11.1-snap201604140932
xCATsn                      (not installed)                2.11.1-snap201604140933

xCAT Dependency Packages
========================

Package Name                Installed                      In Repository
------------                ---------                      -------------
conserver-xcat              8.1.16-10                      8.1.16-10
elilo-xcat                  3.14-4                         3.14-4
fping                       (not installed)                2.4b2_to-2
grub2-xcat                  2.02-0.16.el7.snap201506090204 2.02-0.16.el7.snap201506090204
ipmitool-xcat               1.8.15-1                       1.8.15-1
lldpd                       (not installed)                0.7.15-6.1
net-snmp-perl               5.7.2-20.ael7b                 5.7.2-20.ael7b
perl-AppConfig              (not installed)                1.52-4
perl-Crypt-CBC              2.33-2.el7                     2.33-2.el7
perl-Crypt-Rijndael         1.09-2.ael7a                   1.09-2.ael7a
perl-Expect                 1.21-1                         1.21-1
perl-HTML-Form              6.03-6.el7                     6.03-6.el7
perl-HTTP-Async             0.30-2                         0.30-2
perl-IO-Stty                0.03-1                         0.03-1
perl-IO-Tty                 1.07-1                         1.07-1
perl-JSON                   2.59-2.el7                     2.59-2.el7
perl-Net-HTTPS-NB           0.14-2                         0.14-2
perl-Net-Telnet             3.03-19.el7                    3.03-19.el7
perl-SOAP-Lite              0.710.08-1                     0.710.08-1
perl-XML-Simple             2.20-5.el7                     2.20-5.el7
pyodbc                      (not installed)                3.0.7-1.ael7a
syslinux-xcat               3.86-2                         3.86-2
systemconfigurator          (not installed)                2.2.11-1
systemimager-client         (not installed)                4.3.0-0.1
systemimager-common         (not installed)                4.3.0-0.1
systemimager-server         (not installed)                4.3.0-0.3
xCAT-UI-deps                (not installed)                2.8-2
xCAT-genesis-base-ppc64     (not installed)                2.12-snap201605051443
xCAT-genesis-base-x86_64    (not installed)                2.12-snap201605051534
xCAT-genesis-x86_64         (not installed)                2.7.7-snap201301100842
xnba-undi                   1.0.3-131028                   1.0.3-131028
yaboot-xcat                 1.3.17-rc1                     1.3.17-rc1
