### ISSUE TITLE
[FVT]Can't find expected logs in MN for ubuntu14.04.4 ppc64le

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1431]
Using latest daily build to install CN with ubuntu14.04.4 diskless, then try to find logs in MN:/var/log/xcat/computes.log when xcatdebugmode=1/2, but below log failed to be shown.
```
RUN:cat /var/log/xcat/computes.log | grep "running /opt/xcat/xcatdsklspost"

[cat /var/log/xcat/computes.log | grep "running /opt/xcat/xcatdsklspost"] Running Time:0 sec
RETURN: rc = 1
OUTPUT:
CHECK:output =~ running /opt/xcat/xcatdsklspost [Failed]
```

**Comment by immarvin** [comment]
seems "logger -n" does not work on ubuntu14.04.4 LTS.
opened a ticket to LTC: https://bugzilla.linux.ibm.com/show_bug.cgi?id=144136
@penguhyang ,please trace this ticket and answer the questions from LTC if any

**Comment by penguhyang** [comment]
Ubuntu 14.04.4 use version 2.20.1
It builds fine but ignores the -n switch just like the installed version.
