### ISSUE TITLE
xCAT 2.12.X release information missing in RTD

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1436]
Open this issue to track the release information is missing in the RTD for 2.12.x 
http://xcat-docs.readthedocs.io/en/stable/overview/xcat2_release.html

**Comment by daniceexi** [comment]
I have added the release info for 2.12.1, 2.12 and 2.11.1 through pull request #1506

**Comment by daniceexi** [comment]
Done.
