### ISSUE TITLE
[FVT] `rinstall' did not check if `nodeset' runs successfully, but continue do the net booting.

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1461]
The test environment is RHEL 7.2 runs on PowerVM. And xCAT is the latest build.

    # lsxcatd -v
    Version 2.12.1 (git commit 705c119d0f3166f0532cd401475666c3d5e11d38, built Sun Jul  3 06:45:35 EDT 2016)

The test scenario is quite simple. I stopped the DHCP server intensionally. Thus, ``nodeset`` will fail. Based on the screen output and exit code below, ``rinstall`` is failed as well at last. But while I was monitoring the virtual console output of the LPAR ``c910f02c03p26'', ``rinstall`` still try to do the net boot even if ``nodeset'' is failed. This is time wasting and can be avoid.

    # service dhcpd stop
    Redirecting to /bin/systemctl stop  dhcpd.service
    # rinstall c910f02c03p26 osimage=master_1603a
    Provision node(s): c910f02c03p26
    c910f02c03p26: install rhels7.2-ppc64-master
    dhcp server is not running.  please start the dhcp server.
    dhcp server is not running.  please start the dhcp server.
    Error: failed to run 'nodeset' against the following nodes: c910f02c03p26
    [root@c910f02c03p27 ~]# echo $?
    1

**Comment by neo954** [comment]
I read the code roughly. There are two array, ``@successnodes`` and ``@failurenodes`` in the code, and they are assigned properly when ``nodeset`` returns. But when ``rnetboot`` was running. it was run against all nodes, ``@nodes``. Actually, when ``nodeset`` was failed partially, only nodes in ``@successnodes`` are worth to run ``rnetboot``.

**Comment by daniceexi** [comment]
The error message for the case the dhcpd stopped is:
~~~~
# nodeset c910f02c03p26 osimage
c910f02c03p26: install rhels7.2-ppc64-master
Error: dhcp server is not running.  please start the dhcp server.
Error: dhcp server is not running.  please start the dhcp server.
~~~~

In this case, all the os deployment would fail. So when rinstall command see this message, exit directly.
