### ISSUE TITLE
[FVT]go-xcat -x does not support minor release

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1489]
xCAT 2.12.1 on rhels7.2
[root@c910f03c04k05 /]# ./go-xcat -x 2.12.1 -y install
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.1

Reading repositories ...... failed
go-xcat: download xcat-core resource failed

**Comment by neo954** [comment]
The inconstancy of 2.12 and 2.12.1 is on xcat.org, not in ``go-xcat``.

**Comment by whowutwut** [comment]
@neo954 what is the inconsistency in xcat.org? If you have some information I can investigate it. The release numbers should be consistent.

**Comment by tingtli** [comment]
I think we should support the minor release. especially when we give important fix in the minor release and customer would like to update to this minor release. Why does go-xcat not support that?

**Comment by tingtli** [comment]
we upload the minor release to http://xcat.org/files/xcat/xcat-core/2.xx.x_Linux/xcat-core/. And we put the minor release version in the tar ball. What is the inconsistency in xcat.org

**Comment by daniceexi** [comment]
@tingtli The thing is we don't have online repo for each minor release.

http://xcat.org/files/xcat/repos/yum/2.12/xcat-core/ incldues the latest minor release for 2.12 branch, it could be 2.12.1 or 2.12.2. So we may make a separated dir for each minor release. This can resolve the issue.

**Comment by caomengmeng** [comment]
@tingtli , as go-xcat test cases failed sles11, sles12.1, ubuntu14.04.4 and ubuntu16.04, so test cases should be updated accordingly.

**Comment by daniceexi** [comment]
@caomengmeng We will talk with issue in next Monday's interlock meeting. So keep the test case as is now.

**Comment by zet809** [comment]
@tingtli It seems the conclusion is we will update the directory structure on xcat.org, does this defect just use to trace the action?

**Comment by tingtli** [comment]
@zet809 i think so. I will reopen this issue to trace that. I think we need to support the minor release. I will discuss with @whowutwut  and @neo954  to see what should be done on xcat.org directory.

**Comment by zet809** [comment]
@tingtli Hi, ting ting, will you pls confirm how to modify the directory structure on xcat.org? Once it is done, you can close this defect.

**Comment by whowutwut** [comment]
I think the decision here is to close this issue right now.  The `go-xcat` tool is suppose to help the new user have a very easy way to install/update xCAT.  I think we normally stress to the user to run the latest xCAT code as much as possible, so let's not plan to support minor releases in the xcat.org public yum repo unless we have some customer requirements to do so.
