### ISSUE TITLE
Discovery probe to help debug failed discovery attempts

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#1491]
As is stands, xcat probe can only be used to monitor discovery process while it is running.  Being able to run xcat probe after a finished discovery attempt to debug issues that led to failure would be a very useful feature

**Comment by hu-weihua** [comment]
@pdlun92 , thank you for your suggestion. xcat probe  sub_command  ``osdeploy`` add a new feature "replay the log" can cover your requirement for provision. usage is ``osdeploy -n <node_range> -r <xxhxxm> [-V]``. 

If this feature comes to stable, we will implement is on discovery.

**Comment by hu-weihua** [comment]
@pdlun92 , we have implement replay function for ``discovery`` in xcat2.12.4. Could you try to use and offer some feedback? thank you very much.

**Comment by pdlun92** [comment]
Have observed output from successful and failed discovery attempts, using `xcatprobe discovery` during discovery and `xcatprobe discovery -r` as well as `xcatprobe osdeploy -r` afterwords, all for debug.

My feedback is entirely positive.  The outline of steps is very useful and clear.  
Only suggestion would be to correct some typos in output, but overall the changes are great!

IST team will be running a large scale discovery attempt tomorrow or very soon.  Will ask them to use these methods for additional feedback

**Comment by whowutwut** [comment]
@pdlun92  Can we close this out, is it verified?
