### ISSUE TITLE
[PCM] Provision Dell PowerEdge M605 compute node hangs while setup BMC

### ISSUE THREAD

**Issue by AsirXing** [xcat2/xcat-core#1495]
I am tried to provision Dell PowerEdge M605 compute node with xCAT 2.12, but the provisioning is hang while setup BMC. Below are details for this issue.
**1. The xCAT version:**
...............
[root@db04b11 ~]# lsxcatd -a
Version 2.12 (git commit b33cb213ce79f91621cd65932c9798c735b74bc4, built Fri Jun 24 03:17:21 EDT 2016)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=192.168.108.80|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=192.168.108.80
dbadmin=xcatadm
[root@db04b11 ~]#
...............

**2. The compute node hardware model: Dell PowerEdge M605**

**3. The outputs of ipmitool commands in genesis**
...............
[xCAT Genesis running on db04b12 /tmp]# ipmitool lan print 1
No data available
Get Device ID command failed
No data available
Get Channel Info command failed: Invalid command
Invalid channel: 1
[xCAT Genesis running on db04b12 /tmp]#
...............

**4. The processes tree in genesis** 
...............
  307 ?        S      0:00 screen -L -ln doxcat
  308 ?        Ss     0:00  \_ SCREEN -L -ln doxcat
  309 pts/1    Ss+    0:00      \_ /bin/sh /usr/bin/doxcat
  442 pts/1    S+     0:01          \_ /bin/sh /usr/bin/doxcat
24492 pts/1    S+     0:00          |   \_ sleep 5
  443 pts/1    S+     0:01          \_ /bin/sh /usr/bin/doxcat
24493 pts/1    S+     0:00          |   \_ sleep 5
 1102 pts/1    S+     0:00          \_ /bin/sh /usr/bin/doxcat
24435 pts/1    S+     0:00              \_ /bin/sh /usr/bin/doxcat
24436 pts/1    S+     0:00                  \_ ipmitool raw 0x3a 0x0a
...............

**Comment by daniceexi** [comment]
@AsirXing There's a commit 195f80ee6e544d500545dd00e7b9357498ba872f for Dell server support. You could take a try. 

You can just copy the bmcsetup script from master to 2.12-pcm build and take a try.

**Comment by zet809** [comment]
# ipmitool mc info
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 1.65
IPMI Version              : 2.0
Manufacturer ID           : 674
Manufacturer Name         : DELL Inc
Product ID                : 43707 (0xaabb)
Product Name              : Unknown (0xAABB)
Device Available          : yes
Provides Device SDRs      : no
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    IPMB Event Generator
    Chassis Device
Aux Firmware Rev Info     :
    0x08
    0x01
    0x00
    0x00
From the output above, it seems using "XPROD" ＝ “43707”  to judge whether it is OpenPOWER server is incorrect, we shall use both "XPROD" and "IPMIMFG" to judge.

**Comment by daniceexi** [comment]
@AsirXing do you want the fix get into any specific PCM branch?

**Comment by AsirXing** [comment]
The fix works according to my testing.
[root@db04b11 ~]# lsdef db04b12 | grep status
    appstatus=provision=provisioned
    appstatustime=07-26-2016 03:49:07
    status=booted
    statustime=07-26-2016 03:49:07
[root@db04b11 ~]# xdsh db04b12 uptime
db04b12:  03:54:42 up 10 min,  0 users,  load average: 0.04, 0.72, 0.61
[root@db04b11 ~]# rpower db04b12 stat
db04b12: on
[root@db04b11 ~]#
