### ISSUE TITLE
Improve the Hardware Discovery messages 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1504]
I was not able to review the changes during the pull request, so providing some comments here to track some message improvements.  

Looking at the example in the Release notes for 2.12.1
```
xcat[91111]: xcat.discovery.aaadiscovery: (8335-GTB*100464A) Get a discover request
xcat[91111]: xcat.discovery.blade: (8335-GTB*100464A) Processing discovery request
xcat[91111]: xcat.discovery.blade: (8335-GTB*100464A) Error: Could not find any node
xcat[91111]: xcat.discovery.switch: (8335-GTB*100464A) Processing discovery request
xcat[91111]: xcat.discovery.switch: (8335-GTB*100464A) Find node:c910f05c29 for the discovery request
xcat: The attribute bmcinband is specified, just remove the temp BMC node if there is
xcat: Find BMC node-8335-gtb-100464a, so remove it
xcat: c910f05c29 has been discovered
xcat[91111]: xcat.discovery.zzzdiscovery: (8335-GTB*100464A) Finish to process the discovery request
xcat[91111]: xcat.discovery.zzzdiscovery: (8335-GTB*100464A) Successfully processed by switch method 
```

Suggest the following changes: 

- `xcat[91111]: xcat.discovery.blade: (8335-GTB*100464A) Error: Could not find any node`  <-- suggest "Warning: Could not find any node matching <SN>" 

- `xcat[91111]: xcat.discovery.switch: (8335-GTB*100464A) Find node:c910f05c29 for the discovery request` <-- suggest "Found node: <hostname> matching <SN?> for discovery request"

- How come the following messages do not have the same log tags? 

  ```
  xcat: The attribute bmcinband is specified, just remove the temp BMC node if there is 
  xcat: Find BMC node-8335-gtb-100464a, so remove it
  xcat: c910f05c29 has been discovered
  ```

- `xcat: The attribute bmcinband is specified, just remove the temp BMC node if there is ` <-- i think this is not ncessary

- `xcat: Find BMC node-8335-gtb-100464a, so remove it` <--- Suggest "Removing discovered node definition: node-8335...

- `xcat: c910f05c29 has been discovered` 
I would like this to be something like: 
   `xcat: c910f05c29 (node-8335-gtb-100464a) has been discovered` so we can correlate the discovered definition to the pre-defined definition.

**Comment by zet809** [comment]
Will fix in next release.

**Comment by whowutwut** [comment]
@zet809 I forgot to associate the pull request with this issue.  I think the only lingering comment left to change is the following: 

- How come the following messages do not have the same log tags? 

  ```
  xcat: The attribute bmcinband is specified, just remove the temp BMC node if there is 
  xcat: Find BMC node-8335-gtb-100464a, so remove it
  xcat: c910f05c29 has been discovered
  ```

- `xcat: c910f05c29 has been discovered` 
I would like this to be something like: 
   `xcat: c910f05c29 (node-8335-gtb-100464a) has been discovered` so we can correlate the discovered definition to the pre-defined definition.  


We are not doing much runs of the hw discovery right now, but if I have some chance to rerun, i will look into changing it.

**Comment by zet809** [comment]
@xuweibj Hi, xu wei, will you pls help to modify the discovery related log message? Thx a lot!

**Comment by whowutwut** [comment]
Closing this issue out, Will continue to evaluate the discovery messages and open issues if needed
