### ISSUE TITLE
[FVT]rmvm command on ppc64le test enviroment doesn't work.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1513]
Description:Using latest build to run regression in automation test environment:
```
Cluster Information:
		  MN: c910f03fsp03v02
		  SN: c910f03fsp03v03
		  CN: c910f03fsp03v04
```
While running "Diskless_installation_flat_p8_le" cases, try to "rmvm" below error happens, both ubuntu16.04 and rh7.2 encountered the same issue:

```
RUN:if [ "ppc64le" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04; else rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04 -s 20G; fi;fi

[if [ "ppc64le" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04; else rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04 -s 20G; fi;fi] Running Time:4 sec
RETURN rc = 1
OUTPUT:
c910f03fsp03v04: Error: Unknown issue Path c910f03fsp03v04.sda.qcow2 already exists at /opt/xcat/lib/perl/xCAT_plugin/kvm.pm line 315.
CHECK:rc == 0	[Failed]
```

**Comment by gurevichmark** [comment]
@caomengmeng What os was installed on the CN when this error happened ?

**Comment by caomengmeng** [comment]
@gurevichmark   both ubuntu16.04 and rh7.2 encountered the same issue

**Comment by gurevichmark** [comment]
@caomengmeng Sorry, somehow I missed before, that you already listed the OS in the problem description.

Is it possible for me to login to the system where this is happening and verify the environment ?
If yes, can you provide the id/pw and which node I can access this system from ?

Also, the name of the testcase is "Diskless_installation_flat_p8_le", but why the code there issues:
`mkvm c910f03fsp03v04 -s 20G` to create a vm with 20G disk ?

**Comment by daniceexi** [comment]
@caomengmeng Could you try to recreate this issue without the node which automation is using so that @gurevichmark can take a look? BTW, is this a timing issue since we did not see it before?

**Comment by caomengmeng** [comment]
RH7.2 ppc64le encountered the same issue today with the same cluster using 14. July daily build
```
RUN:if [ "ppc64le" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04; else rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04 -s 20G; fi;fi

[if [ "ppc64le" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04; else rmvm c910f03fsp03v04 -f -p  &&  mkvm c910f03fsp03v04 -s 20G; fi;fi] Running Time:5 sec
RETURN rc = 1
OUTPUT:
c910f03fsp03v04: Error: Unknown issue Path c910f03fsp03v04.sda.qcow2 already exists at /opt/xcat/lib/perl/xCAT_plugin/kvm.pm line 315.
CHECK:rc == 0	[Failed]
```
Test clusters:
```
Cluster Information:
		  MN: c910f03fsp03v02
		  SN: c910f03fsp03v03
		  CN: c910f03fsp03v04
```
@daniceexi As it can be reproduced in our daily run, so don't think it is a timing issue. I will have a try if this can be reproduced without autotest environment.

**Comment by gurevichmark** [comment]
@caomengmeng Any updates to this issue? Were you able to reproduce it without autotest environment ?

**Comment by caomengmeng** [comment]
@gurevichmark  it works well for more than one week, and not reproduced out of autotest environment, so close it.

**Comment by daniceexi** [comment]
If we encountered a problem but could not create it anymore without a fix, it means mostly it would be recur someday later. 
Anyway, we can reopen this issue when encounter again.
