### ISSUE TITLE
Power8 firmware (01SV830) upgrade issue - URGENT 

### ISSUE THREAD

**Issue by mleeus** [xcat2/xcat-core#152]
Hello,
I am trying to upgrade 01SV830 firmware to Power8 8247-22L system by using rflash. xCAT server is 2.10, following are the commands issued and error messages:

Commands:
===========
[root@bdxcatp1 bin]# rpower dlc-lpar off
[root@bdxcatp1 bin]# rpower dlc-cec off
[root@bdxcatp1 bin]# rspconfig dlc-cec pending_power_on_side=temp
[root@bdxcatp1 bin]# mount -o loop H88222373_01SV830_048_048.iso /mnt
[root@bdxcatp1 bin]# rflash dlc-cec -p /mnt --activate disruptive
It may take considerable time to complete, depending on the number of systems being updated.  In particular, power subsystem updates may take an hour or more if there are many attached managed systems. Please waiting.
You can find the log files in the /var/log/xcatd/dfm/rflash/.
bd01dn06-cec: Failed to run start_code_update_lr() to start code update long running
failed to code update for the primary FSP

Log file:
========
In /var/log/xcatd/dfm/rflash/rflash.bd01dn01-cec_172.17.1.1_20150826.155801.log 
20150826.15:58:01 (20076)(140479318308640) 	hcp_ipaddr = 172.17.1.1
20150826.15:58:01 (20076)(140479318308640) 	hcp_ipaddr_backup = 
20150826.15:58:01 (20076)(140479318308640) 	sockfd        0x0003:
20150826.15:58:01 (20076)(140479318308640) 	sockfd_backup 0x0000:
20150826.15:58:01 (20076)(140479318308640) 	vport        0x000b:
20150826.15:58:01 (20076)(140479318308640) 	vport_backup 0x0000:
20150826.15:58:01 (20076)(140479318308640) 	state        0x0000:
20150826.15:58:01 (20076)(140479318308640) 	state_backup 0x0000:
20150826.15:58:01 (20076)(140479318308640) firmware update starting.....
20150826.15:58:02 (20076)(140479318308640) check fsp/bpa type
20150826.15:58:02 (20076)(140479318308640) check fsp/bpa readiness
20150826.15:58:02 (20076)(140479318308640) the rpm available: /install/packages_fw/01SV830_048_048.rpm
20150826.15:58:02 (20076)(140479318308640) the /install/packages_fw/01SV830_048_048.rpm size is: 82951 KB
20150826.15:58:02 (20076)(140479318308640) it needs 248855 KB of the freespace of /tmp at least
20150826.15:58:02 (20076)(140479318308640) the /tmp unused size is: 479884 KB
20150826.15:58:02 (20076)(140479318308640) the raw data size is: 209134 KB
20150826.15:58:02 (20076)(140479318308640) the raw data includes 20736 lids :
20150826.15:58:02 (20076)(140479318308640) 		name=/tmp/fwupdate/data/01SV830_048_048/01SV830.048.0, size=0 bytes
20150826.15:58:02 (20076)(140479318308640) The lid exists. Don't need to create it again.
20150826.15:58:02 (20076)(140479318308640) 		name=/tmp/fwupdate/data/01SV830_048_048/01SV830.048.0, size=0 bytes
20150826.15:58:02 (20076)(140479318308640) The lid exists. Don't need to create it again.
20150826.15:58:02 (20076)(140479318308640) 		name=/tmp/fwupdate/data/01SV830_048_048/01SV830.048.0, size=0 bytes
20150826.15:58:02 (20076)(140479318308640) The lid exists. Don't need to create it again.
.
.
.

Current firmware level:
===================
[root@bdxcatp1 ~]# rinv bd01mn01-cec firm
bd01mn01-cec: Release Level  : 01SV810
bd01mn01-cec: Active Level   : 101
bd01mn01-cec: Installed Level: 101
bd01mn01-cec: Accepted Level : 101
bd01mn01-cec: Release Level Primary: 01SV810
bd01mn01-cec: Level Primary  : 101
bd01mn01-cec: Current Power on side Primary: temp

If you need further information, please let me know.
Thank you in advance.

Best Regards,
Michael Lee
mle@us.ibm.com

**Comment by zet809** [comment]
Which OS is working on your xCAT node?
In the rflash output, it seems you can using "bd01dn06-cec", but the log file is for "bd01dn01-cec". And rinv output is for "bd01mn01-cec". Is there any rflash log file for "bd01dn06-cec"? Will you pls show me the output of rinv and node definition for "bd01dn06-cec"? Thx!

**Comment by mleeus** [comment]
Sorry I didn't keep the same node name. The errors/output are same among all the nodes.
This cluster has 10 nodes: bd01mn01-cec, bd01mn02-cec, bd01dn01-cec to bd01dn08-cec.
Thanks.

**Comment by zet809** [comment]
What is the OS and arch of the Management Node? Which version of xcat-dfm and hdwr_svr you are using? It seems the firmware rpm pkg is parsed incorrectly: 
20150826.15:58:02 (20076)(140479318308640) the raw data includes 20736(It shall not be so many) lids :

And will you pls show me the node definition of bd01dn06-cec?

**Comment by mleeus** [comment]
OS:  Red Hat Enterprise Linux Server release 6.6 (Santiago)
xcat-dfm:  xCAT-dfm-2.8.3-71.x86_64
hdwr_svr:  ISNM-hdwr_svr-RHEL-1.2.0.0-0.x86_64
xCAT:  Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)

**Comment by mleeus** [comment]
[root@bdxcatp1 ~]# lsdef bd01dn08-cec
Object name: bd01dn08-cec
    groups=dlc-cec,compute-cec,all
    hcp=bd01dn08-cec
    hwtype=cec
    mgt=fsp
    mtm=8247-22L
    nodetype=ppc
    postbootscripts=otherpkgs
    postscripts=remoteshell,syncfiles,setupntp,hardeths,setbootfromdisk
    serial=212181A
    status=booting
    statustime=09-01-2015 16:59:27

**Comment by zet809** [comment]
It is a defect for our xcat-dfm 2.8.3 x86_64 build, it had been fixed in xcat-dfm 2.9.1 but there is no build for x86_64. 
So you can either wait for the xcat-dfm 2.9.1 x86_64 build (may takes several days) or use xCAT-dfm 2.9.1 with other arch such as ppc64 or ppc64le.

**Comment by zet809** [comment]
The xcat-dfm x86_64 build which had included the fix is ready, need 2-3 days to upload them onto fix central.

**Comment by mleeus** [comment]
Thanks. I will try the new fix. Will let you know the result.

**Comment by zet809** [comment]
For some reasons, we don't have system X environment in hand, I'm sure the fix works for other arch such as ppc64 and ppc64le. So, I am wondering it is possible for you to use the RPM pkg directly and let us know the result? And how do I send you the pkg?

**Comment by mleeus** [comment]
I am not running on X, I am running on Power8. I noticed that the dfm is for X on my xcat server. That might be the problem.
You can send to me a dfm for Power by email if possible at mle@us.ibm.com.
Thank you.

**Comment by mleeus** [comment]
You can email me to mle@us.ibm.com if possible.
Thank you.

**Comment by mleeus** [comment]
I upgraded xCAT-dfm fileset. When I ran rflash, seems doesn't create /tmp/fwupdate directory and files. Following are the commands I ran:
[root@bdxcatp1 mnt]# rpm -qa|grep dfm
xCAT-dfm-2.9.1-36.x86_64

/nas/ish/powerfw/H88222373_01SV830_048_048.iso on /mnt type iso9660 (ro,loop=/dev/loop0)
     shows /mnt mount point

[root@bdxcatp1 mnt]# rflash bd01dn05-cec -p /mnt --activate disruptive
It may take considerable time to complete, depending on the number of systems being updated.  In particular, power subsystem updates may take an hour or more if there are many attached managed systems. Please waiting.
You can find the log files in the /var/log/xcatd/dfm/rflash/.
bd01dn05-cec: Not found the firmware package data in /tmp/fwupdate/

There is no log file created in /var/log/xcatd/dfm/rflash/

**Comment by zet809** [comment]
With the new dfm build(Not upload to fix central yet) and the latest hdwr_svr build(Have been uploaded to fix central), this issue is fixed.
