### ISSUE TITLE
Clean up xCAT created files when removing node definition objects

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1524]
If nodes are removed from xCAT database and machines are renamed, xCAT leaves around files in `/tftpboot` for example.  It would be good if xCAT's `rmdef` command handles the clean up so the user doesn't need to worry about rogue files on the management node.

**Comment by immarvin** [comment]
hi @whowutwut , currently, the ``def`` commands only manipulates the object definitions inside xCAT DB, they do process the entities related to the object definitions.  

Typically, we add a new command in this case, for example, ``rmdef -t osdistro ...`` vs ``rmosdistro``, ``rmdef -t osimage`` vs ``rmimage``. For the node definition, we have ``rmnodecfg`` and ``noderm`` , maybe we can enhance the commands like this instead of modifying ``rmdef`` command, which will break the current  code logic of the``def`` commands and make it more complicated (which has been complicated enough).

**Comment by daniceexi** [comment]
Original, our principles of design *def command is what @immarvin mentioned that keep *def just do DB operation and keep code simple. This is good for developer, but maybe not for user. For the scenario described in this issue that **rmdef** does not clean up the node configuration, then how user can do the configuration after the node has been removed?

So my idea is we can consider to add necessary action for **rmdef** command. But the following rules should be obeyed:
* Only add action when it's really necessary and explicit
* The code logic of action should be separated with *def itself (don't introduce more complicacy to *def code)

**Comment by whowutwut** [comment]
@immarvin @daniceexi  thanks for the discussions...   I think maybe some of this can be handled by improving the documentation.  If we better document the process for removing and cleaning up, maybe it won't be necessary to do things like this...  

We now provided a `rinstall` script to help users properly install, I think if we had something that would help users easily clean up node definitions, it would be beneficial.  

Something like: 

**Create Node Object Definitions:** 
```
mkdef <noderange>
rinstall <osimage> 
```
**Remove Node Object Definttions:**
```
rmnodecfg <node range> 
rmdef <noderange> 
```

Just ideas...

**Comment by gurevichmark** [comment]
@immarvin I was not able to find a command `rmnodecfg`. Is that an existing command, or were you proposing we create it ?
@whowutwut @daniceexi If we just choose to just improve documentation,  We can just say:

**Remove Node Object Definitions:**
```
nodeset <noderange> offline 
rmdef <noderange> 
```

**Comment by whowutwut** [comment]
@gurevichmark  I think it's in the tools directory `/opt/xcat/share/xcat/tools/rmnodecfg`

**Comment by gurevichmark** [comment]
@whowutwut Thank you. I see it there. 
Looking at the code it appears to only support nodes defined with `pxe` netboot option.

So now I have to ask, do we:
a. Fix `rmnodecfg` to work for other netboot options ?
b. Modify documentation to state that `rmnodecfg` only supports x86 `pxe` ?
