### ISSUE TITLE
xCAT command: lsdef , Errors do not return non zero return codes

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1530]
Issuing a `lsdef` command, when an Error occurs, does not return a correct return code to signify the error.  This makes is extremely hard to write a script and handle errors. ...

Success: 
```
[root@fs1 utilities]#  lsdef -c c910f03c25 -i mac | cut -d= -f2
98:be:94:00:c4:78
[root@fs1 utilities]# echo $?
0
```

Failure, still reports a 0 return code:
```
[root@fs1 utilities]#  lsdef -c c910f03c29 -i mac | cut -d= -f2
Error: Could not find an object named 'c910f03c29' of type 'node'.
[root@fs1 utilities]# echo $?
0
```

**Comment by gurevichmark** [comment]
@whowutwut Are you sure `echo $?` displays the RC from `lsdef` and not from `cut` ?
When I try `lsdef` by itself, it appears to display the RC correctly for me.

**Comment by whowutwut** [comment]
@gurevichmark  Thanks, I had a brain fart.
