### ISSUE TITLE
[dev]rest api does not support ipv6

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#154]
If the MN use ipv6 network, xcatd will use ipv6 network, but restapi does not support rest api;

**Comment by penguhyang** [comment]
may be we should use Net::INET6Glue::INET_is_INET6 to make IO::Socket::INET behave like IO::Socket::INET6

**Comment by bybai** [comment]
can not reproduce this issue.

**Comment by whowutwut** [comment]
We verified that restAPI can return IPv6 information?
