### ISSUE TITLE
Please remove duplicated test cases in each xCAT test bundle files

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1544]
In the xCAT Jenkins test environment, several test bundle files have duplicated test cases in them. Please remove the all the duplicated lines.

**Comment by neo954** [comment]
Below is a complete list. Please consider fix them all.

    $ find . -name '*.bundle' -exec echo {} ';' -exec bash -c 'sort {} | uniq -c | grep -v "1 "' ';'
    ./xCAT-test/autotest/bundle/le_rhels_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/le_sles_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/le_ubuntu_cmd.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/p_rhels_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/p_sles_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels6.7_ppc64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels6.7_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels6.8_ppc64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels6.8_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64le.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/rhels7.2_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles11.4_ppc64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles11.4_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles12.1_ppc64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles12.1_ppc64le.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles12.1_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles12_ppc64le.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/sles12_x86_64.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_ppc64le.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_x86_64.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_ppc64le.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_x86_64.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/x_rhels_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/x_sles_cmd.bundle
       2 nodels_tablevalue_tablecolumn
    ./xCAT-test/autotest/bundle/x_ubuntu_cmd.bundle
       2 lskitcomp_C
       2 nodels_tablevalue_tablecolumn

**Comment by neo954** [comment]
As a design principle, duplicate test cases in a single bundle file is meaningless and should be avoid. Since run a single test case more than once is just waste of time. And there is no way to represent the test result if the first run, second run, third run ... of a multiple-run single test case has failed.

In the case of multiple-run-single-test-case arrangement really has some meaning. I think the test case should be re-designed to avoid this.

**Comment by hu-weihua** [comment]
@neo954 , I have fixed this issue by pull request #1560, Could you please review and verify this fix? thanks.

**Comment by neo954** [comment]
Verified

    $ find . -name '*.bundle' -exec echo {} ';' -exec bash -c 'sort {} | uniq -c | grep -v "1 "' ';'
    ./xCAT-test/autotest/bundle/le_rhels_cmd.bundle
    ./xCAT-test/autotest/bundle/le_sles_cmd.bundle
    ./xCAT-test/autotest/bundle/le_ubuntu_cmd.bundle
    ./xCAT-test/autotest/bundle/p_rhels_cmd.bundle
    ./xCAT-test/autotest/bundle/p_sles_cmd.bundle
    ./xCAT-test/autotest/bundle/rhels6.7_ppc64.bundle
    ./xCAT-test/autotest/bundle/rhels6.7_x86_64.bundle
    ./xCAT-test/autotest/bundle/rhels6.8_ppc64.bundle
    ./xCAT-test/autotest/bundle/rhels6.8_x86_64.bundle
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64.bundle
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64le.bundle
    ./xCAT-test/autotest/bundle/rhels7.2_x86_64.bundle
    ./xCAT-test/autotest/bundle/sles11.4_ppc64.bundle
    ./xCAT-test/autotest/bundle/sles11.4_x86_64.bundle
    ./xCAT-test/autotest/bundle/sles12.1_ppc64.bundle
    ./xCAT-test/autotest/bundle/sles12.1_ppc64le.bundle
    ./xCAT-test/autotest/bundle/sles12.1_x86_64.bundle
    ./xCAT-test/autotest/bundle/sles12_ppc64le.bundle
    ./xCAT-test/autotest/bundle/sles12_x86_64.bundle
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_ppc64le.bundle
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_x86_64.bundle
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_ppc64le.bundle
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_x86_64.bundle
    ./xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle
    ./xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle
    ./xCAT-test/autotest/bundle/x_rhels_cmd.bundle
    ./xCAT-test/autotest/bundle/x_sles_cmd.bundle
    ./xCAT-test/autotest/bundle/x_ubuntu_cmd.bundle
