### ISSUE TITLE
Please fix all the CRLF line terminators in each xCAT test bundle files

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1545]
In the xCAT Jenkins test environment, several test bundle files have CRLF line terminators. Please fix them all.

    # file ubuntu14.04.4_ppc64le.bundle
    ubuntu14.04.4_ppc64le.bundle: ASCII text, with CRLF line terminators

**Comment by neo954** [comment]
Below is a completely list. Please consider fix them all. 

    $ find . -name '*.bundle' -exec file {} +
    ./xCAT-test/autotest/bundle/le_rhels_cmd.bundle:          ASCII text
    ./xCAT-test/autotest/bundle/le_sles_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/le_ubuntu_cmd.bundle:         ASCII text
    ./xCAT-test/autotest/bundle/p_rhels_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/p_sles_cmd.bundle:            ASCII text
    ./xCAT-test/autotest/bundle/rhels6.7_ppc64.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels6.7_x86_64.bundle:       ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels6.8_ppc64.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels6.8_x86_64.bundle:       ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64le.bundle:      ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/rhels7.2_x86_64.bundle:       ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles11.4_ppc64.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles11.4_x86_64.bundle:       ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles12.1_ppc64.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles12.1_ppc64le.bundle:      ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles12.1_x86_64.bundle:       ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles12_ppc64le.bundle:        ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/sles12_x86_64.bundle:         ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_ppc64le.bundle: ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_x86_64.bundle:  ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_ppc64le.bundle: ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_x86_64.bundle:  ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle:   ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle:    ASCII text, with CRLF line terminators
    ./xCAT-test/autotest/bundle/x_rhels_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/x_sles_cmd.bundle:            ASCII text
    ./xCAT-test/autotest/bundle/x_ubuntu_cmd.bundle:          ASCII text

**Comment by neo954** [comment]
This problem affected the xCAT Jenkins auto test facilities. Even if all the other scripts can handle the improper CRLF line terminators. But it need all the other scripts put extra effort on this kindle of handling. Put extra effort on these kind of things is meaningless.

All the source codes and configuration files on Unix/Linux environment should use LF as the line terminators.

**Comment by hu-weihua** [comment]
@neo954 , I have fixed this issue by pull request #1560, Could you please review and verify this fix? thanks.

**Comment by neo954** [comment]
Verified

    $ find . -name '*.bundle' -exec file {} +
    ./xCAT-test/autotest/bundle/le_rhels_cmd.bundle:          ASCII text
    ./xCAT-test/autotest/bundle/le_sles_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/le_ubuntu_cmd.bundle:         ASCII text
    ./xCAT-test/autotest/bundle/p_rhels_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/p_sles_cmd.bundle:            ASCII text
    ./xCAT-test/autotest/bundle/rhels6.7_ppc64.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/rhels6.7_x86_64.bundle:       ASCII text
    ./xCAT-test/autotest/bundle/rhels6.8_ppc64.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/rhels6.8_x86_64.bundle:       ASCII text
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/rhels7.2_ppc64le.bundle:      ASCII text
    ./xCAT-test/autotest/bundle/rhels7.2_x86_64.bundle:       ASCII text
    ./xCAT-test/autotest/bundle/sles11.4_ppc64.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/sles11.4_x86_64.bundle:       ASCII text
    ./xCAT-test/autotest/bundle/sles12.1_ppc64.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/sles12.1_ppc64le.bundle:      ASCII text
    ./xCAT-test/autotest/bundle/sles12.1_x86_64.bundle:       ASCII text
    ./xCAT-test/autotest/bundle/sles12_ppc64le.bundle:        ASCII text
    ./xCAT-test/autotest/bundle/sles12_x86_64.bundle:         ASCII text
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_ppc64le.bundle: ASCII text
    ./xCAT-test/autotest/bundle/ubuntu14.04.3_x86_64.bundle:  ASCII text
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_ppc64le.bundle: ASCII text
    ./xCAT-test/autotest/bundle/ubuntu14.04.4_x86_64.bundle:  ASCII text
    ./xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle:   ASCII text
    ./xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle:    ASCII text
    ./xCAT-test/autotest/bundle/x_rhels_cmd.bundle:           ASCII text
    ./xCAT-test/autotest/bundle/x_sles_cmd.bundle:            ASCII text
    ./xCAT-test/autotest/bundle/x_ubuntu_cmd.bundle:          ASCII text
