### ISSUE TITLE
Please update xCAT.spec and xCATsn.spec to have proper package dependency

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1547]
Since xCAT requires all the xCAT packages are on the same version level. xCAT should put all these requirement in its RPM spec file.

A proper fix of this bug should allow the end user to upgrade xCAT with a simple command.

```
 yum install xCAT
```

**Comment by neo954** [comment]
In this way, xCAT will not obfuscate rookie user after all. See issue #1523 as an example of how xCAT could obfuscate rookie user.

**Comment by neo954** [comment]
The bug is partly covered by the script ``go-xcat``. But I think even though we have ``go-xcat``, this is a bug of xCAT itself, and should be fixed properly.

**Comment by whowutwut** [comment]
:+1:  Nice @neo954  Yes, it would make things a lot easier to not use Wildcards and have the packages do exactly as they should

**Comment by daniceexi** [comment]
Good idea. Now I think we need a way to set the dependency version from the **Version** file instead of changing the .spec files for each Version change.

**Comment by zet809** [comment]
Will deal with this issue in 2.12.3.

**Comment by whowutwut** [comment]
Since this is a big change in behavior, should we deal with this and target a 2.13 release? Maybe we should have the changes in separate branch off of `xcat2/xcat-core` and we can test it separately, then if we feel it's good to go, we can merge it into master, instead of just directly merging into master?

**Comment by zet809** [comment]
The pull request #1659 and #1385 can fix this issue.

**Comment by neo954** [comment]
Verified with xCAT version 2.12.3-snap201609290802. This is the xCAT 2.12.3 GA version.

**Comment by neo954** [comment]
Failed to close this bug. re-open this one.

**Comment by neo954** [comment]
I reviewed pull request #1659 and #1385. I do not see any line related to this issue.

**Comment by neo954** [comment]
Verified with xCAT 2.12.3 GA version. And failed. This problem still exist.

**Comment by zet809** [comment]
We didn't add version number  for depended packages, will deal with it later.

**Comment by zet809** [comment]
Move to next release to do more investigation.

**Comment by neo954** [comment]
Since @zet809 did not spend time on this issue. I tried to fix this issue by myself.

**Comment by daniceexi** [comment]
@neo954 That's good. But we may not put this change in the 2.13 release since it's a little risky.

**Comment by neo954** [comment]
@daniceexi That is fine. Just merge this pull request after xCAT 2.13 GA.

**Comment by whowutwut** [comment]
@daniceexi @neo954  I don't think we want to merge this after the 2.13 GA..  I'm not sure we want to change the numbering of the RPM in a minor release of xCAT... we should consider moving this to 2.14.. or possible  creating a branch.. but this would cause additional effort for development.
