### ISSUE TITLE
makedns failed when input invalid hostname into /etc/hosts.  

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1553]
When input an  invalid host name into /etc/hosts, makedns shows below error : 

...........
Handling c712f10n02-ib1 in /etc/hosts.
Handling c712f9n05-ib0 in /etc/hosts.
Handling pops in /etc/hosts.
Ignoring host pops, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c712f9n05-ib1 in /etc/hosts.
Handling c712f11u30vc in /etc/hosts.
Handling c712f9n02-ib0 in /etc/hosts.
Handling c712f7bmc06 in /etc/hosts.
Handling c712f6n01 in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Updating DNS records, this may take several minutes for a large cluster.
Error: ddns plugin bug, pid 101552, process description: 'xcatd SSL: makedns for root@localhost: ddns instance' with error 'unexpected null domain label at /usr/lib64/perl5/vendor_perl/Net/DNS/Question.pm line 80.
new Net::DNS::RR( ... ) at /usr/lib64/perl5/vendor_perl/Net/DNS.pm line 414.
'

**Comment by daniceexi** [comment]
@wwzhubj could you add more detail for the issue like what kind of invalid hostname could cause this error?

**Comment by wwzhubj** [comment]
like    
9.114.75.32  .pok.stglabs.ibm.com c712f7n02

**Comment by bybai** [comment]
@wwzhubj , I want to confirm with you.
9.114.75.32 .pok.stglabs.ibm.com c712f7n02
ip is 9.114.75.32 ?
.pok.stglabs.ibm.com is domain without hostname?
c712f7n02 is short name?

**Comment by wwzhubj** [comment]
yes
