### ISSUE TITLE
Some bare metal machines can be booted up, some can't in Softlayer

### ISSUE THREAD

**Issue by mattcui** [xcat2/xcat-core#1559]
We used the same Softlayer API to order bare metal machines, we created netboot image with ixgbe driver, and used rinstall command to provision the netboot image to bare metal machines, it worked for some bare metal machines, but failed on some other ones, after running rinstall, the failed machines can't be logged in over SSH. Do you guys have some experiences on this? we ran lspci command to check the network kernel driver, it's ixgbe for all machines.

/cc @zhanggbj

**Comment by daniceexi** [comment]
Did you follow the doc (https://sourceforge.net/p/xcat/wiki/Using_xCAT_in_SoftLayer/) to perform the OS deployment ?

which version of xCAT you are using? show it with ``lsxcatd -a``.

**Comment by zhanggbj** [comment]
Hi @daniceexi , we are using xCAT 2.12.1 as below. Thanks.
# lsxcatd -a
Version 2.12.1 (git commit 0919bf649d99fc957236dbb42cfa3afc087ddad2, built Thu Jul  7 06:20:38 EDT 2016)
This is a Management Node
dbengine=SQLite

**Comment by daniceexi** [comment]
Please answer my question that whether you follow the doc (https://sourceforge.net/p/xcat/wiki/Using_xCAT_in_SoftLayer/)  that using the static ip for OS deployment so that I could tell you how to debug.

**Comment by zhanggbj** [comment]
@daniceexi Yes, we are using static ip. And I'm also comparing our scripts with the doc you mentioned. Thanks a lot for helping:)

**Comment by zhanggbj** [comment]
I noticed new release 2.12.1 have some cool new features, like rintall enhancement and xcatprobe tool, so I upgrade xCAT in my environment. Unfortunately, this issue still remains. I tried to do some debug on os deployment but didn't find any valuable information. Could you please help to take a look and provide some more precise debug instructions. Thanks a lot:) 

## Environment:
**xCAT version**
root@d2b177f8-ca90-4c9c-bd1c-cce197ebc0a0:~# lsxcatd -a
Version 2.12.1 (git commit 0919bf649d99fc957236dbb42cfa3afc087ddad2, built Thu Jul  7 06:20:38 EDT 2016)
This is a Management Node
dbengine=SQLite

**xCAT management node os**
root@d2b177f8-ca90-4c9c-bd1c-cce197ebc0a0:~# uname -a
Linux d2b177f8-ca90-4c9c-bd1c-cce197ebc0a0 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**baremetal os**
CentOS7.0-64 Minimal for Bare Metal

## OS deployment steps:
Here is the link os our scipts. I compared with  https://sourceforge.net/p/xcat/wiki/Using_xCAT_in_SoftLayer/ but not sure we are doing the right way 100%, so if would be great if you could help us to take a review. @daniceexi @bybai 
**xCat management node config**
https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server-release/blob/master/jobs/xcat-server/templates/xcat_ctl.erb

**node provisioning**
https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server/blob/master/scripts/install_node_xcat.sh

## Debug:
Hi @daniceexi, I checked httpd log on /var/log/apache2/access_log, I didn't find too much difference between the successful and failed node, or maybe I'm missing something. Is there any key word or item I should focus on?

Hi @bybai, I'm not familiar with that, do you mean setup conserver as below?
https://sourceforge.net/p/xcat/wiki/Debugging_xCAT_Problems/#setup-conserver

**Comment by daniceexi** [comment]
@zhanggbj , is it possible for @bybai to log in your xCAT MN to take a look what happened?

**Comment by zhanggbj** [comment]
Hi @daniceexi 

It seems @bybai is offline today and I'll try to contact her tomorrow. At the same time, I re-compared the successful and failed node and found some more details. Hope these can provide some more debug information. Would you please help to take a look and provide some instructions on further investigation？Thank you.

**httpd log**

for successful node, there are lots of files transported from server to node like /tftpboot/xxx and /install/xxx as below.
```
10.113.189.207 - - [15/Aug/2016:10:01:26 +0000] "GET /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/initrd-stateless.gz HTTP/1.1" 200 53877286 "-" "iPXE/1.0.3-130626"
......
10.113.189.207 - - [15/Aug/2016:10:01:53 +0000] "GET //install/netboot/ubuntu14.04.3/x86_64/compute/rootimg.gz HTTP/1.1" 200 187679289 "-" "Wget/1.15 (linux-gnu)"
......
10.113.189.207 - - [15/Aug/2016:10:01:58 +0000] "GET /install/postscripts/ HTTP/1.1" 200 23680 "-" "Wget/1.15 (linux-gnu)"
```

but for failed node, it only get serveral files of /tftpboot/xxx from server and it seems that none file of /install/xxx is transported.
```
10.113.109.112 - - [15/Aug/2016:10:08:28 +0000] "GET /tftpboot/xcat/xnba/nodes/baremetal-165-20160809-153106-642 HTTP/1.1" 200 664 "-" "iPXE/1.0.3-130626"
10.113.109.112 - - [15/Aug/2016:10:08:28 +0000] "GET /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/kernel HTTP/1.1" 200 6566178 "-" "iPXE/1.0.3-130626"
10.113.109.112 - - [15/Aug/2016:10:08:29 +0000] "GET /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/initrd-stateless.gz HTTP/1.1" 200 53877286 "-" "iPXE/1.0.3-130626"
10.113.205.212 - - [15/Aug/2016:11:48:18 +0000] "GET /tftpboot/xcat/xnba/nodes/baremetal-165-20160809-153119-967 HTTP/1.1" 200 664 "-" "iPXE/1.0.3-130626"
10.113.205.212 - - [15/Aug/2016:11:48:18 +0000] "GET /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/kernel HTTP/1.1" 200 6566178 "-" "iPXE/1.0.3-130626"
10.113.205.212 - - [15/Aug/2016:11:48:19 +0000] "GET /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/initrd-stateless.gz HTTP/1.1" 200 53877286 "-" "iPXE/1.0.3-130626"
```
**Node Configurations files in /tftpboot/xcat/xnba/nodes/**
for successful node:
```
root@44a3774a-2d7d-4574-86fb-b747e840c22f:/tftpboot/xcat/xnba/nodes# cat baremetal-165-20160809-153054-701
#!gpxe
#boot
sanboot --no-describe --drive 0x80
```
for failed node:
```
root@44a3774a-2d7d-4574-86fb-b747e840c22f:/tftpboot/xcat/xnba/nodes# cat baremetal-165-20160809-153106-642
#!gpxe
#netboot ubuntu14.04.3-x86_64-compute
imgfetch -n kernel http://${next-server}/tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/kernel
imgload kernel
imgargs kernel imgurl=http://${next-server}//install/netboot/ubuntu14.04.3/x86_64/compute/rootimg.gz XCAT=${next-server}:3001  LOGSERVER=${next-server}  xcatdebugmode=1  BOOTIF=01-${netX/machyp}
imgfetch http://${next-server}/tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/initrd-stateless.gz
imgexec kernel
```

These are the differences I found. And BTW, I started `xcatprobe osdeploy -n <node>` before I do provision, but it seems nothing is captured. Am I missing something here? Thank you.

**Comment by zet809** [comment]
Are you able to open console for the failed node to take a look at what the current state is? Can you get the console output?

**Comment by bybai** [comment]
Hi @zhanggbj ,
After pushinitrd command, could you try this?
To login the failed node, and check  /boot/grub/menu.list with right ip netmask gateway, then did rsetboot and rpower reset command in xcat MN.

**Comment by bybai** [comment]
@zhanggbj , systems from softlayer should have OS, so you can refer to doc: https://sourceforge.net/p/xcat/wiki/Using_xCAT_in_SoftLayer/, then you can check if menu.list correct or not.

**Comment by zhanggbj** [comment]
Hi @bybai ,
Last week we did some offline debug with @immarvin.  Here are some updates and progress for your reference. Thanks.

1. Tried `pushinitrd` command after nodeset, but got errors as below. And it seems like that `pushinitrd `is for `diskful` and we are using `diskless`. So didn't go further to check menu.list
```
root@44a3774a-2d7d-4574-86fb-b747e840c22f:~# pushinitrd baremetal-165-20160809-153106-642
Copying /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/kernel to baremetal-165-20160809-153106-642:/boot/bps-netboot-ixgbe-lon02-kernel
baremetal-165-20160809-153106-642: Warning: Permanently added 'baremetal-165-20160809-153106-642,10.113.109.112' (ECDSA) to the list of known hosts.

Copying /tftpboot/xcat/osimage/bps-netboot-ixgbe-lon02/initrd-stateless.gz to baremetal-165-20160809-153106-642:/boot/bps-netboot-ixgbe-lon02-initrd-stateless.gz
baremetal-165-20160809-153106-642: Warning: Permanently added 'baremetal-165-20160809-153106-642,10.113.109.112' (ECDSA) to the list of known hosts.

Running modifygrub on baremetal-165-20160809-153106-642 to update the grub configuration.
baremetal-165-20160809-153106-642: Warning: Permanently added 'baremetal-165-20160809-153106-642,10.113.109.112' (ECDSA) to the list of known hosts.

baremetal-165-20160809-153106-642: bash: /tmp/fileZYARkf.dsh: /usr/bin/perl: bad interpreter: No such file or directory
Error: rc 1 return from cmd: xdsh baremetal-165-20160809-153106-642 -l root -e /opt/xcat/bin/modifygrub -w 75 -p netboot bps-netboot-ixgbe-lon02-kernel bps-netboot-ixgbe-lon02-initrd-stateless.gz "'"'imgurl=http://!myipfn!//install/netboot/ubuntu14.04.3/x86_64/compute/rootimg.gz XCAT=!myipfn!:3001 LOGSERVER=!myipfn! xcatdebugmode=1 '"'" 10.112.116.26 2>&1
```

2. Logged on remote console and run `rinstall` with failed node. It failed with error 
```
Couldn't find the proper booting device, switch to shell ...
```

3. (in progress) @immarvin sent me an new netboot image and I'll try step2 and will update result here.

**Comment by zhanggbj** [comment]
Tried with the new netboot image, but reboot failed at the same stage. Have updated screenshot and whole reboot process to @immarvin for further debug. Thanks.

**Comment by immarvin** [comment]
any update?

**Comment by zhanggbj** [comment]
HI @immarvin ， I sent an email with reboot result to you on 9th, Sep using the latest netboot image you gave to me. Please take a look:)

**Comment by bybai** [comment]
Hi @zhanggbj, could you issue fix until now?

**Comment by zhanggbj** [comment]
Not yet.  This issue still can be reproduced sometimes.

**Comment by immarvin** [comment]
no response from creator, will close it first, please reopen it if any update
