### ISSUE TITLE
Problem using xCat on Knights Landing (Xeon Phi)

### ISSUE THREAD

**Issue by JBBIntel** [xcat2/xcat-core#1572]
I have been trying to get xCat to work on some KNL Xeon Phis. I was able to get through discovery, but the stateless osimage hangs. Has anyone been successful using stateless images with KNL? Are there known issues?

**Comment by daniceexi** [comment]
xCAT have not been maintaining  the Xeon Phi support for a while. Could send an email to maillist for help?

**Comment by chrissamuel** [comment]
@daniceexi from the mailing list this is about Knights Landing (KNL) nodes - not the old Knights Corner KNC accelerator cards!   These are compute nodes in their own right so it would be good to support them especially as major vendors are deploying them now.

**Comment by zet809** [comment]
Will close is issue and reopen it if there is any concerns.
