### ISSUE TITLE
Request support for RHEV for OpenPower

### ISSUE THREAD

**Issue by lxguang** [xcat2/xcat-core#1573]
Hi !
The LTC strategy for virtualization is changing.  RHEV and Ubuntu KVM are now the strategic virtualization approaches (hypervisors).  PowerKVM will be sunset in the near future.  For our work, with RHEL being the most relevant OS, RHEV will be our strategic hypervisor.
It is highly desired to have RHEV 3.5 or 3.6/4.0 enablement for OpenPower/Power8 on Habanero or Tuleta in XCAT.  
Please let me know the instructions to install RHEV hypervisor onto Habanero/Tuleta.
Thanks.
XiaoGuang Liu

**Comment by daniceexi** [comment]
@lxguang You can download the rhev-h for power from the ftp3:/redhat/release_cds/RHEV/ppc64

@immarvin Since xCAT has supported the rhev for x86_64, could you try to install the rhev/ppc64 with xCAT?

**Comment by lxguang** [comment]
Hi,
I just need to install RHEV onto OpenPower/ppc64le instead of ppc64.
The ftp3 location(ftp://ftp3.linux.ibm.com/redhat/release_cds/RHEV/) has no
iso media for ppc64le.
It is required to support Habanero for RHEV.



----------------------------------------------------------------------------

 Jack Liu (刘晓光)
 IBM China Systems and Technology Laboratory(CSTL)
 Tel:    86-10-82450821
 Email:  lxguang@cn.ibm.com
 Address: Building 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West
Road
          Haidian District Beijing P.R.China  100193
          北京市海淀区东北旺西路8号中关村软件园28号楼
          环宇大厦 3YW026          邮编：100193
-----------------------------------------------------------------------------

**Comment by daniceexi** [comment]
@lxguang Yes, currently there's only ``ppc64`` version of RHEV on ftp3. But base on our experience that Habanero should support ppc64 system well. So we will try this ppc64 version first. And could you send an email to ask the one who announce the RHEV support that where to get the ppc64le version?

**Comment by lxguang** [comment]
RHEV 3.6 on POWER for use with RHEL7.2 on ppc64le
(as made initially available by Red Hat at 01/28/2016 on RHN through https://access.redhat.com/errata/product/279/ver=/rhel---7/ppc64le/RHBA-2016:0080 ...)
is available on ftp3 ...

... please see the related ftp3 directories (with all recent RHN updates for RHEV ...) at
https://ftp3.linux.ibm.com/files/redhat/power-le/7/7.2/ppc64le/rhev-mgmt-agent/3/os/
and
https://ftp3.linux.ibm.com/files/redhat/power-le/7/7.2/ppc64le/rhev-tools/3/os/ 
and with the _ppc64_ related packages available at
https://ftp3.linux.ibm.com/files/redhat/rhev-3-ppc64/   or more specific for RHEL7.2 at  https://ftp3.linux.ibm.com/files/redhat/rhev-3-ppc64/7/7.2/ppc64/rhev-tools/3/os/  ...

... RHEV documentation is available from Red Hat at https://access.redhat.com/documentation/en/red-hat-enterprise-virtualization/?version=3.6
and especially for RHEV on POWER at
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.6/html/Release_Notes/chap-RHEV_for_IBM_Power.html ...

... please especially consider the "System Requirements" for RHEV as outlined at 
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.6/html-single/Installation_Guide/index.html#chap-System_Requirements
and also the base RHEL and RHEV limits from
https://access.redhat.com/articles/rhel-limits  and  https://access.redhat.com/articles/rhel-kvm-limits ...

Please note that your RHEL7.2 ppc64le system has to be updated to the most current 7.2.z zstream level before you can use RHEV on POWER with it
ie. please consider the ftp3 web site about "Red Hat Enterprise Linux Updates" at https://ftp3.linux.ibm.com/redhat_updates.php ...
FWIW.. there is also a RHEV 4.0 Beta, leading to expected GA end of August 2016.  This latter is RH CONFIDENTIAL, as I don't believe they have announced yet.

**Comment by zet809** [comment]
Move to next release to do more investigation.

**Comment by gurevichmark** [comment]
@whowutwut Can this issue now be closed, since we documented the process in pr #1979 ?

**Comment by whowutwut** [comment]
@zet809 @immarvin  Mark created a pull request documenting the current steps for creating a RHEV hypervisor for open Power.  As of now, there is no .iso support for the rhev on Power, so I think we should close this and re-open at a later date if an .iso file is provided...

**Comment by immarvin** [comment]
thanks @gurevichmark 

hi @whowutwut , do you the RHEV support should be covered by FVT in this or next release?

**Comment by whowutwut** [comment]
@immarvin  I think depends on the workload of FVT, I think they should focus on creating more automation cases and strengthen the reliability of the framework.  Development will be exercising this for scale testing.
