### ISSUE TITLE
xCAT-test framework does not allow for . in testcase names

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1583]
New to looking at xCAT-test autotest framework... 

When trying to create a new testcase for testing xcat.org, in the `start:`  field, I used `xcat.org_xxx`.  Looks like a name with a period in it , ignores everything after the period. 

Here's the new testcase that I created:
```
$ cat xCAT-test/autotest/testcase/xcat.org/cases* | grep "start"
start:xcatorg_devel_repo
start:xcat.org_2.12
```

but when running xcattest -l , anything after the . is ignored... 
```
# xcattest -l 
...
...
xdsh_o
xdshbak_h
xdshbak_display
xdshbak_c
xdshbak_q
xdshbak_x
xcatorg_devel_repo
xcat   <--------------------  this is the xcat.org_2.12 testcase
```

This is OK to not support periods in the name, but is there a way that we can inform the user that the testcase created is invalid?  OR there's a problem in the testcase name? 

If I create multiple testcases with names like: 
```
xcat.org_devel_public_repo
xcat.org_devel_public_download
xcat.org_2.12_public_repo
xcat.org_2.12_public_download
```
Then on the `xcattest -l` list, we would see... .
```
xcat
xcat
xcat
xcat
```

**Comment by hu-weihua** [comment]
@whowutwut ,  you are right,  depending on below code, we don't support ``.`` in the test case name, the valid characters are ``a-z A-Z 0-9 _ - ``  .

     534             if ($line =~ /^start\s*:\s*([\w-]+)/) {
     535                 $skip = 0;

**Comment by caomengmeng** [comment]
@whowutwut @hu-weihua 
1. The function name can only contains: a-z A-Z 0-9 _ - , I also agree, this makes sense. 
2. How to make the output more friendly:
   2.1 update xcattest man page to make the function name more clearly
   2.2 update xcattest command to output message when the function name contain other characters that not allowed.
How to you think?

**Comment by hu-weihua** [comment]
@caomengmeng, I think we should use code to offer helpful message. Man page isn't visually. In fact not all the customer read man page ahead.

**Comment by caomengmeng** [comment]
@hu-weihua  Yes，2.2 means output messages.

**Comment by caomengmeng** [comment]
@whowutwut @daniceexi 
Fixed this issue with below output messages:
```
[root@c910f02c08p12 bin]# xcattest -c test -l
******************************
loading test cases
******************************
*Test cases:
test_1
test_2-2
*Case name not supported, please use 'a-zA-Z0-9_-' :
test_1.1
test_2-2*3
```

**Comment by whowutwut** [comment]
Verified on the latest build, I am able to see the xcat.org naming

```
cd /opt/xcat/share/xcat/tools/autotest/testcase
mkdir xcat.org
echo "start:xcatorg_devel_repo" >> xcat.org/cases0
xcattest -s command | grep xcat.org
...
xcat.org
```
