### ISSUE TITLE
xCAT-test framework needs a way to view available test cases in bundles 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1584]
New to trying out the `xcattest` command and I'm trying to query the bundles and figure out what is available.  I find it difficult to connect the dots to understand what cases are available for me to execute.   Here's some issues that I see... 

1) Unnecessary output in `xcattest -l` where we are printing out the list of files under the testcase directory...    Running `xcattest -l`  prints out:

```
# xcattest -l 
/opt/xcat/share/xcat/tools/autotest/testcase/addkit/cases0
/opt/xcat/share/xcat/tools/autotest/testcase/addkitcomp/case0
/opt/xcat/share/xcat/tools/autotest/testcase/analyze_log/case0
/opt/xcat/share/xcat/tools/autotest/testcase/bmcdiscover/cases0
/opt/xcat/share/xcat/tools/autotest/testcase/buildkit/cases0
....
....
```

What is the purpose for displaying the casesX files under each directory?  It causes confusion in my next issue. 

2) Specify a wrong bundle name does not invoke an error 

I tried running: `xcattest -b x_sles_cmd -l`, but the actual bundle name is `x_sles_cmd.bundle`.   The output of the command is the output specified in 1) above.  Since something is displayed, I think my command is correct.  But it's really not.    Only when I did the command twice  on different bundles incorrectly do I see there is something wrong... 

```
# xcattest -b x_sles_cmd -l > /tmp/v1
# xcattest -b x_ubuntu_cmd -l > /tmp/v2
# diff /tmp/v1 /tmp/v2
#
```

What I would like to see is something like the following:

```
# xcattest -b x_ubuntu_cmd -l
Error: Bundle named 'x_ubuntu-cmd' does not exist. 
Use 'xcattest -b -l' to list out available bundles
```

3) There's no way to currently get a list of bundles that we can display

Following up with 2) above, there's no way to list the current bundles besides looking at the file names: `ls -1 /opt/xcat/share/xcat/tools/autotest/bundle/`

Having an interface to query the bundles would help and we could add it to the error message in 2)

**Comment by caomengmeng** [comment]
@whowutwut 
Agree with you for 1) 2) and will fix them
But for 3），as bundle files are defined by users themselves, they are just some files, so I don't think it is necessary to show them by some xCAT command. Just like the xCAT logs files created by xCAT, we don't need to support some xCAT commands to show users them.

**Comment by tingtli** [comment]
@whowutwut @caomengmeng we can think of providing way to list the bundle files. Then , users who wants to use the bundle file  can know which bundle file they could use, users don't need to rewritten a bundle file themselves.

**Comment by tingtli** [comment]
How about we provide 2 options. 1 option to display  all the bundle name, 1 option to display the bundle files contents?
e.g
xcattest -b -l means to list all the bundle files names.
xcattest -b xxx.bundle -l to list the xxx.bundle files contents

**Comment by hu-weihua** [comment]
@tingtli @whowutwut , I agree to list bundle files we have by command, but just list bundle files name or test case names may be not helpful enough, because user can't get what the bundle file or test case is used for through a simple name. May be show the description of one bundle or one test case at same time is helpful.  for example:

    #xcattest -b -l 
    le_rhels_cmd.bundle         : description 
    le_sles_cmd.bundle          : description 
    le_ubuntu_cmd.bundle        : description 
    .........

    #xcattest -b xxx.bundle -l 
    makehosts_h                : description 
    makehosts_help             : description 
    makehosts_n                : description 
     ........

**Comment by daniceexi** [comment]
@hu-weihua 👍

**Comment by caomengmeng** [comment]
@hu-weihua 
For these bundle files without os-arch.bundle names, they are not used for daily run now, and  I will delete them from the folder.
Then all the bundle files that will be shown are the os-arch.bundle files. The file name makes it clearly when they will be used, so do think a description is still needed for xcattest -b -l. If yes, that means there should be a description in all bundle files.

**Comment by caomengmeng** [comment]
@tingtli @whowutwut 
If we show bundle files by xcattest command, that means the bundle files must be meaningful to users as they are not examples to help users write one by themselves, they are formally ones released by xCAT product. 

Then, there are two questions:
1. Do users use the bundle files we listed directly? Take "rhels7.2_ppc64.bundle" as an example: if users use it directly, then they will install their CN with diskful installation, run commands, diskless installation flat, statelite installation flat, SN installation, diskful hierarchy, diskless hierarchy, statelite hierarchy, statelite hierarchy by ramdisk, statelite hierarchy by nfs, finally two migration processes and clean up environment, Do users need to do so many things as we run daily regression in there real test environment? Is this meaningful for them?
2. If they use our bundle files directly, and if they want' all test cases passed, they should define in their own default.conf with all vars, do they need to many works, to use xcattest? 

So what is the meaning for bundle files to xCAT users? Just a example to help them to write their own ones, or others, Maybe we should make this clearly firstly. 
If not examples but formally ones, what should be listed, and how to explain clearly to users that @hu-weihua mentioned should be taken into consideration and discussed firstly.

**Comment by daniceexi** [comment]
@caomengmeng As we discussed today that the bundle files are used for xCAT team basically. So all this requirement is for xCAT FVT and DEV to aware the test case list for daily run since we are using bundle to include the test cases.

**Comment by whowutwut** [comment]
Right, this is more for internal use.  If more members of the team are able to understand what is being executed, we might be able to better leverage this framework, moving to 2.12.3 since it's been idle for a while.

**Comment by caomengmeng** [comment]
@whowutwut 
1. there is no "xcattest -l" now:
```
[root@c910f02c08p12 ~]# xcattest -l
Error: please define options correctly
Usage:
Run xcat test cases:
  xcattest [-?|-h]
  xcattest [-f configure file] [-b case bundle files]
  xcattest [-f configure file] [-t cases list]
  xcattest [-f configure file] [-c cmds list]
  xcattest [-f configure file:System] [-t case list]
Show xcat test cases, bundle files, commands lists:
  xcattest [-f configure file] [-b case bundle files] [-l]
  xcattest [-f configure file] [-t cases list] [-l]
  xcattest [-f configure file] [-c cmds list] [-l]
  xcattest [-bl]
  xcattest [-cl]

```

For 2 and 3:
will also update man page to make it clear: the bundle file should be "*.bundle" file under the /opt/xcat/share/xcat/tools/autotest/bundle/
```
[root@c910f02c08p12 bin]# xcattest -b xxxx -l
Error: please input the .bundle file
Usage:
Run xcat test cases:
  xcattest [-?|-h]
  xcattest [-f configure file] [-b case bundle files]
  xcattest [-f configure file] [-t cases list]
  xcattest [-f configure file] [-c cmds list]
  xcattest [-f configure file:System] [-t case list]
Show xcat test cases, bundle files, commands lists:
  xcattest [-f configure file] [-b case bundle files] [-l]
  xcattest [-f configure file] [-t cases list] [-l]
  xcattest [-f configure file] [-c cmds list] [-l]
  xcattest [-bl]
  xcattest [-cl]

[root@c910f02c08p12 bin]# xcattest -b xxxx.bundle -l
Error: Can't open bundle file: xxxx.bundle
Use 'xcattest -bl' to list out available bundles
Usage:
Run xcat test cases:
  xcattest [-?|-h]
  xcattest [-f configure file] [-b case bundle files]
  xcattest [-f configure file] [-t cases list]
  xcattest [-f configure file] [-c cmds list]
  xcattest [-f configure file:System] [-t case list]
Show xcat test cases, bundle files, commands lists:
  xcattest [-f configure file] [-b case bundle files] [-l]
  xcattest [-f configure file] [-t cases list] [-l]
  xcattest [-f configure file] [-c cmds list] [-l]
  xcattest [-bl]
  xcattest [-cl]
```

**Comment by whowutwut** [comment]
Reviewing the changes, is it possible to list out the bundle files if we pass : `xcattest -b -l` without a bundle name?  The only reason I am asking this is because in order to see the bundle name, we have to go to `/opt/xcat/share/xcat/tools/autotest/bundle` directory.   However, we don't need to be in that directory to issue the command.  

So why not just print the bundle lists available to query.... 

External would be: 
```
> xcattest -b -l
rhels6.7_ppc64.bundle
rhels6.7_x86_64.bundle
rhels6.8_ppc64.bundle
...
ubuntu16.04_ppc64le.bundle
ubuntu16.04_x86_64.bundle
> xcattest -b rhels6.7_x86_64.bundle -l
...
...
xdsh_o
```

**Comment by caomengmeng** [comment]
@whowutwut 
yes, there is ```xcattest -s bundle|commad``` to show the bundle files and commands now
Below is to show the bundle files and descriptions in bundle files.
```
c910f02c01p14:~ # xcattest -s bundle
bundle files and descriptions:
ubuntu14.04.4_x86_64.bundle     No description, add "description: details" in this bundle file
rhels7.2_ppc64le.bundle         No description, add "description: details" in this bundle file
sles12_ppc64le.bundle           No description, add "description: details" in this bundle file
rhels7.3_ppc64le.bundle         No description, add "description: details" in this bundle file
rhels7.3_ppc64.bundle           No description, add "description: details" in this bundle file
```

````
c910f02c01p14:~ # xcattest -s command
xcatd
tabrestore
makehosts
rvitals
restorexCATdb
chkosimage
gettab
```

**Comment by whowutwut** [comment]
👍  Thanks!

**Comment by caomengmeng** [comment]
@whowutwut please help to verify this issue, all related codes are merged yesterday.

**Comment by whowutwut** [comment]
Ok, I have verified, thanks!
