### ISSUE TITLE
Enhance xCAT-test framework to display components/commands 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1585]
The `xcattest` command has a `-c` option to specify the command list.  Can we enhance the command to have an option that will display the possible commands/components that is available to select and run? 

For example:  `xcattest -c -l` 
Without specifying a command list, we will display all possible commands that are available to specify

**Comment by daniceexi** [comment]
@whowutwut If you don't object, we hope our FVT could take the responsibility to enhance our automation framework. So I assign this issue to @caomengmeng

**Comment by whowutwut** [comment]
@daniceexi  Sure, I think what I was trying to understand is how we can use the `xcattest` command to figure out what testcases can be run without the need to edit and view the `casesX` files

**Comment by caomengmeng** [comment]
@whowutwut  just take this into consideration now, and there are two ways, firstly, get the commands automated by code, that depends on the current existed all cases, I will make deep research about the commands and cases relationship. secondly, to maintain a list by a file, while there are cases added, this file should be updated.

**Comment by daniceexi** [comment]
@caomengmeng I think that make the code to read all the available command in run-time will be better. We should ignore to maintain a list which can be calculated automatically.

**Comment by caomengmeng** [comment]
@whowutwut  @daniceexi 
Fixed this issue with a new option: -cl, it will shows all the commands.
And commands means: the folder name under the "/opt/xcat/share/xcat/tools/autotest/" and there is "case*" file under this folder, for example:
/opt/xcat/share/xcat/tools/autotest/lsdef/cases0
"/opt/xcat/share/xcat/tools/autotest/" is the default folder for testcases.
sub-folder name is recognized as a command, only when there is case* file with test cases in this sub-folder, all these will be explain clearly in man page. 
```
[root@c910f0p12 ~]# xcattest -cl
******************************
show commands list
******************************
addkit
addkitcomp
analyze_log
bmcdiscover
buildkit
chdef
chkkitcomp
chkosimage
chtab
chvm
confignics
copycds
dockercommand
dumpxCATdb
genesis
genimage
geninitrd
getmacs
gettab
go-xcat
go-xcat
go-xcat
imgexport
imgimport
lsdef
lskit
lskitcomp
lskitdeployparam
lslite
lsvm
lsxcatd
makeconservercf
makedhcp
makedns
makehosts
makeknownhosts
makenetworks
makentp
makeroutes
mkdef
mkdsklsnode
mknimimage
mkvm
ngpfb
nodeadd
nodech
nodegrpch
nodels
noderange
noderm
nodeset
nodestat
packimg
pkg
pping
ppping
prsync
pscp
psh
regnotif
renergy
renergy
restapi/global
restapi/group
restapi/network
restapi/node
restapi/node
restapi/osimage
restapi/policy
restapi/service
restapi/table
restartxcatd
restorexCATdb
reventlog
rinv
rmdef
rmdsklsnode
rmkit
rmkitcomp
rmnimimage
rmvm
rpower
rscan
rspconfig
runcmdinstaller
rvitals
sinv
switchdiscover
sysclone
tabdump
tabgrep
tabprune
tabrestore
testenv
unregnotif
updatenode
xcat2nim
xcatconfig
xcatd
xcatdebugmode
xcatsnap
xcatstanzafile
xdcp
xdsh
xdshbak
```

**Comment by whowutwut** [comment]
@caomengmeng  I am looking at your last comment to validate this issue..  

On a brand new install of `xCAT-test`, there are some 2 issues... 
```
[root@fs4 xdsh]# xcattest -s command
Useless use of reference constructor in void context at /opt/xcat/bin/xcattest line 219.
Error: Can't open config file: /opt/xcat/share/xcat/tools/autotest/default.conf
...
```
1) You must have a default.conf file in order for the command to work, but it's not looking at the file at all.  I just `touch default.conf` and the command worked.  So we should bypass this check. 
2) The `Useless use of reference..`.  message should be fixed.

**Comment by whowutwut** [comment]
The 2) item above is brought up by Issue #2021 , so only question is regarding the 1st comment above

**Comment by hu-weihua** [comment]
@whowutwut ,  long time ago, xCAT_test shipped a ``default.conf`` file. But for some reason, FVT dropped this file but the code didn't change. I have told @caomengmeng , she will change the code to fix the first problem you mentioned above.

**Comment by caomengmeng** [comment]
@whowutwut @hu-weihua @tingtli
submit a new issue, for this: https://github.com/xcat2/xcat-core/issues/2053
If the -f is not used in xcattest command, that means the default.conf is used every time xcattest comand is executed.
@whowutwut, please verify this issue with a config file to avoid this default.conf is deleted issue?

**Comment by whowutwut** [comment]
@caomengmeng  FYI, I added the Issue number to the pull request to create that link above... which we can easily see the status of the pull request....  

The pending should only be set when the code has been merged so that the originator can verify it with the daily build.  Right now it's still Open state.

**Comment by caomengmeng** [comment]
@whowutwut all related codes are merged yesterday, please help to verify this issue.

**Comment by whowutwut** [comment]
Verified on the RC1 build, it is OK,  
```
xcattest -s bundle 
xcattest -s command
``` 
will display bundle names and command names 

I do think the bundles should also contain descriptions, instead of `No description, add with "description: details" in bundle file`
