### ISSUE TITLE
Genesis loading hang in firestone node if ntp time offset is too large

### ISSUE THREAD

**Issue by DanielXLee** [xcat2/xcat-core#1591]
Sometimes, genesis loading hang at the script `/usr/bin/doxcat` in Firestone node, and we found the progress stayed at the below while statement for a long time due the large `ntp` offset in node:

----------------------------

```
ntpd -g -x
# rv 0 state does not work with the new ntp versions
while [ "`ntpq -c \"rv 0 offset\" | grep \"offset=\" | awk -F \"=\" '{print $2}' | awk -F \".\" '{print $1}' | sed s/-//`" -ge 1000 ]; do
    sleep 1
done
```
--------------------
```
[xCAT Genesis running on io155 /]# ntpq -c "rv 0 offset"
offset=1604.980
```
--------------------------

In fact, the unit of value of offset is milliseconds, and 1000 ms is too little to identify ntp service. By default, the threshold is 1000s(1000000 ms) for ntpd exiting with a message to the system log if the offset exceeds the panic threshold
So suggest to change the limitation of offset in script `/usr/bin/doxcat`

**Comment by neo954** [comment]
More then 1000ms time offset in a NTP network environment is quiet abnormal. In regular gigabit ethernet network environment, the typical time offset between NTP server and NTP client is less than 5ms. Even in wide area network environment, the offset is less than 50ms.

**Comment by wjianf** [comment]
In IBM OpenPower Firestone node provisioning, the value of offset is in 50 to 1000 ms when xCAT genesis loading in most time, but sometimes, the value is greater than 1000 ms, and the adjustment is very slow. So the provisioning process sames like hang at the scripts doxcat.

**Comment by zet809** [comment]
Move to next release to reconsider this issue.

**Comment by neo954** [comment]
This is the real problem. Cannot access the hardware clock. :(

    [xCAT Genesis running on c910f03c25 /]# hwclock
    hwclock: Cannot access the Hardware Clock via any known method.
    hwclock: Use the --debug option to see the details of our search for an access method.

**Comment by neo954** [comment]
This is the correct shape on another Firestone machine runs RHEL 7.3 Beta. It seems we really need the kernel module `rtc_opal` in genesis for Firestone machine.

    [root@c910f05c35 ~]# hwclock
    Wed 24 Aug 2016 03:41:42 AM EDT  -0.693350 seconds
    [root@c910f05c35 ~]# ls -l /dev/rtc*
    lrwxrwxrwx 1 root root      4 Aug 17 22:54 /dev/rtc -> rtc0
    crw------- 1 root root 254, 0 Aug 17 22:54 /dev/rtc0
    [root@c910f05c35 ~]# lsmod | grep rtc
    rtc_opal                4993  0

**Comment by neo954** [comment]
I think xCAT needs a least include `rtc-opal.ko` in genesis. Further more, xCAT needs to include all the kernel modules Fedora shipped in genesis as well. Since xCAT rely on genesis to do the hardware detecting. xCAT shipped genesis has to be in the right shape.

**Comment by whowutwut** [comment]
Do we need to recreate the Genesis base?

**Comment by zet809** [comment]
@whowutwut I have build a genesis-base ppc64 and have PCM team to try that, if this defect is fixed, I will commit both the modification and the genesis-base package.

**Comment by whowutwut** [comment]
👍

**Comment by wjianf** [comment]
With the fixes, ntp offset changed to 0 after genesis loaded 10 minutes. The fixes can be accepted.  Thanks
