### ISSUE TITLE
The /var/log/xcat/commands.log needs a better format of datetime

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#160]
Currently, one log entry looks like the following. Beside the off-by-one bug of the month in the ``Date'' field, we need a better datetime format. At least, we need add leading zeros to month, day-of-month, hour, minite and second.

I recommand we use RFC 2822 format. Example: `Mon, 07 Aug 2006 12:34:56 -0600`
Or we may use RFC 3339 format. Example: `2006-08-07 12:34:56-06:00`

    ====================================================
    [Date]       2015-8-8 4:6:33
    [ClientType] cli 
    [Request]    copycds 
    [Response]
    Error: copycds needs at least one full path to ISO currently.

**Comment by whowutwut** [comment]
This seems to be duplicate of Issue #140?

**Comment by neo954** [comment]
Already fixed. I will close this one.
