### ISSUE TITLE
go-xcat creating repo files with different filename than what is shipped on xcat.org

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1618]
When running `go-xcat` , I took a look at the repo files that are stored in `/etc/yum.repos.d` and noticed that the xcat-core.repo and xcat-dep.repo filenames are different than what is shipped on xcat.org.

```
[root@c910f04x42vm101 ~]# ls -ltr /etc/yum.repos.d/xcat*
-rw------- 1 root root 206 Aug  2 13:22 /etc/yum.repos.d/xcat-core.repo
-rw------- 1 root root 209 Aug  2 13:22 /etc/yum.repos.d/xcat-dep.repo
```

however, the .repo files that we provide are named the following: 

```
xcat@sense:/var/www/xcat.org/files/xcat/repos/yum$ find ./ -name "*.repo" -print  | xargs -i{} basename {} | sort | uniq
xCAT-core.repo
xCAT-dep.repo
```

I think we should make the name of the repo file consistent.

**Comment by neo954** [comment]
This is worked as design. Since xCAT shipped with different spelling across difference place. On Red Hat and SuSE, xCAT use ``xCAT-core.repo`` to named the repo file, but the name of repo is actually ``xcat-2-core``. And the subdirectory was named ``xcat-core`` or ``core-snap``.

What is a mess.

In ``go-xcat``, I just renamed everything to ``xcat-core`` to make life easier.

**Comment by whowutwut** [comment]
Maybe then it makes sense to change the public repo files to lower case to match what go-xcat is doing. 

I just don't want to have things out of sync we should be consistent. 

I can make the changes in the build script and in the xcat-dep staging directories if we agree

**Comment by immarvin** [comment]
since the final decision is not made, move to next release

**Comment by neo954** [comment]
I do not intend to fix this issue.

**Comment by whowutwut** [comment]
If we agree then I can do change the xcat.org repo files to be lower case instead of camel case. That will match go-xcat

**Comment by whowutwut** [comment]
@neo954, If you look at the way we are doing otherpkgdir, it looks like we are creating yum repo files using the camel case spelling .. `xCAT-...repo`. @gurevichmark can you confirm?  If this is the case, then i think `go-xcat` naming of the repo files is not consistent with the rest of the xCAT product.

**Comment by daniceexi** [comment]
General comment that we should only use low-case characters in all the code relative file or file names to avoid the case sensitive issues. 

I found we created two branches for pcm against 2.12 branch: 2.12-pcm and 2.12-PCM, but in certain Operating System, git is confusing about the two branches.

**Comment by gurevichmark** [comment]
When creating the repo file for `otherpkg` the file is `/etc/yum.repo.d/xCAT-otherpkgs0.repo`.
But the contents inside the file, use names with all lowercase:

```
[root@frame45cn14 yum.repos.d]# cat xCAT-otherpkgs0.repo
[xcat-otherpkgs0]
name=xcat-otherpkgs0
baseurl=http://192.168.3.29/install/post/otherpkgs/rhels7.3/ppc64le/RHEV4/4.0-GA/Power_Tools-7/ppc64le/os/
enabled=1
gpgcheck=0

[xcat-otherpkgs1]
name=xcat-otherpkgs1
baseurl=http://192.168.3.29/install/post/otherpkgs/rhels7.3/ppc64le/RHEV4/4.0-GA/Management-Agent-Power-7/ppc64le/os/
enabled=1
gpgcheck=0
[root@frame45cn14 yum.repos.d]#
```

**Comment by whowutwut** [comment]
Perhaps we should keep this issue to change all the repo names to using lower case.

**Comment by whowutwut** [comment]
I did an investigation and it seems like this change would affect many aspects of xCAT. 
I did a quick search and replace (maybe I missed some places)  in my forked branch ... https://github.com/whowutwut/xcat-core/tree/repo_lowercase

Perhaps the first step here is to create the lowercase repo files in our build for xcat-core... then add lowercase repo files for xcat-dep.. . do some testing, then remove the camelcase one?  

Thoughts?

**Comment by whowutwut** [comment]
@neo954 Here's an example of issues that may come up....

```
[root@fs4 yum.repos.d]# ls *.repo
local-repository.repo  redhat.repo  xcat-core.repo  xCAT-core.repo  xcat-dep.repo
```

Will those duplicate xcat-core cause isues?   One is generated from `go-xcat` and the other is manually created using `mklocalrepo.sh` ... 
```
[root@fs4 yum.repos.d]# cat xcat-core.repo 
[xcat-core]
name=xCAT 2 Core packages
baseurl=http://xcat.org/files/xcat/repos/yum/latest/xcat-core
enabled=1
gpgcheck=1
gpgkey=http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key


[root@fs4 yum.repos.d]# cat xCAT-core.repo 
[xcat-2-core]
name=xCAT 2 Core packages
baseurl=file:///home/junxiaw/xcat-core
enabled=1
gpgcheck=1
gpgkey=file:///home/junxiaw/xcat-core/repodata/repomd.xml.key
```

**Comment by neo954** [comment]
These two repositories are not duplicated. One is named `xcat-core`, the other is named `xcat-2-core`. They have different repository name, different location. So everything is fine.

It is just like you can have two different online repository, which are pointed to two different RHEL online mirror sites. No harm.

**Comment by whowutwut** [comment]
Closing this issue as I don't think we will fix this unless something urgent is brought up by users.
