### ISSUE TITLE
Security issue of the xcatd command log writer

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#162]
Currently, we use a separate `xcatd` daemon named "Command log writer" to do the extra log operating. It bind to 0.0.0.0 and listern TCP port 3003. This is a critical security problem.

First of all, anyone and submit fake log messages by sending anything to the TCP port 3003. Something like `echo "FAKE LOG" | nc 10.2.3.27 3003` will do the work.

Second, by sending a lot of useless log messages, anyone can exhaust the disk space on the log server.

Last, the log writer use a "Stop-and-Wait" protocol. anyone can block the log writer by connect to TCP port 3003, and do nothing. All the remain log will be blocked. And the server may end up with out of memory or get even worse.

    # ps ax | grep -v grep | grep -i xcatd
    17809 ?        Ss     0:00 xcatd: SSL listener
    17810 ?        S      0:10 xcatd: DB Access
    17811 ?        S      0:01 xcatd: UDP listener
    17812 ?        S      0:00 xcatd: Discovery worker
    17813 ?        S      0:00 xcatd: install monitor
    17820 ?        S      0:00 xcatd: Command log writer
    # netstat -nltp | grep 3003
    tcp        0      0 0.0.0.0:3003            0.0.0.0:*               LISTEN      17820/xcatd: Comman 

Conclusion, we should at lease only `bind()` to 127.0.0.1 or use OpenSSL as the other daemons of xcatd.

**Comment by daniceexi** [comment]
Yes, this is a security problem. Make the logwriter only listen to 127.0.0.1 should be good enough.

**Comment by neo954** [comment]
Already fixed. I will close this one.
