### ISSUE TITLE
[FVT] Please update go_xcat_local_repo_case1 case

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1629]
file: testcase/go-xcat/case0
case: go_xcat_local_repo_case1
description:The go-xcat command is failed to install xCAT in CN,  when executing "xdsh CN "service xcatd status"" in MN, this caused the test environment hang as out of 8 hours. This happened in ubuntu16.04 x84 and ppc64le

```
root@c910f03c17k22:/opt/xcat/share/xcat/tools/autotest/result# xdsh c910f03c17k24 "PAGER=cat service xcatd status"
c910f03c17k24: * xcatd.service
c910f03c17k24:    Loaded: not-found (Reason: No such file or directory)
c910f03c17k24:    Active: inactive (dead)
c910f03c17k24: :DSH_TARGET_RC=3:

c910f03c17k24: Connection to c910f03c17k24 closed.
```

**Comment by tingtli** [comment]
@caomengmeng  I don't think this is case issue.
The problem is when execute xdsh CN service xcatd status, the xdsh hangs there. I will open a defect for xdsh to trace this issue.
