### ISSUE TITLE
[fvt]2.11:offline trouble shooting :could not cover rcons getcons text error info in commands.log

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#164]
1.down load the latest build
2.makeconsercf
3.rcons node
[root@c910f03c05k06 ~]# rcons c910f03c05k08
[Enter `^Ec?' for help]
ERROR/WARNING: communication with the xCAT server seems to have been ended prematurely

------------->could not get information
4.tail -f /var/log/xcat/commands.log
====================================================
[Date]       2015-8-8 4:8:11
[ClientType] cli
[Request]    makeconservercf
[Response]
====================================================
[Date]       2015-8-8 4:8:12
[ClientType] cli
[Request]    getcons c910f03c05k08 text
[Response]
Error: A fatal error was encountered, the following information may help identify a bug: Can't use string ("Unable to query running VM") as an ARRAY ref while "strict refs" in use at /opt/xcat/sbin/xcatd line 3008.
===================================================
----------------------->This is not the real root cause for getcons text failed.

**Comment by samveen** [comment]
@junxiawang the report will be more readable and understandable if you quote the output as per markdown rules with a simple ```` ``` ```` on either end.
