### ISSUE TITLE
[FVT]:rinv does not have manpage for openpower

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1645]
I didn't find the openpower section in the manpage of rinv. Please update that. Thanks!

**Comment by whowutwut** [comment]
@tingtli  @neo954  Are there specific things that need to be addressed for OpenPower servers that is different on `rinv`?

**Comment by tingtli** [comment]
For the manpage of rinv, we have several sections for each hardware platform. e.g
BMC/MPA specific:,  PPC (with HMC) specific: etc.  
I think we need to add a section for "OpenPOWER BMC specific:" to let the users know which options would be used for rinv on OpenPOWER.
See manpage of rflash.

**Comment by whowutwut** [comment]
@zet809 I think we currently do not support any options to rinv for OpenPower..

**Comment by whowutwut** [comment]
Using 10/14 build, man pages are there for Open Power
```
RINV.1(1)                                                    User Contributed Perl Documentation                                                   RINV.1(1)

Name
       rinv - Remote hardware inventory

...
   OpenPOWER server specific:
       rinv noderange {model|serial|deviceid|uuid|guid|vpd|mprom|firm|all}
...
...
```

**Comment by tingtli** [comment]
@zet809 @whowutwut  Same problem with rvitals, do you need to add manpage for OpernPOWER

**Comment by whowutwut** [comment]
@tingtli yea but we should open another issue to track that. This one is for rinv and didn't mention rvitals initially. And this issue is tracked in 2.12.3 and we cannot fix in that release

**Comment by tingtli** [comment]
@whowutwut Ok, i will open another one to trace this #1996
