### ISSUE TITLE
makedns: Failure encountered updating 109.113.10.IN-ADDR.ARPA., error was FORMERR.

### ISSUE THREAD

**Issue by zhanggbj** [xcat2/xcat-core#1648]
These error messages showed up several times when to run **makedns** {my baremetal server} It seems that doesn't fail the provisioning process, but I'm not sure what these error mean and whether it will break something else. And it can't be recreated 100%. Here is the log. Thanks.
Also cc @mattcui

---

makedns {my baremetal server}

Error: Failure encountered updating 109.113.10.IN-ADDR.ARPA., error was FORMERR. See more details in system log.

Error: Failure encountered updating softlayer.com., error was FORMERR. See more details in system log.

Handling {my baremetal server} in /etc/hosts.

Getting reverse zones, this may take several minutes for a large cluster.

Completed getting reverse zones.

Updating zones.

Completed updating zones.

Updating DNS records, this may take several minutes for a large cluster.

Completed updating DNS records.

**Comment by immarvin** [comment]
hi @zhanggbj , would you please provide the output of  following commands:
``tabdump site `` 

``tabdump network``

and provide a simple description of the dns configuration in your cluster?

thanks

**Comment by zhanggbj** [comment]
Hi, here are the outputs of table site and networks. Thanks:)

>root@4a4f960c-d90a-4621-8854-2be9c04ba357:~# tabdump site
#key,value,comments,disable
"blademaxp","64",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","10.113.205.251",,
"forwarders","10.113.205.251",,
"nameservers","10.113.205.251",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","Etc/Universal",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"xcatsslversion","TLSv1",,
"auditskipcmds","ALL",,
"domain","softlayer.com",,
"useflowcontrol","no",,


>root@4a4f960c-d90a-4621-8854-2be9c04ba357:~# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"10_113_205_0-255_255_255_0","10.113.205.0","255.255.255.0","eth0","<xcatmaster>",,"10.113.205.251",,,,,,,,,,,,
"159_122_228_160-255_255_255_224","159.122.228.160","255.255.255.224","eth1","159.122.228.161",,"159.122.228.177",,,,,,,,,,,,
"192_168_122_0-255_255_255_0","192.168.122.0","255.255.255.0","virbr0","<xcatmaster>",,"19 2.168.122.1",,,,,,,,,,,,
"10_113_109_0-255_255_255_0","10.113.109.0","255.255.255.0","!remote!","10.113.109.1","10.113.205.251","10.113.205.251",,,,,,,,,,,,

And Here is the information of DNS configuation. 
>root@4a4f960c-d90a-4621-8854-2be9c04ba357:~# cat /etc/hosts
127.0.0.1 localhost 4a4f960c-d90a-4621-8854-2be9c04ba357.softlayer.com

>The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback 4a4f960c-d90a-4621-8854-2be9c04ba357
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.113.109.187 baremetal-165-20160805-103457-208 baremetal-165-20160805-103457-208.softlayer.com

>root@4a4f960c-d90a-4621-8854-2be9c04ba357:~# cat /etc/resolv.conf
nameserver 10.113.189.212
nameserver 10.0.80.11
nameserver 10.0.80.12

**Comment by daniceexi** [comment]
Refer to the error message: Error: Failure encountered updating 109.113.10.IN-ADDR.ARPA., error was FORMERR. See more details in system log.

You can search the keyword ``109.113.10.IN-ADDR.ARPA.`` in the syslog file, there should have some more detail info for the failure.

**Comment by immarvin** [comment]
any update?

**Comment by zhanggbj** [comment]
Didn't get a chance to reproduce this issue. Will take a look at syslog file next time.

**Comment by immarvin** [comment]
close this ticker first, please reopen it if need
