### ISSUE TITLE
xcatprobe switch-macmap should display the ports in numeric order

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1649]
Using the 8/4/16 build of xCAT 2.12.2, the `xcatprobe switch-macmap` output looks like the following: 

```
[root@fs1 ~]# xcatprobe switch-macmap switch-10-5-23-1
Switch            Port        MAC address         Node                                                            
------------------------------------------------------------------                                                
switch-10-5-23-1  Ethernet1          N/A                                                                          
switch-10-5-23-1  Ethernet10         N/A                                                                          
switch-10-5-23-1  Ethernet11         N/A                                                                          
switch-10-5-23-1  Ethernet12         N/A                                                                          
switch-10-5-23-1  Ethernet13         N/A                                                                          
switch-10-5-23-1  Ethernet14  98:be:94:59:fa:cf   c910f05c35                                                      
switch-10-5-23-1  Ethernet15         N/A                                                                          
switch-10-5-23-1  Ethernet16         N/A                                                                          
switch-10-5-23-1  Ethernet17         N/A                                                                          
switch-10-5-23-1  Ethernet18         N/A                                                                          
switch-10-5-23-1  Ethernet19         N/A                                                                          
switch-10-5-23-1  Ethernet2          N/A                                                                          
switch-10-5-23-1  Ethernet20         N/A    
...
...                                 
```
 
* Sort the ethernet ports in numeric order.  1,2,3... instead of 1,10,11... 2,20,21... 
* Do we need to label the port "EthernetX" or can we have just the port number?
* If we can just have port number, maybe we can have another column for Type...  Do we really need type?  What are the type options that we support? Ethernet and IB?  do we distinguish between 1G and 10G?

**Comment by whowutwut** [comment]
@zet809  I created a pull request to handle the 1st issue mentioned. Can you provide some information about the other bullets?

**Comment by zet809** [comment]
@whowutwut I don't think it is a good idea to remove the characters from the port name column. The following result is got from test team. The port name is like <group_name>/<unit_num>/<port_num>, so the whole port name is more meaningful. 

# xcatprobe switch-macmap c712f11u30vc
Switch        Port         MAC address         Node
------------------------------------------------------------------
c712f11u30vc  ge-0/0/0.0          N/A          c712f7n08-pvt
c712f11u30vc  ge-0/0/1.0   70:e2:84:14:09:a4   c712f7n02-pvt
...
c712f11u30vc  ge-0/0/14.0  70:e2:84:14:0e:36
c712f11u30vc  ge-0/0/14.0  70:e2:84:14:0e:37
...
c712f11u30vc  ge-1/0/0.0   70:e2:84:14:0c:4e   c712f9n01-pvt
c712f11u30vc  ge-1/0/0.0   70:e2:84:14:0c:4d   c712f9n01-pvt
c712f11u30vc  ge-1/0/1.0   70:e2:84:14:0e:f9   c712f9n02-pvt
c712f11u30vc  ge-1/0/1.0   70:e2:84:14:0e:fa   c712f9n02-pvt
...
c712f11u30vc  ge-2/0/9.0   70:e2:84:14:0c:dd   c712f6n10-pvt
c712f11u30vc  xe-0/1/0.0          N/A

**Comment by whowutwut** [comment]
Thanks, let's close this Isssue
