### ISSUE TITLE
xcatprobe switch-macmap has some usability issue when helping to resolve errors in node definition

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1650]
Some usability issues with `xcatprobe switch-macmap` when using it. 

1) I have a switch definition that is not configured correctly.  I think FVT team should also create a testcase for this so to test out the effectiveness of the probe command helping the user fix what is wrong. 

When `nodetype != switch`, we should print out a usage error, not a probe failure because we do not want compute nodes run against this option.  

```
# xcatprobe switch-macmap frame45_sw1
The nodetype is not 'switch' for nodes: frame45_sw1                                                               [FAIL]
```

For example, I am running the probe against a switch definition, but I have configured the switch wrong. So this is a perfect opportunity for probe to help me fix it.  However, the message does not make sense for compute nodes, so I think we should return a generic usage error message instead of `[FAIL]`.   Should be something like: `Error, switch-macmap can only be run against xCAT objects that have nodetype=switch` 

2) The user name message needs to be improved. 

```
# xcatprobe switch-macmap frame45_sw1
frame45_sw1 - Unknown user name                                                                                   [FAIL]
```

With switch, there is a `username` and `snmpusername`.  This message above is not helpful is informing the user which user name is incorrect or unknown

**Comment by zet809** [comment]
Move the next release to fix this issue.

**Comment by zet809** [comment]
@xuweibj Hi, xu wei, will you pls help to take a look at this defect?

**Comment by whowutwut** [comment]
Thanks, I verified on RC2 build.
