### ISSUE TITLE
[DEV] Need to enhance switch configuration script in order to use it externally

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#1652]
For configuring switch after switch was discovered, we provide 2 scripts xCAT-server/share/xcat/tools/configBNT and  xCAT-server/share/xcat/tools/configMellanox to configure static IP address, hostname and SNMP enablement. It is good enough for internal using, but for external using, enhancement is needed. 
For example, need to deal with specified IP address and/or hostname for the specified switch.

**Comment by zet809** [comment]
@cxhong Hi, casandra, do you plan to enhance the 2 switch configuration scripts? If not, I'll move it to the next release.

**Comment by cxhong** [comment]
@zet809 , Can u add suggestion what enhancement we need? 
 Those are issues have been fixed 
#1947 , #1912 , #1906 , #1893 , #1892 , #1878 , #1732

**Comment by cxhong** [comment]
I will close this issue for now.  will open new issue if there need modification.
