### ISSUE TITLE
Install RHEL 7.1 LE on Power 8 - issues/workaround

### ISSUE THREAD

**Issue by mleeus** [xcat2/xcat-core#167]
I installed rhel 7.1le on Power 8 systems. I got some errors but eventually rhel 7.1le were be able to installed to the cluster. Following are 2 main issues and workaround:
1. During boot from xCAT server (load kernel, etc.), I got following error messages and rebooted by itself. I let it reboot, got errors, reboot again for few times by itself, then it passed that break point without any errors. 

Error:
Booting `xCAT OS Deployment'
Loading Install kernel ...
Loading initial ramdisk ...
error: timeout reading `/xcat/osimage/rhels7.1-ppc64-mgmt-dlc/initrd.img'.

Also got following errors, just let it reboot and eventually went through and finished the installation:

Error:
dracut-initqueue[1534]: curl: (22) The requested URL returned error: 404 Not Found
dracut-initqueue[1534]: Warning: Downloading 'http://129.40.29.157:80/install/rhels7.1/ppc64/images/updates.img' failed!
dracut-initqueue[1534]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dracut-initqueue[1534]: Dload  Upload   Total   Spent    Left  Speed
dracut-initqueue[1534]: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
dracut-initqueue[1534]: curl: (22) The requested URL returned error: 404 Not Found
dracut-initqueue[1534]: Warning: Downloading 'http://129.40.29.157:80/install/rhels7.1/ppc64/images/product.img' failed!
dracut-initqueue[1534]: Warning: Could not boot.

2. After OS is install, the OS disk is not in the boot list, the boot list is empty. Have to add boot disk to the boot list in SMS menu. 

Environment:
Systems: 8247-22L with firmware SV810_101
10 nodes cluster
xCAT v2.10
RHEL 7.1 LE

Michael Lee

**Comment by zet809** [comment]
1. You mentioned you are installing RH7.1 LE, but from the error message, it is finding rhels7.1/ppc64. I think the osimage object using is incorrect.
2. Will you pls show me the osimage definition you are using? And the node definition after runing nodeset?

**Comment by mleeus** [comment]
Sorry for copying the wrong log. I tried both RH7.1 and RH7.1 LE at beginning of the installation because of the issues. Following is the error for LE:

Booting `xCAT OS Deployment'
Loading Install kernel ...
error: timeout reading
`/xcat/osimage/rhels7.1
-ppc64le-install-compute/vmlinuz'.

Loading initial ramdisk ...
out of range pointer 0x204f5320

Aborted. Press any key to exit.

**Comment by zet809** [comment]
Are you using 'yaboot' or 'grub2' to install RH7.1 LE? Will you pls show me the node definition?

**Comment by mleeus** [comment]
I am using grub2.

[root@bdxcatp1 ~]# lsdef bd01dn08
Object name: bd01dn08
    arch=ppc64le
    cons=fsp
    currchain=boot
    currstate=boot
    groups=dlc-lpar,dlc-data,s822l-01,all
    hcp=bd01dn08-cec
    hwtype=lpar
    id=2
    initrd=xcat/osimage/rhels7.1-ppc64le-install-compute/initrd.img
    installnic=mac
    ip=129.40.29.148
    kcmdline=quiet inst.repo=http://129.40.29.157:80/install/rhels7.1/ppc64le inst.ks=http://129.40.29.157:80/install/autoinst/bd01dn08 BOOTIF=00:0a:f7:73:44:fe  ip=dhcp
    kernel=xcat/osimage/rhels7.1-ppc64le-install-compute/vmlinuz
    mac=00:0a:f7:73:44:fe
    mgt=fsp
    monserver=129.40.29.157
    netboot=grub2
    nfsserver=129.40.29.157
    nicips.eth0=129.40.29.148
    nodetype=ppc,osi
    os=rhels7.1
    parent=bd01dn08-cec
    postbootscripts=otherpkgs
    postscripts=remoteshell,syncfiles,setupntp,hardeths,setbootfromdisk,ishCreateBiUsers.ps,ishTuneHadoop.ps
    primarynic=mac
    profile=compute
    provmethod=rhels7.1-ppc64le-install-compute
    status=booted
    statustime=09-04-2015 10:56:26
    tftpserver=129.40.29.157
    updatestatus=syncing
    updatestatustime=09-03-2015 14:27:27
    vmcpus=1/24/24
    vmmemory=8/242/242
    vmphyslots=0x21010029,0x2105001f,0x21010018,0x21030015,0x21010010
    xcatmaster=129.40.29.157

**Comment by immarvin** [comment]
hi, please provide xcat release you are using with the result of 

````
lsxcatd -v

````

**Comment by mleeus** [comment]
[root@bdxcatp1 ~]# lsxcatd -v
Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)

[root@bdxcatp1 ~]# cat /tftpboot/boot/grub2/bd01dn08
#boot
set timeout=5

**Comment by zet809** [comment]
1. From the node status attribute(booted) and the file(/tftpboot/boot/grub2/bd01dn08) content, it seems the node is installed successfully.  But it failed.
2. From the error msg: Booting xCAT OS Deployment' Loading Install kernel ... error: timeout reading /xcat/osimage/rhels7.1-ppc64le-install-compute/vmlinuz', it seems the DHCP service is not configured correctly.
3. From the error msg: Loading initial ramdisk ...out of range pointer 0x204f5320, I think you are using yaboot rather than grub2. But you mentioned you are using grub2.
I think you need first check the DHCP or http configuration, if the 3rd issue still exist but the 2nd issue doesn't occur, pls let us know.

**Comment by zet809** [comment]
It seems the rh7.1 ppc64le had been installed on the LPAR successfully. So close this issue.
