### ISSUE TITLE
mkdef -z does not work when reading redirected input from a file

### ISSUE THREAD

**Issue by chrissamuel** [xcat2/xcat-core#1671]
Noticed this for a while, but given it's still in 2.12.1 I thought I'd make a ticket for it:
```
[root@bruce-m tmp]# mkdef -z < rhel68login_updates
Error: No object names were provided.
```
compared to the successful: 
```
[root@bruce-m tmp]# cat rhel68login_updates | mkdef -z
1 object definitions have been created or modified.
```
It's rather counter-intuitive.

Any ideas?

cheers!
Chris

**Comment by immarvin** [comment]
Currently, the mkdef only support the stanza file piped to STDIN,  for the stanza file redirected to STDIN, we can enhance it if required,  

````
 70 else
 71 {
 72     if (-p STDIN) {
 73         while (<STDIN>) { $data .= $_; }
 74         $cmdref->{stdin}->[0] = $data;
 75     }
 76 }
 77
````

**Comment by samveen** [comment]
@chrissamuel  To revisit your original question on the `xcat-users` mailing list:
https://sourceforge.net/p/xcat/mailman/message/34544088/
and the associated caveats
https://sourceforge.net/p/xcat/mailman/message/34544204/

**Comment by immarvin** [comment]
hi @chenglch , would you please take a look at this bug?

thanks
