### ISSUE TITLE
Netboot/Ubuntu: issue with kernel levels and linux-headers

### ISSUE THREAD

**Issue by LudovicEnault** [xcat2/xcat-core#1677]
Hello,

I am generating a netboot image for Ubuntu16.04.1.
The basic image (deboostrap) is generating successfully, with the expected kernel (4.4.0-31). However in the otherpkgs operation, it's updating the kernel to 4.4.0-34 without the according linux-headers.
Installation of some packages (like CUDA drivers) fails because headers are not present.

I had previoulsy "linux-headers-*" on the pkglist, but then there are generations of initrd / vmlinuz for each version of kernel, which takes ages.

It it possible to "lock" a kernel version and / or to refer package to install according to variable ?

Here are the settings of the netboot images:
Object name: ubuntu16.04.1-ppc64el-netboot-compute
    imagetype=linux
    kitcomponents=kitcomponent-cuda-toolkit-full-8.0-ubuntu-16.04-ppc64ell
    netdrivers=bnx2x
    osarch=ppc64el
    osname=Linux
    osvers=ubuntu16.04.1
    otherpkgdir=/install/post/otherpkgs/ubuntu16.04.1/ppc64el,http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted,http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted,http://ports.ubuntu.com/ubuntu-ports/ xenial universe,http://ports.ubuntu.com/ubuntu-ports/ xenial multiverse
    otherpkglist=/install/osimages/ubuntu16.04.1-ppc64el-netboot-compute/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist,/install/custom/netboot/ubuntu/compute.otherpkgs.pkglist,/install/osimages/ubuntu16.04.1-ppc64el-netboot-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist
    permission=755
    pkgdir=/install/ubuntu16.04.1/ppc64el
    pkglist=/install/custom/netboot/ubuntu/compute.pkglist
    postbootscripts=
    postinstall=/install/custom/netboot/ubuntu/compute.postinstall,/install/postscripts/ibmccmpl_mlnx_install
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/ubuntu16.04.1/ppc64el/compute
    synclists=/install/custom/netboot/ubuntu/compute.synclist

**Comment by penguhyang** [comment]
Hi, @LudovicEnault genimage provide a option --noupdate
``This flag allows the user to bypass automatic package updating when installing other packages.`` which may be helpful for you.

**Comment by LudovicEnault** [comment]
Thanks, I hadn't seen this option.
I will let you know if it has the expected behavior the net time there is a new kernel released!

**Comment by LudovicEnault** [comment]
Hell @penguhyang ,
I used "genimage --noupdate IMAGE_NAME", but it installed a newer kernel (4.4.0-36).

**Comment by gurevichmark** [comment]
Old issue, please open a new one if this feature is still desired.
