### ISSUE TITLE
unable provision ubuntu14.04.3 for Power8 using diskless

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#170]
stuck in unable to handle kernel paging

**Comment by zet809** [comment]
Need to specify kernel version 3.19.0-25-generic when genimage. Pls add this into document.

**Comment by whowutwut** [comment]
Is @penguhyang  going to add into the document?

**Comment by whowutwut** [comment]
@pdlun92  Is this similar to the issue you hit when provisioning n33?

**Comment by penguhyang** [comment]
@whowutwut I add the document into the readthedocs. See the page from my local web server: http://10.2.9.7/advanced/gpu/index.html

**Comment by whowutwut** [comment]
@penguhyang  which page is it on?   under gpu/cuda_ubuntu.html I can't find the kernel version text..?
 This? 
![image](https://cloud.githubusercontent.com/assets/10049070/10495517/56d609a4-728a-11e5-9441-c08b8e2bf399.png)
