### ISSUE TITLE
Remove the Debian Support Message in the xcatprobe command.

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1714]
Since xCAT does not support latest Debian for a while, please remove the messages which related to `Debian` in the xcatprobe command.

**Comment by hu-weihua** [comment]
@daniceexi , I have fixed this issue by pull request #1715 , Could you review and merge it? thanks.

**Comment by whowutwut** [comment]
@daniceexi  Can you close this if resolved?

**Comment by daniceexi** [comment]
I have verified the change.
