### ISSUE TITLE
confignics does not handle all new predictable network interface device names

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#172]
Opening this Issue on behalf of Vlad.  He his this issue on RHEL 7 running xCAT 2.10 

```
confignics script does not support RHEL 7 enP interfaces
--- if [ `echo $key | grep -E 'e(n|th|m)[0-9a-z]+'` ];then
+++ if [ `echo $key | grep -E 'e(n|th|m|nP)[0-9a-z]+'` ];then 
```

Looking more into the predictable network interface names that part of systemd, It looks like P is a valid  character.   From: http://cgit.freedesktop.org/systemd/systemd/tree/src/udev/udev-builtin-net_id.c#n20

````
 *
 * Two character prefixes based on the type of interface:
 *   en -- ethernet
 *   sl -- serial line IP (slip)
 *   wl -- wlan
 *   ww -- wwan
 *
 * Type of names:
 *   b<number>                             -- BCMA bus core number
 *   ccw<name>                             -- CCW bus group name
 *   o<index>[d<dev_port>]                 -- on-board device index number
 *   s<slot>[f<function>][d<dev_port>]     -- hotplug slot index number
 *   x<MAC>                                -- MAC address
 *   [P<domain>]p<bus>s<slot>[f<function>][d<dev_port>]
 *                                         -- PCI geographical location
 *   [P<domain>]p<bus>s<slot>[f<function>][u<port>][..][c<config>][i<interface>]
 *                                         -- USB port number chain
 *
````

It seems like most options above are satisfied with the original regular expression, I am OK with the suggested change but it seems like we only care of "en" and nothing else that follows... maybe should just add A-Z ....
```
if [ `echo $key | grep -E 'e(n|th|m)[0-9a-zA-Z]+'` ];then 
```

**Comment by daniceexi** [comment]
@whowutwut I agree with your proposal.

**Comment by samveen** [comment]
As some wise man said,  `Predictable interface names are anything but...`. The only thing predictable is that the device will always have same name, not that the name will follow any predictable scheme. As an example, network interface naming changed from RH 6.6 to Centos 7 to Centos 7.1. ( MN: xCAT 2.9.1 ON C7, HP ProLiant DL380p Gen8 nodes). Please take that into consideration.

**Comment by daniceexi** [comment]
@samveen The naming of interface determined by the kernel and udev/systemd system, xCAT has not good way to control that. Do you have any good idea?

**Comment by whowutwut** [comment]
@samveen . I agree that naming is probably not very predictable but I think we're taking a very WIDE approach to trying to take a best guess as to what would be an "Ethernet" adapter with that line..

Do you have a sample of what the interfaces names are on your CentOS7/7.1 machines? 

What I was trying to cover is anything that starts with ``e`` followed by ``n | th | m`` followed by any combination of letters of numbers would qualify as "Ethernet"...   If something has changed dramatically, then we should add those as we encounter.. but maybe this is good enough to work for now.. until the next change...

**Comment by samveen** [comment]
On our machines, with Centos 7.1, the interface names are eno[1-4] (1G interfaces) and ens1f[01] (10G cards). 

As to the difference in names, another thing that I saw was that interface names given to the interfaces by the genesis image are different from the interface names given by Centos 7.1 (difference in the udevd rule sets, I believe).

**Comment by daniceexi** [comment]
@samveen, since the naming work of nic is determined base OS. Different OS might generate different nic name. Genesis was generated from Centos 6.5 for x86_64.

**Comment by samveen** [comment]
@daniceexi , Yes, I agree. My understanding is that the naming is completely dependent on the distro's `udevd` device naming rules with multiple rule files.
