### ISSUE TITLE
Enabling x86_64 genesis has problem on ppc64le MN

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#1735]
We have made a feature to install x86_64 genesis and run `mknb` on ppc64le MN by default. But we did not enable the xnba on ppc64le MN which caused CN cannot load genesis.

**Comment by zet809** [comment]
@immarvin Hi, Yang song, will you pls take a look at this issue?

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1835

**Comment by whowutwut** [comment]
Can this be closed?

**Comment by whowutwut** [comment]
@daniceexi  Can you close this if resolved?

**Comment by daniceexi** [comment]
I'll verify the fix.

**Comment by daniceexi** [comment]
I have verified the bug.
