### ISSUE TITLE
Add transparency on the Jenkins result email to accurately show problems with framework or code 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1738]
I have brought this up in the past and I think that it's really something that needs to be changed regarding the way we are reporting the status on the automated testing.  

I think the subject line should be a accurate indicate of something wrong in the testing suite, regardless of whether it's because of code bugs or because of testing framework bugs.  If we are going to leverage the autotest for a majority if not all of the xCAT daily testing, a framework problem OR code problem is the same thing, it results in putting the quality of the code base in jeopardy. 

Currently today we are masking the problems with the build framework and only trying to determine the quality of the xCAT code base.  I think this is wrong.   We should have it as transparent as possible.  If there's something wrong with the framework, it should be treated as a high severity problem. 

It's difficult to tell from the daily email that a problem with the framework has been encountered..

Here's the recent email report subject: 
![image](https://cloud.githubusercontent.com/assets/10049070/17776293/dc16b36a-6529-11e6-93d3-680b55c02423.png)

However, we see that almost all x86_64 testing has not executed.. 
![image](https://cloud.githubusercontent.com/assets/10049070/17776322/ff95d708-6529-11e6-9539-b0d3acea813e.png)

One question is how come we have the last bucket able to count the 257 cases not run, but the others are not able to have that count?

**Comment by tingtli** [comment]
"Not run" case number is total case number minus "pass" and "failed" cases.
The all 0 line is because the mn provision is failed,  the test is not started, so the total case is 0.  
FVT is refining the code to take mn provision as a test case. then we could get the total case before mn provision.

**Comment by tingtli** [comment]
@whowutwut  I am not very clear for your requirement to add the failed reason in the subject. The summary email only gives out the test result on different platforms. For each platform, we have independent email to indicate the test result.  The email fo reach platform is
```
[JK][sles12.1-x86_64-2.12-22][FAILED] TotalCase:227 TotalRun:227 Fail:2


======================================
  Test Result for Project sles12.1-x86_64-2.12-22
======================================

[sles12.1+x86_64]

All time consumption: 5 hours 30 minutes 50 seconds

Deploy test environment time consumption: 0 hours 20 minutes 33 seconds

TotalCase 227 TotalRun 227 Failed 2

Failed cases: nodeset_cmdline, nodeset_runimg,


-------------------------------------------
Cluster Information:
MN: c910f04x18v02
SN: c910f04x18v03
CN: c910f04x18v04
```

**Comment by whowutwut** [comment]
@tingtli  I'm not asking to add the failed reason into the subject.  I just want an accurate count of failures, and I think that "no run" is the same thing as "failed" regardless of whether the testcase failed because of a bug or the framework has problems.   It should not be total case - failed - pass unless we know that total case is NOT 0.   If we can know the size of the bucket before hand, then we can accurately calculate the not run number. 

What I'm trying to avoid is the scenario where we have the following:
1. all test cases  that run have 0 failures. 
2. all the x86_64 testcases fail the provisioning and we have 0 as No Run 

The resulting subject line will show: 
`[xCAT Jenkins] Passed: XXXX Failed: 0 No run: 0`

This is very dangerous because at a glance, there is nothing wrong and it's easy for us to assume that the testing succeeded while in reality there was some framework problem.  

However you want to handle it is OK, I just want any failures to be reflected in the counting, whether we initialize total case = 100000  and then overwrite it with the actual number of cases when the test runs... or get the number of cases before the test runs...  Just some way to indicate the failure without missing it.

**Comment by tingtli** [comment]
@whowutwut "no run" is different with "failed" because we have a stop label in the test cases. That means, when there is a case failed, if the case has a stop label on itself, the test will stop at the case and the cases after it will be "not run" case.  

The scenario which you concern only happens when the mn provision failed. Then the test was not triggered and the total case number is not gotten by the script. That is why we are changing the script and will put the mn provision as an test case. Then before we start the case, we will get the total number.

**Comment by whowutwut** [comment]
Thanks! I'm ok with however you want to implement it, I just want to make sure that we avoid any scenario where the autotest will report 0 fail and 0 no run , when really there is some problem.

**Comment by tingtli** [comment]
just under discussion. Move to 2.12.4

**Comment by whowutwut** [comment]
Who is working on this? And can we get an estimated date when it will be implemented?  Last comment was 1 month ago. @daniceexi

**Comment by tingtli** [comment]
@whowutwut 
To fix this issue , we need to resolve 2 problems.
1. Show "Not run" cases in the title of notification mail. This include following code change in xcatjktest before mn installation
    1.1 Get xcat-core tar ball and extract it.
    1.2 Get xCAT-test package and extract it to get the bundle files for each os
    1.3 Put bundle files in specified directory and let the upper framework read this file to get the total test cases number even if mn installation fails.
2.  Not only show the error cases in the test result directory but also show the error in the framework log.
This is a big problem since we didn't design to show the framework issue in the test result notification. We need to update both test framework and test result notification framework. We need to think more about this. 
So, victor, how about we realize problem 1 in the sprint and discuss problem 2 in next sprint?

**Comment by whowutwut** [comment]
@tingtli  Yes, I think that is good.    I have been asking for larger tasks to be broken down into smaller pieces so that we can move the overall task to completion.  As we have time to work on some of the pieces, we can associate the pull requests to the issue.  Each day we can see the changes in the Jenkins report, then modify as needed.

**Comment by whowutwut** [comment]
Tracking this in our testing framework on GHE https://github.ibm.com/xcat2/jenkins/issues/57
