### ISSUE TITLE
bmc tmperary nodes are not deleted after the bmc setup has finished. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1752]
issue: bmc temp nodes are not deleted after the bmc setup has finished. 
Yesterday  Dave discovered  5 JEMTs and entered into the xcat db (via  bmcdiscover -s nmap --range 192.168.130.100-140 -t -z -w )
which created the 5 temp nodes
node-8335-gtb-2109c4a 
node-8335-gtb-2109c6a  
node-8335-gtb-2109c8a 
node-8335-gtb-2109e9a  
node-8335-gtb-2109eaa  

After powered up these 5 temp nodes
and they are stucked in a loop waiting to turn the genesis discovery into the permanent node.
  ```
<166>Aug 22 15:17:48 xcat.genesis.dodiscovery: Beginning echo infomation to discovery packet file...
<166>Aug 22 15:17:50 xcat.genesis.dodiscovery: Discovery packet file is ready.
<166>Aug 22 15:17:50 xcat.genesis.dodiscovery: Sending the discovery packet to xCAT (192.168.130.1:3001)...
<166>Aug 22 15:17:50 xcat.genesis.dodiscovery: Sleeping 5 seconds...
<166>Aug 22 15:17:55 xcat.genesis.dodiscovery: Beginning echo infomation to discovery packet file...
<166>Aug 22 15:17:55 xcat.genesis.dodiscovery: Discovery packet file is ready.
<166>Aug 22 15:17:55 xcat.genesis.dodiscovery: Sending the discovery packet to xCAT (192.168.130.1:3001)...
<166>Aug 22 15:17:55 xcat.genesis.dodiscovery: Sleeping 5 seconds...
<166>Aug 22 15:18:00 xcat.genesis.dodiscovery: Beginning echo infomation to discovery packet file...
<166>Aug 22 15:18:02 xcat.genesis.dodiscovery: Discovery packet file is ready.
<166>Aug 22 15:18:02 xcat.genesis.dodiscovery: Sending the discovery packet to xCAT (192.168.130.1:3001)...
<166>Aug 22 15:18:02 xcat.genesis.dodiscovery: Sleeping 5 seconds...
```
```
After investigation, I found there is two conditions. 
1. for some predefined nodes , the switchport is set to "/1/0/32" , which caused the bmc setup can not find the matching nodes.  After I changed switchport  to the "1/0/32" , the bmc setup can continue, and set the node with more parameters. 
Then the bmc ip in the temp node can not ping , but it is not deleted. 
2. for one node, it's not predefined. after I predefined it , it can be matched and the bmc setup continue to success. but the temp node is not deleted either. 
```
```
 lsxcatd -v
Version 2.12.2 (git commit c672699571a1d8b2af2cf28eb46fcfbcf4c2fe54, built Thu Aug  4 06:16:05 EDT 2016)
[root@c712ems4 httpd]#
```

**Comment by wwzhubj** [comment]
In our environment , I found totally 13 nodes are not deleted 
[root@c712ems4 httpd]# nodels all |grep node
node-8335-gtb-100463a
node-8335-gtb-100469a
node-8335-gtb-100582a
node-8335-gtb-2109c4a
node-8335-gtb-2109c6a
node-8335-gtb-2109c8a
node-8335-gtb-2109c9a
node-8335-gtb-2109cfa
node-8335-gtb-2109d5a
node-8335-gtb-2109e9a
node-8335-gtb-2109eaa
node-8335-gtb-2109f6a
node-8335-gtb-210a01a
 I don't know the details for other 8 nodes , but I know the story about these 5 nodes which I listed in the bug

**Comment by daniceexi** [comment]
@zet809 Could you confirm whether the nodes were missed to be cleaned up when the MN was using old code?

**Comment by cxhong** [comment]
The Lab Service also reported this issue:  the bmc node definition didn't delete after compute node provisioned.

**Comment by whowutwut** [comment]
@wwzhubj  I am closing this issue out.   Please re-open if you see this issue persist
