### ISSUE TITLE
[Feature Request] `makedhcp` should warn if a node's IP falls inside a network's dynamic range

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#1764]
I'm running  xCAT-2.9.1 on a centos7 environment.

Relevant fields of my node definition:

```
[root@xcatm1 ~]# lsdef -t node relay1 -i nicips,mac,primarynic,ip,kcmdline
Object name: relay1
    ip=10.2.2.91
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/centos7.1/x86_64 inst.ks=http://!myipfn!:80/install/autoinst/relay1 ip=eno1:dhcp  inst.cmdline  console=tty0 console=ttyS1,115200
    mac=1c:98:ec:22:65:dc!relay1-priv|14:02:ec:72:c4:7c!relay1-pub
    nicips.eno1=10.2.2.91
    nicips.eno49=10.129.2.91
    primarynic=eno1
```

Snippets from the node's console log during kickstart installation(ellipsis denotes truncation) :

```
Features: HTTP HTTPS iSCSI DNS TFTP EFI
net0: 1c:98:ec:22:65:dc using <NULL> on EFI SNP (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
DHCP (net0 1c:98:ec:22:65:dc)... ok
net0: 10.2.2.91/255.255.255.0
Next server: 10.1.1.2
Filename: http://10.1.1.2/tftpboot/xcat/xnba/nodes/relay1.uefi
http://10.1.1.2/tftpboot/xcat/xnba/nodes/relay1.uefi... ok 
http://10.1.1.2/tftpboot/xcat/elilo-x64.efi... ok 
ELILO v3.14 for EFI/x86_64
Loading kernel /tftpboot/xcat/osimage/centos7.1-x86_64-install-base/vmlinuz...  done
Loading file /tftpboot/xcat/osimage/centos7.1-x86_64-install-base/initrd.img...done
...
Starting automated install
...
Running post-installation scripts
^b2
[anaconda root@relay1 ~]# ip -o a
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eno1    inet 10.2.2.89/20 brd 10.2.2.255 scope global dynamic eno1\       valid_lft 604795sec preferred_lft 604795sec
[anaconda root@relay1 ~]# ps -ef |grep awk
root     10969 10817  0 06:31 pts/0    00:00:00 /usr/bin/awk -f /xcatpost/updateflag.awk 10.1.1.2 3002
root     11086  1744  0 06:50 pts/1    00:00:00 grep awk
```

My problem is that the node receives the correct IP during the PXE boot process, but then gets another IP during the kickstart process. This causes the usual problem of a post-install stuck on updateflag.awk.

I traced this to the fact that the IP address assigned to the node fell under the `dynamicrange` of the associated network definition. This seems to lead to multiple leases for the machine, everytime a lease request is sent. I chalk this down to some obscure bug in `DHCPD`

My question is, that is it possible to give a warning for this during `makedhcp` : In addition to checking that the node's IPs are part of one of the network objects, in case the node's IPs fall under a network's dynamicrange, then throw a warning.

**Comment by daniceexi** [comment]
It's a valid request if we don't have the check in our latest code @baiy

**Comment by hu-weihua** [comment]
@samveen I think this issue has been fixed in xCAT2.10, the commit number is ``ae636e0afa917a28387363987abf7dabd4f3edf6``. Could you upgrade to latest xCAT and try again? 
I will close this issue, If you still hit this issue, you can contact us again. thanks.
