### ISSUE TITLE
genimage deleted /dev/* on the management node...

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1767]
we ran genimage on the following osimage stanza:

```
rhels72_compute:
    objtype=osimage
    exlist=/install/custom/rhel72_compute/compute.exlist
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le
    pkgdir=/install/rhels7.2/ppc64le
    pkglist=/install/custom/rhel72_compute/compute.rhels7.pkglist
    postinstall=/install/postscripts/custom/rhel72_compute/compute.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.2/ppc64le/rhel72_compute
```

then ran genimage rhels72_compute:

right before it stopped it printed:

```
    Complete!
    umount: /sys: umount failed: No such file or directory
    rm: cannot remove '/dev/hugepages': Device or resource busy
    rm: cannot remove '/dev/mqueue': Device or resource busy   
    rm: cannot remove '/dev/pts/10': Operation not permitted   
    rm: cannot remove '/dev/pts/9': Operation not permitted    
    rm: cannot remove '/dev/pts/8': Operation not permitted    
    rm: cannot remove '/dev/pts/12': Operation not permitted   
    rm: cannot remove '/dev/pts/13': Operation not permitted   
    rm: cannot remove '/dev/pts/11': Operation not permitted   
    rm: cannot remove '/dev/pts/14': Operation not permitted   
    rm: cannot remove '/dev/pts/7': Operation not permitted    
    rm: cannot remove '/dev/pts/6': Operation not permitted    
    rm: cannot remove '/dev/pts/5': Operation not permitted    
    rm: cannot remove '/dev/pts/4': Operation not permitted    
    rm: cannot remove '/dev/pts/1': Operation not permitted    
    rm: cannot remove '/dev/pts/0': Operation not permitted    
    rm: cannot remove '/dev/pts/16': Operation not permitted   
    rm: cannot remove '/dev/pts/2': Operation not permitted    
    rm: cannot remove '/dev/pts/3': Operation not permitted    
    rm: cannot remove '/dev/pts/ptmx': Operation not permitted 
    rm: cannot remove '/dev/shm': Device or resource busy      

couldn't find the kernel file matched 3.10.0-327.el7.ppc64le in /install/netboot/rhels7.2/ppc64le/rhel72_compute/rootimg/boot at ./genimage line 74..    
```

it appears to have deleted most of the content of the management nodes /dev directory, which makes the management node no longer functional, requiring a reset to recover.

```
[root@c460mgt01 dcs-wat-garrison-cfg]# ls /dev
hugepages  hvc0  mqueue  mtd0  null  pts  shm  snapshot
```

I believe that part of the problem is this function in /opt/xcat/share/xcat/netboot/rh/genimage

```
sub umount_chroot {
    my $rootimage_dir = shift;

    if (majversion($osver) > 6) {
        system("umount -l $rootimage_dir/proc");
        system("umount -l $rootimage_dir/sys");

        #system("umount -l $rootimage_dir/dev");
        system("rm -rf $rootimage_dir/dev/*");
    }
}
```

I suspect that there is a path through genimage where umount_chroot gets called with an empty string, and the result is the above mini disaster on the management node.

At a minimum this code should be guarded to not hose the system, and perhaps completly halt genimage with an "xdie" call.

Of course the failure path where this is being called with an empty string needs to be identified.  Identifying this would be much quicker if we did not have to hard reboot the management node every time.

**Comment by whowutwut** [comment]
@immarvin I know we found this issue towards the end of last release. Was another issue already opened that we  could duplicate or was there a pull request that was made to fix it?

**Comment by whowutwut** [comment]
Adding @hu-weihua  also, since I think she might have some info

**Comment by ralphbellofatto** [comment]
to prevent crashing our managment node i modified the code in:
/opt/xcat/share/xcat/netboot/rh/genimage

```
sub umount_chroot {
    my $rootimage_dir = shift;

    if ($rootimage_dir =~  /^\s*$/) {
        print "WARNING: rootimage_dir is blank, exiting umount_chroot";
        return;
    }

    if (majversion($osver) > 6) {
        system("umount -l $rootimage_dir/proc");
        system("umount -l $rootimage_dir/sys");


        #system("umount -l $rootimage_dir/dev");
        system("rm -rf $rootimage_dir/dev/*");
    }
}
```

and now i see the error message reads:

```
couldn't find the kernel file matched 3.10.0-327.el7.ppc64le in /install/netboot/rhels7.2/ppc64le/rhel72_compute/rootimg/boot at ./genimage line 74.
WARNING: rootimage_dir is blank, exiting umount_chroot.
````

This at least demonstrates that this error can be guarded against.

**Comment by ralphbellofatto** [comment]
now that we have the management node back, the version we are running is:
[root@c460mgt01 ralphbel]# lsxcatd -v
Version 2.12.2 (git commit e4a7359d31008d81c4c57e0857d5f09009a3269c, built Thu Aug 18 06:43:29 EDT 2016)


I also checked the master branch for this on github and did not find any guard code for the rootimage_dir being blank.

**Comment by ralphbellofatto** [comment]
I think i found the missconfiguration that triggered this glitch..

the "kernel" module was missing from the compute pkg list file.

Here is the contents of the offending package list...

```
wget
ntp
nfs-utils
net-snmp
rsync
yp-tools
openssh-server
util-linux
net-tools
```

when we added the kernel module along with the other packages from
 /opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist

this problem does not happen.

I also took the file  /opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist and commented out the kernel rpm module and also reproduced this problem...

**Comment by immarvin** [comment]
hi @ralphbellofatto , thanks for your feedback. 

The removal of "/dev" on MN is a bug in xCAT,  fixed in https://github.com/xcat2/xcat-core/pull/1769/files

When you create a customised osimage, you'd better  make sure the "pkglist" at lease includes all the packages inside the pkglist shipped in xCAT. 

A tip: xCAT 2.12.2 provides an option "--template" to simplify the creation of customised node/osimage objects. Please refer to the manage of "mkdef" for details.

**Comment by daniceexi** [comment]
We should make sure no critical issue happens when any incorrect define made by user.

**Comment by whowutwut** [comment]
@daniceexi  what is your idea about what we should be doing for checking incorrect definitions?  an option to the `xcatprobe`?   Since I think there is still some work to resolve this issue, i am removing the pending.

**Comment by hu-weihua** [comment]
I think ``xcatprobe`` is just a assistant tool for this problem. We can't guarantee customer run ``xcatprobe`` first before using ``genimage``.  I think we should refine the code of ``genimage`` to **make sure no critical issue happens when any incorrect define made by user**, just as @daniceexi  said above.

We do not do some check for the value of ``pkglis``, such as including double slash in the path,  it has caused critical issue when we run Mellanox InfiniBand installer. I think we should add some code to check or reformat the value of ``pkglis``.

**Comment by ralphbellofatto** [comment]
After looking at the genimage code, i think a final guard in the code that performs the delete function would cover this in all potential error paths.

If the $rootimgdir leads back to "/", either by being blank (the easiest thing to check), or by tracking back all potential links (like with rlink), better and completely bullet proof, then you would be guarded against any future error paths through genimage that could in-advertantly delete something in the root directory.
