### ISSUE TITLE
Disks added to kvm do not match device labels

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#1768]
On MN create a VM with an initial disk of 15G, then I add a disk of 10G and another disk of 5G:

mkvm <vmname> -s 15G
chvm <vmname> -a 10G
chvm <vmname> -a 5G
rpower <vmname> on

On the KVM host things appear as expected:
`virsh dumpxml <vmname>` displays 3 disks: sda size of 15G, sdb size of 10G and sdc size of 5G

![image](https://cloud.githubusercontent.com/assets/16106630/17981969/f40e0572-6ad3-11e6-8a1d-2f5513532d2e.png)

And on KVM host volume information size is displayed as expected:

![image](https://cloud.githubusercontent.com/assets/16106630/17981979/017c8576-6ad4-11e6-9095-d5fcc26671e3.png)

![image](https://cloud.githubusercontent.com/assets/16106630/17981989/06f301a6-6ad4-11e6-83d5-b5c4de92e29e.png)

But when I login to the VM, the additional disks appear to be switched in sizes:

![image](https://cloud.githubusercontent.com/assets/16106630/17982008/1225a6a0-6ad4-11e6-836d-6a3213b961bd.png)

It almost seems that <target dev="xxx"> is not being used to assign label to the disk

Additionally command `ls /dev/disk/by-*` can be used to see the mapping of the label to the scsi id. But even that does not seem to match the XML file specification.

The documentation states the disk labels are just a suggestion and are not guaranteed:

![image](https://cloud.githubusercontent.com/assets/16106630/17982147/a896f3a0-6ad4-11e6-92d2-6f888398b011.png)

But perhaps there is a way to enforce labels some other way ? @daniceexi suggested we should have the mapping correct, since the disk device label can be used by the user when changing disk size and removing disks.

**Comment by immarvin** [comment]
hi @gurevichmark ,

http://libvirt.org/formatdomain.html#elementsDisks mentions:
````
arget
The target element controls the bus / device under which the disk is exposed to the guest OS. The dev attribute indicates the "logical" device name. The actual device name specified is not guaranteed to map to the device name in the guest OS. Treat it as a device ordering hint. The optional bus attribute specifies the type of disk device to emulate; possible values are driver specific, with typical values being "ide", "scsi", "virtio", "xen", "usb", "sata", or "sd" "sd" since 1.1.2. If omitted, the bus type is inferred from the style of the device name (e.g. a device named 'sda' will typically be exported using a SCSI bus). The optional attribute tray indicates the tray status of the removable disks (i.e. CDROM or Floppy disk), the value can be either "open" or "closed", defaults to "closed". NB, the value of tray could be updated while the domain is running. The optional attribute removable sets the removable flag for USB disks, and its value can be either "on" or "off", defaulting to "off". Since 0.0.3; bus attribute since 0.4.3; tray attribute since 0.9.11; "usb" attribute value since after 0.4.4; "sata" attribute value since 0.9.7; "removable" attribute value since 1.1.3
````

Suppose that you get a physical machine with several disks, you specify the name for them "sda","sdb"...,  you can only identify them with the pci slot or scsi address in the guest os.  
If you expect them to be named as you specified, you may need to write own udev rules for the disk devices, considering the variety of linux distributions xCAT support and variety of disk types, I am not sure how much effort it may cost.  According to the experience on processing the similar problem for persistent Network Card naming, I do not think it's a good idea to change the default behaviour of the OS.

Maybe a feasible solution is to update the disk devices names in the domain xml according to the disk names insider guest os after vm is powered on.

**Comment by gurevichmark** [comment]
I agree this work might not be worth it.

Perhaps a better solution could be to make `lsvm` command return a list of device names and which qcow2 files they are mapped to. This way user will have some idea of the mapping when they change size or remove disks.
