### ISSUE TITLE
[DEV] After update MN, SN SSL connect failed

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#1770]
SN: c910f03c17k17

```
[root@c910f03c05k04]# nodeset c910f03c17k20 osimage=sles12-ppc64le-install-compute
c910f03c17k20: install sles12-ppc64le-compute
Error: Unable to dispatch hierarchical sub-command to c910f03c17k17:3001.  Error: Connection failure: SSL connect attempt failed with unknown error error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01 error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at /opt/xcat/lib/perl/xCAT/Client.pm line 278. 
```

**Comment by immarvin** [comment]
can be workaround by "update node SN -P servicenode" after MN updating. Maybe we should add this into xCAT Doc

**Comment by whowutwut** [comment]
Yes, I think we should document the process that should be followed in this scenario.  Is there any more information about how to re-create this?

**Comment by xuweibj** [comment]
Hi @whowutwut , my steps as follows:
1. on MN, used `nodeset` command install SN package on my SN.
2. run `yum update '*xCAT*'` on MN, install a newer version 
3. run any xCAT command will see this error message

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2094
hi @whowutwut , I added a message on xCAT upgrade to make user aware of this

**Comment by immarvin** [comment]
hi @tingtli , could FVT help to recreate this issue ? thanks

**Comment by tingtli** [comment]
@junxiawang  will help verify this bug.

**Comment by immarvin** [comment]
cannot be recreated
unless you run ``xcatconfig -c``

**Comment by immarvin** [comment]
close this issue, please reopen it when you find it
