### ISSUE TITLE
[Feature request]non-interactive option for "/opt/xcat/share/xcat/scripts/setup-local-client.sh"

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#1783]
When the command  `/opt/xcat/share/xcat/scripts/setup-local-client.sh` is run, the `openssl req` command prompts for `[y/n]` twice:
```
[root@xcatmn1 ~]# /opt/xcat/share/xcat/scripts/setup-local-client.sh samveen
...
Certificate is to be certified until Aug 25 05:36:37 2036 GMT (7300 days)
Sign the certificate? [y/n]:y


1 out of 1 certificate requests certified, commit? [y/n]y
...
```
`openssl req` accepts a `-batch` option so that such prompts are no longer shown. 
1. Can this script be changed to add this to the openssl command?
OR
2. If this user interaction is required, can an option  `-b` (or `--batch` ) be added to allow for non-interactive operation?

If this looks like a valid requests, please let me know and I'll submit a MR for the selected option(I've already implemented option 1 at my end).

**_Edit_**: From an automation viewpoint, the following also works(making this request redundant):
```
[root@xcatmn1 ~]# yes y| /opt/xcat/share/xcat/scripts/setup-local-client.sh samveen
```

**Comment by immarvin** [comment]
hi @samveen , thanks for your proposal.  We prefer option 2:
````
2. If this user interaction is required, can an option -b (or --batch ) be added to allow for non-interactive operation?
````
The option should better be "-f|--force" to keep consistent with the existing xCAT command options.

If you are ok with this, please feel free to create a PR.

thanks

**Comment by samveen** [comment]
@immarvin I'll get it done in a couple of days. (Feel free to add  me in the assigned list)

**Comment by whowutwut** [comment]
@samveen  I just added you to the xcat contributor team, without this we cannot assign you in the "asignee list"  If you accept the invite, we can assign you this issue.  :)

**Comment by samveen** [comment]
@whowutwut Victor, accepted with great pleasure :)

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1793
