### ISSUE TITLE
Lack of Linux kernel module rtc-opal.ko in genesis-base ppc64

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#1785]
In the genesis environment running on Firestone machine. The hardware clock is not accessable. Due to the lack of Linux kernel module `rtc-opal.ko`.

```
[xCAT Genesis running on c910f03c25 /]# hwclock
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --debug option to see the details of our search for an access method.
```

**Comment by neo954** [comment]
Issue #1591 is depend on this issue.

**Comment by neo954** [comment]
I will reopen this one. Since genesis need to be rebuilt.

**Comment by zet809** [comment]
The xcat-genesis-base-ppc64 had been uploaded to GSA.

**Comment by zet809** [comment]
@neo954 Hi, gongjie, pls help to verify.

**Comment by whowutwut** [comment]
@neo954  Can you please verify this and close out since we are close to the 2.13 release...

**Comment by neo954** [comment]
Verified with xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch. The problem was fixed. I will close this issue.
