### ISSUE TITLE
Update the documentation to describe the HW discovery process for OpenPower when tagged VLANS are needed for BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1787]
Update the documentation for hw discovery for Open Power machines when BMCs need to be tagged. 
It might be also good to list the options that can be configured on the BMC

Added the testcase requested label to see if FVT team can create test bucket that can be executed in the discovery environment to verify that discovery is OK and things are set correctly, like netmask, IP address, etc..

**Comment by immarvin** [comment]
hi @gurevichmark , would you please take a look at this?

thanks

**Comment by whowutwut** [comment]
Moving the milestone.

**Comment by zet809** [comment]
Need to check whether the document is updated.

**Comment by hu-weihua** [comment]
@whowutwut, could you help to verify this issue? thanks

**Comment by whowutwut** [comment]
I am ok with the changes. Thanks @zet809
