### ISSUE TITLE
Update the documentation to set the default behavior for node discovery to directly provision the OS

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1788]
The current documentation describes the process for running a chain command `runcmd=bmcsetup` to set up OpenPower servers.  However, the genesis kernel just sits there in a loop looking for the next chain command. 

This seems to be an area where there is much confusion regarding what xCAT is doing and whether discovery is complete or in some error state (Maybe a update to the msg should be made to help the user who is looking at the console, get an idea of what should be done next.)

For example, maybe the msg: 
`"Received request to retry in a bit, will call xCAT back in $delay seconds"` 

Should be changed 
`Received request=$dest, will call xCAT back in $delay seconds.  Discovery is complete, run nodeset on this node to provision an Operating System`

Also would suggest that we document the default process to include the `osimage=` attribute in the chain command instead of just leaving the genesis running in an infinite loop.

**Comment by zet809** [comment]
@xuweibj Hi, xu wei, will you pls take a look at this defect? Thx!

**Comment by whowutwut** [comment]
@zet809  @xuweibj  I actually took care of this by the pull request referenced above, so we can close this.
