### ISSUE TITLE
mknb is inconsistent in behavior when upgrading xCAT 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1791]
We have seen some issues when upgrading xCAT the mknb does not actually update the genesis kernel so that the files changes are not updated when updating xCAT.  Can someone verify that this is actually working as intended. 

The issue happened when we moved the /bin/restart file and on a system installed prior to the move of the file, after upgrading xCAT, the genesis complained that /bin/restart , file not found.  But after manually running mknb, it resolved the problem. 

So something is not quite right here...

**Comment by daniceexi** [comment]
@whowutwut You mentioned **genesis complained that /bin/restart**, did it happen during the install/updating of genesis? IF this is the case, the installation would fail.

**Comment by gurevichmark** [comment]
I remember seeing some code that on **update** of xCAT issues a message telling the user to manually run `mknb`.

**Comment by whowutwut** [comment]
Here's an example of what is seen in genesis... 

```
[Tue Aug 30 09:36:28 2016]/bin/dodiscovery: line 277: /bin/restart: No such file or directory 
[Tue Aug 30 09:36:28 2016]<166>Aug 30 09:36:28 xcat.genesis.doxcat: dodiscovery - Complete.
[Tue Aug 30 09:36:28 2016]<166>Aug 30 09:36:28 xcat.genesis.doxcat: Getting certificate -->
...
[Tue Aug 30 09:36:28 2016]<166>Aug 30 09:36:29 xcat.genesis.dodiscovery: Beginning node discovery process...
[Tue Aug 30 09:36:28 2016]<166>Aug 30 09:36:29 xcat.genesis.dodiscovery: Waiting for nics to get addresses
...
[Tue Aug 30 09:36:29 2016]<166>Aug 30 09:36:29 xcat.genesis.dodiscovery: Restart network interfaces...
[Tue Aug 30 09:36:29 2016]/bin/dodiscovery: line 277: /bin/restart: No such file or directory
```

**Comment by whowutwut** [comment]
I don't think we were able to re-create this or think of a scenario where this would actually happen, so closing this for now.
