### ISSUE TITLE
copycds report no error when it is not complete successfully. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1792]
I use : 
 copycds -p /install/rh73snapshot1 -n rhels73 /root/Downloads/RHEL-7.3-20160825.1-Server-ppc64le-dvd1.iso
Copying media to /install/rh73snapshot1

Normally, after it completed, lsdef -t osimage can show the template osimage created for snapshot1. but I can not find.  Which means the copycds haven't ran successfully. 
In this condition, the user should get some error / failure message. 
the version I use: 
[root@c712ems4 install]# lsxcatd -v
Version 2.12.2 (git commit e4a7359d31008d81c4c57e0857d5f09009a3269c, built Thu Aug 18 06:43:29 EDT 2016)

**Comment by immarvin** [comment]
please use "-n rhels7.3"

**Comment by wwzhubj** [comment]
yes, I know "-n rhels7.3" can work. But there are 2 issues: 
1. why  "rhels73 " will fail? 
2. when it fails, why the copycds shows no any error or failure message to user?

**Comment by immarvin** [comment]
"-n" should only be used when the xCAT cannot recognise the iso, this is obviously not the case here. in fact, without "-n", xcat can recognise the iso and "copycds" works well. 

It is not a error for xcat, you just specified an arbitrary os name that xcat does not know what it is, so xcat cannot  create the osimage for it.

**Comment by whowutwut** [comment]
@wwzhubj  I'm not too clear about the issue you encountered.  Can you please provide some proof in the issue of the osimages after running copycds?  I ran the same command and it succeeded for me on my test machine... 

```
[root@fs1 RH7.3beta]# copycds -p /install/rh73snapshot1 -n rhels73 ./RHEL-7.3-20160825.1-Server-ppc64le-dvd1.iso 
Copying media to /install/rh73snapshot1
Media copy operation successful

[root@fs1 ~]# lsdef -t osimage | grep rhels73
rhels73-ppc64le-install-compute  (osimage)
rhels73-ppc64le-install-service  (osimage)
rhels73-ppc64le-netboot-compute  (osimage)
```

Using "-n rhels73" is OK, we still are able to pick up the rhels7 as the default.   However, by not using the "7.3" convention, if xCAT ship a specific template for 7.3, you may default to the rhels7 template file which *may* cause issues down the road. 

```
[root@fs1 ~]# lsdef -t osimage -o rhels73-ppc64le-install-compute
Object name: rhels73-ppc64le-install-compute
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels73-ppc64le
    osname=Linux
    osvers=rhels73
    otherpkgdir=/install/post/otherpkgs/rhels73/ppc64le
    pkgdir=/install/rh73snapshot1
    pkglist=/install/custom/install/rh/compute.rhels7.ppc64le.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

[root@fs1 ~]# ls -ltr /install/custom/install/rh/compute.rhels7.ppc64le.pkglist
-rw-r--r-- 1 root root 308 Aug 11 22:51 /install/custom/install/rh/compute.rhels7.ppc64le.pkglist
[root@fs1 ~]# ls -ltr /opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
-rw-r--r-- 1 root root 3522 Aug 18 05:08 /opt/xcat/share/xcat/install/rh/compute.rhels7.tmp
```

**Comment by immarvin** [comment]
hi @whowutwut ,
On the "copycds -n" issue, I talked with WeiWei last Friday to confirm their requirement, I think it is a real problem that "copycds" cannot differentiate the snapshots builds before the GA of os distributions, and might overwrite the installation resources under"/install/<os>/<arch>" and the osimage definitions created by default. 
 
I am trying to enhance the "copycds -n" to make it work for "copycds -n" such as "rhels7.3beta-snapshot1", "rhels7.3Beta-garision",  and prompt user if no osimage definition can not be created with the specified distance with "-n".

**Comment by whowutwut** [comment]
@immarvin  I think one of the bigger issues here is that some folks are using names like `rh73` that is not following our convention of `rhels`.   I don't think we want to even attempt to address covering those scenarios in your enhancement.  A long time ago RedHat did have a RedHat 7.3 (not RHEL) ....  In Issue #1797 I suggested the `osimage` option for xcatprobe which could be enough to cover this scenario.   FYI @gurevichmark

**Comment by whowutwut** [comment]
@immarvin  let's assign this to someone else

The changes @gurevichmark  made for xcatprobe flags the issue. But the message is still a little cryptic....  I don't think I would know how to fix it. 

```
[root@fs4 tmp]# xcatprobe osimagecheck
No diskless osimages with identical root image directories were found.                              [ OK ]
rh73-ppc64le-install-compute contains depricated 'template' value                                   [WARN]
  /opt/xcat/share/xcat/install/rh/compute.tmpl
rh73-ppc64le-install-service contains depricated 'template' value                                   [WARN]
  /opt/xcat/share/xcat/install/rh/service.tmpl
```

Perhaps we should change to: 
`Depricated 'template' value is being used by rh73-ppc64le-install-compute.  Was -n used with copycds?`

**Comment by immarvin** [comment]
hi @whowutwut , I think the word ``deprecated`` in the warning message might be misleading for user, since for each new OS iso, we only create a new template for it unless the one ,"/opt/xcat/share/xcat/install/rh/compute.tmpl", does not work for it, so it is possible that some osimage generated on "copycds" will use the default "/opt/xcat/share/xcat/install/rh/compute.tmpl". How about modify the message to:

````
The 'template' attribute of osimage "rh73-ppc64le-install-compute" drop to the default template file "/opt/xcat/share/xcat/install/rh/compute.tmpl". If the osimage is created on "copycds -n <os version>", please make sure the "<os version>" specified with "copycds -n" confirm to the naming convention of xCAT, for example, the <os version> for "Red Hat Enterprise Linux 7.3" should be "rhels7.3".  Otherwise, please ignore this warning
````

**Comment by gurevichmark** [comment]
Seems a little long, how about:
```
Default "template" value is being used by rh73-ppc64le-install-compute.                             [WARN]
   If this image was generated by "copycds -n <os version>", make sure the <os version> specified 
   follows xCAT naming convention (for example "rhels7.2")
```

**Comment by immarvin** [comment]
thanks @gurevichmark , you message is better,  would you please create a PR on this modification?

**Comment by gurevichmark** [comment]
Used #2048 to fix, as suggested above, the wording of osimagecheck probe.

**Comment by whowutwut** [comment]
@wwzhubj  please give the xcatprobe commands some try. We are interested in some feedback on ways to continually provide some useful functions in the probe commands
