### ISSUE TITLE
[FVT]Please add confignics man page

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1795]
Please add confignics man page

```
root@c910f04x12v02:/# man confignics
No manual entry for confignics
```

**Comment by daniceexi** [comment]
We don't have man page for postscript. 

Is this doc good enough?
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_network_adapter.html

**Comment by bybai** [comment]
hi @caomengmeng , could you check above doc ?

**Comment by caomengmeng** [comment]
Close this issue for there is a doc.
