### ISSUE TITLE
xcatprobe switch-macmap fails when snmp community string is not "public"

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1798]
We have a setup where we have programmed the switch community strings to somethng other than public and set that value in the site table...

```
[root@c460mgt01 install]# lsdef -t site clustersite -i snmpc
Object name: clustersite
    snmpc=commxxxxxxxxx
```

the switch is progammed to respond to this community string and we have verified it with snmpwalk.

however when we run we get a timeout:

```
xcatprobe switch-macmap
Timeout                                                                             [FAIL]
```

the /var/log/xcat/cluster.log show:
```
Sep  1 13:22:06 c460mgt01 xcat[77462]: Error communicating with 9.47.66.235: Timeout
```

switch based discover in the /opt/xcat/lib/perl/xCAT_plugin/switch.pm findme, which calls /opt/xcat/lib/perl/xCAT/MacMap.pm(find_mac), appears to work.

and we see the proper community string when we look at it with tcpdump, but when we go via the xcatprobe command we see this in tcpdump:

```
Frame 55: 86 bytes on wire (688 bits), 86 bytes captured (688 bits) on interface 0
Ethernet II, Src: Ibm_63:ab:6c (98:be:94:63:ab:6c), Dst: IbmCorpo_b7:cd:00 (74:99:75:b7:cd:00)
    Destination: IbmCorpo_b7:cd:00 (74:99:75:b7:cd:00)
        Address: IbmCorpo_b7:cd:00 (74:99:75:b7:cd:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: Ibm_63:ab:6c (98:be:94:63:ab:6c)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 9.47.68.109, Dst: 9.47.66.235
User Datagram Protocol, Src Port: 46758 (46758), Dst Port: 161 (161)
Simple Network Management Protocol
    version: version-1 (0)
    community: public
    data: get-next-request (1)
        get-next-request
            request-id: 1158818476
            error-status: noError (0)
            error-index: 0
            variable-bindings: 1 item
                1.3.6.1.2.1.2.2.1.2: Value (Null)
```

This shows is asking for the public community string, and it is not picking up the information from the site table.

**Comment by cxhong** [comment]
@ralphbellofatto , we will add code to the dump_mac_info subroutine to read community from site table,
