### ISSUE TITLE
node discovery won't keep nodeset parameters if genesis is still running.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1803]
We attempted use the MTMS method to do discovery.    We are generally following this process..

http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/discovery_using_defined.html

When we get to the end of this process, the genesis image is still running on the system in a loop:

we will see this on the rcons:
```
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling the non-volatile channel access (1)
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling the non-volatile channel access (1): OK
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling the volatile channel access (1)        
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling the volatile channel access (1): OK    
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling ARP responses                          
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling ARP responses: OK                      
<166>Sep  2 14:28:57 xcat.genesis.bmcsetup: Enabling IPMI MD5 LAN access                    
<166>Sep  2 14:28:58 xcat.genesis.bmcsetup: Enabling IPMI MD5 LAN access: OK                
<166>Sep  2 14:28:58 xcat.genesis.bmcsetup: Enabling IPMI v 2.0 LAN access                  
<166>Sep  2 14:29:10 xcat.genesis.bmcsetup: ACCESS=cXaaaaaaaaaaXXX
<166>Sep  2 14:29:10 xcat.genesis.bmcsetup: Set the cipher_privileges for the channel
<166>Sep  2 14:29:11 xcat.genesis.bmcsetup: Set the cipher_privileges for the channel: OK
<166>Sep  2 14:29:11 xcat.genesis.bmcsetup: Enabling SOL for channel 1
<166>Sep  2 14:29:11 xcat.genesis.bmcsetup: Enabling SOL for channel 1: OK
<166>Sep  2 14:29:11 xcat.genesis.bmcsetup: Enabling SOL for ADMIN
<166>Sep  2 14:29:11 xcat.genesis.bmcsetup: Enabling SOL for ADMIN: OK
<167>Sep  2 14:29:11 xcat.genesis.bmcsetup: OpenPower, snooze for 30 seconds...
```

this will loop about every 30 or so seconds..

If we try to do a nodeset, and then wait for a minute.  we find that the parameters we set are no longer set.

for example:

```
nodeset c460c018 osimage=rh72_compute
lsdef  c460c018 >genesis02.txt
sleep 300
lsdef  c460c018 >genesis03.txt
```
doing a diff between these two files we see:

```
 diff genesis02.txt genesis03.txt
10c10
<     currstate=netboot rhels7.2-ppc64le-compute
---
>     currstate=runcmd=bmcsetup
14c14
<     initrd=xcat/osimage/rh72_compute/initrd-stateless.gz
---
>     initrd=xcat/genesis.fs.ppc64.gz
17,18c17,18
<     kcmdline=imgurl=http://!myipfn!:80//install/netboot/rhels7.2/ppc64le/rh72_compute/rootimg.cpio.gz XCAT=!myipfn!:3001 NODE=c460c018 FC=0 BOOTIF=70:e2:84:14:10:ec
<     kernel=xcat/osimage/rh72_compute/kernel
---
>     kcmdline=quiet xcatd=172.1.0.1:3001 destiny=runcmd=bmcsetup
>     kernel=xcat/genesis.kernel.ppc64
34c34
<     statustime=09-02-2016 14:37:08
---
>     statustime=09-02-2016 14:40:04
```

if we are doing this on a rack full of nodes, then it some of the nodes will definitly be set back to the genesis image.

our workaround is to do the following:

```
rpower c460c018 off
c460c018: off
nodeset c460c018  osimage=rh72_compute
c460c018: netboot rhels7.2-ppc64le-compute
rpower c460c018 on
```

**Comment by daniceexi** [comment]
@zet809 I think we have tested this feature when the genesis is looping in waiting for the next task. Could you take a look of this issue?

**Comment by zet809** [comment]
@ralphbellofatto Can you show me the 'currchain,currstate,chain' attributes for the failed node after running nodeset?

**Comment by ralphbellofatto** [comment]
this is are the settings after the nodeset command:
Object name: c460c018
    arch=ppc64le
    bmc=172.2.4.18
    bmcport=0
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    currchain=runcmd=bmcsetup
    currstate=netboot rhels7.2-ppc64le-compute
    disksize=sda:2000GB,sdb:2000GB
    groups=all,compute
    hostnames=c460f04u39
    initrd=xcat/osimage/rh72_compute/initrd-stateless.gz
    installnic=mac
    ip=172.1.4.18
    kcmdline=imgurl=http://!myipfn!:80//install/netboot/rhels7.2/ppc64le/rh72_compute/rootimg.cpio.gz XCAT=!myipfn!:3001 NODE=c460c018 FC=0 BOOTIF=70:e2:84:14:10:ec

and after the node set...
And this is what it looks like after the genesis loops around again.
Object name: c460c018
    arch=ppc64le
    bmc=172.2.4.18
    bmcport=0
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    currchain=runcmd=bmcsetup
    currstate=runcmd=bmcsetup
    disksize=sda:2000GB,sdb:2000GB
    groups=all,compute
    hostnames=c460f04u39
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=172.1.4.18
    kcmdline=quiet xcatd=172.1.0.1:3001 destiny=runcmd=bmcsetup
    kernel=xcat/genesis.kernel.ppc64

**Comment by zet809** [comment]
@ralphbellofatto Hi, Ralph, we have a better workaround:
When setting chain for a node, pls append 'standby' at the end of your tasks. Such as:
chdef node chain="runcmd=bmcsetup,standby"
Then, your compute node won't encounter the looping again after hardware discovery done.

For your current situation, after you modify the chain for all the compute node, you all need to set the currchain and currstate attributes to be 'standby' for all your compute node with the following command:
chdef node currchain=standby currstate=standby
Then, nodeset will work and the issue won't appear.

**Comment by ralphbellofatto** [comment]
ok, that covers a workaround,  is the documentation going to be updated for docovery, or xcat modified so this happens automatically?

**Comment by zet809** [comment]
We will update our document that the task 'standby' need to be appended to 'chain' if  task 'runcmd=xxx' or 'runimage=xxx' is singly used.

**Comment by whowutwut** [comment]
Closing this issue.  The documentation has been updated to reflect to following recommendation: 

![image](https://cloud.githubusercontent.com/assets/10049070/19659915/d300aee6-99fb-11e6-90af-2bc4251d62a6.png)

Essentially, go right into the OS deployment of the compute node after the machine is discovered and the bmc is configured.
