### ISSUE TITLE
Enable Kdump can not work on diskless image for rh7.3 snapshot1

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1805]
I follow steps in  the doc: 
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/enable_kdump.html
But the core files are not saved in the directory I set. 
[root@c712ems4 ~]# lsxcatd -v
Version 2.12.2 (git commit 6fff020a905c64cabe31896e653aebc942ee0694, built Thu Sep  1 06:18:21 EDT 2016)

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1812

Test case required for rh7.x bundle

**Comment by immarvin** [comment]
ping @tingtli

**Comment by daniceexi** [comment]
@immarvin for the fix which needs to be test or add new test case, add the label **component:test**

**Comment by wwzhubj** [comment]
verified it on Sep 19 version, closed it.

**Comment by hu-weihua** [comment]
Test case ``linux_diskless_kdump`` was added by pull request #4964
