### ISSUE TITLE
2.12.2 xcat-core for pcm upgrade failed

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1809]
1. change the code branch to tag 2.12.2
   [root@ppc803c xcat-core]# git branch -v
2. 2.12.2 aa5f6af Merge pull request #1746 from daniceexi/2.12
   master fd747d5 give warnings and return when use -o -p -a for packimage (#1757)
3. build xcat-core for pcm
   ./buildcore.sh UP=0 BUILDALL=1 VERBOSE=1
   ./buildcore.sh UP=0 BUILDALL=1 VERBOSE=1 EMBED=pcm
4. upgrade xcat-core using the self-build package, there is the following error:
   There is no xCAT-probe package in xcat-core, but other packages depends xCAT-probe

[root@fs4 xcat-core]# ll
total 3800
-rw-rw-r-- 1 root root      95 Aug 28 22:19 buildinfo
-rwxrwxr-x 1 root root     670 Aug 28 22:19 mklocalrepo.sh
-rw-rw-r-- 1 root root  564632 Aug 28 22:17 perl-xCAT-2.12.2-snap201608282217.no
drwxrwxr-x 2 root root    4096 Aug 28 22:19 repodata
-rw-rw-r-- 1 root root  220436 Aug 28 22:19 xCAT-2.12.2-snap201608282218.x86_64.
-rw-rw-r-- 1 root root  220392 Aug 28 22:19 xCAT-2.12.2-snap201608282219.ppc64le
-rw-rw-r-- 1 root root  220388 Aug 28 22:19 xCAT-2.12.2-snap201608282219.ppc64.r
-rw-rw-r-- 1 root root  220296 Aug 28 22:19 xCAT-2.12.2-snap201608282219.s390x.r
-rw-rw-r-- 1 root root   67552 Aug 28 22:18 xCAT-buildkit-2.12.2-snap20160828221
-rw-rw-r-- 1 root root  446240 Aug 28 22:18 xCAT-client-2.12.2-snap201608282218.
-rw-rw-r-- 1 root root     216 Aug 28 22:19 xCAT-core.repo
-rw-rw-r-- 1 root root   57744 Aug 28 22:18 xCAT-genesis-scripts-ppc64-2.12.2-sn
-rw-rw-r-- 1 root root   57736 Aug 28 22:18 xCAT-genesis-scripts-x86_64-2.12.2-s
-rw-rw-r-- 1 root root 1628668 Aug 28 22:18 xCAT-server-2.12.2-snap201608282218.
-rw-rw-r-- 1 root root   27456 Aug 28 22:19 xCATsn-2.12.2-snap201608282219.ppc64
-rw-rw-r-- 1 root root   27448 Aug 28 22:19 xCATsn-2.12.2-snap201608282219.ppc64
-rw-rw-r-- 1 root root   27376 Aug 28 22:19 xCATsn-2.12.2-snap201608282219.s390x
-rw-rw-r-- 1 root root   27484 Aug 28 22:19 xCATsn-2.12.2-snap201608282219.x86_6
-rw-rw-r-- 1 root root   38472 Aug 28 22:18 xCAT-vlan-2.12.2-snap201608282218.no
[root@fs4 xcat-core]# ./mklocalrepo.sh
/root/xcat2122ug/xcat-core
[root@fs4 xcat-core]# yum update "_xCAT_"
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use su                                                                                                             bscription-manager to register.
xCAT-rhels7.3-path0                                      | 4.1 kB     00:00
xcat-2-core                                              | 2.5 kB     00:00
xcat-otherpkgs0                                          | 2.9 kB     00:00
xcat-2-core/primary_db                                     |  24 kB   00:00
Resolving Dependencies
--> Running transaction check
---> Package perl-xCAT.noarch 4:2.12-snap201606240317 will be updated
---> Package perl-xCAT.noarch 4:2.12.2-snap201608282217 will be an update
---> Package xCAT.ppc64le 0:2.12-snap201606240318 will be updated
---> Package xCAT.ppc64le 0:2.12.2-snap201608282219 will be an update
--> Processing Dependency: xCAT-probe >= 2.12.1 for package: xCAT-2.12.2-snap201                                                                                                             608282219.ppc64le
--> Processing Dependency: xCAT-genesis-scripts-x86_64 for package: xCAT-2.12.2-                                                                                                             snap201608282219.ppc64le
---> Package xCAT-buildkit.noarch 4:2.12-snap201606240317 will be updated
---> Package xCAT-buildkit.noarch 4:2.12.2-snap201608282218 will be an update
---> Package xCAT-client.noarch 4:2.12-snap201606240318 will be updated
---> Package xCAT-client.noarch 4:2.12.2-snap201608282218 will be an update
---> Package xCAT-genesis-scripts-ppc64.noarch 1:2.12-snap201606240317 will be u                                                                                                             pdated
---> Package xCAT-genesis-scripts-ppc64.noarch 1:2.12.2-snap201608282218 will be                                                                                                              an update
---> Package xCAT-server.noarch 4:2.12-snap201606240318 will be updated
---> Package xCAT-server.noarch 4:2.12.2-snap201608282218 will be an update
---> Package xCAT-vlan.noarch 4:2.12-snap201606240317 will be updated
---> Package xCAT-vlan.noarch 4:2.12.2-snap201608282218 will be an update
--> Running transaction check
---> Package xCAT.ppc64le 0:2.12.2-snap201608282219 will be an update
--> Processing Dependency: xCAT-probe >= 2.12.1 for package: xCAT-2.12.2-snap201                                                                                                             608282219.ppc64le
---> Package xCAT-genesis-scripts-x86_64.noarch 1:2.12.2-snap201608282218 will b                                                                                                             e installed
--> Finished Dependency Resolution
Error: Package: xCAT-2.12.2-snap201608282219.ppc64le (xcat-2-core)
           Requires: xCAT-probe >= 2.12.1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by daniceexi** [comment]
@immarvin could you take a look why PCM's build does not include the xCAT-probe package?

**Comment by immarvin** [comment]
seems xCAT-probe is not included for "PCM"
````
69 # These are the rpms that should be built for each kind of xcat build
 70 ALLBUILD="perl-xCAT xCAT-client xCAT-server xCAT-test xCAT-buildkit xCAT xCATsn xCAT-genesis-scripts xCAT-SoftLayer xCAT-vla    n xCAT-confluent xCAT-probe"
 71 ZVMBUILD="perl-xCAT xCAT-server xCAT-UI"
 72 ZVMLINK="xCAT-client xCAT xCATsn"
 73 # xCAT and xCATsn have PCM specific configuration - conserver-xcat, syslinux-xcat
 74 # xCAT-server has PCM specific configuration - RESTAPI(perl-JSON)
 75 # xCAT-client has PCM specific configuration - getxcatdocs(perl-JSON)
 76 PCMBUILD="xCAT xCAT-server xCAT-client xCATsn"
 77 PCMLINK="perl-xCAT xCAT-buildkit xCAT-genesis-scripts-x86_64 xCAT-genesis-scripts-ppc64 xCAT-vlan"
 78 # Note: for FSM, the FlexCAT rpm is built separately from gsa/git
 79 FSMBUILD="perl-xCAT xCAT-client xCAT-server"
 80 FSMLINK=""
````

**Comment by neo954** [comment]
Maybe, PCM does not need package `xCAT-probe`. We may just remove this dependency.

**Comment by hu-weihua** [comment]
@fenggaobj , due to @tingtli has built a new branch 2.12.3-pcm, this branch has included all xcat probe code, so I think if you build your xcat-core depending on this new branch, you won't hit this problem. Could you verify it ? thanks.

**Comment by hu-weihua** [comment]
@fenggaobj , I have not gotten any update for this issue for a long time. I suppose new 2.12.3 branch has resolved your problem. I set this issue to ``pending``, if you have any new problem, you can comment again. thanks.

**Comment by whowutwut** [comment]
Closing issue, please re-open if needed.
