### ISSUE TITLE
[fvt]2.11:mknb will run two twice during install xcat

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#181]
How to reproduce:
1.down load the latest build
2.yum install xCAT
3.tail -f /var/log/xcat/commands.log
====================================================
[Date]       2015-9-13 6:0:53
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
====================================================
[Date]       2015-9-13 6:1:20
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
---------------------------------->mknb will run two time

**Comment by penguhyang** [comment]
#285 FYI

**Comment by junxiawang** [comment]
issue reproduce on xcat2.11.1 on sles12.1 on ppc64le 
Details:
```
====================================================
[Date]       2016-04-14 06:34:27
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.lzma in /tftpboot/xcat
====================================================
[Date]       2016-04-14 06:54:05
[ClientType] cli
[Request]    mknb ppc64
[Response]
Creating genesis.fs.ppc64.lzma in /tftpboot/xcat
```

**Comment by junxiawang** [comment]
verify the issue using latest build and I works now.

**Comment by daniceexi** [comment]
@junxiawang What was the fix? Who made the fix?

**Comment by immarvin** [comment]
ping @penguhyang
