### ISSUE TITLE
renergy for Power 7 hardware does not work in xcat 2.12 on redhat 2.7

### ISSUE THREAD

**Issue by billwaj** [xcat2/xcat-core#1813]
The xcat 2.12.2 renergy man page states that it supports older Power 7 hardware which should use the PPCenergy.pm code to ultimately use the xCAT-pEnergy rpm to obtain the specified values.  However, PPCenergy.pm is not used and energy.pm is used and has errors with some values.

Is older Power 7 and Power 6 hardware still supported in xCAT 2.12 ?

**Comment by whowutwut** [comment]
@zet809  could you take a look at this?

**Comment by daniceexi** [comment]
@billwaj The energy management for none-OPAL is supported in 2.12.2.  
In xCAT code, we need a way to use the machine type to figure out whether it's a OPAL server. So we have a list for all none-OPAL server. The ones which are not in the list are considered as OPAL.

So I guess you problem was you run renergy against a non-OPAL server which is not in the **non-OPAL** list.

Then what's the MTMS of your server?

**Comment by billwaj** [comment]
The machine type and model of the power 7 I tested for was 9125-F2C.

**Comment by daniceexi** [comment]
@zet809 could you check whether the 9125-F2c has been added in the power6 list. In certain subroutine in the Utils.pm.

**Comment by zet809** [comment]
It seems the MTM 9125-F2C is not put in the power6 list. 
@billwaj Hi, bill, the hash below include the machine type/model for p6 and p7 servers, will you pls add MTM for your servers to have a try? If works, pls tell us all the MTM you'd like to add into the list and then we can check them in xcat. Thx!

# the MTM of P6 and P7 machine
my %MTM_P6P7 = (
    # P6 systems
    'xxxx-xxx' => 1,
    # P7 systems
    'xxxx-xxx' => 1,
);

**Comment by zet809** [comment]
@billwaj Hi, Bill, any update?

**Comment by billwaj** [comment]
Yes and thanks, adding 9125-F2C to %MTM_P6P7 in Utils.pm now successfully calls the PPCenergy plugin  which in turn calls xCAT_cim_client.


One problem I am now working through is that xCAT_cim_client is passed in the hostname of the specified FSP and not the ip address as was done in past xCAT release.  This is causing an error which I am now investigating.


________________________________

**Comment by daniceexi** [comment]
@billwaj 
Besides ``9125-F2C``, are there any other server types you want to add in the P6P7 support list?

**Comment by billwaj** [comment]
The one I'm interested in is 9125-F2C but you can add 8233-E8B and 8236-E8C which can be used for a management node.


thanks.

________________________________

**Comment by daniceexi** [comment]
@zet809 
Please guide @xuweibj to make the change. Thanks.

**Comment by zet809** [comment]
@billwaj This fix will be included in xcat2.12.4, do you also need it in other release?

**Comment by billwaj** [comment]
We do not need this fix in other releases. Thank you for your attention on this.


________________________________

**Comment by zet809** [comment]
@billwaj The code had been included in xCAT 2.12.4, will you pls close this defect if verified? Thx a lot !

**Comment by zet809** [comment]
The code have been included in xCAT 2.12.4, so close this defect.
