### ISSUE TITLE
[CORAL-EA]: Mellanox IB installer cannot support multiple kernels on RHEL 7.x

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1816]
In the hack_uname function, it doesn't support multiple kernels correctly.  Introduced to fix Issue #316   The `uname -r` command looks in the `/lib/modules` directory but only echos 1 kernel back.  If there are more, it will pick the wrong one and fail when `uname -m` is called because it takes the output of `uname -r` and passes it to rpm.  

We will get a message like:
```
# uname -m
package kernel-3.10.0-327.el7.ppc64le is not installed
```

The other issue found by LBS team is that the line 150, ` ppc64el vs ppc64le`

**Comment by neo954** [comment]
@whowutwut, if there are multiple linux kernel installed on the same machine, the `hack_uname()` will choose the latest one, which is the one has larger version number. There is no way to guess which is the right one. The administrator just know which is the right one in his/her mind. There is no way to guess it properly.

**Comment by neo954** [comment]
@whowutwut, on a ppc64le system, `uname -m` always show `ppc64le`, no matter on RHEL or Ubuntu. There is no chance of it to show `ppc64el`. The function `hack_uname` just mimic the behavior of the real `uname` command.

**Comment by hu-weihua** [comment]
Hi @whowutwut , how does ``hack_uname()`` work just as @neo954 explained above, we can't anticipate the right kernel version unless administrator tell us. If we must know some information from administrator before running IB installer, we have to offer a command option to administrator to input such information.  But it is a real good option?  xCAT really can support multiple kernel well?  I think xCAT install the latest kernel during provision too.

Could you tell me where  LSB team get ``ppc64el``? May I know their environment information?

**Comment by whowutwut** [comment]
@neo954 @hu-weihua  If you look at our code for https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2 , at line 150, we have the following code...

```
function hack_uname()
{
...
		"-m")
			ARCH="\$(dpkg --print-architecture 2>/dev/null || rpm -q kernel-\$("\$0" -r) --qf '%{arch}' 2>/dev/null)"
			case "\$ARCH" in
			"amd64")
				ARCH="x86_64"
				;;
			"ppc64el")
			        ARCH="ppc64le"
				;;
...
...
}
```

Was that a typo in our code for the case statement?  `ppc64el`

**Comment by whowutwut** [comment]
Thinking about this some more,  I really only want to achieve a few simple goals here:

1) Allow for debugging of these special hacks easily without the developer/customer needing to modify the code, but just modify the caller with a verbose option.    I don't like to just enable that `set -x`  command.  And because of the hack that we did for uname, we can't replicate the problem by doing a `chroot <rootimgdir> uname -m` because the hack does not replace uname until we run genimage. 

 In our instructions, we ask the user to copy the .v2 script, then call it in the `.postinstall` section of the osimage with the following: 
```
/install/postscripts/mlnxofed_ib_install \
-p /install/<subpath>/<MLNX_OFED_LINUX.iso> -m --add-kernel-support -end- -i $1 -n genimage
```
- Add a -v (verbose) option to get more output: `/install/postscripts/mlnxofed_ib_install -v ...`
- We call hack_uname in 2 locations in the script, add verbose output to display the following values before hacking and after hacking.   `uname -m`, `uname -r`, `uname -s` 

2) There's a `kernelver` attribute of the node definition which was set by the customer: 
```
# lsdef -t osimage rhels7.2_Minsky-ppc64le-diskless-compute -i kernelver
Object name: rhels7.2_Minsky-ppc64le-diskless-compute
    kernelver=3.10.0-327.28.2.el7.openpower5.ppc64le
```
If this is specified, trickle this value down to the hack_uname function so instead of a wildcard in `/lib/modules` we use the kernelver provided by the user. 

```
		"-r")
			cd /lib/modules && for d in * ; do : ; done && echo \$d
			;;
```
would be 
```
		"-r")
			cd /lib/modules && for d in ${KERNEL_VER} ; do : ; done && echo \$d
			;;
```

I think those simple changes would be sufficient to resolve this issue and set us up to debug this more easily in the future.

**Comment by neo954** [comment]
@whowutwut,

No, `ppc64el` is not a typo. It seems you do not really understand the story between `ppc64le` and `ppc64el`.

To make the long story short, on ppc64le machine which runs Ubuntu, `dpkg --print-architecture` shows `ppc64el`, and `uname -m` shows `ppc64le`. The hacked `uname` does exactly what it looks like.

**Comment by whowutwut** [comment]
@neo954  Thanks,..  I see now.    It's only testing for the case where  Ubuntu returns something else and re-setting ARCH.  Ok, I figured that the change LBS made was causing a failure and it helped to resolve it. but looks like it wasn't something that was needed.

**Comment by neo954** [comment]
@whowutwut, The `kernelver` attribute is not always available for an osimage. And the code of xCAT should definitely work without `kernelver` attribute set in an osimag.

**Comment by whowutwut** [comment]
Sure, those are just some suggestions to make this situation better or work around the problem in xcat without the user modifying a script to support a different kernel is ok.

**Comment by hu-weihua** [comment]
@whowutwut, I think we can take your 2 requirement into account. it make the IB installer script better.
But I need to know the priority of this item. it seams it isn't a block issue. Do we need to do it in xCAT 2.12.3? We have a lot high priority work item during next 3 weeks.

I still hope you could offer the directory structure of ``/lib/modules`` in customer 's environment for me. it's helpful for me to understand the root trigger of this issue. Because even we do fix this issue, the fix is a fix for this specific case, so the detailed information (include real file name and directory name) is helpful. thanks

**Comment by whowutwut** [comment]
@hu-weihua, thanks for flagging this early! If you are busy, we can find someone else to work on this, no worries. 

@gurevichmark  will make some quick changes for the 2.12.3 and decide on a longer term solution. I want to at least fix the problem where uname hack is hidden from the user.   We can't reproduct this in a chroot environment because we restored it after `genimage` failed.  So I just want to avoid this unnecessary debug time in the future with some easy debug statements. 

If you copy the uname hack script into a temporary folder, you can easily re-create without the customers environment.  The rpm returned by `uname -r` points to a package that is not installed in the OS.. . and since we rely on that to query the arch, we fail.  That's all 

```
[vhu@victorvm7 hack_uname]$ cat uname
 #!/bin/sh
...
...                      ;;
                "-r")
                        cd lib/modules && for d in * ; do : ; done && echo $d   <--- modify this line to look in PWD for lib/modules instead of /lib/modules 
...
                esac
                exit 0

```

Simulate multiple kernels 
```
[vhu@victorvm7 hack_uname]$ mkdir -p lib/modules/3.10.0-123.openpower4.el7.x86_64
[vhu@victorvm7 hack_uname]$ mkdir -p lib/modules/3.10.0-123.openpower5.el7.x86_64
[vhu@victorvm7 hack_uname]$ mkdir -p lib/modules/3.10.0-123.el7.x86_64
```
Run the commands:
```
[vhu@victorvm7 hack_uname]$ ./uname -r
3.10.0-123.openpower5.el7.x86_64
[vhu@victorvm7 hack_uname]$ ./uname -m
package kernel-3.10.0-123.openpower5.el7.x86_64 is not installed
```

**Comment by gurevichmark** [comment]
Pull request #1839 used to add debug statement before and after `hack_uname()`.
This issue will be moved to the next release to fix the `hack_uname()` to handle multiple kernels in `/lib/modules` directory.

**Comment by whowutwut** [comment]
Thinking about this some more, should we just not specify the exact kernel version to get the architecture of the machine?  

The `uname -r` providing a random kernel response is still concerning, need to check what Mellanox installer script is using `-r` for...   

But anyway..... 

```
$ rpm -q kernel --qf %{arch}
x86_64
# rpm -q kernel --qf %{arch}
ppc64le
```

**Comment by whowutwut** [comment]
Closing issue, will re-open if we start to see problems with the code changes
