### ISSUE TITLE
Configbond is not work

### ISSUE THREAD

**Issue by wjianf** [xcat2/xcat-core#1818]
## Configured nic bonding with "configbond bond0 ib0@ib2 mode=1", but the bonding nic couldn't be brought up with the message as below:

[root@pcm421rhel71mn postscripts]# updatenode compute000 confignics
compute000: Mon Sep 12 05:08:39 EDT 2016 Running postscript: confignics
compute000: confignics on compute000: config install nic:0, remove: 0, iba ports:
compute000: eth2!192.168.12.3
compute000: ib1!192.168.199.2
compute000: bond0!192.168.200.2
compute000: bmc!9.111.251.142
compute000: bond0!configbond bond0 ib0@ib2 mode=1
compute000: confignics on compute000: processing custom scripts: configbond bond0 ib0@ib2 mode=1 for interface bond0
compute000: configbond: Create bond interface bond0 with slaves="ib0 ib2" opts="mode=1"
compute000: configbond: IP information for bond0: IP=192.168.200.2; network=192.168.200.0; netmask=255.255.255.0
## After adding 'TYPE=Bond' in bonding config files, the bonding can be brought up

[root@compute000 ~]# cat /etc/sysconfig/network-scripts/ifcfg-bond0
DEVICE=bond0
BOOTPROTO=none
IPADDR=192.168.200.2
NETMASK=255.255.255.0
ONBOOT=yes
USERCTL=no
BONDING_OPTS="mode=1"
[root@compute000 ~]# ifup bond0
Error: no device found for connection 'System bond0'.
[root@compute000 ~]# echo "TYPE=Bond" >> /etc/sysconfig/network-scripts/ifcfg-bond0
[root@compute000 ~]# ifup bond0
Connection successfully activated (master waiting for slaves) (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/14)
You have mail in /var/spool/mail/root
[root@compute000 ~]# ifconfig bond0
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 192.168.200.2  netmask 255.255.255.0  broadcast 192.168.200.255
        inet6 fe80::6833:76ff:fed4:57a5  prefixlen 64  scopeid 0x20<link>
        ether 6a:33:76:d4:57:a5  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by daniceexi** [comment]
@bybai could you take a look of this issue?

**Comment by bybai** [comment]
TYPE=Bond is missing from configbond

**Comment by wjianf** [comment]
Please help merge the fix into 2.9.1-pcm and 2.11-pcm branch. Thanks!!

**Comment by wjianf** [comment]
Please also commit the fix into 2.12-pcm branch.

**Comment by bybai** [comment]
Hi @wjianf, I cannot find 2.12-pcm from pull request page, could you check if this branch is fine?

**Comment by robin2008** [comment]
Yuan,  is the fix in 2.12.3?

**Comment by whowutwut** [comment]
@robin2008  Yes, the code merged referenced in the issue was merged before 9/30, so it is in the 2.12.3 version of xCAT.  @tingtli @wjianf @bybai  can we close out this issue?
