### ISSUE TITLE
rflash through xcat is failing, but the command xcat is using works.

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1822]
rflash through xcat is failing, but the command xcat is using works.

[root@c712ems4 tom]# rflash ./8335GTB_820.1634.20160907b_update.hpm
Error: Invalid nodes and/or groups in noderange: ./8335GTB_820.1634.20160907b_update.hpm
[root@c712ems4 tom]# rflash c712f7n06-pvt ./8335GTB_820.1634.20160907b_update.hpm
c712f7n06-pvt: rflash started, please wait.......
c712f7n06-pvt: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 10.128.130.36 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/tom/./8335GTB_820.1634.20160907b_update.hpm force failed.
[root@c712ems4 tom]# rflash c712f7n06-pvt `pwd`/8335GTB_820.1634.20160907b_update.hpm
c712f7n06-pvt: rflash started, please wait.......
c712f7n06-pvt: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 10.128.130.36 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/tom/8335GTB_820.1634.20160907b_update.hpm force failed.

I grabbed the command from the error above and ran it:
[root@c712ems4 tom]# /opt/xcat/bin/ipmitool-xcat -H 10.128.130.36 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/tom/8335GTB_820.1634.20160907b_update.hpm force
Setting large buffer to 15000

PICMG HPM.1 Upgrade Agent 1.0.9:

Validating firmware image integrity...OK
Performing preparation stage...
Services may be affected during upgrade. Do you wish to continue? (y/n): y
OK

Performing upgrade stage:

-------------------------------------------------------------------------------
|ID  | Name        |                     Versions                        | %  |
|    |             |      Active     |      Backup     |      File       |    |
|----|-------------|-----------------|-----------------|-----------------|----|
|*  2|BIOS         |   1.10 00000001 | ---.-- -------- |   1.0a 00000011 |100%|
|    |Upload Time: 01:53             | Image Size: 33554584 bytes              |

**Comment by markprez** [comment]
[root@c712ems4 tom]# lsxcatd -v
Version 2.12.2 (git commit 6fff020a905c64cabe31896e653aebc942ee0694, built Thu Sep  1 06:18:21 EDT 2016)

**Comment by whowutwut** [comment]
@markprez  can you also show us the version of ipmitool-xcat? `rpm -qa | grep ipmitool-xcat` Thanks

**Comment by markprez** [comment]
ipmitool-xcat-1.8.15-2.ppc64le

**Comment by chenglch** [comment]
Services may be affected during upgrade. Do you wish to continue? (y/n): y 

The output of the prompt above make me confusing, not sure if the rflash patch for ipmitool-xcat enabled or not while building the ipmitool-xcat package.

**Comment by whowutwut** [comment]
@chenglch yes good catch. It seems like this version of ipmitool-xcat isn't patched correctly... I wonder how this happened... 

Perhaps we need to test the build of ipmitool-xcat after we build to verify the patches are implemented correctly

**Comment by pdlun92** [comment]
Per note from @markprez

**Comment by pdlun92** [comment]
Per note from @markprez 

``` I was looking and we have ipmitool-xcat-1.8.15-2.ppc64le which shows:

[root@c712ems4 hpm]# /opt/xcat/bin/ipmitool-xcat -V
ipmitool-xcat version 1.8.17
``` 

This leads me to believe ipmitool-xcat-1.8.15-2 was overwritten by source ipmitool-1.8.17 compiled as ipmitool-xcat-1.8.17.  If it is source, that would explain the absence of rflash patch.  

Rejecting this issue
