### ISSUE TITLE
xCAT not start from hard disk after provsioned statefull node

### ISSUE THREAD

**Issue by bhbai** [xcat2/xcat-core#1828]
Env: 

> lsxcatd -a
> Version 2.12 (git commit b33cb213ce79f91621cd65932c9798c735b74bc4, built Fri Jun 24 03:17:21 EDT 2016)
> This is a Management Node
> cfgloc=Pg:dbname=xcatdb;host=10.45.5.5|xcatadm
> dbengine=Pg
> dbname=xcatdb
> dbhost=10.45.5.5
> dbadmin=xcatadm
> [root@cit1055 ~]# lsb_release -a
> LSB Version:    :core-4.1-noarch:core-4.1-ppc64le
> Distributor ID: RedHatEnterpriseServer
> Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
> Release:        7.2
> Codename:       Maipo
>  uname --a
> Linux  3.10.0-327.el7.ppc64le #1 SMP Thu Oct 29 17:31:13 EDT 2015 ppc64le ppc64le ppc64le GNU/Linux

Expected result: xCAT must/should boot from hard disk automatically while provision with statefull image.

Detail steps as following:
```
1. Generate discovered_stanzas:
#bmcdiscover --range 9.42.xx.xx -z

2. Add mtm/serial number in stanzas files(If Neccessery)

3. Import <nodecn>
#cat /tmp/cf_predefined_stanzas | mkdef -z -f 
#makehosts <nodecn>

3. Add some <nodecn> attributes
#chdef <nodecn> groups=__Managed,__NetworkProfile_network,__ImageProfile_rhels7.2-ppc64le-statefull-compute,__HardwareProfile_IBM_PowerNV,compute
#chdef <nodecn> bmcpassword=test
#<nodecn> power reset
#makedns -n

4.Scan until get <nodecn> mac
#lsdef <nodecn> | grep mac= | wc -l

5.Cleanup imported node
#nodepurge <nodecn>
#service dhcpd restart

6.Generate bmc format import file as following:
<nodecn>:
	mac=00:90:fa:b9:xx:xx
	nicips=bmc!9.42.xx.xx

7.Import nodecn
nodeimport file=/cf_hostinfo_file networkprofile=fsp_network imageprofile=rhels7.2-ppc64le-statefull-compute hostnameformat=gssio#NNN hardwareprofile=IBM_PowerNV

8.Add some <nodecn> attributes
#chdef <nodecn> bmcpassword=test
#<nodecn> power reset
```

Check result:xCAT not choose start from hard-disk option. refer to:
![2016-09-08 17_27_xcatbooterr](https://cloud.githubusercontent.com/assets/18112233/18463580/be5d7644-79bd-11e6-9fb9-fd7c803904d5.png)

**Comment by tingtli** [comment]
@junxiawang  Would you please take a look at this defect to see if it could be recreated?
I think we ever run the test

**Comment by zet809** [comment]
The data below can be got both from petitboot menu and diskful OS, it shows that the server need to boot from network but empty petitboot configuration file got. That is why the server hung at petitboot menu. 
 # nvram --print-config
"common" Partition
---------------------
petitboot,bootdevs=uuid:00:90:fa:b9:ba:ae uuid:07cf7177-43fe-4141-a38d-53b7e4f37994
petitboot,network=00:90:fa:b9:ba:ae,dhcp
petitboot,bootdev=uuid:00:90:fa:b9:ba:ae
petitboot,timeout=45
petitboot,write?=false

For a server it works, the output shall like this:
 # nvram --print-config
"common" Partition
---------------------

To fix this issue, we need to clean the nvram before rebooting.

**Comment by wwzhubj** [comment]
I hit this problem in firestone node. 
c712f1n01-pvt: System Firmware Product Version: IBM-firestone-ibm-OP8_v1.7_1.62
c712f1n01-pvt: System Firmware Product Additional Info: hostboot-bc98d0b-1a29dff
c712f1n01-pvt: System Firmware Product Additional Info: occ-0362706-16fdfa7
c712f1n01-pvt: System Firmware Product Additional Info: skiboot-5.1.13
c712f1n01-pvt: System Firmware Product Additional Info: hostboot-binaries-43d5a59
c712f1n01-pvt: System Firmware Product Additional Info: firestone-xml-e7b4fa2-c302f0e
c712f1n01-pvt: System Firmware Product Additional Info: capp-ucode-105cb8f

the node can not auto boot from the os option after installation.

**Comment by zet809** [comment]
After clean the nvram, the node can boot successfully. 
But the current problem is, who and when the nvram data is wrote. From xcat point of view, we need to clean up the nvram if there is any in setbootfromdisk script.

**Comment by zet809** [comment]
I have opened a defect https://bugzilla.linux.ibm.com/show_bug.cgi?id=146624 on bugzilla to trace this issue from LTC point of view.

**Comment by zet809** [comment]
Move to next release for a better solution.

**Comment by zet809** [comment]
Move to next release for a better solution. User can clear the nvram with "nvram --update-config=petitboot,bootdev=", "nvram --update-config=petitboot,network=".

**Comment by zet809** [comment]
The script cleanup_nvm.sh provided by the pull requset #1900 will be included in xCAT package, if this issue encountered, you can add it as the postscript to have the CN execute it pre-boot.

**Comment by robin2008** [comment]
Is this issue always hit,  or just casually? 
It is hard to let user to make the decision how to fix such hang issue.

**Comment by zet809** [comment]
@bhbai If this defect is fixed with the script provide above, will you pls close this defect? Thx!

**Comment by whowutwut** [comment]
There is a comment in the pull request.. can we close?

**Comment by bhbai** [comment]
Fixed after use patch xCAT/postscripts/cleanup_nvm.sh(https://github.com/xcat2/xcat-core/pull/1900/files)  with following steps:
====================
nodepurge cnfull1
ipmitool-xcat -I lanplus -H 9.xx.xx.xx -P <password> power off
nodeimport file=/root/bhbai/cit1056_mac.conf networkprofile=zhao_network imageprofile=rhels7.2-ppc64le-stateful-compute hostnameformat=cnfull#N hardwareprofile=IBM_PowerNV
chdef cnfull1  bmcpassword=<password>
chdef cnfull1 installnic=mac
nodeset cnfull1 osimage=rhels7.2-ppc64le-stateful-compute
rsetboot cnfull1  net
ls /install/postscripts/cleanup_nvm.sh
chdef cnfull1 postscripts=cleanup_nvm
lsdef cnfull1 |grep script
ipmitool-xcat -I lanplus -H 9.xx.xx.xx -P <password> power on
service conserver stop
ipmitool-xcat -I lanplus -H 9.xx.xx.xx -P <password> power  status
service dhcpd stop

Note: Due to there is two mac in the same BMC pools,so need to stop DHPC service after osimage delivery
