### ISSUE TITLE
[FVT] Please support PowerKVM 3.1.0 installation in the latest xCAT version 2.11

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#183]
The latest PowerKVM build used for this testing is 3.1.0.0-31 Alpha. The xCAT used in this testing is 2.11-local20150916, build from the latest source code locally.

We need PowerKVM 3.1.0 installation support. Based on the wiki page of PowerKVM and some experience I got from the testing. The following boot arguments are needed. Below shows the actual boot arguments I was used during my testing.

    Kernel:
        http://10.2.3.27/install/powerkvm3.1.0-31/ppc/ppc64le/vmlinuz

    Initrd:
        http://10.2.3.27/install/powerkvm3.1.0-31/ppc/ppc64le/initrd.img

    Boot arguments:
        ifname=enx97:6c:ae:86;02:43:90
        ip=10.3.29.1::10.0.0.103:255.0.0.0:c910f03c29:enx97:none
        root=live:http://10.2.3.27/install/powerkvm3.1.0-31/LiveOS/squashfs.img
        repo=http://10.2.3.27/install/powerkvm3.1.0-31/packages
        console=hvc0
        console=tty0

**Comment by immarvin** [comment]
hi, I tried to provision [ibm-powerkvm-3.1.0.0-33.0-ppc64le-alpha-201509231712.iso](http://ltcphx.austin.ibm.com/isos/frobisher/PowerKVM/releases/3.1.0/0.33.0/iso/) on firestone EUH machine successfully.

the osimage definition is:

````

[root@c910f02c02p08 ~]# lsdef -t osimage -o pkvm3.1-ppc64le-install-compute
Object name: pkvm3.1-ppc64le-install-compute
    imagetype=linux
    osarch=ppc64le
    osdistroname=pkvm3.1-ppc64le
    osname=Linux
    osvers=pkvm3.1
    otherpkgdir=/install/post/otherpkgs/pkvm3.1/ppc64le
    pkgdir=/install/pkvm3.1/ppc64le
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/pkvm/compute.pkvm3.ppc64le.tmpl
````

**Comment by immarvin** [comment]
There are some error messages during system shutting down, opened a [defect](https://bugzilla.linux.ibm.com/show_bug.cgi?id=131054) to LTC

The error message:
````
Unmounting file systems.^M^M
Unmounting /dev/mqueue.^M^M
Unmounting /sys/kernel/debug.^M^M
Unmounting /dev/hugepages.^M^M
Unmounting /sys/kernel/config.^M^M
All filesystems unmounted.^M^M
Deactivating swaps.^M^M
All swaps deactivated.^M^M
Detaching loop devices.^M^M
Detaching loopback /dev/loop2.^M^M
Detaching loopback /dev/loop1.^M^M
Detaching loopback /dev/loop0.^M^M
All loop devices detached.^M^M
Detaching DM devices.^M^M
Detaching DM 253:3.^M^M
Could not detach DM /dev/dm-3: Invalid argument^M^M
Detaching DM 253:25.^M^M
Could not detach DM /dev/dm-25: Invalid argument^M^M
Detaching DM 253:2.^M^M
Could not detach DM /dev/dm-2: Invalid argument^M^M
Detaching DM 253:1.^M^M
Could not detach DM /dev/dm-1: Invalid argument^M^M
Detaching DM 253:0.^M^M
Could not detach DM /dev/dm-0: Invalid argument^M^M
Not all DM devices detached, 6 left.^M^M
Detaching DM devices.^M^M
Detaching DM 253:3.^M^M
Could not detach DM /dev/dm-3: Invalid argument^M^M
Detaching DM 253:25.^M^M
Could not detach DM /dev/dm-25: Invalid argument^M^M
Detaching DM 253:2.^M^M
Could not detach DM /dev/dm-2: Invalid argument^M^M
Detaching DM 253:1.^M^M
Could not detach DM /dev/dm-1: Invalid argument^M^M
Detaching DM 253:0.^M^M
Could not detach DM /dev/dm-0: Invalid argument^M^M
Not all DM devices detached, 6 left.^M^M
Cannot finalize remaining file systems and devices, giving up.^M^M
Storage is finalized.^M^M
Successfully changed into root pivot.^M^M
````

**Comment by whowutwut** [comment]
This seems to be an issue with the **shutdown** of the PowerKVM hypervisor.  Should we change the name of the title.  If this issue is owned by the LTC, should we close out this Issue under xCAT or leave it open to track?

**Comment by whowutwut** [comment]
Should we move this to 2.12 or are we planning to do something with this for 2.11?  It is tagged "FUTURE" in the label...

**Comment by daniceexi** [comment]
@immarvin Any update from LTC?

**Comment by immarvin** [comment]
there is no update from ltc

**Comment by immarvin** [comment]
will add a entry in release notes

**Comment by whowutwut** [comment]
Ok, Let's move to 2.12 then since we will document on the Release Notes

**Comment by neo954** [comment]
This bug was already fixed and verified. I will close this one.
