### ISSUE TITLE
go-xcat failed to call non-existing yum subcommand on RHEL 6

### ISSUE THREAD

**Issue by wangwhao** [xcat2/xcat-core#1836]
On RHEL 6.7, go-xcat tried to call "yum --nogpgcheck updateinfo", which does not exist.

[root@c853mgrs1 yum.repos.d]# /tmp/go-xcat
go-xcat version 1.0.2

Usage: go-xcat [OPTION]... [ACTION]
Install xCAT automatically

Options:
Mandatory arguments to long options are mandatory for short options too.
  -h, --help                    display this help and exit
  --xcat-core=[URL]             use a different URL or path for the xcat-core
                                repository
  --xcat-dep=[URL]              use a different URL or path for the xcat-dep
                                repository
  -x, --xcat-version=[VERSION]  specify the version of xCAT; cannot use with
                                --xcat-core
  -y, --yes                     answer yes for all questions

Actions:
  install                       installs all the latest versions of xcat-core
                                and xcat-dep packages from the repository
  update                        updates installed xcat-core packages to the
                                latest version from the repository

Examples:
  go-xcat
  go-xcat install
  go-xcat update
  go-xcat --yes install
  go-xcat -x 2.12 -y install
  go-xcat --xcat-version=devel install
  go-xcat --xcat-core=/path/to/xcat-core.tar.bz2 \
          --xcat-dep=/path/to/xcat-dep.tar.bz2 install
  go-xcat --xcat-core=http://xcat.org/path/to/xcat-core.tar.bz2 \
          --xcat-dep=http://xcat.org/path/to/xcat-dep.tar.bz2 install

xCAT (Extreme Cloud/Cluster Administration Toolkit): <http://xcat.org/>
Full documentation at: <http://xcat-docs.readthedocs.io/en/stable/>

[root@c853mgrs1 yum.repos.d]# /tmp/go-xcat install
Operating system:   linux
Architecture:       ppc64
Linux Distribution: rhel
Version:            6.7

Reading repositories ...... failed
Loaded plugins: product-id, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
No such command: updateinfo. Please use /usr/bin/yum --help

**Comment by neo954** [comment]
I will look into this one.

**Comment by wangwhao** [comment]
This time go-xcat told me that yum-plugin-security was missing. After having it installed, go-xcat succeeded to install the packages. Thanks for the help!
