### ISSUE TITLE
  [FVT] Virtual machine failed to power on with PowerKVM 3.1.0 and latest xCAT version 2.11

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#184]
The latest PowerKVM build used for this testing is 3.1.0.0-31 Alpha. The xCAT used in this testing is 2.11-local20150916, build from the latest source code locally.

    # lsdef c910f03c29k03
    Object name: c910f03c29k03
        arch=ppc64el
        groups=all
        id=3
        mac=42:07:0a:03:1d:03|42:66:0a:03:1d:03!*NOIP*|42:dd:0a:03:1d:03!*NOIP*|42:d6:0a:03:1d:03!*NOIP*
        mgt=kvm
        netboot=grub2
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        serialport=0
        serialspeed=115200
        status=booting
        statustime=09-16-2015 07:52:28
        vmcpus=2
        vmhost=c910f03c29
        vmmemory=6144
        vmnics=brenx97,brenP4p1s0f1,brenP4p1s0f2,brenP4p1s0f3
        vmstorage=phy:/dev/mapper/vdiskvg-vdisk00n03

While trying to power on the virtual machine. The following error messages were shown.

    # rpower c910f03c29k03 on
    Error: kvm plugin bug, pid 12218, process description: 'xCATd SSL: rpower to c910f03c29k03 for root@localhost: kvm instance' with error 'libvirt error code: 1, message: internal error: qemu does not support SGA
' while trying to fulfill request for the following nodes: c910f03c29k03

I striped the virtual machine definition xml file through `tabdump kvm_nodedata`. Here is what I got.

    <domain type="kvm">
      <name>c910f03c29k03</name>
      <clock offset="utc" />
      <devices>
        <console type="pty">
          <target port="1" />
        </console>
        <disk device="disk" type="block">
          <source dev="/dev/mapper/vdiskvg-vdisk00n03" />
          <target bus="scsi" dev="sda" />
        </disk>
        <disk device="cdrom" type="file">
          <target dev="sdd" />
        </disk>
        <graphics autoport="yes" listen="0.0.0.0" password="UrSi7F5T07jMDZPKV8qr" type="vnc" />
        <input bus="usb" type="tablet" />
        <interface type="bridge">
          <mac address="42:07:0a:03:1d:03" />
          <model type="virtio" />
          <source bridge="brenx97" />
        </interface>
        <interface type="bridge">
          <mac address="42:66:0a:03:1d:03" />
          <model type="virtio" />
          <source bridge="brenP4p1s0f1" />
        </interface>
        <interface type="bridge">
          <mac address="42:dd:0a:03:1d:03" />
          <model type="virtio" />
          <source bridge="brenP4p1s0f2" />
        </interface>
        <interface type="bridge">
          <mac address="42:d6:0a:03:1d:03" />
          <model type="virtio" />
          <source bridge="brenP4p1s0f3" />
        </interface>
        <sound model="ac97" />
        <video><model type="vga" vram="8192" />
        </video>
      </devices>
      <features>
    <acpi></acpi>
        <apic></apic>
        <pae></pae>
      </features>
      <memory>6291456</memory>
      <os>
        <bios useserial="yes" />
        <boot dev="network" />
        <boot dev="hd" />
        <type>hvm</type>
      </os>
      <uuid>dc2360ec-605c-e511-80af-42070a031d03</uuid>
      <vcpu>2</vcpu>
    </domain>

While I was trying to create the virtual machine manually on the PowerKVM host. The following error messages were shown.

    # virsh create c910f03c29k03.xml
    error: Failed to create domain from foo.xml
    error: internal error: qemu does not support SGA

Further investigation is need. I will continue dig into this prblem. But meanwhile, @zet809, please take a look if you have time.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/311

**Comment by whowutwut** [comment]
The workaround is to ``tabedit kvm_nodedata`` and remove the ``<bios useserial="yes" />`` line until the pull request is merged
