### ISSUE TITLE
[CUSTOMER] Feedback on xCAT documentation

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1842]
Some feedback was given from an xCAT customer. Opening this issue to track.  Maybe the RTD documentation is too basic for all users of xCAT and we need to cover more advanced management. 

Add some sections on how the user can determine the type of power machines they are on. Can xCAT provide a tool or maybe incorporate this into the wizard or probe commands.   Sections for x86_64 maybe need to be looked into if we really want to put the SourceForce docs behind us. 

Feedback:
- The xCAT admins are command line driven geeks and one of them has been using xCAT since the earliest versions.  They use tabedit of tables a lot vs chdef commands.  
- The on-line education was very confusing.  They did not know if they had an HMC, an FSP or a BMC.  This lead them to follow paths that messed up the S824L firmware.
- There is no documentation on whether x86 xCAT can provision the S824L or any other Power server.  
- They saw the documentation only supporting one case study, a NEW xCAT installation.  They want to see documentation on how to install it on an existing xCAT installation.

**Comment by whowutwut** [comment]
I think updating the docs would be a never ending task, I'd much rather see some specific requests directly from community users opened  in GitHub, and perhaps samples/playbooks or even shipped stanzas with the product that users could invoke to create a  base starting point.  instead of pure documentation changes.

**Comment by jose-d** [comment]
> shipped stanzas

this is actually not bad idea. Indeed this is not something what can be done in zero time, but having directory with stanzas for common hw or vm setups could be nice starting point.

I know that there is IBM behind xcat, is it fine to mention other than their products?
