### ISSUE TITLE
genimage doesn't pull pkgdir, pkglist, otherpkgdir, otherpkglist from osimage/linuximage tables

### ISSUE THREAD

**Issue by jet737700** [xcat2/xcat-core#1843]
genimage will use the osimage definition for information to generate
       this image.  Additional options specified on the command line will
       override any corresponding previous osimage settings, and will be
       written back to the osimage definition.

It looks like what it really does is to pull them from the "old" default locations and ignores the osimage/linuximage definitions.

In this case:

 lsdef -t osimage osds
Object name: osds
    exlist=/install/custom/netboot/rh/compute.exlist
    imagetype=linux
    osarch=x86_64
    osname=Linux
    osvers=rhel7.2
    otherpkgdir=/install/software/zfs/localrepo
    otherpkglist=/install/software/zfs/zfs.pkglist
    permission=755
    pkgdir=/install/rhel7.2/x86_64,/install/rhel7.2/x86_64/updates
    pkglist=/install/custom/netboot/rh/compute.pkglist
    postinstall=/install/custom/netboot/rh/compute.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhel7.2/x86_64/compute

It is SUPPOSED to pull from the base /install/rhel7.2/x86_64 AND apply updates from /install/rhel7.2/x86_64/updates AND THEN apply OTHER packages from /install/software/zfs/localrepo

It does none of that... it only pulls from the the base if it is in the "usual and customary" location. No updates are applied, no otherpkgs installed.

**Comment by immarvin** [comment]
hi @jet737700 , would you please provide the directory hierarchy of "/install/rhel7.2/x86_64/updates" and "/install/software/zfs/localrepo", is there any repo created under these 2 directories?

**Comment by immarvin** [comment]
no response, move to next release

**Comment by immarvin** [comment]
no response, close this first, please reopen it if need
