### ISSUE TITLE
[FVT]:2.11 xlf is not installed on diskful/diskless CN with KIT on rhels7.2 ppc64le 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#185]
xCAT 2.11 20150915 build.

Use partial kit xlf-15.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar to create a complete kit. Install the complete kit on diskful cn or diskless cn but find that xlf.15.1.2-15.1.2.0-150526a.ppc64le.rpm is not installed on the cn.

How to reproduce
1) download partial kit xlf-15.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar and place it under a workin dir
2) download other xlf packages which are needed by complete kit
[root@c910f03c05k08 build_input]# ls /compilers/
libxlc-13.1.2.0-150526a.ppc64le.rpm
libxlc-devel.13.1.2-13.1.2.0-150526a.ppc64le.rpm
libxlf-15.1.2.0-150526a.ppc64le.rpm
libxlf-devel.15.1.2-15.1.2.0-150526a.ppc64le.rpm
libxlmass-devel.8.1.2-8.1.2.0-150526.ppc64le.rpm
libxlsmp-4.1.2.0-150526.ppc64le.rpm
libxlsmp-devel.4.1.2-4.1.2.0-150526.ppc64le.rpm
xlc.13.1.2-13.1.2.0-150526a.ppc64le.rpm
xlc-license.13.1.2-13.1.2.0-150526a.ppc64le.rpm
xlf.15.1.2-15.1.2.0-150526a.ppc64le.rpm
xlf-license.15.1.2-15.1.2.0-150526a.ppc64le.rpm
3) create complete kit using partial kit
buildkit addpkgs xlf-15.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar.bz2 --pkgdir /compilers/
4) 
addkit xlf-15.1.2-0-ppc64le.tar.bz2
5)
addkitcomp -a -i "rhels7.2-ppc64le-install-compute" xlf.license compute, xlf.compiler-compute,xlf.rte-compute
addkitcomp -a -i "rhels7.2-ppc64le-netboot-compute" xlf.license compute, xlf.compiler-compute,xlf.rte-compute
6) execute "updatenode CN -V" if CN is diskful node or "genimage rhels7.2-ppc64le-netboot-compute " to get a image.
7) check xlf package on cn and find there is no xlf package on cn
[root@c910f03c05k23 ~]# rpm -qa |grep -i xlf
libxlf-15.1.2.0-150526a.ppc64le
xlf.license-compute-15.1.2-0.noarch
xlf-license.15.1.2-15.1.2.0-150526a.ppc64le
xlf.rte-compute-15.1.2-0.noarch
libxlf-devel.15.1.2-15.1.2.0-150526a.ppc64le
xlf.compiler-compute-15.1.2-0.noarch

**Comment by cxhong** [comment]
I found bug..

the kitpkgdeps has to give version number of xlf. like xlf.15.1.2, not xlf

I uploaded the new kit on http://xcat.org/files/kits/hpckits/2.11/rhels7.2/ppc64le/

**Comment by whowutwut** [comment]
@cxhong , I think if a fix has been provided.... , should keep the issue open, add a label to move it to "pending" and then wait for @tingtli  to verify and close the issue.

**Comment by cxhong** [comment]
oh, I closed it by accidentally.

**Comment by tingtli** [comment]
@cxhong The fix has a new issue. Please see #190  for details.

**Comment by tingtli** [comment]
I've verified the new kit. It seems that #190 is my environment clean up issue. Please ignore it.
