### ISSUE TITLE
netboot install has yum broken..

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1851]
We have a user requirement to be able to run yum install on netboot images, so that we can update a running system without having to reboot the node.  In addition, When running postinstall scripts we would like to be able to use yum to install packages, especially to ensure that prerequesite packages are installed prior to running other install scripts.  It is easiest to main these in the same postinstall script rather than adding the packages to the other pkglist option of the osimage.

When we configure a neboot system based on the standard setup for rhels7.2-ppc64le-netboot-compute  and add yum to the pkg list, we end up with a configuration where yum does not run.

It fails to run, because unlike the stateful install the there is no /etc/yum.repos.d created.

```
[root@c460mgt01 tools]# xdsh c460c071 yum --assumeyes install vim
c460c071: There are no enabled repos.
c460c071:  Run "yum repolist all" to see the repos you have.
c460c071:  You can enable repos with yum-config-manager --enable <repo>
```

xdsh c460c071 ls /etc/yum.repos.d shows no files so there is nothing to enable.

We also have a desire to install packages as part of the postinstall process, so that special packages that require special handling get properly installed, installations that may require special handling so they get postinstall fixups or other special handling so that the rpm install process does not ask questions during the installation.

During the postinstall part of the boot of a network booted image, this information is available, /xcatpost/mypostscript:OSPKGDIR='/install/RHEL-7.2-20160512.0-Garrison/ppc64le',  but it is not available to the postinstall scripts kicked off by genimage.

The problem we face with the current setup is that if we create the files a postinstall script, we have to hard code the redhat repositories that the yum.repos.d files are pointed to.  This creates problems when we switch to a different redhat image.  We would like a solution that when we change the pkgimage directory that the corresponding yum.repos.d files get changed as well, without having to manually remember to change the postinstall script files.  As of right now process can leave us with some hard to find bugs in our netboot images.

There are two ways that this could possibly be dealt with, I think.  One immediate way would be to have the genimage script create the necessary files in $installrootdir/etc/yum.repos.d in the same manner that the osiamge script installs.  The other would be to make the same kind of information available that is made available to the postscripts available to the postinstall scripts that are run at genimage time.

Since we frequently create images based on different versions and builds of redhat.  We need this to be taken care of during the genimage step, or the genimage step needs to leave behind enough environment variables such that we can get that information in a post script and create the necessary os image files.

To duplicate the problem we start with cloning off the rhels7.2-ppc64le-netboot-compute example image.

```
lsdef -t osimage rhels7.2-ppc64le-netboot-compute | \
  sed s/rhels7.2-ppc64le-netboot-compute/test-nb-yum/g |
  chdef -z
```

then copy off the package list and add yum to it:

```
mkdir -p /install/custom/test-nb-yum
cp /opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist /install/custom/test-nb-yum

add yum to the list:
echo "yum" >>/install/custom/test-nb-yum/compute.rhels7.ppc64le.pkglist

change the package list to point to the edited list.
chdef -t osimage test-nb-yum pkglist=/install/custom/test-nb-yum/compute.rhels7.ppc64le.pkglist
```

The resultant stanza file looks as follows:

```
# <xCAT data object stanza file>

test-nb-yum:
    objtype=osimage
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.exlist
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le
    permission=755
    pkgdir=/install/RHEL-7.2-20160512.0-Garrison/ppc64le
    pkglist=/install/custom/test-nb-yum/compute.rhels7.ppc64le.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.2/ppc64le/test-nb-yum
```

note the pkgdir is pointed to a special specific redhat repo directory..

```
genimage test-nb-yum
packimage test-nb-yum
nodeset c460c071 osimage=test-nb-yum
rpower c460c071 off; rpower c460c071 on;

```

```
[root@c460mgt01 tools]# xdsh c460c071 yum --assumeyes install vim
c460c071: There are no enabled repos.
c460c071:  Run "yum repolist all" to see the repos you have.
c460c071:  You can enable repos with yum-config-manager --enable <repo>
```

**Comment by ralphbellofatto** [comment]
we found that if we add ospkgs to the xcatdefault postscripts list, this problem be corrected.   the ospkgs postscript will create the yum.repos.d files correctly if yum is installed.

our xcatdefauts table looks like this now:
	"xcatdefaults","syslog,remoteshell,syncfiles,ospkgs,otherpkgs","syncfiles",,

so the ospkgs and otherpkgs get run on netboot installs at boot time.

**Comment by daniceexi** [comment]
@ralphbellofatto The postscript **ospkgs** does try to create repository file and install/update the packages from pkgdir. So ``updatenode <node> ospkgs`` might be the correct way to use want to use.

**Comment by immarvin** [comment]
any update?

**Comment by whowutwut** [comment]
I think this issue was closed by accident. I am going to re-open it.  @ralphbellofatto, This scenario you are describing seems to be a development environment where you want to allow users to have full control of the osimage for some period of time experimenting.   

Why not just generate a larger osimage that contains all the packages from the OS instead of allowing them to select the packages as needed...  What happens in the scenario where the user spend a week or so on the machine adding packages they need.... then a power outtage or something goes wrong with the machine and it is rebooted...  now everything that the person did is lost.   The netboot images are intended to be re-created on the mgmt node so that any reboot doesn't affect the image the user is consuming.

**Comment by ralphbellofatto** [comment]
victor there are two reasons for this issue.

1.  To allow a user to use a node, (off our lsf queues) with sudo rights, and allow them to mess with the node for expermental purposes.

2.  When we are running a node and we get a request to add another library.  If we put it in the ospkgs file, we can't run updatenode on the node while it is live.  We are forced to update the image.

Now why is 2 a problem.

In order to get the image out to the users and make it useful, we have to schedule a maintainance window where we stop all jobs and drain all the queues.  and then reboot the nodes.  We have had experience where we have  had users ask for been running jobs for a max time of 72 hours.  So we can't reboot the nodes until those jobs have cleared.

In the meantime, we have the problem where the user that just asked for a library to be installed, can't start work with it until the maintainance window happens.  If they report any problems with it, like they need yet another package, then they have to wait until the next maintainance window. so something that sould be satisfied less than an your can drag on for 1-4 weeks...

If update-node works on the netboot node, then that problem is solved, we only need the maintenance window for things that will require new drivers and rebooting the node anyway.
