### ISSUE TITLE
when using copycds -p, stateful install has yum point to the wrong repository.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1852]
we installed a new iso to a different directory with 
copycds isoname.iso -p /install/RHEL-7.2-20160512.0-Garrison

And we created a repository that points the pkgdir attribute to this directory.

And then provisioned a node with this image:  after the node boots we inspected the /etc/yum.repos.d file and found the following:'

[root@c460c072 yum.repos.d]# ls /etc/yum.repos.d
local-repository.repo  redhat.repo

the xcat postinstall environment properly points to the same place as the place we copied it:

```
[root@c460mgt01 lsdefs]# lsdef -t osimage test-sb-yum -i pkgdir
Object name: test-sb-yum
    pkgdir=/install/RHEL-7.2-20160512.0-Garrison/ppc64le
```

The environment that the postscripts get points to this image.
/xcatpost/mypostscript:OSPKGDIR='/install/RHEL-7.2-20160512.0-Garrison/ppc64le'

This sometimes works right and sometimes gets really messed up because each time we perform a
copycds -p '/install/RHEL-7.2-somenew-dir

a new link gets created in:
lrwxrwxrwx 1 root root 45 Sep 16 09:35 ppc64le -> /install/RHEL-some-new-dir

So the yum repos.d file now will point to the wrong place...

NOTE: When we have two or more pkgdir's then this seems to work correctly:

We also have a configuration where we have two pkgdirs as follows:

```
[root@c460mgt01 lsdefs]# lsdef -t osimage rh72_op5_login -i pkgdir
Object name: rh72_op5_login
    pkgdir=/install/RHEL-7.2-20160428.0-Garrison/ppc64le,/install/kernel-3.10.0-327.28.2.el7.openpower5
```

When we provision with this configuration we get:

```
/xcatpost/mypostscript:OSPKGDIR='/install/RHEL-7.2-20160428.0-Garrison/ppc64le,/install/kernel-3.10.0-327.28.2.el7.openpower5'
```

and

```
[root@c460mgt01 lsdefs]# xdsh c460login01 cat /etc/yum.repos.d/local*
c460login01: [local-rhels7.2-ppc64le-ppc64le]
c460login01: name=xCAT configured yum repository for rhels7.2/ppc64le/ppc64le
c460login01: baseurl=http://172.1.0.1/install/rhels7.2/ppc64le/
c460login01: enabled=1
c460login01: gpgcheck=0
```

If we perform additional copycd's, then the yum.repos.d in these diskful installs now point to the wrong place...

**Comment by immarvin** [comment]
need some time to look into this problem

**Comment by immarvin** [comment]
hi @penguhyang , can you take a look at this issue? thanks

**Comment by whowutwut** [comment]
@gurevichmark  is already investigating and working on a fix for this issue.  Sorry, we should have assigned it earlier so there is no confusion.

**Comment by immarvin** [comment]
@gurevichmark created a PR https://github.com/xcat2/xcat-core/pull/2009, waiting for review

**Comment by immarvin** [comment]
another PR https://github.com/xcat2/xcat-core/pull/2050

**Comment by immarvin** [comment]
hi @gurevichmark , I reopened this issue and set it to "pending" waiting for verification result from the creator

**Comment by immarvin** [comment]
verified by @gurevichmark and me with Redhat7.3 GA, I will close this ticket first, if @ralphbellofatto find this issue with the latest build, please reopen it

**Comment by whowutwut** [comment]
@immarvin  Pull request#1852 broke `copycds -p` ... 

```
    148                 print "VKHU_DEBUG path=$path\n";
    149                 $path=Cwd::realpath($path); <====== problem line
    150                 print "VKHU_DEBUG path=$path\n";
    151                 unless(substr($path,0,length("/install")) eq "/install"){
    152                     $callback->({ warning => "copycds: the specified path \"$path\" is not a subdirectory under /install. Make sure this path is configured for httpd/apache, otherwise, the provisioning w        ith this iso will fail!" });
    153                 }
```

Running the command: `copycds -p /install/RHEL-7.3-20161019.0-Server/ppc64le /iso/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso`  destroys the path... 

```
VKHU_DEBUG path=/install/RHEL-7.3-20161019.0-Server/ppc64le
Use of uninitialized value $path in concatenation (.) or string at /opt/xcat/lib/perl/xCAT_plugin/copycds.pm line 150.
VKHU_DEBUG path=
```

If I run the command: 
```
copycds -p /install/RHEL-7.3-20161019.0-Server -a ppc64le /iso/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
```

it puts the ISO image in `/install/RHEL-7.3-20161019.0-Server/` instead of `/install/RHEL-7.3-20161019.0-Server/ppc64le`

**Comment by immarvin** [comment]
duplicate with issue #2630
