### ISSUE TITLE
bmcdiscover has problems with mtm discovery.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1853]
We attempted to use bmcdiscover with MTMS based discovery.  It fails to discover when doing this.

the xcat/cluster.log produces the following message:
```
Sep 13 17:34:06 c460mgt01 xcat[5776]: xcat.discovery.mtms: (70:e2:84:14:0d:e6) Error: More than one node were found
```

the directions here are a bit sparse:
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/index.html

so we combined the directions from the switch based discover process with this to do:

```
nodeadd newnode groups=all

chdef newnode mtm=8335-GTB serial=101A4EA
chdef newnode chain="runcmd=bmcsetup",standby

bmcdiscover -s nmap --range 172.2.254.* -t -z -w
node-8335-gtb-100a4ea:
        objtype=node
        groups=all
        bmc=172.1.254.100
        cons=ipmi
        mgt=ipmi
        mtm=8335-GTB
        serial=100A4EA
        nodetype=mp
        hwtype=bmc
```

rpower node-8335-gtb-101a4ea

When we power on this node, we get the following in the /var/log/xcat/cluster.log
```
	Sep 13 17:34:06 c460mgt01 xcat[5776]: xcat.discovery.mtms: (70:e2:84:14:0d:e6) Error: More than one node were found
```
To make it work we had to do

```
chdef node-8335-gtb-100a4ea mtm=
```

**Comment by zet809** [comment]
@ralphbellofatto Can you show me the result of "tabdump vpd | grep -i 100a4ea" before "chdef node-8335-gtb-100a4ea mtm="?
From xcat point of view, even the pre-defined node newnode and node-8335-gtb-100a4ea have same mtm and serial, they have different nodetype and hwtype attributes, can you show me the node definition for the 2 nodes?

**Comment by ralphbellofatto** [comment]
node-8335-gtb-100a4ea:
        objtype=node
        groups=all
        bmc=172.2.1.1
        cons=ipmi
        mgt=ipmi
        mtm=8335-GTB
        serial=100A4EA

**Comment by ralphbellofatto** [comment]
this is a typical definition of a node we are going to try to configure with mtm
Object name: c460c090
    bmc=172.2.6.18
    bmcport=0
    chain=runcmd=bmcsetup
    cons=ipmi
    consoleondemand=1
    currstate=offline
    groups=all,compute,c460f06
    hostnames=c460f06u39
    installnic=mac
    ip=172.1.6.18
    mgt=ipmi
    mtm=8335-GTBx
    netboot=petitboot
    postbootscripts=syncfiles,confignics,setroute,setupntp
    postscripts=custom/check-hostname,syslog,remoteshell,syncfiles,ospkgs,otherpkgs
    primarynic=mac
    rack=c460f06
    serial=100A9BA
    switch=c460tors06
    switchport=0
    unit=u39
    updatestatus=failed
    updatestatustime=09-13-2016 10:31:17

**Comment by cxhong** [comment]
Hi, Ralph:  
I couldn't recreate this issue in our test system with Garrison node. 

looking at your bmc node stanza again.  I think your bmc node stanza missed nodetype and hwtype.
the nodetype and hwtype are created when run "bmcdiscover --range ip_range -t -z -w",  the flag "-t" is very improtant here. 

after -t option ran, the mp table will create a entry with bmc node,
`````
# tabdump mp
#node,mpa,id,nodetype,comments,disable
"node-8335-gtb-2109d0a",,,"bmc",,
``````

the findme() in the typemtms.pm will filter out the mtms for bmc node by checking mp table.
without "-t" option,  nothing will be in the mp table, and will found two nodes with same mtms on vpd table.

**Comment by zet809** [comment]
@ralphbellofatto Hi，ralph, will you pls close this defect if bmcdiscovery -t fix this defect for you? Thx a lot.

**Comment by whowutwut** [comment]
@zet809 Is there a scenario where `-t` option is NOT needed? If it's always needed, maybe we should use this issue to change the code to automatically apply the `-t` option so it's less error prone.

**Comment by ralphbellofatto** [comment]
that would be a good thing, because it is an easy thing to miss, and combined with the fact the message does not tell you what is duplicated, it is hard track down.

**Comment by zet809** [comment]
@whowutwut  and @ralphbellofatto I totally agree with you that the -t option shall be used by default for bmcdiscover. We have suffered a lot for not having nodetype and hwtype attribute set for the temporary node. Will fix it in the next release.

**Comment by whowutwut** [comment]
Using the 10/14 build of xCAT (2.12.4) the -t option is no longer needed 
```
[root@fs4 subcmds]# bmcdiscover --range 50.23.18.1 -z | egrep "nodetype|hwtype"
	nodetype=mp
	hwtype=bmc
```

Using -t will cause a warning message to be printed to stderr, still allowing bmcdiscover for re-direction of the stanzas to a file 

```
[root@fs4 subcmds]# bmcdiscover --range 50.23.18.1 -t -z  1>> /dev/null
Warning: The -t option is deprecated and will be ignored
```

However, in our MTMS documentation , we recommend using bmcdiscover **without the -t** option as an easy way to create a starting point for the predefined stanza.   So now, with the output as is, we cannot redirect to a file and there is more work to remove those lines.  

@cxhong  will create another pull request to NOT display the nodetype,hwtype, but write it into the DB when the -w option is used.

**Comment by whowutwut** [comment]
With @cxhong pull request, i think this is OK now to close.
