### ISSUE TITLE
mtm based discovery produces an unhelpful message

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1854]
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/index.html

If there are more than one node with the same mtm information available we get a message which is a bit unhelpful.

```
	Sep 13 17:34:06 c460mgt01 xcat[5776]: xcat.discovery.mtms: (70:e2:84:14:0d:e6) Error: More than one node were found
```
If this error message was changed to print out the $mtms information, then it would be a great help in finding the error.

To duplicate this problem, one needs to create two records

the directions here are a bit sparse:
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/index.html

so we combined the directions from the switch based discover process with this to do:

```
nodeadd newnode1 groups=all
nodeadd newnode2 groups=all

chdef newnode1 mtm=8335-GTB serial=101A4EA
chdef newnode1 chain="runcmd=bmcsetup",standby

chdef newnode2 mtm=8335-GTB serial=101A4EA
chdef newnode2 chain="runcmd=bmcsetup",standby

bmcdiscover -s nmap --range 172.2.254.* -t -z -w
node-8335-gtb-100a4ea:
        objtype=node
        groups=all
        bmc=172.1.254.100
        cons=ipmi
        mgt=ipmi
        mtm=8335-GTB
        serial=101A4EA
        nodetype=mp
        hwtype=bmc
```

rpower node-8335-gtb-101a4ea

When we power on this node, we get the following in the /var/log/xcat/cluster.log
```
	Sep 13 17:34:06 c460mgt01 xcat[5776]: xcat.discovery.mtms: (70:e2:84:14:0d:e6) Error: More than one node were found
```

If we change the source code in:
/opt/xcat/lib/perl/xCAT_plugin/typemtms.pm

from 
```
        xCAT::MsgUtils->message("S", "xcat.discovery.mtms: ($request->{_xcat_clientmac}->[0]) Error: More than one node were found");
```
to this:
```
        xCAT::MsgUtils->message("S", "xcat.discovery.mtms: ($request->{_xcat_clientmac}->[0]) Error: More than one node were found for $mtms");
```

Then we get useful information that quickly leads us to correcting the problem.

**Comment by zet809** [comment]
@xuweibj Hi, xu wei, will you pls help to add this information within the log message? Thx!

**Comment by whowutwut** [comment]
@gurevichmark Can you test this by running MTMS discovery in our environment to validate the message is better, then we can close this issue out.

**Comment by ralphbellofatto** [comment]
what version do i download and update our xcat to to test this with...?

**Comment by whowutwut** [comment]
If you have xCAT 2.12.3, you should have these log message changes

**Comment by whowutwut** [comment]
Closing out this issue.  The messages that appear now look like the following: 

```
Oct 26 14:50:41 fs4 xcat[14072]: xcat.discovery.aaadiscovery: (70:e2:84:14:0f:0a) Got a discovery request, attempting to discover the node...
Oct 26 14:50:41 fs4 xcat[14072]: xcat.discovery.blade: (70:e2:84:14:0f:0a) Warning: Could not find any nodes using blade-based discovery
Oct 26 14:50:41 fs4 xcat[14072]: xcat.discovery.switch: (70:e2:84:14:0f:0a) Warning: Could not find any nodes using switch-based discovery
Oct 26 14:50:41 fs4 xcat[14072]: xcat.discovery.mtms: (70:e2:84:14:0f:0a) Warning: Could not find any node for 8335-GTB*2109E4A using mtms-based discovery
Oct 26 14:50:41 fs4 xcat[14072]: xcat.discovery.zzzdiscovery: (70:e2:84:14:0f:0a) Failed to discover the node.
```
