### ISSUE TITLE
Diskless boot failed for rhel7.3 because selinux disabled

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1856]
Maybe the ticket code does not work. https://github.com/xcat2/xcat-core/issues/1666

[root@pcmautorhelmn ~]# xcatconfig -v
Version 2.12.2 (git commit aa5f6af055544dc92f547ee9a96b90b286c4477b, built Fri Sep  9 03:12:54 EDT 2016)

[root@pcmautorhelmn ~]# cat /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall | grep SELINUX
    sed -i 's/SELINUX=enforcing|permissive/SELINUX=disabled/' $installroot/etc/selinux/config

[root@pcmautorhelmn etc]# cat /install/osimages/rhels7.3-x86_64-stateless-compute/rootimage/rootimg/etc/selinux/config  | grep SELINUX
# SELINUX= can take one of these three values:
SELINUX=enforcing
# SELINUXTYPE= can take one of three two values:
SELINUXTYPE=targeted

**Comment by immarvin** [comment]
hi, would you please provide the diskless osimage definition?

**Comment by fenggaobj** [comment]
[root@pcmautorhelmn ~]# lsdef -t osimage  -o rhels7.3-x86_64-stateless-compute
Object name: rhels7.3-x86_64-stateless-compute
    addkcmdline=net.ifnames=0
    cfmdir=/install/osimages/rhels7.3-x86_64-stateless-compute/cfmdir
    description=The rhels 7.3 x86_64 stateless compute image profile
    imagetype=linux
    isdeletable=0
    kitcomponents=component-pcm-monitoring-agent-4.3-1.rhels-7-x86_64,component-pcm-base-node-4.3-1.rhels-7-x86_64
    netdrivers=tg3,bnx2,bnx2x,e1000,e1000e,igb,virtio_net,be2net
    osarch=x86_64
    osdistroname=rhels7.3-x86_64
    osname=linux
    osvers=rhels7.3
    otherpkgdir=/install/osimages/rhels7.3-x86_64-stateless-compute/otherpkg
    otherpkglist=/install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist,/install/osimages/rhels7.3-x86_64-stateless-compute/custompkgs.pkglist,/install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist
    permission=755
    pkgdir=/install/rhels7.3/x86_64
    pkglist=/install/osimages/rhels7.3-x86_64-stateless-compute/pkglist.cfm
    postbootscripts=KIT_PCM_setupego,KIT_PCM_setupelk
    postinstall=/install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_COMPONENTS.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/osimages/rhels7.3-x86_64-stateless-compute/rootimage
    serverrole=compute
    synclists=/install/osimages/rhels7.3-x86_64-stateless-compute/synclist.cfm

**Comment by immarvin** [comment]
what is ``/install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_COMPONENTS.postinstall``? does it include the ``/opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall ``?

**Comment by chudegao** [comment]
/install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_COMPONENTS.postinstall is a script install EGO in diskless image. Not include /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall.

**Comment by chudegao** [comment]
[root@pcmautorhelmn pcmrest]# cat /install/osimages/rhels7.3-x86_64-stateless-compute/kits/KIT_COMPONENTS.postinstall
#!/bin/sh

installroot=/install/osimages/rhels7.3-x86_64-stateless-compute/rootimage/rootimg otherpkgdir=/install/osimages/rhels7.3-x86_64-stateless-compute/otherpkg ENV_EGO_TOP=${ENV_EGO_TOP} /install/postscripts/KIT_PCM_genimage_egocore_post.sh
[root@pcmautorhelmn pcmrest]#

**Comment by immarvin** [comment]
ok, please install the /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall in your postinstall script and have a try

**Comment by immarvin** [comment]
maybe we need to mention this in xCAT Documentation

**Comment by whowutwut** [comment]
@immarvin  Which section should this be added to?

**Comment by immarvin** [comment]
hi @whowutwut , we should mention this in the documentation of "postinstallscript" section planed by this ticket  https://github.com/xcat2/xcat-core/issues/1932

**Comment by immarvin** [comment]
added the documentation TODO in ticket https://github.com/xcat2/xcat-core/issues/1932, close this
