### ISSUE TITLE
netboot postscripts have no knowledge about the osimage it is installing.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1857]
We have a need to bake somethings in the image created in the directory that come from the site table as well as the osimage definition itself.

for example we need to know the address of the management node as well as the ospkgdir and otherpkgdir specification so we can do some additional setup in the postinstall scripts to bake somethings into the image.

Currently there is nothing on the command line given to the postinstall scripts or its environment that tells us what is available.

Here is the current information we have available:

Paratemers to this script:
```
installroot=/install/netboot/rhels7.2/ppc64le/test-postscript-nb/rootimg
osver=rhels7.2
arch=ppc64le
profile=compute
workdir=
```

environment:
```
MANPATH=/opt/xcat/share/man:
DB2INSTANCE=xcatdb
PERL_BADLANG=0
LC_ALL=C
XCATROOT=/opt/xcat
PATH=/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/sbin:/usr/sbin:/bin:/usr/bin
PWD=/opt/xcat/share/xcat/netboot/rh
LANG=en_US.UTF-8
EXTSHM=ON
SHLVL=3
_=/bin/env
```

To duplicate this issue we did first copied the osimage rhels7.2-ppc64le-netboot-compute to  test-postscript-nb

And then did the following:
```
copy  postinstall script and display environment variables and parameters...


chdef -t osimage test-postscript-nb postinstall=/install/postscripts/custom/test-postscript-nb/compute.postinstall


[root@c460mgt01 tools]# cat >/install/postscripts/custom/test-postscript-nb <<EOF
#!/bin/sh
installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

echo "=================================================="
echo installroot=$installroot
echo osver=$osver
echo arch=$arch
echo profile=$profile
echo workdir=$workdir
echo "environment:"
echo "--------------------------------------------------"
env

echo "=================================================="
EOF

chmod  +x /install/postscripts/custom/test-postscript-nb

genimage  test-postscript-nb 2>&1 | tee /tmp/ genimage. test-postscript-nb.log
```

**Comment by immarvin** [comment]
hi @ralphbellofatto , we will try to pass all the specified attributes of the osimage definition via command line arguments or environment variables. 

Generally, it is not a good idea for us to take any other attribute except the osimage attributes, such as the attributes of the cluster or the provisioning nodes into the osimage itself, if you need the attributes of this kind, you can run linux commands or xcat commands to get them.

**Comment by ralphbellofatto** [comment]
some of the information we want to get at here comes from the osimage itself, and it would appear that we are lacking the information at the postinstall step to know what image we are dealing with.

**Comment by ralphbellofatto** [comment]
The specific roadblock we have right now is that we need to know the ospkgdir value, but there will probably be other values that we may need to know in a postinstall script as well..

We can't get at them via executing xcat commands directly this point because no information is available as to what the current ospackage is..

**Comment by daniceexi** [comment]
Is it an easy solution that support key word like ``#osimage.ospkgdir#`` in postinstall script, xCAT replace the key word to the real value from the osimage definition before executing the postinstall?

**Comment by ralphbellofatto** [comment]
are you proposing adding this as an environment variable available at the postinstall step?

**Comment by daniceexi** [comment]
@ralphbellofatto Yes.

@immarvin Please estimate which one is easier to implement?

**Comment by immarvin** [comment]
hi @ralphbellofatto @daniceexi ,  I prefer the option to pass the required osimage attribute via environment variables, I added the following attributes in the environment variables of the postinstall script

````
        $ENV{img_arch}=$arch if($arch);
        $ENV{img_osver}=$osver if($osver);
        $ENV{img_profile}=$profile if($profile);
        $ENV{img_prinic}=$prinic if($prinic);
        $ENV{img_pkglist}=$pkglist if($pkglist);
        $ENV{img_pkgdir}=$srcdir if($srcdir);
        $ENV{img_otherpkglist}=$otherpkglist if($otherpkglist);
        $ENV{img_otherpkgdir}=$otherpkgdir if($otherpkgdir);
        $ENV{img_rootimgdir}=$rootimg_dir if($rootimg_dir);
````

is it enough?

**Comment by immarvin** [comment]
if you agree this option, I will create a PR soon

**Comment by ralphbellofatto** [comment]
Can you add the osimage name?

**Comment by ralphbellofatto** [comment]
the rest of the list looks good.

**Comment by immarvin** [comment]
hi @ralphbellofatto , is osimage name mandatory? If you will not run xcat command in the postinstall script, the osimage name is just a string and make any sense. If you really need it, I need to change the current interface of "rh/genimage"

**Comment by ralphbellofatto** [comment]
well, one of our CORAL requirements we have is that the compute node itself can report what image name it is actually booted with.

So, without the  osimage name, i would have to try to figure out what image it is.

**Comment by cxhong** [comment]
Actually, We implemented this requirement already in the packimage process.  the image name will be stored in the /opt/xcat/xcatinfo on the compute node.

**Comment by immarvin** [comment]
hi @ralphbellofatto , just as @cxhong mentioned, we have the following info in "/opt/xcat/xcatinfo" file  in the rootimg.gz on MN and the root file system of running diskless node:
````
#cat /opt/xcat/xcatinfo
IMAGENAME='rhels7.2-ppc64le-netboot-compute'
IMAGEUUID='eb03150d-115e-4666-b173-73b2133173f2'
TIMESTAMP='Fri Sep  9 02:40:17 EDT 2016'
````

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1877

**Comment by ralphbellofatto** [comment]
ok, that's perfect.  somehow I missed that file earlier..




Ralph Bellofatto
IBM TJ Watson Research
1-914-945-3321
ralphbel@us.ibm.com

**Comment by ralphbellofatto** [comment]
packimage, that is too late...

**Comment by immarvin** [comment]
added in https://github.com/xcat2/xcat-core/pull/1885
