### ISSUE TITLE
[FVT]:investigate the output of rinv on Garrision 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1858]
Test platform(including OS and Hardware):  RHELS7.2 , CN:Garrision 
Test xCAT version: Version 2.12.3 (git commit 2a6d45602969f7f0120a168c7c3ae4adb6894377, built Wed Sep  7 06:16:01 EDT 2016)
How to reproduce: 
Here i gives out the message. There is some message which is not meaningful. Please investigate the message. 
[root@fs1 ~]# rinv frame45cn02 all
frame45cn02: BMC Firmware: 2.13
frame45cn02: BMCCARD Board Part Number: 00E4575
frame45cn02: UUID/GUID: 1484E270-A409-0390-0010-DEBFECF6E76B
frame45cn02: Product ID: 43707
frame45cn02: Manufacturer ID: 0
frame45cn02: Device ID: 32
frame45cn02: BMCCARD Board Serial Number: Y130UF61P01S
frame45cn02: BMCCARD Board Manufacturer: IBM
frame45cn02: BMCCARD Board : BMC PLANAR
frame45cn02: CPU 1 Board Part Number: 00YV560
frame45cn02: CPU 1 Board Serial Number: YA3932687050
frame45cn02: CPU 1 Board Manufacturer: IBM
frame45cn02: CPU 1 Board : PROCESSOR MODULE
frame45cn02: CPU 1 Board Additional Info: ECID:019C009801208718020D000000994CB2
frame45cn02: CPU 1 Board Additional Info: EC:10
frame45cn02: CPU 2 Board Part Number: 00YV560
frame45cn02: CPU 2 Board Serial Number: YA3932754284
frame45cn02: CPU 2 Board Manufacturer: IBM
frame45cn02: CPU 2 Board : PROCESSOR MODULE
frame45cn02: CPU 2 Board Additional Info: ECID:019A0095C20047180605000000E74D36
frame45cn02: CPU 2 Board Additional Info: EC:10
frame45cn02: DIMM1 Product Serial Number: 10 a7 1c b5 (    )
frame45cn02: DIMM1 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM1 Product Version: 32 (2)
frame45cn02: DIMM1 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM10 Product Serial Number: 10 a7 1d 07 (    )
frame45cn02: DIMM10 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM10 Product Version: 32 (2)
frame45cn02: DIMM10 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM11 Product Serial Number: 10 a7 1c 7a (   z)
frame45cn02: DIMM11 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM11 Product Version: 32 (2)
frame45cn02: DIMM11 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM12 Product Serial Number: 10 a7 1c 90 (    )
frame45cn02: DIMM12 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM12 Product Version: 32 (2)
frame45cn02: DIMM12 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM13 Product Serial Number: 10 a7 1c 7c (    )
frame45cn02: DIMM13 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM13 Product Version: 32 (2)
frame45cn02: DIMM13 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM14 Product Serial Number: 10 a7 1c ce (    )
frame45cn02: DIMM14 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM14 Product Version: 32 (2)
frame45cn02: DIMM14 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM15 Product Serial Number: 10 a7 1c e6 (    )
frame45cn02: DIMM15 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM15 Product Version: 32 (2)
frame45cn02: DIMM15 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM16 Product Serial Number: 10 a7 1c dc (    )
frame45cn02: DIMM16 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM16 Product Version: 32 (2)
frame45cn02: DIMM16 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM17 Product Serial Number: 10 a7 1c cb (    )
frame45cn02: DIMM17 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM17 Product Version: 32 (2)
frame45cn02: DIMM17 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM18 Product Serial Number: 10 a7 1c db (    )
frame45cn02: DIMM18 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM18 Product Version: 32 (2)
frame45cn02: DIMM18 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM19 Product Serial Number: 10 a7 1c 82 (    )
frame45cn02: DIMM19 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM19 Product Version: 32 (2)
frame45cn02: DIMM19 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM2 Product Serial Number: 10 a7 1c 92 (    )
frame45cn02: DIMM2 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM2 Product Version: 32 (2)
frame45cn02: DIMM2 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM20 Product Serial Number: 10 a7 1c b8 (    )
frame45cn02: DIMM20 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM20 Product Version: 32 (2)
frame45cn02: DIMM20 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM21 Product Serial Number: 10 a7 1c ca (    )
frame45cn02: DIMM21 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM21 Product Version: 32 (2)
frame45cn02: DIMM21 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM22 Product Serial Number: 10 a7 1c 7e (    )
frame45cn02: DIMM22 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM22 Product Version: 32 (2)
frame45cn02: DIMM22 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM23 Product Serial Number: 10 a7 1c d3 (    )
frame45cn02: DIMM23 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM23 Product Version: 32 (2)
frame45cn02: DIMM23 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM24 Product Serial Number: 10 a7 1c 80 (    )
frame45cn02: DIMM24 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM24 Product Version: 32 (2)
frame45cn02: DIMM24 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM25 Product Serial Number: 10 a7 1c e5 (    )
frame45cn02: DIMM25 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM25 Product Version: 32 (2)
frame45cn02: DIMM25 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM26 Product Serial Number: 10 a7 1c 7f (    )
frame45cn02: DIMM26 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM26 Product Version: 32 (2)
frame45cn02: DIMM26 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM27 Product Serial Number: 10 a7 1c 9c (    )
frame45cn02: DIMM27 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM27 Product Version: 32 (2)
frame45cn02: DIMM27 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM28 Product Serial Number: 10 a7 1c 41 (   A)
frame45cn02: DIMM28 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM28 Product Version: 32 (2)
frame45cn02: DIMM28 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM29 Product Serial Number: 10 a7 1c e7 (    )
frame45cn02: DIMM29 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM29 Product Version: 32 (2)
frame45cn02: DIMM29 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM3 Product Serial Number: 10 a7 1c b7 (    )
frame45cn02: DIMM3 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM3 Product Version: 32 (2)
frame45cn02: DIMM3 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM30 Product Serial Number: 10 a7 1c 38 (   8)
frame45cn02: DIMM30 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM30 Product Version: 32 (2)
frame45cn02: DIMM30 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM31 Product Serial Number: 10 a7 1c 51 (   Q)
frame45cn02: DIMM31 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM31 Product Version: 32 (2)
frame45cn02: DIMM31 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM32 Product Serial Number: 10 a7 1c ac (    )
frame45cn02: DIMM32 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM32 Product Version: 32 (2)
frame45cn02: DIMM32 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM4 Product Serial Number: 10 a7 1c a2 (    )
frame45cn02: DIMM4 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM4 Product Version: 32 (2)
frame45cn02: DIMM4 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM5 Product Serial Number: 10 a7 1c 8f (    )
frame45cn02: DIMM5 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM5 Product Version: 32 (2)
frame45cn02: DIMM5 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM6 Product Serial Number: 10 a7 1c 74 (   t)
frame45cn02: DIMM6 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM6 Product Version: 32 (2)
frame45cn02: DIMM6 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM7 Product Serial Number: 10 a7 1c cc (    )
frame45cn02: DIMM7 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM7 Product Version: 32 (2)
frame45cn02: DIMM7 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM8 Product Serial Number: 10 a7 1c af (    )
frame45cn02: DIMM8 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM8 Product Version: 32 (2)
frame45cn02: DIMM8 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: DIMM9 Product Serial Number: 10 a7 1c ab (    )
frame45cn02: DIMM9 Product Manufacturer: 2c 80 (  )
frame45cn02: DIMM9 Product Version: 32 (2)
frame45cn02: DIMM9 Product Model: 9ASF51272PZ-2G3A2
frame45cn02: FAN1: clear
frame45cn02: FAN2: clear
frame45cn02: FAN3: clear
frame45cn02: FAN4: clear
frame45cn02: GPU1 Board Part Number: 15F9-895-A1
frame45cn02: GPU1 Board Manufacturer: NVIDIA
frame45cn02: GPU1 Board : GP100 SXM2
frame45cn02: GPU2 Board Part Number: 15F9-895-A1
frame45cn02: GPU2 Board Manufacturer: NVIDIA
frame45cn02: GPU2 Board : GP100 SXM2
frame45cn02: GPU3 Board Part Number: 15F9-895-A1
frame45cn02: GPU3 Board Manufacturer: NVIDIA
frame45cn02: GPU3 Board : GP100 SXM2
frame45cn02: GPU4 Board Part Number: 15F9-895-A1
frame45cn02: GPU4 Board Manufacturer: NVIDIA
frame45cn02: GPU4 Board : GP100 SXM2
frame45cn02: MEMBUF1 Board Part Number: 00E4554
frame45cn02: MEMBUF1 Board Serial Number: YL30UF5CG0DS
frame45cn02: MEMBUF1 Board Manufacturer: IBM
frame45cn02: MEMBUF1 Board : DDR4 MEM RISER
frame45cn02: MEMBUF1 Board Additional Info: ECID:019A0082401817182512000000D605C1
frame45cn02: MEMBUF2 Board Part Number: 00E4554
frame45cn02: MEMBUF2 Board Serial Number: YL30UF5CG097
frame45cn02: MEMBUF2 Board Manufacturer: IBM
frame45cn02: MEMBUF2 Board : DDR4 MEM RISER
frame45cn02: MEMBUF2 Board Additional Info: ECID:019A00824210771802130000004E04D1
frame45cn02: MEMBUF3 Board Part Number: 00E4554
frame45cn02: MEMBUF3 Board Serial Number: YL30UF5CG0FC
frame45cn02: MEMBUF3 Board Manufacturer: IBM
frame45cn02: MEMBUF3 Board : DDR4 MEM RISER
frame45cn02: MEMBUF3 Board Additional Info: ECID:019A00824210771802180000001C0501
frame45cn02: MEMBUF4 Board Part Number: 00E4554
frame45cn02: MEMBUF4 Board Serial Number: YL30UF5CG05C
frame45cn02: MEMBUF4 Board Manufacturer: IBM
frame45cn02: MEMBUF4 Board : DDR4 MEM RISER
frame45cn02: MEMBUF4 Board Additional Info: ECID:019A0082421077180812000000130441
frame45cn02: MEMBUF5 Board Part Number: 00E4554
frame45cn02: MEMBUF5 Board Serial Number: YL30UF5CG0AL
frame45cn02: MEMBUF5 Board Manufacturer: IBM
frame45cn02: MEMBUF5 Board : DDR4 MEM RISER
frame45cn02: MEMBUF5 Board Additional Info: ECID:019A0082421077181713000000EA0491
frame45cn02: MEMBUF6 Board Part Number: 00E4554
frame45cn02: MEMBUF6 Board Serial Number: YL30UF5CG0AW
frame45cn02: MEMBUF6 Board Manufacturer: IBM
frame45cn02: MEMBUF6 Board : DDR4 MEM RISER
frame45cn02: MEMBUF6 Board Additional Info: ECID:019A0082421077181D13000000E00411
frame45cn02: MEMBUF7 Board Part Number: 00E4554
frame45cn02: MEMBUF7 Board Serial Number: YL30UF5CG07R
frame45cn02: MEMBUF7 Board Manufacturer: IBM
frame45cn02: MEMBUF7 Board : DDR4 MEM RISER
frame45cn02: MEMBUF7 Board Additional Info: ECID:019A0082421077181918000000E604B1
frame45cn02: MEMBUF8 Board Part Number: 00E4554
frame45cn02: MEMBUF8 Board Serial Number: YL30UF5CG08W
frame45cn02: MEMBUF8 Board Manufacturer: IBM
frame45cn02: MEMBUF8 Board : DDR4 MEM RISER
frame45cn02: MEMBUF8 Board Additional Info: ECID:019A008182086718081D000000330421
frame45cn02: NODE 1 Board Part Number: 00E4556
frame45cn02: NODE 1 Board Serial Number: Y230UF61S01T
frame45cn02: NODE 1 Board Manufacturer: IBM
frame45cn02: NODE 1 Board : SYSTEM PLANAR
frame45cn02: NODE 1 Chassis Part Number: 8335-GTB
frame45cn02: NODE 1 Chassis Serial Number: 100499A
frame45cn02: PSU1 Product Serial Number: 5BP024
frame45cn02: PSU1 Product Manufacturer: EMER
frame45cn02: PSU1 Product Version: 0.12
frame45cn02: PSU1 Product Model: 01AF314
frame45cn02: PSU2 Product Serial Number: 5BP097
frame45cn02: PSU2 Product Manufacturer: EMER
frame45cn02: PSU2 Product Version: 0.12
frame45cn02: PSU2 Product Model: 01AF314
frame45cn02: System Firmware Product Version: IBM-garrison-ibm-OP8_v1.9_2.16
frame45cn02: System Firmware Product Additional Info: op-build-4aea2aa
frame45cn02: System Firmware Product Additional Info: buildroot-81b8d98
frame45cn02: System Firmware Product Additional Info: skiboot-68b4d66
frame45cn02: System Firmware Product Additional Info: hostboot-66caa2d-9f08a6f
frame45cn02: System Firmware Product Additional Info: linux-4.4.14-openpower1-d35dfcc
frame45cn02: System Firmware Product Additional Info: petitboot-v1.2.0-5435e4d
frame45cn02: System Firmware Product Additional Info: garrison-xml-b453a81
frame45cn02: System Firmware Product Additional Info: occ-69fb587
frame45cn02: System Firmware Product Additional Info: hostboot-bin

**Comment by daniceexi** [comment]
We need to refine the format of content for a new issue.

We have a format for new issue but why don't use that any more?

**Comment by zet809** [comment]
Move to next release to investigate.

**Comment by whowutwut** [comment]
@daniceexi  not sure i understand your comment, can you clarify?

**Comment by daniceexi** [comment]
The comment was for TT and FVT to use our discussed format to post a new issue. I do think our FVT should relearn our agreed format for new issue and use it strictly .

**Comment by zet809** [comment]
@tingtli Hi, Ting Ting, for the message "frame45cn02: DIMM8 Product Serial Number: 10 a7 1c af ( )", the string in "( )" is used to show the ascii string of "10 a7 1c af", but none valid character can be resolved in the end. That is reasonable, so I reject this defect.

**Comment by tingtli** [comment]
Why we have something like  10 a7 1c 51 ( Q) ?
why there is no string for 10 a7 1c af ( )
I am confused

**Comment by zet809** [comment]
@tingtli hex 51 means 'Q' in ASCII, but hex af  not mapping to a printable character, as well as '10', 'a7' and '1c'. And unprintable character will be replace with space (' '). So for '10 a7 1c 51', it can be resolved as '   Q ', and '10 a7 1c af', it is resolved as '    '.

**Comment by tingtli** [comment]
ok, i understand. Thanks!
