### ISSUE TITLE
[FVT]2.11 duplicate kit components are added to osimage

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#186]
xCAT 2.11 9/15 build on rhels7.2 pp64le
1)  download xlc-13.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar.bz2 
 2) download other xlf packages which are needed by complete kit
 [root@c910f03c05k08 build_input]# ls /compilers/
 libxlc-13.1.2.0-150526a.ppc64le.rpm
 libxlc-devel.13.1.2-13.1.2.0-150526a.ppc64le.rpm
 libxlf-15.1.2.0-150526a.ppc64le.rpm
 libxlf-devel.15.1.2-15.1.2.0-150526a.ppc64le.rpm
 libxlmass-devel.8.1.2-8.1.2.0-150526.ppc64le.rpm
 libxlsmp-4.1.2.0-150526.ppc64le.rpm
 libxlsmp-devel.4.1.2-4.1.2.0-150526.ppc64le.rpm
 xlc.13.1.2-13.1.2.0-150526a.ppc64le.rpm
 xlc-license.13.1.2-13.1.2.0-150526a.ppc64le.rpm
 xlf.15.1.2-15.1.2.0-150526a.ppc64le.rpm
 xlf-license.15.1.2-15.1.2.0-150526a.ppc64le.rpm
 3) create complete kit using partial kit 
 buildkit addpkgs  xlc-13.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar.bz2  --pkgdir /compilers/
 4) 
 addkit xlc-13.1.2-0-ppc64le.tar.bz2
 5)
 addkitcomp -a -i "rhels7.2-ppc64le-install-compute"   xlc.license-compute,xlc.compiler-compute, xlc.rte-compute
6) check osimage rhels7.2-ppc64le-install-compute
[root@c910f03c05k08 build_input]# lsdef -t osimage -o rhels7.2-ppc64le-install-compute
Object name: rhels7.2-ppc64le-install-compute
    imagetype=linux
    kitcomponents=xlc.license-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.rte-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.rte-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.compiler-compute-13.1.2-0-rhels-7.2-ppc64le,xlf.license-compute-15.1.2-0-rhels-7.2-ppc64le,xlf.rte-compute-15.1.2-0-rhels-7.2-ppc64le,xlf.compiler-compute-15.1.2-0-rhels-7.2-ppc64le,xlf.rte-compute-15.1.2-0-rhels-7.2-ppc64le,xlf.license-compute-15.1.2-0-rhels-7.2-ppc64le
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le
    otherpkglist=/install/osimages/rhels7.2-ppc64le-install-compute/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist,/install/osimages/rhels7.2-ppc64le-install-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist
    pkgdir=/install/rhels7.2/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

**Comment by cxhong** [comment]
I found bug..

the kitpkgdeps has to give version number of xlf.   like xlf.15.1.2,  not xlf

I will rebuild the kit

**Comment by cxhong** [comment]
If I addkitcomp one at a time ,  I didn't see there were duplicate kit components added to osimage.
If add three kit comps in  one command,  the xlc.license-compute will be duplicated

# addkitcomp -a -i "rhels7.2-ppc64le-install-compute" xlc.license-compute,xlc.compiler-compute, xlc.rte-compute
Assigning kit component xlc.compiler-compute-13.1.2-0-rhels-7.2-ppc64le to osimage rhels7.2-ppc64le-install-compute
Assigning kit component xlc.license-compute-13.1.2-0-rhels-7.2-ppc64le to osimage rhels7.2-ppc64le-install-compute
Kit components xlc.compiler-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.license-compute-13.1.2-0-rhels-7.2-ppc64le were added to osimage rhels7.2-ppc64le-install-compute successfully

# lsdef -t osimage rhels7.2-ppc64le-install-compute                                    
    Object name: rhels7.2-ppc64le-install-compute
    imagetype=linux
    kitcomponents=xlc.license-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.rte-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.compiler-compute-13.1.2-0-rhels-7.2-ppc64le,xlc.license-compute-13.1.2-0-rhels-7.2-ppc64le
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le
    otherpkglist=/install/osimages/rhels7.2-ppc64le-install-compute/kits/KIT_DEPLOY_PARAMS.otherpkgs.pkglist,/install/osimages/rhels7.2-ppc64le-install-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist
    pkgdir=/install/rhels7.2/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

the output message from addkitcomp are inconsistent.  I will look into code for addkitcomp

**Comment by cxhong** [comment]
Talked to BaiYuan about this issue.  we agreed we will close this since it is not affect functions,  Users need to control the order of addkitcomp for each kit components and its dependency.  we are recommended to add kit component one at a time.
