### ISSUE TITLE
[FVT]:should we change go-xcat on xcat.org permission to be executable. 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1870]
I found the permission of go-xcat on xcat.org is 644, when user download it, users need to change the permission to execute it. I don't think it is convenient. How about we change it to executable?

**Comment by neo954** [comment]
There is no point to the the file permission on the remote site. When you download a file via wget from the Internet, the file permission is calculated base on the umask in your environment. And there is no way to create new file with execution permission automatically. It is just the nature of Unix/Linux.

Anyway, follow the document [1], document is good.

[1] http://xcat.org/download.html
