### ISSUE TITLE
[FVT] "bmcdiscover -i IP -u USERID -p PASSW0RD --ipsource" failed

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1872]
Test environment: rh7.2 and rh6.8 ppc64
Details:
```
RUN:bmcdiscover -i 10.4.30.254 -u USERID -p PASSW0RD --ipsource

[bmcdiscover -i 10.4.30.254 -u USERID -p PASSW0RD --ipsource] Running Time:0 sec
RETURN rc = 1
OUTPUT:
Error: 
CHECK:rc == 0	[Failed]
```

**Comment by cxhong** [comment]
`````
if (defined($bmc_user) && defined($bmc_pass) && defined($::opt_I)) {
            my $res = get_bmc_ip_source($::opt_I, $bmc_user, $bmc_pass);
            return $res;
        }
``````

Userid and password passed in by ($::opt_U) and ($::opt_P),  but never set to $bmc_user and $bmc_pass for this --ipsource option.

**Comment by tingtli** [comment]
@caomengmeng  I think when we open defect, we need to give the steps which developers could use to reproduce the issue. Not the logs which in our test log. This one is simple, but sometimes, in our test log, there is some scripts, it is not easy to understand.
E.g for this example, we need to use this one:
[root@c910f02c08p05 result]# bmcdiscover -i 10.4.30.254 -u USERID -p PASSW0RD --ipsource
Error:
[root@c910f02c08p05 result]# echo $?
1

**Comment by whowutwut** [comment]
@tingtli  :+1:

**Comment by caomengmeng** [comment]
@tingtli 
1. This issue only this one step. 
2. This is happened in daily run test environment which is reused, so I don't have the test environment to run it again.

It works well, so close it.
