### ISSUE TITLE
[FVT] Failed to find the directory: /.statelite/persistent after statelite installation

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1873]
For rh7.2, rh7.3 ppc64 and x86 platform, failed to find the /.statelite/persistent  folder after the statelite installation.
Please help to resolve this problem

**Comment by daniceexi** [comment]
@penguhyang Could you take a look of this problem?

**Comment by tingtli** [comment]
@penguhyang  I think it is a very important bug. This will cause our persistent feature for statelite provision.

**Comment by penguhyang** [comment]
This bug will fixed on 2.12.4

**Comment by bybai** [comment]
The persistent directory does not mounted from NFS server; In the code, it did that, should investigate why the following mount command does not take effect:
 mount $SNAPSHOTSERVER:/$SNAPSHOTROOT/$ME  $NEWROOT/$RWDIR/persistent -o $MNT_OPTIONS

If this line is failed, there is sleep and retry in booting, but I do not see sleep.

**Comment by tingtli** [comment]
@bybai  There fix does not work on hierarchy statelite. Please take a look at it.

**Comment by bybai** [comment]
hi @tingtli ,
The fix can work well in hierarchy statelite, the autotest case should be modified.

1, [root@c910f03fsp03v02 ~]# lsdef c910f03fsp03v04 -i status,servicenode
Object name: c910f03fsp03v04
    servicenode=c910f03fsp03v03
    status=booted
2, After CN is booted in statelite:
[root@c910f03fsp03v04 ~]# df
Filesystem                                                         1K-blocks    Used Available Use% Mounted on
c910f03fsp03v03:/install/netboot/rhels7.3/ppc64le/compute/rootimg   18327552 7862272  10465280  43% /
tmpfs                                                                2086080   20928   2065152   2% /run
rw                                                                   2086080  238464   1847616  12% /tmp
c910f03fsp03v03:/nodedata/c910f03fsp03v04.pok.stglabs.ibm.com       18327552 7862272  10465280  43% /.statelite/persistent
rw                                                                   2086080      64   2086016   1% /.sllocal/log
c910f03fsp03v03:/nodedata/c910f03fsp03v04.pok.stglabs.ibm.com/test  18327552 7862272  10465280  43% /test
devtmpfs                                                             2033728       0   2033728   0% /dev
tmpfs                                                                2086080       0   2086080   0% /dev/shm
tmpfs                                                                2086080       0   2086080   0% /sys/fs/cgroup
tmpfs                                                                 417216       0    417216   0% /run/user/0

3, test if the directory is persistent or not:
In CN:
[root@c910f03fsp03v04 ~]# cd /test
[root@c910f03fsp03v04 test]# ls
123
[root@c910f03fsp03v04 test]# touch 345
[root@c910f03fsp03v04 test]# ls
123  345

In service node:
[root@c910f03fsp03v03 /]# cd nodedata/
[root@c910f03fsp03v03 nodedata]# ls
c910f03fsp03v04.pok.stglabs.ibm.com
[root@c910f03fsp03v03 nodedata]# cd c910f03fsp03v04.pok.stglabs.ibm.com/
[root@c910f03fsp03v03 c910f03fsp03v04.pok.stglabs.ibm.com]# ls
test
[root@c910f03fsp03v03 c910f03fsp03v04.pok.stglabs.ibm.com]# cd test/
[root@c910f03fsp03v03 test]# ls
123  345

**Comment by bybai** [comment]
Hi @tingtli and @caomengmeng ,
The autotest case should be enhanced 
1, In SN, umount -l /install is better;
2, After /install dir is added into /etc/exports, it is better to restart nfs service;
3, Added a test dir in litefile:
"ALL","/test/","persistent",,
4, after liteimg, rsync /install:
rsync -auv --exclude 'autoinst' /install c910f03fsp03v03:/
5, check the result:
In CN:
touch a file in /test such as 345
In SN:
check if there is /nodedata/c910f03fsp03v04.pok.stglabs.ibm.com/test/345

**Comment by tingtli** [comment]
@bybai  
It seems that  hierarchy ramdisk statelite have issue.  NFS based hierarchy statelite has no issue.

**Comment by whowutwut** [comment]
@caomengmeng  please verify and close out this issue asap.

**Comment by caomengmeng** [comment]
@whowutwut Works well now and close it
