### ISSUE TITLE
[FVT]add statelite cases in sles12/sles12.1 bundle file 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1875]
We remove statelite cases in sles12 and sles12.1 last year since we didn't support that on sles12/sles12.1 and that was low priority. Since there is some customer requirement, we will support that and we need to add back these cases to bundle file.

**Comment by immarvin** [comment]
hi @caomengmeng , please update the status of this ticket

**Comment by caomengmeng** [comment]
Add related case in PR: https://github.com/xcat2/xcat-core/pull/1879
Please close this issue.
