### ISSUE TITLE
[FVT]Failed to run "lsdocker -l" on ubuntu14.04.4 x86

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1887]
Test ENV: ubuntu14.04.4 x86_64
Description: Failed to run "lsdocker -l" after docker installed successfully.

```
RUN:lsdocker -l host15c08

[lsdocker -l host15c08] Running Time:0 sec
RETURN rc = 1
OUTPUT:
host15c08: Error: {"message":"No such container: host15c08"}

CHECK:rc != 0   [Pass]
CHECK:output =~ Error: No such container    [Failed]
```

**Comment by zet809** [comment]
@caomengmeng Pls let me know if the issue is produced.

**Comment by zet809** [comment]
Will fix this issue if it is reproduced.

**Comment by zet809** [comment]
Move to next release to do investigate.

**Comment by junxiawang** [comment]
I will modify the testcase for docker version changed ref:https://github.com/xcat2/xcat-core/issues/2404
