### ISSUE TITLE
Support to customize the directory to build the stateless image

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#1889]
Just want to set the buildroot to a different path instead of the default one, for example, use high speed storage like flash.
Note: only for the build root, image is still stored in original path as high-speed storage may not have enough space for all stateless images.

It also could address the NFS issue:
Refer to this old issue: https://bugzilla.linux.ibm.com/show_bug.cgi?id=124177

Now, it could be workaround via symbol link.

**Comment by immarvin** [comment]
you can change the "rootimgdir" 
````
chdef -t osimage  rhels7.2-ppc64le-netboot-compute rootimgdir=/install/netboot/aa
````

since during diskless installation, the rootimg.gz will be downloaded via http, so please make sure the newly specified rootimgdir is exported  in httpd/apacha config

**Comment by immarvin** [comment]
another option is to bind mount the build directory on high speed storage to "$rootingdir/rootimg"

**Comment by whowutwut** [comment]
No objection to @immarvin suggestions, closing out this.
