### ISSUE TITLE
"Edit on Github" link does not work from ReadTheDocs

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#189]
Seems like the "Edit on GitHub" links from ReadTheDocs is not being created correctly. I don't really know why it's doing this... any help/ideas would be appreciated... 

For example: http://xcat-docs.readthedocs.org/en/latest/
The edit link goes to https://github.com/xcat2/xcat-core/blob/masterdocs/sourceindex.rst which does not exist....

it seems like there needs to be a slash between master and doc and then also between source and index... Like the following: https://github.com/xcat2/xcat-core/blob/master/docs/source/index.rst

**Comment by samveen** [comment]
Yeah, I noticed it's missing 2 path separators: 
```
Correct:   https://github.com/xcat2/xcat-core/blob/master/docs/source/index.rst
Incorrect: https://github.com/xcat2/xcat-core/blob/masterdocs/sourceindex.rst
```
(at `master/docs` and `source/index.rst`)

Some more reading: https://github.com/rtfd/readthedocs.org/issues/1637

**Comment by whowutwut** [comment]
Yea, I tried out the "Edit on GitHub" links today, and it looks to be fixed :+1:   Maybe I was too quick to open this issue.
