### ISSUE TITLE
cryptmethod support on linux

### ISSUE THREAD

**Issue by khm** [xcat2/xcat-core#1890]
Currently, xCAT passwd table does not support any sort of cryptmethod except md5 on linux.  glibc and musl both support sha256 ($5) and sha512 ($6) crypt methods, so there's no good reason to continue defaulting to md5.

Please consider at least introducing support for other cryptmethods, and preferably making the default choice stronger.

**Comment by whowutwut** [comment]
Thanks @khm   I also agree that this is something we should look into.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2168

**Comment by whowutwut** [comment]
@tingtli  If @khm  cannot verify this for the 2.13.0 release, can you verify and close out?

**Comment by khm** [comment]
Sorry; didn't know you were waiting on my feedback.  This looks excellent.  Thanks so much for the quick implementation!
