### ISSUE TITLE
[FVT]process sles12.x for hierarchy database installation in test framework

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1894]
in script xcatjktest, we have sentence to process the installation of mysql database setup for sles. But for sles12.x , the packages are different with sles11. So, we need to process the sles12 and above os.

**Comment by whowutwut** [comment]
@tingtli  please verify and close out this issue if resolved

**Comment by tingtli** [comment]
Fixed  with #PR https://github.ibm.com/xcat2/jenkins/commit/56a410828741eb94fd5452bb54722432f683c734
