### ISSUE TITLE
[FVT]Failed to install xCAT with latest build 

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1898]
Failed to install xCAT on rh/sles/ubuntu on x86/ppc64/ppc64le, for below issue:
```
Package xCAT-buildkit-2.12.3-1.noarch.rpm is not signed
```

**Comment by immarvin** [comment]
where did you get the cat-core tarbal?

on the daily build, there is no package with the name you provided.

http://xcat.org/files/xcat/repos/yum/devel/core-snap/
[   ]	buildinfo	2016-09-26 04:17	101	 
[TXT]	mklocalrepo.sh	2016-09-26 04:17	670	 
[   ]	perl-xCAT-2.12.3-snap201609260615.noarch.rpm	2016-09-26 04:17	606K	 
[DIR]	repodata/	2016-09-26 04:17	-	 
[   ]	xCAT-2.12.3-snap201609260616.ppc64.rpm	2016-09-26 04:17	219K	 
[   ]	xCAT-2.12.3-snap201609260616.ppc64le.rpm	2016-09-26 04:17	219K	 
[   ]	xCAT-2.12.3-snap201609260616.s390x.rpm	2016-09-26 04:17	219K	 
[   ]	xCAT-2.12.3-snap201609260616.x86_64.rpm	2016-09-26 04:17	219K	 
[   ]	xCAT-SoftLayer-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	38K	 
[   ]	xCAT-buildkit-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	67K	 
[   ]	xCAT-client-2.12.3-snap201609260615.noarch.rpm	2016-09-26 04:17	510K	 
[   ]	xCAT-confluent-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	3.7K	 
[   ]	xCAT-core.repo	2016-09-26 04:17	206	 
[   ]	xCAT-genesis-scripts-ppc64-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	57K	 
[   ]	xCAT-genesis-scripts-x86_64-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	57K	 
[   ]	xCAT-probe-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	64K	 
[   ]	xCAT-server-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	1.7M	 
[   ]	xCAT-test-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	114K	 
[   ]	xCAT-vlan-2.12.3-snap201609260616.noarch.rpm	2016-09-26 04:17	38K	 
[   ]	xCATsn-2.12.3-snap201609260616.ppc64.rpm	2016-09-26 04:17	27K	 
[   ]	xCATsn-2.12.3-snap201609260616.ppc64le.rpm	2016-09-26 04:17	27K	 
[   ]	xCATsn-2.12.3-snap201609260616.s390x.rpm	2016-09-26 04:17	27K	 
[   ]	xCATsn-2.12.3-snap201609260616.x86_64.rpm	2016-09-26 04:17	27K

**Comment by caomengmeng** [comment]
@immarvin please check Victor's mail: Update for 2.12.3 Release Status, end of day 9/26/16

```
I just created a pull request to merge master -> 2.12 and did this merge.  FVT PLEASE USE THIS VERSION TODAY 
Linux : http://xcat.org/files/xcat/xcat-core/2.12.x_Linux/core-snap/20160926.2037-core-rpms-snap.tar.bz2 
Debian: http://xcat.org/files/xcat/xcat-core/2.12.x_Ubuntu/core-snap/20160926.2037-core-debs-snap.tar.bz2 
```

**Comment by tingtli** [comment]
This has been fixed.

**Comment by caomengmeng** [comment]
works well, so close it.
