### ISSUE TITLE
[FVT]:2.11 genimage returns cannot open /install/kits/xlc-13.1.2-0-ppc64le/other_files/xlc-13.1.2-0-ppc64le_xlc.env

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#190]
With update paritial kit on github.

1) buildkit addpkgs xlf-15.1.2-0-ppc64le.NEED_PRODUCT_PKGS.tar.bz2 --pkgdir /compilers/ 
2)addkit xlf-15.1.2-0-ppc64le.tar.bz2
3) addkitcomp -a -i "rhels7.2-ppc64le-netboot-compute" xlf.license-compute,xlf.compiler-compute,xlf.rte-compute
4) genimage "rhels7.2-ppc64le-netboot-compute"
...
  ustr.ppc64le 0:1.0.4-16.el7
  util-linux.ppc64le 0:2.23.2-25.el7
  which.ppc64le 0:2.20-7.el7
  xz.ppc64le 0:5.1.2-12alpha.el7
  xz-libs.ppc64le 0:5.1.2-12alpha.el7
  zlib.ppc64le 0:1.2.7-15.el7

Complete!
Unable to open the following pkglist files:
cannot open /install/kits/xlc-13.1.2-0-ppc64le/other_files/xlc-13.1.2-0-ppc64le_xlc.env.

[root@c910f03c05k08 testnewkit]# echo $?
1

**Comment by bybai** [comment]
I checked the new partial kit, it has /install/kits/xlc-13.1.2-0-ppc64le/other_files/xlc-13.1.2-0-ppc64le_xlc.env. genimage can work.

**Comment by tingtli** [comment]
Close this defect since it is because of environment cleanup issue.
