### ISSUE TITLE
[FVT]2.9.2 AIX: xcatd returns Undefined subroutine &main::update_udpcontext_from_sslctl called at /opt/xcat/sbin/xcatd line 716 when restart xcatd

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#191]
xCAT 2.9.2
bash-3.2# rpm -qa |grep -i xcat
openslp-xcat-1.2.1-1
perl-xCAT-2.9.2-snap201508122139
xCAT-client-2.9.2-snap201508122139
xCAT-server-2.9.2-snap201508122140
xCAT-2.9.2-snap201508122141
restart xcatd and could see the error message in /var/log/messages. 

Sep 16 23:04:26 nimmaster local4:info xCAT[16318646]: xcatd: possible BUG encountered by xCAT UDP service: Undefined subroutine &main::update_udpcontext_from_sslctl called at /opt/xcat/sbin/xcatd line 716.
Sep 16 23:04:26 nimmaster local4:info last message repeated 476 times
Sep 16 23:04:26 nimmaster daemon:notice bootpd[5242886]: hardware address not found: 00145E5AE09E
Sep 16 23:04:27 nimmaster local4:info xCAT[16318646]: xcatd: possible BUG encountered by xCAT UDP service: Undefined subroutine &main::update_udpcontext_from_sslctl called at /opt/xcat/sbin/xcatd line 716.

**Comment by daniceexi** [comment]
@tingtli This is a Duplicated one of #155.
Please add comment in #155 that require the fix to get into 2.9 branch.
