### ISSUE TITLE
[fvt]2.12.3 install_lsf need to modify the  lsb.hosts script

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1910]

**Comment by junxiawang** [comment]
LSB_HOSTS_FILE="$LSF_TOP/conf/lsbatch/$LSF_CLUSTER_NAME/configdir/lsb.hosts"
  LSB_HOSTS_FILE_ORIG="$LSF_TOP/conf/lsbatch/$LSF_CLUSTER_NAME/configdir/lsb.hosts.orig"
 mv $LSB_HOSTS_FILE $LSB_HOSTS_FILE_ORIG

 PRIMARY_MASTER_NODE=`echo $LSF_MASTER_LIST |  awk '{print $1}'`
     echo "Begin Host" >> lsb.hosts
   ------------------------> need to point the file's directory

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1911/files

**Comment by shensisi** [comment]
We saw a problem in xcat postscript install_lsf.   We used this postscript to install and configure LSF.  After LSF is up, we saw ERROR in LSF configuration file lsf.hosts.     The section header “Begin Host” was missing in lsf.hosts which caused LSF could not get the correct  MXJ (maximum number of jobs).

**Comment by whowutwut** [comment]
@shensisi  does the fix that @immarvin  references resolve the issue that you saw?
