### ISSUE TITLE
xcatdefaults postscript

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1919]
Is the xcat defaults postscript table information available in an lsdef object that can be queried with chdef.

[root@c460mgt01 ~]# tabdump postscripts | head
# node,postscripts,postbootscripts,comments,disable

"xcatdefaults","syslog,remoteshell,syncfiles,ospkgs,otherpkgs","syncfiles",,

I would like to be able to query these fields without having to write a script that dumps the entire table to just parse off that line.

Is there a function that is the reverse of chtab, or is there some table under which these fields show up?

**Comment by immarvin** [comment]
you mean "lsdef"?

``tabdump -w node==xcatdefaults postscripts`` might be the command you want, please refer to "man tabdump" for  details.

**Comment by ralphbellofatto** [comment]
ok, the selective tabdump can cover it.

It would have been better if this could have been gotten at with lsf, as I already have code to parse and archive the lsf data into source control.

**Comment by whowutwut** [comment]
Before we just close this, can we consider what @ralphbellofatto  is looking for and whether there's a better way than using tabdump?

**Comment by immarvin** [comment]
hi @ralphbellofatto , what's the command usage and output  you expect?

**Comment by ralphbellofatto** [comment]
I would like to this to show up under some lsfdef command as part of a stanza...

Since it is a site wide parameter, possibly showing up in the site table.

So far, we can managed keeping track of the state of the xcat configuraton in source control with lsdef xxx -z for all the fields except this one.

**Comment by immarvin** [comment]
adding "xcatdefaults" into site object is not reasonable according to xCAT object definition spec, maybe a enhancement that make sense for xCAT is to add a option, for example "--field"  for ``tabdump`` to display only the specified field with "--field" in the row with the specified key "-w attr==val", we can consider this in the following releases

**Comment by ralphbellofatto** [comment]
the site table is my preference for this, as it should be possible to capture the state of the xcat configuration from lsdef commands alone.

the tabdump is hard to unravel what field goes with what definition.

**Comment by immarvin** [comment]
please reopen this ticket if need

**Comment by runiq** [comment]
Yeah, I would also like this. Maybe make it a hidden node or somethin?
