### ISSUE TITLE
[DEV]"updatenode"  complains "//xcatpost/mypostscript: line 14: [: missing `]'"

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#1921]
caused by https://github.com/xcat2/xcat-core/pull/1832/files:
 in "run_ps":
``+    if [ -z \"\$2\"]; then``
what's more
``./$@ 2>&1 | tee`` should be ``./$1 2>&1|tee``

**Comment by immarvin** [comment]
this affects the following files:
````
./xCAT/postscripts/xcataixpost
./xCAT/postscripts/xcatdsklspost
./xCAT-server/share/xcat/install/scripts/post.debian
./xCAT-server/share/xcat/install/scripts/post.rhel5.s390x
./xCAT-server/share/xcat/install/scripts/post.rhel6.s390x
./xCAT-server/share/xcat/install/scripts/post.sles10.s390x
./xCAT-server/share/xcat/install/scripts/post.sles11.s390x
./xCAT-server/share/xcat/install/scripts/post.xcat
````

**Comment by immarvin** [comment]
this issue is caused by https://github.com/xcat2/xcat-core/pull/1832

this PR provided a little feature for xCAT-probe and breaks the framework on os provision and updatenode, it is not safe to include this PR+(it's fix) in xCAT code at this time. Revert this PR.

the new PR is https://github.com/xcat2/xcat-core/pull/1924/files, will be merged after release

**Comment by zet809** [comment]
@penguhyang The pull request have been merged, @immarvin is this defect fixed?
