### ISSUE TITLE
[FVT] Failled to install CN after xCAT is installed successfully by go-xcat on rh7.2 ppc64

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1925]
Failled to install CN after xCAT is installed successfully by go-xcat on rh7.2 ppc64.
CN is failed to download the /install/autoinst/CN from MN, and status is Powring-on.

The reason is the /install folder permission: 
```
drwx------    8 root root        103 Sep 29 03:16 install
```
Please help to resolve it.

**Comment by whowutwut** [comment]
@pdlun92 let's see if we can verify/resolve this this week since @neo954 is on holiday.

**Comment by neo954** [comment]
This issue was fixed in pull request #1926.

**Comment by zet809** [comment]
@caomengmeng Will you pls verify this defect?

**Comment by caomengmeng** [comment]
work well now
