### ISSUE TITLE
Create a rpm to hold specific configuration with CSM, xCAT-csm

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1935]
Create a new rpm to ship specific templates and postscripts related to csm/coral/. 

name: `xCAT-csm`

This allows us with a way to ship various files to support the differnt types of nodes that will be managed and provisioned using xCAT.

**Comment by mattaezell** [comment]
I would recommend calling the package xCAT-CSM (although I know CSM used to mean something to IBM).  CSM is the management software being developed for the 2 IBM/CORAL systems.

**Comment by whowutwut** [comment]
@mattaezell Thanks! i think that's a good suggestion since it would match the software name.  Will update the issue.

**Comment by whowutwut** [comment]
RPM is currently being built in the devel stream
