### ISSUE TITLE
genimage ctl-c leaves mount points active

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1936]
on our setup we ran:

```
genimage rh72-op5-garison-nb

ctl-c (break out genimage).
```

After the job was exited we got:

```
grep -i install /proc/mounts
/dev/mapper/xcat_data-install /install xfs rw,relatime,attr2,inode64,noquota 0 0
proc /install/netboot/rhels7.2/ppc64le/rh72-op5-garison-nb/rootimg/proc proc rw,relatime 0 0
sysfs /install/netboot/rhels7.2/ppc64le/rh72-op5-garison-nb/rootimg/sys sysfs rw,relatime 0 0
```

If any of the postinstall scripts add additional mount points, very bad things happen with when the rmimage is done.

For example, we had an incident where there was this mount point left active after a genimage ctl-c by a postinstall script

```
install  /install/netboot/rhels7.2/ppc64le/rh72-op5-garison-nb/rootimg/install install rw,relatime 0 0
```

Where the /install directory directory was mounted the rootimage directory.  When rmimage was done, then entire contents of the install /install were deleted.

Also, mount points being left can also render the system unable to re-create the directory again, when genimage is run again, the system returns a failure when genimage attempts to create the root directory.  This is due to stale file handles left behind in active mount points.  The only way we were able to recover from this was to reboot the xcat management node.

We believe that this could be fixed with a simple script in the rmimage program:

```
grep $installroot /proc/mounts | perl -nle '/(\S+) (\S+)/ && print "$2"' | while read -r dir
do
logInfo "$thisscript Unmounting $dir"
umount -rl $dir
done
```

where installroot is pointed to the rootimg directory of the osimage.  We use this script in an exit trap in our postinstall scripts to avoid this problem, but it turned out that ctl-c during the genimage can sometimes bypass this, with rather catastrophic resutls.

**Comment by immarvin** [comment]
hi @ralphbellofatto , would you please provide the xCAT release you are using(``lsxcatd -v``)?

in fact we have signal handler in ``genimage`` in the code,  we need to recreate this issue in our env, this is a bug for genimage if the issue exists in latest xCAT release.

**Comment by ralphbellofatto** [comment]
lsxcatd -v
Version 2.12.3 (git commit ee11ecddb7e3c323b11857826a072303ae5a7b20, built Thu Sep 22 06:16:00 EDT 2016)

**Comment by immarvin** [comment]
duplicate bug as https://github.com/xcat2/xcat-core/issues/448

**Comment by immarvin** [comment]
hi @neo954 , would you please take a look at this?

**Comment by ralphbellofatto** [comment]
This is not exactly a duplicate bug, even if you handle this term signal, the mounts might points might still escape this.

Especially if a postinstall script did a mount point (which is what happened to us).  A precheck prior to removing the image file to make sure there are no mountpoints left in what is about to be deleted, would safeguard against this kind of mistake happening again...

It still leaves the problem of what happens when the rootimage directory changes in an osimage, so maybe that step should also check for stray mount points, as they should not be there at the point that the rootimage directory is moved forward to a new name.

**Comment by immarvin** [comment]
currently, genimage and rummage only unmount the /prov /sys and /dev. We can consider to unmount all the entries in ``mount``  with mount points under "rootimg" directory.

**Comment by neo954** [comment]
@ralphbellofatto, and we need to handle the `umount` operation properly in the signal handler of the post-install script.

**Comment by ralphbellofatto** [comment]
Please do consider this, but also, consider doing the same in rmimage, and possibly when someone does chdef -t osiamge rootimgdir=newrootdir...

User provided postscripts can leave things mounted in here which can cause operational problems later on, sometimes with unexpected, and catastrophic results.

We have bash script exit trap that scans for all mounts and then unmount them, but we did find that hitting ctl-c enough times during genimage can even defeat that and at one point lost our entire /install directory as a result.

This is what we insert into all our postinstall scripts:

```
# exit trap to undo any mounts done earlier
function mnt_exit_trap {
    set +e
    if [ -z $installroot ]; then
	return
    fi
    set -x
    # pull the mounts out submounts to the install directory from the /proc/mounts file.
    grep $installroot /proc/mounts | perl -nle '/(\S+) (\S+)/ && print "$2"' | while read -r dir
    do
	logInfo "$thisscript Unmounting $dir"
	umount -rl $dir
    done
} 
if [ ! -z $installroot ]; then
  trap mnt_exit_trap EXIT
fi
```

My thought here is that this alogrithm is what should be used in genimage exit, rmimage pre-check and chdef -t osimage xxx rootimgdir=newname...

The chdef case is interesting.  It comes from an operational pattern where a new rootimage directory is created (usually with a date) to  keep the existing nodes that point to the older image still working.  If one leaves mount points active in this directory then, months later, when someone goes to clean up the oldest rootimg directories, really bad things can happen.

Effectively, old mount points left behind while running genimage and postinstall scripts AND this operational pattern and a ctrl-c out of a genimage, can leave an operational bomb primed and ready to go off at a later date.

**Comment by ralphbellofatto** [comment]
My point being here, that even with the trap, above trap we still had an escape with ctl-c bypassing the trap, if hit enough times in sequence..

**Comment by neo954** [comment]
Hello @ralphbellofatto, your `mnt_exit_trap()` function `fork()`ed too many times, which is resource consuming. Try to make the code tidy, like the one below. Thus, there is a less chance you break the execution of `mnt_exit_trap()` by a subsequent Ctrl-C.

    # exit trap to undo any mounts done earlier
    function mnt_exit_trap {
        set +e
        [ -z "$installroot" ] && return
        set -x
        # pull the mounts out submounts to the install directory from the /proc/mounts file.
        while read -r blah dir blah
        do
            [ "${dir:0:${#installroot}}" = "${installroot}" ] && umount -rl "$dir"
        done </proc/mounts
    } 
    if [ -n "$installroot" ]; then
        trap mnt_exit_trap EXIT
    fi

**Comment by ralphbellofatto** [comment]
Thanks for the code suggestion,  I will incorporate it,

However, still think the rmimage and chdef -t osimage rootimgdir= need to guard against stray mount points, 

The result of the subsequent removal of the directory with mountpoints either leave us not able to create a new rootimage dir on top of the old one, or worse, leaves us with deleting something we really don't want deleted.

**Comment by ralphbellofatto** [comment]
I took a look at the original code an your re-write,

However, while some things are done in one line and i do them in 2, I'm failing to see why this would make a difference in what happens during ctrl-c?

Also, this construct:
    while read -r blah dir blah
    do
        [ "${dir:0:${#installroot}}" = "${installroot}" ] && umount -rl "$dir"
    done </proc/mounts

Depends on having the /proc file system mounted, and since this can be causing the proc file system to be unmounted, or it may not even be mounted at this point this function is called, this may not work all the time...

**Comment by neo954** [comment]
@ralphbellofatto,

Of course, your script should run outside the chroot environment. Otherwise, how could you do all these `umount`ing stuff.

And by use the `bash` build-in command instead of external command, you reduce the chance of break the execution of `mnt_exit_trap()` by a subsequent Ctrl-C. Since this is a `bash` script instead of real system program which is written in C language. For a C program, in the signal handler function, you cannot use any buffered I/O functions, like `printf()`, and you cannot use any function which use internal static variable to maintain its states. And any succeeded signal delivery is blocked by the kernel while a signal handler is running.

But this is not the case, since in your case, this is a `bash` script. In your original code, you use `grep ... | perl ...` and `print ... | while ... do ... done`. For each pipeline, it need two `fork()s`, two `exec()`s, a `pipe()`, a `setpgrp()`, and a lot of process context switches. This is too much heavy for a "signal handler" in `bash` script. There are too many chance the function get broke by a subsequent Ctrl-C.

**Comment by ralphbellofatto** [comment]
Thanks for the explanation here,

While this reduces the chances of leaving a stray mount point, it does not eliminate it.

It would be a good thing if this type of check could be done before rmimage and before chdef -t osimage rootimgdir=xxx

Without this, we have code in xcat + postinstall scripts that can leave something in the system that can have very unexpected side effects.

**Comment by neo954** [comment]
Hello @ralphbellofatto,

For a really good signal handler in `bash` script, you can design it in the following shape. Just flip a single global variable in the signal hander. And then do all the clean up works in your main script. Of course, in this way, you have to check up the single global variable frequently at some checkpoint in your main script.

And this is also the proper way to write a signal handler in C language, if you intend to do some complex works like `printf()` when signal delivered to your program.

In this way, you can avoid all the mess up and do a proper clean up.

    declare -i CLEANUP_N_EXIT=""

    # exit trap to undo any mounts done earlier
    function mnt_exit_trap {
        set +e
        [ -z "$installroot" ] && return
        set -x
        # pull the mounts out submounts to the install directory from the /proc/mounts file.
        while read -r blah dir blah
        do
            [ "${dir:0:${#installroot}}" = "${installroot}" ] && umount -rl "$dir"
        done </proc/mounts
    } 

    trap mnt_exit_trap EXIT

    trap CLEANUP_N_EXIT=YES EXIT

    # Do things ...
    some_commands
    [ -n CLEANUP_N_EXIT ] && mnt_exit_trap

    # Do things ...
    some_other_commands
    [ -n CLEANUP_N_EXIT ] && mnt_exit_trap

    # Do things ...
    blah_blah_blah
    [ -n CLEANUP_N_EXIT ] && mnt_exit_trap

    # Do things ...
    blah_blah_blah
    [ -n CLEANUP_N_EXIT ] && mnt_exit_trap

**Comment by ralphbellofatto** [comment]
Thank you for the tips on improved signal handling.

But this still does not completely close the hole here,  We really need a way to prevent stray mount points from being left in the rootimg directory prior to rmimage and chdef -osimage rootimgdir=<somenew directory>

Right now, the only alternative you are leaving me with is a cron job that will check for this condition and correct it if it finds it.

**Comment by immarvin** [comment]
a PR on guard code for genimage and rmimage:  https://github.com/xcat2/xcat-core/pull/2036

**Comment by immarvin** [comment]
hi @ralphbellofatto , the PR has been merged, please verify

**Comment by neo954** [comment]
It seems the issue was closed automatically while I merged pull request #2036. Just re-open it since we still need to verify the fix.

**Comment by whowutwut** [comment]
@ralphbellofatto  If you can verify and close out, please do, otherwise @tingtli  Can you assign FVT team to help verify and close out?

**Comment by tingtli** [comment]
I have verified with the 2.12.4 build on rhels7.3 ppc64le
```
[root@c910f03c17k22 ~]# lsxcatd -v
Version 2.12.4 (git commit 64ec2d41285d9a8770d8d9ef909f251ecbb5100b, built Thu Nov 10 23:59:02 EST 2016)
```
This is what i did
1. install xcat 2.12.4 and config mn
2. genimage rhels7.3-ppc64le-netboot-compute 
3. During genimage, press ctrl+c
4. execute grep -i install /proc/mounts and get nothing

```
[root@c910f03c17k22 ~]# grep -i install /proc/mounts
[root@c910f03c17k22 ~]#
```
@immarvin  Is this verification ok? Let me know your comments.

**Comment by ralphbellofatto** [comment]
Is there also a check for this in the "rmimage" command?

**Comment by immarvin** [comment]
hi @ralphbellofatto , yes

@tingtli , the command to check should better be ``grep -F '/install' /proc/mounts``

**Comment by whowutwut** [comment]
@ralphbellofatto  Are you able to validate this in your environment?

**Comment by ralphbellofatto** [comment]
this seems to be ok, i have not seen a stray mount in a root image since the update.

**Comment by whowutwut** [comment]
Thanks @ralphbellofatto
