### ISSUE TITLE
nodeset nodename boot forgets what the node is provisioned with.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1937]
When doing the following sequence with a stateful boot, updatenode subsequently fails, switch to network boot and back to stateful boot.

```
nodeset c460c002 osimage=rh72_op5_login         # diskful boot
xdsh c460c002 reboot
#....  Wait for node to be provisioned
nodeset c460c002 osimage=rh72_op5_compute   # statless boot
xdsh c460c002 reboot
# ...  wiat for node to reboot
nodeset c460c002 boot
```

Update node seems to have lost the infomation to be able to run the postscripts associated with the osimage that was installed on this node previously.

In our lab this is relatively common procedure where we want to temporarly replace the image with a networkbooted image (usually with a custom kernel, or some other test configuration), and then revert back to the network booted state.

After we issue the nodeset xxx boot command we see the following as differences left in the lsdef c460c002:

```
[root@c460mgt01 ralphbel]# diff c460c002.b.lsdef c460c002.lsdef
15c15
19c19
<     initrd=xcat/osimage/rh72_op5_compute/initrd-stateless.gz

---
>     initrd=xcat/osimage/rh72_op5_login/initrd.img
22,23c22,23
<     kcmdline=imgurl=http://!myipfn!:80//install/netboot/rhels7.2/ppc64le/rh72_op5_compute/rootimg.cpio.gz XCAT=!myipfn!:3001 NODE=c460c002 FC=0 BOOTIF=70:e2:84:14:10:ad
<     kernel=xcat/osimage/rh72_op5_compute/kernel

---
>     kcmdline=quiet inst.repo=http://!myipfn!:80/install/RHEL-7.2-20160512.0-Garrison/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/c460c002 BOOTIF=70:e2:84:14:10:ad  ip=dhcp
>     kernel=xcat/osimage/rh72_op5_login/vmlinuz
37a38
>     provmethod=rh72_op5_login
```

The critical element that seems to prevent the updatenode from producing the expected result is the missing provmethod.

We track all configuration changes to our system in source control, so this also results in elements of the lsdef looking like they are still pointing to elements of the stateless boot.  This generates confusion among the people who have to administer the system.

We can work around it one of two ways.

```
chdef c460c002 provmethod=rh72_op5_login
```

This will result in the update node working properly, but still leave behind the rest of the elements in the lsdef, adding to the confusion of using the system.

Another method, and a bit more dangerous would be...

```
nodeset c460c002 osimage=rh72_op5_login
chdef c460c002 currstate=boot
```

However if the second step, the,  current boot setting is omitted or an error is made, then on the next reboot the statefull system will be re-provisioned, wiping out anything stored on the hard drive.  This has caused some complaints from users about unexpectedly loosing their data.

**Comment by immarvin** [comment]
hi @ralphbellofatto , thanks for your explanation, this make things much clear. 

Currently, most key attributes in node definition are switched by "nodeset", these attributes provides instructions  on what to do on next reboot.  After the provision is finished, some attributes like "currstate", "status" are updated, we suppose the attributes of the node at this time represent the current state of the node. 

the diskfull system provisioned with "rh72_op5_login" before the diskless provision with "rh72_op5_compute" is a "historical" state for xCAT. xCAT does not maitain any historical information in the node definition, in fact, xCAT did not know what's on the hard disk after a diskless provision.

Maybe a command to grab the node information on a running node will help in the scenario you described, we need to initiate a discussion on this.

@whowutwut @daniceexi , what do you think?

**Comment by daniceexi** [comment]
How about doing the following two steps:
~~~~
nodeset c460c002 osimage=rh72_op5_login
nodeset c460c002 boot
~~~~

**Comment by ralphbellofatto** [comment]
those two steps are what we are currently doing,

however, it is problematic, because if one forgets the second step, then the next reboot the node is going to be reprovisioned.  So I am reluctant to issue instructions to other administrators that this should be the step to follow.  

Distract the person between step 1 and step2, and, well we have a problem..

The ideal method would be on setting the node to boot, that when it finally boots up, the system can restore the setting to what it was on the nodeset osimage=xxx, with the data extracted from the node once it is booted.  However, that is getting a bit complicated.  Grabbing the information like this has to wait until the node is booted.

Or to provide a variation of the nodeset function that effectively does the two steps you suggest in one atomic operation.  The onus would be on the administrator to properly remember what was previously booted on the node.  But at least we don't loose our users information that is left on the disk.

**Comment by daniceexi** [comment]
@ralphbellofatto I understand your pain point.  Two questions:

* Is this really necessary to be a common function for ``nodeset`` command?
* How to define this function for user to understand?

**Comment by ralphbellofatto** [comment]
well,

Right now we have an operational problem, that either,

- nodeset xxx boot
- updatenode xxx

Does not work and doing 

- nodeset xxx ossimage=stateful image
- nodeset xxx boot

Is prone to operational error.

**Comment by zet809** [comment]
@ralphbellofatto "nodeset xxx ossimage=stateful image" shall be "nodeset xxx osimage=stateful image", just a spell error here?

**Comment by ralphbellofatto** [comment]
yes, spelling error:

should be osimage=stateful_image
