### ISSUE TITLE
nodeset nodename boot forgets what the node is provisioned with.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1938]
When doing the following sequence with a stateful boot, updatenode subsequently fails, switch to network boot and back to stateful boot.
```
nodeset c460c002 osimage=rh72_op5_login         # diskful boot
xdsh c460c002 reboot
#....  Wait for node to be provisioned
nodeset c460c002 osimage=rh72_op5_compute   # statless boot
xdsh c460c002 reboot
# ...  wiat for node to reboot
nodeset c460c002 boot
```

Update node seems to have lost the infomation to be able to run the postscripts associated with the osimage that was installed on this node previously.

In our lab this is relatively common procedure where we want to temporarly replace the image with a networkbooted image (usually with a custom kernel, or some other test configuration), and then revert back to the network booted state.

After we issue the nodeset xxx boot command we see the following as differences left in the lsdef c460c002:

```
[root@c460mgt01 ralphbel]# diff c460c002.b.lsdef c460c002.lsdef
15c15
19c19
<     initrd=xcat/osimage/rh72_op5_compute/initrd-stateless.gz
---
>     initrd=xcat/osimage/rh72_op5_login/initrd.img
22,23c22,23
<     kcmdline=imgurl=http://!myipfn!:80//install/netboot/rhels7.2/ppc64le/rh72_op5_compute/rootimg.cpio.gz XCAT=!myipfn!:3001 NODE=c460c002 FC=0 BOOTIF=70:e2:84:14:10:ad
<     kernel=xcat/osimage/rh72_op5_compute/kernel
---
>     kcmdline=quiet inst.repo=http://!myipfn!:80/install/RHEL-7.2-20160512.0-Garrison/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/c460c002 BOOTIF=70:e2:84:14:10:ad  ip=dhcp
>     kernel=xcat/osimage/rh72_op5_login/vmlinuz
37a38
>     provmethod=rh72_op5_login
```

The critical element that seems to prevent the updatenode from producing the expected result is the missing provmethod.

We track all configuration changes to our system in source control, so this also results in elements of the lsdef looking like they are still pointing to elements of the stateless boot.  This generates confusion among the people who have to administer the system.

We can work around it one of two ways.
```
chdef c460c002 provmethod=rh72_op5_login
```

This will result in the update node working properly, but still leave behind the rest of the elements in the lsdef, adding to the confusion of using the system.

Another method, and a bit more dangerous would be...
```
nodeset c460c002 osimage=rh72_op5_login
chdef c460c002 currstate=boot
```

However if the second step, the,  current boot setting is omitted or an error is made, then on the next reboot the statefull system will be re-provisioned, wiping out anything stored on the hard drive.  This has caused some complaints from users about unexpectedly loosing their data.

**Comment by immarvin** [comment]
hi @ralphbellofatto ,
how about run "nodeset" just before you issue a new provision with "rpower" or "xdhs xxx reboot"?  is there any technical reason that "updatenode" must be run between "nodeset xxxx osimage=yyy" and "rpower"/"xdhs xxx reboot"?

**Comment by ralphbellofatto** [comment]
We could change the order of our operations.

However, in this scenario we are not trying to do a new provision here, we are trying to avoid one.

We have a node that is already statefully provisioned,  Then for a couple of days we want to have it to be stateless with a test setup.  

Then we want to return it to its previous stateful state.  Which is what "nodeset xxx boot" does, however, then updatenode does not work.

If the administrator does a nodeset xxx osimage=stateful-image, then the next reboot will reprovision the node.  This is problematic if our user base has stuff stored on the node, as this will wipe it out.

This makes the nodeset xxx boot, problematic and error prone to use.

the use of updatenode in this scenario is to demonstrate part of the operational problem.

**Comment by immarvin** [comment]
duplicate with https://github.com/xcat2/xcat-core/issues/1937
