### ISSUE TITLE
mkconservercf does not preserve timestamp default information.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1944]
We have a requirement that all console logs have timestamps on every line, so to do that we alter the /etc/conserver.cf file to have timestamp 1l;

Everytime we run makeconservercf it overwrites this data with:
```
default * {
  logfile /var/log/consoles/&;
  timestamp 1lab;
  rw *;
  master localhost;
  options ondemand;
}
```

So to compenstate for this we need to always do a hand edit of makeconserver cf to re establish this setting.

We would like makeconservercf to either preserve this setting or provide a site table setting that would allow us to control this.

This also hits us for anything that xcat does where makeconservercf does that might end up calling the this.

Right now, the workaround for this is put directions out for our admins to alwasy check and edit this file after certain commands.

**Comment by immarvin** [comment]
hi @zet809 , would you please take a look at this requirement? thank

**Comment by mattaezell** [comment]
Ralph, what's wrong with 1lab? Is it the lines added by 'ab' that have the timestamp after the message?
> [-- root@localhost detached -- Wed Oct 12 10:15:24 2016]
> [-- root@localhost attached -- Wed Oct 12 10:15:26 2016]

**Comment by ralphbellofatto** [comment]
hm...

my experience is the default setting sets the timestamp once an hour...

Maybe it is out of date, i'll go check...

**Comment by mattaezell** [comment]
Commit b8763f4a24c859779cc9dfc796486756f3b632a4 on Mar 24 changed the default to 1lab

**Comment by zet809** [comment]
1l means the timestamp as "[Wed Oct 12 10:15:24 2016]" will be added to each line of the log file.

**Comment by whowutwut** [comment]
@ralphbellofatto  That commit specified was done from Pull Request...  https://github.com/xcat2/xcat-core/pull/845 I think you asked for it.    If the value will be changed often by the admin...  then maybe we should support  a configurable value.

**Comment by ralphbellofatto** [comment]
I think we are seeing the beginning of the need to make this configurable...

**Comment by ralphbellofatto** [comment]
1lab is fine...


Does what we want...  So my information may have been out of date or based on an older version, and we had been in the habit of changing the conserver.cf file...

**Comment by ralphbellofatto** [comment]
I do recall filing a previous bug report, so i may have missed when this on this issue.

**Comment by ralphbellofatto** [comment]
looking at the current log after makeconservercf and rebuilding, this looks good now, with this change:
Commit b8763f4

**Comment by zet809** [comment]
@ralphbellofatto Thx, ralph, will you pls close this defect if OK for you?

**Comment by ralphbellofatto** [comment]
closed, 1lab works as we would like it to, no need for further change.
