### ISSUE TITLE
some actions keep setting the ospkgsdir to a directory that does not exist.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1948]
we noticed that xcat keeps setting the ospkgsdir attribute on its own.

To duplicate the problem we do:

```
lsdef -t osimage rh72_op5_compute | tee rh72_01.lsdef
genimage rh72_op5_compute
lsdef -t osimage rh72_op5_compute | tee rh72_02.lsdef

diff rh72_01.lsdef rh72_02.lsdef
7a8
>     otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le

```

**Comment by immarvin** [comment]
"/install/post/otherpkgs/<os>/<arch>" is the default value of  "otherpkgdir" for an osimage definitions, which are defined on "copycds".  
This default value is a hint for user on where to place the additional 3rd party packages they want to install on compute node, xCAT won't create this directory, user need to create this directory by themselves(http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_other_pkg.html). 
There used to be some discussion inside xCAT team, we finally decided to keep the "otherpkgdir" default value and not to create the actual path by default, which left as a step in the documentation.

**Comment by ralphbellofatto** [comment]
Is there any way to get xcat to not continually insert this.  We removed it and every time we run genimage it comes back..

**Comment by cxhong** [comment]
for this issue, otherpkgdir is inserted from genimage command.  users removed this attribute from their osimage, xCAT should not insert it again after genimage.

**Comment by daniceexi** [comment]
@ralphbellofatto I'd like to know the background why you need to clean up this pah?

**Comment by ralphbellofatto** [comment]
well,

1.  we don't use this path in our systems.
2. we keep our xcat lsdefs under source control and this change that we did not do, keeps appearing.
3.  I get tired of explaining why this path has to be in the system, especially when subsystems complain about referencing it.

**Comment by whowutwut** [comment]
I agree with @ralphbellofatto and @cxhong  that we should not put this back into the attribute if the user removed it.   This is a difference in behavior between diskful and diskless, we are not replacing the `otherpkgdir` if the user removes it for diskful systems when we provision the node.     @cxhong , will create a pull request to remove the addition of the otherpkgdir.
