### ISSUE TITLE
Add rhelhpc7.2 and  rhelhpc6.8 support to discinfo.pm

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#1955]
We need to update discinfo.pm for support rhelhpc7.2 and rhelhpc6.8 (RHEL ComputeNode version)

**Comment by immarvin** [comment]
hi @fenggaobj , since the PR has been merged, feel free to set it to "pending" or "close" after you verified

**Comment by fenggaobj** [comment]
Close it first, reopen if there are issues.
