### ISSUE TITLE
Need to have a way update the ipmitool-xcat dependency package with the rest of xCAT 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1957]
In the recent rebuilds of the `ipmitool-xcat` rpm, this rpm is lost in the update process since it won't be picked up with the `yum update "*xCAT*"` string that we document. 

The user would also need to run `yum update "*xcat*"` to pick up the ipmitool-xcat updates. 

Since `ipmitool-xcat` seems to be updated fairly often, and I don't see a stop of that anytime soon... can we consider placing a requires on a package of xCAT that will automatically pull in the `ipmitool-xcat` updates. 

Let me clarify that I don't think we should necessarily fix all the dependency issues on the update, but since ipmitool-xcat is one that is tied to hardware, and we should be at 1.8.17 for Minsky, I'm only trying to solve this problem

**Comment by daniceexi** [comment]
@whowutwut 

I think we have added the version check for ipmitool like following:

~~~~
Requires: ipmitool-xcat >= 1.8.15-2
~~~~

So that means we need to change the required version number for each xCAT release.

**Comment by whowutwut** [comment]
@daniceexi  Ah yes, so the 2.12.3, we should have required 1.8.17..   let's do that for 2.12.4

**Comment by daniceexi** [comment]
@whowutwut we need to add a check in our release check list (work list) to check whether the correct version has been required in the rpm spec file.

**Comment by pdlun92** [comment]
PR #2030 merged.  Closing issue

**Comment by whowutwut** [comment]
@daniceexi  @tingtli Is there any test that we have that would expose this?  I think this should be part of our migration testing.  If we installed the last release.. xCAT 2.12.3 with the 2.12.3 dep, then run `yum update '*xCAT*'` the ipmitool-xcat package should also be updated as a result....

**Comment by daniceexi** [comment]
Since both of xcat install and migration have been covered by test cases, update the corresponding test cases will cover it.
