### ISSUE TITLE
[FVT]Diskless installation failed in X86_64 sles12.1

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1967]
ENV: sles12.1 X86_64
Description:  Failed to install diskless  flat
Reproduce: install diskless normally
Details:

```
RUN:lsdef -l c910f04x12v04 | grep status

[lsdef -l c910f04x12v04 | grep status] Running Time:1 sec
RETURN rc = 0
OUTPUT:
    status=failed
    statustime=10-13-2016 06:03:57
CHECK:rc == 0   [Pass]
CHECK:output =~ booted  [Failed]
```

**Comment by caomengmeng** [comment]
Fixed by :  https://github.com/xcat2/xcat-core/pull/1959
close

**Comment by caomengmeng** [comment]
Failed to install diskless on rh6.8 ppc64 with latest daily build, so reopen this issue:
```
lsdef -l c910f02c08p10 | grep status
    status=netbooting
    statustime=10-14-2016 14:30:06
    updatestatus=synced
    updatestatustime=10-14-2016 14:16:51
```

**Comment by immarvin** [comment]
hi @penguhyang , please contact @caomengmeng and take a look

**Comment by penguhyang** [comment]
This issue can't be recreated.

**Comment by immarvin** [comment]
close this issue since it can not be recreated, please reopen it if you find the same problem
