### ISSUE TITLE
imgexport - Could not  find rootimg

### ISSUE THREAD

**Issue by kkvtran** [xcat2/xcat-core#1971]
````
# imgexport rhels7.2-ppc64le-gca-diskless
Exporting rhels7.2-ppc64le-gca-diskless to /tmp...
Error: Couldn't find rootimg (rootimg.gz) for  rhels7.2-ppc64le-gca-diskless

# cd /install/diskless/rhels7.2/ppc64le/compute
# ls
initrd-stateless.gz  initrd-statelite.gz  kernel  rootimg  rootimg.cpio.gz
````
It seemed that the name of the rootimage file to be rootimg.cpio.gz when doing packimage, but didn't modified accordingly for imgexport.

**Comment by cxhong** [comment]
@kkvtran this issued is fixed in the
https://github.com/xcat2/xcat-core/pull/1907 
should be in the 2.12.3 release.

can u check what version of xcat you have?

**Comment by whowutwut** [comment]
@kkvtran  FYI, If you wrap the code between 3 back ticks (```) it will format your post to be easier read.

**Comment by immarvin** [comment]
seems duplicate with https://github.com/xcat2/xcat-core/issues/1903
