### ISSUE TITLE
[FVT]Failed to install diskfull hierarchy on rh6.8 ppc64

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1973]
ENV: rh6.8 ppc64 latest daily build- 10.14 2016
Description: to install diskfull hierarchy on rh6.8 ppc64, the status is Powering on not booted

```
[root@c910f02  result]# lsdef -l c910f02c08p10 | grep status
    status=powering-on
    statustime=10-14-2016 18:17:06
    updatestatus=synced
    updatestatustime=10-14-2016 14:16:51
```

**Comment by tingtli** [comment]
The root cause is because the SN is not correct installed. Please refer to defect #1958 
I will close this one, please see #1958 for the trace.
