### ISSUE TITLE
Job for dhcpd.service failed. See "systemctl status dhcpd.service" and "journalctl -xn" for details.

### ISSUE THREAD

**Issue by rathdowney** [xcat2/xcat-core#1982]
Hi Guys 
Can someone help me why this happened? It was working fine and now DHCP isn't available

systemctl status dhcpd.service
dhcpd.service - ISC DHCPv4 Server
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-10-18 11:04:55 EDT; 8s ago
  Process: 6967 ExecStart=/usr/lib/dhcp/dhcpd -4 start (code=exited, status=1/FAILURE)

Oct 18 11:04:55 d2mixphhpc033 dhcpd[7095]: than a configuration issue please read the section on submitting
Oct 18 11:04:55 d2mixphhpc033 dhcpd[7095]: bugs on either our web page at www.isc.org or in the README file
Oct 18 11:04:55 d2mixphhpc033 dhcpd[7095]: before submitting a bug.  These pages explain the proper
Oct 18 11:04:55 d2mixphhpc033 dhcpd[7095]: process and the information we find helpful for debugging..
Oct 18 11:04:55 d2mixphhpc033 dhcpd[7095]:
Oct 18 11:04:55 d2mixphhpc033 dhcpd[6967]: Starting ISC DHCPv4 Server
Oct 18 11:04:55 d2mixphhpc033 dhcpd[6967]: please see /var/log/rc.dhcpd.log for details ..failed
Oct 18 11:04:55 d2mixphhpc033 systemd[1]: dhcpd.service: control process exited, code=exited status=1
Oct 18 11:04:55 d2mixphhpc033 systemd[1]: Failed to start ISC DHCPv4 Server.
Oct 18 11:04:55 d2mixphhpc033 systemd[1]: Unit dhcpd.service entered failed state.

**Comment by immarvin** [comment]
hi, 

most issues of this kind are caused by the errors in dhcpd configuration.

````
Oct 18 11:04:55 d2mixphhpc033 dhcpd[6967]: please see /var/log/rc.dhcpd.log for details ..failed
````
any useful info in /var/log/rc.dhcpd.log?

**Comment by immarvin** [comment]
no response from @rathdowney  for 2 months, will close this ticket first, please reopen it if recreated.

**Comment by AntCar23** [comment]
the solution is reboot, it works again.
