### ISSUE TITLE
Add support for cumulus switch

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#1984]
open this issue to keep track items for supporting cumulus switch.
1) discovery cumulus switch
2) Add DHCP request from cumulus onie installer
3)  set up root passwordless
4) config switch  

It will include code changes and documentation changes

**Comment by whowutwut** [comment]
This was the initial support check in for switches running onie installer (Cumulus OS) Closing this issue.  Will track new issues as we start to use the procedure to improve on it.

**Comment by immarvin** [comment]
hi @whowutwut , the Doc committed by @cxhong needs to be refined, I will create a PR to on this.

**Comment by whowutwut** [comment]
:+1:
