### ISSUE TITLE
[FVT]: copy log files from test MN to control node even if it is time out.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1985]
In out autotest framework, we set 10 hours as timeout for the test. That means when the tests last 10 hours, there should have something wrong and should be killed and exit.  But we didn't get the log back to control node. Then , when we analysis the logs, we would get something like "[JK][rhels6.8-x86_64-101][FAILED] TotalCase:0 TotalRun:0 Fail:0". But in fact, the test is run and we have totalcase and totalrun.
We need to add some code to process the log file when the time expired.

**Comment by tingtli** [comment]
@penguhyang Would you please review. Thanks!

**Comment by tingtli** [comment]
@hu-weihua  Would you please help to take a look, thanks!

**Comment by hu-weihua** [comment]
@litingt , I have pull request #28 in github.ibm . Could you review and merge it? thanks

**Comment by tingtli** [comment]
it is reviewed and fixed.
