### ISSUE TITLE
[FVT]:update default.conf file to make ubuntu migration value updates

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2005]
In xcat automation configuration file default.conf. We have following values to set the ubuntu xcat-core and xcat-dep file. I think for the latest ubutnu16.04.1 and ubuntu 14.04.4. It does not work since 2.10 and 2.11 do not support the latest ubuntu. Please update the version to 2.12 and above.  We need to do 2 things:
1. Update default.conf file
2. Update ubuntu16.04.1 and ubuntu14.04.4 bundle file.

**Comment by caomengmeng** [comment]
@tingtli https://github.com/xcat2/xcat-core/issues/2053, the default.conf is not existed now

**Comment by tingtli** [comment]
@caomengmeng Let  me clarify.
Please update the default.conf on github.ibm.com/xcat2/jenkins/nodes/xxx/default.conf
This is for our autotest. Thanks!

**Comment by caomengmeng** [comment]
@tingtli 
ibmgit PR: https://github.ibm.com/xcat2/jenkins/pull/32
xcat-core PR: https://github.com/xcat2/xcat-core/pull/2096

**Comment by tingtli** [comment]
Fixed with #PR 2096
