### ISSUE TITLE
Support bittorrent stateless provisioning in RHEL7

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2010]
Current CORAL plans have 500-1000 nodes per management server.  Transferring the rootimg over the network will become a bottleneck.
@jjohnson42 added bittorrent support in commit 471d9471716c0010612599487cd0814828652e7a, but the support was not carried over to RHEL 7.  Furthermore, it used `ctorrent` which is not available in EPEL7, so we either need a different client or ctorrent needs to be available in xcat-deps.

**Comment by daniceexi** [comment]
Thank you @mattaezell to raise this topic. xCAT team has a plan to work on this. 

@immarvin please take a look.

**Comment by immarvin** [comment]
still investgating

**Comment by immarvin** [comment]
move to next release

**Comment by whowutwut** [comment]
This is under discussion, will remove a milestone until we come up with a descision to reduce issue movement
