### ISSUE TITLE
Time required to run nodeset

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2024]
We've noticed that running `nodeset` to set an `osimage` on multiple nodes can take several seconds.

Single node:

```
# time nodeset summitdev-c0r0n01 osimage=summitdev-compute-rhels7.2 > /dev/null
real    0m1.402s
user    0m0.103s
sys     0m0.003s
```

18 Nodes:

```
# time nodeset c0r0 osimage=summitdev-compute-rhels7.2 > /dev/null
real    0m5.713s
user    0m0.110s
sys     0m0.004s
```

36 Nodes:

```
# time nodeset compute osimage=summitdev-compute-rhels7.2 > /dev/null
real    0m10.648s
user    0m0.118s
sys     0m0.004s
```

I'm worried that when we scale up to the full CORAL system this will take way too long.  What can we do to improve this?

**Comment by daniceexi** [comment]
@chenglch could you take a look why the time cost is in linear increase?

**Comment by immarvin** [comment]
``nodeset <node> osimage=xxx`` will run "makedhcp -a <node>", the time cost versus node number of ``makedhcp`` confirms to the linear increase since  ``makedhcp  -a <node>`` adds the dhcp lease per node in the following steps:
1) resolve the hostnames of the node to ip address
2) add dhcp leases for the node  with omshell

**Comment by daniceexi** [comment]
@immarvin If the call of ``makedhcp`` could not be skipped, we could try to add an option for **nodeset** cmd to avoid of running ``makedhcp`` if user knows that my change does not impact the dhcp cfg.

**Comment by mattaezell** [comment]
I think resolving the hostnames to IPs are pretty quick because we have them in the hosts file.  It looks like about half the time is in `mknetboot`.  There's a really long `foreach my $node (@nodes)` loop, that I wonder if some of the common elements could be pulled outside the loop to save some time.
The other half of the time is in dhcp; it looks like the `dhcp` plugin is called once per node.  Would it be possible to instead call it once with the noderange provided to `nodeset`?  Would that provide opportunities for the `dhcp` plugin to streamline things - like open a single `omshell` and pipe in multiple commands?

**Comment by chenglch** [comment]
<img width="1197" alt="nodeset" src="https://cloud.githubusercontent.com/assets/7165199/20514026/a9fa3424-b0c4-11e6-8f35-45d7d955aab2.png">

I tested `nodeset` command with 10 kvm nodes, above is the statistic graph which show the majority time spent by the subroutines.   
The subroutine `setNodeAttribs`, `subvars` and `copyAndAddCustomizations` cost most time as they are running in a for loop `foreach $node (@nodes)`. I think these calls are necessary and I don't have idea to optimize these subroutine. 
@daniceexi @zet809 @immarvin  any thought about this?

**Comment by chenglch** [comment]
I have updated the test results on http://10.5.101.10:8086 with running nodeset command on 50 nodes. It takes more than 30 seconds to complete. `setNodeAttribs` method is invoked 150 times which takes about 18 seconds

**Comment by gurevichmark** [comment]
So it takes about 1 min to nodeset 100 nodes.
On 5000 node CORAL system nodeset will take about 1 hour ?

**Comment by chenglch** [comment]
Not exactly, I got this result on my own virtual machine and the database is sqlite. The performance graph only shows where the bottleneck is in our code logic. On 5000 node CORAL system, service nodes are used, I guess it will not takes that long, but updating database for so many tables may be a problem.

**Comment by chenglch** [comment]
After optimizing the performance to update the database table, 30 percent better than the original version. See the detail http://10.5.101.10:8086/

**Comment by immarvin** [comment]
hi @chenglch , the index on the url you pasted can not be accessed

**Comment by whowutwut** [comment]
@chenglch  can you upload a screen shot showing the improvements? Would be interesting to see

**Comment by chenglch** [comment]
These mainly focus on the subroutine of setAttris to update data in the database.
original
![nodeset_old](https://cloud.githubusercontent.com/assets/7165199/23199102/4c5ecd76-f907-11e6-8ae8-f888f8b71cda.jpg)

after
![nodeset_new](https://cloud.githubusercontent.com/assets/7165199/23199227/41bf5592-f908-11e6-938b-3978553b8566.jpg)

**Comment by whowutwut** [comment]
I'll try and capture some data on this on the research cluster to compare with the original times in the description after updating xCAT to 2.13.2 release.

**Comment by jjohnson42** [comment]
You all broke a bunch of OS support...

**Comment by jjohnson42** [comment]
broke support for windows, and esx, and broke support for addkcmdline.

Note that once upon a time we did do 10,000 nodes without the slowness being intolerable...

**Comment by robin2008** [comment]
Even after the above performance enhancement.
For ppc64le, the 'nodeset' has bad performance when there are large amount nodes (say 5000 or 10000 fake nodes)

Some test result as below (testing on firestone physical machine with PGSQL,  2.13.3):

Total  Time(s) Commands
================================
~
5000, 104, makehosts performance[1-2500]
5000, 226, makedns -n performance[1-2500]
5000, 235, makedhcp performance[1-2500]
5000, 30280, nodeset performance[1-2500] osimage=rhels7.3-GA-ppc64le-install-compute
5000, 202, makehosts performance[1-5000]
5000, 462, makedns -n performance[1-5000]
5000, 456, makedhcp performance[1-5000]
5000, N/A, nodeset performance[1-5000] osimage=rhels7.3-GA-ppc64le-install-compute

And the result of nodeset for petitboot is larger that  nodeset with xnba. After analysis the petitboot plugin,  we found that the key reason as below:
In nodeset, we need to invoke makedhcp to make sure the lease entry is ok.  And in petitboot, it call makedhcp for each node in a loop,  but in xnba,  it pass the whole noderange to makedhcp.
Currently, makedhcp <one-node> has performance issue when large amount nodes defined. It take about 3-4 seconds to finish when 5000 node defined in DB.  So nodeset will be at least 3*operated_node_num.

5000, 0, makehosts performance1
5000, 4, makedns -n performance1
5000, 4, makedhcp performance1
5000, 6, nodeset performance1 osimage=rhels7.3-GA-ppc64le-install-compute
5000, 3, makehosts performance[1-50]
5000, 8, makedns -n performance[1-50]
5000, 9, makedhcp performance[1-50]
5000, 175, nodeset performance[1-50] osimage=rhels7.3-GA-ppc64le-install-compute
           ~~~ 3 * 50
But in xnba plugin,  as it use bulk operation,  it won't has such issue.

**Comment by robin2008** [comment]
The makedhcp performance issue will be considered by #2676 ,  here we need to consider the bulk operation for makedhcp at least.

**Comment by robin2008** [comment]
We can see that in the old loop no extra node level operation, so use batch operation does not have impact. 
https://github.com/xcat2/xcat-core/commit/b0a34bf12ed8cd263941fc7be27c2c921106c875

The only issue is that, in "makedhcp' batch operation, if one node failure due to wrong configuration,  the operation will not continue for the rest of nodes. But it is the same behavior as xnba.

**Comment by robin2008** [comment]
Test result on 2.13.3:

```
# time nodeset fake[1-50] osimage=rhels7.3-ppc64le-install-compute >/dev/null

real	0m10.978s
user	0m0.156s
sys	0m0.028s
# time nodeset fake[1-36] osimage=rhels7.3-ppc64le-install-compute >/dev/null

real	0m9.602s
user	0m0.172s
sys	0m0.017s
# time nodeset fake[1-18] osimage=rhels7.3-ppc64le-install-compute >/dev/null

real	0m6.777s
user	0m0.164s
sys	0m0.006s
```

**Comment by mattaezell** [comment]
Compared to the original report of 10.6 seconds for 36 nodes, 9.6 seconds for the updated code is considered enough improvement to close this?

**Comment by robin2008** [comment]
@mattaezell Not for the comparison between 10.6 and 9.6,  we can see in previsou
18 -> 36,  the time is from 5 to 10,  and now the growth become more flat 6 -> 9

And in previous,  for OPAL physical machine,  nodeset on 5000 nodes,  it will take about long time.
The root cause is just as you spotted that "dhcp plugin is called once per node",  now we fix it, and get the below comparison (#2681):
```
Total	CMD	range	After-fix	before
5000	 nodeset	1	3	6
5000	 nodeset	50	10	175
5000	 nodeset	100	17	364
5000	 nodeset	250	42	1056
5000	 nodeset	500	97	2858
5000	 nodeset	1000	212	7434
5000	 nodeset	2500	781	30280
5000	 nodeset	5000	2202	35710 (ctrl-c to stop)
```

**Comment by mattaezell** [comment]
@robin2008 Thanks for the clarification, that does look better.

**Comment by robin2008** [comment]
We are still looking for better enhancement for performance of nodeset/makedns/makedhcp in the following sprint , especially for CORAL like hierarchy topology.
