### ISSUE TITLE
Create pkglists in xCAT-csm rpm to match nodes being used in CSM development

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#2028]
xCAT-csm skeleton created in pull request #1941 

Next step is to populate pkglists and postscripts to mirror those being used in CSM development.  End goal is to create xCAT-csm rpm that will allow easy installation of all CSM node types

**Comment by whowutwut** [comment]
I'll review the changes and target 2.13 release to incorporate these files.  We can set to pending once merged.

**Comment by whowutwut** [comment]
Let's re-open this when we have more idea about the xCAT-csm RPM contents
