### ISSUE TITLE
Unable to boot a RHEL compute node with an image that has site.installdir

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#2029]
Steps to recreate:
1. Set site.installdir to something like "/install/abc".
2. Run `copycds` to create an image.
3. Issue `nodeset <node> osimage=<image>`

Errors reported:

```
fs2vm101:/tmp/gurevich # nodeset mgXgeneratedvm1 osimage=rhels7.2-ppc64le-install-compute
Error: /install/abc/postscripts/_xcat is missing.
Error: /install/abc/postscripts/ca is missing.
Error: /install/abc/postscripts/hostkeys is missing.
Error: /install/abc/postscripts/_ssh is missing.
mgXgeneratedvm1: install rhels7.2-ppc64le-compute
```

**Comment by tingtli** [comment]
@gurevichmark  i don't think there is an attribute of rootimgdir in site table.
This is a attribute of osimage
And when you set the rootimgdir to /install/abc, you need to make sure that we have image under /install/abc, otherwise , you will enter #dracut prompt.
We can think about to improve this when user define rootimgdir to /install/abc, to check if there is image under it.

**Comment by gurevichmark** [comment]
@tingtli Thank you for you catching this. I made a mistake and meant `site.installdir` is step 1 above, not `site.rootimagedir`. When I run copycds, the image does get copied to `/install/abc`, but the node still can not be booted for me. Do you know if we have any testcases that try using xCAT when `site.installdir` is changed by the user ?

**Comment by tingtli** [comment]
@gurevichmark We don't have that case. I just run a quick verification and find we have some issues to support the installdir in site table. 
Here is what i tested
1.set the installdir in site table to /install/abc
2. copycds and the image truly copied to /install/abc
3. run nodeset and it got some error
```
[root@c910f02c01p22 /]# nodeset c910f02c01p23 osimage=rhels6.8-ppc64-install-compute
Error: /install/abc/postscripts/_xcat is missing.
Error: /install/abc/postscripts/ca is missing.
Error: /install/abc/postscripts/hostkeys is missing.
Error: /install/abc/postscripts/_ssh is missing.
c910f02c01p23: install rhels6.8-ppc64-compute
```
4. boot node c910f02c01p23 but it still gets the files from /install
```
                     ┌─────────────┤ Error ├─────────────┐
                     │                                   │
                     │ Unable to retrieve                │
                     │ http://c910f02c01p22:80/install/r │
                     │ hels6.8/ppc64/images/install.img. │
                     │                                   │
                     │              ┌────┐               │
                     │              │ OK │               │
                     │              └────┘               │
                     │                                   │
                     │                                   │
                     └───────────────────────────────────┘

```
I see defect #1852.  I am confused why they say this sometimes works. I don't think it works.

**Comment by gurevichmark** [comment]
@tingtli You are right !

1. I am seeing the same errors as you are with missing files when issuing `nodeset` command. Now sure how I missed that before. I will change the description of this issue to include the errors displayed.
2. I am working with @immarvin on #2009. It will fix the code to use the value of `site.installdir` in `local-repository.tmpl`. Today it is hardcoded there to be `/install` which might explain why, when you try to boot it is still trying to get files from `/install`
3. The issue #1852 is a little different. It talks about using `-p` flag on `copycds` command, while keeping `site.installdir` unchanged (set to `/install`)

**Comment by immarvin** [comment]
will add the description in doc and site table on this

**Comment by tingtli** [comment]
confirm with dev, this feature is not supported, they will update the doc. 
Remove the testcase_requested label.
