### ISSUE TITLE
[fvt]2.11:xdsh could not recognize single quote mark 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#203]
1.download the latest build
2.
c910f04x27v05:~ # xdsh c910f04x27v07 "echo 'test' >/tmp/test" 
c910f04x27v07:
c910f04x27v07: Someone could be eavesdropping on you right now (man-in-the-middle attack)!
c910f04x27v07: It is also possible that a host key has just been changed.
c910f04x27v07: The fingerprint for the ECDSA key sent by the remote host is
c910f04x27v07: 8c:f7:65:e6:80:2f:ee:57:19:87:ee:1d:1a:45:3a:3f [MD5].
c910f04x27v07: Please contact your system administrator.
c910f04x27v07: Add correct host key in /root/.ssh/known_hosts to get rid of this message.
c910f04x27v07: Offending ECDSA key in /root/.ssh/known_hosts:2
c910f04x27v07: You can use following command to remove all keys for this IP:
c910f04x27v07: ssh-keygen -R c910f04x27v07 -f /root/.ssh/known_hosts
c910f04x27v07: Password authentication is disabled to avoid man-in-the-middle attacks.
c910f04x27v07: Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.

c910f04x27v07: bash: -c: line 0: unexpected EOF while looking for matching `''
c910f04x27v07: bash: -c: line 1: syntax error: unexpected end of file
------------------>failed here while using ' ' for the string

**Comment by whowutwut** [comment]
@junxiawang  Can you provide the output for "lsxcatd -a" so we know the build date. 
We tried the latest on xcat.org   which is 9/15 and seems to work 

```
[root@c910f02c06p23 xcat-core]# lsxcatd -a 
Version 2.11 (git commit 327db814e6abd420c5ca370a97bab5addfffb495, built Tue Sep 15 05:02:22 EDT 2015)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=10.2.6.23|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=10.2.6.23
dbadmin=xcatadm
[root@c910f02c06p23 xcat-core]# xdsh  c910f02c06p25 "echo 'test' >/tmp/test" 
```

Can you remove the entry in known_hosts  causing that warning and retry?

**Comment by junxiawang** [comment]
@whowutwut yes it could not work after 9.16's build according to autotest's results

**Comment by whowutwut** [comment]
@pdlun92  can you try to update ``p23`` to the build that I created today: http://xcat.org/files_new/xcat/xcat-core/devel/Linux/core-rpms-snap.tar.bz2

Then try the command above again to see if it fails.

**Comment by immarvin** [comment]
This defect is caused by the xcat error while passing the args to xcat plugins. 

For the xcat command:
````
xdsh c910f03c01p08 "echo 'test' >/tmp/test" 
````
The $request passed to xdsh.pm is:
````
[root@c910f02c02p08 ~]# xcatd -f
xCAT: Allowing xdsh to c910f03c01p08 echo '\''test'\'' >/tmp/test for root from localhost
$VAR1 = \{
            '_xcat_clientfqdn' => [
                                    'localhost'
                                  ],
            'env' => [
                       'DSH_FROM_USERID=root',
                       'DSH_TO_USERID=root'
                     ],
            'arg' => [
                       'echo \'\\\'\'test\'\\\'\' >/tmp/test'
                     ],
            'node' => [
                        'c910f03c01p08'
                      ],
            '_xcat_clientport' => [
                                    48667
                                  ],
            '_xcat_authname' => [
                                  'root'
                                ],
            'username' => [
                            'root'
                          ],
            'noderange' => [
                             'c910f03c01p08'
                           ],
            'cwd' => [
                       '/root'
                     ],
            'clienttype' => [
                              'cli'
                            ],
            '_xcatpreprocessed' => [],
            '_xcat_clienthost' => [
                                    'localhost'
                                  ],
            'command' => [
                           'xdsh'
                         ]
          };
````

The string ``echo 'test' >/tmp/test`` is converted to
````
            'arg' => [
                       'echo \'\\\'\'test\'\\\'\' >/tmp/test'
                     ],
````
this caused the error mentioned in this issue.

This issue might be introduced by pull request https://github.com/xcat2/xcat-core/pull/174.

@hu-weihua ,can you take a look at your pull request?

**Comment by junxiawang** [comment]
@whowutwut 
I use your build but still failed,such as the details:
[root@c910f04x30v02 yum.repos.d]# lsdef -v
lsdef - Version 2.11 (git commit c89312f175ebb155944175b560e46e9c3130ca04, built Wed Sep 23 14:19:50 EDT 2015)
[root@c910f04x30v02 yum.repos.d]#
root@c910f04x30v02 yum.repos.d]# xdsh c910f04x30v12 "echo 'test'>>/tmp/t"
c910f04x30v12: bash: -c: line 0: unexpected EOF while looking for matching `''
c910f04x30v12: bash: -c: line 1: syntax error: unexpected end of file
[root@c910f04x30v02 yum.repos.d]#

**Comment by hu-weihua** [comment]
Sorry for this, I modified the original attribute accidently. I will make it right.

**Comment by hu-weihua** [comment]
Fixed. 
pull requests #223

**Comment by immarvin** [comment]
I have merged the fix by @hu-weihua , this issue can be closed.
@junxiawang , can  you verify it with the latest build?

**Comment by junxiawang** [comment]
tested
