### ISSUE TITLE
[FVT] /opt/../autotest/default.conf is deleted, which is the default configure file for xcattest

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#2053]
/opt/xcat/share/xcat/tools/autotest/default.conf is the default configure file for xcattest.
It is important for xcattest command.
This default.conf is supported by xcattest to make the commands easily to be used. No need to write the ```-f /fullpath/config file``` every time the xcattest is executed. 

In man page, it is described as below:
```
       -f configure file
                 Specifies the configuration file, if not specified, the default configure file is
                 /opt/xcat/share/xcat/tools/autotest/default.conf.
```
That means, if the config file is not defined while running xcattest command, the /opt/xcat/share/xcat/tools/autotest/default.conf is used. Otherwise, the config file must be defined every time the xcattest is executed.
So in xcattest code, it is also defined as the default file as well.
If the default.conf is deleted, both the xcattest executed logic, man page, and code, should be changed also.

**Comment by whowutwut** [comment]
Resolves issue #1585
