### ISSUE TITLE
[fvt]2.12.4 xcatprobe discovery could not fix predefined node's wrong definiton  if nodes' switch port using regular expression in switch table

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2060]
env:fs4
build:
[root@fs4 ~]# lsxcatd -v
Version 2.12.4 (git commit 05fdc34e19d3a6349635d3d0ae75d573c5f6f813, built Wed Oct 26 06:15:59 EDT 2016)
[root@fs4 ~]# 
How to reproduce:
```
[root@fs4 ~]# lsdef frame23cn17
Object name: frame23cn17
    arch=ppc64le
    bmc=50.23.17.1
    chain=runcmd=bmcsetup,osimage=rhels7.3-rc2-ppc64le-install-compute
 
   ....
    switch=switch-10-5-23-1
    switchport=17
[root@fs4 ~]# lsdef frame23cn177
Object name: frame23cn177
    arch=ppc64le
    bmc=50.23.17.1
    cons=ipmi frame23cn17
    ...
    profile=compute
    serial=100470A
    supportedarchs=ppc64
    switch=switch-10-5-23-1
    switchport=17
[root@fs4 ~]# 
```

in switch table:
```
[root@fs4 ~]# tabdump switch
#node,switch,port,vlan,interface,comments,disable
"edgecoresw1","switch-10-5-23-1","1",,,,
"discodiscogoodgood","switch-10-5-23-1","|\D+(\d+)\D+(\d+)|($2*1)|",,,,
"test01","switch-10-5-23-1","10",,,,
"disco","switch-10-5-23-1","|\D+(\d+)\D+(\d+)|($2*1)|",,,,
```
-------------------> for disco group node's port  using regular expression
So using xcatprobe discovery -n  frame23cn17 -m switch 
-----------------------------> could not fix the errors using probe
```

**Comment by whowutwut** [comment]
@junxiawang  what is the problem here? I can't quite follow.  

You have two node definitions that are pointing to the same switch and switch port? and that should be detected by probe??

**Comment by junxiawang** [comment]
@whowutwut  xcatprobe discovery precheck wrong if  the nodes using same ports and same switch ,if the switch's port defined using regular expression in switch table such as:\D+(\d+)\D+(\d+)|($2*1)

**Comment by zet809** [comment]
@whowutwut In the original code, it use 'switch' table to get node's 'switch' and 'switchport' information, but if those 2 attributes are assigned with regular expression, there won't be any entry for the specified node in the "switch" table. That is the root cause.
