### ISSUE TITLE
xCAT 2.12.3 - Policy table read incorrectly

### ISSUE THREAD

**Issue by abates1** [xcat2/xcat-core#2072]
We are using the policy table to prevent xCAT commands being run on nodes that belong to the "production" group. To do so, I added one line to the start of the policy table: 

    "1","*",,,"production",,,"deny",,
    "1.1","root",,,,,,"allow",,
    ...

However, this causes commands to fail on all nodes, regardless of their group. I initially thought this was because providing groups as a noderange was not allowed, but then I tried this:

    "1","*",,,"test",,,"allow",,
    "1.1","*",,,"production",,,"deny",,
    "1.2","root",,,,,,"allow",,
    ...

Commands now worked on nodes belonging to the "test" group, but failed on everything else, including nodes not belonging to the "production" group. The final configuration I tested was as follows:

    "1","*",,,"production",,,"deny",,
    "1.1","*",,,"test",,,"allow",,
    "1.2","root",,,,,,"allow",,
    ...

Once again, commands fail on every node including those in the "test" group, even though there is an explicit rule to allow commands on that group, presumably because the production rule comes first.

This issue has a temporary workaround of having the "allow" groups before the "deny" ones, but it is not ideal as now we have to add all nodes that we want to allow commands on to a separate group, or they will fail regardless of their association to the "production" group.

**Comment by immarvin** [comment]
hi @abates1 , would you please provide the output of the following commands?

1.  `lsxcatd -v`
2. `uname -a`
3. `cat /etc/*release`

thanks

**Comment by abates1** [comment]
Hello @immarvin ,

Here is the output of the requested commands:

    [root@tdsxcat ~]# lsxcatd -v
    Version 2.12.3 (git commit 75fe6a2f8f869d03b8c06845b4edffcbe8349a49, built Thu Sep 29 08:01:26 EDT 2016)
    [root@tdsxcat ~]# uname -a
    Linux tdsxcat 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    [root@tdsxcat ~]# cat /etc/*release
    CentOS release 6.7 (Final)
    CentOS release 6.7 (Final)
    CentOS release 6.7 (Final)

**Comment by immarvin** [comment]
hi @hu-weihua , since you are the owner of xcat security, would you please take a look at this?

thanks

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2199 by @hu-weihua

**Comment by whowutwut** [comment]
@tingtli  Can you help verify and close this out, or assign to someone in test to verify and close?

**Comment by neo954** [comment]
It was verified against xCAT version 2.13. I will close this one.
