### ISSUE TITLE
[DEV] add lock on genimage of sles and ubuntu

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2077]
In https://github.com/xcat2/xcat-core/pull/2036/files, we introduce the exclusive lock between genimage, packimage and rmimage, I only finished the rh/genimage, we need to add the lock to ubuntu/genimage and sles/genimage, please refer to the relevant part in PR https://github.com/xcat2/xcat-core/pull/2036/files

**Comment by immarvin** [comment]
please start work on this after the PR https://github.com/xcat2/xcat-core/pull/2036 has been merged

**Comment by immarvin** [comment]
hi @gurevichmark , would you please take a look at this issue?
thanks

**Comment by immarvin** [comment]
please also take a look at ``liteimg`` , ``imgexport``, ``imgimport``

**Comment by daniceexi** [comment]
@tingtli We need to test and add test cases for this new feature.

**Comment by gurevichmark** [comment]
Will do.

**Comment by gurevichmark** [comment]
@immarvin 
* Am I correct in assuming that only ` xCAT-server/share/xcat/netboot/XX/genimage` file needs to be changed for this issue? The other 3 files modified for #2036 are generic for any distro ?
* On the running system I found these `genimage` files. Do I only need to modify `sles/genimage` and `ubuntu/genimage` and leave others alone ?
```
./bin/genimage
./share/xcat/netboot/SL/genimage
./share/xcat/netboot/centos/genimage
./share/xcat/netboot/debian/genimage
./share/xcat/netboot/fedora/genimage
./share/xcat/netboot/fedora12/genimage
./share/xcat/netboot/mic/genimage
./share/xcat/netboot/ol/genimage
./share/xcat/netboot/rh/genimage
./share/xcat/netboot/sles/genimage
./share/xcat/netboot/suse/genimage
./share/xcat/netboot/ubuntu/genimage
```
* What is the purpose of `bin/genimage` file in the list above ? Is it just to find which of the `genimage` scripts to call from the list above ?

**Comment by immarvin** [comment]
hi @gurevichmark , 
1. yes, you only need to modify the genimage for ubuntu and sles,
````
./share/xcat/netboot/suse/genimage
./share/xcat/netboot/ubuntu/genimage
````
you also need to take a look at the following files:
````
./xCAT-server/lib/xcat/plugins/imgport.pm
#this is for ``imgimport/imgexport``
./xCAT-server/lib/xcat/plugins/statelite.pm
#this is for ``liteimg``
````
2. as you know,  xcat is a plugin framework with client/server model.  `bin/genimage` is the  fronted command line for "genimage" command, it commit a genimage request to xcatd, xcat dispatch the request to "xCAT_plugin/genimage.pm",  "xCAT_plugin/genimage.pm" calls the <os>/genimage script under "/opt/xcat/share/xcat/netboot/rh/"

**Comment by zet809** [comment]
The effort will be a little large, and ubuntu/sles is low priority for us, we have RH supported , so close this issue.
