### ISSUE TITLE
[DEV] the lock acquired with"$lock=xCAT::Utils->acquire_lock()" will be released outside the lifecycle of $lock 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2078]
consider the following code slice:
````
...

{
...
my $lock=xCAT::Utils->acquire_lock(...);
...
}
...
````

The acquired lock will be release outside ``{}`` 

it is not reasonable that a subroutine has specific requirement on the lifecycle of the variable holds its  return value

**Comment by immarvin** [comment]
hi @chenglch , would you please take a look at this?

thanks

**Comment by chenglch** [comment]
I think this is the default behavior of the GC which tries to close the file descriptor before getting the object out of the scope recycled.

**Comment by immarvin** [comment]
hi @chenglch ,  thanks for the info. 

would you please add a simply notice in the comments of the subroutine, on the lifecycle of the variable holding the return value and the lock acquired? so that developers can be aware of it in the future? thanks

**Comment by chenglch** [comment]
hi @immavin,  I think no need to add comments about this, a developer should understand the scope of a local variable.
