### ISSUE TITLE
utilities required for statelite missing from sles initrd

### ISSUE THREAD

**Issue by aaronknister** [xcat2/xcat-core#2089]
It appears as though the following utilities required for the statelite init script are missing from the initrd generated by the sles geninitrd script:

* bin/cut
* bin/rm
* bin/touch

I think this is as simple as adding those utilities to the lists here:

https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/netboot/sles/genimage#L1794

and here:

https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/netboot/sles/genimage#L1806

I haven't signed the contributors agreement (it's on my to-do list) so I was wondering if somebody else would be willing to make the changes on my behalf?

Thanks!

-Aaron

**Comment by aaronknister** [comment]
Make that usr/bin/cut. This would also require cut to not be fully qualified in the statelite init script:

https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite#L460

**Comment by immarvin** [comment]
hi @penguhyang , would you please take a look at this? please pay attention to the absolute path of ``cut ``,``rm``,``touch`` in the latest sles release, such as sles12,1

thanks

**Comment by immarvin** [comment]
hi @aaronknister ,  the  instructions to sign a CLA are documented in http://xcat-docs.readthedocs.io/en/stable/developers/license/contributors.html

Or if you know you are covered under a Corporate CLA that was signed, can you please give us the corporation name and we can verify. Thanks!

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2093

**Comment by aaronknister** [comment]
hi @immarvin I work for CSRA (formerly CSGov, formerly CSC). I wouldn't be surprised if they have a  corporate CLA in place given how much various folks in the company make use of xCAT.
