### ISSUE TITLE
delete underlying files for ro statelite mounts

### ISSUE THREAD

**Issue by aaronknister** [xcat2/xcat-core#2090]
This depends on the suggestions in #2089.

When one specifies ro children under a tmpfs parent, e.g.:

```
"ALL","/var/","tmpfs",,
"ALL","/var/cache/","ro",,
"ALL","/var/lib/rpm/","ro",,
"ALL","/var/lib/texmf/","ro",,
```
the contents of the child in the tmpfs mount are only removed if the path in tmpfs doesn't match the expected file type (https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite#L462):

```
            if [ "${CHAREND}" = "/" ]; then # it is one directory
                if [ ! -d ${STRPATH} ]; then
                    /bin/rm -rf ${STRPATH}
                    /bin/mkdir ${STRPATH}
                fi
            else
                if [ ! -f ${STRPATH} ]; then
                    /bin/rm -rf ${STRPATH}
                    /bin/touch ${STRPATH}
                fi
            fi
```

by removing the file type tests around the `rm`, `mkdir`, and `touch` we can free up the space that would be occupied by those files/directory trees in tmpfs which depending on the amount of RAM available and the size of those trees could yield a significant increase in usable RAM.

-Aaron

**Comment by immarvin** [comment]
hi @bybai , would you please take a look this ? thanks

**Comment by bybai** [comment]
Hi @aaronknister ,

Thanks your advice, I will look into this in 2.13.1.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2369

**Comment by aaronknister** [comment]
thanks @immarvin and @bybai !
