### ISSUE TITLE
[DEV]restrict site attributes to their valid values on "tabedit" and "chdef" 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2097]
currently, there are many site attribute with restricted valid values. for example, the valid site.nodestatus should only be "n" or "y", however, user may specify it to be "no","yes","1","0","Y", "N"..., we might need to find a way to add a key "validvalues" in the "tabspec" hash in Schema.pm containing the valid values for this variable, if user specified invalid values for this site attribute with either ``tabedit`` or ``chdef``,  the error message should be prompted. 

The validation should better be on the DB access interface.

**Comment by immarvin** [comment]
hi @chenglch  @neo954 , any suggestion on this?

**Comment by gurevichmark** [comment]
Similar checks probably would need to be done for `mkdef`, `chtab`, `tabch`

**Comment by chenglch** [comment]
@immarvin , As DB operation is a set of general function for all the database tables, I think it is not a good idea to add the restriction for only one table at the db level( although I think a ORM layer should to that, but we do not have this level). Another point is that the history code do not check the return code from the subroutine call, so I think this restriction should be put at the DefOBJ level to print the error message.

**Comment by neo954** [comment]
For the `tabedit` command, I prefer to leave this interface freestyle. That means, end user can input any value he/she want. I think the `tabedit` is somewhat an interface aimed to developer. End user may not use this interface.

We can do value validate for command `chdef`.

**Comment by immarvin** [comment]
covered in xcat-inventory validation during import
