### ISSUE TITLE
xcat object naming is too restrictive after sourceforge issue 4675 fix

### ISSUE THREAD

**Issue by billwaj** [xcat2/xcat-core#2100]
sourceforge 4675 bug limits changing characters used in an object name to a-z, A-Z, 0-9. "-" and "_". However P775 bpa and fsp objects get created with a dynamic ip address and then changed to a static ip address.  The 4675 fix does not allow an ip address to be used for the object name because of the "." in the ip address.

Can DBobjectdefs.pm line following:
    # check the new object name specified with -n
be changed from:
    if ($::command eq "chdef" && $::opt_n && ($::opt_n !~ /^[a-zA-Z0-9-_]+$/)) {
to:
    if ($::command eq "chdef" && $::opt_n && ($::opt_n !~ /^[a-zA-Z0-9-_\.]+$/)) {

To allow for the "." character?

**Comment by daniceexi** [comment]
@billwaj This fix was for 2.10 and greater, are your using 2.7 or not?

**Comment by billwaj** [comment]
We are using 2.12.3 right now to support redhat 7.3. We are still using 2.7 for redhat 6 and AIX.
________________________________

**Comment by daniceexi** [comment]
We prefer to convert the IP to be xx-xx-xx-xx format.

Currently, the fsp objects with IP as name are created automatically by lsslp, right?

**Comment by billwaj** [comment]
yes, we use lsslp to create the stanza file from which we create the fsp/bpa objects.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2114

allow the valid ip address in object name.
