### ISSUE TITLE
[openbmc] IP configuration for OpenBMC-based machines (Witherspoon)

### ISSUE THREAD

**Issue by williamspatrick** [xcat2/xcat-core#2108]
The OpenBMC team has been working on our IPMI providers to ensure they are as compliant with IPMI 2.0.  One of the areas being worked is the ip configuration.

When the ip address is configured it is done through a sequence of 'ipmitool set <cmd> <value>' calls.  The IPMI spec itself allows a "transaction" to be created here but ipmitool itself does not seem to properly implement any mechanism to create this transaction.  We have struggled somewhat with defining a sequence that both compliant to IPMI 2.0, fits the behavior of ipmitool, and interoperates with our network stack.  The crux of this issue is in determining when the user is "done" with a sequence like:

```
ipmitool lan set 1 ipaddr ...
ipmitool lan set 1 netmask ...
ipmitool lan set 1 defgw ipaddr ...
```

xCAT has a sequence like this at https://github.com/xcat2/xcat-core/blob/master/xCAT-genesis-scripts/bin/bmcsetup#L285

The design we have landed at is that a user can issue these set ip commands in any order and then issue an 'ipmitool lan set 1 access on' to confirm the sequence and have them applied.  Afterwards, an 'mc reset' is not required in any form.

This design would also seem to match what is recommended here:
https://www.thomas-krenn.com/en/wiki/Configuring_IPMI_under_Linux_using_ipmitool

Does the xCAT team have any issue with this behavior for OpenBMC-based machines?  Is there any other suggestion on how we indicate the completion of the lan-set sequence?

Our OpenBMC discussion on this topic is in this thread: https://lists.ozlabs.org/pipermail/openbmc/2016-November/005507.html

The proposed OpenBMC code change is at:
https://gerrit.openbmc-project.xyz/#/c/822/

**Comment by daniceexi** [comment]
@williamspatrick Good information. xCAT team will discuss it internally first. Thanks.

**Comment by zet809** [comment]
@williamspatrick Hi, patrick, we think it is OK for us to 'ipmitool lan set 1 access on' to activate all the configurations. Just some questions:
1. Does a 'ipmitool lan set 1 ipsrc static' mean the starting of network configuration?
2. If no 'access on', all the configuration after 'ipsrc static' won't be activated? And the original configuration still can be used to access the BMC out-of-band? Is there a timer to record when the configuration start? Won't the network configuration session be time out? What will happen if time out?
3. Which commands are needed between a 'ipsrc static' and 'access on'? Are they all needed to be set? Is it possible to just modify one parameter?

**Comment by zet809** [comment]
Move to next release to trace the discussion.

**Comment by zet809** [comment]
Issue #2810 and #3051 is used to enhance bmcsetup for OpenBMC based servers, so close this one.
