### ISSUE TITLE
`makehosts` add the "default" domainname to host entry if network is disabled

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2112]
If a network is defined in the `networks` table but disabled, the `makehosts` script adds the default domain name to the host entry in `/etc/hosts`. Eg, with the following `networks` table:
```
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"default","10.0.0.0","255.255.255.0","em3","<xcatmaster>","mgmt",,,,,"10.0.0.20-10.0.0.39",,,,,,"default",,
"external","10.0.2.0","255.255.255.0","em1",,,,"10.0.2.1",,,,,,,,,"external",,"1"
```
`makehosts` generates the following line in `/etc/hosts`:
```
10.102.2.99 host-em1 host-em1.default
```

If we enable the "external" network, it now becomes:
```
10.102.2.99 host-em1 host-em1.external
```
which seems better.

`makehosts` should probably add the relevant domain name from the network definition, no matter if the network is disabled or not.

**Comment by immarvin** [comment]
hi @bybai , would you take a look at this?

**Comment by bybai** [comment]
Hi @kcgthb ,
Let me explain the whole thing first:

The disable in networks table means comment out that line.
In your example,  if "external" network is disable, the same meaning with "external" is not exist in networks table. How does makehosts find "external" domain?

If the node ip network is not defined in the networks table, makehosts will append domain from site table for this node. That is to say,  the domain "default" in "host-em1.default" is from site table domain attribute, it is not from the "default" network. 

In your example, domain in site table is the same with domain in "default" network,  so you feel makehosts finds wrong domain.

Actually, if domain in site table is not the same with domain in "default" network, you can see makehosts finds domain from site table.

If there is no value for domain in site table, makehosts will not generate long name, just generate like this:
10.102.2.99 host-em1

So I think makehosts does not need to be enhanced, what is your opinion?

**Comment by kcgthb** [comment]
Hi @bybai 

Thanks for the explanation, I understand the mechanism. But since the "external" network is disabled, shouldn't the generation of the `/etc/hosts` entries be completely disabled for that network? 

Because in the current situation the generated entry is wrong (it's not in the correct domain, as the `10.0.2.x` IP range is not in the `default` domain)

I understand that an IP may be set in the `hosts` table, but which one should take precedence: the host-level IP address, or the network in which this IP is? Users probably expect that disabling a network in the `networks` table would completely disable generation of any information related to that network.

I guess there is a choice to make here:
- either append the correct domain name that matches the IP range, even if it's disabled in `networks`
- or avoid generating entries for IPs in that range altogether.

But the current behavior doesn't seem right, as it generates incorrect entries (with mismatched IP addresses and domain names).

**Comment by bybai** [comment]
Hi @kcgthb ，
I know your description clearly. Our makehosts command manpage is as following, it needs node hostname, node ip and network domain name to work correctly. Why not you add the correct network into networks table?

makehosts updates the /etc/hosts file based on information stored in the xCAT database object definitions.
       The main three bits of information needed are: node hostname, node ip and network domain name.
       The hostname and ip address are specified as part of the node definition.
       The domain value is taken either from the xCAT network definition associated with the node or from the cluster
       site definition.  If you are using multiple domains in the cluster you should add the domain names to the
       appropriate xCAT network definition.

**Comment by kcgthb** [comment]
Hi @bybai 

> The main three bits of information needed are: node hostname, node ip and network domain name.

Right, so if the network is commented in the `networks` table, why take another (wrong) domain name (the one in the `site` table) rather than not adding the entry in `/etc/hosts`? 

I strongly believe it would be much safer to display a warning and not adding the host entry rather than generating incorrect information, don't you think?

**Comment by bybai** [comment]
Hi @kcgthb ,
The domain name in the site table is the default one.  If you do not want to use the default domain in site table during makehosts, you can `chdef -t site domain=` then execute makehosts command, the default domain will not be added in /etc/hosts.

**Comment by bybai** [comment]
Since xcat should have a default one for domain name, domain name in the site table is default one. Close this issue now.
