### ISSUE TITLE
It does not work for command "rinv  all"

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#212]
The command  "rinv  all" does not work on Firestone.
For example:
[root@rhel72mn ~]# rinv  rhel72mn   all
rhel72mn: Error: Unable to identify plugin for this command, check relevant tables: nodehm.mgt;nodehm.power,mgt

**Comment by zet809** [comment]
Fixed with git commit hash num 172ca1c3db2c800411cc498ef2752283b50cef51.
