### ISSUE TITLE
/etc/logrotate.d/xcat file wrong permissions on CentOS 7.2 prevent log rotation

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/xcat-core#2127]
# lsxcatd -v
Version 2.12.2.8 (git commit a1dc8f33798e35a554477157aa6e7fa9ef271275, built Wed Sep 14 13:36:34 EDT 2016)

# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 

Using this version of xCAT on CentOS 7.2 I found that the cron daily logrotate of the xCAT log files was not working.
When I ran logrotate -d (debug mode) it reported that incorrect file permissions were set on the /etc/logrotate.d/xcat file. 

# logrotate -d /etc/logrotate.conf 
reading config file /etc/logrotate.conf
including /etc/logrotate.d
reading config file chrony
reading config file cups
reading config file glusterfs
reading config file httpd
reading config file iscsiuiolog
reading config file libvirtd
reading config file libvirtd.qemu
reading config file mariadb
reading config file mmcesmonitor
reading config file mmprotocoltrace
reading config file named
reading config file numad
reading config file ppp
reading config file psacct
reading config file samba
olddir is now /var/log/samba/old
reading config file srp_daemon
reading config file sssd
reading config file syslog
reading config file wpa_supplicant
Ignoring xcat because of bad file mode.  <===
reading config file yum
[output edited]

Incorrect file permissions:

# ls -la /etc/logrotate.d/xcat 
-rw-rw-r-- 1 root root 466 Oct  4 16:57 /etc/logrotate.d/xcat

The correct file permissions should be 644:

[root@xcat01 ~]# ls -la /etc/logrotate.d/xcat 
-rw-r--r-- 1 root root 466 Oct  4 16:57 /etc/logrotate.d/xcat

Once this change is made logrotate works as expected.
Can you ensure that the correct file permissions (644) are set for /etc/logrotate.d/xcat file in the xCAT code ?

**Comment by whowutwut** [comment]
@dbrajendra  What architecture are you running on?

**Comment by dbrajendra** [comment]
x86_64 (Intel)

**Comment by whowutwut** [comment]
@neo954  if you look into this, this looks like a Lenovo distribution of  xCAT: https://support.lenovo.com/us/en/solutions/HT118877 based on the versioning number...

**Comment by neo954** [comment]
I do not see any packaging problem for the file permission.

  # rpm -qplv xCAT-2.12.2-snap201608180643.x86_64.rpm | grep logrotate
  -rw-r--r--    1 root    root                      442 Aug 18 05:11 /etc/logrotate.d/xcat

**Comment by neo954** [comment]
For the lenovo packaged edition of xCAT. I do see the permission problem mentioned in this issue report. 

    # wget http://xcat.org/lenovo/16b/downloads/xcat-core-2.12.2.8-1-confluent-1.3.1-1-el7.tar.bz2
    --2016-11-11 01:43:40--  http://xcat.org/lenovo/16b/downloads/xcat-core-2.12.2.8-1-confluent-1.3.1-1-el7.tar.bz2
    Resolving xcat.org (xcat.org)... 166.70.135.166
    Connecting to xcat.org (xcat.org)|166.70.135.166|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 37430752 (36M) [application/x-bzip2]
    Saving to: ‘xcat-core-2.12.2.8-1-confluent-1.3.1-1-el7.tar.bz2’

    100%[==========================================>] 37,430,752  1.08MB/s   in 33s

    2016-11-11 01:44:13 (1.07 MB/s) - ‘xcat-core-2.12.2.8-1-confluent-1.3.1-1-el7.tar.bz2’ saved [37430752/37430752]

    # tar xfj xcat-core-2.12.2.8-1-confluent-1.3.1-1-el7.tar.bz2
    # rpm -qplv el7/x86_64/xCAT-2.12.2.8-1.x86_64.rpm | grep logrotate
    warning: el7/x86_64/xCAT-2.12.2.8-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 6ad06410: NOKEY
    -rw-rw-r--    1 root    root                      442 Jun  8 12:18 /etc/logrotate.d/xcat

**Comment by neo954** [comment]
@whowutwut,

This is a packaging issue. What can we do here? Blame on Lenovo?

**Comment by neo954** [comment]
@jjohnson42,

It is great if you have time and can look into this. It seems a packaging problem against Lenovo shipped xCAT rpm.

**Comment by neo954** [comment]
This issue is against Lenovo shipped xCAT. For now, I will close this one.
