### ISSUE TITLE
Briggs & Stratton - xCAT Genesis is unable to recognize any networks other than loopback

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#2128]
When running discovery on Briggs & Stratton nodes, devices get stuck in xCAT genesis shell, unable to run bmcsetup and provision afterwords.  As shown, this is because the only the network device recognized in genesis shell is the loopback

```
[xCAT Genesis running on (none) /var/log]# ip link show | grep -v "^ " | grep "state UP" | awk '{print $2}'
[xCAT Genesis running on (none) /var/log]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

It appears that we may need the  i40e network driver for the network card in the Briggs & Stratton servers  included in genesis somehow in order for discovery to work on these machines.

**Comment by zet809** [comment]
@pdlun92 Hi, Pat, the i40e driver had been included in the genesis base, but it may not new enough to support the hardware.
[root@fs1 xcat]# rpm -aq | grep -i genesis
xCAT-genesis-scripts-ppc64-2.12.4-snap201611070616.noarch
xCAT-genesis-base-x86_64-2.12-snap201607221057.noarch
xCAT-genesis-scripts-x86_64-2.12.4-snap201611070616.noarch
xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch
[root@fs1 xcat]# modinfo /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/kernel/drivers/net/ethernet/intel/i40e/i40e.ko
filename:       /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/kernel/drivers/net/ethernet/intel/i40e/i40e.ko
version:        1.3.4-k
license:        GPL
description:    Intel(R) Ethernet Connection XL710 Network Driver

**Comment by whowutwut** [comment]
@zet809  Thanks,... will take a look based on this info.

**Comment by zet809** [comment]
@whowutwut  and @pdlun92 Any update for this issue? Shall I assign Pat to be the owner of this defect?

**Comment by whowutwut** [comment]
@pdlun92 can you work on this? We have limited access to the machines but we should  verify if we have the correct driver in genesis or if we were in some error mode on fs4...and if not try to add and get time on the machine to test for 2.13..

**Comment by pdlun92** [comment]
I will verify the driver version on genesis and talk to PCM team about borrowing time to verify

**Comment by pdlun92** [comment]
Used a fedora 23 build machine with i40e version 1.5.16 installed to build xCAT genesis base rpm.  I installed this rpm on a Stratton management node.  The correct driver version is found in the directory provided by this rpm.
```
[root@stratton01 genesis]# rpm -U xCAT-genesis-base-ppc64-2.12-snap201611291557.noarch.rpm
[root@stratton01 genesis]# rpm -qpl xCAT-genesis-base-ppc64-2.12-snap201611291557.noarch.rpm | grep i40e
/opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
[root@stratton01 genesis]# modinfo /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
filename:       /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
version:        1.5.16
```
I then ran `mknb`.  
```
[root@stratton01 genesis]# mknb ppc64
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
```
Upon running `nodeset shell` on another Stratton machine the node was able to receive genesis but was unable to boot into it.  I was able to capture the last output of the console
```
  System information
  System configuration
  Language
  Rescan devices
  Retrieve config from URL
 *Exit to shell







 ──────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, h=help
 Info: performing kexec reboot[31734651826,3] OPAL: Trying a CPU re-init with flags: 0x1
[31832139557,3] OPAL: Trying a CPU re-init with flags: 0x1
 -> smp_release_cpus()
spinning_secondaries = 127
 <- smp_release_cpus()
 <- setup_system()
[    1.602243] OFfb vga: enable CONFIG_FB_LITTLE_ENDIAN to support this framebuffer
[33163970796,3] OPAL: Called with bad token 104 !
```

**Comment by zet809** [comment]
@pdlun92  It seems the xCAT-genesis-base-ppc64-2.12-snap201611291557.noarch.rpm you build have some problems.
Here is the files within the xCAT-genesis-base for 3 versions:
1. rpm -qpl xCAT-genesis-base-ppc64-2.12-snap201611291557.noarch.rpm | wc -l
1415               ==>The package is build by you, much more files
2. rpm -qpl xCAT-genesis-base-ppc64-2.12-snap201611230134.noarch.rpm | wc -l
1321               ==> Our latest official package on GSA
3. rpm -qpl xCAT-genesis-base-ppc64-2.12-snap201612010014.noarch.rpm | wc -l
1322               ==> The package I build with i40e 1.5.16 followed the steps you provide

With the 3rd version of xCAT-genesis-base-ppc64, I can boot up node into genesis shell successfully on a stratton server.

The difference between the latest 2 packages are:
247,248d246
< /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/kernel/drivers/net/ethernet/intel/i40e
< /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/kernel/drivers/net/ethernet/intel/i40e/i40e.ko
355a354,356
> /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel
> /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e
> /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko

**Comment by whowutwut** [comment]
@zet809  Did you install use a new install fedora23 or an existing one you have running somewhere... ? I'm wondering what is causing the differences if following the same steps?

**Comment by zet809** [comment]
Use the existing one, 10.3.5.3.

**Comment by whowutwut** [comment]
@pdlun92  Can you verify that the new xCAT-genesis-base can `nodeset shell` to the Briggs & Stratton box?

**Comment by pdlun92** [comment]
Was able to verify with latest xCAT-genesis-base for ppc64 from xcat-dep.
```
[root@stratton01 ~]# yum update xCAT-genesis-base-ppc64*
[root@stratton01 ~]# yum list xCAT-genesis-base-ppc64*
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Installed Packages
xCAT-genesis-base-ppc64.noarch                              2:2.13.0-snap201612051541                               @xcat-dep
[root@stratton01 ~]# rpm -ql xCAT-genesis-base-ppc64-2.13.0-snap201612051541.noarch | grep i40e.ko
/opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
[root@stratton01 ~]# modinfo /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/lib/modules/4.2.3-300.fc23.ppc64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
version:        1.5.16
[root@stratton01 ~]# mknb ppc64
[root@stratton01 ~]# nodeset stratton22 shell
[root@stratton01 ~]# rsetboot stratton22 net
[root@stratton01 ~]# rpower stratton22 boot
```
stratton22 is able to boot in to genesis with correct DHCP IP on NIC.  

Closing this issue
