### ISSUE TITLE
vmstoragemodel doesn't work for VMs on ppc64le hypervisor

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2139]
When using vmstoragemodel to specify the stroagemodel for a diskfile, it will be replaced by 'scsi' for a ppc64 or ppc64le hypervisor. 

```
 # lsdef testvm -i vmstoragemodel
 Object name: testvm
    vmstoragemodel=virtio
```

```
<disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/var/lib/libvirt/images/testvm.sda.qcow2'/>
      <backingStore/>
      <target dev='sda' bus='scsi'/>             ==> Shall be dev='vda' and bus='virtio'
      <alias name='scsi0-0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```
It is wrongly modified within our code when it detect the hypervisor is a ppc64/ppc64le model. Changing to 'ppc64$' only will work.
```
        if ($confdata->{$hyp}->{cpumodel} and $confdata->{$hyp}->{cpumodel} =~ /ppc64/i) {
            $confdata->{vm}->{$node}->[0]->{storagemodel} = "scsi";
        }
```
It is approved that 'virtio' also works for rhev4.x on ppc64le hypervisor, so need more test for vm related functions.

**Comment by gurevichmark** [comment]
@zet809 I am a little confused by this issue. Did you already fix it with the code you identified above and just some testing needed, OR code needs to be changed as you identified above ?

I can not recreate this problem running on the latest xCAT build from Nov 14. When I create a VM with `vmstoragemodel=virtio` the disk information in the `kvm_nodedat`a does not have any `bus` setting.

```
[root@fs2vm100 gurevich]# lsdef mgXgeneratedvm1
Object name: mgXgeneratedvm1
    arch=ppc64le
    cons=kvm
    currchain=boot
    currstate=install rhels7.2-ppc64le-compute
    groups=vm,all
    initrd=xcat/osimage/rhels7.2-ppc64le-install-compute/initrd.img
    ip=10.3.31.215
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.2/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/mgXgeneratedvm1 BOOTIF=42:d1:0a:03:1f:d7  ip=dhcp  inst.cmdline  console=tty0 console=hvc0,115200
    kernel=xcat/osimage/rhels7.2-ppc64le-install-compute/vmlinuz
    mac=42:d1:0a:03:1f:d7|42:e0:0a:03:1f:d7!*NOIP*|42:7c:0a:03:1f:d7!*NOIP*|42:91:0a:03:1f:d7!*NOIP*
    mgt=kvm
    netboot=grub2
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels7.2-ppc64le-install-compute
    serialport=0
    serialspeed=115200
    vmcpus=1
    vmhost=fs2
    vmmemory=4096
    vmnicnicmodel=virtio
    vmnics=br0,br1,br2,br3
    vmstorage=dir:///var/lib/libvirt/images
    vmstoragemodel=virtio
[root@fs2vm100 gurevich]#
```

```
"mgXgeneratedvm1","<domain type=""kvm"">
  <name>mgXgeneratedvm1</name>
  <clock offset=""utc"" />
  <cpu name=""topology"" cores=""1"" sockets=""1"" threads=""1"" />
  <devices>
    <console type=""pty"">
      <target port=""1"" />
    </console>
    <disk device=""disk"">
      <driver name=""qemu"" cache=""none"" type=""qcow2"" />
      <source file=""/var/lib/libvirt/images/mgXgeneratedvm1.sda.qcow2"" />
      <target dev=""sda"" />
    </disk>
    <disk device=""cdrom"" type=""file"">
      <target dev=""sdb"" />
    </disk>
    <graphics autoport=""yes"" listen=""0.0.0.0"" password=""gYQuXF1P4HmwrPBNonpw"" type=""vnc"" />
    <input bus=""usb"" type=""tablet"" />
    <interface type=""bridge"">
      <mac address=""42:d1:0a:03:1f:d7"" />
      <model type=""virtio"" />
      <source bridge=""br0"" />
    </interface>
```

**Comment by zet809** [comment]
@gurevichmark Hi, Mark, you are right that the 'bus' attribute is not in the xml file directly. But, if we use 'vm﻿storagemodel=virtio', the diskname shall be 'vda' rather 'sda'. 

And then, for cdrom device, if  'vm﻿storagemodel=virtio', it will use name 'hd*' which may also don't support on rhev ppc64el platform. We shall also modify it.

**Comment by gurevichmark** [comment]
@zet809 Thank you for information. Some more questions:
* You indicated that if we use `vm﻿storagemodel=virtio`, the diskname shall be `vda` instead of `sda`. Does this mean that it should also be `<source file=""/var/lib/libvirt/images/mgXgeneratedvm1.vda.qcow2"" />` instead of `<source file=""/var/lib/libvirt/images/mgXgeneratedvm1.sda.qcow2"" />` ?
* I am not sure I understand what you mean about cdrom device. Today with `vm﻿storagemodel=virtio`, the cdrom device name is `sdb`. Is this not correct ? What should it be ? `vdb` ?
* Am I correct in assuming that no code changes have yet been done yet for this issue ?

**Comment by zet809** [comment]
@gurevichmark Him Mark:
For 1 and 3. you are right
2. Yes, the cdrom shall be sdb for rhev ppc64le hypervisor. But if our code just use the 'vmstoragemodel=virtio',  the code below will cause cdrom use hdx, which won't work for rhev. 

    my $cdprefix = 'hd';
    # device name vd* doesn't work for CDROM, so delete it.
    #if ($storagemodel eq 'virtio') {
    #    $cdprefix='vd';
    #} els
    if ($storagemodel eq 'scsi') {
        $cdprefix = 'sd';
    }

**Comment by gurevichmark** [comment]
@zet809 Where do we get the hypervisor cpumodel from (`$confdata->{$hyp}->{cpumodel}`) ? Is it in some xCAT db table ?

**Comment by zet809** [comment]
The code section below getting the cpumodel from hypervisor.
    if (($command eq 'mkvm' or $command eq 'chvm' or $command eq 'rpower') and $hypconn) {
        my $nodeinfo = $hypconn->get_node_info();
        if (exists($nodeinfo->{model})) {
            $confdata->{$hyp}->{cpumodel} = $nodeinfo->{model};

**Comment by gurevichmark** [comment]
Thank you. I can see now that this data comes from hyprevisor's  `virsh nodeinfo`

**Comment by gurevichmark** [comment]
@zet809 After a long vacation break :-) I am looking at working on this issue again.

So to refresh my memory:

- The changes that we discussed above: if we use 'vm﻿storagemodel=virtio', the diskname shall be 'vda' rather than 'sda', does it matter if `cpumodel` is `ppc64` or `ppc64le` ? OR should these changes be made only when `cpumodel` is `ppc64` ?
- What are the possible valid values for `vm﻿storagemodel` attribute? I could node find it in xCAT documentation.
- Why in the example you show at the beginning of the issue, there is a line `<target dev='sda' bus='scsi'/>`, but when I create a VM on my system the `kvm_nodedata` does not have `bus` attribute on that line ?

**Comment by zet809** [comment]
@gurevichmark Hi, Mark, sorry for the delayed response. My answers are:
1. shall be 'vda' no matter what the cpumodel is. It means for ppc64, ppc64le, x86_64, it shall be vda if using 'vm﻿storagemodel=virtio'.
2. I think it can be 'scsi' or 'virtio', but 'scsi' will be used by default.
3. Oh, maybe my mistake, you can see the 'bus' attribute after powering on the VM.

**Comment by gurevichmark** [comment]
@zet809 a few more questions:
- I am a little confused what you meant when you said "*Changing to 'ppc64$' only will work.*" in the initial description of this problem.
- To me it seems the logic should be as follows. Please correct if wrong:
   - if vm﻿storagemodel=virtio then prefix is "**vd**" no matter what cpu model is
   - if vmstoragemodel=scsi then prefix is "**sd**" no matther what cpu model is
   - if vmstoragemodel is not set, we should default to "**scsi**" for ppc64 and ppc64le cpumodel, which will result in "**sd**" prefix
- But what about x86_64 cpumodel ? What should be the default in that case if vmstoragemodel is not set ?
- Are there any settings that should result in "**hd**" prefix ?
- Looking at the kvm.pm code I see these lines:
   ```
    my $cdprefix = 'hd';
    
    # device name vd* doesn't work for CDROM, so delete it.
    #if ($storagemodel eq 'virtio') {
    #    $cdprefix='vd';
    #} els
    if ($storagemodel eq 'scsi') {
        $cdprefix = 'sd';
    }
    ```
    Should I uncomment that, so that cdrom entry is there with "**vd**" prefix when vmstoragemodel=virtio ? If I do not uncomment it, the cdrom prefix will be "**hd**", when storagemodel=virtio or anything not scsi.

**Comment by zet809** [comment]
1. If I remember correctly, the ppc64 hypervisor doesn't support virtio. You can verify that with pkvm2.x
2. Correct
3. For the vmstoragemodel, it doesn't related to the ARCH of the hypervisor. So for x86_64, it can also use the sd* by default
4. In fact, hd* is for another kind of bus, maybe ata. Currently, most servers using scsi bus for disk IO.
5. I remember just uncomment the code above will cause other issue. Maybe CDROM can not be a vd* device.

**Comment by gurevichmark** [comment]
Pull request #2421 fixes this issue.
After some testing it appears that `ppc64` and `ppc64le` support `vmstoragemodel=virtio`.
Therefore, when `vmstoragemodel=virtio` the disk prefix will be set to `vd*` no matter what `cpumodel` of the hypervisor host is.
If `vmstoragemodel=virtio` is not set, default to `vmstoragemodel=scsi`, which will result in disk prefix to be set to `sd*`

**Comment by gurevichmark** [comment]
@zet809 Pull request was merged. Can you close this issue if you feel it is resolved.

**Comment by zet809** [comment]
I have verified, thx a lot!
