### ISSUE TITLE
makedns fails due to perl-Net-DNS installed in different lib directory - paths need updating within xCAT (or xcat-dep needs to replace packages)

### ISSUE THREAD

**Issue by CJCShadowsan** [xcat2/xcat-core#2141]
Not sure whether this is specifically an issue within xcat-dep, or xcat-core.

I noted an issue with latest xCAT, pretty much exactly like:

http://permalink.gmane.org/gmane.comp.clustering.xcat.user/1993

In that we installed a version of perl-Net-DNS on our CentOS7.2 system, and it installed into:
```
/usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi/Net/DNS.pm
```
However at startup xcat logs:
```
 xcat[3000]: Error loading module /opt/xcat/lib/perl/xCAT_plugin/ddns.pm  ...skipping
```
perl -I on it showed that it couldn't find the directory:

```
perl -I /opt/xcat/lib/perl/ -c /opt/xcat/lib/perl/xCAT_plugin/ddns.pm
Can't locate Net/DNS.pm in @INC (@INC contains: /opt/xcat/lib/perl/
/usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at
/opt/xcat/lib/perl/xCAT_plugin/ddns.pm line 4.
BEGIN failed--compilation aborted at /opt/xcat/lib/perl/xCAT_plugin/ddns.pm
line 4.
```

locating it shows:
```
/usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi/Net/DNS.pm
```
Which isn't the location that xcat expects (as per the perl -I output).

We followed the thread within the mailing list, and took their temporary solution to 'downgrade' to perl-Net-DNS-0.72-5.el7.x86_64, which installs in a different location.

The issue is...

...this package used to be submitted as a package in xcat-dep - and is no longer supplied.

[(http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64/]http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64/
)
As such:

Can we update xcat to use the appropriate environment to look in paths that include `/usr/lib/perl5/site_perl` and `/usr/lib/perl5/vendor_perl` respectively?

Either that, or include perl-Net-DNS that installs into a path you're expecting I guess.

Thanks,

Chris

**Comment by zet809** [comment]
@bybai Hi, yuan sir, pls take a look at this issue?

**Comment by immarvin** [comment]
hi @CJCShadowsan ,  the variable @INC includes the paths for perl to look for modules, you can try to add  "/usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi" to @INC by 
````
export PERL5LIB="/usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi/:/usr/lib/perl5/site_perl/5.18.2"
````
then make sure that the paths has been added into @INC by running ``perl -V``
````
perl -V
...
  Built under linux
  Compiled at Aug 18 2016 06:19:53
  %ENV:
    PERL5LIB="/usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi/:/usr/lib/perl5/site_perl/5.18.2"
    PERL_BADLANG="0"
  @INC:
    /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi/
    /usr/lib/perl5/site_perl/5.18.2
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5
````
 
then check whether your problem is solved, if yes, you can add the commands "export ..." into the /etc/profile of your server.

xCAT only ships perl-Net-DNS for the linux releases which does not ship perl-Net-DNS in the installation iso, which is obviously not the case for CentOS 7.2

**Comment by bybai** [comment]
Hi @immarvin ,
If this works, and if we do not add any changes in our packages, we can add this in our docs.

**Comment by CJCShadowsan** [comment]
@immarvin - shouldn't this solution be bundled into the install of xCAT to add this include if not present considering it needs perl-Net-DNS?

Asking people to set it manually every time it's installed is going to grow tiresome for people.

**Comment by immarvin** [comment]
hi @CJCShadowsan , would you please provide the release number of "perl-Net-DNS" you installed with ``rpm -qi perl-Net-DNS``? how did you install it?

**Comment by immarvin** [comment]
no response, close this first, please reopen it if need

**Comment by CJCShadowsan** [comment]
Sorry, totally missed this.

The version of perl-Net-DNS that xcat-dep installs is 0.80 - the version I have to roll back to in order to get perl-Net-DNS to work is 0.72 (bundled in with the OS).

**Comment by CJCShadowsan** [comment]
Btw - I can't re-open this issue, because a contributor closed it - if you could re-open this for me, that'd be great.

**Comment by core2lee** [comment]
This issue is still present in xCAT 2.13.8-snap201711020715, CentOS Linux release 7.4.1708. 

perl-Net-DNS-0.80-1.x86_64 installed from xcat-deps, this caused: 
[root@mgmt01 ~ ]# makedns
Error: Unsupported request

Downgrade to perl-Net-DNS-0.72 is still a valid workaround.

**Comment by CJCShadowsan** [comment]
Does it not just make sense if xcat-dep is installing libraries into a particular lib directory that xcat-dep's installer sets the paths and INCs correctly along with environment variables? That way it shouldn't even matter where it's installed?

Just a thought.

**Comment by whowutwut** [comment]
@immarvin @bybai can you take another look at this one and how we could fix it?

**Comment by immarvin** [comment]
hi @core2lee , it is strange that "perl-Net-DNS-0.80-1.x86_64" shipped in xcat-dep is installed on your 
CentOS Linux release 7.4.1708 MN, since we just shipped  "perl-Net-DNS-0.80-1.x86_64" for sles12
````
[root@c910f03c05k21 xcat-dep]# find . -name "perl-Net-DNS*"
./sles12/ppc64le/perl-Net-DNS-0.80-1.ppc64le.rpm
./sles12/x86_64/perl-Net-DNS-0.80-1.x86_64.rpm
````

please make sure whether you added the correct repo path(for centos7.x, it should be xcat-dep/rh7/x86_64/) under /etc/yum.repo.d when you installed xcat, 

please run the following commands to confirm this
````
#yum info -v perl-Net-DNS-0.80-1.x86_64|grep -i "From repo"
From repo   : XXXXXX
#yum repo info XXXXXX
````

**Comment by immarvin** [comment]
hi @CJCShadowsan , the same question for you...., please check why the  perl-Net-DNS-0.80 for sles12 shipped in xcat-dep is installed on your MN

**Comment by bybai** [comment]
Hi @CJCShadowsan , we do not recommend install ./sles12/x86_64/perl-Net-DNS-0.80-1.x86_64.rpm on centos system , I will close this issue, if you have comments, contact me, thanks.
