### ISSUE TITLE
ac97 sound driver in kvm.pm is causing problems when deploying RHEV

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2143]
We put the sound driver back into the KVM xml in Issues https://github.com/xcat2/xcat-core/issues/723, but looks like in my latest testing of RHEV on ppc64le, it causes some problems when doing a rpower on the VM.  

I'm not sure if we are missing something on the hypervisor , or it's just not supported in ppc64le...  

```
Error message: mgXgeneratedvm1: Error: internal error: qemu unexpectedly closed the monitor: 
2016-11-09T18:43:13.699936Z qemu-kvm: -device AC97,id=sound0,bus=pci.0,addr=0x2: 'AC97' is
not a valid device model name.
```

**Comment by whowutwut** [comment]
I am putting into 2.12.4, but we can move this to 2.13.  I wanted to see what the team felt about this pull request that I created  https://github.com/xcat2/xcat-core/pull/2144

**Comment by immarvin** [comment]
hi @whowutwut , would you please provide the xml of the VM? it is interesting that  in out code, the sound device is "ac71" in lower case but from the message you pasted , it became``-device AC97``


thanks

**Comment by whowutwut** [comment]
I think that's just the error message that comes out.  For a diskful VM , the kvm_nodedata contains the following: 
```
#node,xml,comments,disable
"mgXgeneratedvm1","<domain type=""kvm"">
  <name>mgXgeneratedvm1</name>
  <clock offset=""utc"" />
  <cpu name=""topology"" cores=""1"" sockets=""1"" threads=""1"" />
  <devices>
    <console type=""pty"">
      <target port=""1"" />
    </console>
    <disk device=""disk"">
      <driver name=""qemu"" cache=""none"" type=""qcow2"" />
      <source file=""/var/lib/libvirt/images/mgXgeneratedvm1.sda.qcow2"" />
      <target dev=""sda"" />
    </disk>
    <disk device=""cdrom"" type=""file"">
      <target dev=""sdb"" />
    </disk>
    <graphics autoport=""yes"" listen=""0.0.0.0"" password=""y1pr9YCrgJH9su4a8JGU"" type=""vnc"" />
    <input bus=""usb"" type=""tablet"" />
    <interface type=""bridge"">
      <mac address=""42:1a:c0:a8:17:64"" />
      <model type=""virtio"" />
      <source bridge=""br0"" />
    </interface>
    <sound model=""ac97"" />
    <video><model type=""vga"" vram=""8192"" />
    </video>
  </devices>
  <features>
<acpi></acpi>
    <apic></apic>
    <pae></pae>
  </features>
  <memory>8388608</memory>
  <os>
    <boot dev=""network"" />
    <boot dev=""hd"" />
    <type>hvm</type>
  </os>
  <uuid>82dd206c-bfa7-e611-91cd-421ac0a81764</uuid>
  <vcpu>1</vcpu>
</domain>
```

I can leave it there today... it's defined under fs4 , VM mgXgeneratedvm1

**Comment by whowutwut** [comment]
@zet809  I saw you merged my proposal to remove the ac97 driver from ppc64le.   If we want to investigate supporting the ac97, let's open another issue to track it or allow customers to request support in the future.
