### ISSUE TITLE
Support for PXE boot over Omnipath networks - UPDATED 

### ISSUE THREAD

**Issue by CJCShadowsan** [xcat2/xcat-core#2147]
Hi,

Either i'm missing something or I can't get a node to PXE boot over both Infiniband and GbE.

I can get it to PXE boot over one, or the other, but not both at the same time (by manipulation of the 'master' variable within site:

```
"master","10.142.0.1",,
```

If I change this to 10.143.0.1 it works on IB (labelled ipofa). If it's 10.142.0.1 it's GbE. I can't seem to specify both.

 specifying 2 separate individual DHCP networks in the networks table:

```
"xcat_pdu","10.144.98.0","255.255.255.0","eno1.1004",,,,,,,,,,,,"1004",,,
"xcat_nw","10.142.0.0","255.255.0.0","eno1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.240.1-10.142.255.253",,,,,"1001","cluster.local",,
"xcat_switch","10.144.96.0","255.255.255.0","eno1.1006",,,,,,,,,,,,"1006",,,
"xcat_fpc","10.144.99.0","255.255.255.0","eno1.1003",,,,,,,,,,,,"1003",,,
"ipofa","10.143.0.0","255.255.0.0","ib0","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.240.1-10.143.255.253",,,,,,,,
"xcat_mgmt","10.144.0.0","255.255.128.0","eno1.1002",,,,,,,,,,,,"1002",,,
"xcat_cons","10.144.97.0","255.255.255.0","eno1.1005",,,,,,,,,,,,"1005",,,
```

and specifying dhcpinterfaces as both eno1 and ib0:

```
"dhcpinterfaces","xcat|eno1,ib0",,
```

Am I missing something? Or is this a feature that could do with being added?

**Comment by daniceexi** [comment]
Please set the xcatmaster attribute for specific node to replace site.master.
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: Chris Coates <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc:Subject: [xcat2/xcat-core] Support for PXE boot over multiple networks (#2147)Date: Fri, Nov 11, 2016 10:57 PM 
Hi,
Either i'm missing something or I can't get a node to PXE boot over both Infiniband and GbE.
I can get it to PXE boot over one, or the other, but not both at the same time (by manipulation of the 'master' variable within site:
"master","10.142.0.1",,
If I change this to 10.143.0.1 it works on IB (labelled ipofa). If it's 10.142.0.1 it's GbE. I can't seem to specify both.
specifying 2 separate individual DHCP networks in the networks table:
"xcat_pdu","10.144.98.0","255.255.255.0","eno1.1004",,,,,,,,,,,,"1004",,,"xcat_nw","10.142.0.0","255.255.0.0","eno1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.0.1","10.142.240.1-10.142.255.253",,,,,"1001","bc4.local",,"xcat_switch","10.144.96.0","255.255.255.0","eno1.1006",,,,,,,,,,,,"1006",,,"xcat_fpc","10.144.99.0","255.255.255.0","eno1.1003",,,,,,,,,,,,"1003",,,"ipofa","10.143.0.0","255.255.0.0","ib0","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.0.1","10.143.240.1-10.143.255.253",,,,,,,,"xcat_mgmt","10.144.0.0","255.255.128.0","eno1.1002",,,,,,,,,,,,"1002",,,"xcat_cons","10.144.97.0","255.255.255.0","eno1.1005",,,,,,,,,,,,"1005",,,
and specifying dhcpinterfaces as both eno1 and ib0:
"dhcpinterfaces","xcat|eno1,ib0",,
Am I missing something? Or is this a feature that could do with being added?

**Comment by CJCShadowsan** [comment]
Tried that...

I get DHCP for the node - but then i'm presented with a 'no more network devices' error from iPXE and it doesn't boot past that point.

Tried with the netboot as both xnba and pxe - same result.

tcpdump on the management node shows that it retrieves xnba.efi... But then nothing.

Console logs from the node:

```
  Station IP address is 10.143.240.68
  NBP filename is xcat/xnba.efi
  NBP filesize is 139200 Bytes
 Downloading NBP file...

  Succeed to download NBP file.

 Downloading NBP file...

  Succeed to download NBP file.
xNBA initialising devices...ok


xCAT Network Boot Agent
iPXE 1.0.3-131028 (d603e) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: HTTP HTTPS iSCSI DNS TFTP EFI
No more network devices
xNBA initialising devices...ok


xCAT Network Boot Agent
iPXE 1.0.3-131028 (d603e) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: HTTP HTTPS iSCSI DNS TFTP EFI
No more network devices
```

**Comment by daniceexi** [comment]
Please monitor the /var/log/messages for dhcp request log and /var/log/httpd/access_log for http log when the node booting. Show out the logs you can discovered.
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: Chris Coates <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Xiao Peng Wang/China/IBM@IBMCN, Comment <comment@noreply.github.com>Subject: Re: [xcat2/xcat-core] Support for PXE boot over multiple networks (#2147)Date: Sun, Nov 13, 2016 6:12 PM 
Tried that...
I get DHCP for the node - but then i'm presented with a 'no more network devices' error from iPXE and it doesn't boot past that point.
Tried with the netboot as both xnba and pxe - same result.
tcpdump on the management node shows that it retrieves xnba.efi... But then nothing.
Console logs from the node:
  Station IP address is 10.143.240.68  NBP filename is xcat/xnba.efi  NBP filesize is 139200 Bytes Downloading NBP file...  Succeed to download NBP file. Downloading NBP file...  Succeed to download NBP file.xNBA initialising devices...okxCAT Network Boot AgentiPXE 1.0.3-131028 (d603e) -- Open Source Network Boot Firmware -- http://ipxe.orgFeatures: HTTP HTTPS iSCSI DNS TFTP EFINo more network devicesxNBA initialising devices...okxCAT Network Boot AgentiPXE 1.0.3-131028 (d603e) -- Open Source Network Boot Firmware -- http://ipxe.orgFeatures: HTTP HTTPS iSCSI DNS TFTP EFINo more network devices

**Comment by CJCShadowsan** [comment]
Surely enough:

```
Nov 15 14:39:03 mgmt01 dhcpd: DHCPOFFER on 10.143.240.68 to ff:00:00:00:00:00:02:00:00:01:57:00:11:75:01:01:78:47:6b via ib0
Nov 15 14:39:18 mgmt01 dhcpd: DHCPOFFER on 10.143.240.68 to ff:00:00:00:00:00:02:00:00:01:57:00:11:75:01:01:78:47:6b via ib0
Nov 15 14:40:12 mgmt01 dhcpd: DHCPOFFER on 10.143.240.68 to ff:00:00:00:00:00:02:00:00:01:57:00:11:75:01:01:78:47:6b via ib0
Nov 15 14:40:16 mgmt01 dhcpd: DHCPREQUEST for 10.143.240.68 (10.143.0.1) from ff:00:00:00:00:00:02:00:00:01:57:00:11:75:01:01:78:47:6b via ib0
Nov 15 14:40:16 mgmt01 dhcpd: DHCPACK on 10.143.240.68 to ff:00:00:00:00:00:02:00:00:01:57:00:11:75:01:01:78:47:6b via ib0
Nov 15 14:40:16 mgmt01 in.tftpd[18125]: RRQ from 10.143.240.68 filename xcat/xnba.efi
Nov 15 14:40:16 mgmt01 in.tftpd[18126]: RRQ from 10.143.240.68 filename xcat/xnba.efi
Nov 15 14:40:16 mgmt01 in.tftpd[18127]: RRQ from 10.143.240.68 filename xcat/xnba.efi
```

The node picks up an address on the ib0 network... Manages to load xcat/xnba.efi...

...Then there are no requests for anything inside the httpd logs on 10.143.x.

I guess the question is... What happens inbetween that? It should still have a 10.143.x address right by the time it tries to load the kernel:
```
[root@mgmt01 nodes]# cat compute002.uefi
#!gpxe
chain http://${next-server}/tftpboot/xcat/elilo-x64.efi -C /tftpboot/xcat/xnba/nodes/compute002.elilo
```

```
[root@mgmt01 nodes]# cat compute002.elilo
default="xCAT"
delay=0

image=/tftpboot/xcat/osimage/computeimage/kernel
   label="xCAT"
   initrd=/tftpboot/xcat/osimage/computeimage/initrd-stateless.gz
   append="imgurl=http://10.143.0.1:80//install/netboot/centos7/x86_64/computeimage/rootimg.cpio.gz XCAT=10.143.0.1:3001 NODE=compute002 FC=0  console=tty0 console=ttyS0,115200 BOOTIF=%B"
```

I can guarantee it doesn't get to the point where it attempts to load this based upon the httpd logs.

Right now, the question mark is being placed solely at xnba.efi - As it seems to indicate it attempts to initialise devices...

...And we know that we had an IP in pxe mode prior to loading xnba.efi, but once inside xnba it says there aren't any network devices available.

Note that these nodes use intel omnipath cards. 

The question is:

what does xnba do?

**Comment by CJCShadowsan** [comment]
I believe this is going to link to:

[xNBA is missing Intel Omnipath drivers](https://github.com/xcat2/xNBA/issues/1)

**Comment by immarvin** [comment]
hi @CJCShadowsan , xnba is a xCAT patched ipxe(gpxe). we did not verify the os provision over Intel Omnipath IB card, is Intel Omnipath supported in latest ipxe?

**Comment by jjohnson42** [comment]
We are still working some adapter firmware issues with Intel.

In theory, omnipath should be providing a suitable SNP implementation, supporting adapters using a generic UEFI driver rather than building in the various drivers.

In terms of the specific drivers as a possible alternative, iPXE current does not have specific drivers for Omnipath (though it does have them for Mellanox).

**Comment by CJCShadowsan** [comment]
Yeah - I attempted to boot a compiled snponly.efi that dropped me to a shell.

The network card simply doesn't work... It attempts to send out a DHCP request that never gets answered.

And if you specify a static address? Tcpdump says the traffic coming in to the master is... IPX.

As such, that makes omnipath cards unusable as a bootable target within xCAT. As soon as it picks up an xnba/ipxe image the network card stops working as a bootable device.

**Comment by arif-ali** [comment]
On this note,

I am at SC16, and planning to go to the Omni-Path User group, and going to grab the Omni-Path Architect, so hopefully, I should be able to get any assistance on this

**Comment by immarvin** [comment]
no plan to support ominipath
