### ISSUE TITLE
RHEL7.x CN can not get IP by dhcp if MN's dhcp stop long time and start again.

### ISSUE THREAD

**Issue by chudegao** [xcat2/xcat-core#2161]
The steps are as below:
1. Stop dhcpd on MN long time(more than one day)
2. Reboot CN (or remove the dhcp lease file in cn to simulate this)
3. Start dhcpd on MN
The CN still can not get IP by dhcp.

Check the CN network service is failed and no dhclient process.

**Comment by immarvin** [comment]
if the "dhclient" process is alive, it will try to renew the latest existed dhcp lease, if the lease is not available , it will re-send the dhcp discover and look for a available dhcp server. The problem found by @chudegao  is that the network.service is in "failed" state and there is no alive dhclient on the node.

when the dhclient is alive, the network.service status is like this:
````
[root@c910f03c05k27 ~]# systemctl status network
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: active (running) since Wed 2016-11-09 03:17:57 UTC; 1 weeks 0 days ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/network.service
           └─1495 /sbin/dhclient -H c910f03c05k27 -1 -q -lf /var/lib/dhclient/dhclient-eth0.leases -pf /var/run/dhclient-eth0....

````

The network.service status is like this in the problematic system:
````
[root@c910f03c05k21 ~]# systemctl status network -l
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-10-20 04:30:23 EDT; 3 weeks 6 days ago
     Docs: man:systemd-sysv-generator(8)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
````


the 
hi @xuweibj , would you please take a look at this?

**Comment by neo954** [comment]
I think this issue is some kind of "work-as-design". When `dhclient` failed to get a DHCP response for a certain of time, it may go to die eventually. After that, there is no `dhclient` running on the compute node any more. Even the `dhcpd` daemon on the management node is started again, the compute node will not get IP address. Since the `dhclient` run on compute node was already gone.

**Comment by neo954** [comment]
And I think this issue is a not an xCAT related problem as well. And it is not RHEL related, or Linux related problem.

This issue can be recreated in a common DHCP environment. A regular DHCP client usually behavior in this way. This is the way how DHCP works.

**Comment by immarvin** [comment]
hi @chudegao , 
the network.service on rh7 is like this:
````
[root@c910f03c05k27 ~]# systemctl status network -l
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: active (running) since Thu 2016-11-17 06:08:42 UTC; 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4638 ExecStop=/etc/rc.d/init.d/network stop (code=exited, status=0/SUCCESS)
  Process: 5236 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           └─5449 /sbin/dhclient -H c910f03c05k27 -1 -q -lf /var/lib/dhclient/dhclient-eth0.leases -pf /var/run/dhclient-eth0.pid eth0
````

notice the "-1" option:
````
       -1     Try to get a lease once.  On failure exit with code 2.  In DHCPv6 this sets the maximum duration of the initial exchange to timeout (from dhclient.conf with a default of sixty seconds).
````
this means that the "dhclient" will exit on success/failure during "service network start".  If you want to keep it active, you need to specify "PERSISTENT_DHCLIENT=yes" in "/etc/sysconfig/network"
````
[root@c910f03c05k27 ~]# cat /etc/sysconfig/network
NETWORKING=yes
PERSISTENT_DHCLIENT=yes
````
 
with this option, the network.service is like this:
````
[root@c910f03c05k27 ~]# systemctl status network -l
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: active (running) since Thu 2016-11-17 06:18:35 UTC; 6min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6597 ExecStop=/etc/rc.d/init.d/network stop (code=exited, status=0/SUCCESS)
  Process: 6769 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           └─6978 /sbin/dhclient -H c910f03c05k27 -q -lf /var/lib/dhclient/dhclient-eth0.leases -pf /var/run/dhclient-eth0.pid eth0

Nov 17 06:18:05 c910f03c05k27.test.com systemd[1]: Starting LSB: Bring up/down networking...
Nov 17 06:18:06 c910f03c05k27.test.com network[6769]: Bringing up loopback interface:  [  OK  ]
Nov 17 06:18:06 c910f03c05k27.test.com network[6769]: Bringing up interface eth0:
                                                                                Nov 17 06:18:35 c910f03c05k27.test.com network[6769]: Determining IP information for eth0... done.
Nov 17 06:18:35 c910f03c05k27.test.com network[6769]: [  OK  ]
Nov 17 06:18:35 c910f03c05k27.test.com systemd[1]: Started LSB: Bring up/down networking.
[root@c910f03c05k27 ~]#
````

**Comment by immarvin** [comment]
hi @neo954 , you are right, the behavior of network.service is configurable, the default behavior is that dhclient  will exit when the network service is started or failed

**Comment by chudegao** [comment]
Thanks @immarvin , @neo954 . Good analysis and I think it make sense. As it's uncommon negative case. I think we can keep current design.

**Comment by daniceexi** [comment]
@immarvin do we want to make persistent active of dhclient on CN as default setting?

**Comment by immarvin** [comment]
hi @daniceexi , I think we'd better keep the default behavior of the operating system. 

one problem I can see to keep persistent active:

if a machine has a batch of NICs, but the application only need several nics up. If we make dhclient persistent, all the unused NICs will keep on sending DHCP DISCOVER broadcasts.  In a large cluster, this might be a problem.

**Comment by immarvin** [comment]
hi @chudegao , if you are ok with the ticket, please close it

**Comment by immarvin** [comment]
Talked with @chudegao , this issue has been resolved, close it

**Comment by neo954** [comment]
Thanks, @immarvin
