### ISSUE TITLE
xcat is failing to run postbootscripts on stateful node.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2167]
[root@c460mgt01 ~]# lsxcatd -v
Version 2.12.4 (git commit 64ec2d41285d9a8770d8d9ef909f251ecbb5100b, built Thu Nov 10 23:59:02 EST 2016)

There seems to be a disconnect from the /opt/xcat/xcatpostinti1, which is looking for RUNBOOTSCRIPT=
and the contents of the /xcat/mypostscript which contains RUNBOOTSCRIPTS=yes.

To demonstrate this:

we have setup our site table to run the "postbootscripts" on every state-full boot with the following value in the site table:

```
Object name: clustersite
    runbootscripts=yes
```

We had noticed that after making a change to the lsdef the route for a stateful node, that when we rebooted, the setroute would not get run again and the route value would wrong on the node.

suspecting that we the postscripts were not getting called we added the following lines to "/opt/xcat/xcatpostinit1"
```
echo "\nRB: xcatpostinit" >/dev/console
exec 1>/dev/console
exec 2>&1
set -x
```

and then proceeded to reboot the node.

that resulted in the following data on the console:

```
RB: xcatpostinit
[Thu Nov 17 18:42:33 2016]+ '[' -f /opt/xcat/xcatinfo ']'
[Thu Nov 17 18:42:33 2016]++ grep XCATSERVER /opt/xcat/xcatinfo
[Thu Nov 17 18:42:33 2016]++ cut -d= -f2
[Thu Nov 17 18:42:33 2016]+ XCATSERVER=10.1.0.1
[Thu Nov 17 18:42:33 2016]+ '[' -f /xcatpost/mypostscript ']'
[Thu Nov 17 18:42:33 2016]++ grep NODESTATUS= /xcatpost/mypostscript
[Thu Nov 17 18:42:33 2016]++ awk -F = '{print $2}'
[Thu Nov 17 18:42:33 2016]+ NODESTATUS=
[Thu Nov 17 18:42:33 2016]+ '[' -f /xcatpost/mypostscript ']'
[Thu Nov 17 18:42:33 2016]++ grep RUNBOOTSCRIPT= /xcatpost/mypostscript
[Thu Nov 17 18:42:33 2016]++ awk -F = '{print $2}'
[Thu Nov 17 18:42:33 2016]+ RUNBOOTSCRIPT=
[Thu Nov 17 18:42:33 2016]+ case $1 in
[Thu Nov 17 18:42:33 2016]+ '[' -f /opt/xcat/xcatinfo ']'
[Thu Nov 17 18:42:33 2016]++ grep REBOOT /opt/xcat/xcatinfo
[Thu Nov 17 18:42:33 2016]++ cut -d= -f2
[Thu Nov 17 18:42:33 2016]+ REBOOT=TRUE
[Thu Nov 17 18:42:33 2016]+ '[' TRUE = TRUE -a -r /opt/xcat/xcatdsklspost -a '' = 1 ']'
[Thu Nov 17 18:42:33 2016]+ '[' TRUE = TRUE -a NODESTATUS '!=' n ']'
[Thu Nov 17 18:42:33 2016]+ /xcatpost/updateflag.awk 10.1.0.1 3002 'installstatus booted'
```

What is curious here is the trace of the following lines:
```
# check for the REBOOT specified in xcatinfo to run post boot scripts on reboot 
  if [ -f /opt/xcat/xcatinfo ]; then
    REBOOT=`grep 'REBOOT' /opt/xcat/xcatinfo |cut -d= -f2`
  fi
  # if the xcatdsklspost file exists and this is a reboot - run xcatdsklspost with a mode of 6
  if [ "$REBOOT" = "TRUE" -a -r /opt/xcat/xcatdsklspost -a "$RUNBOOTSCRIPT" = "1" ]; then
      /opt/xcat/xcatdsklspost 6
  elif [ "$REBOOT" = "TRUE" -a "NODESTATUS" != "n" ]; then
      /xcatpost/updateflag.awk $XCATSERVER 3002 "installstatus booted"
  else
```

The value of $RUNBOOTSCRTIPT is NULL so it bypassess running the boot script..

Looking at the contents of /xcatpost/mypostscripts we see:
```
[ralphbel@c460login02 xcat]$ grep BOOT /xcatpost/mypostscript
RUNBOOTSCRIPTS='yes'
export RUNBOOTSCRIPTS
```

There seems to be a disconnect from the /opt/xcat/xcatpostinti1, which is looking for RUNBOOTSCRIPT=
and the contents of the /xcat/mypostscript which contains RUNBOOTSCRIPTS=yes.

attached are the files:
[xcatposts.zip](https://github.com/xcat2/xcat-core/files/598742/xcatposts.zip)

**Comment by ralphbellofatto** [comment]
I believe the problem  is in this file:

/install/postscripts/xcatpostinit1.install

which is part of the xcat-core rpm.

for a temporary fix made the following change in /install/postscripts/xcatpostinit1.install, 

change ALL occurances of RUNBOOTSCRIPT with RUNBOOTSCRIPTS
And change this line to:
```
  if [ "$REBOOT" = "TRUE" -a -r /opt/xcat/xcatdsklspost -a "$RUNBOOTSCRIPTS" = "'yes'" ]; then
```

It was very important to put the extra ' characters in the "'yes'" otherwise it would not compare.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2169
