### ISSUE TITLE
[FVT]2.11: xCAT-* rpm installation on sles11.3 returns  rsyslogd.pid warning message, please remove it.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#218]
Please remove following warning message when xCAT-* rpm installation. 

Installing: xCAT-test-4:2.11-snap201509230241 [done]
Installing: xCAT-buildkit-4:2.11-snap201509230242 [done]
Installing: xCAT-client-4:2.11-snap201509230241 [done]
Installing: xCAT-server-4:2.11-snap201509230241 [done]
Installing: xCAT-2.11-snap201509230242 [done]
Additional rpm output:
/var/tmp/rpm-tmp.12746: line 21: /var/run/rsyslogd.pid: No such file or director                                                                                        y
Restarting xCATd ..done
Running '/opt/xcat/sbin/mknb ppc64', triggered by the installation/update of xCA                                                                                        T-genesis-scripts-ppc64 ...
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
The 'mknb ppc64' command completed successfully.

**Comment by tingtli** [comment]
The same warning message on rh7.1
/var/tmp/rpm-tmp.Si23VX: line 21: /var/run/rsyslogd.pid: No such file or directory

**Comment by whowutwut** [comment]
@daniceexi  should we change this to pending and let @tingtli  close it out after verification?

**Comment by daniceexi** [comment]
@whowutwut I did not close this issue. Looks like the github found the relevant between issue #218 and pull request #242, so when I merged the #242, the #218 was closed automatically.

**Comment by whowutwut** [comment]
oh, interesting... maybe need to rethink our use of this :)
