### ISSUE TITLE
[fvt]2.13 testcase confignics need modified on sles environment 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2184]
Env:sles11.4
c910f02c01p14:/opt/xcat/share/xcat/tools/autotest/result # uname -a
Linux c910f02c01p14 3.0.101-63-ppc64 #1 SMP Tue Jun 23 16:02:31 UTC 2015 (4b89d0c) ppc64 ppc64 ppc64 GNU/Linux
c910f02c01p14:/opt/xcat/share/xcat/tools/autotest/result # 

Build:c910f02c01p14:~ # lsxcatd -v
Version 2.13 (git commit 6653dfdc6acc292cf7ccd8e053263009a6ea960a, built Mon Nov 21 06:15:37 EST 2016)
c910f02c01p14:~ # 
How to reproduce:
```
1.In test cases:
   RUN:if [ "sles" = "ubuntu" ];then xdsh c910f02c02p28 cat /etc/network/interfaces.d/eth4; else xdsh   c910f02c02p28 cat /etc/sysconfig/network*/ifcfg-eth4; fi
    [if [ "sles" = "ubuntu" ];then xdsh c910f02c02p28 cat /etc/network/interfaces.d/eth4; else xdsh c910f02c02p28 cat /etc/sysconfig/network*/ifcfg-eth4; fi] Running Time:1 sec
   RETURN: rc = 1
   OUTPUT:
   c910f02c02p28: cat: /etc/sysconfig/network*/ifcfg-eth4: No such file or directory
   CHECK:output =~ 100.1.0.100     [Failed]

2.This is sles env,so the networks folder is:
   c910f02c01p14:~ # cat /etc/sysconfig/network/ifcfg-eth0  
   DEVICE=eth0
   BOOTPROTO=dhcp
   STARTMODE=onboot
   DHCLIENT_PRIMARY_DEVICE=yes

---------------------> need to modify confignics releated cases for sles environment 

```

**Comment by tingtli** [comment]
@junxiawang
I use /etc/sysconfig/network*/ to cover the different sles and rhels.  * means both /etc/sysconfig/network/  and other format which * could represent.

The failure is because of bug #2183. So the files for eth4 is not create. Then the cat for this file failed. I will close this bug.
