### ISSUE TITLE
[fvt]test case:reg_linux_diskfull_installation_flat need to modify how to check ntp service ready or not on sles environment

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2186]
Env:sles
c910f02c01p14:~ # uname -a
Linux c910f02c01p14 3.0.101-63-ppc64 #1 SMP Tue Jun 23 16:02:31 UTC 2015 (4b89d0c) ppc64 ppc64 ppc64 GNU/Linux

Build:c910f02c01p14:~ # lsxcatd -v
Version 2.13 (git commit 6653dfdc6acc292cf7ccd8e053263009a6ea960a, built Mon Nov 21 06:15:37 EST 2016)

How to reproduce:
```
1.In autotest result log:
   RUN:xdsh c910f02c02p28 service ntpd status
   [xdsh c910f02c02p28 service ntpd status] Running Time:1 sec
   RETURN: rc = 1
   OUTPUT:
   c910f02c02p28: service: no such service ntpd
2.In sles env:
   c910f02c01p14:~ # service ntpd status
  service: no such service ntpd
  c910f02c01p14:~ # 
3.we could use ntpq to monitor ntp ready or not:
  c910f02c01p14:~ # ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
  ==============================================================================
  *LOCAL(0)        .LOCL.          10 l    2   64  377    0.000    0.000   0.001
```

**Comment by junxiawang** [comment]
@tingtli Now in our installation testcase we do not verify ntp server ready or not? So I do not know should we need to modify the ntp verification for installation testcase.

**Comment by robin2008** [comment]
won't fix, if we want it open it in `xcat2-task-management`
