### ISSUE TITLE
[fvt] nodeset node diskless image failed for could not find the diskless image

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2188]
Env:sles ubuntu
Build:c910f02c01p14:~ # lsxcatd  -v
Version 2.13 (git commit 6653dfdc6acc292cf7ccd8e053263009a6ea960a, built Mon Nov 21 06:15:37 EST 2016)
c910f02c01p14:~ #

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2189
