### ISSUE TITLE
[CUSTOMER] Clearly define the method for configuration of RAID using xCAT .tmpl files

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2209]
In the current releases of xCAT the partitioning file is changed and should be pulled out of the .tmpl file.   Need to document the proper way for customers to configure a simple RAID1.  

- ship a template script for RAID1 in xCAT
- Inform the users how to find the persistent disk name
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/persistent_naming.html

```
# ls -l /dev/disk/by-path | egrep "sdj|sdk" | grep -v part
lrwxrwxrwx 1 root root  9 Nov  2 02:35 pci-0003:0a:00.0-ata-1.0 -> ../../sdj
lrwxrwxrwx 1 root root  9 Nov  2 02:35 pci-0003:0a:00.0-ata-2.0 -> ../../sdk
```

Remove the references to the old partitioning scheme in the redhat template file to avoid confusion. What's the impact on SLES, Ubuntu?

**Comment by whowutwut** [comment]
@zet809  we need to address this for 2.13 release.

**Comment by immarvin** [comment]
hi @whowutwut , I think we should recommend user to use the "partitionfile" of "osimage" for customization raid/partition during provision instead of template. We can ship some  basic partition script so that user can use directly or create customized partition file based on it.

**Comment by zet809** [comment]
Hi, @whowutwut and @immarvin It seems to me that the configuring RAID is a feature request for xCAT, I don't think it is and will be a common feature for xCAT. Why not put the script example onto a public repo such as https://github.com/xcat2 for user to download freely, and in our readthedoc document there is an advanced topic to describe this function?
Then, if there is a new requirement, we can add a new script and don't need to rebuild xcat. And user can upload their own user case onto the public repo, and shared to other users.

**Comment by zet809** [comment]
I have created a repo https://github.com/xcat2/scripts to store the scripts for special user cases.

**Comment by immarvin** [comment]
how about naming the repo to "xcat-extensions"? since this repo is to store all the stuff for specific use cases contributed either by xCAT dev team and customers.

**Comment by immarvin** [comment]
the draft of the documentation https://github.com/xcat2/xcat-core/pull/2211

**Comment by whowutwut** [comment]
@zet809  I don't necessarily agree that it's a new feature request, because in the compute.tmpl files have been provided by xCAT for a long time.  In there, we provide samples for RAID.  If we change the way we are passing the partitioning scheme to using linuximage.partitionfile, then we need to clean up the default partition file that we ship, so that we do not confuse the end user.  

Also from the issue opened by the customer, it seems like doing RAID before 2.12.4 worked.. so we broke something in 2.12.4 that I think we should understand and resolve for 2.13... 

By leaving it in the template file, I would assume that we can just un-comment the sections for RAID and it will work.. but that is not the case here as we have seen in the doc changes.  So I think at a minimum, we need to do the following. 

1. Verify the procedure to configure RAID1 (across 2 disks) and tell the user how to find the persistent disk name..  @immarvin has started this with #2211 

2.  Looking at this file: https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/install/rh/compute.rhels7.tmpl 

    - Line 40, XCAT_PARTITION_END should be moved to the bottom of all the partition samples. 
    - Line 42-70, if we do not support RAID in the .tmpl file. remove it and have comments that point to    linuximage.partitonfile
    -  Lines 73-83, this comment section does not make sense to me , maybe I do not understand it, but line 83 is commented out.  If we do not support this, we should not keep it commented out whre the user can uncomment it...  

If we were changing the behavior, should we have created a new .tmpl file instead of using the compute.rhels7.tmpl?

**Comment by whowutwut** [comment]
I'd like to also add that the disk on the RHEL 7.3 OS side is named differently on Firestone/Minsky... 

On Firestone, the disks are sdj and sdk.  But on Minsky, they are sda and sdb...

Garrison is sda/sdb...
```
[root@frame23cn17 ~]# ls -ltr /dev/disk/by-path | egrep "sda|sdb" | grep -v part
lrwxrwxrwx 1 root root  9 Nov 28 06:23 pci-0005:04:00.0-ata-2.0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Nov 28 06:23 pci-0005:04:00.0-ata-1.0 -> ../../sda
```
Firestone is sdj/sdk
```
[root@frame45cn10 ~]# ls -ltr /dev/disk/by-path | egrep "sdk|sdj" | grep -v part
lrwxrwxrwx 1 root root  9 Nov 24 09:19 pci-0003:0a:00.0-ata-2.0 -> ../../sdk
lrwxrwxrwx 1 root root  9 Nov 24 09:19 pci-0003:0a:00.0-ata-1.0 -> ../../sdj
```

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2211 and https://github.com/xcat2/xcat-extensions/pull/1
