### ISSUE TITLE
Environment variable set for a kit used in all postscripts

### ISSUE THREAD

**Issue by LudovicEnault** [xcat2/xcat-core#2219]
Hello,

When a kit is configured with an environment variable (for example ESSL kit: http://xcat-docs.readthedocs.io/en/stable/advanced/kit/hpc/software/essl.html), the variable is exported in all postscripts. The expectation would be that the variable is set only for the kit, not for all the kits or postscripts.

A simple script to check is the following:
xcatmn # cat /install/postscripts/env.sh
#!/bin/bash
/usr/bin/env | grep ^IBM_ESSL

xcatmn# updatenode compute01 env.sh
compute01: xcatdsklspost: downloaded postscripts successfully
compute01: Tue Nov 29 16:20:47 CET 2016 Running postscript: env.sh
compute01: IBM_ESSL_LICENSE_ACCEPT=yes
compute01: Postscript: env.sh exited with code 0
compute01: Running of postscripts has completed.

xcat version is 2.12.3-snap201609290802.ppc64le, OS is RedHat

Ludo

**Comment by LudovicEnault** [comment]
P.S.: Same behavior with xCAT 2.12.4

**Comment by cxhong** [comment]
it's required new design, will move to 2.14.

**Comment by robin2008** [comment]
No further working on kit management, won't fix it.
