### ISSUE TITLE
Provide a way to reset the IPMI based OpenPower BMCs back to factory through xCAT

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2226]
Create a way to reset the IPMI based BMC back to DHCP from within xCAT command

The recommended steps are: 
```
ipmitool-xcat -H ${BMC_IP} -U ${BMC_USER} -P ${BMC_PASS} chassis power off 
ipmitool-xcat -H ${BMC_IP} -U ${BMC_USER} -P ${BMC_PASS} raw 0x32 0xBA 00 00
ipmitool-xcat -H ${BMC_IP} -U ${BMC_USER} -P ${BMC_PASS} raw 0x32 0x66
```

Some things to consider
- do we need to define bmc node definitions? What happens if they have one defined?
- How does this flow into the hardware discovery process?
- nodeset offline, should that reset the BMC?

**Comment by zet809** [comment]
@whowutwut Hi, Victor, in fact, our command 'rspconfig <node> ip=dhcp' is used to have BMC get IP through DHCP. I think the command list above is used to reset the BMC back to factory status.
For the question above, here are my thought:
1. No need to define bmc node, can run again a host node definition directly. If have one BMC node defined, implement this command means teh BMC node useless any more.
2. In fact, for a customer environment, they may not do hardware discovery against a server that had been done. But really need to do, it can be run after the dynamic range for BMC is ready to use.
3. Don't think so, nodeset just need to work for the host rather than BMC.

**Comment by whowutwut** [comment]
@zet809  Thanks for that, let me take a closer look at the rspconfig command you mentioned above.

**Comment by whowutwut** [comment]
@zet809 I ran this today and it seemed to work OK. The compute side does not power off when we run the command. Should we consider powering off the compute side. What would be the use case to reset the BMC and leave compute side on...  

My thoughts is that this machine will be physically moved and maybe the user wants to reset to make discovery easier when installed again...

**Comment by zet809** [comment]
Hi, @whowutwut In more of cases, BMC and host are two independent modules, the configuration of BMC shall not affect the running of the host. If the firmware of BMC is changed, and host need to get some data from firmware, I do think the host shall be rebooted.
For your thought, after think it over, I agree powering off the server is what shall do next. But the option 'ip=dhcp' shall be modified to 'back_to_factory', what is your idea?

**Comment by whowutwut** [comment]
@zet809  i'm not sure I understand the last question.   `ip=dhcp` seems to be a good option that would restore the BMC back to "factory" settings, meaning wipe out any configuration and restore network settings to DHCP mode.

**Comment by whowutwut** [comment]
FYI these commands above does not work for Supermicro OpenPower.  Have we verified this in the past when doing Supermicro briggs & Stratton support..  will try and validate soon.

**Comment by zet809** [comment]
@whowutwut Hi, victor, I don't think we had verified this function for Supermicro servers. This is a standard ipmi command, works for x86_64 server and OpenPOWER server.

**Comment by whowutwut** [comment]
I just verified on a Briggs machine that `rspconfig <> ip=dhcp` does in fact work.  It put the BMC back into DHCP and got an IP address 
```
[root@fs4 ~]# bmcdiscover --range 50.0.0.13 -u ADMIN -p ADMIN
50.0.0.13,8001-22C,130122A,ADMIN,ADMIN,mp,bmc
```

Will close this out.
