### ISSUE TITLE
[FVT]Failed to generate osimage definiton for sles11.4-x86_64-statelite-compute after copycds 

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#2231]
Description: 
Failed to include the ``sles11.4-x86_64-statelite-compute`` after run ```copycds /SLES-11-SP4-DVD-x86_64-GM-DVD1.iso```

Test ENV. : xCAT 2.13 on Nov 30 build in x86 sles11.4

**Comment by whowutwut** [comment]
I think we should enable this for the 2.13 release so it is available for test/dev if needed.

**Comment by caomengmeng** [comment]
Works well now, so close it
