### ISSUE TITLE
Need to require a certain version of xCAT-genesis-base with the recent changes 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2239]
It has come to my attention that we have made some changes in the xCAT-genesis-base that should force users to make sure that the correct xCAT-genesis-base is in sync with the code and hard stop with the dependencies if the xcat-dep repo is not updated. 

So for example, in 2.12.4, we moved function from dhclient-scripts -> doxcat.  With this move, xCAT-genesis-scripts RPM should require a version of xCAT-genesis-base.  

Looking at the xCAT-genesis-base versioning, we are only doing things like... 2.12-snapYYYYMMDD...  Are we able to do a `Requires: xCAT-genesis-base-%{arch} > 2.12-snapYYYYMMDD` ? 

Perhaps this is more fuel to standardize a numbering convention for xCAT RPMs...

**Comment by whowutwut** [comment]
After doing some initial investigation, The initial confusion about the customer potentially running the wrong code base was incorrect.  They are running the 2.12.4 xcat-core and xcat-dep.  

The 2.12.4 GA was Nov 11, 2016 and the commit made by @xuweibj  in https://github.com/xcat2/xcat-core/pull/2064 was merged  on Nov 4, so  I thought the changes were in place for 2.12.4 release....  However, there is nothing in our process to identify and automatically spawn the rebuild of xCAT-genesis-base.  So we never re-spun the xCAT-gensis-base and so the code was old, but not matching the repo.   (FYI @zet809 .. need to think about a better way here..) 

Regardless... doing more investigation, the current way we are naming the RPM does NOT allow us to use versioning to specify a certain level of requires for xCAT-genesis-base.   This is a problem.

I created a dummy rpm that has the following: 
```
$ cat dummy.spec | grep Requires
Requires:	xCAT-genesis-base-ppc64 >= 2.13.0-0
```

Then on a test node, simply using rpm and yum prevents this from being installed
```
[root@fs2vm112 ~]# rpm -ihv dummy-0.1.dev52-0.noarch.rpm 
error: Failed dependencies:
	xCAT-genesis-base-ppc64 >= 2.13.0-0 is needed by dummy-0.1.dev52-0.noarch
[root@fs2vm112 ~]# yum install dummy-0.1.dev52-0.noarch.rpm 
Examining dummy-0.1.dev52-0.noarch.rpm: dummy-0.1.dev52-0.noarch
Marking dummy-0.1.dev52-0.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package dummy.noarch 0:0.1.dev52-0 will be installed
--> Processing Dependency: xCAT-genesis-base-ppc64 >= 2.13.0-0 for package: dummy-0.1.dev52-0.noarch
--> Finished Dependency Resolution
Error: Package: dummy-0.1.dev52-0.noarch (/dummy-0.1.dev52-0.noarch)
           Requires: xCAT-genesis-base-ppc64 >= 2.13.0-0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

If I take the `xCAT-genesis-base` from 2.12.4.. .IT has the following provides: 
```
[root@fs2vm112 ~]# rpm -qip --provides ./xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch.rpm 
warning: ./xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
Name        : xCAT-genesis-base-ppc64
...
xCAT-genesis-base-ppc64 = 1:2.12-snap201610250931
```

Using yum to install WILL resolve the dependency!??!
```
[root@fs2vm112 ~]# yum install ./dummy-0.1.dev52-0.noarch.rpm ./xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch.rpm 
Examining ./dummy-0.1.dev52-0.noarch.rpm: dummy-0.1.dev52-0.noarch
Marking ./dummy-0.1.dev52-0.noarch.rpm to be installed
Examining ./xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch.rpm: 1:xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch
Marking ./xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package dummy.noarch 0:0.1.dev52-0 will be installed
---> Package xCAT-genesis-base-ppc64.noarch 1:2.12-snap201610250931 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================================================================================
 Package                                  Arch                    Version                                   Repository                                                              Size
=========================================================================================================================================================================================
Installing:
 dummy                                    noarch                  0.1.dev52-0                               /dummy-0.1.dev52-0.noarch                                              0.0  
 xCAT-genesis-base-ppc64                  noarch                  1:2.12-snap201610250931                   /xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch                  159 M

Transaction Summary
=========================================================================================================================================================================================
Install  2 Packages

Total size: 159 M
Installed size: 159 M
Is this ok [y/d/N]:
```

After investigating this more... it turns out that the strange numbering with the `1:` in front of the version is caused by the `Epoch` keyword in the spec file. When I added a Provides tag, I saw two versions: 

```
[root@fs2vm112 ~]# rpm -qip --provides xCAT-genesis-base-ppc64-2.13.0-0.noarch.rpm
Name        : xCAT-genesis-base-ppc64
Epoch       : 1
Version     : 2.13.0
Release     : 0
...
xCAT-genesis-base-ppc64 = 1:2.13.0-0
xCAT-genesis-base-ppc64 = 2.13.0-0
```

So I think we need to remove the Epoch keyword.  

We could potentially keep the "snap..." naming convention but this will not allow us to create intermediate xcat-dep builds, but tie it only to releases of xCAT 

What i mean here is that..
xCAT 2.13.0: Requires xCAT-genesis-base >= 2.13.0
if no change...
xCAT 2.13.1: Requires xCAT-genesis-base >= 2.13.0
if change...
xCAT 2.13.2: Requires xCAT-genesis-base >= 2.13.2

I guess this would achieve what we are looking for....

**Comment by zet809** [comment]
@whowutwut Hi, Victor, you are right the pull request made by Xu Wei shall be put in the xcat-genesis-base for 2.12.4 release. 
Do you think we shall support this function in this release?

**Comment by zet809** [comment]
@whowutwut Hi, Victor, the pull request #2284 can fix this issue that depend on a specified version and higher. The requires shall be like ">= Epoch:Version".

**Comment by whowutwut** [comment]
@zet809 Thanks for that.  I did not try that one out.    I will close this as I have tried the current release candidate versions and it does pull in the genesis-base
