### ISSUE TITLE
Modified mlnxofed_ib_install to support MLNX_OFED_LINUX-3.1-0.1.7-rhel7.2-ppc64le

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#224]
Enclosed please find two scripts.

Put `mlnx_ofed_install` in the postbootscript attribute of the node, and `mlnx_ofed_install` will call `mlnxofed_ib_install`.

[mlnxofed_ib_install.txt](https://github.com/xcat2/xcat-core/files/3311/mlnxofed_ib_install.txt)
[mlnx_ofed_install.txt](https://github.com/xcat2/xcat-core/files/3312/mlnx_ofed_install.txt)

**Comment by hu-weihua** [comment]
I have provided a new version of mlnxofed_ib_install. could you review it?
pull requests number is 240

**Comment by neo954** [comment]
Already fixed. I will close this one.
