### ISSUE TITLE
[FVT]:setupntp failed on sles12.1 diskless node

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2248]
xCAT 2.13. SLES12.1
Steps to reproduce
1. Config mn and define cn
2. define setup ntp on cn
```
c910f03c17k22:~ # lsdef -l c910f03c17k24
Object name: c910f03c17k24
    arch=ppc64le
    cons=kvm
    currchain=boot
    currstate=netboot sles12.1-ppc64le-compute
    groups=all
    id=24
    initrd=xcat/osimage/sles12.1-ppc64le-netboot-compute/initrd-stateless.gz
    kcmdline=imgurl=http://c910f03c17k22//install/netboot/sles12.1/ppc64le/compute/rootimg.cpio.gz XCAT=c910f03c17k22:3001 quiet NODE=c910f03c17k24 FC=0 ip=dhcp  BOOTIF=42:88:0a:03:11:18 console=tty0 console=hvc0,115200n8r
    kernel=xcat/osimage/sles12.1-ppc64le-netboot-compute/kernel
    mac=42:88:0a:03:11:18
    mgt=kvm
    monserver=c910f03c17k23
    netboot=grub2
    nfsserver=c910f03c17k23
    os=sles12.1
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,setupntp
    profile=compute
    provmethod=sles12.1-ppc64le-netboot-compute
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=failed
    statustime=12-02-2016 02:01:54
    tftpserver=c910f03c17k22
    updatestatus=failed
    updatestatustime=12-02-2016 02:35:39
    vmcpus=4
    vmhost=c910f03c17
    vmmemory=6144
    vmnicnicmodel=virtio
    vmnics=brenP3p9s0f0
    vmstorage=phy:/dev/mapper/vdiskvg03-vdisk01n24
    xcatmaster=c910f03c17k22
```

3. Diskless boot CN and find ntp is not started on cn
```
c910f03c17k24:/var/log/xcat # service ntpd status
ntpd.service - NTP Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled)
   Active: inactive (dead)
     Docs: man:ntpd(1)
```

4. Check the log
```
Fri Dec  2 01:11:21 EST 2016 Running postbootscript: setupntp
inactive
/usr/sbin/rcntpd ntptimeset
/usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
Fri Dec  2 01:11:22 EST 2016 postbootscript setupntp return with 1
```

**Comment by zet809** [comment]
@cxhong Hi, casandra, will you pls help to take a look at this issue?
My findings are:
1.  It seems the following command failed within setupntp script:
# rcntpd ntptimeset
Time could not be synchronized
 2. If adding a outside ntp server for ntp.conf on either MN or CN, it will succeed. So, it seems to be the ntp server on Management Node is not configured correctly.
Once the MN is ready (For sles, I mean "rcntpd ntptimeset" can return correctly), the setupntp on CN can work smoothly without any change. 
So, it must be the issue the ntp server on Management Node.

**Comment by neo954** [comment]
On SLES 12.1, `ntp-4.2.8p4-1.3.ppc64le` was shipped. We met NTP bugzilla bug number 2965 [1].  `ntpd` doesn't synchronize to local clock anymore in version 4.2.8p4. NTP version 4.2.8p5 fixed this bug [2].

[1] https://bugs.ntp.org/show_bug.cgi?id=2965
[2] https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ChangeLog-stable

Thus, this is an upstream bug. Which is not xCAT related issue. Case closed.

**Comment by daniceexi** [comment]
So we should add a restriction in the 2.13 release notes for sles12.1.

**Comment by tingtli** [comment]
@zet809  I think we have the same issue on sles11.4.  The version is ntp-4.2.8p2-2.18
If you add restriction, please also add sles11.4

**Comment by cxhong** [comment]
assign to @zet809 for add restriction in the 2.13 release notes

**Comment by immarvin** [comment]
the same issue can be recreated on sles12.2, which shippes ntp-4.2.8p8-14.1.ppc64le

````
Thu Dec  8 06:03:11 EST 2016 Running postscript: setupntp
Failed to get properties: Connection timed out
Failed to get properties: Connection timed out
/usr/sbin/rcntpd ntptimeset
/usr/sbin/rcntpd ntptimeset
/usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
/usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
Postscript: setupntp exited with code 1
Thu Dec  8 06:04:26 EST 2016 postscript setupntp return with 1
````

**Comment by immarvin** [comment]
is this a typo?

````
 85     if [ "$NTPSERVERS" = "&lt;xcatmaster&gt;" ] || [ "$NTPSERVERS" = "<xcatmm
    aster>" ]; then
 86         echo "server $master" >>$conf_file
 87     else
 88         for i in $(echo $NTPSERVERS | tr ',' ' ')
 89         do
 90                 echo "server $i" >>$conf_file
 91                 master=$i
 92         done
 93     fi
 94 else
````

**Comment by daniceexi** [comment]
truly, it's a bug I think.

**Comment by neo954** [comment]
Hello @zet809, @tingtli @immarvin and all,

Please notice the NTP bugzilla bug number 2965 [1] I mentioned above is for NTP version 4.2.8p4 **ONLY**.

To make things clear, this bug does not exist for NTP version prior to 4.2.8p3. See the first comment of the bug report, I quoted below`... This still used to work in 4.2.8p3. ...`. And this bug was fixed in NTP version 4.2.8p5. As mentioned in the NTP official change log [2].

[1] https://bugs.ntp.org/show_bug.cgi?id=2965
[2] https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ChangeLog-stable

**Comment by neo954** [comment]
If we still have problem on SLES 11.4 or SLES 12.1. We may need to open another bug.

**Comment by neo954** [comment]
Looked into the NTP problem on SLES 12.2. The local clock worked fluently, without any problem. But it may take up to ten minutes to get its first clock synchronize after the `ntpd` started up.

    # ntpq -pn
         remote           refid      st t when poll reach   delay   offset  jitter
    ==============================================================================
     *127.127.1.0     .LOCL.          10 l   46   64  377    0.000    0.000   0.000

**Comment by immarvin** [comment]
hi @neo954 , on your latest comment, how did you run setupntp, "update node -P" or in postscript during provision?

**Comment by neo954** [comment]
@immarvin, on the management node, run `makentp`. And then wait.

**Comment by tingtli** [comment]
@neo, i have a question, why the remote is  *127.127.1.0 ?

**Comment by cxhong** [comment]
The clock synchronization needs more than 10 mins is affected by CONFIG_RTC_SYSTOHC.
````
CONFIG_RTC_SYSTOHC:
If you say yes here, the system time (wall clock) will be stored in the RTC specified by RTC_HCTOSYS_DEVICE approximately every 11 minutes if userspace reports synchronized NTP status.
``````
on sles12.2 test system:

`````
# zcat /proc/config.gz | grep RTC | grep SYS
# CONFIG_RTC_HCTOSYS is not set
CONFIG_RTC_SYSTOHC=y
CONFIG_RTC_SYSTOHC_DEVICE="rtc0"
CONFIG_RTC_INTF_SYSFS=y
```````

**Comment by neo954** [comment]
@cxhong, On RHEL 6.x, 7.x, Ubuntu 14.04.x, 16.04.x, every Linux distro has `CONFIG_RTC_SYSTOHC=y` in its kernel settings. It is the default kerne settings. This discovery explains nothing.

**Comment by cxhong** [comment]
well, that's what I read from online.  
anyway,  you can google "linux kernel 11 minute mode" to see if something is useful

**Comment by cxhong** [comment]
#2328 had few fixes for makentp and setupntp,  but sync time for MN still needs around 11 mins and CN seems fast, like between 3 to 5 mins from ntpq -p command
````
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l   48   64  377    0.000    0.000   0.000
````````

**Comment by tingtli** [comment]
@cxhong  Doest that mean we need to wait about 10 minutes after CN's provision, then run setupntp?

**Comment by cxhong** [comment]
That's what I saw on the SLES system:
1) took 5 to 11 mins to sync the time for MN after run makentp on MN
2) took 3 to 5 mins to sync the time for CN after run "updatenode CN -P setupntp" on MN

**Comment by neo954** [comment]
@cxhong, I think what you saw on the SLES system is just the normal behavior of ntp daemon.

**Comment by neo954** [comment]
Did not get update for this issue for more than one month. I will close this issue. Please feel free to reopen this issue if needed.
