### ISSUE TITLE
[FVT] Failed to get node message in /var/lib/dhcpd/dhcpd.leases after run makedhcp -a

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#2251]
Using latest daily build to run diskfull installation by automation
```
[root@c910f04x12v02 result]# lsxcatd -v
Version 2.13 (git commit c44f3c60d6a6f57cda9e1c58a285c294dfe4ca26, built Thu Dec  1 09:00:50 EST 2016)
```
After run ``makedhcp -a`` and waiting for 10 seconds, failed to get CN node message in ``/var/lib/dhcpd/dhcpd.leases``
```
1. RUN:makedhcp -a
2. RUN:sleep 10
3. RUN: cat /var/lib/dhcpd/dhcpd.leases|grep c910f04x12v04
RETURN: rc = 1
CHECK:output =~ c910f04x12v04   [Failed]
```
But after more than 10 seconds the node message is shown.

**Comment by whowutwut** [comment]
Does `makedhcp -a` trigger the compute nodes to renew a lease?

**Comment by caomengmeng** [comment]
@whowutwut 
It is happened when trying to install diskful flat in CN, all previous steps are below:
```
RUN: rpower SN
RUN:chdef -t node -o CN servicenode= monserver=MN nfsserver=MN tftpserver=MN  xcatmaster=MN
RUN: rmvm CN -f -p  &&  mkvm CN -s 20G
RUN:makedns -n
RUN:makeconservercf
RUN:cat /etc/conserver.cf | grep CN
RUN:sleep 20
RUN:chtab key=extntpservers site.value=""
RUN:chtab key=ntpservers site.value="<xcatmaster>"
RUN:makentp
RUN:makedhcp -n
RUN:makedhcp -a
RUN:sleep 10
```

It seems to be a timing issue, the CN is booted finally. And the CN node message is shown later in /var/lib/dhcpd/dhcpd.leases.
As no build during the last 2 days, will continue to trace this issue this week with automation test result.

**Comment by immarvin** [comment]
hi @caomengmeng , what's the check ``3. RUN: cat /var/lib/dhcpd/dhcpd.leases|grep c910f04x12v04
`` for? validate the ``makedhcp -a`` ?

**Comment by whowutwut** [comment]
:+1:  @immarvin

**Comment by junxiawang** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2270

**Comment by caomengmeng** [comment]
works well now
