### ISSUE TITLE
[DEV]Install ubuntu 14.04.3 will fail on IBM Power S822LC if RH7.x is installed before

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#229]
2 issue:
1. ubuntu can not list SATA disk used by Power S822LC in /dev/disk/by-path/*
2. RH7.x will use xfs as its filesystem type, the current ubuntu partition scripts can not read it.

**Comment by whowutwut** [comment]
Pull request #323

**Comment by zet809** [comment]
Fixed with git commit hash num: a176c26f3f3d3e8452c74d6f3e7977b767eb3b08
