### ISSUE TITLE
xcat-ui rpm?

### ISSUE THREAD

**Issue by djzort** [xcat2/xcat-core#2293]
Code is still there and being update: https://github.com/xcat2/xcat-core/tree/master/xCAT-UI

I am curious why there is no xcat-ui rpm in http://xcat.org/files/xcat/repos/yum/latest/xcat-core/ ?

**Comment by daniceexi** [comment]
The code is there for zVM usage. Common xCAT version has stopped the support of xcat-ui functions.

**Comment by whowutwut** [comment]
To manually build the xCAT UI, after cloning the xcat-core repo...

```
cd xcat-core
./makerpm xCAT-UI
```

there will be some compiler.jar file dependency that may cause the build to fail. @chuckbrazie @bybai  I know where this compiler.jar is in our build environment but how do external users obtain this? 
```
c

**Comment by bybai** [comment]
hi @whowutwut ,
We do not support xcat-ui now, I think we can close this.

**Comment by bybai** [comment]
Since xcat does not support xcat-ui， close this issue.
