### ISSUE TITLE
xcatprobe subcommands are not consistent in their naming

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2304]
The current list of sub commands are not consistent in their naming convention with a dash or underscore...

- detect_dhcpd
- switch-macmap
- code_template 

Please correct while this is still beta.

**Comment by hu-weihua** [comment]
@whowutwut , this issue has been fixed by PR #2309. Could you help to verify it? thanks.

**Comment by hu-weihua** [comment]
@whowutwut , could you help to verify this issue? if there is not problem, could you close this issue? thanks.

**Comment by whowutwut** [comment]
Looks good with the 1/5/17 build, Thanks!
