### ISSUE TITLE
[FVT]Failed to install SN in sles12.2 p8le and X86

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#2322]
Description: Failed to setup SN with latest daily build in sles12.2 p8le and X86
```
c910f03c17k22:/var/log # lsxcatd -v
Version 2.13.1 (git commit c7eb8b8025d9b8c815b3630461294e5af9803747, built Thu Dec 15 06:15:40 EST 2016)
```

In sles 12.3 p8le and X86_64, the SN is booted, but xcatd is not running.
```
RUN:lsdef -l c910f04x12v03 | grep status

[lsdef -l c910f04x12v03 | grep status] Running Time:1 sec
RETURN rc = 0
OUTPUT:
    status=booted
    statustime=12-22-2016 00:39:08
CHECK:rc == 0	[Pass]
CHECK:output =~ booted	[Pass]

RUN:xdsh c910f04x12v03 date

[xdsh c910f04x12v03 date] Running Time:0 sec
RETURN rc = 0
OUTPUT:
c910f04x12v03: Thu Dec 22 05:42:56 EST 2016
c910f04x12v03: Warning: Permanently added 'c910f04x12v03,10.4.12.3' (ECDSA) to the list of known hosts.

CHECK:rc == 0	[Pass]
CHECK:output =~ \d\d:\d\d:\d\d	[Pass]

RUN:xdsh c910f04x12v03 "ps -ef |grep xcatd"

[xdsh c910f04x12v03 "ps -ef |grep xcatd"] Running Time:1 sec
RETURN rc = 0
OUTPUT:
c910f04x12v03: root     13518 13510  0 05:42 ?        00:00:00 bash -c export NODE=c910f04x12v03; export LANG= LC_CTYPE="POSIX" LC_NUMERIC="POSIX" LC_TIME="POSIX" LC_COLLATE="POSIX" LC_MONETARY="POSIX" LC_MESSAGES="POSIX" LC_PAPER="POSIX" LC_NAME="POSIX" LC_ADDRESS="POSIX" LC_TELEPHONE="POSIX" LC_MEASUREMENT="POSIX" LC_IDENTIFICATION="POSIX" LC_ALL=POSIX PERL_BADLANG=0 ; ps -ef |grep xcatd; export DSH_TARGET_RC=$?; echo ":DSH_TARGET_RC=${DSH_TARGET_RC}:"
c910f04x12v03: root     13545 13518  0 05:42 ?        00:00:00 grep xcatd
c910f04x12v03: :DSH_TARGET_RC=0:
CHECK:rc == 0	[Pass]
CHECK:output =~ xcatd:	[Failed]

RUN:xdsh c910f04x12v03 "lsdef"

[xdsh c910f04x12v03 "lsdef"] Running Time:1 sec
RETURN rc = 1
OUTPUT:
c910f04x12v03: Unable to open socket connection to xcatd daemon on localhost:3001.
c910f04x12v03: Verify that the xcatd daemon is running and that your SSL setup is correct.
c910f04x12v03: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.

RUN:xdsh c910f04x12v03 "tabdump site"
```
Discussed with @immarvin and he is tracking this issue now with automation test environment.

**Comment by immarvin** [comment]
cannot be recreated

**Comment by whowutwut** [comment]
@caomengmeng  Please re-open if it occurs again

**Comment by immarvin** [comment]
can not find ``mysqlsetup -u -f /tmp/servicenodes`` in xCAT-test/autotest/testcase/installation/pre_deploy_sn and  xCAT-test/autotest/testcase/installation/SN_setup_case, which is the mandatory step in http://xcat-docs.readthedocs.io/en/stable/advanced/hierarchy/databases/mysql_configure.html

**Comment by immarvin** [comment]
this is a issue in test case, can someone in FVT take a look?

**Comment by tingtli** [comment]
@immarvin  I think this is realized by following command which is in pre_deploy_sn
$cmd = "echo \"GRANT ALL on xcatdb.* TO xcatadmin@\'%\'  IDENTIFIED BY \'12345\'\;\" | mysql -u root -p12345";

**Comment by caomengmeng** [comment]
Confirmed with @immarvin, it is failed for xCAT code bug, and @immarvin is tracking it.

**Comment by caomengmeng** [comment]
Update description: the latest information is : SN is booted, but xcat failed to work in sles12.2 x86 and p8le.
After run ```updatenode SN```, xcat in SN works well

**Comment by immarvin** [comment]
the issue is caused by the incompatibility issue between sysVinit and systemd, open a specific issue in this https://github.com/xcat2/xcat-core/issues/2586

the work around is to run "service xcatd restart" on sn manually to start xcatd

**Comment by junxiawang** [comment]
As investigated this bug need to open for Dev. does not fix it.
