### ISSUE TITLE
[CUSTOMER] - ntp code in doxcat causing discovery delays up to 15 minutes 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2327]
Customer reported this issue during hardware discovery of 50+ nodes where a few seem to take 15 minutes before actually getting discovered. 

The logs provided are in the `doxcat` code 

```
[Tue Nov 29 11:02:05 2016]cp: cannot stat '/usr/share/zoneinfo/posix/America/Los_Angeles': No such file or directory
[Tue Nov 29 11:02:07 2016]<166>Nov 29 11:02:06 xcat.genesis.doxcat: Acquired IPv4 address on enP5p7s0f1
[Tue Nov 29 11:02:07 2016]192.168.64.174/24
[Tue Nov 29 11:18:03 2016]ppc64   <-- 15 minutes later
```

Looking at the message around this, the only possible code path where we would wait is in the ntp code where we are attempting to sync the clock in the genesis kernel, then sync the hwclock on the server so it will persist on the next reboot. 

Creating this issue to track the discussions .

**Comment by zet809** [comment]
I think we can close this defect first, if there is still issues after customer verified with our fix, reopen it.

**Comment by whowutwut** [comment]
@zet809   Just want to mention is that the changes made doesn't actually do anything with regards to reducing the 15 minute time required to sync the clock. It only makes it more transparent to the user what the code is actually doing during this wait time.

**Comment by zet809** [comment]
@whowutwut Yes, you are right. There are some logs added in the doxcat script, then if the issue happened again, we will know whether the genesis hung for the ntp reason.

**Comment by whowutwut** [comment]
@zet809 @neo954 So with the JEMT Garrison under fs4, I think I hit this problem again trying to test out HW discovery to validate some defects for 2.13.2...   This is very frustrating and I still don't understand why we don't simply run a `ntpd -g -x -q` to attempt to sync the clocks, if failed, it continues.  

Few things I do not like about the new spinning shell....  I am no longer able to copy and paste with the terminal that I have because the spinning icon resets rcons.  So I will provide a screen capture... 

Notice the time differences....  Not sure why that happens. 

![image](https://cloud.githubusercontent.com/assets/10049070/23276371/fe51d6d8-f9d7-11e6-9a15-2c2131ca7afb.png)

I'm going to try and complete the discovery, and I'm not sure what happens once it completes, and whether or not we can re-create this...  To help rerun discovery, you can do the following: 

1) Reset the BMC to dhcp ... and clear out xCAT knowledge of the machine and recreate the predefined stanza...
```
[root@fs4 fs4]# cd /root/c910env/discovery/fs4
[root@fs4 fs4]# ./discover_single_node.sh frame23cn05
....
Wait for the BMCs to discover....
==> bmcdiscover --range 50.0.0.5-20
Execute the following once the BMC responds....
===> bmcdiscover --range <IP> -z -w
===> rsetboot <> net
===> makeconservercf <>
===> rpower <> boot

```
2) Give some time for the BMC to pick up a DHCP IP address , then execute the above notes that the scripts prints out... : 

```
bmcdiscover --range 50.0.0.5-20
rsetboot <> net
rpower <> boot 
```

**Comment by whowutwut** [comment]
@neo954 @zet809  after 30+ minutes it's still waiting, I think something is not configured correctly on fs4 but I will leave this node so you guys can take a look.. . ``rcons node-8335-gtb-211402a`` to see the ntpd waiting...

**Comment by whowutwut** [comment]
So this fix is not acceptable in my point of view and we need to fix it in this next sprint as high priority.   Going to reopen this.  I would have tested out this code earlier but we had some urgent work utilizing the fs1/fs4 environment that I did not want to impact the team uprooting the machines.    I see the importance of running the discovery because some simple bugs slipped through in 2.13.1.  

I still feel that my proposed change is better than what we had implemented. https://github.com/xcat2/xcat-core/pull/2314 Essentially, the old code was broken and we occasionally hit the problem with the 15 min delay in discovery, but it never blocked 30 minutes or more.  My suggestion was to attempt a 1 time sync with the time server, if failed, it would just continue.   In that case, there is no blocking and timeout.  If the ntp server is configured correctly, it should sync up the time.

**Comment by zet809** [comment]
Hi, @whowutwut , it seems we can use the ntp-wait to wait for 1 minute, if not synced, just return.
-n mean try times, and the default try interval is 6 seconds. So, -n 10 means 1 minute, and -n 5 means 30 seconds. I agree with you that we shall not block such a long time (15 minutes). The same issue encountered in IST env, there is no ntp server set up on MN.

[xCAT Genesis running on cn03 /]# time ntp-wait -n 10 -v
Waiting for ntpd to synchronize... No!
ntpd did not synchronize.

real	1m0.041s
user	0m0.023s
sys	0m0.018s
[xCAT Genesis running on cn03 /]# time ntp-wait -n 5 -v
Waiting for ntpd to synchronize... No!
ntpd did not synchronize.

real	0m30.026s
user	0m0.016s
sys	0m0.010s

**Comment by whowutwut** [comment]
Ok that sounds fine. :+1:

**Comment by zet809** [comment]
Hi, @whowutwut , have update the waiting time to be 1 minute in pull request #2627

**Comment by whowutwut** [comment]
The new changes will wait only 1 minute before timing out and provide output to the user if there is no valid NTP to sync with.
