### ISSUE TITLE
copycds manpage document not complete

### ISSUE THREAD

**Issue by robers97** [xcat2/xcat-core#2329]
I'm try to get xcat to accept centos7.3 ppc64le.

copycds doesn't recognize the ISO with -n centos73 and -a ppc64le supplied.

The man page says you can edit /opt/xcat/lib/perl/xCAT/data/discinfo.pm to recognize new OSs, but it doesn't tell you how to calculate the first value of the hash for the distnames array.

%distnames = (
    "1310229985.226287" => "centos6",
    "1323560292.885204" => "centos6.2",
    "1341569670.539525" => "centos6.3",     #x86
    "1362445555.957609" => "centos6.4",     #x86_64
    "1385726732.061157" => "centos6.5",     #x86_64
    "1438724467.511049" => "centos6.7",     #x86_64

Help please!

**Comment by whowutwut** [comment]
Hi Steve, If you can mount the centos iso file: 

```
mkdir -p /tmp/test
mount -o loop </path_to_centos/centos73.iso> /tmp/test
```

Then you should find the identifier in a hidden file under the root .iso image... `ls -ltra /tmp/test`
I don't recall the name, but maybe like some discinfo file.   Then add that line to the discinfo.pm file you referenced above.

Give that a try and i'll see if you can't find it, i'll try to look more closely.

**Comment by immarvin** [comment]
hi @whowutwut @robers97 , @penguhyang is trying to enhance the copycds to recognize centos iso automatically, just like what we did for rhels. the issue is https://github.com/xcat2/xcat-core/issues/2303
