### ISSUE TITLE
[FVT]: 2.11 rinv issues summary on IBM Power S822LC RHEL 7.2

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#233]
1) rinv NODE all
```
[root@c910f03c05k08 /]# rinv c910f05c37 all
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: BMC Firmware: 2.06
c910f05c37: System Description: OpenPOWER Firmware
...
c910f05c37: System Firmware Product Additional Info: hostboot-binaries-4
c910f05c37: System Firmware Product Additional Info: firestone-xml-9163b
c910f05c37: System Firmware Product Additional Info: capp-ucode-105cb8f
c910f05c37: Error: Received incorrect data from BMC
[root@c910f03c05k08 /]# echo $?
1
```
2) rinv NODE pci     ("rinv X-node pci" has no output) 
```
[root@c910f03c05k08 /]# rinv c910f05c37 pci
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
```
3) rinv NODE model 
```
[root@c910f03c05k08 /]# rinv c910f05c37 model
c910f05c37: System Description: OpenPOWER Firmware
```
Here is no model information for Firestone.  For X node, there is output.
```
c910f04x31:~ # rinv c910f04x35 model
c910f04x35: System Description: iDataPlex dx360 M4
c910f04x35: System Model/MTM: 7912AC1
```

4) rinv NODE serial 
```
[root@c910f03c05k08 /]# rinv c910f05c37 serial
```
Nothing output!

X-Node has output
```
c910f04x31:~ # rinv c910f04x35 serial
c910f04x35: System Serial Number: 06CGTR0
c910f04x35: Chassis Serial Number: 06CGTR0
```
5) rinv NODE asset 
```
[root@c910f03c05k08 /]# rinv c910f05c37 asset
```
nothing output

X-Node has output, but no number is displayed.
```
c910f04x31:~ # rinv c910f04x35  asset
c910f04x35: System Asset Number:
```
6) rinv NODE vpd 
```
[root@c910f03c05k08 /]# rinv c910f05c37 vpd
c910f05c37: Manufacturer ID: 0
c910f05c37: Device ID: 32
c910f05c37: BMC Firmware: 2.06
c910f05c37: System Description: OpenPOWER Firmware
c910f05c37: Product ID: 43707
```
X-node has different output
```
c910f04x31:~ # rinv c910f04x35  vpd
c910f04x35: System Description: iDataPlex dx360 M4
c910f04x35: System Model/MTM: 7912AC1
c910f04x35: System Serial Number: 06CGTR0
c910f04x35: Chassis Serial Number: 06CGTR0
c910f04x35: Device ID: 32
c910f04x35: Manufacturer ID: IBM (20301)
c910f04x35: BMC Firmware: 1.25 (1AOO26K 2012/02/23 12:17:37)
c910f04x35: Product ID: 353
```
7) rinv NODE firm
```
[root@c910f03c05k08 /]# rinv c910f05c37 firm
c910f05c37: BMC Firmware: 2.06
```

X-node has different output.
```
c910f04x31:~ # rinv c910f04x35  firm
c910f04x35: Backup IMM Version: 1.25 (1AOO26K 2012/02/23)
c910f04x35: Backup UEFI Version: 1.00 (TDE112D)
c910f04x35: BMC Firmware: 1.25 (1AOO26K 2012/02/23 12:17:37)
c910f04x35: UEFI Version: 1.00 (TDE112D 2012/03/01)
```

8) rinv NODE diag
```
[root@c910f03c05k08 /]# rinv c910f05c37 diag
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
```
X-node has different output
```
c910f04x31:~ # rinv c910f04x35  diag
```
9)rinv NODE bios
```
[root@c910f03c05k08 /]#  rinv c910f05c37 bios
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
```
X-node has different output
```
c910f04x31:~ # rinv c910f04x35  bios
c910f04x35: Backup IMM Version: 1.25 (1AOO26K 2012/02/23)
c910f04x35: Backup UEFI Version: 1.00 (TDE112D)
c910f04x35: UEFI Version: 1.00 (TDE112D 2012/03/01)
```
10) rinv NODE mparom
```
[root@c910f03c05k08 /]#  rinv c910f05c37 mparom
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
```
X-node has no output
```
c910f04x31:~ # rinv c910f04x35  mparom
```
11) rinv NODE mac
```
[root@c910f03c05k08 /]#  rinv c910f05c37 mac
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
```
X-node has output
```
c910f04x31:~ # rinv c910f04x35  mac
c910f04x35: MAC Address 1: 34:40:b5:b9:5c:9e
c910f04x35: MAC Address 2: 34:40:b5:b9:5c:9f
```

**Comment by tingtli** [comment]
with latest build , i sitll get the error of " Error: Received incorrect data from BMC"

[root@c910f03c05k08 testkit]# rinv c910f05c37 all
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: Error: Received incorrect data from BMC
c910f05c37: BMC Firmware: 2.11
c910f05c37: CPU 1 Board Part Number: 00UM003
c910f05c37: UUID/GUID: 1484E270-3901-0384-0010-DEBF5E195E6B
c910f05c37: Product ID: 43707
c910f05c37: Manufacturer ID: 0
c910f05c37: Device ID: 32
c910f05c37: CPU 1 Board Manufacturer: IBM
c910f05c37: CPU 1 Board Serial Number: YA1932708558
c910f05c37: CPU 1 Board : PROCESSOR MODULE
c910f05c37: CPU 1 Board Additional Info: ECID:019A0060010467180A10000000402E13
c910f05c37: CPU 2 Board Part Number: 00UM003
c910f05c37: CPU 2 Board Manufacturer: IBM
c910f05c37: CPU 2 Board Serial Number: YA1932718260
c910f05c37: CPU 2 Board : PROCESSOR MODULE
c910f05c37: CPU 2 Board Additional Info: ECID:019A0067800087180A10000000143075
c910f05c37: DIMM1 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM1 Product Serial Number: 02 d2 51 8a (  Q )
c910f05c37: DIMM1 Product Version: 00 00 (  )
c910f05c37: DIMM1 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM10 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM10 Product Serial Number: 02 d2 51 00 (  Q )
c910f05c37: DIMM10 Product Version: 00 00 (  )
c910f05c37: DIMM10 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM11 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM11 Product Serial Number: 02 d2 51 74 (  Qt)
c910f05c37: DIMM11 Product Version: 00 00 (  )
c910f05c37: DIMM11 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM12 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM12 Product Serial Number: 02 d2 51 80 (  Q )
c910f05c37: DIMM12 Product Version: 00 00 (  )
c910f05c37: DIMM12 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM13 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM13 Product Serial Number: 02 d2 51 40 (  Q )
c910f05c37: DIMM13 Product Version: 00 00 (  )
c910f05c37: DIMM13 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM14 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM14 Product Serial Number: 02 d2 51 83 (  Q )
c910f05c37: DIMM14 Product Version: 00 00 (  )
c910f05c37: DIMM14 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM15 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM15 Product Serial Number: 02 d2 51 0a (  Q )
c910f05c37: DIMM15 Product Version: 00 00 (  )
c910f05c37: DIMM15 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM16 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM16 Product Serial Number: 02 d2 50 f6 (  P )
c910f05c37: DIMM16 Product Version: 00 00 (  )
c910f05c37: DIMM16 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM17 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM17 Product Serial Number: 02 d2 51 0c (  Q )
c910f05c37: DIMM17 Product Version: 00 00 (  )
c910f05c37: DIMM17 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM18 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM18 Product Serial Number: 02 d2 51 26 (  Q )
c910f05c37: DIMM18 Product Version: 00 00 (  )
c910f05c37: DIMM18 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM19 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM19 Product Serial Number: 02 d2 50 f7 (  P )
c910f05c37: DIMM19 Product Version: 00 00 (  )
c910f05c37: DIMM19 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM2 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM2 Product Serial Number: 02 d2 50 fb (  P )
c910f05c37: DIMM2 Product Version: 00 00 (  )
c910f05c37: DIMM2 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM20 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM20 Product Serial Number: 02 d2 51 48 (  QH)
c910f05c37: DIMM20 Product Version: 00 00 (  )
c910f05c37: DIMM20 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM21 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM21 Product Serial Number: 02 d2 51 5e (  Q )
c910f05c37: DIMM21 Product Version: 00 00 (  )
c910f05c37: DIMM21 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM22 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM22 Product Serial Number: 02 d2 51 53 (  QS)
c910f05c37: DIMM22 Product Version: 00 00 (  )
c910f05c37: DIMM22 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM23 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM23 Product Serial Number: 02 d2 51 3d (  Q )
c910f05c37: DIMM23 Product Version: 00 00 (  )
c910f05c37: DIMM23 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM24 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM24 Product Serial Number: 02 d2 51 2e (  Q )
c910f05c37: DIMM24 Product Version: 00 00 (  )
c910f05c37: DIMM24 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM25 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM25 Product Serial Number: 02 d2 51 77 (  Qw)
c910f05c37: DIMM25 Product Version: 00 00 (  )
c910f05c37: DIMM25 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM26 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM26 Product Serial Number: 02 cd d6 d6 (    )
c910f05c37: DIMM26 Product Version: 00 00 (  )
c910f05c37: DIMM26 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM27 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM27 Product Serial Number: 02 d2 51 86 (  Q )
c910f05c37: DIMM27 Product Version: 00 00 (  )
c910f05c37: DIMM27 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM28 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM28 Product Serial Number: 02 d2 51 72 (  Qr)
c910f05c37: DIMM28 Product Version: 00 00 (  )
c910f05c37: DIMM28 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM29 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM29 Product Serial Number: 02 d2 51 28 (  Q )
c910f05c37: DIMM29 Product Version: 00 00 (  )
c910f05c37: DIMM29 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM3 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM3 Product Serial Number: 02 d2 51 5c (  Q )
c910f05c37: DIMM3 Product Version: 00 00 (  )
c910f05c37: DIMM3 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM30 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM30 Product Serial Number: 02 d2 51 70 (  Qp)
c910f05c37: DIMM30 Product Version: 00 00 (  )
c910f05c37: DIMM30 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM31 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM31 Product Serial Number: 02 d2 51 0b (  Q )
c910f05c37: DIMM31 Product Version: 00 00 (  )
c910f05c37: DIMM31 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM32 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM32 Product Serial Number: 02 d2 51 87 (  Q )
c910f05c37: DIMM32 Product Version: 00 00 (  )
c910f05c37: DIMM32 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM4 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM4 Product Serial Number: 02 d2 51 3e (  Q )
c910f05c37: DIMM4 Product Version: 00 00 (  )
c910f05c37: DIMM4 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM5 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM5 Product Serial Number: 02 d2 51 4c (  QL)
c910f05c37: DIMM5 Product Version: 00 00 (  )
c910f05c37: DIMM5 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM6 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM6 Product Serial Number: 02 d2 51 7a (  Qz)
c910f05c37: DIMM6 Product Version: 00 00 (  )
c910f05c37: DIMM6 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM7 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM7 Product Serial Number: 02 d2 51 6f (  Qo)
c910f05c37: DIMM7 Product Version: 00 00 (  )
c910f05c37: DIMM7 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM8 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM8 Product Serial Number: 02 d2 51 84 (  Q )
c910f05c37: DIMM8 Product Version: 00 00 (  )
c910f05c37: DIMM8 Product Model: M393B1G73EB0-YK0
c910f05c37: DIMM9 Product Manufacturer: ce 80 (  )
c910f05c37: DIMM9 Product Serial Number: 02 d2 51 41 (  QA)
c910f05c37: DIMM9 Product Version: 00 00 (  )
c910f05c37: DIMM9 Product Model: M393B1G73EB0-YK0
c910f05c37: FAN1: clear
c910f05c37: FAN2: clear
c910f05c37: FAN3: clear
c910f05c37: FAN4: clear
c910f05c37: GPU1: clear
c910f05c37: GPU2: clear
c910f05c37: MEMBUF1 Board Part Number: 0000000000000000
c910f05c37: MEMBUF1 Board Manufacturer: IBM
c910f05c37: MEMBUF1 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF1 Board : DDR3 MEM RISER
c910f05c37: MEMBUF1 Board Additional Info: ECID:019A0082422087181716000000200361
c910f05c37: MEMBUF2 Board Part Number: 0000000000000000
c910f05c37: MEMBUF2 Board Manufacturer: IBM
c910f05c37: MEMBUF2 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF2 Board : DDR3 MEM RISER
c910f05c37: MEMBUF2 Board Additional Info: ECID:019A0082402447180A11000000270361
c910f05c37: MEMBUF3 Board Part Number: 0000000000000000
c910f05c37: MEMBUF3 Board Manufacturer: IBM
c910f05c37: MEMBUF3 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF3 Board : DDR3 MEM RISER
c910f05c37: MEMBUF3 Board Additional Info: ECID:019A0082402447180E0E0000002D0351
c910f05c37: MEMBUF4 Board Part Number: 0000000000000000
c910f05c37: MEMBUF4 Board Manufacturer: IBM
c910f05c37: MEMBUF4 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF4 Board : DDR3 MEM RISER
c910f05c37: MEMBUF4 Board Additional Info: ECID:019A00824220871811130000002C0321
c910f05c37: MEMBUF5 Board Part Number: 0000000000000000
c910f05c37: MEMBUF5 Board Manufacturer: IBM
c910f05c37: MEMBUF5 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF5 Board : DDR3 MEM RISER
c910f05c37: MEMBUF5 Board Additional Info: ECID:019A0082422087180D0E000000840351
c910f05c37: MEMBUF6 Board Part Number: 0000000000000000
c910f05c37: MEMBUF6 Board Manufacturer: IBM
c910f05c37: MEMBUF6 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF6 Board : DDR3 MEM RISER
c910f05c37: MEMBUF6 Board Additional Info: ECID:019A0082402447180A21000000240391
c910f05c37: MEMBUF7 Board Part Number: 0000000000000000
c910f05c37: MEMBUF7 Board Manufacturer: IBM
c910f05c37: MEMBUF7 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF7 Board : DDR3 MEM RISER
c910f05c37: MEMBUF7 Board Additional Info: ECID:019A008242086718191B0000000903F1
c910f05c37: MEMBUF8 Board Part Number: 0000000000000000
c910f05c37: MEMBUF8 Board Manufacturer: IBM
c910f05c37: MEMBUF8 Board Serial Number: 0000000000000000
c910f05c37: MEMBUF8 Board : DDR3 MEM RISER
c910f05c37: MEMBUF8 Board Additional Info: ECID:019A0082411C87180B220000001303A1
c910f05c37: NODE 1 Board Part Number: 0000000000000000
c910f05c37: NODE 1 Board Manufacturer: IBM
c910f05c37: NODE 1 Board Serial Number: 0000000000000000
c910f05c37: NODE 1 Board : SYSTEM PLANAR
c910f05c37: NODE 1 Chassis Part Number: 8335-GTA
c910f05c37: NODE 1 Chassis Serial Number: 0000000000000000
c910f05c37: PSU1 Product Manufacturer: EMER
c910f05c37: PSU1 Product Serial Number: 55604J
c910f05c37: PSU1 Product Version: 0.12
c910f05c37: PSU1 Product Model: 00FX880
c910f05c37: PSU2 Product Manufacturer: EMER
c910f05c37: PSU2 Product Serial Number: 54V0AX
c910f05c37: PSU2 Product Version: 0.12
c910f05c37: PSU2 Product Model: 00FX880
c910f05c37: System Firmware Product Version: IBM-firestone-ibm-OP8_v1.7_1.1
c910f05c37: System Firmware Product Additional Info: hostboot-bc98d0b-fbf3400
c910f05c37: System Firmware Product Additional Info: occ-0362706-33e06ec
c910f05c37: System Firmware Product Additional Info: skiboot-5.1.6-5288e8a
c910f05c37: System Firmware Product Additional Info: hostboot-binaries-43d5a59
c910f05c37: System Firmware Product Additional Info: firestone-xml-e7b4fa2
c910f05c37: System Firmware Product Additional Info: capp-ucode-105cb8f
c910f05c37: Error: Received incorrect data from BMC
[root@c910f03c05k08 testkit]# echo $?
1
[root@c910f03c05k08 testkit]#

**Comment by whowutwut** [comment]
@tingtli , I edited your initial post and added the markdown to surround the code blocks.   It's much easier to read if you use the markdown.

**Comment by whowutwut** [comment]
I'm going to use this to respond to the items above..  I will edit as i debug each item. 

7)  The rinv has more on X machines because the IMM  (integrated management modules) supports those additional functions. The Power based BMC does not seem to have that support...  If i go into the same code I get the following error:  ``fs2: Error: Invalid or unsupported command``

**Comment by whowutwut** [comment]
Opened #250 to suppress the output about the incorrect data from BMC, @zet809  please review and let me know if you agree or not...  the missing data in the FRU, I am printing out all the sdr_hash data that we are getting back from the FRU units and there is not much . I think we need to replace the unit first before we are able to add in that support.

**Comment by zet809** [comment]
I think the current output msg "Received incorrect data from BMC for FRU ID: <fru_id>" is good enough, this defect can be closed.

**Comment by tingtli** [comment]
Verified and close
[root@c910f03c05k23 ~]# rinv c910f05c35 all
c910f05c35: Received incorrect data from BMC for FRU ID: 1
c910f05c35: Received incorrect data from BMC for FRU ID: 2
c910f05c35: Received incorrect data from BMC for FRU ID: 12
c910f05c35: Received incorrect data from BMC for FRU ID: 21
c910f05c35: Received incorrect data from BMC for FRU ID: 22
c910f05c35: Received incorrect data from BMC for FRU ID: 23
c910f05c35: Received incorrect data from BMC for FRU ID: 24
c910f05c35: Received incorrect data from BMC for FRU ID: 25
c910f05c35: Received incorrect data from BMC for FRU ID: 26
c910f05c35: Received incorrect data from BMC for FRU ID: 27
c910f05c35: Received incorrect data from BMC for FRU ID: 28
c910f05c35: Received incorrect data from BMC for FRU ID: 29
c910f05c35: Received incorrect data from BMC for FRU ID: 30
c910f05c35: Received incorrect data from BMC for FRU ID: 13
c910f05c35: Received incorrect data from BMC for FRU ID: 31
c910f05c35: Received incorrect data from BMC for FRU ID: 32
c910f05c35: Received incorrect data from BMC for FRU ID: 33
c910f05c35: Received incorrect data from BMC for FRU ID: 34
c910f05c35: Received incorrect data from BMC for FRU ID: 35
c910f05c35: Received incorrect data from BMC for FRU ID: 36
c910f05c35: Received incorrect data from BMC for FRU ID: 37
c910f05c35: Received incorrect data from BMC for FRU ID: 38
c910f05c35: Received incorrect data from BMC for FRU ID: 39
c910f05c35: Received incorrect data from BMC for FRU ID: 40
c910f05c35: Received incorrect data from BMC for FRU ID: 14
c910f05c35: Received incorrect data from BMC for FRU ID: 41
c910f05c35: Received incorrect data from BMC for FRU ID: 42
c910f05c35: Received incorrect data from BMC for FRU ID: 43
c910f05c35: Received incorrect data from BMC for FRU ID: 15
c910f05c35: Received incorrect data from BMC for FRU ID: 16
c910f05c35: Received incorrect data from BMC for FRU ID: 17
c910f05c35: Received incorrect data from BMC for FRU ID: 18
c910f05c35: Received incorrect data from BMC for FRU ID: 19
c910f05c35: Received incorrect data from BMC for FRU ID: 20
c910f05c35: Received incorrect data from BMC for FRU ID: 46
c910f05c35: Received incorrect data from BMC for FRU ID: 50
c910f05c35: Received incorrect data from BMC for FRU ID: 51
c910f05c35: Received incorrect data from BMC for FRU ID: 52
c910f05c35: Received incorrect data from BMC for FRU ID: 44
c910f05c35: Received incorrect data from BMC for FRU ID: 45
c910f05c35: Received incorrect data from BMC for FRU ID: 4
c910f05c35: Received incorrect data from BMC for FRU ID: 5
c910f05c35: Received incorrect data from BMC for FRU ID: 6
c910f05c35: Received incorrect data from BMC for FRU ID: 7
c910f05c35: Received incorrect data from BMC for FRU ID: 8
c910f05c35: Received incorrect data from BMC for FRU ID: 9
c910f05c35: Received incorrect data from BMC for FRU ID: 10
c910f05c35: Received incorrect data from BMC for FRU ID: 11
c910f05c35: Received incorrect data from BMC for FRU ID: 3
c910f05c35: Received incorrect data from BMC for FRU ID: 48
c910f05c35: Received incorrect data from BMC for FRU ID: 49
c910f05c35: Received incorrect data from BMC for FRU ID: 47
c910f05c35: BMC Firmware: 2.13
c910f05c35: Manufacturer ID: 0
c910f05c35: CPU 1: clear
c910f05c35: UUID/GUID: 1484E270-7800-0384-0010-DEBF287F6A6B
c910f05c35: Device ID: 32
c910f05c35: Product ID: 43707
c910f05c35: CPU 2: clear
c910f05c35: DIMM1: clear
c910f05c35: DIMM10: clear
c910f05c35: DIMM11: clear
c910f05c35: DIMM12: clear
c910f05c35: DIMM13: clear
c910f05c35: DIMM14: clear
c910f05c35: DIMM15: clear
c910f05c35: DIMM16: clear
c910f05c35: DIMM17: clear
c910f05c35: DIMM18: clear
c910f05c35: DIMM19: clear
c910f05c35: DIMM2: clear
c910f05c35: DIMM20: clear
c910f05c35: DIMM21: clear
c910f05c35: DIMM22: clear
c910f05c35: DIMM23: clear
c910f05c35: DIMM24: clear
c910f05c35: DIMM25: clear
c910f05c35: DIMM26: clear
c910f05c35: DIMM27: clear
c910f05c35: DIMM28: clear
c910f05c35: DIMM29: clear
c910f05c35: DIMM3: clear
c910f05c35: DIMM30: clear
c910f05c35: DIMM31: clear
c910f05c35: DIMM32: clear
c910f05c35: DIMM4: clear
c910f05c35: DIMM5: clear
c910f05c35: DIMM6: clear
c910f05c35: DIMM7: clear
c910f05c35: DIMM8: clear
c910f05c35: DIMM9: clear
c910f05c35: FAN1: clear
c910f05c35: FAN2: clear
c910f05c35: FAN3: clear
c910f05c35: FAN4: clear
c910f05c35: GPU1: clear
c910f05c35: GPU2: clear
c910f05c35: MEMBUF1: clear
c910f05c35: MEMBUF2: clear
c910f05c35: MEMBUF3: clear
c910f05c35: MEMBUF4: clear
c910f05c35: MEMBUF5: clear
c910f05c35: MEMBUF6: clear
c910f05c35: MEMBUF7: clear
c910f05c35: MEMBUF8: clear
c910f05c35: NODE 1: clear
c910f05c35: PSU1 Product Manufacturer: EMER
c910f05c35: PSU1 Product Serial Number: 4CY01H
c910f05c35: PSU1 Product Version: 0.12
c910f05c35: PSU1 Product Model: 00FX880
c910f05c35: PSU2 Product Manufacturer: EMER
c910f05c35: PSU2 Product Serial Number: 4CY009
c910f05c35: PSU2 Product Version: 0.12
c910f05c35: PSU2 Product Model: 00FX880
c910f05c35: System Firmware: clear
c910f05c35: Received incorrect data from BMC for FRU ID: 47
