### ISSUE TITLE
[FVT]:2.11 rvitals issue summary on IBM Power S822LC running RHEL7.2

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#234]
[root@c910f03c05k08 /]# rvitals c910f05c37 all
c910f05c37: Power Status: on
c910f05c37: Power Overload: false
c910f05c37: Power Interlock: inactive
c910f05c37: Power Fault: false
c910f05c37: Power Control Fault: false
c910f05c37: Power Restore Policy: Always off
c910f05c37: Last Power Event: By Request
c910f05c37: Chassis intrusion: inactive
c910f05c37: Front Panel Lockout: inactive
c910f05c37: Drive Fault: false
c910f05c37: Cooling Fault: false
c910f05c37: Identify Light: off
c910f05c37: 12V Sense: 0 Watts (0 BTUs/hr)
c910f05c37: APSS Fault: 0
c910f05c37: Activate Pwr Lt: 0                    (xCAT needs to add support for 198)   <==confusion output
c910f05c37: All PGood: 0
c910f05c37: Ambient Temp: 28 C (82 F)
c910f05c37: BIOS Golden Side: 0                    (xCAT needs to add support for 195)
c910f05c37: BMC Golden Side: 0                    (xCAT needs to add support for 195)
c910f05c37: Boot Count: 0                    (xCAT needs to add support for 195)
c910f05c37: CPU Core Func 1: 0
c910f05c37: CPU Core Func 10: 0
c910f05c37: CPU Core Func 11: 0
c910f05c37: CPU Core Func 12: 0
c910f05c37: CPU Core Func 13: 0
c910f05c37: CPU Core Func 14: 0
c910f05c37: CPU Core Func 15: 0
c910f05c37: CPU Core Func 16: 0
c910f05c37: CPU Core Func 17: 0
c910f05c37: CPU Core Func 18: 0
c910f05c37: CPU Core Func 19: 0
c910f05c37: CPU Core Func 2: 0
c910f05c37: CPU Core Func 20: 0
c910f05c37: CPU Core Func 21: 0
c910f05c37: CPU Core Func 22: 0
c910f05c37: CPU Core Func 23: 0
c910f05c37: CPU Core Func 24: 0
c910f05c37: CPU Core Func 3: 0
c910f05c37: CPU Core Func 4: 0
c910f05c37: CPU Core Func 5: 0
c910f05c37: CPU Core Func 6: 0
c910f05c37: CPU Core Func 7: 0
c910f05c37: CPU Core Func 8: 0
c910f05c37: CPU Core Func 9: 0
c910f05c37: CPU Core Temp 1: 56 C (133 F)
c910f05c37: CPU Core Temp 10: 56 C (133 F)
c910f05c37: CPU Core Temp 11: N/A
c910f05c37: CPU Core Temp 12: 56 C (133 F)
c910f05c37: CPU Core Temp 13: 54 C (129 F)
c910f05c37: CPU Core Temp 14: 55 C (131 F)
c910f05c37: CPU Core Temp 15: 55 C (131 F)
c910f05c37: CPU Core Temp 16: 55 C (131 F)
c910f05c37: CPU Core Temp 17: N/A
c910f05c37: CPU Core Temp 18: 54 C (129 F)
c910f05c37: CPU Core Temp 19: 56 C (133 F)
c910f05c37: CPU Core Temp 2: 55 C (131 F)
c910f05c37: CPU Core Temp 20: 56 C (133 F)
c910f05c37: CPU Core Temp 21: 55 C (131 F)
c910f05c37: CPU Core Temp 22: N/A
c910f05c37: CPU Core Temp 23: 55 C (131 F)
c910f05c37: CPU Core Temp 24: 55 C (131 F)
c910f05c37: CPU Core Temp 3: 56 C (133 F)
c910f05c37: CPU Core Temp 4: 55 C (131 F)
c910f05c37: CPU Core Temp 5: 55 C (131 F)
c910f05c37: CPU Core Temp 6: N/A
c910f05c37: CPU Core Temp 7: 58 C (136 F)
c910f05c37: CPU Core Temp 8: 57 C (135 F)
c910f05c37: CPU Core Temp 9: 56 C (133 F)
c910f05c37: CPU Diode 1: 39 C (102 F)
c910f05c37: CPU Diode 2: 39 C (102 F)
c910f05c37: CPU Func 1: 0
c910f05c37: CPU Func 2: 0
c910f05c37: CPU VDD Curr: 64 Amps
c910f05c37: CPU VDD Volt: 0.95 Volts
c910f05c37: CPU1 Temp: N/A
c910f05c37: CPU2 Temp: N/A
c910f05c37: Checkstop: 0
c910f05c37: DIMM Func 1: 0                    (Present)
c910f05c37: DIMM Func 10: 0                    (Present)
c910f05c37: DIMM Func 11: 0                    (Present)
c910f05c37: DIMM Func 12: 0                    (Present)
c910f05c37: DIMM Func 13: 0                    (Present)
c910f05c37: DIMM Func 14: 0                    (Present)
c910f05c37: DIMM Func 15: 0                    (Present)
c910f05c37: DIMM Func 16: 0                    (Present)
c910f05c37: DIMM Func 17: 0                    (Present)
c910f05c37: DIMM Func 18: 0                    (Present)
c910f05c37: DIMM Func 19: 0                    (Present)
c910f05c37: DIMM Func 2: 0                    (Present)
c910f05c37: DIMM Func 20: 0                    (Present)
c910f05c37: DIMM Func 21: 0                    (Present)
c910f05c37: DIMM Func 22: 0                    (Present)
c910f05c37: DIMM Func 23: 0                    (Present)
c910f05c37: DIMM Func 24: 0                    (Present)
c910f05c37: DIMM Func 25: 0                    (Present)
c910f05c37: DIMM Func 26: 0                    (Present)
c910f05c37: DIMM Func 27: 0                    (Present)
c910f05c37: DIMM Func 28: 0                    (Present)
c910f05c37: DIMM Func 29: 0                    (Present)
c910f05c37: DIMM Func 3: 0                    (Present)
c910f05c37: DIMM Func 30: 0                    (Present)
c910f05c37: DIMM Func 31: 0                    (Present)
c910f05c37: DIMM Func 32: 0                    (Present)
c910f05c37: DIMM Func 4: 0                    (Present)
c910f05c37: DIMM Func 5: 0                    (Present)
c910f05c37: DIMM Func 6: 0                    (Present)
c910f05c37: DIMM Func 7: 0                    (Present)
c910f05c37: DIMM Func 8: 0                    (Present)
c910f05c37: DIMM Func 9: 0                    (Present)
c910f05c37: DIMM1 Temp: 43 C (109 F)
c910f05c37: DIMM10 Temp: 34 C (93 F)
c910f05c37: DIMM11 Temp: 33 C (91 F)
c910f05c37: DIMM12 Temp: 35 C (95 F)
c910f05c37: DIMM13 Temp: 33 C (91 F)
c910f05c37: DIMM14 Temp: 35 C (95 F)
c910f05c37: DIMM15 Temp: 35 C (95 F)
c910f05c37: DIMM16 Temp: 35 C (95 F)
c910f05c37: DIMM17 Temp: 34 C (93 F)
c910f05c37: DIMM18 Temp: 34 C (93 F)
c910f05c37: DIMM19 Temp: 32 C (90 F)
c910f05c37: DIMM2 Temp: 46 C (115 F)
c910f05c37: DIMM20 Temp: 33 C (91 F)
c910f05c37: DIMM21 Temp: 33 C (91 F)
c910f05c37: DIMM22 Temp: 33 C (91 F)
c910f05c37: DIMM23 Temp: 31 C (88 F)
c910f05c37: DIMM24 Temp: 34 C (93 F)
c910f05c37: DIMM25 Temp: 34 C (93 F)
c910f05c37: DIMM26 Temp: 33 C (91 F)
c910f05c37: DIMM27 Temp: 32 C (90 F)
c910f05c37: DIMM28 Temp: 33 C (91 F)
c910f05c37: DIMM29 Temp: 35 C (95 F)
c910f05c37: DIMM3 Temp: 44 C (111 F)
c910f05c37: DIMM30 Temp: 34 C (93 F)
c910f05c37: DIMM31 Temp: 33 C (91 F)
c910f05c37: DIMM32 Temp: 35 C (95 F)
c910f05c37: DIMM4 Temp: 44 C (111 F)
c910f05c37: DIMM5 Temp: 36 C (97 F)
c910f05c37: DIMM6 Temp: 35 C (95 F)
c910f05c37: DIMM7 Temp: 35 C (95 F)
c910f05c37: DIMM8 Temp: 36 C (97 F)
c910f05c37: DIMM9 Temp: 34 C (93 F)
c910f05c37: FW Boot Progress: 0                    (Firmware progress)
c910f05c37: Fan 1: 4200 RPM
c910f05c37: Fan 2: 4200 RPM
c910f05c37: Fan 3: 4200 RPM
c910f05c37: Fan 4: 4200 RPM
c910f05c37: Fan Power A: 39 Watts (133 BTUs/hr)
c910f05c37: GPU Func 1: 0                    (Present)
c910f05c37: GPU Func 2: 0                    (Present)
c910f05c37: GPU Func 3: 0                    (Present)
c910f05c37: GPU Func 4: 0                    (Present)
c910f05c37: GPU Sense: 77 Watts (263 BTUs/hr)
c910f05c37: GPU Temp 1: 34 C (93 F)
c910f05c37: GPU Temp 2: 39 C (102 F)
c910f05c37: GPU Temp 3: 38 C (100 F)
c910f05c37: GPU Temp 4: 43 C (109 F)
c910f05c37: Host Status: 0                    (xCAT needs to add support for 34)
c910f05c37: Mem Buf Func 1: 0                    (Present)
c910f05c37: Mem Buf Func 2: 0                    (Present)
c910f05c37: Mem Buf Func 3: 0                    (Present)
c910f05c37: Mem Buf Func 4: 0                    (Present)
c910f05c37: Mem Buf Func 5: 0                    (Present)
c910f05c37: Mem Buf Func 6: 0                    (Present)
c910f05c37: Mem Buf Func 7: 0                    (Present)
c910f05c37: Mem Buf Func 8: 0                    (Present)
c910f05c37: Mem Buf Temp 1: N/A
c910f05c37: Mem Buf Temp 2: N/A
c910f05c37: Mem Buf Temp 3: N/A
c910f05c37: Mem Buf Temp 4: N/A
c910f05c37: Mem Buf Temp 5: N/A
c910f05c37: Mem Buf Temp 6: N/A
c910f05c37: Mem Buf Temp 7: N/A
c910f05c37: Mem Buf Temp 8: N/A
c910f05c37: Mem Cache Power: 85 Watts (290 BTUs/hr)
c910f05c37: Mem Proc0 Pwr: 37 Watts (126 BTUs/hr)
c910f05c37: Mem Proc1 Pwr: 37 Watts (126 BTUs/hr)
c910f05c37: Motherboard Flt: 0
c910f05c37: OCC 1 Active: 0
c910f05c37: OCC 2 Active: 0
c910f05c37: OS Boot: 0                    (xCAT needs to add support for 31)
c910f05c37: PCI: 0
c910f05c37: PCI Clock Fault: 0
c910f05c37: PCIE Proc0 Pwr: 67 Watts (229 BTUs/hr)
c910f05c37: PCIE Proc1 Power: 61 Watts (208 BTUs/hr)
c910f05c37: PS Derating Fac: 0                    (xCAT needs to add support for 200)
c910f05c37: PSU Fault 1: 0                    (Present)
c910f05c37: PSU Fault 2: 0                    (Present)
c910f05c37: Proc0 Power: 69 Watts (235 BTUs/hr)
c910f05c37: Proc1 Power: 60 Watts (205 BTUs/hr)
c910f05c37: Quick Power Drop: 0
c910f05c37: Ref Clock Fault: 0
c910f05c37: System Event: 0
c910f05c37: TOD Clock Fault: 0
c910f05c37: Watchdog: 0
c910f05c37: LED status not supported on this system
[root@c910f03c05k08 /]#

**Comment by whowutwut** [comment]
What is the purpose of this issue? Should have some text to describe the issue instead of just command line output. You can edit the initial post 

Also can you wrap the console output with three back ticks to have the markdown formatting?

**Comment by cxhong** [comment]
We didn't support more than half of Sensor type, should we support all?  or can we just get rid of the message line: "xCAT needs to add support for "

From output above,  Sensor type 195, 198 and 200 are OEM RESERVED
I add code to support Sensor type 34 and 31, the modified output will be look like that:

from: 
Host Status: 0                    (xCAT needs to add support for 34)
to:
Host Status: 0                    (working)

from:
OS Boot: 0                    (xCAT needs to add support for 31)
to:
OS Boot: 0

**Comment by tingtli** [comment]
The message "xCAT needs to add support for 198" etc was added by Jarrod. It seems that he would like to add some support for the rvitals.  Need more communication with Jarrod.  I record this issue in case I forget this.

**Comment by whowutwut** [comment]
Hi @jjohnson42 , do you have any advice for this issue we are seeing?

**Comment by cxhong** [comment]
Pull request for this issue is #357

**Comment by tingtli** [comment]
I think with the fix, the message makes  more sense. I will close the bug.
[root@c910f03c05k08 /]# lsxcatd -v
Version 2.11 (git commit 76acb1f31566a2721ae1139bee8d538f73b4b468, built Thu Nov  5 19:30:55 EST 2015)

[root@c910f03c05k08 /]# rvitals c910f05c37 all
c910f05c37: Power Status: off
c910f05c37: Power Overload: false
c910f05c37: Power Interlock: inactive
c910f05c37: Power Fault: false
c910f05c37: Power Control Fault: false
c910f05c37: Power Restore Policy: Always off
c910f05c37: Last Power Event: AC failed
c910f05c37: Chassis intrusion: inactive
c910f05c37: Front Panel Lockout: inactive
c910f05c37: Drive Fault: false
c910f05c37: Cooling Fault: false
c910f05c37: Identify Light: off
c910f05c37: 12V Sense: 0 Watts (0 BTUs/hr)
c910f05c37: APSS Fault: 0
c910f05c37: Activate Pwr Lt: 0                    (OEM Reserved 198)
c910f05c37: All PGood: 0                    (Power off)
c910f05c37: Ambient Temp: 36 C (97 F)
c910f05c37: BIOS Golden Side: 0                    (OEM Reserved 195)
c910f05c37: BMC Golden Side: 0                    (OEM Reserved 195)
c910f05c37: Boot Count: 0                    (OEM Reserved 195)
c910f05c37: CPU Core Func 1: 0
c910f05c37: CPU Core Func 10: 0
c910f05c37: CPU Core Func 11: 0
c910f05c37: CPU Core Func 12: 0
c910f05c37: CPU Core Func 13: 0
c910f05c37: CPU Core Func 14: 0
c910f05c37: CPU Core Func 15: 0
c910f05c37: CPU Core Func 16: 0
c910f05c37: CPU Core Func 17: 0
c910f05c37: CPU Core Func 18: 0
c910f05c37: CPU Core Func 19: 0
c910f05c37: CPU Core Func 2: 0
c910f05c37: CPU Core Func 20: 0
c910f05c37: CPU Core Func 21: 0
c910f05c37: CPU Core Func 22: 0
c910f05c37: CPU Core Func 23: 0
c910f05c37: CPU Core Func 24: 0
c910f05c37: CPU Core Func 3: 0
c910f05c37: CPU Core Func 4: 0
c910f05c37: CPU Core Func 5: 0
c910f05c37: CPU Core Func 6: 0
c910f05c37: CPU Core Func 7: 0
c910f05c37: CPU Core Func 8: 0
c910f05c37: CPU Core Func 9: 0
c910f05c37: CPU Core Temp 1: N/A
c910f05c37: CPU Core Temp 10: N/A
c910f05c37: CPU Core Temp 11: N/A
c910f05c37: CPU Core Temp 12: N/A
c910f05c37: CPU Core Temp 13: N/A
c910f05c37: CPU Core Temp 14: N/A
c910f05c37: CPU Core Temp 15: N/A
c910f05c37: CPU Core Temp 16: N/A
c910f05c37: CPU Core Temp 17: N/A
c910f05c37: CPU Core Temp 18: N/A
c910f05c37: CPU Core Temp 19: N/A
c910f05c37: CPU Core Temp 2: N/A
c910f05c37: CPU Core Temp 20: N/A
c910f05c37: CPU Core Temp 21: N/A
c910f05c37: CPU Core Temp 22: N/A
c910f05c37: CPU Core Temp 23: N/A
c910f05c37: CPU Core Temp 24: N/A
c910f05c37: CPU Core Temp 3: N/A
c910f05c37: CPU Core Temp 4: N/A
c910f05c37: CPU Core Temp 5: N/A
c910f05c37: CPU Core Temp 6: N/A
c910f05c37: CPU Core Temp 7: N/A
c910f05c37: CPU Core Temp 8: N/A
c910f05c37: CPU Core Temp 9: N/A
c910f05c37: CPU Diode 1: 40 C (104 F)
c910f05c37: CPU Diode 2: 38 C (100 F)
c910f05c37: CPU Func 1: 0
c910f05c37: CPU Func 2: 0
c910f05c37: CPU VDD Curr: N/A
c910f05c37: CPU VDD Volt: N/A
c910f05c37: CPU1 Temp: N/A
c910f05c37: CPU2 Temp: N/A
c910f05c37: Checkstop: 0
c910f05c37: DIMM Func 1: 0
c910f05c37: DIMM Func 10: 0
c910f05c37: DIMM Func 11: 0
c910f05c37: DIMM Func 12: 0
c910f05c37: DIMM Func 13: 0
c910f05c37: DIMM Func 14: 0
c910f05c37: DIMM Func 15: 0
c910f05c37: DIMM Func 16: 0
c910f05c37: DIMM Func 17: 0
c910f05c37: DIMM Func 18: 0
c910f05c37: DIMM Func 19: 0
c910f05c37: DIMM Func 2: 0
c910f05c37: DIMM Func 20: 0
c910f05c37: DIMM Func 21: 0
c910f05c37: DIMM Func 22: 0
c910f05c37: DIMM Func 23: 0
c910f05c37: DIMM Func 24: 0
c910f05c37: DIMM Func 25: 0
c910f05c37: DIMM Func 26: 0
c910f05c37: DIMM Func 27: 0
c910f05c37: DIMM Func 28: 0
c910f05c37: DIMM Func 29: 0
c910f05c37: DIMM Func 3: 0
c910f05c37: DIMM Func 30: 0
c910f05c37: DIMM Func 31: 0
c910f05c37: DIMM Func 32: 0
c910f05c37: DIMM Func 4: 0
c910f05c37: DIMM Func 5: 0
c910f05c37: DIMM Func 6: 0
c910f05c37: DIMM Func 7: 0
c910f05c37: DIMM Func 8: 0
c910f05c37: DIMM Func 9: 0
c910f05c37: DIMM1 Temp: N/A
c910f05c37: DIMM10 Temp: N/A
c910f05c37: DIMM11 Temp: N/A
c910f05c37: DIMM12 Temp: N/A
c910f05c37: DIMM13 Temp: N/A
c910f05c37: DIMM14 Temp: N/A
c910f05c37: DIMM15 Temp: N/A
c910f05c37: DIMM16 Temp: N/A
c910f05c37: DIMM17 Temp: N/A
c910f05c37: DIMM18 Temp: N/A
c910f05c37: DIMM19 Temp: N/A
c910f05c37: DIMM2 Temp: N/A
c910f05c37: DIMM20 Temp: N/A
c910f05c37: DIMM21 Temp: N/A
c910f05c37: DIMM22 Temp: N/A
c910f05c37: DIMM23 Temp: N/A
c910f05c37: DIMM24 Temp: N/A
c910f05c37: DIMM25 Temp: N/A
c910f05c37: DIMM26 Temp: N/A
c910f05c37: DIMM27 Temp: N/A
c910f05c37: DIMM28 Temp: N/A
c910f05c37: DIMM29 Temp: N/A
c910f05c37: DIMM3 Temp: N/A
c910f05c37: DIMM30 Temp: N/A
c910f05c37: DIMM31 Temp: N/A
c910f05c37: DIMM32 Temp: N/A
c910f05c37: DIMM4 Temp: N/A
c910f05c37: DIMM5 Temp: N/A
c910f05c37: DIMM6 Temp: N/A
c910f05c37: DIMM7 Temp: N/A
c910f05c37: DIMM8 Temp: N/A
c910f05c37: DIMM9 Temp: N/A
c910f05c37: FW Boot Progress: 0                    (Firmware progress)
c910f05c37: Fan 1: N/A
c910f05c37: Fan 2: N/A
c910f05c37: Fan 3: N/A
c910f05c37: Fan 4: N/A
c910f05c37: Fan Power A: 0 Watts (0 BTUs/hr)
c910f05c37: GPU Func 1: N/A
c910f05c37: GPU Func 2: N/A
c910f05c37: GPU Func 3: N/A
c910f05c37: GPU Func 4: N/A
c910f05c37: GPU Sense: 0 Watts (0 BTUs/hr)
c910f05c37: GPU Temp 1: N/A
c910f05c37: GPU Temp 2: N/A
c910f05c37: GPU Temp 3: N/A
c910f05c37: GPU Temp 4: N/A
c910f05c37: Host Status: 0                    (soft-off)
c910f05c37: Mem Buf Func 1: 0
c910f05c37: Mem Buf Func 2: 0
c910f05c37: Mem Buf Func 3: 0
c910f05c37: Mem Buf Func 4: 0
c910f05c37: Mem Buf Func 5: 0
c910f05c37: Mem Buf Func 6: 0
c910f05c37: Mem Buf Func 7: 0
c910f05c37: Mem Buf Func 8: 0
c910f05c37: Mem Buf Temp 1: N/A
c910f05c37: Mem Buf Temp 2: N/A
c910f05c37: Mem Buf Temp 3: N/A
c910f05c37: Mem Buf Temp 4: N/A
c910f05c37: Mem Buf Temp 5: N/A
c910f05c37: Mem Buf Temp 6: N/A
c910f05c37: Mem Buf Temp 7: N/A
c910f05c37: Mem Buf Temp 8: N/A
c910f05c37: Mem Cache Power: 0 Watts (0 BTUs/hr)
c910f05c37: Mem Proc0 Pwr: 0 Watts (0 BTUs/hr)
c910f05c37: Mem Proc1 Pwr: 0 Watts (0 BTUs/hr)
c910f05c37: Motherboard Flt: 0
c910f05c37: OCC 1 Active: 0
c910f05c37: OCC 2 Active: 0
c910f05c37: OS Boot: 0
c910f05c37: PCI: 0
c910f05c37: PCI Clock Fault: 0
c910f05c37: PCIE Proc0 Pwr: 0 Watts (0 BTUs/hr)
c910f05c37: PCIE Proc1 Power: 0 Watts (0 BTUs/hr)
c910f05c37: PS Derating Fac: 0                    (OEM Reserved 200)
c910f05c37: PSU Fault 1: 0                    (Present)
c910f05c37: PSU Fault 2: 0                    (Present)
c910f05c37: Proc0 Power: 0 Watts (0 BTUs/hr)
c910f05c37: Proc1 Power: 0 Watts (0 BTUs/hr)
c910f05c37: Quick Power Drop: 0                    (IERR)
c910f05c37: Ref Clock Fault: 0
c910f05c37: System Event: 0
c910f05c37: TOD Clock Fault: 0
c910f05c37: Watchdog: 0
c910f05c37: LED status not supported on this system
