### ISSUE TITLE
Unable to open kickstart file

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#2342]
Below transcript taken from IRC

<D_FOY> I've just upgraded xcat to 2.12.4 and upon stateful installs I'm getting this error "Unable to open input kickstart file: Could not open/read file:///tmp/partitioning". Has anyone experienced something similar?

<arif-ali> D_FOY, did you manage to resolve your partitioning issue?

<D_FOY> arif-ali, I did the new pre.rh is calling it /tmp/partitionfile but the installer is looking for /tmp/partitioning so I put the old pre.rh back in place

**Comment by arif-ali** [comment]
<D_FOY> I haven't upgraded to that yet just incase there are any bugs. The issue only occured with rhels6 which uses pre.rh and rhels7 uses a pre.rh.rhels7 so no issue occured with rhels7

**Comment by immarvin** [comment]
hi @arif-ali ,seems D_FOY is using the customized template for osimage, there are some modification in default template file shipped in xCAT.

if this is the case, please see ``diff <custimied tmpl> <xCAT shipped tmpl>`` for the modifications, he might need to update the customized template file  based on the latest version of the template file.  

If the customization is on partition scheme, xCAT supports the customized partitionfile or partition script with "linuximage.partitionfile", this is the recommended and stable way, please refer to manpage of ``linuximage.partitionfile`` or http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_partition.html for details.

**Comment by immarvin** [comment]
no response, close this issue first, please reopen it any update, thanks

**Comment by davemx-5** [comment]
Hi immarvin. D_FOY here. I was using a custom template previously. Then set about changing everthing to xCAT defaults before I upgraded. Everything was running fine before the upgrade with the standard xCAT template. However issue only occurred when I upgraded xCAT, then it began to complain about /tmp/partitioning vs /tmp/partitionfile. The error was silenced by putting in place the previous pre.rh.

I've now started looking at this again and discovered that the osimage for rhels6.2 is not using the partitionfile in the osimage definitions. For reference this is my definitions:

imagetype=linux
    osarch=x86_64
    osname=Linux
    osvers=rhels6.2
    otherpkgdir=/install/post/otherpkgs/rhels6.2/x86_64/qmul
    otherpkglist=/install/apocrita/otherpkgs/sl6/compute.rhels6.x86_64.otherpkgs.pkglist
    partitionfile=/install/apocrita/partfile/sl6/compute_sm.partfile
    pkgdir=/install/rhels6.2/x86_64
    pkglist=/install/apocrita/pkgs/sl6/compute.rhels6.x86_64.pkglist
    profile=compute
    provmethod=install
    synclists=/install/apocrita/syncfiles/sl6/compute.synclist
    template=/install/apocrita/templates/sl6/compute.rhels6.x86_64.tmpl

**Comment by immarvin** [comment]
response from D_FOY:
````
Hi immarvin. D_FOY here. I was using a custom template previously. Then set about changing everthing to xCAT defaults before I upgraded. Everything was running fine before the upgrade with the standard xCAT template. However issue only occurred when I upgraded xCAT, then it began to complain about /tmp/partitioning vs /tmp/partitionfile. The error was silenced by putting in place the previous pre.rh.

I've now started looking at this again and discovered that the osimage for rhels6.2 is not using the partitionfile in the osimage definitions. For reference this is my definitions:

imagetype=linux
osarch=x86_64
osname=Linux
osvers=rhels6.2
otherpkgdir=/install/post/otherpkgs/rhels6.2/x86_64/qmul
otherpkglist=/install/apocrita/otherpkgs/sl6/compute.rhels6.x86_64.otherpkgs.pkglist
partitionfile=/install/apocrita/partfile/sl6/compute_sm.partfile
pkgdir=/install/rhels6.2/x86_64
pkglist=/install/apocrita/pkgs/sl6/compute.rhels6.x86_64.pkglist
profile=compute
provmethod=install
synclists=/install/apocrita/syncfiles/sl6/compute.synclist
template=/install/apocrita/templates/sl6/compute.rhels6.x86_64.tmpl
````

**Comment by immarvin** [comment]
hi @davemx-5 , the default template file shipped by xcat is ``/opt/xcat/share/xcat/install/rh/compute.rhels6.x86_64.tmpl``, is ``/install/apocrita/templates/sl6/compute.rhels6.x86_64.tmpl`` different with it?

**Comment by davemx-5** [comment]
hi @immarvin, yes there was a difference I was using the old rhels6 template with the new pre.rh which was the problem. It's solved now and running as normal. Thank you for your help. It's a very silly mistake!ha

**Comment by whowutwut** [comment]
I think this is resolved, so closing, please re-open if needed.

**Comment by samveen** [comment]
@vikaskaprwan333 please change to the shell tab ( `switch tab` as listed in the screenshot), and check the contents of the kickstart file. That should help you with tracing the issue. Use that information to open a new issue, rather than reuse this closed one.
