### ISSUE TITLE
doxcat not waiting long enough before ALLUP_NICS query during provisioning

### ISSUE THREAD

**Issue by adambertsch** [xcat2/xcat-core#2345]
In xcat-core/xCAT-genssis-scripts/bin/doxcat there's a section around line 197 that tries to get the names of all of the interfaces that have link UP.  It then starts a dhclient for each of those interfaces.  If no interfaces are found, it sleeps and tries again.

The problem appears to be that if one interface is up, but the others are not, we can continue.  If you don't have link up yet on the interface where you expect DHCP to work, the code continues on very quickly and then you are dropped to a shell at line 233 and provisioning stops since dhclient was never started for the interface where you have a DHCP server available.

Invoking /usr/bin/doxcat again after a short delay results in successful provision because link has come up by this time.  

The challenge appears to be to know how long is "long enough" to assume link has come up on all interfaces.  I expect that adding a sleep 5 or 10 seconds is probably enough and can submit a pull request to that effect.  However, I'm very much open to ideas about how to more reliably determine that you got an address on the boot interface (on P series where BOOTIF is not defined).

**Comment by immarvin** [comment]
hi @zet809 ,would you please take a look at this?

**Comment by zet809** [comment]
@adambertsch Can you show me the version of xcat-genesis-base you are using with "rpm -qa | grep -i xcat-genesis-base" for RH and 'dpkg -l |  grep -i xcat-genesis-base' for ubuntu? We had fixed this issue in a xCAT-genesis-base Nov 23 build.

**Comment by adambertsch** [comment]
We're on RHEL, and the version is the 2.12.4 release (IBM Garrison ESP supported level), although the code I was looking at above was xcat-core master from today.

[root@rzmanta22 ~]# rpm -qa |grep -i xcat-genesis-base
xCAT-genesis-base-x86_64-2.12-snap201607221057.noarch
xCAT-genesis-base-ppc64-2.12-snap201610250931.noarch
[root@rzmanta22 ~]# 

Looks like the snap is older than your fix.  I will see if I can find the commit and apply it.

**Comment by adambertsch** [comment]
I looked at the fix for #1640 and it looks like it might be a subtly different issue.

My issue is that there is a 10Gb fiber nic with link, and 2x 1Gb copper nic with link.  But the fiber nic comes up first.  However, the 10Gb fiber nic is an external connection, and DHCP is over the internal 1Gb management nic.  So we dhclient to 10Gb and move on, with dhclient never running on the copper nics.

**Comment by adambertsch** [comment]
It appears that the 10Gb nic comes up about 23 seconds after boot, where the 1Gb comes up about 29 seconds after boot.  If the first time we run through this part of doxcat is between 23 and 29 seconds we fail.  If it is before 23 second we delay and it works OK, and if after 29 seconds everyone is up and we are OK.

**Comment by zet809** [comment]
@adambertsch Hi, it is not about issue 1640, the pull request #2187 is the correct fix this defect.
In the fix, we will wait 2+number_of_nics seconds for all the LINKed NICs to be UP.

**Comment by adambertsch** [comment]
Got it.  Closing with my thanks!
