### ISSUE TITLE
[FVT]update script pre_deploy_sn  to support PostgreSQL database in automation test bucket

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2346]
We need to support both Mysql and PostgreSQL in automaton bucket. Need to update pre_deploy_sn to run PostgreSQL setup script.

```
$cmd = "XCATMYSQLADMIN_PW=12345 XCATMYSQLROOT_PW=12345 /opt/xcat/bin/mysqlsetup -i -V";
runcmd("$cmd");

$cmd = "echo \"GRANT ALL on xcatdb.* TO xcatadmin@\'%\'  IDENTIFIED BY \'12345\'\;\" | mysql -u root -p12345";
runcmd("$cmd");
```

**Comment by tingtli** [comment]
Move to 2.13.2 since this is not high priority

**Comment by tingtli** [comment]
We need to run some test for this fix. Move to 2.13.3

**Comment by hu-weihua** [comment]
We don't have hard ware resource to verify it in xcat2.13.3 sprint 2, all the resource have been used to support 2.13.3 release verification. 

Due to we have planed to do postgresql test in 2.13.4, so we can move this issue verification to 2.13.4.

**Comment by hu-weihua** [comment]
It seems this item has lower priority than other items in 2.13.4 sprint2, so move this one to 2.13.5 sprint 1.

**Comment by hu-weihua** [comment]
After fixing one bug, this feature has worked. close this job.
