### ISSUE TITLE
[2.11]FVT:rflash support on IBM Power S822LC

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#235]
This issue is opened to trace the support of rflash on IBM Power S822LC machine.

**Comment by zet809** [comment]
Assign to Cheng Long Since he is working on rflash item.

**Comment by chenglch** [comment]
@tingtli  This code has been merged now, you can verify this feature.

**Comment by zet809** [comment]
The pull request num for rflash code are: 355, 391, 415
For dependency, the ipmitool-xcat-1.8.15 had been uploaded to GSA, a new xcat-dep is needed.
