### ISSUE TITLE
[DEV] No node defined for a switch & switchport which got MAC address 

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#2364]
The 2nd part of issue #1567 
The situation is, when doing switch based hardware discovery, a MAC address passed through a switchport, but there is no pre-defined node matching this switchport.
This issue is supposed to be fixed with tools like Ansible to integrate xcatprobe discovery and xcatprobe switch-macmap subcommands.

**Comment by robin2008** [comment]
won't fix until we get more detail requirement.
