### ISSUE TITLE
Syncfiles cannot create symlinks

### ISSUE THREAD

**Issue by ConstipatedNinja** [xcat2/xcat-core#2368]
It appears that the syncfiles function can't place down symlinks. Writing a script to handle one or two symlink creations is no big deal, but for the sake of having everything in the same place I would love it if the functionality could be added to produce symlinks via syncfiles.

Thanks!

**Comment by daniceexi** [comment]
Use postscript of syncfiles can satisfy your requirement.
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html#postscript-support

**Comment by immarvin** [comment]
no response, close it first. please reopen it any update
