### ISSUE TITLE
Unsupported character in bootparams.addkcmdline

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#2392]
It is not possible to use the character "," in bootparams.addkcmdline. It alsways gets replaces by a space in elilo files.
I need it for UV2000 to set some console parameters like 
`earlyprintk=ttyS0,115200n8` console=ttyS0,115200n`

Affected Version:
Version 2.11.1 (git commit b6e4c8ca1847bf574d7e86687d74a7f2576d428a, built Thu Apr 14 09:32:27 EDT 2016)

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2397

**Comment by immarvin** [comment]
hi @Phhere ,would you please verify the fix? thanks

**Comment by whowutwut** [comment]
@tingtli  Can you help find someone in FVT to validate this fix so we can close the issue?

**Comment by tingtli** [comment]
@junxiawang Please help verify this bug. Thanks!
