### ISSUE TITLE
[FVT]:configcumulus --switches edgecoresw1 --all could not find the license file

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2396]
xCAT 2.13

This is not included in the cumulus documentation. I just run some test for the script. It is a nice to have function. So, i open this in 2.13.2. 

```
[root@fs4 /]# /opt/xcat/share/xcat/scripts/configcumulus --switches edgecoresw1 --all
/root/.ssh/known_hosts updated.
Original contents retained as /root/.ssh/known_hosts.old
ssh configured for edgecoresw1
install_license
file =
 is not exist
start to config_snmp
echo 'US/Eastern'>/etc/timezone;dpkg-reconfigure --frontend noninteractive tzdata
xdsh edgecoresw1 echo 'US/Eastern'>/etc/timezone;dpkg-reconfigure --frontend noninteractive tzdata
```
Take a look at the help information.
```
[root@fs4 ~]# /opt/xcat/share/xcat/scripts/configcumulus -h
Usage:
    configcumulus -h│--help
    configcumulus --switches switchnames --ssh
    configcumulus --switches switchnames --license filename
    configcumulus --switches switchnames --snmp [--user snmp_user] [--password snmp_password] [--group snmp_group]
    configcumulus --switches switchnames --ntp

    To set ssh, install license(license file: /root/license.txt), config snmp and ntp:
        configcumulus --switches switchnames --all

[root@fs4 ~]# ls /root/license.txt
/root/license.txt
```

**Comment by immarvin** [comment]
only the ``configcumulus --switches switchnames --ssh`` is the documented option, the rest options should be supported by postsctipts,  is it ok to remove the other options? @cxhong

**Comment by cxhong** [comment]
I like to keep those options around until cumulus switch process is well defined.

**Comment by tingtli** [comment]
@cxhong @immarvin  I could not find /opt/xcat/share/xcat/scripts/configcumulus in today's build, why?

**Comment by immarvin** [comment]
renamed to configonie see https://github.com/xcat2/xcat-core/commit/f843dcad3cc9484674caa4d75a877ce333f23226

**Comment by cxhong** [comment]
@tingtli ,  yes,  it changed to /opt/xcat/share/xcat/scripts/configonie at PR #2395

**Comment by tingtli** [comment]
I have review the defect and tried the verification on fs4. Since edgecoresw1 is down. The test failed, but the option is realized. Close this bug.
