### ISSUE TITLE
[FVT]:makentp -a returns NTP maynot be synchronized on servicenode

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2398]
xCAT 2.13.1
Seems I only see this problem on sles11.4.   Here is the steps to reproduce it.

1. Setup mn and install SN
```
c910f02c01p13:~ # lsxcatd -v
Version 2.13.1 (git commit 2847ea1da30b546540d076676ee18d4c23900307, built Mon Jan  9 06:15:41 EST 2017)
c910f02c01p13:~ # cat /etc/*release*
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64"
cat: /etc/lsb-release.d: Is a directory
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
SUSE Linux Enterprise Server 11 (ppc64)
VERSION = 11
PATCHLEVEL = 4
```
2. Config SN with following configuration. Make sure setupntp=1 on servicenode
```
c910f02c01p13:~ # lsdef -l c910f02c01p07
Object name: c910f02c01p07
    arch=ppc64
    cons=hmc
    currchain=boot
    currstate=boot
    groups=all
    hcp=c910hmc01
    hidden=0
    hwtype=lpar
    id=7
    initrd=xcat/osimage/sles11.4-ppc64-install-service/initrd64
    kcmdline=quiet autoyast=http://c910f02c01p13:80/install/autoinst/c910f02c01p07 install=http://c910f02c01p13:80/install/sles11.4/ppc64/1 netdevice=e6:d4:d1:e7:f6:03  dhcptimeout=150
    kernel=xcat/osimage/sles11.4-ppc64-install-service/linux64
    mac=e6:d4:d1:e7:f6:03
    mgt=hmc
    netboot=grub2
    nodetype=ppc
    os=sles11.4
    parent=c910f02fsp01
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    pprofile=c910f02c01p07
    profile=service
    provmethod=sles11.4-ppc64-install-service
    setupntp=1
    status=booted
    statustime=01-09-2017 11:21:16
    updatestatus=failed
    updatestatustime=01-10-2017 21:25:35
```
3. make sure MN has correctly ntp server
```
c910f02c01p13:~ # ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l   52   64  377    0.000    0.000   0.000
```
4. make sure ntp attributes in site table is correctly configured
```
c910f02c01p13:~ # tabdump site |grep -i ntp
"ntpservers","<xcatmaster>",,
```
5. run makentp on mn
```
c910f02c01p13:~ # makentp -a
configuring management node: c910f02c01p13.
configuring service nodes: c910f02c01p07
c910f02c01p07: xcatdsklspost: downloaded postscripts successfully
c910f02c01p07: Tue Jan 10 21:24:53 EST 2017 Running postscript: setupntp
c910f02c01p07: Checking for network time protocol daemon (NTPD): ..unused
c910f02c01p07: /usr/sbin/rcntp ntptimeset
c910f02c01p07: /usr/sbin/rcntp ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
c910f02c01p07: postscript: setupntp exited with code 1
c910f02c01p07: Running of postscripts has completed.
```
6. login serivce node to take a look
```
c910f02c01p07:~ # service ntp status
Checking for network time protocol daemon (NTPD):                                                                                                                                                unused
```
7. If start ntp service on service node. and run makentp -a again, will get another message
```
c910f02c01p07:~ # service ntp start
Starting network time protocol daemon (NTPD)                                                                                                                                                     done
c910f02c01p07:~ # ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 c910f02c01p13.p .INIT.          16 u   12   64    0    0.000    0.000   0.000


c910f02c01p13:~ # makentp -a
configuring management node: c910f02c01p13.
configuring service nodes: c910f02c01p07
c910f02c01p07: xcatdsklspost: downloaded postscripts successfully
c910f02c01p07: Tue Jan 10 21:52:28 EST 2017 Running postscript: setupntp
c910f02c01p07: remote refid st t when poll reach delay offset jitter ============================================================================== c910f02c01p13.p .INIT. 16 u 33 64 0 0.000 0.000 0.000 Checking for network time protocol daemon (NTPD): ..running
c910f02c01p07: service ntp stop
c910f02c01p07: /usr/sbin/rcntp ntptimeset
c910f02c01p07: /usr/sbin/rcntp ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
c910f02c01p07: postscript: setupntp exited with code 1
c910f02c01p07: Running of postscripts has completed.
```

**Comment by immarvin** [comment]
seems the same scenario with https://github.com/xcat2/xcat-core/issues/2248

**Comment by tingtli** [comment]
@immarvin  although the warning message is the same, i don't  think they are the same.
Bug 2248 could not be reproduced if MN ntp server is stable and CN's clock could sync with MN at last. But seems SN could not.

**Comment by immarvin** [comment]
hi @cxhong , you mentioned the following message in the https://github.com/xcat2/xcat-core/issues/2248
````
That's what I saw on the SLES system:

took 5 to 11 mins to sync the time for MN after run makentp on MN
took 3 to 5 mins to sync the time for CN after run "updatenode CN -P setupntp" on MN
````

will ``/usr/sbin/rcntp ntptimeset`` block and wait before time synced, or it will try once and fail?

if the answer is the later, can we set a timeout value(such as 20 min) and retry ``/usr/sbin/rcntp ntptimeset`` in a loop in setupntp?

**Comment by cxhong** [comment]
currently, makentp command or setupntp postscripts will just try once, doesnt' have retry.
makentp -a will setup NTP server for both management node and the service node.  from issue #2248, we discovered MN has to wait 5 to 11 mins to sync the time,  so makentp -a command for set up service node will not work since MN time is not sync yet.    

I think we should not use makentp -a to set NTP server for service node. the correct steps should be:
`````
1) makentp   (set up NTP server for management node)
2) wait for MN be synchronized  (check with ntpq -p command)
3) then issue "updatenode SN -P setupntp"  to sync NTP server for service node.
``````

**Comment by cxhong** [comment]
ran this on my test system:
1) MN NTP server is synced.
``````
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l   36   64  377    0.000    0.000   0.000
``````````
2) run "makentp -a"
``````
# makentp -a
configuring management node: c910f03c04k12.
configuring service nodes: c910f03c04k11
c910f03c04k11: xcatdsklspost: updating VPD database
c910f03c04k11: xcatdsklspost: downloaded postscripts successfully
c910f03c04k11: Wed Jan 11 15:19:14 EST 2017 Running postscript: setupntp
c910f03c04k11: inactive
c910f03c04k11: /usr/sbin/rcntpd ntptimeset
c910f03c04k11: /usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
c910f03c04k11: postscript: setupntp exited with code 1
c910f03c04k11: Running of postscripts has completed.

# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 LOCAL(0)        .LOCL.          10 l   12   64    3    0.000    0.000   0.000

`````````
on the service node, /etc/ntp.conf is updated, but no ntpd service is running.

3) after wait for 5 mins,  the time is synced on the MN again
`````
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l    1   64   77    0.000    0.000   0.000
````````
4) then run updatenode
``````
# updatenode c910f03c04k11 -P setupntp
c910f03c04k11: xcatdsklspost: updating VPD database
c910f03c04k11: xcatdsklspost: downloaded postscripts successfully
c910f03c04k11: Wed Jan 11 15:26:07 EST 2017 Running postscript: setupntp
c910f03c04k11: inactive
c910f03c04k11: /usr/sbin/rcntpd ntptimeset
c910f03c04k11: NTPD_FORCE_SYNC_ON_STARTUP="no"
c910f03c04k11: # This works only if NTPD_FORCE_SYNC_ON_STARTUP is set
c910f03c04k11: NTPD_FORCE_SYNC_HWCLOCK_ON_STARTUP="yes"
c910f03c04k11: postscript: setupntp exited with code 0
c910f03c04k11: Running of postscripts has completed.
``````````
5) ntpd is running on the service node, but time is not sync yet.
```````
 # service ntpd status
ntpd.service - NTP Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; enabled)
   Active: active (running) since Wed 2017-01-11 15:00:41 EST; 17s ago
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 10.3.4.12       LOCAL(0)        11 u   21   64    1    0.377    0.064   0.000
`````````````
6) service node is synced after 4 mins
`````````````
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*10.3.4.12       LOCAL(0)        11 u    2   64   17    0.370    0.012   0.042
`````````````````

@immarvin , I think we can set timeout value to check if MN is synced,  then to run updatenode command in the background

**Comment by immarvin** [comment]
hi @cxhong , since ``makentp -a`` invoke "setupntp" postscript on SN, so this is a problem in ``setupntp`` instead of ``makentp`` .  Even when the ntp on MN has been synced, it might still need some time for CN or SN running "setupntp" to sync the time, it is a problem to try only once, I think we should add some retry+timeout logic around ``/usr/sbin/rcntp ntptimeset``

**Comment by tingtli** [comment]
@cxhong  Yes. If we use "updatenode SN -P setupntp". SN could be  synced after several mins. 
The problem is makentp -a could not work as design.

**Comment by cxhong** [comment]
if command /usr/sbin/rcntp ntptimeset failed,  should not exit the setupntp postscript, instead of continue configure the service node and start up the ntpd service for the SN.  Once the MN is synced,  the SN will  sync too.

**Comment by whowutwut** [comment]
I agree with @cxhong , if `makentp -a` is re-starting the NTP server on the management node, then it will never be "ready" to provide the service nodes synchronization.  In this case we should just continue and configure the ntp daemons correctly so that it will sync the times on the nodes once the MN is ready.

**Comment by immarvin** [comment]
ok ,if ``makentp`` is to setup ntp server and not guarantee the time is synced on the command completion,  should we make the similar change for ``makentp`` to prevent the "unsync-exit on error" error on management node? 
````
346     #update the time now
347     if ($ntp_master) {
348         my $cmd;
349         if ($os =~ /sles/) {
350             if (-f "/usr/sbin/rcntpd") {
351                 $cmd = "/usr/sbin/rcntpd ntptimeset";
352             } elsif (-f "/usr/sbin/rcntp") {
353                 $cmd = "/usr/sbin/rcntp ntptimeset";
354             } else {
355                 $cmd = "sntp -P no -r $ntp_master";
356             }
357         } else {
358             $cmd = "ntpdate -t5 $ntp_master";
359         }
360         if ($verbose) {
361             send_msg(\%request, 0, " ...updating the time now. $cmd");
362         }
363         my $result = xCAT::Utils->runcmd($cmd, 0);
364         if ($verbose) {
365             send_msg(\%request, 0, "    $result");
366         }
367         if ($::RUNCMD_RC != 0) {
368             send_msg(\%request, 1, "Error from command $cmd\n    $result.");
369             return 1;
370         }
371     }
````

**Comment by tingtli** [comment]
@cxhong  If we don't return the status but just give the messages to users, Then we could not help user understand if the ntp server is correctly configured.   Users need to double check themselves.  So, i think, to make this command more friendly. We probably needs to do either one
1. Wait about 15 mins in  setupntp until ntp service is correctly setup or timeout
or 2. In the  warning message, gives steps for users for how to check the ntp service. .. 
or 3. If failed , how to re-run
What's your opinion?

**Comment by cxhong** [comment]
@immarvin , for the MN,  I think we should return and ask users to check the expntpservers, since we don't have control of expntpservers.  I will modify the error message.
@tingtli I will update the message, but will not consider first options.

**Comment by tingtli** [comment]
From the test result. It seems that re-run will help to configure the ntp service. 
@cxhong @immarvin What is your decision for this issue? To change code for makentp or to prohibit the makentp -a but use updatenode to sync service node?

**Comment by cxhong** [comment]
Can we add recommendation to use updatenode instead of "makentp -a" on the doc for service node?

**Comment by zet809** [comment]
So, the whole step will be:
1. before SN deploying, run 'makentp -a' to setup ntpserver and sync up time for MN.
2. 15 minutes later, after ntp is synced up on MN, adding 'setupntp' to the postbootscript of SN, starting deploy SN
3. After the SN is installed, the ntp service is ready, and time is sync up. And it can be the ntp server for CN.
Is it right?
If not, what is the correct logic is? Thx!

**Comment by tingtli** [comment]
@zet809 what you said is the original steps. The problem is postscripts on sn will return error on your step 3.

**Comment by cxhong** [comment]
If MN is synced,   always run ````updatenode setupntp```` command or adding ````setupntp```` to the postbootscripts for SN or CN.

If MN is not synced 
1) if ntp server is external , can run "makentp -a" to sync up time for both MN or SN
2) if ntp server is MN,  run ````makentp```` to sync up time for MN,  wait until MN time is synced, then issue ````updatenode setupntp``` command

**Comment by zet809** [comment]
Hi, @cxhong , as @immarvin had mentioned above, even when the ntp on MN has been synced, it might still need some time for CN or SN running "setupntp" to sync the time. So the  ````setupntp````postbootscript will failed to try only one time. Do you think it is possible to add some retry+timeout logic around /usr/sbin/rcntp ntptimeset?

**Comment by cxhong** [comment]
talked to @zet809 about this issue, he was concern even MN has been synced,  the CN still need some time to sync up time with MN.   I retest this on sles 12.2 

first case:  MN is not synced,  CN will get Warning message for setupntp postscripts
````
fs2vm101:~ # ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 LOCAL(0)        .LOCL.          10 l   15   64    1    0.000    0.000   0.000
fs2vm101:~ # updatenode fs2vm111 -P setupntp
fs2vm111: vpdupdate is not supported on the pSeries KVM Guest platform
fs2vm111: xcatdsklspost: updating VPD database
fs2vm111: xcatdsklspost: downloaded postscripts successfully
fs2vm111: Thu Apr 20 14:16:28 EDT 2017 Running postscript: setupntp
fs2vm111: inactive
fs2vm111: /usr/sbin/rcntpd ntptimeset
fs2vm111: WARNING:
fs2vm111:     /usr/sbin/rcntpd ntptimeset failed, NTP may not be synchronized on NTP server
fs2vm111:     please wait for NTP synchronized, may take at least 15 mins
fs2vm111:     use 'ntpq -p' command (output has * or + sign)  to validate the NTP server
fs2vm111:     run 'updatenode nodename -P setupntp' if NTP is synced on NTP server but nodename is not synced
fs2vm111: Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
fs2vm111: postscript: setupntp exited with code 0
fs2vm111: Running of postscripts has completed.
```````

second case:  MN is synced,  CN will be synced after ran "updatenode setupntp" 
````
fs2vm101:~ # ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l    6   64  377    0.000    0.000   0.000
fs2vm101:~ # updatenode fs2vm111 -P setupntp
fs2vm111: vpdupdate is not supported on the pSeries KVM Guest platform
fs2vm111: xcatdsklspost: updating VPD database
fs2vm111: xcatdsklspost: downloaded postscripts successfully
fs2vm111: Thu Apr 20 14:23:33 EDT 2017 Running postscript: setupntp
fs2vm111: active
fs2vm111: systemctl stop ntpd
fs2vm111: /usr/sbin/rcntpd ntptimeset
fs2vm111: postscript: setupntp exited with code 0
fs2vm111: Running of postscripts has completed.
fs2vm101:~ # xdsh fs2vm111 "ntpq -p"
fs2vm111:      remote           refid      st t when poll reach   delay   offset  jitter
fs2vm111: ==============================================================================
fs2vm111: *10.3.31.101     LOCAL(0)        11 u   13   64    1    0.222   -0.841   0.000
`````

**Comment by zet809** [comment]
Hi, @cxhong , the solution looks good to me, thx a lot!

**Comment by tingtli** [comment]
@cxhong @zet809 Does that mean if makentp -a fails, we need to run "updatenode setupntp" on MN for SN again?

**Comment by cxhong** [comment]
@tingtli , Yes.  We should always recommend users to use "updatenode setupntp",  only use "makentp" (without -a) command to sync time for MN.

**Comment by cxhong** [comment]
@zet809 ,  the code is already merged in the 2.13.2.

**Comment by zet809** [comment]
Hi, @cxhong , within manpage of makentp, update is only suggest for Compute Node. But the issue for us seems to be for SN. 
When we run 'makentp -a' to configure NTP server both on MN and SN, the time sync up will be failed for SN as the MN is re-sync time for itself and ntp server maybe not ready. 
So, for SN, updatenode shall also be suggested.
Or, it is possible to add an option for makentp that before dispatch setupntp on SN, makentp shall wait until the NTP server on MN is ready? If not, makentp won't wait before dispatch setupntp. Then setupntp will output a warning message from SN.
What is your idea?

**Comment by zet809** [comment]
Hi, @tingtli , @cxhong had modified the manpage of makentp, will you pls take a look at whether it make sense to this defect? Thx a lot!

**Comment by whowutwut** [comment]
@hu-weihua Can you help or find someone to verify this and close out? thanks

**Comment by tingtli** [comment]
I have reviewed the modification for the makentp manpage and agree to close this defect.
