### ISSUE TITLE
Support for package groups in otherpkgs

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#2406]
It would be great when support for package groups would be available in otherpkgs like in ospkgs

**Comment by immarvin** [comment]
hi @Phhere , where are the package groups in? the os iso?

**Comment by Phhere** [comment]
In my case the package groups came from the hardware vendor iso for some additional kernel modules and so on. I unpacked the iso and integrated it into the custom repo and included the groups in repodata

**Comment by immarvin** [comment]
please provide the linux distribution of your compute nodes, as well as a sample otherpkglist including the package groups if convenient.

**Comment by Phhere** [comment]
Redhat 7.3
Hardware: SGI UV 2000
otherpkglist:
`
iozone
iperf
htop
lldpd
#NEW_INSTALL_LIST#
gpfs.base-4.2.0-0
gpfs.docs
gpfs.ext
gpfs.gpl
gpfs.msg.en_US
#NEW_INSTALL_LIST#
gpfs.base-4.2.0-2
#NEW_INSTALL_LIST#
@SGI MPI
@SGI Foundation Software
`
The Problem maybe is that i put the groups into subfolders of the otherpkgdir

**Comment by immarvin** [comment]
hi @Phhere , if you put the groups into subfolders of otherpkgdir, the pkglist entries can be specified as ``<subdirname>/@<groupname>``

**Comment by immarvin** [comment]
no response, close this issue
