### ISSUE TITLE
Regular Expression expansion is not support for nicips keywords

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2412]
Doing some testing today, it looks like the `nicips.<interface>` keyword in the group is not able to expand regular expressions.  Here's a simple example...

```
[root@fs4 research92]# mkdef -t group -o testnicips 
Warning: Cannot determine a member list for group 'testnicips'.
[root@fs4 research92]# chdef -t group -o testnicips ip='|\D+(\d+)\D+(\d+)|10.1.($1).($2)|'
1 object definitions have been created or modified.
[root@fs4 research92]# chdef -t group -o testnicips nicips.eth1='|\D+(\d+)\D+(\d+)|10.1.($1).($2)|'
1 object definitions have been created or modified.
[root@fs4 research92]# lsdef -t group -o testnicips
Object name: testnicips
    grouptype=static
    ip=|\D+(\d+)\D+(\d+)|10.1.($1).($2)|
    members=
    nicips.eth1=|\D+(\d+)\D+(\d+)|10.1.($1).($2)|
```

Creating a test node....
```
[root@fs4 research92]# mkdef frame10node10 groups=testnicips
1 object definitions have been created or modified.
[root@fs4 research92]# lsdef frame10node10
Object name: frame10node10
    groups=testnicips
    ip=10.1.10.10
    nicips.eth1=|\D+(\d+)\D+(\d+)|10.1.($1).($2)|
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```

As you can see, the ip field expanded correctly, but the `nicips.eth1` field did not.  
I think all the IP related keywords should support this expansion....

Are there other keywords that should support this but does not?

**Comment by zet809** [comment]
Hi, @whowutwut , @chenglch has experience about how to inherit attributes from groups, I'd like him to take a look at this issue.

**Comment by whowutwut** [comment]
I am running with build: 
```
Version 2.13.1 (git commit f834844774a6bef8173db8eb17b23741dd36596f, built Wed Jan 18 06:16:23 EST 2017)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=10.3.25.1|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=10.3.25.1
dbadmin=xcatadm
```

and the node definition has: 

```
    nicips.ib0=|\D+(\d+)\D+(\d+)|20.1.($1*1).($2*1)|
    nictypes.ib0=Infiniband
```

and running `makehosts` , I see the following generated in `/etc/hosts`... 
```
192.168.23.3 frame23cn03 frame23cn03.pok.stglabs.ibm.com
\D+(\d+)\D+(\d+) frame23cn03-ib0 frame23cn03-ib0.pok.stglabs.ibm.com
20.1.($1*1).($2*1) frame23cn03-ib0 frame23cn03-ib0.pok.stglabs.ibm.com
```

Will update to the latest and validate this again with the fix.

**Comment by chenglch** [comment]
@whowutwut , is the nics value from `lsdef <node>` correct?  If so, I think `makehosts` and `configurenics` get the nics attributes from nics table directly, they should be enhanced in the other patch. @bybai , any idea?

**Comment by bybai** [comment]
@chenglch , yes, makehosts and confignics should be enhanced at the same time.

**Comment by whowutwut** [comment]
Running an updated build...  before 
```
[root@fs3 research92]# lsdef c460c0001
Object name: c460c0001
...
    nichostnamesuffixes.ib0=-ib0
    nichostnamesuffixes.ib1=-ib1
    nicips.ib0=|\D+(\d+)\D+(\d+)|10.10.((($2-1)/18+1)%10).((($2-1)%18)+1)|
    nicips.ib1=|\D+(\d+)\D+(\d+)|10.11.((($2-1)/18+1)%10).((($2-1)%18)+1)|
    nicnetworks.ib0=IB00
    nicnetworks.ib1=IB01
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
...

```

After with  `201702212146` build 

```
[root@fs3 research92]# lsdef c460c0001
Object name: c460c0001
...
    nichostnamesuffixes.ib0=-ib0
    nichostnamesuffixes.ib1=-ib1
    nicips.ib0=10.10.1.1
    nicips.ib1=10.11.1.1
    nicnetworks.ib0=IB00
    nicnetworks.ib1=IB01
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
```

So the regular expressions are resolved successfully now.  but the issues brought up above still exists. 

```
[root@fs3 research92]# grep c460c0001 /etc/hosts
[root@fs3 research92]# makehosts c460c0001
[root@fs3 research92]# grep c460c0001 /etc/hosts
10.1.1.1 c460c0001 c460c0001.pok.stglabs.ibm.com c460f01uXX
\D+(\d+)\D+(\d+) c460c0001-ib0 c460c0001-ib0.pok.stglabs.ibm.com 
10.10.((($2-1)/18+1)%10).((($2-1)%18)+1) c460c0001-ib0 c460c0001-ib0.pok.stglabs.ibm.com 
\D+(\d+)\D+(\d+) c460c0001-ib1 c460c0001-ib1.pok.stglabs.ibm.com 
10.11.((($2-1)/18+1)%10).((($2-1)%18)+1) c460c0001-ib1 c460c0001-ib1.pok.stglabs.ibm.com 
```

I'm going to remove the pending, let's keep this issue open to track work to fix `makehosts` `configurenics` to get those working...

**Comment by whowutwut** [comment]
@zet809  Please have someone assigned to making the additional changes required for this issue to be solved completely.   I'd like to get this done asap because it's blocking our ability to create a more complicated regex... 

 If @chenglch  is not the right person, please add another person  to this issue.

**Comment by bybai** [comment]
Hi @whowutwut ,
I opened the issue #2578 makehosts and confignics support Regular Expression for nicips in nics table to fix makehosts configurenics to get those working.
So this issue can be closed now.

**Comment by whowutwut** [comment]
Thanks, I've already verified the above pull request for this initial issue in 2.13.2 release... . Closing.
