### ISSUE TITLE
Power8 node replacement procedure.

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#2414]
When replacing a power8le node or the BMC of a power8le node, we need a procedure or tools for plugging the node in and have it discovered/provisioned using the existing node definition.

**Comment by whowutwut** [comment]
I agree that we should have some documentation here on the process of replacing a OpenPower compute node when we have xCAT configured with some hardware discovery method...   Just thinking out loud, I thin a high level process is the following: 

1. Machine is identified to be replaced 

2. Set the machine's BMC to DHCP (Should we power off compute side? #2226)) 

```
rspconfig <noderange> ip=dhcp 
```

3. Clear the mac address (If the node is being replaced, a new mac address should be detected) 
Perhaps this should be a function of `nodeset .. offline`.  @gurevichmark ? 

4. Set the node to offline 

```
nodeset <noderange> offline
```


Now, when the server is replaced and the new one is connected to the power supply, the BMC should boot and obtain a DHCP IP address. Then it's business as usual for discovery... 

```
bmcdiscover --range <range> -z -w
rsetboot /node-8335.* net 
rpower /node-8335.* boot 
```

**Comment by markprez** [comment]
COMMENT in step 2
1. Machine is identified to be replaced

2. **_New node's BMCs should be set to use DHCP, this step would be needed if a BMC was already configured statically  you wanted to reset it to DHCP._**

Set the machine's BMC to DHCP (Should we power off compute side? #2226))
rspconfig <noderange> ip=dhcp 

3.   Clear the mac address (If the node is being replaced, a new mac address should be detected)
Perhaps this should be a function of nodeset .. offline. @gurevichmark ?

4.  Set the node to offline
nodeset <noderange> offline

Now, when the server is replaced and the new one is connected to the power supply, the BMC should boot and obtain a DHCP IP address. Then it's business as usual for discovery...
bmcdiscover --range <range> -z -w
rsetboot /node-8335.* net

**Comment by whowutwut** [comment]
@markprez  I think in our situation, we're expecting the replacement machine to be coming from MFG so the server should be configured and default to be in DHCP mode.    Step 2 was to set the current machine being replaced (going out of the frame) to DHCP in order to more easily move it to another frame/rack in the datacenter and avoid the need to manually connect by Serial cable to undo the static IP configurations.   Let me update for clarity though...

**Comment by whowutwut** [comment]
@markprez  I created a simple page for documenting, is this sufficient, or requires a bit more information? I'm trying to keep it fairly generic for larger xCAT customers 

https://github.com/whowutwut/xcat-core/commit/79e8de9b9f7f5b0b47f6192b8d5be98944802f26

**Comment by markprez** [comment]
This looks good. I think you may want to clear the serial number as well. If this process was used for swapping nodes or moving them there is a problem if the serial number is in the database. Discovery will find the serial number before it does switch based discovery, this could cause a moved node to be configured with its original node information.

**Comment by daniceexi** [comment]
I think the procedure should depend on the node discovery method. 

* for the switch based discovery, we don't need to clean up the mtms and mac address for node definition, both of them will be replaced when a new node is plugged in.
* for the mtms based discovery, we need to replace the mtms to be the new node's

**Comment by whowutwut** [comment]
@markprez  interesting comments.  I wasn't really looking at the scenario where we are moving machines around, but you bring up valid points.  @daniceexi  Thanks for the comments, will make some additional changes and create a pull request.

**Comment by whowutwut** [comment]
Doc change, will close out this issue.
