### ISSUE TITLE
Missing command in genesis image

### ISSUE THREAD

**Issue by fyhertz** [xcat2/xcat-core#2422]
Hi,

xcat version: 2.13.2 (git commit 4c72fee5435fa53f40f31b41df5809b4c55e4f6b, built Tue Jan 17 06:17:05 EST 2017)

Running on ubuntu 16.04 x86_64

When running bmcsetup on a compute node, running genesis image built with mknb x86_64:
`[xCAT Genesis running on node103 /]# bmcsetup
/bin/bmcsetup: line 107: which: command not found
No ipmitool find, please install it first
`

The command "which" is missing. After manually copying the "which" sh script in the genesis image, bmcsetup seems to work.

Regards

**Comment by whowutwut** [comment]
@fyhertz Thanks for bringing this to our attention

**Comment by zet809** [comment]
@fyhertz Thanks very much for your finding, it is a defect for our script, have fixed in pull request #2424

**Comment by jonathanmills** [comment]
I discovered this the hard way last night, in 2.13.1.  Glad someone's already patched it.

**Comment by whowutwut** [comment]
This has been fixed and verified.
