### ISSUE TITLE
Customize /etc/named.conf

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2423]
Hi!

I'm wondering if there's any way in `makedns` to customize the generated `named.conf` file? 

I'm thinking including custom, site-specific directives, such as custom configuration options, logging directives, or zone delegation? It could be done by having a `/etc/named.conf.local` file whose contents would be appended to the generated `/etc/named.conf` file.

The same principle could ideally be also applied to the generation of `/etc/hosts` or `/etc/dhcpd.conf`

Any thoughts?

**Comment by kcgthb** [comment]
Actually, a mechanism to include external configuration is kind of required, as the generated `named.conf` file currently misses some of the required configuration.

For instance, Redhat provides a `/etc/named.rfc1912.zones` file which provides zone configuration for zones recommended by RFC 1912. This is missing from the `named.conf` file generated by `makedns`. As a result, resolving `localhost` is broken:
```
$ host 127.0.0.1 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#53
Aliases:

Host 1.0.0.127.in-addr.arpa. not found: 3(NXDOMAIN)
```
With the proper `include "/etc/named.rfc1912.zones";` line in `/etc/named.conf`, `localhost` resolves properly:
```
host 127.0.0.1 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#53
Aliases:

1.0.0.127.in-addr.arpa domain name pointer localhost.
```

So, could you please provide a mechanism in `makedns` to include external configuration files?

**Comment by bybai** [comment]
Hi @kcgthb , we plan to add this feature into next release. Thanks.

**Comment by whowutwut** [comment]
@bybai  Please set a milestone when you are ready to look at this issue.

**Comment by kcgthb** [comment]
Just checking to see if any plans have been made to implement customization of `/etc/named.conf`?

**Comment by zet809** [comment]
Let's close this issue.

**Comment by kcgthb** [comment]
Sorry if I missed it, but has this feature been implemented?
