### ISSUE TITLE
nvidia kernel module compile fails because of child process env pollution

### ISSUE THREAD

**Issue by david-shapiro** [xcat2/xcat-core#243]
Abstract - nvidia kernel module compile fails because of child process env pollution

This week, the IST admin team was running xcat install of firestone nodes, and after the RHEL 7.2 install completed, CUDA would not work on the nodes.

There is a work-around, but this is not something that we would want to pass onto our customers. It is also impacting the turnaround times for our node installs.

Just before the start of the national holiday, @neo954 sent us the following explanation of the problem:

*Due to my debugging, the CUDA installation problem is blame on xCAT. While running the postbootscripts in xCAT, xCAT passed over one hundred environment to its children processes. Among them, there is ARCH=ppc64le. Due to this pollution, the compiling of nvidia kernel module will failed. Since in GNU Make, environment variable will become make variable. And while user specify a ARCH, the Makefile will use it instead of calculate it by itself.*

The workaround method is re-run the postinstall script in package nvidia-kmod manually. Maybe with xdsh. Please refer the **bold** lines below.

>[root@c712f7n06 ~]# rpm -q --scripts nvidia-kmod
>postinstall scriptlet (using /bin/sh):
>**dkms add --rpm_safe_upgrade -m nvidia -v 352.39**
>**dkms build -m nvidia -v 352.39**
>**dkms install --force -m nvidia -v 352.39**
>preuninstall scriptlet (using /bin/sh):
>dkms remove --rpm_safe_upgrade -m nvidia -v 352.39 --all || :
>postuninstall scriptlet (using /bin/sh):
>if [ "$1" -eq "0" ] ; then
>    dracut -f /boot/initramfs-$(uname -r).img $(uname -r)
>fi

Can we have this problem compiling the NVIDIA kernel module resolved, please.

**Comment by whowutwut** [comment]
@david-shapiro  I edited your post to include some markdown to make it easier to read.

**Comment by whowutwut** [comment]
@daniceexi @neo954 @cxhong @pdlun92 Including some interested parties

**Comment by whowutwut** [comment]
Issue #232 opened in response to internal talks about this Bug.

**Comment by cxhong** [comment]
David:  

please Add CUDA package to pkglist instead of otherpkglist.   Node needs to reboot to activate NVIDIA driver after CUDA installation.

**Comment by david-shapiro** [comment]
thanks cxhong. We are trying this.

**Comment by david-shapiro** [comment]
John Lemek found that he could not run GPU jobs on our RHEL nodes that Joe installed using xCAT. This problem was also reported at the scrum (John M had found the same thing on his RHEL nodes)

Dave, Please update the xcat defect to add this additional problem - unable to run any gpu jobs.  Besides running nvidia-smi, the xCAT team needs to try running a gpu job to ensure that they are handling the NVIDIA support correctly. NVIDIA provides small sample gpu jobs that they can run

John and I discussed and as we need the machines to be able to run gpu jobs we decided to pull off the nvidia  stuff and reinstall and see if that would fix it  
Joan sent me this note to add to this issue:

John did the following and we can now run gpu jobs on our 2 rhel nodes
rpm -e `rpm -qa | grep "^cuda"` gpu-deployment-kit-352.39-0.ppc64le
rpm -e `rpm -qa | grep "nvidia"`
rpm -ivh cuda-repo-rhel7-7-5-local-7.5-18.ppc64le.rpm
yum install cuda

Then you need to reboot

If you need the gpu-deployment kit (LSF needs it I think) you would have to reinstall that


The blue is the new DD/CUDA that NVIDIA delivered yesterday .. recommend you use that one  as you need to  reinstall before you will be able to run jobs

**Comment by cxhong** [comment]
I able to installation cuda package on firestone nodes and ran sample example from Nivdia site

# ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 4 CUDA Capable device(s)

Device 0: "Tesla K80"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.7
  Total amount of global memory:                 11520 MBytes (12079136768 bytes)
  (13) Multiprocessors, (192) CUDA Cores/MP:     2496 CUDA Cores
.......................................................
> Peer access from Tesla K80 (GPU3) -> Tesla K80 (GPU0) : No
> Peer access from Tesla K80 (GPU3) -> Tesla K80 (GPU1) : No
> Peer access from Tesla K80 (GPU3) -> Tesla K80 (GPU2) : No

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 4, Device0 = Tesla K80, Device1 = Tesla K80, Device2 = Tesla K80, Device3 = Tesla K80
Result = PASS


So, please try put CUDA package into pkglist , then redeploy the firestone nodes.

**Comment by cxhong** [comment]
I borrowed one of nodes in the IST cluster, and provisioned it with a sample of CUDA osimage.  the node came back and works good so far.   The issue here is that we need to reboot after installing the CUDA, so the better place to add cuda is into the pkglist to get installed with the OS.  The newest documentation for CUDA installation on rhel7.2 ppc64le is located at:
http://xcat-docs.readthedocs.org/en/latest/advanced/gpu/cuda.html
