### ISSUE TITLE
tftp continued after xcatd shutdown

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#2436]
I have seen in numerous situations, where xcatd controls the tftp, to start, abut fails to stop it. I've had to on occasions kill the service, so that it releases the lock to the deirectory, it is using.

```
/usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf
```

Could we have a look at this, for the next release, so that we don't have this problem

**Comment by immarvin** [comment]
hi @arif-ali , you mentioned that ``I've had to on occasions kill the service, so that it releases the lock to the deirectory``, what do you mean by "the lock to the deirectory"? can you explain more?

thanks

**Comment by arif-ali** [comment]
I have setup HA with drbd setup, on various customer solutions. The drbd device is mounted under `/xcatdrbd`. When manually failing over from one machine to the other, on occasions, this service will still run, and therefore still hold onto it, as opened files. I am able to grab this information, by running `fuser -m /xcatdrbd`, and this usually points to a person logged in, and in one of the directories that is located under `/xcatdrbd` or a service is still running.

I hope that makes sense

**Comment by immarvin** [comment]
hi @arif-ali ,thanks for your info, we will consider this request in xCAT 2.13.2 release

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2447

**Comment by arif-ali** [comment]
Thanks @immarvin

**Comment by whowutwut** [comment]
On a simple test, it seems to stop `tftp`
```
[root@fs3 dhcp]# lsxcatd -a 
Version 2.13.2 (git commit e05ae84ee0676779c83185cb52fbd7ddac737c48, built Tue Feb  7 06:15:50 EST 2017)
This is a Management Node

[root@fs3 dhcp]# ps -ef | grep tftp
root      31991      1  0 Feb07 ?        00:00:00 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf
root      72804  72760  0 15:27 pts/0    00:00:00 grep --color=auto tftp
[root@fs3 dhcp]# service xcatd stop 
Stopping xcatd (via systemctl):                            [  OK  ]

[root@fs3 dhcp]# ps -ef | grep tftp
root      72868  72760  0 15:27 pts/0    00:00:00 grep --color=auto tftp
```

I will close for now, please re-open if you see issues

**Comment by arif-ali** [comment]
nice one, thanks for testing it @whowutwut
