### ISSUE TITLE
xdsh doesn't read credentials from the passwd table for Infiniband switches

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2441]
Hi, 

The documentation at https://xcat-docs.readthedocs.io/en/stable/advanced/networks/infiniband/switch_configuration.html says:
> If there is only one admin and one password for all the switches then put the entry in the xCAT passwd table for the admin id and password to use to login.

While this works great for Ethernet switches, it does not for Infiniband switches. This is probably related to that test: https://github.com/xcat2/xcat-core/blob/master/perl-xCAT/xCAT/DSHCLI.pm#L982
which only gets credential information from the `passwd` table for `EthSwitch`-type devices.

Would it be possible to extend it to `IBSwitch` devices too? Maybe with a different key in the `passwd` table?

**Comment by cxhong** [comment]
when config switch's username and passwd, xcat will pick up from sshusername of the switch attribute,  if didn't define there, then will pick the username and password from the passwd table.  same way for EthSwitch and IBSwitch.    Can u give me sample example how did u use it?

**Comment by kcgthb** [comment]
@cxhong I don't have any username nor password defined in the `switches` table for my Infiniband switches, nor for my Ethernet switches. I'd like to only use the `passwd` table instead, as indicated in the documentation.

I have a `switch` entry in the `passwd` table:
```
# tabdump passwd | grep switch
"switch","admin","[redacted]",,,,
```

This works very well for Ethernet switches:
```
# xdsh  sh-ethsw-core --devicetype EthSwitch::Dell -T "show version"
TRACE:Default context is XCAT
Processing EthSwitch/Dell device type
TRACE:Node RSH is
TRACE: Fanout value is 64.
TRACE: Timeout value is
Command name: /opt/xcat/sbin/rshell_api -v -l admin -p [redacted] sh-ethsw-core enable; terminal length 0; exit; show version
sh-ethsw-core: 0. prematch=
sh-ethsw-core:
[...]
```
(see how it automatically picked up the "admin" username)

But it doesn't work for Infiniband switches:
```
# xdsh sh-ibsw-core-01 --devicetype IBSwitch::Mellanox  -T 'show version'
TRACE:Default context is XCAT
Processing IBSwitch/Mellanox device type
TRACE:Node RSH is
TRACE: Fanout value is 64.
TRACE: Timeout value is
Command name: /usr/bin/ssh -o BatchMode=yes -x root@sh-ibsw-core-01 cli "show version"
[...]
```
(see how it uses "root" instead of the username in the `passwd` table)

The object definition is:
```
# lsdef sh-ibsw-core-01
Object name: sh-ibsw-core-01
    groups=ib_switch
    ip=10.10.0.201
    mgt=switch
    nodetype=switch
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```

Given the test in https://github.com/xcat2/xcat-core/blob/master/perl-xCAT/xCAT/DSHCLI.pm#L982:
```perl
sub fork_fanout_dsh
{
[...]    
    #get username and passeword for ether net switches (EthSwitch type)
    if ($$options{'devicetype'} =~ /EthSwitch/) {
```
it is expected. But since it doesn't match the documentation, it would be great if it could be fixed.

**Comment by cxhong** [comment]
Thanks @kcgthb , I will make modification.

**Comment by cxhong** [comment]
@kcgthb , I will close this issue for now.  If you still have this issue,  we will re-open it.

**Comment by kcgthb** [comment]
Hi @cxhong 
I don't see any commit for this, has it been fixed?

**Comment by cxhong** [comment]
PR #2445 had this changes

**Comment by kcgthb** [comment]
Oh, excellent, sorry I missed it.
Thanks!
