### ISSUE TITLE
/etc/hostname not properly set?

### ISSUE THREAD

**Issue by thiell** [xcat2/xcat-core#2446]
Hi,

I use xCAT 2.12.3 to deploy both physical nodes and VMs on a new cluster and I am currently using CentOS 7.3 as the Linux distro. Although `hostname` returns the proper node hostname after it is deployed, I noticed that all nodes deployed with xCAT have the default `/etc/hostname` content with `localhost.localdomain`. Also, there is an example of `hostnamectl status` on such deployed node:
```
# hostnamectl status
   Static hostname: localhost.localdomain
Transient hostname: oak-gw04.sunet
         Icon name: computer-vm
           Chassis: vm
...
```

Do you have an idea of how to fix this without writing a postscript? I am a bit surprised this is not done by anaconda, hm? Thanks!

**Comment by whowutwut** [comment]
Thanks for reporting this,.  I am able to re-create this same behavior in the latest version of xCAT.  

xCAT, by default is going to leave the compute nodes as DHCP.  In this case, you see the Transient hostname is set based on the response from DHCP.  The Static is NOT set as you point out and `/etc/hostname` is left as the OS default of `localhost.localdomain`.  

To have xCAT set the provisioning interface to static, you want to add the `hardeths` postscript to your node definition: `chdef -t node <node name> -p postscripts="hardeths"`  Then the `/etc/hostname` will be set.. and the `/etc/sysconfig/network-scripts/ifcfg-<NIC>` will be changed to STATIC IP. 

However, this hardeths postsccripts is not aware of `hostnamectl` command in OS that are running systemd.  So we still need to fix this.  This is something that I will create a pull request for.

**Comment by illmaticone** [comment]
Hi (its Wes BTW)... We recently hit this problem on RH7.3 installs.  looks like even if makedns is run (all nodes resolve fine on the EMS) and we remove forwarders , each node installed ends up with a localhost hostname and /etc/hosts not filled in.  Is this the same problem described above or a separate issue?

We currently do our own version of hardeths to change ifcfg to static and do not run that script today.

**Comment by bybai** [comment]
Hi @illmaticone ,
This is fixed in 2.13.3.
The code change is in https://github.com/xcat2/xcat-core/pull/2452

**Comment by whowutwut** [comment]
Hi Wes, you can take a look at the pull request that resolved it and merge into your own script that you are using... that might help resolve the issue: https://github.com/xcat2/xcat-core/pull/2452/files

**Comment by whowutwut** [comment]
Validated on 2/22 build of 2.13.2.. `git commit dab564dd7f23cb8bc46119f11d235de33c57802a, built Wed Feb 22 22:42:07 EST 2017` 

## diskless: 
```
[root@fs4 ~]# chdef frame23cn16 -p postscripts=hardeths
1 object definitions have been created or modified.
[root@fs4 ~]# xdsh $NODE  hostnamectl | grep hostname
frame23cn16:    Static hostname: frame23cn16.pok.stglabs.ibm.com
[root@fs4 ~]#  xdsh $NODE cat /etc/hostname
frame23cn16: frame23cn16.pok.stglabs.ibm.com
```

## diskful: 

```
[root@fs4 ~]# lsdef $NODE -i provmethod,postscripts
Object name: frame23cn16
    postscripts=syslog,remoteshell,syncfiles,hardeths
    provmethod=rhels7.3-ppc64le-install-compute

[root@fs4 ~]#  xdsh $NODE  hostnamectl | grep hostname
frame23cn16:    Static hostname: frame23cn16
[root@fs4 ~]#  xdsh $NODE  cat /etc/hostname
frame23cn16: frame23cn16
```
