### ISSUE TITLE
<rpower node boot> - powering-off

### ISSUE THREAD

**Issue by tweenysodd** [xcat2/xcat-core#2449]
Hi,

I was performing a routine update, and issued 'rpower compute boot' to the 6 compute nodes. Only 5 of them came back, the last one shows status=powering-off, even if the node is physically turned on or off. The rpower, nodestat, and lsdef commands consistently show power is on or off, when the node power beacon goes on or off, but for the status. sshd isn't running on the node either. Any suggestions would be greatly appreciated.

**Comment by whowutwut** [comment]
Hi @tweenysodd  What Os/Architecture are your machines and which version of xCAT? (`lsxcatd -a`) 
Trying to read between the lines, so the `rpower <node> status` comes back OK and reflects the correct state of the machine?  Can you give us some samples of the command outputs?

**Comment by tweenysodd** [comment]
Hi @whowutwut I'm running a Centos 6.7 cluster, and xCAT is running v 2.10. 
Here are some samples (the node at hand is lenovo03):
lsdef lenovo03 -i status
Object name: lenovo03
    status=powering-off

nodestat lenovo03
lenovo03: noping

ssh lenovo03 -vvv
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to lenovo03 [10.0.1.3] port 22.
debug1: connect to address 10.0.1.3 port 22: No route to host
ssh: connect to host lenovo03 port 22: No route to host

At first, I suspected an ssh problem. However, looking at the physical unit, the fluorescent light that blinks behind the power button isn't on at all. All the other nodes show a consistent blink, once every 2-3 seconds. On the other hand, as I'd earlier mentioned:

rpower lenovo03 stat
lenovo03: on

And if I issue boot to the node through rpower, the stat returns 'off'. The lsdef status however, is always at powering-off.

**Comment by whowutwut** [comment]
@tweenysodd  Humm.. the fact that  stat returns seem to indicate that you should be connecting to the IMM correctly.    But just to verify...  can you make sure the following works...

```
ipmitool-xcat -H <bmc_IP> -U <BMC_USER> -P <BMC_PASS> lan print 1
ipmitool-xcat -H <bmc_IP> -U <BMC_USER> -P <BMC_PASS> chassis power status
```

So it's possible that the networking from the compute node is not configured correctly for the postscripts to report back the correct status...  Can you remote console to the machine  ? (using `rcons`) to take a look at the network settings? 
```
makeconservercf lenovo03
rcons lenovo03
```

IF not, can you remote connect to the compute side using the IMM web browser?

**Comment by tweenysodd** [comment]
I doubt the nodes were set up for bmcs, because the nodes are of the lenovo NeXtScale nx360m5 model. I did try rcons lenovo03 earlier, the output stops at:
rcons lenovo03
[Enter `^Ec?' for help]
I'm going to attempt connecting a serial cable to the node, and physically connect to the node.

**Comment by tweenysodd** [comment]
lsdef lenovo03
Object name: lenovo03
    arch=x86_64
    bmc=lenovo03-imm
    bmcport=1
    chain=runcmd=bmcsetup,shell
    cons=ipmi
    cpucount=20
    cputype=Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
    currstate=netboot centos6.7-x86_64-compute
    disksize=sda:4995GB
    groups=ipmi,compute,all
    initrd=xcat/osimage/centos6.7-x86_64-netboot-compute/initrd-stateless.gz
    ip=10.0.1.3
    kcmdline=imgurl=http://10.1.0.1:80//install/netboot/centos6.7/x86_64/compute/rootimg.gz XCAT=!myipfn!:3001 NODE=lenovo03 FC=0  console=tty0 console=ttyS0,115200
    kernel=xcat/osimage/centos6.7-x86_64-netboot-compute/kernel
    mac=40:f2:e9:c5:50:94
    memory=64048MB
    mgt=ipmi
    mtm=5465AC1
    netboot=xnba
    nfsserver=10.1.0.1
    ondiscover=nodediscover
    os=centos6.7
    otherinterfaces=-imm:10.1.1.3
    postbootscripts=otherpkgs,MST.compute
    postscripts=syslog,remoteshell,syncfiles,restartsshd
    profile=compute
    provmethod=centos6.7-x86_64-netboot-compute
    serial=06FHZFW
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=01-27-2017 09:21:23
    supportedarchs=x86,x86_64
    switch=switch
    switchport=3
    tftpserver=10.1.0.1
    updatestatus=failed
    updatestatustime=01-27-2017 08:59:51

Could you kindly help me with the values I'd need for the ipmi commands?

rcons lenovo03
[Enter `^Ec?' for help] - is all I get.

**Comment by whowutwut** [comment]
you can check `tabdump passwd | grep ipmi` for the user/pass, defaults are sometimes `USERID` and `PASSW0RD` (with a zero)   If you can ping the IMM , you could point to it from a browser and see if you can log into the IMM web portal to get remote console (assuming you have that function activated)

**Comment by tweenysodd** [comment]
That helped a lot! Thanks. The ipmitool-xcat commands returned everything as set up. The chassis power is on for the node. 
I'm in the IMM web portal for the node. The general stats are all normal. Anything I should look for in particular when I drop a remote console?

**Comment by tweenysodd** [comment]
I managed to connect a physical console to the node. Upon rpower lenovo03 boot, the screen shows 'System initializing memory', and stays at that. Thoughts?

**Comment by whowutwut** [comment]
Humm. not sure..  @jjohnson42  Do you have any ideas about this machine stuck in "system initializing memory?"

**Comment by tweenysodd** [comment]
The node powers on and off (green LED) as expected, with "rpower lenovo03 boot", or "rpower lenovo03 off/on". "lsdef lenovo03  -i status" is stuck at powering-off and the physical console stays at "system initializing memory". The IMM web portal for the node says everything is normal. This is where I'm at.

**Comment by tweenysodd** [comment]
UPDATE:
Using the IMM web portal, I dug through the events log - "Memory Logging Limit Removed for memory device 1 in Group 1 on Subsystem System Memory". This message was reported only on lenovo03, during the parallel power off, and power on for all compute nodes. I believe this explains why the console is stuck at "system initializing memory".

**Comment by tweenysodd** [comment]
The DIMM stick had to be replaced, all is good now.

**Comment by whowutwut** [comment]
Great ! thanks for letting us know
