### ISSUE TITLE
xdsh should report down nodes

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2455]
When xdsh is run against a group, remote hosts that fail are silently ignored.  Is there an option (and a way to make it default) that hosts that do not respond are noted?

Current output:
  \# xdsh compute /bin/true
  \#

Expected output:
\# xdsh compute /bin/true
compute02: host did not respond
\#

**Comment by gurevichmark** [comment]
Matt, have you tried the `-v` flag for the `xdsh` ?

**Comment by mattaezell** [comment]
Thanks, that appears to be exactly what I need.  Is there any way to make that behavior default?  Just making an alias is not straightforward since the noderange needs to go between `xdsh` and `-v`, but I guess I could do a bash function...
`xdshv () { nr=$1; shift; xdsh $nr -v $@; }`

**Comment by gurevichmark** [comment]
Matt, we would like to keep default the same, in case users have scripts using `xdsh` and might not expect additional output the "verify" would produce.
What if we added an environment variable DSH_VERIFY. It would control the display of "verify" and could be overwritten by specifying `-v` flag ?

**Comment by mattaezell** [comment]
Mark - sorry for not getting back to you sooner.  Yes, I think a `DSH_VERIFY=1` environment variable, or even `DSH_OPTIONS='-v'` that could hold arbitrary command line switches to apply by default, would work for me.

**Comment by whowutwut** [comment]
I did a quick verification on the pull request code: 

with some fake nodes defined...
```
[root@fs2vm105 xcat-core]# xdsh compute /bin/date
compute001: ssh: Could not resolve hostname compute001: Name or service not known

compute002: ssh: Could not resolve hostname compute002: Name or service not known

frame45cn02: ssh: Could not resolve hostname frame45cn02: Name or service not known

frame45cn04: ssh: Could not resolve hostname frame45cn04: Name or service not known
```

Using the `-v` option: 
```
[root@fs2vm105 xcat-core]# xdsh  compute -v /bin/date 
Error: compute001 is not responding. No command will be issued to this host.
Error: compute002 is not responding. No command will be issued to this host.
Error: frame45cn02 is not responding. No command will be issued to this host.
Error: frame45cn04 is not responding. No command will be issued to this host.
```

using the export:
```
[root@fs2vm105 xcat-core]# export DSH_VERIFY=1
[root@fs2vm105 xcat-core]# xdsh compute /bin/date
Error: compute001 is not responding. No command will be issued to this host.
Error: compute002 is not responding. No command will be issued to this host.
Error: frame45cn02 is not responding. No command will be issued to this host.
Error: frame45cn04 is not responding. No command will be issued to this host.
```

Will close, the code is merged today.
