### ISSUE TITLE
[2.13.2]tftp service will down after xcatd started for a while on sles11.4 and rhels6.8 ppc64

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2463]
env:sles11.4 rhels6.8 ppc64
build:[root@c910f02c01p14 ~]# lsxcatd -v
Version 2.13.2 (git commit d7ca3e7b69befa71c7ce73a66b1da9c7aad6d059, built Mon Feb  6 06:15:41 EST 2017)
How to reproduce：
```
1.start xcatd 
service xcatd start
2.To check tftp service:
[root@c910f02c01p14 ~]# ps -aux |grep tftp
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
root      5559  0.0  0.0 105088  2944 pts/0    S+   00:42   0:00 grep tftp

```

**Comment by chenglch** [comment]
Hi @junxiawang , I can not recreate this problem with your step, please check that if this issue only occurs when you run `service xcatd restart`.
