### ISSUE TITLE
installation loop when there are 2 provision networks.

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#2483]
We have two networks for provision. One is public, The other one is private. 
Garrison nodes are installed from private network.
Firestone nodes are installed from public network. 
In this environment, the site parameters: 
"master","c712ems5",,
"nameservers","c712ems5",,
When they are set with public network ip, the installation will loop when provision garrison nodes. 
When set them with private ip, the installation will loop when provistion firestone nodes. 
It brings much inconvenience for our admin work. 
Could you resolve this problem to avoid changing the site table frequently?

**Comment by immarvin** [comment]
hi @wwzhubj , would you please provide the node definition of a Garrison node and a Firestone node?

**Comment by wwzhubj** [comment]
firestone node: 
```
[root@c712ems5 ~]# lsdef c712f1n12
Object name: c712f1n12
    arch=ppc64le
    bmc=10.128.130.129
    cons=ipmi
    currchain=boot
    currstate=boot
    groups=all
    initrd=xcat/osimage/rhels73rc3DF1650_istGA/initrd.img
    installnic=mac
    ip=9.114.75.235
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.3rc3/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/c712f1n12 BOOTIF=98:be:94:06:9e:b4  ip=dhcp
    kernel=xcat/osimage/rhels73rc3DF1650_istGA/vmlinuz
    mac=70:e2:84:14:02:ec
    mgt=ipmi
    mtm=8335-GTA
    netboot=petitboot
    os=rhels7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    primarynic=mac
    profile=compute
    provmethod=rhels73rc3DF1650_istGA
    serial=2111DDA
    status=booted
    statustime=01-20-2017 07:41:27
    switchport=1/0/15
```
Garrison node: 
```
[root@c712ems5 ~]# lsdef c712f10n14-pvt
Object name: c712f10n14-pvt
    arch=ppc64le
    bmc=10.128.130.204
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    currchain=boot
    currstate=boot
    disksize=sda:1000GB,sdb:1000GB
    groups=f10
    initrd=xcat/osimage/rhels73rc3DF1706_SP1.1/initrd.img
    installnic=mac
    ip=192.168.130.204
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.3rc3/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/c712f10n14-pvt BOOTIF=70:e2:84:14:1e:ad  ip=dhcp
    kernel=xcat/osimage/rhels73rc3DF1706_SP1.1/vmlinuz
    mac=70:e2:84:14:1e:ad|70:e2:84:14:1e:ae!c712f10n14-pvt-enP5p7s0f1
    memory=261493MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nicips.ib0=172.17.0.204
    nicips.ib1=172.17.1.204
    nicips.enP5p7s0f1=9.114.75.204
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nodetype=mp
    os=rhels7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --ibaports=2,setroute
    primarynic=mac
    profile=compute
    provmethod=rhels73rc3DF1706_SP1.1
    routenames=v2094gw9
    serial=2113F4A
    status=booted
    statustime=02-15-2017 03:20:09
    supportedarchs=ppc64
    switch=c712f11u30vc
    switchport=1/0/37
    updatestatus=synced
    updatestatustime=10-28-2016 10:40:52
```

**Comment by immarvin** [comment]
please set the proper "nameservers" for the private network and public network in the networks table.
````
1033  chdef -t network -o c712garrisonPUB nameservers=9.114.75.249

 1036  chdef -t network -o c712garrisonOS nameservers=192.168.130.249 
````

**Comment by wwzhubj** [comment]
The issue still exist after set the proper "nameserver" in networks table.

**Comment by whowutwut** [comment]
@immarvin @wwzhubj in Petitboot can you check what is being sent to the compute node on which interface? I made some changes to make it clear which network is sending the genesis kernel but we never changed anything for the file we created in /tftpboot/petitboot. What is sent over and over causing the loop?

**Comment by wwzhubj** [comment]
The petiboot shows two xCAT option:
 ```
  4.083237] hub 1-3:1.0: 5 ports detected
[    4.087623] tg3 0001:01:00.1 enP1p1s0f1: renamed from eth1
[    4.247575] tg3 0001:01:00.2 enP1p1s0f2: renamed from eth2
 Petitboot (v1.2.6-8fa93f2)                   8335-GTB         2113F4A
 qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
  [Disk: sda2 / 73fe00e3-3102-4dfe-a7bf-31895bea9c5c]
    Red Hat Enterprise Linux Server (0-rescue-530bf04221ea4954a1f8a63f310cf11a)
    Red Hat Enterprise Linux Server (3.10.0-514.el7.ppc64le) 7.3 (Maipo)
  [Network: enP5p7s0f0 / 70:e2:84:14:1e:ad]
    xCAT
  [Network: enP5p7s0f1 / 70:e2:84:14:1e:ae]
    xCAT

  System information
  System configuration
  Language
  Rescan devices
  Retrieve config from URL
 *Exit to shell
 qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
 Enter=accept, e=edit, n=new, x=exit, l=language, h=help
The system is going down NOW!t
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[   21.420437] kexec_core: Starting new kernel
```
```
but in /tftpboot/petitboot, the c712f10n14 is : 
[root@c712ems5 petitboot]# cat c712f10n14-pvt
#install rhels7.3-ppc64le-compute
default xCAT
label xCAT
        kernel http://192.168.130.249:80/tftpboot/xcat/osimage/rhels73rc3DF1706_SP1.1/vmlinuz
        initrd http://192.168.130.249:80/tftpboot/xcat/osimage/rhels73rc3DF1706_SP1.1/initrd.img
        append "quiet inst.repo=http://192.168.130.249:80/install/rhels7.3rc3/ppc64le inst.ks=http://192.168.130.249:80/install/autoinst/c712f10n14-pvt BOOTIF=70:e2:84:14:1e:ad  ip=dhcp "
[root@c712ems5 petitboot]# pwd
/tftpboot/petitboot
```

**Comment by zet809** [comment]
It seems the MASTER in site table is resolved to be 9.114.x,x. Then for CN in 9.114.x.x subnet, no such issue. But for CN in 192.168.x.x, the script can not access xcatd through 9.114.x.x, then it failed to send updateflag to MN. That is why the installation looping.

**Comment by zet809** [comment]
@immarvin  and @whowutwut  To resolve this issue, do you think it is possible that to set a keyword <FACINGIP> or something to the master entry in site table, then resolve it to be the ip address of MN that facing the node that required?

**Comment by whowutwut** [comment]
@zet809 I think we need to understand which network is the provisioning network and the compute node needs to communicate to xCAT via the provisioning network.  If they configured xCAT to be listening on the 9.network, this is "public" intranet, so I don't think this is correct.  If the compute node provisioning network is 192, it should communicate to xCAT using the 192 address.  If the hostname resolves to a 9.IP, then the xCAT master should use the hostname that has the 192 IP address.  

Seems to me like this is a error in the configuration? @markprez?

**Comment by zet809** [comment]
@whowutwut In fact, this is a specific configuration. For some node, they use 9.IP as the installation network, but for others, they may use 192.IP as the installation network. They don't want to modify the configuration to deploy different compute node. It seems the 'xcatmaster' attribute can be used to specify the exact MASTER for a specified node. I had verified, this issue is fixed with the solution. So, I close defect.
