### ISSUE TITLE
Nodeset rejects incorrect value for "tftpserver" attribute, but still puts it into the config file

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#2493]
1. When non-resolvable name is specified for `tftpserver` node attribute, `nodeset` command returns an error. But the entry is put into petitboot config file for the rootimg:

```
[root@fs4 petitboot]# chdef frame23cn17 tftpserver=xyz
1 object definitions have been created or modified.
[root@fs4 petitboot]# nodeset frame23cn17 osimage
frame23cn17: netboot rhels7.3-ppc64le-compute
Error: Unable to resolve the tftpserver for node
Error: Unable to resolve the tftpserver for node
[root@fs4 petitboot]#
```

2. On the other hand, the `nfsserver` node attribute is accepted with a non-resolvable name and no error is reported. The value is put into petitboot config file for the kernel and initrd:

```
[root@fs4 petitboot]# chdef frame23cn17 nfsserver=abc
1 object definitions have been created or modified.
[root@fs4 petitboot]# nodeset frame23cn17 osimage
frame23cn17: netboot rhels7.3-ppc64le-compute
[root@fs4 petitboot]#
```

Resulting config file showing both `nfsserver` and `tftpserver` values:
```
[root@fs4 petitboot]# cat frame23cn17
#netboot rhels7.3-ppc64le-compute
default xCAT
label xCAT
        kernel http://abc:80/tftpboot/xcat/osimage/rhels7.3-ppc64le-netboot-compute/kernel
        initrd http://abc:80/tftpboot/xcat/osimage/rhels7.3-ppc64le-netboot-compute/initrd-stateless.gz
        append "imgurl=http://xyz:80//install/netboot/rhels7.3/ppc64le/compute/rootimg.cpio.gz XCAT=frame23cn16:3001 NODE=frame23cn17 FC=0  LOGSERVER=192.168.23.16  syslog.server=192.168.23.16 syslog.type=rsyslogd syslog.filter=*.*  xcatdebugmode=1 BOOTIF=70:e2:84:14:09:f7 "
[root@fs4 petitboot]#
```

**Comment by gurevichmark** [comment]
Assigning to @zet809 so that he can assign this issue to the right person.

**Comment by immarvin** [comment]
hi @gurevichmark , there is an error ``Error: Unable to resolve the tftpserver for node`` thrown out and the return value of ``nodeset`` is 1, I think it's explicit enough for the user. 
````
c910f02c08p15:~ # nodeset node0001 osimage=sles11.4-ppc64-install-compute
Warning: node0001: yaboot might be invalid when provisioning sles11.4-ppc64-install-compute,valid options: "grub2,grub2-tftp,grub2-http".
For more details see the 'netboot' description in the output of "tabdump -d noderes".
node0001: install sles11.4-ppc64-compute
Error: Unable to resolve the tftpserver for node
c910f02c08p15:~ # echo $?
1
````

**Comment by gurevichmark** [comment]
@immarvin Yes, the `tftpserver` setting to unresolvable name results in an error message when running `nodeset`.
The problem is `nfsserver` setting to unresolvable name:
* No error is reported when running `nodeset`. 
* RC is 0
* `/tftpboot/petitboot\<node-name>` contains entries with unresolvable name

**Comment by immarvin** [comment]
hi @gurevichmark , the ``nfsserver`` in the ``/tftpboot/petitboot/<node-name>`` is not resolved by management node, it will be resolved in the CN during provision. 

another concern is that trying to resolve it in ``nodeset`` might introduce additional time cost

**Comment by gurevichmark** [comment]
@immarvin You are right, when provisioning CN with unresolved `nfsserver`, this error is displayed in the console:
```
Could not resolve host: abc; Unknown error
[Wed Mar 22 11:19:20 2017][   64.394953] dracut-initqueue[524]: Warning: failed to fetch kickstart from http://abc:80/install/autoinst/server_test1
```

But why the difference in behavior for `tftpserver` and `nfsserver` ?
For unresolved  `tftpserver`, `nodeset` displays an error, but not for unresolved `nfsserver` ?

**Comment by immarvin** [comment]
hi @gurevichmark ,``tftpserver``

**Comment by immarvin** [comment]
hi @gurevichmark , ``tftpserver`` is used to specify the server from which the firmware of the node  to get the NBP(such as grub2,yaboot,pxe binaries) and NBP configuration file, this information is passed to the firmware on the node via dhcp lease, since the nameserver information is also passed via dhcp lease,  so we should make sure the tftpserver can be resolved.
````
host c910f02c02p28 {
  dynamic;
  hardware ethernet da:08:4f:d8:b2:03;
  fixed-address 10.2.2.28;
        supersede server.ddns-hostname = "c910f02c02p28";
        supersede host-name = "c910f02c02p28";
        supersede server.filename = "/boot/grub2/grub2-c910f02c02p28";
        supersede server.next-server = 0a:02:01:0e;
}
```` 

the ``nfsserver`` is used to specify the server on which the installer to get the repo,installer conf files inside the installer  during diskful provision, at this time . the name server should have been configured

**Comment by gurevichmark** [comment]
@immarvin Ok, so you feel reducing the time of `nodeset` by not checking if `nfsserver` is resolvable is more important than catching a mistake of user specifying a wrong or unresolvable name for `nfsserver` attribute ?

**Comment by immarvin** [comment]
yes, the dns lookup will introduces significant time cost in ``nodeset`` , this might cause some performance issue in a scaling environment. another problems is that ``nameservers`` is also a configurable attribute for node object, since the compute nodes use an different external DNS server with the management node, is it possible that a node is resolvable for the compute nodes but  unresolvable for the management node ?

**Comment by gurevichmark** [comment]
1. Does the setting of `nameservers` affect resolution of `tftpserver` name ?
2. Can we save additional time by removing verification of `tftpserver` name resolution from `nodeset` ?

**Comment by immarvin** [comment]
talked with Mark offline, I will move this issue to next milestone to keep on discussion. No code change needed

**Comment by whowutwut** [comment]
@zet809 why is this issue moved to Verify in Zenhub?

**Comment by zet809** [comment]
Hi, @whowutwut , got from @immarvin that this issue will be treated as a discussion how to set the tftpserver/nameserver/nfsserver, no code change needed. So I move it to Review/QA state.

**Comment by immarvin** [comment]
hi @gurevichmark , I get some chance to look into this during the verification of SN pool. The ip address instead of hostname of the tftpserver  is written to the ``yaboot/petitboot/grub2/xnba/....`` config file under ``/tftpboot``, I am this is due to some of the network boot loader requires IP address instead of hostname in the configuration file.

**Comment by samveen** [comment]
@immarvin Maybe move this to newer milestone?

**Comment by zet809** [comment]
Hi, @gurevichmark , do you think we can close this task and open new one if there is any more questions or discussion?

**Comment by gurevichmark** [comment]
I think we should just resolve this issue here, no need to open another issue to discuss this.

I opened this issue as a usability problem - If user specifies an unresolvable `tftpserver` name, we report that as an error when `nodeset` command is executed. But if user specifies an unresolvable `nfsserver` name, we do not report that as an error when `nodeset` command is executed, instead, provisioning fails.

If people feel this behavior is acceptable, I am ok to close this issue. If people feel we should be more consistent between `tftpserver` and `nfsserver`, then perhaps this issue can be put in backlog.

**Comment by robin2008** [comment]
Yes,  it is still an issue.  It is required to report error when the following action might get into error.
Just the priority might not be high as `nfsserver` is seldom set.

To resolve it to IP will bring extra time costing, but normally most of the nodes will use the same nfsservers, I don't think there might be lots of nfsserver available in real customer site. So the performance impact is not big if we can cache them when handling.

**Comment by zet809** [comment]
Hi, @robin2008 , I remove the milestone , pls feel free to add one when you plan to fix it. Thx!

**Comment by gurevichmark** [comment]
Ok, good. But I think there might be a second problem. When `tftpserver` is unresolvable, we report an error, yet still put this unresolvable `tftpserver` name into the petitboot cfg file.

**Comment by robin2008** [comment]
@gurevichmark 

In fact, it will get the same result in such below implementations:
  - keep previous one
  - remove the config file
  - using current wrong name in config file

All will cause the installation failure or unexpected installation. I don't think there are  two many difference to change the behavior.

**Comment by gurevichmark** [comment]
Ok, that makes sense, but if I had to pick between the 3 choices above, I would choose the "keep previous one". It would be consistent with commands like `chdef`. If a user issues `chdef` and some problem is detected with parameters or flags passed in, we report an error, but I do not think we will change the object definition ?

**Comment by robin2008** [comment]
I would like to introduce an new action for `nodeset`, like `nodeset check fake1`
This will check if the node configuration is suitable to run `nodeset`.

**Comment by daniceexi** [comment]
@robin2008 is this kind of check can be added in ``xcatprobe``?

**Comment by robin2008** [comment]
`xcatprobe` is also good,  but I think `nodeset` is better to provide it as it might be integrated with `osimage` together by option controlled.

**Comment by daniceexi** [comment]
@robin2008 I understand that, so I recommend to have a  call in xcatprobe to unify the interface for customer even it is implemented in the nodeset itself.

We discussed the ``xcatprobe`` check for node, do we have plan for it?

**Comment by robin2008** [comment]
add `xcatprobe` for it.

**Comment by hu-weihua** [comment]
link to https://github.com/xcat2/xcat2-task-management/issues/61

**Comment by gurevichmark** [comment]
Due to limited resources, this issue will not be addressed.
