### ISSUE TITLE
[openbmc] Support ssh based console in conserver 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2499]
For openbmc, the SOL consoles is moving away from ``ipmitool sol active`` to ssh based on a port opened on the BMC.   This issue requests adding in very quick and basic support for ssh console so we can be ready to test it out once we get machines running openbmc.  

From my investigation, it seems like we can scaffold and just use the normal ssh port to do testing, and the concept is identical.   For example, create a "debugtest" user on a compute node, giving it password "abc123".    Hard code a "ssh" console: 

```
exec "echo abc123 | ssh debugtest\@10.3.25.1";
```

Set ``cons=ssh`` in the dummy xCAT node object and `rcons dummynode` and it will open a console to this machine. 

```
[root@c910f02c05p03 cons]# rcons test_openbmc_ssh
[Enter `^Ec?' for help]

[debugtest@fs4 ~]$ 
[debugtest@fs4 ~]$ 
[debugtest@fs4 ~]$ 
[debugtest@fs4 ~]$ uptime
 06:53:18 up 3 days,  6:11,  3 users,  load average: 0.01, 0.05, 0.05
[debugtest@fs4 ~]$ [disconnect]
[root@c910f02c05p03 cons]#
```

## Planned Externals: 

* new console ``cons=ssh``
 
* User will need to define in the passwd table the password for the ssh console, similar to the entry we have today for ``ipmi`` based consoles.  

* Ability to override the SSH_CONSOLE_PORT on the xCAT MN/SN, so in the ssh console, we will hard code the port based on openbmc, but to allow users to use this against a different port, and to help Unit testing, we should be able to ``export SSH_CONSOLE_PORT=22`` and not have to change the console file code.

**Comment by whowutwut** [comment]
I target the 2.13.2 milestone, we don't need FVT to test this until we get some real machines with openbmc firmware.  This just allows us to be ready with what we can do before machines arrive.

**Comment by cxhong** [comment]
Created a new plugin and cons for openbmc to support this feature
```
# lsdef openbmc1
Object name: openbmc1
    cons=openbmc
    groups=all,openbmc
    ip=x.x.x.x
    mgt=openbmc
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
````
when command `rcons openbmc1`  is running, it will call 
```
exec /opt/xcat/share/xcat/cons/openbmc openbmc1;
```
and `cons/openbmc` will execute `ssh` command as victor described above.
```
exec "echo $password | ssh -tt -p $sshport -l $username $nodeip"
````

it looks like we couldn't pass in the `password` and complained `Pseudo-terminal will not be allocated because stdin is not a terminal.` .  So I downloaded `sshpass` command, then changed to:
```
exec "sshpass -p $password ssh -p $sshport -l $username $nodeip"
````

yum install couldn't find `sshpass` packages,  do u think we can use this command?  can we put it to our xcat-deps?

**Comment by whowutwut** [comment]
I'd rather find another solution first, sent a note to the firmware team to see if we could possibly set up ssh keys for passwordless ssh before we start thinking about adding another package to the dependencies.. let's see what comes back

**Comment by zet809** [comment]
@whowutwut Maybe there is option within ssh that can specify password for a host, @immarvin can help to find this option.

**Comment by whowutwut** [comment]
@tingtli  I don't think there's any automated testcases that we can create for rcons, so I will close this issue.  Will be testing this by use when we get some P9 servers or borrow from firmware teams
