### ISSUE TITLE
"pping" command flag "-f" displays an error

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#2501]
xCAT man page for pping shows that `-f | --use_fping` option can be used.

When trying it, I get:

```
[root@fs4 ~]# pping -f frame23
Cannot open fping pipe: No such file or directory at /opt/xcat/bin/pping line 165.
[root@fs4 ~]# pping --use_fping frame23
Cannot open fping pipe: No such file or directory at /opt/xcat/bin/pping line 165.
[root@fs4 ~]#
```

**Comment by gurevichmark** [comment]
Assigning to @zet809 so that he can assign this issue to the right person.

**Comment by whowutwut** [comment]
@zet809 if you think someone can fix this in this release please assign it. Otherwise let's move it to 2.13.3.  @tingtli can you verify if we have any test cases that test this?

**Comment by zet809** [comment]
It seems the fping package shall be installed to support fping functions. 
[root@xcat]# rpm -aq |grep fping
[root@xcat]# pping -f frame23
Cannot open fping pipe: No such file or directory at /opt/xcat/bin/pping line 165.
[root@xcat]# yum install fping
...
[root@xcat]# rpm -aq |grep fping
fping-2.4b2_to-2.ppc64le
[root@xcat]# pping -f frame23
frame23cn03: ping
frame23cn05: ping
frame23cn16: ping
frame23cn17: ping
...
