### ISSUE TITLE
[FVT]: attribute machinetpye is not deleted completely when nodetype=pdu

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2506]
I found an interested thing when i test pdu on fs1.  When i create a pdu object , then define it with machinetype, then delele it, then create a pud with the same attribute, the machinetype is added to this pdu object automatically. 
Here is the steps.
1. Define a pdu object
```
[root@fs1 ~]# mkdef f5pdu3 groups=pdu ip=50.0.0.8 mgt=pdu nodetype=pdu
1 object definitions have been created or modified.
[root@fs1 ~]# lsdef -l f5pdu3
Object name: f5pdu3
    groups=pdu
    ip=50.0.0.8
    mgt=pdu
    nodetype=pdu
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```
2. Give the pdu object machinetype
```
[root@fs1 ~]# chdef f5pdu3 machinetype=1u
1 object definitions have been created or modified.
[root@fs1 ~]# lsdef -l f5pdu3
Object name: f5pdu3
    groups=pdu
    ip=50.0.0.8
    machinetype=1u
    mgt=pdu
    nodetype=pdu
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```

3. noderm f5pdu3
```
[root@fs1 ~]# noderm f5pdu3
[root@fs1 ~]# lsdef f5pdu3
Error: Could not find an object named 'f5pdu3' of type 'node'.
```
4. define f5pdu5 again, machinetype is automatically set on f5pdu definition
```
[root@fs1 ~]# mkdef f5pdu3 groups=pdu ip=50.0.0.8 mgt=pdu nodetype=pdu
1 object definitions have been created or modified.
[root@fs1 ~]# lsdef -l f5pdu3
Object name: f5pdu3
    groups=pdu
    ip=50.0.0.8
    machinetype=1u
    mgt=pdu
    nodetype=pdu
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```

**Comment by cxhong** [comment]
noderm seems can't remove object from pdu table
```
[root@fs1 ~]# noderm pdutest
[root@fs1 ~]# tabdump pdu
#pdu,machinetype,modelnum,serialnum,outletCount,comments,disable
"f5pdu3","1u",,,,,
"test","1u",,,,,
"testatt","1u",,,,,
"pdutest","1u",,,,,
````

but remdef command works find:
```
[root@fs1 ~]# rmdef pdutest
1 object definitions have been removed.
[root@fs1 ~]# lsdef pdutest
Error: Could not find an object named 'pdutest' of type 'node'.
[root@fs1 ~]# tabdump pdu
#pdu,machinetype,modelnum,serialnum,outletCount,comments,disable
"f5pdu3","1u",,,,,
"test","1u",,,,,
"testatt","1u",,,,,
`````

**Comment by cxhong** [comment]
noderm command didn't work for switches neither.

**Comment by whowutwut** [comment]
@cxhong can you open another issue for ``noderm`` not working against switches? 

@tingtli  Is there any autotest cases that test noderm for the various node object? It seems like this slipped through our test environment.

**Comment by immarvin** [comment]
hi @whowutwut @tingtli , I think ``rmdef`` is the recommended way to manipulate objects,  I do not see "noderm xxx" brings too much convenience than "rmdef -t pdu xxxx" from  a user's perspective.
In fact, it will cost us a lot maintenance effort to provide such worthless flexibility, I don't think it worth us to put effort on enhance``noderm`` to support PDU or swtich objects.

**Comment by tingtli** [comment]
@whowutwut  we only have noderm cases to delete node object. No cases for switch and pdu object.

**Comment by cxhong** [comment]
Change name of pdu table attributes from pdu.pdu to pdu.node will fix this issue since pdu table is newly supported.  We can't do that for switches table,  once change attribute from switches.switch to switches.node, it will lost all the current information in the switches table.  Do u think will be too risk to make changes for switches table? 
anyway, there are actions can take to restore the switches table 
1) User needs to save the information in the switches table, 
2) upgrade the xcat release, switches table will be empty after upgrade
3) **tabedit switches** table,  paste the switches information back to switches table.

**Comment by tingtli** [comment]
@cxhong  with the PR#2158, seems we didn't fix this problem totally.

If we use " mkdef pdu2 groups=pdu nodetype=pdu machinetype=1u", pdu2 is added to pdu table
```
[root@fs1 yum.repos.d]# mkdef pdu2 groups=pdu nodetype=pdu machinetype=1u
1 object definitions have been created or modified.
[root@fs1 yum.repos.d]# lsdef pdu2
Object name: pdu2
    groups=pdu
    machinetype=1u
    nodetype=pdu
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
[root@fs1 yum.repos.d]# tabdump pdu
#node,machinetype,modelnum,serialnum,outletCount,comments,disable
"pdu2","1u",,,,,
[root@fs1 yum.repos.d]# lsdef -t pdu
pdu2  (pdu)
```

But if we use "mkdef pdu6 groups=pdu nodetype=pdu", seems pud6 is not added to pdu table.
```
[root@fs1 yum.repos.d]# mkdef pdu6 groups=pdu nodetype=pdu
1 object definitions have been created or modified.
[root@fs1 yum.repos.d]# lsdef -t pdu
pdu2  (pdu)
```

**Comment by tingtli** [comment]
Verified with xCAT 2.13.2 2/23 build.
```
[root@fs1 /]# lsxcatd -v
Version 2.13.2 (git commit dab564dd7f23cb8bc46119f11d235de33c57802a, built Wed Feb 22 22:42:07 EST 2017)
[root@fs1 /]#  mkdef pdu6 groups=pdu nodetype=pdu
1 object definitions have been created or modified.
[root@fs1 /]# lsdef -t pdu
pdu2  (pdu)
pdu6  (pdu)
[root@fs1 /]# tabdump pdu
#node,nodetype,machinetype,modelnum,serialnum,outletCount,comments,disable
"pdu2",,"1u",,,,,
"pdu6","pdu",,,,,,
```
