### ISSUE TITLE
xcat and VirtualBox 

### ISSUE THREAD

**Issue by monyaaltuwaigi** [xcat2/xcat-core#2509]
i am trying to use xcat with VirtualBox, when i use the rpower command i receive this error Error: vm01: No connection to the web service @ http://10.0.2.2:18083/.

can anybody help me to solve this problem?

**Comment by whowutwut** [comment]
Hi @monyaaltuwaigi  can you provide a little more information .. I'm not sure anyone has tried this out. 
Do you have xcat installed on a vm using virtual box and trying to control other VMs created in virtual box? 

Can we see some node definition for vm01?

**Comment by monyaaltuwaigi** [comment]
yes i have installed xcat in a vm (management node) in order to control vm01. i followed the steps in this link https://sourceforge.net/p/xcat/wiki/Using_VirtualBox_Nodes_Step_by_Step/.  
the node definition vm01 
groups=all,vbox
    ip=192.168.50.1
    mac=0800273BFB52
    mgt=vbox
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    power=vbox

**Comment by whowutwut** [comment]
@monyaaltuwaigi  Will have to take a look at that documentation a bit more, but i might not get around to it soon... 

It looks like there's a note in one of the documentation linking to this message in the user group: http://www.mail-archive.com/xcat-user@lists.sourceforge.net/msg00660.html and looks like virtual box function has not been maintained for quite some time

Are you trying to play with xCAT using VMs on windows?   Another option if you have some machines is to try out the docker containers that would help set up xCAT.  @zet809 would have more info there.

**Comment by robin2008** [comment]
@monyaaltuwaigi First we need to confirm if the VirtualBox web service is running, and the port 18083 is connected from the xCAT management node. (Make sure that no firewall rules to block the access)

BTW: what is the virtualbox version and what kind of virtualbox host:  Windows, Linux, OS X?

**Comment by monyaaltuwaigi** [comment]
thank you for your replies. i solved the problem by using KVM instead of virtualbox and its working fine

**Comment by MasterGroosha** [comment]
Is this still relevant? I managed to successfully control Linux VMs from Windows host with xCAT. I still have "No connection" error sometimes, but it works.
