### ISSUE TITLE
[FVT]:2.11 modify buildcore.sh in prior releases to upload xcat package to xcat.org

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#252]
This issue is opened to trace the work to modify buildcore.sh in prior release such as 2.7, 2.8 and 2.9 etc to upload xcat packages to xcat.org.

**Comment by whowutwut** [comment]
@tingtli I am going to do a demo of the new autobuild framework in our meeting on Thurs. 

The autobuild framework handles the uploading of the builds for xcat.org.  There's a separate script that we can run on xcat.org that will "promote" builds to GA.  This removes the complexity of the code in the buildcore.sh script.  I don't think I removed the code in buildcore.sh yet though.  I wanted the team to take a look and decide before deleting the code. 

However, I do think that for the older release, we should fix the buildcore.sh for 2.7 and 2.8, if needed.  The 2.9 build can be handled by the autobuild scripts.

**Comment by tingtli** [comment]
I will update xCAT 2.7 and 2.8 first. After you introduce the autobuild framework, I will work on 2.9

**Comment by tingtli** [comment]
@whowutwut  I am thinking if we need to modify 2.7, 2.8 and 2.9 to upload the build to xcat.org.
It seems there is almost no customers to use this build.  And the customers who use the build probably are farmilar with SF.  And the release note, xcat-dep is also on SF. 
Do you think we need to update the script?

**Comment by whowutwut** [comment]
@tingtli  Are you saying we should just leave 2.7 and 2.8 uploading to SF for now until we see a greater demand for builds ?  You're right, maybe no one is using this anymore to make the changes..

**Comment by daniceexi** [comment]
@whowutwut @tingtli I agree we don't need to put effort for 2.7/2.8 build script, we can just manually copy the released files to xcat.org if necessary.

**Comment by whowutwut** [comment]
Sounds good, I closed the 2.7 pull request, we can close out this issue.
