### ISSUE TITLE
Error in RH pre scripts during kickstart

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#253]
```
[root@random1 anaconda]# cat  ks-script-SlUFZp.log 
mknod: '/dev/vcs1': File exists
mknod: '/dev/vcsa1': File exists
mknod: '/dev/vcs2': File exists
mknod: '/dev/vcsa2': File exists
mknod: '/dev/vcs4': File exists
mknod: '/dev/vcsa4': File exists
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
uname: write error: Broken pipe
quiet inst.repo=http://xcatmn:80/install/centos7.1/x86_64 inst.ks=http://xcatmn:80/install/autoinst/random1 ip=eno1:dhcp inst.cmdline console=tty0 console=ttyS1,115200 console=tty0 console=ttyS1,115200 BOOTIF=01-23-45-67-89-ab-cd
installstatus installing
```

**Comment by daniceexi** [comment]
@samveen what was the problem? 'uname -r' failed which caused the fail of grep? Could you give more information about the issue and your fix?

**Comment by samveen** [comment]
@daniceexi There are 2 changes here: 
* The issue is an unquoted parameter passed to grep on [line 240 of scripts/pre.rh](https://github.com/samveen/xcat-core/blob/3656dea07d5c11da5b27cc9b34026b7c76ea80c6/xCAT-server/share/xcat/install/scripts/pre.rh#L240). The analogous line in [scripts/pre.rh.rhels7](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/install/scripts/pre.rh.rhels7#L203) had already been fixed earlier in xcat2/xcat-core@3d3f69cdbeaab7766d7b5df1be68eb8f44a48813 .
* The improvement is using the POSIX mandated [`-q` option of grep](http://pubs.opengroup.org/onlinepubs/009604499/utilities/grep.html#tag_04_63_04) and instead of output redirection to `/dev/null`

**Comment by daniceexi** [comment]
@samveen 

* I did not see the execute error of following code that without quote for grep argument on both rh6 and rh7.

~~~~
if uname -u|grep ^3.*el7 > /dev/null; then
    FSTYPE=xfs
    BOOTFSTYPE=xfs
    EFIFSTYPE=efi
fi
~~~~

* Looks like your target nonde is centos7.1, then you should use pre.rh.rhel7 which have fixed this issue. Was the pre.rh selected for your centos7.1?

* This part of code just for rh7.x, so we don't need this part of code in pre.rh.

**Comment by samveen** [comment]
@daniceexi Yes, you are right:
```
[samveen@xcatmn1 ~]$ grep pre.rh  /install/osprofile/centos7.1/baseos/baseos.tmpl
#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/pre.rh#
```
I've fixed this in my template.

As for the fix, it won't hurt to quote the parameter to grep (good practice) or to remove the unnecessary redirection  :)

**Comment by samveen** [comment]
@daniceexi I also noticed that the `post.rh` includes the `post.xcat` and `post.rh.common` scripts while the `post.rhels7` does not (the `post.xcat` script is included into the rhels7 kickstart template directly). Does this mean that the post.rh.common isn't required on rhels7(/centos7)?

**Comment by daniceexi** [comment]
@samveen 

* Refer to the commit cfbd30bf98737239f47e293bd4de497c3bb84820 that following part of code is added for rh7 support. But finally a new version pre.rh.rhels7 was created for rh7 specific.  So I prefer to remove following lines.

~~~~
+if uname -r|grep ^3.*el7 > /dev/null; then
+    FSTYPE=xfs
+    BOOTFSTYPE=xfs
+    EFIFSTYPE=efi
+fi
~~~~~

* Yes, post.rh.common is not necessary for rh7 any more.

**Comment by samveen** [comment]
@daniceexi I've removed the rh7 specific code from `pre.rh` in all 3 pull requests.
