### ISSUE TITLE
MTU in networks table not carried through to static config  with confignics -s

### ISSUE THREAD

**Issue by ChristopherWalker** [xcat2/xcat-core#2535]
https://github.com/xcat2/xcat-core/pull/1933 says it will "Add a MTU column to the networks table. If set, this will configure the MTU in DHCP so that nodes will have the correct MTU during provisioning. "

This works, however the MTU is lost if "confignics -s" is used to set the IP address statically.

It is possible to set this explicitly with something like:
nicextraparams.eth0=MTU=9000
 - but it would be more consistent if the MTU setting for the network were carried through to static config for the install NIC. This is particularly useful for Centos7 where network devices have a variety of different names depending on their position in the host.

**Comment by bybai** [comment]
Hi @ChristopherWalker ,
Thanks your issue, I want to confirm the following:
1, Does adding a MTU column in networks table and setting nicextraparams work around your issue?
2, Your request is to use MTU from networks table and remove nicextraparams, "confignics -s" should configure MTU in the compute node?

**Comment by ChristopherWalker** [comment]
On Thu, 23 Feb 2017 at 02:03, Yuan Bai <notifications@github.com> wrote:

> Hi @ChristopherWalker <https://github.com/ChristopherWalker> ,
> Thanks your issue, I want to confirm the following:
> 1, Does adding a MTU column in networks table and setting nicextraparams
> work around your issue?
>

Yes.


> 2, Your request is to use MTU from networks table and remove
> nicextraparams, "confignics -s" should configure MTU in the compute node.
>

Yes, that's exactly right.

It may be easier to implement this by using the MTU that dhcp has provided.

I guess for completeness that if mtu is set in nicextraparams that should
override the other values.

Chris

>
