### ISSUE TITLE
[go-xcat] If machine cannot connect to xcat.org, can we print a better failure message?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2543]
I had a machine that does not have DNS service for xcat.org, so we need to manually add it.  However, the message failure for go-xcat does not help me figure out what is wrong. 

```
[root@fs3 tmp]# ./go-xcat --xcat-version=devel update
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.3

Reading repositories ...... failed
go-xcat: download xcat-core resource failed
```

Only after I add xcat.org into /etc/hosts, do we get the script to continue..

```
[root@fs3 tmp]# grep xcat.org /etc/hosts
166.70.135.166 xcat.org
[root@fs3 tmp]# ./go-xcat --xcat-version=devel update
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.3

Reading repositories ...... done

xCAT is going to be updated.
Continue? [y/n] y
``` 

Perhaps a better message would be useful.

**Comment by zet809** [comment]
@neo954 Hi, Gong jie, pls take a look at this issue, thx!

**Comment by neo954** [comment]
@whowutwut, For `go-xcat`, I did not put any effort on parse the exit code of `wget`. At most, I can make `go-xcat` print out something like `Network failure` (with exit code `4`). Is it any better?

**Comment by whowutwut** [comment]
What about just doing something simple like "ping -c 1 xcat.org" and if it doesn't return good ping then we print a message cannot resolve Xcat.org so it will help the user see what might be the problem.

**Comment by whowutwut** [comment]
I tested the version commit in git and it improves the message of this issue. Thanks @neo954 !
