### ISSUE TITLE
Duplicated output of postscripts in /var/log/xcat/xcat.log

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2544]
Hi!

It seems that postscripts execution generates duplicated output in `/var/log/xcat/xcat.log` (at least for stateful installation of RHEL 7 nodes).

```
# lsxcatd -v
Version 2.13.1 (git commit 62bd7a4072bb629ede16974272c993f4e707765f, built Wed Jan 11 08:45:41 EST 2017)
# lsdef sh-101-01 -i postscripts
Object name: sh-101-01
    postscripts=syslog,remoteshell,syncfiles,otherpkgs
```
After (successfull) deployment, when SSH'ing to the node to look at the log file, you can see that each postscript line is outputted twice:
```
# cat /var/log/xcat/xcat.log
[... postscripts cop from MN ...]
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
/etc/systemd/system/xcatpostinit1.service generated
xcatpostinit1.service enabled
Thu Feb 23 10:47:04 PST 2017 Running postscript: syslog
Thu Feb 23 10:47:04 PST 2017 Running postscript: syslog
postscript: syslog exited with code 0
Thu Feb 23 10:47:04 PST 2017 postscript syslog return with 0
Thu Feb 23 10:47:04 PST 2017 Running postscript: remoteshell
Thu Feb 23 10:47:04 PST 2017 Running postscript: remoteshell


Could not load host key: /etc/ssh/ssh_host_ed25519_key^M
Could not load host key: /etc/ssh/ssh_host_ed25519_key^M
postscript: remoteshell exited with code 0
Thu Feb 23 10:47:06 PST 2017 postscript remoteshell return with 0
Thu Feb 23 10:47:06 PST 2017 Running postscript: syncfiles
Thu Feb 23 10:47:06 PST 2017 Running postscript: syncfiles
postscript: syncfiles exited with code 0
Thu Feb 23 10:48:26 PST 2017 postscript syncfiles return with 0
Thu Feb 23 10:48:26 PST 2017 Running postscript: otherpkgs
Thu Feb 23 10:48:26 PST 2017 Running postscript: otherpkgs
[...]
```

I tried to look at `/xcatpost/mypostscript` but couldn't find why lines would be duplicated in the log file. Could you please confirm this issue and suggest a fix?

Thanks!

**Comment by kcgthb** [comment]
Oh well, I figured it out. 

In the generated `/xcatpost/mypostscript*` scripts, the `run_ps()` function that is in charge of executing postscripts explicitly logs output to `/var/log/xcat/xcat.log`
```bash
local logfile="/var/log/xcat/xcat.log"
[...]
./$@ 2>&1 | tee -a $logfile
```
These scripts are generated by the [`post.xcat`](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/install/scripts/post.xcat#L218) script, which is called in the kickstart file.

But that kickstart file (generated from [`/opt/xcat/share/xcat/install/centos/compute.centos7.tmpl`](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/install/centos/compute.centos7.tmpl#L169)) already logs everything to that same logfile:
```
mkdir -p /var/log/xcat/
{
cat >> /var/log/xcat/xcat.log << "EOF"
%include /tmp/pre-install.log
EOF
echo "Running Kickstart Post-Installation script..."
#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/post.xcat#
#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/post.rhels7#
} >>/var/log/xcat/xcat.log 2>&1
%end
```

So in the end, we have a kickstart logging to `xcat.log`, which calls a `run_ps()` function which also logs to `xcat.log`. The result is that the same output is logged in `xcat.log` twice.


What do you think should be the best way to fix this? Removing logging from `run_ps()`?

**Comment by penguhyang** [comment]
@kcgthb Thanks for investigation.
The root cause is
1. In the generated /xcatpost/mypostscript* scripts, the output of run_ps() (Output by "echo" in the function here) will be redirected to /var/log/xcat/xcat.log.
2. In the run_ps function, msgutil_r write info to the same log file.
Our solution is removing the ``echo`` command within the run_ps() function
