### ISSUE TITLE
Discovery packet file is ready - Sending the discovery packet to xCAT - Sleeping 5 seconds [REPEAT]

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2550]
Hello, I'm new to xCAT. I have installed the latest version of xCAT and  Linux which are given below:
- xcat-core-2.13.1-linux.tar  xcat-dep-2.13.2-linux.tar
- Centos 7.2.1511 (Core)
Also, I have added one object node. 
-------------------------------------------------
[root@xcatmn xcat]# lsdef cn1
Object name: cn1
    arch=x86_64
    bmc=192.168.220.143
    bmcpassword=123456
    bmcusername=root
    groups=all,x86_64
    mac=00:0c:29:b9:40:af
    mgt=ipmi
    netboot=xnba
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    provmethod=rhels7.1-x86_64-install-compute
-------------------------------------------------------------
[root@xcatmn xcat]# rpower cn1 on
Error: Unable to dispatch hierarchical sub-command to NORESOLUTION:3001.  Error: Connection failure: IO::Socket::INET: Bad hostname 'NORESOLUTION:3001' at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
--------------------------------------------------------------
Above is issue. What should I do??

**Comment by zet809** [comment]
Can you show me the content of site table with "tabdump site"? If not work, pls use "XCATBYPASS=1 tabdump site". Thx!

**Comment by dspatil7768** [comment]
I am doing all this on VMware so it causing some issues. Later I tried on
Centos 6.5, previously I was using 7.2

**Comment by dspatil7768** [comment]
Dear Sir/Mam,

I'm the newbie to xCAT and I'm trying to install latest xCAT i.e *
xcat-core-2.13.2 and xcat-dep-2.13.2*. The Operating System is using is
*Centos
6.5 x86_64*. and I'm installing on VMware

As required I have installed two NICs. Below are some details about my
installation which will be helpful for determining the solution.
--------------------------------------------------------------
[root@xcat xcat]# hostname
xcat.cdac.in
-------------------------------------------------------------
[root@xcat xcat]# cat /T FTP boot/pxelinux.cfg/AC10
DEFAULT xCAT
  LABEL xCAT
  KERNEL xcat/genesis.kernel.x86_64
  APPEND initrd=xcat/genesis.fs.x86_64.lzma quiet xcatd=172.16.0.3:3001
BOOTIF=eth0
-------------------------------------------------------------
[root@xcat xcat]# cat /etc/resolv.conf
; generated by /sbin/dhclient-script
search cdac.in
nameserver 172.16.0.3                                  # It's an
external/private IP of the system
------------------------------------------------------------
I have Configured eth0 for external network and eth1 for internal network
i.e 172.16.0.3 and this is STATIC IP. And the same eth1 I have used for
DHCP server for the internal network within the range given below:
---------------------------------------------------------
172.16.0.100-172.16.0.200
--------------------------------------------------------
Now at the time of PXE booting, I occurred some problems. I have attached
snapshot of it. please find it.

Issue are:
1) While PXE it shows assigned IP address as 172.16.0.100 and afterward its
showing other but in same range means

172.16.0.101 or  172.16.0.102
2) I have not set mgt=ipmi but still showing some IPMI related issue


Please help!

Thank you,

**Comment by dspatil7768** [comment]
[root@xcat ~]# tabdump site
#key,value,comments,disable
"blademaxp","64",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","172.16.0.3",,
"forwarders","172.16.0.3",,
"nameservers","172.16.0.3",,
"domain","cdac.com",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","US/Pacific",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"xcatsslversion","TLSv1",,
"auditskipcmds","ALL",,
"dhcpinterfaces","eth1",,
[root@xcat ~]# clear
[root@xcat ~]# tabdump site
#key,value,comments,disable
"blademaxp","64",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","172.16.0.3",,
"forwarders","172.16.0.3",,
"nameservers","172.16.0.3",,
"domain","cdac.com",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","US/Pacific",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"xcatsslversion","TLSv1",,
"auditskipcmds","ALL",,
"dhcpinterfaces","eth1",,
[root@xcat ~]# clear
[root@xcat ~]# tabdump site
#key,value,comments,disable
"blademaxp","64",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","172.16.0.3",,
"forwarders","172.16.0.3",,
"nameservers","172.16.0.3",,
"domain","cdac.com",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","US/Pacific",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"xcatsslversion","TLSv1",,
"auditskipcmds","ALL",,
"dhcpinterfaces","eth1",,

**Comment by zet809** [comment]
The cn1 is a physical server or VM? Hae you run "nodeset cn1 osimage=rhels7.1-x86_64-install-compute" before powering on it?

**Comment by dspatil7768** [comment]
[root@xcat Packages]# nodeset n00 osimage=centos6.5-x86_64-install-compute
n00: install centos6.5-x86_64-compute
----------------------------------------------------------------------------------------------
It's a VM. Thank you. Something worked. It took an image and did eth0 configuration. But after that it's showing some other error:
- The following problem occurred on line 117 of the kickstart file:
  - A single argument is expected for the rootpw command

**Comment by zet809** [comment]
It seems you forget to run "chtab key=system passwd.username=root passwd.password=abc123" before running nodeset. Pls use the 'chtab' command, and then run nodeset again.

**Comment by dspatil7768** [comment]
Thank you so much. It's working fine. But I have one doubt or confusion don't know. That compute node that now installed is what I defined earlier but while PXE booting it showing that it is getting installed by other than iPXE i.e xCAT Boot Agent. Now when I checked my Compute configuration all parameter are same as that of what I have defined. Will you please give information.
Thank you.
Regards,
Devendra Patil

**Comment by zet809** [comment]
As you can see for the "netboot=xnba" attribute of cn1, xnba short for "xCAT Network Boot Agent for x86 PXE hosts". It is a slightly modified version of gPXE.  It provides enhanced boot features for any UNDI compliant x86 host.  This includes iSCSI, http/ftp downloads, and gPXE script based booting.

**Comment by dspatil7768** [comment]
Now got it. Thank you so much, Sir
