### ISSUE TITLE
sendmsg is not defined in /opt/xcat/lib/perl/xCAT/Template.pm

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2557]
The `sendmsg` function is not declared (nor imported) in `/opt/xcat/lib/perl/xCAT/Template.pm`

As a result, all error messages supposedly sent back to the client are lost, and trying to use `sendmsg` results in the following being logged in `/var/log/xcat/cluster.log`:
```
Undefined subroutine &xCAT::Template::sendmsg called at /opt/xcat/lib/perl/xCAT/Template.pm line 1593.
```

**Comment by zet809** [comment]
@chenglch Hi, cheng long, will you pls take a look at this issue? Thx a lot!
