### ISSUE TITLE
Support for encrypted passwords in the passwd table is broken

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2558]
According to [the documentation]( https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/configure/password.html#configure-passwords), one can store encrypted password in the `passwd` table. The provided example (using `openssl passwd -1` generates password hashes using `md5`.

Now, with #2168, the default crypt method for passwords in the `passwd` table seem to be `sha256`, which is a first problem. The documentation should probably be updated to mention that, and give an example to generate a `sha256` encrypted password hash.

Now, looking at #2168 in more details, especially https://github.com/xcat2/xcat-core/pull/2168/files?diff=unified#diff-97ef2682510dad0de95d0570c8f81106, and unless I missed something, I think there's been a major regression in functionality. 

Before, the value stored in the `passwd` table was checked to see if it started with `$1`, `$5$` or `$6$` (the identifiers for `md5`, `sha256` and `sha512` respectively). If it started with one of those, it was recognized as being already hashed, and was returned as-is by the `crydb()` function. If it did not, it was then hashed with `crypt()` function.

Now, it looks to me that the value from the `passwd` table is crypted no matter what, even if it already is. So as a result, if I store a hashed value in `passwd`, it gets hashed again, and the resulting hash in `/etc/passwd` doesn't correspond to anything anymore, meaning that I can't use the password I chose to authenticate as root.

I believe this is also the case for the stateless and statelite cases (`xCAT-server/lib/xcat/plugins/packimage.pm` and `xCAT-server/lib/xcat/plugins/statelite.pm`).

Could you please restore the previous behavior? We need to be able to store encrypted root passwords in the `passwd` table.

**Comment by kcgthb** [comment]
Also the helpfile for the `passwd` table says:
```
       cryptmethod
                 Indicates the method that was used to encrypt the password attribute.
                 On AIX systems, if a value is provided for this attribute it indicates
                 that the password attribute is encrypted.  If the cryptmethod value is
                 not set it indicates the password is a simple string value. On Linux
                 systems, the cryptmethod can be set to md5, sha256 or sha512. If not
                 set, sha256 will be used as default.
```
Maybe it should say instead that the "cryptmethod" field indicates the method that xCAT will use to generate the encrypted password, and that the password should be stored in plain-text.
Unless this is not the intended usage, but I didn't find any place in the code where the "cryptmethod" value would be used to determine how a hashed password was encrypted. It's only used to determine how to crypt the password.

Anyway, the documentation and the code don't agree, so one should be fixed. :)

**Comment by kcgthb** [comment]
I'm proposing a tentative fix in #2559.

**Comment by immarvin** [comment]
hi @chenglch , is this issue fixed?

**Comment by chenglch** [comment]
@immarvin yes , this issued is fixed by #2559, only test case is needed.

**Comment by hu-weihua** [comment]
@neo954 ,could you  help to verify this fix, thanks

**Comment by tingtli** [comment]
@hu-weihua  Is this what i have verified ? I have send the mails to all the team. The title is "Verification result for encrypted passwords in the passwd table (bug #2558 and #1890) "

**Comment by zet809** [comment]
Thx @tingtli , you are right, I will close this defect.

**Comment by hu-weihua** [comment]
It is great, thanks @tingtli
