### ISSUE TITLE
[FVT]:EXECUTE in syncfile does not execute file sync on RH7

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#257]
```
[root@c910f02c01p13 /]# lsxcatd -v
Version 2.11 (git commit 4bbde501196b0c1aa6e83277023c8cce7a244f8f, built Tue Oct 13 06:19:47 EDT 2015) 

[root@c910f02c01p13 /]# cat /install/custom/netboot/rh/compute.synclist
/tmp/file.post -> /tmp/file.post
EXECUTE:
/tmp/file.post

[root@c910f02c01p13 /]# updatenode c910f02c02p27 -F
c910f02c02p27: File synchronization has completed for nodes.

[root@c910f02c01p13 /]# xdsh c910f02c02p27 cat /tmp/test
c910f02c02p27: hello
```

**Comment by whowutwut** [comment]
@tingtli , I removed the following from your post above. 

```
c910f02c02p27: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
c910f02c02p27: @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
c910f02c02p27: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
c910f02c02p27: IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
c910f02c02p27: Someone could be eavesdropping on you right now (man-in-the-middle attack)!
c910f02c02p27: It is also possible that a host key has just been changed.
c910f02c02p27: The fingerprint for the ECDSA key sent by the remote host is
c910f02c02p27: e9:ac:23:d9:ea:ab:9a:b0:c2:17:54:d9:26:1a:f6:18.
c910f02c02p27: Please contact your system administrator.
c910f02c02p27: Add correct host key in /root/.ssh/known_hosts to get rid of this message.
c910f02c02p27: Offending ECDSA key in /root/.ssh/known_hosts:1
c910f02c02p27: Password authentication is disabled to avoid man-in-the-middle attacks.
c910f02c02p27: Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
```

And wrapped the contents with ``` to make it code markdown

We should enhance the testing framework to clear the ``/root/.ssh/known_hosts`` file before the testing starts  since xCAT re-provisions the machine and the keys ALWAYS change

**Comment by whowutwut** [comment]
I also noticed that the compute.synclist is doing ``/tmp/file.post``... but we are catting ``/tmp/test``.... 

Am I reading this correctly?

**Comment by whowutwut** [comment]
Hi @tingtli , what is the contents suppose to be in /tmp/test?  Is "hello" correct?

**Comment by tingtli** [comment]
Yes. It is a simple script to write "hello" in /tmp/test.

**Comment by whowutwut** [comment]
Did the test above fail because of the man in the middle warning messages?

**Comment by tingtli** [comment]
No, it failed not because of the waring message.It is because the file /tmp/test is not created.

**Comment by whowutwut** [comment]
Maybe I'm confused... can you take a look at the initial post again.  I removed the man in the middle warning messages and see the following now: 

```
[root@c910f02c01p13 /]# cat /install/custom/netboot/rh/compute.synclist
/tmp/file.post -> /tmp/file.post
EXECUTE:
/tmp/file.post

[root@c910f02c01p13 /]# updatenode c910f02c02p27 -F
c910f02c02p27: File synchronization has completed for nodes.

[root@c910f02c01p13 /]# xdsh c910f02c02p27 cat /tmp/test
c910f02c02p27: hello
```

Isn't /tmp/test created with "hello"?

**Comment by whowutwut** [comment]
Ok I see the problem, the regression testing had the same issue today and we looked at it further...
```
[xdsh c910f02c02p27 "cat /tmp/test"] Running Time:1 sec
RETURN rc = 1
OUTPUT:
c910f02c02p27: cat: /tmp/test: No such file or directory
```

Debugged this a bit and it seems like even in 2.10, this problem has existed for a long time. Will look to fix it.

**Comment by samveen** [comment]
@whowutwut Victor, can I suggest that the change you mentioned be implemented in the command `nodeset compute-x osimage=xyz` for a given node `compute-x`(clearing the key for `compute-x` from `~root/.ssh/known_hosts`). The required keys into `known_hosts` would probably be the node name and all node IPs (the `node.ip` and `node.nicips.*` attributes of the node object). I'll see if I can try and add something there.

**Comment by whowutwut** [comment]
@samveen   Do you see problem often in your use of xCAT.  We are constantly re-provisioning machines so I see it daily... but if the real world use case is not such, then it's probably not a big issue.    Just thinking for our regression testing scripts, it gets annoying to see that warning because it clouds the output of the test cases. 

Maybe something like this could be configured and/or documented instead of having xCAT change the known_hosts file... since maybe not all admins would appreciate it :-) 

From http://superuser.com/questions/141344/dont-add-hostkey-to-known-hosts-for-ssh,
```
Host *.mydomain.com 
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  User foo
  LogLevel QUIET
```

**Comment by samveen** [comment]
@whowutwut We're nowhere close to IBM's size (or even one of IBM's production clusters :) ) in terms of nodes managed by xCAT. However, as our infrastructure matures, we're constantly provisioning and re-provisioning machines. In fact, our reuse process for servers requires a provisioning a node using a decomm image, followed by the provision of the correct target osimage. For us, this means that the potential of colliding host keys in the known hosts file is very large. I know people in my team would appreciate the cleanup on re-provision.

**Comment by tingtli** [comment]
regression case passed, close this bug.
