### ISSUE TITLE
makedns fails with a noderange error - 'Undefined subroutine &xCAT_plugin::ddns::noderange'

### ISSUE THREAD

**Issue by CJCShadowsan** [xcat2/xcat-core#2572]
On running makedns -n after running makehosts on a 2.13.2 system:

xcatd: ddns plugin bug, pid 4719, process description: 'xcatd SSL: makedns for root@localhost: ddns instance' with error 'Undefined subroutine &xCAT_plugin::ddns::noderange called at /opt/xcat/lib/perl/xCAT_plugin/ddns.pm line 625, <$parfd> line 260.

This is installed on RHEL7.2.

I've checked to make sure the required libs are there, and they are:

`[root@mgmt01 xcat]# perl -I /opt/xcat/lib/perl/ -c /opt/xcat/lib/perl/xCAT_plugin/ddns.pm
/opt/xcat/lib/perl/xCAT_plugin/ddns.pm syntax OK
`

Any thoughts?

**Comment by immarvin** [comment]
it seems the node range() should be xCAT::NodeRange->noderange()

hi @bybai , would you please take a look at this? thanks

**Comment by CJCShadowsan** [comment]
@immarvin - surely enough changing:

`                    foreach my $host (noderange($hosts)) {
`
to

`                    foreach my $host (xCAT::NodeRange->noderange($hosts)) {
`

Works at line 625 of /opt/xcat/lib/perl/xCAT_plugin/ddns.pm.

**Comment by jjohnson42** [comment]
This is strange though...
our @EXPORT    = qw(noderange nodesmissed);

noderange should be placed into the namespace of the calling method...

**Comment by bybai** [comment]
Hi @jjohnson42 ,
I will reconsider it.
