### ISSUE TITLE
[FVT]: chdef -m should return correct warning message when some attributes is not permit to be changed.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2577]
xCAT 2.13.3

```
c910f03c17k27:~ # lsxcatd -v
Version 2.13.3 (git commit 83ebef0425f6059bb7e689a4b75981a207549991, built Wed Mar  1 06:16:09 EST 2017)
```
See chdef's manpage
```
       -m|--minus
                 If the value of the attribute is a list then this option may be used to remove one or more items from the list.
```
Here is the steps`
```
c910f03c17k27:~ # lsdef -l c910f03c17k29
Object name: c910f03c17k29
    arch=ppc64le
    cons=kvm
    currchain=boot
    currstate=statelite sles12.2-ppc64le-compute
    groups=all
    id=29
    mac=42:b1:0a:03:11:1d
    mgt=kvm
    monserver=c910f03c17k27
    netboot=grub2
    nfsserver=c910f03c17k27
    os=sles12.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,setupntp
    profile=compute
    provmethod=sles12.2-ppc64le-statelite-compute
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=failed
    statustime=03-01-2017 19:57:24
    tftpserver=c910f03c17k27
    vmcpus=4
    vmhost=c910f03c17
    vmmemory=6144
    vmnicnicmodel=virtio
    vmnics=brenP3p9s0f0
    vmstorage=phy:/dev/mapper/vdiskvg04-vdisk01n29
    xcatmaster=c910f03c17k27
c910f03c17k27:~ # chdef -m -t node c910f03c17k29 postscripts="syncfiles"
Warning: syncfiles is not in the attribute of 'postscripts' for the 'c910f03c17k29' definition.
1 object definitions have been created or modified.
c910f03c17k27:~ # tabdump postscripts
#node,postscripts,postbootscripts,comments,disable
"xcatdefaults","syslog,remoteshell,syncfiles","otherpkgs",,
"service","servicenode",,,
"c910f03c17k29","setupntp",,,
c910f03c17k27:~ # chdef -m -t node c910f03c17k29 postscripts="setupntp"
1 object definitions have been created or modified.
```

**Comment by whowutwut** [comment]
Is this a valid testcase? Do we allow/recommend users to remove the default postscripts?  

Regardless of whether it's valid, when I looked into this further, we have a more general problem where we print errors, but then allow the change to happen. 

Before:
```
[root@c910f02c05p02 ~]# tabdump postscripts | grep xcatdefaults 
"xcatdefaults","syslog,remoteshell,syncfiles","otherpkgs",,
```

Remove it: 
```
[root@c910f02c05p02 ~]# chdef -m xcatdefaults postscripts=syncfiles 
Error: Attribute 'groups' is not specified for node 'xcatdefaults', skipping to the next node.
Error: One or more errors occured when attempting to create or modify xCAT 
object definitions.
``` 
Why print the error above... but allow the command to succeed?   List out after: 
```
[root@c910f02c05p02 ~]# tabdump postscripts | grep xcatdefaults
"xcatdefaults","syslog,remoteshell","otherpkgs",,
```

Same thing when adding it back...
```
[root@c910f02c05p02 ~]# chdef -p xcatdefaults postscripts=syncfiles 
Error: Attribute 'groups' is not specified for node 'xcatdefaults', skipping to the next node.
Error: One or more errors occured when attempting to create or modify xCAT 
object definitions.
[root@c910f02c05p02 ~]# tabdump postscripts | grep xcatdefaults
"xcatdefaults","syslog,remoteshell,syncfiles","otherpkgs",,
```

My suggestion is for @tingtli bug reporting,
1) We are already not acting on the command she ran above, but we should NOT print `1 object definitions have been created or modified.`.  It should be 0 modifications.  
2) On the case I showed above, we should NOT allow the `chdef` command to make changes to the `xcatdefaults` field.  Changing this will affect xCAT.  Users can tabedit it and change it themselves, but that's at their own risk, we can only do our best to prevent this from happening.   Then the messages should change and resolve my comment anyway...

**Comment by tingtli** [comment]
@whowutwut @zet809  If we don't permit users to modify xcatdefault value. Then we should give correct warning message. Please remove the message when users execute following commands
```
c910f03c17k27:~ # chdef -m -t node c910f03c17k29 postscripts="syncfiles"
Warning: syncfiles is not in the attribute of 'postscripts' for the 'c910f03c17k29' definition.
1 object definitions have been created or modified.
```

**Comment by whowutwut** [comment]
Yes, I agree., should be 0 because nothing is changed. 

And the `chdef` on `xcatdefaults` prints an error but it allows the change to happen.  I think this should be blocked. If the user want to tabedit, we can't prevent bad things from happening, but with chdef command , we should block it.

**Comment by zet809** [comment]
1. change the manpage of postscript table: the attributes can not be operated with chdef for xcatdefault group
2. chdef shall return non-zero code for -m

**Comment by gurevichmark** [comment]
PR #3045 has made improvements to this issue. But I feel better messages are still needed. Opened new issue #3058 to address that.

**Comment by zet809** [comment]
hi, @tingtli , will you pls verify this issue? For a better error message, it will be covered in #3058. Thx!

**Comment by zet809** [comment]
Hi, @tingtli , you are right that the output is confusing. But, as we mentioned above, it is invalid to remove postscript from xcatdefault group, and for 'chdef -m', return non-zero is OK.

**Comment by tingtli** [comment]
since @gurevichmark has opened #3058 to trace the error message. I will close this one and use #3058 to trace the message issue.
