### ISSUE TITLE
[dev] makehosts  support Regular Expression for nicips in nics table

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2578]
refer to issue #2412 
After nicips.<interface> keyword expand regular expressions, makehosts and confignics should be enhanced to support Regular Expression for nicips.

Currently, after makehosts, the /etc/hosts is as following, confignics have the same problem
```
192.168.23.3 frame23cn03 frame23cn03.pok.stglabs.ibm.com
\D+(\d+)\D+(\d+) frame23cn03-ib0 frame23cn03-ib0.pok.stglabs.ibm.com
20.1.($1*1).($2*1) frame23cn03-ib0 frame23cn03-ib0.pok.stglabs.ibm.com
```

**Comment by whowutwut** [comment]
@bybai  Is this a feature or a bug? Did we never support regular expression for nicips like we do for ips?

**Comment by bybai** [comment]
Hi @whowutwut ,
makehosts and confignics does not support regular expression for nicips in old design.
So I think we can see it as a small feature.

**Comment by whowutwut** [comment]
Does the `makehost` support the ip attribute for the node? wouldn't that be similar?

**Comment by bybai** [comment]
Hi @whowutwut , we have plan to add this into next release. Thanks.

**Comment by whowutwut** [comment]
Also needed for https://github.com/xcat2/xcat-core/issues/2412, make sure that `makehosts` works for all scenarios.

**Comment by bybai** [comment]
After confignetwork integrate confignics, confignics will not add support regular expression.  After discussion in scrum meeting, this issue will only keep makehosts support expression for nicips in nics table.

**Comment by zet809** [comment]
Hi, @bybai , we have user encountered this issue and created defect #3409, so I close this one and use #3409 to trace this issue. Thx!

**Comment by whowutwut** [comment]
@zet809  I don't think we should close this one.  We should use this one to fix the problem and get it into xCAT. This parent issue has been around since Jan and this one was opened in March.  This is required for large cluster so we need to make this high priority. Having the multiple issues referenced should show that it's affecting multiple users.  Let's see if we can have a hard target for 2.13.16.  I think we have to fix this now.

**Comment by zet809** [comment]
Hi, @whowutwut , I have opened an issue #3649 to summary regular expression using in xCAT, so close this task.

**Comment by tingtli** [comment]
case is added in https://github.com/xcat2/xcat-core/pull/5188
