### ISSUE TITLE
[FVT］:go-xcat failed to install xcat packages on rhels6.9 Beta system

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2588]
xCAT 2.13.3
```
[root@c910f04x14v02 /]# cat /etc/*release*
Red Hat Enterprise Linux Server release 6.9 Beta (Santiago)
Red Hat Enterprise Linux Server release 6.9 Beta (Santiago)
cpe:/o:redhat:enterprise_linux:6server:beta:server

[root@c910f04x14v02 /]# ./go-xcat --xcat-core=/core-rpms-snap.tar.bz2 --xcat-dep=/xcat-dep-2.13.2-linux.tar.bz2 -y install
Operating system:   linux
Architecture:       x86_64
Linux Distribution: rhel
Version:            Beta

Reading repositories ...... failed
Failed to set locale, defaulting to C
Loaded plugins: product-id, search-disabled-repos, security, subscription-
              : manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Cleaning repos: local-rhels6.9-x86_64-HighAvailability
              : local-rhels6.9-x86_64-LoadBalancer
              : local-rhels6.9-x86_64-ResilientStorage
              : local-rhels6.9-x86_64-ScalableFileSystem
              : local-rhels6.9-x86_64-Server local-rhels6.9-x86_64-x86_64
              : xcat-2-core xcat-dep
0 metadata files removed
0 sqlite files removed
0 metadata files removed
go-xcat: invalid xcat-dep URL
Failed to set locale, defaulting to C
Loaded plugins: product-id, search-disabled-repos, security, subscription-
              : manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Cleaning repos: local-rhels6.9-x86_64-HighAvailability
              : local-rhels6.9-x86_64-LoadBalancer
              : local-rhels6.9-x86_64-ResilientStorage
              : local-rhels6.9-x86_64-ScalableFileSystem
              : local-rhels6.9-x86_64-Server local-rhels6.9-x86_64-x86_64
              : xcat-2-core xcat-dep
0 metadata files removed
0 sqlite files removed
0 metadata files removed
```

**Comment by tingtli** [comment]
@neo954  Please help to fix this issue. We need to verify rhels6.9 quickly. Thanks!

**Comment by neo954** [comment]
Pull request #2590 fixed this issue. @tingtli, please review the patch.

**Comment by neo954** [comment]
@tingtli, patch merged, please verify this bug.

**Comment by neo954** [comment]
# /tmp/go-xcat check
    Operating system:   linux
    Architecture:       x86_64
    Linux Distribution: rhel
    Version:            6.9

    Reading repositories ...... done

    xCAT Core Packages
    ==================

    Package Name                Installed                      In Repository
    ------------                ---------                      -------------
    perl-xCAT                   2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT                        2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-SoftLayer              (not installed)                2.13.3-snap201703022155
    xCAT-buildkit               2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-client                 2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-confluent              (not installed)                2.13.3-snap201703022155
    xCAT-csm                    (not installed)                2.13.3-snap201703022155
    xCAT-genesis-scripts-ppc64  2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-genesis-scripts-x86_64 2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-probe                  2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-server                 2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-test                   2.13.3-snap201703022155        2.13.3-snap201703022155
    xCAT-vlan                   (not installed)                2.13.3-snap201703022155
    xCATsn                      (not installed)                2.13.3-snap201703022155

    xCAT Dependency Packages
    ========================

    Package Name                Installed                      In Repository
    ------------                ---------                      -------------
    conserver-xcat              8.1.16-10                      8.1.16-10
    cpio                        2.10-13.el6                    2.11-20
    elilo-xcat                  3.14-4                         3.14-4
    esxboot-xcat                (not installed)                1.0.0-2
    fping                       (not installed)                2.4b2_to-2
    grub2-xcat                  2.02-0.16.el7.snap201506090204 2.02-0.16.el7.snap201506090204
    ipmitool-xcat               1.8.17-1                       1.8.17-1
    lldpd                       (not installed)                0.7.15-6.1
    perl-AppConfig              (not installed)                1.52-4
    perl-Crypt-CBC              2.29-3.el6                     2.29-3.el6
    perl-Crypt-Rijndael         1.09-2.el6                     1.09-2.el6
    perl-Expect                 1.21-1                         1.21-1
    perl-HTTP-Async             0.30-2                         0.30-2
    perl-IO-Stty                0.03-1                         0.03-1
    perl-IO-Tty                 1.07-1                         1.07-1
    perl-JSON                   2.50-1.el6.rfx                 2.50-1.el6.rfx
    perl-Net-HTTPS-NB           0.14-2                         0.14-2
    perl-SOAP-Lite              0.710.08-1                     0.710.08-1
    perl-XML-Simple             2.18-1                         2.18-1
    pyodbc                      (not installed)                3.0.3-1
    scsi-target-utils           (not installed)                1.0.24-18.el6
    syslinux-xcat               3.86-2                         3.86-2
    systemconfigurator          (not installed)                2.2.11-1
    systemimager-client         (not installed)                4.3.0-0.1
    systemimager-common         (not installed)                4.3.0-0.1
    systemimager-server         (not installed)                4.3.0-0.3
    xCAT-UI-deps                (not installed)                2.8-2
    xCAT-genesis-base-ppc64     2.13.2-snap201702150049        2.13.2-snap201702150049
    xCAT-genesis-base-x86_64    2.13.2-snap201702200120        2.13.2-snap201702200120
    xCAT-genesis-x86_64         (not installed)                2.7.7-snap201301100842
    xnba-kvm                    (not installed)                1.0.3-131028
    xnba-undi                   1.0.3-131028                   1.0.3-131028
    yaboot-xcat                 1.3.17-rc1                     1.3.17-rc1

**Comment by tingtli** [comment]
It is verified by autotest. Close it.
