### ISSUE TITLE
Provide console support against BMC's running openbmc firmware

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2594]
While openbmc does have ipmi backwards compatibility, it does not plan to support `sol activate` for the SOL console.  Rather it will open port 2200 on the BMC to provide console access.

**Comment by zet809** [comment]
@whowutwut Hi, Victor, does the label 'Epic' mean it is a Story within a release or sprint? If so, how to identify a task within an 'Epic'? Do you think we shall have another label such as sprint_items to filter the story and tasks for a sprint?

**Comment by whowutwut** [comment]
Closing this Issue, we have a larger OpenBMC epic created 2600 that it's being tracked under
