### ISSUE TITLE
[customer]the entire statelite image is rw in sles12sp2 x86_64

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2599]
From customer Lenovo (critical) The entire image is RW – For some reason, the rootimg is mounted as rw and the compute nodes can actually write to anywhere is the rootimg and change it. needless to say, this is a huge issue for statelite J.   The elilo file in the tftproot dir looks ok and the line has ro as the mount option, I am not clear on when or how it was changed to rw. 

I can reproduce it in my env.

**Comment by whowutwut** [comment]
How was this reported? User list?

**Comment by immarvin** [comment]
hi @whowutwut , this issue is reported through mail.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2628#pullrequestreview-26231875 by @bybai

**Comment by bybai** [comment]
how to test:
genimage <statelite_osimage>
liteimg <statelite_osimage>
rinstall <node> osimage=<statelite_osimage>
