### ISSUE TITLE
[EPIC] OpenBMC support - openbmc-rest

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2600]
Creating this epic to track the following pieces in xCAT that would need to be modified to support the new openbmc firmware.   The 1st stage is to support the restful interfaces that openbmc provides, the 2nd stage (*future*) is to support openbmc using the redfish 1.0 specification. 

Planned External Changes: 
```
mgt=openbmc
cons=openbmc
``` 

* framework to support new mgmt type
* rcons
* rinv 
* rpower

**Comment by whowutwut** [comment]
Playing with this epic to see how we can track this better...

**Comment by zet809** [comment]
The renergy support and #3136 are traced in xcat2/xcat2-task-management#23, so close this EPIC.
