### ISSUE TITLE
stateful with rhels7.3 doesn't set hostname

### ISSUE THREAD

**Issue by wiede-man** [xcat2/xcat-core#2607]
Hi all,

I'm using xCAT 2.13.1 and recently switched my rhels7.2 stateful templates to rhels7.3.
Since then, the kickstart installation is using:

network  --hostname=localhost.localdomain

Instead of:

network --hostname=node101.clusterdomain

When I switch back to rhels7.2 it's working properly again...
Any idea how to fix that?

Thank you!

**Comment by wiede-man** [comment]
Same problem with 2.13.2...

**Comment by immarvin** [comment]
please provide the node and osimage definition

**Comment by immarvin** [comment]
and the output of ``tabdump site``

**Comment by wiede-man** [comment]
Node with rhels7.3 (host installed as localhost.localdomain)

[root@gxfsadmin ~]# lsdef node101 -l

Object name: node101                                                                                                                                             arch=x86_64                                                                                                                                            bmc=10.221.120.143                                                                                                                               
    currchain=boot
    currstate=boot
    groups=all,nsd,meta
    initrd=xcat/osimage/rhels7.3-x86_64-install-nsdserver/initrd.img
    ip=10.65.120.143
    kcmdline=quiet inst.repo=http://10.65.120.124:8081/install/rhels7.3/x86_64 inst.ks=http://10.65.120.124:8081/install/autoinst/f01-120-143 ip=dhcp 
    kernel=xcat/osimage/rhels7.3-x86_64-install-nsdserver/vmlinuz
    mac=4c:cc:6a:21:aa:ab
    mgt=ipmi
    netboot=pxe
    nicdevices.bond0=ens27f0|ens27f1
    nicdevices.bond0.797=bond0
    nicips.bond0=10.65.120.143
    nicips.bond0.797=172.18.224.1
    nicnetworks.bond0=network_120
    nicnetworks.bond0.797=daemon-interface
    nictypes.ens27f0=ethernet
    nictypes.ens27f1=ethernet
    nictypes.bond0=bond
    nictypes.bond0.797=vlan
    os=rhels7.3
    otherinterfaces=node101-gpfs:172.18.224.1,mnode101:10.221.120.143
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignetwork,setroute
    power=ipmi
    profile=nsdserver
    provmethod=rhels7.3-x86_64-install-nsdserver
    routenames=route_120
    status=booted
    statustime=03-07-2017 22:26:39
    tftpserver=10.65.120.124
    updatestatus=synced
    updatestatustime=03-03-2017 09:57:34
    xcatmaster=10.65.120.124


Node with rhels7.2 (host installed as node102.clusterdomain)

[root@gxfsadmin ~]# lsdef node102 -l

Object name: node102                                                                                                                                             arch=x86_64                                                                                                                                            
    bmc=10.221.124.143
    currchain=boot
    currstate=install rhels7-x86_64-nsdserver
    groups=all,nsd,meta
    initrd=xcat/osimage/rhels7-x86_64-install-nsdserver/initrd.img
    ip=10.65.124.143
    kcmdline=quiet inst.repo=http://10.65.120.124:8081/install/rhels7 inst.ks=http://10.65.120.124:8081/install/autoinst/f01-124-143 ip=dhcp 
    kernel=xcat/osimage/rhels7-x86_64-install-nsdserver/vmlinuz
    mac=4c:cc:6a:85:ad:fb
    mgt=ipmi
    netboot=pxe
    nicdevices.bond0=ens27f0|ens27f1
    nicdevices.bond0.797=bond0
    nicips.bond0=10.65.124.143
    nicips.bond0.797=172.18.224.2
    nicnetworks.bond0=network_124
    nicnetworks.bond0.797=daemon-interface
    nictypes.ens27f0=ethernet
    nictypes.ens27f1=ethernet
    nictypes.bond0=bond
    nictypes.bond0.797=vlan
    os=rhels7
    otherinterfaces=node102-gpfs:172.18.224.2,mnode102:10.221.124.143
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignetwork,setroute
    power=ipmi
    profile=nsdserver
    provmethod=rhels7-x86_64-install-nsdserver
    routenames=route_124
    status=booted
    statustime=03-07-2017 23:26:53
    tftpserver=10.65.120.124
    updatestatus=failed
    updatestatustime=03-02-2017 12:24:37
    xcatmaster=10.65.120.124


[root@gxfsadmin ~]# tabdump site
#key,value,comments,disable
"auditnosyslog","0",,
"auditskipcmds","ALL",,
"blademaxp","64",,
"cleanupxcatpost","no",,
"consoleondemand","no",,
"databaseloc","/var/lib",,
"db2installloc","/mntdb2",,
"dhcplease","43200",,
"dhcpsetup","n",,
"dnshandler","ddns",,
"domain","clusterdomain",,
"enableASMI","no",,
"forwarders","10.97.1.193,10.97.104.194",,
"fsptimeout","0",,
"httpport","8081",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"master","10.65.120.124",,
"maxssh","8",,
"nameservers","10.65.120.124",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"powerinterval","0",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"setinstallnic","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"sshbetweennodes","ALLGROUPS",,
"syspowerinterval","0",,
"tftpdir","/tftpboot",,
"timezone","Europe/Berlin",,
"useNmapfromMN","no",,
"vsftp","n",,
"xcatconfdir","/etc/xcat",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatsslversion","TLSv1",


Let me mention that the DHCP server on the xcatmaster has been masked as we need to use the customer's DHCP server. The DHCP definition for a node looks like this (and deployment is working this way):

host node101-eth0 {
     hardware ethernet 4C:CC:6A:21:AA:AB;
     option host-name "node101";
     fixed-address 10.65.120.143;
     filename "pxelinux.0";
     next-server 10.65.120.124;
}


Thank you for your assistance!

**Comment by wiede-man** [comment]
I changed the symlink from rhels7.2 to rhels7.3 and deployed the nodes with the rhels7-x86_64-install-nsdserver template. The nodes came up as localhost.localdomain, so it must be something that's no longer working with RHEL 7.3...

**Comment by immarvin** [comment]
would you please provide "/install/custom/install/rh/nsdserver.rhels7.tmpl"? how did you create this customized kickstart template? if based on the default template shipped by xCAT, please take a look at the diff of the template based on which the customized template is created  and the latest template xCAT shipped.

**Comment by immarvin** [comment]
no response over 2 weeks, will close this ticket now , please reopen it if any update
