### ISSUE TITLE
corporate CLA submitted

### ISSUE THREAD

**Issue by khm** [xcat2/xcat-core#2611]
Greetings,

On 3 March 2017 I sent in a signed organizational CLA on behalf of Battelle Memorial Institute at Pacific Northwest National Laboratory.  Please let me know what else I need to do to get us approved to contribute.

Thanks!

**Comment by whowutwut** [comment]
Hi Kurt, Thanks for creating this issue. I had written a note back and it was actually stuck in my drafts.  I apologize.  Can you check again if you had attached the CLA, the email that I got did not have an attachment.  Thanks, Victor

**Comment by whowutwut** [comment]
@khm , Excellent, I got the PDF.  I've added your ID to the contributors for xcat2 project.   If in the future , if you have other members of your organization that require access, please just let us know the org (if we forget) and someone monitoring will verify and add them as well.   No need to resend the CCLA
