### ISSUE TITLE
hostname is linux in sles12.2 statelite

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2616]
After provisioning statelite sles12.2, the system hostname is linux.

**Comment by bybai** [comment]
Hi @immarvin,
Besides the code change, the following should be added into litefile table:
 "ALL","/etc/hostname","tmpfs",,

**Comment by immarvin** [comment]
hi @bybai , should be mentioned in http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/statelite/config_statelite.html#sample-data-for-sles-statelite-setup

**Comment by bybai** [comment]
Hi @immarvin , the documentation is updated.

**Comment by junxiawang** [comment]
@bybai 
Now the issue still exist
After sles12.2 statelite installtion:
On management node:
xdsh c910f03c11k14 hostname 

c910f03c11k14: linux
------> could not get hostname on sles12.2 statelite installation hierarchy by nfs

**Comment by bybai** [comment]
The litefile_sles.csv in autotest case is not updated as my issue described. Fixed in #3263

**Comment by bybai** [comment]
Verified in autotest environment.
