### ISSUE TITLE
[fvt]testcase for genesis need to modify on ppc64 environment

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2618]
env:ppc64
build:
[root@c910f02c08p05 ~]# lsxcatd -v
Version 2.13.3 (git commit 0e53d7936e739174f1d93f758f4dc157d4f8d177, built Wed Mar  8 06:15:49 EST 2017)
[root@c910f02c08p05 ~]# 
How to reproduce:
```
Test case : nodeset_shell, nodeset_cmdline, nodeset_runimg failed on ppc64 for genesis does not support ppc64 machine .So I need to modify test cases here .
```

**Comment by whowutwut** [comment]
Clear the milestone, let's set one if we are still looking at this.

**Comment by hu-weihua** [comment]
duplicate with #2833, close this one.
