### ISSUE TITLE
[FVT]:add mkdef/rmdef cases to test wildcard and regular expression  for range parameters.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2619]
add mkdef/rmdef cases to test wildcast and range parameters

**Comment by tingtli** [comment]
Reference #2707

**Comment by tingtli** [comment]
@zet809  I would like to get some information that what parameters could users use to define the node range.  I didn't find the help information in xCAT object definition for how to use wild card and regular expression to define node range.

**Comment by neo954** [comment]
Will add three to four test cases for typical scenarios.
