### ISSUE TITLE
insalling OS in a KVM node using PXE 

### ISSUE THREAD

**Issue by monyaaltuwaigi** [xcat2/xcat-core#2622]
i am trying to install OS in one of the compute node from my master node. i tried to installed using tftp server. when i reboot the compute node it stop at http://10.0.05/tftpboot/xcat/genesis.kernal.x86_64. 
i don`t know what the problem, i am actually a beginner in using xcat. i hope somebody can help or is theirs another way to install OS to the compute node using PXE  
this is the definition of my compute node 
 addkcmdline=netwait=60
    arch=x86
    currchain=boot
    currstate=install centos7.3-x86_64-compute
    groups=compute,all
    interface=eth1
    ip=10.0.0.10
    mac=52:54:00:fe:81:8b
    mgt=kvm
    netboot=pxe
    nodetype=vm
    os=centos6
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    power=kvm
    profile=64-base
    provmethod=install
    status=powering-on
    statustime=03-09-2017 21:15:24
    vmcpus=1
    vmhost=10.0.0.1
    vmmemory=1000
    vmstorage=ftp://10.0.0.5/pub/
    xcatmaster=master.uva.com

**Comment by immarvin** [comment]
hi @monyaaltuwaigi ,please run ``detect_dhcpd -i <nic on mn facing the compute node> -m <mac of the compute node>`` on your mn to check whether the dhcp lease on mn is ready and whether there is another node response the dhcp discover request from the compute node

**Comment by zet809** [comment]
Seems to me 3 reasons:
1. haven't run makehost/makedns
or 2. haven't run nodeset 
or 3. mac address is incorrect

**Comment by whowutwut** [comment]
We have a command "xcatprobe" that has a sub command that run to check the configuration of the management node and see if things are properly set up. Would be interested to know your feedback with using the command, being a new user

**Comment by monyaaltuwaigi** [comment]
i run the command xcatprobe xcatmn <mac address of the compute node> and it shows that there isn't NIC in current server and the IP  of the mac doesn't belong to any network defined in 'networks' table. i checked the mac address of the compute node and its correct, so i don`t know why  i can`t identify the mac address

**Comment by whowutwut** [comment]
@monyaaltuwaigi   Can you show us the output of: 
1) ip addr show 
2) The command you run for `xcatprobe xcatmn` 

You need to make sure the following is run... 
```
makedhcp -n 
makedns -n 
makehosts <node name>  # this adds an entry into /etc/hosts for the node 
```

How did you get the mac address for the VM? I should be generated by the `mkvm` command.. correct? 
```
mkvm <node> -s <size>
nodeset <node> osimage=centos7.3-x86_64-install-compute 
rpower <node> boot 
```

Can you copy and paste the actual error, that might help some more.  You might want to try `netboot=xnba` as well, which is xcat network boot agent, but pxe should work...

**Comment by whowutwut** [comment]
Closing, due to no response. Please reopen if needed.
