### ISSUE TITLE
Add site:key=httpport to scripts

### ISSUE THREAD

**Issue by wiede-man** [xcat2/xcat-core#2629]
Hi,

I need to use port 8081 for HTTP as 80 and 443 are used by different applications on the xCAT master.
It's nice to see that the httpport value in the site table is working (stateful installation is starting), but scripts need to be adapted to get the postscripts process working.

I have modified the post.xcat script and my kickstart templates are pointing to the modified one.
The changes to get it working are:

```
[root@xcatmaster /]# diff /install/custom/install/rh/scripts/post.xcat.modified /opt/xcat/share/xcat/install/scripts/post.xcat
4,5d3
< # Modified 2017-02-21 for different default http port
< #
13d10
< export HTTPPORT=#TABLE:site:key=httpport:value#
94c91
< wget -l inf -N -r --waitretry=10 --random-wait --retry-connrefused  -e robots=off -nH --cut-dirs=2 --reject "index.html*" --no-parent -t 20 -T 60 http://$MASTER_IP:$HTTPPORT$INSTALLDIR/postscripts/ -P /xcatpost
---
> wget -l inf -N -r --waitretry=10 --random-wait --retry-connrefused  -e robots=off -nH --cut-dirs=2 --reject "index.html*" --no-parent -t 20 -T 60 http://$MASTER_IP$INSTALLDIR/postscripts/ -P /xcatpost
116c113
< wget -N --waitretry=10 --random-wait --retry-connrefused -t 20 -T 60 http://$MASTER_IP:$HTTPPORT$TFTPDIR/mypostscripts/mypostscript.$NODE  -P /xcatpost 2> /tmp/wget.log
---
> wget -N --waitretry=10 --random-wait --retry-connrefused -t 20 -T 60 http://$MASTER_IP$TFTPDIR/mypostscripts/mypostscript.$NODE  -P /xcatpost 2> /tmp/wget.log
```

Is there a chance to get this implemented by default in future releases? Unless changed in the site table, $HTTPPORT should always be 80.

**Comment by immarvin** [comment]
hi @wiede-man , I searched the code, it seems there are lots of places missing support for ``site.httpport `` attribute , we will try to find out all the places which missed``site.httpport `` support and create a fix for this in the next release

**Comment by wiede-man** [comment]
Thank you! I appreciate that a lot.

**Comment by thilo-maurer** [comment]
I need the same thing!

One irritation:
```
httpport:    The port number that the booting/installing nodes should contact the
             http server on the MN/SN on. It is your responsibility to configure
             the http server to listen on that port - xCAT will not do that.
```
Ok, which config files do I have to change? @wiede-man Which ones did you change?

**Comment by thilo-maurer** [comment]
Related issues:
* https://github.com/xcat2/xcat-core/issues/5700
* https://github.com/xcat2/xcat-core/issues/5701

**Comment by robin2008** [comment]
Let's put this high priority and done it in 2.14.5
