### ISSUE TITLE
Man page bug: rspconfig

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#263]
In the EXAMPLES section of the manpage of rspconfig.

    EXAMPLES
           ·  To setup new ssh keys on the Management Module mm:

               B<rspconfig> mm snmpcfg=enable sshcfg=enable

The text `B<rspconfig>` is displayed instead of bold text. This should be fixed easier.

**Comment by neo954** [comment]
If anyone of the reviewer wants to read a rendered HTML page, please check the attachment.

[management.html.txt](https://github.com/xcat2/xcat-core/files/13028/management.html.txt)

**Comment by whowutwut** [comment]
FYI @daniceexi 

In addition, some of the pages are not being generated correctly using the pod2rst.... 
Here's the screen capture between RTD and the terminal man page.... Just to point one out..
If we take a look at rspconfig man page, we can see many formatting issues...  Also there are compile issues. . Is pod2rst the best way to do this? 

![image](https://cloud.githubusercontent.com/assets/10049070/10495897/318e6536-728c-11e5-9930-4b684c270fb4.png)

**Comment by whowutwut** [comment]
Regardless of the convesation above

@pdlun92   please branch off your forked copy and use this defect as practice for creating pull request to fix this issue above.

**Comment by whowutwut** [comment]
@pdlun92 , Once the pull request has been merged, add the "pending" label to the issue so the originator knows it's ready to verify.

**Comment by pdlun92** [comment]
Added. When can I close?

**Comment by whowutwut** [comment]
You can let the originator be responsible for verifying and closing out the Issues

**Comment by neo954** [comment]
Already fixed. I will close this one.
