### ISSUE TITLE
copycds issues when using -p path option

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2630]
@immarvin  Pull request #2050 broke `copycds -p` ...  that was addressing issue #1852.  Decided to open another issue to track this in the correct release. 

## Issue 1 

Running the command: `copycds -p /install/RHEL-7.3-20161019.0-Server/ppc64le /iso/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso`  destroys the path... 

```
    148                 print "VKHU_DEBUG path=$path\n";
    149                 $path=Cwd::realpath($path); <====== problem line
    150                 print "VKHU_DEBUG path=$path\n";
    151                 unless(substr($path,0,length("/install")) eq "/install"){
    152                     $callback->({ warning => "copycds: the specified path \"$path\" is not a subdirectory under /install. Make sure this path is configured for httpd/apache, otherwise, the provisioning w        ith this iso will fail!" });
    153                 }
```

```
VKHU_DEBUG path=/install/RHEL-7.3-20161019.0-Server/ppc64le
Use of uninitialized value $path in concatenation (.) or string at /opt/xcat/lib/perl/xCAT_plugin/copycds.pm line 150.
VKHU_DEBUG path=
```

If I run the command: 
```
copycds -p /install/RHEL-7.3-20161019.0-Server -a ppc64le /iso/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
```
it puts the ISO image in `/install/RHEL-7.3-20161019.0-Server/` instead of `/install/RHEL-7.3-20161019.0-Server/ppc64le` 

## Issue 2... 
```
# copycds -p /install/RHEL-7.3-20161019.0-Server/ppc64le /iso/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
Warning: copycds: the specified path "" is not a subdirectory under /install. Make sure this path is configured for httpd/apache, otherwise, the provisioning with this iso will fail!
Copying media to /install/rhels7.3/ppc64le
Media copy operation successful
```

I think this should NOT be a warning, we should prevent the copycds to happen if we are not using the path provided by the user.  The path is specified here and then we default to `rhels7.3/ppc64le`

**Comment by immarvin** [comment]
hi @whowutwut , the issue 1 is the designed behavior, ``copycds -p $path`` will copy the iso contents into $path, ``-a $arch`` will not be appended to $path;

the issue 2 is a bug, the root cause is that when "$path" does not exist, ``Cwd::realpath`` will return "";

i also  found another issue 3 during debugging, ``copycds -p /installm`` should be complained since ``/installm`` is not a directory under ``/install``

the issue 2 and 3 are fixed in https://github.com/xcat2/xcat-core/pull/2635

**Comment by whowutwut** [comment]
@immarvin  Thanks, issue 1 didn't work with the current code ,so even when I tried to specify the `pp64le` it didn't let me.  Hopefully with your fixes , we will be able to provide the exact path.  Setting to pending...  Will try and verify this ASAP

**Comment by whowutwut** [comment]
Verified this issue with build `Version 2.13.3 (git commit 7bd281016189ca71a1e7c8e93774c077477330b0, built Mon Mar 20 06:15:41 EDT 2017)`

### Issue 1
```
[root@fs2vm105 ~]# ls -ltr /install/RHEL-7.3-20161019.0-Server/ppc64le/media.repo
ls: cannot access /install/RHEL-7.3-20161019.0-Server/ppc64le/media.repo: No such file or directory

[root@fs2vm105 ~]# copycds -p /install/RHEL-7.3-20161019.0-Server/ppc64le /tmp/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
Copying media to /install/RHEL-7.3-20161019.0-Server/ppc64le
Media copy operation successful

[root@fs2vm105 ~]# ls -ltr /install/RHEL-7.3-20161019.0-Server/ppc64le/media.repo
-r--r--r-- 1 root root 114 Oct 19 18:25 /install/RHEL-7.3-20161019.0-Server/ppc64le/media.repo
[root@fs2vm105 ~]# rm -rf /install/RHEL-7.3-20161019.0-Server
```
### Issue 2
```
[root@fs2vm105 ~]# copycds -p /install/RHEL-7.3-20161019.0-Server -a ppc64le /tmp/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
Copying media to /install/RHEL-7.3-20161019.0-Server
Media copy operation successful

[root@fs2vm105 ~]# ls -ltr /install/RHEL-7.3-20161019.0-Server/media.repo
-r--r--r-- 1 root root 114 Oct 19 18:25 /install/RHEL-7.3-20161019.0-Server/media.repo
```

### Issue 3 
```
[root@fs2vm105 ~]# copycds -p /installm/RHEL-7.3-20161019.0-Server/ppc64le /tmp/RHEL-7.3-20161019.0-Server-ppc64le-dvd1.iso
Warning: copycds: the specified path "/installm/RHEL-7.3-20161019.0-Server/ppc64le" is not a subdirectory under /install. Make sure this path is configured for httpd/apache, otherwise, the provisioning with this iso will fail!
Copying media to /installm/RHEL-7.3-20161019.0-Server/ppc64le
Media copy operation successful

[root@fs2vm105 ~]# ls -ltr /installm/RHEL-7.3-20161019.0-Server/ppc64le/media.repo
-r--r--r-- 1 root root 114 Oct 19 18:25 /installm/RHEL-7.3-20161019.0-Server/ppc64le/media.repo
```

The changes look good.

**Comment by tingtli** [comment]
Test cases are added by PR#2714

**Comment by whowutwut** [comment]
@tingtli  Please make sure you reference the **issue from the pull request,** then we can get a link to see that it's merged..  I will do that now...  Also once you add "testcase_added" please remove the testcase_requested so we can filter correctly...

**Comment by tingtli** [comment]
@whowutwut  I don't know why. But seems when i use #2714 past, i can click it and got to this PR.
