### ISSUE TITLE
confignics, makedns and externally-managed network

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2633]
Hi!

I need to configure an node interface on an external network (ie. a network that is not managed by xCAT).

I declared the network in the the `networks` table and the interface parameters in the `nics` table. The problem is that xCAT tries to generate a DNS zone for that external domain when running `makedns`. And fails with:
```
Error: Failure encountered updating <external.network>, error was NOTZONE. See more details in system log.
```

If I comment the network, then `makedns` doesn't generate the zone nor update the node record, which is good. But then, `confignics` doesn't configure the interface either, with the following error: 
```
confignics on <nodename>: Error: Can not find the corresponding network defination for ip address: <xxx.xxx.xxx.xxx>
```

So, what's the recommended way to configure an interface on a network that xCAT doesn't control?

**Comment by whowutwut** [comment]
@bybai Is this a bug , i see you added a label,  do we have a recommendation for @kcgthb  for his last question?

**Comment by bybai** [comment]
Hi @kcgthb ,
Thanks your issue to point the conflicts.
From your comments, makedns does not need configure the external network, while confignics need to configure the external network, they have conflicts, and you have the ugly work around to avoid block your work, am I right?

The confignics should configure network. So let me investigate how makedns avoid the conficts soon.

**Comment by kcgthb** [comment]
Hi @bybai 

That's correct: `makedns` should not create zones for commented networks, but I think that `confignics` should still use the information from all the networks in the `networks` table (including the commented ones) to configure the NICs on the nodes if they need to be configured.

Thanks!

**Comment by bybai** [comment]
Hi @kcgthb ,
Since network is important for `confignics`,  we can only consider to enhance makedns use external network part.

**Comment by kcgthb** [comment]
I'm not sure I understand what you're suggesting, but `confignics` should indeed take commented networks into account. 

`makedns` should continue to ignore commented networks.

**Comment by bybai** [comment]
Hi @kcgthb , thanks your suggestion, will consider it later.

**Comment by kcgthb** [comment]
The issue actually comes from the way `$NETWORKS_LINES` is obtained by `confignics`.
This variable comes from the [`tabdump(networks)`](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/mypostscript/mypostscript.tmpl#L23) call in [`mypostscript.tmpl`](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/mypostscript/mypostscript.tmpl).

That `tabdump()` function calls `dump_all_attribs_in_tabs()` in `Postage.pm`, which in turns calls `getAllEntries()` in `Table.pm`.

That `getAllEntries()` function by default doesn't return commented entries. Maybe when dumping the `networks` table contents it should also return disabled entries (with `getAllEntries("all")`)?

**Comment by bybai** [comment]
Hi @kcgthb , thanks your suggestion, will consider it later.

**Comment by bybai** [comment]
Hi @kcgthb , we will start next release soon, this will be added into next release plan.

**Comment by kcgthb** [comment]
Hi! 

I just wanted to check what the status was for this issue. We currently have to manually edit the generated `/etc/named.conf` file each time we run `makedns`, which is not very convenient... :)

Thanks!

**Comment by whowutwut** [comment]
@bybai  I removed the target milestone, please set one when you have it planned out.

**Comment by ChristopherWalker** [comment]
We are currently facing what looks to be the same issue (Our issue is that having added the network, reverse DNS lookups don't work correctly - but I think the cause and fix will be the same).

**Comment by kcgthb** [comment]
Stumbled upon this again recently, so for posterity, the fix here is to:
1. declare the external network in the `networks` table, 
2. keep it un-commented to allow `confignics` to properly configure interfaces during node deployment, 
3. and make sure that the network has external `nameservers` defined:
```
# lsdef -t network net_name
Object name: net_name
    domain=external_name
    [...]
    nameservers=aaa.aaa.aaa.aaa,bbb.bbb.bbb.bbb
    [...]
```

With that, `makedns` will skip interfaces associated to this external network and log something like:
```
Ignoring host <nodename>, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
```


So there's no bug to fix here, all the required features are already present, it's just a matter of configuring external `nameservers` for external networks.
