### ISSUE TITLE
Quotes in tables' comment field break mypostscript

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2634]
Using simple quotes (`'`) in the comment field of a table (at least the `networks`) table will break postscripts, as the `mypostscript` template will dump table entries without escaping those simple quotes. As a result, we get mismatched quotes in `/xcatpost/mypostscript`.

For instance:
```
# lsdef -t network test_net
Object name: test_net
    mask=255.255.255.0
    net=1.2.3.4
    usercomment=don't use
```
results in the following line in `/xcatpost/mypostscript`, being generated by `tabdump(networks)` in `mypostscript.tmpl`:
```
NETWORKS_LINE1='netname=test_net||net=1.2.3.4||mask=255.255.255.0||mgtifname=||gateway=||dhcpserver=||tftpserver=||nameservers=||ntpservers=||logservers=||dynamicrange=||staticrange=||staticrangeincrement=||nodehostname=||ddnsdomain=||vlanid=||domain=||mtu=||disable=||comments=don't use'
export NETWORKS_LINE1
```
(notice the un-escaped quote in `don't`)

The following error is logged in `xcat/commands.log` on the MN when running a postscript:
```
<nodename>: //xcatpost/mypostscript: line 271: unexpected EOF while looking for matching `''
<nodename>: //xcatpost/mypostscript: line 277: syntax error: unexpected end of file
```

Single quotes should probably be escaped by the `tabdump()` function

**Comment by zet809** [comment]
HI, @bybai , will you pls take a look at this issue? Thx!

**Comment by bybai** [comment]
Hi @kcgthb , this will be fixed within this sprint within 3 weeks.

**Comment by bybai** [comment]
Fixed in pull request #2716

**Comment by hu-weihua** [comment]
@junxiawang , Could you help to verify this issue? thanks

**Comment by bybai** [comment]
testcase #2769

**Comment by bybai** [comment]
It is verified through autotest.
