### ISSUE TITLE
confignics "SLAVE" is misspelled on line 239 and 241

### ISSUE THREAD

**Issue by m0rbo** [xcat2/xcat-core#2638]
Hi, i was looking into a different issue and noticed the misspelling of the word "SLAVE" on these two lines in the confignics file:

239:        str_temp=`ifconfig -a | grep flags | grep -vi loopback | grep -v SALVE | grep -v MASTER | awk -F: {'print $1'}`
241:        str_temp=`ip link show | grep -v link | grep -vi loopback | grep -v SALVE | grep -v MASTER | awk {'print $2'} | sed s/://`

**Comment by whowutwut** [comment]
Thanks for reporting this!

**Comment by bybai** [comment]
This has been fixed in 2.13.3. I will close this issue. Thanks

**Comment by bybai** [comment]
Duplicate with #2545
