### ISSUE TITLE
makehosts erroneously deletes entries from /etc/hosts

### ISSUE THREAD

**Issue by john-d-williams** [xcat2/xcat-core#2657]
The **makehosts** command erroneously removes nodes from /etc/hosts which are a super-string of the pattern match e.g. s01r1b01 is a super string of s01.  

**nodeadd s01 groups=service
nodeadd s01r1b01 groups=compute**

**tabdump hosts**
#node,ip,hostnames,otherinterfaces,comments,disable
"compute","|s(\d+)r(\d)b(\d+)$|10.2.0.1|",,,,
"service","|s(\d+)$|10.2.0.254|",,,,

**lsdef  s01**
Object name: s01
    groups=service
    ip=10.2.0.254
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
**lsdef  s01r1b01**
Object name: s01r1b01
    groups=compute
    ip=10.2.0.1
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles

# Creates entry in /etc/hosts for s01r1b01 as expected.
**makehosts compute
grep s01 /etc/hosts**
10.2.0.1 s01r1b01 s01r1b01.lab1.net 

# Create s01 entry as expected, but wrongly deletes s01r1b01
**makehosts service
grep s01 /etc/hosts**
10.2.0.254 s01 s01.lab1.net 

# However works OK, with single invocation of the command.
**makehosts compute,service
grep s01 /etc/hosts**
10.2.0.254 s01 s01.lab1.net 
10.2.0.1 s01r1b01 s01r1b01.lab1.net

**Comment by immarvin** [comment]
is this the designed behavior? @bybai

**Comment by bybai** [comment]
Hi @immarvin , it is a typo error in hosts.pm in the following line 
```
$hosts[$idx] =~ /^\d+\.\d+\.\d+\.\d+\s+${node}[\s\.r]/)
```

The correct one should be 
```
$hosts[$idx] =~ /^\d+\.\d+\.\d+\.\d+\s+${node}[\s\.\r]/)
```

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2671 by @bybai

**Comment by bybai** [comment]
The test case request is opened in #2674 , so closed this issue.
