### ISSUE TITLE
[dev] /etc/fstab does not take effect in diskless compute node

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2659]
After I modified postinstall in diskless osimage definition, /etc/fstab does not take effect in diskless compute node.
1,  in /opt/xcat/share/xcat/netboot/sles/compute.sles12.x86_64.postinstall:
```
#-- Example how /etc/fstab can be automatically generated during image generation:
cat <<END >$installroot/etc/fstab
proc            /proc    proc   rw 0 0
sysfs           /sys     sysfs  rw 0 0
devpts          /dev/pts devpts rw,gid=5,mode=620 0 0
${profile}_${arch}      /        tmpfs  rw,mode=755,size=3.5G,timeout=20 0 1
none            /tmp     tmpfs  defaults,size=10m 0 2
none            /var/tmp tmpfs  defaults,size=10m 0 2
END

```
2, after CN is booted:
```
bybc0605:~ # cat /etc/fstab
proc            /proc    proc   rw 0 0
sysfs           /sys     sysfs  rw 0 0
devpts          /dev/pts devpts rw,gid=5,mode=620 0 0
compute_x86_64      /        tmpfs  rw,mode=755,size=3.5G,timeout=20 0 1
none            /tmp     tmpfs  defaults,size=10m 0 2
none            /var/tmp tmpfs  defaults,size=10m 0 2

bybc0605:~ # mount |grep rootfs
rootfs on / type tmpfs (rw,relatime,mode=755)
```
3, In redhat, I saw this error:
```
[  OK  ] Started System Logging Service.
[   16.367874] systemd-fstab-generator[1266]: Checking was requested for "compute_x86_64", but it is not a device.

Red Hat Enterprise Linux Server 7.3 (Maipo)
Kernel 3.10.0-513.el7.x86_64 on an x86_64
```

**Comment by bybai** [comment]
This issue is related to #2470

**Comment by daniceexi** [comment]
@bybai could you figure out how the fstab change works in the postinstall script like ./xCAT-server/share/xcat/netboot/rh/compute.rhels7.ppc64.postinstall?

Does it only work for non-rootfs?

**Comment by bybai** [comment]
Hi @daniceexi , I tested in redhat, I found some fstab change can work, but rootfs cannot. For example, I add nfs mount into fstab, it can work. So I want to add comments into   ./xCAT-server/share/xcat/netboot/rh/compute.rhels7.ppc64.postinstall this file to specify this. I will investigate this in sles, after that, I will commit pull request.

**Comment by daniceexi** [comment]
@bybai I do think there was certain reason to remove the -l option. Involve @immarvin in the discussion.

**Comment by bybai** [comment]
There is no any code changes for this issue now, so remove testcase_requested label.

**Comment by immarvin** [comment]
the options should also be specified during initrd bring up,
