### ISSUE TITLE
Support autodiscovery of switches, pdus

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2661]
Node replacement is simple because you can just plug in and power the new node and Genesis will initiate the discovery process.  Replacing a switch or PDU requires you to run the `switchdiscover` or manually update the MAC address in the xCAT tables.  I propose an optional mode where certain devices that show up in the dynamic range automatically get discovered.  ISC DHCP has a feature that lets you run an arbitrary script (see http://jpmens.net/2011/07/06/execute-a-script-when-isc-dhcp-hands-out-a-new-lease/).  You can wrap the execute with conditionals on device type so you run the correct discovery script (for example ONIE switches call switchdiscover).

**Comment by immarvin** [comment]
interesting, if it support the conditional statement on some device-specific filelds in dhcp discover and dhcp request, this might inspire some new type of discovery method for the devices which can be identified by the dhcp requests.  I am interested in doing some invstigation on this

**Comment by zet809** [comment]
Hi, @cxhong , it seems we have implemented autodiscovery of switch, pdu, so can we close this issue? Thx!

**Comment by robin2008** [comment]
Not covered in 2.14, move it to next.

**Comment by immarvin** [comment]
the ztp based autodiscovery has been merged
