### ISSUE TITLE
Support Cumulus ZTP for autoconfiguration

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2662]
After a fresh Cumulus install, it will attempt to run Zero Touch Provisioning ([ZTP](https://docs.cumulusnetworks.com/display/DOCS/Zero+Touch+Provisioning+-+ZTP)).  If given the correct DHCP option, it will download a script and execute it.  We can use this to copy over xCAT keys and possibly do some of the `configonie` steps there as well.  Could also be used as a Genesis-like environment and support running things from the chain table.

**Comment by immarvin** [comment]
hi @mattaezell , thanks for your proposal.
This is an interesting reminder for us, since we can not control finely for the cumulus installer as ordinary linux installers such as anaconda, autoyast.. etc,  we did not have a chance to insert some hooks to perform some user specified postbootscripts on fresh installation, the ZTP might be a hook to perform some interesting configuration and interaction with the management node. 

I will look into this with @cxhong

**Comment by mattaezell** [comment]
Thanks @immarvin.  You could also hook into the ONIE installer by creating a Genesis script that runs instead of the Cumulus installer - I believe it has a busybox shell that you could use to send a discovery packet.  However I believe the switches we are getting for CORAL will have Cumulus preinstalled so we won't be able to take advantage of ONIE-level features (unless we manually reset them to ONIE mode).

**Comment by cxhong** [comment]
For this issue, there are two parts.  
1)  use ZTP autoconfigure the cumulus switch
2) genesis like switch discovery.

as talked to @immarvin , genesis discovery may require  a lot of hook on cumulus switch.  we need to have more time to investigate the ONIE features.  So for the first phase,  we will work on to use ZTP auto configure the cumulus switch.

**Comment by mattaezell** [comment]
Hello @cxhong.  We recently replaced our Cumulus switches, but we had to manually reconfigure them.  I looked into what it would take to get them to autodiscover, but I didn't want to duplicate or conflict with any work you have already done.  What all are you investigating, and how far along are you?  Thanks!

**Comment by cxhong** [comment]
I was working to use ZTP autoconfigure the cumulus switch.  didn't have chance to look into autodiscover yet.  what method did u try to use autodiscover?

**Comment by mattaezell** [comment]
Also through ZTP.  For the ORNL CORAL delivery, our ~300 Edgecore switches will come with Cumulus pre-installed, so we aren't currently investigating ONIE provisioning.  I have a concern that the switches will come with the license file pre-installed, which may prevent ZTP from running on first boot here.  Either way, I made the modification below to xCAT and then created a Cumulus-compatible script that sends the *findme* command to the xCAT server.  With the  `<nodetype>switch</nodetype>` tag present, it will go through auto-discovery.  The next step would be to hook into *getdestiny* to work through items in the chain table, which hopefully dovetails into the work you have been doing.  Or we come up with a way to have the switch request the management node run *configonie*, but we need a way to provide which arguments we want to run against it.

Currently, my script that sends *findme* still has some hard-coded values in it.  I can upload that once I generalize it.  The patch to switch.pm is below:

```
--- ./lib/perl/xCAT_plugin/switch.pm.dist       2017-02-22 22:42:22.000000000 -0500
+++ ./lib/perl/xCAT_plugin/switch.pm    2017-05-03 15:03:39.800282536 -0400
@@ -293,15 +293,19 @@
             #discovery working.  Food for thought.
             return;
         }
+        my $discoverswitch = 0;
+        if (defined $req->{nodetype} and $req->{nodetype}->[0] eq 'switch') {
+            $discoverswitch = 1;
+        }
         my $firstpass = 1;
         if ($mac) {
-            $node = $macmap->find_mac($mac, $req->{cacheonly}->[0]);
+            $node = $macmap->find_mac($mac, $req->{cacheonly}->[0], $discoverswitch);
             $firstpass = 0;
         }
         if (not $node) {    # and $req->{checkallmacs}->[0]) {
             foreach (@{ $req->{mac} }) {
                 /.*\|.*\|([\dABCDEFabcdef:]+)(\||$)/;
-                $node = $macmap->find_mac($1, $firstpass);
+                $node = $macmap->find_mac($1, $firstpass, $discoverswitch);
                 $firstpass = 0;
                 if ($node) { last; }
             }
```

**Comment by immarvin** [comment]
hi @mattaezell , you mentioned "I have a concern that the switches will come with the license file pre-installed, which may prevent ZTP from running on first boot here. " , seems the cumulus user guide does not mention this,  we might need to try and confirm this. 

In https://docs.cumulusnetworks.com/display/DOCS/Zero+Touch+Provisioning+-+ZTP#ZeroTouchProvisioning-ZTP-ZeroTouchProvisioningoverDHCP, it seems there are some conditions which can trigger ZTP process: 

````
Triggering ZTP over DHCP
If provisioning has not already occurred, it is possible to trigger the zero touch provisioning process over DHCP when eth0 is set to use DHCP and one of the following events occur:
Booting the switch
Plugging a cable into or unplugging it from the eth0 port
Disconnecting then reconnecting the switch's power cord
You can also run the ztp --run <URL> command, where the URL is the path to the ZTP script.
````

"...but we need a way to provide which arguments we want to run against it", did you mean the arguments for the configonie script?

**Comment by mattaezell** [comment]
Hi @immarvin.  On that same page you linked, near the bottom, there's a box with the text:

```
Enabling ztp means that ztp will try to occur the next time the switch boots. However, if ZTP already occurred on a previous boot up or if a manual configuration has been found, ZTP will just exit without trying to look for any script.

ZTP checks for these manual configurations during bootup:

    Password changes
    Users and groups changes
    Packages changes
    Interfaces changes
    The presence of an installed license
```

Correct, I was referring to the options to provide to the *configonie* script, if that's what is used along with ZTP.  Customers will want to customize which items they configure, where they stored the license file, etc.

**Comment by zet809** [comment]
The task #3060 and #3176 will cover this requirement.

**Comment by zet809** [comment]
Close this EPIC as all the sub tasks had been finished.
