### ISSUE TITLE
[openbmc] Create framework skeleton for all interactions to the bmc

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2663]
Creating a initial list of commands that potentially interact with the BMC.  

https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/ipmi.pm defines the following `handled_commands` 

```
sub handled_commands {
    return {
        rpower  => 'nodehm:power,mgt',
        renergy => 'nodehm:mgt',         
        getipmicons => 'ipmi',           
        rspconfig   => 'nodehm:mgt',
        rspreset    => 'nodehm:mgt', 
        rvitals     => 'nodehm:mgt',   
        rinv        => 'nodehm:mgt',    
        rflash      => 'nodehm:mgt',   
        rsetboot    => 'nodehm:mgt',
        rbeacon     => 'nodehm:mgt',
        reventlog   => 'nodehm:mgt',
        ripmi       => 'ipmi',
        getrvidparms => 'nodehm:mgt',    
        rscan => 'nodehm:mgt', 
      }
}

```

* rspconfig
* rvitals
* rinv
* rflash
* rpower
* bmcdiscover
* rspreset
* ipmi
* wvid
* winstall
* passwd
* mknb
* rcons 
* rinstall
* nodeset
* pasu
* rbeacon
* reventlog

**Comment by zet809** [comment]
This task had been done with #2688 , so close this task.
