### ISSUE TITLE
[openbmc] rinv support 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2664]
Issue opened to support rinv using openbmc mgmt.

* Inventory is provided by the [openbmc_project/Inventory](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory) endpoint.
* Firmware related information is provided by the [openbmc_project/Software](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software) endpoint 

### OpenPower IPMI
```
   OpenPOWER (using ipmi) server specific:
       rinv noderange [model|serial|deviceid|uuid|guid|vpd|mprom|firm|all]
```

### OpenPower OpenBMC
```
   OpenPOWER (using openbmc) server specific:
       rinv noderange [model|serial|deviceid|firm|cpu|dimm|all]
```

**Comment by zet809** [comment]
Pull Request #2573 include "rinv <node> all".

**Comment by whowutwut** [comment]
@zet809  I will add the issue to the pull request, this way there will be a link appearing on this issue page, instead of the other way around

**Comment by xuweibj** [comment]
For pr #2848 , supported options: cpu, dimm, model, serial, bios, all

Plan to do: memory, firm

**Comment by xuweibj** [comment]
The task was finished in pull request #2848 .

**Comment by whowutwut** [comment]
@gurevichmark I think the development for this function is complete.  If things change from the openbmc code, we should just open issues to track this, or should we keep this epic open for another release?

**Comment by gurevichmark** [comment]
I agree, from what is known now about openbmc, the implementation of `sinv` is finished.
