### ISSUE TITLE
postscript fails and status=booted.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2665]
When we have a postscript that fails,. the overall boot status still shows booted rather than failed.  This makes us blind to failures in the install.

Here is what we did to demonstrate the problem.
Clone an osimage
and then setup
```
cd /install/postscripts/custom
mkdir rh73_post_test
cd rh73_post_test
cat >compute.postscript <<EOF
#/bin/bash
set -x; export PS4='+(`basename ${BASH_SOURCE}`:${LINENO}):'; 
echo "failing postscript"
exit 1
EOF

cat >compute.postbootscript <<EOF
#/bin/bash
set -x; export PS4='+(`basename ${BASH_SOURCE}`:${LINENO}):'; 
exit 0
EOF
chmod +x compute*
```

```
chdef -t osimage rh73_post_test postbootscripts=custom/rh73_post_test/compute.postbootscript
chdef -t osimage rh73_post_test postscripts=custom/rh73_post_test/compute.postscript
```

Final output:
```
[root@c460mgt01 rh73_post_test]# lsdef -t osimage rh73_post_test
Object name: rh73_post_test
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.3-ppc64le
    osname=Linux
    osvers=rhels7.3
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le
    pkgdir=/install/RHEL-7.3-20161019.0-Server/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    postbootscripts=custom/rh73_post_test/compute.postbootscript
    postscripts=custom/rh73_post_test/compute.postscript
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
```

```
nodeset c460c024 osimage=rh73_post_test
xdsh c460c024 reboot

while true; do 
  date; 
  lsdef c460c024 -i status -c; sleep 60; 
done
```

Wait until the node boots.

```
Fri Mar 17 10:46:04 EDT 2017
c460c024: status=powering-off
Fri Mar 17 10:49:05 EDT 2017
c460c024: status=installing
Fri Mar 17 10:56:08 EDT 2017
c460c024: status=booting
Fri Mar 17 11:06:12 EDT 2017
c460c024: status=booted
```
```
scp c460c024:/var/log/xcat/xcat.log /tmp/c460c024.xcat.log
```

```
failing postscript
failing postscript
+++(compute.postscript:4):exit 1
+++(compute.postscript:4):exit 1
postscript: custom/rh73_post_test/compute.postscript exited with code 1
Fri Mar 17 10:55:21 EDT 2017 postscript custom/rh73_post_test/compute.postscript return with 1
Fri Mar 17 10:55:21 EDT 2017 Running postscript: confignics
Fri Mar 17 10:55:21 EDT 2017 Running postscript: confignics
confignics on c460c024: config install nic:0, remove: 0, iba ports: 
confignics on c460c024: config install nic:0, remove: 0, iba ports: 
ib2!10.11.2.6
ib2!10.11.2.6
ib0!10.10.2.6
ib0!10.10.2.6
confignics on c460c024: executed script: configib for nics: ib2,ib0, ports: 
confignics on c460c024: executed script: configib for nics: ib2,ib0, ports: 
postscript: confignics exited with code 1
Fri Mar 17 10:55:32 EDT 2017 postscript confignics return with 1
Fri Mar 17 10:55:32 EDT 2017 Running postscript: setroute
```

[c460c024.xcat.log.zip](https://github.com/xcat2/xcat-core/files/851146/c460c024.xcat.log.zip)

**Comment by gurevichmark** [comment]
I have noticed this behavior myself also.
Perhaps we need another node attribute, `postscriptstatus` ? It could go through states such as `waiting-to-run`, `running`, `failed` and `success`

**Comment by ralphbellofatto** [comment]
That would be one way to handle it.

The method i employed as a work around in my own postscripts and postbootscripts.

The user postscript writes its result to a file, and the postboot script picks up the result to or into its postboot  scripts result.

my postscript looks like this:
```
return_value=0
run_postscripts  XCAT_PS_COMMON $COMMON_PS_DIR || return_value=$?;
run_postscripts  XCAT_PS_LOCAL $LOCAL_PS_DIR || return_value=$?;

mkdir -p /opt/installs
echo $return_value >/opt/installs/xcat.postinstall.result
exit $return_value;
```

and my postboot script looks like this:
```
return_value=0
# pick up the postinstall result and merge it here.
# post install failures are boot failures...
if [ -e /opt/installs/xcat.postinstall.result ]; then
  return_value=$(cat /opt/installs/xcat.postinstall.result);
  echo "postinstall return with $return_value"
fi
#exec 1</dev/console; exec 2>&1
#set -x; export PS4='+(`basename ${BASH_SOURCE}`:${LINENO}):'; 
run_postscripts  XCAT_PS_COMMON $COMMON_PS_DIR || return_value=$?;
run_postscripts  XCAT_PS_LOCAL $LOCAL_PS_DIR || return_value=$?;
exit $return_value;
```

I still miss things if confignics or ospkgs, or otherpkgs, and cat scripts return errors.

but at least this covers my own postscripts.

**Comment by cxhong** [comment]
will try to modify xCAT/postscripts/xcatdsklspost, save return code to /opt/xcat/xcatinfo, then based on return code from /opt/xcat/xcatinfo and postbootscripts

**Comment by daniceexi** [comment]
@immarvin will the **status** be set to ``failed`` only when the postscripts are run through ``updatenode`` command?

**Comment by ralphbellofatto** [comment]
status should be failed either after a fresh provision or an updatenode..


This setup illustrated provision failuire, however it can also illustrate update node failure and the escape too...

**Comment by immarvin** [comment]
hi @ralphbellofatto @daniceexi ,  ``nodelist.status`` only reflect 
(1) the return value of postbootscripts for diskful installation  
(2) the return value of postbootscripts and postscripts for diskless installation

the ``nodelist.updatestatus`` is the attribute to monitor  the result of ``updatenode`` against nodes, 
````
updatestatus:	The current node update status. Valid states are synced,syncing,failed.
updatestatustime:	The date and time when the updatestatus was updated.
````

**Comment by daniceexi** [comment]
@immarvin what's the restriction for diskful to get the status from postscripts?

**Comment by immarvin** [comment]
for diskful provision, the PS and PBS are run in the different phase during provision, the PS is run before 1st reboot during installation, the PBS is run during 1st reboot after installation
Talked with @cxhong , we will try to save the result of PS in the persistent file /opt/xcat/xcatinfo, then determine the final provision status based on the result in  /opt/xcat/xcatinfo and the return value of the PBS

**Comment by daniceexi** [comment]
👍

**Comment by ralphbellofatto** [comment]
If a diskful postscript fails, there should be some indication that the entire install failed, and there isn't..

At the end of a "failed" provisioning, update status shows:

    updatestatus=synced
and
   status=booted

There is nothing here to indicate that we have a failed postscript.

**Comment by immarvin** [comment]
hi @ralphbellofatto , we will enhance the ``novelist.status`` to reflect the return code of postscript

**Comment by gurevichmark** [comment]
So what will `nodelist.status` be when one PS fails but all PBS succeed ?
Will it be `failed` even though the node is booted and is accessible ? Perhaps we need a new state: `booted_ps_failed` ?

**Comment by ralphbellofatto** [comment]
status=failed does not mean the node is not accessable,  It only means one or more of the postbootscripts failed.

A failing postscript will also not necessarily mean that the node is unaccessable, just some aspect of provisioning it failed, such as failing to configure a nic address.

**Comment by hu-weihua** [comment]
@junxiawang , could you help to very this fix, thanks
