### ISSUE TITLE
[DEV] Test cases related rpower need to modify 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2666]
Test cases about ``rpower``, such like ``rpower_off, rpower_stat, rpower_boot, rpower_on, rpower_reset, rpower_noderange, rpower_noderange_nodeps``, are checking some key work of the output of ``rpower`` command. But in different platform, the same intention are expressed by different word. For example, to express the node is working,

       on ppc64le
       # rpower c910f03c17k24 stat
       c910f03c17k24: on

       on ppc64
       # rpower c910f02c04p04 stat
       c910f02c04p04: Running

But in our test case  ``rpower_stat``, we hard code checking  key word ``Running``.
 
      start:rpower_stat
      cmd:rpower $$CN stat
      check:rc==0
      check:output=~Running

So these cases will failed in some platform.

Form xCAT point of view,  it is unnecessary to unify the output. So we have to modify our such test cases to make it more flexible.

**Comment by whowutwut** [comment]
@hu-weihua  Is the code just reporting back what the management utility is reporting back? So  differences in hmc vs bmc vs kvm would report different status?  

Would it make more sense for xCAT to report back the same set of states  regardless of the type of management?  If the machine is "running" or "on", why don't we just report the same state of on? 

Why do we feel the testcase should change?

**Comment by hu-weihua** [comment]
@whowutwut , I had discussed what you cared in one CDL scrum meeting before I opened this issue. Depending on the most people's opinion, first,  It is not very necessary to unify the output. Customer doesn't have problem to understand the meaning of output. Second, we have limited people resource, unifying the output have very low priority. Third, this kind output has been exist long time. If we change the output, customer maybe need to change their interface if they leverage the output of xCAT. 
So we have to change our test case to handle this situation. 
What do you think? Do you think we need to put effort to unify the output. It's not very hard but indeed  need resource.

**Comment by bybai** [comment]
Fixed in #2731

**Comment by hu-weihua** [comment]
hi @bybai , below information maybe helpful for you to refine cases in ppc64

    ------START:rpower_noderange::Time:Sat Mar 25 11:50:34 2017------
    FILENAME:/opt/xcat/share/xcat/tools/autotest/testcase/rpower/cases0

    RUN:rpower c910f02c08p07

    [rpower c910f02c08p07] Running Time:0 sec
    RETURN rc = 1
    OUTPUT:
    No command specified
    Usage: rpower <noderange> [--nodeps] [on|onstandby|off|suspend|reset|stat|state|boot] [-V|--verbose] [-m table.colum==expectedstatus][-m table.colum==expectedstatus...] [-r <retrycount>] [-t <timeout>]
           rpower [-h|--help|-v|--version]
         OpenBMC specific:
           rpower noderange [on|off|reset|boot|stat|state|status]
         KVM Virtualization specific:
           rpower <noderange> [boot] [ -c <path to iso> ]
         PPC (with IVM or HMC) specific:
           rpower <noderange> [--nodeps] [of] [-V|--verbose]
         CEC (with HMC) specific:
           rpower <noderange> [on|off|reset|boot|onstandby]
         LPAR(with HMC) specific:
           rpower <noderange> [on|off|reset|stat|state|boot|of|sms|softoff]
         CEC(using Direct FSP Management) specific:
           rpower <noderange> [on|onstandby|off|stat|state|resetsp]
         Frame(using Direct FSP Management) specific:
           rpower <noderange> [stat|state|rackstandby|exit_rackstandby|resetsp]
         LPAR(using Direct FSP Management) specific:
           rpower <noderange> [on|off|reset|stat|state|boot|of|sms]
         Blade(using Direct FSP Management) specific:
           rpower <noderange> [on|onstandby|off|cycle|state|sms]
         Blade(using AMM) specific:
           rpower <noderange> [cycle|softoff] [-V|--verbose]
        Lenovo high-density server specific:
           rpower <noderange> [on|off|reset|boot|reseat]
         zVM specific:
           rpower noderange [on|off|reset|stat|softoff]
         MIC specific:
           rpower noderange [stat|state|on|off|reset|boot]
         docker specific:
           rpower noderange [start|stop|restart|pause|unpause|state]
         pdu specific:
           rpower noderange [off|on|stat]
           rpower noderange [pduoff|pduon|pdustat]

    CHECK:rc != 0	[Pass]
    CHECK:output =~ Unsupported	[Failed]
    ------END::rpower_noderange::Failed::Time:Sat Mar 25 11:50:34 2017 ::Duration::0 sec------
    ------START:rpower_noderange_nodeps::Time:Sat Mar 25 11:50:34 2017------
    FILENAME:/opt/xcat/share/xcat/tools/autotest/testcase/rpower/cases0

    RUN:rpower c910f02c08p07 --nodeps

    [rpower c910f02c08p07 --nodeps] Running Time:0 sec
    RETURN rc = 1
    OUTPUT:
    Invalid command:
    Usage: rpower <noderange> [--nodeps] [on|onstandby|off|suspend|reset|stat|state|boot] [-V|--verbose] [-m table.colum==expectedstatus][-m table.colum==expectedstatus...] [-r <retrycount>] [-t <timeout>]
           rpower [-h|--help|-v|--version]
         OpenBMC specific:
           rpower noderange [on|off|reset|boot|stat|state|status]
         KVM Virtualization specific:
           rpower <noderange> [boot] [ -c <path to iso> ]
         PPC (with IVM or HMC) specific:
           rpower <noderange> [--nodeps] [of] [-V|--verbose]
         CEC (with HMC) specific:
           rpower <noderange> [on|off|reset|boot|onstandby]
         LPAR(with HMC) specific:
           rpower <noderange> [on|off|reset|stat|state|boot|of|sms|softoff]
         CEC(using Direct FSP Management) specific:
           rpower <noderange> [on|onstandby|off|stat|state|resetsp]
         Frame(using Direct FSP Management) specific:
           rpower <noderange> [stat|state|rackstandby|exit_rackstandby|resetsp]
         LPAR(using Direct FSP Management) specific:
           rpower <noderange> [on|off|reset|stat|state|boot|of|sms]
         Blade(using Direct FSP Management) specific:
           rpower <noderange> [on|onstandby|off|cycle|state|sms]
         Blade(using AMM) specific:
           rpower <noderange> [cycle|softoff] [-V|--verbose]
        Lenovo high-density server specific:
           rpower <noderange> [on|off|reset|boot|reseat]
         zVM specific:
           rpower noderange [on|off|reset|stat|softoff]
         MIC specific:
           rpower noderange [stat|state|on|off|reset|boot]
         docker specific:
           rpower noderange [start|stop|restart|pause|unpause|state]
         pdu specific:
           rpower noderange [off|on|stat]
           rpower noderange [pduoff|pduon|pdustat]

    CHECK:rc != 0	[Pass]
    CHECK:output =~ Unsupported	[Failed]
    ------END::rpower_noderange_nodeps::Failed::Time:Sat Mar 25 11:50:34 2017 ::Duration::0 sec------

**Comment by bybai** [comment]
Enhancement in : #2750
