### ISSUE TITLE
[DEV] Install xcat on ubuntu14.4.4+ppc64le by go-xcat show  "Restarting xcatd ERROR:". That is why Diskless_installation_flat_p8_le always fail and stay on ''powering_on``

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2668]
In ubuntu14.4.4+ppc64le, install xcat by go-xcat show below error message:

    .....
    Created xCAT certificate.
    Created xCAT certificate.
    Restarting xcatd ERROR: Can not execute command /usr/sbin/in.tftpd  -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf.
     .....

Also find the same error message in ``cluster.log``

     Mar 18 16:46:12 c910f03c17k22 xcat:  Install: syslog setup
     Mar 18 16:46:18 c910f03c17k22 xcat[21109]:  ERROR: Can not execute command /usr/sbin/in.tftpd  -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf.
     Mar 18 16:46:18 c910f03c17k22 xcat[21159]:  INFO xcatd: command log process 21159 start
     Mar 18 16:46:21 c910f03c17k22 xcat[21376]:  xCAT: Allowing mknb ppc64 for root from localhost
      .....

So it seems we have problem of tftp service, so when doing provision bases on this kind  of xcat MN,  after reboot CN,  CN will failed at downloading through tftp and stay on "powering-on" state.

    RUN:rinstall c910f03c17k24 osimage=ubuntu14.04.4-ppc64el-netboot-compute

    [rinstall c910f03c17k24 osimage=ubuntu14.04.4-ppc64el-netboot-compute] Running Time:4 sec
    RETURN rc = 0
    OUTPUT:
    Provision node(s): c910f03c17k24
    CHECK:rc == 0   [Pass]
    CHECK:output =~ Provision node\(s\)\: c910f03c17k24     [Pass]

    RUN:sleep 200

    [sleep 200] Running Time:200 sec
    RETURN rc = 0
    OUTPUT:

    RUN:a=0;while ! `lsdef -l c910f03c17k24|grep status|grep booted >/dev/null`; do sleep 10;((a++));if [ $a -gt 100 ];then break;fi done

    [a=0;while ! `lsdef -l c910f03c17k24|grep status|grep booted >/dev/null`; do sleep 10;((a++));if [ $a -gt 100 ];then break;fi done] Running Time:1060 sec
    RETURN rc = 0
    OUTPUT:

    RUN:lsdef -l c910f03c17k24 | grep status

    [lsdef -l c910f03c17k24 | grep status] Running Time:1 sec
    RETURN rc = 0
    OUTPUT:
        status=powering-on
        statustime=03-18-2017 16:57:32
    CHECK:output =~ booted  [Failed]

We can find information in ``cluster.log`` and ``message`` as below
In ``cluster.log``, test case trigger ``rinstall CN ...`` twice between ``Mar 18 16:57:29`` and ``Mar 18 17:18:35`` by different method

    Mar 18 16:57:29 c910f03c17k22 xcat[31888]:  xCAT: Allowing rinstall to c910f03c17k24 osimage=ubuntu14.04.4-ppc64el-netboot-compute for root from localhost
    Mar 18 16:57:32 c910f03c17k22 xcat:  c910f03c17k24 status: powering-on statustime: 03-18-2017 16:57:32
    Mar 18 17:00:52 c910f03c17k22 xcat[31953]:  xCAT: Allowing lsdef -l c910f03c17k24 for root from localhost
     .......
    Mar 18 17:18:33 c910f03c17k22 xcat[605]:  xCAT: Allowing lsdef -l c910f03c17k24 for root from localhost
    Mar 18 17:18:33 c910f03c17k22 xcat[613]:  xCAT: Allowing xdsh to c910f03c17k24 date for root from localhost
    Mar 18 17:18:34 c910f03c17k22 xcat[635]:  xCAT: Allowing xdsh to c910f03c17k24 cat /var/log/xcat/xcat.log for root from localhost
    Mar 18 17:18:35 c910f03c17k22 xcat[657]:  xCAT: Allowing rinstall to c910f03c17k24 osimage for root from localhost
    Mar 18 17:18:38 c910f03c17k22 xcat:  c910f03c17k24 status: powering-on statustime: 03-18-2017 17:18:38

But in ``message``, during this period, except dhcp message, can't find any tftp message. 

    Mar 18 16:57:30 c910f03c17k22 dhcpd: DHCPDISCOVER from 4a:c8:f3:d0:71:03 via eth1: network eth1: no free leases
    .......
    Mar 18 16:57:37 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:9f:0a:03:11:18 via eth1
    Mar 18 16:57:37 c910f03c17k22 dhcpd: DHCPOFFER on 10.3.17.24 to 42:9f:0a:03:11:18 via eth1
    Mar 18 16:57:37 c910f03c17k22 dhcpd: DHCPREQUEST for 10.3.17.24 (10.3.17.22) from 42:9f:0a:03:11:18 via eth1
    Mar 18 16:57:37 c910f03c17k22 dhcpd: DHCPACK on 10.3.17.24 to 42:9f:0a:03:11:18 via eth1
    .......
    Mar 18 17:18:31 c910f03c17k22 dhcpd: DHCPDISCOVER from 4a:c8:f3:d0:71:03 via eth1: network eth1: no free leases
    Mar 18 17:18:32 c910f03c17k22 dhcpd: DHCPDISCOVER from da:08:40:7f:17:03 via eth1: network eth1: no free leases
    Mar 18 17:18:32 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:88:0a:04:0e:29 via eth1: network eth1: no free leases
    Mar 18 17:18:35 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:11:77:5c:cd:30 via eth1: network eth1: no free leases
    Mar 18 17:18:38 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:88:0a:04:0e:29 via eth1: network eth1: no free leases
    Mar 18 17:18:38 c910f03c17k22 dhcpd: DHCPDISCOVER from da:08:47:20:93:03 via eth1: network eth1: no free leases
    Mar 18 17:18:43 c910f03c17k22 dhcpd: DHCPDISCOVER from 4a:c8:f3:d0:71:03 via eth1: network eth1: no free leases
    Mar 18 17:18:43 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:9f:0a:03:11:18 via eth1
    Mar 18 17:18:43 c910f03c17k22 dhcpd: DHCPOFFER on 10.3.17.24 to 42:9f:0a:03:11:18 via eth1
    Mar 18 17:18:43 c910f03c17k22 dhcpd: DHCPREQUEST for 10.3.17.24 (10.3.17.22) from 42:9f:0a:03:11:18 via eth1
    Mar 18 17:18:43 c910f03c17k22 dhcpd: DHCPACK on 10.3.17.24 to 42:9f:0a:03:11:18 via eth1
    Mar 18 17:18:45 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:1c:0a:03:11:09 via eth1: network eth1: no free leases

This brings out 2 problems
*  If start xcat some service failed, whether should treat it as xcat installation successful.  (for go-xcat).
*  If there is already error message in the output of ``go-xcat``, test case ``install_xCAT_on_ubuntu`` still treat it as successful, as long as the return code of ``go-xcat`` is ``0``.

**Comment by hu-weihua** [comment]
I think it is still not the root cause. need to find out why failed to start tftp service in ``go-xcat``.

**Comment by whowutwut** [comment]
Does this happen if we manually install xcat without go-xcat? Go xcat is just a tool to call the installer....maybe something happened in the install scripts for Debian?

**Comment by neo954** [comment]
The `in.tftpd` launched by `xcatd` was failed running. That is due to another `in.tftpd` was already run.

    # ps ax | grep -v grep | grep in.tftpd
    26995 ?        Ss     0:00 /usr/sbin/in.tftpd --listen --user tftp --address [::]:69 --secure /var/lib/tftpboot
    # netstat -nlup | grep tftp
    udp6       0      0 :::69                   :::*                                26995/in.tftpd

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2672

**Comment by neo954** [comment]
Thanks @immarvin. The patch was merged already.

**Comment by hu-weihua** [comment]
@immarvin and @neo954 , depending on the test result on Mar 21, your fix looks like working. I will keep my eyes on it for next few days. If every thing is fine, I will close this issue. thanks.
