### ISSUE TITLE
[xCAT performance]investigate makedhcp scaliability

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2676]
Acceptance: the solution of how to improve the makedhcp performance.

some proposal:
1.  generate the bulk of dhcp leases and write into dhcp lease db once
2. look into the code logic in dhcp.pm,  improve the code logic and eliminate the db access
3. obtain a data on the improved performance compared with the current ``makedhcp`` performance

**Comment by immarvin** [comment]
https://github.com/xcat2/xcat-core/pull/2734

**Comment by zet809** [comment]
The pull request #2734 include the code for this item.

**Comment by immarvin** [comment]
perf data of ``makedhcp <node>``:
http://10.2.8.15/install/perlf/nytprof/opt-xcat-lib-perl-xCAT_plugin-dhcp-pm-140-line.html#1057
````
 perl -d:NYTProf /opt/xcat/sbin/makedhcp node0001
 nytprofhtml  ./nytprof.out
````

draft code for for task https://github.com/xcat2/xcat-core/pull/2676

improve performance of ``makedhcp``
1. refine the code logic of ``getSNList``
2. refine the code logic of ``getipaddr``, ``getipaddr``

some compare between the optimized code and origin code:

1. with xCAT-2.13.2-snap201702222242:
against 100 nodes:
````
c910f02c08p15:/ # time makedhcp node0001-node0100

real	0m13.013s
user	0m0.124s
sys	0m0.017s
````


against 5000 nodes:
````
c910f02c08p15:/ # time makedhcp node0001-node5000

real	3m49.514s
user	0m0.165s
sys	0m0.020s
````

2. with the optimized code:
against 100 nodes:
````
c910f02c08p15:/ # time makedhcp node0001-node0100

real	0m6.587s
user	0m0.124s
sys	0m0.017s
````
against 5000 nodes:
````
c910f02c08p15:/opt # time makedhcp node0001-node5000

real	3m39.259s
user	0m0.168s
sys	0m0.021s
````

**Comment by immarvin** [comment]
created a new branch "xcat-core/perfopt" to include all the PRs on performance optimization

**Comment by immarvin** [comment]
The perf data of incremental node numbers: http://10.3.5.27/install/perf/

**Comment by immarvin** [comment]
refined getipaddr subroutine to cache the dns name lookup result 
the perf data:
http://10.3.5.27/install/perf/manual/nytprof/opt-xcat-lib-perl-xCAT_plugin-dhcp-pm-133-line.html

**Comment by immarvin** [comment]
the pull request is https://github.com/xcat2/xcat-core/pull/2901

**Comment by immarvin** [comment]
a comparison between original code and optimized code:

optimized code:
````
[root@c910f03c05k27 rpms]# time makedhcp  node000001-node010000

real	3m21.301s
user	0m0.208s
sys	0m0.017s

[root@c910f03c05k27 rpms]# time makedhcp  node000001-node005000

real	1m41.058s
user	0m0.154s
sys	0m0.029s

````

old code:
````
[root@c910f03c05k27 rpms]# time makedhcp  node000001-node010000

real	7m57.570s
user	0m0.224s
sys	0m0.016s

[root@c910f03c05k27 rpms]# time makedhcp  node000001-node005000

real	3m13.754s
user	0m0.203s
sys	0m0.004s
````
