### ISSUE TITLE
[FVT]2.11: Please add manpage/docs for diskdiscover and configraid

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#268]
With Latest xCAT 2.11 , I didn't find the man page of diskdiscover and configraid.

[root@c910f03c05k23 ppc64le]# lsxcatd -v
Version 2.11 (git commit 2295560c5048801e80477a18e5267bcdb06a0814, built Thu Oct 15 19:30:47 EDT 2015)

[root@c910f03c05k23 ppc64le]# man diskdiscover
No manual entry for diskdiscover
[root@c910f03c05k23 ppc64le]# man configraid
No manual entry for configraid

**Comment by bybai** [comment]
@tingtli since diskdiscover and configraid are both scripts, we usually do not add man page for them.  You can use '-h|--help' to get usage;

**Comment by bybai** [comment]
Based on morning comments, ``Hardware RAID`` doc should be updated the following part:
1. delete ``mknb <arch>`` from diskdiscover example, add ``note`` for ``mknb <arch>`` in this part bottom. 
2. change 2 diskdiscover examples order;
3. add outputs format for diskdiscover command;
4. add "Supported RAID level is depend on pysical server’s RAID adapter." for raidlevel.
5. add ``rcons`` in monitoring part.
6. update 1. 2. into #.

**Comment by bybai** [comment]
git commit number a842091

**Comment by tingtli** [comment]
Review and close
