### ISSUE TITLE
Test cases and verification for xcatd systemd supporting

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#2680]
xcatd will leverage systemd unit file to control service action, like start, stop/status, on those distro systemd is enabled by default.

It is required to cover below cases:
1, xCAT installation on distro w or w/o systemd: when using SysV init,  /etc/init.d/service will be installed. And systemd unit file will be used when systemd is enabled.

2,Need to cover the uninstallation or upgrade case also. 
Note:  Special upgrade case is required:  upgrade xCAT without systemd supporting to with systemd supporting on a distro which systemd is enabled. (/etc/init.d/xcatd is required to be replaced with systemd unit file)
 
3, xcatd daemon control actions on distro w or w/o systemd. Note:  'service' will keep compatible on distro which systemd is enabled. But it is better to add/modify case to use systemctl in such distro.

**Comment by whowutwut** [comment]
@robin2008  I'm going to take off the milestone, please set an appropriate one when you are looking at this again.

**Comment by robin2008** [comment]
It is planned in 2.14 now, we will revisit it at that time.

**Comment by robin2008** [comment]
we can close it with https://github.com/xcat2/xcat-core/pull/5394
