### ISSUE TITLE
[xCAT performance] Create a way to test the scaliability of xCAT commands 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2681]
Create a utility that will be able to run scalability testing on various xCAT commands and record the timing so that we can execute this script on various branches of code and compare whether the changes we made for performance actually make a difference, positively or negatively.

**Comment by robin2008** [comment]
Plan to add some performance cases for common commands in xCAT-test,  in that we can easily to get the baseline data for new release.

This task is not focusing on network performance in large cluster, but focus on the key command response in a large cluster first. For example, we will get the response time base line for 100, 500, 1000, 5000 nodes.

Note: not consider HW ctrl in first stage.

**Comment by robin2008** [comment]
Finish the script to get the base line according to the cmd list file and total fake node number. (commit in internal github )

Prepare the usage for how to run the tool and get the base line data.

**Comment by robin2008** [comment]
The script "xcatperftest" will be packaged in xCAT-test package, and it could be used standalone or in autotest cases.

Usage:
[PERF_DRYRUN=y] [PERF_NOCREATE=y] xcatperftest <total> [command-list-file]

_command-list-file example as below:_
**#SERIES#** 1,50,100,250,500,1000,2500,5000
mkdef -z -f < #STANZ#
lsdef #NODES#
makehosts #NODES#
makedns -n #NODES#
makedhcp #NODES#
makeknownhosts #NODES#
nodech #NODES# groups,=group1
nodels #NODES# noderes
nodeset #NODES# osimage=rhels7.3-GA-ppc64le-install-compute
chdef -t node -o #NODES# postscripts="fake" profile="install" netboot="grub2"
nodeset #NODES# osimage=rhels7.3-GA-ppc64le-install-compute
rmdef -t node all
mkdef -z < #STANZ#
noderm all

During the xcatperftest running,  #STANZ# will be replaced with the fake nodes stanz file generated by this tool.  And #NODES# will be replaced with each node range defined in #SERIES#, for example,
fake[1-1],  fake[1-50], fake[1-100], ...  which means this command will be tested multiple times with different node range.

After all commands listed in file is executed, the tool will generate the report in /tmp/xcat-performance/report-<total>.<PID>.  And the output as below, each line contains: total, cmd, node-range, time, result, full-command


5000, mkdef, 5000, 76, SUCESS, "mkdef -z -f < /tmp/xcat-performance/stanz-5000.122808"
5000, lsdef, 1, 1, SUCESS, "lsdef fake[1-1]"
5000, lsdef, 50, 3, SUCESS, "lsdef fake[1-50]"
5000, lsdef, 100, 3, SUCESS, "lsdef fake[1-100]"
5000, lsdef, 250, 6, SUCESS, "lsdef fake[1-250]"
5000, lsdef, 500, 12, SUCESS, "lsdef fake[1-500]"
5000, lsdef, 1000, 23, SUCESS, "lsdef fake[1-1000]"
5000, lsdef, 2500, 55, SUCESS, "lsdef fake[1-2500]"
5000, lsdef, 5000, 106, SUCESS, "lsdef fake[1-5000]"
5000, makehosts, 1, 0, SUCESS, "makehosts fake[1-1]"
5000, makehosts, 50, 1, SUCESS, "makehosts fake[1-50]"
5000, makehosts, 100, 2, SUCESS, "makehosts fake[1-100]"
5000, makehosts, 250, 4, SUCESS, "makehosts fake[1-250]"
5000, makehosts, 500, 8, SUCESS, "makehosts fake[1-500]"
5000, makehosts, 1000, 16, SUCESS, "makehosts fake[1-1000]"
5000, makehosts, 2500, 36, SUCESS, "makehosts fake[1-2500]"
5000, makehosts, 5000, 68, SUCESS, "makehosts fake[1-5000]"
5000, makedns, 1, 4, SUCESS, "makedns -n fake[1-1]"
5000, makedns, 50, 4, SUCESS, "makedns -n fake[1-50]"
5000, makedns, 100, 5, SUCESS, "makedns -n fake[1-100]"
5000, makedns, 250, 7, SUCESS, "makedns -n fake[1-250]"
5000, makedns, 500, 9, SUCESS, "makedns -n fake[1-500]"
5000, makedns, 1000, 16, SUCESS, "makedns -n fake[1-1000]"
5000, makedns, 2500, 36, SUCESS, "makedns -n fake[1-2500]"
5000, makedns, 5000, 75, SUCESS, "makedns -n fake[1-5000]"
5000, makedhcp, 1, 1, SUCESS, "makedhcp fake[1-1]"
5000, makedhcp, 50, 4, SUCESS, "makedhcp fake[1-50]"
5000, makedhcp, 100, 5, SUCESS, "makedhcp fake[1-100]"
5000, makedhcp, 250, 14, SUCESS, "makedhcp fake[1-250]"
5000, makedhcp, 500, 28, SUCESS, "makedhcp fake[1-500]"
5000, makedhcp, 1000, 55, SUCESS, "makedhcp fake[1-1000]"
5000, makedhcp, 2500, 135, SUCESS, "makedhcp fake[1-2500]"
5000, makedhcp, 5000, 268, SUCESS, "makedhcp fake[1-5000]"
5000, makeknownhosts, 1, 1, SUCESS, "makeknownhosts fake[1-1]"
5000, makeknownhosts, 50, 0, SUCESS, "makeknownhosts fake[1-50]"
5000, makeknownhosts, 100, 1, SUCESS, "makeknownhosts fake[1-100]"
5000, makeknownhosts, 250, 3, SUCESS, "makeknownhosts fake[1-250]"
5000, makeknownhosts, 500, 4, SUCESS, "makeknownhosts fake[1-500]"
5000, makeknownhosts, 1000, 9, SUCESS, "makeknownhosts fake[1-1000]"
5000, makeknownhosts, 2500, 28, SUCESS, "makeknownhosts fake[1-2500]"
5000, makeknownhosts, 5000, 73, SUCESS, "makeknownhosts fake[1-5000]"
5000, nodech, 1, 0, SUCESS, "nodech fake[1-1] groups,=group1"
5000, nodech, 50, 1, SUCESS, "nodech fake[1-50] groups,=group1"
5000, nodech, 100, 1, SUCESS, "nodech fake[1-100] groups,=group1"
5000, nodech, 250, 1, SUCESS, "nodech fake[1-250] groups,=group1"
5000, nodech, 500, 1, SUCESS, "nodech fake[1-500] groups,=group1"
5000, nodech, 1000, 2, SUCESS, "nodech fake[1-1000] groups,=group1"
5000, nodech, 2500, 4, SUCESS, "nodech fake[1-2500] groups,=group1"
5000, nodech, 5000, 6, SUCESS, "nodech fake[1-5000] groups,=group1"
5000, nodels, 1, 1, SUCESS, "nodels fake[1-1] noderes"
5000, nodels, 50, 1, SUCESS, "nodels fake[1-50] noderes"
5000, nodels, 100, 2, SUCESS, "nodels fake[1-100] noderes"
5000, nodels, 250, 2, SUCESS, "nodels fake[1-250] noderes"
5000, nodels, 500, 5, SUCESS, "nodels fake[1-500] noderes"
5000, nodels, 1000, 9, SUCESS, "nodels fake[1-1000] noderes"
5000, nodels, 2500, 22, SUCESS, "nodels fake[1-2500] noderes"
5000, nodels, 5000, 40, SUCESS, "nodels fake[1-5000] noderes"
5000, nodeset, 1, 3, SUCESS, "nodeset fake[1-1] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 50, 10, SUCESS, "nodeset fake[1-50] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 100, 17, SUCESS, "nodeset fake[1-100] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 250, 42, SUCESS, "nodeset fake[1-250] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 500, 97, SUCESS, "nodeset fake[1-500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 1000, 212, SUCESS, "nodeset fake[1-1000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 2500, 781, SUCESS, "nodeset fake[1-2500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 5000, 2202, SUCESS, "nodeset fake[1-5000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, chdef, 1, 0, SUCESS, "chdef -t node -o fake[1-1] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 50, 2, SUCESS, "chdef -t node -o fake[1-50] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 100, 2, SUCESS, "chdef -t node -o fake[1-100] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 250, 2, SUCESS, "chdef -t node -o fake[1-250] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 500, 4, SUCESS, "chdef -t node -o fake[1-500] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 1000, 6, SUCESS, "chdef -t node -o fake[1-1000] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 2500, 14, SUCESS, "chdef -t node -o fake[1-2500] postscripts="fake" profile="install" netboot="grub2""
5000, chdef, 5000, 25, SUCESS, "chdef -t node -o fake[1-5000] postscripts="fake" profile="install" netboot="grub2""
5000, nodeset, 1, 2, SUCESS, "nodeset fake[1-1] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 50, 10, SUCESS, "nodeset fake[1-50] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 100, 17, SUCESS, "nodeset fake[1-100] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 250, 45, SUCESS, "nodeset fake[1-250] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 500, 92, SUCESS, "nodeset fake[1-500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 1000, 211, SUCESS, "nodeset fake[1-1000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 2500, 759, SUCESS, "nodeset fake[1-2500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, nodeset, 5000, 2286, SUCESS, "nodeset fake[1-5000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000, rmdef, N/A, 39, SUCESS, "rmdef -t node all"
5000, mkdef, 5000, 74, SUCESS, "mkdef -z < /tmp/xcat-performance/stanz-5000.122808"
5000, noderm, N/A, 122, SUCESS, "noderm all"

**Comment by robin2008** [comment]
PR #2916 is submitted for this issue.

**Comment by whowutwut** [comment]
@robin2008 If you wrap code in ``` it will help the read-ability of the comments.
