### ISSUE TITLE
[Test Case] support encrypted passwords in the passwd

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#2686]
Two scenario:
1. encrypted password in passwd table,  password should be changed in the template file generated by nodeset
2. unencrypted password in passwd table, password should be encrypted based on the crtyptmethod in the passwd table.

**Comment by hu-weihua** [comment]
@chenglch , we plan to verify it in 2.13.3 sprint 2 then add case in next sprint

**Comment by zet809** [comment]
HI, @chenglch and @tingtli , there is no information about which Pull request fixed this issue, will you pls reference this issue with in the Pull request that adding the corresponding test cases? Thx a lot!

**Comment by chenglch** [comment]
Testcase is added by PR  #2855
