### ISSUE TITLE
[FVT]2.11:delete raild failed with " wait_for_ipr_device_status: command not found"

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#269]
xCAT 2.11 20151013 build.
[root@c910f03c05k23 ~]# xdsh p8euh diskdiscover
p8euh: --------------------------------------------------------------------------
p8euh: PCI_ID     PCI_SLOT_NAME  Resource_Path  Device  Description   Status
p8euh: ------     -------------  -------------  ------  -----------   ----------------
p8euh: 1014:034a  0001:08:00.0   0:0:0:0        sg0     10 Array Member Active
p8euh: 1014:034a  0001:08:00.0   0:0:1:0        sg1     10 Array Member Active
p8euh: -------------------------------------------------------------------
p8euh: Get ipr RAID arrays by PCI_SLOT_NAME: 0001:08:00.0
p8euh: -------------------------------------------------------------------
p8euh: Name   PCI/SCSI Location         Description               Status
p8euh: ------ ------------------------- ------------------------- -----------------
p8euh: sda    0001:08:00.0/0:2:0:0       RAID 10 Disk Array        1% Rebuilt
[root@c910f03c05k23 ~]# xdsh p8euh "configraid delete_raid=sda"
p8euh: [I]: Renew available target arrays which will be deleting, "0 0:2:0:0"
p8euh: [I]: Round 1: Deletable array >>
p8euh: [I]: Round 1: ipr info before delete >> Name PCI/SCSI Location Description Status
p8euh: [I]: Round 1: ipr info before delete >> ------ ------------------------- ------------------------- -----------------
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: ipr info before delete >> sda 0001:08:00.0/0:2:0:0 RAID 10 Disk Array 2% Rebuilt
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:0:0 RAID 10 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:1:0 RAID 10 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> 0003:04:00.0/1: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: delete_ipr_array, "0 0:2:0:0"
p8euh: [W]: Round 1: Array 0 is un-deletable at present.
p8euh: [W]: Round 1: Array 0:2:0:0 is un-deletable at present.
p8euh: [I]: Round 1: All remaining target arrayes are un-deletable now.
p8euh: [I]: Round 1: Wait for these un-deletable arrayes deletable with tryCnt=360, tryInt=60.
p8euh: /usr/bin/raidutils: line 1240: wait_for_ipr_device_status: command not found
p8euh: [I]: Can not create RAID. There is no create_raid.

**Comment by tingtli** [comment]
The status is "Rebuild"  not "Optimized"

**Comment by bybai** [comment]
@tingtli updated fix in your MN.

**Comment by bybai** [comment]
upload fix in git 2821a1c

**Comment by tingtli** [comment]
Verified with close
