### ISSUE TITLE
[Test case] refine test cases to check hostname in sles12.2 statelite

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2690]
add test case to check hostname in sles12.2 statelite #2616

**Comment by junxiawang** [comment]
Testcases need to refine:
reg_linux_statelite_installation_flat
reg_linux_statelite_installation_hierarchy_by_nfs
reg_linux_statelite_installation_hierarchy_by_ramdisk

**Comment by bybai** [comment]
Hi @junxiawang , yes, these 3 testcases should be enhanced, that is enough. Thanks.
