### ISSUE TITLE
[openbmc] Update document to use openbmc

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2692]

**Comment by whowutwut** [comment]
@zet809 What is your idea to update the documentation?  Really the externals that change is 
```
mgt=openbmc
cons=opnbmc
```

xCAT in general should NOT change much from the users point of view, is that correct?  From what we think we know today...

**Comment by zet809** [comment]
Yes, you are right. My point is, how do the user know how do define a node object and manage it through our openbmc interface?

**Comment by xuweibj** [comment]
The task was finished in pull request #2882 .
