### ISSUE TITLE
rflash fails to update some nodes due to timeout.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2693]
we have two nodes out of our 150+ node cluster that that rflash failed to update:

```
c460c138: rflash started, please wait.......
c460c138: Error: Timeout to check the bmc status
c460c138: Error: failed to update firmware

c460c142: rflash started, please wait.......
c460c142: Error: Timeout to check the bmc status
c460c142: Error: failed to update firmware
```

This appears to be due to the timeout value (which appears to be 24 5 second intervals (or 2 minutes) is too small for some nodes.

we ran a sweep of the time it takes to get the ready signal after doing an mc reset with the following code:

[bmc-reset-ready.zip](https://github.com/xcat2/xcat-core/files/856982/bmc-reset-ready.zip)

Inside this zip file is the sweep.sh program that we used to sweep the reset times, the log of its output AND a csv file of that output and an excel spreadsheet file and graph.

![image](https://cloud.githubusercontent.com/assets/4139514/24130127/337abbba-0dbd-11e7-9d1a-ce5611b78b68.png)

this data shows that there a few nodes clustered that take about 90 seconds, most take around 112-120, AND there are a couple outsiders at > 200 seconds.

This is showing that a 120 second wait time is marginal, but there is probably something off on the outliers that are preventing it from coming back ready in time.

The wait time should probably be increased to 4 or 5 minutes (48 or 60 iterations of the loop) to cover the variation we are currently seeing in the nodes that we have to date.

The code requiring change can be found here:

/opt/xcat/lib/perl/xCAT_plugin/ipmi.pm

specifically: 
```
    # check reset status
    unless (check_bmc_status_with_ipmitool($pre_cmd, 5, 24)) {
        xCAT::SvrUtils::sendmsg([ 1, "Timeout to check the bmc status" ],
            $callback, $sessdata->{node}, %allerrornodes);
        exit -1;
    }
```

Change 24 to 60 would cover the variance we are seeing with a margin for it to be about 20% worse in future units.

**Comment by ralphbellofatto** [comment]
note: this is for the garision compute nodes.

**Comment by whowutwut** [comment]
Hi @chenglch, @ralphbellofatto also indicated that after a firmware flash was unsuccessful, he tried to run another rflash and hit the problem with messages similar to:`` Error: Unknown FRU header version 0x00 ``  This doesn't help the user.  

In the flash code, we should also print a message that helps direct the user in the right direction.. with these boxes, after a firmware update, it needs to be powered on to get some more info...   I think we agreed in PR #2073 that we will not automatically power on the box after the flash.  but we can suggest with a better message about potentially how to fix this issue.   rpower on the machine as a suggestion in addition to the unknown fru header. 

Should do this for the calls to print fru info in the flash path in ipmi.pm.

**Comment by zet809** [comment]
Hi, @whowutwut , just as @ralphbellofatto suggest, we had increased the waiting time to 5 minutes which can cover all the scenario he encountered.
And within the pull request #2725, the "chassis power on" command is triggered in the end.

**Comment by whowutwut** [comment]
@gurevichmark  Can you help validate this Issue and close out on Monday?

**Comment by gurevichmark** [comment]
Ran multiple tests today. Was not able to recreate this issue.

**Comment by zet809** [comment]
Thx, @gurevichmark
