### ISSUE TITLE
Investigation for ingest openbmc console log to BDS

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2697]
Acceptance: make the requirement clear

**Comment by robin2008** [comment]
The initial investigation is done, and slides are uploaded to Box.
 - Log Analysis architecture learning (Knowledge Center)
 - Try load console logs with Logstash
 - Draft the slides and ask John to review and clarify the requirements.

**Comment by robin2008** [comment]
The final decision  is to use filebeat to forward the logs to Logstash (which is running on a remote server)

**Comment by robin2008** [comment]
investigation slide: https://ibm.box.com/s/2kjqu9gpgkrygk4axjdur0jxj5hqwaje
