### ISSUE TITLE
What is the xCAT homepage?

### ISSUE THREAD

**Issue by loz-hurst** [xcat2/xcat-core#270]
https://github.com/xcat2 says that xCAT moved from sourceforge to github on 30 Jul 2015.  http://xcat.sf.net/ has no mention of this and all references I can find to xCAT refer to the SF page as xCAT's home page.  Wikipedia also lists the SF page as the official xCAT homepage.

The situation as to where the source and bug tracking live for the official xCAT project needs to be clearly stated on both github and SF.

Thanks

Laurence

**Comment by whowutwut** [comment]
@loz-hurst  Thanks for bringing this up.   (Bringing @daniceexi  into this topic too FYI)
This kind of feedback is exactly what we need to help tie up some loose ends.  

You are right that we should update something on SourceForge's page to help the users find the pieces they are looking for.  We haven't done that yet as we're trying to get the other pieces ready before hand... 

We decided to make the switch off of SourceForge (SF) a few months ago.. . However, there were things that SF provided that some of our existing users are probably accustomed to that we could not do on GitHub (ie. public yum repos), and we didn't want to go from SF Wiki -> GitHub Wiki and have our documentation tied within a provider's format. 

The plan is for the 2.11 xCAT release to be off of SourceForge.  The prior release will still exist on SF for now and we will slowly migrate them over as needed. So all the following is work in progress as we come closer to the 2.11 GA...   I think something like the below should be officially documented somewhere..  we will work on this.. 

**Landing Page:**  www.xcat.org  (This used to redirect directly to SF page, we now have a small intro and links)
**Bug Tracking**: Using GitHub Issues for all releases
**Mailing List:** continue to use sourceforces mailing lists
**Code Repo**:  Still git, hosted on GitHub
**Doc**: In xcat-core/docs now, Using Spinx format, rendered on ReadTheDocs http://xcat-docs.readthedocs.org/en/latest/   The *attempt* is to simplify the documentation with regards to new users.  The old xcat documentation is very complicated and verbose.
**Repos**: hosted on xcat.org -> http://xcat.org/files/xcat/repos/


Thanks for pointing out the Wikipedia pages, 

I will leave this issue open to address that and if you find anything else, please let us know.

**Comment by loz-hurst** [comment]
@whowutwut No worries!

If you google 'xcat' it's the sourceforge page that comes up too.  There needs to be the cross-referencing to make clear this is now the "main" page, or better yet perhaps a link to the landing page in case it changes again in the future?

> I will leave this issue open to address that and if you find anything else, please let us know.
This is exactly why I opened it as an issue ;)

Regards,

Laurence

**Comment by whowutwut** [comment]
Work in progress...   

**DONE**
* Added a notice in the following pages: 
     * https://sourceforge.net/p/xcat/wiki/Main_Page/
     * https://sourceforge.net/p/xcat/wiki/XCAT_Documentation/

**TODO**
- update Wikipedia xCAT page
- improve google search for xCAT

**Comment by loz-hurst** [comment]
@whowutwut I've taken the liberty of updating the Wikipedia page (https://en.wikipedia.org/wiki/XCAT).  I've only altered the links - I guess the text could probably do with a bit of a refresh and/or expanding but at least people will get to the right homepage if they go from there.

**Comment by whowutwut** [comment]
@loz-hurst thank you!

**Comment by whowutwut** [comment]
Closing out this issue.  Here's the latest summary: 

**xCAT Main Landing Page:** http://xcat.org/  
   * points to GitHub Issues for Bug Tracking
   * points to Documentation page
   * points to mailing list

**xCAT Documentation:** http://xcat-docs.readthedocs.org/    
   * select doc based on xCAT branch version

**GitHub Issues (Bug Tracking/Feature Request)**: https://github.com/xcat2/xcat-core/issues

SourceForge Bug tracking has been turned off to not allow new bugs to be created. GitHub issues is to be used instead.

We will continue to clean up and improve the docs.
