### ISSUE TITLE
[Test Case] add test case to issue #2636  'xcat command returns 0 when cmd fails due authorization'

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2702]
The related issue is #2636

**Comment by neo954** [comment]
Test cases added in pull request #2755.

**Comment by neo954** [comment]
@immarvin, please review the pull request #2755.

**Comment by hu-weihua** [comment]
#2755 has been moved to 2.13.4. So move this issue to 2.13.4

**Comment by zet809** [comment]
Hi, @hu-weihua , will you pls modify the title to include the issue number which the test case was added for? Thx!
