### ISSUE TITLE
Need to update the discinfo for new OS support in xCAT 2.11

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#271]
Open this issue as as placeholder to remind us to update the discinfo for the various RHEL 7.2 iso images.  This can be done closer to GA when the release candidates are available. 

Once we update the code, should also update the release notes to take out the work around for RHEL7.2

**Comment by cxhong** [comment]
Need to update the discinfo for SLES12 SP1 also

**Comment by pdlun92** [comment]
Pull Request #404

**Comment by whowutwut** [comment]
@tingtli , is FVT going to verify copycds? If not, let me know and I'll verify with RC1 build before closing this out

**Comment by tingtli** [comment]
@whowutwut 
I've verified it with SLES12 SP1 and RH7.2.  Close it
