### ISSUE TITLE
List the ipmi raw data for xCAT ipmi hdwr_ctrl command

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2735]
In order to better identify the ipmi raw commands that xCAT is calling to the BMC, make some code changes that we can enable/disable with a flag that will print out the raw commands being called to the BMC for various actions in xCAT.  

This will help us prioritize and verify required function with openbmc firmware teams. 

To enable outputting ipmi raw message, the site attribute 'xcatdebugmode' can be set as: 
```
# chdef -t site xcatdebugmode=1
1 object definitions have been created or modified.
```
The output will look like this:
```
# rpower frame45cn02 state
[ipmi_debug] rpower: state(state), raw_cmd: netfn(0x06=>App), cmd(0x38=>Get Channel Authentication Capabilities), data=[142, 4]
[ipmi_debug] rpower: state(state), raw_cmd: netfn(0x06=>App), cmd(0x3b=>Set session privilege level), data=[4]
[ipmi_debug] rpower: state(state), raw_cmd: netfn(0x06=>App), cmd(0x01=>Get Device ID), data=[]
[ipmi_debug] rpower: state(state), raw_cmd: netfn(0x00=>Chassis), cmd(0x01=>Get Chassis Status), data=[]
frame45cn02: on
[ipmi_debug] rpower: state(state), raw_cmd: netfn(0x06=>App), cmd(0x3c=>Close Session), data=[63, 91, 139, 192]
```
To disable outputting raw message, 
```
]# chdef -t site xcatdebugmodel=0
1 object definitions have been created or modified.
```
The output will be:
```
# rpower frame45cn02 state
frame45cn02: on
```

**Comment by whowutwut** [comment]
Adding some content to the description above.
