### ISSUE TITLE
[ xcat 2.13.2 Centos 6.5 ] Unable to capture image from Golden Client

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2737]
I'm trying to get golden image client. I have installed on Golden Client:

`systemimager-client`
`systemconfigurator`
`systemimager-common`
`perl-AppConfig`

And `systemimager-server` on Management Node

Now when I'm trying to get image. It showing error.

`imgcapture n00 -t sysclone -o centos6.5-x86_64-install-compute`

Output:
`Checking if systemimager packages are installed on localhost.`
`Checking if systemimager packages are installed on n00.`
`Preparing osimage centos6.5-x86_64-install-compute on n00.`
`Getting osimage "centos6.5-x86_64-install-compute" from n00 to localhost.`
`Error: export PERL5LIB=/usr/lib/perl5/site_perl/;LANG=C si_getimage -golden-client n00 -image` `centos6.5-x86_64-install-compute -ip-assignment dhcp -post-install reboot -quiet -update-script YES failed on the localhost.`
`Error: Can not get image centos6.5-x86_64-install-compute from n00`

Please help,
Thanks in advance.

**Comment by whowutwut** [comment]
@brianfinley can you help with this question?

**Comment by hu-weihua** [comment]
@dspatil7768 , it seems you used ``systemimager`` to clone completely and  without involving xCAT.  So maybe @brianfinley could help you.

**Comment by dspatil7768** [comment]
It's giving the same issue on Centos 7.3 and xCAT 2.13.2 also:

`[root@xcat xcat-dep]# imgcapture n00 -t sysclone -o centos7.3-x86_64-install-compute`
`Checking if systemimager packages are installed on xcat.`
`Checking if systemimager packages are installed on n00.`
`Preparing osimage centos7.3-x86_64-install-compute on n00.`
`Error: export PERL5LIB=/usr/lib/perl5/site_perl/;LANG=C si_prepareclient --server xcat --no-uyok --yes failed on the n00.`
`Error: Can not prepare Golden Client on n00.`

**Comment by zet809** [comment]
Hi, @dspatil7768 , which document and which section were you following? There is a spelling error in the "Install and Configure the Golden Client" section in our document.

**Comment by dspatil7768** [comment]
I'm following document from the link given below:

`http://xcat-docs.readthedocs.io/en/stable/advanced/sysclone/sysclone.html`

and I'm using Centos 6.5 and 7.3 with xCAT 2.13.2

**Comment by gurevichmark** [comment]
I have made some corrections to that document under PR #2799

**Comment by zet809** [comment]
hi, @dspatil7768 , has the issue resolved following the correct document? Thx!
