### ISSUE TITLE
rinstall is not able to set or detect the arch , does not happen with nodeset

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2745]
When doing discovery of a ppc64le node, the genesis kernel is ppc64 , so the arch is set to `ppc64`. 

Doing `rinstall` after discovery flags the following error message: 
```
# rinstall sn02 osimage=rhels7.3-ppc64le-install-service
Error: sn02: The value of 'arch' attribute is not same as the 'osarch' attribute for osimage.
Error: No available nodes for provision.
```

However, the older step by step method is OK and  the arch is changed to `ppc64le` 

```
# nodeset sn02 osimage=rhels7.3-ppc64le-install-service
sn02: install rhels7.3-ppc64le-service
# rsetboot sn02 net
sn02: Network
# rpower sn02 boot
sn02: reset
```

**Comment by immarvin** [comment]
hi @whowutwut , what is the node definition after discovery? this message is throw out by the pre-check of ``rinstall``  to make sure the arch of node match the arch of osimage.

**Comment by whowutwut** [comment]
@immarvin  The arch of the node is `ppc64` after discovery

Correct, I suspected that `rinstall` does some pre checks.  But this means we cannot use `rinstall` after we do discovery of PPC64LE machines.   Here's an example.... 

If arch is set right, rinstall works.... 
```
[root@fs1 ~]# lsdef frame45cn05 -i arch
Object name: frame45cn05
    arch=ppc64le
[root@fs1 ~]# rinstall frame45cn05 osimage=rhels7.4-pegas-ppc64le-install-compute
Provision node(s): frame45cn05
```

Force the arch to `ppc64`....  and we hit the problem 
```
[root@fs1 ~]# chdef frame45cn05 arch=ppc64
1 object definitions have been created or modified.
[root@fs1 ~]# rinstall frame45cn05 osimage=rhels7.4-pegas-ppc64le-install-compute
Error: frame45cn05: The value of 'arch' attribute is not same as the 'osarch' attribute for osimage.
Error: No available nodes for provision.
```

But nodeset will change it regardless..... 
```
[root@fs1 ~]# nodeset frame45cn05 osimage=rhels7.4-pegas-ppc64le-install-compute
frame45cn05: install rhels7.4-pegas-ppc64le-compute
[root@fs1 ~]# lsdef frame45cn05 -i arch
Object name: frame45cn05
    arch=ppc64le
```

Even copying a x86_64 osimage, it changes it to x86_64 to match...  
```
[root@fs1 tmp]# nodeset frame45cn05 osimage=rhels7.3-x86_64-install-compute
Warning: frame45cn05: petitboot might be invalid when provisioning rhels7.3-x86_64-install-compute,valid options: "xnba,pxe".
For more details see the 'netboot' description in the output of "tabdump -d noderes".
frame45cn05: install rhels7.3-x86_64-compute
[root@fs1 tmp]# lsdef frame45cn05 -i arch
Object name: frame45cn05
    arch=x86_64
```

So I guess from this...
1) nodeset makes no claims to help error protect the user 

2) We decided that genesis does not have to be compiled in LE, so should `rinstall` be enhanced to detect ppc64le and ppc64be machines? Is it possible? 

Or, if we think there's no change that should be done here, we have to add something in our documentation to state: 
- user cannot use `rinstall` directly after discovery as it cannot differentiate ppc64 and ppc64le.  
- user should either run `nodeset` to set the arch, or manually set the arch to the correct one before doing `rinstall`.

**Comment by immarvin** [comment]
hi @whowutwut , yes, ``nodeset`` won't validate the arch of osimage and node and will set the node.arch to osimage.arch. I do not think the arch of node can be detected by ``rinstall``, it will be better if node discovery can get the right arch of the node, otherwise, I will modify the validation between "ppc64le" and "ppc64" arch in``rinstall``

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2766

**Comment by immarvin** [comment]
hi @whowutwut , is the fix ok and is it ok to close this issue? thanks

**Comment by immarvin** [comment]
verified

**Comment by whowutwut** [comment]
@immarvin  Sorry for the delay and thanks for verifying.
