### ISSUE TITLE
[DEV] stay on "netbooting" after doing ubuntu14.4.4 diskless provison both in ppc64le and x86_64

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2746]
After doing diskless provision against ubuntu144.4 on both ppc64le and x86_64, the node status stay on ``netbooting``.  Found below error in the log

    [PPC64LE]
    [xdsh c910f03c17k24  "cat /var/log/xcat/xcat.log"] Running Time:1 sec
    RETURN rc = 0
    OUTPUT:
    c910f03c17k24: xcatdsklspost: downloaded postscripts successfully
    c910f03c17k24: xcatdsklspost: failed to download mypostscript.<nodename>, trying to call getpostscript.awk...
    c910f03c17k24: Fri Mar 24 17:03:42 EDT 2017 Running postbootscript: syslog
    c910f03c17k24: Fri Mar 24 17:03:42 EDT 2017 postbootscript syslog return with 0
    c910f03c17k24: Fri Mar 24 17:03:42 EDT 2017 Running postbootscript: remoteshell

    [in http log]
    10.3.17.24 - - [24/Mar/2017:17:11:23 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f03c17k24 HTTP/1.1" 404 538 "-" "Wget/1.15 (linux-gnu)"
    10.3.17.24 - - [24/Mar/2017:17:11:23 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f03c17k24 HTTP/1.1" 404 538 "-" "Wget/1.15 (linux-gnu)"

    [x86_64]
    [xdsh c910f04x35v07  "cat /var/log/xcat/xcat.log"] Running Time:1 sec
    RETURN rc = 0
    OUTPUT:
    c910f04x35v07: xcatdsklspost: downloaded postscripts successfully
    c910f04x35v07: xcatdsklspost: failed to download mypostscript.<nodename>, trying to call getpostscript.awk...
    c910f04x35v07: Sat Mar 25 11:25:19 EDT 2017 Running postbootscript: syslog
    c910f04x35v07: Sat Mar 25 11:25:19 EDT 2017 postbootscript syslog return with 0
    c910f04x35v07: Sat Mar 25 11:25:19 EDT 2017 Running postbootscript: remoteshell
    c910f04x35v07:
    
    [in http log]
    10.4.35.7 - - [25/Mar/2017:11:25:19 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f04x35v07 HTTP/1.1" 404 537 "-" "Wget/1.15 (linux-gnu)"
    10.4.35.7 - - [25/Mar/2017:11:25:19 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f04x35v07 HTTP/1.1" 404 537 "-" "Wget/1.15 (linux-gnu)"

Do we have any code change about preparing ``mypostscript.<nodename>`` ? 
@immarvin clould you help to look at it?

**Comment by immarvin** [comment]
duplicate with https://github.com/xcat2/xcat-core/issues/2757
