### ISSUE TITLE
[DEV] stay on "installing" after doing ubuntu144.4 diskful provison both in ppc64le and x86_64

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2747]
After doing diskful provision against ubuntu144.4 on both ppc64le and x86_64, the node status stay on ``installing``. Found below error in the log

     [ppc64le]
     3449 [lsdef -l c910f03c17k24 | grep status] Running Time:1 sec
     3450 RETURN rc = 0
     3451 OUTPUT:
     3452     status=installing
     3453     statustime=03-24-2017 17:53:48
     3454 CHECK:output =~ booted  [Failed]

     [http log]
     10.3.17.24 - - [24/Mar/2017:17:58:14 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f03c17k24 HTTP/1.1" 404 538 "-" "Wget/1.15 (linux-gnu)"

     [x86_64]
     3327 [lsdef -l c910f04x35v07 | grep status] Running Time:0 sec
     3328 RETURN rc = 0
     3329 OUTPUT:
     3330     status=installing
     3331     statustime=03-25-2017 12:26:11
     3332 CHECK:output =~ booted  [Failed]

     [http log]
     1226 10.4.35.7 - - [25/Mar/2017:12:38:19 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f04x35v07 HTTP/1.1" 404 537 "-" "Wget/1.15 (linux-gnu)"

I think this issue maybe has the same root cause with #2746 .
@immarvin  could you help to look at it ? thanks

**Comment by hu-weihua** [comment]
I found the same problem in ``rhels6.9-x86`` and ``rhels6.9-ppc64``

    10.2.2.27 - - [25/Mar/2017:11:32:09 -0400] "GET /tftpboot/mypostscripts/mypostscript.c910f02c02p27 HTTP/1.0" 404 323 "-" "Wget/1.12 (linux-gnu)"

**Comment by hu-weihua** [comment]
Maybe we are finding a problem which resulted in 70% cases failed in daily regression recently.

**Comment by cxhong** [comment]
it asked to enter "passphrase"  while installation ubuntu
````
![image](https://cloud.githubusercontent.com/assets/12398836/24372150/0320fb58-12fb-11e7-9538-77d21cdeb027.png)
`````

**Comment by immarvin** [comment]
duplicate with https://github.com/xcat2/xcat-core/issues/2757
