### ISSUE TITLE
[DEV] CN has report "provision completed" but MN still show "netbooting" in diskless+hierarchy+rhels7.3+x86

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2748]
After doing diskless hierarchy provision in rhels7.3+x86, got below inconsistent result.

Check from MN point of view:

    [lsdef -l c910f04x35v04 | grep status] Running Time:0 sec
    RETURN rc = 0
    OUTPUT:
        status=netbooting
        statustime=03-25-2017 15:08:11
        updatestatus=syncing
        updatestatustime=03-25-2017 15:04:08
    CHECK:rc == 0   [Pass]
    CHECK:output =~ booted  [Failed]

    RUN:xdsh c910f04x35v04 date

    [xdsh c910f04x35v04 date] Running Time:1 sec
    RETURN rc = 0
    OUTPUT:
    c910f04x35v04: Sat Mar 25 19:33:09 UTC 2017

Check from CN point of view:

    [xdsh c910f04x35v04  "cat /var/log/xcat/xcat.log"] Running Time:1 sec
    RETURN rc = 0
    OUTPUT:
    c910f04x35v04: xcatdsklspost: downloaded postscripts successfully
    c910f04x35v04: xcatdsklspost: failed to download mypostscript.<nodename>, trying to call getpostscript.awk...
    c910f04x35v04: Sat Mar 25 19:08:21 UTC 2017 Running postbootscript: syslog
    c910f04x35v04: Sat Mar 25 19:08:21 UTC 2017 postbootscript syslog return with 0
    c910f04x35v04: Sat Mar 25 19:08:21 UTC 2017 Running postbootscript: remoteshell
    c910f04x35v04:
    c910f04x35v04: Sat Mar 25 19:08:24 UTC 2017 postbootscript remoteshell return with 0
    c910f04x35v04: Sat Mar 25 19:08:24 UTC 2017 Running postbootscript: syncfiles
    c910f04x35v04: Sat Mar 25 19:08:24 UTC 2017 postbootscript syncfiles return with 0
    c910f04x35v04: Sat Mar 25 19:08:24 UTC 2017 Running postbootscript: otherpkgs
    c910f04x35v04:   Did not install any extra packages.
    c910f04x35v04: Sat Mar 25 19:08:24 UTC 2017 postbootscript otherpkgs return with 0
    c910f04x35v04: node booted successfully,reporting status...
    c910f04x35v04: provision completed.(c910f04x35v04)

**Comment by junxiawang** [comment]
From my point  may be something wrong with the c910f04x35v02, all provision on this machine could not be executed successfully.

**Comment by immarvin** [comment]
proved to be a test case bug

**Comment by hu-weihua** [comment]
Did not found in last day daily regression, close first and will reopen if need in the future.
