### ISSUE TITLE
[DEV] Failed to reboot after diskful installation in sles11.4+ppc64

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2749]
In sles11.4+ppc64,  after diskful installation (flat), CN failed to reboot from harddisk. the log as below

    Mar 25 10:54:21 c910f02c01p14 xcat[31010]: xCAT: Allowing rinstall to c910f02c02p28 osimage=sles11.4-ppc64-install-compute for root from localhost
    Mar 25 10:54:24 c910f02c01p14 xcat[31107]: xCAT: Allowing nodels to c910f02c02p28 nodehm.conserver for root from localhost
    Mar 25 10:54:24 c910f02c01p14 xcat[31118]: xCAT: Allowing gethmccon to c910f02c02p28 text for root from localhost
    Mar 25 10:54:34 c910f02c01p14 xcat: c910f02c02p28 status: powering-off statustime: 03-25-2017 10:54:34
    Mar 25 10:55:00 c910f02c01p14 dhcpd: BOOTREPLY for 10.2.2.28 to c910f02c02p28 (da:08:4f:d8:b2:03) via eth0
    Mar 25 10:55:00 c910f02c01p14 dhcpd: BOOTREPLY for 10.2.2.28 to c910f02c02p28 (da:08:4f:d8:b2:03) via eth0
    Mar 25 10:55:00 c910f02c01p14 in.tftpd[31130]: RRQ from 10.2.2.28 filename /boot/grub2/grub2-c910f02c02p28
    Mar 25 10:55:08 c910f02c01p14 xcat[31135]: xCAT: Allowing gethmccon to c910f02c02p28 text for root from localhost
    Mar 25 10:55:09 c910f02c01p14 xcat: c910f02c02p28 status: powering-on statustime: 03-25-2017 10:55:09
    Mar 25 10:56:01 c910f02c01p14 xcat: c910f02c02p28 status: installing statustime: 03-25-2017 10:56:01
    Mar 25 11:03:15 c910f02c01p14 xcat: c910f02c02p28 status: booting statustime: 03-25-2017 11:03:15
    Mar 25 11:07:19 c910f02c01p14 xcat[31464]: xCAT: Allowing getpostscript from c910f02c02p28
    Mar 25 11:07:20 c910f02c02p28 xcat: Sat Mar 25 15:07:18 EDT 2017 Running postscript: syslog
    Mar 25 15:07:19 c910f02c02p28 syslog-ng[9777]: syslog-ng starting up; version='2.0.9'
    Mar 25 15:07:19 c910f02c02p28 xcat: Install: syslog setup
    Mar 25 11:07:20 c910f02c02p28 xcat: Sat Mar 25 15:07:19 EDT 2017 postscript syslog return with 0
    Mar 25 15:07:19 c910f02c02p28 xcat: Sat Mar 25 15:07:19 EDT 2017 postscript syslog return with 0
    Mar 25 11:07:20 c910f02c02p28 xcat: Sat Mar 25 15:07:19 EDT 2017 Running postscript: remoteshell
    Mar 25 15:07:19 c910f02c02p28 xcat: Sat Mar 25 15:07:19 EDT 2017 Running postscript: remoteshell
    Mar 25 15:07:19 c910f02c02p28 xcat: remoteshell:  setup /etc/ssh/sshd_config and ssh_config
    Mar 25 15:07:19 c910f02c02p28 xcat: Install: setup root .ssh
    Mar 25 11:07:21 c910f02c01p14 xcat[31467]: xCAT: Allowing getcredentials ssh_dsa_hostkey from c910f02c02p28
    Mar 25 15:07:20 c910f02c02p28 xcat: remoteshell: getting ssh_host_dsa_key
    Mar 25 15:07:24 c910f02c02p28 kernel: klogd 1.4.1, log source = /proc/kmsg started.
    Mar 25 15:27:24 c910f02c02p28 -- MARK --
    Mar 25 15:47:24 c910f02c02p28 -- MARK --
    Mar 25 16:07:19 c910f02c02p28 syslog-ng[9777]: Log statistics; dropped='udp(AF_INET(10.2.1.14:514))=0', processed='center(queued)=16', processed='center(received)=10', processed='destination(mailinfo)=0', processed='destination(mailwarn)=0', processed='destination(loghost)=10', processed='destination(localmessages)=6', processed='destination(newserr)=0', processed='destination(mailerr)=0', processed='destination(netmgm)=0', processed='destination(console)=0', processed='destination(null)=0', processed='destination(mail)=0', processed='destination(xconsole)=0', processed='destination(firewall)=0', processed='destination(acpid)=0', processed='destination(newscrit)=0', processed='destination(newsnotice)=0', processed='source(src)=10'
    Mar 25 16:27:19 c910f02c02p28 -- MARK --

**Comment by immarvin** [comment]
found the issue https://github.com/xcat2/xcat-core/issues/2757 in the environment

**Comment by hu-weihua** [comment]
Have been verified and close this issue.
