### ISSUE TITLE
LiveCD Install based install `osimage`

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#2767]
We have a requirement to install a distribution that comes as a LiveCD with a packaged installer. We are trying to turn this into an install osimage.

However we have no idea where to begin, as this kind of installation does not easily convert into a net-install. Any ideas on how to proceed?

**Comment by immarvin** [comment]
hi @samveen , a suggestion is to refer to the grub.cfg inside the LiveCD iso to find the correct kernel, initrd and kernel options to bring up the root file system inside the iso, then try to make up the correct grub/pxe config file for the network bring up

**Comment by samveen** [comment]
TY for the pointer. I'll investigate and post the findings.
