### ISSUE TITLE
[ Centos 7.3 i.e. 1611 xCAT 2.13.2 ] Discovery packet is ready and waiting for 5 seconds 

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2774]
Hello, previously also I have posted this problem for xCAT installation on VMware for same versions of centos and xCAT. It worked fine in VMware for Centos 6.5 in the case of stateful and stateless. But I'm facing mentioned above in the physical server for Centos 7.3 and xCAT 2.13.2.

My configuration is as below:

tabdump networks

`[root@xcat ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"172_16_0_0-255_255_0_0","172.16.0.0","255.255.0.0","ens34","172.16.0.1","172.16.0.3","172.16.0.3",,,,"172.16.0.50-172.16.0.100",,,,,,,,,
"192_168_220_0-255_255_255_0","192.168.220.0","255.255.255.0","ens33",,,,"192.168.220.2",,,,,,,,,,,,`

tabdump site

`[root@xcat ~]# tabdump site`
`#key,value,comments,disable`
`"blademaxp","64",,`
`"domain","cdac.in",,`
`"fsptimeout","0",,`
`"installdir","/install",,`
`"ipmimaxp","64",,`
`"ipmiretries","3",,`
`"ipmitimeout","2",,`
`"consoleondemand","no",,`
`"master","172.16.0.3",,`
`"forwarders","192.168.220.2",,`
`"nameservers","172.16.0.3",,`
`"maxssh","8",,`
`"ppcmaxp","64",,`
`"ppcretry","3",,`
`"ppctimeout","0",,`
`"powerinterval","0",,`
`"syspowerinterval","0",,`
`"sharedtftp","1",,`
`"SNsyncfiledir","/var/xcat/syncfiles",,`
`"nodesyncfiledir","/var/xcat/node/syncfiles",,`
`"tftpdir","/tftpboot",,`
`"xcatdport","3001",,`
`"xcatiport","3002",,`
`"xcatconfdir","/etc/xcat",,`
`"timezone","Asia/Calcutta",,`
`"useNmapfromMN","no",,`
`"enableASMI","no",,`
`"db2installloc","/mntdb2",,`
`"databaseloc","/var/lib",,`
`"sshbetweennodes","ALLGROUPS",,`
`"dnshandler","ddns",,`
`"vsftp","n",,`
`"cleanupxcatpost","no",,`
`"dhcplease","43200",,`
`"auditnosyslog","0",,`
`"xcatsslversion","TLSv1",,`
`"auditskipcmds","ALL",,`
`"dhcpinterfaces","ens34",,`

- Manual node definition using mkdef:

`mkdef -t node -o n00 groups=all,x86_64 arch=x86_64 netboot=pxe installnic=ens33 interface=ens33
provmethod=centos7.3-x86_64-install-compute primarynic=ens33 mac=00:0C:29:7C:CB:E2 os=centos7.2 postbootscripts=otherpkgs postscripts=syslog,remoteshell,syncfiles,sysfiles profile=compute tftpserver=172.16.0.3 xcatmaster=172.16.0.3`

where `172.16.0.3` is my private ip.

- `chtab key=system passwd.username=root passwd.password=123456`

- `nodeset n00 osimage=centos7.3-x86_64-install-compute`

So what should I do??
I have attached one snap below.
![xcat problem](https://cloud.githubusercontent.com/assets/22992849/24448702/a0b09214-1492-11e7-8483-b17b4b070096.jpg)

**Comment by zet809** [comment]
hi, @dspatil7768 , will you pls try "xcatprobe discovery -n n00  -m mtm" or "xcatprobe discovery -n n00  -m switch"  to do configuration checking? And then let us know the result?

**Comment by dspatil7768** [comment]
-`[root@xcat ~]# xcatprobe discovery -n n00 -m mtms`
`[n00] : No mtm or serival for 'mtms' type discovery                                                          [FAIL]`

-`[root@xcat ~]# xcatprobe discovery -n n00 -m switch`
`[n00] : Attribute switch, switchport Invalid                                                                      [FAIL]`

**Comment by samveen** [comment]
@dspatil7768 Please correct the command to remove the trailing `s`:
`xcatprobe discovery -n n00 -m mtm`

**Comment by dspatil7768** [comment]
`[root@xcat ~]# xcatprobe discovery -n n00 -m mtm`
`Invalid discovery type. the vaild types are mtms,switch                                                           [FAIL]`
`Usage:`
   ` discovery -h`
   ` discovery -n <node_range> -m <discovery_type> [-t <max_waiting_time>] [-V] [--noprecheck]` 
    `discovery -n <node_range> -m <discovery_type> -r <roll_back_duration> [-V] [--noprecheck]`

`Description:`
    `Probe the discovery process, including pre-check for required configuration. If any pre-checks fail, 'discovery' ...`
   ` The default behavior of xcatprobe discovery is to monitor the discovery process in real time. Use the -r option f...`

   ` [NOTE] Currently, hierarchial structure is not supported.`

`Options:`
    `-h           : Get usage information of discovery.`
    `-V           : Output more information for debug.`
    `-m           : The method of discovery, the valid values are mtms,switch.`
    `-n           : The range of predefined nodes, must be used with option -m.`
   ` -t           : The maximum time to wait when doing monitor, unit is minutes. default is 60.`
   ` -r           : Trigger 'Replay history' mode. Follow the duration of rolling back. Units are 'h' (hour) or 'm' (m...`
                   `Supported format examples: 3h30m (3 hours and 30 minutes ago), 2h (2 hours ago), 40m (40 minutes a...`
                  ` If unit is not specified, hour will be used by default.`
   ` --noprecheck : skip pre-checking discovery to validate correct configuration.`

**Comment by zet809** [comment]
Seems to me you planed to do OS deployment. 
1. set ip for the node defintion.
2. makehosts
3. copycds <ISO> --> To generate the osimage object
4. nodeset <node> osimage=<osimage_object_name>
5. rpower <node> reset --> To start os deployment

**Comment by dspatil7768** [comment]
> set IP for the node definition. 

I was facing this from last many days and that is what I was forgetting setting IP in a definition.
Thank you 👍 

`[root@xcat** xcat]# lsdef n00`
`Object name: n00`
  `arch=x86_64`
  `currchain=boot`
  `currstate=boot`
  `groups=all,x86_64`
  `installnic=enp2s0f0`
  `interface=enp2s0f0`
  *`ip=172.16.0.101`*
  `mac=00:1E:67:29:01:7A`
  `netboot=pxe`
  `os=centos7.3`
  `postbootscripts=otherpkgs`
  `postscripts=syslog,remoteshell,syncfiles,sysfiles`
  `primarynic=enp2s0f0`
  `profile=compute`
  `provmethod=centos7.3-x86_64-install-compute`
  `status=booted`
  `statustime=03-30-2017 11:37:34`
  `tftpserver=172.16.0.3`
  `xcatmaster=172.16.0.3`
