### ISSUE TITLE
otherpkgs never executed problem

### ISSUE THREAD

**Issue by wharton9** [xcat2/xcat-core#2775]
xcat version: 2.12
xcat server os: rhel6.8
deploy rhel7.2 to the nodes
After the os were deployed while otherpkgs never executed,  and even no /var/log/xcat directory exists on nodes . 
which log i could get to analysis and what maybe result in this problem?

here is the postscripts setting:
[root@master xcat]# lsdef gss01|grep scripts
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles

and i  made sure below two 
Make sure the path and name of otherpkgs configuration file are correct. Path: /opt/xcat/share/xcat/netboot(install)/<platform>/profile.<os>.<arch>.otherpkgs.pkglist
Make sure the packages have been copied to correct path. Path: /install/post/otherpkgs/<os>/<arch>/xcat

**Comment by immarvin** [comment]
2  possible debug methods:
1.  you can run ``updatenode gss01  -V -P otherpkgs `` 
2. ssh to the provisioned node, then:
(1). ``cd /xcatpost`` 
(2). add "set -x"   and "set +x" to the beginning and end of "otherokgs" 
(3).  run ``./mypostscript.post``

**Comment by immarvin** [comment]
no response, close the ticket now, please reopen it if any update

**Comment by wharton9** [comment]
sorry for delayed, after i change OS from rhel6 to rhel7, then the problem gone. i think the scripts in  packages is based on rhel7 which is not compatible with rhel6. Thanks.
