### ISSUE TITLE
[DEV] postbootscript "syncfiles" failed in sles12.2-ppc64le in hierarchical provision

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2781]
Postbootscript "syncfiles" failed in cases ``reg_linux_diskfull_installation_hierarchy, reg_linux_diskless_installation_hierarchy, reg_linux_statelite_installation_hierarchy_by_ramdisk, reg_linux_statelite_installation_hierarchy_by_nfs`` in sles12.2-ppc64le. 

     [lsdef -l c910f03c17k29 | grep status] Running Time:0 sec
     RETURN rc = 0
     OUTPUT:
     status=failed
     statustime=03-29-2017 15:32:35
     updatestatus=syncing
     updatestatustime=03-29-2017 15:12:44
     CHECK:rc == 0   [Pass]
     CHECK:output =~ booted  [Failed]

     c910f03c17k29: xcatpostinit1.service enabled
     c910f03c17k29: Wed Mar 29 19:22:39 EDT 2017 Running postscript: syslog
     c910f03c17k29: Wed Mar 29 19:22:39 EDT 2017 postscript syslog return with 0
     c910f03c17k29: Wed Mar 29 19:22:39 EDT 2017 Running postscript: remoteshell
     c910f03c17k29:
     c910f03c17k29: Created symlink from /etc/systemd/system/multi-user.target.wants/sshd.service to /usr/lib/systemd/system/sshd.service.
     c910f03c17k29: Wed Mar 29 19:22:42 EDT 2017 postscript remoteshell return with 0
     c910f03c17k29: Wed Mar 29 19:22:42 EDT 2017 Running postscript: syncfiles
     c910f03c17k29: Wed Mar 29 19:23:58 EDT 2017 postscript syncfiles return with 1
     c910f03c17k29: Wed Mar 29 19:23:58 EDT 2017 Running postscript: setupntp
     c910f03c17k29: inactive
     c910f03c17k29: /usr/sbin/rcntpd ntptimeset
c910f03c17k29: Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
c910f03c17k29: Wed Mar 29 15:31:54 EDT 2017 postscript setupntp return with 0
c910f03c17k29: running /xcatpost/mypostscript.post
c910f03c17k29: Wed Mar 29 15:32:35 EDT 2017 Running postbootscript: otherpkgs
c910f03c17k29: Wed Mar 29 15:32:35 EDT 2017 postbootscript otherpkgs return with 0
c910f03c17k29: /xcatpost/mypostscript.post return

**Comment by hu-weihua** [comment]
@junxiawang ,could you help to reproduce this issue in a new cluster for @bybai ? thanks.

**Comment by bybai** [comment]
The `syncfiles` is failed 1 in sles12.2 CN with SN, I got the error from compute.log:
```
Mar 29 15:31:51 c910f03c17k28 xcat[9950]:  xCAT: Allowing syncfiles from c910f03c17k29
Mar 29 15:31:51 c910f03c17k28 xcat[9951]:  Can not open file /tmp/rsync_c910f03c17k29 at /opt/xcat/lib/perl/xCAT/RSYNC.pm line 150.
Mar 29 15:31:51 c910f03c17k28 xcat[9951]:  xcatd: syncfiles plugin bug, pid 9951, process description: 'xcatd SSL: syncfiles for c910f03c17k29: syncfiles instance: xdsh instance' with error 'Died at /opt/xcat/sbin/xcatd line 1974.#012'
Mar 29 15:31:51 c910f03c17k29 xcat:  ./syncfiles: Perform Syncing File action encountered error
Mar 29 15:31:51 c910f03c17k29 xcat  Wed Mar 29 19:23:58 EDT 2017 postscript syncfiles return with 1
Mar 29 15:31:51 c910f03c17k29 xcat  Wed Mar 29 19:23:58 EDT 2017 Running postscript: setupntp
Mar 29 15:31:51 c910f03c17k29 xcat:  Install: Setup NTP
Mar 29 15:31:51 c910f03c17k29 xcat:  /usr/sbin/rcntpd ntptimeset
```
The related code in  /opt/xcat/lib/perl/xCAT/RSYNC.pm line 150:
```
        if ($::SYNCSN == 1)
        {                                                 # syncing service node
            $rsyncfile = "/tmp/rsync_$$config{'dest-host'}";
            $rsyncfile .= "_s";
        }
        else
        {
            $rsyncfile = "/tmp/rsync_$$config{'dest-host'}";
        }
        open RSCYCCMDFILE, "> $rsyncfile"
          or die "Can not open file $rsyncfile";              #line 150
        my $dest_dir_list = join ' ', keys %{ $$config{'destDir_srcFile'} };
        my $dest_user_host = $$config{'dest-host'};
```

I used test.pl to test the line 150 code in both sles12.2 and redhat7.3, both can work well, and there is no die error "Can not open file $rsyncfile"; 
My test.pl:
```
#!/usr/bin/perl
my  $rsyncfile = "/tmp/rsync_bai";
open RSCYCCMDFILE, "> $rsyncfile"
  or die "Can not open file $rsyncfile";
print RSCYCCMDFILE "#!/bin/sh\n";
close RSCYCCMDFILE;
```

So I guess if `/tmp` dir is full in  c910f03c17k29 or the permission is not right for `tmp`;

Hi @junxiawang, could you help reproduce the issue?

**Comment by bybai** [comment]
This cannot be reproduced. I guess it should be environment problem.
