### ISSUE TITLE
[Test case]:run xCAT in "XCATBYPASS" mode and simply reload xCAT to check if there is any errors

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2787]
Reference to defect #2727 
To check if there are any errors in loading xcat and starting xcatd.

**Comment by whowutwut** [comment]
If possible, we should create these kind of testcase in a new bundle, that potentially we can invoke when doing automated verification on each pull request commit.  So the new bundle will be able to be run quickly, no provisioning testing.

**Comment by hu-weihua** [comment]
replaced by new task xcat2/xcat2-task-management#190
