### ISSUE TITLE
Need verify rh6.9 by checklist before xCAT2.13.3 release

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2793]
@junxiawang , we need verify rh6.9-ppc by checklist https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/Redhat%206.9-ppc64%20checklist and rh6.9-x86 by checklist https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/Redhat%206.9-x86_64%20checklist.  Most items have been covered by automation, could you help to verify the rest part before 2.13.3 release. it is a little urgent.  thanks.

**Comment by junxiawang** [comment]
need to do manually  test for rh6.9
