### ISSUE TITLE
Nodeset fails to generate /tftpboot config files if ip attribute is not set

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#2794]
If `ip` attribute for the VM is not set, `nodeset` returns with `RC=0`, but config files for that VM are not generated in `/tftboot/grub2` and the log file has these entries:

```
xCAT: Allowing nodeset to lsvm_test1 osimage=rhels7.3-ppc64le-install-compute for root from localhost
lsvm_test1: grub2 netboot: stop configuration because of none sharedtftp and not on same network with its xcatmaster.
xCAT: grub2 netboot: no valid nodes. Stop the operation on this server.
```
This happens for VMs, but might also happen for real servers

@daniceexi suggested:
*If nodeset does not generate an usable configuration, it should display an error and return non-zero.*

**Comment by robin2008** [comment]
It should be a bug. We can easily reproduce it with below steps:
1, create a node with IP and MAC
2, makehosts/makedns/nodeset osimage=<xxx>
3, chdef the node and remove the IP attribute (not clean the /etc/hosts and DNS),  and remove the boot configuration files
4, run nodeset again,  it will not complain the error.

The IP address should be a key attribute of node for provisioning, we need to validate the it during nodeset. And two cases should be considered:
1,  no Provision IP set in DB
2, conflict IP:  the IP in DB is not the one in DNS. 

Note: This issue will only cover the provision IP address.

**Comment by robin2008** [comment]
For Mark' issue.  It is caused by "sharedtftp = 0", in this case, nodeset will filter the nodes according to its IP address.
```
    #if not shared tftpdir, then filter, otherwise, set up everything
    if ($request->{'_disparatetftp'}->[0]) { #reading hint from preprocess_command
        @nodes = ();
        foreach (@rnodes) {
            if (xCAT::NetworkUtils->nodeonmynet($_)) {
                push @nodes, $_;
            } else {
                xCAT::MsgUtils->message("S", "$_: grub2 netboot: stop configuration because of none sharedtftp and not on same network with its xcatmaster.");
            }
        }
    } else {
        @nodes = @rnodes;
    }

    #>>>>>>>used for trace log>>>>>>>
    my $str_node = join(" ", @nodes);
    xCAT::MsgUtils->trace($verbose_on_off, "d", "grub2: nodes are $str_node");

    # return directly if no nodes in the same network
    unless (@nodes) {
        xCAT::MsgUtils->message("S", "xCAT: grub2 netboot: no valid nodes. Stop the operation on this server.");
        return;
    }
```
As only 1 node without IP passed,  after the filtering,  no nodes passed to the normal process.
But here we cannot return error, as current xcatd might be running on one of the SN. It is the suitable behavior to ignore it.

**Comment by gurevichmark** [comment]
But should we somehow tell the user something went wrong?
User runs `nodeset` command and gets RC=0 and no errors are displayed, but in fact no config files were generated. Are they not needed in this case? Would a user be able to run `rpower` as a next step ?

**Comment by robin2008** [comment]
@gurevichmark 

Currently xCAT hierarchy design has such limitation,  for scale-out operation, like nodeset,  it will broadcast all node range to all SN.  And then each SN will filter those nodes not in its subnet before handling it.

On each SN,  it did not know if the node is handled successfully by other SN or  MN,  so for the nodes filtered by this SN, it is hard to say it is failure. We have to define a rule to tell what's an error.
For example, 
 if the node's xcatmaster is defined,  then on those SN, if the node will be filtered,  it will report error
if no 'xcatmaster' is defined,  then on MN, if the node will be filtered,  it will report error.

As it will introduce more check logic into nodeset, we need to ensure no big performance impact.

**Comment by gurevichmark** [comment]
@robin2008 Thank you for the explanation. I understand now why SN would want to filter out nodes not in its subnet, and therefore might not be an error for a specific SN.
But is it ever valid to have a node definition with no "ip" attribute set ? Should we flag it as an error before the broadcast of all nodes to all SNs?

**Comment by robin2008** [comment]
@gurevichmark 
You have mentioned a good method to handle the error in normal case. But the "IP" definition is more complicate there. I also make the confusing about it in the first time. After discussed with @immarvin, I got that xCAT support both IP definition(I got this understanding from  ) .  one is defined in DB and then populated to DNS,  the other is only defined in DNS (normally an external DNS, check out our auto test environment for such scenario) .

Your idea is good to handle the case if IP defined in DB, but in DNS only mode.  As SN could have different DNS server,  it cannot tell if other SN or MN could resolve the node,  the only method is to broadcast them first, and handled in SN's process_request.

So here,  my proposal is as below:
   if the node explicitly define 'xcatmaster',  and on that SN, we will report warning message when it be filtered.  But RC will not be set to 1,  as in this SN,  it cannot tell if the node be handled by other SN.

To handle the RC,  the only method is to using customized "handle_response" in client.  we can define the return data structure to include each finished node (succ or fail),  and for a node, if no Succ record, then the whole RC is not zero.

But we think the change is too big and risky.

**Comment by robin2008** [comment]
PR #2982 is for it, 
And now it only covers grub2/petitboot/xnba,   yaboot/pxe also has such issue, but they are  in low priority.

**Comment by gurevichmark** [comment]
I am good with this solution.

**Comment by robin2008** [comment]
Update the PR, and apply the changes on review comments from Mark and XiaoPeng.
