### ISSUE TITLE
confignetwork does not work with network confignics can work with.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2798]
Looking at the documentation for confignetwork:
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_network.html

It looks like if one wants bonded bonded or vlan network configurations that it shoud replace confignics.  I'm trying to get confignetwork to setup my regular network configuration before i attempt to setup the vlan setup.

However, when add confignetwork to the postscirpts I get the following errors:

```
[root@c460mgt01 dcsbuild]# updatenode c460mgt02 --scripts=confignetwork 2>&1 | tee /tmp/c460mgt02.confignetwork.log

c460mgt02: [I]: All valid nics and device list:
c460mgt02: [I]: enP1p12s0f0
c460mgt02: [I]: enP1p12s0f1
c460mgt02: [I]: enP1p12s0f2
c460mgt02: [I]: enP1p12s0f3
c460mgt02: [I]: [E]: Error:   pair is invalid nic and nicdevice pair.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f0
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f0.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f1
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f1.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f2
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f2.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f3
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f3.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : [E]: Error:   pair is invalid nic and nicdevice pair.
c460mgt02: [E]: Error : please check nictypes for [E]: Error:   pair is invalid nic and nicdevice pair..
c460mgt02: postscript: confignetwork exited with code 0
c460mgt02: Running of postscripts has completed.

```

below is the configuration that I am testing prior to adding vlan entries.
```
[root@c460mgt01 dcsbuild]# lsdef c460mgt02 -i nicips,nicnetworks,nictypes,nichostnamesuffixes -z
# <xCAT data object stanza file>

c460mgt02:
    objtype=node
    nichostnamesuffixes.enP1p12s0f2:=-enP1p12s0f2
    nichostnamesuffixes.enP1p12s0f1:=-enP1p12s0f1
    nichostnamesuffixes.enP1p12s0f3:=-enP1p12s0f3
    nichostnamesuffixes.enP1p12s0f0:=-enP1p12s0f0
    nicips.enP1p12s0f0=10.1.0.2
    nicips.enP1p12s0f3=129.40.234.4
    nicnetworks.enP1p12s0f0=OS
    nicnetworks.enP1p12s0f3=pub_yellow
    nictypes.enP1p12s0f1=Ethernet
    nictypes.enP1p12s0f2=Ethernet
    nictypes.enP1p12s0f0=Ethernet
    nictypes.enP1p12s0f3=Ethernet
```

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
Now confignetwork cannot replace all the functions from confignics.
They have different functions now. If you want to configure bond vlan bridge, you can use confignetwork, otherwise, you need to use confignics first.  In current solution, you can use confignics and confignetwork both to make your work smoothly.

**Comment by ralphbellofatto** [comment]
Just to establish a baseline, i ran

```
updatenode c460mgt02 --scripts=confignics,confignetwork
```

and it produced:

```
c460mgt02: [I]: ib0
c460mgt02: [I]: [E]: Error:   pair is invalid nic and nicdevice pair.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f0
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f0.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f1
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f1.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f2
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f2.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : enP1p12s0f3
c460mgt02: [E]: Error : please check nictypes for enP1p12s0f3.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : ib0
c460mgt02: [E]: Error : please check nictypes for ib0.
c460mgt02: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c460mgt02: configure nic and its device : [E]: Error:   pair is invalid nic and nicdevice pair.
c460mgt02: [E]: Error : please check nictypes for [E]: Error:   pair is invalid nic and nicdevice pair..
c460mgt02: postscript: confignetwork exited with code 0
c460mgt02: Running of postscripts has completed.
```

So, are you telling me that confignetwork is functioning "correctly" when it is producing errors, that have to be subsequently ignored?

That seems like an odd design point,  to print out "[E]: Error: " messages that are not errors...

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
Thank you to pointing this out. The error message should be enhanced to say like 'confignetwork does not support this function'.

**Comment by ralphbellofatto** [comment]
If this is expected to work in conjunction with confignics and not replace it, it should be an information message OR a warning, but definitely not an Error.

Calling it an error in this case is completely miss-leading as this is expected functionality to only handle bond and vlans and not regular network configuration.

**Comment by bybai** [comment]
Since the design is not finished, remove sprint label.

**Comment by bybai** [comment]
Hi @ralphbellofatto , we will enhance confignetwork script in this sprint. Th user interface design is in this #3089. The framework design is in #3090.  Since all the work break down into several tasks, I will move this issue into icebox, and use other specified tasks to trace the work. thanks.

**Comment by samveen** [comment]
@immarvin Maybe move this to a newer milestone (and other open issues in the `2.13.5` milestone)?

**Comment by immarvin** [comment]
hi @bybai , is there any update on this ticket? is the newly opened tasks finished?

@samveen , thanks for reminder.

**Comment by bybai** [comment]
Hi @samveen and @ralphbellofatto ,
This feature is included in 2.13.6. confignetwork realize configure Ethernet ip just like confignics.  Will add integrate configib later.

**Comment by whowutwut** [comment]
@bybai If this is partially  implemented, can you reference the issues/PR that completes ...  

Is there an issue open to track the configib work? We can also make cross references here until all the function is complete.  Removing the milestone.

**Comment by bybai** [comment]
Hi @whowutwut , 
`confignetwork` can replace `confignics` now. I have integrated `configib` into `confignetwork`, it is in #3072

**Comment by whowutwut** [comment]
@bybai   If implemented, we should move this to pending state and give @ralphbellofatto  A change to validate ....  Which milestone is it complete? 2.13.6 or 2.13.7?
