### ISSUE TITLE
rinv ocasionally produces BMC error without telling which node was in error.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2803]
we have a test where we perform rinv to fetch the firmware levels and check it.

For example, it does the following:
```
rinv c460c[004-009,011-013,015-018,037-040,042-051,053-058,060-061,064-070,073-080,082-085,087-089,133,135-136,139-141,143-147,149-153,155],c460login[01-02] firmware 2>/tmp/40MalkCHMF/stderr
expected firmware levels: bmc_firmware=2.13,sys_firmware=IBM-garrison-ibm-OP8_v1.12_2.70
(ERROR) Error: Error parsing FRU data from BMC

cat /tmp/40MalkCHMF/stderr
```

occasionally this test displays:
```
 Error: Error parsing FRU data from BMC
```

Where the error message parsing fru data from bmc fails to display which node the error came from.

**Comment by zet809** [comment]
Thx, @ralphbellofatto ,we need to fix it in 2.13.4 release.

**Comment by zet809** [comment]
Hi, @ralphbellofatto , this issue was fixed with Pull Request #3030 , pls reference it for more information. Thx!

**Comment by whowutwut** [comment]
@zet809 @ralphbellofatto  Can you help close this out of it's resolved?

**Comment by whowutwut** [comment]
Closing for now, please re-open if the issue persists.
