### ISSUE TITLE
Update xCAT-genesis-builder for building MCP 8.1

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#281]
Update xCAT-genesis-builder for building MCP 8.1, make it suitable for openpower

**Comment by fenggaobj** [comment]
https://github.com/xcat2/xcat-core/commit/5550c0260e240ec3b366e6c8b9904a7cf855b902

**Comment by whowutwut** [comment]
Hi @fenggaobj , I'm trying to understand which branch you committed that above 5550c02 to...   We added you as a contributor to the xcat project with read permission to xcat-core... I think you need to create a pull request to merge the changes to xcat2/xcat-core..

@daniceexi , comments?

**Comment by whowutwut** [comment]
Sorry, I see pull request #284  addressing this issue

**Comment by zet809** [comment]
I had reviewed the pull request and merge the code, so close this issue.
