### ISSUE TITLE
[openbmc]enhance bmcsetup for openbmc

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2810]
Modify bmcsetup script to disable user configuration in-band through IPMI for WSP server.
Acceptance: bmcsetup able to run within host OS or genesis if possible.

**Comment by zet809** [comment]
Hi, @whowutwut , the bmcsetup related to multiple ipmi in-band command supporting for WSP, we have the page https://github.ibm.com/vhu/c910env/blob/master/notes/openbmc/P1_items_openbmc_planning.md to record the test result for the ipmitool command used in bmcsetup. Will you pls check with Firmware team that for the failed command, is there any plan to support it?If yes, when? As for the OK command, will it be changed or deprecated some day? We really need their confirm, thx a lot.

**Comment by zet809** [comment]
It seems the ipmitool in-band interface doesn't work at all:
```
[xCAT Genesis running on p9euh02 /]# ipmitool lan set 1 ipaddr 10.6.9.200
Setting LAN IP Address to 10.6.9.200
[xCAT Genesis running on p9euh02 /]# ipmitool lan print 1
Set in Progress         : Set Complete
Auth Type Support       : MD5
Auth Type Enable        : Callback : MD5
                        : User     : MD5
                        : Operator : MD5
                        : Admin    : MD5
                        : OEM      : MD5
IP Address              : 10.6.9.254
Subnet Mask             : 255.0.0.0
MAC Address             : 70:e2:84:14:24:74
Default Gateway IP      : 10.0.0.101
Cipher Suite Priv Max   : Not Available
Bad Password Threshold  : Not Available
```

**Comment by daniceexi** [comment]
This is a high risk issue for xCAT!!!

**Comment by zet809** [comment]
Hi, @whowutwut, I close this task and use #3051 to tracing the interface implementing by OpenBMC team.
