### ISSUE TITLE
[openbmc]rspconfig support

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2815]
The EPIC to tracing tasks for rspconfig support for openbmc:
final options support for OpenBMC will be: 
ip/netmask/gateway/
vlan/alert/snmpdest/community
useradd/userch/userrm/userls

**Comment by whowutwut** [comment]
@zet809 @xuweibj Can we have some focus on this EPIC ?  Let me know what is missing and I'm also trying to chase down some information in the slack channels...  please communicate with the openbmc team directly to get answers and move some of the issues forward.  If we can code against the endpoint and return 403 forbidden, that would be better.

**Comment by zet809** [comment]
Hi, @whowutwut , I had marked sprint1 label to #3295 and #3339 that will be included in this sprint. I think these 2 tasks need to be delivered in 2.13.7 release.

**Comment by whowutwut** [comment]
One thing that I noticed is that we probably want to more clearly define the externals so that the output is consistent across the commands to the BMC.  I think some of this output is legacy and what we do with IPMI....  

Example: 
```
node-70e28414280d: [openbmc_debug] rspconfig_dhcp_response 200 OK
node-70e28414280d BMC: Setting IP to DHCP...
node-70e28414280d BMC: reboot
```

With my last PR for Hostname, it looks like this: 
```
[root@briggs01 mid05tor12cn05]# rspconfig node-70e28414280d hostname=abc123
node-70e28414280d: Setting BMC Hostname (requires bmcreboot to take effect)...
node-70e28414280d: BMC Hostname: abc123
```

I'm going to update the PR to make the output consistent.

**Comment by zet809** [comment]
Close this Epic, the extra function snmp/alart/useradd/... is traced with xcat2/xcat-task-management#23
