### ISSUE TITLE
[openbmc] rvitals support

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2816]
The vitals information for OpenBMC-Rest is provided by various Sensor objects. 
**API:**  [xyz/openbmc_project/Sensors](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Sensor)

The intent is to keep as much of the externals the same as existing machines...

**Comment by gurevichmark** [comment]
Taking openbmc `rvitals` command to work on.

**Comment by whowutwut** [comment]
With the above pull requests, I think we can close out this initial support task and open issues as we find problems or changes in the openbmc framework.
