### ISSUE TITLE
[openbmc]rflash support

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2818]
The API for Software Updating is here: 

https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

### IPMI based for reference.
```
   OpenPOWER BMC specific:
       rflash noderange hpm_file_path [-c|--check] [--retry=count] [-V]
```

### OpenBMC Based 
```
   OpenPOWER BMC specific:
       rflash noderange pnor_file_path [-c|--check] [-V]
```

For OpenBMC, we want to be able to cover the following
* Flash PNOR 
* Flash OpenBMC OS
* Provide status of the flash process 

_See updated externals below_

**Comment by whowutwut** [comment]
@gurevichmark  Updated some of the description in the first one.  It seems like there is methods defined for providing Activation Status.  Maybe we need to consider a new external that would indicate various status of the node.  

### Power Status 
rpower <node> state 
node1: on

### BMC Status 
rpower <node> bmcstate 
node1:  Ready | Activating | Failed

**Comment by gurevichmark** [comment]
After a design discussion with @whowutwut, the plan is to provide the following externals for the OpenBMC `rflash` command:

#### Priority 1: 
* `rflash <node> -c|--check` => display current version of BMC OS and host firmware
* `rflash <node> <file>`        => upload and activate BMC OS or host firmware files

#### Priority 2:
* `rflash <node> -l|--list`        => list all uploaded files with their ids

#### Priority 3:
* `rflash <node> <id> -d|--delete`  => delete previously uploaded file with specified `id`
* `rflash <node> <id>`  => activate previously uploaded file with specified `id`

#### Priority 4:
* `rflash <node> <file> -u|--upload`        => upload BMC OS or host firmware files, do not activate

**Comment by gurevichmark** [comment]
Update from a "Sametime" conversation with Uma:
```
Looks like we have 3 images
1. pnor
2. bmc
3. pnor and bmc combined 

pnor by 6/14
bmc and combined images by 7/5
```
All 3 images will be in `.tar` format.
Each `.tar` will contain `.txt` file with version info.

**Comment by whowutwut** [comment]
@gurevichmark  I converted this to an epic since you have a few priority items, we can create issues for each one and easily track that progress.

**Comment by gurevichmark** [comment]
Slack conversation on "openbmc" channel (10:58AM) with Adriana and Patrick Williams:

* 3 possible "Purpose" values - BMC, Host and System. System is combined BMC+Host
* Each of the 3 types of the `.tar` files can be uploaded using the same REST `https://<BMC IP>/upload/image/`
* The update file activation is done by changing the `RequestedActivation` attribute. No additional action is needed after changing that attribute. No need for another REST call or reboot.
* To "deactivate" an update file that was previously activated, you’d change the RedundancyPriority value to 0 to the one you want active next . if it hasn’t been activated previously, you’d set RequestedActivation to the desired one

**Comment by zet809** [comment]
hi, @gurevichmark , some questions for the items above:
1. What are the "Purpose" values for?
2. You had mentioned "deactivate" an update file, do you think we shall add an option for rflash in  https://github.com/xcat2/xcat-core/issues/3167
3. What is the purpose of more than one active image?

**Comment by gurevichmark** [comment]
@zet809 
1. The list of firmware updates on the BMC and firmware update `.tar` files will have a "purpose" indicator to show what type of update it is. You can have an update for just BMC side, just Compute side and combined for both. Before, for Firestone and Minsky machines we only had `.hpm` updates which were for both. Now with OpenBMC it looks like we can update BMC side and Compute side separately.
2. It seems like with OpenBMC we will be able to upload multiple firmware update files and then later choose which one of them to "activate" - another words which one to use for the actual update action. The "deactivate" process is to choose a different update file and "turn off" currently active update file. I am not quite sure what you mean by your question if we should add this to #3167 ? Do you expect `rflash` to be used during e2e process for cluster setup ?
3. I think the way it is supposed to work under the current design is this: You upload a `.tar` file and activate it, that is basically a "firmware update" action. That update becomes "active". Later you upload another `.tar` file and activate it. The first update file still stays active, but with a higher RedundancyPriority value. It seems that in this thinking "active" really means "available for use" and RedundancyPriority value of 0 means "currently active"

**Comment by gurevichmark** [comment]
Uploaded file activation:
```
1. User uploads file abc, abc version is in Ready state, no Priority property exists
2. User sets RequestedActivation to Active, activation takes place, abc is in Active state and a Priority property with value 0 is set
3. User uploads file xyz and requests to be Active
4. Both abc and xyz are set Active, but xyz Priority is 0 and abc is 1
5. User sets abc priority to 0, this automatically bumps xyz priority value to 1, and abc is activated
```

Example of REST call to trigger activation:

list all available versions and their properties:
```$ curl -b cjar -k https://w37/xyz/openbmc_project/software/enumerate
{
  "data": {
    "/xyz/openbmc_project/software/409b4fc9": {
      "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active", 
      "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC", 
      "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None", 
      "Version": "v1.99.6-29-ga956295-dirty"
    }
  }, 
  "message": "200 OK", 
  "status": "ok"
```

query a specific property
```$ curl -b cjar -khttps://w37/xyz/openbmc_project/software/409b4fc9/attr/RequestedActivation
{
  "data": "xyz.openbmc_project.Software.Activation.RequestedActivations.None", 
  "message": "200 OK", 
  "status": "ok"
}
```

set a property
```curl -b cjar -k-H "Content-Type: application/json" -X PUT -d '{"data": "xyz.openbmc_project.Software.Activation.RequestedActivations.Active"}' https://w37/xyz/openbmc_project/software/409b4fc9/attr/RequestedActivation
{
  "data": null, 
  "message": "200 OK", 
  "status": "ok"
}
```

check it changed
```curl -b cjar -khttps://w37/xyz/openbmc_project/software/409b4fc9/attr/RequestedActivation
{
  "data": "xyz.openbmc_project.Software.Activation.RequestedActivations.Active", 
  "message": "200 OK", 
  "status": "ok"
}```

**Comment by zet809** [comment]
hi, @gurevichmark , thx for your information, I give the wrong issue number, it shall be #3158

**Comment by zet809** [comment]
Trace task #3671 in xcat2/xcat2-task-management#23. So, close this EPIC.
