### ISSUE TITLE
[New xCAT prototype]python cli client

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2819]
(1) Add project info like version, dependency, requirement, common utils, rest api library
(2)Add command for xcat python prototype
node craate <noderange>: support simple <noderange> definition
node list [<noderange>]: list all the nodes, like lsdef
node show <noderange>: show the detail of nodes
node delete <noderange>: delete nodes
node update <noderange> [<attrs=>,]
node import <file>
node export <noderange> -o <file>

**Comment by chenglch** [comment]
Below are the links about the prototype
 
Client repo and command line usage: https://github.com/chenglch/python-xcat3client
Daemon repo, includes setup steps and performance result:  https://github.com/chenglch/xcat3

**Comment by immarvin** [comment]
hi @chenglch ，in the CLI specification in  https://github.com/chenglch/python-xcat3client
····
usage: xcat3 [--version] [--debug] [--json] [-v] [--xcat3-url XCAT3_URL]
           [--max-retries MAX_RETRIES] [--retry-interval RETRY_INTERVAL]
           <subcommand> ...

Command-line interface to xCAT3 API.

Positional arguments:
<subcommand>
  create              Enroll node(s) into xCAT3 service
  delete              Unregister node(s) from the xCAT3 service.
  export              Export node(s) information as a specific json data
                      file
  get-boot-device     Get next boot device of nodes.
  get-power           Get power state of nodes.
  import              Import node(s) information from json data file
  list                List the node(s) which are registered with the xCAT3
                      service.
  set-boot-device     Set next boot device net or disk or cdrom.
  set-power           Power nodes on or off or reboot.
  set-provision       Deployment service for nodes (not complete).
  show                Show detailed information about node(s).
  update              Update information about registered node(s).
  network-create      Register network into xCAT3 service.
  network-delete      Unregister network from xCAT3 service.
  network-list        List the network(s) which are registered with the
                      xCAT3 service.
  network-show        Show detailed information about network.
  network-update      Update information about registered network(s).
  nic-create          Register nic into xCAT3 service.
  nic-delete          Unregister nic from xCAT3 service.
  nic-list            List the nic(s) which are registered with the xCAT3
                      service.
  nic-show            Show detailed infomation about nic.
  nic-update          Update information about registered nic(s).
  osimage-delete      Unregister osimage from xCAT3 service.
  osimage-list        List the osimage(s) which are registered with the
                      xCAT3 service.
  osimage-show        Show detailed information about osimage.
  osimage-update      Update information about registered osimage.
····

I suggest to classify the operations into different category of objects, such as compute, network, image, etc. The CLI can be:
````
xcat3 <object> <subcommand> <options> <arguments>
````

**Comment by chenglch** [comment]
@immarvin , thanks for your advice,  `openstack cli`, `docker network` and `docker swarm` are the format like your said. Docker or now we should call it Moby also support some legacy format subcommand like `rmi`, `port` etc, I think this depends on the situation. Currently, I will focus on some performance issue, function library or plugin support for this prototype.
