### ISSUE TITLE
Openpower supports bmcsetup chain

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#282]
Update ProfiledNodeUtils. Importing openpower node will add bmcsetup command  in node chain.

**Comment by fenggaobj** [comment]
upload the code in git https://github.com/xcat2/xcat-core/commit/b6b1155f41fabc19c75ffaa73742845487c59300

**Comment by zet809** [comment]
The code for this issue is also put in pull request 284. I have merged them.
