### ISSUE TITLE
[Test case]Refine test case: nodeset_cmdline, nodeset_runimage, nodeset_shell 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2833]
Acceptance :
1 Fix issue #2442 
2 Fix issue #1871 
3 make code clearly for anyone to debug.

**Comment by zet809** [comment]
Duplicated with #3266. So, close this one.

**Comment by hu-weihua** [comment]
@zet809 , This is a task, #3266 is a pull request for this task. this is not duplicate. I will reopen it.
