### ISSUE TITLE
Create the acceptable release criteria

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2836]
1. The items need to test for a release
2. The criteria to accept the items

**Comment by hu-weihua** [comment]
@tingtli , could you paste the link of our release accptable criteria here? thanks

**Comment by tingtli** [comment]
This is the link for this task
https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/End of cycle regression process and release criteria

**Comment by whowutwut** [comment]
@tingtli That URL is malformed..
