### ISSUE TITLE
[FVT]setup automation development environment

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2837]
Acceptance:

*  A similar environment with our current automation test environment.
   * A node as Jenkins web server
   * A node as control node
   * clusters(3 nodes) for each Arch(ppc64, x86_64, ppc64le)

* Offer a document in xcat-progress repo : A step by step to set up new automation environment 
    * include hardware requirement 
    * Include all tricks we used.  
    * include the step of how to add a new cluster in to exist environment.

* modify test.sh to support below things:
    * Add command line option "XCATCORE" AND "XCATDEP". if set these 2 option in command line, pass this 2 value to ``xcatjktest``, if not, calculate in the ``test.sh``, using the latest build.
    * Add command line option "MAILLIST". if set this option in command line, pass this value to ``xcatjktest`` by ``--email`` option, if not, trigger ``xcatjktest`` without ``--email`` option.
     * To avoid mount GPFS log on new automation environment. 
     * Add command line option "SQL", if set the value in command line, pass this value to ``xcatjktest`` by option ``--database``.

[DEADLINE] : May 4

**Comment by neo954** [comment]
Get the installation document here.
[1] https://github.ibm.com/gongjie/jenkins/blob/devel/INSTALL.md

**Comment by neo954** [comment]
The installation document.
https://github.ibm.com/xcat2/jenkins/pull/105

**Comment by neo954** [comment]
All the changes against `test.sh`
https://github.ibm.com/xcat2/jenkins/pull/106
