### ISSUE TITLE
[FVT]Provide a rule to write test cases

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2839]

**Comment by hu-weihua** [comment]
After discussing with @tingtli , draft a doc https://ibm.ent.box.com/notes/157310034970 to describe the rule of how to write a case. any comment are welcome. @neo954 , @junxiawang, @zet809, @daniceexi

**Comment by hu-weihua** [comment]
Also draft a doc https://ibm.ent.box.com/notes/157308394334 to offer a template for how to pull a test case request.

**Comment by daniceexi** [comment]
@hu-weihua I am good with the template, please encourage people to use it.

**Comment by hu-weihua** [comment]
In github:
The rule of how to write a case is https://github.com/xcat2/xcat-process/blob/master/basic-process/The%20Rule%20of%20Writing%20Test%20Case.rst

The template for how to pull a test case request is https://github.com/xcat2/xcat-process/blob/master/basic-process/The%20Template%20of%20Pull%20Request%20of%20Test%20Case.rst
