### ISSUE TITLE
[FVT]The document to debug issue within automation environment

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2840]
Acceptance:
A step by step to debug issue

**Comment by hu-weihua** [comment]
Draft a doc https://ibm.ent.box.com/file/160014293758  on box to describe how to debug issue within automation environment.  Any comment are welcome. @zet809 @robin2008 @daniceexi

**Comment by daniceexi** [comment]
@hu-weihua as we discussed that we could make this available in github, and then put all the links in a doc for team members to refer.

**Comment by hu-weihua** [comment]
The doc in github is https://github.com/xcat2/xcat-process/blob/master/basic-process/The%20Steps%20of%20Debugging%20in%20Automation%20Environment.rst
