### ISSUE TITLE
xcat updatenode issue!!!!!

### ISSUE THREAD

**Issue by TRF123** [xcat2/xcat-core#2845]
I have a vagrant environment which contains a master node and one slave, when I want to update the node using xcat (updatenode mynode -s) it gives me the following error : 
Error: mynode is not responding. No command will be issued to this host.

this is the definition of my node : 
[root@master ~]# lsdef os_gold
Object name: mynode 
    groups=compute,all
    ip=10.0.0.20
    mgt=kvm
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    updatestatus=failed
    updatestatustime=04-08-2017 20:06:44
    vmhost=10.0.0.1
    xcatmaster=10.0.0.10

could anyone help me to solve this issue please !!

**Comment by whowutwut** [comment]
Hi @TRF123  Are you able to ping the compute node?  `ping 10.0.0.20`
What is the response of `nodestat mynode`   If xCAT cannot ping to the compute side, or ssh to the compute side, it won't be able to run the postscripts....

**Comment by TRF123** [comment]
[root@master ~]# nodestat mynode
mynode: noping

my node is created by vagrant and I want to clone its OS and deploy it to another VM , I tried to make the clone for 2 weeks but it did not work for me because the postscrpits are not able to run, what is your advice?  I really need help I will miss the deadline.
NOTE: I followed this link for cloning : http://xcat-docs.readthedocs.io/en/stable/advanced/sysclone/sysclone.html

**Comment by immarvin** [comment]
hi @TRF123 , is mynode up and running? can you ping it with ``ping mynode `` from the management node?

**Comment by TRF123** [comment]
Yes it is up and running and I can ping it .

Sent from my iPhone

On Apr 10, 2017, at 6:17 AM, yangsong <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @TRF123<https://github.com/TRF123> , is mynode up and running? can you ping it with ping mynode from the management node?

**Comment by immarvin** [comment]
hi @TRF123 ,please provide the output of the following command:
````
updatenode mynode -s -V
````

**Comment by TRF123** [comment]
[root@master vagrant]# updatenode mynode  -s -V
Running command on master.cluster.com: /bin/hostname 2>&1

Running command on master.cluster.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on master.cluster.com: /bin/hostname 2>&1

Running command on master.cluster.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on master.cluster.com: chmod -R a+r /install/postscripts 2>&1

  master.cluster.com: Internal call command: xdsh os_gold --nodestatus -s -v -e /install/postscripts/xcatdsklspost 1 -M 10.0.0.10 'setuppostbootscripts' --tftp /tftpboot --installdir /install --nfsv4 no -c -V
Running command on master.cluster.com: /bin/hostname 2>&1
Running command on master.cluster.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1
Running command on master.cluster.com: hostname 2>&1
Running command on master.cluster.com: /opt/xcat/bin/pping mynode 2>&1
Error: mynode is not responding. No command will be issued to this host.

**Comment by TRF123** [comment]
I have errors in every single command in xcat for example: updatenode, nodeset and genimage.
the only thing that works for me in xcat is making a definition for a node, my master is created by vagrant and it works well but all my problems with the communication between the master and the slaves, I am a beginner  in xcat and I think all my problems because I am not adding my slaves correctly and I don not know how to do that.I am doing my senior project on xcat please help me.

**Comment by whowutwut** [comment]
can you ssh to `mynode` and send us the following:  `ip link show` 
From `mynode` can you ping the xCAT master, ping 10.0.0.10? 

Can you also show us the output of `tabdump networks` 

Can you verify that xCAT can run remote keys on this node? 
1. xdsh mynode uptime

If not , can you send the ssh keys over so that xdsh works...  `updatenode mynode -K` and then rerun the command xdsh to verify that remote commands works on this compute node.

**Comment by whowutwut** [comment]
no response for this, i think @TRF123  is working on other machines, so closing out .. feel free to re-open.
