### ISSUE TITLE
nodeset issue

### ISSUE THREAD

**Issue by TRF123** [xcat2/xcat-core#2846]
I want to create a vm by using xcat and KVM hypervisor with ubuntu OS I have the folllowing error when I run the nodeset command 
[root@master vagrant]# nodeset mynode osimage=ubuntu16.04.1-x86_64-netboot-compute
Error: Did you run "genimage" before running "packimage"? kernel cannot be found
Error: Some nodes failed to set up netboot resources on server master.cluster.com, aborting 

could anyone help me !!!!

**Comment by immarvin** [comment]
"ubuntu16.04.1-x86_64-netboot-compute" is a diskless osimage, just as the message mentioned, you need to run "genimage ubuntu16.04.1-x86_64-netboot-compute" and "packimage ubuntu16.04.1-x86_64-netboot-compute" before ``nodeset``

**Comment by TRF123** [comment]
I tried to make genimage but I have this error : 

[root@master vagrant]# genimage ubuntu16.04.1-x86_64-netboot-compute
Generating image: 
cd /opt/xcat/share/xcat/netboot/ubuntu; ./genimage -a x86_64 -o ubuntu16.04.1 -p compute --srcdir "/install/ubuntu16.04.1/x86_64" --pkglist /opt/xcat/share/xcat/netboot/ubuntu/compute.ubuntu16.04.1.pkglist --otherpkgdir "/install/post/otherpkgs/ubuntu16.04.1/x86_64" --postinstall /opt/xcat/share/xcat/netboot/ubuntu/compute.postinstall --rootimgdir /install/netboot/ubuntu16.04.1/x86_64/compute --tempfile /tmp/xcat_genimage.3050 ubuntu16.04.1-x86_64-netboot-compute
Run cmd [debootstrap --verbose  --arch amd64 xenial /install/netboot/ubuntu16.04.1/x86_64/compute/rootimg http://archive.ubuntu.com/ubuntu/] to create rootimage bootstraps
Error: cannnot create bootstraps for rootimage. Make sure you specified full http mirror path.
Error: Command failed: cd /opt/xcat/share/xcat/netboot/ubuntu; ./genimage -a x86_64 -o ubuntu16.04.1 -p compute --srcdir "/install/ubuntu16.04.1/x86_64" --pkglist /opt/xcat/share/xcat/netboot/ubuntu/compute.ubuntu16.04.1.pkglist --otherpkgdir "/install/post/otherpkgs/ubuntu16.04.1/x86_64" --postinstall /opt/xcat/share/xcat/netboot/ubuntu/compute.postinstall --rootimgdir /install/netboot/ubuntu16.04.1/x86_64/compute --tempfile /tmp/xcat_genimage.3050 ubuntu16.04.1-x86_64-netboot-compute 2>&1. Error message: Run cmd [debootstrap --verbose  --arch amd64 xenial /install/netboot/ubuntu16.04.1/x86_64/compute/rootimg http://archive.ubuntu.com/ubuntu/] to create rootimage bootstraps
Error: cannnot create bootstraps for rootimage. Make sure you specified full http mirror path.

I do not know what is wrong!!!!

**Comment by whowutwut** [comment]
@TRF123  What is the OS on your management node,  `root@master`  can you run: 
`uname -a` 
and `cat /etc/*release*` 

diskless `netboot` images need to be created on a node that has the same OS and architecture as the osimage you plan to deploy.  Are you running this on a Mac?

**Comment by TRF123** [comment]
the OS in the MN is centos 6.8 . this is the output of uname:
[root@master vagrant]# uname -a
Linux master.cluster.com 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

no, I am not using MAC I use UBUNTU16 in my localhost and centos in my master node that is created by vagrant.

**Comment by whowutwut** [comment]
Ok, so the reason you cannot run the `genimage` is because the MGMT node is CENTOS (based on RPM package manager) and Ubuntu is using the apt pkg manager.... the management node needs to be able to run apt to generates the diskless image to boot into memory.  

Is that what you want? To run the compute node diskless... the OS installed into RAMDISK? Or are you trying to load a diskful OS, OS installed onto disk.  If diskful, you can launch the install from mixed OS environment, choose the osimage with `install-compute` instead of `netboot-compute`  ==> `ubuntu16.04.1-x86_64-install-compute`

**Comment by TRF123** [comment]
1-do you mean I should change the OS of my MN to ubuntu ?
2- I want to make diskful OS node with UBUNTU, what are the steps should I follow to create the VM ! since I am a beginner at XCAT.

**Comment by immarvin** [comment]
hi @TRF123 , for Q#1, if you just want to make diskful ubuntu node, you do not need to change the MN OS to ubuntu, just as @whowutwut  suggested, you should use "nodest xxx osimage=ubuntu16.04.1-x86_64-install-compute" instead of "ubuntu16.04.1-x86_64-netboot-compute"(the "netboot" osimage is for diskless node, on which the root file system resides in the memory).

For Q#2,  please follow the following Documents:
 http://xcat-docs.readthedocs.io/en/stable/guides/admin-http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/index.html

**Comment by TRF123** [comment]
I tried to make the diskfull installation and it gives me the following error:
[root@master x86_64]# nodeset mnt osimage=ubuntu16.04.1-x86_64-install-compute
Error: Install image not found in /install/ubuntu16.04.1/x86_64
Error: Some nodes failed to set up install resources on server master.cluster.com, aborting

what does this error mean !!!
this is  the definition of my node : 
[root@master x86_64]# lsdef mnt
Object name: mnt
    arch=x86_64
    groups=compute,all
    ip=10.0.0.50
    mac=42:d3:0a:00:00:32
    mgt=kvm
    netboot=xnba
    os=ubuntu16.04.1
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=install
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=04-10-2017 09:56:07
    vmcpus=2
    vmhost=10.0.0.1
    vmmemory=1024
    vmnicnicmodel=virtio
    vmnics=br0
    vmstorage=dir:///var/lib/libvirt/images

**Comment by TRF123** [comment]
I solved the error of the nodeset and it works properly now thank you all, 
my question is when I run the node after the nodeset(rpower mnt on) it says : no bootable device.
what is the next step after the nodeset in the diskfull installation ? how can I run the node with the OS ?

this is the definition of the node:
[root@master tmp]# lsdef mnt
Object name: mnt
    arch=x86_64
    currchain=boot
    currstate=install centos7.3-x86_64-compute
    groups=compute,all
    ip=10.0.0.50
    mac=42:d3:0a:00:00:32
    mgt=kvm
    netboot=xnba
    os=centos7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos7.3-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=04-11-2017 13:03:51
    vmcpus=2
    vmhost=10.0.0.1
    vmmemory=1024
    vmnicnicmodel=virtio
    vmnics=br0
    vmstorage=dir:///var/lib/libvirt/images

**Comment by gurevichmark** [comment]
Did you run `mkvm mnt -s <disk size>`  before power on ?

Also, not sure if it will fix this problem, but `vmmemory` of 1G seems a bit low. Try setting it to to 4096. Make sure to run `mkvm` after that change.

**Comment by whowutwut** [comment]
Since nodeset is solved, closing this issue

**Comment by mherreral** [comment]
@TRF123 How did you solve the nodeset problem?
