### ISSUE TITLE
xcat fails to program gateway on rhel.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2851]
We are trying to get xcat to provision a node that will subsequently be able to boot and work if the xcat management node is no on line.

we have the following configuration:
```
[root@c460mgt01 ralphbel]# lsdef c460mgt02 -i nichostnamesuffixes,nicips,nicnetworks,nictypes
Object name: c460mgt02
    nichostnamesuffixes.enP1p12s0f2:=-enP1p12s0f2
    nichostnamesuffixes.ib0=-ib0
    nichostnamesuffixes.enP1p12s0f1:=-enP1p12s0f1
    nichostnamesuffixes.enP1p12s0f3:=-enP1p12s0f3
    nichostnamesuffixes.enP1p12s0f0:=-enP1p12s0f0
    nicips.enP1p12s0f1=10.3.0.2
    nicips.ib0=10.10.0.2
    nicips.enP1p12s0f3=129.40.234.4
    nicnetworks.enP1p12s0f1=DRBD
    nicnetworks.ib0=IB00
    nicnetworks.enP1p12s0f0=OS
    nicnetworks.enP1p12s0f3=pub_yellow
    nictypes.enP1p12s0f1=Ethernet
    nictypes.ib0=Infiniband
    nictypes.enP1p12s0f2=Ethernet
    nictypes.enP1p12s0f0=Ethernet
    nictypes.enP1p12s0f3=Ethernet
```

with the following information network information.
```
[root@c460mgt01 ralphbel]# lsdef -t network pub_yellow
Object name: pub_yellow
    gateway=129.40.234.30
    mask=255.255.255.224
    mgtifname=enP1p12s0f0
    net=129.40.234.1
```

However when we run updatenode on this node, we get the following in the ethernet configuration file:
```
[root@c460mgt02 network-scripts]# cat ifcfg-enP1p12s0f3
DEVICE=enP1p12s0f3
BOOTPROTO=static
NM_CONTROLLED=no
IPADDR=129.40.234.9
NETMASK=255.255.255.224
ONBOOT=yes
```

Normally we would correct this with the routenames and setroute, however, that depends on a postboot script being run and that won't run unless there is an xcat management node to pull the postboot script from.

I noticed that the gateway only makes its way into the configuration program in configeth for ip6 in configeth line 1009:

```
            if [ `echo $str_ip | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$'` ];then
                configipv4 $str_nic_name $str_ip $str_subnet $str_netmask $num_ipv4_index "$str_extra_params" $str_mtu
                num_ipv4_index=$((num_ipv4_index+1))
            elif [ `echo $str_ip | grep -E ":"` ];then
                configipv6 $str_nic_name $str_ip $str_subnet $str_netmask $num_ipv6_index $num_ipv4_index $str_gateway "$str_extra_params"
                num_ipv6_index=$((num_ipv6_index+1))
            else
                num_index=$((num_index+1))
                continue
            fi
            num_index=$((num_index+1))
```

Seems the gateway parameter is ignored for ipv4...

**Comment by zet809** [comment]
Hi, @bybai , will you pls help to take a look at this issue? Thx!

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
Is the network pub_yellow  the installnic network ?

confignics can configure installnic gateway if we call `confignics -s`;
confignics ignore ipv4 gateway if we call `confignics` to configure secondary adapters, if you are in this scenario, the code will be added the support later.

**Comment by ralphbellofatto** [comment]
pub_yellow is a public network, the install network is enP1p12s0f0

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
Since xCAT has makeroutes command and setroute script to configure route . So currently, confignics ignore ipv4 gateway.  I will move this issue into backlog and lower the priority, if you have more questions, please give your comments, thanks. 
The examples for makeroutes:
```
1, confgure routes table:
]# tabdump routes
#routename,net,mask,gateway,ifname,comments,disable
"10net","10.0.0.0","255.0.0.0","10.0.0.103","eth1",,

2, configure 10net route on MN:
chdef -t site mnroutenames=10net 
makeroutes

3, add 10net route on node1: makeroutes node1
  
4, add 10net on MN route table: makeroutes -r 10net

5, To add route 10net to the os route table on node1:  
makeroutes node1 -d -r 10net
```
The setroute script usage:
```
1, configure routes table:
]# tabdump routes
#routename,net,mask,gateway,ifname,comments,disable
"10net","10.0.0.0","255.0.0.0","10.0.0.103","eth1",,
2, setroute [replace|add]
```

**Comment by bybai** [comment]
Hi @ralphbellofatto ,  I do not know your recent progress, do you try to use makeroutes or setroute for your work?  I do not know if makeroutes or setroute is enough to your work?

**Comment by ralphbellofatto** [comment]
I have not had a chance to try this yet.

**Comment by zet809** [comment]
Move the next release.

**Comment by bybai** [comment]
@ralphbellofatto , since xcat recommend `makeroutes` or `setroute` to configure route, `confignetwork` will not add set route feature. So I will close this issue, can reopen it if needed in the future.

**Comment by thilo-maurer** [comment]
I have the same issue. I find it awkward to have define the same routes twice: The first time via `gateway` entries in networks objects, and the second time using additional routes in table `routes`. 

IMHO then first once should suffice, the second way be used to define additional routes.

@ralphbellofatto How did you solve this issue?

**Comment by whowutwut** [comment]
@bybai Can you provide some help here ☝️

**Comment by thilomaurer** [comment]
@bybai Now using `postscripts="confignetwork,setroute add"` as suggested. No further help needed.
