### ISSUE TITLE
xcat diskfull installation issue 

### ISSUE THREAD

**Issue by TRF123** [xcat2/xcat-core#2853]
I am trying to make a diskfull installation of nodes in the following environment:
1- Master node created by vagrant where xcat installed with centos OS .
2- Localhost with Ubuntu16.
3- KVM hypervisor in the localhost.
the problem is when I power the node ON the node says : no bootable device.
all the commands I have used  are working probably and no errors were shown, it seems that the node could not load the OS iso from the master node which is created by vagrant, what configurations required to the node in order to let the node boot from the iso installed in the master node hard disk.

**Comment by whowutwut** [comment]
Hi @TRF123  This is not a normal environment that we configure in our teams, but if you want to launch KVM nodes, you can follow xCAT's documentataion here: http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/index.html You need to first create a hypervisor node, and then your VMs need to point to that host machine. 

If it no bootable device, does it find a hard disk? 
The compute node needs to be configured to network boot off the management node.

**Comment by TRF123** [comment]
1-what do you mean of a normal environment? I think if this work on real environment it should work on a virtual one.
2- what are the configurations required of the diskfull installation in the real environment so that I can apply the same on my scenario.
3- what do you suggest in my case : diskfull or disless installation?.
4- how can I know if the vm is finding a hard disk?.

thank you .

**Comment by whowutwut** [comment]
1) I mean , we don't use vagrant to create VMs, we have been focusing support on KVM-based hypervisor provided by RHEL and IBM PowerKVM.  (Going to RHEV)  And we normally use xCAT to provision a hypervisor host , that contains libvirt, then use xCAT to create VMs.  xCAT provides the lifecycle management for that.  you're right, there's different ways to build VMs, but we have not focused on this specific scenario. 

2) Diskful installation just requires a hard drive. The node is set to network boot and the server that it points to is the xCAT management machine.    Can you describe the hardware you are running on?   Are you running on a desktop Ubuntu? Is that your localhost?   1 machine simulating more with VMs? 

3) diskful is easier especially if you are in a mix OS/ ARCH environment. 

4) If it says no bootable device, did you provide a backing file for the VM hard drive?  For KVM based VMs, you can do `virsh dumpxml <vm>` and take a look to see if there's a storage file associated with the VM.

**Comment by whowutwut** [comment]
@TRF123  I caught up with issue #2846 and I think that might have been the problem, if you are using xCAT to create the VM, you should provide a `-S <size>` and xCAT will create a disk...  

I would recommend you use the dir option for `vmstorage` 

`chdef vm1 vmstorage=dir:///var/lib/libvirt/images`

Then xCAT will create the disk under the hypervisor /var/lib/libvirt/images. 

If you are new to linux, the hypervisor host must have bridges configured.. `brctl show` if not, it won't be able to virualize the network devie o the VM.  That could also be why there's no bootable source...

**Comment by TRF123** [comment]
I think my problem is with the network, I do not have a bridge between the master node and KVM, could you please help me how to configure the network between KVM and the master node which have centos os !!! 

thank you ...

**Comment by TRF123** [comment]
I stored the iso of the OS which I want to deploy to the compute node in the /tmp file of the MN, after that I made a copycds and it works fine, when I power ON the node it stills say "NO bootable device cannot find directory : http:ipxe.org/2412603b" and I am using a diskfull installation, is the copycds command enough to install the iso on the compute node or should I make extra steps that transfers the ISO to the node ! these are my definitions : 

**The definition of the image:**
[root@master ~]# lsdef -t osimage centos7.3-x86_64-install-compute
Object name: centos7.3-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.3-x86_64
    osname=Linux
    osvers=centos7.3
    otherpkgdir=/install/post/otherpkgs/centos7.3/x86_64
    pkgdir=/install/centos7.3/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.centos7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.centos7.tmpl


**The definition of my compute node :** 
[root@master ~]# lsdef os_test
Object name: os_test
    arch=x86_64
    currchain=boot
    currstate=install centos7.3-x86_64-compute
    groups=vm,all
    ip=10.0.0.60
    mac=42:51:85:f3:9d:d8
    mgt=kvm
    netboot=xnba
    os=centos7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos7.3-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=04-12-2017 19:43:01
    updatestatus=failed
    updatestatustime=04-12-2017 19:47:57
    vmhost=10.0.0.1
    vmnicnicmodel=virtio
    vmnics=virbr1
    vmstorage=dir:///var/lib/libvirt/images

**Comment by whowutwut** [comment]
@TRF123  some simple search will give you better documentation about how to configuration network bridges..  "configure network bridges" (example: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-networkscripts-interfaces_network-bridge.html) 

`brctl show` needs to come back with something other than virbr0.  virbr0 is the default bridge created by libvirt on the loopback. so if your VM doesn't need network connectivity, you can use that.  

Once you create a bridge on the OS, the `vmnics=` should point to the bridge, for example, `vmnics=br0`

**Comment by whowutwut** [comment]
Regarding your comment above, please also show us `ls- ltr /var/lib/libvirt/images` on the hypervisor.. if the VM does not have a file there, then it does not have any virtual "hard disk" , refer to the other issue you 
 opened for steps on creating the VM with a backing storage.  #2846

**Comment by TRF123** [comment]
-rw------- 1 libvirt-qemu kvm       197120 Apr 12 22:38 os_test.sda.qcow2

I found the vm storage in my hypervisor host, but put in your mind that I am using the master node from vagrant which is not the hypervisor host so, how can I point to the storage file that is outside my MN!!!

**Comment by TRF123** [comment]
I got this message when I tried to boot the node with OS 
There is 1 node provision failures
os_test : stop at stage 'download_kernel'   

what is the reason of this problem ?

**Comment by whowutwut** [comment]
The hypervisor host needs to be defined in xCAT and xCAT needs to be able to communicate with it using libvirt..   the vmhost attribute for the node will point to the host.  Like I said, we don't run this particular environment, and currently do not have cycles to replicate it, so i'm not sure how we assist more but to give you some hints.

**Comment by TRF123** [comment]
I am having a great progress, the compute node starts downloading the iso but suddenly it stops the installation at "Anaconda network manager" and does not continue to finish the installation. could anyone help me why this happens ?  

NOTE: I am using centos7 in the compute node.

**Comment by zet809** [comment]
Hi, @TRF123 , how is issue going?

**Comment by TRF123** [comment]
The issue is solved , thank you .

Sent from my iPhone

On Jun 5, 2017, at 7:59 AM, zet809 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @TRF123<https://github.com/trf123> , how is issue going?
