### ISSUE TITLE
[ xCAT 2.13.2 Centos 7.3 ] Install and configure MySQL for xCAT

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2854]
I'm facing issue while executing `lsxcatd -a` and other xCAT commands after migration. I think its problem with configuration of database. I'm at initial level to setup HA.

    [root@xcat2 ~]# lsxcatd -a
    Error: Permission denied for request

I did migration from `sqlite` to `mysql` using `mysqlsetup -i`:

    [root@xcat2 ~]# mysqlsetup -i
    Input the alpha-numberic  password for xcatadmin in the MySQL database:
    Input the password for root in the MySQL database:
    Command failed: chkconfig mysql on 2>&1. Error message: Note: Forwarding request to 'systemctl enable mysql.service'.
    Failed to execute operation: Too many levels of symbolic links.
    chkconfig mysql on failed. MySQL will not restart on reboot.
    Backing up xCAT Database to /root/xcat-dbback.
    This could take several minutes.
    Shutting down the xcatd daemon during database migration.
    Stopping xcatd (via systemctl):                            [  OK  ]
    Restoring the xCAT Database with /root/xcat-dbback to MySQL database.
    This could take several minutes.
    Restarting xcatd (via systemctl):                          [  OK  ]
    xCAT is now running on the MySQL database.

And in database:

    mysql>SELECT host, user FROM mysql.user;
    +------------+-----------+
    | host       | user      |
    +------------+-----------+
    | %          | xcatadmin |
    | 127.0.0.1  | root      |
    | 172.16.0.6 | xcatadmin |
    | ::1        | root      |
    | localhost  | root      |
    | localhost  | xcatadmin |
    | xcat1      | xcatadmin |
    | xcat2      | xcatadmin |
    +------------+-----------+
    8 rows in set (0.00 sec)

Is anything wrong. Please suggest me.

**Comment by immarvin** [comment]
" Error: Permission denied for request" shows that the "lsxcatd" command failed to pass the policy validation.

running xCAT commands with "XCATBYPASS=1" will bypass the policy validation, please check whether the policy table is correct with the following command:

````
XCATBYPASS=1 tabdump policy
```` 
check whether the DB engine has been switched to mysql with:
````
XCATBYPASS=1 lsxcatd -d
````

**Comment by dspatil7768** [comment]
`[root@xcat2 ~]# XCATBYPASS=1 tabdump policy`
`#priority,name,host,commands,noderange,parameters,time,rule,comments,disable`

`[root@xcat2 ~]# XCATBYPASS=1 lsxcatd -d`
`cfgloc=mysql:dbname=xcatdb;host=172.16.0.6|xcatadmin`
`dbengine=mysql`
`dbname=xcatdb`
`dbhost=172.16.0.6`
`dbadmin=xcatadmin`

So do I need to add policy to work around problem.

> To give a user all xCAT command privileges, run "tabedit policy", and add a line:
> 6,"username",,,,,,allow,,

**Comment by immarvin** [comment]
this means that you have successfully migrated to mysql, but why the policy table is empty, is it lost during your migration?

**Comment by dspatil7768** [comment]
Yes it was lost during migration. I have backup with me using ` dumpxCATdb`:

`[root@xcat2 ~]# cat /tmp/xcat/policy.csv`
`#priority,name,host,commands,noderange,parameters,time,rule,comments,disable`
`"1","root",,,,,,"allow",,`
`"1.2","xcat2.cdac.in",,,,,,"trusted",,`
`"2",,,"getbmcconfig",,,,"allow",,`
`"2.1",,,"remoteimmsetup",,,,"allow",,`
`"2.3",,,"lsxcatd",,,,"allow",,`
`"3",,,"nextdestiny",,,,"allow",,`
`"4",,,"getdestiny",,,,"allow",,`
`"4.4",,,"getpostscript",,,,"allow",,`
`"4.5",,,"getcredentials",,,,"allow",,`
`"4.6",,,"syncfiles",,,,"allow",,`
`"4.7",,,"litefile",,,,"allow",,`
`"4.8",,,"litetree",,,,"allow",,`
`"4.9",,,"getadapter",,,,"allow",,`

**Comment by immarvin** [comment]
ok, this is the root cause.  can this ticket be closed?

**Comment by dspatil7768** [comment]
Last question. Should I restore this policy?

**Comment by immarvin** [comment]
yes, policy is mandatory for running xCAT commands. you can restore the xCAT DB with ``restorexCATdb``

**Comment by dspatil7768** [comment]
Thank you !

**Comment by dspatil7768** [comment]
Even though after restoring it showing the same error. And when I did XCATBYPASS=1 no data displayed:

`[root@xcat2 ~]# XCATBYPASS=1 tabdump site`
`#key,value,comments,disable`
`"xcatdport","3001",,`

as it's showing `"xcatdport","3001",,` I entered it manually with `chdef`

I think still there is no connectivity between `xCAT` and `mysql`

But it's showing that restore is complete:

`[root@xcat2 ~]# restorexCATdb -p /tmp/xcat`
`Restore of Database Complete.`

**Comment by immarvin** [comment]
would you please check whether the the DB tables have been restored in the mysql ?
````
# mysql -uxcatadmin -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2753
Server version: 5.5.43 SUSE MySQL package

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> connect xcatdb
Connection id:    2754
Current database: xcatdb

mysql> select * from policy;
+----------+---------------+------+----------------+-----------+------------+------+---------+----------+---------+
| priority | name          | host | commands       | noderange | parameters | time | rule    | comments | disable |
+----------+---------------+------+----------------+-----------+------------+------+---------+----------+---------+
| 1        | root          | NULL | NULL           | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 1.2      | c910f02c08p15 | NULL | NULL           | NULL      | NULL       | NULL | trusted | NULL     | NULL    |
| 2        | NULL          | NULL | getbmcconfig   | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 2.1      | NULL          | NULL | remoteimmsetup | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 2.3      | NULL          | NULL | lsxcatd        | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 3        | NULL          | NULL | nextdestiny    | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4        | NULL          | NULL | getdestiny     | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.4      | NULL          | NULL | getpostscript  | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.5      | NULL          | NULL | getcredentials | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.6      | NULL          | NULL | syncfiles      | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.7      | NULL          | NULL | litefile       | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.8      | NULL          | NULL | litetree       | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
| 4.9      | NULL          | NULL | getadapter     | NULL      | NULL       | NULL | allow   | NULL     | NULL    |
+----------+---------------+------+----------------+-----------+------------+------+---------+----------+---------+
13 rows in set (0.00 sec)

mysql>
````

**Comment by dspatil7768** [comment]
There is nothing in it:

`mysql> select * from policy;`
`Empty set (0.00 sec)`

**Comment by immarvin** [comment]
how about ``XCATBYPASS=1 restorexCATdb -p /tmp/xcat``

**Comment by dspatil7768** [comment]
Great ! Worked fine. Thank you !

**Comment by whowutwut** [comment]
@dspatil7768  Was the policy lost during migration due to user error? Or something within xCAT?

**Comment by dspatil7768** [comment]
@whowutwut I also don't know the root cause behind it. What does exactly user error mean?

**Comment by whowutwut** [comment]
@dspatil7768 Was just wondering if it was caused by xCAT removing something during the upgrade process, or if you took a wrong step in the process. (forgot to save something or restore something)...  if it's caused by xCAT missing something, we should fix it.

**Comment by dspatil7768** [comment]
@whowutwut Below are the steps that I did:

- Installed xCAT 
- Configured on Virtual IP
- Deployed statefull node
- Took backup of xCAT using `dumpxCATdb -p <path to backup>`
- Migration from `sqlite` to `mysql` via `mysqlsetup -i`
- Restored backup on another node with the same configuration via `restorexCATdb`

After all these steps there was no data in MySQL.

**Comment by whowutwut** [comment]
@zet809 @hu-weihua can you look into the above? Seeems like some data is lost in the migration process of the database?

**Comment by zet809** [comment]
Hi, @whowutwut , as you know for our automation hierarchy test, we will migrate to mysql from sqlite, we won't miss any data.
Based on the defect description, it seems the mysql server is not running when backing up and restoring xcat data, that maybe the cause for the data loosing.
```
Command failed: chkconfig mysql on 2>&1. Error message: Note: Forwarding request to 'systemctl enable mysql.service'.
Failed to execute operation: Too many levels of symbolic links.
chkconfig mysql on failed. MySQL will not restart on reboot.
Backing up xCAT Database to /root/xcat-dbback.
```

**Comment by whowutwut** [comment]
@zet809 Thanks, as long as it's not something that we missed....  :-)

**Comment by dspatil7768** [comment]
When I do migration from `SQLite` to `MySQL` while MySQL is running. It shows problem below:

`[root@xcat2 xcat]# mysqlsetup -i`
`MySQL is running.  Database initialization will not take place.`
`Input the alpha-numberic  password for xcatadmin in the MySQL database:`
`Input the password for root in the MySQL database:`
`Command failed: /usr/bin/mysqladmin -u root -p123456 version 2>&1. Error message: Warning: Using a password on the command line interface can be insecure.`
`/usr/bin/mysqladmin: connect to server at 'localhost' failed`
`error: 'Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)'`
`Check that mysqld is running and that the socket: '/var/lib/mysql/mysql.sock' exists!.`
`Wrong MySQL root password.`

**Comment by immarvin** [comment]
``When I do migration from SQLite to MySQL while MySQL is running``, since the mysql is installed and running before "mysqlsetup -i",  is "123456" the  password you specified during you install mysql?

this can be made sure by running ``mysql -u root -p`` then input "123456" on prompt
