### ISSUE TITLE
[DEV] nodes provisioned with redhat osimages created by xCAT 2.12.3 or earlier missed yum repo to MN in xCAT 2.12.4 or later

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2856]
this issue is introduced in PR https://github.com/xcat2/xcat-core/pull/2050/files

**Comment by neo954** [comment]
This problem was found on a testing environment, below are the detailed steps of how to recreate this problem.

* Install xCAT 2.12.4 on a clean newly installed SLES 11.4 x86-64 machine.
* Run `copycds` against RHEL 6.9 iso.
* Update the installed xCAT 2.12.4 to 2.13.2
* Deploy a new compute node with the existing osimage definition `rhels6.9-x86_64-install-compute`
* After a successfully deployment of the compute node, ssh to the compute node, and run `yum install -y bzip2`.

The `yum install` operation on the compute node will fail, due to there is no existing yum repository for the operating system. The correct behavior of xCAT is that xCAT should put a workable yum repository configuration on the newly installed compute node.

**Comment by neo954** [comment]
I consider this problem a **block** issue of the nearing released xCAT 2.13.3. Due to even the default `osimage` created by xCAT, such as `rhels6.9-x86_64-install-compute`, is affected.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2857

**Comment by whowutwut** [comment]
I provisioned a machine and the local-repository file name seemed to have changed...

```
[root@fs3 yum.repos.d]# cat local-repository-0.repo
[local-rhels7.3-ppc64le-ppc64le]
name=xCAT configured yum repository for /install/rhels7.3/ppc64le
baseurl=http://10.2.5.3//install/rhels7.3/ppc64le
enabled=1
gpgcheck=0
```

I never recall the name is `local-repository-0.repo` why is there a -0?

**Comment by immarvin** [comment]
the fix will be available in xCAT 2.13.3 release.

If you hit this issue after migrate xCAT 2.12.3 or earlier releases to  xCAT releases between 2.12.4 and 2.13.2, the work around is to rerun copycds against the redhat isos.

**Comment by immarvin** [comment]
hi @whowutwut ,  xCAT support user to specify multiple directories in the osimage.pkgdir of the diskfull osimage, there might be yum repos under each of these pkgdir directories, in this case, we will create /etc/yum.repos.d/local-repository-x.repo for each directory.

**Comment by whowutwut** [comment]
@immarvin  Yes, I know when we have otherpkgdir in play, we get those kind of naming conventions, but I am not using otherpkgdir...  or otherpkglist... so I would expect something like `local-repository.repo` file to be created, not with `-x`.     seems like some inconsistency here...   I forget it @gurevichmark made some changes to this naming... 

```
[root@c910f02c05p03 ~]# lsdef -t osimage -o rhels7.3-ppc64le-install-compute^C
[root@c910f02c05p03 ~]# lsdef fs3 -i provmethod
Object name: fs3
    provmethod=rhels7.3-ppc64le-install-compute
[root@c910f02c05p03 ~]# lsdef -t osimage -o rhels7.3-ppc64le-install-compute -i otherpkgdir,otherpkglist
Object name: rhels7.3-ppc64le-install-compute
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le
    otherpkglist=
[root@c910f02c05p03 ~]# ls -ltr /install/post/otherpkgs/rhels7.3/ppc64le
ls: cannot access /install/post/otherpkgs/rhels7.3/ppc64le: No such file or directory
```

But on the compute node, the following is created: 

```
[root@c910f02c05p03 ~]# xdsh fs1,fs3,fs2,fs4 "ls /etc/yum.repos.d/local*"
fs3: /etc/yum.repos.d/local-repository-0.repo
fs1: /etc/yum.repos.d/local-repository.repo.disable
fs2: /etc/yum.repos.d/local-repository.repo
fs4: /etc/yum.repos.d/local-repository.repo
```

fs3 was the latest machine installed yesterday...  This is the build of xCAT used.. 

```
[root@c910f02c05p03 ~]# lsxcatd -a 
Version 2.13.3 (git commit 21436b9577c83c525e09ad254bb5167161e5fc63, built Thu Mar 23 06:16:01 EDT 2017)
This is a Management Node
dbengine=SQLite
```

**Comment by robin2008** [comment]
To introduce "-x" here is just for easy supporting multiple "pkgdir",  not "otherpkgdir". The multiple "pkgdir" is normally for OS updates,  for example,  you can add "pkgdir=/install/rhels7.3/ppc64le,/install/updates/rhels7.3/ppc64le" to add an OS updates for this OS repo.

And of course, we can add all this repo into single repo file, just like "local-repository.repo", (the name is also confusing as it is not local) but use "-x" is better to handle in xCAT codes, and keep the consistent with otherpkgs.

Whatever, if we decide to make the configuration change, we must consider the update case to keep them compatible or make configuration migration during the upgrade script.

**Comment by samveen** [comment]
I found that a `local-repository.tmpl` (used by `addsiteyum`) *is* created, but instead of being stored in `/install/postscripts/repos/centos7.3/$ARCH` as expected, it is being stored in the  ``/install/centos7.3/$ARCH/`
