### ISSUE TITLE
2.13.3 release process

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2861]
1. merge code from master to 2.13 branch
2. do RC build
3. update 2.13.3 release notes
    Need to add know issue for the "copycds -p" issue for 2.12.4, 2.13, 2.13.1, 2.13.2 release notes.

**Comment by whowutwut** [comment]
Ok, closing this issue.  Tasks are tracked here: https://github.com/xcat2/xcat.org/issues/56
