### ISSUE TITLE
problem with xcat.gensis.dodiscovery

### ISSUE THREAD

**Issue by monyaaltuwaigi** [xcat2/xcat-core#2868]
i have management node with following properties 
1- Ubuntu as an operating system 
2- virtual machine in KVM 
3- xcat is installed   
i have created a compute node as a VM using KVM as a hypervisor and i`m trying to install OS using PXE from the management node. when i boot the vm to install the OS it stop at "xcat.gensis.dodiscovery could not find /dev/ipmi". when i checked the dev folder in the managment node i didn`t find anything about ipmi. is the problem that i don`t have ipmi and for what do i need ipmi for virtual machines?

the following is the definition of the compute node called vm2
Object name: vm2
    arch=x86_64
    currchain=boot
    currstate=install centos7.3-x86_64-compute
    groups=vm,all
    installnic=mac
    ip=10.0.0.40
    mac=42:ac:0a:00:00:28
    mgt=kvm
    netboot=pxe
    os=centos7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos7.3-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=04-14-2017 21:28:52
    tftpdir=/10.0.0.5
    tftpserver=10.0.0.5
    vmcpus=2
    vmhost=10.0.0.1
    vmmemory=1024
    vmnicnicmodel=virtio
    vmnics=virbr2
    vmstorage=dir:///var/lib/libvirt/images
    xcatmaster=10.0.0.5

**Comment by whowutwut** [comment]
@monyaaltuwaigi do you have a dynamic range set for you network in the networks table? It seems like you have defined the MAC address for the VM so I'm not sure why it's going into discovery or loading the genesis kernel. Maybe u need to run "makedhcp vm2" and it will start provisioning the OS rather than loading the genesis kernel

**Comment by monyaaltuwaigi** [comment]
i have specified the dynamic range 

this is the output of the tabdump networks
"10_0_0_0-255_255_255_0","10.0.0.0","255.255.255.0","eth1","<xcatmaster>",,"10.0.0.5",,,,"10.0.0.1 10.0.0.254",,,,,,,,,

when i did makedhcp vm2 the output was 
Warning: The ip address 10.0.0.40 of node vm2 overlaps with the DHCP dynamic range specified in networks table, will not add this ip address into dhcpd.leases file.
 
the 10.0.0.40 is the ip address i specified for the vm2

**Comment by monyaaltuwaigi** [comment]
thank you for you help,  i have solved the problem
