### ISSUE TITLE
[xCAT performance]automate get the baseline in xCAT-test

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2875]
1, integrated with daily automation system
2,formalize the performance of baseline output

**Comment by robin2008** [comment]
working on the xCAT-test case and config file for xcatperftest.

**Comment by robin2008** [comment]
Change the scope,  no need to compare the result automatically.
It is enough that we can achieve the performance test data into file and stored to our shared folder, then the data could be easily imported to other data analysis tool, like Excel.

**Comment by daniceexi** [comment]
@robin2008 We could accept that only generate data, but you at least give us a manual step that how to compare the data.

**Comment by robin2008** [comment]
I'll have a simple step by step guide for it. It will be in #2500 
 - prepare a command list for getting the data
 - run it to get current result
 - patch the xCAT or upgrade to new version
 - run it again to get new result
 - how to use Excel to draw graph and make comparison on the two result set.
