### ISSUE TITLE
[Test case]Add test case for 2848: enhance rsetboot cases for openbmc

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#2883]
Acceptance:

Add cases about :

1. unsupported option
2. invalid node
3. -h&--help
4. -v
5. multiple nodes
6. rsetboot [group] ***

**Comment by daniceexi** [comment]
Good to see the case list. Would like the owner could work out a case list before implementing.

**Comment by junxiawang** [comment]
Test case list:
1. rsetboot Invalid_node net
2. rsetboot node 0eds
3.rsetboot node1,node2 net
4.rsetboot all net
 4.1 some nodes could use rsetboot
 4.2 some node could not use rsetboot

**Comment by junxiawang** [comment]
Test case name:
1.rsetboot_node_invalidnode
2.rsetboot_node_invalidaction
3.rsetboot_noderange_net
4.rsetboot_group_net
