### ISSUE TITLE
rpm postscripts complain during upgrades

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#2889]
Upgrading of xCAT via rpm packages causes yum to show the following warning when the package postscripts are run:
```
Restarting xcatd (via systemctl):  Warning: Unit file of xcatd.service changed on disk, 'systemctl daemon-reload' recommended.
[  OK  ]
```
As the warning suggests, the rpm `%post` scriptlet should run `systemctl daemon-reload` in case of an `update` (the section under check `$1 == 2` as per https://fedoraproject.org/wiki/Packaging:Scriptlets

**Comment by immarvin** [comment]
hi @samveen ,  this seems to be a bug we have already fixed in https://github.com/xcat2/xcat-core/issues/1509
what is the origin  and dest xCAT releases with ``rpm  -qa|grep -i xcat`` during your upgrade ?

**Comment by samveen** [comment]
This happened during update from 2.9.1 => 2.10 => 2.11 => 2.11.1 => 2.12 => 2.12.1.

The error did not show up during upgrades till version 2.13.2.
