### ISSUE TITLE
[openbmc] reventlog support

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#2892]
The OpenBMC [Logging API](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Logging)

**Comment by xuweibj** [comment]
The task was finished in pull request #2919 .

**Comment by whowutwut** [comment]
`reventlog` support is not completed, and this should not have been closed.  Let's move this to be an EPIC

**Comment by whowutwut** [comment]
Had a discussion with OpenBMC team today a little about SEL events.   The `.yaml` files in the OpenBMC project contains more human readable descriptions, https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project  But we have not yet established how those descriptions would ship.  Need to sync up with RAS and GUI team so we are all in sync with providing consistent output. 

So digging more into IPMI, it looks like xCAT does contain a mapping between sensor codes and readable strings... so it makes sense we would have similar mapping.....   
* perl-xCAT/xCAT/data/ipmigenericevents.pm
* perl-xCAT/xCAT/data/ipmisensorevents.pm
