### ISSUE TITLE
[FVT] CN can't resolve MN's host name in initrd in diskless+ubuntu+x86 environment

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2898]
Setting ``xcatmaster=<hostname>`` in CN's definition, then do provision, after CN enter into initrd, it can't resolve MN's host name and result in provision failed in diskless+ubuntu+x86

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2899

**Comment by immarvin** [comment]
verified by autotest
