### ISSUE TITLE
Confused issues while reading docs on xcat-docs.readthedocs.org

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#290]
1.  ~~~~~~~~~~~~ Add this and below in Oct.21 2015 ~~~~~~~~~~~~
Link: https://xcat-docs.readthedocs.org/en/latest/guides/install-guides/yum/prepare_mgmt_node.html#configure-the-base-os-repository
Description: In Configure the Base OS Repository section, the Step3 means create a new file with following content, but doesn't clearly define it.

2. Link: https://xcat-docs.readthedocs.org/en/latest/guides/install-guides/yum/install_xcat.html#id1
Description: In install xcat-core section, Step1, the address should be updated? Step2 the "tar jxvf xxx" command doesn't work.  And do we need to add Step4 to track if the xcat-core is installed successfully or not?
BTW it is the same to install xcat-dep

3. Link: https://xcat-docs.readthedocs.org/en/latest/guides/install-guides/yum/configure_xcat.html
Description: This page is blank?

4. Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/basic_concepts/global_cfg/index.html
Description: There are long words which are connected by two or three simple words, for example, excludenodes?

5. ~~~~~~~~~~~~ Add this and below in Oct.22 2015 ~~~~~~~~~~~~
Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/copy_image.html
Description: Wrong word: diskfull 

6. Link: https://xcat-docs.readthedocs.org/en/latest/overview/index.html#brief-steps-to-set-up-an-xcat-cluster
Description: In Step5, the referenced link: Hardware Management links to a page without enough content. 
There is still another Hardware Management　page:　https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/management.html
It seems they are related to each other?

7. Link:https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/deploy_os.html#start-the-os-deployment
Description: Before execute "nodeset <nodename> osimage=<osimage>", no obvious suggestion to change password in passwd table, which causes error.

8. ~~~~~~~~~~~~ Add this and below in Oct.23 2015~~~~~~~~~~~~ 
Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/updatenode.html
Description: 2. Rerun postscripts or Run Additional Postcripts ----- do we need to unify capital and small letter?

9. Link: https://xcat-docs.readthedocs.org/en/latest/overview/index.html#brief-steps-to-set-up-an-xcat-cluster
Description: 
  9.1 In Step8 Parallel Shell, change "Shell" to be "shell"
  9.2 In Step9 Contribute to xCAT (OPtional),  change "OPtional" to be "Optional"?
  9.3 In Step9  please do that for the behalf of yours and other xCAT user’s, change "user's" to be "users"

10. Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/parallel_cmd.html
Description: There is a blue link in this sentence "For a list of the Parallel Commands and their man pages doc parallel commands." but it seems it directs to another parallel page with same content: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/parallel_cmd.html#parallel-commands. Mean while in this directed page, there is still another blue link "parallel commands" directs itself.

11. Words Spelling Mistakes
 
Link:　https://xcat-docs.readthedocs.org/en/latest/developers/license/maintainers.html
Description: There is a word “infominformation” , we need to correct it?

Link:https://xcat-docs.readthedocs.org/en/latest/developers/github/index.html
Description: word "execllent" change to be "excellent"? 

Link: https://xcat-docs.readthedocs.org/en/latest/developers/github/change_code.html
Description: "Creating additional branches will allow you to work on on different tasks/enhancements", there are double "on"?

**Comment by whowutwut** [comment]
@caomengmeng  Thank you! This is exactly the type of feedback that we need.  Please continue to raise any flags in our documentation if things are unclear.

**Comment by whowutwut** [comment]
@caomengmeng  To answer the questions above...  I will make the changes and submit a pull request to address your issues and others that I see as a result of looking at these pages. 

1.  Yes, I will clarify in the pull request. 

2. Step1 - Yes, Thank you! I will correct the links in the pull request
    Step2 - Yes,  The filename was incorrectly mentioned, needed bz2 instead of bz.   
    Step4 - No I don't think we need to verify xcat-core is installed right.  It should be an extract of a tar file.  The next sections will install xCAT and verify xCAT installation. 
    
3. @daniceexi  , Regarding the "configure_xcat" page.. should we remove this page? The admin guide -> manage clusters describes how to configure xCAT.  Or do we need a simple example here to configure a node?  Maybe there is no "simple" way... :-) 

4. I have not reviewed this page, but I will do so and clean up as best I can.

**Comment by daniceexi** [comment]
For the **config_xcat** page, I was thinking we need this page to make some gbloable configuration to enable xCAT service:

* check the site table
  check the site.master, make it has correct value;

* network configuration
  check the networks table has correct value
  run **makenetworks** to config network

* dhcp configuration
  set  site.dhcpinterfaces if necessary
  run **makedhcp -n** to cfg dhcpd

* dns configuration
  check site.domain
  check site.nameserver

  run makedns

**Comment by whowutwut** [comment]
Looking at the global configuration page, this seems to just be a copy of the information from ``tabdump -d site`` output.  Do we know what the intent was for is page?

**Comment by caomengmeng** [comment]
@whowutwut  @daniceexi  Many thanks for reply.
5. Link: https://xcat-docs.readthedocs.org/en/latest/overview/index.html#brief-steps-to-set-up-an-xcat-cluster
Description: Step5 referenced link: Hardware Management jump to a page without enough information?
There is also another Hardware Management page: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/management.html
it seems they are related to each other?

**Comment by daniceexi** [comment]
@whowutwut Yes, some of them have been described in the global cfg page, but this page is used to initialize the xCAT to make some basic configuration. This page is used to do something instead of saying something.

Besides what I mentioned, change passwd table also needs be added.

**Comment by daniceexi** [comment]
@junxiawang Jun Xia will draft this xcat_config page.

**Comment by whowutwut** [comment]
Thanks @daniceexi 
@junxiawang  please wait until pull request #290 is merged before working on the xcat_config page as there have been many files added to the install_guide...

**Comment by whowutwut** [comment]
@caomengmeng  , you added more things...  I updated with commid 47dc659d7f44b895ba8b5d2dfcf758edbdb2cdfa

5  Yes, I change to diskful,  There are a few other places that also have diskfull with two l .  Can you open another issue for this, this is a larger piece of work to clean up all occurrences externally and internally. We name pages "diskfull" instead of "diskful" 

6 I will fix the link and remove the management page without any information

7 Under https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/discovery/index.html, there is "Configure xCAT" page which does mention the passwd table .  If this is not clear, maybe open a separate issue for this also. 

8 Changed directly to master

**Comment by caomengmeng** [comment]
@whowutwut 

5. Already open another new issue to track it: https://github.com/xcat2/xcat-core/issues/298.
7. Yes, we found this page yesterday, but still think it doesn't work, maybe need to discuss with others?

**Comment by whowutwut** [comment]
@caomengmeng, just something I noticed... when you number with a period, (5.) GitHub change the number to start at 1. and 2..  so your comment above says 1. and 2.  But I noticed to leave out the period after the number and it will display correctly.  But I figured out you meant item 5 and item 7. :-) 

I think if @junxiawang drafts a version of configure xcat in the install guide , we can take a look to see if the instructions will flow better.  I'm trying to avoid duplicate information.  I think the Basic section should cover everything to get a very small cluster up and running, then we can assume that those steps have been followed and we don't need to repeat steps in the more advanced section. 
 
Please take some time to review pull request #292, as those changes need to be in the master branch before Jun Xia starts working on config_xcat...

**Comment by whowutwut** [comment]
@caomengmeng  I think you should make comments to this issue in this comment box instead of modifying the original post.  I don't think I get notified on the original post.  

Item 10 I address by adding to the pull request, but the other ones I fixed directly. 

Feel free to also fix mis-spellings directly into GitHub when you come across them.

**Comment by caomengmeng** [comment]
@whowutwut  Thanks for reply.
I will pay attention to https://github.com/xcat2/xcat-core/pull/292 and also try to fix mis-spelling mistakes directly to GitHub by myself.

**Comment by caomengmeng** [comment]
Hi @whowutwut , after all the issues listed above are updated, would you please send me a link to you local server, then I can review and make all merged.

**Comment by whowutwut** [comment]
@caomengmeng. Pull request #292 has the link to the server with the changes made to address this issue

**Comment by caomengmeng** [comment]
Fixed and close this issue.
