### ISSUE TITLE
[Test case]enhance testcase nodeset

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2904]
Acceptance: 
1. support when node definition netboot is petitboot/grub2/yaboot.
2. need to cover: nodeset_offline, nodeset_osimage, nodeset_addcmdline

1. cleanup configuration file: dhcp lease file, bootloarder configuration file,
2. run nodeset
3. the configuration need to be checked: dhcp lease file, bootloader configuration file, the autoinst file

**Comment by robin2008** [comment]
@tingtli 

For petitboot:
The boot configuration is in /tftpboot/<HEX-IP> and /tftpboot/petitboot/<nodename>
The autoinstall file is in /install/autoinst/<nodename>

Note:
You can use "nodeset <node-range> offline" to clean-up the boot configuration files 
makedhcp -d <node-range>  to clean-up dhcp lease and "makedhcp -q" to query if lease entry is ready,  pay attention here for operate dhcp server, maybe you need a bit sleep time.
