### ISSUE TITLE
xcatd 3002 port disappear 

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2905]
xcatd 3002 port disappear, after `service xcatd restart`, it came back.
```
[root@stratton01 petitboot]# netstat -aln|grep 3002
[root@stratton01 petitboot]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]
[root@stratton01 petitboot]# netstat -aln|grep 3002
tcp        0      0 0.0.0.0:3002            0.0.0.0:*               LISTEN

]# lsxcatd -v
Version 2.13.3 (git commit 40f3725a50251b7a1027d16e3f3af7f40f19688f, built Thu Mar 30 06:18:02 EDT 2017)
```

**Comment by daniceexi** [comment]
@bybai is there a way to recreate this issue?

**Comment by bybai** [comment]
Hi @daniceexi , 
I hit this twice, during running updateflag.awk when the CN is booting, the script retry 10 times but failed, then I check the 3002 port in MN, it is not there. I think 3002 port should be monitored, and I can know when it disappeared. The quick reproduction of the issue is to re-provision the P9 node. 
YangSong wants to look into this issue, assign this to him.

**Comment by bybai** [comment]
During running `Post-Installation scripts` and system reboot, xcatd running background, the 3002 port disappeared, the issue can be reproduced. When I ran `xcatd -f`, the post-installation scripts hang.

**Comment by whowutwut** [comment]
Does this only happen on the stratton01 machine?

**Comment by immarvin** [comment]
the xCAT ps tree on mn:
````
root      21856  0.0  0.0  60544 50688 ?        Ss   00:45   0:00 xcatd: SSL listener
root      21857  0.0  0.0  60160 49920 ?        S    00:45   0:01  \_ xcatd: DB Access
root      21858  0.0  0.0  58048 46400 ?        S    00:45   0:00  \_ xcatd: UDP listener
root      21859  0.0  0.0  58048 45376 ?        S    00:45   0:00  |   \_ xcatd: Discovery worker
root      21861  0.0  0.0  58240 47232 ?        S    00:45   0:00  \_ xcatd: Command log writer
````

**Comment by immarvin** [comment]
The strace log of the "install monitor service" across its whole lifetime

[strace.log.instamm.txt](https://github.com/xcat2/xcat-core/files/963526/strace.log.instamm.txt)

**Comment by bybai** [comment]
Hi @whowutwut , this happens in stratton01.

**Comment by immarvin** [comment]
possible root cause: https://github.com/xcat2/xcat-core/issues/3010

**Comment by immarvin** [comment]
After Xuwei fixed https://github.com/xcat2/xcat-core/issues/3010 , the "install monitor" service does not disappear any more. 

But observed the following error message on "xcatd -f", https://github.com/xcat2/xcat-core/issues/3026 , which caused there will always be "XCAT" netboot entry inpetitboot and the provision process entered the reinstallation loop

**Comment by immarvin** [comment]
verified with the PR https://github.com/xcat2/xcat-core/pull/3029 , https://github.com/xcat2/xcat-core/pull/3028 and https://github.com/xcat2/xcat-core/pull/3021, the full process of provision goes success.

**Comment by bybai** [comment]
I verified.
