### ISSUE TITLE
[FVT] add a list of people who check in code during last 24 hours in the "xCAT Jenkins Test Report" 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2909]
Acceptance :
1 Depending on long commit id in ``build.info`` to calculate the list of people who check in code during last 24 hours. 

2 highlight this list in ``xCAT Jenkins Test Report``

[DEADLINE] : May 2

**Comment by neo954** [comment]
The code is ready for review.

https://github.ibm.com/xcat2/jenkins/pull/109
