### ISSUE TITLE
[FVT]:2.11:  xdsh <node> "configraid delete_raid=all" hangs when delete raid 0

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#291]
xCAT 2.11   on rh7.1
[root@~]# lsxcatd -v
Version 2.11 (git commit 2295560c5048801e80477a18e5267bcdb06a0814, built Thu Oct 15 19:30:47 EDT 2015)

[root@ ~]# xdsh p8euh diskdiscover
p8euh: --------------------------------------------------------------------------
p8euh: PCI_ID     PCI_SLOT_NAME  Resource_Path  Device  Description   Status
p8euh: ------     -------------  -------------  ------  -----------   ----------------
p8euh: 1014:034a  0001:08:00.0   0:0:0:0        sg0     0 Array Member Active
p8euh: 1014:034a  0001:08:00.0   0:0:1:0        sg1     0 Array Member Active
p8euh: -------------------------------------------------------------------
p8euh: Get ipr RAID arrays by PCI_SLOT_NAME: 0001:08:00.0
p8euh: -------------------------------------------------------------------
p8euh: Name   PCI/SCSI Location         Description               Status
p8euh: ------ ------------------------- ------------------------- -----------------
p8euh: sda    0001:08:00.0/0:2:0:0       RAID 0 Disk Array         Optimized
[root@ ~]# xdsh p8euh "configraid delete_raid=all"

<======hang here.

Here is the log
[I]: Round 1: delete_ipr_array, "0 0:2:0:0"
[W]: Round 1: Array 0 is un-deletable at present.
[W]: Round 1: Array 0:2:0:0 is un-deletable at present.
[I]: Round 1: All remaining target arrayes are un-deletable now.
[I]: Round 1: Wait for these un-deletable arrayes deletable with tryCnt=360, tryInt=60.
/usr/bin/raidutils: line 1356: check_ipr_device_status: command not found
[S]: Wait for device status at time "2015-10-20 21:55:12": status[0]="",status[0:2:0:0]="", expect: "grep -sq -E 'Optimized'".
/usr/bin/raidutils: line 1356: check_ipr_device_status: command not found
[S]: Wait for device status at time "2015-10-20 21:56:12": status[0]="",status[0:2:0:0]="", expect: "grep -sq -E 'Optimized'".
/usr/bin/raidutils: line 1356: check_ipr_device_status: command not found
[S]: Wait for device status at time "2015-10-20 21:57:12": status[0]="",status[0:2:0:0]="", expect: "grep -sq -E 'Optimized'".
/usr/bin/raidutils: line 1356: check_ipr_device_status: command not found

**Comment by bybai** [comment]
This is my unit test result:
~]# xdsh p8euh configraid delete_raid=all
p8euh: [I]: Renew available target arrays which will be deleting, "0 0:2:0:0 0 0:2:1:0"
p8euh: [I]: Round 1: Deletable array >> 0:2:0:0
p8euh: [I]: Round 1: Deletable array >> 0:2:1:0
p8euh: [I]: Round 1: ipr info before delete >> Name PCI/SCSI Location Description Status
p8euh: [I]: Round 1: ipr info before delete >> ------ ------------------------- ------------------------- -----------------
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: ipr info before delete >> sda 0001:08:00.0/0:2:0:0 RAID 0 Disk Array Optimized
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:0:0 RAID 0 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> sdb 0001:08:00.0/0:2:1:0 RAID 0 Disk Array Optimized
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:1:0 RAID 0 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> 0003:04:00.0/1: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: delete_ipr_array, "0 0:2:0:0 0 0:2:1:0"
p8euh: [W]: Round 1: Array 0 is un-deletable at present.
p8euh: [W]: Round 1: Array 0 is un-deletable at present.
p8euh: [I]: Round 1: Verified array slocs for deletion are "0:2:0:0 0:2:1:0".
p8euh: [I]: Round 1: Delete 0 array sg6=0:2:0:0
p8euh: [I]: Round 1: Delete 1 array sg8=0:2:1:0
p8euh: [I]: Renew available target arrays which will be deleting, ""
p8euh: [I]: Round 2: All target arrays were gone!
p8euh: [I]: Can not create RAID. There is no create_raid.

**Comment by tingtli** [comment]
Verified and close
