### ISSUE TITLE
[Test case]Add test case for openbmc rspconfig command

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2912]
Acceptance:

Add cases about :

Supported options: ip, netmask, gateway (valid/invalid)

**Comment by junxiawang** [comment]
Test cases list:
1.rspconfig node ip=valid ip
2.rspconfig node ip=Invalid ip
3.rspconfig node netmask=valid netmask
4.rspconfig node netmask=Invalid netmask
5.rspconfig node gateway=valid gateway
6.rspconfig node gateway=Invalid gateway
7.rspconfig noderange netmask=valid netmask ,ip=valid ip ,gateway=valid gateway 
8.rspconfig noderange netmask=valid netmask,ip=invalid ip
9.rspconfig testnode(invalid node) netmask=valid netmask

**Comment by daniceexi** [comment]
one comment that since the options are various, how the test case check to know that whether the current server supports the corresponding options?

**Comment by junxiawang** [comment]
Testcase new added name:
1.rspconfig_ip
2.rspconfig_ip_invalid
3.rspconfig_netmask
4.rspconfig_netmask_invalid
5.rspconfig_gateway
6.rspconfig_gateway_invalid
7.rspconfig_node_invalid
8.rspconfig_ip_null
