### ISSUE TITLE
[openbmc]rspconfig support option: ip/netmask/gateway/vlan

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2913]
Acceptance: support option ip/netmask/gateway/vlan for rspconfig against openbmc

**Comment by whowutwut** [comment]
In the process of investigating this new support Issue, it would be good if we can put in some description pointing to openbmc URLs where we find out the endpoint that we need to hit to make the changes required here..

**Comment by xuweibj** [comment]
The url that provided by openbmc team is ``/xyz/openbmc_project/network///0/`` now.
We start to work on ``rspconfig`` command according this. The interface is not enough for us to send real request.

**Comment by xuweibj** [comment]
Interface:

```
 # rspconfig node1 [ip|netmask|gateway]=x.x.x.x
BMC [IP|Netmask|Gateway]: x.x.x.x
```

```
# rspconfig node1 ip=x.x.x.x netmask=x.x.x.x gateway=x.x.x.x
BMC IP: x.x.x.x
BMC Netmask: x.x.x.x
BMC Gateway: x.x.x.x
```

**Comment by whowutwut** [comment]
I should have added this also, we need to be able to tag the VLAN using rspconfig. Is this possible?

**Comment by whowutwut** [comment]
@xuweibj  Regarding `/xyz/openbmc_project/network///0/` in the [README.md](https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Network/README.md) , you have to view it raw because the markdown is not rending correctly.  Then you can see the interfaces planned and we can code against that API.

**Comment by xuweibj** [comment]
Hi @whowutwut , now the code is just framework, I will modify it when I got the final interface.

**Comment by xuweibj** [comment]
The task was finished in pull request #2966 .(framework)
