### ISSUE TITLE
[xCAT performance]enhance performance of nodeset(phase 1)

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2918]
Investigate the possibility to enhance the performance of nodeset.
Investigate the performance difference with and without SN(flat and non-flat).

**Comment by robin2008** [comment]
Sub-Task1 investigation is done.

After nytprof and code level analysis.  In a default "nodeset" of ppc64le/x86_64 osimage.  The most of time are used for "makedhcp" (20%) and "setdestiny" (50%).

And in "setdestiny", the most of time are get data from DB and generate the boot configuration file, auto install response file based on template.

**xCAT::Template::includefile**:  1/3 time is used to remove the trailing space and generate the final Template. And in a cluster, most of the nodes has the same attribute and it means the same template, no need to generate the same template multiple times.

**xCAT::Template::tabdb**: DB operation is time consuming, use TABLE in template as less as possible,  for example, for site attribute, we can get it in cache. Also for node attribute, we can get it from transient cache.

There are still some other place could be enhanced to improve the performance,  the target is not to run the duplicate same codes for each nodes in a big loop. 

With above enhancement,  in a large cluster which most of the nodes are the same, or just small groups with same attribute.  The performance of nodeset (without dhcp plugin) might be improved about 20-30%

For makedhcp, it considered in other task. A possible way is not to re-add the existing node to dhcp server.

**Comment by robin2008** [comment]
For non-flat hierarchy topo:   two SN, each has 2500 nodes  and serve different subnet.
The result on 2.13.4 daily build:

5000, lsdef, 5000, 98, SUCESS, "lsdef perftest"
5000, makehosts, 5000, 52, SUCESS, "makehosts perftest"
5000, makedns, 5000, 550, SUCESS, "makedns -n perftest"
5000, makedhcp, 5000, 272, SUCESS, "makedhcp perftest"
5000, makeknownhosts, 5000, 262, SUCESS, "makeknownhosts perftest"
5000, nodech, 5000, 13, SUCESS, "nodech perftest groups,=group1"
5000, nodels, 5000, 62, SUCESS, "nodels perftest noderes"
5000, nodeset, 5000, 1770, SUCESS, "nodeset perftest osimage=rhels7.3-ppc64le-install-compute"
5000, chdef, 5000, 27, SUCESS, "chdef -t node -o perftest postscripts="fake" profile="install" netboot="grub2""
5000, nodeset, 5000, 1886, SUCESS, "nodeset perftest osimage=rhels7.3-ppc64le-install-compute"

**Comment by robin2008** [comment]
5000 nodes but all nodes IP in both MN and SN's subnets.

```
site:
sharedtftp=1 and setupdhcp=n
5000, mkdef, 5000, 70, SUCESS, "mkdef -z -f < /tmp/xcat-performance/stanz-5000.21286"
5000, lsdef, 5000, 92, SUCESS, "lsdef perftest"
5000, makehosts, 5000, 52, SUCESS, "makehosts perftest"
5000, makedns, 5000, 109, SUCESS, "makedns -n perftest"
5000, makedhcp, 5000, 408, SUCESS, "makedhcp perftest"
5000, makeknownhosts, 5000, 179, SUCESS, "makeknownhosts perftest"
5000, nodech, 5000, 10, SUCESS, "nodech perftest groups,=group1"
5000, nodels, 5000, 42, SUCESS, "nodels perftest noderes"
5000, nodeset, 5000, 2063, SUCESS, "nodeset perftest osimage=rhels7.3-ppc64le-install-compute"
5000, chdef, 5000, 27, SUCESS, "chdef -t node -o perftest postscripts="fake" profile="install" netboot="grub2""
5000, nodeset, 5000, 2104, SUCESS, "nodeset perftest osimage=rhels7.3-ppc64le-install-compute"
```

**Comment by robin2008** [comment]
And the command run on MN and on SN will have different performance:
```
[root@c910f03c05k29 ~]# time makedhcp perftest -l

real	6m11.011s
user	0m0.197s
sys	0m0.026s
[root@c910f03c05k29 ~]# free
              total        used        free      shared  buff/cache   available
Mem:        3645632      455488      127808      137984     3062336     2874048
Swap:       4195264           0     4195264
[root@c910f03c05k29 ~]# exit
logout
Connection to c910f03c05k29 closed.
[root@c910f03c05k20 xcat-performance]# time makedhcp perftest -l

real	1m45.670s
user	0m0.158s
sys	0m0.016s
[root@c910f03c05k20 xcat-performance]# ssh c910f03c05k30
Last login: Wed May 10 05:07:30 2017 from c910f03c05k20.private.zone
[root@c910f03c05k30 ~]# time makedhcp perftest -l

real	6m37.804s
user	0m0.227s
sys	0m0.023s
```
This might be related to the DB access and DNS lookup via IP remotely.  And for large number of nodes, the network impact might be big,  so even if we using two SNs to take the workload for boot configuration file, but the performance does not increase. 
Performance of Handling 5000 on MN is better than handling 2500 on two SN 

But if we using 8 (1+1) SN groups,  it means there is possibility to reduce the number to 600 on each SN with special configuration. 
```
[root@c910f03c05k29 ~]# time makedhcp fake[1-600] -l

real	0m52.202s
user	0m0.128s
sys	0m0.025s
```

**Comment by robin2008** [comment]
Base on above:
using SNs could get better performance in some kinds of configuration,  but we still need to figure out what's the configuration (how many SNs, and if using non-flat networking) based on the the total number.

Whatever,  we still can improve the performance on single MN or SN by refine the codes.
