### ISSUE TITLE
PXE booting freeze during OS installation 

### ISSUE THREAD

**Issue by monyaaltuwaigi** [xcat2/xcat-core#2928]
i am trying to install centos7 to my compute node. the compute node start to install the vmlinuz and initrd.img and then it freeze. the following image show you where the OS installation freeze. 
![screenshot from 2017-04-24 20-05-30](https://cloud.githubusercontent.com/assets/25745358/25349159/7aebe96a-2929-11e7-92a3-a90ac46588a5.png)

i don`t where the problem exactly, i hope someone can help me 

compute node info:
arch=x86_64
    currchain=boot
    currstate=install centos7.3-x86_64-compute
    groups=vm,all
    ip=10.0.0.40
    mac=42:47:0a:00:00:28
    mgt=kvm
    netboot=xnba
    os=centos7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos7.3-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=04-24-2017 17:03:56
    vmcpus=2
    vmhost=10.0.0.1
    vmmemory=1024
    vmnicnicmodel=virtio
    vmnics=virbr2
    vmstorage=dir:///var/lib/libvirt/images

**Comment by immarvin** [comment]
hi @monyaaltuwaigi , please provide the osimage definition by ``lsdef -t osimage -o centos7.3-x86_64-install-compute``.

From the screenshot you provided, seems the anaconda  is not started yet. would you please provide the last 50 lines of  /var/log/httpd/access_log on your management node? thanks

**Comment by monyaaltuwaigi** [comment]
this is the definition of the osimage 
Object name: centos7.3-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.3-x86_64
    osname=Linux
    osvers=centos7.3
    otherpkgdir=/install/post/otherpkgs/centos7.3/x86_64
    pkgdir=/install/centos7.3/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.centos7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.centos7.tmpl
and this for the http access_log
10.0.0.1 - - [24/Apr/2017:14:05:05 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:05:06 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2731 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:05:11 +0000] "POST /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2565 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:08:00 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:08:02 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2801 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:27 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:29 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2731 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:35 +0000] "POST /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2774 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:47 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:48 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2732 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:09:58 +0000] "POST /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2772 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:24:02 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:24:04 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2727 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:24:04 +0000] "GET /uva_v4/assets/img/user3.png HTTP/1.1" 200 2282 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:35:39 +0000] "POST /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2768 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:35:46 +0000] "GET /uva_v4/dashboard.php?currentPage=dashboard HTTP/1.1" 200 3212 "http://10.0.0.5/uva_v4/profile.php?currentPage=profile" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.1 - - [24/Apr/2017:14:35:48 +0000] "GET /uva_v4/profile.php?currentPage=profile HTTP/1.1" 200 2725 "http://10.0.0.5/uva_v4/dashboard.php?currentPage=dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.0.0.100 - - [24/Apr/2017:15:01:44 +0000] "GET /tftpboot/xcat/xnba/nets/10.0.0.0_24 HTTP/1.1" 200 442 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:15:01:44 +0000] "GET /tftpboot/xcat/genesis.kernel.x86_64 HTTP/1.1" 200 4152546 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:15:01:44 +0000] "GET /tftpboot/xcat/genesis.fs.x86_64.gz HTTP/1.1" 200 36440912 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:16:22:29 +0000] "GET /tftpboot/xcat/xnba/nodes/monyavm1 HTTP/1.1" 200 696 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:16:22:29 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/vmlinuz HTTP/1.1" 200 5392290 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:16:22:30 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/initrd.img HTTP/1.1" 200 43372764 "-" "iPXE/1.0.3-130626"
10.0.0.13 - - [24/Apr/2017:16:22:41 +0000] "GET /install/centos7.3/x86_64/.treeinfo HTTP/1.1" 200 569 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:16:22:41 +0000] "GET /install/centos7.3/x86_64/LiveOS/squashfs.img HTTP/1.1" 200 332746966 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:16:22:48 +0000] "GET /install/centos7.3/x86_64/images/updates.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:16:22:48 +0000] "GET /install/centos7.3/x86_64/images/product.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:16:22:49 +0000] "GET /install/autoinst/monyavm1 HTTP/1.1" 200 84695 "-" "curl/7.29.0"
10.0.0.30 - - [24/Apr/2017:16:34:53 +0000] "GET /tftpboot/xcat/xnba/nodes/node03 HTTP/1.1" 200 695 "-" "iPXE/1.0.3-130626"
10.0.0.30 - - [24/Apr/2017:16:34:53 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/vmlinuz HTTP/1.1" 200 5392290 "-" "iPXE/1.0.3-130626"
10.0.0.30 - - [24/Apr/2017:16:34:54 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/initrd.img HTTP/1.1" 200 43372764 "-" "iPXE/1.0.3-130626"
10.0.0.227 - - [24/Apr/2017:16:35:05 +0000] "GET /install/centos7.3/x86_64/.treeinfo HTTP/1.1" 200 569 "-" "curl/7.29.0"
10.0.0.227 - - [24/Apr/2017:16:35:05 +0000] "GET /install/centos7.3/x86_64/LiveOS/squashfs.img HTTP/1.1" 200 332746966 "-" "curl/7.29.0"
10.0.0.227 - - [24/Apr/2017:16:35:19 +0000] "GET /install/centos7.3/x86_64/images/updates.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.227 - - [24/Apr/2017:16:35:19 +0000] "GET /install/centos7.3/x86_64/images/product.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.227 - - [24/Apr/2017:16:35:20 +0000] "GET /install/autoinst/node03 HTTP/1.1" 200 84746 "-" "curl/7.29.0"
10.0.0.100 - - [24/Apr/2017:16:56:21 +0000] "GET /tftpboot/xcat/xnba/nets/10.0.0.0_24 HTTP/1.1" 200 442 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:16:56:21 +0000] "GET /tftpboot/xcat/genesis.kernel.x86_64 HTTP/1.1" 200 4152546 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:16:56:22 +0000] "GET /tftpboot/xcat/genesis.fs.x86_64.gz HTTP/1.1" 200 36440912 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:16:59:34 +0000] "GET /tftpboot/xcat/xnba/nets/10.0.0.0_24 HTTP/1.1" 200 442 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:16:59:34 +0000] "GET /tftpboot/xcat/genesis.kernel.x86_64 HTTP/1.1" 200 4152546 "-" "iPXE/1.0.3-130626"
10.0.0.100 - - [24/Apr/2017:16:59:34 +0000] "GET /tftpboot/xcat/genesis.fs.x86_64.gz HTTP/1.1" 200 36440912 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:17:04:11 +0000] "GET /tftpboot/xcat/xnba/nodes/monyavm1 HTTP/1.1" 200 696 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:17:04:11 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/vmlinuz HTTP/1.1" 200 5392290 "-" "iPXE/1.0.3-130626"
10.0.0.40 - - [24/Apr/2017:17:04:11 +0000] "GET /tftpboot/xcat/osimage/centos7.3-x86_64-install-compute/initrd.img HTTP/1.1" 200 43372764 "-" "iPXE/1.0.3-130626"
10.0.0.13 - - [24/Apr/2017:17:04:27 +0000] "GET /install/centos7.3/x86_64/.treeinfo HTTP/1.1" 200 569 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:17:04:28 +0000] "GET /install/centos7.3/x86_64/LiveOS/squashfs.img HTTP/1.1" 200 332746966 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:17:04:41 +0000] "GET /install/centos7.3/x86_64/images/updates.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:17:04:41 +0000] "GET /install/centos7.3/x86_64/images/product.img HTTP/1.1" 404 474 "-" "curl/7.29.0"
10.0.0.13 - - [24/Apr/2017:17:04:41 +0000] "GET /install/autoinst/monyavm1 HTTP/1.1" 200 84695 "-" "curl/7.29.0"

**Comment by immarvin** [comment]
hi @monyaaltuwaigi , from access_log, we can find that the installer and kickstart file have been downloaded.  you can try the following steps to help debug:
1. Please enable the ssh access inside installer by ``chdef monyavm1 -p addkcmdline=inst.sshd``
2. run ``nodeset monyavm1  osimage=centos7.3-x86_64-install-compute`` then rerun deployment
3. try to ssh the installer when the installation hang and check whether the installer can be accessed via ssh

**Comment by immarvin** [comment]
no response, close this first, will close if any update
