### ISSUE TITLE
investigate the issue  #2859 xCAT daemon stuck for months and cause problem when xCAT upgrading

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2930]
for issue https://github.com/xcat2/xcat-core/issues/2859:

@neo954 will spend some time to investigate the issue:
1. find the way to recreate the issue 
2. estimate the influence of this issue

**Comment by hu-weihua** [comment]
This is a problem, but now we have not had root cause and solution, compare with other work item in 2.13.4 sprint2, it has lower priority, so move it to 2.13.5 sprint1

**Comment by zet809** [comment]
Close this task and reopen it if we plan to put effort to find the root cause.
