### ISSUE TITLE
refine the workflow and documentation on the network management in xCAT

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2931]
1. refine the workflow on network configuration and network management with xCAT, such as networks tables, confignics and confignetworks scripts

2. refine the documentation http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_network_adapter.html to include the typical workflow, steps and technical descriptions on network management and network configuration in xCAT

**Comment by bybai** [comment]
The related scripts and commands:
nicutils.sh
updatenetwork
configbond
config_bootnicsea
hardeths
routeop
configefi
configeth
configeth_aix    -----------this is low priority for aix
setroute 
confighfi   -----------this is low priority for hfi
configib
configinterface
confignetwork
joindomain
confignics
makehosts
makenetworks
makeroutes

**Comment by bybai** [comment]
https://github.com/xcat2/xcat-core/issues/2997
