### ISSUE TITLE
[openbmc]collect current xCAT concerns and confirm with Firmware team

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2932]
1. openbmc in-band access interface, especially the interface to configure user account for RESTful interface
2. the schedule for the interfaces needed by xCAT

**Comment by zet809** [comment]
We have xCAT milestone page with https://github.ibm.com/vhu/c910env/blob/master/notes/openbmc/interlock/README.md, need to trace the progress of Firmware team.

**Comment by zet809** [comment]
Keep the task open to trace the the openbmc interface implementation progress.

**Comment by whowutwut** [comment]
This is ongoing and currently scheduled out to End of July.

**Comment by zet809** [comment]
Seems this tasks is never need, may I close it? @whowutwut

**Comment by whowutwut** [comment]
Yes, I'm not sure exactly why we created this one, maybe just to indicate some work being done. . It's more of an continuous interlock meeting and ensuring that we have properly defined the requirements from xCAT to OpenBMC function...   let's close
