### ISSUE TITLE
[openbmc]create new genesis-base for WSP server

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2933]
- [x] Phase 2:
1. build genesis-base after Fedora 26 GAed at July 11.
2. include the build in xcat-dep tar ball for 2.13.6

- [x] Phase 1:
1. Verify current genesis-base on WSP server
2. If not work, try latest Fedora diskless on WSP server
3. If Fedora not work, build genesis-base based on Pegas.

**Comment by zet809** [comment]
Tried Fedora 26 Alpha ppc64 on p9euh02, and the genesis-base build based on it works fine. 
Several issue:
1. the Mlx_en and i40e driver will be a problem for Fedora26
2. lots of libxxx dependency need to be cleared.

**Comment by whowutwut** [comment]
@zet809 How did you create the xCAT genesis base, can we automate this step?  

The comments you provide is not detailed enough for us to understand... why is the drivers a problem for fedora26...  

If it's documented in our internal wiki or github somewhere, then it's sufficient, but we need to have more documentation about these manual processes so that anyone can see what was done and provide coverage if needed.

**Comment by zet809** [comment]
For 1, As you know, we had embed i40e 1.5.16 driver and mlx_en 3.2-1.0.1.1 driver within xCAT-genesis-base. The building process of those 2 drivers are failed on Fedora 26 Alpha ppc64, for i40e1.5.16, I had opened  https://sourceforge.net/p/e1000/bugs/566 to trace. But for mlx_en, no driver available for Fedora26 yet.
For 2, in our install file, there are lots of libraries specified with version number, we need to modify it for difference OS. I have tried to remove those special information and tried on Fedora26 ppc64, it works fine. Once the modification is verified that works also for x86_64, it will be much easier to support new OS. 

We have internal wiki about the building process for genesis-base, the process is very easy and just some packages need to be installed.

**Comment by whowutwut** [comment]
@zet809 Why is this changed to Review? Is pull request ready for review?

**Comment by zet809** [comment]
The pull request #2975 is ready to review, the pull request include the modification to build genesis-base on Fedora26

**Comment by whowutwut** [comment]
Fedora 26 release is scheduled https://fedoraproject.org/wiki/Releases/26/Schedule currently states 7/11. So let's target this issue for then. The work can be completed ahead

**Comment by zet809** [comment]
Thx @whowutwut

**Comment by whowutwut** [comment]
@zet809 Trying to track the remaining tasks for this ... 

- [ ] Put the beta version of xCAT genesis base on xcat.org
For this, did you create `files/xcat/xcat-dep/2.x_Linux/beta` on xcat.org?   If so, let's upload the beta version of xCAT-genesis-base there and cross this off..  
- [ ] After Fedora26 GA, rebuild the xCAT-genesis base   (only for RHEL 7.x ppc64le platform) 
- [ ] Include it in the xcat-dep packages for the next release of xCAT

If you want to convert this to an epic, feel free, then we should create those tasks, or just track them here.

**Comment by zet809** [comment]
Hi, @whowutwut , I had rebuilt the xCAT-genesis-base and uploaded it onto xcat.org.
For the next 2 things you mentioned above, I'd like to reuse this task to trace them and had updated the description of this task.

**Comment by whowutwut** [comment]
@zet809  👍  I like this plan.  

Adding in the URL for reference: http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-base-ppc64-2.13.5-snap201706220300.noarch.rpm

**Comment by zet809** [comment]
The new package is available at https://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-base-ppc64-2.13.6-snap201707120359.noarch.rpm
The issue is, 
- [ ] No suitable mlnx-en driver for Fedora 26, still finding.
- [ ] The i40e driver included in Fedora26 is newer than documented, so remove the section in the builldrpm script.

**Comment by whowutwut** [comment]
@zet809 Do we need the mlnx-en driver in xCAT-genesis?  Is there a pull request for xcat-dep we should cross reference?

**Comment by zet809** [comment]
The newer mlnx-en driver that Fedora shipped was  required by someone long time several months ago, if I can find suitable driver, I can include it in xCAT-genesis. 
If not, maybe we shall just include the drvier shipped by Fedora26.
The script related to build xcat-genesis-base had been modified in 2.13.4 I think, I will create a new PR for the modification mentioned above.

**Comment by zet809** [comment]
After some search, there is no suitable mlnx-en driver available for Fedora26 ppc64. 
So, for the user have Mlanxo ethernet device to user newer mlx4-en driver, he have to either switch to older xcat-genesis-base when latest xcat is installed or keep using xCAT 2.13.2.
To switch to the older xcat-genesis-base, you have to:

**Comment by zet809** [comment]
I'd like to close this task since #3513 had been opened to trace building genesis-base on latest RH on MN. And the package had been uploaded to GSA. What do you think, @whowutwut ?

**Comment by whowutwut** [comment]
@zet809 Sure, we can close this if tracking the remaining items in another issue.
