### ISSUE TITLE
[PGS support]run new-os-support-bundle for PGS against WSP server

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2934]
1. prepare flat new-os-support-bundle
2. run xcat-test with this bundle to verify the PGS supporting.
3. 2 scenarios: p8->p9, p9->p9

**Comment by zet809** [comment]
All tasks done except p9->p9

**Comment by whowutwut** [comment]
@zet809  Looking at some process in place...  Should this Issues been switched to an Epic so that we can connect issues/pull request to it to track?  Or even should we have linked the PR and Issues to this issue tso that it tracks some work.....

**Comment by zet809** [comment]
Hi, @whowutwut , you are right, I will ask @hu-weihua  to help referencing the PGS support issue number here. 
This task is in the PGS OS support EPIC: #2936 , so I think use this EPIC to trace the PGC support is enough, what is your idea?
