### ISSUE TITLE
Handle case where user defined snmp auth

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#2942]
Discussed a problem with Casandra where we tried to bring in a switch that already had snmp auth defined. This issue to handle defined snmp auth,

**Comment by immarvin** [comment]
hi @markprez @cxhong , what did you plan to do on this ticket?

**Comment by cxhong** [comment]
currently,  xCAT used postscripts "enablesnmp" to config snmp for cumulus switch with default username and password.   If user defined snmp information in the switches table,  enablesnmp postscripts will not pick up and cause switch_macmap function failed and any compute nodes connect to the cumulus switch will not able to discovery.   To fix this,  1) we need to get snmp information from switches table and pass to ```enablesnmp``` postscripts, or 2)  use ```configonie --snmp``` command to send the snmp information to the switch.

**Comment by whowutwut** [comment]
@cxhong If you think this is resolved, we can close it on behalf of Mark.

**Comment by cxhong** [comment]
sure, I think we can close this one
