### ISSUE TITLE
TFTP Open Timeout on Upgrade from xCat 2.6 to 2.10

### ISSUE THREAD

**Issue by jpferraro** [xcat2/xcat-core#2947]
I upgraded from xCAT 2.6 to 2.10 on a RHEL 7.3. Now when I try to start my cluster, the compute nodes report TFTP Open Timeout. I noticed during the upgrade it stated the atftp was obsoleted? What replaced atftp? 

Thanks!
Jeff

**Comment by whowutwut** [comment]
Hi @jpferraro  Can you post the actual error message? 

On RHEL 7,3
```
[root@fs2vm105 ~]# cat /etc/*release* | grep PRETTY
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
[root@fs2vm105 ~]# rpm -qa | grep tftp
tftp-server-5.2-13.el7.ppc64le
tftp-5.2-13.el7.ppc64le
```

**Comment by jpferraro** [comment]
[root@athena-mgmt xcat]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@athena-mgmt xcat]# rpm -qa | grep tftp
tftp-server-5.2-13.el7.x86_64
tftp-5.2-13.el7.x86_64

On the primary compute node console I get the following

CLIENT MAC ADDR: 5C F3 FC A( A8 20 GUID: ......
CLIENT IP: 10.51.163.14 MASK: 255.255.255.0 DHCP IP: 10.51.163.10
GATEWAY IP: 10.51.163.1
PXE-E32: TFTP open timeout
TFTP....

**Comment by whowutwut** [comment]
Can you check if this helps to solve it? http://www.linuxquestions.org/questions/linux-general-1/pxe-tftp-installation-server-504252/#post3361915

**Comment by jpferraro** [comment]
No, that did not help resolve the issue

**Comment by immarvin** [comment]
hi @jpferraro , the ``atftp`` is replaced with ``tftp``, is it ok to upgrade to xCAT 2.13.3? this is the latest stable release.

**Comment by immarvin** [comment]
btw, would you please provide the following information:
1.  the output of `` ps aux --forest|grep -i  -E "xcat|ftp"|grep -v grep`` on MN
2. the node definition by ``lsdef <compute node>``

**Comment by immarvin** [comment]
no response, close it right now, please reopen it if any update
