### ISSUE TITLE
[ xCAT 2.13.2 Centos 7.3 ] Error: unable to get cib

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2952]
I'm trying for `HAMN` in xCAT in Centos 7.3. I have configured `xCAT` and `drbd` working. I'm following official documentation for `HAMN` and `Appendix C` 

`[root@xcat2 xcat]# systemctl status corosync`
`● corosync.service - Corosync Cluster Engine`
 `  Loaded: loaded (/usr/lib/systemd/system/corosync.service; disabled; vendor preset: disabled)`
  ` Active: active (running) since Thu 2017-04-27 12:33:51 IST; 31s ago`
  `Process: 103780 ExecStart=/usr/share/corosync/corosync start (code=exited, status=0/SUCCESS)`
 `Main PID: 103787 (corosync)`
 `  CGroup: /system.slice/corosync.service`
  `         └─103787 corosync`

`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [VOTEQ ] Waiting for all cluster members. Current votes: 1 expected_votes: 2`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [QUORUM] Members[1]: 2`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [MAIN  ] Completed service synchronization, ready to provide service.`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [TOTEM ] A new membership (172.16.0.4:112) was formed. Members joined: 2886729732`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [VOTEQ ] Waiting for all cluster members. Current votes: 1 expected_votes: 2`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [VOTEQ ] Waiting for all cluster members. Current votes: 1 expected_votes: 2`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [QUORUM] Members[2]: 2886729732 2`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103787]:  [MAIN  ] Completed service synchronization, ready to provide service.`
`Apr 27 12:33:51 xcat2.cdac.in corosync[103780]: Starting Corosync Cluster Engine (corosync): [  OK  ]`
`Apr 27 12:33:51 xcat2.cdac.in systemd[1]: Started Corosync Cluster Engine.`

`[root@xcat2 xcat]# pcs cluster setup --local --name xCAT xcat1  xcat2 --force`
`Shutting down pacemaker/corosync services...`
`Redirecting to /bin/systemctl stop  pacemaker.service`
`Redirecting to /bin/systemctl stop  corosync-qdevice.service`
`Failed to stop corosync-qdevice.service: Unit corosync-qdevice.service not loaded.`
`Redirecting to /bin/systemctl stop  corosync.service`
`Killing any remaining services...`
`Removing all cluster configuration files...`

I'm facing issue:

`[root@xcat2 xcat]# pcs cluster cib xcat_cfg`
`Error: unable to get cib`

**Comment by immarvin** [comment]
hi @bybai ,would you please take a look at this? thanks

**Comment by bybai** [comment]
Hi @dspatil7768 , Could the 2 nodes can connect to each other? Is there udp traffic between the 2 nodes?

**Comment by dspatil7768** [comment]
Got it. Thank you. There was lots of confusion for me in documentation. 

`2 nodes and 12 resources configured`

`Online: [ xcat1 xcat2 ]`

`Full list of resources:`

 `ip_xCAT        (ocf::heartbeat:IPaddr2):       Started xcat2`
`apache_xCAT    (ocf::heartbeat:apache):        Started xcat2`
 `db_xCAT        (ocf::heartbeat:mysql): Started xcat2`
`dhcpd  (systemd:dhcpd):        Stopped`
 `Master/Slave Set: ms_drbd_xCAT [drbd_xCAT]`
`     Masters: [ xcat2 ]`
`     Slaves: [ xcat1 ]`
` dummy  (ocf::heartbeat:Dummy): Stopped`
 `xCAT   (lsb:xcatd):    Started xcat2`
` Clone Set: named-clone [named]`
 `    Started: [ xcat1 xcat2 ]`
` Resource Group: grp_xCAT`
 `    fs_xCAT    (ocf::heartbeat:Filesystem):    Started xcat2`
`     symlinks_xCAT      (ocf::tummy:drbdlinks): Started xcat2`

`Daemon Status:`
`  corosync: active/enabled`
 ` pacemaker: active/enabled`
`  pcsd: active/enabled`
