### ISSUE TITLE
[FVT] lsdef can not list all attirbutes In very rare instances

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2957]
Found in automation environment, lsdef can not list all attirbutes In very rare instances. 
It should be a kind of instability of xCAT product.

Below are some log of automation environment, run ``lsdef`` twice and the time interval is 2 seconds, without any other operation,  in the second time, the ``status`` and ``statustime`` attributes are failed to be listed.

    ====================================================
    [Date]       2017-04-27 10:50:32
    [ClientType] cli
    [Request]    lsdef -l c910f03c11k17
    [Response]
    Object name: c910f03c11k17
        arch=ppc64el
        cons=kvm
        currchain=boot
        currstate=boot
        groups=all
        id=17
        mac=42:af:0a:03:0b:11
        mgt=kvm
        monserver=c910f03c11k15
        netboot=grub2
        nfsserver=c910f03c11k15
        os=ubuntu14.04.4
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        profile=compute
        provmethod=ubuntu14.04.4-ppc64el-install-compute
        serialflow=hard
        serialport=0
        serialspeed=115200
        status=booted
        statustime=04-27-2017 10:47:37
        tftpserver=c910f03c11k15
        vmcpus=4
        vmhost=c910f03c11
        vmmemory=8192
        vmnicnicmodel=virtio-net-pci
        vmnics=br10
        vmstorage=phy:/dev/mapper/vdiskvg-vdisk00n17
        xcatmaster=c910f03c11k15
    [ElapsedTime] 0 s
    ====================================================
    [Date]       2017-04-27 10:50:34
    [ClientType] cli
    [Request]    lsdef -l c910f03c11k17
    [Response]
    Object name: c910f03c11k17
        arch=ppc64el
        cons=kvm
        currchain=boot
        currstate=boot
        groups=all
        id=17
        mac=42:af:0a:03:0b:11
        mgt=kvm
        monserver=c910f03c11k15
        netboot=grub2
        nfsserver=c910f03c11k15
        os=ubuntu14.04.4
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        profile=compute
        provmethod=ubuntu14.04.4-ppc64el-install-compute
        serialflow=hard
        serialport=0
        serialspeed=115200
        tftpserver=c910f03c11k15
        vmcpus=4
        vmhost=c910f03c11
        vmmemory=8192
        vmnicnicmodel=virtio-net-pci
        vmnics=br10
        vmstorage=phy:/dev/mapper/vdiskvg-vdisk00n17
        xcatmaster=c910f03c11k15
    [ElapsedTime] 0 s
    ====================================================

**Comment by chenglch** [comment]
Could not get any useful information/steps from the description and could not locate where the error is , remove 2.13.4 milestone label.

**Comment by robin2008** [comment]
Just leave it as a bug

**Comment by whowutwut** [comment]
@robin2008 Can we provide some information as to why we decided to leave as a bug and not fix it?

**Comment by robin2008** [comment]
chenglong/weihua did many investigations on it,  it is hard to reproduce in a real environment with admin operations.

The only seen place is that when we run it in scripts for thousands times in a short time, so we treat it as very low priority and the effort is large to find the cause and fix it.

And then for such issue which has no impact and effort is large, we decide not to fix it and go with risk.

Of course, if there are customer really hit the problem, we can re-open it.
