### ISSUE TITLE
[FVT] simplify the usage of  xcattest config file

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#2958]
what to do:
    simplify the usage of xcattest
    Add more searching function

**Comment by whowutwut** [comment]
@gurevichmark If you try out the `xcattest` script and you have some comments about usability and the help... we can provide it here...

**Comment by gurevichmark** [comment]
@hu-weihua I am trying to understand the structure and format of the `xcattest` command.
I can run `xcattest -c xdcp -l` and get the list of testcases that will test `xdcp` command:
```
[root@stratton01 tmp]# xcattest -c xdcp -l
xdcp_h
xdcp_V
xdcp_src_dst
xdcp_P_src_dst
xdcp_RP
xdcp_R
xdcp_all_files_of_dir
xdcp_rsync
xdcp_rsyncfile_single_file
xdcp_rsyncfile_files
xdcp_rsyncfile_files_changename
xdcp_nonroot_user
[root@stratton01 tmp]#
```

But I do not understand how to use `-t` option. For example:
```
[root@stratton01 tmp]# xcattest -t xcatd_start -l
xcatd_start
[root@stratton01 tmp]#
```
What is this trying to show me ?

**Comment by hu-weihua** [comment]
@whowutwut and @gurevichmark , I am trying to refactor ``xcattest`` script, the 80% code have been down, I plan to pull request before next Monday. I will show the detailed usage of new ``xcattest`` in the post box of pull request. Welcome any comment

**Comment by gurevichmark** [comment]
@hu-weihua Ok, I will wait. Once you are done with the changes, perhaps you can point me to the machine when your code is running. I can then try to use `xcattest` and give you feedback on usability.

**Comment by whowutwut** [comment]
@hu-weihua One UseCase that I was trying to find today is testcases that deal with regular expression.  I was unable to do so easily by using xcattest.  

We can list out the commands, but that is it.. .we can't drill down to the testcase level.  And even if we did, it doesn't display any "description:" tags.. so what is the purpose of the description entry?  My solution was just using grep... 

```
cd /opt/xcat/share/xcat/tools/autotest/testcase
[root@fs3 testcase]# grep -R "start:"  | grep regex
mkdef/cases1:start:mkdef_regex_bmc
mkdef/cases1:start:mkdef_regex_ip
mkdef/cases1:start:mkdef_regex_kvm
```
Even looking at the descrption, there's nothing that says anything about regular expression...
```
[root@fs3 testcase]# grep -R "description:" | egrep "regex|regular"
[root@fs3 testcase]#
```

**Comment by hu-weihua** [comment]
@whowutwut , We do support ``description`` label in test case to describe the usage of case. But unfortunately, we did not add description for every case in the past. I have told FVT must add description when she/he add a new test case. I will plan to add description for the old case.

**Comment by hu-weihua** [comment]
Have finished by PR#3048
