### ISSUE TITLE
[openbmc] From xCAT's point of view, need to be able to understand when the state is "ready" 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2969]
In the ipmi based IBM OpenPower S822LC machines, we were given a command to test that the BMC is ready before executing commands on it.  This happens when we have to flash the firmware or whenever the `mc reset cold` command is issued to reset the BMC. 

The command is: `raw 0x3a 0x0a`

However, with the openbmc firmware, if we reboot the BMC, the machine responds to ssh very quickly, but the services are not up that would provide response for the restful queries, and/or respond to `obmcutil`.  

xCAT needs to handle this. 

```
root@p9euh01-bmc:~# uptime
 17:30:24 up 1 min,  load average: 4.41, 1.27, 0.44

root@p9euh01-bmc:~# obmcutil power state

Traceback (most recent call last):
  File "/usr/sbin/obmcutil", line 154, in <module>
    obj = bus.get_object(bus_name, obj_path)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.openbmc.control.Power was not provided by any .service files
root@p9euh01-bmc:~#
```

**Comment by zet809** [comment]
hi, @xuweibj , will you pls help to check this issue, if it still occurs, we shall ask Firmware team for help. Thx!

**Comment by zet809** [comment]
hi, @whowutwut , so the question changes to is there an interface to check the RESTful service status on OpenBMC right? We can not ssh to OpenBMC to check that.
I had noticed that the ipmi command will be ready once the BMC is pingable. But the raw command "0x3a 0x0a" is unsupported. 
So, is it possible to ask Firmware team to provide this ipmi raw command?

**Comment by whowutwut** [comment]
Yes, let's bring it up today.

**Comment by whowutwut** [comment]
@zet809  I'm not sure that we need to reset the BMC for openbmc.  We should attempt to call ReST and until we get back `OK 200` we will just block... or wait...    Is this sufficient?

**Comment by zet809** [comment]
I think this is fine. I had tried 'curl' to login the OpenBMC after reboot, after the IP is pingable, the curl request will hung and returned "200 OK" in the end.

**Comment by zet809** [comment]
hi, @whowutwut and @gurevichmark , will this step be included in rflash?

**Comment by gurevichmark** [comment]
Not sure about `rflash` yet. BMC team was talking about some "progress indicator" that we can monitor after firmware update.

**Comment by zet809** [comment]
hi, @whowutwut and @gurevichmark , we have `rpower bmcstate` to check the status of BMC like this, so can we close this issue?
```
[root@briggs01 ~]# rpower p9up bmcstate
mid05tor12cn18: Error: BMC did not respond within 10 seconds, retry the command.
mid05tor12cn13: BMC Ready
mid05tor12cn16: BMC Ready
mid05tor12cn11: BMC Ready
mid05tor12cn15: BMC Ready
mid05tor12cn02: BMC Ready
mid05tor12cn05: BMC Ready
```

**Comment by whowutwut** [comment]
Yes, @zet809 Let's close it...
