### ISSUE TITLE
Readthedocs - "Setup the MN Hierarchical Database" has broken links

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#297]
http://xcat-docs.readthedocs.org/en/latest/advanced/hierarchy/setup_mn_hierachical_database.html#mysql-or-mariadb

The links on this page take user to "localhost/fake_todo" page

Perhaps they should link to 
http://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/large_clusters/databases/index.html
or maybe the two pages should be combined in some fashion.

**Comment by whowutwut** [comment]
@pdlun92  Feel  free to close this issue
