### ISSUE TITLE
[ xCAT 2.13.2 Centos 7.3 ] DHCP server not starting

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#2976]
I'm trying for HAMN. Another failover is working fine i.e.`http`. I don't know why DHCP server is not starting. I have configured it on `virtual IP`. And when I change to private IP instead of virtual one it works fine. 

- `[root@xcat2 ~]# ip a`
`enp6s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000`
  `link/ether 00:1e:67:29:01:7a brd ff:ff:ff:ff:ff:ff`
` inet 172.16.0.5/16 brd 172.16.255.255 scope global enp6s0f0`
` valid_lft forever preferred_lft forever`
` inet 172.16.0.6/16 brd 172.16.255.255 scope global secondary enp6s0f0:0`
` valid_lft forever preferred_lft forever`
 ` inet6 fe80::21e:67ff:fe29:17a/64 scope link`
` valid_lft forever preferred_lft forever`

- `tabdump site`:
`[root@xcat2 ~]# tabdump site`
`"dhcpinterfaces","enp6s0f0:0",,`

- `tabdump networks`
`[root@xcat2 ~]# tabdump networks`
`#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable`
`"10_208_34_0-255_255_254_0","10.208.34.0","255.255.254.0","enp6s0f1","10.208.34.1",,,,,,,,,,,,,,,`
`"172_16_0_0-255_255_0_0","172.16.0.0","255.255.0.0","enp6s0f0:0","172.16.0.6","172.16.0.6","172.16.0.6","172.16.0.6",,,"172.16.0.50-172.16.0.100",,,,,,,,,`

Whereas 
- `10.208.34.0` is public network
- `172.16.0.0` is private network

`[root@xcat2 ~]# service dhcpd status`
`Redirecting to /bin/systemctl status dhcpd.service`
`● dhcpd.service - DHCPv4 Server Daemon`
 ` Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; disabled; vendor preset: disabled)`
` Active: failed (Result: exit-code) since Wed 2017-05-03 19:04:32 IST; 19s ago`
 ` Docs: man:dhcpd(8)`
` man:dhcpd.conf(5)`
` Process: 72566 ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid (code=exited, status=1/FAILURE)`
` Main PID: 72566 (code=exited, status=1/FAILURE)`

`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]: ** Ignoring requests on enp6s0f0:0. If this is not what`
`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]: you want, please write a subnet declaration`
`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]: in your dhcpd.conf file for the network segment`
`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]: to which interface enp6s0f0:0 is attached. **`
`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]:`
`May 03 19:04:32 xcat2.cdac.in dhcpd[72566]:`
`May 03 19:04:32 xcat2.cdac.in systemd[1]: dhcpd.service: main process exited, code=exited, status=1/FAILURE`
`May 03 19:04:32 xcat2.cdac.in systemd[1]: Failed to start DHCPv4 Server Daemon.`
`May 03 19:04:32 xcat2.cdac.in systemd[1]: Unit dhcpd.service entered failed state.`
`May 03 19:04:32 xcat2.cdac.in systemd[1]: dhcpd.service failed.`

Suggest if I'm going wrong.

**Comment by immarvin** [comment]
hi @dspatil7768 , from the log in ``service dhcpd status``, it seems there is some error in /etc/dhcp/dhcpd.conf, have you run ``makedhcp -n`` after change?

**Comment by dspatil7768** [comment]
Yes I did it. `makedhcp -n`,`makedhcp all` and `service dhcpd restart`

**Comment by immarvin** [comment]
is it ok to attach the /etc/dhcp/dhcpd.conf ?

**Comment by immarvin** [comment]
no response over 2 weeks, close this first, please reopen it if any update
