### ISSUE TITLE
Create simulation environment for OpenBMC hardware test

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#2987]
supported commands: rpower/rsetboot/rspconfig (not ip)
bmcdiscover: listening on 2200
rinv,rvitals,reventlog

**Comment by xuweibj** [comment]
https://github.com/xuweibj/openbmc_simulator

**Comment by whowutwut** [comment]
@xuweibj  Some comments on your README.md file from the above link.

- In Git, you can `chmod +x simulator` , then commit it, and it will retain the execute permission
- The README can simply be to "clone the repo"  then the steps will be reduced to cloning and running `./simulator`

**Comment by xuweibj** [comment]
@whowutwut Thank you for your comments. I have modified.
