### ISSUE TITLE
[fvt]2.11 makedhcp -n return error info in rhel7 enviroment 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#299]
How to reproduce:
[root@c910f02c01p13 ~]# cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.0 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.0"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.0 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0
Red Hat Enterprise Linux Server release 7.0 (Maipo)
Red Hat Enterprise Linux 
[root@c910f02c01p13 ~]# lsdef -v
lsdef - Version 2.11 (git commit b1dff58244d7c51a7ddc061b8befa6261fc0dd77, built Thu Oct 22 06:17:32 EDT 2015)
[root@c910f02c01p13 ~]# makedhcp -n
Renamed existing dhcp configuration file to  /etc/dhcp/dhcpd.conf.xcatbak

Error: The file /etc/sysconfig/dhcpd6 doesn't exist, check the dhcp server
--------------------------------------> error info here.
[root@c910f02c01p13 ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","eth0","10.2.1.12",,"10.2.1.13",,,,,,,,,,,,
"fd03:2e76:8631::/64","fd03:2e76:8631::/64","/64","eth0",,,,,,,,,,,,,,,
[root@c910f02c01p13 ~]# ls -al /etc/sysconfig/dhcpd6
ls: cannot access /etc/sysconfig/dhcpd6: No such file or directory
[root@c910f02c01p13 ~]# 
[root@c910f02c01p13 ~]# ls -al /etc/sysconfig/dhcpd6
ls: cannot access /etc/sysconfig/dhcpd6: No such file or directory
[root@c910f02c01p13 ~]# 
[root@c910f02c01p13 ~]# ls -al /etc/sysconfig/dhcpd6
ls: cannot access /etc/sysconfig/dhcpd6: No such file or directory
--------------->could not find such file 
[root@c910f02c01p13 ~]#

**Comment by immarvin** [comment]
hi, on redhat7,

the dhcp configuration is different from the previous release in the following aspects:

# If you are here to restrict what interfaces should dhcpd listen on,
# be aware that dhcpd listens *only* on interfaces for which it finds subnet
# declaration in dhcpd.conf. It means that explicitly enumerating interfaces
# also on command line should not be required in most cases.

**Comment by whowutwut** [comment]
I think I made the last change for this in https://sourceforge.net/p/xcat/bugs/3832/, but it looks like RHEL7 dhcp is more similar to SLES 11 in terms of the ``/etc/sysconfig/dhcpd`` being a common shared file for dhcpd and dhcpd6 config ..
