### ISSUE TITLE
Verify confignetwork MTU support 

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#2991]
For task #2604, pull request is #2973  
1,  Add mtu value into networks table for one specific network;
2, Execute confignetowork to configure vlan/bridge/bond using the same network in 1
3, Check mtu for vlan/bridge/bond on CN, check the ifcfg-*(vlan/bridge/bond) with "MTU=<value>"

Example:
1, configure ethernet static ip:
```
[root@byrh13 ~]# lsdef bytest15 -i nicips.eth1,nicnetworks.eth1,nictypes.eth1
Object name: bytest15
    nicips.eth1=10.4.41.15
    nicnetworks.eth1=10_0_0_0-255_0_0_0
    nictypes.eth1=ethernet
[root@byrh13 ~]# updatenode bytest15 confignetwork
[root@byrh13 ~]# xdsh bytest15 ip a
[root@byrh13 ~]# xdsh bytest15 "cat /etc/sysconfig/network-scripts/ifcfg-eth1"
```
2, confgure bridge:
```
[root@byrh13 /]# lsdef bytest15 |grep nic
    ...
    nicdevices.br0=eth1
    nicips.br0=10.4.41.15
    nicnetworks.br0=10_0_0_0-255_0_0_0
    nictypes.eth1=ethernet
    nictypes.br0=bridge
    ...
[root@byrh13 ~]# updatenode bytest15 confignetwork
[root@byrh13 ~]# xdsh bytest15 ip a
[root@byrh13 ~]# xdsh bytest15 "cat /etc/sysconfig/network-scripts/ifcfg-eth1"
[root@byrh13 /]# xdsh bytest15 "cat /etc/sysconfig/network-scripts/ifcfg-br0"
```

**Comment by daniceexi** [comment]
@bybai do we have plan to make a test case to cover this test?

**Comment by bybai** [comment]
Hi @daniceexi , task #2997 is for add test case for confignetwork. I put it into blacklog.

**Comment by neo954** [comment]
Verified with the latest daily build, version `2.13.4-snap201705110615`.
