### ISSUE TITLE
Help with passing in log_buf_len=4M to kernel parameter and persist reboot

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2995]
Wondering how we can pass in the kernel attribute `log_buf_len` into the OS to persist on reboot. 

RHEL 7.X ppc64le was my test environment

### Issue 1: We need to put this documentation into RTD.. I don't think it's there. 

I found this document on SF: https://sourceforge.net/p/xcat/wiki/Installing_Stateful_Linux_Nodes/
Found a similar page on GitHub Wiki with similar content: https://github.com/xcat2/xcat-core/wiki/supporting_persistent_kernel_cmdline_after_diskful_installation

### Issue 2, how do we get this into the kernel params to persist on reboot? 

Looking into this problem it seems that when I set ``R::log_buf_len=4M`` to ``addkcmdline``: 
```
[root@c910f02c05p03 ~]# lsdef fs2vm105 -i addkcmdline
Object name: fs2vm105
    addkcmdline=modprobe.blacklist=nvidiafb,R::net.ifnames=0,R::log_buf_len=4M
```

The kernel parameter does not go down into the configuration:
```
[root@fs2vm105 ~]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.ppc64le root=/dev/mapper/system-root ro crashkernel=auto rd.lvm.lv=system/root console=hvc0,115200 net.ifnames=0
```

### Issue 3, how to confirm the value is being set, regardless of using xCAT....

Then if i force this configuration into `grub.cfg` and then reboot the node, I do see it in `/proc/cmdline` but the effective value is not changed...  still SHIFT is 20...  should be 22 for 4M.... 
```
# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.ppc64le root=/dev/mapper/system-root ro crashkernel=auto rd.lvm.lv=system/root console=hvc0,115200 net.ifnames=0 log_buf_len=4M <=== SEE IT HERE... 

# grep CONFIG_LOG_BUF_SHIFT /boot/config-*
CONFIG_LOG_BUF_SHIFT=20
#  perl -e 'printf "%d KiB\n",(1<<20)/1024'
1024 KiB
```

**Comment by immarvin** [comment]
hi @whowutwut , ``/boot/config-<uname -r>`` is the kernel config file which was used to built the current kernel, it is shipped  with kernel rpm.  According to the https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/Documentation/kernel-parameters.txt?id=refs/tags/v3.10.105, 
````
log_buf_len=n[KMG]	Sets the size of the printk ring buffer,
			in bytes.  n must be a power of two.  The default
			size is set in the kernel config file.
````

**Comment by immarvin** [comment]
the ``addkcmdline`` entries should be delimited with space `` `` instead of ``,``.

this is what i tried in my env:

on mn:
````
[root@c910f03c11k09 ~]# lsdef c910f03c11k11 -i addkcmdline
Object name: c910f03c11k11
    addkcmdline=inst.sshd R::net.ifnames=0 R::netwait=60 R::log_buf_len=4M
````

on the installed node:
````
[root@c910f03c11k11 ~]# cat /boot/grub2/grub.cfg |grep buf
        linux /vmlinuz-3.10.0-514.el7.ppc64le root=/dev/mapper/system-root ro net.ifnames=0 netwait=60 log_buf_len=4M crashkernel=auto rd.lvm.lv=system/root con                                                 nsole=hvc0,115200n8r LANG=en_US.UTF-8
        linux /vmlinuz-0-rescue-4afe4c3f66a3486481952a2994b644cc root=/dev/mapper/system-root ro net.ifnames=0 netwait=60 log_buf_len=4M crashkernel=auto rd.lvm

[root@c910f03c11k11 ~]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.ppc64le root=/dev/mapper/system-root ro net.ifnames=0 netwait=60 log_buf_len=4M crashkernel=auto rd.lvm.lv=system/root consolle=hvc0,115200n8r LANG=en_US.UTF-8
[root@c910f03c11k11 ~]#
````

**Comment by whowutwut** [comment]
Thanks @immarvin  I was also able to re-create it.  It seems like the config file sets the default and it overrides, so maybe we won't see the CONFIG_LOG_BUF_SHIFT change..   Let me talk to Wes and if it's OK will close this issue out.

**Comment by whowutwut** [comment]
Closing for now, I think it's ok. Will open if issues re arise
