### ISSUE TITLE
RHEL update caused boot failure due to selinux

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2996]
I updated our RHEL 7.3 repositories to pick up recent security updates.  The node failed to boot with the following message:

```
[Fri May  5 16:25:38 2017][   31.941132] systemd-journald[906]: Received SIGTERM from PID 1 (systemd).
[Fri May  5 16:25:38 2017][   31.955732] type=1404 audit(1494015917.470:2): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
[Fri May  5 16:25:38 2017][   32.001858] systemd[1]: Failed to load SELinux policy.
[Fri May  5 16:25:38 2017][!!!!!!] Failed to load SELinux policy, freezing.
```

I tracked down what changed, and apparently sssd-common now requires selinux-policy

```
* Fri Feb 03 2017 Jakub Hrozek <jhrozek@redhat.com> - 1.14.0-43.13
- Resolves: rhbz#1418943 - If a long-running task (e.g. enumeration) blocks the
                           sssd_be process, sssd_be can deadlock
- Also Require a new-enough version of selinux-policy so that setpgid() by sssd
  is allowed
```

Is xCAT expected to work with selinux?  I worked around this by adding *selinux=0* to addkcmdline.    I found a postinstall script that updates /etc/selinux/config, is that the preferred method?

**Comment by immarvin** [comment]
seems similar situation with issue https://github.com/xcat2/xcat-core/issues/1666

xCAT expect selinux to be disable, xCAT will disable selinux on xCAT MN, we also disabled selinux on diskless node to fix the issue above.

do you mean ``xCAT-server/share/xcat/netboot/rh/compute.rhels7.xxxx.postinstall``? it's for diskless.

seems we might need to disable selinux on diskful nodes since selinux might be installed/updated by default

**Comment by mattaezell** [comment]
We are running diskless, but we have a custom postinstall script that does other stuff (enable non-default services, fixup some config files, etc).  I guess we aren't running the default stuff which you expect will handle this, so I guess it's our responsibility to integrate the existing postscript into our running config (and watch it for updates between versions, since it evolves over time).  The other option is that xCAT unconditionally passes *selinux=0* on the kcmdline so sed in a postscript is not needed

**Comment by immarvin** [comment]
maybe passing `` selinux=0`` kernel option is better than word substitution in compute.rhels7.ppc64.postinstall file. we will consider this in the following release. thanks @mattaezell

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/3140
