### ISSUE TITLE
The cookie_jar option used in HTTP::Async for openbmc doesn't work on ubuntu14.04.x

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3019]
root@xcat-1395471020-gnx6m:/opt/xcat# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@xcat-1395471020-gnx6m:/opt/xcat# XCAT_OPENBMC_DEVEL=YES rpower wspoon009 state
Warning: Currently running development code, use at your own risk.  Unset XCAT_OPENBMC_DEVEL to disable.
Error: openbmc plugin bug, pid 1786, process description: 'xcatd SSL: rpower to wspoon009 for root@localhost: openbmc instance' with error 'cookie_jar not valid for _set_opt at /usr/share/perl5/HTTP/Async.pm line 182, <$parfd> line 1.
' while trying to fulfill request for the following nodes: wspoon009
root@xcat-1395471020-gnx6m:/opt/xcat# dpkg -l | grep libhttp-async-perl
ii  libhttp-async-perl               0.23-1                                     all          module for parallel non-blocking processing of multiple HTTP requests

It works on RH7.3 with perl-HTTP-Async-0.30-2.noarch

**Comment by zet809** [comment]
The pkg //ftp.us.debian.org/debian/pool/main/libh/libhttp-async-perl/libhttp-async-perl_0.26-1_all.deb works.

**Comment by zet809** [comment]
hi, @xuweibj , pls help to check with ubuntu 16.04

**Comment by xuweibj** [comment]
On Ubuntu16.04.1 the async is newer version, does not have this problem.
```
# dpkg -l | grep libhttp-async-perl
ii  libhttp-async-perl                 0.30-1                                     all          module for parallel non-blocking processing of multiple HTTP requests
```

Close this.
