### ISSUE TITLE
[FVT] Command nodeset failed with "Unable to determine the image server"

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#302]
The management node runs Red Hat 7.2 Snapshot2 ppc64le. The xCAT build is the early build of 2.11.

When I run the ``nodeset`` command, I got an weird error message I did not understand.

    [root@c910f03c01p19 ~]# nodeset c910f05c35 osimage=compute_1543a
    c910f05c35: install rhels7.2snapshot2-ppc64le-compute
    Error: : Unable to determine the image server for c910f05c35

    [root@c910f03c01p19 ~]# rpm -qa | grep -i xcat
    grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
    ipmitool-xcat-1.8.11-3.ppc64le
    xCAT-buildkit-2.11-snap201510220202.noarch
    xCAT-client-2.11-snap201510220202.noarch
    xCAT-genesis-scripts-ppc64-2.11-snap201510220202.noarch
    conserver-xcat-8.1.16-10.ppc64le
    perl-xCAT-2.11-snap201510220202.noarch
    xCAT-server-2.11-snap201510220202.noarch
    xCAT-genesis-base-ppc64-2.10-snap201505172314.noarch
    xCAT-2.11-snap201510220202.ppc64le

Here is the node definition and osimage definition.

    [root@c910f03c01p19 ~]# lsdef c910f05c35
    Object name: c910f05c35
        arch=ppc64le
        bmc=50.5.35.1
        bmcpassword=abcxyz
        bmcusername=ADMIN
        cons=ipmi
        currchain=boot
        currstate=install rhels7.2snapshot2-ppc64le-compute
        groups=pkvm,all
        hidden=0
        initrd=xcat/osimage/compute_1543a/initrd.img
        installnic=mac
        ip=10.5.35.254
        kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.2snapshot2/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/c910f05c35 BOOTIF=98:be:94:59:fa:cf  ip=dhcp  inst.cmdline  console=tty0 console=ttyS0,115200
        kernel=xcat/osimage/compute_1543a/vmlinuz
        mac=98:be:94:59:fa:cf
        mgt=ipmi
        netboot=petitboot
        nodetype=mp
        os=rhels7.2snapshot2
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        primarynic=mac
        profile=compute
        provmethod=compute_1543a
        serialport=0
        serialspeed=115200
        status=installing
        statustime=10-22-2015 21:28:49
    [root@c910f03c01p19 ~]# lsdef -t osimage compute_1543a
    Object name: compute_1543a
        imagetype=linux
        osarch=ppc64le
        osdistroname=rhels7.2snapshot2-ppc64le
        osname=Linux
        osvers=rhels7.2snapshot2
        otherpkgdir=/install/post/otherpkgs/rhels7.2snapshot2/ppc64le
        pkgdir=/install/rhels7.2snapshot2/ppc64le
        pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
        profile=compute
        provmethod=install
        template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

**Comment by zet809** [comment]
It is because the node can not be resolved by DNS server. But need to modify the error msg.

**Comment by zet809** [comment]
Hi, Xu wei, will you pls help to have a look at?

**Comment by xuweibj** [comment]
The return info for my_ip_facing is an array with the following information:
[<return_code>, <info0>,<info1>]
For example:  
1. If node can not be resolved, the return info will be like this:
[1, "The $node can not be resolved"].
2. If no IP found that matching the giving node, the return info will be:
[2, "No found matching IP for $node"].
3. If IP found:
[0, <ip1>, <ip2>...]

**Comment by neo954** [comment]
Will verify it later.

**Comment by whowutwut** [comment]
@neo954 Should this be moved to 2.11.1 or leave in 2.11 ?

**Comment by daniceexi** [comment]
Change to 2.11.1 is useful for later search to know which release includes this fix.

**Comment by neo954** [comment]
The bug is not fixed properly. Removed the pending label.

**Comment by neo954** [comment]
If the node was defined but cannot be DNS resolved. I can get a proper error message.

    [root@c910f02c03p27 ~]# nodeset c910f02c03p99 osimage=rhels7.2-ppc64-install-compute 
    c910f02c03p99: install rhels7.2-ppc64-compute
    Error: The c910f02c03p99 can not be resolved
    [root@c910f02c03p27 ~]# host c910f02c03p99
    Host c910f02c03p99 not found: 3(NXDOMAIN)

If the node was defined and can be DNS resolved, but the IP address is in another subnet which the xCAT server does not know. The strange error message is still there.

    [root@c910f02c03p27 ~]# nodeset c910f02c03p99 osimage=rhels7.2-ppc64-install-compute
    c910f02c03p99: install rhels7.2-ppc64-compute
    Error: : Unable to determine the image server for c910f02c03p99
    [root@c910f02c03p27 ~]# host c910f02c03p99
    c910f02c03p99 has address 172.18.3.99

**Comment by neo954** [comment]
@xuweibj, I wrote a few comments in your original pull request #386. Please take a look.

https://github.com/xcat2/xcat-core/pull/386/files

**Comment by xuweibj** [comment]
#879 @neo954

**Comment by neo954** [comment]
Okay, close this one.
