### ISSUE TITLE
[zz support]FSP2 investigate for zz

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3031]
Acceptance:
1. ctrl FSP2 through HMC
   verify hardware ctrl command for FSP2 through HMC
   rpower,rcons
2. Check can switch to OPAL mode
3. What new feature are provided by FSP2?

Reference https://github.ibm.com/vhu/c910env/issues/52 for more information.

**Comment by neo954** [comment]
Prerequisite
* Require HMC version V8R8.7.0
* The zz machine needs firmware updating (pending)

Verified the following xCAT features worked.
* `rpower` works
* `rscan` works
* `getmacs` works
* `rcons` works
* `nodeset` works
