### ISSUE TITLE
[openbmc] rinv command returns scattered data and usage is not correct

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3034]
I'm trying to see what commands we can start to expose.  I think rinv might be a good one, but it's still very messy in the output and the man pages/usage is not cleaned up.  

Few issues I see when I run the rinv command against openbmc. 

### The man page shows options that do not work for openbmc

 can we update the man page to reflect what is currently working, or the options that plan to be supported. 
```
   OpenPOWER server specific:
       rinv noderange {model|serial|deviceid|uuid|guid|vpd|mprom|firm|all}
```

If we plan to leave all the options,that is OK, but we should probably print a message that no information obtained  instead of returning blank...  

### The output of the openbmc node does not order any of the data

If you compare the output of rinv with P8 openpower machines and what is being printed in openbmc, the data is not sorted in any way.  CPU/PSU/DIMM information is all inter mixed together.  Can we go a better job with the formatting here so we can start to expose some of the commands to the user?

**Comment by xuweibj** [comment]
Hi @whowutwut , 
The data we got from firmware is not stable now, so we just print what got and did not filter and order all data. 
For some options ``deviceid|uuid|guid|vpd|mprom`` the code is just framework that we can not get data. I think you are right. We could print a message that no information obtained instead of returning blank.
But if we want to make it the same with ipmi, I think we should wait for firmware is ready.

**Comment by whowutwut** [comment]
Ok, that sounds fine to wait before we remove the options. However, I think we can organize or sort the data better so that it's out is not scattered.  @gurevichmark  If you have some cycles you can also look at this.

**Comment by gurevichmark** [comment]
Taking to do a quick sorted formatting.

**Comment by whowutwut** [comment]
@gurevichmark  The sorting looks good, but I wonder if we should keep this open to verify that the options are correct.  It seems like from the API, we should be able to tell if anything will be supported like GUID/UUID and if not, we should remove them from the usage.

**Comment by gurevichmark** [comment]
Ok, I agree. Lets keep this issue open until we are sure about all supported options.

**Comment by whowutwut** [comment]
Helps with support for rinv in #2664.  I have another pull request open to remove the guid/uuid and fields that are not going to be returned by this openbmc API, so let's close this
