### ISSUE TITLE
Keep man page synopsis and usage output same

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3039]
In several commands' man page we use {} to indicate "one of", but in "usage" output we use [] to indicate "optional".
It should be [] because everything is optional.

**Comment by gurevichmark** [comment]
I think the commands that need the changes should be listed here. Not all xCAT commands need this. 
While reviewing the recent OpenBMC code changes, I found two: `rinv` and `rpower`. 
But they handle flags differently:
For `rinv` all parameters are optional, so `[]` should be used.
For `rpower`, at least one of the options is required, so `{}` should be used.

**Comment by gurevichmark** [comment]
@xuweibj Do you think we should keep this issue open ?

**Comment by xuweibj** [comment]
@gurevichmark I think we could close it. I will close it.
