### ISSUE TITLE
[openbmc]enhance bmcsetup to use ipmi interface "set access on"

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3051]
The task is used to trace the ipmi in-band interface "ipmitool set <channel> access on", we were using "ipmitool raw 0x06 0x40" as recommend in issue [openbmc issue 1565](https://github.com/openbmc/openbmc/issues/1565#issuecomment-299777089).

**Comment by whowutwut** [comment]
@zet809  Could you follow up with the openbmc team again on this one?

**Comment by zet809** [comment]
Seems the interface will be ready in one or two weeks, if no progress in this sprint, I will put it as a low priority issue.

**Comment by zet809** [comment]
hi, @whowutwut , which node have the specified firmware level 'GHE build 8/24'? I need to take a try, if the command is send out and ip had been configured, we can replace raw command with `set access on`, if not, I suggest we don't change it.

```
[xCAT Genesis running on (none) /]# ipmitool lan set 1 access on
IPMI command failed: Command response could not be provided
Unable to Set Channel Access(non-volatile) for channel 1
[xCAT Genesis running on (none) /]#
```

**Comment by whowutwut** [comment]
@zet809 The `node-70e28414280d` under briggs01 has Ratan's development build on it.  Please do NOT define `mid05tor12cn05` into xCAT, we want to leave it in Genesis to more easily do UT and reset to DHCP for now....

You can run it there, but I've documented a great deal of the UT here: https://github.ibm.com/vhu/c910env/issues/135

**Comment by zet809** [comment]
Modified in #3833 , so close this task.
