### ISSUE TITLE
Investigation of the ZTP based discovery and auto configuration of Cumulus switch

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3060]
Background:

1. what is ZTP?
Zero touch provisioning  (ZTP) enables network devices to be quickly deployed in large-scale environments. On first boot, Cumulus Linux will invoke ZTP, which executes the provisioning automation used to deploy the device for its intended role in the network.

The provisioning framework allows for a one-time, user-provided script to be executed. You can develop this script using a variety of automation tools and scripting languages, providing ample flexibility for you to design the provisioning scheme to meet your needs. You can also use it to add the switch to a configuration management (CM) platform such as Puppet, Chef, CFEngine or possibly a custom, proprietary tool.

While developing and testing the provisioning logic, you can use the ztp command in Cumulus Linux to manually invoke your provisioning script on a device.

ZTP in Cumulus Linux can occur automatically in one of the following ways, in this order:

    Via a local file
    Using a USB drive inserted into the switch (ZTP-USB)
    Via DHCP

2. The basic idea of ZTP based switch discovery and auto configuration
Currently, xCAT provides the switch discovery and configuration mechanism initiated from the management node. With the help of ZTP, this discovery and configuration can be initiated by the switch itself on the switch power-on/port plugin, the process is like this: the cumulus switch request a ZTP script from MN via DHCP  request, then invoke the script on the switch. This script can be something like "findme" in xcat node discovery, The switch will report some switch information about itself to MN and create/update the switch definition on the MN, then initiate a configuration script or request from MN.  

Acceptance Criteria:
1.  A feasible work manual flow of ZTP based discovery and auto configuration of Cumulus switch
2.  mini-design of the ZTP based discovery and auto configuration

Difficulties:
1. how to trigger the ZTP process on a cumulus switch with OS provisioned and licence file installed?

see https://github.com/xcat2/xcat-core/issues/2662

**Comment by cxhong** [comment]
the ztp is disable if license is already installed.
````
cumulus@cumulus:~$ sudo systemctl -l status ztp.service
● ztp.service - Cumulus Linux ZTP
   Loaded: loaded (/lib/systemd/system/ztp.service; enabled)
   Active: inactive (dead) since Tue 2017-05-16 12:34:12 UTC; 13min ago
     Docs: man:ztp(8)
 Main PID: 1328 (code=exited, status=2)

May 16 12:34:07 cumulus systemd[1]: Started Cumulus Linux ZTP.
May 16 12:34:09 cumulus ztp[1328]: ztp [1328]: Switch has already been configured. /var/log/dpkg.log was modified
May 16 12:34:09 cumulus ztp[1328]: ztp [1328]: ZTP will not run
May 16 12:34:09 cumulus ztp[1328]: Removed symlink /etc/systemd/system/multi-user.target.wants/ztp.service.
May 16 12:34:11 cumulus ztp[1328]: ztp [1328]: ZTP disabled
May 16 12:34:12 cumulus ztp[1328]: ztp [1328]: Exiting and disabling ZTP...
````
To enable the ZTP, needs to run
```
sudo ztp -e
```
To Reset ZTP, This removes the ztp directory and ztp runs the next time the switch reboots.
```
sudo ztp -R
sudo reboot
````
if we define ztp code to the dhcpd.conf, it will pick up ztp scripts and runs on cumulus switch
```
option cumulus-provision-url code 239 = text;
option cumulus-provision-url  "http://172.21.253.27/install/onie/ztp.sh";
```

**Comment by cxhong** [comment]
for pre-installed cumulus switch, we have to get to switch and trigger the ZTP process.
@immarvin , I agree your idea addressed in the #3085 .  Let's use @mattaezell 's dhcp-eval process.

By the way, the 1st dhcp request package doesn't include  vendor-class-identifier, I guess we have to use mac address to identifier the cumulus switch.

**Comment by immarvin** [comment]
composed a script to obtain switch information and send "findme" request to xcatd to initiate the discovery process

**Comment by immarvin** [comment]
the tcpdump file of ZTP on reboot:
![ztplog](https://cloud.githubusercontent.com/assets/5668922/26396604/46b3197c-40a6-11e7-9794-0b3de000d16a.png)

the tcpdump file of "ztp -r xxxx"
![ztplog r](https://cloud.githubusercontent.com/assets/5668922/26396637/62d26540-40a6-11e7-8c0a-1f031adf2a48.png)

**Comment by immarvin** [comment]
updated https://github.com/xcat2/xcat-core/pull/3129 , the switch can be discovered with the "documulusdiscover", 

todo: chain the autoconfiguration with the discovery

**Comment by immarvin** [comment]
the mini design has been send out and discussed internally.
