### ISSUE TITLE
[New xCAT prototype]build ansible playbook to setup xcat3 service

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3067]
Acceptance:
1. git clone xcat3 codes onto hosts, start and configure xcat3 service
2. configure apache and dhcp, tftp, mysql/mariaDB service

**Comment by whowutwut** [comment]
@zet809 I don't think we should just close tasks like these... There's been no information provided or any documentation linked.  There's no value for this issue except for tracking single tasks that really have no evidence that anything was completed...   How does one go about looking at any of the effort that was done for this?   There's no pull request or any progress indication....

**Comment by chenglch** [comment]
Append the link here:

A repo for xcat playbook, https://github.com/chenglch/xcat-play. There is readme page to describe how to setup ansible on ubuntu or redhat system.  The readme link also contains a link https://github.com/chenglch/xcat-play/blob/master/ansible/xcat3/README.rst to redirect to the playbook page for xcat3.

**Comment by zet809** [comment]
hi, @whowutwut , you are right that I shall keep the issue open until Pull Request, document and anything that this task need covered are finished and attached. Thx for the reminder.
