### ISSUE TITLE
add doc how to configure routes using makeroutes or setroutes

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3070]
Add doc
1, how to configure routes using makeroutes
2, how to configure routes using setroutes

**Comment by bybai** [comment]
I got several issues about how to `configure routes using xcat`, should add doc about this basic xcat usage.

**Comment by whowutwut** [comment]
@bybai (@cxhong also getting asked some questions on this) Is there any documentation on how to set the default route to a different network?  It seems like in some instances, there's a route to the public network, but we want the compute nodes to set their default route to the network that provisioned it...

**Comment by bybai** [comment]
Hi @whowutwut , Plan to add doc within this sprint.
