### ISSUE TITLE
[xCAT 2.9.1] DHCP issue with relayed requests before Discovery.

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3074]
Problem: I'm attaching new inventory into our environment and need to do discovery for the nodes. The nodes are being attached to 2 switches, first one configured with subnet `10.81.105.0/24` and the second one with `10.81.107.0/24`. However, DHCPd is sending incorrect IP addresses to the hosts on subnet `10.81.107.0/24` which causes them to fail to boot genesis.

OS configuration:
```
[vndc:samveen@xcatmn1 ~]$ uname -a
Linux xcatmn1.vndc 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[vndc:samveen@xcatmn1 ~]$ cat /etc/system-release
CentOS Linux release 7.1.1503 (Core)
```
xCAT and DHCP versions:
```
[vndc:samveen@xcatmn1 ~]$ lsxcatd  -v
Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)
[vndc:samveen@xcatmn1 ~]$ lsxcatd  -t
This is a Management Node
[vndc:samveen@xcatmn1 ~]$ rpm -qf /etc/dhcp/dhcpd.conf
dhcp-4.2.5-36.el7.centos.x86_64
```
xCAT definitions:
```
[vndc:samveen@xcatmn1 ~]$ lsdef -t site clustersite |grep dhcp
    dhcpinterfaces=xcatmn1|eno1,ens1f0,!remote!
    dhcplease=604800
[vndc:samveen@xcatmn1 ~]$ lsdef -t network VNDC-POD-00105-IPv4,VNDC-POD-00107-IPv4
Object name: VNDC-POD-00105-IPv4
    dhcpserver=10.16.1.11
    dynamicrange=10.81.105.193-10.81.105.254
    gateway=10.81.105.1
    mask=255.255.255.0
    mgtifname=!remote!ens1f0
    net=10.81.105.0
    ntpservers=10.16.1.11
    tftpserver=10.16.1.11
Object name: VNDC-POD-00107-IPv4
    dhcpserver=10.16.1.11
    dynamicrange=10.81.107.193-10.81.107.254
    gateway=10.81.107.1
    mask=255.255.255.0
    mgtifname=!remote!ens1f0
    net=10.81.107.0
    ntpservers=10.16.1.11
    tftpserver=10.16.1.11
```

DHCP log:
```
[vndc:samveen@xcatmn1 ~]$ sudo journalctl -u dhcpd -n 20000 |grep -A 8 'DHCPDISCOVER from 0c:c4:7a:a3:3e:f6 via 10.81.107.1$' |egrep -- '--| 0c:c4:7a:a3:3e:f6 '
May 16 04:40:31 xcatmn1.vndc dhcpd[50038]: DHCPDISCOVER from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:40:32 xcatmn1.vndc dhcpd[50038]: DHCPOFFER on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:40:34 xcatmn1.vndc dhcpd[50038]: DHCPREQUEST for 10.81.105.201 (10.16.1.11) from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:40:34 xcatmn1.vndc dhcpd[50038]: DHCPACK on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
--
May 16 04:42:39 xcatmn1.vndc dhcpd[50038]: DHCPDISCOVER from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:42:40 xcatmn1.vndc dhcpd[50038]: DHCPOFFER on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:42:43 xcatmn1.vndc dhcpd[50038]: DHCPREQUEST for 10.81.105.201 (10.16.1.11) from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 04:42:43 xcatmn1.vndc dhcpd[50038]: DHCPACK on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
--
May 16 05:06:58 xcatmn1.vndc dhcpd[50038]: DHCPDISCOVER from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:06:59 xcatmn1.vndc dhcpd[50038]: DHCPOFFER on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:02 xcatmn1.vndc dhcpd[50038]: DHCPREQUEST for 10.81.105.201 (10.16.1.11) from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:02 xcatmn1.vndc dhcpd[50038]: DHCPACK on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:29 xcatmn1.vndc dhcpd[50038]: DHCPDISCOVER from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:29 xcatmn1.vndc dhcpd[50038]: DHCPOFFER on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:33 xcatmn1.vndc dhcpd[50038]: DHCPREQUEST for 10.81.105.201 (10.16.1.11) from 0c:c4:7a:a3:3e:f6 via 10.81.107.1
May 16 05:07:33 xcatmn1.vndc dhcpd[50038]: DHCPACK on 10.81.105.201 to 0c:c4:7a:a3:3e:f6 via 10.81.107.1
```
As you can see above the node with mac `0c:c4:7a:a3:3e:f6` receives an offer for `10.81.105.201` despite the request being relayed via `10.81.107.1`

**Comment by immarvin** [comment]
hi @samveen ,  please make sure the switch configuration  is correct, and check whether there is a static lease for ``0c:c4:7a:a3:3e:f6`` on the dhcp server

**Comment by samveen** [comment]
@immarvin I believe I've found the issue: This is a problem with how xCAT uses DHCPD, not with xCAT or DHCPD themselves (or maybe my assumptions about how xCAT should behave). More details below.

xCAT creates `shared-nework` definitions based on `networks.mgtifname`, whether if `!remote!` is present or not. If 2 network definitions share the same value of interface for `networks.mgtifname`, then they get grouped into the same shared network. 

This grouping of networks into `shared-network` is what causes my issue: As per dhcpd, the first free address from the `dynamic-bootp` ranges will be used to respond for requests coming from any of the subnets of a `shared-network`. This is by design.

In the above case, both subnets are part of `shared-network ens1f0`(see `networks.mgtifname` above), so any request that comes from any of the subnets is answered by the first free address, which unfortunately is from the wrong subnet: In this case, both are `!remote!` and requests are relayed - this is both `necessary` and `sufficient` condition for failure, as in this case.

The only solution I can think of is to create separate `shared-network` definitions for every network that has `!remote!` set in `network.mgtifname`.

**Comment by immarvin** [comment]
hi @samveen , would you please provide a sample(or part of) dhcpd.conf that works if convenient ?

**Comment by samveen** [comment]
@immarvin In the end we used a hackish method to work around the issue.
Network definition:
```
[vndc:samveen@xcatmn1 ~]$ lsdef -t network VNDC-POD-00101-IPv4 
Object name: VNDC-POD-00101-IPv4
    dhcpserver=10.16.1.11
    domain=lzd.io
    dynamicrange=10.81.101.128-10.81.101.254
    gateway=10.81.101.1
    mask=255.255.255.0
    mgtifname=!remote!ens1f101
    net=10.81.101.0
    ntpservers=10.16.1.11
    tftpserver=10.16.1.11
```
Please notice the `mgtifname=!remote!ens1f101`. This interfaces doesn't actually exist: I'm just using this string as a hack to allow creation of a new shared network.
This created an independent `shared-network` as below:
    shared-network ens1f101 {
      subnet 10.81.101.0 netmask 255.255.255.0 {
        max-lease-time 604800;
        min-lease-time 604800;
        default-lease-time 604800;
        option routers  10.81.105.1;
        next-server  10.16.1.11;
        option ntp-servers 10.16.1.11;
        option domain-name "lzd.io";
        option domain-name-servers  10.1.1.10;
        option domain-search  "lzd.io", "sgdc";
        zone lzd.io. {
          primary 10.1.1.10; key xcat_key;
        }   
        zone 105.81.10.IN-ADDR.ARPA. {
          primary 10.1.1.10; key xcat_key;
        }   
        if option user-class-identifier = "xNBA" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent
           always-broadcast on;
           filename = "http://10.16.1.11/tftpboot/xcat/xnba/nets/10.81.101.0_24";
        } else if option user-class-identifier = "xNBA" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent
           filename = "http://10.16.1.11/tftpboot/xcat/xnba/nets/10.81.101.0_24.uefi";
        } else if option client-architecture = 00:00  { #x86
          filename "xcat/xnba.kpxe";
        } else if option vendor-class-identifier = "Etherboot-5.4"  { #x86
          filename "xcat/xnba.kpxe";
        } else if option client-architecture = 00:07 { #x86_64 uefi
           filename "xcat/xnba.efi";
        } else if option client-architecture = 00:09 { #x86_64 uefi alternative id
           filename "xcat/xnba.efi";
        } else if option client-architecture = 00:02 { #ia64
           filename "elilo.efi";
        } else if option client-architecture = 00:0e { #OPAL-v3
           option conf-file = "http://10.16.1.11/tftpboot/pxelinux.cfg/p/10.81.101.0_24";
        } else if substring(filename,0,1) = null { #otherwise, provide yaboot if the client isn't specific
           filename "/yaboot";
        }   
        range dynamic-bootp 10.81.105.128 10.81.105.254;
      } # 10.81.101.0/255.255.255.0 subnet_end
    } # ens1f101 nic_end

As this shared-network is now independent, there is no more issues with the IP ranges to be used for dynamic leases.

**Comment by samveen** [comment]
Closing this, as this is not exactly an xCAT issue.
