### ISSUE TITLE
[DEV] Can not get correct firmware information when run rinv firm/all command

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3078]
Based on information get from https://github.com/openbmc/openbmc/issues/1547, need to modify URL of ``rinv firm/all`` command.

URL : ``/xyz/openbmc_project/software/enumerate``

**Comment by whowutwut** [comment]
As part of the investigation of the issue, we should add into the description the endpoint API that we are going against for openbmc, @xuweibj Please add this information to the description.  It should point to the Software endpoint.

**Comment by whowutwut** [comment]
@junxiawang Can you verify this?

**Comment by xuweibj** [comment]
The output like this:
```
# rinv redfishtest firm
redfishtest: System Firmware Product Version: v1.99.5-41-gbdd2b66
```
