### ISSUE TITLE
[fvt]2.13.5: getAllNodeAttribs function can't get all information from table occasionally

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#3081]
env:all os
build:
c910f04x30v24:~ # lsxcatd -v
Version 2.13.4 (git commit fc047c13f86b31121dd1c6f3ab3ceb14fbf97fd3, built Tue May 16 10:49:12 EDT 2017)
c910f04x30v24:~ #
How to reproduce:
```
1.
chdef testnode ip=34.3.3.3 groups=all
2.
makehosts 
3.
cat /etc/hosts
-----------------> could not find testnode information in /etc/hosts sometimes
```

**Comment by hu-weihua** [comment]
After long time debug, I found this is not the problem of ``makehosts (hosts.pm)`` itself, this is problem of xcat DB operation( ``getAllNodeAttribs`` function).

What I did:

Run below case for more than 1000 times. will hit this problem one time.

    start:makehost_n_r_1
    descriptions:modify makehosts testcases according to special node name eg:s01 and s01r* . for issue #2717 and #2683
    cmd:cp -f /etc/hosts /etc/hosts.xcatbakautotest
    cmd:nodeadd s01 groups=service; chdef s01 ip=70.2.0.254;nodeadd s01r1b01 groups=compute; chdef s01r1b01 ip=80.2.0.254;tabdump hosts;makehosts
    check:rc==0
    cmd:a=0;while true; do [ $a -eq 60 ] && exit 1;rc=`cat /etc/hosts`;if [[ $rc =~ "70.2.0.254 s01" ]] && [[ $rc =~ "80.2.0.254 s01r1b01" ]];then exit 0;else a=$[$a+1];sleep 1;echo $a;fi;done
    check:rc==0
    cmd:if [ -e /tmp/s01.standa ]; then rmdef s01; cat /tmp/s01.standa | mkdef -z; rm -rf /tmp/s01.standa; else rmdef s01;fi
    check:rc==0
    cmd:if [ -e /tmp/s01r1b01.standa ]; then rmdef s01r1b01; cat /tmp/s01r1b01.standa | mkdef -z; rm -rf /tmp/s01r1b01.standa;else rmdef s01r1b01; fi
    check:rc==0
    cmd:mv -f /etc/hosts.xcatbakautotest /etc/hosts
    end

When we hit such problem, it works like below:

    RUN:nodeadd s01 groups=service; chdef s01 ip=70.2.0.254;nodeadd s01r1b01 groups=compute; chdef s01r1b01 ip=80.2.0.254;tabdump hosts;makehosts [Fri Jun  9 02:27:14 2017]
    ElapsedTime:1 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    1 object definitions have been created or modified.
    #node,ip,hostnames,otherinterfaces,comments,disable
    "c910f03c17k39","10.3.17.39",,,,
    "s01","70.2.0.254",,,,
    "s01r1b01","80.2.0.254",,,,
    CHECK:rc == 0    [Pass]

We can see that, after added 2 new nodes, we could find these 2 new nodes in ``hosts`` table by ``tabdump hosts`` command. but when ``makehosts`` was running, it could not get all new nodes information from ``hosts`` table. 

I added some debug statement in ``hosts.pm`` like below:

    520         if ($DELNODE)
    521         {
    522             return;
    523         }
    524         my @hostents =
    525           $hoststab->getAllNodeAttribs(
    526             [ 'ip', 'node', 'hostnames', 'otherinterfaces' ]);
    527         print "---------------Dumper host table-----------------\n";
    528         print Dumper \@hostents;
    529
    530         my @allnodes;
    531         foreach (@hostents)
    .........
    574 sub writeout
    575 {
    576     my $targ;
    577     #open($targ, '>', "/etc/hosts");
    578     if(!open($targ, '>', "/etc/hosts")){
    579         print "open /etc/hosts failed:$!\n";
    580         return ;
    581     }
    582     print "-------------Dumper host arrary---------------\n";
    583     print Dumper \@hosts;
    584     foreach (@hosts)
    585     {
    586         print $targ $_;
    587     }
    588     close($targ);
    589 }
 
The running debug information like below:

    ---------------Dumper host table-----------------
    $VAR1 = [
              {
                'ip' => '10.3.17.39',
                'node' => 'c910f03c17k39'
              },
              {
                'ip' => '70.2.0.254',
                'node' => 's01'
              }
            ];

    -------------Dumper host arrary--------------
    $VAR1 = [
              '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ',
              '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    ',
              '
    ..........
    ',
              '14.1.0.100 c910f03c11k11-eth3 c910f03c11k11-eth3.pok.stglabs.ibm.com aliases2-2
    ',
              '10.3.17.39 c910f03c17k39 c910f03c17k39.pok.stglabs.ibm.com
    ',
              '70.2.0.254 s01 s01.pok.stglabs.ibm.com
    '
            ];

We could see one node information was missed when we invoked ``getAllNodeAttribs`` function to get information from ``hosts`` table.

**Comment by chenglch** [comment]
@hu-weihua , from your description, I could not know if it is caused by getAllNodeAttribs ? If you catch the event that the record is missing , can you get the missing record when your run the command the next time? (without chdef again)

**Comment by hu-weihua** [comment]
@chenglch , you can see after added 2 new nodes (s01, s01r1b01), then run ``tabdump hosts``. there are 2 entries 

    #node,ip,hostnames,otherinterfaces,comments,disable
    "c910f03c17k39","10.3.17.39",,,,
    "s01","70.2.0.254",,,,
    "s01r1b01","80.2.0.254",,,,

But when we invoked ``getAllNodeAttribs``, we just got ``s01``, missed ``s01r1b01``

    ---------------Dumper host table-----------------
    $VAR1 = [
          {
            'ip' => '10.3.17.39',
            'node' => 'c910f03c17k39'
          },
          {
            'ip' => '70.2.0.254',
            'node' => 's01'
          }
        ];

**Comment by chenglch** [comment]
Not sure how to detect the race condition and it is hard to debug as the db cache layer has been existed for a very long time.

**Comment by hu-weihua** [comment]
I think this issue maybe have the same reason with issue #2957
