### ISSUE TITLE
[FVT] makedns can't restart named successfully occasionally in sles11.4  

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3082]
In sles11.4, ``makedns`` can't guarantee restart named 100% successfully.
Occasionally, after ``makedns`` restart named, there were 2 named service alive at the same time.
Then the named service worked incorrectly.

ENV:
MN : c910f02c01p14
SN:  c910f02c01p08

XCAT version:
Version 2.13.4 (git commit 6ee3741498768994e4bb10d2a77c9699bcabde90, built Mon May 15 06:15:43 EDT 2017)

    RUN:makedns -n [Tue May 16 11:42:00 2017]
    [makedns -n] Running Time:26 sec
    RETURN rc = 0
    OUTPUT:
    Handling c910hmc04 in /etc/hosts.
    Handling c910f03fsp03v06.pok.stglabs.ibm.com in /etc/hosts.
    ......
    Handling c910f02c01p08.pok.stglabs.ibm.com in /etc/hosts.
    ......
    Handling c910f02c03p11 in /etc/hosts.
    Getting reverse zones, this may take several minutes for a large cluster.
    Completed getting reverse zones.
    Updating zones.
    Completed updating zones.
    Restarting named
    Restarting named complete
    Updating DNS records, this may take several minutes for a large cluster.
    Completed updating DNS records.
    CHECK:rc == 0   [Pass]

    ........

    RUN:makedhcp -a [Tue May 16 11:46:45 2017]
    [makedhcp -a] Running Time:2 sec
    RETURN rc = 1
    OUTPUT:
    Warning: The hostname c910f02c01p08 of node c910f02c01p08 could not be resolved.
    Error: Unable to resolve the tftpserver for node
    CHECK:rc == 0   [Failed]

    c910f02c01p14:~ # ps aux|grep named
    named     6317  0.0  0.5 147392 20992 ?        Ssl  May16   0:00 /usr/sbin/named -t /var/lib/named -u named
    root     13013  0.0  0.0   5312  2176 pts/0    S+   04:33   0:00 grep named
    root     24344  0.0  0.1   5824  4480 ?        Ss   May16   0:22 /sbin/syslog-ng -a /var/lib/dhcp/dev/log -a /var/lib/dhcp6/dev/log -a /var/lib/named/dev/log
    named    25188  0.0  0.4 144512 19456 ?        Ssl  May16   0:00 /usr/sbin/named -t /var/lib/named -u named

**Comment by immarvin** [comment]
hi @robin2008 , any update on this?

**Comment by robin2008** [comment]
In most of the time, DNS plugin (ddns.pm) will restart named first and then start it again.
There might be time racing there, especially on the legacy SysV system. As a result, the previous named is listening on the port and new daemon won't work.

Better to add a sleep there if requires both restart and start.

**Comment by robin2008** [comment]
Fix it in PR #3388
