### ISSUE TITLE
[xCAT performance] nodeset improvement - try to using multi-process to parallelize

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#3087]
Using multi-process to parallelize the nodeset to reduce the time consuming,  and the method could be used by other plugins.

**Comment by robin2008** [comment]
After discussion, we want to use fork to parallelize the process.  And put it higher priority.

**Comment by robin2008** [comment]
1, Need to consider what's part of codes be parallelized 
2, And how to make the parallelization (For each node or bunch of nodes,  we need to balance the CPU/MEM usage and the time consuming)

After some trying,  it is planned to be enhanced as below:
1,  in petitboot/xnba/grub2 "preprocess", we can split the node range as small part,  so that xCAT could handle them in parallel.

2, Only if nodes number > 250,  we will split the node range,  and we only create max 5 sub-process for it.

```
[root@c910f03c05k20 xcat]# time nodeset fake[1-2500] osimage=rhels7.3-ppc64le-install-compute >/dev/null

real	4m29.678s
user	0m2.026s
sys	0m0.027s

Before enhancement:

[root@c910f03c05k20 xcat]# time nodeset fake[1-2500] osimage=rhels7.3-ppc64le-install-compute >/dev/null

real	10m24.508s
user	0m1.282s
sys	0m0.037s
 ```
we can see that it have about 50% down.

**Comment by daniceexi** [comment]
@robin2008 
Good found. Please test the scenarios that have 50 or more processes to handle the node request.

**Comment by immarvin** [comment]
interesting that 5 sub-process does not bring 80% time reduce

**Comment by robin2008** [comment]
I will find a physical machine to do the testing,  then we don't need to care much about the cpu and memory.

**Comment by robin2008** [comment]
Some test result on an physical power8 server:

1, using max 5 processes for parallel , and each have at least 250 nodes

5000; nodeset; 1; 2; SUCESS; "nodeset fake[1-1] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 50; 6; SUCESS; "nodeset fake[1-50] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 100; 11; SUCESS; "nodeset fake[1-100] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 250; 26; SUCESS; "nodeset fake[1-250] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 500; 43; SUCESS; "nodeset fake[1-500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 1000; 81; SUCESS; "nodeset fake[1-1000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 2500; 217; SUCESS; "nodeset fake[1-2500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 5000; 545; SUCESS; "nodeset fake[1-5000] osimage=rhels7.3-GA-ppc64le-install-compute"

2, 10 processes for parallel, and each have at least 250

5000; nodeset; 1; 1; SUCESS; "nodeset fake[1-1] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 50; 7; SUCESS; "nodeset fake[1-50] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 100; 13; SUCESS; "nodeset fake[1-100] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 250; 30; SUCESS; "nodeset fake[1-250] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 500; 47; SUCESS; "nodeset fake[1-500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 1000; 77; SUCESS; "nodeset fake[1-1000] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 2500; 198; SUCESS; "nodeset fake[1-2500] osimage=rhels7.3-GA-ppc64le-install-compute"
5000; nodeset; 5000; 460; SUCESS; "nodeset fake[1-5000] osimage=rhels7.3-GA-ppc64le-install-compute"

**Comment by robin2008** [comment]
I've finished most of the UT for w and w/o SN, now it is ready to an official review and merge.
