### ISSUE TITLE
[FVT] test basic function against go-xcat and migration manually before 2.13.4 release

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3097]
What to do:
*  test basic function against go-xcat
*  test migration against rhels7.3+ppc64le for 2.13.4 release
   *  2.13.1->2.13.4
   *  2.13.2->2.13.4     
   *  2.13.3->2.13.4
   *  2.12.4->2.13.4

**Comment by junxiawang** [comment]
Done
