### ISSUE TITLE
[ xCAT 2.13.2 Centos 7.3 ] service node

### ISSUE THREAD

**Issue by dspatil7768** [xcat2/xcat-core#3103]
I'm currently trying for `xCAT Service Node`. But as defined in document there is no such `osimage`.

> When copycds was run against the ISO image, several osimages are created into the osimage table. The ones named *-service are provided by easily help provision xCAT service nodes.
 lsdef -t osimage | grep rhels7.1
  rhels7.1-ppc64le-install-compute  (osimage)
  rhels7.1-ppc64le-install-service  (osimage)   <======
  rhels7.1-ppc64le-netboot-compute  (osimage)

`[root@xcat2 ~]# lsdef -t osimage`
`centos7.3-x86_64-install-compute  (osimage)`
`centos7.3-x86_64-netboot-compute  (osimage)`
`centos7.3-x86_64-statelite-compute  (osimage)`

**Comment by immarvin** [comment]
hi @dspatil7768 , please create the relevant links to 
````
/opt/xcat/share/xcat/install/rh/service.rhels7.tmpl
/opt/xcat/share/xcat/install/rh/service.rhels7.x86_64.pkglist
/opt/xcat/share/xcat/install/rh/service.rhels7.x86_64.otherpkgs.pkglist
````
under ``/opt/xcat/share/xcat/install/centos/``, the link name should be relevant names replacing the "rhels7" with "centos7"

**Comment by dspatil7768** [comment]
Worked fine. Thank you.

`[root@xcat2 ~]# lsdef -t osimage`
`centos7.3-x86_64-install-compute  (osimage)`
`centos7.3-x86_64-install-service  (osimage)`
`centos7.3-x86_64-netboot-compute  (osimage)`
`centos7.3-x86_64-statelite-compute  (osimage)`
