### ISSUE TITLE
xCAT-csm packaging 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3109]
To automate the following steps may help CSM user
1) install xCAT
2) copycds osimage
3) pick a osimage and create addition ones for CRL (run some script or command)
- launch
- login
4) rinstall login[01-05] osimage=....login
5) rinstall launch[01-05] osimage=...launch

**Comment by whowutwut** [comment]
This rpm was not used by customers of CSM as they created their own definitions for the nodes they needed.  Closing out.
