### ISSUE TITLE
/var/lib/pgsql/data/pg_hba.conf created with wrong host entry

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3119]
After migrating xCAT database to postgre, when I opened the pg_hba.conf file to add the service node entries I noticed the wrong mask was set in this file.
my interface config files uses a 10 bit that is my subnet mask is 255.192.0.0.  When I looked at the file i was expecting to see my mgt server address as 10.10.1.3/10 instead I am seeing:
````
# IPv4 local connections:
host    all          all        10.10.1.3/32      md5
````

**Comment by immarvin** [comment]
hi @cxhong , would you please take a look at this? thanks

**Comment by cxhong** [comment]
I think this is for local connections of MN, so should be single host.  so 32 is correct mask value.
Here is doc: https://www.postgresql.org/docs/9.3/static/auth-pg-hba-conf.html
````
Typical examples of an IPv4 address range specified this way are 172.20.143.89/32 for a single host, or 172.20.143.0/24 for a small network, or 10.6.0.0/16 for a larger one. An IPv6 address range might look like ::1/128 for a single host (in this case the IPv6 loopback address) or fe80::7a31:c1ff:0000:0000/96 for a small network. 0.0.0.0/0 represents all IPv4 addresses, and ::0/0 represents all IPv6 addresses. To specify a single host, use a mask length of 32 for IPv4 or 128 for IPv6. In a network address, do not omit trailing zeroes
```

**Comment by cxhong** [comment]
Clive agreed, and I will close this issue.
