### ISSUE TITLE
addkcmdline doesn't get used in stateful xcat ver 2.9.2

### ISSUE THREAD

**Issue by dletai** [xcat2/xcat-core#313]
Trying to add hugepages=2000 to the kernel line of some nodes(*).

What I've tried: 
setup a new group and used:
`tabch node=testhuge bootparams.addkcmdline="R::hugepages=2000"`
`lsdef node1 -i addkcmdline`
> Object name: node1
>    addkcmdline=R::hugepages=2000

`nodeset node1 osimage=rhels6.5-x86_64-install-compute`
`grep ^bootloader /install/autoinst/node1`
> bootloader

The kickstart file doesn't update with `--append` as expected from `Template.pm`

Am I doing something wrong, or is there an issue with addkcmd in stateful?

(*)[As per kernel.org docs](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt)
> The administrator can allocate persistent huge pages on the kernel boot
> command line by specifying the "hugepages=N" parameter, where 'N' = the
> number of huge pages requested.  This is the most reliable method of
> allocating huge pages as memory has not yet become fragmented.

**Comment by immarvin** [comment]
hi, this feature is enabled from rhels7.0

you can enable it in rhels6.5 by replacing the following line
````
#
# bootloader config
# --append <args>
# --useLilo
# --md5pass <crypted MD5 password for GRUB>
#
bootloader
````

in /opt/xcat/share/xcat/install/rh/compute.rhels6.x86_64.tmpl with 
````

#
# bootloader config
# --append <args>
# --useLilo
# --md5pass <crypted MD5 password for GRUB>
#
#KICKSTARTBOOTLOADER#
````

**Comment by dletai** [comment]
Thanks, that solved the issue.
