### ISSUE TITLE
[FVT] For CUDA 7.5 support for diskless compute node, need a place to hack command uname while run genimage on Red Hat environment

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#314]
While trying to install CUDA 7.5 for diskless node on RHEL 7.2 Snapshot 2. The management node runs RHEL 7.2 Beta 1. That means, the management node has kernel version ``3.10.0-313.el7.ppc64le``. And the compute node will use kernel version ``3.10.0-316.el7.ppc64le``. In this case the kernel module of CUDA failed to compile during the ``genimage`` procedure.

We need a place to hack command ``uname``.

**Comment by neo954** [comment]
Need run ``mknod /dev/null c 1 3`` in the chroot environment as well.

**Comment by zet809** [comment]
The fix had been checked in. Pls verify.

**Comment by neo954** [comment]
Already fixed. I will close this one.
