### ISSUE TITLE
[fvt]2.11 could not generate *stateful-mgmtnode  (osimage) on rh7.0

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#315]
How to reproduce:
1.download the latest build
2.on rh7:
[root@c910f02c01p13 /]# cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.0 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.0"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.0 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0
Red Hat Enterprise Linux Server release 7.0 (Maipo)
Red Hat Enterprise Linux Server release 7.0 (Maipo)
[root@c910f02c01p13 /]# uname -a
Linux c910f02c01p13.pok.stglabs.ibm.com 3.10.0-123.el7.ppc64 #1 SMP Mon May 5 11:18:37 EDT 2014 ppc64 ppc64 ppc64 GNU/Linux
[root@c910f02c01p13 /]# 
3.copycds RHEL-7.0-20140507.0-Server-ppc64-dvd1.iso 
4.lsdef -t osimage
rhels7-ppc64-install-compute  (osimage)
rhels7-ppc64-install-service  (osimage)
rhels7-ppc64-netboot-compute  (osimage)
-------------------------------------> no rhels7-ppc64-stateful-mgmtnode  (osimage) here

**Comment by whowutwut** [comment]
I noticed this a week or so ago but I was not sure what osimage list is suppose to be supported out of the box.  I did think it was strange that we are not supporting state lite...

Wondering if we can add a flag to copycds or just have copycds (without -n) fail if the "required" osimage are not produced.  That would make copycd more "self testing"

**Comment by immarvin** [comment]
hi, according to the previous plan, the "statelite" mode will not be supported anymore in the future xCAT releases.

"rhels7-ppc64-stateful-mgmtnode (osimage)" definition will only be created when the osver and arch of the os DVD copied in are the same as the osver and arch of the MN. This is a feature requested by PCM 2 years ago.

**Comment by whowutwut** [comment]
@immarvin. Sorry I meant to write stateful and wrote state lite

**Comment by immarvin** [comment]
hi, yang peng, can you take a look at this bug?

some hints: 

look in to the call trace:

 subroutine "copycd" in anaconda.pm => subtoutine "update_tables_with_mgt_image" in "SvrUtils.pm"
