### ISSUE TITLE
xCAT should better support the service group (servicenode postscript) to avoid errors when using Hierarchy

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3150]
With hierarchy support and the configuration of Service Nodes, the service group is a special group for xCAT, yet the users are able to fall into many configuration traps and prone to user errors.  

Let me try and describe some problems: 

### Issue:  If node is not added to "service" group, `servicenode` postscript not run 

Create a fake node: 
```
[root@fs2vm110 ~]# mkdef sn01 groups=all netboot=petitboot mac=00:00:00:00:00:00
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef sn01
Object name: sn01
    groups=all
    mac=00:00:00:00:00:00
    netboot=petitboot
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
```

nodeset a "service node" osimage and see what happens....

```
[root@fs2vm110 ~]# nodeset sn01 osimage=rhels7.3-ppc64le-install-service
sn01: install rhels7.3-ppc64le-service
Error: The sn01 can not be resolved
Error: dhcp server is not running.  please start the dhcp server.
[root@fs2vm110 ~]# lsdef sn01
Object name: sn01
    arch=ppc64le
    currchain=boot
    currstate=install rhels7.3-ppc64le-service
    groups=all
    mac=00:00:00:00:00:00
    netboot=petitboot
    os=rhels7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=service
    provmethod=rhels7.3-ppc64le-install-service
```

The profile is set to `service` in the node definition, but the `servicenode` postscript is not added to this node definition, causing errors when provisioning service nodes. 

### Issue: service group can be deleted, once deleted it does not work... 

Multiple Issues here.... not sure how to re-create it..... seems like once the service group is deleted, it doesn't behave well anymore. 

Create a group service, and servicenode postscript is there... 
```
[root@fs2vm110 ~]# lsdef -t group -o service
Error: Could not find an object named 'service' of type 'group'.
[root@fs2vm110 ~]# mkdef -t group -o service 
Warning: Cannot determine a member list for group 'service'.
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef -t group -o service
Object name: service
    grouptype=static
    members=
    postscripts=servicenode
```

Once we remove it, can't re-create it...

```
[root@fs2vm110 ~]# rmdef -t group -o service
1 object definitions have been removed.
[root@fs2vm110 ~]# mkdef -t group -o service 
Warning: Cannot determine a member list for group 'service'.
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef -t group -o service
Object name: service
    grouptype=static
    members=
```

### Issue:  We are able to create a REGEX group called "service" , if we do not use `-p` option for postscripts, it will overwrite servicenode postscript in the group.  

This combination goes on and on and it's all traps for the user to fall into and configure the environment incorrectly.  

## Suggested Resolution:

I think what we need is to understand the `profile=service` that is attached to the osimage.  If a node it set to provision with an osimage that has a `profile=service` it seems the node definition also inherits this keyword. In this case, we should have the postscript automatically applied to this node.  

Similar to the `xcatdefaults` postscripts, we should add `servicenode` behind the defaults.   This will ensure that postscript configuration is done correctly when service nodes are in play.

**Comment by immarvin** [comment]
hi @whowutwut , I think it's a good idea to add "servicenode" in the ``postscripts`` attribute of the osimages for service nodes created on ``copycds``, such as``rhels7.3-ppc64le-install-service``.   

we'd better keep the current behavior of "service" group to keep backward compatibility

**Comment by robin2008** [comment]
Agree, we need add default attributes for service nodes into the service node osimage. 

Actually, 'service' group name does not has special meaning,  with define the node name in "servicenode" table, we even can have no group for service nodes.

**Comment by zet809** [comment]
For `xcatdefault`, it is a special keyword and deal with specially. 
But for `service`, it is a group, similar as other dynamic group to have the members inherit attribute for it.
It is a good idea to add "servicenode" script to "postscripts" of a service node osimage. But there are "nameserver,dhcpserver,tftpserver,nfsserver,conserver" services need to be determine whether to be start on service node. 
So, why not for the group or node defined in "servicenode" table, run "servicenode" script by default?

**Comment by zet809** [comment]
hi, @whowutwut , what do you think about @immarvin, @robin2008 and mine idea?

**Comment by whowutwut** [comment]
@immarvin  I think this is a good start, but even if we add it to the postscript , the user is able to set `postscript=""` and it will clear it out.  This is something that doesn't happen with the default attirbutes.  

@zet809 If we can set a attribute in the osimage definition to indicate that it's an osimage for Service Nodes, and then from that , we run the correct postscript automatically, i think this is the best way.  Since this postscript is required for the Service node to come up correctly...

**Comment by zet809** [comment]
@immarvin will verify whether "servicenode" script works in the middle of a group of postscripts, so move to next release.

**Comment by immarvin** [comment]
hi @whowutwut , I verified the provision of rhels7.3-ppc64le-install-service on the following node

````
[root@c910f03c05k21 ~]# lsdef c910f03c17k42 -i postscripts
Object name: c910f03c17k42
    postscripts=syslog,remoteshell,syncfiles, servicenode, confignics -s
````

The provision finished successfully

So ``servicenode `` do not need to be the last PS

**Comment by immarvin** [comment]
hi @whowutwut , The PR is https://github.com/xcat2/xcat-core/pull/3442

**Comment by immarvin** [comment]
verified by autotest
