### ISSUE TITLE
Backup service node is not reflected in the /opt/xcat/xcatinfo file

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3151]
It was thought that the backup service node attribute would be reflected somewhere in the provisioned node.   However, it looks like there is nothing passed down to the compute node: 

Defined the node: 
```
Object name: mid05tor12cn07
    servicenode=172.20.254.1,172.20.254.2
    xcatmaster=172.20.254.1
```

After the node comes up, nothing in xcatinfo....
```
[root@mid05tor12cn07 ~]# cat /opt/xcat/xcatinfo
IMAGENAME='rhels7.3-ppc64le-netboot-compute'
IMAGEUUID='8e45b0a5-3800-4e06-82d7-94792b4daf23'
TIMESTAMP='Fri May 19 13:41:10 EDT 2017'
NODE=mid05tor12cn07
XCATSERVER='172.20.254.1'
```

No indication of the backup service node in any of the environment variables

```
[root@mid05tor12cn07 xcatpost]# grep "172.20.254.2" mypostscript
[root@mid05tor12cn07 xcatpost]#
```

**Comment by robin2008** [comment]
Here, "servicenode" is the MN facing IP or name on SN,  normally the north-bound interface on SN, MN could see it.  But "xcatmaster" is the CN facing IP or name on SN, south-bound interface on SN, and the SN could see it.   That means CN should not care about the "servicenode" definitions, but only using "xcatmaster".

And I'm not sure it is a good idea to expose the upper details to compute nodes. For CN,  it does not need to care about how complex the upper level it is, it just need an active server(maybe fixed IP or floating IP) for netboot, DNS, NTP, etc.
In that, if  anything changed in management level,  it won't impact compute level.

**Comment by zet809** [comment]
Any updates for this issue?

**Comment by robin2008** [comment]
It is simple to add an extra attribute into xcatinfo.
To modify the "mypostscript.tmpl" to add 
```
--- /opt/xcat/share/xcat/mypostscript/mypostscript.tmpl.bak	2017-06-23 03:55:53.955070248 -0400
+++ /opt/xcat/share/xcat/mypostscript/mypostscript.tmpl	2017-06-23 03:58:32.128104664 -0400
@@ -44,6 +44,9 @@
 MASTER=#TABLE:noderes:$NODE:xcatmaster#
 export MASTER

+SERVICENODE=#TABLE:noderes:$NODE:servicenode#
+export SERVICENODE
+
 SYSLOG=#TABLE:noderes:$NODE:syslog#
 export SYSLOG
```
Then we can have mypostscript have the variable, and then update the existing post scripts to update xcatinfo.

Now my concerns is that do we require it?  It seems CSM want to have such feature.

**Comment by robin2008** [comment]
@whowutwut do we still require this ?

**Comment by robin2008** [comment]
Here,  we can store the sn group into xcatinfo if noderes.servicenode is defined for this node.
```
# cat /opt/xcat/xcatinfo
IMAGENAME='rhels7.3-ppc64le-netboot-compute'
IMAGEUUID='fca980f5-2550-4be8-b0f9-8fa76f933289'
TIMESTAMP='Thu Jun 22 11:33:27 EDT 2017'
NODE=mid05tor12cn07
XCATSERVER=172.20.253.104
USEFLOWCONTROL=NO
SERVICEGROUP=sn01,sn02
```
But it seems the facing IP of those nodes are better to be used in CN side. If using different subnet between SN and CN,  the short host name of SN is not the one binding the right IP. 

It is still an performance issue to get the right CN facing IP of the SNs,  for example, xcatd on sn01 can only know its facing IP (say ifconfig), if it want to know sn02 facing IP to CN, it have to ssh to sn02 to get the IP address.  And it will hit problem if sn02 is not accessible. So this is not a good method.

If we must use IP address,  I suggest that user must define the IP of service nodes into nics table. Then we can get the IP directly from DB.
@whowutwut what's your opinion?

**Comment by robin2008** [comment]
@whowutwut I still keep the current design to just use the node attribute (noderes.servicenode), 
so that there are more flexibility for admin to use IPs or nodenames he wants (the CN could access)

I've verified on the fs3 environment, and to close it first. If you have any concerns or comments, please open it again.
