### ISSUE TITLE
[openbmc]rflash support for firmware file delete

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3158]
OpenBMC `rflash` command support - priority 3:

Delete uploaded file
`rflash <node> <id> -d|--delete`

**Comment by zet809** [comment]
Hi, @gurevichmark and @whowutwut , the code looks good to me, as we have made the 2.13.6 RC1 build, do you think we need to merge the code and make another RC build or have this code be included in 2.13.7?

**Comment by zet809** [comment]
I had merged the code into 2.13.6 RC build, it will be included in 2.13.6 release.
