### ISSUE TITLE
[CRL E2E]makedns setup

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3168]
The document/steps of setting up name server in CRL cluster.
MN(nameserver) <--> (name client) SN (name server) <--> (name client)CN

1. The supported mode we had supported, and the using scenario
2. Which mode is suitable for CRL
3. The step by step to configure DNS in CRL

**Comment by zet809** [comment]
Hi, @whowutwut , do we have such document to setup hierarchical name server in CRL simulation environment? If yes, we can close this task.

**Comment by robin2008** [comment]
Now in CORAL simulation environment, the named is running forward mode on service node. 
```
options {
	directory "/var/named";
	dump-file "/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	recursion yes;
	forward only;
	forwarders {
		172.10.253.27;
	};
};
```

After testing, when MN (172.10.253.27) is DNS down,  we can still query the DNS from service node. (Not sure the expire time). 

But it might be not quiet right now for the /etc/resolv.conf setting on SN and CN,  it seems it is using the subnet nameserver settings (via dhcp).  So it is always

```
lsdef -t network 172_12_0_0-255_255_0_0
Object name: 172_12_0_0-255_255_0_0
    dhcpserver=172.12.253.27
    dynamicrange=172.12.253.100-172.12.253.200
    gateway=<xcatmaster>
    mask=255.255.0.0
    mgtifname=enP34p1s0f0.12
    net=172.12.0.0
    tftpserver=<xcatmaster>
# tabdump site|grep nameserver
"nameservers","172.10.253.27",,

lsdef mid05tor12cn11 | grep xcatmaster
    xcatmaster=172.12.254.2
```

on CN:
```
# cat /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search pok.stglabs.ibm.com.
nameserver 172.10.253.27
```

**Comment by robin2008** [comment]
And I think, we need some special configuration for them to make the DNS server more available on CN and SN.

For example:
For SN,  we set MN and 127.0.0.1 as nameservers
For CN,  we set sn01,sn02, mn as nameservers

we can do this setting in  group using regular expression (`noderes.nameservers`)

**Comment by robin2008** [comment]
It seems xCAT does not support per node level `nameservers` in `noderes` table.
```
       nameservers
                 An optional node/group specific override for name server list.  Most people want to stick to site or network defined nameserver configuration.
```

we may have some enhancement on this.
