### ISSUE TITLE
Verify support for Mellanox OFED 4.2 Beta in xCAT

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3172]
Create issue to track work related to supporting upcoming Mellanox OFED releases

**Comment by cxhong** [comment]
will move to next release, since the OFED 4.2 is not release yet.

**Comment by zet809** [comment]
hi, @cxhong , if you check the task #xcat2/xcat2-task-management:20 , @neo954 have verified latest CUDA9.2 and MLNX4.3 days before, 3 PR applied and waiting for your reviewing. Thx!
