### ISSUE TITLE
[openbmc]rflash support for firmware upload+update

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3173]
OpenBMC `rflash` command support - priority 1:

File upload and update.
`rflash <node> <file> --activate`

Update files are expected to be in `.tar` format.

**Comment by gurevichmark** [comment]
There is no single action provided by openbmc to upload and activate a file in one step.
Possible algorithm might be:

1. Upload a file and look at its version in MANIFEST file.
2. Once file finishes upload run `/software/enumerate`
3. Look through all the output entries and find the match of "Version" attribute to the one from MANIFEST.
4. Activate the ID that matched in step 3 above

This assumes there can be no duplicate version strings returned from `/software/enumerate`

**Comment by whowutwut** [comment]
@gurevichmark we would post this question to the firmware team and see if they can provide the function.  Or at least confirm that the process seems OK

**Comment by gurevichmark** [comment]
I discussed this algorithm with Adriana before posting it here, and she agreed that it should work.

**Comment by zet809** [comment]
Hi, @gurevichmark , can we close this task since the code had been included in 2.13.6 RC build?

**Comment by gurevichmark** [comment]
I think this issue should remain open. I am not written any code to support this function.
Currently 2 steps are needed - upload file then activate the image.
This issue is to support upload and activation in 1 step.

**Comment by gurevichmark** [comment]
PNOR file upload and activation implemented by PR #3750

**Comment by zet809** [comment]
Thx, @gurevichmark , more friendly for users.
