### ISSUE TITLE
Implementation of ZTP based ONIE switch discovery and configuration

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3176]
Based on the result of https://github.com/xcat2/xcat-core/issues/3060

Acceptance:
1. finish the implementation of the mandatory TODO features listed in the mini-design https://github.com/xcat2/xcat-core/wiki/mini-design-of-ZTP-based-onie-switch-discovery-and-configuration , the "nice to have" won't be covered by this task.
    1.1 the implementation of autodiscover
    1.2 the implementation of basic out of box configuration
2. finish function verification 
3. code merge to master branch
4. finish documentation[Low priority]

The customer requirement available at #2662

**Comment by immarvin** [comment]
The verification steps:
1. on mn, clean out any static dhcp lease for switch
  ``makedhcp -d mid05tor10``
2. predefine <onie switch>  ：
····
# lsdef mid05tor10
Object name: mid05tor10
    groups=switch,edge_switch
    ip=172.21.205.10
    mgt=switch
    nodetype=switch
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    switch=mgmtsw01
    switchport=10
····
3. ``makehosts mid05tor10 ``

4. ssh to the switch and run "ztp -R" to enable ZTP

5. reboot switch with "reboot"

6. wait several minutes

7. verify that switch has been discovered and configured
````
# lsdef mid05tor10
Object name: mid05tor10
    arch=armv7l
    groups=switch,edge_switch
    ip=172.21.205.10
    mac=xx:xx:xx:xx:xx:xx
    mgt=switch
    netboot=onie
    nodetype=switch
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=11S01FT690YA50YD73EACH
    status=configured
    statustime=06-22-2017 23:14:14
    supportedarchs=armv7l
    switch=mgmtsw01
    switchport=10
    switchtype=Edgecore Networks Switch
````

**Comment by zet809** [comment]
Let's move this task to done and close it after FVT is finished.

**Comment by tingtli** [comment]
I did a quick verification with today's build. Please refer to #3212

**Comment by robin2008** [comment]
@neo954 Do you finish all testing?  if yes, we can close this ticket.

**Comment by zet809** [comment]
Confirmed with @neo954 , the scope for this task is completed. So close this task.
