### ISSUE TITLE
[FVT] Offer one bundle for new hardware control and implement the missed cases

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3181]
what to do:

* Offer one bundle for new hardware control
* List the test cases we still missed now 
* implement the missed cases

The doc to refer to
https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/New%20Hardware%20Support%20Checklist

**Comment by tingtli** [comment]
Since PR# 3271 is merged. I will close this one.
