### ISSUE TITLE
[FVT] offer a tool to monitor all hardware resource of automation environment

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3182]
what to do:

* [ ] offer a solution of how to monitor all hardware resource in both 2 automation environment
  * Check the status (CPU/memory/disk space) of hypervisor.
  * Check the  status of control node 
  * Host a little group meeting to discuss this plan

* [ ] implement this tool
* [ ] hold a small meeting to show demo

**Comment by zet809** [comment]
Move the 2.13.6

**Comment by neo954** [comment]
Access the Web UI of the zabbix monitor tool at http://10.3.1.11/zabbix/
with default Zabbix administrator account `Admin`/`zabbix`.

**Comment by whowutwut** [comment]
:+1:  Very neat
