### ISSUE TITLE
[FVT] add or refine test cases for rinv command against OpenBMC

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3184]
What to do:

* add case for ``rvitals`` ``altitude`` option, this one was missed in last sprint

* add test cases for ``rinv`` command agaist OpenBMC for below options:
  * rinv noderange [cpu|dimm]

* refine test cases for ``rinv`` command agaist OpenBMC for below options:
   *  rinv noderange [model|serial|vpd|firm|all]

* add test cases for ``rinv`` command for regular command validity checking, such like ``-h``, ``-v``.....

* combine files ``~/xCAT-test/autotest/testcase/rinv/cases0`` and ``~/xCAT-test/autotest/testcase/rinv/cases1``.

**Comment by junxiawang** [comment]
Testcases need to add:
rvitals_altitude
rinv_h
rinv_v
rinv_help
rinv_deviceid
rinv_uuid
rinv_guid
rinv_vpd
rinv_mprom
rinv_cpu
rinv_dimm
rinv_errorcommand
rinv_invalidnode

**Comment by zet809** [comment]
Hi, @junxiawang , the comments [](https://github.com/xcat2/xcat-core/pull/3145#issuecomment-305066504) mentioned that "deviceid|uuid|guid|vpd|mprom" won't be supported by OpenBMC, so, the related case were not needed.

**Comment by junxiawang** [comment]
@gurevichmark ,@zet809 as er tao comments "deviceid|uuid|guid|vpd|mprom" won't be supported by OpenBMC,so do you think the testcase needed?We talk about the test scope today all man page mentioned: 
   OpenPOWER (using openbmc) server specific:
       rinv noderange [model|serial|deviceid|uuid|guid|vpd|mprom|firm|cpu|dimm|all]
will be  in testcases and I could open issues if option could not be supported .So what's your opinion?

**Comment by gurevichmark** [comment]
The testcases for "deviceid|uuid|guid|vpd|mprom" should be removed based on comments in PR #3145. That same PR modified the man page and "usage" output. Once the PR #3145 is merged, you should see the changed man page and "usage" for `rinv` command.

**Comment by whowutwut** [comment]
@zet809 just FYI, On the slack channel, it was mentioned that there's a unique uuid from Patrick Williams, but I'm not sure when/if that will be exposed...  right now there's nothing, but it doesn't mean that we won't provide this later on if there is something exposed.

**Comment by zet809** [comment]
OK, thx for the information, I agree to keep the uuid cases.

**Comment by whowutwut** [comment]
I think if the plan is to keep the cases just have them commented out so they are not executed

**Comment by junxiawang** [comment]
@whowutwut ,in testcase's framework  I will add such cases's:"uuid" output.One is "No uuid information is available" if not surpported and another is output have no than one lines but could not have "No uuid information is available" if this option surpported .
