### ISSUE TITLE
confignetwork support --script

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3190]
confignetwork support --script

**Comment by bybai** [comment]
As discussed in new confignetwork framework design, "--script" is to use a full script to replace this framework, seems not helpful for us.  Move this into icebox.

**Comment by samveen** [comment]
@bybai Maybe change the milestone to one of the future ones?

**Comment by bybai** [comment]
Hi @samveen, we do not have requirement for this feature, xCAT other function can realize this function. So this task is moved into icebox. Thanks.

**Comment by bybai** [comment]
Close this feature task since xCAT other function can realize this function.
