### ISSUE TITLE
investigate the work scope to enable latest conserver

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3193]
1.xcat-core code changes about `sslauthority`
2.If there is no conserver package default repo, download or build the package for different platforms
3.This task only cover rh7.3 ppc64le
There will be another task to cover the converserver package build for other OS+arch

**Comment by chenglch** [comment]
From investigation, we can not leverage the latest conserver package from the distribution directly as the package is not included by default. It is also not a good choice(dependency issues) to download rpm/deb packages for different systems as `sslcacertificatefile` is not supported until 8.1.19 version. Considering the migration issues, below are the work items:

- Apply the patches from xcat-dep to conserver_8.2.1
- build packages for 11 systems
  rh7 x86_64,  rh7 ppc64,   rh7 ppc64le,   rh6 ppc64,   rh6 x86_64,  ubuntu 14.04 x86_64,  ubuntu 
  14.04 ppc64le,  sles 11.4 x86_64,  sles12 x86_64,  sles12 ppc64le,  sles11.4 ppc64
- Convert `sslauthority` to `sslcacertificatefile` in xcat-core
- Migration config script to upgrade xcat from earlier version
- Build ansible playbook to build conserver ?

**Comment by chenglch** [comment]
Close this one as investigation is done.
We can track conserver work item with #3239
