### ISSUE TITLE
[New xCAT prototype]Implement petitboot plugin to deploy OpenPOWER bare metal servers

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3196]
- [x]  Enhance copycd interface to create and destroy osimage.
- [x] Update dhcp interface to support 209 options for petitboot
- [x] Build petitboot configuration file
- [x] Add clean up method to delete configurations during callback(deploy complete) or clean request( -d option).
- [x] Enhance the abstraction interface for pxe and petitboot

**Comment by chenglch** [comment]
The main changes for this item can be found in the commits below:
https://github.com/chenglch/xcat3/commit/f3871f06a0b362b2d409e36c683fadbb745191cd
https://github.com/chenglch/xcat3/commit/8455e588bd13c859845d5d5c179eb5977845b4f1

**Comment by whowutwut** [comment]
@chenglch I change the numbered list to check boxes.  Which items are resolved by the commits? All of them?

**Comment by chenglch** [comment]
@whowutwut, yes all of the items have been implemented, which means the prototype can be used to provision a very simple diskful system for OpenPOWER servers.

**Comment by CJCShadowsan** [comment]
Is this meant to be working?

On install of a Power9 AC922 i'm met with:

The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[   34.394241] kexec_core: Starting new kernel
[   55.488966033,5] OPAL: Switch to big-endian OS
[   57.297922324,5] OPAL: Switch to little-endian OS

And that's where it hangs...

**Comment by whowutwut** [comment]
@CJCShadowsan Which OS are you attempting to provision, and which version of xCAT is being used? (diskful, diskless?)

**Comment by whowutwut** [comment]
@CJCShadowsan Talking to the OpenBMC firmware team, they think that a checkstop may have occurred on your machine, are you able to run `fircheck` using openfsi, or power off/on and collect eSEL data?  Contacting IBM Support, they would be able to give you detailed instructions for this.

**Comment by CJCShadowsan** [comment]
Was attempting to provision RHEL7.4 diskful using latest 2.13.9 xCAT. Should be able to collect any logs needed, just point me at what you need.

Can't use grub2 inside noderes as petitboot complains that the binary isn't a 64-bit executable so it has to be petitboot, which is why i'm asking.

I'll have a quick poke around and see what I can do

**Comment by CJCShadowsan** [comment]
And surely enough:

[root@mgmt01 ~]# reventlog pn001
pn001: 01/17/2018 10:27:33 [1]: Unrecoverable Hardware Failure, (Critical) A system checkstop occurred (AffectedSubsystem: Canister/Appliance, PID: 1743), Resolved: 0
pn001: 01/17/2018 10:28:32 [2]: Not found in policy table: org.open_power.Host.Error.MaintenanceProcedure (PID: 1222), Resolved: 0
pn001: 01/17/2018 10:30:25 [3]: Unrecoverable Hardware Failure, (Critical) A system checkstop occurred (AffectedSubsystem: Canister/Appliance, PID: 2357), Resolved: 0
pn001: 01/17/2018 10:31:26 [4]: Not found in policy table: org.open_power.Host.Error.MaintenanceProcedure (PID: 1222), Resolved: 0
pn001: 01/23/2018 15:04:09 [5]: Communication Failure/Timeout, (Warning) Failed to read from I2C device (AffectedSubsystem: Systems Management - Core / Virtual Appliance, PID: 1801), Resolved: 0

**Comment by whowutwut** [comment]
@CJCShadowsan It looks like you have the ibm-crassd rpm installed to get those detailed logging messages using reventlog.  Can you disclose the customer here?  Do you have a contact in IBM support?

**Comment by CJCShadowsan** [comment]
Already got a ticket open and progressing within IBM. The customer is a
university, which is about as much as I can say right now :)

In other news (probably not relevant to this) - what's the status of a
CentOS7 ppc64 genesis rpm? Noted that there's now an x86_64 CentOS7
genesis, but no equivalent for ppc64.

Happy to help/test/etc if needed!

**Comment by whowutwut** [comment]
👍 excellent!

@zet809 any info about the centos genesis question?

**Comment by zet809** [comment]
Hi, @CJCShadowsan , thx for your information. I am looking at building genesis-base based on Centos7.
Just some question, is there any special reason to user Centos7 ppc64? Not Centos7 ppc64le? 
The kernel version is a little old `3.10.0-693.el7.ppc64le` for Centos7.4, '4.11.8-300' for fedora26 and `4.11.0-28` for RH7.4.

**Comment by CJCShadowsan** [comment]
No specific reason at all. ppc64le would be great 😊

**Comment by zet809** [comment]
OK, will build and test next week, once ready will let you know.

**Comment by whowutwut** [comment]
@zet809  Should we open an issue to track that above task?

**Comment by zet809** [comment]
hi, @whowutwut , #4774 is opened to trace building xCAT-genesis-base-ppc64le based on centos7.4 ppc64le.

**Comment by CJCShadowsan** [comment]
Note - we've just found out that genesis will *NOT *work using standard
RHEL7.4 for ppc64le and instead needs a RHEL for Power 9 specific kernel.

This might get folded into standard 7.4 but right now, it needs a very
specific kernel to even boot: 4.11.0-44.el7a.ppc64le

Just a heads-up for anyone really.

**Comment by whowutwut** [comment]
@CJCShadowsan Thank you for posting this, appreciate it.   You are correct. 

In the [2.13.10 release notes](https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.10_Release_Notes) under the test environment for AC922 hardware, we have a link to the [blog](https://www.redhat.com/en/blog/red-hat-launches-support-latest-ibm-hardware-red-hat-enterprise-linux) announcement.   This is not too clear though obviously as we are seeing folks hit this problem. 

It is confusing from RHEL, the RHEL 7.4 GA for all platforms (including ppc64le) was earlier last year , Aug 2017 (https://access.redhat.com/announcements/3134761) However, this did not include Power9 support and that was announced around Nov 2017 (https://www.redhat.com/en/blog/red-hat-launches-support-latest-ibm-hardware-red-hat-enterprise-linux) naming that one: **Red Hat Enterprise Linux 7.4 for Power Little Endian (POWER9)** .

Like you said you need to run this version to successfully deploy.

**Comment by zet809** [comment]
It is found that the xCAT-genesis-base-ppc64 based on Fedora26 can support P9 server right now.
```
[xCAT Genesis running on mid05tor12cn13 /]# cat /proc/device-tree/model
8335-GTC[xCAT Genesis running on mid05tor12cn13 /]# uname -a
Linux mid05tor12cn13 4.11.8-300.fc26.ppc64 #1 SMP Thu Jun 29 19:52:48 UTC 2017 ppc64 ppc64 ppc64 GNU/Linux
[xCAT Genesis running on mid05tor12cn13 /]# cat /proc/cpuinfo
processor	: 0
cpu		: POWER9 (raw), altivec supported
...
```

**Comment by zet809** [comment]
The tasks have been done, let's close this task.
