### ISSUE TITLE
support onboot=no for unlinked network interfaces

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3197]
This is from Slack:
> is there a way to have onboot=no for interfaces that do not physically have a link up ? so that we do not spend so much time trying to bring up that interface?  For example, if we have a 4 port adapter, enP4p1s0f[0,1,2,3] and we know the IP is on f0, there's no need to try and bring up ,1,2,3.. it just wastes time to DHCP time out.. on every reboot.
Based on investigate, we can enhance current post.rhels7 to support onboot=no for unlinked network interfaces.

**Comment by bybai** [comment]
From code, if Link detected."yes", will write ONBOOT=yes, or else write nothing. So I start to look into if the default ifcfg.* files have "ONBOOT" or not:
```
  if ethtool $nicname|grep -E -i "Link detected.*yes" >/dev/null 2>&1
     if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
        msgutil_r "$MASTER_IP" "info" "set NIC $nicname to be activated on system boot" "/var/log/xcat/xcat.log"
     fi
     then sed -i 's/ONBOOT=no/ONBOOT=yes/' $i
  fi
```

**Comment by bybai** [comment]
Summary change"ONBOOT" in post.rhels7:
1, When there is linked interfaces on physical server, after we install diskful on CN, post.rhels7 will add "ONBOOT=yes" in the linked interfaces ifcfg-* file;
2, When there is unlinked interfaces on physical server, after we install diskful on CN, post.rhels7 will not change "ONBOOT"  value in the unlinked interfaces ifcfg-* file;
So it is no need to change any code in post.rhels7;

I tested above in the following example:
There are 2 network interfaces in p9euh01 CN, enP5p1s0f0 is up while enP5p1s0f1 is down.  After I installed diskful rhels on p9euh01, "ONBOOT=yes" is in ifcfg-enP5p1s0f0 while "ONBOOT=no" is in ifcfg-enP5p1s0f1, that is the same with what we expect.

```
[root@p9euh01 network-scripts]# ethtool enP5p1s0f1 |grep "Link detected"
        Link detected: no

[root@p9euh01 network-scripts]# ethtool enP5p1s0f0 |grep "Link detected"
        Link detected: yes

[root@p9euh01 network-scripts]# cat ifcfg-enP5p1s0f0
# Generated by parse-kickstart
DEVICE="enP5p1s0f0"
IPV6INIT="yes"
BOOTPROTO="dhcp"
UUID="47f1efd3-5bf6-454f-b978-57bd34a75fb9"
ONBOOT="yes"

[root@p9euh01 network-scripts]# cat ifcfg-enP5p1s0f1
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=dhcp
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=enP5p1s0f1
UUID=4177cd2c-b426-4e75-a69d-a3f171d16400
DEVICE=enP5p1s0f1
ONBOOT=no
```

Hi @whowutwut , is this what your expect ?

**Comment by whowutwut** [comment]
Yes @bybai  If there is not physically detected link on the interface of the adapter, we should not set `onboot=yes`.  This causes `network.service` to report failure when we restart network because expected interfaces are not connected.  I think this issue was closed by accident, will reopen.

**Comment by robin2008** [comment]
In some rare case,  the NIC order might be changed at different stage of the installation.
For example,  it is eth7 at anaconda stage and it's detected linked in that time,  so we will set it to 'Yes'.  And another NIC, say eth5 is not linked at the time. 

However, After first boot,  there are some weird thing, the eth5 is becoming the7,  then it will get the bad result.

In general speaking,  we will not consider such negative case. But I would suggest to handle it again in confignetwork or confignics.

**Comment by bybai** [comment]
@whowutwut, post.rhels7 is for OS provision,  if the link is up, post.rhels7 change `onboot=yes`, if the link is down, the default value is `onboot=no`, we do not run post.rhels7 outside anaconda stage, so it is no need to change post.rhels7. As @robin2008 mentioned, we need another script to re-check the interfaces linked or not, confignetwork is a good option.  
@robin2008, I got your point. In confignetwork， it configures all nics from nics table, we can discuss if check unlinked interfaces or not in confignetwork framework design.   If the nics are configured in nics table, confignetwork can configure them, if nics are not configured in nics table and these nics are unlinked, we can let confignetwork configure `onboot=no` for these nics.
So add confignetwork framework design task here: #3090

**Comment by bybai** [comment]
Hi @whowutwut, What is your opinion about above comments?  If we can use another script to re-check the interfaces linked or not after the CN is booted, confignetwork is a good option, now I am working on new confignetwork enhancements, I can add this check in confignetwork.

**Comment by whowutwut** [comment]
@bybai  I re-provisioned the node yesterday and things looked OK.  I wonder what had happened before?  The networks that had physical cables connected had "ONBOOT=yes" and the networks that did not have physical cables connected was left "ONBOOT=no"  So I think this is sufficient for now.   I'm ok to close this out... 

Could it be possible that I was using an older version of xCAT on the mgmt node that had some issues??

**Comment by bybai** [comment]
Hi @whowutwut ， May be the following typo issue affects your previous result. I am agree with you to close this issue now. If you hit problem later, we can reopen this issue.
```
commit 6c8034cfa90d461adab5fa990622ad8820218270
Author: immarvin <yangsbj@cn.ibm.com>
Date:   Thu Jun 1 21:49:32 2017 +0800

    fix typo in if-clause
```
