### ISSUE TITLE
Default "no_pass_through" configuration is not set.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3198]
It looks like when GetOptions() is used in code, the invalid arguments are not caught in error path.
In some places in xCAT we explicitly set `Getopt::Long::Configure("no_pass_through");` before calling GetOptions. kvm.pm, for example.

The documentation for GetOptions (http://perldoc.perl.org/5.16.1/Getopt/Long.html) says `pass_through` is disabled by default. And looking at /usr/share/perl/5.18.2/Getopt/Long.pm in the  ConfigDefaults() the code is 
`$passthrough = 0;           # leave unrecognized options alone`

One suggestion to debug this problem is to do a check of config settings before calling GetOptions() in our code.

Also if a small standalone Perl script is written to use  GetOptions() it works as expected (`pass_through` is disabled by default)

**Comment by immarvin** [comment]
hi @gurevichmark , I looked into the http://perldoc.perl.org/5.16.1/Getopt/Long.html#Return-values-and-Errors and did some simple test subroutine "mkvm" in kvm.pm

The behavior of GetOpt confirm to the behavior mentioned in perldoc/GetOpt:
````
pass_through (default: disabled)
Options that are unknown, ambiguous or supplied with an invalid option value are passed through in @ARGV instead of being flagged as errors. This makes it possible to write wrapper scripts that process only part of the user supplied command line arguments, and pass the remaining options to some other program.
````

in kvm.pm, I modified the following code slice to print the return value of GetOptions ($ret) and @ARGV in the cases when ``pass_through`` is disabled and enabled:
````
3036 sub mkvm {
3037     shift;    #Throw away first argument
3038     @ARGV = @_;
3039     my $disksize;
3040     my $mastername;
3041     my $force = 0;
3042     require Getopt::Long;
3043     my $memory;
3044     my $cpucount;
3045     my $errstr;
**3046 Getopt::Long::Configure("pass_through");**
3047     my $ret=GetOptions(
3048         'master|m=s' => \$mastername,
3049         'size|s=s'   => \$disksize,
3050         "mem=s"      => \$memory,
3051         "cpus=s"     => \$cpucount,
3052         'force|f'    => \$force
3053     );
**3054 print "ret=$ret\n";
3055 print "ARGV=".Dumper(\@ARGV);**
````


When the line #3046 is commented out, the default behavior of  GetOptions is "no_pass_through":
(1) when invalid option "-x 10g" is passed in,  GetOptions throw out a message "Unknown option: x"  to STDERR, the invalid option "-x" is not passed through into @ARGV
(2) when valid option "-s 10g" is passed in, GetOptions returns TRUE("1")

````
[root@c910f03c05k21 xcat]# XCATBYPASS=1 mkvm c910f03c05k28 -s 10g
ret=1
ARGV=$VAR1 = [];

[root@c910f03c05k21 xcat]# XCATBYPASS=1 mkvm c910f03c05k28 -x 10g
Unknown option: x
ret=
ARGV=$VAR1 = [
          '10g'
        ];
````


When the line #3046 is uncommented out, the pass-through will be enabled, regardless of whether the options passed in is specified or not, the return value of GetOptions is TRUE("1"), the unspecified option "-x" is passed through into @ARGV 
 
````
[root@c910f03c05k21 xcat]# XCATBYPASS=1 mkvm c910f03c05k28 -s 10g
ret=1
ARGV=$VAR1 = [];
c910f03c05k28: Error:
[root@c910f03c05k21 xcat]# XCATBYPASS=1 mkvm c910f03c05k28 -x 10g
ret=1
ARGV=$VAR1 = [
          '-x',
          '10g'
        ];
````

**Comment by gurevichmark** [comment]
@immarvin Ok good investigation, but I have a few comments:
1. Why do we explicitly set `Getopt::Long::Configure("no_pass_through");` on line 1845 of kvm.pm for `chvm` command ?
2. Did you try your test with a simple flag, like `mkvm <node> -z` ?
3. I encountered this problem while developing code for OpenBMC. Can you try the same tests in `openbmc.pm` for `rflash` command around line 651. You will need to comment out the checks for invalid arguments on lines 471-489
4. Is there a function to check the set value of `Configure("pass_through")` before calling GetOptions() ?

**Comment by immarvin** [comment]
``Getopt::Long::Configure("debug");``

or 

``use Getopt::Long qw(:config debug);``

turns on the debug output of Getoptions

the output is like 
````
Getopt::Long 2.4 called from package "xCAT_plugin::kvm".
  argv: (-x 10g)
  autoabbrev=1,bundling=1,getopt_compat=1,gnu_compat=0,order=1,
  ignorecase=0,requested_version=0,**passthrough=0**,genprefix="(--|-|\+)",longprefix="(--)".
=> link "master" to SCALAR(0x1003573b5f0)
=> link "size" to SCALAR(0x1003573b620)
=> link "mem" to SCALAR(0x1003573bb18)
=> link "cpus" to SCALAR(0x1003573bb48)
=> link "force" to SCALAR(0x1003573bab8)
=> $opctl{master} = ARRAY(0x10037d3c6d0) ["s","master","<undef>",$,1,1]
   $opctl{m} = ARRAY(0x10037d3c6d0) ["s","master","<undef>",$,1,1]
   $opctl{s} = ARRAY(0x10037d8ae00) ["s","size","<undef>",$,1,1]
   $opctl{force} = ARRAY(0x10037d71ba8) ["","force","<undef>",$,,]
   $opctl{size} = ARRAY(0x10037d8ae00) ["s","size","<undef>",$,1,1]
   $opctl{mem} = ARRAY(0x10037dd1a50) ["s","mem","<undef>",$,1,1]
   $opctl{f} = ARRAY(0x10037d71ba8) ["","force","<undef>",$,,]
   $opctl{cpus} = ARRAY(0x10037d1e5f8) ["s","cpus","<undef>",$,1,1]
=> arg "-x"
=> find "-x"
=> split "-"+"x"
=> -x unbundled from -x
Unknown option: x
````

**Comment by immarvin** [comment]
another hint is the ``use Getopt::Long;`` and ``require Getopt::Long;``



`require() reads a file containing Perl code and compiles it.Before attempting to load the file it looks up the argument in %INC to see whether it has already been loaded. If it has, require() just returns without doing a thing. Otherwise an attempt will be made to load and compile the file.`


`use(), just like require(), loads and compiles files containing Perl code, but it works with modules only and is executed at compile time.`


I am afraid ``Getopt::Long::Configure("debug");`` applies to the ``GetOptions`` in the same process

**Comment by gurevichmark** [comment]
@immarvin Thanks for the debugging idea. 

I added `require Getopt::Long;` to the openbmc.pm.
I also added `Getopt::Long::Configure("debug");` right before `GetOptions()` call in `parse_command_status()` in the `if` statement handling `rflash` command.
The debug output seems to indicate that `passthrough` is enabled:

**Comment by robin2008** [comment]
@gurevichmark @immarvin   are we still working on it?

**Comment by samveen** [comment]
@immarvin Maybe change the milestone to one of the future ones for this one too?

**Comment by whowutwut** [comment]
What's the decision on what we should have the default behavior be?

**Comment by immarvin** [comment]
hi @robin2008 @whowutwut , this is an interesting problem on language level, I did some debug and provided some debugging hints, but did not have time to investigate further.

hi @gurevichmark ,  any update on this?  Is this a still a blocking issue?

**Comment by gurevichmark** [comment]
It is not blocking. I was able to work around this issue.
The problem is that I noticed this accidentally with `rflash` command, and there might be other xCAT commands with this issue.
Does FVT run testcases for xCAT commands with invalid arguments/flags, expecting some error message and RC != 0 ?
