### ISSUE TITLE
xCAT cannot install correctly when RHEL EPEL repos are present on the machine

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3202]
xCAT can't install correctly when EPEL repos are installed on the machine.  

I found this with `go-xcat` but I don't think it's a problem with go-xcat.  I think we ship a version of `perl-SOAP-Lite-1.10-1.el7.noarch` in our xcat-deps that conflicts with a version in the EPEL repository. 

Here's the error that comes out.... 
```
--> Processing Dependency: perl(Class::Inspector) for package: perl-SOAP-Lite-1.10-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: perl-SOAP-Lite-1.10-1.el7.noarch (epel)
           Requires: perl(Class::Inspector)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

But when I move the epel.* repo files out of `/etc/yum.repos.d/` and run `yum clean all` and rerun go-xcat....

No problems, it's picked up from the xcat-dep repo...

```
 perl-PlRPC        noarch  0.2020-14.el7   local-rhels7.3-ppc64le-ppc64le  36 k
 perl-SOAP-Lite    noarch  0.710.08-1      xcat-dep                       267 k
 perl-Sys-Syslog   ppc64le 0.33-3.el7      local-rhels7.3-ppc64le-ppc64le  42 k
```

**Comment by immarvin** [comment]
hi @whowutwut , xCAT-deps ships "perl-SOAP-Lite-0.710.08-1.noarch.rpm"
````
[root@c910f03c05k21 xcat-dep]# find . -name "perl-SOAP-Lite*"
./SL5/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./SL6/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./SL6/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./fedora12/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./fedora13/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./fedora14/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./fedora15/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh5/ppc64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh5/s390x/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh5/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh6/ppc64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh6/s390x/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh6/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh6/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh7/ppc64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh7/ppc64le/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh7/s390x/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh7/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./rh7/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles10/ppc64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles10/s390x/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles10/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles11/ppc64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles11/s390x/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles11/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles11/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles12/ppc64le/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles12/x86_64/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./sles12/perl-SOAP-Lite-0.710.08-1.noarch.rpm
./perl-SOAP-Lite-0.710.08-1.noarch.rpm
````
``perl-SOAP-Lite-1.10-1.el7.noarch`` is shipped in epel, 

what command did you run to hit this problem?

The steps to update xCAT in http://xcat-docs.readthedocs.io/en/stable/guides/install-guides/yum/update_xcat.html 
````
yum clean metadata # or, yum clean all
yum update '*xCAT*'
````
won't hit this issue. 

``yum update`` will hit this issue, since it will try to update all the packages having update candidates,  if``go-xcat update`` tries to update all the packages with ``go-xcat update`` instead of following the update steps in xCAT documentation, I think it should be a bug of go-xcat.

**Comment by whowutwut** [comment]
I always use the `yum update "*xCAT*"` to update xCAT.  I think the issue is that the later version of perl-SOAP in the EPEL requires Class::Inspector, that is not present anywhere for it to resolve.  

But the larger issue here is whether having a later version of perl-SOAP will cause some problems with xCAT... if the Class:Inspection dependency is resolved, it would have installed a later version of Perl-SOAP, i think.

**Comment by neo954** [comment]
Maybe, the better solution is prevent the end user to install `perl-SOAP-Lite-1.10-1.el7.noarch` from EPEL.

Here comes the quick-and-dirty solution. Edit file `/etc/yum.repos.d/epel.repo`, and hack the section `[epel]`, and one extra line, `exclude=perl-SOAP-Lite`, at the end of this section. As shown below.

    [epel]
    name=Extra Packages for Enterprise Linux 7 - $basearch
    #baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
    mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    failovermethod=priority
    enabled=1
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    exclude=perl-SOAP-Lite                                # <= ADD THIS LINE

After the hacking, you are good to go.

BTW, here is a trick, you may check the repository with `/path/to/go-xcat check`. Try do this before and after the hacking.

**Comment by neo954** [comment]
Another not-so-dirty solution is adapting xCAT to a later version of `perl-SOAP-Lite`.

**Comment by whowutwut** [comment]
So @immarvin  said 
>  I think it should be a bug of go-xcat.

But I think this is a generic issue for xCAT rpms because we ship a lower version of `perl-SOAP-Lite` and the EPEL configures a repo that ships a later one. 

The bigger problem in my opinion, is that if we do not update the `perl-SOAP-Lite` and the user has the dependencies resolved where it can resolve this:
```
Error: Package: perl-SOAP-Lite-1.10-1.el7.noarch (epel)
           Requires: perl(Class::Inspector)
```
Then a later version of this library is installed and we are not expecting that. 


@neo954 I think the hack is overkill.  If we wanted to do something quick, just check any EPEL repos are defined for RHEL and print a WARNING message.  That's all.    

Or ... 
1. Adopting a later version of `perl-SOAP-Lite`. 
2. Require the use of EPEL ( :-1:  this is not good for those installing xCAT without internet connectivity)

**Comment by neo954** [comment]
@whowutwut, Here is another workaround. You can do `yum update --exclude=perl-SOAP-Lite` if you already have `perl-SOAP-Lite-0.710.08-1.noarch` installed on your system. Unfortunately, there is no way to specify the repository when use `--exclude` argument of `yum` from command line. So, if it is a brand new install of xCAT, it is doomed. No perfect solution.

Clearly, we don't want to adapting xCAT to fit `perl-SOAP-Lite` version 1.10-1.el7. 😞

**Comment by neo954** [comment]
There is no black magic in `go-xcat`. When you run `go-xcat update`, it runs something like the following command under the hood.

    # yum update $(rpm -q --qf '%{name}\n' perl-xCAT xCAT xCAT-buildkit \
    > xCAT-client xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 \
    > xCAT-server conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat syslinux-xcat \
    > xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xnba-undi yaboot-xcat)`

The script `go-xcat` just helps the user configure the yum repositories of `xcat-core` and `xcat-dep`. If after the yum repositories of `xcat-core` and `xcat-dep` were set up. And the command of `yum update ...` above cannot be run from the command line, `go-xcat` can do nothing as well.

Of course, we can do some black magic in the `go-xcat` to help the user of xCAT make life easier. In this situation, hacking `/etc/yum.repos.d/epel.repo` secretly behind the screen clearly is not a good solution. If we really intend to do something inside `go-xcat`, we have to figure it out first.

**Comment by neo954** [comment]
Maybe we can update the rpm dependency of package `perl-xCAT`, and add version information into it.

Currently, we have ...

    # rpm -qR perl-xCAT | grep SOAP
    perl(SOAP::Lite)

We can update it to ...

    perl(SOAP::Lite) < 1.0.0-0

This will prevent the end user update package `perl-SOAP-Lite` beyond version 1.0-0.

**Comment by whowutwut** [comment]
I guess if there's no harm in allowing for `Requires: perl(Class::Inspector)` to install... then we can just leave this issue alone if the dependency is resolved.  Otherwise, if we want to block the install of a later version, then we can make the changes that are suggested `< 1.0.0-0` to ensure that we install the version from `xcat-deps`...   I don't think we should spend too much time on this since its low prio

**Comment by whowutwut** [comment]
If not fixing, lets close.

**Comment by whowutwut** [comment]
@robin2008  I think we need to fix this.  The EPEL is Extra Packages Enterprise Linux and is intended to be used with Enterprise versions of RHEL, when I have a node and I've configured: 

* local OS repo
* EPEL repo 
* RHEL Extra Packages repo 

Then... downloaded xcat-core. and xcat-deps, it fails to install.  

To resolve: 
```
1. mv /etc/yum.repos.d/epel-generated.repo /etc/yum.repos.d/epel-generated.repo.hide
2. yum clean all
3. yum install xCAT
4. mv /etc/yum.repos.d/epel-generated.repo.hide /etc/yum.repos.d/epel-generated.repo
```

I don't think this is good.

**Comment by robin2008** [comment]
@whowutwut  just as I pointed, you are using EPEL via a wrong way.

For using EPEL with RHEL, you need extra repo and optional repo,  it is clearly documented in EPEL (https://fedoraproject.org/wiki/EPEL). search for "NOTE for RHN users"
you can refer to below ticket https://bugzilla.redhat.com/show_bug.cgi?id=1262772

So if you want to use EPEL, you should make sure:

    

- local OS repo
- EPEL repo
- 'optional' repository (rhel-7-server-optional-rpms)
- RHEL Extra Packages repo (rhel-7-server-extras-rpms)

If we want to resolve it by xcat dep,  we could bundle perl-SOAP-Lite 1.10 and perl(Class::Inspector) into xcat-dep.  And verify all function using SOAP are still working.

As you know,  xCAT key feature does not requires SOAP, only for belows:
```
./perl-xCAT/xCAT/vboxService.pm
./xCAT-server/lib/xcat/plugins/vbox.pm:    my $soapsupport = eval { require SOAP::Lite; };
./xCAT-server/lib/xcat/plugins/hpblade.pm
./perl-xCAT/xCAT/hpoa.pm
```
And xCAT-softlayer,  I want to find a way to remove the auto-requires for SOAP there in `perl-xCAT`

**Comment by robin2008** [comment]
I've check the codes,  by default SOAP::Lite is introduced by dynamically. After vbox supporting,  it becomes an default requirements. 

virtualbox supporting is an advance feature, and not maintained now.  
Plan to follow previous decision to disable it,  user should install it manually to enable vbox supporting.  The change is addressed in https://github.com/xcat2/xcat-core/pull/4910

After this, new installed xCAT won't install perl-SOAP-lite by default. And then, no conflicts with EPEL.

**Comment by hu-weihua** [comment]
@tingtli , could you help to verify this issue during your test against openbmc? thanks.

**Comment by robin2008** [comment]
@tingtli , I've done the verification with rhel7.3 MN + EPEL on xcat 2.13.11

```
[root@c910f03c05k30 ~]# yum repolist
Failed to set locale, defaulting to C
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
repo id                                                                          repo name                                                                                     status
epel/ppc64le                                                                     Extra Packages for Enterprise Linux 7 - ppc64le                                               11887
local-rhels7.3-ppc64le--install-rhels7.3-ppc64le                                 xCAT configured yum repository for /install/rhels7.3/ppc64le                                   3454
xcat-core                                                                        xCAT 2 Core packages                                                                             21
xcat-dep                                                                         xcat-dep                                                                                         33
repolist: 15395
[root@c910f03c05k30 ~]# /tmp/go-xcat install
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.3

Reading repositories ...... done

xCAT is going to be installed.
Continue? [y/n] y
Failed to set locale, defaulting to C
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Package conserver-xcat-8.2.1-1.ppc64le already installed and latest version
Package elilo-xcat-3.14-4.noarch already installed and latest version
Package grub2-xcat-2.02-0.16.el7.snap201506090204.noarch already installed and latest version
Package ipmitool-xcat-1.8.18-0.ppc64le already installed and latest version
Package syslinux-xcat-3.86-2.noarch already installed and latest version
Package xnba-undi-1.0.3-131028.noarch already installed and latest version
Package yaboot-xcat-1.3.17-rc1.noarch already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package perl-xCAT.noarch 4:2.13.11-snap201803130745 will be installed
---> Package xCAT.ppc64le 0:2.13.11-snap201803130745 will be installed
--> Processing Dependency: xCAT-probe = 4:2.13.11-snap201803130745 for package: xCAT-2.13.11-snap201803130745.ppc64le
---> Package xCAT-buildkit.noarch 4:2.13.11-snap201803130745 will be installed
---> Package xCAT-client.noarch 4:2.13.11-snap201803130745 will be installed
---> Package xCAT-genesis-base-ppc64.noarch 2:2.13.10-snap201801170133 will be installed
---> Package xCAT-genesis-base-x86_64.noarch 2:2.13.10-snap201801170129 will be installed
---> Package xCAT-genesis-scripts-ppc64.noarch 1:2.13.11-snap201803130745 will be installed
---> Package xCAT-genesis-scripts-x86_64.noarch 1:2.13.11-snap201803130745 will be installed
---> Package xCAT-server.noarch 4:2.13.11-snap201803130745 will be installed
--> Running transaction check
---> Package xCAT-probe.noarch 4:2.13.11-snap201803130745 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                     Arch    Version                    Repository
                                                                           Size
================================================================================
Installing:
 perl-xCAT                   noarch  4:2.13.11-snap201803130745 xcat-core 662 k
 xCAT                        ppc64le 2.13.11-snap201803130745   xcat-core 239 k
 xCAT-buildkit               noarch  4:2.13.11-snap201803130745 xcat-core  67 k
 xCAT-client                 noarch  4:2.13.11-snap201803130745 xcat-core 519 k
 xCAT-genesis-base-ppc64     noarch  2:2.13.10-snap201801170133 xcat-dep   91 M
 xCAT-genesis-base-x86_64    noarch  2:2.13.10-snap201801170129 xcat-dep   87 M
 xCAT-genesis-scripts-ppc64  noarch  1:2.13.11-snap201803130745 xcat-core  59 k
 xCAT-genesis-scripts-x86_64 noarch  1:2.13.11-snap201803130745 xcat-core  59 k
 xCAT-server                 noarch  4:2.13.11-snap201803130745 xcat-core 1.8 M
Installing for dependencies:
 xCAT-probe                  noarch  4:2.13.11-snap201803130745 xcat-core  87 k

Transaction Summary
================================================================================
Install  9 Packages (+1 Dependent package)

Total download size: 181 M
Installed size: 643 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               22 MB/s | 181 MB  00:08
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 4:xCAT-client-2.13.11-snap201803130745.noarch               1/10
  Installing : 4:perl-xCAT-2.13.11-snap201803130745.noarch                 2/10
  Installing : 4:xCAT-server-2.13.11-snap201803130745.noarch               3/10
  Installing : 4:xCAT-probe-2.13.11-snap201803130745.noarch                4/10
  Installing : 4:xCAT-buildkit-2.13.11-snap201803130745.noarch             5/10
  Installing : 2:xCAT-genesis-base-ppc64-2.13.10-snap201801170133.noarc    6/10
  Installing : 1:xCAT-genesis-scripts-ppc64-2.13.11-snap201803130745.no    7/10
If you are installing/updating xCAT-genesis-base separately, not as part of installing/updating all of xCAT, run 'mknb <arch>' manually
  Installing : 2:xCAT-genesis-base-x86_64-2.13.10-snap201801170129.noar    8/10
  Installing : 1:xCAT-genesis-scripts-x86_64-2.13.11-snap201803130745.n    9/10
If you are installing/updating xCAT-genesis-base separately, not as part of installing/updating all of xCAT, run 'mknb <arch>' manually
  Installing : xCAT-2.13.11-snap201803130745.ppc64le                      10/10
Generating new node hostkeys...
Generating SSH2 RSA Key...
Generating SSH2 DSA Key...
Generating SSH2 ECDSA Key...
Copied /root/.ssh/id_rsa.pub to /install/postscripts/_ssh/authorized_keys.
Restarting xcatd (via systemctl):  [  OK  ]
dns server has been enabled on boot.
httpd has been restarted.
xCAT is now running, it is recommended to tabedit networks
and set a dynamic ip address range on any networks where nodes
are to be discovered. Then, run makedhcp -n to create a new dhcpd
configuration file, and /etc/init.d/dhcpd restart. Either examine sample
configuration templates, or write your own, or specify a value per
node with nodeadd or tabedit.
Running '/opt/xcat/sbin/mknb', triggered by the installation/update of xCAT-genesis-scripts ...
Error: Permission denied for request
The 'mknb ppc64' command returned error code: 1.
Error: Permission denied for request
The 'mknb x86_64' command returned error code: 1.
  Verifying  : 2:xCAT-genesis-base-x86_64-2.13.10-snap201801170129.noar    1/10
  Verifying  : 2:xCAT-genesis-base-ppc64-2.13.10-snap201801170133.noarc    2/10
  Verifying  : 4:xCAT-server-2.13.11-snap201803130745.noarch               3/10
  Verifying  : xCAT-2.13.11-snap201803130745.ppc64le                       4/10
  Verifying  : 4:perl-xCAT-2.13.11-snap201803130745.noarch                 5/10
  Verifying  : 4:xCAT-probe-2.13.11-snap201803130745.noarch                6/10
  Verifying  : 4:xCAT-buildkit-2.13.11-snap201803130745.noarch             7/10
  Verifying  : 1:xCAT-genesis-scripts-ppc64-2.13.11-snap201803130745.no    8/10
  Verifying  : 1:xCAT-genesis-scripts-x86_64-2.13.11-snap201803130745.n    9/10
  Verifying  : 4:xCAT-client-2.13.11-snap201803130745.noarch              10/10

Installed:
  perl-xCAT.noarch 4:2.13.11-snap201803130745
  xCAT.ppc64le 0:2.13.11-snap201803130745
  xCAT-buildkit.noarch 4:2.13.11-snap201803130745
  xCAT-client.noarch 4:2.13.11-snap201803130745
  xCAT-genesis-base-ppc64.noarch 2:2.13.10-snap201801170133
  xCAT-genesis-base-x86_64.noarch 2:2.13.10-snap201801170129
  xCAT-genesis-scripts-ppc64.noarch 1:2.13.11-snap201803130745
  xCAT-genesis-scripts-x86_64.noarch 1:2.13.11-snap201803130745
  xCAT-server.noarch 4:2.13.11-snap201803130745

Dependency Installed:
  xCAT-probe.noarch 4:2.13.11-snap201803130745

Complete!

xCAT has been installed!
========================

If this is the very first time xCAT has been installed, run the following
commands to set environment variables into your PATH:

For sh:
    source /etc/profile.d/xcat.sh

For csh:
    source /etc/profile.d/xcat.csh
```

**Comment by robin2008** [comment]
@whowutwut 

Note: this does not resolve the perl-SOAP-lite issue, but not install it by default (as xcat main feature does not rely on this perl module). 

And If you have already installed the package, you may still hit the same issue, then you need subscribe RHEL 'optional' or 'extra' repository.
