### ISSUE TITLE
xCAT upgrade changes boot order settings

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3204]
This problem was reported by `vsolasa@us.ibm.com - Veera s Solasa/Poughkeepsie/IBM`

1. All cluster nodes had their boot order set to "hd". After upgrade from xCAT 2.12 to 2.13.5 the boot order was changed to "default".  Same was observed when upgrading 2.13.3 to 2.13.4

2. The `rsetboot stat` returns `frame5u39: boot override inactive` message, which sounds like an error, but in fact just a message that default order is in effect. Perhaps we should change the message to something that sounds less like an error? Maybe something like "default boot order is in effect" ?

3. Should it be possible to provision a node in default boot order ? Currently provisioning gets stuck in genesis when boot order is default.

**Comment by immarvin** [comment]
hi @zet809 , would you please take a look at this issue?

hi @gurevichmark , can you provide the node definition of frame5u39?

**Comment by gurevichmark** [comment]
Yes. frame5u39 is defined on stratton01 as:
```
bject name: frame5u39
    arch=ppc64le
    bmc=50.5.39.1
    cons=ipmi
    cpucount=160
    cputype=POWER8 (raw), altivec supported
    currchain=boot
    currstate=boot
    disksize=sda:1000GB,sdb:1000GB
    groups=all,compute
    installnic=mac
    ip=10.5.39.1
    mac=98:be:94:59:ee:a7
    memory=261482MB
    mgt=ipmi
    mtm=8335-GTA
    netboot=petitboot
    nodetype=mp
    os=rhels7.4-pegas-alpha
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels7.4-pegas-alpha-ppc64le-install-compute
    serial=2100EEA
    status=powering-on
    statustime=05-17-2017 11:25:43
```

**Comment by zet809** [comment]
Hi, @gurevichmark , for the questions, the answer are:
For 1. need more investigate
       2.I agree with you that we need to modify the output message
       3. For OpenPOWER server, to do netboot (OS deployment or run genesis), 'rsetboot net' is needed to have the server boot from network otherwise it will choose the default boot item(maybe the harddisk). So, it is impossible to deploy a node with default boot order.

**Comment by gurevichmark** [comment]
For item 2, is there a reason why we treat "default" differently from what the value of default actually is ? If user runs `rsetboot stat`, can we just display what the default is set to, like `net` or `hd` instead of saying `boot override inactive` ?

For item 3. If the default boot item is harddisk, can we just attempt to boot from whatever the default is, like harddisk, if user does not explicitly run `rsetboot` ?

**Comment by zet809** [comment]
Hi, @gurevichmark 
For item2, from the IPMI specification, the output "boot override inactive" indicate the returned data is invalid or locked. And `rsetboot stat` will return what option is enabled right now, if error got, it will output "boot override inactive".
```
[root@fs1 xcat]# rsetboot frame45cn04,frame45cn05,frame45cn07,frame45cn02 state
frame45cn02: boot override inactive
frame45cn05: BIOS default
frame45cn04: Network
frame45cn07: Network
```
For item 3, if the `rsetboot state` doesn't return "Network", it shall boot from harddisk if there is OS installed. For the issue that CN get stuck in genesis, what will the genesis run? Send discovery request? If yes, it seems there is no 'mac,ip' pair defined on MN. If not, need to get the 'chain,currchain,currstate' attribute for the compute node.

**Comment by gurevichmark** [comment]
Based on the interlock conversation with @zet809 yesterday:
1. Still need to investigate boot order changes after the xCAT upgrade. However, one thing to note is that by default `rsetboot` sets the boot order only for the next provision. After the provision is done, boot order is reset to default. `rsetboot -p` can be used to set a persistent boot order.

2. `boot override inactive` message is actually an error. It is different for the `default` boot order message.

3. If boot order is `default`, the node should still be able to boot if there is an OS on the disk.

**Comment by gurevichmark** [comment]
@zet809 Is there a way to query what the "default" boot order is for each machine ? My thinking is that instead of displaying `BIOS default` message from `rsetboot stat` we can display what the actual setting is for the default ?

**Comment by zet809** [comment]
No, if the boot order is set to `BIOS default`, it can not get what the real order is. It need to be check in BIOS.

**Comment by zet809** [comment]
Hi, @gurevichmark , do you think we can close this issue? Thx!

**Comment by gurevichmark** [comment]
Closing this issue, the resolution is that `rsetboot -p` needs to be used in order to preserve boot setting.
