### ISSUE TITLE
[openbmc] bmcdiscover does not return the correct MTM and Serial for OpenBMC systems

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3205]
This issue is opened to close out any remaining work for verification with the `bmcdiscover` command for OpenPower OpenBMC support. 

API: [Inventory](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory)
Endpoint: `inventory/system`
Model Type Value: `{PartNumber}`
Serial Number Value:  `{SerialNumber}`

Examples:

**Comment by zet809** [comment]
Hi, @whowutwut , I'd like to keep this issue open until MTMS can be got other than "000000000"

**Comment by whowutwut** [comment]
Sure will try to monitor when ITC machines arrive

**Comment by whowutwut** [comment]
No change on the ITC machines, still all zeros being reported back...  going to move this to the next release to continue tracking.

**Comment by zet809** [comment]
Move to next release to trace.

**Comment by whowutwut** [comment]
Seems with later firmware levels, we do get the MTM/SN back after the host boots...  Should we close?

**Comment by zet809** [comment]
Hi, @whowutwut , I think we can, but we shall remove the "Invalid data" message below before close it.
Hi, @xuweibj , will you pls help to fix it? Thx a lot!
```
[root@stratton01 xcat]# rinv frame6u05 model
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis, contact firmware team!
frame6u05: SYSTEM Model : 8335-GTC
[root@stratton01 xcat]# rinv frame6u05 serial
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/fault, contact firmware team!
frame6u05: ERROR: Invalid data for /xyz/openbmc_project/inventory/system/chassis, contact firmware team!
frame6u05: SYSTEM SerialNumber : 1318C4A
```

**Comment by whowutwut** [comment]
We can close this after the above PR is merged.
