### ISSUE TITLE
[FVT] FVT for new ipmitools and conserver

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3213]
what to do:

1 FVT for dev task #3194  and #3193 
2 need to handle effect for migration(2.13.4->2.13.5 can be covered by daily regression)
3 need to handle effect for rcons ( x86 physical machine and openpower physical machine)
    The OS+arch for MN are:
          RH7.3 ppc64le
          ubuntu 16.04.1 ppc64le
          sles 12.2 ppc64le
          rh7.3 x86_64
4 need to handle SIGNAL problem for conserver

**Comment by chenglch** [comment]
For ipmitool testing
recreate the issue with kill -SIGKILL
- run `ipmitool sol activate` against OpenPOWER machines.
- kill -9 `ipmitool sol pid`
- rerun `ipmitool sol activate` immediately， the session should be disconnected in one minutes.
test the patch on ipmitool for conserver
- run `ipmitool sol activate` against OpenPOWER machines.
- kill -HUP `ipmitool sol pid`
- rerun `ipmitool sol activate` immediately, the session should be alive.

For conserver testing
- Migration test for conserver logs and rcons
- makeconservercf and `service conserver start/stop/restart/status` on different distribution.
