### ISSUE TITLE
[confignetwork fvt]installnic and secondary nic ethernet configuration

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3214]
The test cases need to add: 
1. static installnic configuration
2. secondary nic configuration
The configuration items shall cover the attributes in nics table: nicips,nictypes,niccustomscripts,nicnetworks,nicextraparams,nicaliases,disable.

**Comment by bybai** [comment]
Hi @tingtli , you can refer to this doc and old confignics test cases: https://github.com/bybai/xCAT_features/files/1031227/confignetwork.usage.design_v5.pdf

**Comment by tingtli** [comment]
The test cases list here.
1. Test case 1:  confignetworks_s_installnic_diskful
 Test steps. 1. Define CN, node definition should have installnic ip which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have installnic network
                    3. Define confignetworks -s as CN’s postscript 
                    4. Do diskful provision
                    5. Check if installnic is correctly configured by confignetworks.
2. Test case 2:  confignetworks_s_installnic_diskless
 Test steps. 1. Define CN, node definition should have installnic ip which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have installnic network
                    3. Define confignetworks -s as CN’s postbootscript
                    4. Do diskless provision
                    5. Check if installnic is correctly configured by confignetworks.
3. Test case 3:  confignetworks_secondarynic_diskless
 Test steps. 1. Define CN, node definition should have both installnic ip and  secondary nic’s nicips,nictypes,nicnetworks which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have both networks
                    3. Define confignetworks -s as CN’s postbootscript
                    4. Do diskless provision
                    5. Check if installnic and secondary nic are correctly configured by confignetworks.
4. Test case 4:  confignetworks_secondarynic_updatenode
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicnetworks which will be configured by confignetworks
                    3. Define confignetworks  as CN’s postscript
                    4. Do updatenode confignetworks
                    5. Check if secondary nic is correctly configured by confignetworks.
5. Test case 5:  confignetworks_secondarynic_nicaliases_updatenode
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicnetworks and nicaliases which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have secondary nic’s network
                    3. Define confignetworks  as CN’s postscript
                    4. Do updatenode confignetworks
                    5. Check if secondary nic  nicaliases is correctly configured by confignetworks.
6. Test case 6:  confignetworks_secondarynic_nicextraparams_updatenode
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicnetworks and nicextraparams which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have secondary nic’s network
                    3. Define confignetworks  as CN’s postscript
                    4. Do updatenode confignetworks
                    5. Check if secondary nic  nicextraparams is correctly configured by confignetworks.
7. Test case 7:  confignetworks_secondarynic_nicaliases_nicextraparams_diskful
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicnetworks ,nicaliases and nicextraparams which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have secondary nic’s network
                    3. Define confignetworks  as CN’s postscript
                    4. Do diskful provision 
                    5. Check if secondary nic ,nicaliases and  nicextraparams is correctly configured by confignetworks.
8. Test case 8:  confignetworks_secondarynic_nicaliases_nicextraparams_diskfless
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicnetworks ,nicaliases and nicextraparams which will be configured by confignetworks
                    2. Define correct networks table. The networks table should have secondary nic’s network
                    3. Define confignetworks  as CN’s postbootscript
                    4. Do diskless provision 
                    5. Check if secondary nic ,nicaliases and  nicextraparams is correctly configured by confignetworks.
9. Test case 9:  confignetworks_secondarynic_nicaliases_nicextraparams_diskfless_false
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicaliases and nicextraparams which will be configured by confignetworks. Do not define nicnetworks
                    3. Define confignetworks  as CN’s postbootscript
                    4. Do diskless provision 
                    5. Check if there is error returns.
10. Test case 10:  confignetworks_secondarynic_nicaliases_nicextraparams_updatenode_false
 Test steps. 1. Define CN, node definition should have secondary nic’s nicips,nictypes,nicaliases and nicextraparams which will be configured by confignetworks. Do not define nicnetworks
                    3. Define confignetworks  as CN’s postbootscript
                    4. Do updatenode confignetworks
                    5. Check if there is error returns.
11. Test case 11:  confignetworks_help
 Test steps. 1. run confignetworks -h/—help
                    2. check if there is help information is returned.

**Comment by daniceexi** [comment]
@tingtli could you polish the format like following? Thanks.


1. Test case:  confignetworks_s_installnic_diskful
Test steps:
    1). Define CN, node definition should have installnic ip which will be configured by confignetworks
    2). Define correct networks table. The networks table should have installnic network
    3). Define confignetworks -s as CN’s postscript 
    4). Do diskful provision
    5). Check if installnic is correctly configured by confignetworks.
2. Test cases: ...

**Comment by tingtli** [comment]
@daniceexi  Done.

**Comment by bybai** [comment]
Hi @tingtli ,
My ideas:

1. script name is confignetwork

2. test case 7 , 8, 9 can be deleted. These codes can be covered by updatenode test cases also.

3. You can add updatenode test case to cover false cases:
     If there is no nicips in nics table
     If there is no nictypes in nics table

4. We can add `confignetwork_disable_set_to_yes` and `confignetwork_disable_set_to_1`,  you can refer to `confignics_disable_set_to_yes` and `confignics_disable_set_to_1`

5. You can design new test cases for niccustomscripts;

**Comment by tingtli** [comment]
@bybai  Update according to your comments.
