### ISSUE TITLE
[confignetwork fvt]test cases for configuring bond

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3215]
What to do:

* [ ] offer a test cases scope
* [ ] add test cases for testing vlan
   * Configure bond based on:
      * ethernet nics

**Comment by tingtli** [comment]
confignetwork configuring bond case list:
confignetwork_bond_eth2_eth3
CN has 2 Ethernet nics, eth2 and eth3, user configures bond bond0 using ethernet nic eth2 and eth3

**Comment by bybai** [comment]
Yes, It is enough.

**Comment by tingtli** [comment]
PR #3413
