### ISSUE TITLE
[confignetwork fvt]test cases for configuring vlan

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3216]
What to do:

* [ ] offer a test cases scope
* [ ] add test cases for testing vlan
   * Configure vlan based on:
      * ethernet nics
      * bond

**Comment by tingtli** [comment]
confignetwork for vlan case list:
confignetwork_vlan_eth0
CN has Ethernet nic eth0, user wants to confgure 2 vlans, Configure vlan eth0.6 60.5.106.9 and eth0.7 70.5.106.9 based on ethernet nic eth0

**Comment by bybai** [comment]
It  is correct.

**Comment by tingtli** [comment]
PR #3413
