### ISSUE TITLE
[confignetwork fvt]test cases for configuring bridge

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3217]
What to do:

* [ ] offer a test cases scope
* [ ] add test cases for testing bridge

**Comment by tingtli** [comment]
confignetwork configuring bridge test cases list:
1.confignetwork_2eth_bridge_br0
CN has 2 Ethernet nics eth2 and eth3, user want to configure bond bond0 using eth2 and eth3, creates bridge br0 based on bond0
2.confignetwork__2eth_bridge_br22_br33
CN has 2 Ethernet nics eth2 and eth3, user wants to bond them as bond0, then make vlan bond0.2 and bond0.3, using bond0.2 create bridge br22,using bond0.3 create bridge br33. Use confignetwork to configure bond bond0, create vlan bond0.2 and bond0.3, create bridge br22 and br33
3. confignetwork__3eth_bridge_br1_br2_br3
CN has 3 Ethernet nics. User wants to use one Ethernet nic eth0 as management network for xCAT, user wants to use the other 2 nics to create 3 vlan, then create 3 bridge based on these vlan as data network. So he can use `confignetwork -s` to configure all nics, create bond bond0 with eth2 and eth3, create vlan bond0.1 bond0.2 bond0.3, create bridge br1 based on bond0.1, create bridge br2 based on bond0.2, create br3 based on bond0.3

**Comment by bybai** [comment]
This is enough for valid cases. You'd better add some invalid cases.

**Comment by tingtli** [comment]
Fixed in PR #3441.
