### ISSUE TITLE
The tftp and dhcp working mode for hierarchical cluster

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3218]
The difference behavior for different setting of site attribute sharedftp, shareinstall and disjointdhcp

1. How to set the values
2. Which special values suggested for special scenarios.

Acceptance: 
The list of setting cases for difference scenarios.

**Comment by gurevichmark** [comment]
Should the `installloc` site attribute also be mentioned ?

**Comment by zet809** [comment]
hi, @gurevichmark , the `installloc` attribute will be used when `sharedinstall` set to `sns` or `all`. It maybe included in a special scenario.

**Comment by robin2008** [comment]
And actually,  for Linux,  "sharedinstall" is not used (It is only in "aixinstall" and "snmove"). 
For Linux, by default,  SN will mount /install from MN (means "all" and the installloc is from default MN export)

This task is to make clear what the hierarchy and large cluster mode we want to support, and in each mode, what's the typical configuration for the PXE services (tftp/dhcp)
And the doc (http://xcat-docs.readthedocs.io/en/stable/advanced/hierarchy/index.html) will be modified accordingly.

In addition, we need to check if xcat current codes are following what we defined here, if not, we will log ticket to fix them.

**Comment by robin2008** [comment]
In `Hierarchical Clusters / Large Cluster Support` document, it is clearly defined 3 kinds of configuration
```
The following configurations are supported:

        Each service node installs/manages a specific set of compute nodes
        Having a pool of service nodes, any of which can respond to an installation request from a compute node (Requires service nodes to be aligned with networks broadcast domains, compute node chooses service nodes based on who responds to DHCP request first.)
        A hybrid of the above, where each specific set of compute nodes have 2 or more service nodes in a pool
```
_In this ticket, we only cover the PXE related service,  for others, like parallel shell, remote control, they may be considered in other ticket._


1st option:  dedicate mode.  It is used to split a large management domain into separate islands, and assign different service node to manage one or more islands. 

In such mode,  the CN nodes will be explicitly bound to a service node or management node (empty service node) 

2nd option: global share mode. service nodes and management node consists of a big pool to server the PXE provisioning, normally it used in a FLAT network, and the installation workload are balanced among the pool (the first responder of PXE request)

In such mode, don't specify a service node for a compute node.

3rd mode: share group mode. It is a hybrid of the above two. Service nodes and management node consists of many different pools to server the PXE provisioning for different groups of compute nodes.
The service nodes are shared in one  group, but isolated between different groups.

**Comment by robin2008** [comment]
For each of the above option, need to clearly define the designed behavior and how to config, especially based on different networking,  flat, vlan(subnet), etc.

**Comment by robin2008** [comment]
Here for discussion:

Global share mode:  normally used in smaller scalable cluster, say 1000 compute nodes.

1, Normally using FLAT in provisioning network
2, Table 'site': sharedtftp=1, disjointdhcps=0, installloc=/install
3, Table servicenode to define SN: nameserver=1, dhcpserver=1, tftpserver=1, nfsserver=1, conserver=1
4, Only 1 network is defined. And DHCP on service node will not server “dynamic range”, it should only be configured on MN.
5, For CN, not required to define servicenode, xcatmaster, tftpserver, nfsserver.  For those attributes, the node will use whoever responds to its boot request as its master.

Both MN and SN serve PXE services, they are peers. All installation request will be redirected to server node pool randomly.
As both tftpboot and install are shared, not required to dispatch `nodeset` to other MN/SN. 


Dedicate mode: 

1, Normally used in an isolated subnet networking. 
2, Table site: sharedtftp=0, disjointdhcps=1
3, Table servicenode to define SN: nameserver=1, dhcpserver=1, tftpserver=1, nfsserver=1, conserver=1
4, Multiple subnets are required for different SN, “dynamic range” will be configured on SN too.
5, For CN, servicenode=sn, xcatmaster=cn_facing_IP of SN, tftpserver=<xcatmaster>, nfsserver=<xcatmaster>.

"installloc=/install" is not mandatory here, if not using an shared install directory, you need to sync all OS image contents to SNs after any modification. And in large cluster, GPFS share storage is recommended.

netboot/dhcp will be dispatched to MN and dedicate SN only, ( and if using shared installloc, not required the kickstartfile ) 

Group share mode: (Now only support to define primary and backup SN)

1, Both FLAT and subnet networking
2, Table site: sharedtftp=0, disjointdhcps=1, installloc="/install" 
3, Table servicenode: Setting nameserver=1, dhcpserver=1, tftpserver=1, nfsserver=1, conserver=1
4, service node server DHCP, but “dynamic range” is only configured on MN, ignored on SN
5, For CN, servicenode=psn,bsn,  xcatmaster=cn_facing_IP of PSN, tftpserver=<xcatmaster>, nfsserver=<xcatmaster>.

"installloc=/install" is not mandatory here, if not using an shared install directory, you need to sync all OS image contents to SNs after any modification. And in large cluster, GPFS share storage is recommended.

netboot/dhcp will be dispatched to MN and failover group, ( and if using shared installloc, not required the kickstartfile )

**Comment by robin2008** [comment]
@immarvin help to take a look first.

**Comment by zet809** [comment]
Hi, @robin2008 , some questions:
For 1. Global share mode
    1. What does "All installation request will be redirected to server node pool randomly" mean?
    2."For CN, not required to define servicenode, xcatmaster, tftpserver, nfsserver. For those attributes, the node will use whoever responds to its boot request as its master.", it is true for pxe on x86_64, but doesn't work for power petitboot/grub2. 
    So, in this case, for power, the SN is just a DHCP/DNS server and all the following traffic are go through MN and CN.

For 2.Dedicate mode:
    The MN and CN shall not be able to contact each other directly. So why dispatch netboot/dhcp to MN? 

For 3. It shall be *share group mode*:
     For dynamic range, it need to be set only on MN in FLAT network, right?
     How to position the psn and bsn? Multiple next-server configuration in DHCP may work, but need verify.

**Comment by robin2008** [comment]
Adding the document in box:
`https://ibm.box.com/s/o923g7tzyxzvdzunh2gr1dkvx6w1fze2`

**Comment by zet809** [comment]
Lets close this task as the investigation work is done.
