### ISSUE TITLE
The bundle to setup and use openbmc simulator to support multiple BMC IPs

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3220]
1. a configuration file specify the IP range and nicname
2. a test case generate the env: 
     bmc node based on the IP range
3. reuse the openbmc test cases to verify the simulator functions
4. rpower state on 100,1000,5000 IP

**Comment by xuweibj** [comment]
Test environment:
MN: c910f03c11k08

Results:
100 IP: rpower on 6s; rpower stat: 1s
1000 IP: rpower on 60s; rpower stat: 15s
5000 IP: rpower on 305s; rpower stat: 74s

**Comment by xuweibj** [comment]
The task was finished in pull request #3265
