### ISSUE TITLE
lstree command does not display correct hierarchy output.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3230]
`lstree` command does not display correct hierarchy output if compute nodes specify their service nodes as IP.

1. The man page for `lstree -s` command says you should get this output
```
Service Node: mysn01
|__mycn01
|__mycn02
|__mycn03

Service Node: mysn02
|__mycn11
|__mycn12
|__mycn13
......
```
But when compute nodes specify their service nodes using IP, instead of service node name, its IP address is displayed, making it hard for the user to know which service node it actually is:

```
[root@fs3 ~]# lsdef mid05tor12cn07,mid05tor12cn08 -i servicenode -c
mid05tor12cn07: servicenode=172.20.254.1,172.20.254.2
mid05tor12cn08: servicenode=172.20.254.2,172.20.254.1
[root@fs3 ~]#

[root@fs3 ~]# lstree -s
Service Node: 172.20.254.1,172.20.254.2
|__mid05tor12cn07

Service Node: 172.20.254.2,172.20.254.1
|__mid05tor12cn08

[root@fs3 ~]
```

2.  The man page for `lstree -s <service node name>` command says you should get `lstree` output only for the specified service node, but it does not work when service nodes are specified as IP. Using setup above:

```
[root@fs3 ~]# lstree -s sn01
[root@fs3 ~]# lstree -s 172.20.254.1
Error: Invalid nodes and/or groups in noderange: 172.20.254.1
[root@fs3 ~]#
```

**Comment by daniceexi** [comment]
@gurevichmark it's not a correct usage, see the definition of the **servicenode** attribute

```
servicenode:	A comma separated list of node names (as known by the management node) that provides most services for this node. 
```
