### ISSUE TITLE
Create documentation to help configure large systems [OpenPower]

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3231]
Similar to the [Power775](https://sourceforge.net/p/xcat/wiki/XCAT_Power_775_Hardware_Management/) support documentation, create documentation that can be used generically that would help setting pu large scale systems using xCAT. 

* Best Practices with Configuration of xCAT 
* Database 
* Service Nodes 
* HA 
* Switch Discovery
* Hardware Discovery

**Comment by zet809** [comment]
Remove milestone and add when needed.
