### ISSUE TITLE
makedhcp error messages

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3233]
While removing nodes I ran makedhcp -d and got the following error messages:
````
# makedhcp -d svgrp
Error: Invalid nodes and/or groups in noderange: svgrp
[root@mn1 consoles]# makedhcp -d svcgrp
Error: Unable to dispatch hierarchical sub-command to sn1:3001.  Error: Connection failure: IO::Socket::INET: connect: No route to host at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn4:3001.  Error: Connection failure: IO::Socket::INET: connect: timeout at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn3:3001.  Error: Connection failure: IO::Socket::INET: connect: timeout at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn2:3001.  Error: Connection failure: IO::Socket::INET: connect: timeout at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
````

It seem the task was completed but if these error messages are not important can they be suppressed, if they are a sign of something wrong/going wrong please let me know.

**Comment by immarvin** [comment]
hi @cganglin , this is the default behavior in xcat currently, we are planning to enhance this in this or next release.

**Comment by robin2008** [comment]
I don't think we have a plan to change it for share service node pool in recent,  it seems a design behavior.  When you hit such error,  it means you have xCAT SNs and the xcatd on those SNs are not active, then the request cannot be dispatched to those MNs.

If in a share pool of hierarchy supporting, those errors must be known by admin,  and fix them ASAP.

**Comment by whowutwut** [comment]
@cganglin  Yes, this is because you created more service node definitions than are really there, so it indicates an error because we cannot communicate to the service nodes defined.
