### ISSUE TITLE
bmcdiscover error

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3234]
Running bmcdiscover with a range like 10.10.2.150-250 produces the following error.  When bmcdiscover is run with like 10.10.1.0/24  it runs without error messages.  What is wrong here?

# bmcdiscover --range 10.10.1.150-250
10.10.1.152,8335-GCA,7817C0A,,,mp,bmc
10.10.1.153,8335-GCA,7817BEA,,,mp,bmc
10.10.1.154,8335-GCA,7817BFA,,,mp,bmc
Error: bmcdiscover plugin bug, pid 62711, process description: 'xcatd SSL: bmcdiscover for root@localhost: bmcdiscover instance' with error 'Can't use string ("Can not get status of 2200 port.") as a HASH ref while "strict refs" in use at /opt/xcat/lib/perl/xCAT/MsgUtils.pm line 407.

**Comment by cxhong** [comment]
duplicate with #3207
