### ISSUE TITLE
nodeset errors

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3235]
Command seem to complete but lots of error messages - using xCAT 2.13.4

[root@mn1 ~]# nodeset svcgrp osimage=rhels7.3-ppc64le-install-service
sn1: install rhels7.3-ppc64le-service
sn2: install rhels7.3-ppc64le-service
sn3: install rhels7.3-ppc64le-service
sn4: install rhels7.3-ppc64le-service
Error: Unable to dispatch hierarchical sub-command to sn3:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn1:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn2:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn4:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
[root@mn1 ~]# nodeset sn1 osimage=rhels7.3-ppc64le-install-service
sn1: install rhels7.3-ppc64le-service
Error: Unable to dispatch hierarchical sub-command to sn3:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn2:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn4:3001.  Error: Connection failure: IO::Socket::INET: connect: timeout at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
[root@mn1 ~]# nodeset sn2 osimage=rhels7.3-ppc64le-install-service
sn2: install rhels7.3-ppc64le-service
Error: Unable to dispatch hierarchical sub-command to sn1:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn3:3001.  Error: Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.
Error: Unable to dispatch hierarchical sub-command to sn4:3001.  Error: Connection failure: IO::Socket::INET: connect: No route to host at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.

**Comment by cxhong** [comment]
duplicate with issue #3233
