### ISSUE TITLE
Service node build stops

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3236]
Using xCAT 2.13.4.  Only additional software added to the standard xCAT service node install is Mellanox OFED.  The install stop so does the versions called out in the package list is too old?

Starting installer, one moment...
anaconda 21.48.22.93-1 for Red Hat Enterprise Linux 7.3 started.
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * when reporting a bug add logs from /tmp as separate text/plain attachments
18:19:25 Running pre-installation scripts
18:19:29 Not asking for VNC because of an automated install
18:19:29 Not asking for VNC because text mode was explicitly asked for in kickstart
Starting automated install...
Checking software selection
================================================================================
================================================================================
Question

You have specified that the package 'openssl098e.ppc64' should be installed.
This package does not exist.  Would you like to ignore this package and continue
with installation?

Please respond 'yes' or 'no':

**Comment by immarvin** [comment]
hi @cganglin , 'openssl098e.ppc64' is in service.rhels7.ppc64.pkglist instead of  service.rhels7.ppc64le.pkglist, would you please provide the osimage definition and the node definition?

**Comment by cganglin** [comment]
Hi I updated my definition to use service.rhels7.ppc64le.pkglist.  Just using openssl with a version number worked also but I overlooked the ppc64le package list and have updated my configuration.  The stop during install was fixed .
