### ISSUE TITLE
xCAT range command failing

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3237]
When i try to use a range in xCAT I am getting errors like the one below
root@mn1 consoles]#  rpower sn[1-3] off
Unsupported command: rpower sn2

If using the command with just a single node or group works.

**Comment by gurevichmark** [comment]
Have you tried something like `rpower sn1,sn2,sn3 off` ?
Also try `rpower sn[1-3] stat`

**Comment by xuweibj** [comment]
Hi @cganglin, could you provide more information about this issue? Such as nodes' definition, xcat's version.

**Comment by cganglin** [comment]
Hi @gurevichmark I am using xCAT 2.13.4.  No I haven't tried sn1,sn2,sn3 but have since rebuilt the nodes so please close.  Should this happen again I will collect the information you requested.  Thanks

**Comment by gurevichmark** [comment]
Closing issue as originator requested.
