### ISSUE TITLE
[FVT] makehosts failed to configure multiple nic aliases 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3242]
Found this problem in automation environment.

xcat version:  ``2.13.5 (git commit d9d0cfd42ccdee03085f36fed194d850622804b9, built Thu Jun  8 06:15:37 EDT 2017)``
xcat build : ``xcat2_autobuild_daily_builds/20170608.0615/linux_rpm/devel/core-rpms-snap.tar.bz2``

How to reproduce :

    The original /etc/hosts:
    cat /etc/hosts
    127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    ........
    10.3.11.2 c910f03c11 c910f03c11.pok.stglabs.ibm.com
    10.0.0.201 c910hmc01 c910hmc01.pok.stglabs.ibm.com
    50.5.1.1 c910f05c01cmm01 c910f05c01cmm01.pok.stglabs.ibm.com

    RUN:mkdef -t network -o 11_1_0_0-255_255_0_0 net=11.1.0.0 mask=255.255.0.0 mgtifname=eth2  mtu=1501 [Thu Jun  8 20:49:54 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:mkdef -t network -o 12_1_0_0-255_255_0_0 net=12.1.0.0 mask=255.255.0.0 mgtifname=eth2   mtu=1501 [Thu Jun  8 20:49:54 2017]
    ElapsedTime:1 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:mkdef -t network -o 13_1_0_0-255_255_0_0 net=13.1.0.0 mask=255.255.0.0 mgtifname=eth3    mtu=1503 [Thu Jun  8 20:49:55 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:mkdef -t network -o 14_1_0_0-255_255_0_0 net=14.1.0.0 mask=255.255.0.0 mgtifname=eth3     mtu=1503 [Thu Jun  8 20:49:55 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:chdef c910f03c11k05 nicips.eth2="11.1.0.100|12.1.0.100" nictypes.eth2=Ethernet nicnetworks.eth2="11_1_0_0-255_255_0_0|12_1_0_0-255_255_0_0" nicaliases.eth2="aliases1-1|aliases1-2" [Thu Jun  8 20:49:55 2017]
    ElapsedTime:1 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:chdef c910f03c11k05 nicips.eth3="13.1.0.100|14.1.0.100" nictypes.eth3=Ethernet nicnetworks.eth3="13_1_0_0-255_255_0_0|14_1_0_0-255_255_0_0" nicaliases.eth3="aliases2-1|aliases2-2" [Thu Jun  8 20:49:56 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    1 object definitions have been created or modified.
    CHECK:rc == 0    [Pass]

    RUN:makehosts c910f03c11k05 [Thu Jun  8 20:49:56 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    CHECK:rc == 0    [Pass]

    RUN:cat /etc/hosts [Thu Jun  8 20:49:56 2017]
    ElapsedTime:0 sec
    RETURN rc = 0
    OUTPUT:
    127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    ........
    10.3.11.2 c910f03c11 c910f03c11.pok.stglabs.ibm.com
    10.0.0.201 c910hmc01 c910hmc01.pok.stglabs.ibm.com
    50.5.1.1 c910f05c01cmm01 c910f05c01cmm01.pok.stglabs.ibm.com
    12.1.0.100 c910f03c11k05-eth2 c910f03c11k05-eth2.pok.stglabs.ibm.com aliases1-2
    14.1.0.100 c910f03c11k05-eth3 c910f03c11k05-eth3.pok.stglabs.ibm.com aliases2-2
    CHECK:output =~ aliases1-1    [Failed]

**Comment by bybai** [comment]
This is not makehosts issue.  The test case has problem.
