### ISSUE TITLE
bmcdiscovery error

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3264]
Using xCAT 2.13.5.
Compute Nodes are Minsky 
All compute nodes are in the same state - bmc set to dhcp.  Dhcp address received from MN without issues.
When i do discovery I get the below message
```
[root@mn1 ~]# bmcdiscover --range 10.10.1.0/24
10.10.1.102,8335-GTB,7817BBA,,,mp,bmc
Error: Can not get status of 2200 port for ip 10.10.1.106.
```
If i run the command immediately after the node is discovered OK.  Wait a little and run bmcdiscover and the error is produced again.  Is this something to be concerned about?

**Comment by zet809** [comment]
hi, @xuweibj , will you pls take a look at this issue? Thx!

**Comment by xuweibj** [comment]
Hi @cganglin , could you help to run ``nmap 10.10.1.106 -p 2200 -Pn`` and show me the result?

**Comment by whowutwut** [comment]
Closing this out, @cganglin  Please re-open this if you continue to see issues using the latest builds.

**Comment by cganglin** [comment]
Sorry,was swamp for some time. Now 2.13.5 is official will try everything again and give feedback. Thanks again @whowutwut
