### ISSUE TITLE
[FVT]Add missed cases for hardware control bundle

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#3269]
Reviewed all the hardware control cases , we missed following cases. Need to realize them in the test bucket.

CEC with HMC:
rpower_onstandby 

BMC:
rpower_softoff
rpower_wake    (delayed for low priority)
rpower_suspend_w_o_r  (delayed for low priority)

rinv_mprom
rinv_guid
rinv_dimm

**Comment by hu-weihua** [comment]
This issue  is related task #3181

**Comment by tingtli** [comment]
It is fixed by #PR 3285.
