### ISSUE TITLE
[FVT]:refine rpower cases in test bucket.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#3270]
Review rpower cases in current test bucket and find the cases are not formatted well and miss some information. Need to refine all the rpower cases.
```
rpower_off
rpower_stat
rpower_status
rpower_state
rpower_boot
rpower_on
rpower_reset
rpower_noderange
rpower_noderange_nodeps
rpower_err_noderange
```

**Comment by hu-weihua** [comment]
I don't think we need to open one bug specially, maybe it is ok to refer the pull request to task. But that is fine, I have merged the pull request.

**Comment by tingtli** [comment]
Since the code is merged. Close this bug.
