### ISSUE TITLE
[openbmc]rflash support for firmware file activate

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3273]
OpenBMC `rflash` command support - priority 3:

Activate uploaded file
`rflash <node> <id> --activate`

If activating the PNOR, compute side should be powered off before activating the update.

**Comment by gurevichmark** [comment]
Implemented in Pull Request #3550

**Comment by zet809** [comment]
Closed since the code had been included in 2.13.6 RC build.
