### ISSUE TITLE
Feature Request - How to verify the Service Nodes are really used to service commands etc

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3277]
I know I can put xcat in debug mode but that should be a last resort.  I know I can see in the /tftpboot/petitboot/<nodename> file on MN to see the SN that will service the node build.  What I would like to know is if there is a way to verify when I run commands from MN to CN it uses the correct SN.  I tailed the cluster log and ran uptime across all of my nodes but the only thing that showed in the log was 
Jun 15 21:49:37 mn1 xcat[11445]: xCAT: Allowing xdsh to cn uptime for root from localhost

I was expecting to see a log of the command being dispatched to different SN for servicing.  Any solution available for this today.  Using 2.13.5.

**Comment by cganglin** [comment]
Additonal question - is there a list of commands that will be serviced by the SN or everything run from the MN with destination to a CN goes via SN?

**Comment by immarvin** [comment]
2 options:
1. run ``cat /var/log/xcat/cluster.log|grep 'xCAT: Allowing'|grep -v 'from localhost'`` on MN
2. run ``xdsh  service cat  /var/log/xcat/commands.log`` or ``xdsh  service -s tail -f /var/log/xcat/commands.log`` to monitor the request dispatched to the service node in "service" group
