### ISSUE TITLE
xCAT allowed illegal character in postscript 

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3279]
I found that xCAT 2.13.5 allowed a space while adding the postscript information to node definition, because of this I could not build and subsequently couldn't open consoles etc and didn't get an error while inputting. 
I cut and paste the following:
```
postscripts=syslog,remoteshell,syncfiles,servicenode,mlnxofed_ib_install.v2 -p /install/ofed/MLNX_OFED_LINUX-3.4-2.0.0.1-rhel7.3-ppc64le.iso, hardeths, confignics -s,configiba.1port
                                                                                                      ^             ^
                                                                                      Spaces were inputted at those two places
````
When i tried building i kept getting the following which was hard to figure out because everything looked good.           
````
<166>Jun 15 17:40:29 xcat.genesis.doxcat: Received destiny=  <error>No archictecture defined in nodetype table for sn4</error>
  <errorcode>1</errorcode>
runcmd=bmcsetup
<166>Jun 15 17:40:29 xcat.genesis.doxcat: The destiny=<error>No, destiny parameters=bmcsetup
<163>Jun 15 17:40:29 xcat.genesis.doxcat: Unrecognized directive (dest=<error>No)
````

I finally found the 2 spaces and after correcting everything worked as plan.  It would be good for incorrect format to be flagged in someway just like when one uses tabedit it does a check and enforce some rules before saving.

**Comment by cganglin** [comment]
![2017-06-16_08-40-43](https://user-images.githubusercontent.com/28903850/27231857-40410d60-5271-11e7-977d-c31124057c1f.png)

My write up may have my pointers (^) showing at the wrong place.  Preview this picture to see where I had the spaces - denoted by the orange markers

**Comment by immarvin** [comment]
hi @cganglin ,how did you add the "hardeths" and "confignics -s" to the postscripts? ``chdef -p``?

**Comment by cganglin** [comment]
Yes

**Comment by immarvin** [comment]
would you please provide the ``chdef`` command to create the resulted "postscripts" attribute? The white spaces can not be added unless the white spaces are specified by yourself.

**Comment by cganglin** [comment]
This is the command but again as I mentioned before, I wrote the commands out then cut and paste

 chdef sn4 -t node -o sn4 -m postscripts="mlnxofed_ib_install.v2 -p /install/ofed/MLNX_OFED_LINUX-3.4-2.0.0.1-rhel7.3-ppc64le.iso,  hardeths,  confignics -s,configiba.1port"

**Comment by immarvin** [comment]
hi @cganglin , thanks for your information. 

@zet809 , from my point of view, I do not think  extra spaces in ``postscripts`` will break anything. would you please take a look why the extra spaces in ``postscripts`` will cause discovery failure?

thanks

**Comment by zet809** [comment]
hi, @cganglin , can you show me the 'chain' attribute? Thx!

**Comment by immarvin** [comment]
verified that the extra spaces in the ``postscripts`` won't hurt anything for ``nodeset`` and node provision

**Comment by cxhong** [comment]
@cganglin,  I think there was something else caused your issue at that time.  the service node on our test system also has space for the postscripts.
```
postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,mlnxofed_ib_install -p /install/mlnxofed/MLNX_OFED_LINUX-3.4-2.0.0.1-rhel7.3-ppc64le.iso, hardeths, confignics -s,servicenode
    profile=service
    provmethod=rhels7.3-ppc64le-install-service
```

**Comment by cganglin** [comment]
Ok. Thanks for looking into this
