### ISSUE TITLE
Changing site table attributes using chdef does not return the correct message

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3289]
This is just one sample, but I'm thinking that this behavior may applies to most attributes for the site table. 

I was using the `chdef`  command to change attributes for the site table and the message returned does not reflect correctly on the behavior... 

```
[root@fs2vm110 ~]# tabdump site | grep dhcplease
"dhcplease","43200",,
[root@fs2vm110 ~]# lsdef -t site clustersite -i dhcplease
Object name: clustersite
    dhcplease=43200
[root@fs2vm110 ~]# chdef -t site clustersite dhcplease=300
No object definitions have been created or modified.
```

Looking at the value afterwards, it has made the change: 
```
[root@fs2vm110 ~]# lsdef -t site clustersite -i dhcplease
Object name: clustersite
    dhcplease=300
```

**Comment by immarvin** [comment]
hi @chenglch , would you please take a look  at this? thanks

**Comment by chenglch** [comment]
This error is imported by the pull request #3045, @zet809

**Comment by zet809** [comment]
hi, @whowutwut , I had fixed this issue in Pull Request #3301 , will you pls help to verify this defect? Thx!

**Comment by whowutwut** [comment]
Verified on todays development build... 
```
[root@fs2vm110 ~]# lsxcatd -v
Version 2.13.6 (git commit 576a72598788a6de04735c0df2f00fef46a09a30, built Fri Jun 30 06:15:40 EDT 2017)
```

Looks good for the above scenario. 
```
[root@fs2vm110 ~]# tabdump site | grep dhcplease
"dhcplease","300",,
[root@fs2vm110 ~]# lsdef -t site clustersite -i dhcplease
Object name: clustersite
    dhcplease=300
[root@fs2vm110 ~]# chdef -t site clustersite dhcplease=3000
1 object definitions have been created or modified.   <==== EXCELLENT!
[root@fs2vm110 ~]# lsdef -t site clustersite -i dhcplease
Object name: clustersite
    dhcplease=3000
```

**Comment by hu-weihua** [comment]
Test case has been added by #3609.  Remove ``testcase_requested`` label

**Comment by whowutwut** [comment]
@hu-weihua For future, is it possible to show the output of the testcase in the PR? 

First the failure from the testcase, then update xCAT with the fix and show that the testcase works...  Otherwise, this has to be executed by the author of the testcase right, so it should be copy/paste... Otherwise how do we validate it?

**Comment by hu-weihua** [comment]
@whowutwut After we added a test case, as long as this case can be run in automation environment, fvt will add it into daily regression. 

Below is the daily regression result of test cast "chdef_site_check" added by pr #3609 

```
------START::chdef_site_check::Time:Thu Apr 26 08:13:48 2018------

RUN:var=`lsdef -t site clustersite -i dhcplease|grep 'dhcplease=' |awk -F= '{print $2}'`;echo $var>/tmp/sitevalue;chdef -t site clustersite dhcplease=300 [Thu Apr 26 08:13:48 2018]
ElapsedTime:1 sec
RETURN rc = 0
OUTPUT:
1 object definitions have been created or modified.
CHECK:rc == 0   [Pass]
CHECK:output =~ 1 object definitions have been created or modified.     [Pass]

RUN:lsdef -t site clustersite -i dhcplease|grep 'dhcplease=' |awk -F= '{print $2}' [Thu Apr 26 08:13:49 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
300
CHECK:output =~ 300     [Pass]

RUN:if [ -f  /tmp/sitevalue ];then var=`cat /tmp/sitevalue`;chdef -t site clustersite dhcplease=$var;rm -rf /tmp/sitevalue;fi [Thu Apr 26 08:13:49 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
1 object definitions have been created or modified.
CHECK:rc == 0   [Pass]

------END::chdef_site_check::Passed::Time:Thu Apr 26 08:13:49 2018 ::Duration::1 sec------
```

Of cause, I will notice fvt to add output of the testcase in pull request.
