### ISSUE TITLE
[openbmc] rspconfig - support setting the ip address to DHCP for the BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3295]
This task tracks the support for adding to rspconfig to set the BMC IP address to DHCP. 

* ~~Power off compute hosts~~  - Currently for OpenPower, we do not power off the compute node when we reset the BMC IP address back to DHCP.  Should we consider this? 
* Reset the BMC IP address back to DHCP

**Comment by zet809** [comment]
Hi, @whowutwut , I don't think we need to power off the compute node when reset BMC back to DHCP. 1. If we keep host is powering on, we can check the dynamic IP BMC got through the host.
2. From my point of view, the changing of BMC ip shall not affect the host.

**Comment by whowutwut** [comment]
@zet809 Thanks for the comments, that is a valid point.  In the re-discovery scripts that I have written for P8 OpenPower nodes,  I normally just use raw commands  directly to BMC to reset to DHCP, but I will change those to use `rpower <> off` then `rspconfig`

**Comment by xuweibj** [comment]
https://github.com/openbmc/docs/blob/master/dbus-interfaces.md#orgopenbmcnetworkmanager

**Comment by whowutwut** [comment]
@xuweibj did you look into that URL? If you think you have a command to execute I can help execute it if we think we may mess up the configuration where we will not be able to recover IP  address.  I have a serial cable plugged into the box elder board on mid05tor12cn02 so that would be the machine we should try this on

**Comment by xuweibj** [comment]
Hi @whowutwut ,
1. To set BMC to DHCP:
```
curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": ["eth0"]}' https://172.20.140.102/org/openbmc/NetworkManager/Interface/action/EnableDHCP
```
It will not get any response and hung there. 
Now ``mid05tor12cn02`` bmc ip is ``172.20.253.105``.

2. Check Address Type:
```
curl -k -b cjar -H "Content-Type: application/json" -X POST -d '{"data": ["eth0"]}' https://172.20.140.102/org/openbmc/NetworkManager/Interface/action/GetAddressType
{
  "data": "DHCP",
  "message": "200 OK",
  "status": "ok"
}
```

**Comment by whowutwut** [comment]
Nice!! Thanks!  That's unfortunate that it hangs. The ipmitool command returned so we could get back out .. :-(. Can we put that curl cmd into ip=dhcp command or does xcat not handle that hang well?

**Comment by xuweibj** [comment]
Now, we did not have code working on ``ip=dhcp``, I think we need to find a method to handle this. Sorry, I did not know how to set it back to static, now we cannot try again.

**Comment by whowutwut** [comment]
Opened an issue over on openbmc https://github.com/openbmc/openbmc/issues/1952 , this endpoint needs to be exposed first.   The ones referenced above by @xuweibj  is pointing at the wrong endpoint.

**Comment by gurevichmark** [comment]
This will basically be a "reset" action. When openbmc issue 1952 is implemented, it will reset ip to DHCP along with resetting other BMC attributes.

**Comment by zet809** [comment]
Hi, @whowutwut and @gurevichmark , do you think this function can be covered by `rspconfig <node> ip=dhcp` within OpenBMC support?

**Comment by whowutwut** [comment]
The firmware on frame6u05 does have this support.   
Here's an example of what we need to do...
UT code here: 
```
[root@stratton01 frame6u05]# pwd
/root/c910env/notes/openbmc/UT/Network/frame6u05
```


1. Reset to DHCP 
```

[root@stratton01 frame6u05]# ./login.sh
==> IP=10.6.5.254
+ curl -c cjar -k -X POST -H 'Content-Type: application/json' -d '{"data": [ "root", "0penBmc" ] }' https://10.6.5.254/login
{
  "data": "User 'root' logged in",
  "message": "200 OK",
  "status": "ok"
}[root@stratton01 frame6u05]# ./reset_dhcp.sh
+ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X POST -d '{"data": [] }' https://10.6.5.254/xyz/openbmc_project/network/action/Reset
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```

2. Reboot the BMC 

```
[root@stratton01 frame6u05]# ./reboot_bmc.sh
+ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data": "xyz.openbmc_project.State.BMC.Transition.Reboot" }' https://10.6.5.254/xyz/openbmc_project/state/bmc0/attr/RequestedBMCTransition
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```

I opened this issue: https://github.com/openbmc/openbmc/issues/2140 

But we should be able to code up the `ip=dhcp` changes based on the above..

**Comment by whowutwut** [comment]
Ok the above is correct to reset to DHCP. Can work on this issue.

**Comment by gurevichmark** [comment]
Implemented by #3716

**Comment by zet809** [comment]
hi, @whowutwut , do you think we can close this task as the code had been merged?

**Comment by whowutwut** [comment]
@zet809 Yes, but I would like to verify the issue... I thought that was the established process.  The issue is set to pending when the pull request is merged, then the originator validates and closes...

Why has this been changing??  I've noticed that you are closing lots of issues without the originator validating and closing it out...

**Comment by whowutwut** [comment]
I periodically go through and look for issues that I open and are set to pending, I don't do this daily, so you have to give us the opportunity to follow the process we have.

**Comment by zet809** [comment]
Let's move this task to done and close it after verified.

**Comment by zet809** [comment]
Hi, @whowutwut , have you verified this defect?

**Comment by whowutwut** [comment]
Yes, but this function is not exposed to the user.  Let me see if i can partially expose certain functions of rspconfig

**Comment by whowutwut** [comment]
@zet809  the last commit in that pull request exposes the ip=dhcp.   Once that is merged, we can close out this issue.  

It is something that customers are looking for, and we should not block all of `rspconfig` when we have partial function that can be leveraged. @ralphbellofatto the above PR will expose `rspconfig <> ip=dhcp` to factory reset.  Although there are still issues in the openbmc side... (https://github.com/openbmc/openbmc/issues/865#issuecomment-325803073)

**Comment by ralphbellofatto** [comment]
this will be available with an openbmc update or an xcat update?

**Comment by whowutwut** [comment]
After the above code is merged it will be available with xcat update   Exposes the option for ip=dhcp

**Comment by ralphbellofatto** [comment]
when is that xcat update due out?

**Comment by ralphbellofatto** [comment]
log of last boot sequence...
[c460c817.console.log.txt](https://github.com/xcat2/xcat-core/files/1262156/c460c817.console.log.txt)

system went bad here:
```
[Tue Aug 29 21:07:12 2017][  132.221371] nvidia-uvm: Loaded the UVM driver in 8 mode, major device number 240
[Tue Aug 29 21:07:32 2017][  152.456546] Unable to handle kernel paging request for data at address 0x00000028
[Tue Aug 29 21:07:32 2017][  152.456699] Faulting instruction address: 0xc00800004045d084
[Tue Aug 29 21:07:32 2017][  152.456808] Oops: Kernel access of bad area, sig: 11 [#1]
[Tue Aug 29 21:07:32 2017][  152.456898] SMP NR_CPUS=2048 
[Tue Aug 29 21:07:32 2017][  152.456899] NUMA 
[Tue Aug 29 21:07:32 2017][  152.456956] PowerNV
[Tue Aug 29 21:07:32 2017][  152.457033] Modules linked in: mst_pciconf(OE) nvidia_uvm(POE) nfsv3 nfs fscache binfmt_misc rdma_ucm(OE) ib_ucm(OE) rdma_cm(OE) iw_cm(OE) ib_ipoib(OE) ib_cm(OE) ib_uverbs(OE) ib_umad(OE) mlx5_ib(OE) mlx5_core(OE) cxl mlx4_en(OE) mlx4_ib(OE) ib_core(OE) mlx4_core(OE) devlink mlx_compat(OE) i2c_dev ghash_generic xts gf128mul ctr vmx_crypto sg shpchp ibmpowernv ipmi_powernv ipmi_devintf ofpart ipmi_msghandler powernv_flash uio_pdrv_genirq uio opal_prd mtd nfsd auth_rpcgss knem(OE) nfs_acl lockd grace sunrpc ip_tables ext4 jbd2 mbcache sd_mod nvidia_drm(POE) nvidia_modeset(POE) nvidia(POE) ast i2c_algo_bit drm_kms_helper syscopyarea ttm sysfillrect sysimgblt fb_sys_fops ahci drm libahci libata nvme tg3 nvme_core i2c_core ptp pps_core dm_mirror dm_region_hash dm_log dm_mod [last unloaded: mst_pci]
[Tue Aug 29 21:07:32 2017][  152.458296] CPU: 93 PID: 0 Comm: swapper/93 Tainted: P           OE  ------------   4.11.0-16.el7a.ppc64le #1
[Tue Aug 29 21:07:32 2017][  152.458464] task: c00020396cc81600 task.stack: c00020396cc3c000
[Tue Aug 29 21:07:32 2017][  152.458567] NIP: c00800004045d084 LR: c00800004045d058 CTR: c000000000bcb010
[Tue Aug 29 21:07:32 2017][  152.458667] REGS: c000000007cc78d0 TRAP: 0300   Tainted: P           OE  ------------    (4.11.0-16.el7a.ppc64le)
[Tue Aug 29 21:07:32 2017][  152.458835] MSR: 9000000000009033 <SF,HV,EE,ME,IR,DR,RI,LE>
[Tue Aug 29 21:07:32 2017][  152.458846]   CR: 28002022  XER: 20000000
[Tue Aug 29 21:07:32 2017][  152.459001] CFAR: c00800004045d928 DAR: 0000000000000028 DSISR: 40000000 SOFTE: 0 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR00: c00800004045d058 c000000007cc7b50 c008000040993ac8 0000000000000000 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR04: c000003fc1758008 0000000000000008 000000000000002d c008000037710000 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR08: 0000000000000020 0000000000000028 0000000000000000 c00800004051e3e0 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR12: 0000000028002028 c000000007b64500 c00020396cc3ff90 0000000000000000 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR16: 0000000000000000 c000000001375e08 c000003feff037e0 0000000000000001 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR20: 0000000000000000 0000000000000001 0000000000000002 0000000000000238 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR24: c000003f340aa1b8 0000000000000001 c000003f340aa000 c000000007cc7bb0 
[Tue Aug 29 21:07:32 2017][  152.459001] GPR28: c000003f37031808 c000003fc1758008 c000003fc01e1408 00000000000002e8 
[Tue Aug 29 21:07:32 2017][  152.460496] NIP [c00800004045d084] _nv031686rm+0xc4/0x1b0 [nvidia]
[Tue Aug 29 21:07:32 2017][  152.460852] LR [c00800004045d058] _nv031686rm+0x98/0x1b0 [nvidia]
[Tue Aug 29 21:07:32 2017][  152.460952] Call Trace:
[Tue Aug 29 21:07:32 2017][  152.461263] [c000000007cc7b50] [c00800004045d058] _nv031686rm+0x98/0x1b0 [nvidia] (unreliable)
[Tue Aug 29 21:07:32 2017][  152.461647] [c000000007cc7b90] [c0080000404fc28c] rm_gpu_copy_mmu_faults_unlocked+0x13c/0x190 [nvidia]
[Tue Aug 29 21:07:32 2017][  152.462047] [c000000007cc7d60] [c00800003fb70b54] nvidia_isr+0x54/0x1d0 [nvidia]
[Tue Aug 29 21:07:32 2017][  152.462167] [c000000007cc7dc0] [c0000000001b7410] __handle_irq_event_percpu+0xb0/0x340
[Tue Aug 29 21:07:32 2017][  152.462318] [c000000007cc7e90] [c0000000001b77a4] handle_irq_event+0x74/0x110
[Tue Aug 29 21:07:32 2017][  152.462446] [c000000007cc7ed0] [c0000000001bda10] handle_fasteoi_irq+0xf0/0x280
[Tue Aug 29 21:07:32 2017][  152.462574] [c000000007cc7f00] [c0000000001b5cb0] generic_handle_irq+0x50/0x80
[Tue Aug 29 21:07:32 2017][  152.462697] [c000000007cc7f20] [c000000000015ed8] __do_irq+0x98/0x200
[Tue Aug 29 21:07:32 2017][  152.462810] [c000000007cc7f90] [c00000000002ce80] call_do_irq+0x14/0x24
[Tue Aug 29 21:07:32 2017][  152.462924] [c00020396cc3fab0] [c0000000000160e0] do_IRQ+0xa0/0x120
[Tue Aug 29 21:07:32 2017][  152.463012] [c00020396cc3fb00] [c000000000009a74] h_virt_irq_common+0x114/0x120
[Tue Aug 29 21:07:32 2017][  152.463166] --- interrupt: ea1 at arch_local_irq_restore+0x68/0x130
```

**Comment by whowutwut** [comment]
You can either bypass with what I ping'ed you and the function should be working today, to reset via dhcp.  Then depending on when the pull request is merged, it would expose the function without the requirement to export the DEV variable, and if merged tomorrow, would be in the next day's development build.

**Comment by ralphbellofatto** [comment]
Is it safe enough to pick up a development build to use on a production system?
If so what does the yum.repos.d file look for that?

**Comment by whowutwut** [comment]
I think for P9 support, we need to run development builds because we are trying to push function as soon as we can.  https://xcat.org/files/xcat/repos/yum/devel/core-snap/xCAT-core.repo
