### ISSUE TITLE
Command nodeset exit zero when hit error

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3304]
It is xCAT 2.13.4 GA edition. The compute node is x86-64 KVM guest, `netboot` attribute is `xnba`. This test case is intentional checking the exit code when the hostname cannot be resolved. 

    [root@c910f02c03p27 ~]# nodeset testnode1 osimage=rhels6.6-x86_64-install-compute
    testnode1: install rhels6.6-x86_64-compute
    Warning: The hostname testnode1 of node testnode1 could not be resolved.
    [root@c910f02c03p27 ~]# echo $?
    0

A non-zero exit code is expected.

**Comment by robin2008** [comment]
it should be already fixed.
