### ISSUE TITLE
[openbmc] rspconfig - support configuration of the BMC hostname

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3309]
The default is `witherspoon` when the firmware is flashed, need to be able to set some value in `/etc/hostname`  

Externals: 

`rspconfig <node> hostname=newhostname`

**Comment by gurevichmark** [comment]
Code for this function has been already written.
PR #3990 fixes the message - BMC reboot is no longer needed for hostname change.

**Comment by zet809** [comment]
Let's move this issue to 2.13.9 to verify the setting hostname function for newer firmware version.

**Comment by whowutwut** [comment]
This function is done. However a bug was introduced in 1738 driver and I will look for the issue to cross reference to this one

**Comment by whowutwut** [comment]
The support to set hostname in the BMC is complete with xCAT and was working prior to 1738... so any level of BMC > ibm-v1.99.9-0-r4 may exist the behavior where the hostname is effectively `witherspoon` 

At this time the issue still exists in: ibm-v1.99.10-0-113-r8
