### ISSUE TITLE
[openbmc] After firmware update, very first call to BMC results in 503: Service Unavailable

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3310]
I'm opening this issue so that we can track this to see whether the problem is something in the xCAT implementation of something with the firmware.   There is an upcoming code drop for more flash support in the BMC so perhaps things will change once the firmware is flashed via REST... 

After a flash of the openbmc firmware, the very first call from xCAT ,  ` rpower <node> stat` always results in 503: Unavailable.   After this, everything works fine. 

I think we need to do the following...
1) Flash the firmware 
1) How long after the BMC is booted is the REST services avail
2) After REST services are avail, run a few curl commands to check state 
3) Flash the firmware again 
4) Run rpower command to the BMC with XCATBYPASS=1

**Comment by gurevichmark** [comment]
Ran some experiments with `p9euh02` - 10.6.9.254

Some observations:
1. It takes about 1 minute after rebooting BMC before it is pingable
2. It takes about 30 seconds after BMC is pingable before REST service is available
3. The very first login request takes 12 seconds to complete, each subsequent login request takes 0.4 seconds to complete.

**Comment by gurevichmark** [comment]
I think this issue can be closed now. I am not seeing "503: Service Unavailable" error anymore.

**Comment by whowutwut** [comment]
Interesting. I didn't think they were planning on changing anything from the firmware side... ok let's close

**Comment by gurevichmark** [comment]
Reopening. Starting to see this issue again.
It appears that the first time login is attempted by xCAT command "503: Service Unavailable" is returned. Subsequent login attempt is fine. 
This problem does not happen with login attempt when using a `curl` command. It take some time to complete, but eventually succeeds and "503: Service Unavailable" is never returned.

**Comment by zet809** [comment]
Hi, @xuweibj , any idea? Seems the `503: Service Unavailable` is returned by HTTP::Async.

**Comment by whowutwut** [comment]
@zet809  @xuweibj  I don't think we should spent too much time on this. See this discussion: https://github.com/openbmc/openbmc/issues/1924
