### ISSUE TITLE
[FVT] genimage failed in sles

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3313]
``genimage`` failed in sles11.4 and sles12.2 in automation environment. 

xCAT version : ``Version 2.13.5 (git commit b8c402c86a23ce0203bcc8da8712f89ebd4eb305, built Wed Jun 21 06:15:37 EDT 2017)``

Below are some important log from ``sles12.2-ppc64le"

    ....
    ailed to connect to bus: No such file or directory
    Failed to connect to bus: No such file or directory
    Enter the dracut mode. Dracut version: Version     : 044. Dracut directory: dracut.
     sed: can't read /install/netboot/sles12.2/ppc64le/compute/rootimg/etc/inittab: No such file or  directory
     Added scsi_transport_srp.ko as an autodetected dependency
     Added libahci.ko as an autodetected dependency
     Added virtio_ring.ko as an autodetected dependency
     Added virtio.ko as an autodetected dependency
     Added crc16.ko as an autodetected dependency
     Added jbd2.ko as an autodetected dependency
     Added mbcache.ko as an autodetected dependency
      Try to load drivers: scsi_mod libata mbcache jbd2 crc16 virtio virtio_ring libahci scsi_transport_srp af_packet ext3 ext4 virtio_pci virtio_blk scsi_dh ahci megaraid_sas sd_mod ibmvscsi to initrd.

     chroot /install/netboot/sles12.2/ppc64le/compute/rootimg dracut  --compress "/usr/bin/pigz -p 4 " -f /tmp/initrd.8052.gz 4.4.21-69-default
    dracut: Executing: /usr/bin/dracut --compress "/usr/bin/pigz -p 4 " -f /tmp/initrd.8052.gz 4.4.21-69-default
    dracut: Turning off host-only mode: '/sys' is not mounted!
    dracut: Turning off host-only mode: '/proc' is not mounted!
    dracut: Turning off host-only mode: '/run' is not mounted!
    .....

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/issues/3313

**Comment by immarvin** [comment]
verified with autotest
