### ISSUE TITLE
`No object definitions have been created or modified' printed by chdef when change site table

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3316]
With xCAT 2.13.4 GA build. While use `chdef` to change the attribute in the `site` table. It print out `No object definitions have been created or modified.`, but actually `chdef` did change the attributes.

    # chdef -t site master=10.2.3.27 nameservers=10.0.0.103
    No object definitions have been created or modified.
    # echo $?
    0

**Comment by zet809** [comment]
Duplicated with #3289
