### ISSUE TITLE
[openbmc] Support firmware update rflash in hierarchical environment.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3318]
Potentially need to transfer/copy update file to the appropriate service node, before executing REST call.

**Comment by whowutwut** [comment]
Could this be resolved by having a process in place for it? 
* Use a shared filesystem
* Rsync the firmware images to the service nodes before running the --upload?

**Comment by gurevichmark** [comment]
Adding "pending" tag. Issue can be closed. Man page for `rflash` command has been updated to tell the user image file(s) must be accessible from SN in hierarchical environment.

**Comment by zet809** [comment]
The manpage had been updated within the 2.13.6 rc build. So close this task.
