### ISSUE TITLE
[CUSTOMER] bmcdiscover not finding water cooled ITC witherspoon 

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#3320]
Version 2.13.5 (git commit 5416a7546ed2ba551a0f98f02d28fb822bfe6e27, built Fri Jun  2 06:15:51 EDT 20
dhcp leases:
```
Jun 22 18:40:29 c685mgt02 dhcpd: DHCPREQUEST for 9.114.82.96 from 70:e2:84:14:2a:32 (witherspoon) via enp1s0f2
Jun 22 18:40:29 c685mgt02 dhcpd: DHCPACK on 9.114.82.96 to 70:e2:84:14:2a:32 (witherspoon) via enp1s0
```

```
[root@c685mgt02 ~]# bmcdiscover --range 9.114.82.90-97 -s nmap
Warning: Unable to establish IPMI v2 / RMCP+ session: unauthorized name for 9.114.82.93
```

ssh to 9.114.82.96, it is the witherspoon BMC.

**Comment by whowutwut** [comment]
@markprez  Yes, I also came across this. IF you update to today's build, it should have a Warning message, but that still doesn't resolve the problem.  I just created a pull request that will let us get by the bmcdiscover, but the VPD information is not programmed into the ITC machines which is also a problem. 

If you have a cronus setup, maybe we can use that to program on the MTM and Serial into the machines..

**Comment by whowutwut** [comment]
@markprez  This should work now.  Also tagging @david-shapiro FYI.  

Until we figure out what VPD information is going to be burned into the machine, we created this `export XCAT_DEV_WITHERSPOON=TRUE` variable into the code that will remove the MTM value and cause the discovered node definition to be a unique string.  This is to bypass the 000000000 that is being returned today.  More info here:  https://github.com/xcat2/xcat-core/pull/3321#issuecomment-310556588

Will close, please re-open if any more issues arise.
