### ISSUE TITLE
Create a xcat-dep public repo for development builds, similar to xcat-core

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3322]
Without a development build of xcat-dep, we always have risk of breaking existing customer who are using the public repos:  Examples
* https://sourceforge.net/p/xcat/mailman/xcat-user/thread/3DCC7A4E-F88D-4BA2-8387-588E3799894D%40brown.edu/#msg35907923
* https://github.com/xcat2/xcat-dep/issues/18

This work will involve many pieces of xCAT..  
 * first should define a manual process before the automated methods are in place 
 * build scripts for Linux and Ubuntu
 * xcat.org location to upload
 * promote script used to promote development builds would also need to modify the repos for xcat-dep

**Comment by neo954** [comment]
The following two directories have been created manually. But we still need to update our build script and promote script.

http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/
http://xcat.org/files/xcat/repos/apt/devel/xcat-dep/

**Comment by zet809** [comment]
So, we still don't have the script to update dev repo automatically, right?

**Comment by robin2008** [comment]
@neo954 Do we have already updated our prompt/build script?

**Comment by gurevichmark** [comment]
@whowutwut I think we can close this issue.
We already have `devel` directory for `xcat-dep` and `promote_build.py` appears to have a `devel` option.

**Comment by whowutwut** [comment]
This one is partially complete as we do have a space for the dev vesion of xcat-deps in the  public yum repo:  http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/ 

What is missing is that under each `os/arch` we have xcat-dep.repo file, those are not pointing to  the  correct path, so if a user does  a `wget` of that file,  and `yum install xCAT` they would pick  up the GA version. 

What I think should happen here is in our GSA deps holding area, we  should hard  code the dev version and the  builddeps scripts  will push a new version to the devel  area, then have a   promote_script like we do for xcat-core that would copy it to the  GA version and  sed/replace  the repo file

**Comment by gurevichmark** [comment]
Fixed by #6444
