### ISSUE TITLE
2.13.5 release process

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3325]
what to do:

*  End of cycle regression process: https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/End%20of%20cycle%20regression%20process
*  merge master branch to 2.13 branch
*  refine release notes: https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.5_Release_Notes
 * go through release process for 2.13.5: xcat2/xcat.org#63

Finish this job in 2.13.6 sprint1 first week.

**Comment by samveen** [comment]
@hu-weihua @tingtli @whowutwut Just to clarify, The `2.13.5` release will be unreachable from `HEAD` on `master` branch(for the purposes of `git describe`), right? (Tail end of the discission on #2886 )

**Comment by tingtli** [comment]
@samveen  Yes.  2.13.5 will be released this Friday. It will be unreachable from HEAD on master branch. You can see the 2.13.5 tag on 2.13 branch.

**Comment by whowutwut** [comment]
Sorry,  I haven't had a chance to look into this.  @samveen  I had given this some thought but I wanted to run some tests in my own repo first before we do it in xCAT. 

If we tag the release in the master branch before we merge `master` -> `<release branch>. I think the tag will persist.  Really we want the tags on the master so `git describe` works.  What I'm not sure is the process if we create multiple release candidate builds, we want to tag it before each merge and reuse the tag name. 

I think this should be possible, but again, I haven't tried it out to make sure it does satisfy this requirements.
