### ISSUE TITLE
[CORAL] Refine end to end steps for Alpha

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3329]
1. The steps is based on https://github.ibm.com/vhu/c910env/tree/master/notes/coral/end2end
2. Some of the steps in the doc above are work around and have not detailed configuration step, need to break down them to be executable commands and steps.
3. For non-supported/not well supported commands or features, implement or enhance them. Based on step2.

- [ ] Transient hostname short and long issue: https://github.ibm.com/vhu/c910env/issues/76

**Comment by whowutwut** [comment]
@zet809  I think you assigned a wrong issue as a blocking in ZenHub, can you double check.  I removed it for now.

**Comment by zet809** [comment]
Hi, @whowutwut , you are right, it shall be #3218

**Comment by robin2008** [comment]
Update xCAT MN section based on 2.13.5

**Comment by whowutwut** [comment]
Does any one on the team have any idea for the transient hostname issue: https://github.ibm.com/DCS-research/R92-cluster/issues/1246 ?
