### ISSUE TITLE
[fvt]x86_64 physical machine could not powering on 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#3335]
env:
1. x86_64 physical machine:
c910f04x18
[root@c910f04x30v02 ~]# lsdef c910f04x18
Object name: c910f04x18
    arch=x86_64
    bmc=10.4.18.254
    cons=ipmi
    currchain=boot
    currstate=install rhels7.3-x86_64-compute
    groups=ipmi
    installnic=mac
    ip=10.4.18.1
    mac=40:F2:E9:0A:4E:C4
    mgt=ipmi
    monserver=c910f04x30v02
    netboot=xnba
    nfsserver=c910f04x30v02
    os=rhels7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,setupntp
    primarynic=mac
    profile=compute
    provmethod=rhels7.3-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=06-26-2017 07:39:21
    tftpserver=c910f04x30v02
    xcatmaster=c910f04x30v02
2.[root@c910f04x30v02 ~]# rpower c910f04x18 stat
c910f04x18: off
[root@c910f04x30v02 ~]# rpower c910f04x18 on
c910f04x18: on
[root@c910f04x30v02 ~]# rpower c910f04x18 stat
c910f04x18: off
--------------------> could not powering on and gongjie help to update the firmware but failed

**Comment by whowutwut** [comment]
Opened Sev3 defect to the lab: SW394099

**Comment by whowutwut** [comment]
For future, please open lab hardware related issues to our c910env repo to track internally.
