### ISSUE TITLE
bmcdiscover, performance issues on first call to OpenBMC REST service? 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3336]
I'm pretty sure this is related to #3310, because I updated the firmware to 1724A, and I'm not sure if this was the first executed REST call.  

Instead of having a 503 response, we did get a response, but it took a long time to respond against a single IP address.  

Creating these issues to go back and validate these scenario if we do find the underlying reason: 

First attempt to run `bmcdiscover` results in 13 seconds to respond, the 2nd attempt is under 1 second. 

```
====================================================
[Date]       2017-06-26 11:46:16
[ClientType] cli
[Request]    bmcdiscover --range 172.20.253.103
[Response]
XCAT_DEV_WITHERSPOON=TRUE, forcing MTM to empty string for 172.20.253.103 (Original MTM=)
172.20.253.103,,000000000000,,,mp,bmc
[ElapsedTime] 13 s
====================================================
[Date]       2017-06-26 11:46:34
[ClientType] cli
[Request]    bmcdiscover --range 172.20.253.103 -z
[Response]
XCAT_DEV_WITHERSPOON=TRUE, forcing MTM to empty string for 172.20.253.103 (Original MTM=)
node-ac14fd67:
        objtype=node
        groups=all
        bmc=172.20.253.103
        cons=openbmc
        mgt=openbmc
        serial=000000000000

[ElapsedTime] 1 s
```

**Comment by whowutwut** [comment]
FYI @zet809 @xuweibj @gurevichmark

**Comment by xuweibj** [comment]
Hi @whowutwut , Is this issue still existed? Which MN and CN could I use to debug?

**Comment by whowutwut** [comment]
@xuweibj Sorry, I forgot to cross link with issues that I opened up on the openbmc team after I re-created it outside of xCAT code... . https://github.com/openbmc/openbmc/issues/1881 .  

It's a firmware design issue and there's nothing that xCAT code can do to change this... so let's close it.

**Comment by whowutwut** [comment]
So summary, there's no fix going in for xCAT, and this is dependent on any changes in openbmc to resolve this issue.
