### ISSUE TITLE
[FVT] Offer a document : How to Add New project into Jenkins

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3342]
What to do:

* [ ]  finish document ``How to Add New project into Jenkins`` under https://github.ibm.com/xcat2/team_process/tree/master/FVT.  Format : MD

**Comment by daniceexi** [comment]
@hu-weihua One of my question is what's rule to put a doc in github.com or github.ibm.com?

**Comment by whowutwut** [comment]
@daniceexi  This is an internal process of xCAT tools, so it should be github.ibm.com, which is the URL that @hu-weihua  used....

However, I don't know why we are opening issues in the public GitHub to track this, we can open issues for this in the internal repos..   Unless we are trying to trace all work on the external site.. which i'm not sure I agree with.

**Comment by daniceexi** [comment]
@whowutwut I am OK with our current way to store our docs. As I mentioned before that I'd like we could put all the docs in public github if there's no specific confidential content to easy the management.
