### ISSUE TITLE
[FVT] add test cases for issue 3047 : Regular Expression broken it lastest development build

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3344]
What to do:
* [ ] offer a test cases scope
* [ ] add test cases for issue #3047

**Comment by neo954** [comment]
One test case will be added for typical scenario.

The test case will be named mkdef_regex_nicsip. It will verify if regular expression is support in the nicips attribute in node definitions. As the problem reported in issue #3047.
