### ISSUE TITLE
[FVT] add test case for issue 2948: rpower commands run against OpenPower BMC should be blocked if not supported

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3345]
What to do:
* [x] offer a test cases scope
* [x] add test cases for issue #2948

**Comment by junxiawang** [comment]
Need to add testcase:
rpower_softoff_OpenpowerBmc
rpower_wake_OpenpowerBmc
rpower_suspend_OpenpowerBmc
rpower_errorcommand_OpenpowerBmc
