### ISSUE TITLE
[CORAL]Verify installation of Pegas EA2 with Kernel Patch 4.11.0-8 on P9 WSP

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3348]
Trace the task:https://github.ibm.com/vhu/c910env/issues/64

**Comment by bybai** [comment]
I verified diskless with new kernel patch on p9euh01, I got successful, I updated steps in https://github.ibm.com/vhu/c910env/issues/64. 
I will start to diskful installation next day.
