### ISSUE TITLE
[CORAL]CumulusLinux is NOT configured correctly with regards to VLAN

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3349]
Trace the task: https://github.ibm.com/vhu/c910env/issues/74

**Comment by cxhong** [comment]
port7 tagged to 553 vlan only.  in the file /etc/network/interfaces.d/xCAT.intf
```
auto swp7
iface swp7
  mstpctl-portadminedge yes
  bridge-access 553
```
Need to remove "bridge-access 553" to accept both vlan 1 and vlan 553.

The compute node is up and running again.

**Comment by whowutwut** [comment]
Thanks @cxhong  I didn't look at the switch port for the config, just the overall config.
