### ISSUE TITLE
chdef of mgmt type from ipmi to openbmc does not move required information 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3358]
I have a node incorrectly defined with `mgt=ipmi` , the bmc value is set in the ipmi table...

```
[root@fs3 xcat]# tabdump ipmi
#node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable
"coral_sn_regex","|\D+(\d+)|172.21.254.(($1%100)+100)|",,,,,,,
"cn_regex","|\D+(\d+)\D+(\d+)\D+(\d+)|172.21.(($1-1)*32+$2).($3%100)|",,"553",,,,,
"mid05tor12cn02","172.20.140.102",,,,,,,
```

When I change this mgt=openbmc, the entry does not move to the correct table...

```
[root@fs3 xcat]# chdef mid05tor12cn02 mgt=openbmc
1 object definitions have been created or modified.
t[root@fs3 xcat]# tabdump openbmc
#node,bmc,consport,taggedvlan,username,password,comments,disable
"node-ac14fd67","172.20.253.103",,,,,,
"node-ac14fd66","172.20.253.102",,,,,,
```

But if I change it together, it does...
```
[root@fs3 xcat]# chdef mid05tor12cn02 bmc=172.20.140.102 chain=runcmd=bmcsetup,standby mgt=openbmc
1 object definitions have been created or modified.
[root@fs3 xcat]# tabdump openbmc
#node,bmc,consport,taggedvlan,username,password,comments,disable
"node-ac14fd67","172.20.253.103",,,,,,
"node-ac14fd66","172.20.253.102",,,,,,
"mid05tor12cn02","172.20.140.102",,,,,,
```

**Comment by immarvin** [comment]
hi @xuweibj ,would you please take a look at this? thanks

**Comment by zet809** [comment]
Hi, @whowutwut , when specify bmc and mgt together, each parameter shall be judged about which table it shall be set. For example, for bmc, the *def code will check the mgt of the node and determine which table shall this attribute be set.
But, if no bmc attribute specified, only the mgt attribute be set in nodehm, then nothing more will be done for *def command.
If we have *def command read out all attributes first and then re-determine where those attributes shall be set, the performance will be unacceptable and logic will be much complex.

**Comment by whowutwut** [comment]
OK,  I think this issue is a result of a mixed environment where we have some compute nodes mgt by IPMI and some mgt by OPENBMC, but the regex groups that it's part of does not differentiate between the two.  IF that was configured, we should not run into this problem.   

A group for p8 with `mgt=ipmi,cons=ipmi` and a group for p9 with `mgt=openbmc,cons=openbmc` would have resolved it.  

Will update our docs procedures internally and expose them later.
