### ISSUE TITLE
nvidia-smi report Error modprobe: FATAL: Module nvidia not found.

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#336]
1) Today I updated xCAT to esp version. 
[root@c712ems2 postscripts]# lsxcatd -v
Version 2.11 (git commit 5c2ff6120bd8c83545fbb8c75d72b7ee06d4a95f, built Wed Oct 28 13:33:17 EDT 2015)

2) then I create a diskless image cuda_diskless_1544a_esp, and install cuda esp version following below new xCAT docs. 
http://xcat-docs.readthedocs.org/en/latest/advanced/gpu/cuda.html
I saw this part：　
For the diskless installation, the CUDA package can be included either in otherpkglist or pktlist fields.
ｓｏ　Ｉ　ｐｕｔ　ｃｕｄａ　ｉｎｔｏ　ｐｋｇｌｉｓｔ．　

and ofed esp ,  compiler, essl, pessl,ppe 1544a also put into it. 
but nvidia-smi failed. 

[root@c712f3n05 ~]# nvidia-smi
modprobe: FATAL: Module nvidia not found.
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

[root@c712f3n05 ~]# uname -a
Linux c712f3n05.pok.stglabs.ibm.com 3.10.0-316.el7.ppc64le #1 SMP Tue Sep 15 10:16:14 EDT 2015 ppc64le ppc64le ppc64le GNU/Linux
[root@c712f3n05 ~]# rpm -qa |grep cuda
cuda-command-line-tools-7-5-7.5-18.ppc64le
cuda-curand-7-5-7.5-18.ppc64le
cuda-cusparse-dev-7-5-7.5-18.ppc64le
cuda-runtime-7-5-7.5-18.ppc64le
cuda-cudart-dev-7-5-7.5-18.ppc64le
cuda-7.5-18.ppc64le
cuda-cufft-dev-7-5-7.5-18.ppc64le
cuda-documentation-7-5-7.5-18.ppc64le
cuda-core-7-5-7.5-18.ppc64le
cuda-cusparse-7-5-7.5-18.ppc64le
cuda-cusolver-7-5-7.5-18.ppc64le
cuda-npp-dev-7-5-7.5-18.ppc64le
cuda-driver-dev-7-5-7.5-18.ppc64le
cuda-samples-7-5-7.5-18.ppc64le
cuda-cudart-7-5-7.5-18.ppc64le
cuda-visual-tools-7-5-7.5-18.ppc64le
cuda-drivers-352.59-0.ppc64le
cuda-cufft-7-5-7.5-18.ppc64le
cuda-misc-headers-7-5-7.5-18.ppc64le
cuda-curand-dev-7-5-7.5-18.ppc64le
cuda-7-5-7.5-18.ppc64le
cuda-cublas-dev-7-5-7.5-18.ppc64le
cuda-npp-7-5-7.5-18.ppc64le
cuda-nvrtc-dev-7-5-7.5-18.ppc64le
cuda-toolkit-7-5-7.5-18.ppc64le
essl.3264.rtecuda-5.4.0-0.ppc64le
cuda-cublas-7-5-7.5-18.ppc64le
cuda-license-7-5-7.5-18.ppc64le
cuda-cusolver-dev-7-5-7.5-18.ppc64le
cuda-nvrtc-7-5-7.5-18.ppc64le
[root@c712f3n05 ~]# rpm -qa |grep dkms
dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch
[root@c712f3n05 ~]# rpm -qa |grep ofed
mlnxofed-docs-3.1-1.0.3.1.noarch
ofed-scripts-3.1-OFED.3.1.1.0.3.ppc64le

some commands I use: 
lsdef -t osimage -z xcat_diskless_1541a_test >zz
 vi zz; change the image name , dir for rootimage, otherpkgdir
rpm -e `rpm -qa |grep cuda`
rpm -ivh cuda-repo-rhel7-7-5-local-7.5-18.ppc64le.rpm
cp /var/cuda-repo-7-5-local/* /install/cuda-esp/cudaesp/
cd /install/cuda-esp/cudaesp/
createrepo .
put dkms rpm in /install/cuda-esp/cuda-deps
createrepo .
cd /install/cuda-esp
createrepo .
chdef -t osimage cuda_diskless_1544a_esp pkgdir=/install/rhels7.2snapshot2/ppc64le,/install/cuda-esp

ib
/install/custom/netboot/rh/compute.rhels7.ppc64le.postinstall
cp compute.rhels7.ppc64le.postinstall cuda_diskless_1544a_esp.postinstall
vi cuda_diskless_1544a_esp.postinstall , use the mofed ESP version
chdef -t  osimage cuda_diskless_1544a_esp postinstall=/install/custom/netboot/rh/cuda_diskless_1544a_esp.postinstall

chroot into rootimage
chkconfig rpcbind on
chkconfig autofs on
genimage 
packimage
nodeset c712f3n05 osimage=
rsetboot c712f3n05  net 
rpower c712f3n05  boot

**Comment by whowutwut** [comment]
Hi @wwzhubj , just a comment, you can wrap the command line text between 3 ` (back tick) to comply with the **GitHub markdown** so that it's easier to read the post.  The link right in the comment box explains more. 

Sorry about this, I think you picked up the document too quickly.  We had put in a fix to address diskless image which results in a change in the way create the diskless image:  

http://xcat-docs.readthedocs.org/en/latest/advanced/gpu/nvidia/osimage/rhels.html#diskless-images

**[diskless note]**: For diskless images, the requirement for rebooting the machine is not applicable because the images is loaded on each reboot. The install of the CUDA packages is required to be done in the ``otherpkglist`` **NOT** the ``pkglist``.

**Comment by whowutwut** [comment]
Can you try again with the new documented steps?
