### ISSUE TITLE
Create Documentation for ZTP based ONIE switch setup

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3361]
Acceptance criteria:
1. The documentation covers the steps to ZTP based ONIE switch discovery and configuration
2. The documentation be merged to master

**Comment by immarvin** [comment]
PR https://github.com/xcat2/xcat-core/pull/3362

**Comment by whowutwut** [comment]
@immarvin  Isn't this complete with #3362?  Why is it target for 2.13.6 release?

**Comment by immarvin** [comment]
hi @whowutwut , it is complete. This task is done in 2.13.6 sprint1 though the PR is targeted for 2.13.5 release, so the milestone is 2.13.6 here.
