### ISSUE TITLE
Error in deploy sysclone image 

### ISSUE THREAD

**Issue by amrabdelaziem** [xcat2/xcat-core#3366]
[root@mnode ~]# imgcapture compute03 -t sysclone -o centos7clone1Checking if systemimager packages are installed on mnode.
Checking if systemimager packages are installed on compute03.
Preparing osimage centos7clone1 on compute03.
Getting osimage "centos7clone1" from compute03 to mnode.
Using the existing osimage "centos7clone1" defined on mnode.

[root@mnode ~]# chdef -t osimage -o centos7clone1\ otherpkglist=/opt/xcat/share/xcat/install/rh/sysclone.rhels7.x86_64.otherpkgs.pkglist

[root@mnode ~]# chdef -t osimage -o centos7clone1\ otherpkgdir=/install/post/otherpkgs/centos7.3/x86_64/xcat/

[root@mnode ~]# lsdef -t osimage centos7clone1
Object name: centos7clone1
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.3-x86_64
    osname=Linux
    osvers=centos7.3
    otherpkgdir=/install/post/otherpkgs/centos7.3/x86_64/
    otherpkglist=/opt/xcat/share/xcat/install/rh/sysclone.rhels7.x86_64.otherpkgs.pkglist
    pkgdir=/install/centos7.3/x86_64
    profile=compute
    provmethod=sysclone
    rootimgdir=/install/sysclone/images/centos7clone1

those were steps I did for taking sysclone image to deploy it as a diskfull image on new node 
but when I deploy it by nodeset the installation didn't complete and stuck on the following screen 
![dsc_0012](https://user-images.githubusercontent.com/25757140/27637879-91edd0fe-5c11-11e7-8a99-901fc0b5b836.JPG)
Please help.

**Comment by zet809** [comment]
Hi, @hu-weihua , will you pls take a look at this issue? Thx!

**Comment by amrabdelaziem** [comment]
I can't solve the problem yet also with new release 2.13.5.
if anyone can help!

**Comment by zet809** [comment]
Remove the milestone and add when we plan to fix.

**Comment by ChrisPJames** [comment]
For reference - encountered exactly the same issue today. using xCAT 2.13.8. cloned a c6.2 client and tried to restore back onto the same machine.

**Comment by immarvin** [comment]
we have no plan to support sysclone anymore, close the ticket
