### ISSUE TITLE
[FVT]2.9.2: rinv CN model -t returns hmc plugin bug

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#338]
bash-3.2# rpm -qa |grep -i xcat
openslp-xcat-1.2.1-1
perl-xCAT-2.9.2-snap201510270404
xCAT-client-2.9.2-snap201510270404
xCAT-server-2.9.2-snap201510270405
xCAT-2.9.2-snap201510270407

bash-3.2# rinv c910f03c01p17 model -t
Error: hmc plugin bug, pid 15335518, process description: 'xCATd SSL: rinv to c9ecial manipulation of  or strange circumstances in an XS library, remove evals il request for the following nodes: c910f03c01p17
bash-3.2# echo $?
1

**Comment by zet809** [comment]
Have apply pull request for both 2.9 and master branch.

**Comment by whowutwut** [comment]
Pull request #340 fixed this issue

**Comment by tingtli** [comment]
Verified and close
