### ISSUE TITLE
Play out the end to end scenario and use case for the getadapter command

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3382]
Creating this issue to close out #3046,  As @gurevichmark pointed out in https://github.com/xcat2/xcat-core/issues/3046#issuecomment-310179977, `getadapter` call is quite destructive on the target node. 
* If diskful, it will reboot the node into genesis kernel, losing access to node
* If diskless, it will reboot the node into genesis kernel, losing all transient data on the node. 

I think the node still stays in the genesis kernel after complete, correct? 

## Suggestions: 
1) Update the documentation/man page to indicate that the target node will be booted into genesis  (if this is not clear)
2) After getadapter is complete, should we reboot the node back to what it was running before? 
   *  If the user is using getadapter to discover the node initially, there's nothing to boot back into, how do we handle this? 
   * why would we want to leave it in genesis? 
3) Whats' the end 2 end use case here,  a bunch of adapters is generated 
```
[root@fs3 dhcpd]# lsdef sn02 -i nicsadapter
Object name: sn02
    nicsadapter.enP1p1s0f4= mac=5c:f3:fc:32:b4:90pci=/pci0001:00/0001:00:00.0/0001:01:00.4 linkstate=DOWN
    nicsadapter.enP1p1s0f4d1= mac=5c:f3:fc:32:b4:98pci=/pci0001:00/0001:00:00.0/0001:01:00.4 linkstate=DOWN
    nicsadapter.enP1p1s0f4d2= mac=5c:f3:fc:32:b4:a0pci=/pci0001:00/0001:00:00.0/0001:01:00.4 linkstate=DOWN
    nicsadapter.enP1p1s0f4d3= mac=5c:f3:fc:32:b4:a8pci=/pci0001:00/0001:00:00.0/0001:01:00.4 linkstate=DOWN
    nicsadapter.enP5p7s0f0= mac=70:e2:84:14:0a:71pci=/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:04.0/0005:07:00.0 linkstate=UP
    nicsadapter.enP5p7s0f1= mac=70:e2:84:14:0a:72pci=/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:04.0/0005:07:00.1 linkstate=DOWN
[root@fs3 dhcpd]#
```
How does the user even use this info...  For example enP5p7s0f0 is link UP, so it has a connection to a switch... what additional steps are needed to add to xCAT (ip address, netmask, vlan) to allow xCAT to configure this adapter..  (postscripts need to be added?)  Essentially what I'm looking for is documentation to complete the end to end picture of `getadapters` to help users leverage this tool.

**Comment by gurevichmark** [comment]
I think #1 from above is already done.
Currently the man page shows:

![image](https://user-images.githubusercontent.com/16106630/27739675-77762ad8-5d7d-11e7-85b1-d07f7e353eb5.png)

**Comment by chenglch** [comment]
Actually, `getadapter` is a feature that has not been completed. Our original plan is to make it work with `configure network` which is a work item we are refactoring currently. 

Now, I do not think the original design is a correct,  from my experience of `ansible`,  it can retrieve the adapter information via ssh, maybe we could think about how to implement `getadapter` in this way if newer `configure network` can really work correctly in a complex environment.

**Comment by gurevichmark** [comment]
@chenglch I thought the main use of get `adapter` is to use it before provisioning a node with OS, so that adapter information can be entered into the node definition. That is why I thought we had to boot into genesis.

**Comment by whowutwut** [comment]
agree with @gurevichmark   I thought the initial plan was to figure out the predictable naming of the adapter based on the physical pci location...  Maybe we need to revisit this command altogether and come up with a use case and work to complete the use case.

**Comment by chenglch** [comment]
I think we should divided the usage scenario into two category considering the the usage of`configure network`.

1. Before provision: the script of `getadapter` could be put into the command list of genesis discovery, so that the machine could run `getadapter` during the discovery stage. In this case, `configure network` can work based on the nics information detected by the `getadapter` before provision.

2. `configure network` can also work as a part of `updatenode`. In this case `ssh` is available, we can detect the nics info especially the link state whenever we want.

So my opinion is that If the node definition is ready to provision a system (this is how `getadapter` work currently), it cost too much to boot into genesis again.

**Comment by daniceexi** [comment]
@chenglch 's proposal looks good.

**Comment by zet809** [comment]
The issue #1174 will be covered by this task.

**Comment by whowutwut** [comment]
@chenglch @daniceexi @zet809 

I am not quite understanding the flow @chenglch proposed above.  Let's discuss this tonight.

**Comment by chenglch** [comment]
I divided the `getadapter` work into two parts.

#### As a part of discovery
To make `getadapter` work during discovery stage, `getadapter` can be set in the chain table and it can be looked as a script running after `findme`. When the `findme` is done, the predefine node has already built the `mac-node` relationship in the `mac` table. As `getadapter` script will inspect all the information including mac about the nics, when the `nics` message is sending back via `TCP`, xcatd can fork a process with `getadapter` plugin and address the node from the message with `macs` information. Then `getadapter` plugin can update the `nicsadapter` attibute in `nics` table for the node been found.

In this design, `getadapter` is designed as a pluginable function for discovery and do not affect current `findme` process.

 #### Running as command using xdsh(ssh)

If the machine has already been deployed, `getadapter` could act as a command to execute a script to inspect the adapter information via ssh. `getadapter` command will accept a parameter( default 5) which indicate the concurrent processes to run the ssh command. `getadapter` should maintain a task queue and wait for the result of ssh command for the node in the noderange. Then update the nics attibutes based on the message returned from ssh.

## Work Item
For the milestone 2.13.6, I will focus on the first part to make it work within discovery stage. 

For the part 2, I will not start it very soon until we really have this requirement. I'm not sure if `xdsh` can help control the task number running concurrently， maybe xcat should provide a framework like `ansible`(or just use ansible directly) to control the procedure to dispatch the task to the remote nodes.
