### ISSUE TITLE
Install Error: Deploying 'go-xcat' on Ubuntu Xenial amd64 LXD Container

### ISSUE THREAD

**Issue by ladams00** [xcat2/xcat-core#3384]
Greetings,

I've attempted to install xCAT via latest 'go-xcat' script into an Ubuntu Xenial amd64 LXD container.  I've yet to test the install on ppc64el with LXD.  Based on the '/tmp/go-xcat.log' output, I suspect it may have something to do with the security containment of devices that xcat-genesis-base-ppc64 deb package is trying to create.

```
dpkg: error processing archive /var/cache/apt/archives/xcat-genesis-base-ppc64_2.13.2-snap201702150049_all.deb (--unpack):
 error creating device './opt/xcat/share/xcat/netboot/genesis/ppc64/fs/dev/console': Operation not permitted
```

I will attempt to try again, but this time with a privileged LXD container and will report back those results. 

Relevant Bits:
- Host OS (bare metal): Ubuntu 16.04.2 LTS Xenial amd64
- LXD installed from snaps, edge release channel:  Version git-d36b797, Rev 2658, Developer canonical
-- 'lxd --version'
-- 2.15
- Container OS: Ubuntu 16.04.2 LTS Xenial amd64
-- 'lxc launch ubuntu: xcat-mn1'
-- 'lxc exec xcat-mn1 -- /bin/bash'
- Following instructions from http://xcat-docs.readthedocs.io/en/latest/guides/install-guides/apt/automatic_install.html
`wget https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT-server/share/xcat/tools/go-xcat -O - >/tmp/go-xcat && chmod +x /tmp/go-xcat && /tmp/go-xcat install`

Abbreviated console output:
```
Errors were encountered while processing:
 /var/cache/apt/archives/xcat-genesis-base-ppc64_2.13.2-snap201702150049_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


Boo-boo
=======

Something went wrong. :(

Please check log file `/tmp/go-xcat.log' for more details.
root@xcat-mn1:~#  
```

Contents of '/tmp/go-xcat.log':
-- Too long to post, attaching separately:  
[go-xcat.log.txt](https://github.com/xcat2/xcat-core/files/1117515/go-xcat.log.txt)

**Comment by ladams00** [comment]
I've found some resolution :-) So modifying the container to run in privileged mode certainly takes care of the issue with device creation I have reported above.  Upon trying to deploy again, I encountered an NFS issue that was easily remedied thanks to Tycho Anderson and Shilpa Kaul's discussion thread here: https://lists.ubuntu.com/archives/juju/2016-June/007471.html

In it's entirety, here's what I needed to successfully deploy xCAT using the 'go-xcat' script under an LXD container on Ubuntu:

```
lxc init ubuntu: xcat-mn1
lxc config set xcat-mn1 security.privileged true
lxc config set xcat-mn1 raw.apparmor "mount fstype=nfs, mount fstype=nfs4, mount fstype=nfsd, mount fstype=rpc_pipefs,"
lxc start xcat-mn1
lxc exec xcat-mn1 -- /bin/bash
```
and subsequently:
`wget https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT-server/share/xcat/tools/go-xcat -O - >/tmp/go-xcat && chmod +x /tmp/go-xcat && /tmp/go-xcat install`

Instead of opting to close my own issue, I'll leave it open for those with authority to determine what to do with the report.

**Comment by immarvin** [comment]
interesting work. thanks for your info @ladams00 , xCAT team also did some work to run xCAT in Docker container. 

The Doc can be found in http://xcat-docs.readthedocs.io/en/stable/advanced/docker/dockerized_xcat/dockerized_xcat.html

The helper and hacking scripts for "dockerized" xCAT can be found in https://github.com/immarvin/xcat-docker, hope this can help you to do the similar thing in LXC

**Comment by whowutwut** [comment]
@immarvin Is there anything that we need to change in our documentation from this issue? It looks like it was moved to the icebox in zenhub, if that's the case, we should just close the issue and mark it as "won't fix"

**Comment by immarvin** [comment]
hi @whowutwut , I think we do not need to make any change.  We do not have any plan or customer requirement on running xcat inside LXD(another type of LXC based container technology like Docker). 

Anyway, it is an interesting work,  if @ladams00 would like to keep on updating on the steps and solutions on this thread during his investigation, maybe we can keep this ticket open but do not put it into our sprint plan. what do you think? @whowutwut 

hi @ladams00 , if you would like to share the steps and solutions on your work, it is ok to contribute a Doc on this and we can consider to take it as an experimental feature for xCAT. thanks

**Comment by immarvin** [comment]
no update for 1 week, close this ticket now; please reopen it if any update
