### ISSUE TITLE
[FVT]2.9.2:rcons CN -f could not open console in read-write mode

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#339]
xCAT 2.9.2
bash-3.2# rpm -qa |grep -i xcat
openslp-xcat-1.2.1-1
perl-xCAT-2.9.2-snap201510270404
xCAT-client-2.9.2-snap201510270404
xCAT-server-2.9.2-snap201510270405
xCAT-2.9.2-snap201510270407

If there is another console open,  use "rcons c910f03c01p17 -f" to enter the console, enter "root" and get the following error message.

bash-3.2# rcons c910f03c01p17 -f

AIX Version 7
Copyright IBM Corporation, 1982, 2015.
Console login: root
/dev/vty0: You must "exec" login from the lowest login shell.

INIT: failed write of utmp entry: "          cons"

                                                  INIT: failed write of utmp entry: "          cons"

**Comment by zet809** [comment]
The disk is 100% used on your compute node, after clear something. The console works ok.
