### ISSUE TITLE
[support] `mysql`/`mariadb` package requirement

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3392]
As part of the hierarchical cluster installation, the section for installation on redhat suggests the following packages:

```
mariadb-devel-5.*
mariadb-libs-5.*
mariadb-server-5.*
mariadb-bench-5.*
mariadb-5.*
perl-DBD-MySQL*
mysql-connector-odbc-*
unixODBC*
```
The other OS sections don't mention `mariadb-bench*` or `mariadb-devel*` or similar packages (`-dev` or similar either). Can I get more details about why these 2 package are part of the requirements?

The same question applies to `mysql-bench*` and `mysql-devel*` package.

As far as I can make out the requirements can be reduced to `mariadb-5.* mysql-server-5.* perl-DBD-MySQL-* mysql-connector-odbc-* `.  The other required packages would automatically install for dependencies. similar situation for `mysql-*`.

**Comment by whowutwut** [comment]
@cxhong, it looks like I did those changes to the requirements list, but I'm not sure where it came from. Did we have some issues when we tried the install?    I don't think xCAT specifically requires this `-bench` package.

**Comment by samveen** [comment]
The `mariadb-devel-5.*` and the `unixODBC-devel` (from `unixODBC*`) packages aren't needed either, from what I can make out.

**Comment by whowutwut** [comment]
@cxhong If verified, we can close out for @samveen ..

**Comment by samveen** [comment]
@whowutwut I forgot to add that this works.
