### ISSUE TITLE
rinv reports plugin bug with communicating with openbmc

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3405]
I am not able to re-create this and I'm not sure what the cause is.  But if this helps to point to some piece in our code that we should be handling a little better, it might be good to check. 

```
[root@fs3 ~]# rinv mid05tor12cn11
Error: openbmc plugin bug, pid 112565, process description: 'xcatd SSL: rinv to mid05tor12cn11 for root@localhost: openbmc instance' with error 'malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Timed out") at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 937.
' while trying to fulfill request for the following nodes: mid05tor12cn11
```

**Comment by zet809** [comment]
Hi, @xuweibj , why not set pending label for this defect after it is fixed?

**Comment by xuweibj** [comment]
The issue was fixed in pull request #3431

**Comment by whowutwut** [comment]
Thanks, I  will verify.

**Comment by zet809** [comment]
Hi, @whowutwut , have this issue been verified? Can we close this issue? Thx!

**Comment by whowutwut** [comment]
I verified with 
```
[root@fs2vm110 frame6u05]# lsxcatd -v
 Version 2.13.7 (git commit c548d0bd77e294b5de610bae33880757b15060b3, built Tue Aug 15 06:15:45 EDT 2017)
[root@fs2vm110 frame6u05]#
```
I don't see this issue anymore, but saw another one, notified @xuweibj  in #3506 

But this one is ok...
