### ISSUE TITLE
Clean up the discovered node definition work around for P9 discovery

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3406]
Is it possible to modify the node discovery to look for the `node-<IP -> HEX>` discovered node definitions as part of hardware discovery?  

The issue here is that I'm not 100% confident that we will be able to rely on the model type serial number of these OpenBMC boxes because the VPD information is not avail until you boot the compute side. Then only the serial number appears.   The Model number is not yet burned in... 

So while we have this work around, if we can't find a node definition for `node-mt-sn` could we then look for the `node-<ip>` and delete it if it's found? 

The task include: 
* For bmcdiscover: 
- [x] Use MTM/Serial, if there
- [x] Fall back to MAC address (REST, if 00:00:00... then nmap value 
- [x] Temporary BMC node like node-<MTM>-<Serial> or node-<MAC of BMC>(In case MTMS is not available) will be created
* For dodiscovery in genesis:
- [x] Collect BMC MAC information through 'ipmitool lan print 1'
* For hardware discovery request matching process
- [x] Search corresponding BMC node with name like node-<MTM>-<Serial> or node-<MAC of BMC>(In case MTMS is not available)

**Comment by whowutwut** [comment]
@zet809  I assigned this to you for now.  If you agree and think someone else should work on it , please reassign.

**Comment by zet809** [comment]
OK, I see, it is a good idea to use the IP to match the temporary BMC node.

**Comment by whowutwut** [comment]
You mentioned on the call that we need to be able to figure this out from the host.   So the MT/Serial could be done...   This temporary DHCP IP address will change after we made discovery and restarted network... , is that a problem in the removal?

**Comment by zet809** [comment]
The Dynamic ip for the host will be changed during the node is booting into petitboot and genesis kernel, but the Dynamic IP for the BMC won't be changed until expired. So, i think it won't be a problem to remove the temporary BMC node.

**Comment by zet809** [comment]
hi, @whowutwut , any idea?

**Comment by whowutwut** [comment]
@zet809 do you mean use the MAC address to generate a temp bmc node definition name? We don't have that with bmc discover. 

I wonder if there is any unique ID we can use on the openbmc. Haven't figured any out yet..

**Comment by whowutwut** [comment]
I think this should not block #3464  but the priority implementation should be... 

- [ ] Use MTM/Serial, if there
- [ ] Fall back to MAC address (REST, if 00:00:00... then nmap value 
- [ ] Ensure MAC address is cleaned up 
- [ ] Don't use the IP address -> HEX

**Comment by zet809** [comment]
Hi, @whowutwut , we'd like to use this issue to trace all the items related to using BMC MAC address as the unique ID to search BMC node for a host. I had updated description of this issue with more detailed information, pls take a look at.

**Comment by zet809** [comment]
Hi, @whowutwut , do you think we can close this task?

**Comment by whowutwut** [comment]
@cxhong and I plan to do some test with this tomorrow. If all looks ok will close out

**Comment by whowutwut** [comment]
Verified on this build: 
```
[root@boston01 ~]# lsxcatd -v
Version 2.13.6 (git commit b5e5b00c43db3c811d6679b3647af06ea86635ba, built Thu Jul 27 06:15:36 EDT 2017)
```

Looks good! 

```
Jul 27 21:15:04 sn02 xcat[14929]: xcat.discovery.aaadiscovery: (70:e2:84:14:29:10) Got a discovery request, attempting to discover the node...
Jul 27 21:15:04 sn02 xcat[14929]: xcat.discovery.blade: (70:e2:84:14:29:10) Warning: Could not find any nodes using blade-based discovery
Jul 27 21:15:16 sn02 xcat[14929]: xcat.discovery.switch: (70:e2:84:14:29:10) Found node: mid05tor12cn11
Jul 27 21:15:17 sn02 xcat[14929]: xcat.discovery.nodediscover: Removing discovered node definition: node-70e28414290f...
Jul 27 21:15:17 sn02 xcat[14929]: xcat.discovery.nodediscover: node-70e28414290f definition removed from xCAT
```
