### ISSUE TITLE
Makehosts doesn't seem to handle regex properly

### ISSUE THREAD

**Issue by cganglin** [xcat2/xcat-core#3409]
In service group i have the following regex
````
ip=|\D+(\d+)\D+|10.80.1.($1*2+103)|
nicips.ib0=|\D+(\d+)\D+|10.160.1.($1*2+3)|
switchport=|\D+(\d+)\D+|($1+15)|
````

When node definition values are correct, but after running makehosts and checking /etc/hosts the below is what i get:

````
10.80.1.111 sn4b sn4b.lbs.hpc
\D+(\d+)\D+ sn4b-ib0 sn4b-ib0.lbs.hpc
10.160.1.($1*2+3) sn4b-ib0 sn4b-ib0.lbs.hpc
````
Any ideas what to debug

**Comment by cganglin** [comment]
Using xcat 2.13.5

**Comment by immarvin** [comment]
This defect can be easily recreated with xcat 2.13.5 GA version.

hi @bybai , would you please take a look at this? thanks

**Comment by zet809** [comment]
Hi, @cganglin , this is a known issue(Duplicated with #2578 ) and we haven't fixed it yet.

**Comment by cganglin** [comment]
Hi @zet809 Is there any kind of workaround for the time being, if not I have to manually update /etc/hosts and not run makehosts?

**Comment by whowutwut** [comment]
To reduce the scope, We should create a reference page that shows which keywords in the node definition should have regular expression supported and which ones do not . 

Of the ones that should be supported, we should test whether it's broken or not.     We can then prioritize which ones should be fixed now and which ones are lower priority.  

@hu-weihua We need to have some regular expression testcases created, as we don't want https://github.com/xcat2/xcat-core/issues/3047 to happen again as we are making changes to this code.

**Comment by bybai** [comment]
Hi @cganglin , currently, the work around is to manually update /etc/hosts . For this `makehosts` issue, I start to fix it within this sprint. Thanks

**Comment by bybai** [comment]
Hi @cganglin , I fixed this issue in #3432 code. You can have a try if you have time. Thanks.

**Comment by cganglin** [comment]
Ok, which drop of the code I would need to use to get this change?

**Comment by whowutwut** [comment]
@cganglin  It was merged 1 day ago so if you update to today's build, should be there.

**Comment by hu-weihua** [comment]
@whowutwut, I will plan to add test case for this in 2.13.6 sprint2. thanks
