### ISSUE TITLE
[FVT] xcattest treats all nonexistent test cases as `Passed`

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3411]
Currently, `xcattest` treats all nonexistent test cases as `Passed`. Which is not good. Since there may be misspelling in the bundle files. In that case, misspelled test cases will be counted as `Passed`.

I suggest, treats all nonexistent test cases as `No Run`.

    # xcattest -t nonexistent_test_case,blah,foo,bar,baz,quux
    xCAT automated test started at Thu Jul  6 02:23:02 2017
    ******************************
    loading test cases
    ******************************
    To run:
    nonexistent_test_case
    blah
    foo
    bar
    baz
    quux
    ******************************
    Start to run test cases
    ******************************
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1163.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1163.
    ------START::::Time:Thu Jul  6 02:23:02 2017------
    
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1164.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1165.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1167.
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1300.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1300.
    ------END::::Passed::Time:Thu Jul  6 02:23:02 2017 ::Duration::0 sec------
    Use of uninitialized value in array element at /opt/xcat/bin/xcattest line 1301.
    Use of uninitialized value in concatenation (.) or string at /opt/xcat/bin/xcattest line 1301.
    ------Total: 6 , Failed: 0------
    
    xCAT automated test finished atThu Jul  6 02:23:02 2017
    Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
    and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20170706022302 file for failed cases.
    see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20170706022302 file for time consumption

**Comment by hu-weihua** [comment]
This issue is same with #4189.

**Comment by hu-weihua** [comment]
@neo954 , this issue has been fixed by PR #4279. Could you please verify it? You also can refer to the description of #4279 to get the output of fix. thanks.

**Comment by hu-weihua** [comment]
@neo954 . I have not received any feedback for this issue up to now, I suppose the fix has worked. 
Close this issue first, if you find any problem in future, you can reopen this issue again, thanks.
