### ISSUE TITLE
[CI] Add format check for man page and document change

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#3417]
I prefer that we could add the check in the CI check for the new added/modified man page and document to make sure the format is correct.

Since rebuild all the .rst doc need a long time to finish, could we just check the modified or new added one?

**Comment by hu-weihua** [comment]
@daniceexi Due to xCAT team will use IBM internal github to manage task. So move this to https://github.ibm.com/xcat2/task_management/issues/176. Close this one. Could you use new link to track this task, thanks.
