### ISSUE TITLE
rflash support for code update on Supermicro based firmware, LC box "for BigData"

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3421]
The IBM S822LC for Big Data boxes use firmware update procedures different than the "for HPC" boxes where a `pUpdate` tool is used instead of `ipmitool`. 

I think a hpm file may be supplied but we probably want to rely on the recommended process from the knowledge center.  https://www.ibm.com/support/knowledgecenter/POWER8/p8eit/p8eit_fixes_kickoff.htm

Need to define the external changes to rflash to support this.  I think initially we should assume that the user provides us the pUpdate utility as an argument ... 

@gurevichmark @chenglch  Any ideas for the externals?

**Comment by gurevichmark** [comment]
Will we need to include the `pUpdate` with xCAT deps ? Or just ask the user to download from "Fix Central" ?

As for externals, we could use something similar to how "PPC" does it, buy specifying a `-d directory` option. In our case we would expect the `bmc.bin` and `pnor.bin` files to be in that directory.
OR
We could accept both files as input to `rflash` command, perhaps something like:
`rflash --bmc=<path to bmc.bin> --pnor=<path to pnor.bin>`

**Comment by chenglch** [comment]
I haven't found the download link of `pUpdate` from Fix Central. I found the `pUpdate` tarball from login node. I think it is difficult to ship the binary files in the `xcat-dep`, so I prefer the way to make it as the externals. 

For externals, I prefer the way to pass a directory argument which contains the `pUpdate`, `bmc.bin` and `poor.bin` files.  Maybe we do not need `-d` as a option. We can check the argument, if it is a directory, we look it as the `pUpdate` method and check the files in the directory. If the argument is a file and end with `.hpm`, we look it as the `ipmitool hpm` method.

**Comment by whowutwut** [comment]
@chenglch When I go to the fix central site above and select Power -> Scale Out LC -> 8001-22C and select OP825 and select the version 2.10...  Then continue to the download page for it...

![image](https://user-images.githubusercontent.com/10049070/28070965-9f14b65c-661c-11e7-8bc8-ee3a674e2991.png)

It's available to be downloaded with the firmware.  I don't think we should ship it because if it changes, we have to continue to update this tool... the User should get the current one and provide us the path to it..

**Comment by whowutwut** [comment]
@chenglch passing a directory seems to be a good idea...  will keep the arguments more simple.   We can detect the files and then continue based on the `pUpdate,bin,pnor` being found or `hpm` for ipmi...

**Comment by gurevichmark** [comment]
Implemented by PR #3463

**Comment by whowutwut** [comment]
Closing this, asking folks in the lab to execute this whenever possible.  Issues will be opened if needed.
