### ISSUE TITLE
[FVT]add test case for issue 3409 Makehosts doesn't seem to handle regex properly

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3433]
Add test case for issue #3409 
* Discussed with team member; Support there is only one regex in nicips.
* Does not support there are multiple nicips for one nic, and nicips contain regex.

what to do:
* [ ] offer test case list and description
* [ ] implement these test cases

**Comment by hu-weihua** [comment]
hi @bybai, if you want add some test cases for your some issue, just need to add ``testcase_requested`` label in your issue, do not need to open a task. When FVT make work plan, we will go through ``testcase_requested`` label to plan task. 

I will use this task you create this time.  thanks.

**Comment by hu-weihua** [comment]
@neo954 , could you list your test plan in the comment, you have delayed than origin plan one week. One more thing, please discuss your test plan with @bybai first before you paste you plan in comment. thanks

**Comment by hu-weihua** [comment]
@neo954, TWO weeks have passed of this sprint. You still didn't update anything for this task. Could you update what is you plan for this task?

**Comment by hu-weihua** [comment]
This task is duplicate with #3649 . close this one.
