### ISSUE TITLE
[OpenBMC] Modify bmcdiscover to use MAC address of the BMC?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3464]
Opening this issue to track this.  Perhaps we can use the MAC address to get something unique off the boxelder board...

**Comment by whowutwut** [comment]
With the current Firmware, there's NO mac address, but it looks promising.... 

```
[root@fs3 mid05tor12cn14]# ./login.sh
==> IP=172.20.253.102
+ curl -c cjar -k -X POST -H 'Content-Type: application/json' -d '{"data": [ "root", "0penBmc" ] }' https://172.20.253.102/login
{
  "data": "User 'root' logged in",
  "message": "200 OK",
  "status": "ok"
}[root@fs3 mid05tor12cn14]# ./list.sh
++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.20.253.102/xyz/openbmc_project/inventory/system/chassis/list
{
  "data": [
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet",
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc"
  ],
  "message": "200 OK",
  "status": "ok"
}[root@fs3 mid05tor12cn14]# ./boxelder.sh
++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.20.253.102/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc
{
  "data": {
    "BuildDate": "",
    "FieldReplaceable": 0,
    "Manufacturer": "IBM",
    "Model": "",
    "PartNumber": "01DH118",
    "Present": 1,
    "PrettyName": "BMC PLANAR  ",
    "SerialNumber": "000000000000"
  },
  "message": "200 OK",
  "status": "ok"
}++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.20.253.102/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet
{
  "data": {
    "FieldReplaceable": 0,
    "MACAddress": "00:00:00:00:00:00",
    "Present": 1,
    "PrettyName": ""
  },
  "message": "200 OK",
  "status": "ok"
```

**Comment by whowutwut** [comment]
Opened this issue to ask FW team. 
https://github.com/openbmc/openbmc/issues/1968

**Comment by zet809** [comment]
hi, @whowutwut , in bmcdiscover, we use nmap to scan the UPing host IP from an IP range. From the output, it can also return the MAC address for the IP. I think we can modify the bmcdiscover.pm a little to get the MAC address for a specified IP easily. What is you idea?
```
# nmap -sn -n 172.20.140.100-115
Starting Nmap 6.40 ( http://nmap.org ) at 2017-07-16 22:27 EDT
Nmap scan report for 172.20.140.102
Host is up (0.00029s latency).
MAC Address: 70:E2:84:14:29:1B (Wistron InfoComm(Zhongshan))
Nmap scan report for 172.20.140.104
Host is up (0.00032s latency).
MAC Address: 70:E2:84:14:28:0D (Wistron InfoComm(Zhongshan))
Nmap scan report for 172.20.140.111
Host is up (0.00021s latency).
MAC Address: 70:E2:84:14:29:0F (Wistron InfoComm(Zhongshan))
Nmap done: 16 IP addresses (3 hosts up) scanned in 0.56 seconds
```

**Comment by zet809** [comment]
Can be dealt in #3406

**Comment by whowutwut** [comment]
@zet809 if we can get the MAC address that might be a good way to create a unique node definition for discovery while we figure out what the boxelder board will have burned on

**Comment by whowutwut** [comment]
@zet809 Yes, can we have someone implement this support so we can try to remove this work around for ITC boxes.  the boxelder boards should have MAC address restful, so we want to check that first, then fall back on using the nmap...  unless this performs quicker than the rest call.  IT seems like we are already running a rest call against the BMC, so maybe there's no difference...  ?

**Comment by whowutwut** [comment]
MTM/Serial is not available until first IPL boot, we cannot rely on this, See: https://github.com/openbmc/openbmc/issues/1829

**Comment by zet809** [comment]
hi, @whowutwut , yes we have running a rest call to BMC to get MTMS, seems the enumerate method can get both MAC and MTMS info if there is. In this case, I agree with you that we can use the MAC address can show in the return information of the rest call.

**Comment by whowutwut** [comment]
@xuweibj  I assigned this to you since you worked on the MAC implementation in #3406, I think we can close this one out , seems like a duplicate... ?

**Comment by zet809** [comment]
Hi, @whowutwut , you are right that this issue is duplicated with #3406, so I close this one.
