### ISSUE TITLE
[FVT]Confused issues for Prescripts and Postscripts pages

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#347]
1. Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/post_script.html

Description:

Item1:   There is a sentence : See Suggestions for writing scripts. Should we add a link to this file?

Item2:  Another sentence:　The mypostscript file is generated according to the mypostscript.tmpl file.
When Ｉ see this mypostscript.tmpl file, just wonder what is it?
Then notice that below section in this page describes the tmpl file, so do we need to add a current page link to this tmpl file when it appears in this sentence?
Not sure this is a problem or not?

Below issues are all updated directly to GitHub
Item3: In sentence "xCAT provides a way for the admin to customize the information that will be provide to the postscripts/postbootscripts when they run on the node", do we need to update the provide to be provided? or other?

Item4: In section: site table precreatemypostscripts attribute, there are two words "xcat", do we need to change them to be "xCAT"?, and do we need to update the section title first word "site" to be "Site"?

Item5: In sentence "Note the attributes are not always defined exactly as", is it changed to be "Note: the xxxx"? just like other "Note:" reminders?

Item6: In sentence:＂For example, to get the new updatstatus attribute from the nodelist table:＂ change the "updatstatus" to be "updatestatus"

**Comment by caomengmeng** [comment]
@junxiawang, I am reading these pages, and will update if there are anything confused.
Not sure all should be updated just mark them here.

**Comment by daniceexi** [comment]
@caomengmeng Could you talk with @tingtli @junxiawang to figure out how to fix the issues in your list?

**Comment by caomengmeng** [comment]
@daniceexi , I talked with @junxiawang  before opening this issue, and she suggests me to do so. 
I just list the issues maybe should updated, but not sure by myself and @junxiawang  will make final decision.
And for some obvious spelling mistakes, I just updated directly.

**Comment by junxiawang** [comment]
@daniceexi ,I will modify it after meng meng read all the document.

**Comment by whowutwut** [comment]
Assigned to @junxiawang , seems like she is working on this issue.

**Comment by caomengmeng** [comment]
Track with PR: https://github.com/xcat2/xcat-core/pull/417

**Comment by tingtli** [comment]
@caomengmeng  please verify and close it asap

**Comment by caomengmeng** [comment]
Description:

Item1: No need to add  "See Suggestions for writing scripts". 

Item2: Add the folder to find mypostscript.tmpl.

As the description, all other issues listed are fixed before. So close.
