### ISSUE TITLE
[FVT] automatize GPU test 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3478]
what to do:

* [x] offer a test solution, include hardware requirement.
* [x] offer test case list, include detailed description and prerequisite.
* [x]  implement these test cases
* [x] Test these test cases in target environment

**Comment by neo954** [comment]
The following test cases will be added.

    enable_cuda_diskfull_rhels
    enable_cuda_diskless_rhels
    enable_cuda_diskfull_ubuntu
    enable_cuda_diskless_ubuntu
    update_cuda_diskfull_rhels
