### ISSUE TITLE
Fix missed file links in documentation

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#348]
1. Link: https://xcat-docs.readthedocs.org/en/latest/overview/quick_start.html, 
Description: step6 miss Hardware Managment link -- the page source is right, but why no link shown? --Done
2. Link: http://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/index.html
Description: "Initialize the Compute for Deployment" link missed --- Done.

3. Link： https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/updatenode.html
Description:
Item1: For "Using_Clone_to_Deploy_Server#Update_Nodes_Later_On ", miss links, need to update.
there is the content: https://xcat-docs.readthedocs.org/en/latest/advanced/sysclone/sysclone.html
Item2: For "Use instuctions in Sync-Files-label",  is it also a file link?
https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html
The location of synclist file for updatenode and install process

4. Link: https://xcat-docs.readthedocs.org/en/latest/advanced/hierarchy/configure_dhcp.html
Description:
Failed to link doc for 
 XCAT_pLinux_Clusters/#setup-dhcp: 
 https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/discovery/config_environment.html

**Comment by caomengmeng** [comment]
@bybai  Would you please check if the files links should be added or not?

**Comment by bybai** [comment]
@caomengmeng When we wrote the updatenode.rst, these docs were not there, and we just left link there. Now we have these docs, so you can add these 2 links in updatenode.rst.

**Comment by whowutwut** [comment]
We decided this Issue should be expanded this task to search the TODO in the documentation and add the missing links throughout the doc.

**Comment by caomengmeng** [comment]
issue1 and 2 are fixed by https://github.com/xcat2/xcat-core/pull/381

**Comment by caomengmeng** [comment]
Issue 3 and Issue 4 are fixed by https://github.com/xcat2/xcat-core/pull/397
