### ISSUE TITLE
[FVT] add test case for issue 3414 : incorrect petitboot configuration for nodeset shell in flat hierarchical 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3480]
Add test case for issue #3414
what to do:

* [x] offer test case list and description
* [ ] implement these test cases

**Comment by junxiawang** [comment]
cases need to modify:
nodeset_shell_incorrectmasterip

**Comment by zet809** [comment]
The case have been merged, so close this task.
