### ISSUE TITLE
[FVT] add test case for issue 1939: linux orderly shutdown not noticed by xcat.

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3482]
Add test case for issue #1939
what to do:

* [ ] offer test case list and description
* [ ] implement these test cases

**Comment by junxiawang** [comment]
Cases need to modify:
xdsh_node_reboot
xdsh_node_poweroff

**Comment by hu-weihua** [comment]
replaced by task xcat2/xcat2-task-management#103
