### ISSUE TITLE
[FVT] add test case for issue 1002 : lsvm command does not work for kvm VMs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3483]
Add test case for issue #1002
what to do:

* [ ] offer test case list and description
* [ ] implement these test cases

**Comment by junxiawang** [comment]
Cases need to add:
lsvm_vm
lsvm_kvmhost
lsvm_h
lsvm_a
lsvm_all
lsvm_noderanage
Cases need to modify:
lsvm_node

**Comment by gurevichmark** [comment]
The list of testcases looks good to me.

**Comment by hu-weihua** [comment]
close this one and replaced by  xcat2/xcat-core#111
