### ISSUE TITLE
[FVT] add test case for issue 922: Ping not working for non root users on Diskless PowerKVM guests

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3485]
Add test case for issue #922
what to do:

* [ ] offer test case list and description
* [ ] implement these test cases

**Comment by junxiawang** [comment]
Testcase need to modify:reg_linux_diskless_installation_flat

**Comment by hu-weihua** [comment]
close this one and replaced by xcat2/xcat-core#112
