### ISSUE TITLE
[HW support]go through new hardware support checklist for Boston server

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3486]
* [x] The rflash #3373 
Pls follow the checklist https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/New%20Hardware%20Support%20Checklist

Pls modify the checklist below with the command/cases for the specified items.
* [x] bmcsetup verifcation

**Comment by whowutwut** [comment]
@zet809 Is there an internal doc we are following for this... , if so, let's link the URL

**Comment by junxiawang** [comment]
I will use boston02  to do test

**Comment by zet809** [comment]
The verification is done, so close this task.

**Comment by whowutwut** [comment]
@zet809 Do we have any documentation about what was tested and what was supported?  There is suppose to be a copy of the new hardware checklist, where is the URL ?

**Comment by junxiawang** [comment]
I do not do os provisioning for Boston machine support .Such as the test item:
https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/New%20Hardware%20Support%20Checklist%20for%20Boston%20server
