### ISSUE TITLE
[FVT] add test case for issue 3088 : nodeset improvement

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3487]
Add test case for issue #3456 
what to do:

* [ ] offer test case list and description
* [ ] implement these test cases
* [ ] verify issue #3088 before 2.13.6 release

**Comment by hu-weihua** [comment]
@neo954, could you list your test plan in the comment, you have delayed than origin plan one week. One more thing, please discuss your test plan with @robin2008  first before you paste you plan in comment. thanks

**Comment by hu-weihua** [comment]
@neo954, TWO weeks have passed of this sprint. You still didn't update anything for this task. Could you update what is you plan for this task?

**Comment by robin2008** [comment]
Disjoint mode Design is already finalized. The test case need to cover below scenario with SNs at least: 

sharedtftp=0, disjointdhcps=1 :  
   - w/ dhcpserver/dynamic range defined in networks
   - w/o dhcpserver/dynamic range defined in networks
dhcpserver will handled whole node range, and other sn will handle its own children.


 sharedtftp=0, disjointdhcps=0: 
The nodeset request will be dispatched to all MN and SNs

 sharedtftp=1 (Assume that old cases should already cover it)

Extra for "query" action;
nodeset xxx stat -a in disjoint mode.
