### ISSUE TITLE
[FVT] add test case for new feature 3426 :confignetwork support configure a specified ethernet network interface

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3488]
what to do:

* [ ] offer test case list and description
* [ ] implement these test cases
* [ ] verify this issue for 2.13.6 release

**Comment by hu-weihua** [comment]
@neo954, TWO weeks have passed of this sprint. You still didn't update anything for this task. Could you update what is you plan for this task?

**Comment by neo954** [comment]
Will add one test case to testing `confignetwork` against non-install-NIC scenario.
