### ISSUE TITLE
[FVT] "rscan <hmc> -w"  will delete ip attribute of node which was defined ahead

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3490]
**Environment**:
* ``xcat version`` : 2.13.6 (git commit 42fe5c7bf8b86bf81fe8bfe689ce07fe2a721344, built Mon Jul 17 06:15:45 EDT 2017)
* ``arch `` : ppc64

**Bug description:**

If predefine a lpar node which have IP attribute,  then run ``rscan <hmc> -w`` command,  the IP attribute will be deleted. It is unreasonable.  

**How to reproduce:**
*  predefine a node 

       Object name: c910f02c01p07
        arch=ppc64
        cons=hmc
        currchain=boot
        currstate=boot
        groups=all
        hcp=c910hmc01
        hidden=0
        hwtype=lpar
        id=7
        ip=10.2.1.7
        mac=e6:d4:d1:e7:f6:03
        mgt=hmc
        netboot=yaboot
        nodetype=ppc
        os=rhels6.9
        parent=c910f02fsp01
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        pprofile=c910f02c01p07
        profile=service
        provmethod=rhels6.9-ppc64-install-service
        status=powering-off
        statustime=07-17-2017 14:39:08
        updatestatus=synced
        updatestatustime=07-17-2017 13:13:06

* run ``rscan c910hmc01 -w``
* IP of c910f02c01p07 is deleted 

      Object name: c910f02c01p07
        arch=ppc64
        cons=hmc
        currchain=boot
        currstate=boot
        groups=lpar,all
        hcp=c910hmc01
        hidden=0
        hwtype=lpar
        id=7
        mac=e6:d4:d1:e7:f6:03
        mgt=hmc
        netboot=yaboot
        nodetype=ppc,osi
        os=rhels6.9
        parent=c910f02fsp01
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        pprofile=c910f02c01p07
        profile=service
        provmethod=rhels6.9-ppc64-install-service
        status=powering-off
        statustime=07-17-2017 14:39:08
        updatestatus=synced
        updatestatustime=07-17-2017 13:13:06

**Comment by hu-weihua** [comment]
This is the root cause of test case  ``makehosts_null``,  ``makehosts_l`` and `` makehosts_n`` failure in automation environment.

**Comment by zet809** [comment]
Fixed in pull request #3493
