### ISSUE TITLE
xCAT-genesis should use predictable naming instead of old style interface names 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3494]
When doing discovery in xCAT Genesis, the resulting information added to the pre-defined node definition uses the interface names that is running in the Genesis Kernel... 

For example: `eth2` 

```
[root@fs3 Packages]# lsdef sn02 -i hostnames,mac
Object name: sn02
    hostnames=sn02-eth2
    mac=5c:f3:fc:32:b4:90!sn02-eth2|70:e2:84:14:0a:71
```

However, the discovery data knows about the PCI information, 
```
..."eth0!0009:07:00.0,eth1!0009:07:00.1,eth2!0001:01:00.4,eth3!0001:01:00.4,eth4!0001:01:00.4,eth5!0001:01:00.4",...
```

eth2 is `0001:01:00.4` so it should really be : `enP1p1s0f4`

**Comment by immarvin** [comment]
if the nic name the same as the nic name inside genesis, interesting that the nic name in genesis is not predictable naming, is it caused by the genesis udev rule or kernel version? or is there any kernel option like "net.ifname=0" to prohibit the predictable naming

**Comment by whowutwut** [comment]
Yes, the nic name that is stored in `discoverydata` is the same as what we see when we are in the xCAT genesis kernel...   not sure why it's not using the predictable naming, i *think* this is based on Fedora26.   Need to check the rpm....

**Comment by zet809** [comment]
Hi, victor, the new xcat-genesis-base package is available at fs3:/tmp/xCAT-genesis-base-ppc64-2.13.6-snap201707190550.noarch.rpm
haven't upload to xcat.org yet, will do it tomorrow.

**Comment by samveen** [comment]
Is the `x86_64` genesis built on Fedora26 too as well?

**Comment by whowutwut** [comment]
@samveen No, we have not re-built it for that....  Was only looking to update the ppc64 version and we started creating beta builds here:  http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/

If this update something you are interested in for x86_64?

**Comment by whowutwut** [comment]
@zet809 Do we think there's any risk if we update the xcat-dep to use the new xCAT-genesis base so we don't need to use the rpms in beta?   Actually, I just checked xcat.org and @neo954 restructured this so we have a devel area here: http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/ 

I don't know if any of the automation promotion scripts exist that will promote xcat-dep.. so @hu-weihua we need to also be aware of this when we release 2.13.6...  

At least we can get rid of the beta directory and use the devel repo so we can start testing with 2.13.6 , can you upload the new version to the devel repo @zet809 ?

**Comment by zet809** [comment]
Hi, @whowutwut , have uploaded, it is available at https://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-base-ppc64-2.13.6-snap201707190550.noarch.rpm

**Comment by zet809** [comment]
After some search, it seems it is very hard to support newer mlx4-en driver on Fedora26 ppc64. If user want to use it, he either need to reinstall older genesis-base or build genesis-base locally(Opened task #3513 to trace).

**Comment by samveen** [comment]
@whowutwut The title of the ticket contains `genesis should use predictable naming` so I expected that it would be for all platforms,

**Comment by whowutwut** [comment]
@samveen , good point.  

@zet809  Regarding the mlnx4.. .what about having xCAT dep for rh7.4 and leave rh7 alone?    Is this too much change?  Or even temporarily calling it pegas...   this way we won't affect normal users who do not need to change to fedora26...

**Comment by zet809** [comment]
Hi, @whowutwut , for devel version of xcat-dep, I think it is OK to have a single pegas-ppc64le or rh7.4-pegas repo, but I don't think we shall include more that 1 genesis-base in xcat-dep tar ball for release.
So, currently, we may need to provide a link that can download older version of xCAT-genesis-base-ppc64 based on Fedora 24. What is your idea?

**Comment by whowutwut** [comment]
@cxhong  I think the current versions of xCAT-genesis-base that we are testing with have the new predictable naming,   Can you confirm and if so, let's close this out.  

Opening another issue to track the x86_64 @samveen

**Comment by whowutwut** [comment]
Verified in the discoverydata table that we are getting the predictable naming:
```
tg3,enP5p1s0f1!tg3,enP52p1s0f0!tg3,enP52p1s0f1!tg3,enP52p1s0f2!tg3,enP52p1s0f3
```
