### ISSUE TITLE
2.13.6 release process

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3503]
what to do:

* [x] End of cycle regression process: https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/End%20of%20cycle%20regression%20process
* [x] merge master branch to 2.13 branch
* [x] refine release notes: https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.6_Release_Notes
* [x] go through release process below for 2.13.6 :

## Preparation

* [x]  Update the xCAT release notes
   https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.6_Release_Notes

* [x]  Modify the xCAT release page in RTD   http://xcat-docs.readthedocs.io/en/2.13.6/overview/xcat2_release.html 

*  [x]  Update the xcat.org pages, Pull Request:
     * [x] index.html
     * [x] download.html

## Day of Release 
* [x]  Update the xcat-core Wiki page and include the sidebar link to the release notes 
        https://github.com/xcat2/xcat-core/wiki
* [x] Create a release and tag for the 2.13.6 in GitHub  
        https://github.com/xcat2/xcat-core/releases
* [x]   Update the xcat.org pages
    * [x]   merge master -> stable , then `git pull` on xcat.org server 
    * [x]   Once the RC build has been blessed, run the promote_build script on xcat.org for 2.13.6
    * [x]   Manually symlink for xcat-deps
* [x]   Activate the RTD build for the 2.13.6 release 
  Updated the badge in https://github.com/xcat2/xcat-core/blob/master/README.rst
* [x]  bump up the xCAT Version in the master branch to 2.13.7

**Comment by zet809** [comment]
The items above have been done, so close this task. Thx @tingtli

**Comment by samveen** [comment]
@hu-weihua  For future iterations, may I suggest adding one more item in the `Day of Release` section for re-labeling the open tickets in the milestone to future milestones so that the milestone shows up a complete.
CC: @zet809

**Comment by samveen** [comment]
@zet809 Can I also suggest that you take a look at the commits on the 2.13 branch that are not in `2.13.6` release tag.  I expected that the `2.13` branch should have too many commits ahead of the `2.13.6` tag ):

 https://github.com/xcat2/xcat-core/compare/2.13.6...2.13
