### ISSUE TITLE
[Support] Allowing value `reboot` in `chain` attribute

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3504]
I cannot trace any particular commit where the value of `reboot` was removed as a valid value for the `chain` attribute, and the reason why. All I get are documentation changes about this change.

Can I get the reason why this value was removed?

Note: `xCAT-2.9.1` has this as a valid value, and `xCAT-2.13.2` does not. The `dodestiny` script still supports this value, but `xcatd` returns `Unknown state reboot requested`

**Comment by zet809** [comment]
Hi, @samveen , will you pls try 'boot' instead of 'reboot'?

**Comment by samveen** [comment]
@zet809 I use the chain `runcmd=bmcsetup,runimage=register_inventory,reboot,shell`. I need the reboot so that the server reboots and goes back to `shell` (back into genesis), otherwise, the nodes keep sending discovery packets to the server, overwriting the `discoverydata.method` to `undef` (due to bugs in `doxcat` that cause multiple instances of `doxcat` to spawn.).

From what I can make out on the in `doxcat`, the `boot` the same behaviour. However, I am unsure about the xCAT-server's destiny and discovery code. Is the intented usage identical?

**Comment by zet809** [comment]
hi, @samveen , from my point of view, if the node go into runcmd, it won't send discovery package any more. 
And, you shall not use reboot or boot in the chain attribute.After runimage, the genesis will go to shell automatically. If reboot/boot is used, it will cause the host boot into harddisk OS if there is OS installed.

**Comment by samveen** [comment]
@zet809 That is why I want to understand why `reboot` was removed, because from what I see in `xCAT-2.9.1`, reboot just forces a reboot back into genesis.

**Comment by zet809** [comment]
Can you show me the output of 'nodeset <node> reboot' with xCAT-2.9.1, from the code, I don't think it works.

**Comment by samveen** [comment]
I am unable to set the state with `nodeset`
```[sgdc:samveen@inframgtlivexcatmn1 ~]$ nodeset  spare31 shell
spare31: shell
[sgdc:samveen@inframgtlivexcatmn1 ~]$ lsdef  spare31 -i currstate
Object name: spare31
    currstate=shell
[sgdc:samveen@inframgtlivexcatmn1 ~]$ nodeset  spare31 reboot
Error: Unknown state reboot requested
```
However, the value behaves as expected when in the `chain` attribute for a node:
```
[vndc:samveen@xcatmn ~]$ nodels spare-a282135 chain.chain
spare-a282135: runimage=http://xcatmn1/install/custom_runimage/glpi_discover.tgz,runcmd=bmcsetup,reboot,shell
```

**Comment by zet809** [comment]
Will you pls boot the node up and have it run into genesis shell?
Then, let it go through the chain and show me the output from rcons?

**Comment by zet809** [comment]
Hi, @samveen , is there still a problem?

**Comment by samveen** [comment]
Hi @zet809 The requirement of `reboot` as a `chain` value was due to the fact that for my environment, the doxcat script kept sending discovery packets even after `nodediscoverdef` was run, resetting the discovery type from `manual` back to `undef`. This was true for `xCAT-2.9.1` for sure. I am unsure if this still applies or not. I'll be doing a lot of discovery next week, with `xCAT 2.13.6`, and hopefully that particular problem should be resolved. 
In the meantime, you can remove it from all milestones until I can confirm that it is not required.

**Comment by zet809** [comment]
Thx, @samveen
