### ISSUE TITLE
How to ensure that xCAT code levels are kept in sync in Hierarchy Environment, Doc improvements needed

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3515]
How do we ensure that the xCAT MN node image and the xCAT SN images are kept in sync? 

It seems like in order to install the service node image, we have to have a xcat-core/xcat-dep repos.  If they are mismatched and incompatible, then the message is not clear as to the real problem. 

How do we flag and bubble these issues up to the admin...  For example, a plugin bug message doesn't indicate the real problem : https://github.com/xcat2/xcat-core/issues/3495 

Few issues that should be addressed: 
* What's the upgrade process for updating xCAT in a Hierarchy Environment? Is this in RTD?  
* How do we tell that the levels are in sync? 
* Bubble up the correct error messages to help the user figure out the problem...

**Comment by daniceexi** [comment]
Is the command **xcatprobe xcatmn** a good place for this purpose that user run it by manual instead of our xcatd or plugin to check it dynamically.

**Comment by immarvin** [comment]
hi @whowutwut @daniceexi , I have another proposal:
While customer invokes the commands which will be forwarded  from MN to SN, if the version of MN does not match the version of SN, a warning like 
``Warning: <SN>: my xCAT version "Version 2.13.5 (git commit c66de1d8e0fd979700a71a09fb081a89595xxf7b, built Fri Jun 18 02:08:59 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on <MN>``
 will be included in the response.  so that once the version is different between MN and SN, the customer can be aware of it.

Created a PR https://github.com/xcat2/xcat-core/pull/3522 for this proposal, the verification result:
````
[root@c910f03c05k21 ~]# makedhcp c910f03c17k42
Warning: c910f03c05k27: my xCAT version "Version 2.13.5 (git commit c66de1d8e0fd979700a71a09fb081a89595xxf7b, built Fri Jun 18 02:08:59 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21
Warning: c910f03c17k41: my xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe729, built Fri Jun 23 03:06:06 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21

[root@c910f03c05k21 ~]# nodeset c910f03c17k42 offline
Warning: c910f03c17k41: my xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe729, built Fri Jun 23 03:06:06 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21
Warning: c910f03c05k27: my xCAT version "Version 2.13.5 (git commit c66de1d8e0fd979700a71a09fb081a89595xxf7b, built Fri Jun 18 02:08:59 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21
c910f03c17k42: offline
Warning: c910f03c17k41: my xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe729, built Fri Jun 23 03:06:06 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21
Warning: c910f03c05k27: my xCAT version "Version 2.13.5 (git commit c66de1d8e0fd979700a71a09fb081a89595xxf7b, built Fri Jun 18 02:08:59 EDT 2017)" does not match the forwarder's xCAT version "Version 2.13.5 (git commit 5cd9b632a18faabb540f722fba86488019afe629, built Fri Jun 23 03:06:06 EDT 2017)" on c910f03c05k21
[root@c910f03c05k21 ~]#
````

**Comment by zet809** [comment]
Remove the milestone, can't include in 2.13.8
