### ISSUE TITLE
[FVT]:2.9.2rspconfig HMC sshcfg does not show disable state even the state is disabled.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#352]
xCAT 2.9.2  on AIX.

bash-3.2# lsxcatd -v
Version 2.9.2 (git commit 03d9972bf285ba805dfacb15986260c96a634822, built Tue Oct 27 04:04:28 CDT 2015)
bash-3.2# rspconfig c910hmc02 sshcfg
c910hmc02: enabled
bash-3.2# rspconfig c910hmc02 sshcfg=disable
c910hmc02: disabled
bash-3.2# rspconfig c910hmc02 sshcfg
c910hmc02: enabled

**Comment by whowutwut** [comment]
I don't understand the bug here, the disable shows "c910hmc02: disabled"... where is the problem? 

```
bash-3.2# rspconfig c910hmc02 sshcfg=disable
c910hmc02: disabled
```

**Comment by zet809** [comment]
The problem is, after running the command you mentioned, and run "rspconfig c910hmc02 sshcfg" to check the hmc ssh configuration. It returns "enabled".

**Comment by whowutwut** [comment]
HAHA, Sorry about that comment.  Thanks for the explanation,  :-)  I thought the sshcfg without any options was to "enable" the command but I just took a look at the manpage... need to have ``sshcfg=enable`` to enable it.

**Comment by whowutwut** [comment]
Is there a pull request for 2.10 branch?

**Comment by tingtli** [comment]
Verified and close

**Comment by daniceexi** [comment]
After the fix, sometimes the command ``rspconfig <node> sshcfg`` still cannot return the correct status.

**Comment by tingtli** [comment]
Yes, It seems I verified the defect on the node with Er tao's efix.

**Comment by daniceexi** [comment]
@tingtli do you mean xCAT make a new fix again? Or Er tao still need to do something to entirely fix this issue?

**Comment by whowutwut** [comment]
@tingtli @daniceexi Can we verify and close out this issue? or is there something else that needs to be done... questions brought up for the GA readiness review...

**Comment by daniceexi** [comment]
@zet809 did you plan to fix this legacy issue? If yes, could you fix it ASAP?

**Comment by zet809** [comment]
@tingtli I have checked in code, pls verify.

**Comment by tingtli** [comment]
bash-3.2# rspconfig c910hmc02 sshcfg=disable
c910hmc02: disabled
bash-3.2# rspconfig c910hmc02 sshcfg
c910hmc02: disabled
