### ISSUE TITLE
[FVT]:2.9.2 renergy on AIX returns missing /opt/xcat/sbin/xCAT_cim_client for POWER 8 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#353]
xCAT 2.9.2 on AIX

bash-3.2# lsxcatd -v
Version 2.9.2 (git commit 03d9972bf285ba805dfacb15986260c96a634822, built Tue Oct 27 04:04:28 CDT 2015)

bash-3.2# renergy c910f03fsp01 all
c910f03fsp01: ERROR: Cannot find the Energy Management Plugin for xCAT [/opt/xcat/sbin/xCAT_cim_client] or it's NOT executable. Please install the xCAT-cimclient package correctly. Get more information from man page of renergy command.
bash-3.2# echo $?
1

**Comment by daniceexi** [comment]
xCAT energy support for P8 only covers the bmc-based or dfm-based since xCAT needs to communicate directly with the fsp. So for hmc-based hardware control, energy management is not supported.
