### ISSUE TITLE
addkcmdline for deployed kernel only?

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#3532]
Hi!

I'm wondering if there's a way to specify kernel arguments that would be **only** used for the deployed kernel after installation, but not for the installation kernel itself.

As far as I understand things, the `addkcmdline` field in the `linuximage` or `bootparms` tables are used to pass arguments to the deployment kernel, and can also be used after installation for the deployed kernel if prefixed with `R::`. 

But I don't see any way to only use them for the deployed kernel after installation, and *not* for the installation kernel. Is that possible?

Typical use case is to use `rootflags=usrquota,grpquota` to enable XFS quotas on the `/` partition after installation. The problem is that the installation environment does not use XFS, and thus the installation fails with those kernel parameters.

**Comment by immarvin** [comment]
hi @kcgthb , the kernel options in ``addkcmdline`` with prefix ``R::`` will apply to the provisioned kernel only.

**Comment by kcgthb** [comment]
Oh ok, thanks, I thought they would be used for both the installation and provisioned kernel. Maybe it would be worth clarifying the documentation?

Thanks!

**Comment by immarvin** [comment]
hi @kcgthb , updated the description, please review https://github.com/xcat2/xcat-core/pull/3536
