### ISSUE TITLE
Failed to connect to compute node via ssh, even if the nodestat shows sshd.

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3549]
The problem can be recreated with the latest 2.13.5 GA build.

Here is a piece of `bash` script to recreate the problem

    COMPUTE_NODE="c910f03c01p10"
    OSIMAGE_NAME="rhels7.3-ppc64le-netboot-compute"

    makedhcp -n
    rinstall "${COMPUTE_NODE}" "osimage=${OSIMAGE_NAME}"

    NETBOOT_TIMEOUT=600
    declare -i WAIT=0

    while sleep 5
    do
            (( WAIT += 5 ))
            nodestat "${COMPUTE_NODE}" | grep ': sshd$'
            [ "$?" -eq "0" ] && break
            [ "${WAIT}" -le "${NETBOOT_TIMEOUT}" ]
            [ "$?" -ne "0" ] && echo "Netboot failed" >&2 && exit 1
    done

    xdsh "${COMPUTE_NODE}" date
    [ "$?" -ne "0" ] && echo "Failed connect to compute node via SSH." >&2 && exit 1

I observed in some case (2 of 10), the script above failed with the following error message.

    c910f03c01p10: ssh: connect to host c910f03c01p10 port 22: Connection refused

**Comment by neo954** [comment]
The proper behavior I expect is that the compute node can be connected via ssh immediately after the state of the node changed to `sshd`.

**Comment by neo954** [comment]
Some time, I get `Permission denied`.

    c910f03c01p10: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by neo954** [comment]
Reduce the sleep time will increase the chance of failing. For a fast recreation, consider reduce the sleep time to `1` or `0.01`.

**Comment by zet809** [comment]
Remove the milestone and add when plan to fix it.

**Comment by robin2008** [comment]
won't fix
