### ISSUE TITLE
Update xCAT-Genesis-base across the product to use version based on Fedora26

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3551]
This track the creation of xCAT-genesis-base from discussions https://github.com/xcat2/xcat-core/issues/3494

Target 2.13.6? 

- [x] ppc64 - Created a version to support P9 servers https://github.com/xcat2/xcat-core/issues/2933  
    - does not include mlnx drivers and i40e, cannot find.. (https://github.com/xcat2/xcat-core/pull/3514)
- [ ] x86_64 - @samveen requested that we update both to Fedora26 in https://github.com/xcat2/xcat-core/issues/3494

@zet809 Can we bump both up to Fedora26? Are we able to find the mlnx and i40 for x86_64

**Comment by whowutwut** [comment]
@immarvin re-built a version of xcat-dep yesterday:

https://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-201707270619.tar.bz2
https://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201707270523.tar.bz2

**Comment by whowutwut** [comment]
@immarvin Is this version reflected in 
the public repo?
   * http://xcat.org/files/xcat/repos/yum/xcat-dep/

Or the devel one? 
 * http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/

@neo954 made changes to create these repos...

**Comment by immarvin** [comment]
hi @whowutwut , the version reflected in http://xcat.org/files/xcat/repos/yum/xcat-dep/

**Comment by zet809** [comment]
Hi, @whowutwut , no newer mlx-en driver available for Fedora newer than Fedora 24.

**Comment by samveen** [comment]
The newer mlx-en driver are be available on RHEL/Centos 7.x. Why not use that as base for genesis? (Centos instead of RHEL to bypass potential licensing issues).

**Comment by whowutwut** [comment]
@zet809 what's the down side to using centos as the base for genesis instead of fedora?

**Comment by zet809** [comment]
It seems that the corresponding supporting of CentOS will be several months later than Redhat. 
That means it won't be able to support the latest hardware as Fedora or even Redhat.

**Comment by samveen** [comment]
@zet809 @whowutwut , While I agree that `CentOS` will always be released later than corresponding `RHEL`, I already have a counter example where latest drivers are already available for `CentOS`, but not for `Fedora`:  the `mlx-en` driver itself.

**Comment by zet809** [comment]
Hi, @samveen , you are right. 
But for us, such as the latest P9 server, no CentOS or even RH support it yet when latest Fedora does. So, we use the latest Fedora to build Genesis base for P9 servers to do hardware discovery.
And for your concerns, we were considering ship a script or command to have the user be able to build xCAT-genesis-base by themselves through the latest RH MN, what do you think?

**Comment by samveen** [comment]
@zet809 Due to concerns beyond my control, my environment is constrained to CentOS 7.x.
1. Thus we don't use any hardware that cannot be used with it.
2. We won't probably end up using RH. 

However, if `genesis` is based on RHEL 7.x `[base]` (this is an easily repeatable configuration, if the `[updates]` repo is ignored), then I won't need to rebuild the `genesis` RPM. I can just build an `-addon` rpm that'll `just work` with the `genesis-base` rpm.

**Comment by zet809** [comment]
Hi, @samveen , the latest xCAT-genesis-base-x86_64 is built on centos7.4. Maybe a work around is, chroot to the genesis filesystem directory, and install the needed RPM. After that, run `mknb x86_64` to regenerate the genesis initrd.

**Comment by samveen** [comment]
@zet809 @whowutwut I think this ticket is obsolete can should be closed (and move it back to the 2.13.8 milestone).

**Comment by zet809** [comment]
Ok, thx!
