### ISSUE TITLE
Enhance xcatprobe discovery precheck

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3554]
* [x] 1. Check genesis files
        1.1 If there is NIC with lable ``noboot`` in site table (dhcpinterface), check whether has files for that ip range under tftpdir. If has, show warning message.
        1.2 Check genesis packages Version, if build in environment ".fc26", print msg.
        1.3 Check time of initrd file whether later than package install. If not, remind to run ``mknb``. 
* [x] 2. Get switch information by ``switch_macmap``
        2.1 Whether can get information of switch
        2.2 Check whether has node defined wrong port num.
* [x] 3. Check value of chain, need to has value.
* [x] 4. Check node's IP parse
       Check the return IP is same as pre-defined.
* [x] 5. add option for discovery to run pre-check

**Comment by zet809** [comment]
All the check point have been included in #3592 , so this task is completed.
