### ISSUE TITLE
The line 71 of postbootscript "setbootfromnet" is wrong in rhels7.4GA

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3562]
OS: rhels7.4 GA
xcat version: Version 2.13.6 (git commit 3139353de14074526135936490453597cd7d95c0, built Sat Jul 29 06:15:35 EDT 2017)

The line 71 of postbootscript ``setbootfromnet``  is wrong in rhels7.4.

    c910f02c08p07: Sun Jul 30 17:04:55 UTC 2017 Running postbootscript: setbootfromnet
    c910f02c08p07: ./setbootfromnet: line 71: [: too many arguments
    c910f02c08p07: ./setbootfromnet: The network interface NIC on the host 10.2.8.7 is not retrieved, pls check.\n

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/3569

**Comment by immarvin** [comment]
verified by autotest
