### ISSUE TITLE
Discovery in Hierarchy does not work when MN does not have access to CN subnet

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3570]
In hierarchy environment where the xCAT MN does not have access to the Service Node -> Compute Node subnet, we are unable to power control the compute nodes from the MN without the *discovered node definition* adding a `servicenode=<node>` attribute. 

Can the `bmcdiscover` command be enhanced so that the `servicenode` attribute is automatically added to the *discovered node definiton* to avoid this extra step.  

Use case: 
1. Discover the BMCs: `xdsh <service node> "bmcdiscover --range <OPEN RANGE>" -w ` 
2. Power on the compute side to start discovery: `rpower /node-.* boot`

The interface have been implemented in PR #3607
The manpage, usage is included in PR #3686

**Comment by zet809** [comment]
As mentioned in the slack channel, there are much advantage to have MN to access the CN network directly and some issues if not. 
And, also, we can change the command in step 2 to be: 
`xdsh <service node> rpower /node-.* boot`.
What is your idea?

**Comment by whowutwut** [comment]
@zet809 It's not a requirement that the MN has access to the CN.  Yes, it does make life easier, but we don't have a hard requirement for that.   So if users do not have that ability...  is the recommendation to `xdsh <service> rpower /node-.* boot` ? 

Some issues there too... 
* This means that if we do in fact have "islands" where not all SN can communicate with all compute nodes, then we would recommend `xdsh <service>`?
* And what happens in the scenario where we have 2 service nodes managing a group of compute nodes, we don't want to send all the service nodes the rpower command to boot the machines, we only want to send the command to 1 node to launch it... 

It looks like we can't know which service node to assign to the discovered node definition....  we just need to pick one...  

Question here is: 
1. How can we even know we are in hierarchy when we run bmcdiscover ? Can we tell? 
2. If so, then tie the service node to the bmcdiscover output `servicenode=<>` .  Then the mgmt node is able to rpower the compute 

If not, what other ideas are there?

**Comment by zet809** [comment]
It seems we can add another option to bmcdiscover such as --sn <sn_name> to dispatch the discovery request to that SN and add the sn_name to the servernode attribute of the discovered BMC node, what is your point? 
Another simple idea here is, add a route on MN to have it be able to access the subnet on SN.

**Comment by whowutwut** [comment]
The bmc discover can be dispatched to the service node by running Xdsh. But once we write the discoverer definition into the database. From the xcat mn we are unable to do "rsetboot <> net" and "rpower <> boot" because the mn may not have access to the compute network.

Are you suggesting that the bmcdiscover command would have a -- sn option to append that to the discoverer definition?

**Comment by zet809** [comment]
Yes, and had did that with PR #3607

**Comment by zet809** [comment]
Both the codes and doc,manpage had been merged, so, close this task.
