### ISSUE TITLE
makenetworks does not detect existing network defined in the network tables..

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3571]
`makenetworks` does not detect duplicate entry in the networks table. 

Before: 
```
# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","enP2p1s0f1","10.0.0.101",,"<xcatmaster>",,,,,,,,,,,,,
"172_10_0_0-255_255_0_0",,,,,"172.10.253.27",,,,,,,,,,,,,,
```

After....
```
# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","enP2p1s0f1","10.0.0.101",,"<xcatmaster>",,,,,,,,,,,,,
"172_10_0_0-255_255_0_0",,,,,"172.10.253.27",,,,,,,,,,,,,,
"172_10_0_0-255_255_0_0","172.10.0.0","255.255.0.0","enP5p1s0f0","<xcatmaster>",,"<xcatmaster>",,,,,,,,,,,,,
"172_11_0_0-255_255_0_0","172.11.0.0","255.255.0.0","enP5p1s0f1","<xcatmaster>",,"<xcatmaster>",,,,,,,,,,,,,
```

@cxhong and I are doing some end to end bring up, I'm not sure how the first entry was added into the networks table, but when we run `makenetworks` on the MN, two entries are added in addition to the first.... 

Not sure why the first entry is not reused.

**Comment by zet809** [comment]
It seems in networks table, it use the 'net' and 'mask' as the key, not the 'netname'. Will try to fix it tomorrow.

**Comment by bybai** [comment]
This issue can reproduce in my environment.  If all of  `netname` `net`  and `mask` are the same, `makenetworks` can find duplicate record network in networks table. @whowutwut and @zet809 , I think if `netname` or `net` is the same,  the record should also be regarded the same. What are your opinions?

**Comment by whowutwut** [comment]
@zet809 If 'net' and 'mask' are keys, we should not allow chdef to create definitions without those exactly fields... 

This actually exposes more bugs than I had thought....

```
[root@fs2vm110 ~]# mkdef -t network -o "mynetname" net=172.10.0.0
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef -t network -o mynetname
Object name: mynetname
    net=172.10.0.0
```

Now if i create another with net and mask... I have to create a new name
```
[root@fs2vm110 ~]# mkdef -t network -o "mynetname2" net=172.10.0.0 mask=255.0.0.0
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef -t network -o mynetname2
Object name: mynetname2
    mask=255.0.0.0
    net=172.10.0.0
```

Now if i chdef and add in a mask for the "mynetname", it doesn't apply because I think it matches mynetname2.   
```
[root@fs2vm110 ~]# chdef -t network -o mynetname mask=255.0.0.0
1 object definitions have been created or modified.
[root@fs2vm110 ~]# lsdef -t network -o mynetname
Object name: mynetname
    net=172.10.0.0
```

This is pretty serious and we should fix this asap to ensure the DB is correct.... 

@bybai   The `chdef` commands require a netname provided to run changes...

```
chdef -t network -o <netname> mtu=9000
```

So I would expect that the netname should be treated as a "primary" key...  

Again, I don't know how we got that entry into the table, but it looks like from the above, there's more issues here..  @hu-weihua Looks like we need some testcases here...  And we can't just check return code of the command, we have to check that the intended change actually did go into effect....

**Comment by bybai** [comment]
Hi @whowutwut and @zet809 ,  My opinions about this issue:
1, ``netname`` should be the "primary" key, so that ``lsdef`` and other scripts can show the correct information about the specified network; If ``netname`` is the same, there is duplicate.
2, If  ``netname`` is different, but both ``net`` and ``mask`` are the same, this network is duplicate.
3, When using ``tabedit`` to edit ``networks`` table, ``netname``, ``net`` and ``mask`` are required.
4, If using ``chdef`` or ``mkdef`` to create one specified network, ``net`` and ``mask`` are required. 

In above, ``chdef`` example : ``chdef -t network -o <netname> mtu=9000``,  ``net`` and ``mask`` should already be in ``networks`` table. Here only add/modify ``mtu`` value.

**Comment by zet809** [comment]
If the `net` and `mask` are keys of the networks entry, why there is entry without these 2 attributes be wrote in the networks table?

**Comment by bybai** [comment]
Hi @zet809 ,
If use `tabedit`, any lines can be added into xcat table.
For this issue, should enhance `mkdef/chdef` to check if `netname` exists in networks table, update the old  record.

**Comment by bybai** [comment]
Hi @hu-weihua , this task requests test cases for mkdef and chdef command for networks table, you can find related command examples in #3667 descriptions.

**Comment by whowutwut** [comment]
Just thought about a test case... 

What about the situation here where we have to add entries if we want service nodes to handle different dhcp dynamic open range?  Do we just need to create a unique name for this row entry?

**Comment by bybai** [comment]
Hi @whowutwut , you advance a typical scenario, FVT can think about it.
I pasted lots of unit test examples in my pull request #3667, FVT can reference my examples.
