### ISSUE TITLE
xcatprobe xcatmn check the genesis configuration

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3587]
Request to add a check in xcatprobe xcatmn for the genesis config files for the network.  

For example, if we add network entries into the networks table after xCAT is installed, we have to run `mknb` again for the genesis config files to be populated. If this is NOT done, then petitboot will never get the genesis config files. 

The flow is something like: 
1. For each entry in the network tables, if there's a dynamic range defined, validate there's a entry in /tftpboot/pxelinux.cfg/p/<network> 
2. Unless the interface is set to `noboot` in the site.dhcpinterfaces

**Comment by zet809** [comment]
hi, @whowutwut , the default petitboot configuration file generated *not* based on the entries in networks table. But all the subnets available on the node that have mknb run.
These 2 checking had been included "xcatprobe discovery --precheck" functions in task #3554

**Comment by zet809** [comment]
Hi, @whowutwut , the items have been implemented in #3554 , so close this issue.

**Comment by whowutwut** [comment]
Thanks! please ensure that we add a note to the end to end for running this check
