### ISSUE TITLE
xcat-dep repos are not in sync after devel repo created 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3589]
@neo954 manually created the yum repos on xcat.org, and I'm thinking we probably do not want to continue to use this because the complete picture is not implemented. I think we will be worse off when the devel repos are not kept in sync with the latest.  

There's too many pieces that must be completed for this to work
* https://github.com/xcat2/xcat-core/blob/master/builddep.sh
* https://github.com/xcat2/xcat.org/blob/master/promote_build.py
* GSA location where we are storing the files 

I think the flow should be.... 
1. Put the xcat-dep packages in GSA 
2. Running build-dep should ALWAYS upload the file to http://xcat.org/files/xcat/xcat-dep/2.x_Linux/ or http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/ and the rsync to xcat.org yum repo should always go here: http://xcat.org/files/xcat/repos/yum/devel/xcat-dep 
3. When we are ready to promote a release, the promote script should move the yum repo from the devel area to the public: http://xcat.org/files/xcat/repos/yum/xcat-dep/ 

Without this in place, after @immarvin built a new xcat-dep and published it, the devel repo is out of date.  

Here's what happened: 
1. Installed 8/1 build of xCAT using `go-xcat` 
2. Realized the xCAT-genesis-base ppc64 is NOT updated, but it IS there in the non devel repo 
```
[root@briggs01 yum.repos.d]# cat xcat-dep.repo
[xcat-dep]
name=xcat-dep
baseurl=http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/rh7/ppc64le
enabled=1
gpgcheck=0
```
Looking at what files are provided by the repos....
```
[root@briggs01 yum.repos.d]# yum list   |grep xCAT-genesis
xCAT-genesis-base-ppc64.noarch          2:2.13.2-snap201702150049  @xcat-dep <------
xCAT-genesis-base-x86_64.noarch         2:2.13.2-snap201702200120  @xcat-dep
xCAT-genesis-scripts-ppc64.noarch       1:2.13.6-snap201708010615  @xcat-core
xCAT-genesis-scripts-x86_64.noarch      1:2.13.6-snap201708010615  @xcat-core
xCAT-genesis-x86_64.noarch              1:2.7.7-snap201301100842   xcat-dep
```

This is dated from Feb.... 

Looking at the xcat-dep.repo file URL,  the version is not updated.... http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/rh7/ppc64le/xCAT-genesis-base-ppc64-2.13.2-snap201702150049.noarch.rpm

**Comment by whowutwut** [comment]
Another reason why we need #3587

**Comment by immarvin** [comment]
hi @whowutwut , 
````
I think the flow should be....

Put the xcat-dep packages in GSA
Running build-dep should ALWAYS upload the file to http://xcat.org/files/xcat/xcat-dep/2.x_Linux/ or http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/ and the rsync to xcat.org yum repo should always go here: http://xcat.org/files/xcat/repos/yum/devel/xcat-dep
When we are ready to promote a release, the promote script should move the yum repo from the devel area to the public: http://xcat.org/files/xcat/repos/yum/xcat-dep/

````

what is the policy for the subdirectories under http://xcat.org/files/xcat/repos/yum/ with version info (2.11,2.12,2.13) ?

**Comment by neo954** [comment]
@immarvin,

I think we do not intend to preserve `xcat-dep` online repository for old xCAT version (2.12, 2.11 and earlier version). Thus, only `latest` and `devel`.

**Comment by hu-weihua** [comment]
@whowutwut , could you help verify this defect and close it? thanks

**Comment by whowutwut** [comment]
@neo954 @hu-weihua I think things were OK for 2.13.7, correct? If so, let's just close this.
