### ISSUE TITLE
Add debug log for DB subroutine

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#3612]
Plans for sprint1:

* [x] Design a mechanism to enable or disable the debug configuration without restarting xcat.
* [x] Add trace point for the SQL statement
* [x] Add trace point for the cache building.
* [x] Add trace point for the subroutine of Table.pm ( Analyze the traceback information of the subroutine.).

**Comment by zet809** [comment]
Close this task as the code have been merged.
