### ISSUE TITLE
[CORAL]cuda9 support on Pegas

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3623]
* [ ] The pkglist, otherpkglist...
* [ ] The document

**Comment by cxhong** [comment]
I verified CUDA9.0  diskless installation last week on pegas for P9 system. 
the version of CUDA is:  **cuda-repo-rhel7-9-0-local-rc-9.0.103-1.ppc64le.rpm**
the osimage is based on:   **rhels7.4-EA3-ppc64le-netboot-compute**

**Comment by zet809** [comment]
Thx, @cxhong , any modification needed for the document or code?
Have you tried the test script wrote by @neo954 #3559 ? It can help to verify the installation process.

**Comment by zet809** [comment]
Move the next sprint for verification.
The OS shall be pegas Beta.

**Comment by cxhong** [comment]
I verified cuda-9.0  on pegas Beta OS.   Followed documentation http://xcat-docs.readthedocs.io/en/latest/advanced/gpu/nvidia/index.html,   worked fine.  No modification needed.
