### ISSUE TITLE
enhance xcatprobe discovery to check configuration from SN

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3625]
Need to be able to do discovery configuration check on the specified SN. 
`Only` pre-check need to be covered in this task.
* [x] Investigate which items need to be check on SN.
* [ ] Based on the result above, implement the code. ==> will be included in #3657

**Comment by xuweibj** [comment]
No need to modify: 
1. If hierarchy environment, show msg to remind ``Please run xcatprobe xcatmn -i <nic>``.
2. Check all nodes' definition on MN.

Need to add:

1. ** Need to make sure SN's provision network**
  1.1 If defined ``dhcpinterface`` in site table
    1.1.1 Only 1: consider it as provision network nic
    1.1.2 Has 2, but one with noboot: consider the one without noboot as provision network nic
    1.1.3 Has 2, all without noboot: print error msg that need to add noboot for bmc network
  1.2 Get SN's network information by ``tabdump networks``
  1.3 If can not get network by above method, print error msg.
2. Check genesis files
  2.1 Version whether is same with MN ------warning msg
  2.2 All needed files whether exist ------based on SN's network, files exist and could be downloaded.
3. Check dhcp dynamic range
  3.1 Need to add that check whether has dynamic range for SN's provision network.
  3.2 Check whether has node's ip within dynamic range.
4. Use hierarchy framework.

**Comment by immarvin** [comment]
on ``dhcpinterface``, should check whether the specified interface on SN exists, other wise, the incorrect dhcpd.conf might be generated and "dhcpd" service cannot be started, see "tabdump -d site|grep dhcpinterface -A10" for details

**Comment by zet809** [comment]
The investigate is done, and coding will be covered in #3657, so close this task.
