### ISSUE TITLE
[FVT] change the xcat-dep repos to resolve the issue 3589

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3626]
Solve issue #3589 
what to do:
* [x] change the script to upload xcat-dep dev to xcat.org dev directory
* [x] when release, promote the xcat-dep dev package to release directory.

**Comment by zet809** [comment]
Move to next sprint.

**Comment by neo954** [comment]
Two pull requests #3791, xcat2/xcat.org#74 were submitted.
