### ISSUE TITLE
[CORAL]provide a solution to switch IB device to Ethernet mode

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3631]
After IB driver is installed, the IB device will be working in IB mode. 
For SN in CORAL, we need to configure it to be Ethernet mode and assign IPv4 ip address to it.
This task is used to provide the solution to switch IB device working mode and configure IP for it.
* [ ] The solution
* [ ] The document

**Comment by robin2008** [comment]
@bybai    https://github.ibm.com/vhu/c910env/blob/master/notes/coral/end2end/service_nodes.md#switching-mellanox-adapter-to-ethernet-mode

**Comment by whowutwut** [comment]
@bybai This came up today in our working session... 

So before we get too far into this, let me explain the situation.  The machine will have two IB adapters, CX-5 and CX-4 and both will be set to IB Link mode.  The idea here is whether or not it's possible to switch a specified adapter to ETH link mode.   And how would we specify which adapter to change? 

[CX-4 Getting started](https://community.mellanox.com/docs/DOC-2294) ID is 4115
[CX-5 Getting started](https://community.mellanox.com/docs/DOC-2755) ID is 4119

Would we also support 1 link or just all links on the adapter would the switched.  

It would be good if you can describe a high level outline here in the issue before you get too far along so we can see if this would satisfy the requirement.

**Comment by bybai** [comment]
Hi @whowutwut,

Based on review meeting comments from China team, now we lower this task priority and suspend the development work. If I have chance, I will have a try based on your comments.

Summarize review meeting results from China Team:
1, The service nodes are not so many in Coral cluster.
2, Switching IB adapter to Ethernet Mode requirement is not so strong from LBS part.
3, We can not see the future usage from other customers.

**Comment by whowutwut** [comment]
:+1:  OK agreed,  I wanted to make sure we have a plan before working on this.  I do think it's not high priority because it only needs to be run 16 times total... and it doesn't change back.  Let's close this.
