### ISSUE TITLE
[FVT] refine old or add new test cases for xcatconfig 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3636]
what to do:

* [ ] go through all ``xcatconfig`` test case to make sure if they can be used to do new os verification
* [ ] refine old or add new test cases for ``xcatconfig -i/-u/-k/-s/-c``

**Comment by tingtli** [comment]
I think we have cases for xcatconfig.
xcatconfig_null
xcatconfig_h
xcatconfig_v
xcatconfig_k
xcatconfig_k_c
xcatconfig_s
xcatconfig_s_c
xcatconfig_d_V
xcatconfig_i
xcatconfig_u
xcatconfig_u_check_xcatsslversion_rhels_sles
xcatconfig_u_check_xcatsslversion_ubuntu
What we need to do is to standard these cases and add these cases to daily bundle.

**Comment by junxiawang** [comment]
Cases need to modify and add:
modify xcatconfig testcase for issue:#3636
I modify testcases:
xcatconfig_i
xcatconfig_u
xcatconfig_k
xcatconfig_s
xcatconfig_k_c
xcatconfig_s_c
add one new testcase:
xcatconfig_c
