### ISSUE TITLE
[FVT] refine old or add new test cases for ppping

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3639]
what to do:

* [ ] go through all ppping test case to make sure if they can be used to do new os verification
* [ ] refine old or add new test cases for ppping.

The target is to test ppping during doing new os verification automatically.

**Comment by junxiawang** [comment]
Modify testcase:
pping_node
ppping_node
ppping_V_node
ppping_q_node
ppping_d_node
ppping_i_node
ppping_nodes
ppping_V_nodes
ppping_V_s_nodes
New cases added:
pping_invalidnode

**Comment by hu-weihua** [comment]
This task has been finished by pull request #3863. close this task
