### ISSUE TITLE
[FVT] refine old or add new test cases for "Updatenode -P/-F/-S"

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3640]
what to do:

* [ ] go through all ``updatenode`` test case to make sure if they can be used to do new os verification
* [ ] refine old or add new test cases for ``Updatenode -P/-F/-S``

The target is to test ``Updatenode -P/-F/-S`` during doing new os verification automatically.

**Comment by junxiawang** [comment]
@hu-weihua  we just need to modify bundle
