### ISSUE TITLE
xcat reventlog does not work on witherspoon 

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3652]
trying reventlog on the witherspoon results in:
```
reventlog c460c811
This openbmc related function is not yet supported. Please contact xCAT development team.
```

**Comment by immarvin** [comment]
hi @xuweibj  , would you please take a look at this?

**Comment by xuweibj** [comment]
Hi @ralphbellofatto , the command ``reventlog`` on witherspoon is not supported now.

**Comment by ralphbellofatto** [comment]
when will it be supported, we are starting to use witherspoons with xcat at scale and not having this work is a problem.

@whowutwut

**Comment by whowutwut** [comment]
I have asked the openbmc team, if we call the logging API, the data returned is the following: 

```
[root@stratton01 ~]# reventlog frame6u05
frame6u05: 1502335620127 org.open_power.Host.Event.Error.Event
frame6u05: 1502327556629 org.open_power.Host.Event.Error.Event
frame6u05: 1502301309463 org.open_power.Host.Event.Error.Event
frame6u05: 1502314083647 org.open_power.Host.Event.Error.Event
frame6u05: 1502314372698 org.open_power.Host.Event.Error.Event
frame6u05: 1501511600221 xyz.openbmc_project.Common.Error.InternalFailure
frame6u05: 1502315500996 org.open_power.Host.Event.Error.Event
frame6u05: 1502300144862 org.open_power.Host.Event.Error.Event
frame6u05: 1502313424078 org.open_power.Host.Event.Error.Event
```
This is not really useful for anyone, talking to OpenBMC team .... there are some bugs with the associations that are required to map sysfs to inventory paths..

https://github.com/openbmc/openbmc/issues/2103

**Comment by whowutwut** [comment]
Unsetting the target...

**Comment by whowutwut** [comment]
@ralphbellofatto  closing this issue as it's exposed now... but will track new ones with reventlog, for examlple: https://github.com/xcat2/xcat-core/issues/3880
