### ISSUE TITLE
rinv witherspoon firm does not report system firmware

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3655]
rinv firmware appears to not be supported for witherspoon

issuing this for witherspoon results in:
```
rinv c460c801 firm
c460c801: BMC Firmware Product: ibm-v1.99.5-0-r0 (Active)
```

where for the garison it results in:
```
[ralphbel@c460mgt01 chk_sys_firmware]$ rinv c460c001 firm
c460c001: BMC Firmware: 2.13
c460c001: System Firmware Product Version: IBM-garrison-ibm-OP8_v1.12_2.70
c460c001: System Firmware Product Additional Info: op-build-66286d8
c460c001: System Firmware Product Additional Info: buildroot-211bd05
c460c001: System Firmware Product Additional Info: skiboot-5.4.3
c460c001: System Firmware Product Additional Info: hostboot-2eb7706-837c96a
c460c001: System Firmware Product Additional Info: linux-4.4.30-openpower1-a5bfb1d
c460c001: System Firmware Product Additional Info: petitboot-v1.3.2-9a212b5
c460c001: System Firmware Product Additional Info: garrison-xml-19a5164
c460c001: System Firmware Product Additional Info: occ-d7efe30-d919b07
c460c001: System Firmware Product Additional Info: hostb
```
How do we tell the other firmware levels on the witherspoon?

**Comment by immarvin** [comment]
hi @zet809 @xuweibj , would you please take a look at this?

**Comment by whowutwut** [comment]
@gurevichmark Can provide a more clear answer...  he'll be back next week. 

@ralphbellofatto This function was working and then broken in a recent firmware update. It should be back soon... once the firmware is fixed to show it, xCAT will display the additional information.

**Comment by whowutwut** [comment]
@ralphbellofatto Output would be something like this:  https://github.com/xcat2/xcat-core/pull/3306

**Comment by gurevichmark** [comment]
Yes, it appear to work on later versions of firmware:
```
[root@stratton01 ~]# rinv p9euh02 firm
p9euh02: HOST Firmware Product: IBM-witherspoon-sequoia-ibm-OP9_v1.17_1.67 (Active)
p9euh02: HOST Firmware Product: -- additional info: buildroot-2017.5-93-g9b91216
p9euh02: HOST Firmware Product: -- additional info: capp-ucode-9c73e9f
p9euh02: HOST Firmware Product: -- additional info: hostboot-3fa8be9
p9euh02: HOST Firmware Product: -- additional info: hostboot-binaries-6a7251e
p9euh02: HOST Firmware Product: -- additional info: linux-4.12.1-openpower1-p3a0d8f7
p9euh02: HOST Firmware Product: -- additional info: machine-xml-efdf4aa
p9euh02: HOST Firmware Product: -- additional info: occ-1647d53
p9euh02: HOST Firmware Product: -- additional info: op-build-v1.17-176-g11dd356-dirty
p9euh02: HOST Firmware Product: -- additional info: petitboot-v1.5.0-p3eae874
p9euh02: HOST Firmware Product: -- additional info: sbe-2021c6-p1db2ba
p9euh02: HOST Firmware Product: -- additional info: skiboot-v5.7-rc2
p9euh02: BMC Firmware Product: v1.99.8-178-g7a75570 (Active)
p9euh02: BMC Firmware Product: v1.99.8-181-ga6755e6 (Active)
[root@stratton01 ~]#
```

**Comment by ralphbellofatto** [comment]
we just updated to the most recent sequoia firmware 1730c and we still see only this:
```
rinv c460c802 firm
c460c802: BMC Firmware Product: ibm-v1.99.8-98-g6734f31-r2-0-g752ced3 (Active)
```

The bmc pflash function shows we have the following firmware:
```
IBM-witherspoon-sequoia-ibm-OP9_v1.17_1.87
	op-build-v1.17-210-gbabb528
	buildroot-2017.05-93-g9b91216
	skiboot-v5.7
	hostboot-f523eaa
	linux-4.12.1-openpower1-p8927fdf
	petitboot-v1.5.1-pce8abef
	machine-xml-5575e7e
	occ-ca84830
	hostboot-binaries-c24fccd
	capp-ucode-9c73e9f
	sbe-02021c6-p6a0f00f
```

**Comment by ralphbellofatto** [comment]
this came in from Mark Perez.

Hello,

 I think Kurt's SW398982 IP address 0.0.0.0 and our inability to set permanently set dhcp in petitboot is the same OpenBMC issue #2033:
https://github.com/openbmc/openbmc/issues/2033#issuecomment-318353661

   If I am correct, Uma said this would be in the next official firmware release. 

  We are doing a lot more network boots and installs requiring DHCP, is it possible to get a target for a fix for when it will be available?

  Thanks, Mark

**Comment by whowutwut** [comment]
Yea... @ralphbellofatto  I don't think the OP910 drivers have the fix in there yet...    The first time I have seen this information re-appear is on last Fridays' development build...  it shows this. 
```
[root@stratton01 ~]# rinv frame6u05 firm
frame6u05: HOST Firmware Product: IBM-witherspoon-sequoia-ibm-OP9_v1.18_1.11 (Active)
frame6u05: HOST Firmware Product: -- additional info: buildroot-2017.5-163-g8035745
frame6u05: HOST Firmware Product: -- additional info: capp-ucode-9c73e9f
frame6u05: HOST Firmware Product: -- additional info: hostboot-binaries-883d218
frame6u05: HOST Firmware Product: -- additional info: hostboot-faac61e
frame6u05: HOST Firmware Product: -- additional info: linux-4.12.3-openpower1-p593bf1b
frame6u05: HOST Firmware Product: -- additional info: machine-xml-5575e7e-p28bf2dc
frame6u05: HOST Firmware Product: -- additional info: occ-d650501
frame6u05: HOST Firmware Product: -- additional info: op-build-v1.18-36-g3419fa8
frame6u05: HOST Firmware Product: -- additional info: petitboot-v1.5.1-p1b1d3ef
frame6u05: HOST Firmware Product: -- additional info: sbe-2021c6-pea3c159
frame6u05: HOST Firmware Product: -- additional info: skiboot-7937c7
frame6u05: BMC Firmware Product: ibm-v1.99.8-188-g91af6d-test0-0-g7ea721b-dirty (Active)
```

But with that firmware, our machine has some check stops. and cannot boot into the host, goes into Quiesced.  So I have not applied this build on any other machines nor have I taken Monday's dev build.

**Comment by ralphbellofatto** [comment]
how do we make sure this firmware makes into a OP release so i can install it.?

**Comment by whowutwut** [comment]
This is prebuilds that will eventually be part of the OP910 builds...  It's built from the IBM GHE repo.  FYI @jayeshmpatel There are more users that are looking forward to the builds coming up...

**Comment by ralphbellofatto** [comment]
I was told there was one OP910 build happening in about 2 weeks. How do we tell if this is included in that.

I have noticed that there is not a new release of the opennbmc code yet.  Last release was July 12:

![image](https://user-images.githubusercontent.com/4139514/29362661-dc8032dc-825a-11e7-9e3d-58240eb1171f.png)

**Comment by gurevichmark** [comment]
It appears a new OP910 build got released today - 1734.
Verified that `rinv <node> firm` works on it.

**Comment by whowutwut** [comment]
Closing based on Mark's verification, @ralphbellofatto Please open new ones as we see.. They are trying to release a new FW on friday 9/1...

**Comment by ralphbellofatto** [comment]
will the firmware released on 9/1 work on dd1 hardware??

**Comment by whowutwut** [comment]
I *think* yes.... They are trying to fix that right now.
