### ISSUE TITLE
Implement xcatprobe discovery pre-check on SN enhance 

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3657]
#3625 

* [ ] Configuration Check
* [ ] Genesis files Check
* [ ] Node definition

**Comment by zet809** [comment]
Move the next sprint to implement.

**Comment by zet809** [comment]
Remove the milestone and add one when we plan to work on it.

**Comment by zet809** [comment]
Let's close this task and reopen it if plan to do.
