### ISSUE TITLE
Investigate the performance of bmcdiscover in large cluster

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3658]
Need to modify code to return different mtms for different node.

**Comment by xuweibj** [comment]
Setup one CN as multiple simulators with different IPs bind on the same NIC, return different mtms.

200 nodes 
* -z:                     58.703s
* -w:                    58.253s
* -z & -w:          1m3.403s

500 nodes:
* -z :                  2m0.815s
* -w :                 2m8.345s
* -z & -w :         2m15.829s

1000 nodes:
* -z :                  4m22.750s
* -w:                  4m56.516s
* -z & -w:          4m23.901s

2000 nodes: 

Only can discover less than 1100 nodes (4m56.916s) and with error msg ``Error: bmcdiscover plugin bug, pid 27387, process description: 'xcatd SSL: bmcdiscover for root@localhost: bmcdiscover instance' with error 'socketpair: Too many open files at /opt/xcat/lib/perl/xCAT_plugin/bmcdiscover.pm line 598.``.

**Comment by zet809** [comment]
*[ ] What is the performance of find 1 node in a range of 5000/10000 IPs.

**Comment by whowutwut** [comment]
@xuweibj If you edit the initial post, then the purpose of the issue will be all contained in the first post for easier readability. 

Can you also add what the goal is for this issues....  ? Maybe in a check list like @zet809  created.

**Comment by xuweibj** [comment]
bmcdiscover against 5000 IPs find 1 node :  2m38.711s
 bmcdiscover against 10000 IPs find 1 node :  5m59.377s

**Comment by daniceexi** [comment]
@xuweibj please talk with @neo954 for any nmap option change to improve performance.

**Comment by whowutwut** [comment]
One big problem here that mentioned https://github.com/openbmc/openbmc/issues/1881#issuecomment-322544672 is that the first call to OpenBMC rest causes the REST service to be activated.  

This can take 30 seconds to 1 minute...  That's about a min of 38 hours if running against 4600 nodes.  It's unlikely that we would do this all at once.... but still not good.

**Comment by xuweibj** [comment]
Scan 10000 IPs:
1 host up : 371.89 seconds
10 host up: 283.06 seconds
100 host up: 248.51 seconds
500 host up: 247.38 seconds
1000 host up: 245.76 seconds

**Comment by zet809** [comment]
Hi, @whowutwut , yes, 1st the RESTful access are parallel, 2nd there won't be so many BMC booting up at the same time, 200+ node a weeks for Alpha, right? So, won't be that long.

**Comment by xuweibj** [comment]
MN: fs1
Simulator: frame45cn02
bmcdiscover against 2000 IPs (192.168.101-110.1-200), 200 Host up (192.168.101.1-200)
-w: 2m10.861s
-z: 1m25.141s

**Comment by chenglch** [comment]
Interesting result,  does `-w` take more work about updating the database? This extra action takes more than half a minute.

**Comment by xuweibj** [comment]
bmcdiscover against 2000 IPs (192.168.101-110.1-200), 500 Host up (1920.168.101-105.1-100)
-w : 4m43.735s
-z : 2m11.186s

**Comment by whowutwut** [comment]
Is the perf data stored in some excel doc that we can view and graph trends...?  Or just in this text format above?

**Comment by xuweibj** [comment]
After modify code to allow max 32 children processes.(I will create pull request) Test results:
bmcdiscover against 2000 IPs (192.168.101-120.1-100), 500 Host up (192.168.101-105.1-100)
-z: 29s--31s
-w: 3m--4m

So will suggest customer to run ``bmcdiscover`` with ``-z`` create a stanza file. And then ``mkdef`` to create nodes.

**Comment by zet809** [comment]
We get the result of the verification, so close this task.
