### ISSUE TITLE
the osver function return the same value for redhat7 with or without argument

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#366]
for redhat6, The function osver's return value is rhels6 and rhserver6 with or without argument(all).
The redhat 7 return the same value. We should keep the coherence.

**Comment by immarvin** [comment]
when "type" is not specified for Utils::osvers(), the return value should be "rhels6" for rhels6, however, some existed code in xcat is still using “rhserver6” , we'd better keep the current code to keep compatibility.
