### ISSUE TITLE
[openbmc] rsetboot with no options and machine is quiesced will forever hang

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3668]
I'm not sure how to force the OpenBMC node into the "quiesced" state, whomever works on this issue should contact Uma or someone on the OpenBMC FW team to ask....

Running `rsetboot <node>` with no options never returns...

```
[root@stratton01 ~]# rsetboot frame6u05

```

Running again with BYPASS:
```
[root@stratton01 ~]# rsetboot frame6u05
$VAR1 = {
          'frame6u05' => {
                           'password' => '0penBmc',
                           'bmc' => '10.6.5.254',
                           'cur_status' => 'LOGIN_REQUEST',
                           'username' => 'root'
                         }
        };

Use of uninitialized value in pattern match (m//) at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 654.
Use of uninitialized value $subcommand in pattern match (m//) at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 731.
Use of uninitialized value $subcommand in string eq at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 745.
$VAR1 = {
          'LOGIN_REQUEST' => 'LOGIN_RESPONSE'
        };


```

Waited over 5 minutes for this command to return...

In a 2nd window, I checked to see if the BMC is responding.. or the node is UP..

```
[root@stratton01 ~]# rpower frame6u05 state
frame6u05: quiesced
```

So we should have some sort of timeout on the command side to prevent this from happening... 
This is probably a generic change that is required for the plugin framework...

**Comment by zet809** [comment]
Hi, @xuweibj , will you pls take a look at this issue? Thx!

**Comment by xuweibj** [comment]
Hi @whowutwut , I modified code to support rsetboot <node> with no options. But I don't think the rpower's result is related with it. For ``rsetboot`` command, just sent login request and then our code hang. It should not affect CN's status.

**Comment by whowutwut** [comment]
I've verified this using:
```
[root@stratton01 ~]# lsxcatd -a
Version 2.13.7 (git commit b0249c798f381e4d24a2f4dafc612a1317c81c44, built Thu Aug 24 06:15:36 EDT 2017)
This is a Management Node
dbengine=SQLite
```

Looks good.. not able to reproduce with the simple test:
```
[root@stratton01 ~]# rpower p9euh02,frame6u05 stat
frame6u05: on
p9euh02: quiesced
[root@stratton01 ~]# rsetboot p9euh02
p9euh02: Default
```
