### ISSUE TITLE
TravisCI does not catch the some warnings in openbmc code... 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3669]
This is probably more difficult than I had originally thought we think to have travisCI to catch these warning in the code when running under BYPASS mode. 

```
[root@stratton01 ~]# rsetboot frame6u05
$VAR1 = {
          'frame6u05' => {
                           'password' => '0penBmc',
                           'bmc' => '10.6.5.254',
                           'cur_status' => 'LOGIN_REQUEST',
                           'username' => 'root'
                         }
        };

Use of uninitialized value in pattern match (m//) at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 654.
Use of uninitialized value $subcommand in pattern match (m//) at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 731.
Use of uninitialized value $subcommand in string eq at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 745.
$VAR1 = {
          'LOGIN_REQUEST' => 'LOGIN_RESPONSE'
        };


```

This code path only is invoked for openbmc managed machines and we don't have any of those in CI.... we have to run a specific command to get it to down this code path, if we run rpower on the same node... we don't see the warnings ...

```
[root@stratton01 ~]# rpower frame6u05 state
$VAR1 = {
          'frame6u05' => {
                           'password' => '0penBmc',
                           'bmc' => '10.6.5.254',
                           'cur_status' => 'LOGIN_REQUEST',
                           'username' => 'root'
                         }
        };

$VAR1 = {
          'LOGIN_REQUEST' => 'LOGIN_RESPONSE',
          'RPOWER_STATUS_REQUEST' => 'RPOWER_STATUS_RESPONSE',
          'LOGIN_RESPONSE' => 'RPOWER_STATUS_REQUEST'
        };

frame6u05: quiesced
```

Lines 654 was added in PR: https://github.com/xcat2/xcat-core/pull/3506 and passed the CI testing. 

Line 741 and 745 was added months ago, so this is probably before TRAVIS CI was implemented. 

Perhaps the process should be that developers always run in bypass mode  in their UT to reduce the warnings ...

**Comment by whowutwut** [comment]
@hu-weihua I think this would be difficult to implement in CI because we are not testing different management types of machines in CI currently, if you agree. please close this and add "won't fix"

**Comment by hu-weihua** [comment]
@whowutwut , yes, I agree to close it first.
