### ISSUE TITLE
[openbmc] Add support for rflash to run in the background and redirect

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3671]
Opening this task to track.  In https://github.com/xcat2/xcat-core/pull/2203 we enabled rflash to run on the xcatdaemon side so that any interruptions to the ssh connection to the MN will not disrupt the flash process..

We should also do this on both the upload/activate pieces.  

In my latest attempt to rflash, I do not see anything saved for `frame6u05` into `/var/log/xcat/rflash` 

```
[root@stratton01 ob910.1732.20170807n]# ls -ltr /var/log/xcat/rflash/
total 48
-rw-r--r-- 1 root root 47050 Jul 24 13:35 briggs01.log
```

If @chenglch has some cycles, can help...

**Comment by chenglch** [comment]
@whowutwut , OK, I will look into this.

**Comment by gurevichmark** [comment]
Removing myself since @chenglch said he will look into this.

**Comment by zet809** [comment]
Remove the sprint label and add one in the sprint plan when we plan to support.

**Comment by whowutwut** [comment]
@chenglch So here... what we want to do is take an approach similar to IPMI.... 

Here's an example of IPMI flashing: 
```
[root@stratton01 ~]# rflash boston02 -d /mnt/xcat/iso/supermicro_firmware/p9/20170929PNOR_BMC0.30/xCAT/
boston02: rflash started, Please wait...
boston02: Firmware updated, powering chassis on to populate FRU information...
```

Without using -V, we don't print anything about the file being stored in `/var/log/xcat/rflash/` but I think we might even want to change this message in IPMI... to be the following:

```
cn01: rflash started, Please wait... (see /var/log/xcat/rflash/cn01.log for details)
```

Then for OpenBMC, we want to mimic this and save the output into /var/log/xcat/rflash and not have the code check status to standard out... 

Currently it looks like the following: 

```
[root@briggs01 p9_generic]# rflash mid05tor12cn13 -a /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/witherspoon.pnor.squashfs.tar
mid05tor12cn13: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/witherspoon.pnor.squashfs.tar ...
mid05tor12cn13: Upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.52
mid05tor12cn13: rflash started, please wait...
mid05tor12cn13: Activating firmware update. 10%
mid05tor12cn13: Activating firmware update. 10%
mid05tor12cn13: Activating firmware update. 10%
mid05tor12cn13: Activating firmware update. 10%
mid05tor12cn13: Activating firmware update. 10%
...
```

Since we do have an upload/activate step for OpenBMC, maybe we can reduce this to: 
```
[root@briggs01 p9_generic]# rflash mid05tor12cn13 -a /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/witherspoon.pnor.squashfs.tar
mid05tor12cn13: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/witherspoon.pnor.squashfs.tar ...
mid05tor12cn13: Upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.52
mid05tor12cn13: rflash started, please wait... (see /var/log/xcat/rflash/mid05tor12cn13.log for details)
```

**Comment by chenglch** [comment]
@whowutwut  I haven't run rflash against openbmc servers before. Do we need some special steps to protect from bricking BMC before running `rflahs -a` ?

**Comment by whowutwut** [comment]
@chenglch The output today is fairly verbose ... here's an example over 4 nodes. .

```
[root@briggs01 vhu]# rflash mid05tor12cn[02,05,13,15] -a /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/obmc-phosphor-image-witherspoon.ubi.mtd.tar 
mid05tor12cn13: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
mid05tor12cn02: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
mid05tor12cn05: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
mid05tor12cn15: Uploading /mnt/xcat/iso/openbmc/910.1740.20171003b_1740A/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
mid05tor12cn02: Upload successful. Attempting to activate firmware: ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn13: Upload successful. Attempting to activate firmware: ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn13: rflash started, please wait...
mid05tor12cn02: rflash started, please wait...
mid05tor12cn05: Upload successful. Attempting to activate firmware: ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn13: Firmware update successfully activated
mid05tor12cn15: Upload successful. Attempting to activate firmware: ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn02: Activating firmware update. 10%
mid05tor12cn05: rflash started, please wait...
mid05tor12cn05: Firmware update successfully activated
mid05tor12cn15: rflash started, please wait...
mid05tor12cn15: Activating firmware update. 10%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Activating firmware update. 30%
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn02: Firmware update successfully activated
mid05tor12cn15: Activating firmware update. 30%
mid05tor12cn15: Error: DBusException("Unknown interface 'xyz.openbmc_project.Software.ActivationProgress'.",)
[root@briggs01 vhu]# 
```

Ill have to follow up with FW team about that last error.

**Comment by chenglch** [comment]
@whowutwut , As rest api is a little different from the ipmi , it is already a stateless interface and all of the message is defined by us. Do we still need this issue which intent to redirect the output for each node?

**Comment by whowutwut** [comment]
Sorry for the delay in my response.  Yes, there's no need to run this in the background... but is there any value in providing the output stored for the command in `/var/log/xcat/rflash`?  On each run of rflash, does the output get appended or replaced? 

Why did we save it to those files in the first place?

**Comment by chenglch** [comment]
@whowutwut, I think this is a common question for our xcat command, as the output is from xcat code, not like the ipmi one from the ipmitool command. I don't have too much user experience about this. Maybe @neo954 could give us some advice from the system admin perspective.

**Comment by whowutwut** [comment]
@gurevichmark When we have error messages coming out from the rflash command, does any of it log anywhere in our `/var/log/xcat/`.  I'm trying to think... if we do batch update of firmware and the return code from rflash is not zero, we could grep for the errors in some log file....    I guess commands.log would store it. 

@chenglch But if someone breaks the connection of the terminal running rflash, we would not get the response... perhaps it would get saved in commands.log?  Not sure.... anyone know?

**Comment by chenglch** [comment]
@whowutwut, As the http rest request is atomic,  if the scenario you mentioned happens, `rflash` command exits unexpectedly,  the user should use `rflash -l` or other related command to verify the status. I think xcat should do nothing here.

I think your thought is like a system to check the status of history command or jobs, this maybe useful for long time jobs.

**Comment by whowutwut** [comment]
@chenglch Understand... 

@bybai   what is the plan for #4245 and what happens if it's interrupted in the middle of the process, the admin would have to finish off the flashing procedure manually?

**Comment by zet809** [comment]
rflash works well now, do we still want to do such thing?
