### ISSUE TITLE
[openbmc] rflash must run the preserve network REST api before doing any flash 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3672]
@gurevichmark see this thread: https://ibm-systems-power.slack.com/archives/C6DL07230/p1502467965861157

After I ran it with todays build.... , it erased my static IP configuration, so maybe this should be a bug.

Opening this issue to make sure that we preserve the network setting via rest calls before running any code update..  Please clarify with Adriana whether we need for both PNOR and BMC....

**Comment by whowutwut** [comment]
We might want to always protect the network regardless...

**Comment by zet809** [comment]
As I know about FSP and BMC for x86_64, they don't need to call preserver the network configurations before doing firmware update. No sure why BMC for OpenPOWER and OpenBMC don't follow this.
I agree with you @whowutwut that we shall keep the network configuration regardless.

**Comment by whowutwut** [comment]
@zet809. Not sure. I'm trying to figure this out the next few days....I think it's a work around documented in the flash process   

But it might be wise for us to just run the preserve network since we don't know what version we are upgrading to/from.

**Comment by gurevichmark** [comment]
For reference the REST call to make is 
```
curl -c cjar -b cjar -k -H “Content-Type: application/json” -d “{\“data\” : 1}” -X PUT https://${BMC_IP}/org/openbmc/control/flash/bmc/attr/preserve_network_settings
```

**Comment by gurevichmark** [comment]
But I think this issue should be closed. According to Adriana Kobylak, the "preserve_network_settings" 
REST API will not be supported in the official driver. She said all `/org/openbmc/control/flash` will be removed before GA.

**Comment by daniceexi** [comment]
If the preservation of network cfg won't be supported by openBMC itself, then what's our solution?

**Comment by gurevichmark** [comment]
My understanding that it will be done by default:

![image](https://user-images.githubusercontent.com/16106630/29321473-83b505f4-81a8-11e7-8da7-50a11b87526b.png)

**Comment by whowutwut** [comment]
Confirmed with Adriana, the interface will be removed 

> Adriana Kobylak: correct, the org/openbmc/control/flash interface will be removed and there won’t be a need to issue that command

[Slack Link](https://ibm-systems-power.slack.com/archives/C6DL07230/p1502843559000207?thread_ts=1502733630.512602&cid=C6DL07230)

**Comment by daniceexi** [comment]
Get it, thanks.

**Comment by zet809** [comment]
Hi, @gurevichmark , after the BMC is updated, will the host be powered on? Then, we can run "nodeset <node> runcmd=bmcsetup,osimage=<diskless_image_name>" before rflash, then after flash finished and the host will boot into genesis to configure BMC again, then boot to deploy diskless image.
If not, it will be a little complex to reconfigure OpenBMC.
Or, will the firmware preserve the network configuration automatically? That will be best method.
