### ISSUE TITLE
[openbmc] reventlog - ability to clear log messages 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3673]
This is blocked by the following issues in OpenBMC:
* https://github.com/openbmc/openbmc/issues/1561
* https://github.com/openbmc/openbmc/issues/1327

xCAT only supports the clear all function today.   Is there a need to clear individual event logs.. 

In https://github.com/openbmc/openbmc/issues/1561, still waiting decision about whether they will provide an option to clear all..   I think we should wait for this function.  Asking for an API so we can code it up. 

In https://github.com/openbmc/openbmc/issues/1327, there's an example of the delete option, we are not calling this... but should we even implement this?

**Comment by immarvin** [comment]
hi @xuweibj , would you please take alook at this?

**Comment by xuweibj** [comment]
This is fixed in pull request #3967. 
@whowutwut shall we close this issue?

**Comment by whowutwut** [comment]
Ok yes.  I don't want to verify on too many of the machines because I want to use some of the errror to see if the RAS logging can make sense of any of the logs in the logging API
