### ISSUE TITLE
[openbmc] rflash should remove the known_host entry for the BMC when flashing

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3674]
When we flash the BMC, it will essentially install a new version of the OS, because of this, the RSA key will not match what is saved in the known_hosts on the MN or SN.  Causing problems with rcons.. 

We would get this message: 
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
b1:d2:e7:22:09:53:f4:a8:c7:60:24:db:bc:25:a4:3c.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending RSA key in /root/.ssh/known_hosts:9
```

So to fix this, we should remove the entry in the known_hosts when we activate a new BMC .. 

Some discussion here: https://ibm-systems-power.slack.com/archives/C6DL07230/p1502476526200600

**Comment by zet809** [comment]
So, it means:
1. remove the old entry in known_hosts file
2. call rspconfig sshcfg internally?

**Comment by whowutwut** [comment]
I think we should just look into the first step for this issue. Eventually the bmc is suppose to persist the keys so we should not have to run ssh config under the covers.  So this is another reasons maybe we want to ship sshpass or recommend the admin download it.

**Comment by zet809** [comment]
hi, @neo954 , as we discussed in the sprint plan meeting, can you pls verify whether @chenglch 's fix can fix this issue? Thx!

**Comment by neo954** [comment]
Verified with `xCAT-server-2.13.7-snap201709200615.noarch`. The problem was fixed.

**Comment by neo954** [comment]
I will close this one since it was fixed.
