### ISSUE TITLE
[FVT] Unknown command shows in /xcatpost/mypostscript: line 224

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3697]
The bug is against `xCAT-2.13.7-snap201708140615` on `ppc64le`.

**The recreation steps**

1. Install a compute node with the default xCAT generated osimage definition, `rhels7.4-ppc64le-netboot-compute`.
1. After the operating system deployment on the compute node finished. Log in to the compute node.
   * Check the log file `/var/log/xcat/xcat.log`
     Please notice, near the end of this file, there is a line shows `/xcatpost/mypostscript: line 224: c910f03c01p09: command not found`. Where `c910f03c01p09` is the hostname of the xCAT management node.
   * Check line 224 of file `/xcatpost/mypostscript`. It seems line 224 does have problem.

.

        # tail -n 15 /var/log/xcat/xcat.log
        /etc/ssh/sshd_config line 138: Deprecated option KeyRegenerationInterval
        Could not load host key: /etc/ssh/ssh_host_ed25519_key
        Wed Aug 16 03:37:45 EDT 2017 postscript remoteshell return with 0
        Wed Aug 16 03:37:45 EDT 2017 Running postscript: syncfiles
          Did not sync any files.
        Wed Aug 16 03:37:45 EDT 2017 postscript syncfiles return with 0
        /xcatpost/mypostscript: line 224: c910f03c01p09: command not found
        Removed /etc/systemd/system/multi-user.target.wants/NetworkManager.service.
        Removed /etc/systemd/system/dbus-org.freedesktop.NetworkManager.service.
        Removed /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service.
        running /xcatpost/mypostscript.post
        Wed Aug 16 03:40:11 EDT 2017 Running postbootscript: otherpkgs
        Wed Aug 16 03:40:11 EDT 2017 postbootscript otherpkgs return with 0
        provision completed.(c910f03c01p10)
        /xcatpost/mypostscript.post return

.

        # cat -n /xcatpost/mypostscript | tail -n 15
           221	run_ps postscript syncfiles
           222	# defaults-postscripts-end-here
           223	# postscripts-end-here
           224	c910f03c01p09
           225
           226	#save bad return code to /opt/xcat/xcatinfo
           227	if [ "$return_value" -ne "0" ]; then
           228	    grep 'POSTSCRIPTS_RC' /opt/xcat/xcatinfo > /dev/null 2>&1
           229	    if [ $? -eq 0 ]; then
           230	        sed -i "s/POSTSCRIPTS_RC=.*/POSTSCRIPTS_RC=1/" /opt/xcat/xcatinfo
           231	    else
           232	        echo "POSTSCRIPTS_RC=1" >> /opt/xcat/xcatinfo
           233	    fi
           234	fi
           235

**Comment by neo954** [comment]
At this point, I have no clue of the root cause.

**Comment by neo954** [comment]
The problem is in the line, `/xcatpost/getpostscript.awk |sed -e 's/<[^>]*>//g'|egrep -v '^ *$'|sed -e 's/^ *//' | sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' -e 's/&quot;/"/g' -e "s/&apos;/'/g" > /xcatpost/mypostscript`. 

This line is included in the kickstart file. `/xcatpost/getpostscript.awk` was called to get the initial `mypostscript`. xCAT server will response with an XML. The subsequence `sed` in the command above was used to strip all the XML tags.

**Comment by neo954** [comment]
On the compute node, the following command will get the initial `mypostscript`. Clearly, the `<xcatdsource>c910f03c01p09</xcatdsource>` was wrongly striped and included in the final file.

    # USEOPENSSLFORXCAT=yes XCATSERVER=10.3.1.9:3001 /xcatpost/getpostscript.awk
    <xcatresponse>
      <data>AUDITNOSYSLOG='0'
    </data>
      <data>export AUDITNOSYSLOG
    </data>
      <data>XCATCONFDIR='/etc/xcat'
    </data>
      <data>export XCATCONFDIR
    </data>
      <data>TFTPDIR='/tftpboot'
    </data>
      <data>export TFTPDIR
    </data>
      <data>PPCMAXP='64'
    </data>
      <data>export PPCMAXP
    </data>
      <data>PPCTIMEOUT='0'
    </data>
      <data>export PPCTIMEOUT
    </data>
      <data>VSFTP='n'
    </data>
      <data>export VSFTP
    </data>
      <data>CLEANUPXCATPOST='no'
    </data>
      <data>export CLEANUPXCATPOST
    </data>
      <data>IPMIRETRIES='3'
    </data>
      <data>export IPMIRETRIES
    </data>
      <data>NODESYNCFILEDIR='/var/xcat/node/syncfiles'
    </data>
      <data>export NODESYNCFILEDIR
    </data>
      <data>MAXSSH='8'
    </data>
      <data>export MAXSSH
    </data>
      <data>DHCPLEASE='43200'
    </data>
      <data>export DHCPLEASE
    </data>
      <data>TIMEZONE='America/New_York'
    </data>
      <data>export TIMEZONE
    </data>
      <data>XCATSSLVERSION='TLSv1'
    </data>
      <data>export XCATSSLVERSION
    </data>
      <data>XCATDEBUGMODE='2'
    </data>
      <data>export XCATDEBUGMODE
    </data>
      <data>POWERINTERVAL='0'
    </data>
      <data>export POWERINTERVAL
    </data>
      <data>PPCRETRY='3'
    </data>
      <data>export PPCRETRY
    </data>
      <data>SYSPOWERINTERVAL='0'
    </data>
      <data>export SYSPOWERINTERVAL
    </data>
      <data>ENABLEASMI='no'
    </data>
      <data>export ENABLEASMI
    </data>
      <data>SHAREDTFTP='1'
    </data>
      <data>export SHAREDTFTP
    </data>
      <data>CONSOLEONDEMAND='no'
    </data>
      <data>export CONSOLEONDEMAND
    </data>
      <data>DOMAIN='pok.stglabs.ibm.com'
    </data>
      <data>export DOMAIN
    </data>
      <data>DB2INSTALLLOC='/mntdb2'
    </data>
      <data>export DB2INSTALLLOC
    </data>
      <data>AUDITSKIPCMDS='ALL'
    </data>
      <data>export AUDITSKIPCMDS
    </data>
      <data>BLADEMAXP='64'
    </data>
      <data>export BLADEMAXP
    </data>
      <data>XCATIPORT='3002'
    </data>
      <data>export XCATIPORT
    </data>
      <data>SITEMASTER='10.3.1.9'
    </data>
      <data>export SITEMASTER
    </data>
      <data>IPMIMAXP='64'
    </data>
      <data>export IPMIMAXP
    </data>
      <data>INSTALLDIR='/install'
    </data>
      <data>export INSTALLDIR
    </data>
      <data>NAMESERVERS='10.3.1.9'
    </data>
      <data>export NAMESERVERS
    </data>
      <data>SSHBETWEENNODES='ALLGROUPS'
    </data>
      <data>export SSHBETWEENNODES
    </data>
      <data>SNSYNCFILEDIR='/var/xcat/syncfiles'
    </data>
      <data>export SNSYNCFILEDIR
    </data>
      <data>FORWARDERS='10.0.0.103'
    </data>
      <data>export FORWARDERS
    </data>
      <data>IPMITIMEOUT='2'
    </data>
      <data>export IPMITIMEOUT
    </data>
      <data>XCATDPORT='3001'
    </data>
      <data>export XCATDPORT
    </data>
      <data>FSPTIMEOUT='0'
    </data>
      <data>export FSPTIMEOUT
    </data>
      <data>USENMAPFROMMN='no'
    </data>
      <data>export USENMAPFROMMN
    </data>
      <data>DATABASELOC='/var/lib'
    </data>
      <data>export DATABASELOC
    </data>
      <data>DNSHANDLER='ddns'
    </data>
      <data>export DNSHANDLER
    </data>
      <data>ENABLESSHBETWEENNODES='YES'
    </data>
      <data>export ENABLESSHBETWEENNODES
    </data>
      <data>ZONENAME=''
    </data>
      <data>export ZONENAME
    </data>
      <data>NETWORKS_LINES=1
    </data>
      <data>export NETWORKS_LINES
    </data>
      <data>NETWORKS_LINE1='netname=10_0_0_0-255_0_0_0||net=10.0.0.0||mask=255.0.0.0||mgtifname=eth0||gateway=10.0.0.103||dhcpserver=||tftpserver=10.3.1.9||nameservers=||ntpservers=||logservers=||dynamicrange=||staticrange=||staticrangeincrement=||nodehostname=||ddnsdomain=||vlanid=||domain=||mtu=||disable=||comments='
    </data>
      <data>export NETWORKS_LINE1
    </data>
      <data>NODE=c910f03c01p10
    </data>
      <data>export NODE
    </data>
      <data>#get compute node ip address
    </data>
      <data>IPADDR=10.3.1.10
    </data>
      <data>export IPADDR
    </data>
      <data># get GROUP list
    </data>
      <data>GROUP='lpar,all,f03c01compute'
    </data>
      <data>export GROUP
    </data>
      <data>NFSSERVER='10.3.1.9'
    </data>
      <data>export NFSSERVER
    </data>
      <data>INSTALLNIC=''
    </data>
      <data>export INSTALLNIC
    </data>
      <data>PRIMARYNIC=''
    </data>
      <data>export PRIMARYNIC
    </data>
      <data>MASTER='10.3.1.9'
    </data>
      <data>export MASTER
    </data>
      <data>SERVICEGROUP=''
    </data>
      <data>export SERVICEGROUP
    </data>
      <data>SYSLOG=''
    </data>
      <data>export SYSLOG
    </data>
      <data>NODEROUTENAMES=''
    </data>
      <data>export NODEROUTENAMES
    </data>
      <data>MASTER_IP=10.3.1.9
    </data>
      <data>export MASTER_IP
    </data>
      <data>OSVER='rhels7.4'
    </data>
      <data>export OSVER
    </data>
      <data>ARCH='ppc64le'
    </data>
      <data>export ARCH
    </data>
      <data>PROFILE='compute'
    </data>
      <data>export PROFILE
    </data>
      <data>PROVMETHOD='rhels7.4-ppc64le-install-compute'
    </data>
      <data>export PROVMETHOD
    </data>
      <data>PATH=`dirname $0`:$PATH
    </data>
      <data>export PATH
    </data>
      <data>NODESETSTATE=boot
    </data>
      <data>export NODESETSTATE
    </data>
      <data>UPDATENODE=0
    </data>
      <data>export UPDATENODE
    </data>
      <data>NTYPE=compute
    </data>
      <data>export NTYPE
    </data>
      <data>MACMAC='ba:60:8e:8d:a4:03'
    </data>
      <data>export MACMAC
    </data>
      <data>MACADDRESS=ba:60:8e:8d:a4:03
    </data>
      <data>export MACADDRESS
    </data>
      <data>MONSERVER='c910f03c01p09'
    </data>
      <data>export MONSERVER
    </data>
      <data>MONMASTER='10.3.1.9'
    </data>
      <data>export MONMASTER
    </data>
      <data>OSPKGDIR='/install/rhels7.4/ppc64le'
    </data>
      <data>export OSPKGDIR
    </data>
      <data>OSPKGS='wget,ntp,nfs-utils,net-snmp,rsync,yp-tools,openssh-server,util-linux,net-tools'
    </data>
      <data>export OSPKGS
    </data>
      <data>NOSYNCFILES=1
    </data>
      <data>export NOSYNCFILES
    </data>
      <data>NICNODE=''
    </data>
      <data>export NICNODE
    </data>
      <data>NICIPS=''
    </data>
      <data>export NICIPS
    </data>
      <data>NICHOSTNAMESUFFIXES=''
    </data>
      <data>export NICHOSTNAMESUFFIXES
    </data>
      <data>NICTYPES=''
    </data>
      <data>export NICTYPES
    </data>
      <data>NICCUSTOMSCRIPTS=''
    </data>
      <data>export NICCUSTOMSCRIPTS
    </data>
      <data>NICNETWORKS=''
    </data>
      <data>export NICNETWORKS
    </data>
      <data>NICEXTRAPARAMS=''
    </data>
      <data>export NICEXTRAPARAMS
    </data>
      <data>NICDEVICES=''
    </data>
      <data>export NICDEVICES
    </data>
      <data>CFGMGR=''
    </data>
      <data>export CFGMGR
    </data>
      <data>CFGSERVER=''
    </data>
      <data>export CFGSERVER
    </data>
      <data># postscripts-start-here
    </data>
      <data># defaults-postscripts-start-here
    </data>
      <data>syslog
    </data>
      <data>remoteshell
    </data>
      <data>syncfiles
    </data>
      <data># defaults-postscripts-end-here
    </data>
      <data># postscripts-end-here
    </data>
      <data># postbootscripts-start-here
    </data>
      <data># defaults-postbootscripts-start-here
    </data>
      <data>otherpkgs
    </data>
      <data># defaults-postbootscripts-end-here
    </data>
      <data># postbootscripts-end-here
    </data>
      <xcatdsource>c910f03c01p09</xcatdsource>
    </xcatresponse>
    <xcatresponse>
      <serverdone></serverdone>
    </xcatresponse>

**Comment by neo954** [comment]
It seems the `xcatdsource` response was newly added by @robin2008 recently.

    $ grep xcatdsource ./xCAT-server/sbin/xcatd
                            $_->{xcatdsource}->[0] = $MYXCATSERVER unless ($_->{xcatdsource});
                        $response->{xcatdsource}->[0] = $MYXCATSERVER;
    $ git blame ./xCAT-server/sbin/xcatd | grep xcatdsource
    405ed14a20 xCAT-server/sbin/xcatd         (XU Bin          2017-08-02 15:33:42 +0800 2597)                         $_->{xcatdsource}->[0] = $MYXCATSERVER unless ($_->{xcatdsource});
    405ed14a20 xCAT-server/sbin/xcatd         (XU Bin          2017-08-02 15:33:42 +0800 2605)                     $response->{xcatdsource}->[0] = $MYXCATSERVER;

I will re-assign this bug to @robin2008.

**Comment by neo954** [comment]
This bug is cause by pull request #3547.

**Comment by robin2008** [comment]
Root cause:
when generating mypostscript content,  current script does not filter the non-content lines. 

I check existing codes, there only one place to filter the content by "egrep '<data>'" already, so we can follow it for other places.

Also check other *.awk which get content from MN,  not found such issues.

**Comment by robin2008** [comment]
Fix it by PR #3705

**Comment by robin2008** [comment]
@neo954 Could our daily autotest could be enhanced to find such issue?

**Comment by neo954** [comment]
I merged pull request #3705. I think this bug may affect xCAT 2.13.6 GA edition.

**Comment by neo954** [comment]
I will close this one.
