### ISSUE TITLE
[DEV] Callback message may hang at xcatd side

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#3698]
We encountered this problem while running bmc discovery for a large cluster (more than 2 thousand nodes). The child processes may hang at the end if  `xCAT::MsgUtils->message("I" , ...` is called. This is a general error of xcatd while redirecting the message from pipe to the client.

**Comment by chenglch** [comment]
After running some self scripts, the root cause is from the code logic of xcatd while handling communication between the socket pairs if multiple child processes exist.

Below is the code block that has race condition if child processes send the message back to the client at the same time. `relay_fds` is running in `immidiate` process and `convey_response` is running in child plugin processes.
```
sub relay_fds { # Relays file descriptors from pipes to children to the SSL socket
    my $fds        = shift;
    my $replyqueue = shift;
    my $goneclient = 0;
    my $collate    = (scalar @_ > 0 ? shift : 0);
    my @readyset   = $fds->can_read(1);
    my $rfh;
    my $rc = @readyset;
    my $text;

    # A PIPE signal might be received when run fd_retrieve from the plugin sub processors
    # This mostly happens when there are multiple plugins are called for certain command
    # So spkit the pipe error handle
    $pipeexpected = 1;
    foreach $rfh (@readyset) { # go through each child, extract a complete, atomic message
        my $line;
        my $resp;
        eval {
            $resp = fd_retrieve($rfh);
        };
        if ($@ and $@ =~ /^Magic number checking on storable file/) { # this most likely means we ran over the end of available input
            $fds->remove($rfh);
            close($rfh);
        } else {
            push @$replyqueue, $resp;
            print $rfh "nfin\n";
        }
    }
   ....
```

```
sub convey_response {
    my $resp = shift;

    # TODO: This is where the following will/may happen:
    # -Track transaction id
    # -Save output for deferred commands
    unless ($parent_fd) {
        build_response($resp);
        return;
    }
    unless ($resp) { return; }
    $pipeexpected = 1;

    #$resp = XMLout($resp,KeyAttr=>[], NoAttr=>1,RootName=>'xcatresponse');
    # sanitize the response, to avoid being killed by non-printable bytes
    #$resp =~ tr/\011-\177/?/c;
    # seeing if using utf-8 offloads potential issues to client terminal, it didn't
    store_fd($resp, $parent_fd);
    yield; # parent must get timeslice anyway before an ack could possibly return
    my $parsel = new IO::Select;
    $parsel->add($parent_fd);
    my $selbits = $parsel->bits;
    my $rsp;
    while ($selbits && ($rsp = select($selbits, undef, undef, 5))) { # block up to five seconds

        if ($quit) {    # Obey quit flag
            xexit 0;
        }
        if ($rsp == 0) {    # This means the filedescriptor was removed
            last;
        }
        if ($rsp < 0) {     # A signal caused select to skip out, do-over
            next;
        }

        # At this point, the only possibility is a positive return, meaning parent_fd requires attention of some sort
        $rsp = <$parent_fd>;
        if ($rsp) { # If data actually came in, last, otherwise, remove it from the IO::Select, but both should amount to the same thing
            last;
        } else {
            $parsel->remove($parent_fd);
            last;
        }
    }
    yield; # If still around, it means a peer process still hasn't gotten to us, so might as well yield
    $selbits = $parsel->bits;
}
```
Below is my guess.

I focus on the `convey_response` at first, after sending the response to `immidiate` process though `store_fd($resp, $parent_fd);`, it use a select to wait for the response and then read it `$rsp = <$parent_fd>;`. My test script always hangs here as the race condition of multiple child processes call the `read system call` and blocks.  When the write event from `print $rfh "nfin\n";` of `relay_fds` comes, one of the blocked read `system call` will be waked up. Unfortunately, in a multi-processes environment, `immidate` process may call the `print` multiple times and then the cpu switch to the child processes. Only one of the child processes may be waked up, so some of the wake up event made by writing pipe  is missing. ( I can't find detail document to explain why only one of blocked read `system call` is waked up but the other blocked read `system calls` are still waiting even though there are buffer to read from the pipe, **if anyone knows, could tell me if the guess is right or not**).

To handle this, previous xcat code use a select to check is it the right time to read from the $parent_fd pipe, it only decrease the probability but can not avoid it. Imaging that there are two child processes passed the select check , one call the read and then the pipe is empty, the other  child process is waiting for the write event. But if the write event is missing like the situation described above, there are always child processes waiting for the write event, then hangs.

**Comment by daniceexi** [comment]
@chenglch do you mean that the race condition won't happen if we add a ``yield`` sentence in the relay_fds->'foreach fs' loop, so that the child could get cpu to read the buffer?

**Comment by chenglch** [comment]
@daniceexi , no,  this won't help.  The block line is `$rsp = <$parent_fd>;`  as it is a block IO.

race condition:
1. multiple ( assume 2) child process reach `$rsp = <$parent_fd>;`, then block.
2. parent process get cpu and call `print $rfh "nfin\n";` multiple times (assume more than 2 times)
3. one of the child process get cpu, and read from $parent_fd. **(consume more than one write event)**  The other child process hangs as there are no write event to wake up.

**Comment by daniceexi** [comment]
@chenglch I meant to add a yield in the step 2 to avoid the multiple times to write to child processes.

**Comment by chenglch** [comment]
This also could not help resolve this race condition, as the parent process could also get the CPU very soon especially in SMP arch.
