### ISSUE TITLE
xcatprobe switch_macmap , does not display VLAN correctly for CumulusLinux

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3700]
Since we cannot currently display the VLAN correctly, we should just detect CumulusLinux OS and NOT print the wrong VLAN information instead of displaying it. 

At least it won't cause confusion until we figure out a way to support it...

**Comment by mattaezell** [comment]
The SNMP script on the Cumulus switch that provides the BRIDGE-MIB says:
> Note: just before the dotted decimal mac you need an FDB ID of 1

xCAT seems to want to use that as the VLAN directly.  I think technically that's supposed to be an index into another table, but maybe other vendors index that table using the VLAN number?

If you don't mind changing a python script on the cumulus switch, you can edit */usr/share/snmp/bridge_pp.py* (and restart snmpd) to get the behavior you are expecting.  It probably makes sense to open a support case with Cumulus to see if they are willing to make this change upstream (or if they have a better idea).

I walked the entire MIB, and I only see PVIDs on ports (not per-mac VLANs).

```
# diff -u bridge_pp.py.save20170816 bridge_pp.py
--- bridge_pp.py.save20170816   2017-08-16 22:42:18.274479219 -0400
+++ bridge_pp.py        2017-08-16 22:58:07.884116512 -0400
@@ -692,7 +692,7 @@
                    (qBridgeMIB, qBridgeMIBObjects,
                     dot1qTp, dot1qTpFdbTable,
                     dot1qTpFdbEntry, myindex,
-                    dot1qFdbId, fdbArray[mac]['macdec']),
+                    fdbArray[mac]['vlan'] or 0, fdbArray[mac]['macdec']),
                    fdbArray[mac][mystring])
     return None
 ```

**Comment by whowutwut** [comment]
Thanks @mattaezell ! @immarvin can you take a look at the above?

**Comment by immarvin** [comment]
hi @mattaezell ,thanks for your info.

@whowutwut , I think changing the script inside cumulus switch might not be acceptable for the upstream. We might need to look for the MIB on the VLAN numbers of the switch ports

**Comment by immarvin** [comment]
hi @whowutwut , I went though the MIB and cannot find the proper OID for mac/port-VLAN, is @cxhong familiar with the MIB stuff in the switches?

**Comment by cxhong** [comment]
yes, when I implemented this function,  I couldn't find any MIB associated with VLAN number.  Mellanox sx1410 and sx1400 both supported, but cumulus switch is not supported.  I agree with @immarvin , don't think  it's good idea to edit mib file.    for cumulus switch, we may need to find another method to get mac/port vlan.

**Comment by immarvin** [comment]
hi @cxhong , would you please contact the cumulus or mellanox staff to get some technical support? you can also mention the modification from @mattaezell to check whether they can adopt it, if not, maybe they can give us some advice. I remember that @whowutwut has the contact information of mellanox 

thanks
