### ISSUE TITLE
confignetwork error message enhancement

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3704]
From Victor's comments:
1. Going though the `confignetwork` and we see some new error messages, not able to really tell...

```sn02: [E]: Error: enP52p1s0f0 enP52p1s0f0 pair is invalid nic and nicdevice pair.
sn02: [E]: Error: enp1s0f0 enp1s0f0 pair is invalid nic and nicdevice pair.

```
Turns out what this means is that we should not define the `nicdevices.enP52p1s0f0`... can we make that error message more clear? We figured it out by playing with the options

2. This message should have `Error` .. so we can see it easily... and be consistent

```
sn02: [E]: configeth on sn02: Network object cn is not defined.

```
should be `[E]: Error:`

**Comment by whowutwut** [comment]
@bybai Perhaps something more direct for the first message...
```
sn02: [E]: Error: nicdevice.enp1s0f0 in not required. (only on vlan,bond?) 
```

**Comment by bybai** [comment]
Hi @whowutwut , Since this error message is not only for ethernet, it is a general error for all the nicdevice and its base nic device check, I enhanced the log error message in pull request #3710
