### ISSUE TITLE
investigate reason to cost 20 second for the discovery request to be matched in switch based discovery

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#3712]
why it will costs about 20 second for the discovery request to be matched?

**Comment by whowutwut** [comment]
This is not something in the xCAT code, but rather something in the OpenBMC framework.  I have talked to Brad about this on the phone late last week and he was going to update the issue: 
https://github.com/openbmc/openbmc/issues/1881

I don't think this is anything we can do to reduce this until they change something in the BMC...

**Comment by whowutwut** [comment]
@bybai Actually, maybe I posted this too fast without knowing the scenario...

Can you provide more details in your above testing...
1. Is this P9 Witherspoon with OpenBMC? 
2. Where do you see the 20 seconds....?

**Comment by bybai** [comment]
Hi @whowutwut ,
This task is duplicate with #3709 ;
1. It is not P9 witherspoon with openBMC, it is from switchdiscover;
2. During switch based node discovery, findme cost 20sec, so create #3709 to investigate the reason.
