### ISSUE TITLE
Add script to help analyze the the db subroutines based on the syslog output

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#3713]
* [ ] Enhance the command log from xcatd as `[ElapsedTime]` from command log is always 0 s.   
* [x] Read and parse the content from the end of xcat.log and command log
* [x] Calculate how much time is taken within the db subroutine for the executed command.
* [x] List the time to handle the SQL statement for the executed command. 
* [x] List how many db queries are cached or with cache hit.
The tasks below will be include in this sprint:
* [x] The total time costs for xCAT cmd, take nodeset as example, no SN take into account.
* [x] The db read/write time costs, read/write times, cache hit times.
* [x] Show case.

**Comment by daniceexi** [comment]
👍 We might find interesting points.

**Comment by whowutwut** [comment]
@chenglch Was there anything created after this work effort was completed? Anything stored in Box?  Can you forward to me if there is something...  I might have missed it in email.

**Comment by chenglch** [comment]
@whowutwut , I have put the analysis script and the result for commands in csv result in the pull request https://github.com/xcat2/xcat-core/pull/3899
