### ISSUE TITLE
Verify that SOL connection is stable on Supermicro Based Boston Servers

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3729]
Part of #3486, Verify that IPMI SOL is stable on Supermicro Based Boston servers . We experienced many issues with the SOL on the OpenPOWER P8 servers ...  

We need to ensure that on reboots , there's no issues with the SOL connection and that the console logs are consistently written into the logs.  

We have to reboot the server multiple time and have multiple connections into the rcons open and ensure that the logs are not interrupted in the `/var/log/consoles...` 

Assign to @chenglch, feel free to delegate

**Comment by chenglch** [comment]
I have tested `rcons` on `boston02` and cover the following scenarios:

- reboot `boston02` multiple times
- restart conserver and then check the console log
- run `rcons` from multiple clients

The SOL connection seems stable.

**Comment by whowutwut** [comment]
@chenglch One of the requirements is that the sol connection on reboot of the server still continues to work.. so we should see console logs to the file regarding the host shutdown and IPL back and boot,  If that is OK , let's close this.

**Comment by chenglch** [comment]
@whowutwut Yes, we could see the console logs in the scenario you mentioned.
