### ISSUE TITLE
[FVT]2.9.2 install xCAT 2.9.2 on AIX61 TL8 SP6 returns "SSL connect handshake problemserror"

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#373]
xCAT  2.9.2 
bash-3.2# lsxcatd -v
Version 2.9.2 (git commit 03d9972bf285ba805dfacb15986260c96a634822, built Tue Oct 27 04:04:28 CDT 2015)

Install xCAT on AIX6.1 TL8 SP6 node and get following error.
bash-3.2# nodels
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: SSL connect attempt failed because of handshake problemserror:00000000:lib(0):func(0):reason(0) at /opt/xcat/lib/perl/xCAT/Client.pm line 265.

**Comment by tingtli** [comment]
verified and close

**Comment by daniceexi** [comment]
Refer to the #364 for the fix.
