### ISSUE TITLE
Cumulus discovery does not work with MTMS

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#3730]
Eventually we want to use switch-based switch discovery, but for early verification I tried to use MTMS-based discovery.  The _documulusdiscovery_ script does not send a MTM, so MTMS-based discovery cannot work.  It's sending the MTM in the _vendor_ attribute:
https://github.com/xcat2/xcat-core/blob/2679d56b730d0f70ef73225b714580bc664d8277/xCAT/postscripts/documulusdiscovery#L56

In my original [draft](https://gist.github.com/mattaezell/f385baa5bdccf6f63145489f3c172da2), MTM was sent as mtm, not vendor.  Why was this changed @immarvin?

**Comment by immarvin** [comment]
hi @mattaezell , the logic in ``documulusdiscovery `` is designed and verified to discover cumulus switch follows the similar logic with switch based node discovery, the unit test does not covered MTMS baed discovery, you can create a PR on this, thanks

**Comment by mattaezell** [comment]
@immarvin I'll work on a simple PR for this tomorrow. I also noticed that sequential did not work (something about BMC addresses).  I now have switch-based switch discovery setup on our test cluster so this is less important.  Getting #3732 merged is higher priority.
Thanks

**Comment by immarvin** [comment]
hi @mattaezell , the PR #3732 has been merged. The documulusdiscovery requires further refinement according to PR https://github.com/xcat2/xcat-core/pull/3601/files#diff-4033787c6534fab1cd85faa4b7e30b4f,  I will do this in next sprint
