### ISSUE TITLE
Understanding the xCAT node properties of Virtual Machines when lifecycle is managed by xCAT

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3735]
This was brought up by myself and @gurevichmark months ago when @gurevichmark was fixing some issues with VMs.. 

It seems like some properties of the VM we allow to be changed by xCAT chdef command on the VM node object, but they really do not take effect on the running machine.  Also things like power off and on of a VM after changing the attributes do not take any effect...  like cpu count or memory. 

Could we have a table that documents the attributes related to VMs that can be set on a node definition and which one requires re-create of a VM and which ones take effect immediately.

**Comment by gurevichmark** [comment]
See issue #199 for more details. Especially the comment there from March 22, 2017

**Comment by bybai** [comment]
Work summary:
I enabled SR-IOV and defined VM using the VF pci.I think the environment is enough for code development. My next work is to look into xCAT command to manage this VM.
For the environment problem, in this hypervisor frame45cn02,`ibstat mlx5_0` state is down, if there is IB switch in this environment, should log into the IB switch and enable virtual functions + restart the subnet manager. So that the state can become active, and we can test VM connect to hypervisor through IB.   
1. Eabled SR-IOV on the MLNX_OFED driver on hypervisor frame45cn02:
```
]# lspci | grep -i mellanox
0000:01:00.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4]
0000:01:00.1 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4 Virtual Function]
0000:01:00.2 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4 Virtual Function]
0000:01:00.3 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4 Virtual Function]
0000:01:00.4 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4 Virtual Function]
0008:01:00.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4]

]# virsh dumpxml frame45cn02v1
...........................................
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <driver name='vfio'/>
      <source>
        <address domain='0x0000' bus='0x01' slot='0x00' function='0x1'/>
      </source>
      <alias name='hostdev0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </hostdev>
...............................................
```
2.  Added one of the PCI device to the VM frame45cn02v1:
```
]# lspci |grep Mel
00:05.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4 Virtual Function]
]# ip addr show ib0
3: ib0: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 1024
    link/infiniband 80:00:00:27:fe:80:00:00:00:00:00:00:11:22:33:44:77:66:77:01 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
```

**Comment by bybai** [comment]
Discussed this task in last Friday China scrum meeting:
Since the develop environment was ready, this task should be closed. Opened new task #3893 to trace support SRIOV development work.
