### ISSUE TITLE
[FVT]:updatenode still return 0 when syncfile does not exist.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#3737]
updatenode still return 0 when syncfile does not exist.
The steps to reproduce
```
1. mkdir -p /install/custom/install/rhels7.3/
2. echo "/tmp/non-existent -> /etc/motd" > /install/custom/install/rhels7.3/booboo.synclist
3. chdef -t osimage -o rhels7.3-ppc64-install-compute synclists=/install/custom/install/rhels7.3/booboo.synclist
4. updatenode c910f02c01p23 -F
[root@c910f02c01p22 /]# updatenode c910f02c01p23 -F
c910f02c01p23: rsync: link_stat "/tmp/non-existent" failed: No such file or directory (2)
c910f02c01p23: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
File synchronization has completed for nodes.
[root@c910f02c01p22 /]# echo $?
0
```

**Comment by zet809** [comment]
hi, @bybai , will you pls help to take a look at this issue? Thx!

**Comment by bybai** [comment]
This is not high priority, will look at it in next sprint or else. Thx.

**Comment by hu-weihua** [comment]
In rhels6.9+ppc64, except above problem, there is below problem too.  using the same steps, the output of ``updatenode`` is:

    [root@c910f02c01p13 autotest]# cat /tmp/updatenode.F.out
    There were no syncfiles defined to process. File synchronization has completed.

It does not make sense.

**Comment by robin2008** [comment]
updatenode will call xdcp to do the file sync, and it will return error.
```
xdcp sn02 --nodestatus -F /tmp/abc.lst
sn02: Remote_command_failed, error_code=23
sn02: rsync: link_stat "/tmp/non-existent" failed: No such file or directory (2)
sn02: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
```

updatenode should handle the error and set the return code accordingly.

**Comment by robin2008** [comment]
Fix it by PR #3816,  when some nodes are failed,  the "buildnodestatus" method will fill the failed nodes into @::FAILEDNODES

**Comment by robin2008** [comment]
And it might require more wide discussion.  

Maybe the existing design is the right:
- the return code of updatenode is only to response the updatenode operation is triggered successfully or not.
- but the operation result for each node should be got from the DB (updatestatus)

If it is, then we need modify our test case for it instead to apply the PR #3816

**Comment by robin2008** [comment]
@hu-weihua 

For your comments in https://github.com/xcat2/xcat-core/issues/3737#issuecomment-324543420
I suspect it is using the wrong osimage name there. For example,  on that ppc64 environment, the osimage which current CN using is not the one we combine <os>-<arch>-install-compute

Better to use "provmethod" to get current using osimage name as we already switched to use the new mode to define the osimage.

If the osimage name is right,  it might be a timing issue as after you set the synclists for osimage, and then run updatenode, it cannot get the attribute from the right osimage.
