### ISSUE TITLE
switch-based switch discovery find switch with wrong name

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#3741]
We have the following setup:
```
         +-----------------+
         |tundra-ethsw-core|
         +-----------------+
          |   |         |
      mgmt|   |uplink   |
          |   |         |
 +----------------+     |
 |tundra-ethsw-inf|     |uplink
 +----------------+     |
                |       |
            mgmt|       |
                |       |
              +-----------------+
              |tundra-ethsw-r0c0|
              +-----------------+
```
If I configure them correctly, things work as expected:
```
# lsdef tundra-ethsw-inf|egrep switch=\|switchport
    switch=tundra-ethsw-core
    switchport=Eth1/4
# lsdef tundra-ethsw-r0c0|egrep switch=\|switchport
    switch=tundra-ethsw-inf
    switchport=swp32
```
```
xcat.discovery.switch: (8c:ea:1b:aa:aa:aa) Found node: tundra-ethsw-r0c0
```

If I change tundra-ethsw-r0c0 to a bogus switchport (swp320), then it discovers as tundra-ethsw-inf.
```
xcat.discovery.switch: (8c:ea:1b:aa:aa:aa) Found node: tundra-ethsw-inf
```
The issue is that tundra-ethsw-core 'sees' tundra-ethsw-inf and all of its children through Eth1/4

**Comment by zet809** [comment]
Hi, @mattaezell , are the mgmt port and uplink port of tundra-ethsw-inf the same port? If yes, then there will be such issue. 
If not, it means tundra-ethsw-inf is matched to port "Eth1/4" of tundra-ethsw-core, but the MAC address of tundra-ethsw-r0c0 will show on other port(may be a XGE port) that connect to the uplink port of tundra-ethsw-inf, it won't be mapping to `tundra-ethsw-inf`, right?

**Comment by immarvin** [comment]
hi @zet809 , would you please take a look at this?

**Comment by mattaezell** [comment]
Sorry for the noise, my hardware connection documentation was wrong.  Eth1/4 is the uplink, not the management port. tundra-ethsw-inf's management port connects to itself.
```
         +-----------------+
         |tundra-ethsw-core|
         +-----------------+
              |         |
    +--+      |uplink   |
mgmt|  |      |         |
 +----------------+     |
 |tundra-ethsw-inf|     |uplink
 +----------------+     |
                |       |
            mgmt|       |
                |       |
              +-----------------+
              |tundra-ethsw-r0c0|
              +-----------------+
```
