### ISSUE TITLE
[fvt]2.13.7 reventlog clear could not available now 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#3745]
This issue is related with issue #3727 
Build:
[root@c910f03c11k08 ~]# lsxcatd  -v
Version 2.13.7 (git commit 940a0b6dd4f3945021ee9aa516b67df487e6d78e, built Tue Aug 22 06:15:44 EDT 2017)
[root@c910f03c11k08 ~]#
Env:
[root@c910f03c11k08 ~]# uname  -a
Linux c910f03c11k08 4.10.0-11.el7.ppc64le #1 SMP Mon Apr 17 14:21:19 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux
How to reproduce:
```
reventlog p9euh01 clear [Tue Aug 22 13:20:48 2017]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
Command reventlog is not available now!
-------> the command could not available now.
CHECK:rc == 0   [Pass]
CHECK:output =~ p9euh01\s*:\s*clear|SEL cleared [Failed]
```

**Comment by whowutwut** [comment]
I think in this scenario, we should also request that a RC of non zero is returned when the command is not yet available. This would help FVT testcase not have special processing....

**Comment by hu-weihua** [comment]
Have verified, thanks @xuweibj 

```
------START::reventlog_clear::Time:Thu Sep 21 09:07:03 2017------

RUN:reventlog p9euh01 clear [Thu Sep 21 09:07:03 2017]
ElapsedTime:2 sec
RETURN rc = 0
OUTPUT:
p9euh01: clear
CHECK:rc == 0   [Pass]
CHECK:output =~ p9euh01\s*:\s*clear|SEL cleared [Pass]
```
