### ISSUE TITLE
[PCM] The merge function of updatenode cannot work with special charcharacters like '+'

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#3749]
when special characters are used in order to enable NIS authentication in /etc/passwd file as show below:
+@sysadmins::::::
+@p8users::::::
+:*:::::/sbin/nologin

After running updatenode computenode -F, will sync the passwd to CN from passwd.merge file. However, if we run the command  again, it creates duplicate entries of the above line plus few 2-3 users to CN.  Run the command third time, it will triplicate those line in passwd in CN and so on.

**Comment by robin2008** [comment]
the merge operation is handled by "/opt/xcat/share/xcat/scripts/xdcpmerge.sh"
In this script,  it use "grep -E",  but it not handle the special char when removing the duplicate entries, so those line will be always there.

For example,  I add some print info in the script and run as below to print the grep command:
./xdcpmerge.sh `pwd` /root/cfmdir/etc/passwd.merge:/etc/passwd
grepcmd=grep -v -E '^(+@p8users|adit|advocate|lsfadmin|mysql|nscd|nslcd|pcmadmin)' /var/xcat/node/syncfiles/org/etc/passwd > /var/xcat/node/syncfiles/org/etc/passwd.nodups

'+' here is special char for Regular Expression,  so we need handle it.

**Comment by whowutwut** [comment]
Is this a bug or a feature that was never supported/or tested?

**Comment by whowutwut** [comment]
Evidently this severity was raised internally on the RTC issue... .. @robin2008 Is there an ETA?

**Comment by robin2008** [comment]
As we only need to handle the id part (1st part in each line, delimited by ':'),  there is no many special chars.

Get some information from web:
```
/etc/passwd : add the following line:
+::::::
This will autorise all the users present in the server map to connect to the client. We can refine these authorizations using the symbols + and - to authorize or forbid access to the client. In order to forbid the guest user, you would add the line
-guest::::::
The fields you don't want to modify, should remain empty It is possible however to add more:
+me::::::/bin/ksh
The user "me" will use ksh instead of his/her usual shell (which is defined in /etc/passwd of the NIS server).
As a final important note, I want to add that NIS perfectly supports the use of netgroups3
+@sysadmins:::::::
```

So we need to handle the first char if it is `+` or `-`

**Comment by robin2008** [comment]
This customer is using SCF 4.2.2,  which is use xCAT `2.12.3-pcm` branch

So we need at least merge this fix to below branch:
```
2.12.3-pcm (SCF 4.2.2)
2.12
2.13-pcm (SCF 4.3)
master (trunk,  for now 2.13.x)
```
SCF team will get our patch and release their official path to customer.

**Comment by robin2008** [comment]
commit into 2.12.3-pcm by https://github.com/xcat2/xcat-core/pull/3777

**Comment by robin2008** [comment]
commit into 2.12.3-pcm by PR #3778
