### ISSUE TITLE
[openbmc]rflash support for "association" attibute

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3752]
A new "association" attribute is being introduced by the OpenBMC team.
It will be used to indicate which image is "currently" active. The Priority of 0 attribute will now indicate the image that "will become active on the next reboot".

There will be 3 different "active" states - "active", "currently active", "will be active on the next reboot"
Currently using `(*)` in the output of the `--list` to indicate which image is "currently active". Will need another marker to indicate "will become active on the next reboot".

Delete action will not be allowed on the image marked with "association" attribute.

**Comment by whowutwut** [comment]
Are we planning to support all these new functions in the initial support for `rflash` or should we ensure the mininum set is working before we add on these new things? Or would we not be able to support everything without these new pieces?

**Comment by gurevichmark** [comment]
This "association" attribute will only be used to properly display output of `rflash --list`. Without it, we can not indicate which image in the list is "currently active".

**Comment by zet809** [comment]
Hi, @gurevichmark , what is the different between "active" and "currently active"?

**Comment by gurevichmark** [comment]
"Currently active" means this firmware image is running on the machine. "Active" is more like a "Standby", it is an image that has been written to flash memory, after an upload, and it will survive a reboot. There can be several images in "Active" state, but only one in "Currently active".

**Comment by whowutwut** [comment]
Let me take a stab at maybe a external for the 3... 
```
Active (*)  <-- Currently Active, cannot be Deleted 
Active (+) <--- Pending , will be active on next boot  (can this be deleted?) 
Active   <--- Active firmware that is in the BMC, can be deleted 
```

**Comment by zet809** [comment]
Get it, thx @gurevichmark and @whowutwut 

Some small concerns, 
1. it is OK for the implementation of the RESTful interface, but from the user point of view, do they really want to know so many images?
For example, when we flash firmware, we'd like to enable it automatically. And recover to the original one if there are issues for the latest version. 
2. How may firmware file can be stored on BMC? The uploaded firmware will be there until user delete it manually? Will the upload function report the message that no enough space if upload failed?

**Comment by gurevichmark** [comment]
@zet809 My understanding is:
1. Perhaps this will help the administrator with staging the update. They can upload the images to all the nodes in the cluster, but then wait until some upgrade maintenance window in the future to "activate" and reboot. This way they can verify that all the nodes have the correct update file listed with `-l` flag. Then use `-a` flag to activate and verify all nodes have the update activated and marked as "pending". Finally they can reboot the nodes and see the update in "currently active" state.

2. It is not known to me how many images can be stored on BMC. If image was never activated (still in "Ready" state) it can be manually removed by the user. Image in "pending" state can also be manually removed by the user. Image in "Currently active" state can not be removed by the user. I do not know what will happen if there is no space left to upload the image. I imagine the REST call will fail, but this is something we have to test.

**Comment by zet809** [comment]
hi, @gurevichmark , the PR #3895 seems to be used to enable update BMC firmware. So have this task be fixed? I will move this task to 2.13.8, pls move back and close it if it have been fixed. Thx!

**Comment by gurevichmark** [comment]
This is still a valid issue. We are waiting for the OpenBMC team to add their support.
Do not expect this to be done this week, so will keep this issue in 2.13.8

**Comment by zet809** [comment]
hi, @whowutwut , it seems this issue have been fixed(current *, next +), shall we close this issue?

**Comment by whowutwut** [comment]
@zet809 Thanks, I just linked in the Pull Request.
