### ISSUE TITLE
Virtual Machine cannot power on due to xCAT Plugin Bug around graphics code 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3769]
Opening on behalf of Zhibao Hu

```
[root@ems6 bin]# rpower essio61-vm on
Error: kvm plugin bug, pid 8711, process description: 'xcatd SSL: rpower to essi
o61-vm for root@localhost: kvm instance' with error 'Can't call method "setAttri
bute" on an undefined value at /opt/xcat/lib/perl/xCAT_plugin/kvm.pm line 1403.
' while trying to fulfill request for the following nodes: essio61-vm
```

So looking quickly at this code, I modified line 1403 to check if graphics is defined.    I think this is for VNC password... 
```
1398     my $parseddom = $parser->parse_string($xml);
1399     my ($graphics) = $parseddom->findnodes("//graphics");
1400     if ($confdata->{vm}->{$node}->[0]->{vidpassword}) {
1401         $graphics->setAttribute("passwd", $confdata->{vm}->{$node}->[0]->{vidpassword});
1402     } else {
1403         if (defined($graphics)) {
1404             $graphics->setAttribute("passwd", genpassword(20));
1405         }
1406     }
``` 

With this patch , we are able to get the VM to power up.  

However, what I don't understand is what causes the `//graphics` entry to be inserted into the XML data.  Any wouldn't we hit this in our testing? @hu-weihua ? There's nothing about `vidpassword` either in the node... 
```
[root@ems6 ~]# lsdef essio62-vm | grep vidpass
[root@ems6 ~]#
```

So maybe the better fix is to wrap the graphics check at line 1400 and cover both the if and else case.....

Assign to @bybai  to investigate and create a better fix.

**Comment by bybai** [comment]
Hi @whowutwut ,
`//graphics` entry is added into xCAT essio61-vmby `mkvm` command. We can also `chtab node=vm1 vm.vidpassword=abc123` to add `vidpassword` into `vm` table, all these 2 commands can make our kvm.pm code line from 1400 to 1405 work well.
In their env, there is no `graphics` entry for essio61-vm , it can reproduce the error. 
If added as following, the `rpower` for can work. If the vm essio61-vm is created by xcat `mkvm`, this error can not be produced. I think vm essio61-vm xml data in kvm_nodedata is not created by xCAT, so there is no `graphics` entry. From code perspective, if code check `$graphics` defined, it is more strong. I will commit a pull request here.
 ```
    if ($confdata->{vm}->{$node}->[0]->{vidpassword}) {
        $graphics->setAttribute("passwd", $confdata->{vm}->{$node}->[0]->{vidpassword});
    } else {
        if(defined($graphics)) {         ===========> add this line
            $graphics->setAttribute("passwd", genpassword(20));
        }
    }
    if(defined($graphics)) {     =============> add this line
        $graphics->setAttribute("listen", '0.0.0.0');
    }
```

**Comment by bybai** [comment]
Hi @whowutwut ,
If there is no `graphics` entry in `kvm_nodedata`, the `wcons` command will be affect too.  So we recommend user to add `graphics` entry for the node in `kvm_nodedata` as following. For this issue, I will add "if  $graphics is not defined print warning message, in both rpower and wcons related code" in later code fix.
```
    <graphics type='vnc' port='5900' autoport='yes' listen='0.0.0.0'>
    </graphics>
```

**Comment by whowutwut** [comment]
@bybai  So we automatically always set up the graphics attribute?  

1. What happens if there's no VNC server that plans to ever by used by the VM?
2. What VNC service is started? What's the difference between that VNC and rcons session?  Is it just a graphic desktop with a console? 
3. Without all the X11 packages and desktop, the VM VNC session would be quite bare.. is this useful?
 
Why not only set it if vidpassword is provided?  I guess in the code, we generate a vidpassword if it's not provided in the passwd table, how is this password send back to the user, do we add it into the node definition of the node object? 

In any case... I think we also need to test the graphics object is defined here in the if clause... that's why i suggested maybe wrapping it around the whole piece of code at line 1400... 
```
 if ($confdata->{vm}->{$node}->[0]->{vidpassword}) {
       $graphics->setAttribute("passwd", $confdata->{vm}->{$node}->[0]->{vidpassword});
   }
```

**Comment by bybai** [comment]
Hi @whowutwut ,
Yes, we automatically always set up the graphics attribute.
1. If there is no VNC server that plans to ever by used by the VM, except `wcons`, other command can work well.
2. `rcons` use text, rcons provides access to a single remote node serial console, using the out-of-band infrastructure for the node, while `wcons` is front-end in an xterm session for each console.
3. I remember, we use `wcons` for some servers if serial console does not work well. In some situation, it is useful.

`vidpassword` is saved in `vm` table. I think in the code, `graphics` is one of the default label. If there is no `vidpassword` configured in `vm` table, we generate a vidpassword. It is not in `passwd` table. It is not in the node definition of the node object.  After `mkvm`, `vidpassword` is added into `graphics` label of `kvm_nodedata` table.
```
(optional)For monitoring and access the VM with vnc client, set vidpassword value:
chtab node=vm1 vm.vidpassword=abc123
```
After `mkvm`, it is added into `kvm_nodedata` table:
```
<graphics autoport=""yes"" listen=""0.0.0.0"" password=""abc123"" type=""vnc"" />

**Comment by bybai** [comment]
For this issue fix, I think all `$graphics` should be checked if it is defined and print out warning, execpt line 1400 around.

**Comment by whowutwut** [comment]
Thanks @bybai  Can you make that fix mentioned above, it would help our code be more robust.   How did ESS Team hit the problem with mkvm command?  If they created the VM via xCAT, it should not be missing graphics....?

**Comment by bybai** [comment]
@whowutwut , If ESS team used `mkvm` command to create VMs, they cannot hit this problem, it should not be missing graphics.
