### ISSUE TITLE
Pick up skills for large cluster tunning

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3790]
Pls reference https://sourceforge.net/p/xcat/wiki/Hints_and_Tips_for_Large_Scale_Clusters/
Give out the suggestion what shall be modified for the configuration in CORAL cluster.
Output:
    The document about the suggested configuration.

**Comment by zet809** [comment]
Move to next release.

**Comment by robin2008** [comment]
Addressed by https://github.com/xcat2/xcat-core/pull/5038
