### ISSUE TITLE
Discovery does not start running chain command because mac address NOIP....

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3792]
I've been seeing lots of people get hung up on this issue, so much so that I immediately know the answer...   which is not good....

 @ralphbellofatto brought this up to my attention today and it's difficult for users to understand the problem here...  

So they are re-discovering a node and it sits in genesis looping, can't continue... 
```
[Mon Aug 28 14:28:28 2017]<166>Aug 28 14:28:27 xcat.genesis.doxcat: The destiny=discover, destiny parameters=discover
```

The chain attribute is: `chain=runcmd=bmcsetup,standby` but it never gets to running bmcsetup. 

The mac is: `mac=70:e2:84:14:29:2b!*NOIP*`

So the reason for this is makehosts/makedhcp is NOT run. 

@zet809 I thought you said it would automatically run in discovery?? 

* So how can we better confirm that makedhcp is automatically run?
* What is the missing step that causes us to get hung up on this so much? Reproduce this... 
* Is there a way to improve the logging? 
* Does xCAT probe find it? Can it be used during discovery to find problems to resolve?

**Comment by zet809** [comment]
1. We can use `makedhcp -q <node>` to check the DHCP configuration for a node.
2. Have him run 'makedns <pre-defined-node>' before starting hardware discovery?
3. Yes, we can enhance the log to report the error configuration. Updated in PR #3806
4. Yes, this error can be checked by `xcatprobe discovery -c` to do pre-check before start hardware discovery.

**Comment by zet809** [comment]
Hi, @whowutwut , with PR #3806, I think we can close this issue, what is your idea?

**Comment by whowutwut** [comment]
Sure, this one is more difficult for me to re-produce right now, so let's close and see if anything comes up during testing.
