### ISSUE TITLE
[FVT]:confignetwork still configures networks and return 0 even the configuration values are not correct

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#3794]
xCAT 2.13.6
The steps to reproduce
```
1. chdef c910f04x12v04 nicips.eth2= nictypes.eth2= nicnetworks.eth2= nicips.eth1= nictypes.eth1= nicnetworks.eth1=
2. mkdef -t network -o 30_5_0_0-255_255_0_0 net=30.5.0.0 mask=255.255.0.0
    mkdef -t network -o 40_5_0_0-255_255_0_0 net=40.5.0.0 mask=255.255.0.0
3. chdef c910f04x12v04 nicdevices.br22= nicdevices.br33= nictypes.br22=bridge nictypes.br33=bridge nicnetworks.br22=30_5_0_0-255_255_0_0 nicnetworks.br33=40_5_0_0-255_255_0_0 nicips.br22=30.5.106.8 nicips.br33=40.5.106.8 nicdevices.bond0.2=bond0 nicdevices.bond0.3=bond0 nictypes.bond0.2=vlan nictypes.bond0.3=vlan nictypes.bond0=bond nictypes.eth2=ethernet nictypes.eth1=ethernet nicdevices.bond0="eth2|eth1"
4. updatenode c910f04x12v04 -P confignetwork
```
Since there is no nicdevices is set, configtnetworks should return error message and return none zero.

**Comment by robin2008** [comment]
Better to describe your idea about your case.
BTW:  empty bridge is legal configuration in some case.  What's your concern about "no nicdevices is set"?

**Comment by tingtli** [comment]
As i discussed with Yuan, whennicdevices is not set, confignetworks should return error since it is a required option for configuring a network bridge.

**Comment by robin2008** [comment]
Not sure of it,  in some case, for example,  to setup a host-only bridge on a VM hypervisor.

**Comment by tingtli** [comment]
@bybai 
Another configuration is as follows. by design, with following configuration, since nictypes is empty, confignetwork should return error directly. But in fact, it configures cn.
```
chdef c910f03c11k14 nicdevices.br22=bond0.2 nicdevices.br33=bond0.3 nictypes.br22= nictypes.br33= nicnetworks.br22=30_5_0_0-255_255_0_0 nicnetworks.br33=40_5_0_0-255_255_0_0 nicips.br22=30.5.106.8 nicips.br33=40.5.106.8 nicdevices.bond0.2=bond0 nicdevices.bond0.3=bond0 nictypes.bond0.2=vlan nictypes.bond0.3=vlan nictypes.bond0=bond nictypes.eth0=ethernet nictypes.eth1=ethernet nicdevices.bond0="eth0|eth1"
```

**Comment by bybai** [comment]
@tingtli , 
1, If nictypes is not set, code should return 1, and the related nic should not be configured, other nics will be configured as design.
2, If nicdevices partially configured in nics table, confignetwork will configure this partial parts. 

For this issue, I will reproduce it, and look into it if it is as designed or not.

**Comment by bybai** [comment]
Verified in autotest env.
