### ISSUE TITLE
[Performance] Refresh xCAT 2.13 performance baseline to fill the real result

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#3797]
1, Refresh the test result based on 2.13.7 
2, Using the physical server environment (CORAL silmuation)
3, Add the performance data for performance base line.

**Comment by zet809** [comment]
Pls collect the performance data about:
* [ ] bmcdiscover performance data
* [ ] switch SNMP access performance data
* [ ] hardware discovery performance data

**Comment by robin2008** [comment]
Updated result in Box:
https://ibm.box.com/s/u9po2pi2hjows9dhihz6evhvik0x670f
