### ISSUE TITLE
discovery enhancement:  discovery performance data in scaling environement

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3800]
1. obtain the performance data of switch based discovery in the simulation scaling environment
2. document the steps of scaling simulation environment setup

**Comment by immarvin** [comment]
The steps:
1. stop xcatd on MN
2. run 100 docker containers as nodes to discover
3. start xcatd on MN and start timing
4. wait for all the nodes are discovered and stop timing

The result:
real	4m53.996s
user	3m19.177s
sys	1m27.286s

**Comment by daniceexi** [comment]
Good progress. 
* I recommend to add a chain task to make sure the discovery has been done completely and entered the next task in the chain.  We need to make sure all 100 nodes have got into next task.
* Also I'd like to see the time consuming data when handling a discovery request.
* Do more test in loop to test the stability is also recommended.

**Comment by immarvin** [comment]
The performance data for discovery against 500 nodes, 5 switches with 100 ports:


real	45m7.351s
user	24m23.802s
sys	9m57.316s

**Comment by immarvin** [comment]
The stuff to build docker image of the nodes to discover: https://github.com/immarvin/discovery_scaling_simulator

The Docker image of the nodes to discover:
https://hub.docker.com/r/xcat/discovery_scaling_simulator/builds/

**Comment by immarvin** [comment]
looked into cluster.log of the scaling and have the following points to enhance the discovery performance:
1. remove the ``sleep 2`` at the end of ``nodediscover.pm`` after the node discovery is finished
2. replace the snmp::getnext  with snmp::bulkwalk in the following code slice in MacMap.pm:
````
876         # my $mactoindexmap = walkoid($session,'.1.3.6.1.2.1.17.4.3.1.2');
877         my $mactoindexmap = bulkwalkoid($session, '.1.3.6.1.2.1.17.7.1.2.2.1.2', silentfail => 1, verbose => $self->{show_verb    ose_info}, switch => $switch, callback => $self->{callback});
878         unless (defined($mactoindexmap)) { #if no qbridge defined, try bridge mib, probably cisco
879               #$mactoindexmap = walkoid($session,'.1.3.6.1.2.1.17.7.1.2.2.1.2');
880             $mactoindexmap = bulkwalkoid($session, '.1.3.6.1.2.1.17.4.3.1.2', ciscowarn => $iscisco, verbose => $self->{show_v    erbose_info}, switch => $switch, callback => $self->{callback});
````

Some performance comparation in:
````
time snmpbulkwalk -v 3 -u xcatadmin -l authPriv -a sha -x DES -A xcatpassw0rd -X xcatpassw0rd virtswitch1 .1.3.6.1.2.1.17.7.1.2.2.1.2

real	0m11.430s
user	0m0.235s
sys	0m0.076s


# time snmpwalk -v 3 -u xcatadmin -l authPriv -a sha -x DES -A xcatpassw0rd -X xcatpassw0rd virtswitch1 .1.3.6.1.2.1.17.7.1.2.2.1.2|wc -l
10436

real	0m16.995s
user	0m0.843s
sys	0m0.387s

[root@c910f03c05k21 ~]# time snmpbulkwalk -v 3 -u xcatadmin -l authPriv -a sha -x DES -A xcatpassw0rd -X xcatpassw0rd virtswitch2 .1.3.6.1.2.1.17.7.1.2.2.1.2 |wc -l
21951

real	0m47.412s
user	0m0.495s
sys	0m0.044s
[root@c910f03c05k21 ~]# time snmpwalk -v 3 -u xcatadmin -l authPriv -a sha -x DES -A xcatpassw0rd -X xcatpassw0rd virtswitch2 .1.3.6.1.2.1.17.7.1.2.2.1.2 |wc -l
21951

real	1m2.465s
user	0m1.919s
sys	0m0.707s

````

**Comment by immarvin** [comment]
after change the method to read macmap table with ``ssh``:

refresh_switch virtswitch13 ElapsedTime:3 sec
refresh_switch virtswitch5 ElapsedTime:3 sec
refresh_switch virtswitch3 ElapsedTime:3 sec
refresh_switch virtswitch32 ElapsedTime:3 sec
refresh_switch virtswitch54 ElapsedTime:3 sec
refresh_switch virtswitch33 ElapsedTime:3 sec
refresh_switch virtswitch34 ElapsedTime:3 sec
refresh_switch virtswitch12 ElapsedTime:3 sec
refresh_switch virtswitch51 ElapsedTime:3 sec
refresh_switch virtswitch52 ElapsedTime:3 sec
refresh_switch virtswitch53 ElapsedTime:4 sec
refresh_switch virtswitch35 ElapsedTime:4 sec
refresh_switch virtswitch14 ElapsedTime:4 sec
refresh_switch virtswitch55 ElapsedTime:4 sec
refresh_switch virtswitch15 ElapsedTime:4 sec
refresh_switch virtswitch31 ElapsedTime:4 sec
refresh_switch virtswitch1 ElapsedTime:4 sec
refresh_switch virtswitch11 ElapsedTime:4 sec
refresh_switch virtswitch43 ElapsedTime:6 sec
refresh_switch virtswitch25 ElapsedTime:6 sec
refresh_switch virtswitch22 ElapsedTime:6 sec
refresh_switch virtswitch45 ElapsedTime:6 sec
refresh_switch virtswitch24 ElapsedTime:7 sec
refresh_switch virtswitch4 ElapsedTime:7 sec
refresh_switch virtswitch44 ElapsedTime:7 sec
refresh_switch virtswitch41 ElapsedTime:7 sec
refresh_switch virtswitch42 ElapsedTime:7 sec
refresh_switch virtswitch23 ElapsedTime:7 sec
refresh_switch virtswitch2 ElapsedTime:7 sec
refresh_switch virtswitch21 ElapsedTime:7 sec
total refresh_switch ElapsedTime:7 sec

**Comment by immarvin** [comment]
``ssh`` based refresh_switch against 5 switches:
refresh_switch virtswitch1 ElapsedTime:1 sec
refresh_switch virtswitch3 ElapsedTime:1 sec
refresh_switch virtswitch5 ElapsedTime:1 sec
refresh_switch virtswitch4 ElapsedTime:1 sec
refresh_switch virtswitch2 ElapsedTime:1 sec
total refresh_switch ElapsedTime:2 sec

**Comment by immarvin** [comment]
The discovery data for 200 nodes , 5 cumulus switches with average 10000 mac entries:

real	3m9.437s
user	2m2.611s
sys	1m12.677s

**Comment by immarvin** [comment]
encountered a random issue  https://github.com/xcat2/xcat-core/issues/3920  for 500 nodes
