### ISSUE TITLE
xCAT 2.13.6 released, but milestone 2.13.6 still has open issues

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3801]
xCAT-2.13.6 is already released, however the milestone `2.13.6` still contains open issues. Not only that, some of the issues and PRs in that milestone were closed **after** the 2.13.6 release, technically making them part of the 2.13.7 release but still showing up in the 2.13.6 milestone, which gives an incorrect idea about which releases fixed which bugs.

Please correct this (and milestones of older releases still containing open tickets/PRs).

**Comment by zet809** [comment]
Thx @samveen , will correct this.

**Comment by whowutwut** [comment]
Yes! Thank you for bringing this up! :+1:  Will remind the team to move their issues...

**Comment by zet809** [comment]
Thx, @samveen , I will close this issue since there is no issue opened for 2.13.6.
For 2.13.7, we have opened #3956 to trace we closing all issues for 2.13.7. 
Thx again for the reminder.
