### ISSUE TITLE
[fvt] refine rspconfig test cases

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3804]
Need  refine rspconfig test cases depending on the feedback.

what to do:
 * [ ] make the cases easier to debug
 * [ ] split some case to cover ``set`` and ``list`` requirement.

**Comment by junxiawang** [comment]
Cases need to add:
rspconfig_list_ip
rspconfig_set_ip
rspconfig_list_netmask
rspconfig_set_netmask
rspconfig_list_gateway
rspconfig_set_gateway
rspconfig_list_vlan
rspconfig_set_vlan
rspconfig_list_all
rspconfig_set_all
rspconfig_list_all_vlan
rspconfig_set_all_vlan
rspconfig_noderange_invalid
Cases need to modify:
rspconfig_set_ip
rspconfig_set_netmask
rspconfig_set_gateway

**Comment by zet809** [comment]
THe task is finished so close it.
