### ISSUE TITLE
Enable a test in TravisCI that would check for man page creation on RTD

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3810]
@hu-weihua  Could we do a simple pass of `create_man_pages.py` as part of the checking, that would remind users to run ... 

Another check is... if any .pod files changed, without corresponding .rst files in the pull request, we just error out of the travisCI job...

**Comment by hu-weihua** [comment]
@whowutwut, I have recorded this requirement, once I have resource, I will put it on schedule.

**Comment by hu-weihua** [comment]
Due to xCAT team will use IBM internal github to manage task. So move this task to ibm internal git hub. The new location is  https://github.ibm.com/xcat2/task_management/issues/178. close this one
@whowutwut, could you use new link to track the task? thanks.
