### ISSUE TITLE
[cumulus] mini-design the backup and restore of switch configuration

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3821]
investigate the backup and restore procedure of cumulus switch, draft a design

**Comment by immarvin** [comment]
The section  "Understanding the Locations of Configuration Data is Required for Successful Upgrades, Migration, and Backup" in the doc https://docs.cumulusnetworks.com/display/DOCS/Upgrading+Cumulus+Linux mentions the config files which should  and should not be backup and restore during upgrading.

**Comment by immarvin** [comment]
the draft design can be found in https://github.com/xcat2/xcat-core/wiki/the-mini-design-of-license-and-network-policy-distribution

**Comment by zet809** [comment]
Since this priority of license management is very low, let's close this task and reopen when needed. Thx!
