### ISSUE TITLE
[cumulus] refine the syslog script for cumulus switch

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3822]
* [ ] refine the syslog script to make the cumulus switch log forwarding consistent with the compute nodes
* [ ] make syslog compatible with configonie

**Comment by immarvin** [comment]
hi @cxhong ,  i noticed that there is strings like "for Cumulus OS inside ONIE switches" in syslog script,  have we already  finished the syslog support for cumulus ?

**Comment by cxhong** [comment]
No, I don't think so

**Comment by immarvin** [comment]
made a simple test, seems that syslog has support cumulus. but it's not included in configonie

**Comment by immarvin** [comment]
hi @cxhong , I think we need add "syslog","configinterface","enablesnmp",config passwordless root ssh, "configntp" as the default operation in ``switchdiscover --setup``, would you please take a look at this?

thanks

**Comment by cxhong** [comment]
the PR is merged, will close this issue.
