### ISSUE TITLE
[cumulus] cumulus ZTP process enhancement

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3823]
* [ ] add a switch in site table to disable ZTP 
* [x] refine the documulusdiscovery script to reflect the changes introduced in https://github.com/xcat2/xcat-core/pull/3601

**Comment by immarvin** [comment]
https://github.com/xcat2/xcat-core/pull/3886

**Comment by whowutwut** [comment]
@immarvin what is the intent of having the site table value to disable ztp? Would it also enable it? Why not just have a command?

**Comment by immarvin** [comment]
hi @whowutwut , since we are not sure whether ZTP is enabled in cumulus switches shipped in CRL, if the ZTP is well configured on MN, the switches will walk through the discovery and configuration 1st time on power on, then when we discover switches with "switchdiscover --setup", the switches will be configured for the second time, this might cause some problem. what do you think? @whowutwut @cxhong

**Comment by cxhong** [comment]
if switch discovered and configured 1st time using ZTP,   the ip address should change to static ip address already.   The user will pass in range of DHCP ip address to run switchdiscover --setup command,  so I don't think there will have problems.
