### ISSUE TITLE
[OpenBMC] rspconfig, expose a option to switch DHCPEnabled out of band

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3829]
OpenBMC provides a way to turn on and off DHCP, similar to the IPMI commands

* lan set 1 ipsrc static  => DHCPEnabled=>0
* lan set 1 ipsrc dynamic => DHCPEnabled=>1

So enhance rspconfig, propose the following externals... 

Use case: 
1. Prior to setting an IP address, it defaults to DHCPEnabled=1, 
```
rspconfig <node> network=eth0,static
rspconfig <node> ip=<IP> netmask=<NETMASK> gateway....
```

2. To reset back to DHCP
```
rspconfig <node> network=eth0,dhcp 
```
or, reset all network settings, which would default back to DHCPEnabled=1
```
rspconfig <> ip=dhcp
```

The first use case is more important because as we wait for https://github.com/openbmc/openbmc/issues/2138 We need a way to set DHCPEnabled=0 before HW discovery.  

Here's a sample of the REST: 
```
[root@briggs01 mid05tor12cn05]# ./set_enable_dhcp.sh eth0 1
++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data": 1 }' https://172.12.253.119//xyz/openbmc_project/network/eth0/attr/DHCPEnabled
```

We need to specify the network because with VLAN, it would be `network=eth0_14,dhcp` if applying to VLAN 14.  

When we modify the man page, also make the change to add `ip=dhcp` option for rspconfig

**Comment by zet809** [comment]
hi, @whowutwut , for *The first use case is more important because as we wait for openbmc/openbmc#2138 We need a way to set DHCPEnabled=0 before HW discovery.*, I think in bmcsetup, it will set ipsrc=static before configure IP/netmask/gateway/vlan, what is your concern?

**Comment by whowutwut** [comment]
This #2138 may not make it into the driver in the next week or two. So the work around for those machines is to first set DHCPEnables=0 before hardware discovery is run. 

So it has to run on the bmcdiscovered node before Genesis is invoked with bmcsetup or inband calls will fail.   

Having a command if we can implement is easier than calling rest on a large set of machines 

Looks like nothing was implemented last night so I will look at this when back from vacation. Can someone at least comment on the externals?

**Comment by zet809** [comment]
Applied a PR #3843

**Comment by zet809** [comment]
Hi, @whowutwut , after discuss with @xuweibj , It seems to me that the interface `rspconfig ipsrc=eth0,static` is inconvenient, the `DHCPEnabled=0` shall be set internally at the end of `ip,netmask,gateway` setting, and shall only need to set for `eth0` since there is no change for `eth0_11` to get a dynamic IP address. So, overall interface shall be like this:
```
rspconfig <node> ipsrc|ip|netmask|gateway|vlan
rspconfig <node> [ip=<IP>|netmask=<MASK>|gateway=<GW>|vlan=<vlan_id>] # In the end of every setting, `DHCPEnabled` shall be set to `0` for `eth0` 
rspconfig <node> ip=dhcp # To remove the static IP configuration for OpenBMC, and only eth0 left to get Dynamic IP. 
```
What is your idea?

**Comment by zet809** [comment]
Hi, @whowutwut , The implementation is done in pull request #4121 , pls help to view, thx!

**Comment by whowutwut** [comment]
This issue was opened initially as a way to work around a problem with the BMC where before we are able to run inband ipmitool commands  we had to set DHCPEnabled=0.... 

Since then it's been fixed by https://github.com/openbmc/openbmc/issues/2138 so closing it out.
