### ISSUE TITLE
Timeout error while running bmcreboot comamnd from xcat

### ISSUE THREAD

**Issue by rahulmah** [xcat2/xcat-core#3832]
While triggering bmc reboot from xCAT, sometime bmcreboot command fails with below timeout message.  Although BMC is getting reboot successfully without any problem.

```
[root@wsxcat ~]# rpower wsbmc008 bmcreboot

wsbmc008: Error: 504 Gateway Timeout
```

**Configuration details:**
xCAT version
```
[root@wsxcat ~]# lsxcatd -a
Version 2.13.7 (git commit feb51eb6a6abd2ef27d78b363ff0e3a7a4c71e3d, built Wed Aug 16 06:15:37 EDT 2017)
This is a Management Node
dbengine=SQLite
```
System : Witherspoon
BMC : ibm-v1.99.9-0-r3-0-g8bb9b44
PNOR : IBM-witherspoon-sequoia-ibm-OP9_v1.18_1.54

**Comment by immarvin** [comment]
hi @zet809 , any idea on this?

**Comment by zet809** [comment]
hi, @immarvin , @xuweibj was working on that, we can reproduce this issue but need to confirm with OpenBMC team.

**Comment by whowutwut** [comment]
@zet809. I think I linked you the conversation to slack where I asked the firmware team. If not you can search for this issue is that channel and you should be able to see the conversation

**Comment by whowutwut** [comment]
This should be fixed in BMC with https://github.com/openbmc/openbmc/issues/2241 so need to wait for that issue to close, then figure out which driver it went into...   

No planned action on xCAT here... 

When the fix is verified in a driver, we should indicate which xCAT release it matches up with for the benefits of our users

**Comment by whowutwut** [comment]
Seems like OpenBMC team says it's not quite as easy to fix this in their side...

**Comment by whowutwut** [comment]
@rahulmah With the latest build, we have hid the timeout 504 when doing a call for BMC reboot.  This occurs when the BMC is already shutting down and doesn't have a chance to send back a proper response, so we decided to hide the msg to prevent confusion from the user.  Please re-open if you see issues.
