### ISSUE TITLE
Use of uninitialized value $mtm_serial in xcatprobe nodecheck

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3834]
This bug is against xCAT latest daily build, `xCAT-probe-2.13.7-snap201708310615.noarch`.

**The recreation steps**
```
# xcatprobe nodecheck
Use of uninitialized value $mtm_serial in exists at /opt/xcat/probe//subcmds/nodecheck line 140.
Use of uninitialized value $mtm_serial in hash element at /opt/xcat/probe//subcmds/nodecheck line 172.
No nodes with duplicate mtm and serial numbers were found.                      [ OK ]
```

**What actually happened**
There is no node definition.
```
# lsdef
Could not find any object definitions to display.
```

**Comment by hu-weihua** [comment]
@gurevichmark, Could you help to look at this issue? thanks.

**Comment by gurevichmark** [comment]
Fixed by #3848

**Comment by zet809** [comment]
Hi, @neo954 , will you pls check whether this issue is fixed? Thx!

**Comment by neo954** [comment]
Verified on xCAT-probe-2.13.7-snap201709150615.noarch.

**Comment by neo954** [comment]
I will close this one.
