### ISSUE TITLE
[fvt] xcatd in SN did not load the latest version file after xcat upgrade in SN

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3855]
[environment]
rhels-pegas + ppc64le
xcat version : snap201709050615

[How to reproduce]

1. install MN and SN to snap201708300615
1. update xcat in MN  to snap201709050615
2. update SN installation osimage to include the snap201709050615 package.
3. run  ``updatenode  fsn01 -S``
4. check in SN, will found below things

        [root@fsn01 ~]# rpm -qa|grep -i xcat
        xCAT-genesis-base-x86_64-2.13.2-snap201702200120.noarch
        perl-xCAT-2.13.7-snap201709050615.noarch
        elilo-xcat-3.14-4.noarch
        conserver-xcat-8.2.1-1.ppc64le
        xCAT-probe-2.13.7-snap201709050615.noarch
        xCAT-genesis-scripts-x86_64-2.13.7-snap201709050615.noarch
        grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
        syslinux-xcat-3.86-2.noarch
        xCAT-server-2.13.7-snap201709050615.noarch
        xCAT-genesis-scripts-ppc64-2.13.7-snap201709050615.noarch
        ipmitool-xcat-1.8.18-0.ppc64le
        xCATsn-2.13.7-snap201709050615.ppc64le
        xCAT-genesis-base-ppc64-2.13.6-snap201707280206.noarch
        xCAT-client-2.13.7-snap201709050615.noarch

        [root@fsn01 ~]# cat /opt/xcat/lib/perl/xCAT/Version.pm
        #!/usr/bin/env perl
        .......
        sub Version
        {
            .........
            if ($version eq 'short')
            {
                $version = ''    . '2.13.7' ;
            }
            else
            {
                $version = 'Version '    . '2.13.7' . ' (git commit ca67bbf9f632ad376c729246c83880557acbbade, built Tue Sep  5 06:15:45 EDT 2017)' ;
            }
            .......
        }
        ..........

        [root@fsn01 ~]# lsdef -v
        lsdef - Version 2.13.7 (git commit 80bbe5eecef2afb76fc9c4d3a975a7b686ab9f9a, built Wed Aug 30 06:15:39 EDT 2017)

        [root@fsn01 ~]# restartxcatd
        restartxcatd invoked by root.

        Restarting xCATd                                           [  OK  ]
        [root@fsn01 ~]# lsdef -v
        lsdef - Version 2.13.7 (git commit ca67bbf9f632ad376c729246c83880557acbbade, built Tue Sep  5 06:15:45 EDT 2017)

        [root@fsn01 ~]# cat  /var/log/yum.log
        ......
        Sep 01 06:23:04 Installed: 4:xCATsn-2.13.7-snap201708300615.ppc64le
        Sep 05 22:27:30 Updated: 4:xCAT-probe-2.13.7-snap201709050615.noarch
        Sep 05 22:27:31 Updated: 4:xCAT-server-2.13.7-snap201709050615.noarch
        Sep 05 22:27:32 Updated: 4:perl-xCAT-2.13.7-snap201709050615.noarch
        Sep 05 22:27:33 Updated: 4:xCAT-client-2.13.7-snap201709050615.noarch
        Sep 05 22:27:33 Updated: 1:xCAT-genesis-scripts-x86_64-2.13.7-snap201709050615.noarch
        Sep 05 22:27:34 Updated: 1:xCAT-genesis-scripts-ppc64-2.13.7-snap201709050615.noarch
        Sep 05 22:28:15 Updated: 4:xCATsn-2.13.7-snap201709050615.ppc64le

So we can see, after upgrade xcat in SN, the new xcatd did not load the latest version file.  Restarted xcatd in SN one more time, everything was fine.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/3857
