### ISSUE TITLE
Unable to do BMC code update using xCAT

### ISSUE THREAD

**Issue by bsuresh1** [xcat2/xcat-core#3862]
After uploading BMC image(witherspoon-20170831180734.all.tar - ibm-v1.99.9-0-r4-0-gf0746a0)using below command, we dont see uploaded BMC image getting listed.

[root@wsxcat ~]# XCAT_OPENBMC_DEVEL=YES  rflash wsbmc015 /root/witherspoon-20170830193249.all.tar -u
wsbmc015: Uploading /root/witherspoon-20170830193249.all.tar ...
wsbmc015: Successful, use -l option to list.
[root@wsxcat ~]# XCAT_OPENBMC_DEVEL=YES  rflash wsbmc015 -l                     wsbmc015: ID       Purpose State      Version
wsbmc015: -------------------------------------------------------
wsbmc015: 729a501a Host    Active(*)  IBM-witherspoon-redbud-ibm-OP9_v1.19_1.2
wsbmc015: 6a656a19 BMC     Active     ibm-v1.99.9-0-r3-0-g8bb9b44
wsbmc015:

**Comment by zet809** [comment]
Hi, @gurevichmark , it seems our rflash can flashing the BMC firmware but can not list it, will you pls check with OpenBMC team for the interface? Thx a lot!

**Comment by rahulmah** [comment]
@zet809 : I dont see BMC getting updated/flashed. I cross check the system and found that same old level was present. So the issue here is BMC code update not happening via xcat.  

```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.9"
VERSION_ID="ibm-v1.99.9-0-r3-0-g8bb9b44"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.9"
BUILD_ID="ibm-v1.99.9-0-r3"
root@witherspoon:~#
```

**Comment by gurevichmark** [comment]
@zet809 @bsuresh1 I do not think BMC update is supported yet on OpenBMC systems using REST.
The HOST update is supported, and `rflash` can be used for that. I am still waiting for the witherspoon build to test xCAT `rflash` uploading and activating BMC update.

**Comment by whowutwut** [comment]
We are targeting this function in 2.13.7 release..  We are waiting for the builds that allow for BMC updates via REST, which is not currently available in a OP910 driver...   If you are testing with OpenBMC daily or dev builds, you may be ahead of us as we have to support teams that are running OP910 driver levels. 

Closing for now, we can estimate an ETA when we have one.
