### ISSUE TITLE
switch_macmap fails with "No switch information obtained" on Cisco switch

### ISSUE THREAD

**Issue by ryanbowen** [xcat2/xcat-core#3867]
Hello,

I'm currently trying to run through the base configuration of a new MN. I have set up the management node and am now attempting to test SNMP on my top-level switch which is a Cisco Catalyst 3850. I set up SNMP v3 by following the configuration in the "Configure Ethernet Switches" section of the documentation and the snmpwalk test case runs correctly (after removing the privacy key). When I try to use switch_macmap on my switch, it returns no Port to MAC mapping. The only thing that I can think of that may be causing a problem is that the management node is accessing the switch through the ip for the Vlan 2 SVI rather than the physical management port.

It seems to be able to communicate correctly using SNMP but the mapping is not being generated as shown in this output:

[root@xCAT ~]# xcatprobe switch_macmap MasterSwitch -V
[xCAT]: <INFO>MasterSwitch: Attempting to refresh switch information...
[xCAT]: <INFO>MasterSwitch: Generate SNMP session with parameter: 
                'Version' => '3'
                'AuthPass' => 'passw0rd'
                'SecName' => 'xcat'
                'UseNumeric' => '1'
                'SecLevel' => 'authNoPriv'
                'DestHost' => '192.168.2.254'
                'AuthProto' => 'SHA'
[xCAT]: <INFO>MasterSwitch: SNMP Session query OID:".1.3.6.1.2.1.31.1.1.1.1"
[xCAT]: <INFO>MasterSwitch: SNMP Session get data for OID:".1.3.6.1.2.1.31.1.1.1.1":
                 '1' => 'Gi0/0'
                 '2' => 'Nu0'
                 '3' => 'Gi1/0/1'
                 '4' => 'Gi1/0/2'
                 '5' => 'Gi1/0/3'
                 '6' => 'Gi1/0/4'
                 '7' => 'Gi1/0/5'
                 '8' => 'Gi1/0/6'
                 '9' => 'Gi1/0/7'
                 '10' => 'Gi1/0/8'
                 '11' => 'Gi1/0/9'
                 '12' => 'Gi1/0/10'
                 '13' => 'Gi1/0/11'
                 '14' => 'Gi1/0/12'
                 '15' => 'Gi1/0/13'
                 '16' => 'Gi1/0/14'
                 '17' => 'Gi1/0/15'
                 '18' => 'Gi1/0/16'
                 '19' => 'Gi1/0/17'
                 '20' => 'Gi1/0/18'
                 '21' => 'Gi1/0/19'
                 '22' => 'Gi1/0/20'
                 '23' => 'Gi1/0/21'
                 '24' => 'Gi1/0/22'
                 '25' => 'Gi1/0/23'
                 '26' => 'Gi1/0/24'
                 '27' => 'Gi1/1/1'
                 '28' => 'Gi1/1/2'
                 '29' => 'Gi1/1/3'
                 '30' => 'Gi1/1/4'
                 '31' => 'Te1/1/1'
                 '32' => 'Te1/1/2'
                 '33' => 'Te1/1/3'
                 '34' => 'Te1/1/4'
                 '35' => 'StackPort1'
                 '36' => 'StackSub-St1-1'
                 '37' => 'StackSub-St1-2'
                 '38' => 'Gi2/0/1'
                 '39' => 'Gi2/0/2'
                 '40' => 'Gi2/0/3'
                 '41' => 'Gi2/0/4'
                 '42' => 'Gi2/0/5'
                 '43' => 'Gi2/0/6'
                 '44' => 'Gi2/0/7'
                 '45' => 'Gi2/0/8'
                 '46' => 'Gi2/0/9'
                 '47' => 'Gi2/0/10'
                 '48' => 'Gi2/0/11'
                 '49' => 'Gi2/0/12'
                 '50' => 'Gi2/0/13'
                 '51' => 'Gi2/0/14'
                 '52' => 'Gi2/0/15'
                 '53' => 'Gi2/0/16'
                 '54' => 'Gi2/0/17'
                 '55' => 'Gi2/0/18'
                 '56' => 'Gi2/0/19'
                 '57' => 'Gi2/0/20'
                 '58' => 'Gi2/0/21'
                 '59' => 'Gi2/0/22'
                 '60' => 'Gi2/0/23'
                 '61' => 'Gi2/0/24'
                 '62' => 'Gi2/1/1'
                 '63' => 'Gi2/1/2'
                 '64' => 'Gi2/1/3'
                 '65' => 'Gi2/1/4'
                 '66' => 'Te2/1/1'
                 '67' => 'Te2/1/2'
                 '68' => 'Te2/1/3'
                 '69' => 'Te2/1/4'
                 '70' => 'StackPort2'
                 '71' => 'StackSub-St2-1'
                 '72' => 'StackSub-St2-2'
                 '73' => 'Vl1'
                 '74' => 'Vl2'
                 '75' => 'Vl284'
[xCAT]: <INFO>MasterSwitch: SNMP Session query OID:".1.3.6.1.2.1.2.2.1.4"
[xCAT]: <INFO>MasterSwitch: SNMP Session get data for OID:".1.3.6.1.2.1.2.2.1.4":
                 '1' => '1500'
                 '2' => '1500'
                 '3' => '1500'
                 '4' => '1500'
                 '5' => '1500'
                 '6' => '1500'
                 '7' => '1500'
                 '8' => '1500'
                 '9' => '1500'
                 '10' => '1500'
                 '11' => '1500'
                 '12' => '1500'
                 '13' => '1500'
                 '14' => '1500'
                 '15' => '1500'
                 '16' => '1500'
                 '17' => '1500'
                 '18' => '1500'
                 '19' => '1500'
                 '20' => '1500'
                 '21' => '1500'
                 '22' => '1500'
                 '23' => '1500'
                 '24' => '1500'
                 '25' => '1500'
                 '26' => '1500'
                 '27' => '1500'
                 '28' => '1500'
                 '29' => '1500'
                 '30' => '1500'
                 '31' => '1500'
                 '32' => '1500'
                 '33' => '1500'
                 '34' => '1500'
                 '35' => '0'
                 '38' => '1500'
                 '39' => '1500'
                 '40' => '1500'
                 '41' => '1500'
                 '42' => '1500'
                 '43' => '1500'
                 '44' => '1500'
                 '45' => '1500'
                 '46' => '1500'
                 '47' => '1500'
                 '48' => '1500'
                 '49' => '1500'
                 '50' => '1500'
                 '51' => '1500'
                 '52' => '1500'
                 '53' => '1500'
                 '54' => '1500'
                 '55' => '1500'
                 '56' => '1500'
                 '57' => '1500'
                 '58' => '1500'
                 '59' => '1500'
                 '60' => '1500'
                 '61' => '1500'
                 '62' => '1500'
                 '63' => '1500'
                 '64' => '1500'
                 '65' => '1500'
                 '66' => '1500'
                 '67' => '1500'
                 '68' => '1500'
                 '69' => '1500'
                 '70' => '0'
                 '73' => '1500'
                 '74' => '1500'
                 '75' => '1500'
[xCAT]: <INFO>MasterSwitch: SNMP Session query OID:".1.3.6.1.4.1.9.9.68.1.2.2.1.2"
[xCAT]: <INFO>MasterSwitch: SNMP Session get data for OID:".1.3.6.1.4.1.9.9.68.1.2.2.1.2":
                 '3' => '2'
                 '4' => '2'
                 '5' => '2'
                 '6' => '2'
                 '7' => '2'
                 '8' => '2'
                 '9' => '2'
                 '10' => '2'
                 '11' => '2'
                 '12' => '2'
                 '13' => '2'
                 '14' => '2'
                 '15' => '2'
                 '16' => '2'
                 '17' => '2'
                 '18' => '2'
                 '19' => '2'
                 '20' => '2'
                 '22' => '2'
                 '24' => '2'
                 '26' => '2'
                 '27' => '1'
                 '28' => '1'
                 '29' => '1'
                 '30' => '1'
                 '31' => '1'
                 '32' => '1'
                 '33' => '1'
                 '34' => '1'
                 '38' => '1'
                 '39' => '1'
                 '40' => '1'
                 '41' => '1'
                 '42' => '1'
                 '43' => '1'
                 '44' => '1'
                 '45' => '1'
                 '46' => '1'
                 '47' => '1'
                 '48' => '1'
                 '49' => '1'
                 '50' => '1'
                 '51' => '1'
                 '52' => '1'
                 '53' => '1'
                 '54' => '1'
                 '55' => '1'
                 '56' => '1'
                 '57' => '1'
                 '58' => '1'
                 '59' => '1'
                 '60' => '1'
                 '61' => '1'
                 '62' => '1'
                 '63' => '1'
                 '64' => '1'
                 '65' => '1'
                 '66' => '1'
                 '67' => '1'
                 '68' => '1'
                 '69' => '1'
[xCAT]: <INFO>MasterSwitch: SNMP Session query OID:".1.3.6.1.4.1.9.9.46.1.6.1.1.5"
[xCAT]: <INFO>MasterSwitch: SNMP Session get data for OID:".1.3.6.1.4.1.9.9.46.1.6.1.1.5":
                 '3' => '1'
                 '4' => '1'
                 '5' => '1'
                 '6' => '1'
                 '7' => '1'
                 '8' => '1'
                 '9' => '1'
                 '10' => '1'
                 '11' => '1'
                 '12' => '1'
                 '13' => '1'
                 '14' => '1'
                 '15' => '1'
                 '16' => '1'
                 '17' => '1'
                 '18' => '1'
                 '19' => '1'
                 '20' => '1'
                 '21' => '1'
                 '22' => '1'
                 '23' => '1'
                 '24' => '1'
                 '25' => '1'
                 '26' => '1'
                 '27' => '1'
                 '28' => '1'
                 '29' => '1'
                 '30' => '1'
                 '31' => '1'
                 '32' => '1'
                 '33' => '1'
                 '34' => '1'
                 '38' => '1'
                 '39' => '1'
                 '40' => '1'
                 '41' => '1'
                 '42' => '1'
                 '43' => '1'
                 '44' => '1'
                 '45' => '1'
                 '46' => '1'
                 '47' => '1'
                 '48' => '1'
                 '49' => '1'
                 '50' => '1'
                 '51' => '1'
                 '52' => '1'
                 '53' => '1'
                 '54' => '1'
                 '55' => '1'
                 '56' => '1'
                 '57' => '1'
                 '58' => '1'
                 '59' => '1'
                 '60' => '1'
                 '61' => '1'
                 '62' => '1'
                 '63' => '1'
                 '64' => '1'
                 '65' => '1'
                 '66' => '1'
                 '67' => '1'
                 '68' => '1'
                 '69' => '1'
[xCAT]: <INFO>MasterSwitch: Finished refreshing switch information.
MasterSwitch: [xCAT]: Error: No switch information obtained.                                                      [FAIL]

We have previously configured a seperate, larger xCAT management network setup for another environment which works correctly using Nexus switches, but the 3850s in this setup don't seem to work.

**Comment by ryanbowen** [comment]
Yes it succeeds:

[root@xCAT ~]# snmpwalk -v 3 -u xcat -a SHA -A passw0rd -l authnoPriv MasterSwitch .1.3.6.1.2.1.17.1.4.1.2 
SNMPv2-SMI::mib-2.17.1.4.1.2.19 = INTEGER: 21
SNMPv2-SMI::mib-2.17.1.4.1.2.21 = INTEGER: 23
SNMPv2-SMI::mib-2.17.1.4.1.2.23 = INTEGER: 25
SNMPv2-SMI::mib-2.17.1.4.1.2.25 = INTEGER: 27
SNMPv2-SMI::mib-2.17.1.4.1.2.26 = INTEGER: 28
SNMPv2-SMI::mib-2.17.1.4.1.2.27 = INTEGER: 29
SNMPv2-SMI::mib-2.17.1.4.1.2.28 = INTEGER: 30
SNMPv2-SMI::mib-2.17.1.4.1.2.29 = INTEGER: 31
SNMPv2-SMI::mib-2.17.1.4.1.2.30 = INTEGER: 32
SNMPv2-SMI::mib-2.17.1.4.1.2.31 = INTEGER: 33
SNMPv2-SMI::mib-2.17.1.4.1.2.32 = INTEGER: 34
SNMPv2-SMI::mib-2.17.1.4.1.2.65 = INTEGER: 38
SNMPv2-SMI::mib-2.17.1.4.1.2.66 = INTEGER: 39
SNMPv2-SMI::mib-2.17.1.4.1.2.67 = INTEGER: 40
SNMPv2-SMI::mib-2.17.1.4.1.2.68 = INTEGER: 41
SNMPv2-SMI::mib-2.17.1.4.1.2.69 = INTEGER: 42
SNMPv2-SMI::mib-2.17.1.4.1.2.70 = INTEGER: 43
SNMPv2-SMI::mib-2.17.1.4.1.2.71 = INTEGER: 44
SNMPv2-SMI::mib-2.17.1.4.1.2.72 = INTEGER: 45
SNMPv2-SMI::mib-2.17.1.4.1.2.73 = INTEGER: 46
SNMPv2-SMI::mib-2.17.1.4.1.2.74 = INTEGER: 47
SNMPv2-SMI::mib-2.17.1.4.1.2.75 = INTEGER: 48
SNMPv2-SMI::mib-2.17.1.4.1.2.76 = INTEGER: 49
SNMPv2-SMI::mib-2.17.1.4.1.2.77 = INTEGER: 50
SNMPv2-SMI::mib-2.17.1.4.1.2.78 = INTEGER: 51
SNMPv2-SMI::mib-2.17.1.4.1.2.79 = INTEGER: 52
SNMPv2-SMI::mib-2.17.1.4.1.2.80 = INTEGER: 53
SNMPv2-SMI::mib-2.17.1.4.1.2.81 = INTEGER: 54
SNMPv2-SMI::mib-2.17.1.4.1.2.82 = INTEGER: 55
SNMPv2-SMI::mib-2.17.1.4.1.2.83 = INTEGER: 56
SNMPv2-SMI::mib-2.17.1.4.1.2.84 = INTEGER: 57
SNMPv2-SMI::mib-2.17.1.4.1.2.85 = INTEGER: 58
SNMPv2-SMI::mib-2.17.1.4.1.2.86 = INTEGER: 59
SNMPv2-SMI::mib-2.17.1.4.1.2.87 = INTEGER: 60
SNMPv2-SMI::mib-2.17.1.4.1.2.88 = INTEGER: 61
SNMPv2-SMI::mib-2.17.1.4.1.2.89 = INTEGER: 62
SNMPv2-SMI::mib-2.17.1.4.1.2.90 = INTEGER: 63
SNMPv2-SMI::mib-2.17.1.4.1.2.91 = INTEGER: 64
SNMPv2-SMI::mib-2.17.1.4.1.2.92 = INTEGER: 65
SNMPv2-SMI::mib-2.17.1.4.1.2.93 = INTEGER: 66
SNMPv2-SMI::mib-2.17.1.4.1.2.94 = INTEGER: 67
SNMPv2-SMI::mib-2.17.1.4.1.2.95 = INTEGER: 68
SNMPv2-SMI::mib-2.17.1.4.1.2.96 = INTEGER: 69

**Comment by cxhong** [comment]
yeh,  for cisco switch,  xcat used vlan contexts.    I wonder if xcat failed to open a snmp session with vlan contexts. 
From switch_macmap output,  there were no problem to open snmp session first time without vlan contexts.   after query ".1.3.6.1.4.1.9.9.46.1.6.1.1.5",  xcat will open another snmp session with vlan contexts,  I didn't see any output after that.

**Comment by ryanbowen** [comment]
Does xCAT use SNMPv3 for that or v2? I have specified "context vlan- match prefix" for the xcatadmin group for v3.

**Comment by cxhong** [comment]
if switch in the switch tables define snmpv3,  it will use v3 ,  otherwise, will use snmp v1.  In this case,  will use snmpv3

**Comment by ryanbowen** [comment]
If I use snmpwalk with v3 and don't use -e to get a context, I do not get any of vlan2's information. I'm noticing that the output of switch_macmap does however include all the context output combined. It just doesn't get MAC addresses.

**[root@xCAT ~]# snmpwalk -v3 -l authNoPriv -u xcat -a SHA -A passw0rd -n vlan-1 MasterSwitch .1.3.6.1.2.1.17.1.4.1.2**
SNMPv2-SMI::mib-2.17.1.4.1.2.19 = INTEGER: 21
SNMPv2-SMI::mib-2.17.1.4.1.2.21 = INTEGER: 23
SNMPv2-SMI::mib-2.17.1.4.1.2.23 = INTEGER: 25
SNMPv2-SMI::mib-2.17.1.4.1.2.25 = INTEGER: 27
SNMPv2-SMI::mib-2.17.1.4.1.2.26 = INTEGER: 28
SNMPv2-SMI::mib-2.17.1.4.1.2.27 = INTEGER: 29
SNMPv2-SMI::mib-2.17.1.4.1.2.28 = INTEGER: 30
SNMPv2-SMI::mib-2.17.1.4.1.2.29 = INTEGER: 31
SNMPv2-SMI::mib-2.17.1.4.1.2.30 = INTEGER: 32
SNMPv2-SMI::mib-2.17.1.4.1.2.31 = INTEGER: 33
SNMPv2-SMI::mib-2.17.1.4.1.2.32 = INTEGER: 34
SNMPv2-SMI::mib-2.17.1.4.1.2.65 = INTEGER: 38
SNMPv2-SMI::mib-2.17.1.4.1.2.66 = INTEGER: 39
SNMPv2-SMI::mib-2.17.1.4.1.2.67 = INTEGER: 40
SNMPv2-SMI::mib-2.17.1.4.1.2.68 = INTEGER: 41
SNMPv2-SMI::mib-2.17.1.4.1.2.69 = INTEGER: 42
SNMPv2-SMI::mib-2.17.1.4.1.2.70 = INTEGER: 43
SNMPv2-SMI::mib-2.17.1.4.1.2.71 = INTEGER: 44
SNMPv2-SMI::mib-2.17.1.4.1.2.72 = INTEGER: 45
SNMPv2-SMI::mib-2.17.1.4.1.2.73 = INTEGER: 46
SNMPv2-SMI::mib-2.17.1.4.1.2.74 = INTEGER: 47
SNMPv2-SMI::mib-2.17.1.4.1.2.75 = INTEGER: 48
SNMPv2-SMI::mib-2.17.1.4.1.2.76 = INTEGER: 49
SNMPv2-SMI::mib-2.17.1.4.1.2.77 = INTEGER: 50
SNMPv2-SMI::mib-2.17.1.4.1.2.78 = INTEGER: 51
SNMPv2-SMI::mib-2.17.1.4.1.2.79 = INTEGER: 52
SNMPv2-SMI::mib-2.17.1.4.1.2.80 = INTEGER: 53
SNMPv2-SMI::mib-2.17.1.4.1.2.81 = INTEGER: 54
SNMPv2-SMI::mib-2.17.1.4.1.2.82 = INTEGER: 55
SNMPv2-SMI::mib-2.17.1.4.1.2.83 = INTEGER: 56
SNMPv2-SMI::mib-2.17.1.4.1.2.84 = INTEGER: 57
SNMPv2-SMI::mib-2.17.1.4.1.2.85 = INTEGER: 58
SNMPv2-SMI::mib-2.17.1.4.1.2.86 = INTEGER: 59
SNMPv2-SMI::mib-2.17.1.4.1.2.87 = INTEGER: 60
SNMPv2-SMI::mib-2.17.1.4.1.2.88 = INTEGER: 61
SNMPv2-SMI::mib-2.17.1.4.1.2.89 = INTEGER: 62
SNMPv2-SMI::mib-2.17.1.4.1.2.90 = INTEGER: 63
SNMPv2-SMI::mib-2.17.1.4.1.2.91 = INTEGER: 64
SNMPv2-SMI::mib-2.17.1.4.1.2.92 = INTEGER: 65
SNMPv2-SMI::mib-2.17.1.4.1.2.93 = INTEGER: 66
SNMPv2-SMI::mib-2.17.1.4.1.2.94 = INTEGER: 67
SNMPv2-SMI::mib-2.17.1.4.1.2.95 = INTEGER: 68
SNMPv2-SMI::mib-2.17.1.4.1.2.96 = INTEGER: 69



**[root@xCAT ~]# snmpwalk -v3 -l authNoPriv -u xcat -a SHA -A passw0rd -n vlan-2 MasterSwitch .1.3.6.1.2.1.17.1.4.1.2**
SNMPv2-SMI::mib-2.17.1.4.1.2.1 = INTEGER: 3
SNMPv2-SMI::mib-2.17.1.4.1.2.2 = INTEGER: 4
SNMPv2-SMI::mib-2.17.1.4.1.2.3 = INTEGER: 5
SNMPv2-SMI::mib-2.17.1.4.1.2.4 = INTEGER: 6
SNMPv2-SMI::mib-2.17.1.4.1.2.5 = INTEGER: 7
SNMPv2-SMI::mib-2.17.1.4.1.2.6 = INTEGER: 8
SNMPv2-SMI::mib-2.17.1.4.1.2.7 = INTEGER: 9
SNMPv2-SMI::mib-2.17.1.4.1.2.8 = INTEGER: 10
SNMPv2-SMI::mib-2.17.1.4.1.2.9 = INTEGER: 11
SNMPv2-SMI::mib-2.17.1.4.1.2.10 = INTEGER: 12
SNMPv2-SMI::mib-2.17.1.4.1.2.11 = INTEGER: 13
SNMPv2-SMI::mib-2.17.1.4.1.2.12 = INTEGER: 14
SNMPv2-SMI::mib-2.17.1.4.1.2.13 = INTEGER: 15
SNMPv2-SMI::mib-2.17.1.4.1.2.14 = INTEGER: 16
SNMPv2-SMI::mib-2.17.1.4.1.2.15 = INTEGER: 17
SNMPv2-SMI::mib-2.17.1.4.1.2.16 = INTEGER: 18
SNMPv2-SMI::mib-2.17.1.4.1.2.17 = INTEGER: 19
SNMPv2-SMI::mib-2.17.1.4.1.2.18 = INTEGER: 20
SNMPv2-SMI::mib-2.17.1.4.1.2.19 = INTEGER: 21
SNMPv2-SMI::mib-2.17.1.4.1.2.20 = INTEGER: 22
SNMPv2-SMI::mib-2.17.1.4.1.2.21 = INTEGER: 23
SNMPv2-SMI::mib-2.17.1.4.1.2.22 = INTEGER: 24
SNMPv2-SMI::mib-2.17.1.4.1.2.23 = INTEGER: 25
SNMPv2-SMI::mib-2.17.1.4.1.2.24 = INTEGER: 26

**switch_macmap output:**
[xCAT]: <INFO>MasterSwitch: SNMP Session query OID:".1.3.6.1.4.1.9.9.46.1.6.1.1.5"
[xCAT]: <INFO>MasterSwitch: SNMP Session get data for OID:".1.3.6.1.4.1.9.9.46.1.6.1.1.5":
                 '3' => '1'
                 '4' => '1'
                 '5' => '1'
                 '6' => '1'
                 '7' => '1'
                 '8' => '1'
                 '9' => '1'
                 '10' => '1'
                 '11' => '1'
                 '12' => '1'
                 '13' => '1'
                 '14' => '1'
                 '15' => '1'
                 '16' => '1'
                 '17' => '1'
                 '18' => '1'
                 '19' => '1'
                 '20' => '1'
                 '21' => '1'
                 '22' => '1'
                 '23' => '1'
                 '24' => '1'
                 '25' => '1'
                 '26' => '1'
                 '27' => '1'
                 '28' => '1'
                 '29' => '1'
                 '30' => '1'
                 '31' => '1'
                 '32' => '1'
                 '33' => '1'
                 '34' => '1'
                 '38' => '1'
                 '39' => '1'
                 '40' => '1'
                 '41' => '1'
                 '42' => '1'
                 '43' => '1'
                 '44' => '1'
                 '45' => '1'
                 '46' => '1'
                 '47' => '1'
                 '48' => '1'
                 '49' => '1'
                 '50' => '1'
                 '51' => '1'
                 '52' => '1'
                 '53' => '1'
                 '54' => '1'
                 '55' => '1'
                 '56' => '1'
                 '57' => '1'
                 '58' => '1'
                 '59' => '1'
                 '60' => '1'
                 '61' => '1'
                 '62' => '1'
                 '63' => '1'
                 '64' => '1'
                 '65' => '1'
                 '66' => '1'
                 '67' => '1'
                 '68' => '1'
                 '69' => '1'
[xCAT]: <INFO>MasterSwitch: Finished refreshing switch information.

**Comment by ryanbowen** [comment]
Just an update, I used a standalone switchport mapping tool to check the functionality of the switch's SNMP config. It was able to successfully map my 3850 using all 3 versions of SNMP, so it seems to be an xCAT issue.

**Comment by cxhong** [comment]
@zet809 , can u take look this issue for  Vlan- context of Cisco Switch?  I need to find a cisco switch to verify this.

**Comment by ryanbowen** [comment]
Another update, the same happens with all versions of SNMP through xCAT. Strangely, after changing xCAT to use SNMPv1 and letting the switch sit a while, switch_macmap began to function correctly. Now the problem is that the access switches under it (all 3850s also) are now having the same problem as the main switch did with switch_macmap. Again, a standalone port mapping tool is able to map them correctly through all versions of SNMP.

**Comment by ryanbowen** [comment]
@cxhong @zet809 It was a case of the error message not really being descriptive of the problem. If you don't have a node definition that uses the switch, the macmap will fail even if SNMP is working correctly.

To test, I created a test node and added `switch=MasterSwitch switchport=Gi1/0/1` and re-ran the macmap and it succeeded.

The output is now:
[xCAT]: <INFO>Switch01: Finished refreshing switch information.
[xCAT]: Switch    Port(MTU)           MAC address(VLAN)           Node
[xCAT]: --------------------------------------------------------------------------------------
[xCAT]: Switch01  Gi1/0/10(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/11(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/12(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/13(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/14(1500)      N/A                         sw1test
[xCAT]: Switch01  Gi1/0/15(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/16(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/17(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/18(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/19(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/2(1500)       00:b5:6d:00:3a:d7           
[xCAT]: Switch01  Gi1/0/20(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/21(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/22(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/23(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/24(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/25(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/3(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/36(1500)      N/A                         
[xCAT]: Switch01  Gi1/0/4(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/5(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/6(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/7(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/8(1500)       N/A                         
[xCAT]: Switch01  Gi1/0/9(1500)       N/A                         
[xCAT]: Switch01  Te1/0/48(1500)      N/A                         
[xCAT]: --------------------------------------------------------------------------------------

I'm not sure if this is intended or not, but it is now working correctly.

**Comment by cxhong** [comment]
oh, I see..  Thanks @ryanbowen .  We will modify the error message.....

**Comment by cxhong** [comment]
sign to @zet809 , need to verify code for switch without node defined to it

**Comment by cxhong** [comment]
if no nodes define to cisco switch, the message ```No switch information obtained``` will be logged,  other switch doesn't have this issue.

**Comment by zet809** [comment]
Hi, @ryanbowen , the fix will be included in 2.13.7 release.

**Comment by immarvin** [comment]
no update, close this first, please feel free to reopen if the issue still exists
