### ISSUE TITLE
Support Mellanox Ethernet Switch Firmware Update Procedure 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3868]
Modifying this issue to be more generic. I think it's tagged to the wrong epic: 

Mellanox Ethernet consists of: 
* Mellanox 10Gig (SX1410) 
* Mellanox 1G (Edge Core) running CumulusLinux
   * This one should be covered here: http://xcat-docs.readthedocs.io/en/latest/advanced/networks/onie_switches/os_cumulus/upgrade.html

**Comment by zet809** [comment]
hi, @whowutwut , does `Mellanox Ethernet 1G Switch` mean cumulus switch here?

**Comment by whowutwut** [comment]
@zet809 yes that one seems to be covered ok. Perhaps should switch this issues to be regarding the sx1410...

**Comment by whowutwut** [comment]
I updated this issue to be more broad, it probably should not be part of the cumulus linux epic, but rather should be an epic itself.  The pending issue is for Mellanox Switch OS (Cumulus Linux seems to be handled in detail already)

**Comment by immarvin** [comment]
hi @whowutwut , is this still requested? is it to close this?

**Comment by whowutwut** [comment]
Do we have any procedures documented on updating the Mellanox Switch OS?  @cxhong is this something you think we should come up with a  way under xCAT to perform, or let the admin manage?

**Comment by whowutwut** [comment]
@cxhong I believe this support is complete, could you  provide links to the documentation if any... if not, maybe  that is required to close this out.

**Comment by cxhong** [comment]
The Mellanox Ethernet switch (not cumulus) Firmware update is defined here:
https://xcat-docs.readthedocs.io/en/stable/advanced/networks/infiniband/firmware_updates.html?highlight=firmware#
