### ISSUE TITLE
Running discover on the latest P9 Processor causes segmentation fault in dodiscovery

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3870]
When running xCAT Genesis on P9, getting segmentation fault in `dodiscovery`.   Some internal investigation details here: https://github.ibm.com/vhu/c910env/issues/150

```
<166>Sep  6 11:51:02 xcat.genesis.doxcat: Received destiny=discover
<166>Sep  6 11:51:02 xcat.genesis.doxcat: The destiny=discover, destiny parameters=discover
<166>Sep  6 11:51:02 xcat.genesis.doxcat: Running dodiscovery...
<166>Sep  6 11:51:02 xcat.genesis.dodiscovery: Beginning node discovery process...
<166>Sep  6 11:51:02 xcat.genesis.dodiscovery: Waiting for nics to get addresses
enP5p1s0f0|172.12.253.129
<166>Sep  6 11:51:02 xcat.genesis.dodiscovery: Network configuration complete, commencing transmit of discovery packets
<166>Sep  6 11:51:02 xcat.genesis.dodiscovery: Beginning echo information to discovery packet file...
/usr/bin/doxcat: line 449:  1485 Segmentation fault      /bin/dodiscovery
<166>Sep  6 11:51:06 xcat.genesis.doxcat: dodiscovery - Complete.
```

It eventually makes it through and does send discovery packet to xCAT... 

Wondering if this is an issue with kernel level (Fedora26) or possibly ppc64 vs ppc64le... Genesis is running in Big Endian mode. ..   @zet809 @immarvin Need to open LTC issue?

**Comment by zet809** [comment]
Hi, @whowutwut , based on some investigation, it seems there are library issue with currently genesis running on DD2.0, we plan to provide a method to build genesis based on latest PEGAS to support DD2.0 or newer, what is you idea?

**Comment by whowutwut** [comment]
@zet809  Which library?  Please do whatever is necessary to get a working genesis-base that we can test with.  Please DO NOT upload this to xcat.org since it is not based on Fedora26..  

Once we understand the problem exactly and have a work around, we can discuss more about how to ship or whether we can legally ship it...  but need to understand exactly what is causing this ..

**Comment by zet809** [comment]
Hi, @whowutwut , I have create a gensis-base based on Pegas 1.0(4.11.0-28.el7a.ppc64le) and available at, there is no ntp-wait available on Pegas so we need to remove it in the doxcat script.
```
[root@briggs01 tmp]# ls -lh /tmp/xCAT-genesis-base-ppc64-2.13.7-snap201709080156.noarch.rpm
-rw-r--r-- 1 root root 38M Sep  8 01:58 /tmp/xCAT-genesis-base-ppc64-2.13.7-snap201709080156.noarch.rpm
```

**Comment by zet809** [comment]
Move to 2.13.8 to follow.

**Comment by zet809** [comment]
The work around is
1. Make sure the MN is installed Pegas with kernel version newer than `4.11.0-28.el7a.ppc64le`
2. download xCAT-genesis-builder-2.13.7-snap000000000000.noarch.rpm from http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/, install and run `/opt/xcat/share/xcat/netboot/genesis/builder/buildrpm`, then the xCAT-genesis-base-ppc64 package will be available at `/root/rpmbuild/RPMS/noarch/`.
3. install the xCAT-genesis-base-ppc64 package get from step2, then `mknb ppc64` to enable it.

**Comment by whowutwut** [comment]
@zet809 We really should create a new build without the `00000` in the name.  I've mentioned this multiple times in various places.... 

Even if we re-name it, it's going to be really hard to differentiate what is created by a normal user in a sandbox build and which is the version that we are asking users to download.. or even if we create a new one.... Can you create one with `snap201709220001 `  (indicates version 0001 for 2.13.7 release which is 9/22/17)  and upload it... then let's reference it for future.

**Comment by zet809** [comment]
Hi, @whowutwut , apply a PR #4006 to do the modification.
And have upload a new build called xCAT-genesis-builder-2.13.8-snap201709260001.noarch.rpm onto xcat.org, available at:
https://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-builder-2.13.8-snap201709260001.noarch.rpm

**Comment by zet809** [comment]
Which Epoch:3 for customized xCAT-genesis-base-ppc64 package, newly build package with Epoch:2 won't overwrite it aumotically.
```
[root@frame45cn02v1 builder]# rpm -aq | grep -i xCAT-genesis-base-ppc64
xCAT-genesis-base-ppc64-2.13.8-snap201710120354.noarch
[root@frame45cn02v1 builder]# rpm -qi xCAT-genesis-base-ppc64-2.13.8-snap201710120354.noarch | grep Epoch
Epoch       : 3
[root@frame45cn02v1 builder]# rpm -qpi /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.8-snap201710182246.noarch.rpm | grep Epoch
Epoch       : 2
[root@frame45cn02v1 builder]# rpm -Uvh /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.8-snap201710182246.noarch.rpm
Preparing...                          ################################# [100%]
	package xCAT-genesis-base-ppc64-3:2.13.8-snap201710120354.noarch (which is newer than xCAT-genesis-base-ppc64-2:2.13.8-snap201710182246.noarch) is already installed
```

**Comment by whowutwut** [comment]
@zet809 Thanks, we need to create another version to upload here: 

http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/

That has the Epoch set.  I think we will have to ask those who have already created a genesis base to install a new one that has the Epoch set, so that on 2.13.8 or future release where we may touch the xCAT-genesis base, it doesn't override a custom one

**Comment by zet809** [comment]
Hi, @whowutwut , I have uploaded a new xCAT-genesis-builder with Epoch:3 onto the location you mentioned above.
Since the new xCAT-genesis-base is only for Witherspoon server, maybe we can announce it in 2.13.8 release notes? Since we don't plan to do newer xCAT-genesis-base build than 2.13.7 do.

**Comment by zet809** [comment]
Hi, @whowutwut , shall we close this task and open newer ones to trace the update of xCAT-genesis-builder or include modules in xCAT-genesis-base package?

**Comment by whowutwut** [comment]
Documented this in RTD as a known issue under CORAL Reference architecture: http://xcat-docs.readthedocs.io/en/latest/references/coral/known_issues/genesis_base.html
