### ISSUE TITLE
Allow multiple options for rinv [OpenBMC]

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3889]
It may be useful for the options that we allow filtering on , that we allow multiple options to be specified.
  It's kind of a costly execution to query the BMC and get all the data back, and we filter on the data...
 
So we either only query for specific key words, or we allow multiple options.. Need to think about this, so open an issue to track. 

```
[root@briggs01 p9_generic]# rinv mid05tor12cn02 model
mid05tor12cn02: SYSTEM Model : 8335-GTC
[root@briggs01 p9_generic]# rinv mid05tor12cn02 serial
mid05tor12cn02: SYSTEM SerialNumber : 1318D3A
[root@briggs01 p9_generic]# rinv mid05tor12cn02 model serial
Only one option is supported at the same time for rinv

```

**Comment by gurevichmark** [comment]
@whowutwut What do you want to do for a case like this:
`rinv <node> model abc cpu` ? 
Return an error message saying the `abc` option is invalid or display results for `model` and `cpu` plus a warning message that `abc` option is invalid ?

**Comment by gurevichmark** [comment]
Decided to stop as soon as invalid option is detected.

**Comment by whowutwut** [comment]
This looks good, running verification on: 

```
[root@briggs01 ~]# lsxcatd -v
Version 2.14.1 (git commit 31d41643fbb709b6b1a00a74ef0f2c5b691a09cb, built Tue May 29 07:15:49 EDT 2018)
[root@briggs01 ~]#
```

Running full inventory is around 10 seconds....

```
[root@briggs01 ~]# time rinv mid05tor12cn16 > /dev/null

real	0m9.413s
user	0m0.151s
sys	0m0.011s
```

Running a subset is less,  there is still some overhead in the RESTFul call...
```
[root@briggs01 ~]# time rinv mid05tor12cn16 firm > /dev/null

real	0m2.739s
user	0m0.113s
sys	0m0.000s
[root@briggs01 ~]# time rinv mid05tor12cn16 serial > /dev/null

real	0m2.518s
user	0m0.108s
sys	0m0.000s
[root@briggs01 ~]# time rinv mid05tor12cn16 serial,firm
mid05tor12cn16: Error: Unsupported command: rinv serial,firm

real	0m0.248s
user	0m0.096s
sys	0m0.000s

[root@briggs01 ~]# time rinv mid05tor12cn16 serial firm > /dev/null

real	0m3.857s
user	0m0.112s
sys	0m0.000s
```
