### ISSUE TITLE
Configfpc fails with "configfpc plugin bug"

### ISSUE THREAD

**Issue by ryanbowen** [xcat2/xcat-core#3890]
We are attempting to provision our FPCs in our Lenovo enclosures using the configfpc plugin. Whenever it is ran against our MN interface, it fails partway through the first FPC with the below output:

`Sep 09 14:45:17 xcat13.cluster xcat[4943]: Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at /opt/xcat/lib/perl/xCAT_plugin/ipmi.pm line 935, <$parfd> line 4.`
`Sep 09 14:45:17 xcat13.cluster xcat[4943]: xcatd: configfpc plugin bug, pid 4943, process description: 'xcatd SSL: configfpc for root@localhost: configfpc instance: ipmi instance' with error 'Died at /opt/xcat/sbin/xcatd line 1999, <$parfd> line 4.`

It seems to successfully see the first FPC but fails to configure it, and then outputs "could not change netmask" without continuing further.

**Comment by immarvin** [comment]
hi @zet809 ,would you please take a look at this?

**Comment by zet809** [comment]
hi, @ryanbowen , can you show me the xCAT version you are using and the node definition of the CN? Thx!

**Comment by zet809** [comment]
Move to next release.

**Comment by immarvin** [comment]
no update
