### ISSUE TITLE
`hardeths` setting `bootproto` to `static` instead of `none` for RHEL7/Centos7

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3903]
For RHEL7/Centos7 the interface configuration files use `none` as valid value for `bootproto` instead of `static`, but the `hardeths` postscript still sets it as `static`. Can this be updated to use the correct value?

References:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/Networking_Guide/index.html

**Comment by bybai** [comment]
Hi @samveen , thanks your recommendation about this, will consider about this.

**Comment by bybai** [comment]
Hi @samveen , I think `static` for `bootproto` is valid too, so we will not change `static` to `none` now in `hardeths`. Thanks

**Comment by samveen** [comment]
@bybai I checked the network scripts, and it looks like `static` instead of `none` will work (the state of the `ifcfg` scripts will not match documented standards, but it will work):

```
[samveen@centos7vm203 ~]$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
[samveen@centos7vm203 ~]$ grep BOOTPROTO /etc/sysconfig/network-scripts/* |grep -v ifcfg
/etc/sysconfig/network-scripts/ifdown-eth:check_device_down ${DEVICE} && [ "$BOOTPROTO" != "dhcp" -a "$BOOTPROTO" != "bootp" ] && [ -n "$VLAN" -a "$VLAN" != "yes" ] && exit 0
/etc/sysconfig/network-scripts/ifdown-post:    -o "${BOOTPROTO}" = "bootp" -o "${BOOTPROTO}" = "dhcp" ] ; then
/etc/sysconfig/network-scripts/ifup:if [ "${BOOTPROTO}" = "bootp" -o "${BOOTPROTO}" = "dhcp" ]; then
/etc/sysconfig/network-scripts/ifup-eth:if [ "${BOOTPROTO}" = "bootp" -o "${BOOTPROTO}" = "dhcp" ]; then
/etc/sysconfig/network-scripts/ifup-ib:if [ "${BOOTPROTO}" = "dhcp" ]; then
```

PS. Actually, given the conditionals in the network scripts, any value other than `bootp` and `dhcp` will work identical to `none`

**Comment by bybai** [comment]
@samveen , So currently we will keep "static" in `hardeths`, I will close this issue. If you hit issue in the future, you can reopen it or open a new issue. Thanks.
