### ISSUE TITLE
The default configuration of rsyslog may not provide the log data integrity for xcat log locally

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#3910]
I encounter this problem on redhat7.3, 
Version 2.13.7 (git commit 436f69e85fefd2325738eac0770c801fc51e31bf)

The method from `xCAT::MsgUtils->message("S"...)` subroutine send the log message to the syslog, but some of log may be lost as the option of `$OmitLocalLogging on` from the configuration of `rsyslog`.

Some description for this option
```
# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
```
After changing `$OmitLocalLogging` from `on` to `off`, all of the log can be kept.

**Comment by neo954** [comment]
The default `rsyslog.conf` has the following configurations.
```
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
$ModLoad imudp
$UDPServerRun 514
$ModLoad imtcp
$InputTCPServerRun 514
$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging on
$IMJournalStateFile imjournal.state
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
```

Due to [1], [2]. module `imjournal` reads systemd socket "SystemLogSocketName", which is `/run/systemd/journal/syslog` on RHEL7 by default, and modules `imuxsock` reads `/dev/log`. That is why `$OmitLocalLogging on` is used.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1459633
[2] http://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html

After set `$OmitLocalLogging off` on RHEL7, local log messages will be logged twice.

**Comment by neo954** [comment]
In [3], it mentioned, the performance of module `imjournal` may be notably slower than when using `imuxsock`.

[3] http://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html

Thus, I guess, when use module `imjournal`, some logs were missing due to poor performance.

**Comment by neo954** [comment]
As a workaround of the performance problem with module `imjournal`. Do the following steps.

1. Edit file /etc/rsyslog.conf.
   1. Change the line `$OmitLocalLogging on` to `$OmitLocalLogging off`. This change will let module `imuxsock` to handle local logs.
   1. Comment out line `$ModLoad imjournal`. This change will fully disable module `imjournal`, and void duplicate local logs.
1. Restart rsyslog daemon.
   1. Run `systemctl restart rsyslog.service`.

Below is what the file `/etc/rsyslog.conf` looks like after the editing. Use it as a reference.
```
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
#$ModLoad imjournal # provides access to the systemd journal
$ModLoad imudp
$UDPServerRun 514
$ModLoad imtcp
$InputTCPServerRun 514
$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging off
$IMJournalStateFile imjournal.state
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
```

**Comment by neo954** [comment]
Forget the workaround method in the last comment. Here is the real solution.

Edit file, `/etc/systemd/journald.conf`. The original file shipped by Red Hat has the content below.
```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See journald.conf(5) for details.

[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitInterval=30s
#RateLimitBurst=1000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=yes
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

Uncomment the line `#RateLimitInterval=30s`. And change line `#RateLimitBurst=1000` to `RateLimitBurst=1000000`. After the editing, the file should look like below.

The original settings has a 1000-log-entries-per-30-seconds upper limit of the rate limit of logging. After the editing, the rate limit will be raised to 1,000,000 log entries per 30 seconds.

```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See journald.conf(5) for details.

[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
RateLimitInterval=30s
RateLimitBurst=1000000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=yes
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

Make sure file `/etc/systemd/journald.conf` looks good. Now, restart the `systemd-journald` service to apply the changes. `systemctl restart systemd-journald`
