### ISSUE TITLE
[feature request] rpower cycle support for BMC/IPMI

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#3913]
Hi!

Is there any reason why the `cycle` command is not supported for BMC/IPMI power management? It's supported for Blades and is defined in the help page as "Power off, then on".

There are some situations where a power cycle is necessary, and where a power reset is not sufficient, so it would be great if `cycle` could be supported for BMC/IPMI nodes. There's actually a direct IPMI command to power cycle nodes, that is implemented by `ipmitool chassis power cycle` for instance.

**Comment by whowutwut** [comment]
@zet809 FYI

**Comment by zet809** [comment]
Thx @kcgthb and @whowutwut 
I have checked the `cycle` implementation for blade, it is not supported.
As for the `ipmitool chassis power cycle`, we can add it later in 2.13.8.

**Comment by kcgthb** [comment]
That would be great, thanks!

**Comment by zet809** [comment]
Fixed in PR #4812

**Comment by zet809** [comment]
Let's close this issue and reopen if needed.
