### ISSUE TITLE
`xHRM bridgeprereq` converts interface with static configuration to bridge configured via DHCP 

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3923]
I have a KVM server where I run `hardeths` to update the network interface to be statically configured. However, when I run xHRM to configure the bridge (using `xHRM bridgeprereq br0`), the resultant bridge is **NOT** statically configured, but has reverted to using `DHCP`.

**Comment by bybai** [comment]
hi, @samveen , 
`confignetwork` is to recommended to create bridge in xCAT, could you have a try to it?
`confignetwork` is enhanced a lots in xcat 2.13.6 and 2.13.7. The new doc is here: http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/network/cfg_network_adapter.html
Thanks.

**Comment by samveen** [comment]
@bybai from the `confignetwork` document: 
> If configuring VLAN, BOND, or BRIDGES, nicdevices in nics table must be configured. VLAN, BOND or BRIDGES is only supported on RHEL.

However I just have on interface so it is a lot of manual overhead to manage bridges, especially with the RHEL/Centos `predictable interface naming` (we've been dealing with that for 2 years now, and it gets worse with every server we add into the cluster).

For that reason alone, xHRM is a much much simpler option for us, especially if it is cleaned up and it's bugs fixed (which I am working on).

**Comment by bybai** [comment]
@samveen , welcome to issue bugs or commit bug fixes, thanks. Your comments are very precious for xcat.

**Comment by immarvin** [comment]
any update on this? @samveen @bybai , can this be closed?

**Comment by bybai** [comment]
@samveen , I knew you have used `xHRM` several days and commit bug fixes before, if you have any updates, welcome you commit more. Currently, xcat recommend use `confignetwork`, `confignetwork` is stronger and easy control than `xHRM`, for example, if configure complex multiple types of nics, need call `xHRM` several times. I will close this issue, we can reopen it or open new issue if needed in future. Thanks.

**Comment by samveen** [comment]
@bybai Apologies on the delayed response. MR created.
