### ISSUE TITLE
[Stateless SN] httpd is not starting on stateless SN

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#3936]
When using stateless SN to provision CN, found that no `xCAT` entry in petitboot.
After investigation, it is caused that the httpd is not starting. Detail as below:
```
Sep 15 10:07:59 sn02.pok.stglabs.ibm.com httpd[12241]: [Fri Sep 15 10:07:59.429743 2017] [so:warn] [pid 12241] AH01574: module rewrite_module is already loaded, skipping
Sep 15 10:07:59 sn02.pok.stglabs.ibm.com httpd[12241]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/logs/' for main error log

[root@sn02 ~]# ls -l /etc/httpd/logs
lrwxrwxrwx 1 root root 19 Sep 14 10:05 /etc/httpd/logs -> ../../var/log/httpd
```
As we use /var/log in localdisk,  the content in image does not be synced to localdisk. Then httpd cannot be started.

After we manually create it, the httpd could be started successfully.

**Comment by zet809** [comment]
Hi, @robin2008, is it possible to update our RTD about diskless SN?

**Comment by robin2008** [comment]
Stateful SN is still xCAT prefer option, Stateless SN is still limited supported and error prone when different  
As xCAT don't ship the default osimage for stateless SN

**Comment by robin2008** [comment]
Doc it in 2.13.7 as known issue and provide workaround first
we can have better solution in 2.13.8

**Comment by robin2008** [comment]
already document limitation of localdisk for stateless https://github.com/xcat2/xcat-core/pull/3971
and move this one to  2.13.8

**Comment by zet809** [comment]
Hi, @robin2008 , can we close this issue since the document have been updated as you mentioned above? Thx!

**Comment by robin2008** [comment]
Still need an enhancement for `localdisk` feature on stateless.
When using stateless with `localdisk`, it will sync-up the contents from stateless image for files defined in `litefile` of this osimage at the first time.

1, During rc.localdisk running, it will check if it is required to sync contents to localdisk. If yes, then the script will sync the contents via `cp -a` to localdisk.

2, How to determine if it is required to sync, to define a FLAG file on `localspace` root directory
`<localspace_mout>/.NOTSYNCTOLOCAL`, by default,  `localspace` is mouted on `/.sllocal/localmnt`. If no this file, then sync to local.

Case 1:

To provision the stateless node with new disk and do partitioning, the disk is new and the filesystem is also new, there is no FLAG file, then the corresponding contents will be synced to local disk.

Case 2: 
To provision a stateless node with existing partitioned disk, but empty contents, the contents will be synced.

Case 3: reboot the stateless CN after the first provision, as the FLAG file is created, so no sync again.

Limitation:
User could remove the FLAG file to force an sync from osimage rootfs to local disk, but the contents on local disk will be override.

**Comment by robin2008** [comment]
After the fix, we need to modify the document to remove the workaound part.
