### ISSUE TITLE
[fvt] investigate the work status of xcat command handles noderange(such like nodeset)

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3957]
what to do:

* [ ] investigate the work status of xcat command handles node range
     *  ``nodeset``
     * ``rpower`` ``rsetboot`` ``rinstall`` ``updatenodes``
     *  ``makedhcp`` ``makehost`` ``makedns``  (including but not limited)

**Comment by neo954** [comment]
`command noderange`

| Command | Function | Exit code<br>when partly failed | Error message | Comment |
|------|:----:|-----:|:----:|------|
| makehosts | OK | **0** | OK |  |
| makedns | OK | **0** | OK |  |
| makedhcp | OK | 1 | OK |  |
| makeconservercf | OK | 0 | Problem | See issue #4009 |
| rpower | OK | 1 | OK |  |
| rsetboot | OK | 1 | OK |  |
| updatenodes | OK | 1 | OK |  |
| rinstall | OK | 1 | Problem | No distinct error message |
