### ISSUE TITLE
For OpenPOWER machine, the usage of rflash need to be clarified

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#3960]
In xCAT `rflash` document [1] agains OpenPOWER, it only mentioned use `rflash` against the HPM file. But in reality, the situation is much more complex.

[1] http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/management/advanced/rflash.html

The following items need to be clarified in the document.
* [ ] Where the latest firmware can be found?
* [ ] How to distinct OpenPOWER BMC (using IPMI) machine and OpenPOWER OpenBMC machine?
* [ ] Which machine models can use HPM file for its firmware updating?
* [ ] Which machine models can use tar file for its firmware updating?
* [ ] Which machine models can use data directory for its firmware updating?
* [ ] When specify a data directory for firmware updating, what files should be placed in the data directory?
* [ ] For machines with Supermicro® firmware, executable file `pUpdate` is needed, where the executable file `pUpdate` can be found.
* [ ] How to determine if `pUpdate` is needed for a particular OpenPOWER machine model? 
* [ ] How to check the release version of a firmware updating file?
* [ ] How to check the release version of the firmware installed on a OpenPOWER machine?
* [ ] What is the relationship between the version number of a firmware updating file and the version number printed out by `rflash -c` or `rflash -l`?

**Comment by gurevichmark** [comment]
I did not know we had this document [1].

Maybe all detailed `rflash` information should be kept in man page and this document [1] just gives a short explanation and a few examples of `rflash` command. Similar to other commands, listed by http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/management/advanced/index.html, like `rspconfig`.

**Comment by whowutwut** [comment]
@neo954 you bring up good points.. 

I guess would the man page be the correct place or do we really need a table to document the support matrix.  If the code correctly blocks the flash of machines that are not supported. Are we ok?

**Comment by neo954** [comment]
Okay, man page is a good place to gather all the information. Actually, I have to read the source code of xCAT to get the details I need when I use `rflash`. And I think we do need a table of `rflash` support matrix in the document. I asked all the xCAT members in Beijing office last week, no one has the full picture of the `rflash` support matrix in his/her mind. And no one can tell the difference among HPM file, tar file and data directory.

**Comment by neo954** [comment]
Hello all,

I believe only a few items in the list were clarified, most of them are not. And I think the documentation xCAT provides is from an xCAT developer's view, not from an xCAT user's view.

* [ ] Where the latest firmware can be found?
* [ ] How to distinct OpenPOWER BMC (using IPMI) machine and OpenPOWER OpenBMC machine?
* [ ] Which machine models can use HPM file for its firmware updating?
* [x] Which machine models can use tar file for its firmware updating?
* [ ] Which machine models can use data directory for its firmware updating?
* [ ] When specify a data directory for firmware updating, what files should be placed in the data directory?
* [ ] For machines with Supermicro® firmware, executable file `pUpdate` is needed, where the executable file `pUpdate` can be found.
* [ ] How to determine if `pUpdate` is needed for a particular OpenPOWER machine model? 
* [ ] How to check the release version of a firmware updating file?
* [x] How to check the release version of the firmware installed on a OpenPOWER machine?
* [ ] What is the relationship between the version number of a firmware updating file and the version number printed out by `rflash -c` or `rflash -l`?

**Comment by neo954** [comment]
And I think, in the xCAT user document, the internal codename, like `witherspoon` should be avoid.

**Comment by whowutwut** [comment]
@neo954  You bring up good comments, I answered some of them inline ☝️   @gurevichmark can you reply to the above where I've mentioned? 

* Here's a sample of a support matrix table that we _could_ create....

  | Server | Code name | Model | Power | BMC Management | 
  |----|----|----|--|---|
  | 8335-GTA | Firestone | IBM Power Systems S822LC for HPC | Power 8 LE | IPMI |
  | 8335-GTB  | Minsky | IBM Power Systems S822LC for HPC | Power 8 LE | IPMI |
  | 8001-12C/22C | Stratton/Briggs | IBM Power Systems S822LC for Big Data | Power 8 LE  | IPMI |   
  | 8335-GTC/GTW | Witherspoon | OpenPower AC922 (p9le) | Power 9 LE | OpenBMC | 
  | 9006-22C | Boston | ? | Power 9 LE | IPMI | 


@gurevichmark Will the firmware flash fail if the wrong files are presented on the wrong servers?

**Comment by zet809** [comment]
hi, @whowutwut ,the table looks great, maybe we can add another column to link to different document for different Server type

**Comment by gurevichmark** [comment]
Updated comments in the checklist. Also `Newell` should be used as a node name instead of Witherspoon.

**Comment by neo954** [comment]
The typical user scenario in my mind is ...

* Based on xCAT `rflash` document, the end user can prepare the firmware files for updating in advance, before he/she can have a chance to run `rflash` against the real machine.

Thus, I think rely on the error message of `rflash` is not good enough. That is due to the end user has to have a real machine, and run `rflash` against it, before he/she can get the correct information. In this way, the end user may waste his/her scheduled maintenance timeslot.

**Comment by whowutwut** [comment]
Assigning this issue to @gurevichmark

**Comment by whowutwut** [comment]
@neo954 I highly doubt that administrators will have a production system that they are unfamiliar with and flashing firmware for the first time during a maintenance window...
