### ISSUE TITLE
[OpenBMC] The rpower reset option needs to send a hard reset

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3966]
I found today that the `rpower <> reset` is sending `{"data":"xyz.openbmc_project.State.Host.Transition.Reboot"}'` to the host0 endpoint

This will in turn send a SOFT Power Off.  

In the man pages for rpower, the reset should do a Hard Reset. 

We need to update this code to do a off on Chassis and On on Host to force a hard reset. 
Or if there is an option to provide a Hard reset, we should use that.

**Comment by whowutwut** [comment]
I think this is required for 2.13.7 and I would switch to  be high priority if `rinstall <> osimage=` would call `rpower <> reset`, because it should be doing a hard reset, but it's actually doing a soft reset the way it's implemented today.

**Comment by gurevichmark** [comment]
Fixed by PR #3969

**Comment by whowutwut** [comment]
In my testing, I don't think this works...  We need to query the state to make sure that it's off before sending the on.  It didn't always take effect... and is not reliable...

**Comment by xuweibj** [comment]
https://github.com/openbmc/openbmc/issues/2471

**Comment by whowutwut** [comment]
@xuweibj  Thanks for following up,  I think we will need to implement the code logic to send a hard off... then wait.. until it actually turns off, then send a on again.    I added another comment to clarify in the above openbmc issue.

**Comment by xuweibj** [comment]
@whowutwut I agree with you. I think we could start to implement, what's your opinion?

**Comment by whowutwut** [comment]
Yea if you can please do

**Comment by whowutwut** [comment]
Thinking about this more, I think we should implement this hard reset to block until the node powers off and back on...   if each can go in parallel for the node range, that should be OK,  It's just like `rnetboot <node>` for Power7 nodes where the `rnetboot` does not return until the machine is booting.

**Comment by immarvin** [comment]
can this one be closed? @whowutwut @xuweibj

**Comment by whowutwut** [comment]
@immarvin I plan to sit behind the servers tomorrow and give this a bit of testing, I will close after that is done.

**Comment by whowutwut** [comment]
@xuweibj Tried this today on a node running 1742C, here's the result: 

```
[root@mgt03 vhu]# rpower f7n02 reset
f7n02: Internal Error, failed to rpower off, please try again
[root@mgt03 vhu]# tabedit site
[root@mgt03 vhu]# rpower f7n02 reset
Fri Nov  3 14:20:57 2017 f7n02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://192.168.74.172/login
Fri Nov  3 14:20:58 2017 f7n02: [openbmc_debug] login_response 200 OK
Fri Nov  3 14:20:58 2017 f7n02: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://192.168.74.172/xyz/openbmc_project/state/enumerate
Fri Nov  3 14:20:58 2017 f7n02: [openbmc_debug] rpower_status_response 200 OK
f7n02: off
[root@mgt03 vhu]# rpower f7n02 state 
Fri Nov  3 14:21:11 2017 f7n02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://192.168.74.172/login
Fri Nov  3 14:21:11 2017 f7n02: [openbmc_debug] login_response 200 OK
Fri Nov  3 14:21:11 2017 f7n02: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://192.168.74.172/xyz/openbmc_project/state/enumerate
Fri Nov  3 14:21:12 2017 f7n02: [openbmc_debug] rpower_status_response 200 OK
f7n02: off
[root@mgt03 vhu]# rpower f7n02 on 
Fri Nov  3 14:21:18 2017 f7n02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://192.168.74.172/login
Fri Nov  3 14:21:18 2017 f7n02: [openbmc_debug] login_response 200 OK
Fri Nov  3 14:21:18 2017 f7n02: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.State.Host.Transition.On"}' https://192.168.74.172/xyz/openbmc_project/state/host0/attr/RequestedHostTransition
Fri Nov  3 14:21:18 2017 f7n02: [openbmc_debug] rpower_on_response 200 OK
f7n02: on
```

What is this internal error?  Unfortunately this is all the debug I have. It looks like the node did power on, but didn't reboot it...

**Comment by xuweibj** [comment]
Hi @whowutwut , for rpower reset, if the current status is "off", will do nothing and print ``off``. If is "on", will do off and then on. 
I think during your test, the first ``rpower reset`` run off first, and then check the status 5 times, but still on so print "Internal Error, failed to rpower off, please try again". Maybe we could set the max retry times more than 5. 
And then when you run ``rpower reset`` again, the current status is "off", so it did nothing.

**Comment by whowutwut** [comment]
@xuweibj  correct. I should have been more specific. I was pointing out just the internal error. It looks like we are not waiting long enough for the machine to power off because we see that in fact the node is off when I query the state. 

Can these values be configured in any way? I think we should configure some max timeout value that can be configured and then in individual places we can change the interval that we check.  For example there is code for the checking of firmware to show up. I think we wait 1 min. I think here waiting 1 min is probably safe too. If this value can be default to 1 min and then overridden by site table value we will make this code more flexible without the need to change code 

The internal errro is also not informative enough to figure out what went wrong.

**Comment by xuweibj** [comment]
@whowutwut , I think 1 min maybe too long for a command. I think we could  set interval as 2s, and the most timeout 30s. Do you think it's OK?

**Comment by whowutwut** [comment]
Yea 1 min would be the max wait time. But we could keep checking every 5 seconds or so

**Comment by xuweibj** [comment]
@whowutwut , I have created pull request #4256 for this issue. Interval is 2s, and the max retry times is 30. I think it's enough. If it's not off even 1m, the node may have problem.
And I think we don't need add attribute just for this in site table. 'site' table should not have too many attributes.

**Comment by xuweibj** [comment]
Hi @whowutwut , could this issue be closed?

**Comment by whowutwut** [comment]
Yes, let's close for now, I will monitor in this release when doing power on/off and will try to use rinstall/reset as much as I can.
