### ISSUE TITLE
Power9 NVME Bolt adapter update 

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#3974]
The NVME bolt cards on the witherspoon power9 will require a BIOS update. This is a request to provide a method through xCAT to update the firmware. I will update this issue with the process from Matt Scheckel.

**Comment by whowutwut** [comment]
I've also been looking into this based on the information here: http://ausgsa.ibm.com/projects/s/scsi_sas/de/bolt/bolt.htm

**Comment by immarvin** [comment]
@whowutwut @zet809 can this one be closed?

**Comment by zet809** [comment]
Let me close this task as the code have been merged in.
