### ISSUE TITLE
Refactoring of ipmi.pm is needed for rflash command.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#3975]
Currently ipmi `rflash` checks for Boston/Briggs nodes and uses pUpdate to update those nodes. If we do not detect that nodes are Boston/Briggs or if nodes are not determined to be OpenPower, the code falls through and displays messages that are not easy for user to understand.

ipmi.pm should be refactored so that we explicitly check for supported nodes and tell the use if nodes they are trying to flash are not supported.

Perhaps something similar to what @whowutwut suggested in issue #3972:

```
I think this issue requires some refactoring of the ipmi.pm code to test the following:

if (openPower) { 
   if (S822LC for HPC) {  
   } else if (S822LC for Big Data) { 
   } else {
      rflash is not supported for this machine
  }
}

the way it's written today means that we are going into code path that is not intended. 
We also saw this issue on flashing Boston server that had a MTM that 
was not tested by xCAT, but in fact it fell into the 
OpenPower code and printed a message from there.

```

**Comment by gurevichmark** [comment]
Also make sure something like this returns an error:
`rflash fs3 -d /tmp/firmware/8335_820.1642.20170327n_update.hpm`

**Comment by zet809** [comment]
Seems need to cleanup the subroutine do_firmware_update() in ipmi.pm, there are more than 500 lines in this subroutine, may need to split the step out for either OpenPOWER server or supermicro server. 
Hi, @gurevichmark , let's discuss the steps to clean it up here.

**Comment by zet809** [comment]
The effort will be much large for us and ipmi.pm is a little low priority for us, let's close this issue.
