### ISSUE TITLE
switch discovery for ib switches is NOT scalable if we use our own community string.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3977]
we are doing the following process:
following this set of directions:
https://github.ibm.com/vhu/c910env/blob/master/notes/coral/end2end/edge_switch.md

template and groups are different here...
```
mkdef c699ibs[1-2]_[00] groups="switch,ib_switch" 
```
if we have not already done so add to group ib_switch
```chdef -t group nodetype=switch ib_switch password=admin     username=admin```

Then the individual discover gorp.
```
chdef c699ibs1_00 switch=c699eag01 switchport=16 ip=10.5.100.1
chdef c699ibs2_00 switch=c699eag01 switchport=18 ip=10.5.100.2
makehosts -a
```

then do a non write trial of the switch discover:
```
switchdiscover --range 10.5.254.1-250
```

no workee:
```
[root@c699mgt00 ~]# switchdiscover --range 10.5.254.1-250
Discovering switches using nmap for 10.5.254.1-250. It may take long time...
 No switch found                                                            
```

using nmap -sn we got:
```
[root@c699mgt00 ~]# nmap -sn 10.5.254.1-250

Starting Nmap 6.40 ( http://nmap.org ) at 2017-09-20 16:03 EDT
Nmap scan report for 10.5.254.1
Host is up (0.00023s latency).
MAC Address: 24:8A:07:B1:C1:CC (Unknown)
Nmap scan report for 10.5.254.2
Host is up (0.00025s latency).
MAC Address: 24:8A:07:B1:C1:5C (Unknown)
Nmap scan report for 10.5.254.5
Host is up (0.0013s latency).
MAC Address: A4:BF:01:36:38:C3 (Unknown)
Nmap scan report for 10.5.254.7
Host is up (0.00023s latency).
MAC Address: 24:8A:07:20:B5:EE (Unknown)
Nmap done: 250 IP addresses (4 hosts up) scanned in 2.06 seconds
```

10.5.254.1 and 10.5.254.2 are the switches we defined...

**Comment by ralphbellofatto** [comment]
doing this to debug:
```
switchdiscover --range 10.5.254.1-2 -s snmp -V
[c699mgt00]: Discovering switch using snmpwalk for 10.5.254.1-2 .....
[c699mgt00]: Process command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.5.254.1-2 | grep -v 'host down' | grep -E 'Nmap scan report|^161' | perl -pe 's/\n/ / if $. % 2'

[c699mgt00]: Nmap scan report for 10.5.254.1 161/udp open  snmp
Nmap scan report for 10.5.254.2 161/udp open  snmp

[c699mgt00]: Run snmpwalk command to get information for 10.5.254.1
[c699mgt00]: Process command: snmpwalk -Os -v1 -c comm4poklabRW 10.5.254.1 1.3.6.1.2.1.1.1

[c699mgt00]: Could not process this command: snmpwalk -Os -v1 -c comm4poklabRW 10.5.254.1 1.3.6.1.2.1.1.1
[c699mgt00]: Run snmpwalk command to get information for 10.5.254.2
[c699mgt00]: Process command: snmpwalk -Os -v1 -c comm4poklabRW 10.5.254.2 1.3.6.1.2.1.1.1

[c699mgt00]: Could not process this command: snmpwalk -Os -v1 -c comm4poklabRW 10.5.254.2 1.3.6.1.2.1.1.1
[c699mgt00]:  No switch found
```

our configuraton looks like this:
[root@c699mgt00 ~]# lsdef -t group switch -z
# <xCAT data object stanza file>

switch:
    objtype=group
    members=c699tor00,c699eag01,c699ibs1_00,c699ibs2_00
    mgt=switch
    nodetype=switch
    snmppassword=comm4poklabRW

[root@c699mgt00 ~]# lsdef -t site  clustersite  -i snmpc
Object name: clustersite
    snmpc=comm4poklabRW
[root@c699mgt00 ~]# lsdef c699ibs1_00 -z
# <xCAT data object stanza file>

c699ibs1_00:
    objtype=node
    groups=switch,ib_switch
    ip=10.5.100.1
    mgt=switch
    nodetype=switch
    password=xxxx
    snmppassword=comm4poklabRW
    switch=c699eag01
    switchport=16
    username=xxxx

# <xCAT data object stanza file>

ib_switch:
    objtype=group
    members=c699ibs1_00,c699ibs2_00
    nodetype=switch
    password=xxxx
    username=xxxx

```

**Comment by ralphbellofatto** [comment]
These mellanox switches were pulled out of their packaging and installed in the rack, cabled and powered on.

requiring that the community string be already be programmed on the node does not result in a salable setup.

Also the site to have a public community string is  a known security risk...  So we need a scalable way to do the discovery and then get things all properly setup.

**Comment by ralphbellofatto** [comment]
we were able to get around this by temporarly resetting the site snmpc=public attribute.

Then setting it nback when done

But inspite of the fact that the snmpPassword was set for the switch group.  running:
```switchdiscover --range 10.5.254.1-2 -s snmp -w --setup```

Failed to program the community string.

![image](https://user-images.githubusercontent.com/4139514/30670100-0c6877ee-9e2f-11e7-974a-b0e67ccd4d2d.png)


While we can program this by hand for now, this is not a scalable solution for 100's of racks.  It is not a scalable solution even for the 34 switches we have in this scaling cluster.

**Comment by cxhong** [comment]
We talked about this on the meeting.  Do u think this is reasonable?
switchdiscover command will use default community string "public".   
xCAT will add a option (-c) to let user pass in the community string if other than public, like:
```
switchdiscover --range 10.5.254.1-2 -s snmp -c community_string --setup
```

**Comment by ralphbellofatto** [comment]
yes, that would work better than what we have now...

**Comment by ralphbellofatto** [comment]
also, NOTE: that the --setup does not seem to program the community string attached to the switch definition when it is done.  I had to do those one at a time by hand, and that does not scale.

**Comment by cxhong** [comment]
I will open another issue to set up community string.

**Comment by cxhong** [comment]
close this issue, will open another if see the issue again.
