### ISSUE TITLE
IB driver can not be installed via /opt/xcat/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#398]
1. cp /opt/xcat/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2 \
   /install/postscripts/mlnxofed_ib_install_fromxcat
2. define it in node definition:
chdef c712f6n01  postbootscripts="mlnxofed_ib_install.fromxcat -p /install/Updates/CS15b/IB/MLNX_OFED_LINUX-3.1-1.0.3.1-rhel7.2-ppc64le.iso -m --without-32bit --without-fw-update --add-kernel-support --force -end-"
3. customize the packagelist
4. nodeset node  osimage=##
5. rsetboot node net
rpower node boot
6. the ib packages are not installed.

My env: MN: 9.114.39.149
CN: c712f6n01.
[root@c712ems2 postscripts]# lsdef c712f6n01
Object name: c712f6n01
    arch=ppc64le
    bmc=c712f6bmc01
    cons=ipmi
    conserver=9.114.39.149
    currchain=boot
    currstate=boot
    groups=all,IST,f6,snpsht4,DP
    initrd=xcat/osimage/zz_test/initrd.img
    installnic=mac
    kcmdline=quiet inst.repo=http://9.114.39.149:80/install/rhels7.2snapshot2/ppc64le inst.ks=http://9.114.39.149:80/install/autoinst/c712f6n01 BOOTIF=98:be:94:5c:f4:26  ip=dhcp  inst.cmdline  console=tty0 console=ttyS0,115200
    kernel=xcat/osimage/zz_test/vmlinuz
    mac=98:be:94:5c:f4:26
    mgt=ipmi
    netboot=petitboot
    nfsserver=9.114.39.149
    os=rhels7.2snapshot2
    postbootscripts=otherpkgs,mlnxofed_ib_install.fromxcat -p /install/Updates/CS15b/IB/MLNX_OFED_LINUX-3.1-1.0.3.1-rhel7.2-ppc64le.iso -m --without-32bit --without-fw-update --add-kernel-support --force -end-
    postscripts=syslog,remoteshell,syncfiles,sync_poe.limits
    primarynic=mac
    profile=compute
    provmethod=zz_test
    serialport=0
    serialspeed=115200
    status=failed
    statustime=11-12-2015 02:15:48
    tftpserver=9.114.39.149
    updatestatus=synced
    updatestatustime=11-10-2015 16:44:47
----------------------------------------------------------------------------------------------------------
[root@c712ems2 postscripts]# lsdef -t osimage zz_test
Object name: zz_test
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.2snapshot2-ppc64le
    osname=Linux
    osvers=rhels7.2snapshot2
    otherpkgdir=/install/post/otherpkgs/rhels7.2snapshot2/compute_1543a
    pkgdir=/install/rhels7.2snapshot2/ppc64le,/install/cuda-esp/cudaesp,/install/cuda-esp/cuda-deps
    pkglist=/install/custom/install/rh/compute.rhels7.xcat.pkglist
    postscripts=setupntp,synfilesfromems2
    profile=compute
    provmethod=install
    synclists=/install/custom/install/rh/compute.rhels7.synclist
    template=/install/custom/install/rh/compute.rhels7.tmpl

**Comment by neo954** [comment]
Fixed by pull request #401

**Comment by whowutwut** [comment]
@wwzhubj  Please wrap the terminal related output with the markdown style to help with readability.   It is good practice. You can edit any of your existing posts.  Please also indicate the build version you are using so we can diagnose the problem properly.  
```
[root@c712ems2 ~]# lsxcatd -a
Version 2.11 (git commit 5c2ff6120bd8c83545fbb8c75d72b7ee06d4a95f, built Wed Oct 28 13:33:17 EDT 2015)
This is a Management Node
dbengine=SQLite
```
Please update your mgmt node code to a newer weekly build http://xcat.org/files/xcat/xcat-core/devel/Linux/core-snap/?C=M;O=D

Closing this issue due to comment @neo954

**Comment by whowutwut** [comment]
I just realized that the problem has been fixed and merged this week..  the weekly build will be created Thurs night EST/ Friday morning China time, @wwzhubj , please pick up the build tomorrow  morining and try it out.  Re-opening, please verify and close if OK

**Comment by wwzhubj** [comment]
Xcat team FVT has verified this bug.

**Comment by neo954** [comment]
Close this one. Since it is already fixed in the latest build.
