### ISSUE TITLE
xdsh timeout options didn't work

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#3992]
looking one of research cluster.  

the switchdiscover --setup is hung due to xdsh command didn't come back with timeout value 10.
````
xCAT: Allowing xdsh to switch-10-5-254-9 -t 10 -l admin --devicetype IBSwitch::Mellanox enable;configure terminal;no interface mgmt0 dhcp;interface mgmt0 ip address 10.5.111.3 255.255.0.0;configuration write;exit;exit for root from localhost
`````
we know ip address actually changed, but xdsh should return back if host is not reachable any more, right?

**Comment by chenglch** [comment]
I tested some command with xdsh, if host is not reachable within 10 second(default), I always get `Caught SIGINT - terminating the child processes` message and `xdsh` command exit.

**Comment by chenglch** [comment]
I tested the following command to change the ip address of the target node, it exit as expected. 
```
root@c910f05c01bc01k10:~# xdsh kvmguest1 -t 10 ifconfig ens3 10.5.101.58
Error: Caught SIGINT - terminating the child processes.
```

**Comment by zet809** [comment]
So, is it possible that the command 'enable;configure terminal;no interface mgmt0 dhcp;interface mgmt0 ip address $static_ip $mask;configuration write;exit;exit' to configure switch IP hung?

**Comment by chenglch** [comment]
Maybe not, if there is not output from the output, `xdsh` should terminate itself when timeout.

**Comment by cxhong** [comment]
@zet809 , I issued those command one by one on the switch.  It worked well.

**Comment by chenglch** [comment]
hi @cxhong 
From my investigation, `xdsh` do always work as expected. Does it take effect on the switch side when running the xdsh command above?  I don't know how the switch terminal works. Does `configure terminal` open a terminal? Does the commands after `configure terminal` run inside the switch terminal? 

For `xdsh`, if there was always output printing from the above command, the timeout option could not take effect.

**Comment by robin2008** [comment]
Could we run `ssh` instead of `xdsh` with the required commands and see what's the result on Research LAB switch?

**Comment by cxhong** [comment]
the Mellanox command "no interface mgmt0 dhcp" caused switch hung. Jame will upgrade this switch to newest firmware level, then we will try again.  it's not xdsh issue.  I will close this.

**Comment by cxhong** [comment]
I like to reopen this issue.   
did some test on serial connection to the switch and from remote terminal to change the ip address.
```
"xdsh $dswitch -t 10 -l admin --devicetype IBSwitch::Mellanox 'enable;configure terminal;no interface mgmt0 dhcp;interface mgmt0 ip address $static_ip $mask;configuration write;exit;exit' ";
````
That command worked but never return back.  from other screen, we can access to switch via the $static_ip.   

If we issue the command one by one on the switch,   "no interface mgmt0 dhcp"  will remove the ip address.  that will cause  switch could not reach any more and have to set up ip address again from serial connection.  (so  xdsh command works better : )

Is there a way force xdsh timeout?

**Comment by chenglch** [comment]
@cxhong , as I can not recreate this issue locally, could you try to add some debug log at https://github.com/xcat2/xcat-core/blob/262f03089439fe74bdfb1cc813c254235e38e4e3/perl-xCAT/xCAT/DSHCLI.pm#L162  to trace the timeout event. 
From the code logic, if there are not any input from the remote, `xdsh` will terminate the child process.

**Comment by cxhong** [comment]
The switch is on research system.  don't think i can add debug code there.

**Comment by cxhong** [comment]
what if xCAT lost connection with remote host during the xdsh process, what will do?   that's what we hit,  xdsh send out serial of command to remote host, only finish half of commands, then lost connection.  xdsh never returns back...

**Comment by chenglch** [comment]
It will send INT signal to the ssh process, and then exit, like my experiment which I change the ip address of the target host below:
```
xdsh kvmguest1 -t 10 ifconfig ens3 10.5.101.58
Error: Caught SIGINT - terminating the child processes.
```

**Comment by robin2008** [comment]
@cxhong it is expected behavior `xdsh` without timeout option will hang when lost the connection to remote host.  

And I agree with chenglong, we may need more debug level trace log in the plugin to see what's happened in that environment which could recreate the issue.

**Comment by zet809** [comment]
Let's remove the priority label and treat it as a normal issue.

**Comment by zet809** [comment]
hi, @cxhong , let me remove the milestone and resort the priority later.

**Comment by cxhong** [comment]
@zet809  and @chenglch , do u think we should close this issue?  I debugged this with @chenglch , not sure how much we can do here.

**Comment by robin2008** [comment]
Let's close it first as we cannot recreate it on our own general environment, it may be related to specific env.
