### ISSUE TITLE
rpower not working after updating Witherspoon to 1738

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#3999]
Once I successfully updated my Witherspoon to 1738 level FW code, rpower doesn't work on my service node

(0) root @ xcat1: /root

rpower sn02 on

sn02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://192.168.85.3/login
sn02: [openbmc_debug] login_response 200 OK
sn02: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.State.Host.Transition.On"}' https://192.168.85.3/xyz/openbmc_project/state/host0/attr/RequestedHostTransition
sn02: [openbmc_debug] rpower_on_response 403 Forbidden
sn02: Error: 403 Forbidden - This function is not yet available in OpenBMC firmware.

This is the xCat level running on my machine
(1) root @ xcat1: /root

lsxcatd -a

Version 2.13.8 (git commit 8e9102a057332fc4c251ad49012c1476940ca133, built Fri Sep 22 06:15:36 EDT 2017)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=192.168.92.1|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=192.168.92.1
dbadmin=xcatadm

**Comment by moralesj** [comment]
rinv sn02 firm
sn02: [openbmc_debug] curl -k -c cjar -H “Content-Type: application/json” -d ‘{ “data”: [“root”, “xxxxxx”] }’ https://192.168.85.3/login
sn02: [openbmc_debug] login_response 200 OK
sn02: [openbmc_debug] curl -k -b cjar -X GET -H “Content-Type: application/json” https://192.168.85.3/xyz/openbmc_project/software/enumerate
sn02: [openbmc_debug] rinv_firm_response 200 OK
sn02: HOST Firmware Product: IBM-witherspoon-sequoia-ibm-OP9_v1.19_1.32 (Active)*
sn02: HOST Firmware Product: -- additional info: buildroot-2017.8-6-g319c6e1
sn02: HOST Firmware Product: -- additional info: capp-ucode-9c73e9f
sn02: HOST Firmware Product: -- additional info: hostboot-3d6c541
sn02: HOST Firmware Product: -- additional info: hostboot-binaries-836385d
sn02: HOST Firmware Product: -- additional info: linux-4.13-openpower1-pbe1de24
sn02: HOST Firmware Product: -- additional info: machine-xml-f8aaa73-pf7fdf7e
sn02: HOST Firmware Product: -- additional info: occ-a43395b
sn02: HOST Firmware Product: -- additional info: op-build-e87d6b0
sn02: HOST Firmware Product: -- additional info: petitboot-v1.5.1-p810ff34
sn02: HOST Firmware Product: -- additional info: sbe-8d90ab2
sn02: HOST Firmware Product: -- additional info: skiboot-v5.8-73-g4a2b8317fd3f

**Comment by moralesj** [comment]
(0) root @ xcat1: /root
# rflash sn02 -l
sn02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://192.168.85.3/login
sn02: [openbmc_debug] login_response 200 OK
sn02: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://192.168.85.3/xyz/openbmc_project/software/enumerate
sn02: [openbmc_debug] rflash_list_response 200 OK
sn02: ID       Purpose State      Version
sn02: -------------------------------------------------------
sn02: 0        BMC     Active     ibm-v1.99.10-0-r5-0-g0b8d737
sn02: 8ee5291f Host    Active(*)  IBM-witherspoon-sequoia-ibm-OP9_v1.19_1.32
sn02:

**Comment by whowutwut** [comment]
@moralesj Can you contact Adriana Kobylak and have her look at your node. There seems to be something wrong with the flash or upgrade....  It should also be running -r7.. not -r5... but we were able to power on the node with r5... you have something else corrupted going on here... ... 

```
root@witherspoon:~# obmcutil state
CurrentBMCState:    xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState:  xyz.openbmc_project.State.Chassis.PowerState.Off
Traceback (most recent call last):
  File "/usr/sbin/obmcutil", line 169, in <module>
    obj = bus.get_object(bus_name, obj_path)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name xyz.openbmc_project.State.Host was not provided by any .service files
```

Since you are on r5 version, you can use xCAT to flash the firmware. .   @gurevichmark  FYI, if you need to help @moralesj   


You can rflash the BMC using
```
rflash <> -a obmc-phosphor-image-witherspoon.ubi.mtd.tar
```

You need to provide the .tar file ...

**Comment by whowutwut** [comment]
@moralesj resolved this by re-flashing the node using the correct procedures...  closing
