### ISSUE TITLE
[Customer][Feature-req]  Add LBNL-NHC to monitoring options of xcat

### ISSUE THREAD

**Issue by dletai** [xcat2/xcat-core#400]
The LBNL-NHC just announced a new version (1.4.2) and complete separation from werewulf. I suggest allowing integration so in addition to support of werewulf,clustershell and pdsh it will be possible to use integrated monitoring service of xcat and use it to update e.g. nodestate in tables.

https://github.com/mej/nhc/blob/master/README.md
https://github.com/mej/nhc/releases

**Comment by arif-ali** [comment]
👍

**Comment by gurevichmark** [comment]
4 and 1/2 years old. Closing. Please open a new issue if this feature is still desired.
