### ISSUE TITLE
Node group name does not work if only consists of numbers 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4000]
Created a group called `1738` , and it does not work....  It creates OK

```
[root@briggs01 p9_generic]# lsdef -t group  | grep 1738
1738  (group)
fw1738  (group)
[root@briggs01 p9_generic]# lsdef -t group -o 1738
Object name: 1738
    members=mid05tor12cn11,mid05tor12cn13
```

But using the group does not work...
```
[root@briggs01 p9_generic]# nodels 1738
Error: Invalid nodes and/or groups in noderange: node1738
```

**Comment by immarvin** [comment]
hi @chenglch , would you please take a look at this?thanks

**Comment by chenglch** [comment]
I looked into this issue and trace the subroutines `defs`->`processArgs`->`noderange`->`expandatom`. I could not fix this issue as I'm not familiar with perl and its regular expression.

**Comment by whowutwut** [comment]
@chenglch humm...  ok...  There's no way to just block the creation of the node group?  If we can block it during the create with an error, then we don't have to worry about commands run against it...

**Comment by immarvin** [comment]
hi @whowutwut , this is the designed behavior, see manpage of "noderange"
````
# man noderange
...
       A node shorthand range of nodes:

        10-20   (equivalent to: node10,node11,node12,...node20)
        10+3    (equivalent to: node10,node11,node12,node13)

       Currently, the prefix that will be prepended for the above syntax is always "node".  Eventually, the prefix and
       optional suffix will be settable via the environment variables XCAT_NODE_PREFIX and XCAT_NODE_SUFFIX, but currently
       this only works in bypass mode.
````
