### ISSUE TITLE
Set snmpv1 community string for switches

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#4002]
the out of box switches have default community defined.   XCAT will provide a option to change the user defined community string for snmpv1.

**Comment by immarvin** [comment]
this is a feature request similar with https://github.com/xcat2/xcat-core/pull/3818/files?

**Comment by cxhong** [comment]
switchdiscover --setup for Mellanox switch only config SNMPv3 now. 
If user predefined the community string to switch,  switchdiscover --setup should able to config it.
