### ISSUE TITLE
[OpenBMC] xCAT does not reflect correct status of boot device

### ISSUE THREAD

**Issue by rahulmah** [xcat2/xcat-core#4008]
xCAT's restboot command does not reflect correct status of boot device. It is showing CDROM instead of Default. 

rsetboot command is meant to set or view the boot device which needs to be used for BMC-based servers for the next boot only.

```
[root@wsxcat ~]# rsetboot  wsbmc014 stat
wsbmc014: CD/DVD   <--- It should be showing Default here.
[root@wsxcat ~]#
```
```
bash-4.1$ curl -c cjar -b cjar -k https://wsbmc014/xyz/openbmc_project/control/host0/boot/one_time
{
  "data": {
    "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Regular",
    "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.Default",
    "Enabled": 1
  },
  "message": "200 OK",
  "status": 
```
xCAT version
```
[root@wsxcat ~]# lsxcatd -v
Version 2.13.8 (git commit 69900c531366c73cd96cd0c0534de801e79237fc, built Sun Sep 24 06:15:41 EDT 2017)
[root@wsxcat ~]#
```

BMC Version:
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.10"
VERSION_ID="ibm-v1.99.10-0-r6-0-g08df70f"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.10"
BUILD_ID="ibm-v1.99.10-0-r6"
root@witherspoon:~#
```

**Comment by zet809** [comment]
Hi, @xuweibj, will you pls take a look at this issue? Thx!

**Comment by xuweibj** [comment]
Currently, the command ``rsetboot stat`` is get info of path ``/xyz/openbmc_project/control/host0/boot``. I will modify based on the issue https://github.com/openbmc/openbmc/issues/2338.

**Comment by whowutwut** [comment]
@xuweibj So i guess we should show the nextboot, if there is one defined.. if not then go back to what we normally show?

**Comment by whowutwut** [comment]
@rahulmah Please update to the latest firmware and xCAT and re-try this.  Please reopen if you see additional problems.

**Comment by rahulmah** [comment]
I will update test result by end of day.

**Comment by rahulmah** [comment]
Verified. This issue is fixed. Tested with below xCAT version.

```
[root@wsxcat ~]# lsxcatd -v
Version 2.13.8 (git commit 9dc508f9c033d44bd70fdbf3ff47202c314b96b4, built Mon Oct  9 06:15:39 EDT 2017)
```
