### ISSUE TITLE
Commad makeconservercf should check attribute cons in node definition

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#4009]
This bug is against xCAT 2.13.7 snap201709220216.

**The recreation steps**
```
# mkdef tz998 groups=all cons=foo
1 object definitions have been created or modified.
# makeconservercf tz998
# echo $?
0
```

**What actually happened**

The following section was add in file `/etc/conserver.cf`. Even if `/opt/xcat/share/xcat/cons/foo` does not exist at all.
```
#xCAT BEGIN tz998 CONS
console tz998 {
  type exec;
  exec /opt/xcat/share/xcat/cons/foo tz998;
}
#xCAT END tz998 CONS
```

**What is expected**

* A proper error message is expected. In this way, the end users will get better understanding of their misconfiguration.
* The return value should be non-zero

**Comment by zet809** [comment]
Hi, @neo954 , does 'makegocons' have the same issue?

**Comment by chenglch** [comment]
I think `makegocons` also has this kind of issue.

**Comment by hu-weihua** [comment]
@neo954, could you help to verify the fix and close this issue? thanks.

**Comment by neo954** [comment]
The problem was verified. I will close this one.
