### ISSUE TITLE
[WSC] makedns/makedhcp might be wrong when define a bmc node with name ends with '-bmc'  

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4029]
Reported by Ralphbel 

we created two nodes definitions, one for the node itself and another for its underlying bmc so we can have the correct BMC address even when the bmc looses its ip information during reconfigurtion;

we define the parent node as follows:
```
# lsdef node1 -i bmc,ip -z
# <xCAT data object stanza file>

node1:
    objtype=node
    bmc=10.5.100.141
    ip=10.2.100.41
```
and its companion bmc def as follows:
```
# lsdef node1-bmc  -z
# <xCAT data object stanza file>

node1-bmc:
    objtype=node
    groups=bmc
    ip=10.5.100.141
    mac=a0:42:3f:32:fa:4f
```
we do

makehosts -a
makedns
makedhcp  node1-bmc

and we get the wrong answer in the leases file:
```
# tail -n 7 /var/lib/dhcpd/dhcpd.leases
host node1-bmc {
  dynamic;
  hardware ethernet a0:42:3f:32:fa:4f;
  fixed-address 10.4.100.41;
        supersede server.ddns-hostname = "node1-bmc";
        supersede host-name = "node1-bmc";
}
```
If we change the bmc name to remove the '-' character, then it appears to work..
```
# chdef -n node1bmc node1-bmc
# lsdef node1bmc
Object name: node1bmc
    groups=bmc
    ip=10.5.100.141
    mac=a0:42:3f:32:fa:4f
    postbootscripts=otherpkgs
```
makehosts -a
makedns
makedhcp node1bmc
```
# tail -n 7 /var/lib/dhcpd/dhcpd.leases
host node1bmc {
  dynamic;
  hardware ethernet a0:42:3f:32:fa:4f;
  fixed-address 10.5.100.141;
        supersede server.ddns-hostname = "node1bmc";
        supersede host-name = "node1bmc";
}
```

**Comment by robin2008** [comment]
May not an function issue, Ralphbel found that -bmc is defined as suffixes.
But, do we have warning when hitting the conflicts in `makehosts`.

**Comment by robin2008** [comment]
The source one is closed 
https://github.ibm.com/DCS-research/WSC-coral/issues/80

we can close it if `makehosts` has clear warnings or logs,  or leave it as a low priority issue to track.

**Comment by bybai** [comment]
let me try to reproduce this in my env.

**Comment by bybai** [comment]
@robin2008，I want to confirm the scenario from makehosts perspective:
1, If there are two nodes  node1 and node1-bmc defined with the same ip 10.5.100.141, `makehosts` will only add one line for node1-bmc into /etc/hosts, nodes with the same ip will be regarded as the duplicate in `makehosts`, node1 is not added into /etc/hosts:
10.5.100.141 node1-bmc node1-bmc.cluster

2, If there is only one node node1 defined, if want to use suffix '-bmc' as alias name, we can define `hostnames`  as node1-bmc in `hosts` table. after `makehosts`, the node1 and node1-bmc will both added into /etc/hosts:
10.5.100.141 node1 node1.cluster node1-bmc

3, If want to use suffixes in `nics` table, this suffix should have a ip configured in nics.nicips.

4, currently, if `makehosts` regards 2 lines are duplicate, there is no warning message print.

**Comment by robin2008** [comment]
@bybai 
they have `node1-bmc` with IP 10.5.100.141, and for `node1`, it has a nic suffix `-bmc` and the IP is 10.4.100.141

so the 10.4.100.141 will override 10.5.100.141 entry in /etc/hosts or DNS.

**Comment by bybai** [comment]
@robin2008， yes, it will override 10.5.100.141.  `makehosts` does not print warning messages when there is duplicate hostname or ip, it regards node1-bmc as duplicate.  So can add warning messages during duplicate happens for `makehosts` enhancement.
