### ISSUE TITLE
xCAT interaction with config management systems

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4041]
Many sites use configuration management systems such as cfengine, puppet, chef, or ansible.  Often times, the configuration will be stored in a version control system that might support additional features like rollback, branching, ACLs, etc.  When running multiple clusters (with separate management nodes), configuration management can help ensure that changes are properly propagated to all relevant nodes.

xCAT's database is difficult to make interoperate with config management.  Using xCAT commands, administrators can change settings without providing any kind of "commit message".  Some sites (ORNL and @ralphbellofatto) have written cron jobs that compare xCAT's database state with a known-good dump stored in git.

It certainly makes sense for many items (commonly-changing or voluminous) to remain in the xCAT database.  Static "configuration" items might make more sense to support via flat files.  Examples include the `site` table or `osimage` definitions.

I discussed this very briefly with @whowutwut at HPCXXL.

**Comment by immarvin** [comment]
hi @mattaezell  @ralphbellofatto , @whowutwut ,  seems @ralphbellofatto is managing the xCAT configuration data by managing the stanza file output by obj commands like `lsdef`, the problem of this way is that the  inheritance relationship is lost

how about manage the xCAT configuration data by managing the CSV files dumped by `dumpxCATdb`?

**Comment by ralphbellofatto** [comment]
the tabdump file in CSV format does not really allow the user of the system to actually see is that you don't really see the relationship of the data that has changed to the lsdef commands that change  them.  You see an entry in a table and have no idea what lsdef command that corresponds to, or how to change that value other than a table edit,  Trying to train our administrators to understand the table structure is hard, and encouraging direct table edits as a normal part of admin, is kind of risky.

We asked for a feature that would allow one to do an lsdef which would list ONLY those entries that were NOT inherited from a group definition, but that request did not get any attention.

We did get a solution to (almost) manage the lsdef inheritance,  At least it has been working ok, for us.

What we do is when we list out an lsdef we also list out the its group membership and then infer what fields are inherited.  We work out any field that in a backward search  of the group definitions for the node definition. Then if it matches the current definition, we assume this is inherited and don't store it as part off the lsdef for the node.  We also use this step to strip out any data that represent current status rather than definition.

If xcat could provide an lsdef command line option that would list ONLY those fields that are 1 NOT transient, and 2 did not come from groups, that would go a long way to being able to keep things under source control without the kludge we had to implement on top of this.

**Comment by immarvin** [comment]
hi @ralphbellofatto , sorry for inconvenience, I will discuss this with team this week and make a decision on how to support this. Please trace the progress in this ticket

thanks

**Comment by robin2008** [comment]
@mattaezell @ralphbellofatto 

We also think it is very useful to backup the `config data` of xcat for the whole cluster resource definitions.  And xcat provide the tool `dumpxCATdb`  to do the backup the table data into flat file(xcat support to exclude some table if required), and you can put those flat files into Git.

Even if it also backup the transient data (like status), in most of the case, it can work well for daily or weekly backup and restore case as xCAT won't have big DB. 

It is focusing on table level as xCAT is based on table at the beginning. And now you are asking for an `object level` config change management, say static attributes for `node`, `site`, `osimage`, `group`, etc. It is a big feature for xCAT,  And could we see the configuration might be changed frequently in a production cluster? 

Base on that, I think a short term plan for the below is reasonable

> If xcat could provide an lsdef command line option that would list ONLY those fields that are 1 NOT transient, and 2 did not come from groups, that would go a long way to being able to keep things under source control without the kludge we had to implement on top of this.

And we will continue to see if xcat can support full config management, including the definition in DB and the config on target managed nodes. It might be xCAT long term plan.

**Comment by ralphbellofatto** [comment]
let me see if i understand what you are saying.

1.  It is useful to backup the xcat configuration periodically and tabdump is useful for doing that.
2.  You will be attempting to provide an lsdef command that can shows all fields that are NOT status and NOT inherited for the purpose of working with configuration management software.

for item 1.  yes backups are useful, but don't answer the questions answered by configuration management , 1. what changed, 2. who changed it. 3. why was it changed. 4. how do i back just that one change out.  Tabdump is very difficult to sort out that information.  the lsdef method we are currently using at IBM research presents the information in the same manner that the administrators would use to set the data. Hence, answering the question of how to back out the change, is easy to spot.

I don't know if this will meet @mattaezell needs here, but it will go quite a way along to close the gap in our solution where we have a value that is the SAME as an inherited value, but is really an override.  This would also help in not mistakingly setting an override value when doing something like lsdef node -z >filename.txt

Change the data and then use chdef -z.  Doing that actually un-intentionally overrides the inherited values.  so having the lsdef feature you mentioned here would go along way to eliminating that problem.

@mattaezell would have to comment if this solution would help them out with how they do configuration management.

**Comment by mattaezell** [comment]
For item 1, that's great for disaster recovery, but it's not useful for day-to-day operations.
For item 2, that would simplify our workaround, but it doesn't really address the real reason I opened this issue.  As @robin2008 mentioned, we will need a long term plan.

**Comment by zet809** [comment]
Move to next release.

**Comment by immarvin** [comment]
compared the tables in xCAT db and xCAT objects:
there are 72 tables in xCAT
````
auditlog
bootparams
boottarget
cfgmgt
chain
deps
discoverydata
domain
eventlog
firmware
hosts
hwinv
hypervisor
ipmi
iscsi
kit
kitcomponent
kitrepo
kvm_masterdata
kvm_nodedata
linuximage
litefile
litetree
mac
mic
monitoring
monsetting
mp
mpa
networks
nics
nimimage
nodegroup
nodehm
nodelist
nodepos
noderes
nodetype
notification
openbmc
osdistro
osdistroupdate
osimage
passwd
pdu
pduoutlet
performance
policy
postscripts
ppc
ppcdirect
ppchcp
prescripts
prodkey
rack
routes
servicenode
site
statelite
storage
switch
switches
taskstate
token
virtsd
vm
vmmaster
vpd
websrv
winimage
zone
zvm
````

while 59 of them are abstracted or referred in xCAT objects 
````
     auditlog
     bootparams
     boottarget
     cfgmgt
     chain
     domain
     eventlog
     firmware
     hosts
     hwinv
     hypervisor
     ipmi
     iscsi
     kit
     kitcomponent
     kitrepo
     linuximage
     mac
     mic
     monitoring
     mp
     mpa
     networks
     nics
     nimimage
     nodegroup
     nodehm
     nodelist
     nodepos
     noderes
     nodetype
     notification
     openbmc
     osdistro
     osdistroupdate
     osimage
     pdu
     pduoutlet
     policy
     postscripts
     ppc
     ppcdirect
     ppchcp
     prescripts
     prodkey
     rack
     routes
     servicenode
     site
     storage
     switch
     switches
     taskstate
     vm
     vpd
     websrv
     winimage
     zone
     zvm
````

the following 13 tables are not referred at all.
````
< deps
< discoverydata
< kvm_masterdata
< kvm_nodedata
< litefile
< litetree
< monsetting
< passwd
< performance
< statelite
< token
< virtsd
< vmmaster
````

**Comment by immarvin** [comment]
covered in xcat-inventory
