### ISSUE TITLE
[Feature request] makeconservercf should not restart unmodified consoles

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4043]
When `makeconservercf` runs, it restarts the console server, which disconnects _**ALL**_ consoles, instead of just those consoles that have changed. In an environment with a lot of nodes, this means that the console server will take a **LOT** of time to reconnect consoles. 

* Can `conserver` be changed to support re-reading config on `SIGHUP` and  then `shutting down/starting up` just those consoles that are now modified, instead of all consoles? 
* consequently, can `makeconservercf` be changed to send `SIGHUP` to `conserver` instead of restarting the service?

**Comment by whowutwut** [comment]
@chenglch Can you take a look at this request?

**Comment by chenglch** [comment]
@zet809 , @whowutwut , to solve the `rcons` and `makeconservercf` issue for openbmc (https://github.com/xcat2/xcat-core/issues/3543) and to support this feature, I don't know how much effort we would take to update the diff patch and to build the packages for `conserver` on different platforms. I wrote a `consoleserver` (https://github.com/chenglch/consoleserver) with golang which support enrolling the terminal session on demand through rest api, could someone else in our team take some effort to try it or test it and then to see if we could enhance it in the future or integrate it with xcat.

**Comment by samveen** [comment]
@chenglch `conserver`'s console logging is very important for me which is the reason for this feature request. If `consoleserver` do console logging *and* if it can be used to a drop in replacement for the existing conserver, that would work very well.

**Comment by whowutwut** [comment]
@chenglch We need to have some instructions on how "consoleserver` drops into xCAT2 and how to flip between this and the existing version of conserver.  If we have this defined, we can give it some try and see how it works or refine the process.

**Comment by chenglch** [comment]
@whowutwut , I plan to add a new command maybe called `makecongo` to register the nodes into the new `consoleserver`( maybe I will change the name to `congoserver`  which means console with golang). `conserver` will be kept and user could still use it like before. 
I think the new `consoleserver` could be looked as a experiment feature aims to solve the problems we met about console especially for `OpenBMC`.

**Comment by samveen** [comment]
maybe change it  to `goconserver` and `makegocon`?

**Comment by zet809** [comment]
Yes, you are using `makegocons` and goconserver right now, it won't affect the unmodified consoles. So, close this issue, pls reopen if encounter problems. Thx!
