### ISSUE TITLE
xHRM fails when installnic is not set

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4058]
Hi!

When `installnic` is not set in the `noderes` table, the documentation states that the value will default to `primarynic`, and then to the `mac` keyword in case `primarynic` is not defined either.

Turns out this is not really the case, as the default diskful install template (`mypostscript.tmpl`) does [this](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/mypostscript/mypostscript.tmpl#L43):
```
:INSTALLNIC=#TABLE:noderes:$NODE:installnic#
```
So if `installnic` is not defined in the `noderes` table, an empty `INSTALLNIC` environment variable is exported to the postinstall scripts.

As a consequence, the `xHRM` postinstall script fails when called without any argument, when `installnic` is not set, and exits with ["Incorrect usage"](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/scripts/xHRM#L141):

```
# lsdef -c sh-hv01 -i installnic
sh-hv01: installnic=

# updatenode sh-hv01 -P "xHRM bridgeprereq"
sh-hv01: xcatdsklspost: downloaded postscripts successfully
sh-hv01: Fri Oct  6 15:07:24 PDT 2017 Running postscript: xHRM
sh-hv01: Incorrect usage
sh-hv01: postscript: xHRM exited with code 1
sh-hv01: Running of postscripts has completed.
```

**Comment by samveen** [comment]
@bybai As per the [documentation of xHRM](docs/source/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/hypervisorKVM.rst), this behaviour is correct: 
1.  Bridge name is required (in which case the primary interface is used) _or_
2. `installnic` must be set (in which case bridge `default` is created).
xHRM is *not* expected to run without minimum information as above.

I assume what you want is extending xHRM to combine the defaults from options 1 and 2:
* Create a bridge `default` using the primary interface in case no information is provided.

**Comment by bybai** [comment]
Hi  @kcgthb,
Executing "xHRM bridgeprereq" directly still cause error if there is "installnic" defined.  The correct usage is:
1,configure bridge `xHRM bridgeprereq port:bridge_name`: xHRM bridgeprereqport eth1:br1
2,configure bridge br1 based on bond,the bond use eth2 and eth3:
xHRM bridgepreqport eth1&eth2:br1
3,configure bridge vlan02 based on vlan,eth1->eth1.02->vlan02:
xHRM bridgepreqport eth1:vlan02

**Comment by bybai** [comment]
Hi @samveen , I already created a pull request for this issue. You can continue your work in your branch. It is no conflict. You can give me comments also , thanks for your efforts.

**Comment by kcgthb** [comment]
@samveen @bybai I'm refering to the documentation at https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/hypervisorKVM.html that states:

> To create a bridge with default name ‘default’ against the installation network device specified by installnic:
> `chdef kvmhost1 -p postscripts="xHRM bridgeprereq"`

I would expect the xHRM script to use the fallback default of `installnic` then it's not defined.

**Comment by bybai** [comment]
hi @kcgthb ,
So I enhance xHRM based on doc:
"When installnic is not set in the noderes table, the documentation states that the value will default to primarynic, and then to the mac keyword in case primarynic is not defined either."
Thanks.
