### ISSUE TITLE
bmcsetup as postscript hangs due to background process

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4065]
I discovered a couple boston nodes with an old firmware level, and the BMCs failed to configure with `bmcsetup`.  Once they booted to OS, I tried `updatenode <mynode> -P bmcsetup`, but it hangs at the end:
```
...
gw1: bmcsetup: Enabling SOL for channel 1: OK
gw1: bmcsetup: Enabling SOL for ADMIN
gw1: bmcsetup: Enabling SOL for ADMIN: OK
gw1: bmcsetup: Lighting Identify Light
```
It looks like `mypostscript` is waiting on the backgrounded process that blinks the LED
```
# pstree -p|grep mypos
           |-mypostscript(5706)---sleep(10102)
           |-sshd(5247)---bash(5253)---file7gGC8F.dsh(5258)---mypostscript(5335)---tee(5347)
```

I guess when run inside `genesis` the chain scripts don't care and the node just gets rebooted?  I certainly don't want the beacon left on forever.  Is there a way to detect if this is running in `genesis` or in a running osimage?

**Comment by whowutwut** [comment]
@zet809  Can you take a look?

**Comment by zet809** [comment]
Fixed in #4089

**Comment by immarvin** [comment]
hi @mattaezell , can this issue be closed?

**Comment by mattaezell** [comment]
We haven't moved to a snapshot with this fix to verify, but I'm OK to close.
