### ISSUE TITLE
[CORAL]pgsqlsetup support adding more hosts in pg_hba.conf

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#4067]
This requirement is coming from the following xcat MN HA:
1, In xCAT MN HA, when using virtual ip in postgresql, pgsqlsetup will add site.master ip into pg_hba.conf, if the site.master ip is alias virtual ip, `pgsql` cannot connect `postgresql` as following error, so `pgsqlsetup` should add physical ip into pg_hba.conf for HA.
```
[root@bybc0609 pgsql]# su - postgres
Last login: Tue Sep 26 04:34:46 EDT 2017 on pts/1
-bash-4.2$ psql -h 10.5.106.100 -U xcatadm -d xcatdb
psql: FATAL:  no pg_hba.conf entry for host "10.5.106.9", user "xcatadm", database "xcatdb", SSL off
```
2.  In HA, both primary MN ip and standby MN ip should be added into pg_hba.conf;

**Comment by immarvin** [comment]
seems this feature has been implemented in PR https://github.com/xcat2/xcat-core/pull/3519/files

**Comment by robin2008** [comment]
It seems difference,  one is for the IP which postgresql daemon is listening, and the asking is for extra host authentication in `pg_hba.conf`

**Comment by bybai** [comment]
@immarvin , Just like @robin2008 said, the enhancement need add IPv4 local connections in `pg_hba.conf` like:
```
host    all          all        10.5.106.100/32    md5
host    all          all        10.5.106.5/32      md5
```

**Comment by bybai** [comment]
After reading pgsqlsetup code, I found the option "-a|--access" is to add IPv4 local connection in `pg_hba.conf`, but the `pgsqlsetup` manpage says "-a" is for adding service node access, so `pgsqlsetup` code is no need to be changed, man page should be enhanced.

**Comment by whowutwut** [comment]
Helps resolve #3938
