### ISSUE TITLE
[fvt] add test case for issue 3838 (related command is nodeset)

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4068]
what to do:

Add test case for #3838.
refer to #4037 to get some test scenario

* [ ] offer a test cases mini design in WIKI
* [ ] implement these test cases

**Comment by neo954** [comment]
A test plan was placed in the following URL.

https://github.com/xcat2/xcat-core/wiki/Test-cases-against-nodeset-error-handling

**Comment by neo954** [comment]
@robin2008, It is great if you have time and can take a look at the test plan.
