### ISSUE TITLE
[fvt] new feature test for 3820:  support the cumulus os upgrade procedure

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4069]
what to do:

test new feature : support the cumulus os upgrade procedure
* [x] The mini-design about the FVT.
* [x] The switch discovery and configuration based on cumulus 3.4.1
* [x] The cumulus OS upgrade test, from lower version to 3.4.1 and higher
* [x]  Verify the configuration is not missed after OS upgrade.

**Comment by immarvin** [comment]
the cumulus upgrade doc: http://xcat-docs.readthedocs.io/en/latest/advanced/networks/onie_switches/os_cumulus/upgrade.html

**Comment by hu-weihua** [comment]
The test design is https://github.com/xcat2/xcat-core/wiki/Cumulus_OS_Upgrade_Support_Test
