### ISSUE TITLE
Buggy Bios with xnba

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#4071]
Hello,
i have some servers with a buggy bios which fails with xnba on boot.
The config just returns "exit" and the system does not fall back to use the next boot device in order.
When i modify xnba.pm to return "sanboot --no-describe --drive 0x80" the systems works.

Is it possible to add a option/switch for it?

Kind regards

**Comment by immarvin** [comment]
hi @Phhere , first please make sure whether hard disk is included in the boot device list of the firmware

if the boot device list is ok, it should be the firmware bug you mentioned, I searched on google,  seems that some type of servers with firmware bug which can only boot from hard disk with `sanboot --no-describe --drive 0x80`,  while most servers only works with `exit`, it is hard for us to tell the server falls to which kind of the 2.  

so what is your server type? is it possible to differentiate it with the node definition?

**Comment by Phhere** [comment]
hi @immarvin ,
yes i checked that hard disk is included,
These are servers from Bull /  Atos from their BullX-Series and there is not firmware update available. 

I know that it is not possible to detect the type of a node which is not booting directly so a attribute in node definition is fine for it.

**Comment by immarvin** [comment]
hi @Phhere , please provide your node definition

**Comment by Phhere** [comment]
It looks like this

> Object name: hilbert29
    addkcmdline=R:: net.ifnames=0 biosdevname=0 ipv6.disable=1 modprobe.blacklist=nouveau
    appstatustime=10-10-2017 17:00:39
    arch=x86_64
    bmc=10.28.11.29
    bmcpassword=superuser
    bmcusername=root
    currchain=boot
    currstate=boot
    groups=base,cuda_rhel7.x,chassis9,b500
    initrd=xcat/osimage/hilbert_rhel7.x_compute/initrd.img
    installnic=eth0
    ip=10.28.2.29
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.3/x86_64 inst.ks=http://!myipfn!:80/install/autoinst/hilbert29 ip=192.168.128.29::192.168.2.1:255.255.0.0:hilbert29:eth0:none::08:00:38:35:fb:e0 nameserver=192.168.2.201
    kernel=xcat/osimage/hilbert_rhel7.x_compute/vmlinuz
    mac=08:00:38:35:fb:e0
    mgt=ipmi
    netboot=xnba
    nicextraparams.ib0=CONNECTED_MODE=yes
    nichostnamesuffixes.ib0=-ib
    nicips.ib0=10.100.0.29
    nicips.eth1=10.28.2.29
    nicnetworks.ib0=ibnet
    nicnetworks.eth1=internal
    nictypes.ib0=Infiniband
    nictypes.eth0=Ethernet
    nodetype=compute
    os=rhels7.x
    postbootscripts=otherpkgs,HHU/rhel7/postbootscripts/fix_boot.sh,HHU/rhel7/postbootscripts/gpfsRegisterNode.sh,HHU/rhel7/postbootscripts/gpu/public_ip.sh,HHU/rhel7/postbootscripts/gpu/install_nvidia.sh,HHU/rhel7/postbootscripts/gpu/install_cuda.sh,HHU/rhel7/postbootscripts/gpu/install_dcv.sh,HHU/rhel7/postbootscripts/createPbsConfig.sh,HHU/rhel7/postbootscripts/addToObeservium.sh,HHU/rhel7/postbootscripts/checkNodeHealth.sh
    postscripts=remoteshell,syncfiles,confignics --ibaports=1,hardeths,setupntp,HHU/rhel7/postscripts/createMountPoints.sh,HHU/rhel7/postscripts/enableServices.sh,HHU/rhel7/postscripts/gpu/disable_nouveau.sh,HHU/rhel7/postscripts/disableIPv6.sh,HHU/rhel7/postscripts/fixHostname.sh,HHU/rhel7/postscripts/fixRoutes.sh,HHU/rhel7/postscripts/enableSyslog.sh
    power=ipmi
    profile=compute
    provmethod=hilbert_rhel7.x_compute_autoupdate_gpu
    serialport=1
    serialspeed=115200
    status=powering-off
    statustime=10-12-2017 09:21:01
    updatestatus=synced
    updatestatustime=10-11-2017 09:25:32

**Comment by immarvin** [comment]
hi @Phhere , from the node definition you provided, there is no hint for us to tell it's `servers from Bull / Atos from their BullX-Series` you mentioned.

**Comment by Phhere** [comment]
It should be possible to detect theses servers by mac 
Or is it possible to add a new attribute to switch the behavior?

**Comment by immarvin** [comment]
````

MAC Address/OUI | Vendor {Company}
-- | --
08:00:38 | BULL S.A.S.


````
