### ISSUE TITLE
Genesis fails on Boston if IPMI SOL is connected

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4072]
I've only tried this once so far, so I would need to reproduce this before anyone spends too much time researching.  After the petitboot menu, I got the following message:

```
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[   69.345538] kexec_core: Starting new kernel
[   83.295193639,5] OPAL: Switch to big-endian OS
[   85.111588818,5] OPAL: Switch to big-endian OS
 -> smp_release_cpus()
spinning_secondaries = 127
 <- smp_release_cpus()
[    1.887592] Failed to find blacklist at 396000003d290008
[    1.887641] Failed to find blacklist at 396000003d290008
[    1.887671] Failed to find blacklist at 282a000041a00008
[    1.887700] Failed to find blacklist at 396000004800001c
[    1.985857] OFfb vga: enable CONFIG_FB_LITTLE_ENDIAN to support this framebuffer
```

and it just hung there.  Even if I disconnected the SOL it didn't proceed.  I reset the chassis without being connected with SOL and it successfully made it through Genesis.

Has anyone else seen this?

**Comment by whowutwut** [comment]
@mattaezell Sorry, this one slipped through my radar, saw it while cleaning up my email. 

I can do some digging tomorrow on this.  Can you let me know the FW versions on this Boston node that you saw it...  `rinv <node> firm`

If i understand correctly, you had an SOL session open and it hung at that point.  Then you got out of the SOL and rebooted the chassis and it went on OK.

**Comment by mattaezell** [comment]
Hi @whowutwut, this was with the "stock" Big-Endian F26-based Genesis.  We have since moved to a little endian Pegas-based Genesis.  If this bug is even reproducible, it's likely an issue for the firmware team or the kernel team, not xCAT.  As such, I recommend we just close this and I can followup elsewhere if we hit this again.  Thanks!
