### ISSUE TITLE
bmcsetup will hang on firestone 

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#408]
bmcsetup will hang on firestone, rcons can not reconnect to BMC again in the process of running bmcsetup. The command "ipmitool mc reset cold" works well if we run it manually.
The information of hang is following:
Acquiring network addresses..rsyslogd: error: option -c is no longer supported - ignored
Acquired IPv4 address on enP3s1f3: 192.168.5.3/24
ppc64le
                                                         
rm: cannot remove '/tmp/ipmicfg.xml': No such file or directory
/usr/bin/bmcsetup: line 46:  2021 Terminated              allowcred.awk
Auto detecting LAN channel...Detected LAN channel 1
Setting LAN IP Address to 50.4.8.18
Setting LAN Subnet Mask to 255.255.255.0
Set up following user table: 
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1                    false   false      true       ADMINISTRATOR
2   ADMIN            false   false      true       ADMINISTRATOR
Enabling Channel 1: OK
Enabling ARP responses: OK
Enabling IPMI v 1.5 MD5 LAN access:OK
Enabling IPMI v 2.0 LAN access: OK
Enabling SOL for channel 1:OK
Enabling SOL for ADMIN:OK
Resetting BMC ...
Sent cold reset command to MC
Waiting for the BMC to appear ...
Error: No response to keepalive - Terminating session
Console not ready, retrying in 16 seconds (Ctrl-e,c,o to skip delay) 
Info: SOL payload already de-activated
[SOL Session operational.  Use ~? for help]

**Comment by zet809** [comment]
It is not bmcsetup hung, just console is closed when BMC is resetting. After you refresh the console half minute later, the console will be back if the bmc ip is not changed.

**Comment by whowutwut** [comment]
@zet809 Is this not a valid issue? should reject and close?

**Comment by fenggaobj** [comment]
The console will not back on our firestone, but it seems the issue is related to MCP8.1, so close it now.
