### ISSUE TITLE
xcatprobe xcatmn needs improvements

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4092]
The xcatprobe xcatmn needs some improvements.  As I'm running it, here are some of my comments: 

### simplify the call to the probe utility 

We need to provide the network interface name for the utility, and then it checks that the site table is configured with an IP address on the interface.  I feel this is backwards.  It would be so much easier just to be able to run `xcatprobe xcatmn` without any options...

where currently to run it, I have to do... 
* `tabdump site | grep master`
* From that IP, do `ifconfig` or `ip addr show` and look for the interface, then rerun xcatmn with that interface name...

Why not do the following: `xcatprobe xcatmn`
- If site.master is not defined, ERROR stating such...
- If site.master is defined, find the interface and use that one.... 

### xcatprobe xcatmn does not work with complicated networking on the MN

Scaling cluster is a prime example of this... 

```
[root@c699mgt00 ~]# xcatprobe xcatmn -i enP1p12s0f2
[mn]: Checking all xCAT deamons are running...                                                                    [ OK ]
[mn]: Checking xcatd can receive command request...                                                               [ OK ]
[mn]: Checking 'site' table is configured...                                                                      [ OK ]
[mn]: Checking provision network is configured...                                                                 [FAIL]
[mn]: The IP 10.2.100.41
 10.2.100.250 of enP1p12s0f2 doesn't equal the value of 'master' in 'site' table                                  [mn]: IP 10.2.100.41
 10.2.100.250 of enP1p12s0f2 doesn't belong to any network defined in 'networks' table                            =================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [FAIL]
    Checking provision network is configured...                                                                   [FAIL]
        The IP 10.2.100.41
        IP 10.2.100.41
[root@c699mgt00 ~]# tabdump site | grep master
"master","10.2.100.250",,
[root@c699mgt00 ~]# ip addr show enP1p12s0f2
4: enP1p12s0f2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 98:be:94:63:ab:6e brd ff:ff:ff:ff:ff:ff
    inet 10.2.100.41/16 brd 10.2.255.255 scope global enP1p12s0f2
       valid_lft forever preferred_lft forever
    inet 10.2.100.250/16 scope global secondary enP1p12s0f2:0
       valid_lft forever preferred_lft forever
    inet6 fe80::9abe:94ff:fe63:ab6e/64 scope link 
       valid_lft forever preferred_lft forever
```

We should use the `ip` command instead of ifconfig because there can be multiple inets defined.

**Comment by whowutwut** [comment]
Fixing only the first issue quickly would be a huge improvement on usability..

**Comment by hu-weihua** [comment]
@whowutwut, Why we designed a option ``-i`` is we have met such customer many times who plan to use network A as provision network, but for some mistake, they assigned another network ip address to ``master`` attribute in ``site`` table.  So  what ``xcatprobe xcatmn`` to do is to double check if MN work as customer's original design.  If you stand on a engineer who need to debug in customer's environment point of view, that is true, we do need to check ``site`` table then pick up the ip of provision network, then do the rest things. ``xcatmn`` without any option is better option. But if we stand a admin's point of view, admin has change to make mistake for the configuration of ``site`` table.  The original design just exist in admin's mind, so ``xcatmn`` need admin tell it what they really want to do.  In this case, ``-i`` is necessary.

**Comment by hu-weihua** [comment]
@whowutwut, for the second question, yes, you are right, we did not take multiple vlan in one NIC into accouter when we developed ``xcatmn``.  If we need to fix this problem, we have to let customer offer vlan info when they call ``-i`` option, such like ``-i eth0.12`` .

**Comment by whowutwut** [comment]
@hu-weihua  Thanks, yes, I understand the idea for xcatprobe, where we are looking from the point of view of validating xCAT is configured correctly for the intended network.  So, if we intend on having xCAT master be on "eth3" and the site table is configured to an IP on "eth2" we would be able to detect it. 

Recently when running xCAT probe, there's so many networks that the `ifconfig` or `ip addr show` fills more than 1 page, so the process to find the `-i` interface is not as quick as I would like... which is why I opened this..  
* `tabdump site | grep MASTER`
* look at IP from ^, or maybe look at `tabdump networks`
* `ifconfig` or `ip addr show` to find the interface name
* since it's not `eth0`, `eth1` need to copy/paste the interface name back into xcatprobe command

But really, I want to check other things, I know xCAT is configured to the correct network, but I want to probe to see if anything else that was changed is affected on the MN.  For example, the UDP issue...  

What about if we had an option... if `-i` is specified, we use that, if not we check the configuration based on the value in the site table...

```
xcatprobe xcatmn
INFO: No interface provided, detected site table IP attribute, 10.5.28.1.  Checking xCAT configuration using interface: enP4p1s0.  
INFO: If this is incorrect, rerun with -i <ifname> option
```
That `INFO` could also be `WARNING:`

**Comment by hu-weihua** [comment]
@whowutwut , I have updated ``xcatmn`` depending on your new requirements. I did UT on briggs01, but I can't test it on ``c699mgt00`` due to command right problem. I extracted some code to small script and run them on ``c699mgt00``, they worked.  I suppose the change work. @xuweibj is reviewing the PR #4113 now. If the PR is merged, could you try it again? If there is any problem, please let me know. thanks.

**Comment by whowutwut** [comment]
👍  Thanks @hu-weihua !
