### ISSUE TITLE
[OpenBMC] In later FW, seems like when we reboot after setting BMC=dhcp, its unable to get REST response

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4105]
I've been seeing this timeout when setting rspconfig ip=dhcp...

```
[root@briggs01 p9]# rspconfig mid05tor12cn05 ip=dhcp
mid05tor12cn05: BMC Setting IP to DHCP...
mid05tor12cn05: Error: 504 Gateway Timeout
```

The reboot actually happens, so that's good, but if the reboot happens too quicky and we can't get a response from REST, then we should just not have this 2nd call...

I will run some more tests on this during verification of #3908 and see if it occurs across a node range.

**Comment by whowutwut** [comment]
Running again, it worked: 
```
[root@briggs01 common]# rspconfig mid05tor12cn05 ip=dhcp
mid05tor12cn05: BMC Setting IP to DHCP...
mid05tor12cn05: BMC reboot```

**Comment by xuweibj** [comment]
I think this is the same with #3832, sometime firmware run reboot directly and did not return response.

**Comment by whowutwut** [comment]
@xuweibj  Ok, thanks for that insight.  If it's not consistent, then perhaps it's better to not print the 2nd response output and just have something like: 

`mid05tor12cn05: BMC Setting IP to DHCP and reboot BMC`

**Comment by whowutwut** [comment]
The real issue is https://github.com/openbmc/openbmc/issues/2241 and if that is fixed by OpenBMC , xCAT should respond correctly, so instead of hiding this message, Firmware team agreed to fix it. 

No issue here for xCAT, wait for the above to close out and it should resolve itself.

**Comment by whowutwut** [comment]
When the fix is verified in a driver, we should indicate which xCAT release it matches up with for the benefits of our users

**Comment by whowutwut** [comment]
Seems like OpenBMC team said it's not that easy for them to fix this... looking at other options. 
This is caused by the `bmcreboot` command being sent to the BMC and really it's actually sent and because the BMC starts to shut down, the response isn't completely sent back OK and we get this 504 timeout. 

So the normal output should be: 

```
rpower <range> bmcreboot
cn01: BMC reboot
cn02: BMC reboot
```

Not sure if we should hide this 100%, but instead if printing a response ERROR: 

```
rpower <range> bmcreboot
cn01: BMC reboot
cn02: Error: 504 Gateway Timeout
```

Considering changing the response message to: 
```
rpower <range> bmcreboot
cn01: BMC reboot
cn02: BMC reboot [504 response]
```

Or should we just hide it, or star it....  

```
rpower <range> bmcreboot
cn01: BMC reboot
cn02: BMC reboot *
```

In testing, it seems the BMCReboot call 100% will reboot the BMC, but the API response is not that great in getting us 200 OK...

**Comment by whowutwut** [comment]
@zet809 @xuweibj @chenglch. I'm going to create a PR and can you answer with your vote on the format?
