### ISSUE TITLE
bmcsetup on Witherspoon

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4106]
When we discovered a Witherspoon node, we noticed that it came up the default root password.  Has anyone validated `bmcsetup` on Witherspoon?

```
# updatenode time1 -P bmcsetup
time1: xcatdsklspost: downloaded postscripts successfully
time1: Sun Oct 15 20:16:26 EDT 2017 Running postscript: bmcsetup
time1: ipmitool version 1.8.18
time1: Invalid channel: 16
time1:

time1: ./bmcsetup: line 150:  5929 Terminated              allowcred.awk
time1: bmcsetup: BMC Information obtained from xCAT
time1: bmcsetup: NUMBMCS=1 ==> BMC IP=REDACTED/255.255.224.0, GW=REDACTED, VLAN=off
time1: bmcsetup: IPMIVER=2.0, IPMIMFG=42817, XPROD=16975
time1: bmcsetup: Auto detecting LAN channel...
time1: bmcsetup: Detected LAN channel 1
time1: Setting LAN IP Address to REDACTED
time1: Setting LAN Subnet Mask to 255.255.224.0
time1: Setting LAN Default Gateway IP to REDACTED
time1:
time1: IPMI command failed: Command response could not be provided
time1: Unable to Set Channel Access(volatile) for channel 1
time1: postscript: bmcsetup exited with code 0
time1: Running of postscripts has completed.
```

Does `OpenBMC` support this with its ipmi?  On the actual node:
```
# ipmitool user list 1
IPMI command failed: Invalid command
```

**Comment by whowutwut** [comment]
@mattaezell  Yes, bmcsetup does work, but I don't know if we ran it as updatenode.  (@zet809  FYI) There's quite a few moving parts...  I wasn't aware that you had any Witherspoon boxes yet...

Which processor version do you have?  At DD 2.01, there's an issue with the xCAT genesis kernel based on Fedora26, so we would need you to build `xCAT-genesis-base` on the PEGAS OS (https://github.com/xcat2/xcat-core/issues/3870) ,but seems like you may not be running the xCAT genesis kernel, looks like you have an OS installed already. 

What version of xCAT are you currently running? (lsxcatd -v)
And can you provide the output of `rinv time1 firm -V`, so i can check the level of FW you have on the Witherspoon node... 

The output of:
```
time1:
time1: IPMI command failed: Command response could not be provided
time1: Unable to Set Channel Access(volatile) for channel 1
``` 

Is due to the `ipmitool access on` call that we make from bmcsetup, at a later version of the firmware, we changed it back from a raw command to `access on` in https://github.com/xcat2/xcat-core/pull/3833  so I want to validate which version of the OpenBMC firmware you are running with, if you have not updated to some later version, we might be seeing some xCAT code/FW code mismatch...  

The OpenBMC team has not yet supported non root user.. I don't believe.  @bradbishop, can you comment?   I will also check with him tomorrow if I don't see anything here... This issue has been open for some time now: https://github.com/openbmc/openbmc/issues/813   xCAT didn't specifically open an issue in that repo for that, but it was on our list of items that we had interlocked..

**Comment by bradbishop** [comment]
The OpenBMC REST API for changing the password of the root console user just went in, so that support would be missing here.

At the moment OpenBMC does not have any user management support via REST, IPMI or any other interface, other than changing the root console user password (REST only).

**Comment by mattaezell** [comment]
@whowutwut We have a very small quantity of DD2.0 (maybe 2.01? not sure) Witherspoons on loan from IBM.  We did bring it up and discover it using genesis.  OpenBMC is running `ibm-v1.99.10-0-r11-0-g9c65260` and PNOR is `IBM-witherspoon-ibm-OP9_v1.19_1.52`.  We've been given access to newer firmware, but we lost access to one BMC so we've been gun-shy about updating the others.  If we need them newer, let me know and I can push for that.

```
# rinv time1 firm -V
time1: [mgmt1]: BMC Firmware Product: ibm-v1.99.10-0-r7-0-gcce0f1b (Active)
time1: [mgmt1]: BMC Firmware Product: ibm-v1.99.10-0-r11-0-g9c65260 (Active)*
time1: [mgmt1]: HOST Firmware Product: IBM-witherspoon-sequoia-ibm-OP9_v1.19_1.41 (Active)
time1: [mgmt1]: HOST Firmware Product: -- additional info: buildroot-2017.8-6-g319c6e1
time1: [mgmt1]: HOST Firmware Product: -- additional info: capp-ucode-9c73e9f
time1: [mgmt1]: HOST Firmware Product: -- additional info: hostboot-3d6c541
time1: [mgmt1]: HOST Firmware Product: -- additional info: hostboot-binaries-edd568f
time1: [mgmt1]: HOST Firmware Product: -- additional info: linux-4.13-openpower1-p1b975d8
time1: [mgmt1]: HOST Firmware Product: -- additional info: machine-xml-f8aaa73-p3357dc
time1: [mgmt1]: HOST Firmware Product: -- additional info: occ-a43395b
time1: [mgmt1]: HOST Firmware Product: -- additional info: op-build-v1.7-1383-g487ffd1
time1: [mgmt1]: HOST Firmware Product: -- additional info: petitboot-v1.5.1-p65d605b
time1: [mgmt1]: HOST Firmware Product: -- additional info: sbe-8d90ab2
time1: [mgmt1]: HOST Firmware Product: -- additional info: skiboot-v5.8-90-g398a98123641-pb7fe7a5
time1: [mgmt1]: HOST Firmware Product: IBM-witherspoon-ibm-OP9_v1.19_1.52 (Active)*
time1: [mgmt1]: HOST Firmware Product: -- additional info: buildroot-2017.8-6-g319c6e1
time1: [mgmt1]: HOST Firmware Product: -- additional info: capp-ucode-p9-dd2-v1
time1: [mgmt1]: HOST Firmware Product: -- additional info: hostboot-8e7e2ad
time1: [mgmt1]: HOST Firmware Product: -- additional info: hostboot-binaries-b7d8417
time1: [mgmt1]: HOST Firmware Product: -- additional info: linux-4.13.4-openpower1-p1c668f0
time1: [mgmt1]: HOST Firmware Product: -- additional info: machine-xml-1bd247d-p7c6c471
time1: [mgmt1]: HOST Firmware Product: -- additional info: occ-60c9cd
time1: [mgmt1]: HOST Firmware Product: -- additional info: op-build-v1.7-1421-g2f4cbfe
time1: [mgmt1]: HOST Firmware Product: -- additional info: petitboot-v1.6.0-p85a1eab
time1: [mgmt1]: HOST Firmware Product: -- additional info: sbe-ff713df
time1: [mgmt1]: HOST Firmware Product: -- additional info: skiboot-v5.8-130-g712837cedca0
```

We are using xCAT 2.13.7.  We have considered pulling nightlies but haven't run into anything yet that has forced our hand.  If you think we need something newer, let us know.

```
# lsxcatd -v
Version 2.13.7 (git commit 9ec6d0c0cce9f61a078a4dcd044927f5a65a606f, built Fri Sep 22 02:16:45 EDT 2017)
```

We are OK using the 'root' user for the bmc, but need to (eventually) set a non-default password.

**Comment by zet809** [comment]
hi, @mattaezell , so you mean you can access the OpenBMC with newer firmware before, then loss the connection? What happened? The IP of OpenBMC is changed? Can you access the host OS? Can you use `ipmitool lan print 1` to get the BMC network configuration information?

**Comment by mattaezell** [comment]
@zet809 We flashed one node to `ibm-v1.99.10-0-r13-0-g076c283`, but the BMC was having connectivity problems.  I was able to ping it, but it would not respond over SSH or https/REST.  We left it unplugged over the weekend, and this morning we were able to talk to it again.  I set `ibm-v1.99.10-0-r11-0-g9c65260` back as active until we can better understand what happened.  

But that issue is unrelated to the problem this issue was opened for.  As @bradbishop said, the firmware doesn't support user management through the inband ipmi interface yet.

**Comment by zet809** [comment]
OK, yes, the `ipmitool user list 1` is not supported yet against OpenBMC.

**Comment by whowutwut** [comment]
@mattaezell Just to update you on this, talking to FW team, the ability to change the root password code was merged but will not be in a driver until sometime in Nov... not the early ship driver. 

I opened https://github.com/xcat2/xcat-core/issues/4196 to work on the function that needs to be added into xCAT to support this.

**Comment by mattaezell** [comment]
Thanks for the update @whowutwut!

**Comment by immarvin** [comment]
can this be closed? @mattaezell @whowutwut @zet809

**Comment by mattaezell** [comment]
OK with me to close

**Comment by zet809** [comment]
Thx，let's close this issue.
