### ISSUE TITLE
[OpenBMC] Support display of "Really" active firmware 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4111]
The issue here is when we activate the FW, the priority is set to 0.  Which indicates the FW that will be applied on the next boot.  However, without any way to tell what is "really" running, we can't help the ADMIN identify which pieces require rebooting (BMC or Host) so that the BMC or PNOR updates are REALLY applied 

With the 1742 firmware driver, the decorator attribute is available.  I'm still having a problem understanding how these attributes are really described by the API to code against it before the code appears in the firmware, but anyway... 

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Decorator/OperationalStatus.interface.yaml

No references to it in the Network API README.md...  

Here's what it looks like: 

```
[root@briggs01 p9]#  curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.11.139.11/xyz/openbmc_project/software/functional
{
  "data": {
    "endpoints": [
      "/xyz/openbmc_project/software/12913e05", 
      "/xyz/openbmc_project/software/390e9d0f"
    ]
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

So need to design externals for supporting this...  Thinking about it....  here's what it looks like today

```
[root@briggs01 p9]#rflash mid05tor12cn11 -l
mid05tor12cn11: ID       Purpose State      Version
mid05tor12cn11: -------------------------------------------------------
mid05tor12cn11: 9e55358e BMC     Active     ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn11: 221d9020 Host    Active     IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
mid05tor12cn11: 12913e05 BMC     Active(*)  ibm-v1.99.10-113-g65edf7d-r1-0-g84427f0
mid05tor12cn11: 390e9d0f Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.62
mid05tor12cn11: 
```

**Comment by whowutwut** [comment]
So `(*)` today indicates the firmware at Priority=0, so the one that is intended to be run. 
However, if the functional reply does not match that one, then it means that it's NOT really active active....

I'd rather not change the meaning of the `(*)` since we have users that are growing accustomed to it.... so I think the code logic is: 

1. If functional is present in the API, those are marked with `(*)`. 
2. If there is a firmware that is Priority 0, and does not match the list in functional, then `(pending)`, or `(nextboot)` or `(+)`.  

Pending: 
```
[root@briggs01 p9]#rflash mid05tor12cn11 -l
mid05tor12cn11: ID       Purpose State           Version
mid05tor12cn11: ------------------------------------------------------------
mid05tor12cn11: 9e55358e BMC     Active(*)       ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn11: 221d9020 Host    Active          IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
mid05tor12cn11: 12913e05 BMC     Active(pending) ibm-v1.99.10-113-g65edf7d-r1-0-g84427f0
mid05tor12cn11: 390e9d0f Host    Active(*)       IBM-witherspoon-ibm-OP9_v1.19_1.62
mid05tor12cn11: 
```

Nextboot
```
[root@briggs01 p9]#rflash mid05tor12cn11 -l
mid05tor12cn11: ID       Purpose State            Version
mid05tor12cn11: -------------------------------------------------------------
mid05tor12cn11: 9e55358e BMC     Active(*)        ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn11: 221d9020 Host    Active           IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
mid05tor12cn11: 12913e05 BMC     Active(nextboot) ibm-v1.99.10-113-g65edf7d-r1-0-g84427f0
mid05tor12cn11: 390e9d0f Host    Active(*)        IBM-witherspoon-ibm-OP9_v1.19_1.62
mid05tor12cn11: 
```

Or `(+)`.... 
```
[root@briggs01 p9]#rflash mid05tor12cn11 -l
mid05tor12cn11: ID       Purpose State      Version
mid05tor12cn11: -------------------------------------------------------
mid05tor12cn11: 9e55358e BMC     Active(*)  ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn11: 221d9020 Host    Active     IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
mid05tor12cn11: 12913e05 BMC     Active(+)  ibm-v1.99.10-113-g65edf7d-r1-0-g84427f0
mid05tor12cn11: 390e9d0f Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.62
mid05tor12cn11: 
```


`rinv <node> firm` code also has to be changed to have the "really" active display as `rinv <> firm` and all of them to be displayed with the -V option.  This should be a little easier since the functional firmware should be the only one returned. 

Need to of course support backwards compatibility for systems not yet at 1742 firmware levels.

**Comment by whowutwut** [comment]
Or.....   just get rid of the `(*)` completely... and use text... 

```
[root@briggs01 p9]#rflash mid05tor12cn11 -l
mid05tor12cn11: ID       Purpose State            Version
mid05tor12cn11: -------------------------------------------------------------
mid05tor12cn11: 9e55358e BMC     Active(current)  ibm-v1.99.10-0-r11-0-g9c65260
mid05tor12cn11: 221d9020 Host    Active           IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
mid05tor12cn11: 12913e05 BMC     Active(nextboot) ibm-v1.99.10-113-g65edf7d-r1-0-g84427f0
mid05tor12cn11: 390e9d0f Host    Active(current)  IBM-witherspoon-ibm-OP9_v1.19_1.62
mid05tor12cn11: 
```

Thoughts?

**Comment by immarvin** [comment]
hi @xuweibj @zet809 , would you please take a look at this? thanks

**Comment by xuweibj** [comment]
I think I prefer "pending". What's your opinion? @zet809

**Comment by zet809** [comment]
hi, @whowutwut , as you have mentioned that we have users that are growing accustomed to "*" for `current`, I think `+`  can be used to map "nextboot".
