### ISSUE TITLE
[OpenBMC] If user compiles sshpass instead of downloading from EPEL, may be in different location

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4123]
If user compiles sshpass from source, it may be in a different location: 

```
[root@iodxcat xcat]# which sshpass
/usr/local/bin/sshpass
[root@iodxcat xcat]# 
```

Instead of hard code path in `/opt/xcat/share/xcat/cons/openbmc` , see if it's available.

**Comment by whowutwut** [comment]
@zet809 This was suppose to be a really simple fix...    We can do something like this and it would fix the problem that occurred... 

```
use File::Which; 

my $sshpass_path = which `sshpass`;
if (-x $sshpass_path) { 
   old code... 
} 
```

If that is changed, then we won't have the problem where if users complied sshpass and it's not in the normal hard coded path that we used.  go conserver is an alternate, but this is a 3 line change..  that would fix the problem...

**Comment by whowutwut** [comment]
Ok it might be more code since File::Which is not always avail on the node.  Will see if I can make a quick fix for this.

**Comment by zet809** [comment]
Hi, @whowutwut , shall we close this task since goconserver cover the ssh session for openbmc?

**Comment by whowutwut** [comment]
sure, let's close
