### ISSUE TITLE
syncfiles reports success despite critical errors

### ISSUE THREAD

**Issue by robers97** [xcat2/xcat-core#4136]
This indicates that file synchronization completed.  However it did not due to some error I haven't figured out.  Likely some credential mismatch with the service node??  Anyway this error is too silent.

(0) root @ xcat1: /tmp
# updatenode cn03 -F
cn03: Permission denied, please try again.
cn03: Permission denied, please try again.
cn03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cn03: Permission denied, please try again.
cn03: Permission denied, please try again.
cn03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cn03: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
cn03: rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
cn03: Permission denied, please try again.
cn03: Permission denied, please try again.
cn03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cn03: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
cn03: rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
File synchronization has completed for nodes.

(1) root @ xcat1: /tmp

**Comment by immarvin** [comment]
can you ssh cn03 without password?

**Comment by immarvin** [comment]
close this ticket due to no update over 2 weeks, please reopen it if any update
