### ISSUE TITLE
Investigation how to support kinda of version control for osimage

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4155]
the files under version control should include pkglist,otherokglist files which cannot be observed in osimage definition

**Comment by robin2008** [comment]
Here are some brief summary of our discussion about the feature:

1, `osimage` object will contains both attributes in DB and also attributes in text files. Those information could be easily exported/imported to/from one file or some files (Yaml/JSON,  or something like the format of Dockerfile)
In that, Admin could easily manage it with their own version control tools and share with others. 

Constraints:  TBD 
 - The OS distro ISO, Other software package binaries, customized self-build initrd is still not in consideration. (Maybe Repository management in future)
 - How to handle User provided postscripts

2, To create an `osimage`, better to create a new dedicate directory for it and the directory contains all its required files. For example:
```
/install/osimage_repo/rhels7.3-ppc64le-netboot-service
exlist
otherpkgs.pkglist
os.pkglist
postinstall
partition
...
```

Here those files will refer to the built-in files shipped by xCAT, and user could add their own, just like:
```
INCLUDE:/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.exlist
/myexclude
...

```
Note: it is not recommend that user change the default files shipped by xCAT as it might impact xCAT function. If they want to that, he must remove 
the INCLUDE and provide full contents.

3, An easy way to copy or rename an osimage (deep clone), a copy will make a new directory, and the copied osimage may not have relation ship with the source. A renamed osimage will also have a renamed directory, and all things will be pointed to the new directory without user intervene. 

 TBD : what's the impact to existing nodes if rename its osimage?

4, Stageing or Snapshot of the osimage.

Simple option:
- copy from the existing osimage A -> A1
- make modification on A1 -> A1'
- nodeset a little nodes with A1' and test it
- Apply A1' -> A

If the changes does not impact node's boot configuration (for example, kernel params), then the appliance will be done quickly without touch nodes. 

There might be more complicate method to make something like `revision`, or `tagging`. It requires more investigation there.

**Comment by daniceexi** [comment]
👍 
Looks like we need introduce a new command to handle the osimage change/rename/copy. And we may just consider diskless in the first stage.

**Comment by cxhong** [comment]
can we also consider to add cuda, kits or ofed to base image? something like:
makeimage --base rhels_base_image --cuda  cuda.iso

**Comment by robin2008** [comment]
`kit` might not be in our consideration as more new things merging for application configuration.

CUDA and OFED is still HPC key component, we could have user friendly way to handle it. But it should be based on the current idea.
