### ISSUE TITLE
summarize nics/hosts table related issues and make a Q/A list

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#4157]
1, summarize nics/hosts table for hostnames related issues
       * some questions from xcat-user mailing list
       * #4082 
       * #4078 
       * #4080 
       * #2142
       * #3676 
       * #3242
       * #3676
       ... ...
2, analyze reason and category the problem

**Comment by bybai** [comment]
status:

**Comment by bybai** [comment]
status:

**Comment by bybai** [comment]
status:  analyze about 70%;  
problems categories are(in progress):
1, same hostname in different domains
2, define a host with teaming nics
3, create records in /etc/hosts for different nics, how to use nics.nichostnamesuffixes and nics.aliases
4, use hosts table and nics table to create hostnames for different networks, the differences among hosts.hostnames, hosts.otherinterfaces, nics.aliases
5, if makedns can work well or not after makehosts command, related to configure nameservers and domain, including /etc/resolv.conf, site.domain, networks.domain, site.nameservers, networks.nameservers
6, when duplicate records found in /etc/hosts, there are no warning messages in makehosts
7, makehosts performance

**Comment by bybai** [comment]
Summary:
Open #4270 to make a Q/A list for makehosts;
Plan to fix #2142 to support same hostname in different domains without any suffix

Low priority issues:
#4080 makehosts does not warn when there are duplicate records
#4082 makehosts performance

Long term concerns:
Will consider a better way to layout the nics data in configuration management, since nics table is complex and is easy to make mistakes.

**Comment by whowutwut** [comment]
@bybai Why not create an EPIC task and then link in the issues using that and zenhub?

**Comment by bybai** [comment]
@whowutwut , that's a good idea, I opened a EPIC task #4280, and put all related issues under it. Thanks
