### ISSUE TITLE
Diskfull installation does not contain NODE= in /opt/xcat/xcatinfo

### ISSUE THREAD

**Issue by tgooding** [xcat2/xcat-core#4169]
I tried a diskfull node installation and the resulting installation produced an `/opt/xcat/xcatinfo` file that did not contain this line:
```
    NODE=<hostname>
```

We have other pieces of software are depending on xcatinfo for a consistent node name to reference back to xCAT.  

Running xCAT release `snap201710110615`.

Let me know if you need other info from the system.  Thanks!  Tom

**Comment by whowutwut** [comment]
@cxhong Were you going to fix this one?

**Comment by whowutwut** [comment]
Closing this out as it was merged into 2.13.8, @tgooding please open a new issue if you see problems after upgrading to the latest build.
