### ISSUE TITLE
Reduce the amount of logs generated into the commands.log file for console

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4172]
Each node is creating a entry into the commands.log file for console and will quickly fill up. 

```
====================================================
[Date]       2017-10-23 03:34:02
[ClientType] cli
[Request]    getopenbmccons mid05tor12cn08 text
[Response]
mid05tor12cn08: openbmc, getopenbmccoms
mid05tor12cn08
[ElapsedTime] 0 s
```

* Is there a way to reduce this by? 
* Why do we need this command to get logged, what benefits does it provide?

**Comment by hu-weihua** [comment]
@whowutwut, When design ``commands.log `` long time ago,  the purpose is to log the output of all command from CLI or Restapi.  But due to xcat itself may trigger some command which also send to xcatd like CLI during it's lift cycle, there is no flag to let ``commands.log `` to distinguish which command really come from CLI and which come from xcat itself.  So  ``commands.log `` log almost all of them.   But when I implemented ``commands.log ``, I have noticed some command logs are  useless but with high rate， I have filtered them out, such like below

```
   3507     $tmpreq =~ s/\[Request\]\s+(.+)/$1/g;
   3508     if ($tmpreq =~ /getipmicons/) { return 1; }
   3509     if ($tmpreq =~ /getcons/)     { return 1; }
```
``getopenbmccons`` was developed later than ``commands.log``, so it was not added into filter list.   If need, we can add it.

**Comment by hu-weihua** [comment]
@whowutwut  @zet809 @chenglch,  do you think we should add ``getopenbmccons`` into filter list as ``getipmicons``? If we agree that, I will add it ASAP. thanks.

**Comment by mattaezell** [comment]
@hu-weihua 👍 Please!

**Comment by whowutwut** [comment]
@hu-weihua Yes, please add it into the filter list, I don't think there's any value to that log message!

**Comment by hu-weihua** [comment]
@whowutwut, the fix has been merged. Could you try again? thanks

**Comment by whowutwut** [comment]
@hu-weihua  Updated to todays build and the logs are no longer there in commands.log. This is good 👍 

```
[root@briggs01 xcat]# lsxcatd -v
Version 2.13.8 (git commit 2353abb48a6ea72affc2ecacafb353bec02b3d79, built Wed Oct 25 06:15:45 EDT 2017)
[root@briggs01 xcat]#
[root@briggs01 xcat]# date
Wed Oct 25 11:23:41 EDT 2017
[root@briggs01 xcat]# tail -f commands.log | grep openbmc
^C
[root@briggs01 xcat]# date
Wed Oct 25 11:24:31 EDT 2017
```


On a similar note, in cluster.log, we also get this message that just fills up the logs:
```
 Oct 25 11:26:57 briggs01 xcat[97664]: xCAT: Allowing getopenbmccons to mid05tor12cn09 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97674]: xCAT: Allowing getopenbmccons to mid05tor12cn03 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97678]: xCAT: Allowing getopenbmccons to mid05tor12cn01 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97688]: xCAT: Allowing getopenbmccons to mid05tor12cn10 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97695]: xCAT: Allowing getopenbmccons to mid05tor12cn14 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97701]: xCAT: Allowing getopenbmccons to mid05tor12cn04 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97708]: xCAT: Allowing getopenbmccons to mid05tor12cn06 text for root from localhost
Oct 25 11:26:59 briggs01 xcat[97713]: xCAT: Allowing getopenbmccons to mid05tor12cn07 text for root from localhost
Oct 25 11:27:00 briggs01 xcat[97720]: xCAT: Allowing getopenbmccons to mid05tor12cn12 text for root from localhost
Oct 25 11:27:00 briggs01 xcat[97727]: xCAT: Allowing getopenbmccons to mid05tor12cn08 text for root from localhost
Oct 25 11:27:01 briggs01 xcat[97736]: xCAT: Allowing getopenbmccons to mid05tor12cn09 text for root from localhost
Oct 25 11:27:02 briggs01 xcat[97746]: xCAT: Allowing getopenbmccons to mid05tor12cn03 text for root from localhost
Oct 25 11:27:02 briggs01 xcat[97750]: xCAT: Allowing getopenbmccons to mid05tor12cn01 text for root from localhost
Oct 25 11:27:02 briggs01 xcat[97760]: xCAT: Allowing getopenbmccons to mid05tor12cn10 text for root from localhost
```

Looking at the last 500 lines...
```
[root@briggs01 xcat]# tail cluster.log -n 500 | grep "Allowing getopenbmccons" | wc
    500    7500   57500
```

Is there anything we can do there, is there value in logging this...   it's just too much I think.

**Comment by hu-weihua** [comment]
@whowutwut , This kind of logs come from ``policy`` process.  It will log all commands which is ``xCAT: Allowing`` or ``xCAT: Denying`` into syslog for audit.  If you don't want such audit log, you can close it in ``site`` table, just set ``auditnosyslog=1``. But it will close audit for all command.

If we just do not want to audit ``getopenbmccons``, we need add filter in below code. 

``~/xCAT-server/lib/perl/xCAT/xcatd.pm``
```
    262                 my $skipsyslog = 0; # default is to write all commands to auditlog and syslog
    263                 if (defined($auditnosyslog)) {
    264                     $skipsyslog = $auditnosyslog; # take setting from site table,  1 means no syslog
    265                 }
    ....
    295                     if ($skipsyslog == 0) {    # write to syslog and auditlog
    296                         $rsp->{syslogdata}->[0] = $logst;   # put in syslog data
    297                     }
    ......
```
**But it is a good option to hard code a filter list in the policy process?**

**Comment by whowutwut** [comment]
@hu-weihua @chenglch  Also talking about this in another thread, how come that `getopenbmnccons` needs to run so often.. i guess that is my question.

**Comment by chenglch** [comment]
@whowutwut , this script runs by `conserver` as the console session could not be established. `conserver` will send the `getopenbmnccons` request to xcat and try to setup console session again automatically.

**Comment by whowutwut** [comment]
@chenglch  Thanks! :thumbsup:  With your comment, I just realized it was the nodes that are not real that are generating that message into /var/log/xcat/console. 

Once I removed them all with `makeconservercf -d <node>` the frequent logging messages stopped.  This is good...

On the `makeconservercf -d` it re-runs the console for all nodes:
```
Oct 30 10:25:28 briggs01 xcat[80717]: xCAT: Allowing makeconservercf to mid05tor12cn04 -d for root from localhost
Oct 30 10:25:29 briggs01 xcat[80808]: xCAT: Allowing getopenbmccons to mid05tor12cn18 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80814]: xCAT: Allowing getopenbmccons to mid05tor12cn05 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80819]: xCAT: Allowing getopenbmccons to mid05tor12cn11 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80825]: xCAT: Allowing getopenbmccons to mid05tor12cn15 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80829]: xCAT: Allowing getopenbmccons to mid05tor12cn02 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80835]: xCAT: Allowing getopenbmccons to mid05tor12cn13 text for root from localhost
Oct 30 10:25:29 briggs01 xcat[80838]: xCAT: Allowing getopenbmccons to mid05tor12cn17 text for root from localhost
Oct 30 10:25:30 briggs01 xcat[80844]: xCAT: Allowing getopenbmccons to mid05tor12cn16 text for root from localhost

```

Did we have an issue there that was resolved?

**Comment by hu-weihua** [comment]
@whowutwut , I logged a ``Q&A`` issue #4241  for this problem. It may help for other people who hit the same problem.

**Comment by whowutwut** [comment]
@hu-weihua This just removed the logs, when I set xcatdebugmode=1 , There are still requests....

So I think we just hit the issue...
```
Nov 15 09:31:58 briggs01 xcat[117040]: DEBUG xcatd: connection from root@localhost
Nov 15 09:31:58 briggs01 xcat[117040]: DEBUG xcatd: open new process : xcatd SSL: getopenbmccons to node-8335-gtc-781923a for root@localhost
Nov 15 09:32:00 briggs01 xcat[116993]: DEBUG xcatd: close connection with root@localhost
Nov 15 09:32:11 briggs01 xcat[117044]: DEBUG xcatd: connection from root@localhost
Nov 15 09:32:11 briggs01 xcat[117044]: DEBUG xcatd: open new process : xcatd SSL: getopenbmccons to node-8335-gtc-1318c4a for root@localhost
Nov 15 09:32:12 briggs01 xcat[117040]: DEBUG xcatd: close connection with root@localhost
```

We need to fix #4293 to resolve this.. but this just hit the issue, we are still having a lot of connection opening/closing... and hiding this would raise "Why is xCATd so busy?..." and we don't see this ...

**Comment by hu-weihua** [comment]
@whowutwut , Just as you mentioned, add ``Q&A`` for #4241 is not suitable. I have closed that issue. thanks.

**Comment by whowutwut** [comment]
Closing this out, we have some other issues tracking the console connections.
