### ISSUE TITLE
setroute postscript had an error but returned 0 so the overall boot status does not fail.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#4181]
setroute postscript had an error but returned 0 so the overall boot status does not fail.

```
[root@c699mgt00 jenkins]# updatenode c699login01 --scripts=setroute
c699login01: xcatdsklspost: downloaded postscripts successfully    
c699login01: Wed Oct 25 16:31:54 EDT 2017 Running postscript: setroute
c699login01: Error: invalid format of netmask .                       
c699login01: postscript: setroute exited with code 0                  
c699login01: Running of postscripts has completed.                    
```

the return code for postscript with an error should not be zero.

**Comment by bybai** [comment]
Hi @ralphbellofatto , thanks you issue this. In the past, some scripts always return 0, it is an old issue. Currently, if we hit it, we start to enhance them. Will put this issue in our latest plan to fix it.

**Comment by bybai** [comment]
`setroute` calls `routeop`, so here should consider `routeop` return code too.
