### ISSUE TITLE
KVM nodes have terrible default cpu model

### ISSUE THREAD

**Issue by jonathanmills** [xcat2/xcat-core#4182]
I apologize if I've missed the mark on this one.  I have looked all over to try to find a way to explicitly set (in xCAT definitions) the cpu instruction flags for the libvirt xml created by xCAT for its KVM nodes (which it shoves into the kvm_nodedata table).  Long story short, I can't find a way to do it, short of hacking something into kvm.pm.

Here's an example of what I'm talking about:

These are CPU flags on a hypervisor of mine (as seen in `lscpu`):

> Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida arat

And here are the CPU flags in a xCAT-created KVM vm running on that same hypervisor:

> Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology pni cx16 x2apic hypervisor lahf_lm

So you can see, that's rather a huge difference.  Those cpu flags are the conservative 'hypervisor default' that libvirt chose in the absence of any better guidance.  I think xCAT needs to do something more sensible by default.  And I think that the sane default should be the 'host-model' cpu instruction set flags simply passed up to the VM.  In terms of libvirt XML, the code to do that would look just like this:
```
<cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
</cpu>
```
 which typically would come right after the `<features>` section.

I hope you consider my recommendation here.

**Comment by immarvin** [comment]
hi @jonathanmills ,we will have a discussion on this

attach the doc url https://libvirt.org/formatdomain.html#elementsCPU here as a background for discussion

**Comment by samveen** [comment]
@jonathanmills I  faced the same issue in in our environment: we had to work around it with the following steps:
- `chdef -t site clustersite persistkvmguests=yes`
- create the VM as per usual process `mkdef...`, `chdef ...`, `mkvm...`.
- power down the vm `rpower $VM off`
- Then run the following against the sed command against the VM's domain XML on the vm.host:
```
export EDITOR="sed -i '"'s#\(</os>\)$#\1\n  <cpu mode='"'\"'custom'\"'"' match='"'\"'exact'\"'"'>\n    <model fallback='"'\"'forbid'\"'"'>SandyBridge</model>\n  </cpu>#'"'"  ; virsh edit vm-0999
```

**Comment by whowutwut** [comment]
@immarvin Is there a way that we could more easily take defaults that libvirt would use to create a new VM, there must have been some hard coded defaults in kvm.pm that are now out of date, but to reduce the overhead, there has to be a better way to accept defaults so that changes are not needed to be made in kvm.pm to keep the xCAT code up to the latest... 

Also what @samveen is a good work around, but what about something that could be passed into mkvm, in XML we could then shove into the VM XML file, to make this a little easier for the users.

**Comment by immarvin** [comment]
hi @whowutwut ,  this is also a pain point for us from the developer's perspective. 

The difficulty is that libvirt has tons elements and attributes in xml (https://libvirt.org/format.html), we abstract several major attribute among them to be xcat kvm node attributes, and hard coded several of them in kvm.pm. 

We cannot add each node attribute for them, so  it is almost infeasible to represent too many kvm attributes in the node attribute. In fact, for some new attributes required by customer, we have tried to tell user to specify them in  "kvm.othersettings", but since  the code to add each element and attribute into the xml, which is generatec by xcat  and feed to libvirt, is different, we still have to modify kvm.pm to support each new attribute.

**Comment by immarvin** [comment]
hi @chenglch , do you know how open stack handle the complexity of  kvm attribute user interface?

**Comment by chenglch** [comment]
@immarvin , openstack handle the attribute in DOM with the python library below:
```
from lxml import etree
```
Even with this, it is very complex.

**Comment by immarvin** [comment]
the method @samveen provided, modifying the kvmnodedata table,   is also the way how I customize the kvm guest definition during my work, maybe we can consider to make this way more smoothly. This method requires user have some knowledge on the kvm domain xml

**Comment by whowutwut** [comment]
What about if an xml snip can be provided by the user in a file and we inject it into the XML? 

making this up...
```
lsdef vm01 -i vm.xmlconfig
vm01: 
    vm.xmlconfig=/path/to/vm/config.xml
```

Then if that is specified, we inject the contents into some place in the kvm node attributes when we run `mkvm`, but this might not work if we are creating using libvirt., then saving the xml to KVM nodedata...   

If `mkvm` generates a XML first and we can inject the user defined xml directly into the XML file, before we do a virsh create... or something..  again making all this up for some ideas.

**Comment by immarvin** [comment]
hi @whowutwut , finding out the target position to insert the xml snip is hard for us, we need to maintain the full kvm xml specification in xCAT and process the xml node in the snip case by case. 

To provide the correct xml snip, the user is also required to 1) have the knowledge of the kvm xml specification and 2) look into the kvm xml generated by xCAT as the context. 

How about provide an attribute in kvm node definition for user to specify the full xml of the kvm guest? (composed based on the xml generated by xcat, not from scratch ) or ease the workflow for user to edit and apply the kvm nodedata? in this way, we can provide more flexibility for user to have full control over the kvm guest and minimize the overhead for both the xcat user and xcat developer.

**Comment by samveen** [comment]
There isn't a trivial solution to this issue. Can I suggest support for cpu in `vm`.`othersettings` ?

**Comment by ajw1980** [comment]
I fixed this problem with this:
```
--- /opt/xcat/lib/perl/xCAT_plugin/kvm.pm       2019-08-07 14:53:47.000000000 -0500
+++ kvm.pm      2019-09-03 13:09:40.501497964 -0500
@@ -731,6 +731,7 @@
     my %cpupinhash;
     my @passthrudevices;
     my $memnumanodes;
+    my $cpumode;
     my $advsettings = undef;
     if (defined $confdata->{vm}->{$node}->[0]->{othersettings}) {
         $advsettings = $confdata->{vm}->{$node}->[0]->{othersettings};
@@ -741,6 +742,7 @@
     #cpu pining:         "vcpupin:<physical cpu set>"
     #pci passthrough:    "devpassthrough:<pci device name1>,<pci device name2>..."
     #memory binding:     "membind:<numa node set>"
+    #cpu mode:          "cpumode:<host-model|host-passthrough>"
     if ($advsettings) {
         my @tmp_array = split ";", $advsettings;
         foreach (@tmp_array) {
@@ -763,6 +765,9 @@
                 $memnumanodes = $1;
             }
 
+            if (/cpumode:(.*)/) {
+                $cpumode = $1;
+            }
         }
     }
 
@@ -780,6 +785,12 @@
         $xtree{vcpu}->{cpuset} =~ s/\"\'//g;
     }
 
+    if (defined $cpumode) {
+        if ( $cpumode eq 'host-passthrough' or $cpumode eq 'host-model') {
+            $xtree{cpu}->{mode} = $cpumode;
+        }
+    }
+
     #prepare the xml hash for pci passthrough
     my @prdevarray;
     foreach my $devname (@passthrudevices) {
```
Then you can do this and it seems to work:
`chtab node=kvm vm.othersettings=cpumode:host-passthrough`

I tried to add the cpumode:custom and cpumodel:XXX, but I couldn't get it working and I don't plan on using it so the host-passthrough was enough for me.

**Comment by gurevichmark** [comment]
@Obihoernchen or @ajw1980 I am trying to verify #6503. When the VM is running, how can I verify that the `chtab node=kvm vm.othersettings=cpumode:host-passthrough` affected the created VM ?

**Comment by ajw1980** [comment]
Just check /proc/cpuinfo

It should be obvious if it is the generic cpu or the host cpu.

**Comment by gurevichmark** [comment]
Verified:

* Default setting:
```
[root@c910f04x12v04 ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 1.5.3
stepping        : 3
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl cpuid tsc_known_freq pni cx16 hypervisor lahf_lm pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 1.5.3
stepping        : 3
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl cpuid tsc_known_freq pni cx16 hypervisor lahf_lm pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

* With `chtab node=kvm vm.othersettings=cpumode:host-passthrough`
```
[root@c910f04x12v04 ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping        : 7
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti tsc_adjust xsaveopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping        : 7
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti tsc_adjust xsaveopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

* With `chtab node=c910f04x12v04 vm.othersettings=cpumode:host-model`
```
[root@c910f04x12v04 ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel Xeon E312xx (Sandy Bridge)
stepping        : 1
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti xsaveopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel Xeon E312xx (Sandy Bridge)
stepping        : 1
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti xsaveopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by jonathanmills** [comment]
Hello!  I would just like to thank of those who worked to resolve this!  This is really going to be helpful, and good for xCAT. Cheers!
