### ISSUE TITLE
[OpenBMC] rpower (or framework) calls is not sent from xCAT in parallel 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4192]
I think this is a fundamental problem in the framework, @chenglch did some improvements for rflash, I think @xuweibj has some data about the performance of the calls in the OpenBMC perl module. 

With changes I made to #4187 I'm able to show the issues that I have been seeing.  It seems to spawn when the BMC connection is not good.  But because of this, the framework blocks sending all the rest calls to the BMCs, I think this should NOT block. 

Here's an example, I reboot the BMC, so that it won't respond correctly to force this situation: 
```
[root@briggs01 openbmctoolfordist]# time rpower mid05tor12cn[02,11] bmcreboot
Thu Oct 26 16:50:27 2017 mid05tor12cn11: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.11.139.11/login
Thu Oct 26 16:50:28 2017 mid05tor12cn02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.11.139.2/login
Thu Oct 26 16:50:28 2017 mid05tor12cn11: [openbmc_debug] login_response 200 OK
Thu Oct 26 16:50:28 2017 mid05tor12cn11: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.State.BMC.Transition.Reboot"}' https://172.11.139.11/xyz/openbmc_project/state/bmc0/attr/RequestedBMCTransition
Thu Oct 26 16:50:28 2017 mid05tor12cn02: [openbmc_debug] login_response 200 OK
Thu Oct 26 16:50:28 2017 mid05tor12cn02: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.State.BMC.Transition.Reboot"}' https://172.11.139.2/xyz/openbmc_project/state/bmc0/attr/RequestedBMCTransition
Thu Oct 26 16:50:29 2017 mid05tor12cn11: [openbmc_debug] rpower_reset_response 200 OK
mid05tor12cn11: BMC reboot
Thu Oct 26 16:50:29 2017 mid05tor12cn02: [openbmc_debug] rpower_reset_response 200 OK
mid05tor12cn02: BMC reboot

real	0m1.775s
user	0m0.098s
sys	0m0.000s
```

After the BMC starts to ping again, I run `bmcstate`, which should trigger the REST service to start, which we know has some delays. 

```
[root@briggs01 openbmctoolfordist]# time rpower mid05tor12cn[02,11] bmcstate
Thu Oct 26 16:52:01 2017 mid05tor12cn11: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.11.139.11/login
Thu Oct 26 16:53:01 2017 mid05tor12cn02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.11.139.2/login
Thu Oct 26 16:53:26 2017 mid05tor12cn11: [openbmc_debug] login_response 503 Service Unavailable
mid05tor12cn11: BMC NotReady
Thu Oct 26 16:53:26 2017 mid05tor12cn02: [openbmc_debug] login_response 200 OK
Thu Oct 26 16:53:26 2017 mid05tor12cn02: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.2/xyz/openbmc_project/state/enumerate
Thu Oct 26 16:53:31 2017 mid05tor12cn02: [openbmc_debug] rpower_status_response 404 Not Found
mid05tor12cn02: BMC NotReady

real	1m30.581s
user	0m0.103s
sys	0m0.000s
[root@briggs01 openbmctoolfordist]#
```

So if you look at the time stamp between the first and 2nd CURL call to send out the login request, it's 1 minute.  cn11 takes 1.5 minutes to respond, but it takes 1 minute before the 2nd curl command is sent out.  

Regardless of what is going on in the BMC, xCAT should spawn the calls as fast as possible and NOT contribute to the delay going on in the BMC.

**Comment by robin2008** [comment]
For this issue, if we cannot give a feasible fix with current `HTTP::Async`.  Or fork with `curl` will bring two many performance impacts.

I would suggest below method:
We implement a new parallel http ping tool using other Language (Or leverage existing open source), 
Then in our codes, just use it ping first and get the accessible nodes then do other thing as usual.

I think there might be many open source project to do the same things.

**Comment by xuweibj** [comment]
Hi @whowutwut , could this issue closed? Or what else we need to do for this issue?

**Comment by zet809** [comment]
Based on the discussion last night, we are not plan to switch the OpenBMC framework now, so, let's close this issue?

**Comment by whowutwut** [comment]
I still think we should keep this issue opened because i still think this is a problem that we should work towards resolving.... We can remove an estimate if that makes us feel better, but the problem still exists and I think it will show it's ugly head when we scale higher.. 

Unless there is some data that we can prove that shows some good performance, I would like to keep this as an issue we should look towards resolving.

**Comment by zet809** [comment]
This issue will be covered by #4553

**Comment by zet809** [comment]
Let's close this issue since we have implement rpower in python.

**Comment by whowutwut** [comment]
👍🏼
