### ISSUE TITLE
[OpenBMC] Support setting root user password for the BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4196]
This is not yet available in the BMC, but we can get started on adding in the support in xCAT: 

The man page for `rspconfig` show existing function:
```
       rspconfig noderange admin_passwd={currentpasswd,newpasswd}

       rspconfig noderange general_passwd={currentpasswd,newpasswd}

       rspconfig noderange *_passwd={currentpasswd,newpasswd}
```

I think we would want to follow this, but the only thing that would be supported is `admin_passwd` 

The password interface is here: [Password.interface.yaml](https://github.com/openbmc/phosphor-dbus-interfaces/blob/32847991c31d580aa41e2fdc6489c6219400bf22/xyz/openbmc_project/User/Password.interface.yaml)

I got the following information from OpenBMC team about the API:

**Method**: POST
**Endpoint**: `/xyz/openbmc_project/user/root/action/SetPassword`
**Data**: `{ "data": ["passw0rd"]}`

This should be enough to get some code going that would just return 503 until the service is in the code.

**Comment by xuweibj** [comment]
https://github.com/xcat2/xcat-core/wiki/rspconfig-password

**Comment by gurevichmark** [comment]
Do we want this command to also modify xCAT `passwd` table to store the new new pw there ?

**Comment by gurevichmark** [comment]
man page for `rspconfig` command should also be updated to include pw changing options under `OpenBMC` section.
