### ISSUE TITLE
[goconserver]goconserver implementation and enhancement

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4199]
* [x] Rename the old prototype to `goconserver`.
   * [x] UT test for SSL/TLS mutual authentication
   * [x] Build binary file for `goconserver` on x86_64 and ppc64le platforms
   * [x] Add script to setup `goconserver`, provide a tarball file contains this script and binary file. 

After this task done, the test could be started against the `rest api` , `console connection` , `logging of console session`, `client command`, `cmd` type console and `ssh` type console.
For more details: https://github.com/chenglch/consoleserver

**Comment by chenglch** [comment]
@neo954 , I have upload the binary files to https://github.com/chenglch/goconserver/releases ,
you could download and setup it with the following steps:
```
wget https://github.com/chenglch/goconserver/files/1437496/goconserver_linux_amd64.tar.gz
tar xvfz goconserver_linux_amd64.tar.gz
cd goconserver_linux_amd64
./setup.sh
```
For more information, you could refer `README.md` in https://github.com/chenglch/goconserver
Any problem and advice please make me know.
