### ISSUE TITLE
fix the algorithm how to calculate attribute preposition attribute correct value in 'chdef'

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#4200]
From @robbin, Obviously the previous code logic has bug and it give an inaccurate error message to user.
Here I define an x64 ipmi node, and the complain is still mgt=openbmc
```
mkdef fake1 ip=1.1.1.1 arch=x86_64 netboot=xnba groups=all
chdef fake1 bmc=10.3.1.101 groups=all
```
Checked the chdef code, the algorithm how to calculate '$invalidattr->{$att}->{condition}' is not correct. Open this issue to trace it.

**Comment by zet809** [comment]
Hi, @bybai , will you pls add more issue description?

**Comment by bybai** [comment]
@zet809, In `chdef`, there are codes to  get preposition attribute value for current value to check if current attribute is invalid or not.as following 

```
# the table for this attr might depend on the  value of some other attr
# need to check the only_if entries to find one where the other attr value matches what we have
# ex. like if I want to set hdwctrlpoint I will have to match the right value for mgtmethod 
# if my attr value for the attr to check doesn't match this then try the next one
# ex. say I want to set hdwctrlpoint, the table will depend on the mgtmethod attr - so I need
#  to find the 'only_if' that matches the value specified for that attr (ex. mgtmethod=hmc)
# need to check the attrs we are setting for the object as well as the attrs for this object that may be already set in DB
```

Currently, this method return wrong result, for example, `mkdef fake1 ip=1.1.1.1 arch=x86_64 netboot=xnba groups=all`, `chdef fake1 bmc=10.3.1.101 groups=all`, the calculate result is 'mgt=openbmc`, but not `mgt=ipmi`.
