### ISSUE TITLE
New console implementation 'goconserver' to xCAT for system console 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4214]
The EPIC for the implementation of goconserver, track mini-design, dev code, fvt work issues. `goconserver` is a potential replacement tool for  `conserver`. 

**TODO**
For makegocon command in xcat2
   * [x] The other type of console will be implement such as kvm, ...

For more details: https://github.com/chenglch/consoleserver

**Comment by neo954** [comment]
Find an old software requirements document for the [Conserver Replacement](https://github.com/xcat2/xcat-core/wiki/Conserver_Replacement).
