### ISSUE TITLE
[OpenBMC] bmcdiscover blathering garbage on non OpenBMC nodes 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4221]
Bridging issues found in Scaling Cluster: https://github.ibm.com/DCS-research/WSC-coral/issues/384 found by @ralphbellofatto

```
bmcdiscover --range=10.3.251.0/24,10.3.252.0/24,10.3.253.0/24,10.3.254.0/24
Warning: HTTP::Response=HASH(0x1000a0485c8)->status_line for 10.3.251.5
Warning: HTTP::Response=HASH(0x10009fbcd48)->status_line for 10.3.251.7
Warning: HTTP::Response=HASH(0x1000a04a438)->status_line for 10.3.251.13
Warning: HTTP::Response=HASH(0x1000a048288)->status_line for 10.3.251.4
```

Reproduced inside our cluster if we go against a switch:
```
[root@briggs01 ~]# bmcdiscover  --range 10.5.23.1
Warning: HTTP::Response=HASH(0x10003268120)->status_line for 10.5.23.1
```

In our code, we default to running `bmcdiscovery_openbmc` when we should NOT unless we determine the IP to really be a BMC node.

**Comment by whowutwut** [comment]
Need a quick fix for this in 2.13.8 release so @cxhong  will create a PR.

**Comment by whowutwut** [comment]
@hu-weihua  We should add some testcases for error scenarios... but this means we need to understand switches in our automation, since we have some additional switches avail, maybe I can make one avail for FVT to integrate into the environment

**Comment by ralphbellofatto** [comment]
if this is being closed, does that mean a fix is on the way?

**Comment by whowutwut** [comment]
Yes @ralphbellofatto  tomorrow morning dev build will have it. Can leave it open until you verify

**Comment by whowutwut** [comment]
I ran the above statement on WSC today after build was updated and did not find the complaint messages, closing out.

**Comment by hu-weihua** [comment]
relate to task #4352
