### ISSUE TITLE
[OpenBMC] Investigate syslog configuration to allow redirection from the BMC 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4234]
Test OpenBMC syslog redirection function

* Can we configure this in the BMC 
   * Is there a REST endpoint to configure this... 
* Does the configuration persist across firmware flashing of the BMC 

IF not, we need to discuss with BMC team 

Tagging some interested parties: @xuweibj @zet809

**Comment by zet809** [comment]
Move to 2.13.11 to follow.

**Comment by zet809** [comment]
hi, @whowutwut , it seems the dump interface can capture all the log files on OpenBMC, so, is this still required?

**Comment by zet809** [comment]
Hi, @whowutwut , shall we move this issue forward?

**Comment by whowutwut** [comment]
I had opened this issue to request function: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW423045

No response yet.

**Comment by whowutwut** [comment]
I am going to close this one for now,  perhaps RedFish would provide something. The idea here is to have a  restful command that  would allow  us to point  to a server  to redirect  syslog ...  but doesn't look like the BMC  will address it at this point of time.
