### ISSUE TITLE
[OpenBMC] bmcdiscover --check does not seem to work

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4240]
```
[root@briggs01 ~]# bmcdiscover -i 172.12.139.117 --check -u root -p 0penBmc
Warning: Wrong BMC password
```

If this is not supported from BMC, we need to block this function and say it's not supported. This is misleading and indicates that the password is incorrect. 

@zet809 We should add this as a known issue for 2.13.8

**Comment by zet809** [comment]
Hi, @whowutwut , it is a little hard to distinguish between BMC and OpenBMC, and not much user is using these 2 options, so I disable them in PR #4258 .

**Comment by zet809** [comment]
After code merged, I will add restriction in 2.13.8 release notes. Thx!

**Comment by zet809** [comment]
Add restriction in 2.13.8 release notes, so, @whowutwut , can we close this issue? Thx!

**Comment by zet809** [comment]
The `--check` and `--ipsource` option have been disabled, so close this issue. 
```
[root@briggs01 ~]# bmcdiscover -i 172.12.139.117 --check -u root -p 0penBmc
Error: The option '--check' is not supported
```
