### ISSUE TITLE
Reduce the amount of logs generated into the commands.log or cluster.log file for console

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4241]
**[Question]**
Sometime, you may found there are a lot of console log generated into ``/var/log/xcat/commands.log``, ``/var/log/xcat/cluster.log`` and ``/var/log/xcat/console``. The rate is every 3 seconds.  These log files will quickly fill up.  For example

In ``commands.log``.
```
====================================================
[Date]       2017-10-25 11:26:59
[ClientType] cli
[Request]    getopenbmccons mid05tor12cn10 text
[Response]
mid05tor12cn10: openbmc, getopenbmccoms
mid05tor12cn10
[ElapsedTime] 0 s
====================================================
[Date]       2017-10-25 11:27:02
[ClientType] cli
[Request]    getopenbmccons mid05tor12cn10 text
[Response]
mid05tor12cn10: openbmc, getopenbmccoms
mid05tor12cn10
[ElapsedTime] 0 s
```

In ``cluster.log``
```
Oct 25 11:26:59 briggs01 xcat[97688]: xCAT: Allowing getopenbmccons to mid05tor12cn10 text for root from localhost
....
Oct 25 11:27:02 briggs01 xcat[97760]: xCAT: Allowing getopenbmccons to mid05tor12cn10 text for root from localhost
```
**[Answer]**
These logs are generated when the console session could not be established. 
**Please check if the target node exist or is connectable.**
If the target node does not existed, please run ``makeconservercf -d <node>`` to stop frequent logging messages.

**Comment by whowutwut** [comment]
@hu-weihua I think we should probably not use this for Q&A because how would this issue ever be closed. There is also situations where the user cannot remove the console becasue it was a temporary node definition which opened by #4293
