### ISSUE TITLE
[OpenBMC] Change the bmcsetup code back to use raw ipmi commands for "access on"

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4242]
Revert the `bmcsetup` code back to raw commands from `access on`

I'm not sure the history about why we had changed the raw command back to `access on` , it seemed like it was working at some later build of OpenBMC... 
* We first set it here: https://github.com/xcat2/xcat-core/pull/2990
* Then undid it here: https://github.com/xcat2/xcat-core/pull/3833

But looking at https://github.com/openbmc/openbmc/issues/2492, it seems that certain commands will not take effect without the raw command (Setting IPSRC to DHCP)

**Comment by whowutwut** [comment]
Doing some testing here regarding https://w3.rchland.ibm.com/projects/bestquest/?defect=SW407037 Also seems like using the raw command does work better than `access on`

@zet809 Do you remember why we changed it back?  

```
[xCAT Genesis running on mid05tor12cn05 /]# time /bin/bmcsetup                    
ipmitool version 1.8.18
Invalid channel: 16
/bin/bmcsetup: line 150:  2643 Terminated              allowcred.awk
xcat.genesis.bmcsetup: BMC Information obtained from xCAT
xcat.genesis.bmcsetup: NUMBMCS=1 ==> BMC IP=172.11.139.5/255.255.0.0, GW=172.11.253.27, VLAN=11
xcat.genesis.bmcsetup: IPMIVER=2.0, IPMIMFG=42817, XPROD=16975
xcat.genesis.bmcsetup: Auto detecting LAN channel...
xcat.genesis.bmcsetup: Detected LAN channel 1
Setting LAN IP Address to 172.11.139.5
Setting LAN Subnet Mask to 255.255.0.0
Setting LAN Default Gateway IP to 172.11.253.27
Unable to send RAW command (channel=0x0 netfn=0x6 lun=0x0 cmd=0x40 rsp=0xce): Command response could not be provided

real	0m22.008s
user	0m0.220s
sys	0m0.066s
```

By doing `ipmitool -d 0 raw 0x06 0x40 $LANCHAN 0x42 0x44` instead of `access on` the networking DOES in fact

**Comment by whowutwut** [comment]
Here's a patch file: 
[bmcsetup.4242.patch.txt](https://github.com/xcat2/xcat-core/files/1451181/bmcsetup.4242.patch.txt)

To patch your system: 

1.  Download patch file to: `/tmp/bmcsetup.4242.patch.txt`
2. `cd /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin`
3. `patch -p0 < /tmp/bmcsetup.4242.patch.txt`

**Comment by hu-weihua** [comment]
relate to task #4352

**Comment by hu-weihua** [comment]
@whowutwut, we use manual test to cover node discovery test, including ``bmcsetup``.   This test won't run daily. So even we add test step for this issue, this problem won't be found as quick as daily regression.

**Comment by whowutwut** [comment]
@hu-weihua Thanks for the comments, I removed the label, I am trying to think of a way to test it and it's not that easy for automation
