### ISSUE TITLE
[OpenBMC] Improve the bmcdiscover output when MTMS is not available to show MAC in short listing. 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4243]
In verifying #4221, I noticed on BMC that didn't respond with a MT/SN.... 

```
[root@c699mgt00 ~]# bmcdiscover --range 10.3.252.78 
10.3.252.78,,,,,mp,bmc,,
```

Digging deeper, I used the -z output.... 
```
[root@c699mgt00 ~]# bmcdiscover --range 10.3.252.78 -z
node-70e284142c69:
	objtype=node
	groups=all
	bmc=10.3.252.78
	cons=openbmc
	mgt=openbmc
```

So it's returning the MAC address because the compute host was not booted yet to obtain the MT and SN.   But should we have something displayed in the output for this?  

Instead of: `0.3.251.28,8335-GTW,782EFAA,,,mp,bmc,,` maybe something like mac in place of model type...  Suggest: `10.3.252.78,70e284142c69,,,,mp,bmc,,`

Functionally, I this is OK...  but was just surprised because we should not be allowing invalid data to be printed so I thought the blank was an error... but we do calculate the node name using MAC so when we write to DB, it is OK

**Comment by zet809** [comment]
I think it is OK to output lines like `10.3.252.78,70e284142c69,,,,mp,bmc,,`, but what confusing is, for the output of `bmcdiscover --range 10.3.252.78 -z`, it is added in nodename and no attribute have the value "70e2...".

**Comment by whowutwut** [comment]
@zet809 Oh humm...  we could update the bmcdiscover man page to add a statement: 

> For OpenPower OpenBMC managed servers, if Model and Serial number cannot be detected, the temporary node will be created using the MAC address of the BMC

**Comment by whowutwut** [comment]
@zet809 did we agree on what we plan to do with this one?

**Comment by xuweibj** [comment]
After checking our code, I think output like ``10.6.3.100,,,,,mp,bmc,,,70e284142897`` or ``10.6.3.100,,,,,mp,bmc,70e284142897,,`` is better. If we use mac in place of model, we need more code to distinguish the value whether "mtm" or "mac" when format output and write to db.

**Comment by zet809** [comment]
Hi, @whowutwut , the PR #5129 may have fixed this issue, do you think we can close this defect?

**Comment by whowutwut** [comment]
ok let's close. Thanks
