### ISSUE TITLE
[OpenBMC] Streamline the rflash procedure to run unattended

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4245]
OpenBMC implemented a flash for their FW process that allows for great flexibility, but with that, introduces complexity that most system admins may not want to deal with.  

While a system admin could upload the FW files to the BMC before a maintenance window, the upload step doesn't take hours, so the savings in time vs the added steps may not be worth it for some. 

In the past, BMCs also provided a single image with BMC+PNOR or a utility to perform the correct actions on the target node to ensure that the software updates with minimal issues.  None of this is currently provided by OpenBMC 

So I'm proposing that we streamline the firmware flash process to do the necessary steps against the target node to help ensure that the BMC and PNOR are updated correctly and the BMC and Host are rebooted for the update to apply. 

External Suggestion: 

```
rflash <noderange> -a /path_to/pnor.tar,/path_to/bmc.tar --force
```

With the `--force` option, xCAT will do the following: 
1. For each .tar file provided (max 2), upload and activate the firmware 
2. If BMC is provided, run bmcreboot on the BMC, and wait for BMC to come back with BMCReady
3. If PNOR is provided, reboot the host.

**Comment by whowutwut** [comment]
@ralphbellofatto. FYI

**Comment by whowutwut** [comment]
@chenglch  we can also see how @gurevichmark is feeling next week and assign to him.  I noticed that if we run this unattended, we can send the request and activate on the BMC at the same time: 
```
[root@briggs01 ~]# rflash mid05tor12cn18 -l
mid05tor12cn18: WARNING, The current firmware is unable to detect running firmware version.
mid05tor12cn18: ID       Purpose State      Version
mid05tor12cn18: -------------------------------------------------------
mid05tor12cn18: b5273d71 BMC     Activating ibm-v1.99.10-113-g65edf7d-r8-0-g713d86d
mid05tor12cn18: 4659ba6c BMC     Active     ibm-v1.99.10-0-r13-0-g076c283
mid05tor12cn18: 776f6a74 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.52
mid05tor12cn18: 5fa4bbac BMC     Active(*)  ibm-v1.99.10-113-g65edf7d-r3-0-g9e4f715
mid05tor12cn18: 0        BMC     Active     ibm-v1.99.10-0-r7-0-gcce0f1b
mid05tor12cn18: 48f968f9 Host    Activating IBM-witherspoon-ibm-OP9_v1.19_1.112
mid05tor12cn18:
```

**Comment by bybai** [comment]
Hi @whowutwut , We assume the following steamline the firmware flash process is reasonable, could you have different comments? Thanks.
User interface: `rflash <noderange> -a /path_to/pnor.tar,/path_to/bmc.tar --force`
Streamline the firmware flash process:
1,  For each .tar file provided (max 2), upload and activate the firmware
2, If BMC is provided, run bmcreboot on the BMC
3, If PNOR is provided, power off the host
4, wait for BMC to come back with BMCReady
5, If BMCReady, power on the host

**Comment by ralphbellofatto** [comment]
so you are proposing that both tar files can be provided on the same command line.?

Also, the current process will print out any error messages for nodes that don't quite progaam in the middle of the output stream, and at the end of the process will print out a "success" message for those nodes that did work. 

If any node failed to update the final status of rflash should be a non zero exit code and a summary printed out indicating that "n" nodes failed flash and list the nodes that failed.

One should NEVER see the words "success" at the end of a run that had failures in it.

**Comment by zet809** [comment]
Hi, @ralphbellofatto , yes, we plan to provide an option to upload and activate both PNOR and BMC firmware with 1 command.

As for the next 2 comments, they can be covered in the discussion of issue #4246.

**Comment by mattaezell** [comment]
It might be nice if the user supplied a directory that contains both the BMC and PNOR files, similar to how it works for Boston.

**Comment by whowutwut** [comment]
@mattaezell 👍  

Can I also get your thoughts on this...  In the initial support for OpenBMC flashing, we  took the stand that the functions provided by the OpenBMC API allows the flexibility for the Sysadmin to do things ahead of a service window.  For example, before a service window, you could upload the firmware and even active it.  And on the service window, the actions would be just to reboot the BMC and HOST. But does this really happen in reality?   

In the past few weeks of running this in multiple clusters in-house, it seems like this level of flexibility put a huge burden on the Admin to do things correctly in order to have the FW really active.... so I created this issue to address this month. 

There are still places where we can get in trouble, but running unattended means the admin can just kick it off and walk away without knowing the details..

**Comment by mattaezell** [comment]
@whowutwut As long as the firmware upload process is relatively quick, we would prefer to do it during the outage.  Imagine a scenario where we upload new firmware before the outage but a node crashes and reboots.  Then it will have the new PNOR but not the new BMC, but it's usually recommended to do the BMC first.  And it will be different from all the other nodes in the pool, which could have some slightly differing behavior.

**Comment by ralphbellofatto** [comment]
just fyi, in our environment we always put the node in a service reservation for any kind of firmware update, either bios or other firmware and adjust our tests to verify that it makes it to all the nodes it is supposed to be on before ending the service window.

It is just that much less to keep track of, the node is either at the right firmware or it is not, if its not, then we don't allow jobs on it.

**Comment by whowutwut** [comment]
@ralphbellofatto Thanks for the info. 

I thought I had replied to this earlier, but looks like I lost my window with my response...  
So @bybai going by what @mattaezell suggested, perhaps we could use the `-d` directory to run the unattended flashing  and avoid another option... 

```
rflash <noderange> -d /path-to-directory/
```

And this would trigger the following: 
1. Look in the directory, **upload** the .tar files 
   * do some error checking, only 1 PNOR and 1 BMC allowed
2. If PNOR supplied, Power OFF the Host
3. If BMC supplied, activate the BMC 
4. If PNOR supplied, activate the PNOR 
5. Wait here until the BMC and/or PNOR become Active
6. Once active....
    1. If BMC supplied, reboot the bmc 
    2. Wait for BMC to become BMCReady (takes 4-5 minutes or so...
7. If PNOR, host should have been powered off, so now power ON the host
8. break out of command.

**Comment by bybai** [comment]
Hi @whowutwut,
I think using "-d" is better to use "-a --force". From user interface perspective, "--force" is ambiguous to only support "-a" or other options. So I accept your latest comments. Thanks.

**Comment by bybai** [comment]
Hi @whowutwut , I checked the input options, "-d|--delete" is used as "rflash noderange image_id {[-a|--activate] | [-d|--delete]}".
So I think "-p" can be used in "rflash <noderange> -p /path-to-directory/" here as the user interface. Thanks.

**Comment by ralphbellofatto** [comment]
one other "very important" thing is to note any failures and summarize the nodes that failed at the very end of the run and report success or failure (with a matching exit code) at the end of the run.

It should not be necessary to hunt through the entire output of 100's nodes being updated to tell if it succeeded or not and which nodes require futher attention.

The summary at the end should be brief like.

```
(ERROR) c699c010 -- rflash failed.
(ERROR) c699c099 -- rflash failed.
98 nodes flashed successfully, 2 failures.
FAILED
```

or, for a successful

```
100 nodes flashed successfully, 0 failures.
```
SUCCESS

**Comment by mattaezell** [comment]
@whowutwut After flashing the BMC, I've been rebooting it before applying the PNOR.  This helps ensure the PNOR update is using the latest utilities on the BMC.

**Comment by mattaezell** [comment]
@bybai That would be very confusing.  We have Bostons and Witherspoons, so having a consistent command is desired.  Would it be acceptable to require delete to specify `--delete` and leave the short option `-d` for data directory?  Do you expect that would impact many people?  I've never deleted an image on an OpenBMC machine...

**Comment by whowutwut** [comment]
@ralphbellofatto  Yep that one is being tracked by #4246 

@bybai  I would be ok with @mattaezell  suggestion to use `--delete` and leave `-d` for directory.   Or since it's early we can change the option to `-r | --remove` to remove the firmware and implement `-d | --directory `

Now with the later firmware levels, there isn't such a need to manage the deletion because BMC is doing clean up and hold 2 PNOR or 2 BMC images, it wasn't the case when we started :)  Agree, the need of running delete now is much lower.

**Comment by bybai** [comment]
@whowutwut and @mattaezell,  so will use `--delete` to specify delete require, use `-d` for directory.

**Comment by zet809** [comment]
* [ ] provide a mini-design
* [ ] the implementation

**Comment by bybai** [comment]
Mini-design: https://github.com/xcat2/xcat-core/wiki/rflash_streamline_procedure

**Comment by whowutwut** [comment]
@bybai some comments on the design. 
- Power off of the host should be done if PNOR was specified in the directory, before activating.  This will speed up the end step to just "Power on host"

**Comment by gurevichmark** [comment]
I like `--delete` for removing FW and `-d` to specify a directory.

**Comment by bybai** [comment]
Hi @gurevichmark , that is correct, ``--delete`` for removing FW and ``-d `` to specify a directory.

**Comment by bybai** [comment]
Hi @whowutwut, 
The original design is :  Power off of the host should be done if PNOR was specified in the directory, before activating.
While we discussed this action in xcat China dev team, there is 2 opinions  here considered: 
1, if we do not power off the hosts, when the BMC is updated and activated failed, we may login the host and can do something. Or else, if power off the host but BMC is updated and activated failed,  the host may fail to power on, and we can do nothing.
2, Some works/jobs can continue working on host during BMC updating and activating.
Based on above 2, we think power off host behind reboot BMC is better.
