### ISSUE TITLE
[OpenBMC] rflash should provide status at the end with success/failed 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4246]
Raising the following issues again:

* Remove the percentage complete unless Verbose is requested ( @chenglch here's where if we stored output to /var/log/xcat/rflash, maybe verbose output should be written to file) 
* The summary at the end should display the the return status of the entire command 
   For example, if we activate 100 nodes, the Success/Error messages would get lost and if we are not saving to file, we cannot find the error ...   There should be a summary message at the end

Whomever works on this, please come up with the external message at the end showing how this would be displayed first, then after that's approved, we implement it.

**Comment by xuweibj** [comment]
My idea is like this:

If all successful:
```
Summary:
-------------------------------------------------------
All 100 nodes firmware activation Successful.

```
If have several failed:
```
Summary:
-------------------------------------------------------
97 nodes firmware activation Sccessful.
3 nodes firmware activation Failed.
-------------------------------------------------------
cn01: Error: 504 Gateway Timeout
cn02: Error: 404 Not Found.
cn03: Error: DBusException("Unknown interface 'xyz.openbmc_project.Software.ActivationProgress'.",)
```

**Comment by whowutwut** [comment]
I would even keep it more simple: 
```
Summary:
-------------------------------------------------------
Success:  97
Failed: 3
Failed Nodes: cn01,cn02,cn03
```

Also bringing again up the debate of storing the rflash output into files, if we do that, we don't need to list the reason for the failure here.  The admin can go look at what happened in `/var/log/xcat/rflash/cn01` instead of looking through the output above.

**Comment by xuweibj** [comment]
I got a suggestion that set nodes' status when start rflash and rflash is ended. So that users could find the failed nodes easier. If so, the output could be simple like you mentioned above:
```
Summary:
-------------------------------------------------------
Success:  97
Failed: 3
```
If we use a file to save all nodes' information, it's hard for us to clear it. But we could save information for each node in his own file when ``-V``.

**Comment by xuweibj** [comment]
@whowutwut , based on pull request #4246, if run rflash with ``-V`` will print out the summary. And if without, no summary (because each node just has one result line). Do you think it's OK? If ok, shall we close this issue?

**Comment by whowutwut** [comment]
@xuweibj Just hit this one again :-) . Was talking to @gurevichmark , I think against a node range we should print the summary, maybe if > 1 we should print the summary.  Verbose would contain so much output but I ran against 7 nodes today with xcatdebubmode=1 and i missed seeing that 1 node failed with the DEBUG output printing out... so it is useful in short node groups as well.

**Comment by whowutwut** [comment]
Ok, I think the flash output is modified, we can allow customers  some time to give it a try and provide us feedback and go from there.
