### ISSUE TITLE
[HA] not using the VIP in priority when determine the MASTER for node

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4257]
In an HA environment, there are both the VIP and IP of physical interface. 
By design it will try to use the facing IP as the node's XCAT MASTER if no dedicate xcatmaster setting for this node.

However, current codes does not consider multiple facing IPs well. 

It is reported by (https://github.ibm.com/DCS-research/WSC-coral/issues/470), but it is a general issue.

**Comment by zet809** [comment]
Hi, @robin2008 , can we reference the WSC issue number here? Thx!

**Comment by cxhong** [comment]
The sub `my_ip_facing` will return both VIP and IP address, for the most case, we only use first one in the list.  in the research system:
```
# ip addr | grep inet | grep 10.3
    inet 10.3.100.41/16 brd 10.3.255.255 scope global enP1p12s0f0
    inet 10.3.100.250/16 scope global secondary enP1p12s0f0:0

# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"IB02","10.12.0.0","255.255.0.0","ib0",,,,,,,,"10.12.0.0-12.10.255.255","1",,,,,,,
"IB03","10.13.0.0","255.255.0.0","ib0",,,,,,,,"10.13.0.0-10.13.255.255","1",,,,,,,
"IB01","10.11.0.0","255.255.0.0","ib0",,,,,,,,"10.11.0.0-11.10.255.255","1",,,,,,,
"IB00","10.10.0.0","255.255.0.0","ib0",,,,,,,,"10.10.0.0-10.10.255.255","1",,,,,,,
"xcat_compute","10.3.0.0","255.255.0.0","enP1p12s0f0","<xcatmaster>",,"10.3.100.250",,,,"10.3.251.1-10.3.254.250",,,,,,,,,
"pub_yellow","129.40.234.1","255.255.255.224","enP1p12s0f3","129.40.234.30",,,,,,,,,,,,,,,
"net_infra","10.5.0.0","255.255.0.0","enP1p13s0f1","<xcatmaster>",,"10.5.100.250",,,,"10.5.251.1-10.5.254.250",,,,,,,,,
.......
````
How xCAT should know which one is correct facing ip address?  Can we force user to define one of servers (nameserver, ntpservers., ...) to use as the interface(or network) for compute node or switches to communicate with MN?

**Comment by bybai** [comment]
Summary:
The logic to determine the $ENV{XCATMASTER} confirm to the following priority(from high to low):
    * Using noderes.xcatmaster
    * Facing_IP on MN or SN to the CN (If multiple and the SITEMASTER is also there, using SITEMASTER).  If the CN is using SN, should configure xcatmaster for the CN, this should be included in doc.
    * using SITEMASTER

**Comment by zet809** [comment]
* [ ] summary how the `master`. `xcatmaster`, `facing IP` are using
* [ ] design and modify

**Comment by gurevichmark** [comment]
No further HA related work.
