### ISSUE TITLE
xcatprobe osdeploy unable to obtain install NIC on MN

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4267]
In the scenario that there are multiple IP configured on the deploy NIC of MN,  `xcatprobe osdeploy` failed to obtain the NIC.

```
-bash-4.2$ ip addr show dev enP1p12s0f0
2: enP1p12s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 98:be:94:63:ab:6c brd ff:ff:ff:ff:ff:ff
    inet 10.3.100.41/16 brd 10.3.255.255 scope global enP1p12s0f0
       valid_lft forever preferred_lft forever
    inet 10.3.100.250/16 scope global secondary enP1p12s0f0:0
       valid_lft forever preferred_lft forever
    inet6 fe80::9abe:94ff:fe63:ab6c/64 scope link
       valid_lft forever preferred_lft forever
```
···
#xcatprobe osdeploy -node01 -p phase
Failed to obtain install NIC in current server                                                                    [FAIL]
The value of 'master' in 'site' table is 10.3.100.250, can't get corresponding network interface in current server
All nodes to be deployed are valid                                                                                [ OK ]
···
One more comment, as you can see, the last message is `OK`, a little confusing that what had been done, and what haven't start yet.

**Comment by hu-weihua** [comment]
@zet809 , The fix has been merged, could you help to verify it? thanks.

**Comment by hu-weihua** [comment]
@zet809, I have not received any feedback up to now for this issue, I suppose the fix has worked. 
Close this issue first, if you find any problem in future, you can reopen this issue again, thanks.

**Comment by kcgthb** [comment]
@hu-weihua the fix doesn't seem to work in hierarchical mode.

When running osdeploy on a Service Node, the script checks for the IP of the Master Node, doesn't find it, and fails.

What is the best way to monitor deployments happening through Service Nodes?
