### ISSUE TITLE
investigation and mini design of xCAT version control

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4268]
https://github.com/xcat2/xcat-core/wiki/The-design-of-xCAT-configuration-data-version-control

**Comment by whowutwut** [comment]
@immarvin Why not just take a look at the possibility of getting xCAT osimage into some sort of flat file that could be placed in various source controls out there, and consuming that into osimages within xCAT...  ?

**Comment by immarvin** [comment]
hi @whowutwut , according to the discussion in https://github.com/xcat2/xcat-core/issues/4041, the version control of node/osimage/site/... object definition will provide basic version control for xCAT configuration data which user can use, which is also a basis for the version control of osimage entity you mentioned. The version control of osimage entity will also be considered in this EPIC
