### ISSUE TITLE
bmcsetup can not set BMC IP on firestone

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#428]
The BMC IP can not be changed using bmcsetup script on firestone. It can reboot successfully, but the BMC IP is not changed after cold reset.

Please refer to the log:

Done
ERROR: BOOTIF missing, can't detect boot nic
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
Generating private key...Done
Setting IP via DHCP...
[   31.783669] bnx2x: [bnx2x_dcbnl_set_dcbx:2350(eth3)]Requested DCBX mode 5 is beyond advertised capabilities
Acquiring network addresses..rsyslogd: error: option -c is no longer supported - ignored
Acquired IPv4 address on eth3: 30.0.0.3/8
ppc64le
                                                         
rm: cannot remove '/tmp/ipmicfg.xml': No such file or directory
/usr/bin/bmcsetup: line 43:  1912 Terminated              allowcred.awk
Auto detecting LAN channel...Detected LAN channel 1
Setting LAN IP Address to 50.4.8.18
Setting LAN Subnet Mask to 255.255.255.0
Set up following user table: 
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1                    false   false      true       ADMINISTRATOR
2   ADMIN            false   false      true       ADMINISTRATOR
Enabling Channel 1: OK
Enabling ARP responses: OK
Enabling IPMI v 1.5 MD5 LAN access:OK
Enabling IPMI v 2.0 LAN access: OK
Enabling SOL for channel 1:OK
Enabling SOL for ADMIN:OK
Resetting BMC ...
Sent cold reset command to MC
Waiting for the BMC to appear ...
Error: No response to keepalive - Terminating session
Error: No response de-activating SOL payload

**Comment by zet809** [comment]
As talked with Gao Feng, this issue occurs with genesis-base build by PCM team which is based on MCP. We didn't encounter this issue with our xcat-genesis-base-ppc64_2.11. So, reject it.
