### ISSUE TITLE
setupntp postscript will hung on compute node if ntp server on MN is down

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#4286]
https://github.ibm.com/DCS-research/WSC-coral/issues/538

For some reason,  ntpd service is not running on the management node.   run setupntp postscripts to the compute node will cause ntpd hung and node status will reported `powering-off` for a diskfull node and `netbooting` for a diskless node.

**Comment by immarvin** [comment]
has `xcatprobe xcatmn` covers some check on this?

**Comment by immarvin** [comment]
hi @cxhong , I looked into the code and we had a discussion on this, some thoughts:
1. `xcatprobe xcatmn` has covered the ntp server status checking on mn 
2.  the default timeout value of "ntpd -qg"  is 1000s, we'd better decrease the timeout value less  than 2 minutes, I did not find a "ntpd " option to specify the timeout value, do you know how to?
3. in "setupntp", it the "ntpd -qg"  return with  timeout  and leave the clock un-synced,  maybe we can get a  timestamp from MN and set it to the node, like `getpostscripts.awk` or `getcredentials.awk`

what do you think? @cxhong @whowutwut

**Comment by immarvin** [comment]
for the #2, the command `timeout` can be used, something like `timeout 120 ntpd -qg`, see `man timeout` for details.

**Comment by zet809** [comment]
Hi, @cxhong, shall we close this defect?
