### ISSUE TITLE
Remove bmc node from conserver config

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4293]
`bmcdiscover` creates temporary nodes so you can issue commands to the node.  We've found that running `makeconservercf` and `rcons` is sometimes necessary to debug issues in discovery.  Once the node is successfully discovered, the temporary BMC node is removed from the xCAT database.  Now `makeconservercf -d` doesn't work any more, and the config is "stranded" out there.  That starts filling up our logs with reconnect attempts.  An admin has to manually update the config file. I suggest either:
- `rmdef` of a node should spawn a `makeconservercf -d` of that node (what if someone hasn't setup consoles, or they are using confluent?)
- Make `makeconservercf -d` support removing "unknown" nodes based solely on the name provided on the command line

**Comment by whowutwut** [comment]
Agree completely here....  @zet809 This is same issue as #2306  and we had discussed back then too... the argument you made at that time is during discovery, combining with rmdef would mean that the restart of console server may affect other consoles at that time.  But we do want to make sure that the consoles are able to be cleaned up when we have the chance.  (Option 1 above)

Option 2, we could implement `makeconservercf -d unknown` where `unknown` is a special keyword (hope that no one names a node definition: `unknown`) and we clean up all the entries that xCAT does not know about and then do a single restart at the end.  

This would address @zet809 concern about handling it when rmdef is executed.

**Comment by zet809** [comment]
hi, @whowutwut and @mattaezell , good point, I agree with you that shall enhance our interface to remove console entry.
Will do it next week.

**Comment by zet809** [comment]
* [ ] add `makeconservercf -d <node>` in `rmdef -c`
* [ ] `makeconservercf -d unknown`

**Comment by zet809** [comment]
Hi, @mattaezell , will you pls help to verify and close this requirement if the concern is fixed? Thx a lot!

**Comment by whowutwut** [comment]
The solution here is to use `makeconservercf -C` to remove nodes that no longer exist in the xCAT database and cleanup conserver.  Closing out.
