### ISSUE TITLE
[OpenBMC] Sorting code is removing zeros from string 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4298]
Found in Austin Cluster: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW405512

```
rinv cn05 serial 
cn05: SYSTEM SerialNumber : 781A9A
```
The serial number is actually `781A09A`

I can re-create it on our machine if I replace the `$content_info` with that number: 

```
rinv mid05tor12cn11 serial
....
Tue Nov 14 14:55:08 2017 mid05tor12cn11: [openbmc_debug] 781A09A
mid05tor12cn11: 781A9A
```

I'm not sure if this only affects serial number, but i think it should affect all code that runs through this sorting..

**Comment by whowutwut** [comment]
@robin2008 @xuweibj   The sorting code is doing something wrong.  Need some help to figure this out.  I think I didn't use a default sort because it was not producing correct output.

**Comment by whowutwut** [comment]
Understand this a little more now... If we replace the sort with just `my $sorted_output = sort @sorted_output;`  and run rinv against a p9 node, you will see the sorting is all whack.  

In the string we have a few fields that have counts greater than 10. And the way Perl sorts, it's not sorting naturally, so it ends up being 0,1,10,2,20,3., etc which is really annoying to look at.  We have fields like
```
CPU0 CORE0
...
CPU0 CORE24

DIMM0 
...
DIMM16...
```

**Comment by robin2008** [comment]
There is no builtin natural sorting in perl, and also other programming language. As normally the sorting is a algorithmic based on the contents. 

And for xCAT, it often use many format like,  'node01', 'DIMM10', 'cdl-rack01-cn05', etc; We can consider build the sorting algorithmic for such kinds of string. To sort a string with numbers inside:
- Decomposing Strings Into Sub-Components using RE
- Made Strings Containing Numbers Into Numbers
- Sort each components with the order and given an unified sorted list

Now our  sorting codes is not well implemented for this, it is better to work out a utility function for it.

**Comment by robin2008** [comment]
For numbers, I think unsigned integer is enough for current.

**Comment by robin2008** [comment]
It is introduced a new sorting method in xCAT::Utils and in openbmc to use it.
