### ISSUE TITLE
`xdsh` return with no output when "site.master" is not set

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4299]
update:

steps to reproduce:
````
 chdef <cn> servicenode=
 chdef -t site -o clustersite master=
 xdsh <cn> hostname
````

==============================================

I'm not getting any output from `xdsh` unless I turn on bypass mode.

```
[root@mgmt1 ~]# lsdef -s compute
h41n01  (node)
h41n02  (node)
h41n03  (node)
h41n04  (node)
h41n05  (node)
h41n06  (node)
h41n07  (node)
h41n08  (node)
h41n09  (node)
h41n10  (node)
h41n11  (node)
h41n12  (node)
h41n13  (node)
h41n14  (node)
h41n15  (node)
h41n16  (node)
h41n17  (node)
h41n18  (node)
[root@mgmt1 ~]# xdsh compute hostname
[root@mgmt1 ~]# xdsh compute -T -v hostname
[root@mgmt1 ~]# ssh h41n01 hostname
h41n01
[root@mgmt1 ~]# xdsh compute -B hostname
h41n03: h41n03
h41n02: h41n02
h41n11: h41n11
h41n01: h41n01
h41n10: h41n10
h41n14: h41n14
h41n04: h41n04
h41n06: h41n06
h41n07: h41n07
h41n08: h41n08
h41n12: h41n12
h41n15: h41n15
h41n17: h41n17
h41n18: h41n18
h41n16: h41n16
h41n13: h41n13
```
Any ideas?

```
[root@mgmt1 ~]# lsxcatd -v
Version 2.13.8 (git commit fe7405f1702f63758e0b65ae7999bd457ea0cd5a, built Thu Nov  2 07:15:44 EDT 2017)
```

**Comment by cxhong** [comment]
@mattaezell , can u check `nslookup` output?  
if you get this:
```
[root@mgmt1 ~]# nslookup h41n01
Server:         160.91.203.61
Address:        160.91.203.61#53

** server can't find h41n01: NXDOMAIN
````
check /etc/resolv.conf, add mgmt1's ip address , then run 'makedns' again.

**Comment by mattaezell** [comment]
Hello @cxhong.  We don't have our compute nodes in DNS, they are in the /etc/hosts file.  Notice the ssh above worked fine.

**Comment by whowutwut** [comment]
@chenglch @zet809 any ideas here?

**Comment by immarvin** [comment]
hi @mattaezell , strange that `xdsh` works in BYPASS mode. 

would you please try the following steps:
1. `xdsh <single cn against which xdsh has no out put> -m xxxx` , watch and provide the output
2. check whether the command has been successfully dispatched to the node, run command  `xdsh <single cn against which xdsh has no out put> -s "while true; do echo TESTTEST;done"` on MN, login to the node and check whether the ssh session created by ssh is running by `ps aux|grep 'TESTTEST'`

thanks

**Comment by whowutwut** [comment]
@cxhong  and I debugged with Glen.... after a few commands to see what is going on, we ran `xcatprobe xcatmn` and it detected site was not configured.

[No sensitive information is exposed in the command so i'll paste it here]
```
# xcatprobe xcatmn
[mn]: Checking all xCAT deamons are running...                                                                    [ OK ]
[mn]: Checking xcatd can receive command request...                                                               [ OK ]
[mn]: Checking 'site' table is configured...                                                                      [FAIL]
[mn]: There isn't 'master' definition in 'site' table
=================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [FAIL]
    Checking 'site' table is configured...                                                                        [FAIL]
        There isn't 'master' definition in 'site' table
```

So while the probe commands are still sorta beta and may not work on more complicated network environments, there is some basic checking that is done! 👍

After updating the site table, xdsh is working again so closing this issue

**Comment by zet809** [comment]
It is great that our tool is helpful!

**Comment by immarvin** [comment]
i think it's still a bug for `xdsh` that it return without any message when `site.master` is not set.
this is easy to reproduce in our env.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4313

**Comment by immarvin** [comment]
hi @whowutwut , `site.master` is not mandatory for xdsh, this proved to be a bug in xCAT, the fix has been merged
