### ISSUE TITLE
[Coral] issues for ntp configuration on Accton switches

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#4300]
Issues found from lab:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408125
   --- incorrect sets NTP server
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408126
    -- incorrect iburst entry
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408127
   --didn't update timezone

for configonie --ntp,  we should replace code to use `setupntp` postscripts, or get rid of this command and update the documentation to suggest  user to use `setupntp` postscripts to set ntp on the accton switches.

**Comment by immarvin** [comment]
how to export the environment variables to setupntp during `configonie`? maybe we can consider leverage getmyposttscript.cumulus to generate the mypostscript and run the specified script, just like what we do for the updatenode against node, will look into this...
