### ISSUE TITLE
[Coral]  issues for install license file on accton switches.

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#4301]
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408131
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408130

after upgrade the cumulus OS,  xcat suggest to install license file via xdsh command.  if user invoke `switchdiscover --setup` or `configonie --all` command,  the configuration of interface will failed since license is not install yet at that time.

**Comment by immarvin** [comment]
Specifying the licenses for switches in a network range on `switchdiscover ` is difficult for us.  If user upgrade cumulus os with fresh installation, we can leverage ztp to install the license, I will draft a design on this
