### ISSUE TITLE
[OpenBMC] rflash on a range results in 'Path or object not found'

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4310]
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408030

Chasing this intermittent problem where we see error messages like the following: 

```
# rflash cn01,cn03,cn04,cn05,cn08 /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar -a
cn08: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn04: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn03: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn01: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn05: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn08: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn04: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn01: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn08: Could not find ID for firmware ibm-v2.0-0-r5-0-g2fd869c to activate, waiting 10 seconds and retry...
cn04: rflash started, please wait...
cn05: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn04: Error: Path or object not found: /xyz/openbmc_project/software/a625b9dd
cn01: rflash started, please wait...
cn03: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn01: Activating firmware . . . 30%
cn05: rflash started, please wait...
cn05: Activating firmware . . . 30%
cn03: rflash started, please wait...
```

After adding more information in the message using PR #4303, we came across another cluster that has experienced this behavior and now understand what is happening inside xCAT code.

```
c650f07p21: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p17: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p19: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p11: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p09: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p13: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: cf0d88bc)
c650f07p15: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r7-0-ge521a31 (ID: 29c0a606)
c650f07p17: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p19: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p11: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p09: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p13: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p21: Error: Path or object not found: /xyz/openbmc_project/software/29c0a606
c650f07p15: Firmware activation successful.
[ElapsedTime] 108.047 s
```

The HASH ID that we save for querying the endpoint is written on the Activation, so in the above eample, the last HASH `29c0a606` starts to be used to query the state for all nodes in the batch of updates.  And since this hash does not match the other nodes hash, we hit this error. 

## Cause

This is caused by the firmware team changing the HASH method after 1740A firmware level and now depending on which BMC you are running, you will get an old hash ID or a new hash ID for the same firmware.... .  It's very dangerous because you can flash the same FW on twice and EVEN activate it!!   I think after flashing twice on the new hashing FW, it should resolve itself out...  But since we have users running into this problem, we need to fix this in order to support the unattended flash.

The activation has already been sent via REST at this point so the BMC is in Activating state. It's just our monitoring code that breaks out of the waiting loop.

**Comment by whowutwut** [comment]
Talking to @gurevichmark today, I think one solution is to store the IDs for each node in range instead of assuming that the single file would generate the same ID.

**Comment by gurevichmark** [comment]
After additional discussion, it was decided to identify the node with hash ID which does not resolve to an expected hash ID. For that node, the firmware will be uploaded but not activated, leaving it in "Ready" state.
PR #4322

**Comment by zet809** [comment]
Hi, @whowutwut, "This is caused by the firmware team changing the HASH method after 1740A firmware level and now depending on which BMC you are running, you will get an old hash ID or a new hash ID for the same firmware." Not quite understand. 
Even they change the HASH method, the only result is, the hash ID of a firmware file is changed to B from A, right? Why there are 2 hash ID at the same time?

**Comment by gurevichmark** [comment]
Perhaps the following can happen:

You are running on 1740A and upload and activate firmware 1740D. A hash ID using the old method is created for it - 123. You reboot BMC, so now you are running on 1740D. You upload and activate the same firmware 1740D tar file. This time the new hash method is used and generates hash ID - 789. At the end, I think, there will be 2 entries: hash ID 123 and hash ID 789, both referring to the same 1740D update.

**Comment by whowutwut** [comment]
@gurevichmark This one I think we can close out?   After 2 flashes with the new algorithm, we should not see this issue anymore.
