### ISSUE TITLE
copycds does not generate osimage for ESXi and Windows

### ISSUE THREAD

**Issue by dotRollen** [xcat2/xcat-core#4323]
copycds does not generate osimage for ESXi and Windows

Creates the install folder for each os but not the osimage definitions.

**Comment by immarvin** [comment]
hi @dotRollen , what is your ESXi and Windows version? please provide  the output of `copycds -i <iso>`

The windows and esxi support does not belong to the features be verified on each xCAT release.

**Comment by splaksunov** [comment]
The same problem
[root@xcat iso]# copycds -n esxi6.0 -a x86_64 VMware-ESXi-6.0.0.update03-5050593-LNV-20170414.iso
perl: symbol lookup error: /usr/lib64/perl5/auto/Socket6/Socket6.so: undefined symbol: Perl_Gthr_key_ptr
[root@xcat iso]# copycds VMware-ESXi-6.0.0.update03-5050593-LNV-20170414.iso
perl: symbol lookup error: /usr/lib64/perl5/auto/Socket6/Socket6.so: undefined symbol: Perl_Gthr_key_ptr

**Comment by immarvin** [comment]
close this ticket, please reopen it if any update

**Comment by dotRollen** [comment]
@immarvin  when running copycds it does not create a osimage here is the following output requested.

```
[root@216f9d7a95fc tftpboot]# copycds -i 7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso 
OS Image:/tftpboot/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
DISTNAME:win2k8r2
ARCH:x86_64
```

Also nodeset <node> winshell is not working either was this removed in 2.13? In tftpboot i have the winboot folder generated from the sourceforge instructions [here](https://sourceforge.net/p/xcat/wiki/XCAT_Windows/)
