### ISSUE TITLE
Sometimes pping cannot work as normal.

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4324]
Here found an issue:
```
# nodestat c910f03c11k14
c910f03c11k14: noping
[root@c910f03c11k12 result]# pping c910f03c11k14
c910f03c11k14: noping
[root@c910f03c11k12 result]# nmap c910f03c11k14

Starting Nmap 6.40 ( http://nmap.org ) at 2017-11-16 23:48 EST
Nmap scan report for c910f03c11k14 (10.3.11.14)
Host is up (0.00041s latency).
rDNS record for 10.3.11.14: c910f03c11k14.pok.stglabs.ibm.com
All 1000 scanned ports on c910f03c11k14 (10.3.11.14) are filtered
MAC Address: 42:67:0A:03:0B:0E (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 21.37 seconds
[root@c910f03c11k12 result]# ping c910f03c11k14
PING c910f03c11k14.pok.stglabs.ibm.com (10.3.11.14) 56(84) bytes of data.
64 bytes from c910f03c11k14.pok.stglabs.ibm.com (10.3.11.14): icmp_seq=1 ttl=255 time=0.418 ms
64 bytes from c910f03c11k14.pok.stglabs.ibm.com (10.3.11.14): icmp_seq=2 ttl=255 time=0.371 ms
64 bytes from c910f03c11k14.pok.stglabs.ibm.com (10.3.11.14): icmp_seq=3 ttl=255 time=0.443 ms
```

**Comment by robin2008** [comment]
check the pping codes, it seems using below `nmap` command:
```
nmap -PE --system-dns --unprivileged --send-ip -sP c910f03c11k14
Warning:  You are not root -- using TCP pingscan rather than ICMP

Starting Nmap 6.40 ( http://nmap.org ) at 2017-11-16 23:51 EST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
```
It is failed, and follow the suggestion to use '-Pn', it works.
```
nmap -Pn --system-dns --unprivileged --send-ip -sP c910f03c11k14

Starting Nmap 6.40 ( http://nmap.org ) at 2017-11-16 23:52 EST
Nmap scan report for c910f03c11k14 (10.3.11.14)
Host is up.
rDNS record for 10.3.11.14: c910f03c11k14.pok.stglabs.ibm.com
Nmap done: 1 IP address (1 host up) scanned in 0.01 seconds
```

**Comment by cxhong** [comment]
The issue is caused by  the firewall actively blocking ping probes
ping will works again after stop the firewall
```
service firewalld stop
````

**Comment by cxhong** [comment]
@robin2008  and @zet809 ,  pping calls nmap command to check ping status
````
nmap -PE --system-dns --unprivileged --send-ip -sP
````
is there reason why we use unprivileged?

on our test system, I turned firewall on for mid08torcn01, but host still reachable(ping and ssh).  pping will not work.  If remove --unprivileged from nmap command, pping works fine
```
# pping mid08tor03cn01,mid08tor03cn10,mid08tor03cn26
mid08tor03cn01: ping
mid08tor03cn10: ping
mid08tor03cn26: noping
````

**Comment by robin2008** [comment]
I think it is introduced by https://github.com/xcat2/xcat-core/pull/4102

@jjohnson42 It seems `--unprivileged` will cause `pping` not working too. Do you have some idea about it?

**Comment by Obihoernchen** [comment]
I just hit this issue.
```
# nmap -PE --system-dns --unprivileged --send-ip -sP <ips...>
Nmap done: 22 IP addresses (20 hosts up) scanned in 0.01 seconds

# nmap -PE --system-dns --send-ip -sP <ips...>
Nmap done: 22 IP addresses (22 hosts up) scanned in 0.04 seconds
```
Two nodes have an active firewall and pping fails. I really think the new behaviour (`--unpriviliged`) is worse than before. It's called p*ping*, not port scan ;-)

Because of this `xdsh -v`, `updatenode` etc. fails.

Furthermore, `-SP` is deprecated. The new option is called: `-sn`

**Comment by robin2008** [comment]
This is mentioned in https://github.com/xcat2/xcat-core/commit/fb02c18853dd2004ed936c77afabd310d7f115dd
>  Fix erroneous 'noping' in various circumstances
> nmap's raw IP facility is prone to mistakes in various
> environments.  Disable the raw IP handling by
> telling nmap to run as if it didn't have privilege

But it seems it will introduce `noping` on the target node which is enabled firewall. As from `nmap` manual

> The default host discovery done with -sn consists of an ICMP echo request, TCP SYN to port 443, TCP ACK to port 80, and an ICMP timestamp request by default. When executed by an unprivileged user, only SYN packets are sent (using a connect call) to ports 80 and 443 on the target. When a privileged user tries to scan targets on a local ethernet network, ARP requests are used unless --send-ip was specified. The -sn option can be combined with any of the discovery probe types (the -P* options, excluding -Pn) for greater flexibility. If any of those probe type and port number options are used, the default probes are overridden. When strict firewalls are in place between the source host running Nmap and the target network, using those advanced techniques is recommended. Otherwise hosts could be missed when the firewall drops probes or their responses.
> 
> In previous releases of Nmap, -sn was known as -sP.

we can see that `nmap` only send TCP to ports 80 and 443 to target nodes with unprivileged user. With `tcpdump`, we can also see the difference:
```
nmap -PE --unprivileged --system-dns --send-ip -sn mid05tor12cn03
Warning:  You are not root -- using TCP pingscan rather than ICMP

Starting Nmap 6.40 ( http://nmap.org ) at 2018-09-27 01:40 EDT
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 0.00 seconds


01:40:14.205429 IP briggs01.40504 > mid05tor12cn03.http: Flags [S], seq 18878289, win 29200, options [mss 1460,sackOK,TS val 732517690 ecr 0,nop,wscale 7], length 0
01:40:14.205932 IP mid05tor12cn03 > briggs01: ICMP host mid05tor12cn03 unreachable - admin prohibited, length 68
01:40:19.262093 ARP, Request who-has briggs01 tell mid05tor12cn03, length 46
```
But without `--unprivileged`, only ICMP is sent as we specified `-PE`
```
01:42:36.262127 IP briggs01 > mid05tor12cn03: ICMP echo request, id 1628, seq 0, length 8
01:42:36.262618 IP mid05tor12cn03 > briggs01: ICMP echo reply, id 1628, seq 0, length 8
```

Without `--unprivileged` and `-PE`
```
01:43:50.632120 IP briggs01 > mid05tor12cn03: ICMP echo request, id 59888, seq 0, length 8
01:43:50.632146 IP briggs01.33557 > mid05tor12cn03.https: Flags [S], seq 2032569925, win 1024, options [mss 1460], length 0
01:43:50.632161 IP briggs01.33557 > mid05tor12cn03.http: Flags [.], ack 2032569925, win 1024, length 0
01:43:50.632172 IP briggs01 > mid05tor12cn03: ICMP time stamp query id 21177 seq 0, length 20
01:43:50.632234 IP mid05tor12cn03 > briggs01: ICMP echo reply, id 59888, seq 0, length 8
01:43:50.632269 IP mid05tor12cn03 > briggs01: ICMP host mid05tor12cn03 unreachable - admin prohibited, length 52
01:43:50.632278 IP mid05tor12cn03 > briggs01: ICMP time stamp reply id 21177 seq 0: org 00:00:00.000, recv 05:52:00.230, xmit 05:52:00.230, length 20
01:43:50.632646 IP mid05tor12cn03 > briggs01: ICMP host mid05tor12cn03 unreachable - admin prohibited, length 48
```

**Comment by robin2008** [comment]
In addition, xcat could let you customized nmap options in `site.nmapoptions`, but this is used for all nmap cases, there would be side impact for other commands.

**Comment by Obihoernchen** [comment]
Checking port 22 sounds better :+1: 

A quick search shows the following files use `nmap -PE` with `nmapoptions`.
```
bin/pping # --unprivileged
lib/perl/xCAT_plugin/nodestat.pm # --unprivileged
lib/perl/xCAT/NetworkUtils.pm # uses privileged mode
lib/perl/xCAT/SLP.pm # uses privileged mode, but does not read nmapoptions
lib/perl/xCAT/PPCenergy.pm # uses privileged mode

probe/lib/perl/xCAT/NetworkUtils.pm # uses privileged mode
```
It seems to be kinda inconsistent. I think a small nmap wrapper library would be a good idea to keep everything consistent across the board.

**Comment by robin2008** [comment]
Yes, there are some consistent, but check the codes, it seems a bit different for those calling. 
So this time, we only fix the pping/nodestat issue, and kept others as is.

This is covered in https://github.com/xcat2/xcat-core/pull/5699
