### ISSUE TITLE
Mini design of the enhancement of node status

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#4335]
To discuss the possible enhancement on node status, it should cover the provisioning status, reboot status and discovering status.

**Comment by robin2008** [comment]
Draft design: 
https://github.com/xcat2/xcat-core/wiki/node-status-enhancement

**Comment by robin2008** [comment]
@whowutwut 
Per performance issue, it is not good to report all detail status to MN. 
Here we just want to introduce a new status `configuring` there, and it means xCAT entering the stage to run `postbootconfiguring`.

**Comment by chenglch** [comment]
Maybe some status for rflash should be taken into account. Could you help define some status name for rflash below:
- rflashing
- rflash failure
- rflash success
- rflash recovering
Not sure if the status about rflash upload or rflash activate for openbmc should be included.

**Comment by robin2008** [comment]
From my opinion,  For `rflash`, it is better to use app status (`appstatus`) , instead of node status.

**Comment by daniceexi** [comment]
@robin2008 Looks good for me.
