### ISSUE TITLE
[goconserver] Build scripts and service scripts for goconserver

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat-core#4336]
Build rpm and deb packages depends on the tarball which contains the binary files for goconserver.
Tasks include:
- [x] systemd unit file to start goconserver daemon
- [ ] sysv scripts to start goconserver service ??
- [x] simple build script for rpm
- [x] simple build script for deb  ??

**Comment by neo954** [comment]
See pull request chenglch/goconserver#12
