### ISSUE TITLE
/opt/xcat/xcatinfo does not have the IMAGENAME for diskfull nodes.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#4341]
diskless install looks like:
```
[root@c699mgt00 scratch]# xdsh c699c057 cat /opt/xcat/xcatinfo
c699c057: IMAGENAME='rh74_compute_csm'
c699c057: IMAGEUUID='8410b1a5-5540-4390-a5be-096580ddb4ae'
c699c057: TIMESTAMP='Mon Nov 20 12:01:33 EST 2017'
c699c057: NODE=c699c057
c699c057: XCATSERVER='10.3.100.41'
c699c057: USEFLOWCONTROL=NO
```

diskfull install looks like this.
```
[root@c699mgt00 scratch]# xdsh c699wrk01 cat /opt/xcat/xcatinfo
c699wrk01: XCATSERVER=10.3.100.41
c699wrk01: INSTALLDIR=/install
c699wrk01: REBOOT=TRUE
c699wrk01: NODE=c699wrk01
c699wrk01: USEFLOWCONTROL=NO
```

The image name really should be in both...

**Comment by ralphbellofatto** [comment]
it would seem there is no way to tell from the information xcat leaves behind what osimage is behind this node provisioning...

**Comment by whowutwut** [comment]
@cxhong Did we add this in, or thought about adding it but never got around?

**Comment by whowutwut** [comment]
@ralphbellofatto For diskful it's slightly different...

```
[root@c699mgt00 scratch]# xdsh c699c057 cat /opt/xcat/xcatinfo
c699c057: IMAGENAME='rh74_compute_csm'
c699c057: IMAGEUUID='8410b1a5-5540-4390-a5be-096580ddb4ae'
c699c057: TIMESTAMP='Mon Nov 20 12:01:33 EST 2017'
c699c057: NODE=c699c057
c699c057: XCATSERVER='10.3.100.41'
c699c057: USEFLOWCONTROL=NO
```
The uuid and timestamp for the diskless node is when the user runs `packimage` but for diskful, we could add IMAGENAME and TIMESTAMP, but the time stamp would not match across the board, because it would be some time when the OS provisioned or installed ... 

Is IMAGENAME alone sufficient?

**Comment by ralphbellofatto** [comment]
it got added for the diskless, but not the diskfull installation...

I ran into this because there was something in the postboot scripts i wanted to do in common code that would depend on what the image name is...

I'm sure there are more people who have run into this implementation issue.

In any case, adding it to the diskless image but not the diskfull seems a bit of an oversite.

**Comment by ralphbellofatto** [comment]
IMAGENAME would cover us for this.

Timestamp of the original provisioning might be useful, I'm not sure...

**Comment by robin2008** [comment]
`TIMESTAMP` now just means the image packing time for diskless,  hard to find a matching for stateful.  And a bit confusing if using the same key for different things.

Let's add IMAGENAME first.

**Comment by ralphbellofatto** [comment]
that would be good, i have an immediate use for the IMAGENAME...  when i just want a small install variation but a common script.

**Comment by whowutwut** [comment]
Testing on 
```
Version 2.13.9 (git commit db20025558aed1822cd8a45b81b8c3673485f043, built Tue Nov 28 21:56:18 EST 2017)
```

```
[root@briggs01 ~]# nodeset mid05tor12cn15 osimage=rhels7.4-alternate-ppc64le-install-compute
mid05tor12cn15: install rhels7.4-alternate-ppc64le-compute
[root@briggs01 ~]# rsetboot mid05tor12cn15 net
mid05tor12cn15: Network
[root@briggs01 ~]# rpower mid05tor12cn15 boot
mid05tor12cn15: reset
```

Will update with the result of `/opt/xcat/xcatinfo` after the machine gets installed.

**Comment by whowutwut** [comment]
After installed... 

```
[root@mid05tor12cn15 ~]# cat /opt/xcat/xcatinfo
XCATSERVER=172.12.253.27
INSTALLDIR=/install
REBOOT=TRUE
NODE=mid05tor12cn15
IMAGENAME=rhels7.4-alternate-ppc64le-install-compute
```
