### ISSUE TITLE
[OpenBMC] Usability improvements for creating BMC dumps needed

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4342]
1.  Should we consider a different way to save the dumps, maybe using the date?  Right now if we clear the dumps, it will overwrite over itself ...  

All the dumps are stored in /var/log/xcat/dump/<hostname>_dump_<id>.tar.xz

So looking at the use case from #4235  and #4327 , if we ask for dumps to be generated across 200 of 500 nodes, if we had a time stamp with that, then the admin could tar up all the dump files by....

```
cd /var/log/xcat/dump
tar -czvf 2017-11-20-bmcdump.tar.gx ./2017-11-20* 
```

Instead of picking and choosing the nodes that want to be saved, or even clearing out the directory first before capturing the dump. 

2.  Allow for an option to get all dumps off the BMC... 

   * ` rspconfig <node> dump -d all `
   or 
   * `rspconfig <node> dump -d `

Currently, the only way to do this is to run a wrapper script  and loop through each dump file.  I'm not sure this is necessary yet.. so I put 1 at a higher priority.

**Comment by gurevichmark** [comment]
Item 1 has already been implemented by PR #4382, the generated names for dumps are now:
```
[root@briggs01 Logging]# ls -l /var/log/xcat/dump/
total 324
-rw-r--r-- 1 root root 112784 Dec 21 11:15 20171221-1114_mid05tor12cn18_dump_1.tar.xz
-rw-r--r-- 1 root root 113208 Dec 21 11:20 20171221-1118_mid05tor12cn18_dump_2.tar.xz
-rw-r--r-- 1 root root  99452 Jan  3 16:27 20180103-1626_mid05tor12cn16_dump_3.tar.xz
```

Using this issue to implement item 2.

**Comment by gurevichmark** [comment]
PR #4651 implements "all" option (item 2 above).

**Comment by whowutwut** [comment]
Closing out, if problems arise we can track with new issues
