### ISSUE TITLE
[OpenBMC] rspconfig needs to support multiple IPs on the BMC  and ignore ZeroConfigIPs

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4353]
With the BMC 2.0 version, FW team added in ZeroConfigIP address to the BMC, We initially took the stand that we would not support multiple IP addresses on the BMC, so we blocked this code in `rspconfig` if we were returned multiple IP objects.. 

Here's what the network returns ...

```
+ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.11.139.18/xyz/openbmc_project/network/enumerate
{
  "data": {
    "/xyz/openbmc_project/network/config": {
      "DefaultGateway": "172.11.253.27",
      "HostName": "witherspoon"
    },
    "/xyz/openbmc_project/network/config/dhcp": {
      "DNSEnabled": 1,
      "HostNameEnabled": 1,
      "NTPEnabled": 1
    },
    "/xyz/openbmc_project/network/eth0": {
      "AutoNeg": 0,
      "DHCPEnabled": 0,
      "DomainName": [],
      "InterfaceName": "eth0",
      "MACAddress": "70:e2:84:14:31:af",
      "NTPServers": [],
      "Nameservers": [],
      "Speed": 0
    },
    "/xyz/openbmc_project/network/eth0/ipv4/370b212a": {
      "Address": "169.254.80.3",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
      "PrefixLength": 16,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0_11": {
      "AutoNeg": 0,
      "DHCPEnabled": 0,
      "DomainName": [],
      "Id": 11,
      "InterfaceName": "eth0.11",
      "MACAddress": "70:e2:84:14:31:af",
      "NTPServers": [],
      "Nameservers": [],
      "Speed": 0
    },
    "/xyz/openbmc_project/network/eth0_11/ipv4/b23972be": {
      "Address": "172.11.139.18",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 16,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0_11/ipv4/ebbb9b13": {
      "Address": "169.254.181.81",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
      "PrefixLength": 16,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    },
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 0,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }
  },
  "message": "200 OK",
  "status": "ok"
}
```

Opened this internal issue https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408847 to discuss with FW team...   I'm wondering why when we set static IP , the ZeroConfig IP still stays around... 

But if nothing changes in the FW, we should look into what it would take to support xCAT ignoreing the ZeroConfigIP and running configuration on the static IP adress in the correct subnet. 

Here's the FW version that we see it on...
```
[root@briggs01 autotest]# rinv mid05tor12cn18 firm
mid05tor12cn18: BMC Firmware Product: ibm-v2.0-0-r9-0-gecda565 (Active)*
mid05tor12cn18: HOST Firmware Product: IBM-witherspoon-ibm-OP9_v1.19_1.83 (Active)*
...
```

Here's what happens...

```
[root@briggs01 autotest]# rspconfig mid05tor12cn18 ip
mid05tor12cn18: Interfaces with multiple IP addresses are not supported
```

**Comment by whowutwut** [comment]
@xuweibj Could you give an estimate on the effort required for this?

**Comment by xuweibj** [comment]
* I think for command ``rspconfig ip``, we just need to modify the output to print all info. For the output's format we need to discuss.
* For configuration, I think the IP objects belongs 2 types. 
One is that the current BMC IP configured on, and one is not. 
If we want to config IP, add a new IP object to the NIC that current BMC IP configured on and then rm the object current IP on. If we do so, I think the code is not too hard, but we need to spend much time to test.

For the above, I think more than 3 days.

**Comment by whowutwut** [comment]
@hu-weihua  @xuweibj Can we prepare some UT cases in automation in parallel? 

The issue here is that we should NOT allow the user to modify the ZeroConfig IP, how do we prevent that? It looks like the `ipmitool` inband configuration is currently sending the correct IP address but this is only a single node testing.... in the previous FW, it was not, so we were getting the 169 IP address when we did `lan print 1` on ipmitool.  

So @gurevichmark and I were only planning to support the single IP address, but looks like with the 2.0 firmware, even when we set STATIC IP, the ZeroConfigIP is not removed..

**Comment by hu-weihua** [comment]
@whowutwut, after discussing with @xuweibj, I got one information, we can configure multiple work networks in one bmc nic. That means even if there is no ZeroConfigIP network, we still have multiple networks which can be connected  from outside to BMC. is it ture?

If it is true, that means our user interface ``rspconfig <> ip``, ``rspconfig <> gateway`` ..... do not make sense. Because it is meanless for customer to just get one ip, gateway, or netmask.  Only by showing them in group can make sense for customer.   So we only need one user interface, something like ``rspconfig <> network``.   

It seems now we are letting customer set ip, gateway, or netmask in one command.  when we issue ``rspconfig <> ip``, xcat will throw out a error.

```
[root@briggs01 ~]# rspconfig mid05tor12cn02 ip=172.11.139.2
mid05tor12cn02: Error: IP, netmask and gateway must be configured together.
```
So do we still need to support user interface such like `rspconfig <> ip``, ``rspconfig <> gateway`` .....?

**Comment by gurevichmark** [comment]
@whowutwut Did you mean to set `priority: serverity` label ?

**Comment by whowutwut** [comment]
@gurevichmark Yes, I wanted to fix this for 2.13.9 so wanted to make sure that it bubbles up to the top. 

@hu-weihua Yes, that is true...  However, this value is not going to appear inband `ipmitool lan print 1`.  So what is the purpose of setting multiple inets with regards to xCAT? 

If you think there is value, we can create a small external that would describe how the admin would configure multiple intes.  

Regarding the error you print, Talking to Ratan, the ability to configure single attributes of the IP object will be supported for the GA 2.0, not sure what exactly that means, but probably not working until next year.  So in order to support this @xuweibj created PR #4326 that requires the attribute to be specified together.  (Which is why we see that error now) To implement partial support, based on the OpenBMC firmware restriction today, we would have to first obtain the IP object, then override the values that the user specifies., create a new object with the properties, and then delete the original object

**Comment by hu-weihua** [comment]
@whowutwut , My question is our test case are written to test ``rspconfig <> ip``, ``rspconfig <> gateway``, ``rspconfig <> netmask``. We suppose these command should work. But now, it seems we can not support to set IP, gateway, netmask separately, that means case should check these commands are invalid. But depending on your information, we will support these operation next year, that means case should check these commands work. So I am not sure what FVT should do next. If I keep the test case logic( checking these commands should work now), that means these case will failed everyday. But if I change the logic of test case but xcat will support them next year , it will contrary to original test_driven intention. So what is xcat final target against ``rspconfig``? that is very important.

**Comment by whowutwut** [comment]
@zet809 @xuweibj @hu-weihua @gurevichmark  We need this fixed ASAP, we cannot run `rspconfig hostname` ... or at least unblock the hostname function as it does not influenced by the multiple IPs.. 

At 1742Ef level... 
1) Need a PR to unblock the hostname setting and getting function

```
 /opt/xcat/bin/rspconfig abc123 hostname=abc123-bmc
abc123: BMC Setting Hostname...
abc123: Interfaces with multiple IP addresses are not supported
```

**Comment by whowutwut** [comment]
@hu-weihua I think we should support it and ignore printing out the ZeroConfigIP.  does that make sense... 

So the original code still applies, except now xCAT needs to know which IP addresses are ZeroConfig and which ones are User configured.  Ignore ZeroConfig ones, we can display it, but we should not allow users to modify it.  And if there is > 1 User configured IP, we should print that "multiple IP addresses are not supported message" 


Does this make sense?  If not, let's sync up on the meeting.

**Comment by whowutwut** [comment]
I am working on a quick fix

**Comment by whowutwut** [comment]
I see @zet809  fixed with #4383

**Comment by whowutwut** [comment]
This seems to be resolved, closing out.

**Comment by whowutwut** [comment]
@hu-weihua  Sorry for the really late reply, still catching up on all my email notifications for this project.. Regarding your comment above: https://github.com/xcat2/xcat-core/issues/4353#issuecomment-347439822 

I think you are correct and I think we should have supported this.  

The reason we cannot set individual ip, netmask, gateway, is because OpenBMC does not support it.  They allow us to call the REST endpoint, and it returns 200 OK, but behind the scenes it does not do anything. Ratan said they would be supporting this next year in the API, so until then, we have to specify all 3 together and we create a new IP object to make changes to the existing. 

I had brought it up in the past and I think what xCAT code should have done is the following:
1) Allow user to specify ip, netmask, gateway as the code works today with IPMI
2) We would first GET the network config... initialize with those values 
3) Over write the values specified by the user...
4) Create the new IP object. 

Then when the support is added to OpenBMC, from the users perspective, nothing is changed and our testcases would have worked fine...  just our code internally would be able to directly set existing object instead of creating a new IP object. 

@zet809 @xuweibj  FYI...
