### ISSUE TITLE
Anaconda fails to install packages if pkglist= has more than one entry.

### ISSUE THREAD

**Issue by sfantao** [xcat2/xcat-core#4368]
I was attempting to provision a machine with RHEL:
```
[root@minsky4 ~]# uname -a
Linux minsky4 3.10.0-693.5.2.el7.ppc64le #1 SMP Fri Oct 13 11:01:41 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux
```
and configured my image with two files in its pkglist= entry:

```
[root@ibmxcat1 rhels7.4-ppc64le-install-compute]# lsdef -t osimage -o rhels7.4-ppc64le-install-compute
Object name: rhels7.4-ppc64le-install-compute
    imagetype=linux
    kitcomponents=mellanox-OFED-component-1.0-2-rhels-7.4-ppc64le
    osarch=ppc64le
    osdistroname=rhels7.4-ppc64le
    osname=Linux
    osvers=rhels7.4
    otherpkgdir=/install/post/otherpkgs/rhels7.4/ppc64le
    otherpkglist=/install/osimages/rhels7.4-ppc64le-install-compute/kits/KIT_COMPONENTS.otherpkgs.pkglist
    partitionfile=s:/install/custom/rhels7.4-ppc64le-install-compute/compute-minsky.sh
    pkgdir=/install/rhels7.4/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist,/install/custom/rhels7.4-ppc64le-install-compute/compute.rhels7.pkglist
    postbootscripts=KIT_mellanox-OFED-component-1.0-2-rhels-7.4-ppc64le_kit_mlnx_ofed_install.sh
    profile=compute
    provmethod=install
    synclists=/install/custom/rhels7.4-ppc64le-install-compute/synclist
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
```
I couldn't find anything in the docs saying that doing so is illegal.

So, while provisioning anaconda would halt because it couldn't find wget during the execution of the `%%post` of the kickstart file. Curiously, when I started a shell, I was able to see that the packages were installed.

I don't understand anaconda well enough, but my guess is that it runs from inside a sandbox and it also needs the packages there and that xCAT configuration caused it fail doing so.

I was able to work around this by moving the second entry in the pkglist to otherpkglist, but it would be nice to have this fixed to avoid other people getting into the same problem. Alternatively, one should provide a diagnostic saying that that is not legal to do.

This is my xCAT version:
```
Version 2.13.8 (git commit fe7405f1702f63758e0b65ae7999bd457ea0cd5a, built Thu Nov  2 07:15:44 EDT 2017)
```

Thanks

**Comment by zet809** [comment]
hi, @immarvin ,will you pls take a look at? Thx!

**Comment by immarvin** [comment]
hi @sfantao , what did you specified in `/install/custom/rhels7.4-ppc64le-install-compute/compute.rhels7.pkglist`, are they all included in the `/install/rhels7.4/ppc64le` directory?

`pkglist` should only contain the pkgs which are shipped in the os installation iso and can be found in the`pkgdir` generated by `copycds`?

**Comment by immarvin** [comment]
hi @sfantao , would you please provide the output of `cat /install/autoinst/<*replace me with the node name you provision*>|grep -A30 -w 'packages'`

**Comment by sfantao** [comment]
hi @immarvin, here's the information you requested:

```
[root@ibmxcat1 install]# cat /install/custom/rhels7.4-ppc64le-install-compute/compute.rhels7.pkglist
git
nano
openldap
openldap-clients
sssd-ldap
Lmod
cuda
bzip2
gcc-gfortran
```
Not all of these packages, are available in `/install/rhels7.4/ppc64le`. I didn't know that was requirement. They are available in separate repositories but all in the same server, under `/install`.

```
[root@ibmxcat1 autoinst]# cat /install/autoinst/minsky4 |grep -A30 -w 'packages'
%packages
#INCLUDEBAD:cannot open /opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist,/install/custom/rhels7.4-ppc64le-install-compute/compute.rhels7.pkglist#
%end
%pre
{
echo "Running Kickstart Pre-Installation script..."
export XCATDEBUGMODE=""
if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
    set -x
fi

if grep n8r /proc/cmdline > /dev/null 2>&1;
then
  stty crtscts
fi
for x in 0 1 2 3 4 5 6 7 8
do
	mknod /dev/vcs$x c 7 $x
	mknod /dev/vcsa$x c 7 $[$x+128]
done
chmod 644 /dev/vcs*
chown root /dev/vcs*
if [ -r /tmp/updates/etc/pki/tls/certs/ca-bundle.crt ]; then
        cp -f /tmp/updates/etc/pki/tls/certs/ca-bundle.crt /etc/pki/tls/certs/
fi



cat >/tmp/baz.py <<EOF
#!/usr/bin/python
import socket
```

Thanks!
Samuel

**Comment by immarvin** [comment]
hi @sfantao , there are 2 problems according to your info:
1. currently, the `osimage.pkglist`  should only contain the pkgs under `osimage.pkgdir`, i.e, `/install/rhels7.4/ppc64le`, for 3rd party pkgs, you can follow http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_other_pkg.html and specify the appropriate `osimage.otherpkgdir` and `osimage.otherpkglist` 

2. currently, xCAT does not support multiple pkglist files be specified in `osimage.pkglist`, but you can use  macro `#INCLUDE:/install/post/custom/<distro>/myotherlist#` in `osimage.pkglist` or `osimage.otherpkglist` to include multiple separate pkglists, see http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_pkg.html#include-pkglist-files  and http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_other_pkg.html#include-other-pkglist-files for details

**Comment by sfantao** [comment]
@immarvin, thanks for the clarification. I was not aware of 

> currently, xCAT does not support multiple pkglist files be specified in osimage.pkglist

and that was the main reason why I filed this issue. Feel free to close if you think that's right thing to do.
