### ISSUE TITLE
[FVT]: 2.12: could not go to next state in currchain when currstate is shell

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#437]
This bug is found when I use test provision after I create the RAID.

Here is the command I used to define node:

[root@c910f03c05k23 ~]# nodeset p8euh runcmd="configraid delete_raid=all stripe_size=256 create_raid=rl#0|pci_slot_name#0001:08:00.0|disk_num#2",shell,osimage=ubuntu14.04.2-ppc64el-install-compute
p8euh: runcmd=configraid delete_raid=all stripe_size=256 create_raid=rl#0|pci_slot_name#0001:08:00.0|disk_num#2
[root@c910f03c05k23 ~]# rsetboot p8euh net
p8euh: Network
[root@c910f03c05k23 ~]# rpower p8euh reset
p8euh: reset

Monitor the console, after raid is created, system goes into shell, but could not go ahead to start provsion.

[root@c910f03c05k23 ~]# lsdef -l p8euh
Object name: p8euh
    arch=ppc64el
    bmc=50.3.15.1
    bmcpassword=passw0rd
    cons=ipmi
    conserver=10.3.5.23
    currchain=osimage=ubuntu14.04.2-ppc64el-install-compute
    currstate=shell
    groups=all,kvm
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=10.4.41.200
    kcmdline=quiet console=tty0 console=hvc0,115200 xcatd=10.3.5.23:3001 destiny
    kernel=xcat/genesis.kernel.ppc64
    mac=6C:AE:8B:02:12:50
    mgt=ipmi
    netboot=petitboot
    nfsserver=10.3.5.23
    os=ubuntu14.04.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    primarynic=mac
    profile=compute
    provmethod=ubuntu14.04.2-ppc64el-install-compute
    serialport=0
    serialspeed=115200
    status=shell
    statustime=11-19-2015 02:52:39
    tftpserver=10.3.5.23

**Comment by whowutwut** [comment]
Since this is waiting in shell, does ssh into shell and exit cause the process to continue?

**Comment by tingtli** [comment]
Verified can closed. 
I don't have raid system, so i only test nodeset c910f05c33 shell,osimage=ubuntu14.04.3-ppc64el-install-compute. Did not try "nodeset p8euh runcmd="configraid delete_raid=all stripe_size=256 create_raid=rl#0|pci_slot_name#0001:08:00.0|disk_num#2",shell,osimage=ubuntu14.04.2-ppc64el-install-compute"

```
[root@c910f03c05k23 ~]# lsxcatd -v
Version 2.12 (git commit 588076d19fdf219157690ce65299e92ca42f1398, built Fri May 20 03:10:38 EDT 2016)
[root@c910f03c05k23 ~]# cat /etc/*release*
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2 Beta"
Red Hat Enterprise Linux Server release 7.2 Beta (Maipo)
Red Hat Enterprise Linux Server release 7.2 Beta (Maipo)
cpe:/o:redhat:enterprise_linux:7.2:beta:server
[root@c910f03c05k23 ~]# nodeset c910f05c33 shell,osimage=ubuntu14.04.3-ppc64el-install-compute
c910f05c33: shell
[root@c910f03c05k23 ~]# rsetboot c910f05c33 net
c910f05c33: Network
[root@c910f03c05k23 ~]# lsdef -l c910f05c33
Object name: c910f05c33
    arch=ppc64el
    bmc=50.5.33.10
    bmcpassword=passw0rd
    bmcusername=ADMIN
    cons=ipmi
    currchain=osimage=ubuntu14.04.3-ppc64el-install-compute
    currstate=shell
    groups=firm
    hidden=0
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=10.5.33.254
    kcmdline=quiet console=tty0 console=hvc0,115200 xcatd=10.3.5.23:3001 destiny=shell
    kernel=xcat/genesis.kernel.ppc64
    mac=98:be:94:59:ea:27
    mgt=ipmi
    netboot=petitboot
    nodetype=mp
    os=ubuntu14.04.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,xHRM bridgeprereq br0
    primarynic=mac
    profile=compute
    provmethod=ubuntu14.04.3-ppc64el-install-compute
    serialport=0
    serialspeed=115200
    status=booted
    statustime=06-16-2016 21:13:44
    updatestatus=synced
    updatestatustime=12-03-2015 01:44:09
```
