### ISSUE TITLE
[automation] rspconfig show "AttributeError("Attribute 'parameter_list' not defined.",)" when set ip/netmask/gateway/vlan

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4370]
xcat version:

Version 2.13.9 (git commit f5437609d44aba15a7a3f0b3933d5b01593c11ca, built Thu Nov 23 06:15:44 EST 2017)

The error are:
```
[root@c910f03c11k08 ~]# rspconfig  f6u17 netmask=255.0.0.0
f6u17: Error: AttributeError("Attribute 'parameter_list' not defined.",)

[root@c910f03c11k08 ~]# rspconfig  f6u17 gateway=10.0.0.101
f6u17: Error: AttributeError("Attribute 'parameter_list' not defined.",)

[root@c910f03c11k08 ~]# rspconfig  f6u17 ip=10.6.17.100
f6u17: Error: AttributeError("Attribute 'parameter_list' not defined.",)

[root@c910f03c11k08 ~]# rspconfig  f6u17 vlan=Disabled
f6u17: Error: AttributeError("Attribute 'parameter_list' not defined.",)
```

**Comment by whowutwut** [comment]
@hu-weihua I removed this "bug" label because we already have one: "type:bug"

**Comment by whowutwut** [comment]
@hu-weihua This is related to: https://github.com/xcat2/xcat-core/issues/4378
Although I think the fix for that one is not the same since that one the endpoint is HostName....  

@xuweibj can we fix this bug asap?

**Comment by whowutwut** [comment]
@hu-weihua I believe this was caused by this issue, https://github.com/xcat2/xcat-core/issues/4378 It seems to show the same attributes, since that one is merged, if we do not see anything in the FVT automation these few days, we can close it out.

**Comment by hu-weihua** [comment]
It seems the bug has been fixed. close this issue.
