### ISSUE TITLE
genimage and latest sles 12 sp2 dracut update

### ISSUE THREAD

**Issue by sergimore** [xcat2/xcat-core#4372]
SLES has changed the dracut string version format in last update (dracut-044.1-109.17.1.x86_64) and I think that this breaks the way genimage is checking for dracut version. 

# rpm -qi dracut | grep Version
Version     : 044.1

/opt/xcat/share/xcat/netboot/sles/genimage is expecting only three decimal characters:

if ($dracutver =~ /^\d\d\d$/)...

Line 620 from /opt/xcat/share/xcat/netboot/sles/genimage

When running genimage it fails with following error:

dracut: dracut module 'xcat' cannot be found or installed.
Error: failed to generate the initial ramdisk for stateless..

I'm using xcat 2.13.5 but 2.13.8 has same genimage code.

Thank you,
Sergi.

**Comment by immarvin** [comment]
hi @bybai , would you please take a look at this? thanks

**Comment by bybai** [comment]
Hi @sergimore , thanks reporting this, will reproduce and fix it later.
