### ISSUE TITLE
[Customer]xCAT 2.11 disabled logging to /var/log/messages

### ISSUE THREAD

**Issue by mfoliveira** [xcat2/xcat-core#438]
Hi,

xCAT commented out the logging to /var/log/messages in rsyslog.conf
With xCAT-2.11-snap201511121931.ppc64le, RHEL 7.x, S822LC.

3rd chunk in this diff:

```
[root@xcat-mn ~]# diff /etc/rsyslog.conf.XCATORIG /etc/rsyslog.conf
15,16c15,16
< #$ModLoad imudp
< #$UDPServerRun 514
---
> $ModLoad imudp
> $UDPServerRun 514
19,20c19,20
< #$ModLoad imtcp
< #$InputTCPServerRun 514
---
> $ModLoad imtcp
> $InputTCPServerRun 514
54c54
< *.info;mail.none;authpriv.none;cron.none                /var/log/messages
---
> #*.info;mail.none;authpriv.none;cron.none                /var/log/messages
91a92,93
> # xCAT settings
> #*.debug  /var/log/messages
```

**Comment by whowutwut** [comment]
@neo954  can you take a look at this?

**Comment by neo954** [comment]
@mfoliveira , Now, xCAT log to ``/var/log/xcat/cluster.log``. And all the logs coming from xCAT compute nodes go to ``/var/log/xcat/computes.log``.

**Comment by tingtli** [comment]
This is not a defect, it is a feature support in xCAT 2.11.
I move this discussion in 2.12 release.

**Comment by mfoliveira** [comment]
@neo954 

Hi. Yeah, the xCAT logs are properly handled, I see.
The problem is that *non-xCAT* logs are discarded.
I don't see a replacement/modifier for the *.info rsyslog rule for non-xCAT components.

AFAIK, the rules in /etc/rsyslog.d/xcat-*.conf are OK for this xCAT feature,
but commenting the *.info rule disables far more than just xCAT messages.

Is there any other place or rule for logging non-xCAT components elsewhere?

@tingtli 

If there's no other rule for keeping the logs of non-xCAT components in some place, this looks like a defect, for 2.11. As it's a valid use-case to look for system logs of non-xCAT components (say, dhcp, dns, disks, etc)

Thanks!

**Comment by whowutwut** [comment]
@neo954 , just looking at this and maybe there is some misunderstanding.  What @mfoliveira  is saying is that the normal system logs are no longer being saved into /var/log/messages.  We should save the xCAT related logs into /var/log/xcat but what happened to the other non xCAT system log messages?   

Looking at my test system...  It's empty. 
```
[root@c910f03c04k12 log]# ls -ltr /var/log/messages
-rw------- 1 root root 0 Dec  7 03:19 /var/log/messages
```

Did we configure this incorrectly?

**Comment by neo954** [comment]
This issue is tracked with issue #739. Thus I will close this one.
