### ISSUE TITLE
[OpenBMC] rspconfig has no information about the dump option

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4381]
Issues: 
* man page does not have any information for dump 

Enhancement
* Can we have a short help usage to help OpenBMC users? The man page is too much 

I think dump will be used by https://github.com/xcat2/xcat-core/issues/4331 but ...is there a way to reduce the help output?? `rspconfig mid05tor12cn18 dump -h` can be handled by the openbmc.pm plugin? 

```
[root@briggs01 910.1746.20171124a_1742Ee]# rspconfig mid05tor12cn18 dump
mid05tor12cn18: Error: Invalid parameter for rspconfig
```

**Comment by whowutwut** [comment]
@gurevichmark If not done by tomorrow, Could you help create the man page for this? 

```
rspconfig <noderange> dump 

with no options, will generate, wait and download the dump files to /var/log/xcat/dump
```

I believe these are the supported options, @xuweibj please correct me if mistake. 

```
-c <id> | all 
  clear single with <id> or all will clear all 

-l 
  list 

-g 
  generate a dump 

-d <id>
  download a dump
```

**Comment by gurevichmark** [comment]
Man page and usage added by PR #4491

**Comment by whowutwut** [comment]
Closing this out.
