### ISSUE TITLE
`genimage` tries direct DB access instead of via xCATd

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4385]
When I try to run `genimage` as a non-privileged user, I get the following error:
```
[samveen@xcatmn1 ~]$ genimage centos7.4-x86_64-netboot-compute
Failed to connect to site table after retrying 3 times: DBI connect('/etc/xcat/site.sqlite','',...) failed: unable to open database file at /opt/xcat/lib/perl/xCAT/Table.pm line 972.

Can't call method "prepare" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 998.
```

I assume it is because the checks are in the client command side (in `bin/genimage`) instead of `xCATd` introduced in this commit:
```
commit 6abbe5c74b2b00d8681a3cb96f8028ddd472917a
Author: sjing <sjing@8638fb3e-16cb-4fca-ae20-7b5d299a9bcd>
Date:   Tue Jun 18 08:08:03 2013 +0000

    bug2830 - use xCAT::TableUtils->get_site_attribute("installdir") instead of gettab.
    
    git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/trunk@16658 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd
```

Is is possible to move the checks into `genimage.pm`, so that `genimage` works as expected while honouring `policy`.

**Comment by zet809** [comment]
hi, @immarvin , will you pls help to take a look at? Thx!

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4924

**Comment by immarvin** [comment]
hi @samveen , the fix is in ,you can verify whether this fixed your issue.
ps, you need to grant the user permission for  `genimage` and `lsdef` to run `genimage`
