### ISSUE TITLE
[OpenBMC] DBusException when checking progress, maybe need to open CQ issue

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4388]
Sometimes we see this message and I've been going back and forth with FW team about it... 

```
f7n13: Activating firmware . . . 30%
f7n11: Activating firmware . . . 30%
f7n12: Activating firmware . . . 30%
f7n14: Activating firmware . . . 30%
f7n13: Error: DBusException("Unknown interface 'xyz.openbmc_project.Software.ActivationProgress'.",)
f7n11: Activating firmware . . . 30%
f7n12: Firmware activation Successful.
f7n14: Firmware activation Successful.
f7n11: Firmware activation Successful. 
```

Talking to the FW team, the issue here is that the activation progress is ONLY available when the firmware is Activating.  Once it's Active, this value is no longer there. So on our polling interval of 15 seconds, we will sometimes hit the case where the Firmware activated already and then we query that...?  But I don't think this is accurate because I think when I turned debug on, we only go against the `software/<id>` endpoint... 

On another run:
```
f7n12: Firmware activation Successful.
f7n13: Error: DBusException("Unknown interface 'xyz.openbmc_project.Common.FilePath'.",)
f7n11: Firmware activation Successful.
```

So looks like there are various DBusExceptions being thrown...  

@gurevichmark can you ask the FW team about this and maybe open a CQ issue?

**Comment by whowutwut** [comment]
```
[root@briggs01 910.1746.20171116b_1742Ed]# XCATBYPASS=1 rflash $NODE -a 82087175
DEBUG filename=0, updateid=1, options=-a, invalid= rflash_arguments=82087175
Attempting to activate ID=82087175, please wait...
Mon Nov 20 12:07:36 2017 mid05tor12cn15: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.11.139.15/login
Mon Nov 20 12:07:37 2017 mid05tor12cn15: [openbmc_debug] login_response 200 OK
Mon Nov 20 12:07:37 2017 mid05tor12cn15: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.Software.Activation.RequestedActivations.Active"}' https://172.11.139.15/xyz/openbmc_project/software/82087175/attr/RequestedActivation
Mon Nov 20 12:07:38 2017 mid05tor12cn15: [openbmc_debug] rflash_update_activate_response 200 OK
Mon Nov 20 12:07:38 2017 mid05tor12cn15: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.15/xyz/openbmc_project/software/82087175
Mon Nov 20 12:07:41 2017 mid05tor12cn15: [openbmc_debug] rflash_update_check_state_response 500 Internal Server Error
mid05tor12cn15: Error: DBusException("Unknown interface 'xyz.openbmc_project.Software.ActivationProgress'.",)
```

Found some debug code here above, we just loop over that endpoint.. perhaps they fixed some DBus Exception issues?

**Comment by whowutwut** [comment]
Cross reference CQ issue: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW409813

Slack conversation with Deepak: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1511930173000116

**Comment by zet809** [comment]
THe CQ issue is closed with `the BMC needs to be at the fixed level (1742Ex), then update to
a different level to verify this defect.`, so let's close this issue.
