### ISSUE TITLE
IBM Power S812LC using rspconfig to set bmc ip address failed if the bmc is in dhcp mode 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#440]
# rspconfig dn22 ip
dn22: BMC IP: 50.2.0.28

 # rspconfig dn22 ip=50.2.0.72
dn22: BMC IP: 50.2.0.28

 # rspconfig dn22 ip
dn22: BMC IP: 50.2.0.28

 # ipmitool-xcat -I lanplus -H 50.2.0.28 -U xxx -P xxx lan print 1
Set in Progress         : Set Complete
Auth Type Support       : MD5 
Auth Type Enable        : Callback : MD5 
                        : User     : MD5 
                        : Operator : MD5 
                        : Admin    : MD5 
                        : OEM      : MD5 
IP Address Source       : DHCP Address
IP Address              : 50.2.0.28
Subnet Mask             : 255.0.0.0
MAC Address             : a0:42:3f:30:62:5e
SNMP Community String   : AMI
IP Header               : TTL=0x40 Flags=0x40 Precedence=0x00 TOS=0x10
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Gratituous ARP Intrvl   : 0.0 seconds
Default Gateway IP      : 0.0.0.0

Default Gateway MAC     : 00:00:00:00:00:00
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:c0:a4
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 
Cipher Suite Priv Max   : Not Available

**Comment by zet809** [comment]
Pull request 443.

**Comment by whowutwut** [comment]
@zet809  Can you modify the above and wrap in markdown.  

You are trying to set dn22 to 50.2.0.72 and it does not work? Can you use rspconfig to display the existing configured IP address? Before and after?  
For my knowledge, looking at ipmitool output against 50.2.0.28, how can you tell that BMC is in DHCP mode? Does the rspconfig work if the BMC is not in DHCP mode? 

Trying to understand the problem so I can better review the fix.

**Comment by zet809** [comment]
@whowutwut I have modify the defect description.
For the 2nd question, you can see line "IP Address Source : DHCP Address" from output of ipmitool which means the BMC get ip address through DHCP. 
The origin rspconfig ip=<new_bmc_ip> works for System X and Tuleta machines when the BMC is in DHCP mode, but S812LC doesn't.

**Comment by bybai** [comment]
Hi @whowutwut and @zet809 ,
``bmcdiscover`` can show  if ip source for BMC ip is dhcp or static ip address; I added the feature when I developed ``bmcdiscover`` 
for example:
```
[root@c910f03c05k23 ~]# bmcdiscover -i 50.3.15.1 -p passw0rd --ipsource
 Static Address
```
