### ISSUE TITLE
[OpenBMC] Improve messages when BMC is not responding correctly

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4403]
Opening an issue here to collect possible ways to help both the Admins and ourselves when debugging issues with the BMC, whether it's incorrect IP configuration or some issue on the BMC itself... 

Today, we only get the following message: 
```
[root@briggs01 ~]# rpower mid05tor12cn18 state
mid05tor12cn18: Error: BMC did not respond. Verify BMC is in BMCReady state and retry the command.
```
This doesn't help anyone know the "next steps" on what is going on with this BMC, but in the code, we do know more than we are printing out.

**Comment by whowutwut** [comment]
Handling the following tests: 

Scenario 1:  BMC IP is incorrect

```
[root@stratton01 ~]# rpower p9euh01 state
p9euh01: Error: Login to BMC failed. Status: 500 Can't connect to 10.6.7.254:443 (No route to host).
p9euh01: Error: BMC did not respond. Validate BMC configuration and retry the command.
```

Scenario 2: BMC is pinging, but not ready

**Comment by whowutwut** [comment]
Let me keep this issue open for a bit, need to figure out to make sure other areas are OK

**Comment by zet809** [comment]
What is the status for this issue? SHall we close it?

**Comment by whowutwut** [comment]
Yes, thanks @zet809, the output has changed quite a bit and I think it's OK now with the recent pull requests.
