### ISSUE TITLE
[OpenBMC] Allow the ability to set/get the value of AutoReboot on the BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4405]
Seems like this is a function of interest that popped up recently....

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Control/Boot/RebootPolicy.interface.yaml  - No README like usual...

**Endpoint**: https://BMCIP/xyz/openbmc_project/control/host0/auto_reboot
**Protocol**: GET 
**Output**: 
```
+ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.11.139.5/xyz/openbmc_project/control/host0/auto_reboot
{
  "data": {
    "AutoReboot": 1
  },
  "message": "200 OK",
  "status": "ok"
}
```

SET should be a PUT command similar to other places in the code. 

### Proposed Externals: 

Display: 
   * `rspconfig <node range> autoreboot`

Modify:  
   * `rspconfig <node range> autoreboot=0` 
   * `rspconfig <node range> autoreboot=1`

**Comment by whowutwut** [comment]
I believe the nodes FW have this defaulted to on, and the plan is to have this running autoboot=1 (on) , but this may be a good feature to have to help assist changing this configuration.  

Thinking about this, i wonder if there's some generic mapping file that we could create that would give us generic keyword support... 

autoreboot => { control/host0/auto_reboot , { on, off },  } 


Then if `rspconfig <node> keyword` we could support based on some mapping that we create... 

just throwing out some idea...

**Comment by whowutwut** [comment]
Looks like no one picked this up...  added high.

**Comment by gurevichmark** [comment]
I will start looking at this.

**Comment by gurevichmark** [comment]
The command to set the value:
```
 curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data":true}' https://mid05tor12cn16-bmc/xyz/openbmc_project/control/host0/auto_reboot/attr/AutoReboot
```
