### ISSUE TITLE
remoteshell is very slow

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4414]
`remoteshell` has a LOT of long-ish sleeps in it.

```
[root@mgmt1 ~]# time updatenode h41n01 -P remoteshell
h41n01: xcatdsklspost: downloaded postscripts successfully
h41n01: Fri Dec  1 01:06:17 EST 2017 Running postscript: remoteshell
h41n01:
h41n01: postscript: remoteshell exited with code 0
h41n01: Running of postscripts has completed.

real    2m17.663s
user    0m0.566s
sys     0m0.029s
```

I tried to enable xCAT flow support, but that actually took longer.
```
[root@mgmt1 ~]# time updatenode h41n01 -P remoteshell
h41n01: xcatdsklspost: downloaded postscripts successfully
h41n01: Fri Dec  1 01:10:07 EST 2017 Running postscript: remoteshell
h41n01:
h41n01: postscript: remoteshell exited with code 0
h41n01: Running of postscripts has completed.

real    3m0.601s
user    0m0.588s
sys     0m0.010s
```

I hopped on the node and saw 14 concurrent `xcatflowrequest` commands that were reparented to init.  I didn't tune `xcatmaxconnections` or `xcatmaxbatchconnections`, but I only ran this on a single node, so the defaults should be ok.

It would be great if `remoteshell` could get all the keys in a single command instead of one sleep+RTT for each key.

**Comment by robin2008** [comment]
Yes, it would be more efficient to request all in one round.

And for better understand your point, how many nodes in provisioning at the time when you find the problem?

**Comment by mattaezell** [comment]
In both cases, this was on a single node using `updatenode`.  For the first case, it's somewhat expected since there are a bunch of `sleep`s in the code.  For the second case, I don't think flow control is working correctly.

**Comment by mattaezell** [comment]
```
[root@mgmt1 ~]# time ssh h41n01 /bin/true

real    0m0.283s
user    0m0.098s
sys     0m0.000s
```

**Comment by robin2008** [comment]
@immarvin it it possible to get a tarball there for all required keys to improve the efficiency?

For Flow control, let's discuss it later after more investigation.

**Comment by immarvin** [comment]
hi @mattaezell , there are indeed several request/response dialogs between mn and cn during the execution of `remoteshell`, but i do not think it will cost 3min for single node, would you please provide the following info:

1. set `site.xcatdebugmode=1` and run `updatenode -P remoteshell`, the trace output can be seen in the output, you can find which line takes most time
2. please provide the `ps aux --forest` on mn during during the invoking of `remoteshell ` on cn

**Comment by immarvin** [comment]
hi @mattaezell , any update on this?

**Comment by mattaezell** [comment]
@immarvin Sorry for the delay.  With debug mode on, it dumps our private keys to the logs, so I can't upload it without scrubbing it first.

I'm seeing it retry `getcredentials.awk ssh_root_pub_key` 10 times.  About to look into root cause of that.

**Comment by mattaezell** [comment]
Our `/root/.ssh/id_rsa.pub` doesn't have a newline at the end.  Adding that seems to fix it.  I'll see if I can get our config management software to include the newline, but it might make sense for xCAT to also check and add a newline if not present.

With the newline, `remoteshell` completes very quickly.

**Comment by whowutwut** [comment]
Wow @mattaezell  interesting find there! Good that it gets around this issue. 

@immarvin I don't think our `id_rsa.pub`  key file has a new line at the end of it...  Wonder if something else is going on here too?

**Comment by mattaezell** [comment]
@whowutwut To make sure we are on the same page, I don't mean an extra newline, I mean no newline anywhere in the file.  If you `cat id_rsa.pub` on our system, your next prompt shows up on the same line as the output

**Comment by immarvin** [comment]
hi @mattaezell , good catch.

@whowutwut , if pub key does not have newline at the end, the response of `getcredentials.awk ssh_root_pub_key` will looks like:
 
````
    <content>
ssh-rsa CCCCCCCC1yc2EAAAADAQABAAABAQDPrk8c7kPswicTDjExYu17q0aJsMKYRi7BJmBnV7TphLqJ2n+xYanbdhnEST27Oj10uHnHRSgT8mUM90tBuIYHs2W0/ytq4evnGRYkhhw5TyKRxHHpXoM0dolkx4zi31g5THaqDRr30Rf+IoEkJktDv8RxWYyzOpdGYFkvhrElOK2DCP/BZ5c9gBwUMb8szqGyD37oXjVVApnAUOnE21xM9G5CyZnkyBgxB2dZHZ3yf2f2i7rXhKlAqResWw0fZ7tJeBfEPaB4n8FR0sHyJeOg6ssdTjmYu8zgtVAeBna9dTTAAAAAAAAAAAAAAAA root@AAAAAAAA.abc.com</content>
````

when our `remoteshell` tries to strip out the extra lines in the xml formatted response with `./getcredentials.awk ssh_root_pub_key|grep -E -v '</{0,1}xcatresponse>|</{0,1}serverdone>'|sed -e 's/&lt;/</' -e 's/&gt;/>/' -e 's/&amp;/&/' -e 's/&quot/"/' -e "s/&apos;/'/"|grep -E -v '</{0,1}errorcode>|</{0,1}data>|</{0,1}content>|</{0,1}desc>'`, the key data will be filtered out, so a blank key file is generated
