### ISSUE TITLE
Hierarchical mode support with nodenames in synclist

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4425]
Hi!

It looks like having nodenames in synclist doesn't work in hiearchical mode.

I have a syncfile that contains:
```
/tmp/a   -> (sh-101-60)     /tmp/a
/tmp/b   -> (sh-6-34)       /tmp/b
```

`sh-101-60` is directly managed by the management node, while `sh-6-34` is managed by a service node:
```
# lsdef -c sh-101-60,sh-6-34 -i servicenode
sh-101-60: servicenode=
sh-6-34: servicenode=sh-hn03
```

Distributing files on `sh-101-60` (direct mode) works normally:
```
# updatenode sh-101-60 -F
File synchronization has completed for nodes.
# md5sum /tmp/a && ssh sh-101-60 md5sum /tmp/a
c563744e1d6d090285937d352e3128db  /tmp/a
c563744e1d6d090285937d352e3128db  /tmp/a
```
but it fails on `sh-6-34` (hierarchical mode):
```
# updatenode sh-6-34 -f
File synchronization has completed for service nodes.
# updatenode sh-6-34 -F
sh-6-34: Permission denied (publickey,hostbased).
sh-6-34: /tmp/rsync_sh-6-34: line 3: syntax error near unexpected token `('
sh-6-34: /tmp/rsync_sh-6-34: line 3: `/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz  /var/xcat/syncfiles/tmp/b sh-hn01.SUNet@sh-6-34:(sh-6-34)/tmp'
File synchronization has completed for nodes.
```

The problem is that the `rsync` script generated for the hierarchical mode fails to filter synclist entries based on hostnames and includes them all, with an erroneous syntax:
```
# ssh sh-hn03 cat /tmp/rsync_sh-6-34
#!/bin/sh
/usr/bin/ssh  sh-hn01.SUNet@sh-6-34 '/bin/mkdir -p (sh-6-34)/tmp (sh-101-60)/tmp'
/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz  /var/xcat/syncfiles/tmp/b sh-hn01.SUNet@sh-6-34:(sh-6-34)/tmp
/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz  /var/xcat/syncfiles/tmp/a sh-hn01.SUNet@sh-6-34:(sh-101-60)/tmp
```
Note how the generated `rsync` command still includes the destination hostname inside parenthesis as the destination path for the file.

Could you please provide a fix for this? This is currently making the hierarchical mode pretty unusable for us. Thanks!

**Comment by kcgthb** [comment]
I've started looking at the code, and I can see two issues with the current state of things:

### 1. incorrect `synclist` parsing on SN
The synclist file parsing that is done in the `parse_rsync_input_file_on_SN()` function in `/opt/xcat/lib/perl/xCAT/DSHCLI.pm` on the Service Nodes completely ignore the `src -> (node) dest` format. This is what leads to the incorrect `rsync` commands mentioned earlier. The relevant part of code is at https://github.com/xcat2/xcat-core/blob/master/perl-xCAT/xCAT/DSHCLI.pm#L5658

### 2. SN synchronization doesn't take destination nodes into account
Even with the first issue fixed, there would still be a problem: the Service Node synchronization (`updatenode -f/--snsync`) doesn't take that noderange syntax into account either. Which means that the intermediate SN sync only copies the files for which the Service Node is in the permitted node list, and skip the ones that are explicitly listed for the destination node.

With my previous examples, `/tmp/b` would never be copied to `sh-6-34`, since `sh-6-34`'s service node (`sh-hn03`) is not in the destination list for that file, so it would simply not be copied to `/var/xcat/syncfiles` on `sh-hn03`. And `updatenode sh-6-34 -F` would fail to copy `/tmp/b` from `sh-hn03` to `sh-6-34`.

I guess the `DSHCLI.pm` script would have to build the list of files to sync to the Service Nodes by considering all the nodes that are serviced by that SN as valid destinations.

<br/>

This is a quite a serious limitation right now, I'm really surprised that nobody ever tried this before. I would really appreciate if the priority could be raised and that bug, to provide a fix in a timely fashion. Thanks!

**Comment by cxhong** [comment]
@kcgthb , thanks.   We will debug this on our test system.

**Comment by kcgthb** [comment]
Hi @cxhong 
I'm proposing a fix in PR #4445. It seems to be working fine for our needs, but I don't pretend to have thought about all possible cases.

**Comment by kcgthb** [comment]
Hi @cxhong 
Did you manage to reproduce the issue in your test system and figure out a fix? 

Again, this is currently very impactful for us and is currently delaying a major system migration we've been planning for months, as we just discovered the problem. So we would really appreciate any attention you could bring to this matter.

**Comment by whowutwut** [comment]
@robin2008 can you also help look at this as well...   I think @kcgthb has created a pull request but it doesn't address the issue completely...

**Comment by kcgthb** [comment]
I think I found a better test to correctly address the situation I mentioned in https://github.com/xcat2/xcat-core/pull/4445#issuecomment-349472901

Given the following `synclist`, `xdcp <node> -F synclist` now works reliably:
```
# sn1:  service node
# cn2:  compute node, hierarchical mode
# cn1:  compute node, direct mode (no service node)

# common file
/tmp/xdcp/common         ->           /tmp/xdcp/

# node specific, different destination
/tmp/xdcp/sn1            -> (sn1)     /tmp/xdcp/
/tmp/xdcp/cn1            -> (cn1)     /tmp/xdcp/
/tmp/xdcp/cn2            -> (cn2)     /tmp/xdcp/

# node specific, same destination
/tmp/xdcp/c.sn           -> (sn1)     /tmp/xdcp/dest
/tmp/xdcp/c.cn_direct    -> (cn1)     /tmp/xdcp/dest
/tmp/xdcp/c.cn_via_sn    -> (cn2)     /tmp/xdcp/dest
```

**Comment by robin2008** [comment]
@kcgthb 
`sh-hn01.SUNet` is your MN fqdn name, right? 

could you run below command successfully on your `sh-hn03`?
`/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz  /var/xcat/syncfiles/tmp/a sh-hn01.SUNet@sh-6-34:/tmp`

**Comment by kcgthb** [comment]
@robin2008 
> `sh-hn01.SUNet` is your MN fqdn name, right?

That's correct, yes.

> could you run below command successfully on your sh-hn03?
`/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz /var/xcat/syncfiles/tmp/a sh-hn01.SUNet@sh-6-34:/tmp`

Nope, indeed, it doesn't work, because `sh-hn01.SUNet@sh-6-34:/tmp` is not a valid destination, it should be `root@sh-6-34:/tmp`. I just realized this and I'm currently trying to understand why a hostname (`sh-hn01.SUNet`) ends up being used instead of a valid username.

The problem does not happens when using `xdcp sh-6-34 -F synclist`: in that case, the generated `/tmp/rsync_sh-6-34` on the SN (`sh-hn03`) is well formatted and contains:
```
/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz  /var/xcat/syncfiles/tmp/xdcp/common /var/xcat/syncfiles/tmp/xdcp/sh-6-34 root@sh-6-34:/tmp/xdcp/
```

But when using `updatenode sh-6-34 -F`, the resulting `/tmp/rsync_sh-6-34` file uses the MN hostname instead of `root`:
```
/usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz /var/xcat/syncfiles/tmp/a sh-hn01.SUNet@sh-6-34:/tmp
```

My analysis so far is that at some point in the process, the `DSH_FROM_USERID` environment variable is set to `sh-hn01.SUNet` (which is wrong) when using `updatenode -F`, but not when using `xdcp -F`. I'm trying to figure out where this comes from, but if you have any pointer, that may go faster. :)

**Comment by kcgthb** [comment]
I traced the source of the hostname/username issue to https://github.com/xcat2/xcat-core/blob/master/xCAT-server/sbin/xcatd#L1514
```
        my $peer     = $connection->peer_certificate("owner");
        if ($peer) {
            $peer =~ m/CN=([^\/]*)/;
            $peername = $1;
        } else {
            $peername = undef;
        }
```

In my case, `$connection->peer_certificate("owner");` returns the hostname of my management server (`sh-hn01.SUNet`), instead of a username. 

Any idea why?

**Comment by kcgthb** [comment]
So, I can confirm that this piece of code gets certificate information that comes from `/etc/xcat/cert/server-cert.pem` on the management node. This certificate identifies the MN host, not any user, so I can't understand why `xcatd` expects to get some username information out of it...

**Comment by kcgthb** [comment]
Oh, I just realized this is exactly the issue described in #4455 !
