### ISSUE TITLE
makedhcp -d not working

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4426]
I haven't tried this before today, so maybe I'm doing something wrong.  Should this work?

```
[root@mgmt1 ~]# makedhcp -d a05n13
[root@mgmt1 ~]# echo $?
0
[root@mgmt1 ~]# grep a05n13 /var/lib/dhcpd/dhcpd.leases
host a05n13 {
        supersede server.ddns-hostname = "a05n13";
        supersede host-name = "a05n13";
        supersede conf-file = "http://10.10.0.11/tftpboot/petitboot/a05n13";
```

**Comment by mattaezell** [comment]
Maybe we have a larger issue with dhcp...
```
[root@mgmt1 ~]# chdef a05n13 mac=aa:bb:cc:dd:ee:aa
1 object definitions have been created or modified.
[root@mgmt1 ~]# lsdef -i mac a05n13
Object name: a05n13
    mac=aa:bb:cc:dd:ee:aa
[root@mgmt1 ~]# nodeset a05n13 osimage=compute
a05n13: netboot rhels7.4-ppc64le-compute
[root@mgmt1 ~]# grep aa:bb:cc:dd:ee:aa /var/lib/dhcpd/dhcpd.leases
[root@mgmt1 ~]# 
```

**Comment by whowutwut** [comment]
@mattaezell For the 2nd comment , you have to run a `makedhcp a05n13` after setting the mac for it to get added into the lease file.   This happens automatically under the covers when we are doing discovery and fill in the mac address on a predefined node. 

```
chdef a05n13 mac=aa:bb:cc:dd:ee:aa
makedhcp a05n13
```

Then grep for it.

**Comment by mattaezell** [comment]
`nodeset` calls `makedhcp` also.  We've been running with `disjointdhcps=1` from back when we thought we were going to run DHCP on all the service nodes.  It seems like now that's preventing this from working.  It's sending the `makedhcp` commands to the service node, but they aren't doing anything or logging any errors.

**Comment by mattaezell** [comment]
I think things are working OK with `disjointdhcps=0`.  I can't explain why/how this was working previously.  Is `disjointdhcps=0` the recommendation on our system?

**Comment by whowutwut** [comment]
@mattaezell humm.. ok I had a suspicion that something with hierarchy and disjoint may be causing a problem, but wanted to talk to @robin2008 about it..   @robin2008 could you chime in? 

I think in the end, we do want to run with `disjointdhcps=1` , but need to fix whatever is going on here. 

>  disjointdhcps:  If set to '1', the .leases file on a service node only contains
                 the nodes it manages. And when 'sharedtftp' is disabled, nodeset handles
                 boot loader configuration on a service node only for the nodes it manages.
                 The default value is '0'. It means include all the nodes in the subnet.

The idea is that the service node pairs would be the only ones responding to the compute nodes they manage, instead of all service nodes able to respond to the DHCP broadcast

**Comment by mattaezell** [comment]
Right now we are only running dhcp on the master.  Since we are running in a flat network, does it make sense to have 17 DHCP servers? All 17 will see every request, so 16 of them will have to ignore requests that they don't own.  Does that really provide that much scalability?

**Comment by robin2008** [comment]
@mattaezell   
when `disjointdhcps=0` makedhcp -d will send the request to all SNs.
And `disjointdhcps=1` will only be handled on the dedicate service nodes of the CN,  and also be forwarded to `dhcpservers` defined in networks table. (Could you confirm that the mgmt1 is defined as dhcpserver in your networks table? )

If you want to switch to `disjointdhcps=1`,  we assume that you should clean up the lease information when `disjointdhcps=0` first (nodeset offline), or there would be some lease cannot be cleaned on some service nodes.

**Comment by robin2008** [comment]
And @mattaezell ,  
is it possible for your the set xcatdebugmode=2 in site table and run nodeset again?
More debug level logs in /var/log/xcat/cluster.log may help something.

**Comment by robin2008** [comment]
I try to modify `nodeset` to always handle the req on master, but still found issue.  Check the log
we can see that, the makedhcp request only be preprocessed,  but not calling process_request.

Check the code, and found that in dhcp.pm preprocess_request, 
if disjointdhcps=1 ($snonly = 1), sharedtftp=1, and invoked from `nodeset`, it will go into below if-clause ($localonly=1) .

From the codes, it will not return the requests back to xcat for MN.  (array `requests` is return to xcatd, and it contains the req need to be handled.)

```
    if (($snonly == 1) && (!$opt{n})) {

        # if a list of nodes are specified
        if (@nodes > 0) {

            # get the hash of service nodes
            my $sn_hash = xCAT::ServiceNodeUtils->getSNformattedhash(\@nodes, "xcat", "MN");

            # if processing only on the local host
====>       if ($localonly) {

                # compare the service node hash with the iphash - a match adds this service node
                foreach (keys %$sn_hash) {
                    if (exists($iphash{$_})) {
                        my $reqcopy = {%$req};
                        $reqcopy->{'node'}                 = $sn_hash->{$_};
                        $reqcopy->{'_xcatdest'}            = $_;
                        $reqcopy->{_xcatpreprocessed}->[0] = 1;
                        push @requests, $reqcopy;
                        last;
                    }
                }
}
```

**Comment by robin2008** [comment]
The issue is covered in PR #4440

**Comment by robin2008** [comment]
Verified with the below build: 
`Version 2.13.9 (git commit e7e6b60215ff075dd6bc33337ea85014cf525813, built Thu Dec  7 06:16:04 EST 2017)`

1, Not using `shared tftp` and set disjointdhcps=1
```
#lsdef -t site -i sharedtftp,disjointdhcps
Object name: clustersite
    disjointdhcps=1
    sharedtftp=0
```

2, all SNs not running dhcp
```
#lsdef c910f03c09k04 -i setupdhcp
Object name: c910f03c09k04
    setupdhcp=0
```
3, setup the node under this service node, and test `nodeset` and `makedhcp`
```
#chdef c910f03c09k05 servicenode=c910f03c09k04 tftpserver=c910f03c09k04 nfsserver=c910f03c09k04  xcatmaster=c910f03c09k04


# nodeset c910f03c09k05 osimage -V
c910f03c09k05: [c910f03c09k03]: install rhels7.4-alternate-ppc64le-compute
c910f03c09k05: [c910f03c09k04]: install rhels7.4-alternate-ppc64le-compute
# makedhcp -q c910f03c09k05 -V
[c910f03c09k03]: c910f03c09k05: ip-address = 10.3.9.5, hardware-address = 42:5c:0a:03:09:05

# nodeset c910f03c09k05 stat -V
c910f03c09k05: [c910f03c09k03]: install rhels7.4-alternate-ppc64le-compute
c910f03c09k05: [c910f03c09k04]: install rhels7.4-alternate-ppc64le-compute

# makedhcp -d c910f03c09k05
# echo $?
0
# makedhcp -q c910f03c09k05
# echo $?
0
```
4, using `petitboot` as netboot
```
chdef c910f03c09k05 netboot=petitboot

# nodeset c910f03c09k05 osimage -V
c910f03c09k05: [c910f03c09k03]: install rhels7.4-alternate-ppc64le-compute
c910f03c09k05: [c910f03c09k04]: install rhels7.4-alternate-ppc64le-compute

cat /tftpboot/petitboot/c910f03c09k05
#install rhels7.4-alternate-ppc64le-compute
default xCAT
label xCAT
	kernel http://c910f03c09k04:80/tftpboot/xcat/osimage/rhels7.4-alternate-ppc64le-install-compute/vmlinuz
	initrd http://c910f03c09k04:80/tftpboot/xcat/osimage/rhels7.4-alternate-ppc64le-install-compute/initrd.img
	append "quiet inst.repo=http://c910f03c09k04:80/install/rhels7.4-alternate/ppc64le inst.ks=http://c910f03c09k04:80/install/autoinst/c910f03c09k05 BOOTIF=42:5c:0a:03:09:05  ip=dhcp  inst.cmdline  console=tty0 console=hvc0,115200n8r"

# xdsh c910f03c09k04 "cat /tftpboot/petitboot/c910f03c09k05"
c910f03c09k04: #install rhels7.4-alternate-ppc64le-compute
c910f03c09k04: default xCAT
c910f03c09k04: label xCAT
c910f03c09k04: 	kernel http://c910f03c09k04:80/tftpboot/xcat/osimage/rhels7.4-alternate-ppc64le-install-compute/vmlinuz
c910f03c09k04: 	initrd http://c910f03c09k04:80/tftpboot/xcat/osimage/rhels7.4-alternate-ppc64le-install-compute/initrd.img
c910f03c09k04: 	append "quiet inst.repo=http://c910f03c09k04:80/install/rhels7.4-alternate/ppc64le inst.ks=http://c910f03c09k04:80/install/autoinst/c910f03c09k05 BOOTIF=42:5c:0a:03:09:05  ip=dhcp  inst.cmdline  console=tty0 console=hvc0,115200n8r"

# nodeset c910f03c09k05 offline -V
c910f03c09k05: [c910f03c09k03]: offline
c910f03c09k05: [c910f03c09k04]: offline

# makedhcp -q c910f03c09k05
# echo $?
0
``` 

We can see that when only MN run dhcp server,  the nodeset/makedhcp can work as expected behavior:
 - lease is generated on MN
 - petitboot file are generated on both MN and SN, in case CN could use SN for its installation.
 - when `offline`, the corresponding info could be cleaned up.

PASSed.
