### ISSUE TITLE
confignetwork does not support multiple bonds of different nic type

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4433]
Our login nodes have an Ethernet and Infiniband bond.

I'm getting the error:
```
login1: [E]:Error: [E]: different nic device types in ib0@ib1.
```

I think I see the problem, patch coming soon

**Comment by whowutwut** [comment]
@bybai can you follow this issue

**Comment by whowutwut** [comment]
Fixed with PR #4434

**Comment by whowutwut** [comment]
@bybai Please associate the milestone when we close the issue, so we have the correct tracking.

**Comment by bybai** [comment]
Hi @whowutwut , I added this into EPIC for network configuration in xcat 2.13.x
