### ISSUE TITLE
Timeout while executing "renergy noderange temperature|powerusage"

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#444]
OS: 
MN -- ppc64 le, RH7.1
CN -- x86

Description:
There is an timeout message while executing the "renergy noderange temperature|powerusage" commands. 
But it should not appear here.

[root@c910f03c05k07 ~]# renergy c910f04x36 powerusage
c910f04x36: Error: The option 'powerusage' is only supported for OpenPOWER servers
c910f04x36: Error: timeout
[root@c910f03c05k07 ~]# renergy c910f04x36 temperature
c910f04x36: Error: The option 'temperatue' is only supported for OpenPOWER servers
c910f04x36: Error: timeout
[root@c910f03c05k07 ~]# renergy c910f04x36 temperature=
c910f04x36: Error: The option 'temperatue' is only supported for OpenPOWER servers
c910f04x36: Error: timeout

**Comment by zet809** [comment]
Fixed in pull request 454.

**Comment by caomengmeng** [comment]
Verify Pass.
[root@c910f03c05k07 ~]# renergy c910f04x36 temperature
c910f04x36: Error: The option 'temperatue' is only supported for OpenPOWER servers
[root@c910f03c05k07 ~]# renergy c910f04x36 powerusage
c910f04x36: Error: The option 'powerusage' is only supported for OpenPOWER servers
[root@c910f03c05k07 ~]# renergy c910f04x36 temperature=
c910f04x36: Error: The option 'temperatue' is only supported for OpenPOWER servers
[root@c910f03c05k07 ~]# renergy c910f04x36 powerusage=
c910f04x36: Error: The option 'powerusage' is only supported for OpenPOWER servers
