### ISSUE TITLE
[FVT]2.12 deleteraid/configraid enhancement: return warning message when RAID Status is in Rebuilt other than hanging there

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#445]
This is an enhancement for deleteraid/configraid. 
In current code, when RAID status is in Rebuilt, if customer would like to delete it and create a new RAID,  it hangs for a very very long time.  Could we just return a warning message when the RAID is in Rebuilt status?  I think if the RAID is in Rebuilt status,  delete and config RAID operation should be prohibitted.

**Comment by bybai** [comment]
This will be fixed in 2.12.

**Comment by bybai** [comment]
while the RAID status is Rebuilding, configraid will not delete raid, it will wait until its status reach Optimized. The old timeout is 6 hours, it is too long; I will change the timeout to be 2 minutes. Outputs will be as following, code will be check in 2.12:
``` 
 ~]# xdsh p8euh 'configraid delete_raid="sda"'
p8euh: [I]: Renew available target arrays which will be deleting, "0 0:2:0:0"
p8euh: [I]: Round 1: Deletable array >>
p8euh: [I]: Round 1: ipr info before delete >> Name PCI/SCSI Location Description Status
p8euh: [I]: Round 1: ipr info before delete >> ------ ------------------------- ------------------------- -----------------
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: ipr info before delete >> sda 0001:08:00.0/0:2:0:0 RAID 10 Disk Array 61% Rebuilt
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:0:0 RAID 10 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> 0001:08:00.0/0:0:1:0 RAID 10 Array Member Active
p8euh: [I]: Round 1: ipr info before delete >> 0003:04:00.0/1: PCI-E SAS RAID Adapter Operational
p8euh: [I]: Round 1: delete_ipr_array, "0:2:0:0"
p8euh: [W]: Round 1: Array 0:2:0:0 is un-deletable at present.
p8euh: [I]: Round 1: All remaining target arrayes are un-deletable now.
p8euh: [I]: Round 1: Wait for these un-deletable arrayes deletable with tryCnt=2, tryInt=60.
p8euh: [S]: Wait for device status at time "2015-11-20 03:24:24": status[0:2:0:0]="Rebuilding, 61% Rebuilt", expect: "grep -sq -E 'Optimized'".
p8euh: [S]: Wait for device status at time "2015-11-20 03:25:24": status[0:2:0:0]="Rebuilding, 61% Rebuilt", expect: "grep -sq -E 'Optimized'".
p8euh: [W]: RAID device "0:2:0:0" status is not Optimized.
p8euh: [W]: Delete raid devices: "0:2:0:0" failed! (expected: "grep -sq -E 'Optimized'")
p8euh: [I]: Can not create RAID. There is no create_raid.
```

**Comment by tingtli** [comment]
@bybai  will you fix this in 2.12?

**Comment by tingtli** [comment]
This is fixed by https://github.com/xcat2/xcat-core/pull/891
But I don't have test environment now. Will let it in pending status and verify when I get the machine.

**Comment by tingtli** [comment]
I verify this defect and seems it still has some issue.
I will open it and put it in 2.12.1

**Comment by tingtli** [comment]
@bybai  Please take a look. Thanks!

**Comment by bybai** [comment]
hi @tingtli , I need the proper server with RAID, could you have one?

**Comment by bybai** [comment]
Hi @tingtli , if we do not have the proper system with RAID, I will move this issue to 2.13.4, thx.

**Comment by whowutwut** [comment]
@zet809  I removed this since the priority is set to low, probably won't get around to it.

**Comment by zet809** [comment]
So, let's close this issue.
