### ISSUE TITLE
updatenode -f loses directories when copying files to SN

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4456]
We sync deep directory trees using syncfiles.  `updatenode -f` seems to drop the last directory when the files make it to the service node
```
# lsdef -t osimage -i synclists compute
Object name: compute
    synclists=/install/custom/managed/master/synclists/synclist-compute
# grep ssh /install/custom/managed/master/synclists/synclist-compute
/install/custom/managed/master/syncfiles/ssh/common/ -> /
# ls /install/custom/managed/master/syncfiles/ssh/common/
etc
# updatenode a01n01 -f
File synchronization has completed for service nodes.
# ssh sn1 ls /var/xcat/syncfiles/install/custom/managed/master/syncfiles/ssh
etc
```
What happened to the *common* directory?

**Comment by mattaezell** [comment]
Alternatively, the service nodes could just use the files directly from /install without syncing anything.  /install is mounted from the management node.  We do have a single file that lives outside of /install, but we could live with a restriction that it's up to us to make sure all the relevant files are on each SN.

**Comment by whowutwut** [comment]
@robin2008  @zet809 Please see above...  

@mattaezell  When I talked to @zet809 I think the team will discuss and think about this problem some more.. maybe the fix is not too straightforward... 

Based on what is found.... could you potentially use this mounted `/install` as a work around to keep moving forward?

**Comment by mattaezell** [comment]
I'm happy to use `/install` (might actually be my preference) but I don't know how to tell xCAT to use that instead of `/var/xcat/syncfiles/install`.  Is that straightforward?

**Comment by immarvin** [comment]
the site.SNsyncfiledir is used to relocate the directory to place the synclist and file on SN:
```
 SNsyncfiledir:  The directory on the Service Node, where xdcp will rsync the files
                 from the MN that will eventually be rsync'd to the compute nodes.
```
but if it is specified to a shared directory, such as `/install`, `updatenode -f` might overwrite the files under the shared directory

but `updatenode -f`  is mandatory for syncing files in hierarchy cluster, since the synclist itself need to be synced to sn with  `updatenode -f`  first

**Comment by robin2008** [comment]
SN mount "/install" from MN is a default behavior of xCAT hierarchy, if possible we may need to consider to leverage it for `SNsyncfiledir` and ignore the sync between MN and SN to improve the performance.

**Comment by kcgthb** [comment]
You may want to consider the case where the MN already mounts `/install` (or even just portions of it) from someplace else, like an external NFS filer. In that case, re-exporting a NFS mounted `/install` from the MN to SNs is not an option, and synchronizing files to `SNsynfiledir` is the only way.

**Comment by robin2008** [comment]
Yes, local `SNsynfiledir` should be still required too. But better to support the option for a shared case. Whatever using same NFS or GPFS.

**Comment by immarvin** [comment]
hi @mattaezell , 

if you want to sync the directory itself "/install/custom/managed/master/syncfiles/ssh/common/" from MN to CN, the synclist entry in `/install/custom/managed/master/synclists/synclist-compute` should be 
```
/install/custom/managed/master/syncfiles/ssh/common -> /
```
There will be a directory "/common/" under "/" on the target CN after sync 

if you want to sync the stuff under directory "/install/custom/managed/master/syncfiles/ssh/common/" from MN to CN, the synclist entry in `/install/custom/managed/master/synclists/synclist-compute` should be 
```
/install/custom/managed/master/syncfiles/ssh/common/* -> /

```
All the stuff under `/install/custom/managed/master/syncfiles/ssh/common/` will be placed under `/` on the target CN after sync

you can workaround this issue first considering the 2 options above according to your need

The processing of sync list entry
````
/install/custom/managed/master/syncfiles/ssh/common/ -> /

````
is a bug for xCAT. 
```
[root@c910f03c05k04 ~]# cat /tmp/synclist
/install/custom/managed/master/syncfiles/ssh/common/ -> /
[root@c910f03c05k04 ~]# updatenode c910f03c17k20 -f
File synchronization has completed for service nodes.
[root@c910f03c05k04 ~]# updatenode c910f03c17k20 -F
c910f03c17k20: rsync: change_dir "/var/xcat/syncfiles/install/custom/managed/master/syncfiles/ssh/common" failed: No such file or directory (2)
c910f03c17k20: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
File synchronization has completed for nodes.
```
I am looking into the code to fix it and also the PR https://github.com/xcat2/xcat-core/pull/4445/files from @kcgthb

**Comment by immarvin** [comment]
the behavior of sync list entry 
```
/install/custom/managed/master/syncfiles/ssh/common/ -> /

```
is a little ambiguous , what do you expect its behavior should be?
consider the 2 behaviors in the option 1) or option 2) described in my comments above, which one do you prefer? @mattaezell @kcgthb @whowutwut

**Comment by kcgthb** [comment]
@immarvin I think that the synclist behavior should follow `rsync`'s, ie. that when both the source and destination paths end with a trailing `/`, the _contents_ of each directory should be copied.

That is, if your have the following hierarchy on the MN:
```
/install/custom/managed/master/syncfiles/ssh/common/ 
├── file1
└── dir1
    ├── d1f1
    └── d1f2
```
then, with the following `synclist`:
```
/install/custom/managed/master/syncfiles/ssh/common/ -> /
```
you should end up with this on the destination node:
```
/
├── file1
└── dir1
    ├── d1f1
    └── d1f2
```
Which is what you decribed in option 2.

**Comment by kcgthb** [comment]
@immarvin  No, I don't think the issues are related.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4494
