### ISSUE TITLE
Mount consoles from management node

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4457]
We are running with stateless service nodes.  `/var/log/consoles` is in the ramdisk and gets lost every time we reboot the service nodes.  We either need to setup the local disks to mount under /var or we should NFS mount the `/var/log/consoles` directory from the management node, similar to the way `installdir` and `tftpdir` are handled.  The latter is preferred, so we can look at all consoles on the management node.  Does it make sense to handle this in `setup_CONS`?

**Comment by chenglch** [comment]
I think so. We can do it like `setup_TFTP` does.

**Comment by immarvin** [comment]
is `/var` mounted from local disk?

**Comment by mattaezell** [comment]
@immarvin on the MN it's currently mounted from a RAID-1 local mirror.  Soon, it will be moved to a Fibre-Channel attached RAID device.  The SNs currently just mount var from the ramdisk.

**Comment by robin2008** [comment]
@mattaezell 
In my opinion, for `/tftpboot` and `/install`, they are all related for xCAT functions, but `/var/log/consoles` are not, it only for logs.

- If you would like to store it in an shared directory, you can just create an postscript for SN to create an symbol link for `/var/log/consoles` there.

- Another considerations is we allow you define the log directory to another directory which it is shared.

**Comment by immarvin** [comment]
hi @mattaezell , what do you think on @robin2008 's comment?

**Comment by mattaezell** [comment]
@immarvin We have created postscripts that manually mount the consoles directory from the management node.  Our preference would still be to have xCAT handle this internally, but the solution we have now is acceptable.  In the future if we move to `goconserver` we have some more options to use tcp output and avoid local writes.
