### ISSUE TITLE
Boot hanging at updateflag

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4458]
We've seen several nodes fail to boot, with the last thing in the console being:
```
[Thu Dec  7 02:38:37 2017][   11.959905] mlx5_core 0033:01:00.0: Port module event: module 0, Cable plugged
[Thu Dec  7 02:38:37 2017][   12.045816] mlx5_core 0033:01:00.1: Using 64-bit DMA iommu bypass
[Thu Dec  7 02:38:38 2017][   12.090191] mlx5_core 0033:01:00.1: capi_init:1736:(pid 1165): capi is NOT supported
[Thu Dec  7 02:38:38 2017][   12.090348] mlx5_core 0033:01:00.1: firmware version: 16.21.116
[Thu Dec  7 02:38:40 2017][   14.769632] mlx5_core 0033:01:00.1: Port module event: module 1, Cable plugged
[Thu Dec  7 02:38:40 2017][   14.819195] mlx5_ib: Mellanox Connect-IB Infiniband driver v4.1-4.1.5 (01 Nov 2017)
[Thu Dec  7 02:40:44 2017][  138.390561] dracut-initqueue[1550]: awk: /tmp/updateflag:19: fatal: can't redirect to `/var/log/xcat/xcat.log' (No such file or directory)
```
If you attach with `rcons`, the terminal is unresponsive

**Comment by whowutwut** [comment]
@immarvin A similar issue to #4411 but not exactly the same...

**Comment by immarvin** [comment]
hi @mattaezell , is this a normal reboot  or the 1st boot after provision?
what is the status of the failing node?

**Comment by mattaezell** [comment]
This is a normal reboot, it has been rebooted post-discovery multiple times.  The status of the failing node is that it appears hung at the console

**Comment by immarvin** [comment]
what is the `lsdef <failed node> -i status ` on mn?

**Comment by mattaezell** [comment]
```
[root@sn2 ~]# tail -1 /var/log/consoles/a32n07
[Thu Dec  7 03:23:35 2017][  153.750580] dracut-initqueue[1555]: awk: /tmp/updateflag:19: fatal: can't redirect to `/var/log/xcat/xcat.log' (No such file or directory)
[root@sn2 ~]# lsdef a32n07 -i status
Object name: a32n07
    status=powering-off
[root@sn2 ~]# ping -c1 a32n07
PING a32n07.myfqdn (10.10.2.159) 56(84) bytes of data.

--- a32n07.myfqdn ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by immarvin** [comment]
hi @mattaezell , is a32n07 totally unreachable from mn? try `ping a32n07`

please provide `cat /tftpboot/petitboot/a32n07 ` if convenient

**Comment by mattaezell** [comment]
I provided ping from the SN, same scenario from the MN.
```
# cat /tftpboot/petitboot/a32n07
#netboot rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.10.0.12:80/tftpboot/xcat/osimage/compute/kernel
        initrd http://10.10.0.12:80/tftpboot/xcat/osimage/compute/initrd-stateless.gz
        append "imgurl=http://10.10.0.12:80//install/netboot/compute/20171206/rootimg.cpio.gz XCAT=10.10.0.12:3001 NODE=a32n07 FC=0 BOOTIF=70:e2:84:14:49:21  selinux=0  powersave=off"
```

**Comment by immarvin** [comment]
hi @mattaezell , `ping -c1` can not prove a32n07 is unreachable, need more time/retry...

**Comment by immarvin** [comment]
hi @mattaezell . please check the xcatd status on mn, with `service xcatd status` and
````
ps aux --forest|grep xcat
````

**Comment by robin2008** [comment]
@mattaezell  

Not sure if there are any relationship with the issue which Glen reported (rpower hit an issue when change the node status. )
```
Error: openbmc plugin bug, pid 36350, process description: 'xcatd SSL: rpower for mgmt1.summit.olcf.ornl.gov@mgmt1: openbmc instance' with error 'no connection to syslog available
        - unix dgram connect: Connection refused
        - stream can't open /dev/log: No such device or address at /opt/xcat/lib/perl/xCAT_monitoring/monitorctrl.pm line 707.
' while trying to fulfill request for the following nodes:
```

As `/tmp/updateflag` will report the status to `install monitor` process, if it hit the same issue, we need to check the process status of `xcatd: install monitor` on all SN and MN. And also /var/log/xcat/cluster.log

**Comment by mattaezell** [comment]
@immarvin @robin2008 When rebooting a rackof 18 nodes, between 0 and 3 will generally get in this state.  I think the MN is ok, since 15-18 nodes boot just fine.  The install monitor is present.

**Comment by immarvin** [comment]
hi @mattaezell , 
1. we want to make sure whether the failed nodes are not reachable from its relevant SN or MN, you pasted the `ping -c1` result, would you please help to make sure whether it is totally unpingable without `-c1`?

2. And also, in the initrd on CN, the initrd will finally drop in emergency shell after long enough timeout, you can run commands inside initrd shell via `rcons`, would you please make sure that you can enter the initrd shell?

3. please provide the dhcp lease time with `lsdef -t site -o clustersite -i dhcplease`,  you can provide the `cat /etc/dhcp/dhcpd.conf` if convenient

**Comment by mattaezell** [comment]
@immarvin I think we are treating this as a hardware/firmware issue for now

**Comment by immarvin** [comment]
the following up issue is https://github.com/xcat2/xcat-core/issues/4489
