### ISSUE TITLE
Documentation for setupntp is incorrect

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#4469]
Was following instruction for setting up NTP servers on our cluster from here 
https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/references/man1/makentp.1.html
and here 
https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/references/man5/servicenode.5.html?highlight=ntpserver%20

This statement is incorrect

ntpserver

Not used. Use setupntp postscript to setup a ntp server on this service node? Valid values:yes or 1, no or 0. If no or 0, it does not change the current state of the service.

The value has to be 1, or 0.  Using Yes or No will not be interpreted.

**Comment by whowutwut** [comment]
Closing out this task as we prepare for the next release.  Documentation has been updated in the latest devel build and on RTD (latest) version. Please re-open if additional comments or open a new issue.
