### ISSUE TITLE
[OpenBMC] RestAPI functions in OpenBMC need to be exposed to help Admin managed the servers

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4471]
Creating an Epic to hold a bunch of functions that seems to be needed in OpenBMC support

**Comment by whowutwut** [comment]
@gurevichmark FYI, rolling some of the issues into this higher epic so we can see them together.

**Comment by zet809** [comment]
Hi, @whowutwut , all the sub tasks are done, shall we close this EPIC?

**Comment by whowutwut** [comment]
Yes close it.
