### ISSUE TITLE
[OpenBMC] Allow the ability to clear GARD via REST on the BMCs

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4474]
This is maybe more for development ...  when we hit a GARD stop, it is nice to be able to clear the GARD file and reboot the node...  

The file to clear is: 
`/var/lib/phosphor-software-manager/pnor/prsv/GUARD` 

There's a REST interface, but OpenBMC team will change the team will change the path to xyz, so until that happens trying to track down the org/openbmc interface if we want to support this quicker... 

## Proposed External: 
```
rspconfig <noderange> reset_gard
```

What I don't understand is the file is spelled `GUARD` but the REST API endpoing is `gard`... oh well.

**Comment by whowutwut** [comment]
I don't think this is ready yet to use yet... , they have a typo in the org/openpower endpoint that needs to be resolved..    If we get a clear endpoint defined, we could do the development and just error on endpoint incorrect...  will track this and update if I find out more info.

**Comment by whowutwut** [comment]
This function is in the `r21` build of OP910 driver, https://w3.austin.ibm.com/afs/austin/projects/gfw/images/openpower9/910.1746.20171215a/ship/ so this work can begin...

**Comment by whowutwut** [comment]
I verified on the r21 build today that it works... 

The following script just does a `ls -ltr` on  `/var/lib/phosphor-software-manager/pnor/prsv/GUARD` on the BMC.... 

```
root@briggs01 Control]# ./list_gard.sh
==> BMCIP=172.11.139.18
-rw-rw-r--    1 root     root         20480 Dec 13 07:46 /var/lib/phosphor-software-manager/pnor/prsv/GUARD

Then using the UT scripts: 

```
[root@briggs01 Control]# ./login.sh
==> BMCIP=172.11.139.18
+ date
Mon Dec 18 21:43:14 EST 2017
+ curl -c cjar -k -X POST -H 'Content-Type: application/json' -d '{"data": [ "root", "0penBmc" ] }' https://172.11.139.18/login
{
  "data": "User 'root' logged in",
  "message": "200 OK",
  "status": "ok"
}
[root@briggs01 Control]# ./clear_gard.sh
+ date
Mon Dec 18 21:43:33 EST 2017
+ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X POST -d '{"data":[]}' https://172.11.139.18/org/open_power/control/gard/action/Reset
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```

Then checking the file again afterwards:

```
[root@briggs01 Control]# ./list_gard.sh
==> BMCIP=172.11.139.18
ls: /var/lib/phosphor-software-manager/pnor/prsv/GUARD: No such file or directory
```

**Comment by whowutwut** [comment]
@xuweibj if you have some time to implement this, could you self assign this issue?

**Comment by xuweibj** [comment]
Hi @whowutwut , do we just need the command to reset gard?  Do we need to list it?

**Comment by whowutwut** [comment]
@xuweibj Checking if there's a REST endpoint that would show us this.  I don't want to interact with ssh commands to the BMC.  

Talking to FW team, they found this in the code: 
https://github.com/openbmc/openpower-pnor-code-mgmt/blob/7f80e0b534b91b3a868f33934d92024427235e89/item_updater.cpp#L635

```
    // The GARD partition is currently misspelled "GUARD." This file path will
    // need to be updated in the future.
```

**Comment by xuweibj** [comment]
The task was finished in pull request #4573 .
