### ISSUE TITLE
[OpenBMC] bmcdiscover should only create temporary node definitions using node-<mac> format. 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4477]
As we start monitoring some of the bring up going on with the OpenPower servers running OpenBMC. I think we should NOT support creating temporary node definitions for OpenBMC servers in the format of `node-<mode>-<sn>`.  

Before the host is booted for the very first time, the boxelder board doesn't have any information about the VPD model/serial... and so the only way we could detect a unique node is creating the temporary node based on the MAC address.  

This all works fine, but if the user runs `bmcdiscover` on a node range where the host has been booted, then writing those to the xCAT database would result in a definition called `node-<model>-<serial>` and now this is confusing.  There's 2 node definitions pointing to the same machine. 

To prevent this, we should be consistent and only support 1 format.  
@zet809 Also would affect clean up of the temporary node definition when discovery is made.

**Comment by zet809** [comment]
hi, @xuweibj , will you pls help to take a look at this issue?
 [ ] check whether both node-$mac and node-$mtm-$sn can be removed during the hardware discovery process
 [ ] update or create node-$mac only for OpenBMC node. If no $mac found (such as remote OpenBMC), if $mtm and $sn found, create node-$mtm-$sn. Otherwise, report error that no MAC or $mtms found for the IP(Such as a remote OpenBMC haven't been booted yet).

**Comment by whowutwut** [comment]
I'm not sure how to validate this because our nodes are powered on and the BMCs see this information already there, need to think about this... . 

Just updated to todays build: 
```
Version 2.13.10 (git commit 730d4550413c8851dfb7d8681c26872cf3ad4917, built Wed Dec 20 06:16:03 EST 2017)
```

and seems to still work:

```
[root@briggs01 yum.repos.d]# bmcdiscover --range 172.12.253.100
172.12.253.100,8335-GTC,1318C4A,,,mp,bmc,,
[root@briggs01 yum.repos.d]# bmcdiscover --range 172.12.253.100 -w
Writing node-8335-gtc-1318c4a (172.12.253.100,8335-GTC,1318C4A,,,mp,bmc,,) to database...
[root@briggs01 yum.repos.d]# rsetboot node-8335-gtc-1318c4a net
node-8335-gtc-1318c4a: Network
[root@briggs01 yum.repos.d]# rpower node-8335-gtc-1318c4a reset
```

**Comment by whowutwut** [comment]
It's difficult to clear out the BMC information once the machine IPLed, so i will close this .  The fix here is to detect if there is already a temporary definition for the node and update that instead of creating a new one.
