### ISSUE TITLE
[DEV]xcat code logic only can transfer 'INT' and 'TERM' to plugin, cannot transfer to the script triggered by plugin

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#448]
If user hit "ctrl+c" in client side during running one command, xcatd will receive this signal and kill the specific process (i.e. plugin) which was forked by xcatd and take responsible to handle this command. sometime, xcat plugin will trigger other scripts, when this plugin terminate, these scripts won't be handled. so even these scripts have signal handle function, but due to they can't receive signal, so some unpredictable things will happen.

**Comment by neo954** [comment]
I am going to look into this one.

**Comment by neo954** [comment]
Yeah, a new patch against this issue is available.

**Comment by neo954** [comment]
@hu-weihua, the patch has been merged days ago. Please verify if this issue is fixed.

**Comment by hu-weihua** [comment]
I have verified this issue, the fix works. thanks @neo954 ! :+1:

**Comment by neo954** [comment]
@hu-weihua, Cool.
