### ISSUE TITLE
xcat 2.13.8 on CentOS 7.3

### ISSUE THREAD

**Issue by hargoth** [xcat2/xcat-core#4483]
Fresh install on clean system, from yum repository.
```
# . /etc/profile.d/xcat.sh
# xcatd
IPv6 support re-enabled in __PACKAGE__, got disabled in file /opt/xcat/lib/perl/xCAT/Client.pm line 45 at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 220.
Can't call method "prepare" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 998.
```

**Comment by immarvin** [comment]
hi @hargoth , please provide the xcat version with `lsxcatd -v` and perl-IO-Socket-SSL version with `rpm -qa|grep -i perl-io-socket`

**Comment by hargoth** [comment]
lsxcatd -v does not run because the xcatd never starts

$ rpm -qa|grep -i perl-io-socket
perl-IO-Socket-INET6-2.69-5.el7.noarch
perl-IO-Socket-IP-0.21-4.el7.noarch
perl-IO-Socket-SSL-1.94-6.el7.noarch

**Comment by whowutwut** [comment]
@hargoth  Can you try to run bypassing xcatd.. 
```
XCATBYPASS=1 lsxcatd -v
```

@immarvin  my guess is that it should be the GA version of 2.13.8....

**Comment by hargoth** [comment]
# XCATBYPASS=1 lsxcatd -v
Error loading module /opt/xcat/lib/perl/xCAT_plugin/AAsn.pm  ...skipping
Can't call method "prepare" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 998.

**Comment by hargoth** [comment]
# ls -l /opt/xcat/lib/perl/xCAT_plugin/AAsn.pm
-rw-r--r-- 1 root root 43620 Nov  2 06:16 /opt/xcat/lib/perl/xCAT_plugin/AAsn.pm


It is there ...

**Comment by immarvin** [comment]
hi @hargoth , I think  the 2 messages are irrelevant, `IPv6 support re-enabled in __PACKAGE__, got disabled in file /opt/xcat/lib/perl/xCAT/Client.pm line 45 at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 220` is just a warning message on the IPV6 support, lets' ignore it.

`Can't call method "prepare" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 998.` is a critical error which prevent xcatd from starting,  it shows that the db access is failed. would you please provide the output of `XCATBYPASS=1 lsxcatd -d` and `ls /etc/xcat`? thanks

**Comment by immarvin** [comment]
close this ticket due to no update, please reopen it if any update

**Comment by dajiji** [comment]
Suggest to
yum install perl-DBD-SQLite
