### ISSUE TITLE
rmdef cannot handle certain strings that are allowed from mkdef

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4487]
Here's a situation where if we can block the creation of the object, we can avoid this situation... 
Or fix it so that we can remove it....

```
[root@briggs01 ~]# mkdef -t group -o service[1-5]
Warning: Cannot determine a member list for group 'service[1-5]'.
1 object definitions have been created or modified.
```

But now I can't remove this one... 
```
[root@briggs01 ~]# rmdef -t group -o service[1-5]
Error: Could not find an object named 'service[1-5]' of type 'group'.
No objects have been removed from the xCAT database.
[root@briggs01 ~]# rmdef -t group -o "service[1-5]"
Error: Could not find an object named 'service[1-5]' of type 'group'.
No objects have been removed from the xCAT database.
[root@briggs01 ~]# rmdef -t group 'service[1-5]'
Error: Could not find an object named 'service[1-5]' of type 'group'.
No objects have been removed from the xCAT database.
```

Forced to use `tabedit nodegroup`.  Or we should....  print something like: 

`Error: Could not find an object named 'service[1-5]' of type 'group'.  If this is correct, use "tabedit nodegroup" to remove.` 

Something to help the admin out....

**Comment by robin2008** [comment]
it could be still removed by `chtab`,  for example, `chtab -d groupname="service[1-5]" nodegroup`
But if you have more attributes set for this group, and they are in different table and key column is different, you have to run below commands for each table.
```
chtab -d|--delete keycolname=keyvalue[,keycolname=keyvalue...] tablename [tablename]...
```

**Comment by zet809** [comment]
It seems we failed to resolve `service[1-5]` to `service1, service2,service3,service4,service5`.
```
root@c910f03c05k10:~# mkdef -t group -o service[1-5]
Warning: Cannot determine a member list for group 'service[1-5]'.
1 object definitions have been created or modified.
root@c910f03c05k10:~# lsdef -t group | grep service
service  (group)
service[1-5]  (group)
root@c910f03c05k10:~# lsdef -t group "service\[1-5\]"
Object name: service\[1-5\]
    members=
```

**Comment by robin2008** [comment]
We have a discussion and plan to disable the range feature for non-node objects. If the name contains illegal char, then we will stop with error.

**Comment by whowutwut** [comment]
@robin2008 Thanks, If i understand that comment, we are going to stop allowing the creation of the object with the bad name to avoid the problems when we try to remove?
