### ISSUE TITLE
Need a way to set ethtool parameters early in boot

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4489]
Due to #4458 we have a need to set some `ethtool` parameters on our boot nic.  We've seen it fail before we've even downloaded the image, so these settings need to happen in the initrd.  Unfortunately, the `tg3` module doesn't take any relevant parameters, so it looks like something will need to call `ethtool` very soon after the device is discovered.

Idea 1: Create udev rules so that when any device using the `tg3` driver comes online it runs `ethtool`.  Problem: you can't set `rx-jumbo` if the interface MTU is 1500.  Workaround: set the MTU to 9000, run `ethtool`, set the MTU back to 1500.

Idea 2: Use `dhclient`'s hook infrastructure to run scripts whenever an interface is configured.  Problem: dracut's version of `dhclient-script` doesn't call any hooks.  Workaround: patch `dhclient-script.sh` inside dracut.

Idea 3: Put something in the xcat dracut module.  Downside: there's a non-zero time between when the interface comes up and when the xcat module runs.  Might be trivial, but the interface *could* fail in that window.

Thoughts?

**Comment by robin2008** [comment]
For idea 3,  if the interface failed in the window, is it possible to recover it ? for example, down and up the interface.

**Comment by immarvin** [comment]
hi @mattaezell , idea 2 is equivalent with idea 3.  the script "xcatroot" shipped in `xcat` dracut module is invoked in `dhclient-script`, all the steps to provision the diskless node are included in `xcatroot` , so I think it's ok to add the `ethtool` stuff at the beginning of the `xcatroot`

idea 1 can be an option too, we can create or insert the customized udev rule invoking `ethtool` in a script in `Hook: cmdline` of dracut. See https://www.kernel.org/pub/linux/utils/boot/dracut/dracut.html#_hook_cmdline for details

**Comment by immarvin** [comment]
hi @mattaezell , if you want to debug or look into the device status inside initrd, you can set dracut break points for the dracut , then the diskless boot will drop into dracut shell inside initrd at the point you specified.

the doc on dracut is https://www.kernel.org/pub/linux/utils/boot/dracut/dracut.html, 
the kernel options for available dracut break points are:
````
rd.break={cmdline|pre-udev|pre-trigger|initqueue|pre-mount|mount|pre-pivot|cleanup}
drop to a shell on defined breakpoint
````
the descriptions of these break points can be found in https://www.kernel.org/pub/linux/utils/boot/dracut/dracut.html,

the steps to set the break points are:

 ````
[root@briggs01 ~]# chdef mid05tor12cn05 addkcmdline='rd.break=initqueue'
[root@briggs01 ~]# nodeset mid05tor12cn05 osimage
[root@briggs01 ~]# rpower mid05tor12cn05 boot
[root@briggs01 ~]# rcons mid05tor12cn05



[Enter `^Ec?' for help]
initqueue:/#
initqueue:/#

````

**Comment by mattaezell** [comment]
@robin2008 Usually. I've also seen the ethtool settings "fix" it live, so maybe not much of a concern

@immarvin I already implemented Idea 1 and Idea 2 on our cluster, I'm just trying to figure out the best way to upstream it.  It sounds like `xcatroot` is the best place?

**Comment by immarvin** [comment]
@mattaezell , either idea 1 and idea 3 is ok.  The customization should better be done with the script specified in attribute `postinstall` of osimage, so that xCAT upgrading won't affect it in most cases
```

postinstall:	Supported in diskless image only. The fully qualified name of the scripts running in non-chroot mode after the package installation but before initrd generation during genimage. If multiple scripts are specified, they should be seperated with comma ",". A set of osimage attributes are exported as the environment variables to be used in the postinstall scripts:

      IMG_ARCH(The architecture of the osimage, such as "ppc64le","x86_64"),
      IMG_NAME(The name of the osimage, such as "rhels7.3-ppc64le-netboot-compute"),
      IMG_OSVER(The os release of the osimage, such as "rhels7.3","sles11.4"),
      IMG_KERNELVERSION(the "kernelver" attribute of the osimage),
      IMG_PROFILE(the profile of the osimage, such as "service","compute"),
      IMG_PKGLIST(the "pkglist" attribute of the osimage),
      IMG_PKGDIR(the "pkgdir" attribute of the osimage),
      IMG_OTHERPKGLIST(the "otherpkglist" attribute of the osimage),
      IMG_OTHERPKGDIR(the "otherpkgdir" attribute of the osimage),
      IMG_ROOTIMGDIR(the "rootimgdir" attribute of the osimage)

```
