### ISSUE TITLE
[openbmc] the output of rflash summary function is not correct

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4490]
xCAT version:
 Version 2.13.9 (git commit 6a292c803930eb9f3d1c4aad578bdd20cc9bf7b7, built Sat Dec  9 06:16:01 EST 2017)

The output of rflash summary function is not correct.

```
------START::rflash_option_a_with_non_existent_id::Time:Fri Dec  8 02:44:52 2017------

RUN:rflash f6u17 -a 1234567 [Fri Dec  8 02:44:52 2017]
ElapsedTime:1 sec
RETURN rc = 1
OUTPUT:
f6u17: Error: Invalid ID provided to activate. Use the -l option to view valid firmware IDs.
Attempting to activate ID=1234567, please wait...
-------------------------------------------------------
Firmware update complete: Total=1 Success=0 Failed=1
f6u17: BMC is not ready
-------------------------------------------------------
CHECK:output =~ Error: Invalid ID provided to activate	[Pass]
CHECK:output !~ Attempting to activate	[Failed]

RUN:rflash f6u17 -a 123abcm [Fri Dec  8 02:44:53 2017]
ElapsedTime:0 sec
RETURN rc = 1
OUTPUT:
f6u17: Error: Invalid option specified with -a: 123abcm

------END::rflash_option_a_with_non_existent_id::Failed::Time:Fri Dec  8 02:44:53 2017 ::Duration::1 sec------
```

The reason ``f6u17: Error: Invalid ID provided to activate. Use the -l option to view valid firmware IDs.`` and ``f6u17: BMC is not ready`` are different.

**Comment by whowutwut** [comment]
@hu-weihua  I think this is caused because the output is different for the following scenarios:
1. `-a` option used when providing a .tar file 
2. `-a` option use when specifying a ID

@gurevichmark Can you confirm this? 

`CHECK:output !~ Attempting to activate` <=== I don't think we would see this message when we provide an invalid ID.

**Comment by whowutwut** [comment]
oh, nevermind, I see the problem.... It should not go to "Attempting to activate..." !!!

👍

**Comment by whowutwut** [comment]
Disregard me message, I think the output of the FVT test put the "Attempting to activate" message after the error but when running it, the Attempting to activate is a generic message that comes out.  The Pull request that was created looks to address the issue and the Error Message reflects what is really happening.

**Comment by hu-weihua** [comment]
@whowutwut I though @xuweibj has fixed the first issue. 
For the issue entering into ``Attempting to activate`` will be traced by #4465. 
I will close this one and reopened #4465. thanks

**Comment by hu-weihua** [comment]
The output of latest code (2.13.9 (git commit af7bfe8489888dae3ef285233d1edc468750b051, built Wed Dec 13 06:16:04 EST 2017)): 
```
RUN:rflash f6u17 -a 1234567 [Thu Dec 14 01:58:08 2017]
ElapsedTime:1 sec
RETURN rc = 1
OUTPUT:
f6u17: Error: Invalid ID provided to activate. Use the -l option to view valid firmware IDs.
Thu Dec 14 01:58:08 2017 OpenBMC: [openbmc_debug]
Attempting to activate ID=1234567, please wait...
Thu Dec 14 01:58:09 2017 f6u17: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://10.6.17.100/login
Thu Dec 14 01:58:09 2017 f6u17: [openbmc_debug] login_response 200 OK
Thu Dec 14 01:58:09 2017 f6u17: [openbmc_debug] curl -k -b cjar -X PUT -H "Content-Type: application/json" -d '{"data":"xyz.openbmc_project.Software.Activation.RequestedActivations.Active"}' https://10.6.17.100/xyz/openbmc_project/software/1234567/attr/RequestedActivation
Thu Dec 14 01:58:09 2017 f6u17: [openbmc_debug] rflash_update_activate_response 403 Forbidden
-------------------------------------------------------
Firmware update complete: Total=1 Success=0 Failed=1
f6u17: Invalid ID provided to activate. Use the -l option to view valid firmware IDs.
-------------------------------------------------------
CHECK:output =~ Error: Invalid ID provided to activate	[Pass]
CHECK:output !~ Attempting to activate	[Failed]
```
