### ISSUE TITLE
[Customer］xCAT 2.11: failed to nodeset <node> offline (back to default/discovery boot config)

### ISSUE THREAD

**Issue by mfoliveira** [xcat2/xcat-core#450]
xCAT: xCAT-2.11-snap201511121931.ppc64le
OS: RHEL 7.2 on S822LC

Node is discovered, and defined in dhcpd.leases.
And the boot config file exists.

	# sed '/p8r1n2/,/}/p' -n /var/lib/dhcpd/dhcpd.leases
	host p8r1n2 {
	  dynamic;
	  hardware ethernet 98:be:94:59:f0:f2;
	  fixed-address 10.1.1.2;
		supersede server.ddns-hostname = "p8r1n2";
		supersede host-name = "p8r1n2";
		supersede conf-file = "http://10.1.0.1/tftpboot/petitboot/p8r1n2";
	}

	# cat /tftpboot/petitboot/p8r1n2 
	#offline
	default xCAT
	label xCAT
		kernel http://10.1.0.1:80/tftpboot/
		initrd http://10.1.0.1:80/tftpboot/

Now try to cleanup it's boot config back to none/default/discovery:

	# nodeset p8r1n2 offline
	p8r1n2: offline

	# nodeset p8r1n2 stat
	p8r1n2: offline

It didn't work.
The configuration didn't change in dhcpd.leases / boot config file.

	# sed '/p8r1n2/,/}/p' -n /var/lib/dhcpd/dhcpd.leases
	host p8r1n2 {
	  dynamic;
	  hardware ethernet 98:be:94:59:f0:f2;
	  fixed-address 10.1.1.2;
		supersede server.ddns-hostname = "p8r1n2";
		supersede host-name = "p8r1n2";
		supersede conf-file = "http://10.1.0.1/tftpboot/petitboot/p8r1n2";
	}

	# cat /tftpboot/petitboot/p8r1n2 
	#offline
	default xCAT
	label xCAT
		kernel http://10.1.0.1:80/tftpboot/
		initrd http://10.1.0.1:80/tftpboot/

It works correctly if you remove that section from dhcpd.leases, and restart the dhcp daemon.

	# sed '/p8r1n2/,/}/d' -i /var/lib/dhcpd/dhcpd.leases

	# sed '/p8r1n2/,/}/p' -n /var/lib/dhcpd/dhcpd.leases
	# 

	# systemctl restart dhcpd

**Comment by daniceexi** [comment]
@gurevichmark I think the petitboot.pm missed the code path to remove the configuration file.  I saw the code in xnba.pm. I think we can refer to the code in xnba.pm to handle the ``offline`` in petitboot.pm.

~~~~
      if($args[0] eq 'offline') {
        unlink($tftpdir."/xcat/xnba/nodes/".$_);
        unlink($tftpdir."/xcat/xnba/nodes/".$_.".pxelinux");
        unlink($tftpdir."/xcat/xnba/nodes/".$_.".uefi");
        unlink($tftpdir."/xcat/xnba/nodes/".$_.".elilo");
      }
~~~~

**Comment by daniceexi** [comment]
@gurevichmark Could we fix this issue in 2.12 sprint 2?

**Comment by gurevichmark** [comment]
Will attempt to fix for Sprint 2.

**Comment by gurevichmark** [comment]
Completed work with pull request #1394:
1. Man pages and usage modified for `nodeset` command
2. `nodeset stat` fixed to return `offline` if `nodeset offline` was issued previously.
3. `grub2.pm`, `xnba.pm` and `petitboot.pm` were modified to remove the boot configuration files and delete node entries from `dhcpd.lease` file.

**Comment by whowutwut** [comment]
Closing this issue, please open a new issue if the problem persists
