### ISSUE TITLE
xCAT 2.11 / S822LC: Node Discovery failed due to MTM with spaces

### ISSUE THREAD

**Issue by mfoliveira** [xcat2/xcat-core#457]
Hi,

There's a mismatch when there are trailing spaces in the MTM (maybe in SN too)
between findme() and populate_vpd_hash() with regards to XCATVPDHASH.

This causes node discovery to fail with node not found, because the node's MTM has no trailing spaces in the stanza generated by bmcdiscover, but does have spaces in the stanza generated by dodiscovery and parsed by PPC.pm.

As a work-around, I had to manually add a trailing space to the mtm field. (i.e., mtm="8335-GTA ")

Debugging:
--------------

Notice the inconsistency in the $mtms value between these 2 functions:

populate_vpd_hash() @ sbin/xcatd

        xCAT::MsgUtils->message("S", "Populate VPD Hash Debug: MTMS-".$mtms);
        push @{$::XCATVPDHASH{$mtms}}, $_->{node};

	<...> xcat[141847]: Populate VPD Hash Debug: MTMS-8335-GTA*0000000000000000

findme() @ lib/perl/xCAT/PPC.pm

    xCAT::MsgUtils->message("S", "Discovery Debug: MTMS-".$mtms);
    my $tmp_nodes = $::XCATVPDHASH{$mtms};

	<...> xcat[141847]: Discovery Debug: MTMS-8335-GTA *0000000000000000

**PROBLEM**: Notice the SPACE before the asterisk :) (ie, trailing space at MTM, before Serial Number)

With a modified genesis's /bin/dodiscovery to print the MTM and SERIAL lines of discopacket:

        MTM LINE IN DISCOPACKET
        <mtm>8335-GTA        </mtm>

        SERIAL LINE IN DISCOPACKET
        <serial>0000000000000000</serial>

So, it's caused because bmcdiscover takes care of removing trailing spaces with this regex:

                # For firestone and habanero, the fru 3 will contain the MTMS
		<...>
                if (($fru3_output =~ /Chassis Part Number\s*:\s*(\S*).*Chassis Serial\s*:\s*(\S*)/)) {
                    $mtm = $1;
                    $serial = $2;
                }

But it's not done when PPC.pm processes the discovery packets/requests.

Work-around:
------------------

Manually add a trailing space to the MTM field of the BMC node and Host node, so they match.

	# chdef node-8335-gta-0000000000000000 mtm='8335-GTA '
	
	# lsdef node-8335-gta-0000000000000000 | grep mtm | sed 's,$,<END>,'
	    mtm=8335-GTA <END>

	# chdef p8r4n2 mtm='8335-GTA '
	
	# lsdef p8r4n2 | grep mtm | sed 's,$,<END>,'
	    mtm=8335-GTA <END>

Environment: 
-----------------
- xCAT-2.11-snap201511121931.ppc64le
- RHEL 7.2
- S822LC

**Comment by mfoliveira** [comment]
Hi @whowutwut 

FYI. I think this is an important defect for 2.11. Thanks!

**Comment by whowutwut** [comment]
Thanks @mfoliveira!
@zet809 Can you take a look at this and see if we can get a fix into the RC1 build tomorrow morning.

**Comment by zet809** [comment]
Fixed in pull request 459.

**Comment by zet809** [comment]
@mfoliveira The modification had been merged and included in the latest build, will you pls verify this issue? Thx a lot.

**Comment by mfoliveira** [comment]
Hi @zet809 

Sorry, I can't.  The hardware gone away :)

It's possible to manually reproduce it by setting the MTM variable/line in discopacket, as in the first comment:

```
  MTM LINE IN DISCOPACKET
    <mtm>8335-GTA        </mtm>
```

Hope this helps!

Thanks!

**Comment by zet809** [comment]
I have verified the data in discopacket, the spaces are removed. So, close this defect.
