### ISSUE TITLE
[OpenBMC] Add ability to resolve Error faults on the BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4571]
To clear out the LED faults, the issues have to be resolved then marked as resolved in the Logging API, then the LED will turn off.  

One way is to clear all logs, or clear individual logs.  I don't think xCAT supports this clear of individual logs, opening this issue to track the function.

To resolve a issue, pass  `'{"data":1}'` to the following endpoint:
```
https://$bmcIP/xyz/openbmc_project/logging/entry/$logNumber/attr/Resolved
```

Thinking about how we can externalize this, maybe the following external interface.
```
reventlog <node> resolved=1,4,5,6,20
```

This doesn't seem to difficult, can we get this into sprint 1 of 2.13.10? @zet809

**Comment by whowutwut** [comment]
@xuweibj This one came up on the Triage call, it would be good if xCAT can assist in clearing the Faults individually (which then would clear the LED and turn off the fault...) without doing a full remove of all the BMC logs. 

I will also look into this today and provide and update if I resolve it

**Comment by whowutwut** [comment]
@xuweibj I created PR #4579 to handle it, please review if you have a chance.

**Comment by zet809** [comment]
hi, @whowutwut , shall we close this issue since the PR is merged? Thx!
