### ISSUE TITLE
[DEV] refine the code logic to determine the proper disk to partition in "pre.<os>" 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#458]
1.  investigate and design the logic to determine the proper disk to partition
2. refine the current code for different linux distributions in pre script, make it consistent for redhat, suse and ubuntu. abstract the logic in one common file, include it in the pre script of various linux distributions.

**Comment by bybai** [comment]
This defect has been converted into new feature in 2.12: determine the proper disk to partition rh/ubuntu/sles/powerKVM

**Comment by xuweibj** [comment]
pull requests #531

**Comment by dletai** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    I don't have access to a git clone of xcat right now, but I'd like
    to offer a couple of style changes:
    1) assuming FS_TYPE is never case insensitive (why would you assume
    it is?)
    - fs_type=$(udevadm info --query=property
        --name=/dev/$partition | grep -i "FS_TYPE"
        | awk -F = '{print $2}')
    + fs_type=$(udevadm info --query=property
        --name=/dev/$partition |awk -F= '/FS_TYPE/{print $2}')
        or if case insensitivity must be preserved
        +  fs_type=$(udevadm info
            --query=property --name=/dev/$partition
            |awk -F= 'toupper($0)~/FS_TYPE/{print
            $2}')
        
        2) use [:<tag>:] rather than [character-range] - in
        different locales bash might not handle character ranges
        correctly, especially non-ascii or multibyte chars
        - disk_part=$(echo
    $partition | tr -d '[0-9]')
    - disk_wwn=$(udevadm info --query=property --name=$disk_part |
        grep '\<ID_WWN\>' |
        cut -d "=" -f2 |
        tr A-Z a-z)
    + disk_part=$(tr -d '[:digit:]'
            <<< $partition)
          + disk_wwn=$(udevadm info
              --query=property --name=$disk_part
              | grep '\<ID_WWN\>' |
              cut -d "=" -f2 |
              tr [:upper:] [:lower:])
                or even
                + disk_wwn=udevadm info --query=property
                --name=$disk_part | awk -F= '/\<ID_WWN\>/{print
                tolower($2)}'
                or with sed (but less clear)
                + disk_wwn=udevadm info
                            --query=property --name=$disk_part |
                sed '/\<ID_WWN\>/!d;s/.*=\(.*\)/\L\1/'
              -
        
    On 04/01//2016 07:22, xuweibj wrote:
    
    
      pull requests #531
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by whowutwut** [comment]
@xuweibj  I think the previous comment here is referencing your pull request #531, please take a look at the suggestions made by @dletai
