### ISSUE TITLE
Should goconserver logs be in /var/log/consoles ? 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4583]
@chenglch Should goconserver logs be in `/var/log/consoles`? 

It seems like they do not conflict since the logs are under a `nodes` directory AND have `.log` in their filename....
```
[root@briggs01 log]# ls -ltr goconserver/
total 92948
drwx------ 2 root root     4096 Dec 21 15:47 nodes
-rw------- 1 root root 95169175 Dec 21 15:47 server.log
[root@briggs01 log]# ls goconserver/nodes/
dummytest.log  mid05tor12cn02.log  mid05tor12cn05.log  mid05tor12cn13.log  mid05tor12cn15.log  mid05tor12cn16.log  mid05tor12cn18.log  node-8335-gtc-1318c4a.log  sn01.log  sn02.log
[root@briggs01 log]#
```
And `/var/log/consoles`....
```
[root@briggs01 log]# ls -ltr consoles/
total 2024728
-rw-r--r-- 1 root root    239270 Nov 15 10:23 mid05tor12cn01
-rw-r--r-- 1 root root    185269 Nov 15 10:23 mid05tor12cn06
-rw-r--r-- 1 root root    189775 Nov 15 10:23 mid05tor12cn07
-rw-r--r-- 1 root root 275528624 Nov 15 10:23 mid05tor12cn08
```

I thought that console was not working when looking at the logs but then realized it was in a different location. So having it like this would trip up some people if we eventually want to move to using gocons...

**Comment by robin2008** [comment]
Yes, better to make it configurable.

**Comment by chenglch** [comment]
It's configurable at `goconserver` side, a yaml format configuration file `/etc/goconserver/server.conf`.  I will modify the default value in `makegocons` command from xcat and consider the requirement https://github.com/chenglch/goconserver/issues/14 together.

At xcat side, I plan to add a new option `-f` to accept a yaml configuration file customized by the user, this is also friendly to the version control system.

**Comment by whowutwut** [comment]
@chenglch  How was this rpm generated and how does it plan to be generated? 

```
[root@briggs01 ~]# rpm -qf /etc/goconserver/server.conf
goconserver-0.1.0-snap201712080604.ppc64le
```

Is it created by our team and shipped in xcat-dep rpm?   

Before we fully support it as a replacement for conserver, is the user suppose to do the following: 
1. Configure the xcat-core and xcat-dep  repos
2. Install xCAT
3. If using goconserver, `yum install goconserver` 

Regarding that config file, what happens on update on `goconserver` , would any changes be overwritten in that file?

**Comment by chenglch** [comment]
@whowutwut , the rpm is downloaded from the release link https://github.com/chenglch/goconserver/releases and the rpm is generated by the script https://github.com/chenglch/goconserver/blob/master/dirty-rpmbuild based on the binary tarball with golang environment.

As goconserver is still in the development stage, it would take too much effort to build packages and upload them to the xcat-dep repos. My thought is that we could upload a new version rpm packages for goconserver when we release xcat, and then user suppose to do the following:

1. install xcat
2. If using goconserver, download goconserver rpm from `xcat.org`, yum install goconserver

**Comment by whowutwut** [comment]
@chenglch if the code is modified in the other repo, we can close this issue..

**Comment by chenglch** [comment]
Close this one as the default configuration changes at https://github.com/xcat2/xcat-core/pull/4603

**Comment by whowutwut** [comment]
@chenglch  Is there any documentation that says we have to reload go-conserver for this to take effect.  

We have updated xCAT many times in the last month, and today the logs were still writing to /var/log/goconserver/nodes.... 
 

```
[root@briggs01 lib]# service goconserver restart
Redirecting to /bin/systemctl restart goconserver.service
```

That fixed it.. . but looks like changes in the code and updating xCAT won't make these things take effect.  Just a FYI

**Comment by chenglch** [comment]
@whowutwut , there is not documentation for this currently. Only `service goconserver restart` could reload the configuration, updating or restarting xcat would not affect goconserver.

On `briggs01`, to test the `output plugins`, the log is written to both `/var/log/goconserver/nodes` and `/var/log/consoles/`.
```
logger:                                              # multiple logger targets could be specified
    file:                                              # file logger, valid fields: name,logdir. Accept array in yaml format
       - name: default                                 # the identity name customized by user
         logdir: /var/log/consoles                   # default log directory of xcat
       - name: gocons
         logdir: /var/log/goconserver/nodes
```

**Comment by whowutwut** [comment]
@chenglch I am testing this today and it's still using the /var/log/goconsole instead of storing into /var/log/console 

```
[root@fs2vm110 goconserver]# rpm -qa | grep goconserver
goconserver-0.2.1-snap201802021015.ppc64le
[root@fs2vm110 goconserver]# ls -ltr /var/log/consoles/
total 0
[root@fs2vm110 goconserver]# ls -ltr /var/log/goconserver/
total 8
drwx------ 2 root root 4096 Feb  2 10:15 nodes
-rw------- 1 root root  792 Feb 13 11:39 server.log
```


I thought the config file was planned to be modified:
```
[root@fs2vm110 goconserver]# egrep "logdir|logfile" /etc/goconserver/server.conf
  logfile: "/var/log/goconserver/server.log"
      # valid fields: name, logdir
        logdir: /var/log/goconserver/nodes/
      #   logdir: the directory for the console log
```

**Comment by whowutwut** [comment]
Thinking about this some more.... 

it does make more sense to be in `/var/log/goconserver`instead of `/var/log/conserver`...  we just have to get used to it.   

The issue is when we have management nodes switched to /var/log/goconserver and didn't remove the /var/log/console logs, so it looks like the consoles stopped responding and no longer write to those files...

**Comment by whowutwut** [comment]
Ok really confused now @chenglch  I created a 2nd VM, and it's config looks like this: 

```
[root@fs2vm112 consoles]# egrep "logdir|logfile" /etc/goconserver/server.conf
  logfile: /var/log/goconserver/server.log             # the log for goconserver
    file:                                              # file logger, valid fields: name,logdir. Accept array in yaml format
         logdir: /var/log/consoles                   # default log directory of xcat
    #    logdir: /var/log/goconserver/nodes
```

vm110 and vm112 are identical,  looks like we are injecting this somewhere...

**Comment by chenglch** [comment]
`makegocons` would change this configuration, if `goconserver` is not used with xCAT, the default console log path would be `/var/log/goconserver/nodes` and user could change it based on their requirement.

**Comment by whowutwut** [comment]
@chenglch thanks!  Yes, Makes sense. I opened an issue under the goconserver project with some other questions
