### ISSUE TITLE
figure out user case based on automation environment

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4594]
* [ ] the inventory template based on automation env

**Comment by whowutwut** [comment]
@zet809  I don't understand this task...   you must have something in mind for creating this issue. Why not just create with the single Use Case in mind instead of "figure out" the use case... do we not know a use case?  

Don't know what inventory template based on automation env means...

**Comment by zet809** [comment]
The idea is based on the automation env scenario, such as 1MN+2CN, we shall be able to generate an inventory file that can be used to recreate the env. For example, some configuration is missed up, some attribute/node is removed.

**Comment by zet809** [comment]
Seems this issue is covered by #4749, close this one.
