### ISSUE TITLE
[Project management] Correction of milestones 

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4602]
Taking a look at all issues and pull requests not under a milestone, I get a very long list: https://github.com/xcat2/xcat-core/issues?q=is%3Aclosed+no%3Amilestone

-  The merged PRs in this list should not be here, but should instead be under their correct corresponding milestone.
- The closed PRs are correctly placed here.
- Issues may or may not be here depending on whether they are closed with an associated fix or just closed.

This is a low priority project management task, but something I hope can be done as it helps me build my case for xCAT upgrades to my company management in a much easier manner (just look at the milestones and pick out the fixes that affect us, instead of searching ...), allowing them to crosscheck easily too.

**Comment by bybai** [comment]
👍

**Comment by whowutwut** [comment]
@samveen Thanks for bringing this up, I have been trying to correctly label and set milestones so i can run queries and this is an issue, will make sure that we do better moving forward, i got most of the 2.13.9 issues tagged to the milestone , will work on this in the next few weeks to close the list

**Comment by whowutwut** [comment]
OK.... @samveen  I opened all the milestones back to 2.11 ( I might have messed up some of those at 2.11 release) but found I can query `closed:>YYYY-MM-DD` and searched each release from 2.13.9 going backwards and associated to the milestone.. 

The query above you ran now shows 0 closed issues.  We will try and do a better job in keeping it zero moving forward.  

Thanks again for bringing this up.
