### ISSUE TITLE
Possible issues with using a DNS name for `xcatmaster` instead of an IP

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4606]
I have a situation where I need to convert 4 separate xCAT clusters into a single hierarchical cluster. For that purpose, I decided to use some DNS magic, setting the `xcatmaster` attribute to a dns name instead of an IP. The rationale behind this is that as xcat service on all nodes are configured to connect back to the value specified in the `XCATSERVER` field in `/opt/xcat/xcatinfo`, I could trick the nodes to send responses to the new service node for each cluster using dns magic.

However now, when I use `xcatprobe` to check the xcat masters that need to be replaced by service nodes, I see the following error:
```
=================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [FAIL]
    Checking 'site' table is configured...                                                                        [FAIL]
        The value of 'master' in 'site' table isn't an IP addres
```
My question is that why is there so much of a reliance on the IP of the server? Is there any technical reason why I can't use a `DNS name` instead of the server's IP?

**Comment by robin2008** [comment]
@samveen 
I think here is to avoid potential DNS issue which the name cannot be resolved during the CN provisioning.
And in fact, xCAT now will use IP instead in most of the case (pxe/petitboot file, xcatinfo) even if you are set an hostname.

If you could guarantee the DNS is always working you can use the name, we don't see any potential risk even if the xcatprobe report error.

**Comment by samveen** [comment]
@robin2008 Can the xcatprobe output downgrade this to a warning instead of an error, with a warning about the availibility of DNS? (We manage DNS outside of xCAT (replicating inventory information from our information system into xCAT and DNS auto-magically) )

**Comment by robin2008** [comment]
@samveen Thanks, we will have more discussion on in the team to see if we can downgrade it as a warning

**Comment by robin2008** [comment]
@hu-weihua 

Could you help to give an estimation here for `xcatprobe`,  I found that it need a bit enhancement in xcatprobe framework to report error or warning in a same checking. Just like below:
```
checkA()
   if unmet A.1 :  report error
   elif unmet A.2 : report warn

```
For site.master checking,  here is better to report an warning if using name but the name is resolvable.

**Comment by hu-weihua** [comment]
@samveen xCAT probe xcatmn has been enhanced by pull request #5693 , could you help to try again? thanks.

**Comment by hu-weihua** [comment]
@samveen , since we have verified this fix in our environment, I closed this issue first. If you find it can not work at your environment, feel free to reopen it again. thanks.
