### ISSUE TITLE
The result of rvitals for habanera is not correct 

### ISSUE THREAD

**Issue by mavscjb** [xcat2/xcat-core#461]
When using rvitals to get habanera's dimm's temperature, the results we got are as follows:[root@mn62 xCAT]# rvitals cnless19 temp | grep DIMM
cnless19: DIMM1 Temp 1: 35 C (95 F)
cnless19: DIMM1 Temp 2: 0 C (32 F)           (At or below lower non-critical threshold)
cnless19: DIMM1 Temp 3: 37 C (99 F)
cnless19: DIMM1 Temp 4: 0 C (32 F)           (At or below lower non-critical threshold)
cnless19: DIMM1 Temp 5: 36 C (97 F)
cnless19: DIMM1 Temp 6: 0 C (32 F)           (At or below lower non-critical threshold)
cnless19: DIMM1 Temp 7: 34 C (93 F)
cnless19: DIMM1 Temp 8: 0 C (32 F)           (At or below lower non-critical threshold)
cnless19: DIMM2 Temp 1: 35 C (95 F)
cnless19: DIMM2 Temp 2: 0 C (32 F)           (At or below lower non-critical threshold)
cnless19: DIMM2 Temp 3: 34 C (93 F)
cnless19: DIMM2 Temp 4: 0 C (32 F)           (At or below lower non-critical threshold)

I think that the DIMM's temp should not be 0℃.
This may be a bug for xcat.

**Comment by bybai** [comment]
Could you give us the output of ipmitool?
ipmitool-xcat -I lanplus -H <bmc_ip> -U <bmcuser> -P <bmc_pw> sdr elist all

**Comment by zet809** [comment]
From xCAT point of view, it just read sensor info and translate it to text, and based on the fact that the ipmitool also return the same value. So, I think it is the hardware(especially the sensor) failure which cause the Temp to be 0. So reject this defect.
