### ISSUE TITLE
update xcat-genesis-base-amd64 from 2.13.2 failed to move directory to links

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4614]
After contos 7, the directory bin, lib, lib64 and sbin are modified to links to directory under /usr.

Since the latest xcat-genesis-base-amd64 is build based on centos7.4, we shall deal with the modification in order to have user update the package. 
The rpm package have been fixed, this task is for ubuntu .deb build.

```
lrwxrwxrwx    1 root root    7 Nov 27 03:33 bin -> usr/bin
lrwxrwxrwx    1 root root    7 Nov 27 03:33 lib -> usr/lib
lrwxrwxrwx    1 root root    9 Nov 27 03:33 lib64 -> usr/lib64
lrwxrwxrwx    1 root root    8 Nov 27 03:33 sbin -> usr/sbin
```

**Comment by samveen** [comment]
@zet809 It could possibly be fixed by changing the file paths of the `xCAT-genesis-scripts-*` packages to be `/usr/*bin/` instead of `/*bin` which will remove the path collisions where `/*bin` is a `dir` vs `/*bin` is a link.

**Comment by samveen** [comment]
@zet809 @neo954 It could possibly be fixed by changing the file paths of the `xCAT-genesis-scripts-*` packages to be `/usr/*bin/` instead of `/*bin` which will remove the path collisions where `/*bin` is a `dir` vs `/*bin` is a link.

This _should_ fix both `rpm` and `deb` packages.
