### ISSUE TITLE
The result of "rvitals wattage" is not right on firestone and habanero

### ISSUE THREAD

**Issue by mavscjb** [xcat2/xcat-core#462]
When using command "rvitals wattage" to get cpu's power consumption on firestone and habanero,the result shows as follows:

[root@mn62 ~]# rvitals cnless19 wattage
cnless19: CPU VDD Curr: 48 Amps

I think that the result should directly returns the power consumption。

**Comment by zet809** [comment]
@jjohnson42 From the ipmi.pm, it seems wattage point to sensor type 0x03 which means Current in IPMI specification. Even the value is united in watts for system X with sensor type 0x03, but it shouldn't.
So, my fixes is, to check the sensor unit of sensor, if it equal to 0x06 (Watts), it shall be output for wattage option of rvitals. 
The pull request is 468, will you pls help to review?

**Comment by bybai** [comment]
verified.
