### ISSUE TITLE
[FVT]:copycds SLES12 SP1 iso need to specify the OS version

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#463]
xCAT 2.11 sles12 sp1
c910f03c04k04:/iso/suse/12/SP1_RC2 # copycds SLE-12-SP1-Server-DVD-ppc64le-RC2-D
Error: copycds could not identify the ISO supplied, you may wish to try -n <osver>

**Comment by tingtli** [comment]
It is tricky that 11/19 build does not get the fix of 2c22c82b4d34af9d62e2c86959a038ed6376d4e7
Use today's build verify and close.

**Comment by whowutwut** [comment]
Ha! I was just going to ask what lsxcatd showed. :-)  we fixed this on Friday... So I was surprised that this issue was opened
