### ISSUE TITLE
[Customer]The method to mix initrd.gz from mini.iso and vmlinux from full LE ISO does not work for Ubuntu14.04.3

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#464]
In order to boot from network, the current method mentioned in wiki is only replace initrd.gz which is from mini.iso. But this will lead to the unmatched kernel version between initrd.gz and vmliuz sometimes. In bugzilla 132960, they said, it does not permit to mix the mini.iso and full LE ISO.

Please refer to the link:
http://sourceforge.net/p/xcat/wiki/Ubuntu_Quick_Start/
http://sourceforge.net/p/xcat/wiki/XCAT_P8LE_Hardware_Management/
https://bugzilla.linux.ibm.com/show_bug.cgi?id=132960

**Comment by bybai** [comment]
Hi @fenggaobj, our FVT hit the same problem before. Sometimes, the mini.iso downloaded from http://ports.ubuntu.com/ubuntu-ports/dists/trusty-updates/main/installer-ppc64el/current/images/vivid-netboot/ cannot work with full LE ISO, but we also download the available mini.iso which is used by you.

**Comment by zet809** [comment]
As the bugzilla 132960 mentioned, there will be a new defect needed to open to ask for the mini.iso for ubuntu14.04.3 GA. Once the url of the mini.iso is ready, I can put it into xCAT doc. Pls attach the bugzilla number here the trace the issue. Thx!

**Comment by zet809** [comment]
PCM have open another defect https://bugzilla.linux.ibm.com/show_bug.cgi?id=133655 for this issue.

**Comment by zet809** [comment]
We will upload the matching mini.iso onto xcat.org and update document later. Keep this defect open to trace the process.

**Comment by whowutwut** [comment]
How does this normally work for Ubuntu customers? It looks like they assume their customers will always run at the latest version?   If that's the case, why should we provide the download for these mini isos if it's not a supported scenario from Ubuntu?

**Comment by zet809** [comment]
The problem is that, if the user want to use released ubuntu ISOs such as 14.04.1, 14.04.2, 14.04.3... They may not be able to find where to download the correct mini.iso.
If they use the latest dev version, they need to download mini.iso by themselves.

**Comment by robin2008** [comment]
I don't think LTC will accept the request.  Actually booting from net, the Linux kernel in vmlinux and initrd should be the same version, or you might hit the driver issue.

Could we investigate how to enhance it in xCAT side, for example, use the vmlinux and initrd both from mini.iso.
@zet809,  could you explain why we cannot use the vmlinux from mini.iso?

**Comment by zet809** [comment]
@robin2008 If the mini.iso is correct for the release ubuntu ISO, the vmlinux in mini.iso and ubuntu ISO is exactly same. 
Our solution is, putting the corresponding mini.iso on xcat.org and modify our doc to let user know which mini.iso shall be downloaded for specified ubuntu ISO.

**Comment by zet809** [comment]
@robin2008 I have uploaded the mini.iso for each LTS ubuntu release onto xcat.org, pls reference http://xcat-docs.readthedocs.io/en/latest/ for the updates.

**Comment by whowutwut** [comment]
Here's the location on xcat.org 
https://xcat.org/files/netboot/
