### ISSUE TITLE
[OpenBMC] openbmc in python framework refactor

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4671]
* [ ] redefine the interface, framework for openbmc in python
       design and coding
* [ ] move rpower with new framework

**Comment by robin2008** [comment]
It is addressed in https://github.com/xcat2/xcat-core/pull/4763

The new rpm in shared location: /data/xcat/openbmc-python/xCAT-openbmc-py-2.13.11-snap201802020253.noarch.rpm
