### ISSUE TITLE
enable goconserver by default for xCAT

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4684]
Priority 1:
* [x] move code directory from private repo to xcat2 repo

Priority 2:
* [x] need to modify code to enable goconserver by default, seems just setup goconserver by default, user need to run `makegocons` to enable goconserver, so @chenglch , pls help to udpate the RTD.

**Comment by whowutwut** [comment]
@zet809 Is there really a need to enable this by default for the next xCAT release? Why not just offer this as an alternative to conserver that addresses a list of problems (where is this list?) and allow the user to decide to make the switch. 
* 
*

Internally in the various clusters that are running xCAT, we should push them to move over to goconserver to get more testing and ensure that we have covered all the scenarios that we will need to support: 
* redirecting console logs to BDS
* rollover of console logs? 
* full hierarchy support tested
* anything else?

**Comment by chenglch** [comment]
I agree with @whowutwut , we could ship goconserver in `xcat-dep` for RHEL7.0 system or higher, but it is only an alternative choice as an addon package for the user.

I think we could add some playbook to setup xcat-mn, xcat-sn and the other dependency tools like goconserver. RPM/DEB package is not flexible enough to setup a xcat cluster.

**Comment by zet809** [comment]
It seems like this:
1. For refresh installation, we can enable goconserver by default.
2. For update, we can provide the steps to switch to goconserver.
What is your idea?

**Comment by chenglch** [comment]
@zet809 , I think we should consider the following steps:

* Move the repo to xcat2
* Enable gconserver package in xcat-dep only for RHEL 7 systems (ppc64le and amd64)
* Get some feedback from tester or user
* Enhance goconserver based on the requirement

The workload to build packages and upload packages is very high. I don't think we should enable it by default immediately.

**Comment by whowutwut** [comment]
@chenglch @zet809 How is this intended to work? I talked to @zet809 and @robin2008 last night on the phone, but it seems like both conserver and goconserver is installed by default, but it's really up to the user to decide which one to activate, either by 

* makeconservercf
* makegocons

```
[root@fs2vm111 ~]# rpm -qa | grep conserver
conserver-xcat-8.2.1-1.ppc64le
goconserver-0.2.1-snap201802021015.ppc64le
[root@fs2vm111 ~]# ps -ef | grep conserver
root     26308 26243  0 11:16 pts/0    00:00:00 grep --color=auto conserver
[root@fs2vm111 ~]# makeconservercf f6u13
[root@fs2vm111 ~]# ps -ef | grep conserver
root     26351     1  0 11:16 ?        00:00:00 /usr/sbin/conserver -o -O1 -d
root     26352 26351  0 11:16 ?        00:00:00 /usr/sbin/conserver -o -O1 -d
root     26364 26243  0 11:16 pts/0    00:00:00 grep --color=auto conserver
[root@fs2vm111 ~]# makegocons
Error: conserver is started, please stop it at first.
```
If I run makeconservercf, it will start conserver.  

But if we want to push for users to switch to `goconserver`, then we have to update the documentation to change references to `makegocons`...

**Comment by chenglch** [comment]
@whowutwut ，Maybe we just setup goconserver by default.  User could choose which one to use when they run `makeconserver`, `makegocons` or `makeconfluentcfg` command. 

Yes, we have to update the documentation to describe how to enable these console plugins.

**Comment by zet809** [comment]
Yes, we shall update RTD to use `makegocons` by default for RH7 or ubuntu16.04...
