### ISSUE TITLE
[fvt] verify new feature : makegocons -q

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4691]
what to do :

* [ ] offer a test plan [Test Design of makegocons option l](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-makegocons-option-l) . The expected run time is before 2018/2/2 (CDL time)

The estimated time of code ready : the end of 2th week of sprint 1, around 2018/2/2
The expected run time is 2018/2/5 (CDL time)

**Comment by hu-weihua** [comment]
@neo954 , please handle your task in time. The test plan should be a detailed step by step. The commit finish day of this task is last Friday (Feb 2). It has been delay.

**Comment by neo954** [comment]
Issue #4880 opened.
