### ISSUE TITLE
[FVT]Need to support detach operation for PowerKVM PCI pass-through

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#470]
xCAT 2.11 support PCI pass-through feature for PowerKVM. With this feature, now, the end user can attach PCI adapter for PowerKVM guest. But for xCAT support, there is no detach operation. While virsh and PowerKVM do support the detach operation.

I think xCAT need to support detach operation for PowerKVM PCI pass-through.

**Comment by immarvin** [comment]
https://github.com/xcat2/xcat-core/pull/524

**Comment by neo954** [comment]
This bug is verified. I will close this one.
