### ISSUE TITLE
makedhcp -a produces ambiguous errors 

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#4717]
When trying to run 
makedhcp -a 
from the management node, it couldn't start the DHCP server on the service nodes.  The error that was returned did not state that 

```root @ xcat1: /root
# makedhcp -a
Error: dhcp server is not running.  please start the dhcp server.
Warning: Unable to find mac address for xcat1
Error: dhcp server is not running.  please start the dhcp server
```

[root@sn01 Witherspoon]# lsxcatd -v
Version 2.13.9 (git commit 113bab618f6f99aa6c17cabef54f2748d4bb11cf, built Fri Dec 15 07:16:01 EST 2017)

**Comment by whowutwut** [comment]
@robin2008 I think this issue is just to enhance the output message to tag the service node the message is coming from?

**Comment by robin2008** [comment]
Plan to made some changes on the error/warn message,  for such error/warn message, we should print the service node hostname by default.

**Comment by robin2008** [comment]
This ticket include two different issues:
1, error/warn will not show server name, then user cannot determine which node need to be inspect.
2,to check dhcpd is in preprocess handler,  so it could not find the issue on service node when its dhcp is not running.

**Comment by robin2008** [comment]
show server name for  error/warn message is addressed in https://github.com/xcat2/xcat-core/pull/5119

**Comment by robin2008** [comment]
The dhcpd issue is already covered in ca6024750fe81102a2c3f18b229f7c3dff9cba7a
