### ISSUE TITLE
[OpenBMC] Add support for modifying BootMode settings

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4718]
With the framework set in place, we can easily add support for things like BootMode: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Control/Boot/Mode.interface.yaml and allow the user to leverage xCAT to set this attributes instead of running CURL commands manually.  (similar to `RSPCONFIG_POWERRESTORE_POLICY`)

I'm not sure what the use case is for this ,we should discuss with Firmware team to understand when we would want to set this ..

**Comment by gurevichmark** [comment]
Implemented by #4727
