### ISSUE TITLE
[OpenBMC] rspconfig cases failed in automation 

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#4721]
Failed cases:
rspconfig_set_ip, rspconfig_ip_invalid, rspconfig_ip_null, rspconfig_set_netmask, rspconfig_netmask_invalid, rspconfig_set_gateway, rspconfig_gateway_invalid, rspconfig_list_all, rspconfig_list_gateway, rspconfig_list_ip, rspconfig_list_netmask, rspconfig_list_vlan, rspconfig_set_all_invalid, rspconfig_set_vlan, rspconfig_set_vlan_invalid, rspconfig_set_hostname_equal_star_with_bmc_is_ip, rspconfig_set_hostname_equal_star_with_bmc_is_hostname, rspconfig_get_hostname, rspconfig_hostname_with_error_input, rspconfig_set_hostname, rspconfig_set_admin_passwd_with_error_input, rspconfig_set_admin_passwd_with_error_origin_password, rspconfig_sshcfg_with_error_input, 

Example:
```
RUN:rspconfig f6u17 hostname |tee /tmp/rspconfig_get_hostname/rspconfig_output [Wed Jan 24 19:39:26 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
       rspconfig <noderange> powerrestorepolicy
       rspconfig <noderange> powerrestorepolicy={always_on|restore|always_off}
       rspconfig <noderange> powersupplyredundancy
       rspconfig <noderange> powersupplyredundancy={disabled|enabled}
       rspconfig <noderange> autoreboot
       rspconfig <noderange> autoreboot={0|1}

CHECK:rc == 0	[Pass]
```

**Comment by gurevichmark** [comment]
Fixed by #4716
