### ISSUE TITLE
mixed mgt type does not provide good output messages when using noderange

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4728]
It looks like in a mixed Power9 environment where some are managed by ipmi and some are managed by openbmc, the messages across node ranges does not tag the node name where the error is coming from 

```
[root@stratton01 Control]# rspconfig p9 bootmode
Unsupported command: rspconfig bootmode
p9euh01: BMC BootMode : Regular
```

So here, initially I thought the firmware does not support the BootMode display, but then looking at the list of nodes, I find one is a boston (IPMI) and one is a witherspoon (openbmc)

```
[root@stratton01 Control]# nodels p9
boston02
p9euh01
```

Really the output should be: 

```
[root@stratton01 Control]# rspconfig p9 bootmode
boston02: Unsupported command: rspconfig bootmode
p9euh01: BMC BootMode : Regular
```

This is just an example, I'm sure there are many more...  

@hu-weihua Is there any automation plans to test mixed compute node environment?

**Comment by zet809** [comment]
hi, @xuweibj , will you pls help enhance the output of hw command? Thx!

**Comment by zet809** [comment]
Hi, @whowutwut and @xuweibj , the message below is a little confusing for user. 'rspconfig bootmode' is supported or unsupported? 
```
[root@stratton01 Control]# rspconfig p9 bootmode
boston02: Unsupported command: rspconfig bootmode
p9euh01: BMC BootMode : Regular
```
So, it maybe much helpful to add more information, for example, `boston02: Unsupported command "rspconfig bootmode" for ipmi management method`?

**Comment by hu-weihua** [comment]
@whowutwut, could you help to verify this issue? thanks. 

It is little hard to automated mixed cluster test because of test case depending on CN's attribute. But we can cover this test in manual test first.

**Comment by whowutwut** [comment]
This looks good, 
```
[root@stratton01 ~]# lsxcatd -v
Version 2.14 (git commit d94387bc147628571dce326d35cf8c6fabdb68d0, built Tue Apr 10 06:15:48 EDT 2018)
```

Running original case:
```
[root@stratton01 ~]# rspconfig p9 bootmode
boston02: Error: Unsupported command: rspconfig bootmode when using mgt=ipmi.
boston33: Error: Unsupported command: rspconfig bootmode when using mgt=ipmi.
f4u18: Error: Unsupported command: rspconfig bootmode when using mgt=ipmi.
Cannot figure out plugin for nodes:f4u18
p9euh01: Error: [500] Login to BMC failed: 500 Can't connect to 10.6.7.254:443 (No route to host).
p9euh01: Error: BMC did not respond. Validate BMC configuration and retry the command.
f6u03: BMC BootMode : Regular
f6u13: BMC BootMode : Regular
```
