### ISSUE TITLE
Crash when netbooting anything but genesis

### ISSUE THREAD

**Issue by ryanbowen** [xcat2/xcat-core#4730]
I'm having issues trying to boot to any stateless image other than genesis (The new centos7.4 version). If I boot a fresh node, PXE's fine, discovers fine and drops into standby. When I run nodeset, it reboots and again successfully gets dhcp and xnba, but then times out in xNBA at:
 
```
Filename: http://<MN-IP>/tftpboot/xcat/xnba/nodes/<node>.uefi
http://<MN-IP>/tftpboot/xcat/xnba/nodes/<node>.uefi............
```

The weird thing is every once in a while it successfully boots. I don't see anything when tailing httpd so I'm thinking it has to do with a driver issue for the Broadcom card, but genesis doesn't have this problem.

**Comment by ryanbowen** [comment]
Just an update, this is only occurring while booting using UEFI. Changing to Legacy makes everything work correctly.

**Comment by immarvin** [comment]
hi @ryanbowen , how did you power cycle the node? for uefi mode, do not forget to use `rsetboot -u`

**Comment by immarvin** [comment]
` Also, genesis fails to boot in the same way when "nodeset node1 shell" is done on the node, but does not fail on initial discovery boot.`, please provide more detail information on this, thx

**Comment by ryanbowen** [comment]
What I meant by that was:
Undiscovered node -> power on -> successfully boots to genesis for discovery  -> discovered -> nodeset shell -> reboot -> fails to boot to genesis (times out getting bootloader config)

**Comment by immarvin** [comment]
what do you see on screen when `times out getting bootloader config` ?

**Comment by zet809** [comment]
Hi, @ryanbowen , is there any more information or logs?
Can you show me the http.log on your Management Node?
What kind of x86_64 are you using? the xNBA doesn't support it?

**Comment by zet809** [comment]
Hi, @ryanbowen , is there any more information or logs?
Can you show me the http.log on your Management Node?
What kind of x86_64 are you using? the xNBA doesn't support it?

**Comment by zet809** [comment]
Hi, @ryanbowen , where do you see 'http.... uefi' information?
The information is in httpd log on my env:
```
# cat /var/log/httpd/access_log  | grep uefi
x.x.x.x - - [25/Jan/2018:09:34:24 -0500] "GET /tftpboot/xcat/xnba/nodes/<node>.uefi HTTP/1.1" 200 109 "-" "iPXE/1.0.3-131028 (d603e)"
```

**Comment by ryanbowen** [comment]
Hi @zet809,

That information shows on the console of the booting node when in xNBA. I see nothing in my https logs related to the node during this but the http is definitely working.

**Comment by ryanbowen** [comment]
![2018-01-25_13-18-01](https://user-images.githubusercontent.com/11137988/35443303-a1648218-0278-11e8-9f5b-6dc90eba47ed.png)

**Comment by zet809** [comment]
hi, @ryanbowen , is the file "bdt-n1.uefi" is available to download?
Pls try "wget http://10.2.255.253/tftpboot/xcat/xnba/nodes/btd-n1.uefi" on your MN or 10.2.255.253. Thx!

**Comment by ryanbowen** [comment]
Hi @zet809,

Yes it is able to be downloaded:
![image](https://user-images.githubusercontent.com/11137988/35598909-1e31d006-05f4-11e8-9ff1-4f4266406531.png)

**Comment by zet809** [comment]
hi, @ryanbowen , any update for this issue?

**Comment by ryanbowen** [comment]
Hi @zet809 , it seemed to be an issue with the Broadcom NIC firmware that was applied by the manufacturer. Seems to be resolved with the latest update.
