### ISSUE TITLE
reventlog does not work against boston servers

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4740]
I didn't spend much time to investigate this, but need someone to look at it asap. 
```
[root@stratton01 ~]# reventlog boston02
boston02: Error: ERROR: Invalid role
[root@stratton01 ~]# reventlog boston02 -V
boston02: [stratton01]: Error: ERROR: Invalid role
```

**Comment by whowutwut** [comment]
Ok, looks like some role is not configured for this node,  I tried on another node and it's working...

@zet809 do we have this process documented somewhere?

**Comment by cxhong** [comment]
boston node has different user/name, and ipmi command will not work

**Comment by cxhong** [comment]
@zet809 ,  stratton01 has the fixes https://github.com/xcat2/xcat-core/pull/4710  relate to this issue https://github.com/xcat2/xcat-core/issues/4652  but failed to verifiy.

**Comment by whowutwut** [comment]
Something with the FW got out of whack.  Opened https://github.com/open-power/boston-openpower/issues/922 but looks like the way to recover this was to manually reset all the configuration (not sure what was bad)  

`ipmitool .. raw 0x30 0x40`
