### ISSUE TITLE
Validate that xCAT can support PDU control when passwords are changed from the shipped defaults

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4742]
Opening this issue to make sure that xCAT PDU support can operate when default passwords are changed for the following PDUs. 

* CORAL compute rack PDU 
* Infrastructure rack PDU (IBM PDU Manager)

**Comment by zet809** [comment]
hi, @whowutwut , shall we make sprint for this task? ^_^

**Comment by whowutwut** [comment]
@cxhong ^ ?

**Comment by cxhong** [comment]
should able to make this sprint.

**Comment by whowutwut** [comment]
Closing out
