### ISSUE TITLE
setroute doesn't work for DHCP interfaces

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4743]
I'm trying to define a default route on my CentOS 7 nodes, on the install NIC, via the `setroute` postscript. It works when the script i s executed, but since the NIC are configured via DHCP, the route settings are ignored when the node reboots or the network is restarted.

For instance, I want to deploy `sh-101-60` with `10.10.0.62` as its default gateway, via `em1` (its installation NIC):
```
# lsdef -t route gw_ln02
Object name: gw_ln02
    gateway=10.10.0.62
    mask=0.0.0.0
    net=default
    usercomment=route all traffic through sh-ln02

# lsdef sh-101-60 -i routenames
Object name: sh-101-60
    routenames=gw_ln02

# lsdef sh-101-60 --nics
Object name: sh-101-60
    nicaliases.bmc=sh-101-60
    nicaliases.ib0=sh-101-60
    nicextraparams.em1=MTU=9000
    nicextraparams.ib0=MTU=65520 CONNECTED_MODE=yes
    nicips.bmc=10.11.101.60
    nicips.ib0=10.9.101.60
    nicnetworks.bmc=net_ipmi
    nicnetworks.ib0=net_ib_100
    nictypes.bmc=bmc
    nictypes.ib0=infiniband

# lsdef sh-101-60 -i postscripts
Object name: sh-101-60
    postscripts=syslog,remoteshell,syncfiles,otherpkgs,confignetwork,setroute replace
```

After deployment, `sh-101-60` is configured with `em1` (the install NIC) in DHCP, and the static route is correctly defined:
```
# cat /etc/sysconfig/network-scripts/ifcfg-em1
# Generated by parse-kickstart
DEVICE="em1"
IPV6INIT="yes"
BOOTPROTO="dhcp"
UUID="44756a91-8596-4eea-85dc-1d3dfd711304"
ONBOOT="yes"

# cat /etc/sysconfig/network-scripts/route-em1
default/0 via 10.10.0.62
```
But since the interface is configured for DHCP, the static route is ignored.

After a reboot:
```
mn # ssh sh-101-60 ip route \| grep default
default via 10.10.0.1 dev em1
```

`setroute` works when it's executed manually:
```
mn # updatenode sh-101-60 -P setroute
sh-101-60: xcatdsklspost: downloaded postscripts successfully
sh-101-60: Fri Jan 26 16:18:06 PST 2018 Running postscript: setroute
sh-101-60: Adding temporary route: ip route replace default via 10.10.0.62; Error: the device name is necessary to configure static route.
sh-101-60: postscript: setroute exited with code 0
sh-101-60: Running of postscripts has completed.

mn # ssh sh-101-60 ip route \|grep default
default via 10.10.0.62 dev em1
```

But restarting the network (or renewing then DHCP lease when it expires) remove the route:
```
mn # ssh sh-101-60 service network restart
Restarting network (via systemctl):  [  OK  ]
mn # ssh sh-101-60 ip route \|grep default
default via 10.10.0.1 dev em1
```

So, how can `setroute` be used on the installation NIC? The [documentation](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/network/cfg_routes.html) seems to imply that this is possible, but doesn't give any specific and doesnt mention DHCP vs static configuration for the interfaces.

Alternatively, what's the best way to configure the install NIC in static mode?

**Comment by immarvin** [comment]
hi @kcgthb  , thanks for reporting this.  I made some investigation, some of my findings:
1) 
```
```

**Comment by kcgthb** [comment]
Great, thanks for investigating this!

**Comment by kcgthb** [comment]
My current workaround is to remove the gateway from the network served by DHCP in the `networks` table (so `dhcpd.conf` doesn't contain any `routers` option for that network). In that case, since no default route information is provided via DHCP, the static route in `/etc/sysconfig/network-scripts/route-<nic>` is correctly applied.

**Comment by samveen** [comment]
Another workaround is the `postbootscripts` field: set it to `setroute` postscript, so that when the xcatpostinst service runs, the postscript is auto-executed. As the xcatpostinst service is dependent on `@network` service, you have a guarantee that the interface will be up already.

**Comment by kcgthb** [comment]
I appreciate the tip, and it's a very valid point. We actually had that in place already (`setroute` in `postbootscripts`), but the issue still happens (and that's how we actually became aware of it) when the DHCP lease is renewed: the default gateway is then provided by the DHCP server again and the local, static default route set up by `setroute` is overridden.

Depending on your DHCP lease expiration time, it could happen more or less often. :)

**Comment by immarvin** [comment]
hi @bybai , would you please take a look at this and check whether we can do some enhancement in our code? thx

**Comment by bybai** [comment]
Hi @kcgthb and @samveen , thanks your suggestions, this issue is under discussion.

**Comment by samveen** [comment]
@kcgthb As luck would have it, in my environment, we don't publish gateway information for networks via DHCP, so maybe that is why it continues to work for us. As the gateway is never set via DHCP information, we never faced this issue. However, the lack of a gateway in the DHCP information opens yet another can of worms, which you do not want to see.

**Comment by bybai** [comment]
Our suggestion: in general user scenario, dynamic gateway from DHCP has conflict with static gateway for one network.
1, if use `setroute` or `makeroutes` to configure static route for compute node, remove gateway for the network in `networks` table before executing `makedhcp` command.
2, if use dynamic gateway from DHCP, configure gateway for the network in `networks` table. 

Will add NOTES in [documentation](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/network/cfg_routes.html)
