### ISSUE TITLE
Disable PowerSupplyRedundancy automatically during discovery of CORAL machines

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4751]
For certain model types of the AC922 servers, the plan of record is to always run with PowerSupplyRedundancy set to disabled.  

The OpenBMC firmware at 1742Ex drivers (ibm-v2.0-0-r25), the default value for this was changed to "Enable", this will cause the PSU to throttle back if issues are detected and it not the desired behavior. 

To help with this, a proposal is for xCAT to disable this value during the discovery process of the hardware. If `8335-GTC` or `8335-GTW` servers are discovered, set the power supply redundancy to Disabled from the Genesis kernel, which will then apply the setting on the next reboot and IPL of the server

* New server is installed into the frame 
* bmcdiscover is issued to discover the BMC 
* power on the host, this kicks off the genesis kernel for discovery
* Inside genesis, discovery is done and we can see the MTM of the server, if GTC or GTW is detected, disable power supply redundancy
   * inband setting (check with FW team if this is an option) 
   * out of band curl setting (requires curl in the genesis kernel) 
*  When the machine OS is deployed, it will cause a reboot of the host and the IPL will cause this to take effect

**Comment by whowutwut** [comment]
Thinking about this some more, let's hold off, I think xCAT may not implement anything because in order for this to be of value, the firmware shipped in MFG must be at a level that will persist the value.  Time may be better spent in getting rspconfig to scale using the Python framwork.. moving to icebox for now...

**Comment by mattaezell** [comment]
I think it would be useful to allow setting all supported settings (`PowerSupplyRedundancy`, `AutoReboot`, etc; see #4294).  I could even be nice to store all relevant settings in the `openbmc` table so that a command like `rspconfig <noderange> all` would fully configure a server "correctly".

**Comment by whowutwut** [comment]
Thanks for that comment @mattaezell Let me follow up on it. 


Turns out the FW does implement this inband...  comment provided in https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW415250  gives us the following: 

```
-bash-4.1$ ./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x2d 0x0b
 00 00 02 00  ==> Read the value, 02 Indicates it is Enabled

-bash-4.1$ ./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x30 0x0b 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00
==> Write the value, 01 indicates to Disable

-bash-4.1$ ./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x2d 0x0b
 00 00 01 00  ==> Read of the sensor indicates it is disabled (01)

-bash-4.1$ ./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x30 0x0b 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 ==> Write the value, 02 indicates to Enable

-bash-4.1$ ./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x2d 0x0b
 00 00 02 00 ==> Read indicates it is enabled
```

So:
`./ipmitool -I lanplus -H wsbmc002 -P 0penBmc -C 1 raw 0x04 0x30 0x0b 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00` to disable
```

**Comment by zet809** [comment]
HI, @whowutwut , maybe we shall add this in bmcsetup script?

**Comment by whowutwut** [comment]
@zet809 I think we can think about this some.. @cxhong is looking at the `ondiscover` issue mentioned above and created a pull request for that.  It might be better if we did not do things under the covers in bmcsetup...

**Comment by hu-weihua** [comment]
@whowutwut, could you help to verify this issue? thanks

**Comment by whowutwut** [comment]
At this time I don't think we plan to do any changes here, will rely on documentation on how to use the `ondiscover` functions to customize site specific configurations.
