### ISSUE TITLE
confignetwork -s prevents nodes to be deployed

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4754]
The `confignetwork` [documentation](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_ethernet_nic.html) indicates that using `confignetwork -s` will configure network interfaces as static:

But on CentOS 7, using xCAT 2.13.10, using `confignetwork -s` in postscripts make the nodes start a deployment loop, and prevents them to be deployed.

Removing the `-s` flag allow the nodes to deploy properly.

**Comment by kcgthb** [comment]
Here's the debug log excerpt from `configmetwork -s` which I think causes the issue: `em1` (install NIC) can't be brought up, so the node can't reach the MN,  and deployment fails:

```
+ log_info 'configure the install nic em1. '
+ local '__msg=configure the install nic em1. '
+ log_print_default '[I]: configure the install nic em1. '
+ printf '%s\n' '[I]: configure the install nic em1. '
[I]: configure the install nic em1.
+ return 0
+ instnic_conf=1
+ configeth -s em1
+ log_lines info
+ local pcnt=1
+ local __level=info
+ shift
+ local cmd=log_info
+ local hit=0
+ local 'OIFS=
'
+ local 'NIFS=
'
+ IFS='
'
+ local __msg
+ IFS='
'
+ '[' 0 -eq 0 -a 1 -le 1 ']'
+ read __msg
+ log_info '[I]: configeth on sh-101-60: os type: redhat'
+ local '__msg=[I]: configeth on sh-101-60: os type: redhat'
+ log_print_default '[I]: [I]: configeth on sh-101-60: os type: redhat'
+ printf '%s\n' '[I]: [I]: configeth on sh-101-60: os type: redhat'
[I]: [I]: configeth on sh-101-60: os type: redhat
+ return 0
+ read __msg
ls: cannot access /var/lib/dhclient/*em1*: No such file or directory
+ log_info 'ib0!MTU=65520 CONNECTED_MODE=yes'
+ local '__msg=ib0!MTU=65520 CONNECTED_MODE=yes'
+ log_print_default '[I]: ib0!MTU=65520 CONNECTED_MODE=yes'
+ printf '%s\n' '[I]: ib0!MTU=65520 CONNECTED_MODE=yes'
[I]: ib0!MTU=65520 CONNECTED_MODE=yes
+ return 0
+ read __msg
/sbin/ifup: line 73: nmcli: command not found
+ log_info '[E]:Error: ifup em1 failed.'
+ local '__msg=[E]:Error: ifup em1 failed.'
+ log_print_default '[I]: [E]:Error: ifup em1 failed.'
+ printf '%s\n' '[I]: [E]:Error: ifup em1 failed.'
[I]: [E]:Error: ifup em1 failed.
+ return 0
```

The config details are the ones provided in #4743

**Comment by bybai** [comment]
Hi @kcgthb ,
Thanks reporting this. I noticed the error "/sbin/ifup: line 73: nmcli: command not found" which made "ifup em1" failed, could you check if there is nmcli in your system?

`confignetwork` should not returns 0 when configeth fails, which is an problem here.

**Comment by bybai** [comment]
Hi @kcgthb,
 `confignetwork` should not returns 0 when configeth fails is fixed in #4789

**Comment by bybai** [comment]
Hi @kcgthb , In installer, there may not be nmcli in your system, if confignetwork is in postscripts, "/sbin/ifup: line 73: nmcli: command not found" can make the nodes start a deployment loop. Will enhance this in #4789 later.

**Comment by immarvin** [comment]
when the scripts `confignetworks` and `confignics` are running in the installer(chroot environment), they should only generate the necessary configuration files , should not invoke operations like `ifdown/ifup`

**Comment by kcgthb** [comment]
I agree with @immarvin, things like `nmcli` are not present in the chroot installer environment, so they can't work.
