### ISSUE TITLE
makeconfluentcfg -h reports truncted command help text

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/xcat-core#4755]
xCAT-server/lib/xcat/plugins/confluent.pm  contains the help text report when you run "makeconfluentcfg -h":
Instead of reporting "makeconfluentcfg" it reports "makeconfluentcf":

# makeconfluentcfg -h
  makeconfluentcfg [-d|--delete] noderange
  makeconfluentcf [-l|--local]
  makeconfluentcf [-c|--confluent]
  makeconfluentcf 
  makeconfluentcf -h|--help
  makeconfluentcf -v|--version
    -c|--confluent   Configure confluent only on the host.
                     The default goes down to all the confluent instances on
                     the server nodes and set them up
    -l|--local       Configure confluent only on the local system.
                     The default goes down to all the confluent instances on
                     the server nodes and set them up
    -d|--delete      Conserver has the relevant entries for the given noderange removed immediately from configuration
    -h|--help        Display this usage statement.
    -V|--verbose     Verbose mode.
    -v|--version     Display the version number.

Make a minor change to xCAT-server/lib/xcat/plugins/confluent.pm to correct the usage text from "makeconfluentcf" to "makeconfluentcfg".
(Verified the problem exits in the latest source).

**Comment by immarvin** [comment]
hi @jjohnson42 ,would you please take a look at this?
