### ISSUE TITLE
[FVT]:add -V in rflash help and manpage in python version

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#4758]
We don't have -V options in help and manpage in python version but in fact we support this option. Please add it in the help and manpage. Thanks!

**Comment by zet809** [comment]
Hi, @tingtli , It seems the [-V|--verbose] is in bad format for xCAT usage and manpage. Suggest to switch this defect to be a general one to fix in the future.  
For xCAT command, we shall support [-V|--verbose] for all the commands.

**Comment by tingtli** [comment]
@zet It's hard to trace if we open a defect for all the xcat commands. And I don't think it is missed for all the commands. Let's just open for specific command. For rflash , i think it is fixed.
