### ISSUE TITLE
[fvt] pegas1.1 failed to be installed in kvm environment

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4762]
pegas1.1 (``RHEL-ALT-7.5-20180110.1-Server-ppc64le-dvd1.iso``) failed to be installed in kvm environment. Depending on the result of automation test, it can be installed in P9 physical machine. 
Log this ticket to trace this problem.

**Comment by zet809** [comment]
Setup mid05tor12cn02 to be hypervisor with pegas1.0+rhv4.2 beta, pegas1.1 beta can be installed the the VMs created on it.

**Comment by immarvin** [comment]
hi @hu-weihua , consider comment from @zet809 , should this ticket be closed?

**Comment by hu-weihua** [comment]
ok. thanks @zet809 @immarvin
