### ISSUE TITLE
[FVT]: Should --delete option be used for the firmware in active(*) state?

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#4770]
In the manpage of rflash, the explanation of --delete option is as follows:

```
   --delete:

       This delete option will delete update image from BMC. It expects an ID as the input.
``` 

Since the Image_ID is in active (*) state,that means this image is currently used by bmc/host.  I think we should assume users don't want to delete it.  The option should be used for the image_ID in not active (*) state, such as ready or active state.

**Comment by gurevichmark** [comment]
User should receive an error when attempting to delete an active image.
I think it is better to report the error to the user that way, instead of trying to describe the rules for a valid image ID to delete.

**Comment by tingtli** [comment]
Yes. When users use --delete for the active image, there returns error message to prohibit users to do that.

**Comment by gurevichmark** [comment]
Ok, in that case, since users will see an error message, I feel there is no need to update man page and this issue can be closed.

**Comment by whowutwut** [comment]
@tingtli What is your expected behavior here? Just that the man page should indicate that only images that are not active should be specified.  I agree if the error message comes out, that should be OK to keep the doc generic.

**Comment by tingtli** [comment]
@whowutwut My expect behavior here is when user uses --delete option for the active image, we should prohibit user to do that and give a warning message to users.

**Comment by whowutwut** [comment]
@tingtli  I'm not sure if this is what you mean by creating this issue, but you need to show the output of the problem in the description!  😄 @gurevichmark did we not try this?  Or maybe something broke.....

I thought there was an error message printed and didn't understand why you were replying with the response you had, so i went to try it out to paste in the error message... 

```
[root@briggs01 ~]# rflash mid05tor12cn05 -l
mid05tor12cn05: ID       Purpose State      Version
mid05tor12cn05: -------------------------------------------------------
mid05tor12cn05: df4b8673 Host    Active     IBM-witherspoon-ibm-OP9_v1.19_1.90
mid05tor12cn05: f57b7b1b BMC     Active     ibm-v2.0-0-r26-0-g7285b52
mid05tor12cn05: 1829bcbd Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.119
mid05tor12cn05: a419ff24 BMC     Active(*)  ibm-v2.0-0-r26.1-0-gfb7714a
mid05tor12cn05:
[root@briggs01 ~]# rflash mid05tor12cn05 --delete 1829bcbd
Attempting to delete ID=1829bcbd, please wait...
mid05tor12cn05: Firmware removed
```
What ☝️?!?!


[root@briggs01 ~]# rflash mid05tor12cn05 -l
mid05tor12cn05: ID       Purpose State      Version
mid05tor12cn05: -------------------------------------------------------
mid05tor12cn05: df4b8673 Host    Active     IBM-witherspoon-ibm-OP9_v1.19_1.90
mid05tor12cn05: f57b7b1b BMC     Active     ibm-v2.0-0-r26-0-g7285b52
mid05tor12cn05: 1829bcbd Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.119
mid05tor12cn05: a419ff24 BMC     Active(*)  ibm-v2.0-0-r26.1-0-gfb7714a
mid05tor12cn05:
```

So this is a bug...  @gurevichmark Can you look into this?

**Comment by whowutwut** [comment]
Discussion with firmware team about this, I thought this was working at some point where it was not returning a success 200 OK ... but I'm not 100% sure...

**Comment by gurevichmark** [comment]
Block user from issuing a `--delete` action to `active` Host FW if host is not powered off. Deleting `active` FW on powered off host should be allowed.

**Comment by zet809** [comment]
hi, @gurevichmark , have this  issue been fixed? If yes, pls set label and have owner verify it. Thx!

**Comment by gurevichmark** [comment]
Didn't have time to fix it in 2.13.11. Moving to 2.14.

**Comment by gurevichmark** [comment]
Error message that will be displayed:
```
Error: Deleting currently active firmware is not supported
```

**Comment by gurevichmark** [comment]
Perl version implemented in #4953

**Comment by tingtli** [comment]
verified with 2.14 4/3 build. It is fixed.
```
[root@boston02 ~]# rflash mid08tor03cn01 -l
mid08tor03cn01: ID       Purpose State      Version
mid08tor03cn01: -------------------------------------------------------
mid08tor03cn01: 25a5c3e0 Host    Active(*)  IBM-witherspoon-ibm-OP9-v1.21.2-2.6
mid08tor03cn01: 84fb16be BMC     Active(*)  ibm-v2.1-215-g6e7eacb-r2-0-gecb3626
mid08tor03cn01: 78d09908 BMC     Active     ibm-v2.0-0-r44-0-g843c2e1
mid08tor03cn01: 4f901d3d Host    Active     IBM-witherspoon-ibm-OP9_v1.19_1.154
mid08tor03cn01:
[root@boston02 ~]# rflash mid08tor03cn01 84fb16be --delete
Attempting to delete ID=84fb16be, please wait...
mid08tor03cn01: Error: Deleting currently active BMC firmware is not supported
[root@boston02 ~]# rflash mid08tor03cn01 25a5c3e0 --delete
Attempting to delete ID=25a5c3e0, please wait...
mid08tor03cn01: Error: Deleting currently active firmware on powered on host is not supported
```

**Comment by tingtli** [comment]
Test case is in https://github.com/xcat2/xcat-core/pull/5161
