### ISSUE TITLE
[OpenBMC] Additional support needed to enable NTP time server sync in BMC

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4771]
Issue https://github.com/xcat2/xcat-core/issues/4472 initially added the ability to set/get a list of NTP servers for the BMC to configure and sync time against. 

Are we are testing this, turns out there are some issues that cause this to not work.  Lack of documentation here: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Time 

What we have found out in the last few days: 
* For the settings to be applied, the HOST needs to be power cycled https://github.com/openbmc/phosphor-time-manager#special-note-on-host-on
* The Sync Method needs to be manually set to NTP
```
curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X PUT \
-d '{"data": "xyz.openbmc_project.Time.Synchronization.Method.NTP" }' \
https://$BMCIP/xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod
```
* Still some FW issues exists because it seems like `/etc/systemd/timesyncd.conf` is not modified by any of the RestAPI commands and needs to be restarted for the NTP to sychronize. 
Internal Issue: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW415613

It seems like from xCAT's perspective, the following should be done. 
1. `rspconfig <noderange> time_sync_method=NTP`
2. `rspconfig <noderange> ntpservers=IP1,IP2,etc`
3. Something needs to be fixed on the BMC to set this correctly and restart timesyncd (pending response from FW team)
4. Then power cycle the host for it to apply...

We did see that rebooting the bmc seems to sync up the time, but need to gather the output of `timedatectl status` and `journalctl` to see if we actually sync'ed with a time server or not

**Comment by whowutwut** [comment]
After flagging this, the Firmware team debugged and found an issue where the systemd was not reloading to pick up the changes for ntpservers: 
https://github.com/openbmc/openbmc/issues/2859

**Comment by whowutwut** [comment]
GitHut automatically closing issue, i should have tagged it differently in the pull request, let me keep this open until we resolve the issues on the FW side and it's properly tested.

**Comment by whowutwut** [comment]
@gurevichmark Can you look at this. With 1742Fx-r2 driver, setting NTP servers will cause `systemd-networkd` to restart on the BMC and will reload the NTP server setting. 

However, the power needs to be off on the host for this to apply.  

So can you come up with a plan to address this?

**Comment by gurevichmark** [comment]
Email sent to Lei Yu to check what happens is host is on whole ntp is set and host is then rebooted.

**Comment by gurevichmark** [comment]
Answer from Lei Yu: "Changes are deferred and are applied when the host is powered off "
Suggestion to display a message when user changes NTP servers: `rspconfig <noderange> ntpservers=xxx`

**Comment by whowutwut** [comment]
Closing, the msg change has been implemented.
