### ISSUE TITLE
kvm plugin bug: RMVM hangs on missing volume.

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4777]
xCAT version:
```[samveen@xcatmn ~]$ lsxcatd -t
This is a Management Node
[samveen@xcatmn ~]$ lsxcatd -v
Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)
```

We have some xCAT managed VMs (KVM type) that we initially provisioned using default disk format (QCOW2), but which were then manually migrated to use RAW disks. However, the storage pool on the kvm host was not updated when this was done.

This leads to the issue that when `rmvm` was invoked with `-p`, the` rmvm` command hangs after issuing the following alert:

```
[samveen@xcatmn ~]$  rmvm -p randomvm
Error: kvm plugin bug, pid 5996, process description: 'xCATd SSL: rmvm to randomvm for samveen@localhost: kvm instance' with error 'libvirt error code: 50, message: Storage volume not found: no storage vol with matching path '/data/vms/randomvm.vda.raw'
' while trying to fulfill request for the following nodes: randomvm
```
The following ssh process spawned by the KVM plugin shows up as hung:
```
[samveen@xcatmn ~]$ ps -ef |grep ssh |grep kvm1 |grep -v screen
root      8322  8321  0 10:39 ?        00:00:00 ssh -l root -T -o BatchMode=yes -e none kvm1 sh -c 'if 'nc' -q 2>&1 | grep "requires an argument" >/dev/null 2>&1; then ARG=-q0;else ARG=;fi;'nc' $ARG -U /var/run/libvirt/libvirt-sock'
```

I can unwind the hanging process by logging into the kvm host `kvm1` ,and searching for `nc` and killing it:
```
[root@kvm1 ~]# ps -ef |grep '\<nc\>' |grep -v color
root      8305  8301  0 10:39 ?        00:00:00 sh -c if nc -q 2>&1 | grep "requires an argument" >/dev/null 2>&1; then ARG=-q0;else ARG=;fi;nc $ARG -U /var/run/libvirt/libvirt-sock
root      8316  8305  0 10:39 ?        00:00:00 nc -U /var/run/libvirt/libvirt-sock
[root@myasclivekvm2.sgdc ~]# kill 8316
[root@myasclivekvm2.sgdc ~]# ps -ef |grep '\<nc\>' |grep -v color|wc -l
0
```

The bug may have been fixed in more recent versions of xCAT, but as I am unsure, I am opening one anyway.

**Comment by gurevichmark** [comment]
@samveen When the migration from .qcow2 to .raw was done, was .qcow2 file removed ?
Was anything in the xcat definition of that vm changed at that time ?
Was anything in the kvm_nodedata table changed at that time ?

**Comment by samveen** [comment]
@gurevichmark 
1. we have `persistkvmguests=yes` set for our site.
2. The changes were made in the domainxml on the KVM server via `virsh edit`
3. The qcow2 file was removed.

The following items were **_not_** done and **should HAVE been done**:
1. Create a new entry for the raw file in the storage pool
2. Remove the qcow2 entry from the storage pool.

The lack of the correct entry in the storage pool is what triggered this issue.

**Comment by gurevichmark** [comment]
I think what is happening here is this:

a. When `rm -p` is specified, we extract the .qcow2 disk entries from kvm_nodedata entry for the vm. 
b. For each such entry we call virsh function  `get_storage_volume_by_path()` to check if the disk is still there.
c. If true is returned we call virsh function volume->delete().

Since the removed qcow2 entry was not removed from the storage pool, step (b) above most likely returns true and we proceed to step (c). Step (c) fails with the error reported in this issue, but xCAT code should do a more graceful exit in this situation.
