### ISSUE TITLE
Some question about the behavior of go-xcat and whether it should overwrite existing repo config for xCAT

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4785]
Currently the repo configuration for xCAT is incorrect on my MGMT node, was trying to use `go-xcat` to fix it...

```
[root@briggs01 yum.repos.d]# ls -ltr
total 32
-rw-r--r-- 1 root root  358 Dec 27 03:11 redhat.repo
-rw-r--r-- 1 root root  212 Dec 27 06:29 centos.repo.disable
-rw-r--r-- 1 root root  314 Jan  2 02:34 bazel.repo.disable
-rw-r--r-- 1 root root  176 Jan  5 02:37 xcat-ai-temp.repo.disable
drwxr-xr-x 2 root root 4096 Jan 16 21:23 bak
-rw-r--r-- 1 root root  136 Jan 24 01:13 xCAT-core.repo
-rw-r--r-- 1 root root  137 Jan 24 01:16 kernel.repo.bak
-rw-r--r-- 1 root root  205 Jan 24 01:36 local-repository-0.repo
```

Using `go-xcat --xcat-version devel update/install` does not modify the repo to make things work.... 

I have to remove xCAT-core.repo in order for it to work....

Two questions that I have:
1. If go-xcat creates repo files in lower case, xcat-core.repo and xcat-dep.repo, why are we looking at xCAT-core.repo 
2. Should we take the hit and change the xCAT-core.repo and xCAT-dep.repo to lower case? 
3. Should running `go-xcat` re-write the repo files to do what we want it to do on the command line?

**Comment by neo954** [comment]
Once I explained the consideration of this design in issue #1618.

> ... xCAT shipped with different spelling across difference place. xCAT use `xCAT-core.repo` to named the repo file, but the name of repo is actually `xcat-2-core`. And the subdirectory was named `xcat-core` or `core-snap`.

And for Ubuntu, the name of repo file is `xcat-core.list`.

See the table below for a quick summary.

| Packaging | Filename | Name of repo | Name of subdirectory |
| ---- | ---- | ---- | ---- |
| RPM | `xCAT-core.repo` | `xcat-2-core` | `xcat-core` or `core-snap` |
| DEB | `xcat-core.list` | N/A | `xcat-core` or `core-snap` |

In `go-xcat`, everything is renamed to `xcat-core`. It makes the design simple and clear. And get consistency across different Linux distributions.

**Comment by neo954** [comment]
In pull request #4991, there is a patch https://github.com/xcat2/xcat-core/pull/4991/commits/54c0634a29f51ef23c0b9ff2692645fb9a9a1a00.

**Comment by hu-weihua** [comment]
@whowutwut, could you help to verify the patch? thanks

**Comment by whowutwut** [comment]
I have provisioned a few VMs using go-xcat and also install from source... it looks good...

go-xcat only
```
fs2vm112: -rw-r--r--. 1 root root 215 Mar 14 16:42 local-repository-0.repo
fs2vm112: -rw-r--r--  1 root root 358 Mar 14 18:53 redhat.repo
fs2vm112: -rw-------  1 root root 204 Apr  3 14:40 xcat-core.repo
fs2vm112: -rw-------  1 root root 118 Apr  3 14:40 xcat-dep.repo
```

install source, 2.13.11 and then update with go-xcat
```
fs2vm115: -rw-r--r--. 1 root root 215 Mar 14 16:46 local-repository-0.repo
fs2vm115: -rw-r--r--  1 root root 358 Apr  4 13:57 redhat.repo
fs2vm115: -rw-r--r--  1 root root 162 Apr  4 14:17 xCAT-core.repo.nouse
fs2vm115: -rw-r--r--  1 root root 154 Apr  4 14:30 xcat-core.repo
fs2vm115: -rw-r--r--  1 root root 179 Apr  4 14:39 xCAT-dep.repo.nouse
fs2vm115: -rw-r--r--  1 root root 179 Apr  4 16:10 xCAT-dep.repo
fs2vm110: total 8
```

This looks good, thanks @neo954
