### ISSUE TITLE
[CI] is possible to add the check for missing milestones in the Pull requests?

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4787]
from @whowutwut 
```
Please run this query and take a look if you are the owner or the person who merged the PR 
and set milestones/labels as best you can, I would like this to become better habit, 
 https://github.com/xcat2/xcat-core/issues?utf8=%E2%9C%93&q=+no%3Amilestone+is%3Aclosed+  , 
it is very useful to have issues and pull requests tagged correctly
```

is it possible to add the check in CI?

**Comment by hu-weihua** [comment]
Have implemented in pull request #4825, @immarvin could you verify it and close this issue? thanks

**Comment by samveen** [comment]
@hu-weihua @immarvin @whowutwut The problem with milestone checking is that for a newly created pull request, there is no Milestone or Label set on it. That means that _every new_ PR **will fail** the travis check.
Can you please review this change again?

**Comment by whowutwut** [comment]
@hu-weihua I would agree here,  it seems like all the PR that we are creating will fail the TravisCI and we have to close/re-open..  so I'm not sure this is a good place to put that test.

**Comment by hu-weihua** [comment]
@samveen @whowutwut , How about change ``error`` to ``warning``? i.e. If a new PR without Labels or Mileshone, CI report will include a warning message, but do not stop the following test. If customers found such warning, they can add Labels or Milestone later without triggering test again. what do you think?

**Comment by samveen** [comment]
@hu-weihua Yeah, that should be fine, reducing false positives for CI.
