### ISSUE TITLE
Create better message detecting invalid node names?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4792]
Opening as a usability issue, wondering if we can better detect this and provide a better message to the user? 

Trying to create a node definition with the following: 
```
c100.domain.com:
    objtype=node
    groups=mm
    mgt=blade
    mpa=c100u01.domain.com
```

Results in:
```
[root@briggs01 ~]# cat test.stanza  | mkdef -z
Error: The object name 'c100.domain.com' is invalid, please refer to "man xcatdb" for the valid "xCAT Object Name Format"
```

The reason is that there's a domain here, is there a way we could better inform the user of the problem.  Or update the man page to state that domains are not allowed as an xCAT node definition. 

Suggestion, something like:

```
[root@briggs01 ~]# cat test.stanza  | mkdef -z
Error: The object name 'c100.domain.com' is invalid.  Cannot use '.' in node name.  
``` 

If this could be a quick check, could help new users figure out what is wrong quicker.

**Comment by cxhong** [comment]
looks like we do supports "." in the node name before this PR https://github.com/xcat2/xcat-core/pull/2114
````
[root@prh03 tmp]# lsdef | grep ibm.com
c10f2bc2mm1.pok.stglabs.ibm.com  (node)
c10f2bc3mm1.pok.stglabs.ibm.com  (node)
c10f2bc4mm1.pok.stglabs.ibm.com  (node)
c11bc1mm1.pok.stglabs.ibm.com  (node)
c11bc2mm1.pok.stglabs.ibm.com  (node)
c11bc3mm1.pok.stglabs.ibm.com  (node)
c11bc4mm1.pok.stglabs.ibm.com  (node)
c12hmc1.pok.stglabs.ibm.com  (node)
`````
should we add this support back in?

**Comment by immarvin** [comment]
@cxhong , I remember that allow "." in node name might cause some issue so we prohibited this, cannot recall the details on this

**Comment by zet809** [comment]
hi, @bybai , seems '.' in node name will cause DNS report wrong short or long name. So, pls take a look at this issue. Thx!

**Comment by bybai** [comment]
Will look into this later. Thanks @zet809
