### ISSUE TITLE
libnss_dns missing from genesis

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4804]
Hi!

It looks like `libnss_dns` is missing in the RHEL 7.4 genesis environment. This prevents proper hostname resolution using DNS within genesis, and could result in deployment failures.

`libnss_files` is there, so name resolution from `/etc/hosts` works, but for anything else, DNS name resolution fails.

Could you please consider adding it?

Thanks!

**Comment by zet809** [comment]
Rebuild xCAT-genesis-base-ppc64 and xCAT-genesis-base-x86_64 to include libnss_dns. The package will be available next Monday.

**Comment by hu-weihua** [comment]
@kcgthb, could you help to verify and close this issue? thanks

**Comment by kcgthb** [comment]
Hi @hu-weihua 

Sure! What RPM version is the fix available in?

**Comment by hu-weihua** [comment]
Hi @kcgthb, you can download the latest xcat-dep package from http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201804041617.tar.bz2 , then you will find below 2 new genesis RPMs which include the fix.

```
xcat-dep/xCAT-genesis-base-ppc64-2.14-snap201804041553.noarch.rpm
xcat-dep/xCAT-genesis-base-x86_64-2.14-snap201803282249.noarch.rpm
```

**Comment by neo954** [comment]
This issue is verified with the latest build. I will close this one.
