### ISSUE TITLE
xcat dependancies repo not correct 

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#4814]
When obtaining the packages to make a local repo, the dependancies repo list is not created correctly.
I have to manually delete the `repodata` folder located at 
`xcat.org/files/xcat/repos/yum/2.13/xcat-dep/rh7/ppc64/`
and create a new one using `createrepo .`

**Comment by immarvin** [comment]
hi @moralesj , have you tried to download the xcat-dep tarball under http://xcat.org/files/xcat/xcat-dep/2.x_Linux/, then uncompress it as the repo?

**Comment by moralesj** [comment]
No, I usually just do 
`wget -r -np --no-check-certificate  http://xcat.org/files/xcat/repos/yum/devel/core-snap`

**Comment by neo954** [comment]
@moralesj, I cannot recreate your problem. Can you post some detail information, like error messages?

**Comment by neo954** [comment]
I will close this issue.

Please do not hesitate to reopen this issue if there is any question.
