### ISSUE TITLE
copycds with `rhels7` in the name string does not correctly assign the default template --> Pane is Dead

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4819]
Need to fix this.... here's an example: 

```
[root@fs2vm110 tools]# copycds -n "rhels7.4-pegas1.0GA_SP1" /mnt/xcat/iso/pegas/ALT-7.5-Snapshot-2/RHEL-ALT-7.5-20180201.1-Server-ppc64le-dvd1.iso
Copying media to /install/rhels7.4-pegas1.0GA_SP1/ppc64le
Media copy operation successful
```

The name of the image has `rhels7` in it, but yet we don't detect the correct default template file: 

```
[root@fs2vm110 tools]# lsdef -t osimage rhels7.4-pegas1.0GA_SP1-ppc64le-install-compute -i template
Object name: rhels7.4-pegas1.0GA_SP1-ppc64le-install-compute
    template=/opt/xcat/share/xcat/install/rh/compute.tmpl
```

Resulting in the `Pane is dead` message when trying to provision this node.   It should have defauled to use the `compute.rhels7.tmpl` file. 

I've tried to address this using #3262 but it failed some UT regression since it hits a lot of osimage paths, need someone to continue that do we can autodetect osimage regardless of the name provided with `-n` 

Not giving a `-n` option does allow the copycds to detect the correct os... 
```
[root@fs2vm110 tools]# copycds /mnt/xcat/iso/pegas/ALT-7.5-Snapshot-2/RHEL-ALT-7.5-20180201.1-Server-ppc64le-dvd1.iso
Copying media to /install/rhels7.5-alternate/ppc64le
Media copy operation successful

[root@fs2vm110 tools]# lsdef -t osimage -o rhels7.5-alternate-ppc64le-install-compute -i template
Object name: rhels7.5-alternate-ppc64le-install-compute
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
```

**Comment by gurevichmark** [comment]
The problem seems to be the second `.` in the specified name `-n "rhels7.4-pegas1.0GA_SP1"`
In get_file_name() inside SvrUtils.pm, we do:
```
 my $dotpos = rindex($os, ".");
 my $osbase = substr($os, 0, $dotpos);
```
to get $osbase name.
The second dot, causes us to get `$osbase=rhels7.4-pegas1` instead of intended `$osbase=rhels7`

**Comment by immarvin** [comment]
hi @whowutwut , how do you expect copycds to determine the right template? from substring in the specified `-n` option "rhels7.4-pegas1.0GA_SP1"? or from the `.discinfo` under the ISO like the code logic without `-n`?

**Comment by whowutwut** [comment]
@immarvin In the pull request https://github.com/xcat2/xcat-core/pull/3262 if i remember correctly, I go into the .discinfo and extract the release.  This way the -n can be any text that the user wants to specify and we don't need to parse it.. we rely on what we can determine from the .dicsinfo. 

But that pull request did not pass all the regression testing on the sandbox, so I haven't taken a look at it since.  But I think here, @gurevichmark fixed the issue where if there are multiple `.` in the name string, we don't detect the correct OS.
