### ISSUE TITLE
in xcat 2.9.2 chdef -t group -o oldgroupname -n newgroupname doesn't work

### ISSUE THREAD

**Issue by dletai** [xcat2/xcat-core#482]
Trying to modify a group name (the group itself, not the members) result in the message
"Changed the object name from oldgroupname to newgroupname."
However, lsdef on either the new groupname or member nodes shows only the old name, returning an error for the new name.

How to reproduce:
1. chdef -p -t node -o node01 groups="old"
2. chdef -t group -o old -n new

trying to verify
1. lsdef -t group -o new
2. lsdef -t node -o node01 -i groups

The group always remains old.

Workaround:
Add the node to new group, delete the old group:
1. chdef -p -t node -o node01 groups="new"
2. chdef -m -t node -o node01 groups="old"

**Comment by bybai** [comment]
@dletai thanks your pointing this out.

**Comment by daniceexi** [comment]
@dletai 
The group object is a dynamic value from the nodes definition, so generally we can not change the group list for nodes through change the group object name. That means xcat did not attend to support this functionality.

@bybai We need to add some description for this limition in the man page.
The '-n' flag for
