### ISSUE TITLE
error message improvement when adding users in hierarchical configuration

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#4820]
Problem statement: error message when adding xdsh capabilities, does not reveal that the user is missing from the service nodes, in this hierarchical configuration.

Use case: A user was added to the primary xCAT server, and granted initial ability to open a node console.
> run '/opt/xcat/share/xcat/scripts/setup-local-client.sh ccuser' as 'root' to generate the client certificates
Then the policy table was updated for this local user to do xCAT commands, which included xdsh.
> chdef -t policy -o 5.7 name=ccuser commands=nodels,rpower,lsdef,xdsh rule=allow
A postscript is run to add the user to the compute nodes, and ssh, nodels, rpower, all are tested and work.  Finally, I attempted to add xdsh capability.
> xdsh cn01 -K
...
> Error: xdsh plugin bug, pid 68135, process description: ‘xcatd SSL: xdsh: xdsh instance’ with error ‘cannot open file /.ssh/copy.sh
> ’ while trying to fulfill request for the following nodes: cn01

The root cause of the error was that xdsh, unlike ssh, was attempting to route through the service node (by design).  I had neglected to add the user and  sync the /etc/passwd files to the service nodes.

This issue request is to remove the plugin bug message and have some better message to figure out where the error is coming from, if it's MGMT node or SN.  Otherwise it's quite difficult to pinpoint the error.

documentation reference for this user scenario:
http://xcat-docs.readthedocs.io/en/stable/advanced/security/security.html

**Comment by marksmit-ibm** [comment]
After creating the user in SN's and on a target compute, cn12, (and syncing /etc/passwd with SN),
I then re-attempted on the newly created user.   
(0) root @ xcat1: /etc
# su - ccuser
Last login: Fri Feb  9 13:26:17 CST 2018 on pts/7
[ccuser@xcat1 ~]$ xdsh cn12 -K
Enter the password for the userid: ccuser on the node where the ssh keys 
will be updated:

Error: Command failed:  cp /home/ccuser/.ssh/authorized_keys /home/ccuser/.ssh/tmp/authorized_keys 2>&1. Error message: cp: cannot stat '/home/ccuser/.ssh/authorized_keys': No such file or directory.

Error:  cp /home/ccuser/.ssh/authorized_keys /home/ccuser/.ssh/tmp/authorized_keys failed.

Error: Failed to copy ssh credentials and helper script to cn12: 3:Child PID 76629 exited with status 256
Error: SSH setup failed for the following nodes: cn12.
return code = 1
[ccuser@xcat1 ~]$ ssh cn12
ccuser@cn12's password: 
[ccuser@cn12 ~]$ ls -al
total 256
drwx------ 3 ccuser ccusers 140 Feb  9 19:31 .
drwxr-xr-x 6 root   root    320 Feb  8 22:21 ..
-rw-r--r-- 1 ccuser ccusers  18 Aug  3  2017 .bash_logout
-rw-r--r-- 1 ccuser ccusers 193 Aug  3  2017 .bash_profile
-rw-r--r-- 1 ccuser ccusers 231 Aug  3  2017 .bashrc
-rw-r--r-- 1 ccuser ccusers 172 Feb 10  2017 .kshrc
drwx------ 2 ccuser ccusers 100 Feb  9 19:35 .ssh
[ccuser@cn12 ~]$ ls -al .ssh
total 192
drwx------ 2 ccuser ccusers  100 Feb  9 19:35 .
drwx------ 3 ccuser ccusers  140 Feb  9 19:31 ..
-rw------- 1 ccuser ccusers  940 Feb  9 19:35 authorized_keys
-rw------- 1 ccuser ccusers 1679 Feb  9 19:35 id_rsa
-rw------- 1 ccuser ccusers  405 Feb  9 19:35 id_rsa.pub
[ccuser@cn12 ~]$ cat .ssh/authorized_keys 
cat: /tmp/ccuser/.ssh/authorized_keys: No such file or directory
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGPVmgZqxJ3U7V/PNgmyAsb6fwB9Yk43axm8XOSW+SV5/k9puduZadIlbLdS+GicHOTnV1sYHHBXXI8opUTXYfdRPSOXPR2vj9yLumpVJ0AekiSUqsK8SGILgYZ8QbPiILVWkXk5VosFk4X9r1YDl4xToqucLfpqiJlnMdTP/ozitQuP3YdHet3Pj0hizQcPb7qSJdEWWJ74fCCs3KP89uEo5TH2s3HTEFqD0woNPqMR5DiTGRQzF7DSCQ93W84vgSDFPfYj1DORU+M/nvyto48Et6GdmvFnr+YOrUoXkRZYiQn/QE9ONBXHpg9Qx6lFJgKBtLUk+5OD1G5ZnJ/kRH ccuser@sn02.hst.ibm.net
cat: /tmp/ccuser/.ssh/authorized_keys: No such file or directory
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGPVmgZqxJ3U7V/PNgmyAsb6fwB9Yk43axm8XOSW+SV5/k9puduZadIlbLdS+GicHOTnV1sYHHBXXI8opUTXYfdRPSOXPR2vj9yLumpVJ0AekiSUqsK8SGILgYZ8QbPiILVWkXk5VosFk4X9r1YDl4xToqucLfpqiJlnMdTP/ozitQuP3YdHet3Pj0hizQcPb7qSJdEWWJ74fCCs3KP89uEo5TH2s3HTEFqD0woNPqMR5DiTGRQzF7DSCQ93W84vgSDFPfYj1DORU+M/nvyto48Et6GdmvFnr+YOrUoXkRZYiQn/QE9ONBXHpg9Qx6lFJgKBtLUk+5OD1G5ZnJ/kRH ccuser@sn02.hst.ibm.net
[ccuser@cn12 ~]$ 

It seems to me we still have a functional problem with `xdsh cn12 -K` on the initial instance.

**Comment by immarvin** [comment]
hi @marksmit-ibm , for  hierarchy cluster, I think you need run `xdsh -K ` against the service node first, then run `xdsh -K ` against the compute nodes served by it.

From the information you provided, `Error: Command failed: cp /home/ccuser/.ssh/authorized_keys /home/ccuser/.ssh/tmp/authorized_keys 2>&1. Error message: cp: cannot stat '/home/ccuser/.ssh/authorized_keys': No such file or directory.` , it means that `/home/ccuser/.ssh/authorized_keys` does not exist on the Service Node, which is created by `xdsh -K`.

I created a hierarchy cluster to go through the steps for setting up password-less ssh today,  write them down here as a reference:
1) on MN with "root", create user "immarvin" by `useradd immarvin`, set password by `echo immarvin:cluster|chpasswd`, grant the permission of `xdsh` for "immarvin" in policy table, generate SSL credentials `/opt/xcat/share/xcat/scripts/setup-local-client.sh immarvin`
2)on MN with "root",  create user "immarvin" on SN by running `xdsh <SN s> "useradd immarvin; echo immarvin:cluster|chpasswd"` 
3) on MN with "root",  create user "immarvin" on CN by running `xdsh <CN s> "useradd immarvin; echo immarvin:cluster|chpasswd"` 
4) change to  user `immarvin` by running `su immarvin` on MN
5) setup ssh keys on SN by `xdsh <SN s> -K` with "immarvin"
6) setup ssh keys on CN by `xdsh <CN s> -K` with "immarvin"

**Comment by immarvin** [comment]
A PR is created to refine the message more informative: https://github.com/xcat2/xcat-core/pull/4822

**Comment by marksmit-ibm** [comment]
Thank you for the tip.  That did solve my setup problem:
$ xdsh service -K
/usr/bin/ssh setup is complete.
return code = 0

$ xdsh cn09 -K
/usr/bin/ssh setup is complete.
return code = 0
