### ISSUE TITLE
Can't PXE boot nodes after deployment in UEFI mode

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#4830]
Hi!

To follow up on #4824, I can't seem to make nodes PXE boot after deployment if they configured in UEFI mode. I'm trying to deploy diskfull Dell PowerEdge servers (Rx30s and C6320s) via PXE in UEFI
boot mode, without success.

The servers PXE-boot just fine when configured in BIOS boot mode, but switching to UEFI apparently makes the initial DHCP request timeout, and generate a PXE-E18 Server Response Timeout error.

Looking at the network traffic, I see just 2 DHCP frames in the initial exchange:
1. DHCP Discovery from the server
2. DHCP Offer from the DHCP/TFTP server

And then nothing else, as if the PXE-booting node never received the DHCP Offer, or at least didn't act on it.

Again, the exact same setup works flawlessly when the PXE-booting node is in BIOS boot mode. And deployment (via `rinstall`) starts and runs fine in either mode, BIOS or UEFI.

To sum up:
* **CN in BIOS mode**: initial deployment works, next PXE boot after deployment works, falls back to the local disk works, OS boots fine
* **CN in UEFI mode**: initial deployment works, next PXE boot after deployment hangs (PXE-E18 Server Response Timeout error).

Looking at the DHCP lease for that node, I see this:
```
host sh-101-59 {
  dynamic;
  hardware ethernet 7c:d3:0a:c1:6f:88;
  uid 7c:d3:0a:c1:6f:88;
  fixed-address 10.10.101.59;
        supersede server.ddns-hostname = "sh-101-59";
        supersede host-name = "sh-101-59";
        if option user-class-identifier = "xNBA" and option client-architecture
             = 00:00 {
          supersede server.always-broadcast = 01;
          supersede server.filename =
                  "http://${next-server}/tftpboot/xcat/xnba/nodes/sh-101-59";
        } elsif option user-class-identifier = "xNBA" and option
                client-architecture = 00:09 {
          supersede server.filename =
                                      "http://${next-server}/tftpboot/xcat/xnba/nodes/sh-101-59.uefi";
        } elsif option client-architecture = 00:07 {
          supersede server.filename = "xcat/xnba.efi";
        } elsif option client-architecture = 00:00 {
          supersede server.filename = "xcat/xnba.kpxe";
        } else {
          supersede server.filename = "";
        }
}
```

Is there any reason why this could happen?

**Comment by Phhere** [comment]
I think some of my systems have the same problem.

For me there is a workaround:
https://github.com/xcat2/xcat-core/issues/4071#issuecomment-335812282

It replaces exit with sanboot in pxe file, so the server continue with boot from local disk

**Comment by kcgthb** [comment]
Thanks for the suggestion, I'll try it, but I doubt that's exactly the same issue, since in my case, the compute node doesn't even acknowledge the initial DHCP Offer packet, so it doesn't try to download anything form the TFTP server. The timeout occurs before it even downloads the boot file that contains the `exit` directive.

**Comment by immarvin** [comment]
hi @kcgthb ,how did you kick off the provision in UEFI mode? 
you should use `rinstall -u` or 
```
nodeset 
rsetboot compute net -u
rpower boot
```
for uefi mode

Here is some hints on x86 server provision, https://sourceforge.net/p/xcat/wiki/XCAT_iDataPlex_Cluster_Quick_Start/#configure-the-pxe-boot-mode-of-the-node

**Comment by kcgthb** [comment]
Hi @immarvin 

I tried `rinstall -u`, but the behavior is still the same: the node deploys correctly, and then, during the first reboot, it hangs in POST while issuing its DHCP requests, and the PXE boot process fails with "PXE-E18: Server response timeout."

Looking at the traffic between the compute node and the xCAT DHCP server, I can't see any kind of DHCP ACK packet. Here's the full bootp session (PCAP format) if anyone's interested: [UEFI_bootp.pcap.gz](https://github.com/xcat2/xcat-core/files/1748845/UEFI_bootp.pcap.gz)

I guess I'll stick with BIOS mode for now.

**Comment by immarvin** [comment]
hi @kcgthb , regarding the PXE-E18,  not sure whether the issue mentioned in 
https://www.ibm.com/support/home/docdisplay?lndocid=migr-5080390

**Comment by kcgthb** [comment]
Yes, I've seen that issue, which prompted me to try disabling jumbo frames on that network, but without any success. 

Plus those nodes are Dell servers, and it looks like others can PXE boot those same servers in UEFI mode without any problem. This is why I suspected one of the (many) options in the `dhcpd.conf` file, and was wondering if anyone had a similar experience.

**Comment by immarvin** [comment]
hi @kcgthb ,any update on this?

**Comment by kcgthb** [comment]
Unfortunately no, I had to move back to BIOS mode, and haven't found out much more about the EFI DHCP timeouts.

**Comment by kleykenb** [comment]
Think I struggled with this same issues on HPE. The solution was to set netboot=xnba and make sure there are not multiple DHCP leases for the client (you can force this with "makedhcp -n")
