### ISSUE TITLE
Incorrect error message given when creating VM and storage exists 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4831]
@gurevichmark Can you take a look at this? 

Came across this by accident, I thought the `-f` option for rmvm would remove the persistence storage, but it's actually the `-p` option to purge.  

```
[root@c910f02c05p03 ~]# rpower fs2vm113 off
fs2vm113: off
[root@c910f02c05p03 ~]# nodeset fs2vm113 offline
fs2vm113: offline
[root@c910f02c05p03 ~]# rmvm -f fs2vm113
```

Then when I create it: 
```
[root@c910f02c05p03 ~]# mkvm fs2vm113 -s 20G
fs2vm113: Error: Storage creation request conflicts with existing file(s) fs2vm113.sda.qcow2. To force remove the existing storage file, rerun mkvm with the -f option.
```

So this error message doesn't make sense.. at this point, we cannot `rmvm -f` anymore because it's gone. 

I can recover doing:
```
[root@c910f02c05p03 ~]# mkvm fs2vm113
[root@c910f02c05p03 ~]# rmvm -p fs2vm113
[root@c910f02c05p03 ~]# mkvm fs2vm113 -s 20G
```

But when we create a VM, that -s option can't be used because storage is already there. You can't remove storage with -s... so the message is wrong

**Comment by gurevichmark** [comment]
Perhaps the message can be made a little more obvious, but it states to "rerun mkvm with -f", not "rmvm -f". The "mkvm -f" supposed to "If the storage already exists, remove it before creating a new virtual machine."

**Comment by whowutwut** [comment]
@gurevichmark  I see... yes...   I was over thinking this a bit and didn't read the message carefully.
