### ISSUE TITLE
[Customer]xCAT 2.11: CUDA pkglist files do not reference XCATROOT (breaks ospkgs in some cases)

### ISSUE THREAD

**Issue by mfoliveira** [xcat2/xcat-core#484]
Hi,

The ospkgs is broken if an user doesn't set the cuda pkglist as the osimage pkglist
(for example, instead, he includes the cuda pkglist from another pkglist, which is the one set in the osimage).

Example (notice the #INCLUDEBAD string in the middle of the pkg list, which makes the rest of the yum command to become a command, and those commented packages do not get installed.
```
<...> xcat: OSPKGS=wget,ntp,nfs-utils,net-snmp,rsync,yp-tools,openssh-server,util-linux,net-tools,#INCLUDEBAD:cannot open /install/custom/install/rh/compute.rhels7.pkglist#,kernel-de
vel,gcc,pciutils,dkms,cuda,pciutils-libs,pciutils,tcl,tk,tcsh,gcc-gfortran,lsof,libnl,libxml2-python,python-devel,redhat-rpm-config,rpm-build,kernel-devel,gtk2,atk,cairo,ksh
```

It happened because the osimage.pkglist points to a file which #INCLUDEs the cudafull pkglist.

And it turns out the cuda pkglists are among the very few pkglists in /opt/xcat/share/xcat/install/rh/ that do not use XCATROOT to fix that problem. (64 total, 4 do not use XCATROOT, 2 of those 4 are cuda.)

```
[root@xcat-mn ~]# grep -r '#INCLUDE:' /opt/xcat/share/xcat/install/rh/ | wc -l
64

[root@xcat-mn ~]# grep -r '#INCLUDE:' /opt/xcat/share/xcat/install/rh/ | grep -v '#INCLUDE:#ENV:XCATROOT#' | wc -l
4

[root@xcat-mn ~]# grep -r '#INCLUDE:' /opt/xcat/share/xcat/install/rh/ | grep -v '#INCLUDE:#ENV:XCATROOT#'
/opt/xcat/share/xcat/install/rh/storage.tmpl:#INCLUDE:../scripts/pre.rh#
/opt/xcat/share/xcat/install/rh/storage.tmpl:#INCLUDE:../scripts/post.rh#
/opt/xcat/share/xcat/install/rh/cudafull.rhels7.ppc64le.pkglist:#INCLUDE:compute.rhels7.pkglist#
/opt/xcat/share/xcat/install/rh/cudaruntime.rhels7.ppc64le.pkglist:#INCLUDE:compute.rhels7.pkglist#
```

**Comment by mfoliveira** [comment]
Hi @zet809 
Can you take a look / assign this one? 
I guess @whowutwut may be out for the US Holidays.
Thanks!

**Comment by bybai** [comment]
Hi @mfoliveira, We recommend customer use the solution in  our doc: http://xcat-docs.readthedocs.org/en/latest/advanced/gpu/nvidia/osimage/index.html 
So move it into 2.12 to look into.

**Comment by mfoliveira** [comment]
@bybai ok, thanks!

**Comment by daniceexi** [comment]
@mfoliveira Does the new doc in the readthedocs work for this issue?

**Comment by daniceexi** [comment]
@mfoliveira I close this issue first, please reopen this issue if you still have problem.

**Comment by mfoliveira** [comment]
Hi @daniceexi 

Thanks for checking.
The problem would still exist as the file [1] doesn't use the XCATROOT based path.

[1] https://github.com/xcat2/xcat-core/blob/master/xCAT-server/share/xcat/install/rh/cudafull.rhels7.ppc64le.pkglist

**Comment by daniceexi** [comment]
@pdlun92 @cxhong Could one of you take a look of this issue?
