### ISSUE TITLE
verify the kdump on pegas 1.x diskless

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4840]
someone reported kdump does not work for pegas 1.x diskless node, we need to cover this in manual verification, and autotest cases if any

hi @bybai , would you cover this in your manual verification?

hi @hu-weihua , do we have autotest cases for kdump on diskless provision?

thx

**Comment by mattaezell** [comment]
kdump on diskless pegas is working at our site

**Comment by whowutwut** [comment]
@mattaezell Thanks for the confirmation!

**Comment by bybai** [comment]
Hi @mattaezell, 
I tried diskless pegas 1.1, at last, it is working.

**Comment by bybai** [comment]
Hi @mattaezell , thanks your confirmation. 
At last, kdump works in my pegas1.1 beta while I set "crashkernelsize=auto" in diskless osimage definition . I hit problem when I set other value for crashkernelsize, so what is your value for "crashkernelsize" in diskless osimage definition? @mattaezell 

The diskless hang problem : the final vmcore file is 322M, when I set  "crashkernelsize=400M@32M", the system cannot enter diskless,  I tried many values for crashkernelsize, all failed except "crashkernelsize=aoto", the hang as following screem:
```
  System configuration
  System status log
  Language
  Rescan devices
  Retrieve config from URL
  Plugins (0)
 *Exit to shell





 ──────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, g=log, h=help
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[   31.450921] kexec_core: Starting new kernel
[   53.158887351,5] OPAL: Switch to big-endian OS
```

**Comment by belldi** [comment]
Hello @bybai I've been testing kdump on diskless Pegas 1.0 with kernel  4.11.0-44.4.1.el7a.bz162380.7.ppc64le.  Kernel includes patch for Bugzilla 162380.  The attribute crashkernelsize is set to 4 GB (crashkernelsize=4096M).  When I trigger kdump, I see Out of Memory (OOM) errors.  I'll modify the size to from '4096M' to 'auto' to see if this improves things.

**Comment by mattaezell** [comment]
We are using `crashkernel=1024M`

**Comment by belldi** [comment]
I executed kdump test on Feb 23, 2018, for diskless Pegas 1.0 compute node with kernel (4.11.0-44.4.1.el7a.bz162380.7.ppc64le).  I modified attributes 'crashkernelsize' and 'dump' for osimage.  With modifcations, kdump saved to service node <service_node>:/DUMPS/var/crash/.  Modification of attribute crashkernelsize from '4096M' to 'auto' (crashkernelsize=auto) appears to have triggered dump transfer to <service_node>.  Explicit values, such as 4096M, for crashkernelsize are expected to work.

Further testing is required to understand issue.


1. Followed procedure for kdumps at link for xcat readthedocs
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/enable_kdump.html

2. Attributes for dump and crashkernelsize for osimage
# lsdef -t osimage rhels7.4-pegas1.0GA_SP1-ppc64le-netboot-compute-lab12a-kernel4.1.bz162380.7-02-22-2018 -i dump,crashkernelsize
Object name: rhels7.4-pegas1.0GA_SP1-ppc64le-netboot-compute-lab12a-kernel4.1.bz162380.7-02-22-2018
    crashkernelsize=auto
    dump=nfs:///DUMPS

3. Trigger kdump
# echo c > /proc/sysrq-trigger 
[  770.847016] sysrq: SysRq : Trigger a crash
[  770.847053] Unable to handle kernel paging request for data at address 0x00000000
[  770.847156] Faulting instruction address: 0xc000000000769b94
[  770.847248] Oops: Kernel access of bad area, sig: 11 [#1]
[  770.847304] SMP NR_CPUS=2048 
[  770.847305] NUMA 
[  770.847371] PowerNV
.
.
kdump: dump target is <service_node_ip>:/DUMPS
kdump: saving to /sysroot//var/crash/<compute_node_ip>-2018-02-23-19:45:45/
kdump: saving vmcore-dmesg.txt
kdump: saving vmcore-dmesg.txt complete
kdump: saving vmcore
Copying data                       : [100.0 %] \
kdump: saving vmcore complete
.
.

**Comment by belldi** [comment]
I ran another kdump test on Feb 23, 2018, to modify attribute crashkernelsize for osimage.  With osimage attributes' "crashkernelsize=4096M" and "dump=nfs:///DUMPS" I was able to trigger kdump on diskless Pegas 1.0 compute node and kdump saved to /DUMPS/var/crash/ on service node. 



1. Trigger kdump
# date && echo c > /proc/sysrq-trigger 
Fri Feb 23 23:16:17 UTC 2018
[  451.728421] sysrq: SysRq : Trigger a crash
[  451.728481] Unable to handle kernel paging request for data at address 0x00000000
[  451.728591] Faulting instruction address: 0xc000000000769b94
[  451.728679] Oops: Kernel access of bad area, sig: 11 [#1]
[  451.728758] SMP NR_CPUS=2048 
[  451.728759] NUMA 
[  451.728805] PowerNV
.
.
kdump: dump target is <service_node_ip>:/DUMPS
kdump: saving to /sysroot//var/crash/<compute_node_ip>-2018-02-23-23:17:23/
kdump: saving vmcore-dmesg.txt
kdump: saving vmcore-dmesg.txt complete
kdump: saving vmcore
Copying data                       : [100.0 %] \
kdump: saving vmcore complete
.
.


2. Verify kdump saved to service node
# pwd
/DUMPS/var/crash/<compute_node_ip>-2018-02-23-23:17:23

# ls -l
total 1572480
-rw------- 1 root root 1610198047 Feb 23 23:18 vmcore
-rw-r--r-- 1 root root     129560 Feb 23 23:17 vmcore-dmesg.txt

**Comment by bybai** [comment]
My summary:
Pegas1.1 beta Kernel 4.14.0-36.el7a.ppc64le on power9 witherspoon machine with 123G
1, when `crashkernelsize=auto` in diskless osimage, kdump works well.
2, when `crashkernelsize=4196M` in diskless osimage, kdump works well.
3, when `crashkernelsize=4196M@32M`, diskless hang as the following screen:
```
System configuration
  System status log
  Language
  Rescan devices
  Retrieve config from URL
  Plugins (0)
 *Exit to shell





 ──────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, g=log, h=help
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[   31.450921] kexec_core: Starting new kernel
[   53.158887351,5] OPAL: Switch to big-endian OS
```

**Comment by bybai** [comment]
Hi @whowutwut and @immarvin,
Based on https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/kernel_crash_dump_guide/sect-kdump-config-cli, we can enhance our doc about `crashkernelsize` section,  The `crashkernel=` option can be defined in multiple ways. 
`crashkernelsize=auto` or `crashkernelsize=<specific size>M` is more general.
 For some systems, it might be necessary to reserve memory with a certain fixed offset like `crashkernelsize=X@Y` .  But in our doc, there are some examples like, that is not the case:
```
For system p machine, set the crashkernelsize attribute to this:
chdef -t osimage <image name> crashkernelsize=<size>@32M
```

**Comment by belldi** [comment]
I ran another kdump test on Feb 23, 2018, to modify attribute crashkernelsize for osimage.  With osimage attributes' "crashkernelsize=4096M" and "dump=nfs:///DUMPS" I was able to trigger kdump on diskless Pegas 1.0 compute node and kdump saved to /DUMPS/var/crash/ on service node. 



1. Trigger kdump
# date && echo c > /proc/sysrq-trigger 
Fri Feb 23 23:16:17 UTC 2018
[  451.728421] sysrq: SysRq : Trigger a crash
[  451.728481] Unable to handle kernel paging request for data at address 0x00000000
[  451.728591] Faulting instruction address: 0xc000000000769b94
[  451.728679] Oops: Kernel access of bad area, sig: 11 [#1]
[  451.728758] SMP NR_CPUS=2048 
[  451.728759] NUMA 
[  451.728805] PowerNV
.
.
kdump: dump target is <service_node_ip>:/DUMPS
kdump: saving to /sysroot//var/crash/<compute_node_ip>-2018-02-23-23:17:23/
kdump: saving vmcore-dmesg.txt
kdump: saving vmcore-dmesg.txt complete
kdump: saving vmcore
Copying data                       : [100.0 %] \
kdump: saving vmcore complete
.
.


2. Verify kdump saved to service node
# pwd
/DUMPS/var/crash/<compute_node_ip>-2018-02-23-23:17:23

# ls -l
total 1572480
-rw------- 1 root root 1610198047 Feb 23 23:18 vmcore
-rw-r--r-- 1 root root     129560 Feb 23 23:17 vmcore-dmesg.txt

**Comment by bybai** [comment]
@belldi , that's fine, thanks confirmation.
