### ISSUE TITLE
[FVT][OpenBMC] sync up manpage and help information for rbeacon 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#4851]
xCAT 2.13.11. The help information and manpage for rbeacon is not consistent. Please update.

Help information does not have blink option but manpage has. Should we put different hardware type in different option list?
```
[root@briggs01 ltt]# rbeacon -h
Usage: rbeacon <noderange> [on|off|stat] [-V|--verbose]
       rbeacon [-h|--help|-v|--version]
``` 
Here is the manpage
```
SYNOPSIS
       rbeacon noderange {on|blink|off|stat}

       rbeacon [-h|--help]

       rbeacon {-v|--version}
```

**Comment by whowutwut** [comment]
@xuweibj @gurevichmark please coordinate to see which tasks can be split between you, I think this one seemed like it could have been fixed very quickly but maybe was assigned to @xuweibj and sat there for 2 weeks.

**Comment by xuweibj** [comment]
Have fixed in pull request https://github.com/xcat2/xcat-core/pull/4859.

**Comment by tingtli** [comment]
I've verified with xcat 2.14 3/26 build. Close this bug.
