### ISSUE TITLE
[FVT][OpenBMC]should rbeacon have stat option for OpenBMC managed node?

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#4853]
xCAT 2.13.11. rbeacon only has on/off options  on OpenBMC managed node. How could user know the status of the beacon?

```
[root@briggs01 ~]# rbeacon mid05tor12cn05 stat
mid05tor12cn05: Error: Only 'on' or 'off' is supported for OpenBMC managed node
```

**Comment by zet809** [comment]
Hi, @xuweibj , seems we can use rinv, right?

**Comment by xuweibj** [comment]
We can use ``rvitals lads`` to get status.

**Comment by zet809** [comment]
Hi, @tingtli , pls close this issue if `rvitals leds` make sense for you. Thx!

**Comment by daniceexi** [comment]
If the getting LED status is functioning, do we want to make it available in rbeacon command which would make it more sense?

**Comment by whowutwut** [comment]
Yea we might want to have stat reply with the identify light status. @gurevichmark can you take a look?

**Comment by whowutwut** [comment]
Rvitals led reports more than the identify light

**Comment by gurevichmark** [comment]
I think we should add support for `rbeacon stat`. It would be good to display just one line per node with beacon information. `rvitals leds` displays 3 lines:
```
[root@briggs01 ~]# rvitals mid05tor12cn05 leds
mid05tor12cn05: Front . . . . . : Power:On Fault:On Identify:Off
mid05tor12cn05: Front Fans  . . : No LEDs On
mid05tor12cn05: Rear  . . . . . : Power:On Fault:On Identify:Off
[root@briggs01 ~]#
```

**Comment by gurevichmark** [comment]
Our documentation says that `rbeacon stat` and `rbeacon blink` works on IPMI controlled nodes, but it seems we do not have support in our code:
```
[root@briggs01 ~]# rbeacon sn02 stat
sn02: Error: Only 'on' or 'off' is supported for IPMI managed nodes.

[root@briggs01 ~]# rbeacon sn02 blink
sn02: Error: Only 'on' or 'off' is supported for IPMI managed nodes.
[root@briggs01 ~]#
```

Even for fsp and blades (blade.pm) seems like code is missing for `stat`:

```
sub beacon {
    my $subcommand = shift;
    my $data;
    unless ($subcommand) { $subcommand = "stat"; }
    if ($subcommand eq "stat") {
    } elsif ($subcommand eq "on") {
        $data = $session->set(new SNMP::Varbind([ $beaconoid, $slot, 1, 'INTEGER' ]));
    } elsif ($subcommand eq "off") {
        $data = $session->set(new SNMP::Varbind([ $beaconoid, $slot, 0, 'INTEGER' ]));
    } elsif ($subcommand eq "blink") {
        $data = $session->set(new SNMP::Varbind([ $beaconoid, $slot, 2, 'INTEGER' ]));
    } else {
        return (1, "$subcommand unsupported");
    }
```

**Comment by whowutwut** [comment]
@gurevichmark Yes, inconsistency there.  I agree it would be good to show `rbeacon <> state` as a one liner that indicates if the identify light is on or off.

**Comment by tingtli** [comment]
Test with xcat 2.14 3/26 build, it is fixed.
```
[root@briggs01 ~]# lsxcatd -v
Version 2.14 (git commit 3217230d197babb3688fef28f26135fb5e5ad1a1, built Mon Mar 26 06:15:52 EDT 2018)
[root@briggs01 ~]# rbeacon mid05tor12cn05 stat
mid05tor12cn05: Front:On Rear:Off

```

A further question.  when the front is on  and the Rear is off. Which light rbeacon will be applied on?

**Comment by gurevichmark** [comment]
I do not know how cn05 got into this state.
Normally `rbeacon on` should turn both front and rear to "Blink"

**Comment by whowutwut** [comment]
@tingtli  I also do not know what happens to trigger this.  @gurevichmark we should go up to the lab and take a look at what is going on and report this to the FW team.  I have seen also a blue light on in the front and off in the rear, i suspect this is the same issue here and I'm not sure the FW team knows why it gets into this state...

**Comment by tingtli** [comment]
```rbeacon on``` turns both front and rear to "Blink". I have a question. Sometimes, i see Front is On and Rear is off. How could we set that ? We could only use ```rbeacon CN on``` or "rbeacon CN off" to make both front and rear to the same state.

**Comment by zet809** [comment]
It seems the Front and Rear Identify LED not consistent is a firmware/hardware problem can be trace with https://github.ibm.com/vhu/c910env/issues/223 , so let's close this issue.
