### ISSUE TITLE
[FVT] [OpenBMC] rinv return code is not correct in python version

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#4854]
xCAT 2.13.11 The return code is not same for the same command in perl and python version. Please take a look. I think the return code should not be 0 when there is warning message.

Here is the information in python version
```
[root@briggs01 ~]# chdef mid05tor12cn05 bmcpassword=test
1 object definitions have been created or modified.
[root@briggs01 ~]# rinv mid05tor12cn05 all
mid05tor12cn05: Error: [401] Invalid username or password
[root@briggs01 ~]# echo $?
0
```

Her is the information in perl version
```
[root@briggs01 ~]# chdef mid05tor12cn05 bmcpassword=test
1 object definitions have been created or modified.
[root@briggs01 ~]# rinv mid05tor12cn05 all
mid05tor12cn05: Error: [401] Invalid username or password
[root@briggs01 ~]# echo $?
1
```

**Comment by whowutwut** [comment]
Shouldn't the return code be done in the framework so that we exit with or without error and it's not per command basis...

**Comment by whowutwut** [comment]
Also this one: 
```
[root@briggs01 autotest]# export XCAT_OPENBMC_PYTHON=YES
[root@briggs01 autotest]# rpower mid05tor12cn05 bmcstate
mid05tor12cn05: BMC NotReady
[root@briggs01 autotest]# echo $?
0
```

**Comment by gurevichmark** [comment]
There are many places in Python code where **self.messager.info** is used.
Instead we should use **self.messager.error**, this way RC=1 will be set.

However, there is a small problem using **self.messager.error** - it prints "Error:" in front of the passed in text. So we get something like:
```
Error: mid05tor12cn02: BMC did not respond. Validate BMC configuration and retry the command.
```
Instead of what we want:
```
mid05tor12cn02: Error: BMC did not respond. Validate BMC configuration and retry the command.
```

Perhaps part of fixing this issue should be overwriting the default **self.messager.error**, so that "Error:" is displayed after nodename.

**Comment by tingtli** [comment]
I've verified this bug.
```
[root@briggs01 ~]# lsxcatd -v
Version 2.14 (git commit a290387148347ca54c2aaeb67a7023f702731f6b, built Thu Mar 22 06:15:42 EDT 2018)
[root@briggs01 ~]# tabedit site
[root@briggs01 ~]# rinv mid05tor12cn05 all
mid05tor12cn05: Error: [401] Invalid username or password
[root@briggs01 ~]# echo $?
1
```

**Comment by tingtli** [comment]
@whowutwut I don't know how to set bmc to "BMC NotReady" state.  I get nothing when I execute following command
```
[root@briggs01 ~]# rpower mid05tor12cn05 bmcstate
```
Let me know your steps and I will try again.  At the moment. I close this one to indicate the original one is fixed. Let's open a new one if we think rpower is not fixed.
