### ISSUE TITLE
kdump testing on diskless RHEL 7.4 ppc64le (Pegas 1.0) intermittently takes up to 5-6 mins to update nfs path in /etc/kdump.conf

### ISSUE THREAD

**Issue by belldi** [xcat2/xcat-core#4865]
**Problem description**
I'm executing kdump tests on diskless RHEL 7.4 ppc64le (Pegas 1.0) running on Power9 compute node.  I've been referencing the link below to execute kdump tests on Pegas 1.0.  I've been modifying attribute 'dump' for diskless osimage to specify NFS paths.  The default path 'dump=nfs:///DUMPS' saves crash dumps to the primary service node.  However, I've modified 'dump=nfs://<xcat_master_ip>/DUMPS' to save dumps to xcat management node and also used 'dump=nfs://<secondary_service>/DUMPS' to save dumps to the secondary service nodes.  Before executing kdump tests with 'echo c > /proc/sysrq-trigger'  I inspect the /etc/kdump.config to confirm that nfs path is present.  In several instance, I've observed up to 6 minutes delay before /etc/kdump.conf was updated with the NFS path from attribute 'dump'.  The compute nodes, service nodes, and management nodes are on private network and switches.  If the delay is expected and normal, please let me know.

http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/enable_kdump.html

**Observed 5-6 mins delay before compute nodes /etc/kdump.conf was updated with NFS path**
1. Contents of /etc/kdump.conf for 4 minutes of uptime
```
#raw /dev/vg/lv_kdump
#ext4 /dev/vg/lv_kdump
#ext4 LABEL=/boot
#ext4 UUID=03138356-5e61-4ab3-b58e-27507ac41937
#nfs my.server.com:/export/tmp
#ssh user@my.server.com
#sshkey /root/.ssh/kdump_id_rsa
path /var/crash
core_collector makedumpfile -l --message-level 1 -d 31
#core_collector scp
#kdump_post /var/crash/scripts/kdump-post.sh
#kdump_pre /var/crash/scripts/kdump-pre.sh
#extra_bins /usr/bin/lftp
#extra_modules gfs2
#default shell
#force_rebuild 1
#force_no_rebuild 1
#dracut_args --omit-drivers "cfg80211 snd" --add-drivers "ext2 ext3"
#fence_kdump_args -p 7410 -f auto -c 0 -i 10
#fence_kdump_nodes node1 node2
```

2. Contents of /etc/kdump.conf after 5 mins of uptime.  I replaced IP with <service_node_ip>.
```
nfs <service_node_ip>:/DUMPS
default shell
dracut_args --omit "xcat"
```

**xCAT level**
```
# lsxcatd -a
Version 2.13.11 (git commit 41c86021be74de908b09e3244b1b4c41a6e4ef68, built Thu Feb 22 06:15:44 EST 2018)
```
This is a Management Node
```
cfgloc=Pg:dbname=xcatdb;host=<xcat_master_ip>|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=<xcat_master_ip>
dbadmin=xcatadm
```

**Comment by immarvin** [comment]
hi @belldi , the updating of `/etc/kdump.conf` is done with in postbootscript `enablekdump`,  which is one of the scripts which run after node boot up, it might be run a while later after node boot up, depends on the execution of other postbootscript s before it. Did you notice the status of the node before the `/etc/kdump.conf` is updated? is it `booted` or `booting`?

**Comment by belldi** [comment]
Hello @immarvin the compute node was at runtime.  However, I did not that postscripts were still running based on messages in the console.  Maybe, I need to review the number of postscripts that run after diskless Pegas 1.0 boots.

**Comment by belldi** [comment]
Based on my observations monitoring log on xCAT server, it takes time for xCAT server to run postscripts.  We should be able to close this issue for now.  If I find additional info, I'll reopen this issue.

**Comment by bybai** [comment]
Thanks @belldi , you can reopen this issue if needed.
