### ISSUE TITLE
[fvt]verify openbmc in python installation, upgrade and basic function against  RCs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4868]
what to do

For 2.13.11 core package use openbmc in python by default. So need to verify it against RC1s manually.
* [ ] installation
* [ ] upgrade
* [ ] basic function

The expected run time is 2018/3/6-2018/3/7 (CDL time)

**Comment by robin2008** [comment]
Now you can get the draft documents in https://github.com/xcat2/xcat-core/pull/4907

**Comment by whowutwut** [comment]
@hu-weihua Please log the results here, instead of just checking the boxes and closing.   Would like to have data associated here for verification records.
