### ISSUE TITLE
rhels7.4 provision hang in anaconda with `ValueError: name already in use` 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4876]
In the default parition scheme, a volume group named "system" will be created, if there is a vg named`system`  already exists, this might conflict in some case, hence you see the error message " ValueError: name already in use".
```
+echo "volgroup system pv.01" >> /tmp/partitionfile
+echo "logvol / --vgname=system --name=root --size 1 --grow --fstype $FSTYPE" >> /tmp/partitionfile
```

```
anaconda 21.48.22.121-1 exception report
Traceback (most recent call first):
  File "/usr/lib/python2.7/site-packages/blivet/__init__.py", line 1122, in newVG
    raise ValueError("name already in use")
  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 1891, in execute
    peSize=pesize)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 1826, in execute
    v.execute(storage, ksdata, instClass)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 2392, in doKickstartStorage
    ksdata.volgroup.execute(storage, ksdata, instClass)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/spokes/storage.py", line 416, in execute
    doKickstartStorage(self.storage, self.data, self.instclass)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/hubs/summary.py", line 64, in setup
    spoke.execute()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/__init__.py", line 171, in setup
    should_schedule = obj.setup(self.ENVIRONMENT)
  File "/sbin/anaconda", line 1351, in <module>
    anaconda._intf.setup(ksdata)
ValueError: name already in use

What do you want to do now?
1) Report Bug
2) Debug
3) Quit
```

**Comment by zet809** [comment]
Hi, @immarvin ,have is issue fixed? If yes, pls set labels. Thx!

**Comment by immarvin** [comment]
cannot recreate this, close first, please reopen it if any update

**Comment by rashmjain** [comment]
I am hitting this problem on about 3 to 4 systems They are Cisco UCS M5.

How do I get out of this situation? 
If it a Hardware issue  I need to be able to report this to  the proper stakeholder.

Please guide

**Comment by immarvin** [comment]
this issue is recreated, spent some time to look into it. The root cause in this scenario is:
1.  there are multiple disks on the server: sda, sdb
2. there is an incomplete os installation on sda, the installation process is interrupted before kernel rpm is installed, there is no `vmlinuz*` file under `/boot` directory, hence:
   (1) `getinstalldisc` does not pick up sda as the installation disk, 
   (2) there is a volume group named `system` on sda, 
3. sdb is selected  as an installation disk, the partitionfile in anaconda is:
```
[anaconda root@mid08tor03cn26 ~]# cat /tmp/partitionfile
ignoredisk --only-use=/dev/sdb
part None --fstype "PPC PReP Boot" --ondisk /dev/sdb --size 8
part /boot --size 512 --fstype ext3 --ondisk /dev/sdb
part swap --recommended --ondisk /dev/sdb
part pv.01 --size 1 --grow --ondisk /dev/sdb
volgroup system pv.01
logvol / --vgname=system --name=root --size 1 --grow --fstype ext4
bootloader  --boot-drive=sdb
```  
4. fatal error occurs due to existing `system` VG on sda while creating `system` VG on sdb with `volgroup system pv.01`

**Comment by immarvin** [comment]
the workaround is to set `site.xcatdebugmode=2` to enable xcatdebugmode and kick off provision, then ssh to the installer and remove the VG `system` with 
```
vgchange -a n system
vgremove -f system
```

I also created a PR on this, but this will come into next release

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/5855/files
