### ISSUE TITLE
confignetwork for bond as postscript

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#4892]
Hello,

i am trying to setup an ipoib bond in postscripts with confignetwork but it fails to load kernel module bonding

lsxcatd -v
Version 2.13.10 (git commit 4fe63ecd9f836f3cf447118d461e1c10c69b1652, built Fri Jan 26 00:09:41 EST 2018)
Node definition:
> nicdevices.bond0=ib0|ib1
> nichostnamesuffixes.bond0=-ib
> nicips.bond0=10.100.0.200
> nicnetworks.bond0=ibnet
> nictypes.bond0=bond
> postscripts="remoteshell,syncfiles,confignetwork -S"

Output of confignetwork:

> [I]: All valid nics and device list:
> [I]: eth1
> [I]: bond0 ib0@ib1
> Running in chroot, ignoring request.
> [I]: NetworkManager is inactive.
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> configure nic and its device : eth1
> [I]: configure eth1
> [I]: call: configeth eth1 10.28.2.200 internal
> [I]: configeth on hilbert200: os type: redhat
> configeth on hilbert200: old configuration: 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
>     link/ether 08:00:38:3c:ee:47 brd ff:ff:ff:ff:ff:ff
>     inet 10.28.2.200/22 brd 10.28.3.255 scope global eth1
>        valid_lft forever preferred_lft forever
>     inet6 fe80::a00:38ff:fe3c:ee47/64 scope link 
>        valid_lft forever preferred_lft forever
> [I]: configeth on hilbert200: new configuration
>        10.28.2.200, 10.28.0.0, 255.255.252.0, 10.28.1.1
> 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT qlen 1000
> RTNETLINK answers: Cannot assign requested address
> [I]: configeth on hilbert200: eth1 changed, modify the configuration files
> bring up ip
> ['/etc/sysconfig/network-scripts/ifcfg-eth1']
> [I]: >> DEVICE=eth1
> [I]: >> BOOTPROTO=static
> [I]: >> NM_CONTROLLED=no
> [I]: >> IPADDR=10.28.2.200
> [I]: >> NETMASK=255.255.252.0
> [I]: >> ONBOOT=yes
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> configure nic and its device : bond0 ib0@ib1
> [I]: create_bond_interface ifname=bond0 slave_ports=ib0,ib1 slave_type=infiniband
> [I]: Pickup xcatnet, "ibnet", from NICNETWORKS for interface "bond0".
> [E]:Error: Fail to load kernel module "bonding"
> [I]: >>
> ./nicutils.sh: line 1341: /sys/class/net/bonding_masters: No such file or directory
> [E]:Error: stage 0: Fail to create bond device "bond0"

When i run the script as a postbootscript everything is fine

**Comment by bybai** [comment]
Hi @Phhere , postscripts will be ran before node reboot. From your log,  kernal bonding module is not loaded during postscripts. Could you check if "lsmod|grep bonding" and "modprobe --first-time bonding" failed in postscripts? 
You can create a test script for example /install/postscripts/test.sh, then add this script in postscripts to confirm if kernel bonding module is loaded or not during postscripts. 
```
# cat /install/postscripts/test.sh
modprobe --first-time bonding
lsmod|grep bonding
```

**Comment by bybai** [comment]
Hi @Phhere, are there any updates in your issue?

**Comment by bybai** [comment]
Will closed this issue, if any updates, can re-open it.
