### ISSUE TITLE
RH7.2 ppc64le diskless cuda related otherpkglist need to be modified

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#490]
The current cuda related otherpkglist as below for diskless image can not be used at all, we need to modify them as well as the document.
 #cat cudaruntime.rhels7.ppc64le.otherpkgs.pkglist 
 #For Cuda 7.5
 kernel-devel 
 gcc
 pciutils
 dkms
 cuda-runtime-7-5

**Comment by zet809** [comment]
Pull request 491.

**Comment by daniceexi** [comment]
@zet809 Do we have to make this change in  2.11 now? Does the current doc+current code not work?

**Comment by bybai** [comment]
Hi @daniceexi,  current doc+current code work now. And IST and our FVT have tested them before.

From @zet809, current doc+current code look ugly, they are just workaround.

**Comment by daniceexi** [comment]
@bybai @zet809 Please make sure that we have plan and time to verify the code and doc if want to change it.

**Comment by bybai** [comment]
Discussed this defects in team meeting,cuda version should not be specified in otherpkgs.list;
If CUDA version is specified in otherpkgs.pkglist as "cuda-7.5/ppc64le/cuda-deps/dkms", cuda version may be changed soon, and this otherpkgs.pkglist is till invalid;
Since current doc+code works, this pull request will be closed now.

**Comment by whowutwut** [comment]
@cxhong  @daniceexi  I think we changed the documentation for the ESP since we could not rebuild the code, but now we never went back and change the shipped samples so that it's easier on the user...  

Should we make this change? When could we plan a change like this?? There's no schedule PTF...

**Comment by daniceexi** [comment]
@whowutwut I think it's too later to do it now. I suggest we can make the fix in 2.11 branch after 2.11 GA so that if necessary we can make this change included in next 2.11 minor release.
