### ISSUE TITLE
When xCAT-openbmc-py is not installed on Service Node, log does not help describe the problem

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4908]
In this environment, the Service node does not contain the xCAT-openbmc-py package
```
[root@boston02 DEVBUILD]# xdsh sn02 "rpm -qa | grep xCAT-openbmc-py"
[root@boston02 DEVBUILD]#
```

And the error message points to `/var/log/xcat/cluster.log`. But in-fact there is no log on the service node....
```
[root@boston02 DEVBUILD]# xdsh sn02 ls /var/log/xcat
sn02: commands.log
sn02: dump
sn02: rflash
sn02: xcat.log
[root@boston02 DEVBUILD]#
```

If we are referring to the MN, the log doesn't help us... 

```
Mar  9 16:31:53 boston02 xcat[79770]: DEBUG xcatd: open new process : xcatd SSL: rpower to mid08tor03cn01 for root@localhost
Mar  9 16:31:53 boston02 xcat[79771]: DEBUG xcatd: dispatch request 'rpower mid08tor03cn01 state' to plugin 'openbmc2'
Mar  9 16:31:53 boston02 xcat[79771]: DEBUG xcatd: handle request 'rpower' by plugin 'openbmc2''s preprocess_request
Mar  9 16:31:53 boston02 xcat[79773]: DEBUG dispatch hierarchical sub-command rpower to sn02:3001
Mar  9 16:31:54 boston02 xcat[79770]: xCAT: Allowing rpower to mid08tor03cn01 state for root from localhost
Mar  9 16:31:54 boston02 xcat[79775]: DEBUG xcatd: dispatch request 'rpower mid08tor03cn01 state' to plugin 'openbmc'
Mar  9 16:31:54 boston02 xcat[79775]: DEBUG xcatd: handle request 'rpower' by plugin 'openbmc''s preprocess_request
Mar  9 16:31:54 boston02 xcat[79770]: DEBUG xcatd: close connection with root@localhost
```

Is it possible to default to Perl in this case... Or since Python is on the MN, it will send it in Python or attempt to send in Python?

**Comment by robin2008** [comment]
@whowutwut 
In an hierarchy environment, if you want print where the error message is coming from, you need to use `-V` commands.

And on sn02,  it seems the syslog on MN with tag xcat does not forwarding to MN, so the logs cannot be shown in `/var/log/xcat/cluster.log`

You can get them on sn02 `/var/log/message`
```
Mar  9 01:04:54 sn02 xcat[60862]: start_python_agent() Error: '/opt/xcat/lib/python/agent/agent.py' does not exist
Mar  9 01:04:54 sn02 xcat[60860]: xCAT: Allowing rpower to mid08tor03cn01 stat for root from boston02
Mar  9 01:05:03 sn02 xcat[60873]: start_python_agent() Error: '/opt/xcat/lib/python/agent/agent.py' does not exist
Mar  9 01:05:03 sn02 xcat[60871]: xCAT: Allowing rpower to mid08tor03cn01 stat -V for root from boston02
Mar  9 01:06:05 sn02 xcat[60928]: start_python_agent() Error: '/opt/xcat/lib/python/agent/agent.py' does not exist
Mar  9 01:06:05 sn02 xcat[60926]: xCAT: Allowing rpower to mid08tor03cn01 stat -V for root from boston02
```
Note: with the default syslog configuraiton, those log information should be in MN's /var/log/cluster.log
I think it is our design,  we still need it to collect all xCAT logs together.

**Comment by robin2008** [comment]
whatever, we can give an error message about it more clearly.
it is covered in https://github.com/xcat2/xcat-core/pull/4912

**Comment by robin2008** [comment]
For where the message is from, maybe we can have another issue to trace it.
Maybe for each error message, the `hostname` is mandatory.
