### ISSUE TITLE
Python framework stops responding and provides no help back to the user for debug

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4936]
It seems that when the xCAT Python agent or something gets into some unknown state... there's no indication to the user. We have just seen this happen on the system test cluster 

```
[root@mgt03 ~]# rpower f6n11 bmcstate
Tue Mar 13 07:46:44 2018 f6n11: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://192.168.74.130/login -d '{"data": ["root", "xxxxxx"]}'
Tue Mar 13 07:46:45 2018 f6n11: [openbmc_debug] login 200 OK
Tue Mar 13 07:46:45 2018 f6n11: [openbmc_debug] get_bmc_state curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://192.168.74.130/xyz/openbmc_project/state/bmc0/attr/CurrentBMCState
Tue Mar 13 07:46:45 2018 f6n11: [openbmc_debug] get_bmc_state 200 OK
f6n11: BMC Ready
[root@mgt03 ~]# rbeacon f6n11 off
[root@mgt03 ~]# rsetboot f6n11
[root@mgt03 ~]# rvitals f6n11
[root@mgt03 ~]# rinv f6n11
[root@mgt03 ~]#
```

What is strange here is that the `rpower` command is using the python framework based on the debug messages and it works, but the other commands have no indication of what happened. 

In debugging, restarting of xCATd fixed this issue, but . it leaves not help in debug.  
* xcatdebugmode=1 shows nothing for those commands that returned nothing
* no entries were logged in `/var/log/xcat/agent.log`

## Workaround

Disable Python framework
```
chdef -t site clustersite openbmcperl=ALL
```

**Comment by whowutwut** [comment]
Since we do want to get 2.13.11 out the door, I think we should mark this one as a known issue and tag the Python framework as "beta" for now...  user feedback would be helpful.

**Comment by gurevichmark** [comment]
If we can recreate this, one thing to try is to issue one of these failing commands with an invalid parameter, maybe `rbeacon junk` and see if we even enter our code to check the arguments.

**Comment by robin2008** [comment]
If we hit it once more,  I think for now just to add more logs there to see if it is using python agent.

**Comment by robin2008** [comment]
Never hit it more, to close it first.  If we found it again, just reopen.

For the logs of agent.py, it is better to leverage python's logging,  and now there might be multiple agent process,  the default logging is not suitable,  need to consider something like `ConcurrentLogHandler `
