### ISSUE TITLE
[OpenBMC] Verbose option not in Python for rinv or rvitals

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#4937]
Verbose `-V` option is supported for `rinv` and `rvitals` commands in Perl, but is not supported in Python:

```
[root@briggs01 xcat]# rvitals mid05tor12cn13 -V
Error: [briggs01]: Failed to parse arguments for rvitals: ['-V']

[root@briggs01 xcat]# rinv mid05tor12cn13 -V
Error: [briggs01]: Failed to parse arguments for rinv: ['-V']
[root@briggs01 xcat]#
```

`rvitals` man page and usage also needs to be modified to show support for `-V`

**Comment by robin2008** [comment]
@gurevichmark  could you help to review it ASAP, we need it done before this Friday

**Comment by gurevichmark** [comment]
Man page change for `rvitals` done in #5079
