### ISSUE TITLE
[Customer]xCAT 2.11: BMC Network is configured with wrong network mask (after node discovery)

### ISSUE THREAD

**Issue by mfoliveira** [xcat2/xcat-core#494]
xCAT: 20151124.0304-core-rpms-snap.tar.bz2
RHEL 7.2 GA
IBM S822LC

Networks table:
- Network with **16-bit** network mask 

```
	[root@xcat-mn ~]# mkdef -t network net-svc net=10.2.0.0 mask=255.255.0.0 mgtifname=enP3p3s0f2 # network visible to mgmt node
	1 object definitions have been created or modified.

	[root@xcat-mn ~]# lsdef -t network net-svc
	Object name: net-svc
	    mask=255.255.0.0
	    mgtifname=enP3p3s0f2
	    net=10.2.0.0
```

BMC Network Config:
(after node discovery)
- Network with **24-bit** network mask (_incorrect/different from specified_)

```
	[root@p8r1n1 firmware]# ipmitool -I lanplus -H fe80::72e2:84ff:fe14:254%enP3p3s0f2 -U ADMIN -P admin lan print 1
	<...>
	IP Address Source       : Static Address
	IP Address              : 10.2.1.1
	Subnet Mask             : 255.255.255.0
	<...>
```

This seems to be rspconfig.

Thanks!

**Comment by mfoliveira** [comment]
Hi @whowutwut 

Just FYI.
Hope you've had nice holidays! :)

Thanks

**Comment by zet809** [comment]
Hi, @mfoliveira 
In fact, we haven't called rspconfig to configure netmask for the BMCs.
If you'd like to configure BMC during hardware discovery process, please use "chdef <node> chain="runcmd=bmcsetup"" before starting hardware discovery process.
If you want to configure BMC if the host OS is installed, you can use "nodeset <node> runcmd=bmcsetup", "rpower <node> reset" to restart the node to do BMC configuration.

**Comment by mfoliveira** [comment]
Hi @zet809 

Well, if the netmask ends up set incorrectly to something more restrictive than on the mgmt node (say, /24 on BMC, and /16 on mgmt node), the BMC will not be accessible from the mgmt node, if it's in a different subnet (e.g., BMC is 10.2.1.1/24, mgmt node is 10.2.0.1/16 - the subnets differ for BMC perspective).

So I think it should be fixed (i.e., do set the netmask), otherwise, the user may lose access to the BMC (e.g., rpower & rsetboot commands) in a similar scenario.

I discussed this w/ @whowutwut today, and recommend this not to be rejected.

Not sure if anything is wrong or you've discussed this, but there is evidence that rspconfig indeed *was called* during node discovery.  I didn't set chain/runcmd.

Here's the info I provided to Victor:

The node discovery log:

```
Nov 25 23:09:44 redbook01 dhcpd: DHCPDISCOVER from 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:09:45 redbook01 dhcpd: DHCPOFFER on 10.1.254.5 to 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:09:45 redbook01 dhcpd: DHCPREQUEST for 10.1.254.5 (10.1.0.1) from 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:09:45 redbook01 dhcpd: DHCPACK on 10.1.254.5 to 98:be:94:59:f0:f2 via enP3p3s0f2

Nov 25 23:09:50 redbook01 xcat[30280]: xCAT: Allowing getcredentials x509cert
Nov 25 23:11:02 redbook01 xcat[17646]: xcatd: Processing discovery request from 10.1.254.5
Nov 25 23:11:03 redbook01 xcat[17646]: Discover info: configure static BMC ip:10.2.1.1 for host_node:p8r1n1.
Nov 25 23:11:03 redbook01 xcat[30322]: xCAT: Allowing rspconfig to p8r1n1 ip=10.2.1.1 for root from localhost

Nov 25 23:11:19 redbook01 dhcpd: DHCPRELEASE of 10.1.254.5 from 98:be:94:59:f0:f2 via enP3p3s0f2 (found)
Nov 25 23:11:19 redbook01 dhcpd: DHCPDISCOVER from 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:11:19 redbook01 dhcpd: DHCPOFFER on 10.1.1.1 to 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:11:19 redbook01 dhcpd: uid lease 10.1.254.5 for client 98:be:94:59:f0:f2 is duplicate on enP3p3s0f2
Nov 25 23:11:19 redbook01 dhcpd: DHCPREQUEST for 10.1.1.1 (10.1.0.1) from 98:be:94:59:f0:f2 via enP3p3s0f2
Nov 25 23:11:19 redbook01 dhcpd: DHCPACK on 10.1.1.1 to 98:be:94:59:f0:f2 via enP3p3s0f2

Nov 25 23:11:19 redbook01 xcatd: Discovery worker: fsp instance: nodediscover instance: p8r1n1 has been discovered

Nov 25 23:11:20 redbook01 xcat[17646]: Discover info: configure static BMC ip:10.2.1.1 for host_node:p8r1n1.
Nov 25 23:11:20 redbook01 xcat[30357]: xCAT: Allowing rspconfig to p8r1n1 ip=10.2.1.1 for root from localhost
Nov 25 23:11:30 redbook01 xcat[30361]: xCAT: Allowing getcredentials x509cert from p8r1n1
Nov 25 23:11:30 redbook01 xcat: credentials: sending x509cert
Nov 25 23:11:34 redbook01 xcatd: Discovery worker: fsp instance: nodediscover instance: Failed to notify 10.1.254.5 that it's actually p8r1n1.
 ```

The BMC node definition from bmcdiscover:

```
[root@xcat-mn ~]# bmcdiscover --range 10.1.254.1-2 -t -w
node-8335-gta-0000000000000000:
        objtype=node
        groups=all
        bmc=10.1.254.1
        cons=ipmi
        mgt=ipmi
        mtm=8335-GTA
        serial=0000000000000000
        nodetype=mp
        hwtype=bmc 
```

The host node definition:

```
[root@xcat-mn ~]# lsdef p8r1n1
Object name: p8r1n1
    bmc=10.2.1.1
    cons=ipmi
    groups=all,s822lc
    ip=10.1.1.1
    mgt=ipmi
    mtm=8335-GTA
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=0000000000000000 
```

Networks table:

```
[root@xcat-mn deps]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"net-mgmt","10.1.0.0","255.255.0.0","enP3p3s0f2","<xcatmaster>",,"10.1.0.1",,,,"10.1.254.1-10.1.254.254",,,,,,,,
"net-svc","10.2.0.0","255.255.0.0","enP3p3s0f2",,,,,,,,,,,,,,,
"net-app-10gbe-port1","10.3.0.0","255.255.0.0",,,,,,,,,,,,,,,,
"net-app-10gbe-port2","10.4.0.0","255.255.0.0",,,,,,,,,,,,,,,,
"net-app-ib-port1","10.5.0.0","255.255.0.0",,,,,,,,,,,,,,,,
"net-app-ib-port2","10.6.0.0","255.255.0.0",,,,,,,,,,,,,,,,
```


Thanks.

**Comment by whowutwut** [comment]
@zet809  I think we need to look into this for 2.12. We can discuss in the interlock meeting. 
Basically in Utils.pm, we set the IP address in the discovery...
 
Nov 25 23:11:20 redbook01 xcat[17646]: Discover info: configure static BMC ip:10.2.1.1 for host_node:p8r1n1.

That is done running ``rspconfig p8r1n1 ip=10.2.1.1``

The IP address is picked up from the ipmi table, but the problem here is that the 255.255.255.0 netmask was used, possibly because it was the "default"...  The issue here is that the 10.2 network in @mfoliveira  system has a netmask of 255.255.0.0 and the xCAT mgmt node is on a different subnet... the BMC configured with 255.255.255.0 could not talk to the mgmt node after this IP was set..  

Going to unset the rejected status.

**Comment by daniceexi** [comment]
@whowutwut @pdlun92 @mfoliveira @zet809 
* If @mfoliveira set up the BMC through discovery, the bmcsetup should added in the chain table;
* If @mfoliveira set up the BMC IP through ipmitool, he should cover the netmask and gateway setup by himself.

**Comment by mfoliveira** [comment]
Not sure what the context of the last message is; providing a clarification:

The bmcsetup was performed through discovery; and the netmask was not set
(but it should, as it's required on network setup).

Thanks!

On Tue, Apr 26, 2016 at 5:14 AM, Xiaopeng Wang <notifications@github.com>
wrote:

> @whowutwut <https://github.com/whowutwut> @pdlun92
> <https://github.com/pdlun92> @mfoliveira <https://github.com/mfoliveira>
> @zet809 <https://github.com/zet809>
>
>    - If @mfoliveira <https://github.com/mfoliveira> set up the BMC
>    through discovery, the bmcsetup should added in the chain table;
>    - If @mfoliveira <https://github.com/mfoliveira> set up the BMC IP
>    through ipmitool, he should cover the netmask and gateway setup by himself.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xcat2/xcat-core/issues/494#issuecomment-214663681>
>



-- 
Mauricio Faria de Oliveira
http://mfoliveira.org

**Comment by daniceexi** [comment]
@mfoliveira For your case, adding 'bmcsetup' in the chain table will fix your problem. Refer to http://xcat-docs.readthedocs.io/en/latest/advanced/chain/run_tasks_during_discovery.html?highlight=bmcsetup

**Comment by mfoliveira** [comment]
Hi @daniceexi 
Ok. Should this be performed automatically during node discovery? (when the setup of the bmc network configuraton happened)

**Comment by daniceexi** [comment]
@mfoliveira yes, the **bmcsetup** will be called automatically to set up the bmc.

**Comment by whowutwut** [comment]
@daniceexi  If i recall correctly, I don't think it will work....   I think we are NOT selecting the correct netmask.  If you look at my comment from 12/1/15, in the code when we are looking for the netmask, we are running the `rspconfig` and that does not select the correct netmask.   

I'll see if @pdlun92  can take a look at this for 2.12  (also need to cherry pick to 2.11... )

**Comment by daniceexi** [comment]
@whowutwut bmcsetup script does not call rspconfig. For FS server, two actions will be executed one by one to set up network for discovered nodes:

1. run rspconfig (always be executed)
2. run bmcsetup ( if the bmcsetup is added in the chain table)

So if bmcsetup is added in chain table, it would be execute to set up network for discovered node. It can handle the netmask correctly.

**Comment by daniceexi** [comment]
Since this is a usage issue, so close it.

**Comment by mfoliveira** [comment]
Hi @daniceexi 

Thanks for the clarifications, but I'm not sure this is a usage issue.
At the time the bug was reported, with that package version, the normal node discovery process (documented in the official doc pages at that time) for S822LC was performed - so I guess the bmcsetup should have been added/ran automatically.

**Comment by daniceexi** [comment]
@mfoliveira As I mentioned before, the following action would be run always despite the ``bmcsetup`` was specified or not.  

1. configure bmc through rspconfig (always be executed)

**Comment by mfoliveira** [comment]
Hi @daniceexi

Sorry, I'm a bit confused; can you please confirm this?

The point here is -- correctly configure the network mask for the BMC with
the default node discovery process in xCAT (this is a normal expectation).

From what I can see in the comments, rspconfig is called BUT is does not
work correctly, and bmcsetup works correctly BUT is not called. Is that
right?

Or things have changed and the default node discovery sets the netmask
correctly nowadays?

Thanks!

On Thu, May 12, 2016 at 9:29 AM, Xiaopeng Wang <notifications@github.com>
wrote:

> @mfoliveira <https://github.com/mfoliveira> As I mentioned before, the
> following action would be run always despite the bmcsetup was specified
> or not.
>
>    1. configure bmc through rspconfig (always be executed)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xcat2/xcat-core/issues/494#issuecomment-218742414>
>



-- 
Mauricio Faria de Oliveira
http://mfoliveira.org

**Comment by whowutwut** [comment]
Hi @mfoliveira , when I discussed this with @daniceexi , the conclusion is that you should use the `bmcsetup` script to do the hardware discovery for OpenPower nodes, then it will not call the rspconfig call that you saw and it should be able to set the netmask correctly.

**Comment by mfoliveira** [comment]
Ok, thanks.

Is this something that needs to be configured / documented for the node
discovery?

Regards,

**Comment by daniceexi** [comment]
Right, for the openPOWER server, only the bmcsetup is supported to set up the BMC network.

Since the 'rspconfig' way to set tup BMC network is just a workaround for certain server, it will be restricted to be run only for the specific server. For general servers, the ``bmcsetup``should be used.

**Comment by mfoliveira** [comment]
All right.
I've seen this has been updated in the 2.11 docs with
commit 2d565b3939a9362618d2ba5ac5bfac85c0946b1d
Thanks!
