### ISSUE TITLE
When we cannot connect to the BMC, the output that is returned in Python framework is not as informative as Perl

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4942]
When comparing rpower between python and perl, it seems the error messages are not informative, 

```
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: Error: BMC did not respond. Validate BMC configuration and retry the command.
```

There's two `Error: Error ` in the output line...

and in Perl
```
[root@briggs01 ~]# chdef -t site clustersite openbmcperl="rpower"
1 object definitions have been created or modified.
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: [500] Login to BMC failed: 500 Can't connect to 172.11.139.11:443 (No route to host).
mid05tor12cn11: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 ~]#
```

@gurevichmark @xuweibj  I thought we improved this and was planning to put the IP address of the node as part of this.  But was the above message what we had ended up with at the end?

**Comment by xuweibj** [comment]
hi @whowutwut , I have fixed this issue in pull request #4884 . But I forget that we will not merge 4884 before release. Do you think we need to fix it in 2.13.11? If so, I could create a new pull request for it.

**Comment by whowutwut** [comment]
No it’s ok to go into the next release. Thanks!!!

**Comment by whowutwut** [comment]
@xuweibj Using the 3/26 build of xCAT, there's no change from the issue describe above... 

```
[root@briggs01 ~]# lsxcatd -a
Version 2.14 (git commit 3217230d197babb3688fef28f26135fb5e5ad1a1, built Mon Mar 26 06:15:52 EDT 2018)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=172.10.253.27|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=172.10.253.27
dbadmin=xcatadm
```

## Python
```
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: BMC did not respond. Validate BMC configuration and retry the command.
```

## Perl 
```
[root@briggs01 ~]# lsdef -t site clustersite -i openbmcperl
Object name: clustersite
[root@briggs01 ~]# chdef -t site clustersite openbmcperl="rpower"
1 object definitions have been created or modified.
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: [500] Login to BMC failed: 500 Can't connect to 172.11.139.11:443 (No route to host).
mid05tor12cn11: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 ~]#
```

so i don't think we can put this in pending...

**Comment by xuweibj** [comment]
hi @whowutwut , I thought that the issue is just because the multiple ``Error:``. Should we print out msg like ``[500] Login to BMC failed: 500 Can't connect to 172.11.139.11:443 (No route to host).``? I think this msg is enough. Do you mean we should do it like https://github.com/xcat2/xcat-core/pull/4988?

**Comment by whowutwut** [comment]
Hi @xuweibj yea we should print out some error number if it’s a connection issue so that w don’t need to ask for recreate and can tell if the bmc has some issue and it’s not in xcat code

**Comment by hu-weihua** [comment]
@whowutwut, could you help to verify this issue again? thanks

**Comment by whowutwut** [comment]
This looks good for the original test case: 
```
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: Login to BMC failed: Can't connect to 172.11.139.11 (Connection reset by peer).
[root@briggs01 ~]# chdef -t site clustersite openbmcperl="rpower"
1 object definitions have been created or modified.
[root@briggs01 ~]# rpower mid05tor12cn11 state
mid05tor12cn11: Error: [500] Login to BMC failed: 500 Can't connect to 172.11.139.11:443 (No route to host).
mid05tor12cn11: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 ~]# chdef -t site clustersite openbmcperl=
1 object definitions have been created or modified.
```
