### ISSUE TITLE
Boston p9, rspconfig ip=dhcp does not seem to work on Boston servers ... 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4946]
Reported from IST team, using `rspconfig <node> ip=dhcp` on Boston p9 servers does not reset the IP... 

Before:
```
IP Address Source       : Static Address
IP Address              : 192.168.1.110
Subnet Mask             : 255.255.240.0
```

After, it changes the Source but the address is the same... 
```
IP Address Source       : DHCP Address
IP Address              : 192.168.1.110
Subnet Mask             : 255.255.240.0 
```

**Comment by markprez** [comment]
Full details, after BMC setup run and set a status IP, lan print 1 shows:
[root@csm01 ~]# ipmitool -H 192.168.1.110 -U ADMIN -P ADMIN lan print 1
Set in Progress         : Set Complete
Auth Type Support       : NONE MD2 MD5 PASSWORD
Auth Type Enable        : Callback : MD2 MD5 PASSWORD
                        : User     : MD2 MD5 PASSWORD
                        : Operator : MD2 MD5 PASSWORD
                        : Admin    : MD5
                        : OEM      : MD2 MD5 PASSWORD
IP Address Source       : DHCP Address
IP Address              : 192.168.1.110
Subnet Mask             : 255.255.240.0
MAC Address             : ac:1f:6b:0d:14:6c
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Default Gateway IP      : 192.168.1.2
Default Gateway MAC     : 40:f2:e9:5d:87:36
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 1,2,3,6,7,8,11,12
Cipher Suite Priv Max   : XaaaXXaaaXXaaXX
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
Bad Password Threshold  : 5
Invalid password disable: yes
Attempt Count Reset Int.: 600
User Lockout Interval   : 600

After trying to set it to dhcp:
[root@csm01 ~]# rspconfig f1n10 ip=dhcp
[root@csm01 ~]# ipmitool -H 192.168.1.110 -U ADMIN -P ADMIN lan print 1
Set in Progress         : Set Complete
Auth Type Support       : NONE MD2 MD5 PASSWORD
Auth Type Enable        : Callback : MD2 MD5 PASSWORD
                        : User     : MD2 MD5 PASSWORD
                        : Operator : MD2 MD5 PASSWORD
                        : Admin    : MD5
                        : OEM      : MD2 MD5 PASSWORD
IP Address Source       : DHCP Address
IP Address              : 192.168.1.110
Subnet Mask             : 255.255.240.0
MAC Address             : ac:1f:6b:0d:14:6c
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Default Gateway IP      : 0.0.0.0
Default Gateway MAC     : 00:00:00:00:00:00
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 1,2,3,6,7,8,11,12
Cipher Suite Priv Max   : XaaaXXaaaXXaaXX
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
Bad Password Threshold  : 5
Invalid password disable: yes
Attempt Count Reset Int.: 600
User Lockout Interval   : 600

**Comment by zet809** [comment]
So, it seems ip=dhcp just set ip source to be DHCP, not have it restart network configuration.

**Comment by zet809** [comment]
I have tried 'rspconfig ip=dhcp' against an x86_64 BMC, the ip is changed after change to DHCP.
And from the IPMI specification, there is no command can be used to restart Network server on BMC, so it seems to be the BMC firmware that responsible for restart network service to get BMC IP through DHCP. 
So, maybe we need to open an issue for Boston BMC team. @whowutwut and @markprez 
```
[root@c910f05c01bc05 ~]# ipmitool lan print 1
Set in Progress         : Set Complete
...
IP Address Source       : Static Address
IP Address              : 50.5.1.105
...
```
After set to DHCP:
```
[root@c910f05c01bc05 ~]# ipmitool lan print 1
...
IP Address Source       : DHCP Address
IP Address              : 50.5.10.105
...
```

**Comment by zet809** [comment]
And test on our own environment, the IP is changed 2 seconds later. So, @markprez , may I log on your environment to take a look at? 
```
[root@stratton01 ~]# ipmitool -I lanplus -H 50.6.31.1 -U ADMIN -P ADMIN lan print 1
Set in Progress         : Set Complete
...
IP Address Source       : Static Address
IP Address              : 50.6.31.1
Subnet Mask             : 255.0.0.0
MAC Address             : 0c:c4:7a:f4:5b:0e
...
[root@stratton01 ~]# rspconfig boston02 ip=dhcp
[root@stratton01 ~]# ipmitool -I lanplus -H 50.6.31.10 -U ADMIN -P ADMIN lan print 1
...
IP Address Source       : DHCP Address
IP Address              : 50.6.31.10
Subnet Mask             : 255.0.0.0
MAC Address             : 0c:c4:7a:f4:5b:0e
...
```

**Comment by zet809** [comment]
Close this issue and reopen if we encounter it again.

**Comment by whowutwut** [comment]
Let me put this in my backlog, once I have some P9 Boston servers in a private network, I can run this test to verify.

**Comment by cxhong** [comment]
@whowutwut , I verify this issue on the boston02.  I think it's working as expected.

````
# ipmitool -I lanplus -H 172.21.226.26 -U ADMIN -P admin lan print 1
.........
IP Address Source       : Static Address
IP Address              : 172.21.226.26
Subnet Mask             : 255.255.0.0
MAC Address             : 0c:c4:7a:f4:5b:01
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Default Gateway IP      : 172.21.253.31
Default Gateway MAC     : 0c:c4:7a:ea:9d:ff
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
.........
````
Change to DHCP ip address
```
# rspconfig mid08tor03cn26 ip=dhcp
````

DHCP message from /var/log/message:
````
Apr 23 14:22:42 boston02 dhcpd: DHCPDISCOVER from 0c:c4:7a:f4:5b:01 via enP50p3s0f1
Apr 23 14:22:43 boston02 dhcpd: DHCPOFFER on 172.21.253.154 to 0c:c4:7a:f4:5b:01 via enP50p3s0f1
Apr 23 14:22:43 boston02 dhcpd: DHCPREQUEST for 172.21.253.154 (172.21.253.31) from 0c:c4:7a:f4:5b:01 via enP50p3s0f1
Apr 23 14:22:43 boston02 dhcpd: DHCPACK on 172.21.253.154 to 0c:c4:7a:f4:5b:01 via enP50p3s0f1
````
Checking ip address of BMC
````
# ipmitool -I lanplus -H 172.21.253.154 -U ADMIN -P admin lan print 1
````
...................
IP Address Source       : DHCP Address
IP Address              : 172.21.253.154
Subnet Mask             : 255.255.0.0
MAC Address             : 0c:c4:7a:f4:5b:01
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Default Gateway IP      : 172.21.253.31
Default Gateway MAC     : 0c:c4:7a:ea:9d:ff
...........
````
The firmware of this  Boston node:
````
# rflash mid08tor03cn26 -c
mid08tor03cn26: Node firmware version for SMC BMC FW   component:   1.18.0
mid08tor03cn26: Node firmware version for PNOR FW      component:   3.30.6176
mid08tor03cn26: Node firmware version for  component:   0.00.0
````

**Comment by whowutwut** [comment]
Closing for now based on the above. Thanks @cxhong
