### ISSUE TITLE
In large systems, "xcatmax*" default configuration values are not sufficient 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4947]
In large systems > 4000 nodes, it seems that the default configuration values for the following is not sufficient and one potential side effect is that the xcat parent process is pegged at 100% CPU 

* xcatmaxconnections
* xcatmaxbatchconnections

Seems by changing to `xcatmaxconnections=128` and `xcatmaxbatchconnections=100`, it improves things.  

**NOTE:** . If you are experiencing this, to change the values use XCATBYPASS as you probably won't be able to communicate with the xcatd ....
```
XCATBYPASS=1 chdef -t site clustersite xcatmaxconnections=128
XCATBYPASS=1 chdef -t site clustersite xcatmaxbatchconnections=100
```

How did we initially come up with this default values of 64 and 50 and does it make sense to adjust these values in the code or somehow make it vary depending on the cluster size?  

We reference this value in https://sourceforge.net/p/xcat/wiki/Hints_and_Tips_for_Large_Scale_Clusters/ but we have not moved over that documentation to RTD and even in that page we provide no documentation about it or recommendations about it. 

What is the down side for defaulting to a larger value if we are running small systems? if no performance impact, perhaps it should be increased....

**Comment by robin2008** [comment]
Is this make working?  the options is to set the max accepted client (TCP from user request, or UDP from node requesting).  So it is to keep the CPU higher away on the OS (not to fork too many processes) when set it to a small value.  

If too many requesting,  it should be using the flowcontrol,  Maybe we can  have a flood testing on  it.

**Comment by robin2008** [comment]
It seems there are lots of `getopenbmccons` requesting on MN (10+ seconds), and it consumes up the `xcatmaxconnections` as if a node does not have valid user/pass IP, /opt/xcat/share/xcat/cons/openbmc will try to send the request again and again.

**Comment by hu-weihua** [comment]
@whowutwut, could you verify this issue? Can we close this issue now?

**Comment by immarvin** [comment]
the doc is created in https://github.com/xcat2/xcat-core/pull/5038

**Comment by whowutwut** [comment]
Thanks for the doc changes @immarvin
