### ISSUE TITLE
Improve error message usability for nodeset command

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#4948]
For a command usage mistake:
```
[root@csm01 ~]# nodeset boston rhels7.5-alternate-ppc64le
Error: Unknown state rhels7.5-alternate-ppc64le requested
[root@csm01 ~]#
```

Improve usability by displaying:
```
[root@csm01 ~]# nodeset boston rhels7.5-alternate-ppc64le
Error: Unknown state rhels7.5-alternate-ppc64le requested

Did you mean? 
    runcmd=rhels7.5-alternate-ppc64le
    osimage=rhels7.5-alternate-ppc64le
    runimage=rhels7.5-alternate-ppc64le
[root@csm01 ~]#
```

**Comment by robin2008** [comment]
@gurevichmark I'm not sure it is a good choice. As it will confuse user when he just give a typo on the command,  for example, If I issue `nodeset boston ofline`, what I want is `nodeset boston offline`

Now xCAT does not have the capability to figure out the intention, then I prefer to just give the usage there when failed to parse args.

**Comment by gurevichmark** [comment]
Ok, I agree. Lets not get too fancy.

**Comment by robin2008** [comment]
I think some opensource CLI frameworks could support such fancy feature, we can revisit it when build new CLIs.
