### ISSUE TITLE
Copycds does not generate a windows osimage definition

### ISSUE THREAD

**Issue by dotRollen** [xcat2/xcat-core#4952]
When running `copycds` it does not create a `osimage` here is the following output after `copycds`.

```
[root@216f9d7a95fc tftpboot]# copycds -i 7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso 
OS Image:/tftpboot/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
DISTNAME:win2k8r2
ARCH:x86_64
```

Doing a `lsdef -t osimage` no windows definition is available. Also when using `nodeset winshell` it does not recognize the argument `winshell` even though winpe is in the proper tftpboot directory.

**Comment by immarvin** [comment]
hi @dotRollen , windows support is no longer announced in xCAT now, you can take a look at `/opt/xcat/lib/perl/xCAT_plugin/windows.pm` and make it work by yourself, we can provide technical support during this.

thx
