### ISSUE TITLE
Switching to goconvers doesn't modify conserver startup configuration. goconserver doesn't start on reboot. 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4961]
When we switch over to `goconserver` the `sysVinit` still contains the configuration for conserver asking it to auto start when the server boot up...
```
[root@boston02 consoles]# chkconfig --list | grep conserver

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
```

So in the case that we switch to goconserver, it doesn't modify any start up scripts

```
[root@boston02 ~]# cd /var/log/consoles
[root@boston02 consoles]# rm -rf *
[root@boston02 consoles]# service conserver stop
Stopping conserver (via systemctl):                        [  OK  ]
[root@boston02 consoles]# service goconserver start
Redirecting to /bin/systemctl start goconserver.service
[root@boston02 consoles]#
[root@boston02 consoles]# ls -ltr
total 12
-rw------- 1 root root 55 Mar 17 14:55 sn02.log
-rw------- 1 root root 55 Mar 17 14:55 mid08tor03cn01.log
-rw------- 1 root root 55 Mar 17 14:55 mid08tor03cn10.log
```

Now let's reboot this server.... 

After reboot, you can tell right away the conserver has taken over again, because of the log files. 

```
[root@boston02 consoles]# ls -ltr
total 24
-rw------- 1 root root   55 Mar 17 14:55 sn02.log
-rw------- 1 root root   55 Mar 17 14:55 mid08tor03cn01.log
-rw------- 1 root root   55 Mar 17 14:55 mid08tor03cn10.log
-rw-r--r-- 1 root root 1239 Mar 17 15:01 sn02
-rw-r--r-- 1 root root 1182 Mar 17 15:01 mid08tor03cn01
-rw-r--r-- 1 root root 1182 Mar 17 15:01 mid08tor03cn10
[root@boston02 consoles]#
```

**Comment by whowutwut** [comment]
Some options that I can think about.. @chenglch  I think we need to consider some changes here to make this work on reboot.. 

1. As part of the `makegocons` we should call `chkconfig conserver off` ... 
but then when user runs `makeconservercf` we have to put it back

1. ask user to remove conserver rpm 
   * How does this affect xCAT update? We don't want conserver to be installed again 

3. `goconserver` does not start automatically even if conserver is not running   - So here's a bigger problem... 

```
chkconfig conserver off
reboot

[root@boston02 ~]# service goconserver status | grep Active
Redirecting to /bin/systemctl status goconserver.service
   Active: inactive (dead)
[root@boston02 ~]# uptime
 15:11:06 up 3 min,  1 user,  load average: 0.16, 0.33, 0.16
[root@boston02 ~]#
```

So this does not work ...

**Comment by samveen** [comment]
Maybe a `Conflicts: conserver` and it's debian equivalent in the go-conserver RPM/Deb configuration?

**Comment by chenglch** [comment]
@whowutwut , I think I could work on item 1 and item 3 at first.  For item2, conserver is still needed for a while, there are two reasons: 
1. `goconserver` could not support all of the systems.
2. `goconserver` do not support hardware console server but `conserver` do.

**Comment by chenglch** [comment]
With #5001, after running `makegocons` , the startup configuration should take effect. Only available for on systemd based system.

**Comment by neo954** [comment]
The problem was verified. I will close this one.
