### ISSUE TITLE
passwd, shadow, and group files are not merged up until mtime changes

### ISSUE THREAD

**Issue by gualican** [xcat2/xcat-core#4972]
I'm using xCAT v. 2.13.11 and /etc/passwd, /etc/shadow, and /etc/group are not synced (merged) neither after a fresh install nor after running `updatenode <node> -F` .

I've found that running `touch /etc/{passwd,shadow,group}` **before** running updatenode works.

Is there a check on mtime (that doesn't consider file content as well as size)?

**Comment by robin2008** [comment]
@gualican 
xCAT is using `rsync` there, I guess there might be an NTP issue on your compute node.

**Comment by gualican** [comment]
@robin2008 
```
# ntpstat
synchronised to NTP server (172.172.0.1) at stratum 4 
   time correct to within 207 ms
   polling server every 1024 s
```
(yeah, that's a private IP address that's not RFC1918 compliant)

**Comment by robin2008** [comment]
close it first, if any new update, we can reopen it again.
