### ISSUE TITLE
If RSA fingerprint is changed for BMC, cannot run bmcdiscover, incorrect warning message

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4977]
I am re-doing discovery testing and hit this: 
```
[root@briggs01 ~]# bmcdiscover --range 172.12.253.104
Warning: BMC password is incorrect for 172.12.253.104
```

So then checked the passwd table and everything looked OK, and also was able to ssh to this BMC: 
But got this issue: 
```
[root@briggs01 ~]# ssh root@172.12.253.104
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:sXzLt1NmijlcnMQxFqlMU8ACio57BBhpRXT4DrTxTtc.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending RSA key in /root/.ssh/known_hosts:21
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
root@witherspoon:~#
```
After removing this file, bmcdiscover worked...

```
[root@briggs01 ~]# rm /root/.ssh/known_hosts
rm: remove regular file ‘/root/.ssh/known_hosts’? y
[root@briggs01 ~]# bmcdiscover --range 172.12.253.104 -z
node-8335-gtc-785263a:
	objtype=node
	groups=all
	bmc=172.12.253.104
	cons=openbmc
	mgt=openbmc
	mtm=8335-GTC
	serial=785263A
```

So that warning message is not right.

**Comment by samveen** [comment]
@whowutwut Victor, I have an orthogonal question. 
- For the BMC, what are the conditions for the ssh server keys to be changed? I expect that the BMC sshd should not change it's server keys, but it seems to have happened in this case. 
- Can it be explained as a change to the IP assigned for the BMC?

These question are not related to the problem as such, but just an FYI for me.

**Comment by zet809** [comment]
Hi, @whowutwut , is it possible the same issue with https://github.ibm.com/vhu/c910env/issues/238?
bmcdiscover never ssh to BMC to retrieve information.
So, will you pls use 'arp -a | grep 172.12.253.104' to get the MAC address and compare with the real BMC MAC address if you reproduce it?

**Comment by whowutwut** [comment]
@samveen good question, I'm actually not sure why a `ip=dhcp` would change the ssh server keys, let me try and rerun this test tomorrow...    I didn't reset the BMC to default, just wiped out the network configuration. 

@zet809 will try what you suggest tomorrow if i can reproduce it.

**Comment by zet809** [comment]
Close this issue and reopen if we encounter it again.
