### ISSUE TITLE
the error message of *def command is disordered when running internally

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4989]
xcat version: 

```
[root@c910f02c01p13 ~]# lsdef -v
lsdef - Version 2.14 (git commit b0ea8ec79232994f200c387af2ba9b4d4dbfd687, built Wed Mar 21 06:15:49 EDT 2018)
```
The error message of ``bmcdiscover`` is disordered when it hit database problem.

```
[root@c910f02c01p13 ~]# bmcdiscover --range  10.4.30.254 -u USERID -p PASSW0RD -w
Writing  (10.4.30.254) to database...
Error: Command failed: chdef. Error message: No object names were provided.
Usage: chdef - Change xCAT data object definitions.
  chdef [-h | --help ] [-t object-types]
  chdef [-t object-types] [-o object-names] [-n new-name] [node]
  chdef [-V | --verbose] [-t object-types] [-o object-names] [-d | --dynamic]    [-z | --stanza] [-m | --minus] [-p | --plus]    [-w attr==val [-w attr=~val] ... ] [noderange] [attr=val [attr=val...]]

The following data object types are supported by xCAT.
auditlogboottargeteventlogfirmwaregroupkitkitcomponentkitrepomonitoringnetworknodenotificationosdistroosdistroupdateosimagepdupolicyrackroutesitetaskstatezonezvmivp
Use the '-h' option together with the '-t' option toget a list of valid attribute names for each object type..

Error: create or modify node is failed.

```
The correct format of chdef error msg looks like this:
```
# chdef -t node -o '' bmc=10.4.30.254 groups=all
Error: No object names were provided.

Usage: chdef - Change xCAT data object definitions.

  chdef [-h | --help ] [-t object-types]

  chdef [-t object-types] [-o object-names] [-n new-name] [node]

  chdef [-V | --verbose] [-t object-types] [-o object-names] [-d | --dynamic]
    [-z | --stanza] [-m | --minus] [-p | --plus]
    [-w attr==val [-w attr=~val] ... ] [noderange] [attr=val [attr=val...]]


The following data object types are supported by xCAT.

auditlog
boottarget
eventlog
firmware
group
kit
kitcomponent
kitrepo
monitoring
network
node
notification
osdistro
osdistroupdate
osimage
pdu
policy
rack
route
site
taskstate
zone
zvmivp

Use the '-h' option together with the '-t' option to
get a list of valid attribute names for each object type.
```

**Comment by robin2008** [comment]
Move it to next release

**Comment by zet809** [comment]
The fix #4989 just fix the first part of the issue that bmcdiscover won't call chdef if not get the full node attributes.

**Comment by zet809** [comment]
Hi, @cxhong , you are right. The data after 6 have no '\n' in the end.

**Comment by zet809** [comment]
Hi, @cxhong , will you pls help cover this issue? Thx!

**Comment by cxhong** [comment]
the command behavior is different from CLI and Plugin routine.  
using error case of `chdef` as example, when called from plugin routine,  the output of defch_usage() will  treat as `error` and return to client as-is.   but for CLI,  each line in the defch_usage() will treat as ARRAY of `info`, when return to client, the client will add `\n` to each message.  in the client.pm:
```
if ($rsp->{info}) {
        #print "printing info\n";
        if (ref($rsp->{info}) eq 'ARRAY') {
            foreach my $text (@{ $rsp->{info} }) {
                my $desc = "$text";
                $desc = "[$msgsource]: $desc" if ($msgsource && $desc);
                print "$desc\n";
            }
        }
        else {
            my $desc = $rsp->{info};
            $desc = "[$msgsource]: $desc" if ($msgsource && $desc);
            print "$desc\n";
        }
    }
````
I don't know if i can remove `\n` right now, not sure how many logging code will affect if remove new line for each message. @zet809 , @hu-weihua , any suggestion?

anyway to take care of this issue, I will like to change
1) in the bmcdiscover plugin,  if hit chdef error, it will return error code but not error message 
2) for all the def usage subroutine in the `DBobjectdefs.pm`,  i will add space between each  datatype instead put each datatype to ARRAY.

**Comment by robin2008** [comment]
why we need print the error message from `chdef`? it is required to check the parameters before passing them to `chdef`.  Also print the error `command` when it pass our check and it still failed, so that user could easily know the cause.

**Comment by cxhong** [comment]
nothing changed if user run `chdef` from command line, it will show error message and chdef usage as before.
Ertao's PR#4992 will not call chdef if `bmcdiscover` command has invalid node object.   
in the PR#5220,  I modified if chdef failed in the `bmcdiscover` plugin, it will print out error message but not chdef usage
```
# bmcdiscover --range 172.20.253.104 -w
Error: Failed to run chdef command for node=
```

**Comment by hu-weihua** [comment]
Has been verified by 2.14.1 May 30 07:15:51 build . thanks @cxhong
