### ISSUE TITLE
[DEV] "xcatd: SSL listener" process keeps 100% cpu and all xCAT requests hang

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4996]
This issue is found on a large cluster with ~1000 nodes served by the management node, the `ps -elf` shows the cpu usage of "SSL listener" process is around 100%:

```
root       1149      1 97 12:26 ?        02:31:33 xcatd: SSL listener
root       1150   1149  2 12:26 ?        00:03:21  \_ xcatd: DB Access
root       1155   1149  0 12:26 ?        00:00:02  \_ xcatd: UDP listener
root       1157   1155  0 12:26 ?        00:00:00  |   \_ xcatd: Discovery worker
root       1156   1149  0 12:26 ?        00:00:00  \_ xcatd: install monitor
root       1158   1149  0 12:26 ?        00:00:00  \_ xcatd: Command log writer
```

any xcat command will hang

**Comment by immarvin** [comment]
the `journalctl -r -uxcatd` show the following `Too many open files at...` entries:
```
Mar 21 20:34:08 sierra4347 xcat[99526]: xcatd: possible BUG encountered by xCAT TCP service: Can't locate HTTP/Status.pm: Too many open files at /usr/share/perl5/vendor_perl/HTTP/Response.pm line 8.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/HTTP/Response.pm line 8.
Compilation failed in require at /usr/local/share/perl5/HTTP/Async.pm line 10.
BEGIN failed--compilation aborted at /usr/local/share/perl5/HTTP/Async.pm line 10.
Compilation failed in require at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 19.
BEGIN failed--compilation aborted at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 19.
Compilation failed in require at /opt/xcat/sbin/xcatd line 1900.
```

the  `ulimit -n` shows the max  open file number is the default value 1024:
```
[root@sierra4347:tmp]# ulimit -n
1024
```

the file handles opened by  `SSL listener`  has exceeded the limitation:
````
#ll /proc/1149/fd |wc -l
1025
````

the `SSL Listener` process stuck in a loop that
 1) accepting socket connection 
 2)failed to accept socket connections due to open file handle number limitation 
 3) go to step 1)

any newly coming requests from either CLI or nodes can not be sent to xcatd and just hang there until timeout

For xCAT management node managing over 1000 nodes, the open file handler limitation "1024" is insufficient, increase the value to a reasonable value can solve this

```
echo "ulimit -n 8192" > /etc/sysconfig/xcat
service xcatd restart
```
or using `prlimit` to change a running xcatd’s process without restart xcatd.
```
prlimit --pid `cat /var/run/xcat/mainservice.pid` --nofile=8192:8192
prlimit --pid `cat /var/run/xcat/mainservice.pid` | grep NOFILE
NOFILE     max number of open files                8192      8192```
```

**Comment by whowutwut** [comment]
@immarvin @robin2008 I think this issue is really a result of large systems and configuration of the limits.conf for number of file descriptors as well as TCP socket settings, is there anything planned to be added on the xCAT site, perhaps documentation updates in the reference architecture section for CORAL?  

It's moved to done but not in pending....

**Comment by immarvin** [comment]
we refined the code logic in xcatd(https://github.com/xcat2/xcat-core/pull/5005)  and added tips in tuning doc(https://github.com/xcat2/xcat-core/pull/5005) to cover this issue

**Comment by hu-weihua** [comment]
We have offer [Performance Tuning](http://xcat-docs.readthedocs.io/en/latest/advanced/performance_tuning/index.html) in RTD. So close this issue.
