### ISSUE TITLE
Unable to provision linux to KVM guest, though it gets network boot installation not going through

### ISSUE THREAD

**Issue by pharthiphan** [xcat2/xcat-core#5004]
Unable to provision linux to KVM guest

Installed, configure xCAT to provision network install but though KVM guest boots through network, installation not going through

[cluster.log](https://github.com/xcat2/xcat-core/files/1841156/cluster.log)
[commands.log](https://github.com/xcat2/xcat-core/files/1841157/commands.log)

# lsxcatd -a
Version 2.13.10 (git commit 4fe63ecd9f836f3cf447118d461e1c10c69b1652, built Fri Jan 26 00:09:41 EST 2018)
This is a Management Node
dbengine=SQLite
#

Please help

![installation gets stuck while using kvm](https://user-images.githubusercontent.com/18302174/37824581-1b893bfe-2eb3-11e8-94f4-1cc8b9bcf55d.PNG)

**Comment by immarvin** [comment]
hi @pharthiphan , did you see vmlinuz and initrd been downloaded from access_log of http server on MN?

**Comment by pharthiphan** [comment]
I can see GET request for vmlinuz but not initrd, Please help

[root@vime6-01 ~]# cat /var/log/httpd/error_log
[Sun Mar 25 03:29:02.107520 2018] [auth_digest:notice] [pid 22246] AH01757: generating secret for digest authentication ...
[Sun Mar 25 03:29:02.108451 2018] [lbmethod_heartbeat:notice] [pid 22246] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 25 03:29:02.108522 2018] [mpm_prefork:notice] [pid 22246] AH00163: Apache/2.4.6 (CentOS) SVN/1.7.14 configured -- resuming normal operations
[Sun Mar 25 03:29:02.108528 2018] [core:notice] [pid 22246] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[root@vime6-01 ~]# cat /var/log/httpd/error_log-20180325 
[Fri Mar 23 04:19:08.258628 2018] [suexec:notice] [pid 22246] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Mar 23 04:19:08.278320 2018] [so:warn] [pid 22246] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.52.101.201. Set the 'ServerName' directive globally to suppress this message
[Fri Mar 23 04:19:08.279003 2018] [auth_digest:notice] [pid 22246] AH01757: generating secret for digest authentication ...
[Fri Mar 23 04:19:08.279528 2018] [lbmethod_heartbeat:notice] [pid 22246] AH02282: No slotmem from mod_heartmonitor
[Fri Mar 23 04:19:08.282177 2018] [mpm_prefork:notice] [pid 22246] AH00163: Apache/2.4.6 (CentOS) SVN/1.7.14 configured -- resuming normal operations
[Fri Mar 23 04:19:08.282197 2018] [core:notice] [pid 22246] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sun Mar 25 03:29:02.078150 2018] [mpm_prefork:notice] [pid 22246] AH00171: Graceful restart requested, doing restart
[Sun Mar 25 03:29:02.104082 2018] [so:warn] [pid 22246] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.52.101.201. Set the 'ServerName' directive globally to suppress this message
[root@vime6-01 ~]# cat /var/log/httpd/access_log
[root@vime6-01 ~]# cat /var/log/httpd/access_log-20180325 
10.52.101.101 - - [23/Mar/2018:06:24:55 -0400] "GET /tftpboot/xcat/xnba/nodes/vcn01 HTTP/1.1" 200 393 "-" "iPXE/1.0.3-131028 (d603e)"
10.52.101.101 - - [23/Mar/2018:06:24:55 -0400] "GET /tftpboot/xcat/osimage/cnimage/vmlinuz HTTP/1.1" 200 5877760 "-" "iPXE/1.0.3-131028 (d603e)"
[root@vime6-01 ~]#

**Comment by immarvin** [comment]
hi @pharthiphan , would you please provide the information of your kvm hypervisor? the os, qemu and kvm and libvirt related versions. we might need to try to recreate this in our env,

**Comment by pharthiphan** [comment]
please find the details below, it was the same issue with RHEL 7.4 aslo

```
cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```
```
# rpm -qa | egrep "qemu|kvm|libvirt"
libvirt-libs-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-interface-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-nwfilter-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-config-network-3.2.0-14.el7_4.9.x86_64
qemu-kvm-common-1.5.3-141.el7_4.6.x86_64
libvirt-daemon-driver-storage-mpath-3.2.0-14.el7_4.9.x86_64
libvirt-gobject-1.0.0-1.el7.x86_64
libvirt-daemon-config-nwfilter-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-storage-gluster-3.2.0-14.el7_4.9.x86_64
qemu-common-2.0.0-1.el7.6.x86_64
libvirt-daemon-driver-qemu-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-storage-3.2.0-14.el7_4.9.x86_64
libvirt-client-3.2.0-14.el7_4.9.x86_64
libvirt-python-3.2.0-3.el7_4.1.x86_64
libvirt-daemon-driver-network-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-storage-rbd-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-nodedev-3.2.0-14.el7_4.9.x86_64
libvirt-gconfig-1.0.0-1.el7.x86_64
qemu-guest-agent-2.8.0-2.el7.x86_64
libvirt-daemon-kvm-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-lxc-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-storage-logical-3.2.0-14.el7_4.9.x86_64
qemu-kvm-1.5.3-141.el7_4.6.x86_64
qemu-img-1.5.3-141.el7_4.6.x86_64
libvirt-daemon-driver-storage-disk-3.2.0-14.el7_4.9.x86_64
ipxe-roms-qemu-20170123-1.git4e85b27.el7_4.1.noarch
libvirt-daemon-driver-storage-iscsi-3.2.0-14.el7_4.9.x86_64
libvirt-3.2.0-14.el7_4.9.x86_64
qemu-system-x86-2.0.0-1.el7.6.x86_64
libvirt-daemon-driver-storage-scsi-3.2.0-14.el7_4.9.x86_64
libvirt-glib-1.0.0-1.el7.x86_64
libvirt-daemon-driver-storage-core-3.2.0-14.el7_4.9.x86_64
libvirt-daemon-driver-secret-3.2.0-14.el7_4.9.x86_64
# 
```

**Comment by samveen** [comment]
@pharthiphan Can you show me the contents of /tftpboot/xcat/xnba/nodes/vcn01? AFAIK, KVM based VMs should request pxelinux configuration instead of xnba configuration. (from `/tftpboot/pxelinux.cfg/` instead of `/tftpboot/xcat/xnba/nodes/`).

**Comment by immarvin** [comment]
hi @pharthiphan , would you please modify the netboot attribute to `pxe`, then rinstall?

**Comment by pharthiphan** [comment]
After changing from xnba to PXE it worked. Thank you so much




Get Outlook for Android







On Thu, Mar 29, 2018 at 12:31 PM +0530, "yangsong" <notifications@github.com> wrote:












hi @pharthiphan , would you please modify the netboot attribute to pxe, then rinstall?
