### ISSUE TITLE
xCAT REST interface file has wrong permissions

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5019]
When trying to use xCAT REST, this error is logged into `/var/log/httpd/ssl_error_log` file:

```
Permission denied: exec of '/opt/xcat/ws/xcatws.cgi' failed
``` 

After changing the execute permission on that file to "all" xCAT REST works.
Should execute ermissions for this file be set by default on install ?

**Comment by samveen** [comment]
If not, then atleast add a appropriate section to xcat2/xcat-core/blob/master/docs/source/advanced/restapi/restapi_setup/restapi_setup.rst

**Comment by zet809** [comment]
Oh, in even 2.13.7, the file is an  executable file, but removed when merge Zvm related PR, maybe we didn't change it to be executable when adding it back.
Thx, @samveen , we will change the file access permission.

**Comment by zet809** [comment]
The execute permission of xcatws.cgi is changed in PR #5037
