### ISSUE TITLE
exlist has minor typo error and redundant entries

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5023]
Provided exlist: /opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64.exlist
1. ./usr/share/man*   this line appears twice
2. ./lib/kdb/keymaps/include*  this line seems to have a typo error:  'kdb' should be 'kbd'
3. the following first line, should make the 2nd line not required:
./usr/share/doc*
./usr/share/doc/packages/cyrus-sasl/doc*

Reference doc:  http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/trim_diskless_rootimg.html?highlight=exlist

lsxcatd -a
Version 2.14  built Tue Mar 27 06:15:43 EDT 2018

**Comment by marksmit-ibm** [comment]
It occurs to me that issue #3 may be there on purpose to help if the user wants to easily add back in, like this (just a guess on my part)
+ ./usr/share/doc/packages/cyrus-sasl/doc*

**Comment by immarvin** [comment]
hi @bybai ,would you please take a look at this?

**Comment by bybai** [comment]
Hi @marksmit-ibm , thanks your suggestions, will look into it.

**Comment by immarvin** [comment]
hi @marksmit-ibm , will the duplicate entries break anything?

**Comment by marksmit-ibm** [comment]
As long as a user sees both entries and chooses to remove, or comment out, both entries when they _do_ want man pages, then they would get the expected outcome.  I'm just thinking we should remove one for usability.  I have looked at the list many times and only when I did a grep/compare of line by line with another exlist, did I see the duplicate.
