### ISSUE TITLE
xCAT REST API doc and sending pw investigate work

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5031]
Currently xCAT REST API provides functionality similar to `lsdef` command. For example:
```
[gurevich@c910loginx01 xcat-core]$ curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn15+1/attrs/mgt?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "mid05tor12cn16":{
      "mgt":"openbmc"
   },
   "mid05tor12cn15":{
      "mgt":"openbmc"
   }
}
```
OR
```
[gurevich@c910loginx01 xcat-core]$ curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn15+1/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "mid05tor12cn16":{
      "nodestat":"sshd"
   },
   "mid05tor12cn15":{
      "nodestat":"sshd"
   }
}
```

1. It would be useful for the CORAL customers to have a REST API with a more compact output similar to the `nodels` command, where just a list of nodes is returned.
```
{
   "mid05tor12cn16",
   "mid05tor12cn15"
}
```
2. There seems to be a difference in the output depending on the way the noderange is specified (comma reparated vs. `[]`). We should make it more consistent, if possible:
```
[gurevich@c910loginx01 xcat-core]$ curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn15,mid05tor12cn16/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "mid05tor12cn16":{
      "nodestat":"sshd"
   },
   "mid05tor12cn15":{
      "nodestat":"sshd"
   }
}

[gurevich@c910loginx01 xcat-core]$ curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn[15-16]/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'

[1/2]: https://briggs01/xcatws/nodes/mid05tor12cn15/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1 --> <stdout>
--_curl_--https://briggs01/xcatws/nodes/mid05tor12cn15/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1
{
   "mid05tor12cn15":{
      "nodestat":"sshd"
   }
}

[2/2]: https://briggs01/xcatws/nodes/mid05tor12cn16/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1 --> <stdout>
--_curl_--https://briggs01/xcatws/nodes/mid05tor12cn16/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1
{
   "mid05tor12cn16":{
      "nodestat":"sshd"
   }
}
```

3. The documentation suggests to increase the timeout because some commands like `copycds` could take a long time, why would we block while `copycds` is executing, shouldn't it just trigger a `copycds` and then a query should show either the osimage is there or it's not there....
#5019 

4. Investigate if it is possible to avoid sending pw on each REST call, can we implement something similar to the way OpenBMC works, where a login is first required and user/pw is saved in a `cjar` file (`-c cjar`. This file can then be used for next REST call without explicitly giving userid/pw (`-b cjar`)?

```
curl -c cjar -k -X POST -H "Content-Type: application/json" -d '{"data": [ "root", "<root-pw>" ] }' https://$BMCIP/login

curl -b cjar -k https://$BMCIP/xyz/openbmc_project/xxxxxx
```

**Comment by bybai** [comment]
Hi @gurevichmark, 
For: "It would be useful for the CORAL customers to have a REST API with a more compact output similar to the nodels command, where just a list of nodes is returned." 
I think the following REST API output is similar to the nodels command, is it not enough?
```
pd]# curl -X GET --cacert /root/ca-cert.pem 'https://bybc0602.cluster.com/xcatws/nodes?userName=wsuser&userPW=cluster'
["bybc0605","bybc0607","bybc0609","c699login01","hpcmn-test","node000111","node01","node1","node1-pub","s01r1b01","simulation_test","sn4b","test01","test13","testnode1","testnode1_public"]
```

**Comment by gurevichmark** [comment]
No, this is not quite what they want. the `https://bybc0602.cluster.com/xcatws/nodes` returns all nodes.
What they want is send a noderange and get back a list of nodes matching that range:
`https://briggs01/xcatws/nodes/mid05tor12cn15+1/nodels`
OR
`https://briggs01/xcatws/nodes/mid05tor12cn[15-20]/nodels`

**Comment by bybai** [comment]
Hi @gurevichmark , I got your points here, I think there are 3 tasks as following, so I created a new feature request to trace 1 , you can use this task to trace 2 and 3. 
1, xCAT REST API that returns output similar to nodels range command, use this task  https://github.com/xcat2/xcat2-task-management/issues/38 to trace, and I will commit a pull request next day.
2, enhance REST API document as PR #5032 
3, Investigate if it is possible to avoid sending pw on each REST call here.

**Comment by bybai** [comment]
Hi @gurevichmark , I created pull request to add rest api for nodels, please review https://github.com/xcat2/xcat-core/pull/5050

**Comment by bybai** [comment]
For above 2 noderange thing, should use URL format,  command like following can get correct result:
```
[root@briggs01 ws]# curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn0\[1-3\]/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "mid05tor12cn01":{
      "nodestat":"noping"
   },
   "mid05tor12cn02":{
      "nodestat":"noping"
   },
   "mid05tor12cn03":{
      "nodestat":"noping"
   }
}
```

**Comment by bybai** [comment]
Hi @gurevichmark , I think you are working on above sending passwd investigate 4, I am not sure if you plan to finish it within 2.14 or not, so I move milestones from 2.14 to 2.14.1.

**Comment by gurevichmark** [comment]
Item 3 from above is already in our code. Our code already allows creating a token and then using this token on REST API calls. 
Nothing left to do for this issue.
