### ISSUE TITLE
Missing paramiko dependency by xCAT-openbmc-py package

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5034]
It looks like PR #4837 missed a dependency for `python-paramiko`. 

So on a fresh install of xCAT, we hit this problem: 
```
/opt/xcat/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py:13: RuntimeWarning: Patching more than once will result in the union of all True parameters being patched
  monkey.patch_all()
Traceback (most recent call last):
  File "/opt/xcat/lib/python/agent/xcatagent/server.py", line 87, in _handle
    req['module'])
  File "/opt/xcat/lib/python/agent/xcatagent/base.py", line 18, in get_manager_func
    raise ImportError(err)
ImportError: cannot import name NoValidConnectionsError
```

**Comment by whowutwut** [comment]
It looks like EPEL provides one at version `1.16.1-2.el7`  but we are looking for the one that is provided by RHEL extras at `2.1.1-2.el7` ..  Is this a requirement @zet809 , If so we have to put a version on that rpm.

**Comment by robin2008** [comment]
Do we really need 2.1.1?

**Comment by whowutwut** [comment]
I’m not sure. There is some strange set up on this cluster too as someone doenloaded anaconda python and set that in the path. That had some issues in loading default libraries...

**Comment by robin2008** [comment]
`NoValidConnectionsError` is introduced in 1.15.5, but I found that an old paramiko version 1.15.2 is installed by PIP on your environment (you could try `pip list|grep paramiko`), so even if you install the right RPM, the old 1.15.2 is still used by `xcat`.  And I rename its egg file for a temporary try (`/usr/lib/python2.7/site-packages/paramiko-1.15.2-py2.7.egg`), xcat works fine. I recovered this change and made some changes on xcat codes.
```--- /opt/xcat/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py    2018-03-31 23:53:39.157822327 -0500
+++ /opt/xcat/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py.orig    2018-03-31 23:56:56.009377033 -0500
@@ -13,10 +13,7 @@
 monkey.patch_all()
 from gevent import sleep
 import paramiko
-try:
-    from paramiko.ssh_exception import NoValidConnectionsError
-except:
-    from socket import error as NoValidConnectionsError
+from paramiko.ssh_exception import NoValidConnectionsError

 import time```
As only rspconfig will rely on paramiko,  we don’t know if it works well with paramiko 1.15.2,  but I think xcat need to add specific version for dependency there.

**Comment by robin2008** [comment]
Also need to isolate rspconfig with other features, as paramiko and scp is only specific to `rspconfig`, better to not impact other function.

**Comment by robin2008** [comment]
Uisng both PIP and RPM will mess the running environment, that's why I prefer to use our own directory instead of the system default one. As for those ones, it could be controlled by xcat, instead messed up by user or other applications.

**Comment by robin2008** [comment]
address it by https://github.com/xcat2/xcat-core/pull/5042
