### ISSUE TITLE
[fvt]2.11:sles12.1 ppc64le diskfull install failed on p8levm

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#504]
How to reproduce:
1.download the latest build
2.nodeset vm osimage
rpower vm boot
---------------------->then p8le vm install will hang here
 tail -f /var/log/consoles/vm
 ----------------->
 root@localhost bumped root@localhost -- Tue Dec  1 21:26:54 2015
opal_async_comp_init: Opal node not found
Moving into tmpfs... done.
Integrating /parts/00_lib
insmod /modules/squashfs.ko
/parts/00_lib: type = squashfs.
mount: /parts/00_lib: we need a loop device
mount: using /dev/loop0
Integrating /parts/01_usr
/parts/01_usr: type = squashfs.
mount: /parts/01_usr: we need a loop device
mount: using /dev/loop1^

21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(addLine):656 Adding Line 1 "mdadm: No arrays found in config file or automatically" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(getUntilEOF):622 pid:2918 added lines:1 stderr:true 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):336 stopwatch 0.018058s for "/sbin/mdadm --assemble --scan --config=/tmp/libstorage-lwxiMp/mdadm.conf" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):356 system() Returns:1 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(logOutput):674 stderr:mdadm: No arrays found in config file or automatically 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] Storage.cc(waitForDevice):8282 calling prog:/sbin/udevadm settle --timeout=20 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(SystemCmd):62 constructor SystemCmd( "/sbin/udevadm settle --timeout=20" ) doThrow: false 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(execute):134 SystemCmd Executing: "/sbin/udevadm settle --timeout=20" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):336 stopwatch 0.009370s for "/sbin/udevadm settle --timeout=20" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):356 system() Returns:0 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] Storage.cc(waitForDevice):8284 returned prog:/sbin/udevadm settle --timeout=20 retcode:0 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] DmraidCo.cc(activate):134 old active:false val:true 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(SystemCmd):83 constructor SystemCmd() 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] Dm.cc(activate):514 old active:false val:true 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(SystemCmd):83 constructor SystemCmd() 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(execute):134 SystemCmd Executing: "/sbin/dmsetup version" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(addLine):656 Adding Line 1 "Library version:   1.03.01 (2015-05-15)" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(addLine):656 Adding Line 2 "Driver version:    4.26.0" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(getUntilEOF):622 pid:2920 added lines:2 stderr:false 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):336 stopwatch 0.008905s for "/sbin/dmsetup version" 
Dec  1 21:31:49 c910f03fsp03v10 yast2[2762]:  <1> [libstorage] SystemCmd.cc(doExecute):356 system() Returns:0 

 BUG: soft lockup - CPU#0 stuck for 22s! [btrfs-delayed-m:2956]

**Comment by cxhong** [comment]
@junxiawang , can u able to recreate this issue every time?  We have a test machine with few ppc64le VMs.  I couldn't able to create this issue.   We saw one of VM stucked on some loop, but eventually successful booted.

**Comment by immarvin** [comment]
hi, I can not recreate the problem on firestone and vm with SLE-12-SP1-Server-DVD-ppc64le-GMC3-DVD1.iso.
````
[root@c910f03c05k23 ~]# lsdef c910f05c33 -i status
Object name: c910f05c33
    status=booted
````

````
[root@c910f02c01p17 ~]# lsdef c910f03fsp03v11 -i status
Object name: c910f03fsp03v11
    status=booted
````

I suggest FVT run the sles12sp1 diskful provision cases in our autotest environment, check whether this issue can be recreated

**Comment by whowutwut** [comment]
@daniceexi @junxiawang  why is this issue closed?  We should have some remarks when closing the issue.  I thought this was still "trying to recreate" Was it resolved after running sles12 SP1 through autotest environment?
