### ISSUE TITLE
[fvt］The output of rvitals did not satisfy 3 sections format

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#5054]
xcat version:
```
[root@f6u13k10 hwh]# lsdef -v
lsdef - Version 2.14 (git commit f7867c9e516f28843b498e69399c6029adf52bca, built Tue Apr  3 06:15:43 EDT 2018)
```

For the output of ``rvitals``, we expected it satisfy 3 section format, for example:
```
[root@f6u13k10 ~]# rvitals f6u03
f6u03: Ambient: 25.026 C
f6u03: Fan0 0: 0 RPMS
f6u03: Fan0 1: 0 RPMS
f6u03: Fan1 0: 0 RPMS
f6u03: Fan1 1: 0 RPMS
```

But there are some lines did not follow this format

```
------START::rvitals_outputs_format_checking::Time:Tue Apr  3 23:44:18 2018------

RUN:rvitals f6u03 | grep -v -E '^[^:]+:[^:]+:[^:]+$' [Tue Apr  3 23:44:18 2018]
ElapsedTime:2 sec
RETURN rc = 0
OUTPUT:
f6u03: Front . . . . . : Power:Blink Fault:Off Identify:Off
f6u03: Rear  . . . . . : Power:Blink Fault:Off Identify:Off
CHECK:rc == 1	[Failed]

------END::rvitals_outputs_format_checking::Failed::Time:Tue Apr  3 23:44:20 2018 ::Duration::2 sec------
------Total: 1 , Failed: 1------
```

This is maybe a problem.

**Comment by robin2008** [comment]
# rvitals mid05tor12cn16|wc
    111     666    4475
# tabedit site

For pyhon:
# rvitals mid05tor12cn16|wc
    115     726    4898

**Comment by xuweibj** [comment]
The output below is the output of ``rvitals leds``.
```
f6u03: Front . . . . . : Power:Blink Fault:Off Identify:Off
f6u03: Rear  . . . . . : Power:Blink Fault:Off Identify:Off
```
For command ``rvital <noderange>`` means ``rvitals <noderange> all``. I think we should print out leds information for ``rvitals all`` too, and have modified code in python.

**Comment by robin2008** [comment]
So there is a design change for `rvitals <noderange> all`, and now its output including `rvitals leds`
But the changes is only in python, not in perl.

Okay, now we know it is not related to code bug, this might not be an urgent issue to be covered before April 6.

**Comment by whowutwut** [comment]
Discussed with @gurevichmark today and he will create a PR to address this, making the output in single lines.

**Comment by gurevichmark** [comment]
Proposed output:
```
mid08tor03cn01: Ps1 Output Current: 18.625 Amps
mid08tor03cn01: Ps1 Output Voltage: 12.218 Volts
mid08tor03cn01: Total Power: 358 Watts
mid08tor03cn01: LEDs Front Power: On
mid08tor03cn01: LEDs Front Fault: On
mid08tor03cn01: LEDs Front Identify: Off
mid08tor03cn01: LEDs Fan0: X
mid08tor03cn01: LEDs Fan1: X
mid08tor03cn01: LEDs Fan2: X
mid08tor03cn01: LEDs Fan3: X
mid08tor03cn01: LEDs Rear Power: On
mid08tor03cn01: LEDs Rear Fault: On
mid08tor03cn01: LEDs Rear Identify: Off
```

**Comment by hu-weihua** [comment]
Have been verified in automation environment, close this issue. thanks @xuweibj and @gurevichmark
