### ISSUE TITLE
Result for "pscp -v|-h" are not as excepted

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#506]
OS: x86, sles11.4

c910f0 # pscp -v
No node range specified
Usage: pscp [ -f fanout] [-i <SUFFIX>] [SCP OPTIONS...] FILE... <NODERANGE>:<DESTINATION>

c910f0 # pscp -h
No node range specified
Usage: pscp [ -f fanout] [-i <SUFFIX>] [SCP OPTIONS...] FILE... <NODERANGE>:<DESTINATION>

c910f0 # psh -v
Unknown option: v
Usage: psh [-i <interface>] [-l <user>] [-f <fanout>] [--nonodecheck] [-t <timeout value in seconds>] <noderange> <command>

**Comment by whowutwut** [comment]
@bybai  If we have a 2.11 RC3 build, should this be included?  Or just fix in 2.12?

**Comment by bybai** [comment]
@whowutwut Since there are man pages for psh and pscp, the priority is low, we can just fix them in 2.12.
