### ISSUE TITLE
Add lsdef interface for REST token management

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5081]
xCAT has a `token` table to store REST API authentication tokens. 
```
[root@briggs01 gurevich]# tabdump token
#tokenid,username,expire,comments,disable
"a6815f52-d6cc-4885-be6f-e9133b6f8c40","wsuser","1523464789",,
"3326f83f-2242-4f8b-9a48-b062ff21fc7b","wsuser","1523464852",,
"2cefb5dc-c9d2-4c25-8198-57100be1eae5","wsuser","1523472597",,
"8d32daa9-ab61-4829-8105-bb95ebda2ffb","wsuser","1523472735",,
"bc1ae1a5-12c3-49e8-8954-4ae6f97cda06","wsuser","1523472829",,
"bd901309-3c39-4a0f-aa38-da32b1b89edb","wsuser","1523472861",,
"4a4ffc14-1687-4469-a5d8-1e24acf4a63d","wsuser","1523472922",,
"123388d3-04f1-43a0-a95f-cf4ee1836fc0","wsuser","1523472952",,
"4f80fde9-ba65-4c59-86f1-f9ae1f2ed5fe","wsuser","1523473377",,
"c078319f-4ad1-4d3a-9792-2abee1de6899","wsuser","1523473835",,
[root@briggs01 gurevich]#
```
But `tokens` is not one of the supported object types. Would be useful if admin could
revoke these tokens with `rmdef -t token xxxxxxx`. Or if admin could adjust the expiration time with
`chdef -t token xxxxxx expire=yyyyyyy`. Or if admin could list tokens and have a human readable expiration time with `lsdef -t token`

**Comment by bybai** [comment]
Now token is used by xCAT REST API.  I think it is better to use xCAT REST API to manage token resource. PUT method is to adjust the expiration time, GET method is to list tokens.

**Comment by robin2008** [comment]
`token` is just a simple implementation in xCAT now,  and no user management too.
Better to provide some APIs by simple, instead of support full `*def` for it.

**Comment by daniceexi** [comment]
@bybai I only saw the POST is supported for token creating, could you confirm whether the 'GET' and 'POST' are supported?

**Comment by bybai** [comment]
Hi @daniceexi, @robin2008 and @gurevichmark , 'GET' and 'PUT' are not supported for token resource now. We can use `tabedit token` or `tabch` to change the expire time like  :`tabch tokenid="2649d2be-877b-44a3-9301-5b9c9bd64cbf" token.expire=2023519000`. 
 I think here we can enhance the following:
1, add 'GET' and 'PUT' method for token resources
2, change the expire time format in `token` table to human readable expiration time format, now its format is unix timestamp like "2023519000",  better human readable format can like "2034-02-14 00:00:00".

**Comment by gurevichmark** [comment]
I am planning to add item 2 from above (make token expiration human readable) under #5082.

**Comment by immarvin** [comment]
hi @gurevichmark , any update on this?is it ok to close?

**Comment by gurevichmark** [comment]
I do not know, maybe @whowutwut or @zet809 can make this decision.

We have a `token` table, but currently REST API can not access it. If we feel it is important that REST API is complete, we should keep this issue open.

**Comment by whowutwut** [comment]
Let's keep it open but we can put it in the icebox for now...

**Comment by gurevichmark** [comment]
Due to limited resources, this issue will not be addressed.
