### ISSUE TITLE
Add attribute to site table to allow non-default REST API authentication token expiration

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5082]
Currently REST API authentication token expires in 24 hours.
Add a new attribute to `site` table to allow the user to specify how may days or `never` for token expiration.
Default will still stay at 24 hours.

**Comment by gurevichmark** [comment]
Code for managing tokens is in xCAT-server/lib/perl/xCAT/xcatd.pm gettoken().

**Comment by robin2008** [comment]
I am not sure it is good to given a `never` expire token for all user,  it would be potential security risk.

I would suggest there are two steps to get an long-lived token.
1, get a short lived token first  (this is for all user)
2, Provide a new API to change its to expire time, and this API could be controlled by `policy` table, to assign it for only `service` account.

For normal user, they will still get a short-lived token.

**Comment by bybai** [comment]
I think after we change the expire time format as human readable format, it is easy for user to customize the expire time to a long time as they expect. It is no need to support `never` expire token in our code considering security risk. 
Now, user can change expire time in `token` table using `tabedit` or `tabch` command, if we can provide REST API interface to change expire time, user can use or integrate the REST API to update the token expire time as they expect.

**Comment by gurevichmark** [comment]
Had a meeting with Fernando and Victor today. They felt for CORAL and CSM use, it would be useful to have a ability to modify token expiration time by just changing `site` table entry. This way it can be changed for the whole cluster and all tokens created after that point will have new expiration time. They also wanted ability to have a token that `never` expires, similar to how GitHub manages tokens.

**Comment by gurevichmark** [comment]
This issue will also be used to add "creation" time of the token and "last" access time of the token to the `token` table.
All times will be stored in human readable format.
