### ISSUE TITLE
[Customer]Xcat extenstion development for Ubuntu Juju Charms applications 

### ISSUE THREAD

**Issue by topstarnetwork** [xcat2/xcat-core#51]
Hello,
would it be possible to develop a Xcat extenstion for Ubuntu Juju Charms applications?
Here is the link for more info https://juju.ubuntu.com/

This would make it more easy and fast to instal Xcat on my Ubuntu server.

**Comment by whowutwut** [comment]
@topstarnetwork , very sorry for the very late response,  this kind of slipped through the cracks... we are looking at some unassigned issues as we get ready for the xCAT 2.11 release.  Is this still something you are interested in? 

We had looked at Juju very briefly but not really sure about the Use Case for this.  If it's only covering the install process of xCAT and putting it inside a charm, not sure the value added there.  Could you describe the scenario you are working on?  

We are preparing the new documentation on ReadTheDocs for the 2.11 release, the Ubuntu sections are still missing a bit but should be filled in better within the next month.  The configuration of the noodes and networks are still something that the user would need to do after xCAT is installed.. .

I think the Juju support would be lower on our priority list, we always welcome new contributors to help work on functions like this if you are willing to sign the CLA and participate.

**Comment by whowutwut** [comment]
There's a group within IBM that is creating charms for various IBM products, xCAT being one of them.  There was an initial effort last year to charm xCAT and a simple release of it is available here:   https://jujucharms.com/u/ibmcharmers/xcat/trusty/0

I've been in communication with the folks who are going to make some improvements this year, I'm going to close this issue as the link above should be used to view the latest progress.

**Comment by topstarnetwork** [comment]
Oh I also apologise for this late reply, I missed your response,
well I changed my mind, I would like to evoluate with webmin instead as   webmin is bsd license http://webmin.com/
webmin is written in perl just like xcat, it would be nice to have a webmin xcat plugin  module,
this would make it easy to go.

Cloudmin is nice but not bsd license   http://webmin.com/cloudmin.html
