### ISSUE TITLE
REST API does not respect the "host" setting in "policy" table.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5111]
If "host" field in "policy" table is not set, REST API calls from other hosts like `c910loginx01` work well.
But if "host" field in "policy" table is set to `"c910loginx01.pok.stglabs.ibm.com"` or `"c910loginx01"`, REST API call fails with:
```
[gurevich@c910loginx01 ~]$ hostname -A
c910loginx01.pok.stglabs.ibm.com c910loginx01
[gurevich@c910loginx01 ~]$ curl -X GET -k 'https://briggs01/xcatws/nodes/p9up/nodestat?userName=wsuser&userPW=<xxxx>&pretty=1'
{
   "errorcode":"2",
   "error":"Authentication failure"
}

[gurevich@c910loginx01 ~]$
```

**Comment by gurevichmark** [comment]
Do you think we should fix this? Perhaps if `xcatws.cgi` has the name of the host from which the request came, it can be forwarded to `xcatd` for checking against `policy` table ?

Or should we just change the docs, because currently this sounds like `host` attribute can be used for REST API:
```
host

    The host from which users may issue the commands specified by this rule. Default is “*” (all hosts). Only all or one host is supported
```

**Comment by zet809** [comment]
Seems yes, OK, let me check that. Thx for point it out, @gurevichmark
