### ISSUE TITLE
Using copycd to generate cumulus OS image

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#5117]
Based on this minidesign: https://github.com/xcat2/xcat-core/wiki/The-mini-design-of-syncfiles-for-cumulus, create this issue for step1.  open discussion for new plug in name and osimage name:
1) plug in name:  onie.pm, cumulus.pm or armel.pm ?
2) osimage name:  cumulus-3.5.2-armel ?
the output of cumulus os bin file:
````
# ./cumulus-linux-3.5.2-bcm-armel.bin
Verifying image checksum ...OK.
Preparing image archive ... OK.
Control File Contents
=====================
Description: Cumulus Linux 3.5.2
Release: 3.5.2
Architecture: armel
Switch-Architecture: bcm-armel
Build-Id: bab9bc5z1d1b1f3
Build-Date: 2018-01-31T00:41:00+0000
Build-User: clbuilder
Homepage: http://www.cumulusnetworks.com/
Min-Disk-Size: 1073741824
Min-Ram-Size: 536870912
mkimage-version: cl3u13
````

**Comment by immarvin** [comment]
hi @cxhong , there is some update on the `copycds` part in https://github.com/xcat2/xcat-core/wiki/The-mini-design-of-syncfiles-for-cumulus

**Comment by whowutwut** [comment]
@immarvin Going to comment about the first step documented in the mini design here, this task seems to track the copycds work item.   Can you create an EPIC for this and include this task into the epic.. 

I think you should provide the full path to the bin file in the osimage definition: 

```
# copycds cumulus-linux-3.5.2-bcm-armel.bin
...
lsdef -t osimage -o ...
Object name: cumulus3.5.2-armel
    imagetype=onie
    osarch=armel
    osvers=cumulus3.5.2
    pkgdir=/install/cumulus3.5.2/armel/cumulus-linux-3.5.2-bcm-armel.bin
...
    postscripts=xxxx
    postbootscripts=xxxx
```

This will allow the user to specify a different bin file and putting multiple .bin files into that directory won't break this...

**Comment by immarvin** [comment]
the epic : https://github.com/xcat2/xcat2-task-management/issues/59
