### ISSUE TITLE
Support nodeset <switch> osimage command for cumulus switch

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#5126]
for Epic:
https://github.com/xcat2/xcat2-task-management/issues/59

nodeset performs the following operations:
(1) find the ".bin" file under the first entry in osimage.pkgdir, then copy the ".bin" to /install/osimages/cumulus3.5.2-armel
(2)assign the node.provmethod to the osimage name
(3)run "makedhcp -a ", generate the dhcp lease with full path to the bin file in default-url option

nodeset mid05tor12 osimage=cumulus3.5.2-armel
[root@briggs01 ~]# lsdef mid05tor12
Object name: mid05tor12
    groups=switch,edge_switch
    ip=172.11.205.12
    mac=xx:xx:xx:xx:xx:xx
    mgt=switch
    netboot=onie

**Comment by cxhong** [comment]
@immarvin ,  what's reason to copy `.bin` to a new location?  the `.bin` will be in the `osimage.pkgdir` already. I think the `default-url` can just point to `osimage.pkgdir`

**Comment by immarvin** [comment]
ok, the /install directory is accessible in http server

**Comment by zet809** [comment]
hi, @cxhong and @immarvin , what is the status of this task, have it been finished?

**Comment by immarvin** [comment]
the task is finished, close it

**Comment by tingtli** [comment]
https://github.com/xcat2/xcat-core/pull/5168
