### ISSUE TITLE
[healthy check]  To check if logging of xcatd is still alive

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5131]
`xcatd` depends on syslog to log its log message and using `rsyslog` into `/var/log/xcat/cluster.log`

Some upgrade will change `rsyslog` configuration, and also user might customize rsyslog by wrong,  it is required to have some kinds of capability to check it. (like `xcatprobe`)

And it is recommended to run it after upgrade,  or put `xcatprobe mn` into cron for check the health periodically.

For xCAT installation/upgrade testcase, it is required to run it to make sure the default is functional.

**Comment by robin2008** [comment]
Below is suggested way:
    - checking the service status (rsyslog, journald)
    - issuing a checking log and to see if it could be seen in /var/log/xcat/cluster.log*

For service nodes, there might be more special when customize the node attributes.

**Comment by xuweibj** [comment]
Check items:
1. rsyslog config: ``rsyslogd -N1``
2. rsyslog process: ``ps -A | grep rsyslog``
3. rsyslog service: ``service rsyslog status`` | ``systemctl status rsyslog.service``
4. Try to add log ``logger -p local4.debug -t xcat 'xcatprobe rsyslog checking'``, check whether in /var/log/xcat/cluster.log*

**Comment by robin2008** [comment]
verified on `Version 2.14.1 (git commit bed114d6b9779d48ba37447deb7842ec954e808e, built Tue May 22 06:15:46 EDT 2018)`

```
    Checking rsyslog service is configured...                                                                     [FAIL]
        rsyslog service is not running! Please check on current node
    Checking xCAT log is stored in /var/log/xcat/cluster.log...                                                   [WARN]
        Failed to store MN logs to /var/log/xcat/cluster.log
```

**Comment by whowutwut** [comment]
For completeness this check has been added to `xcatprobe xcatmn` option.
