### ISSUE TITLE
RFE: console broadcast mode

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5134]
I'd like to request an enhancement for the `rcons`/`wcons`, ie. the ability to broadcast commands to several consoles at once, similar to https://github.com/dun/conman

The rationale is that some older machines don't have very good management capabilities, and often require interactive input, such as BIOS menus. Having the possibility to input the same control sequences on multiple consoles simultaneously would be a tremendous improvement.

**Comment by immarvin** [comment]
hi @kcgthb , the support for goconserver has been merged, pls take a look

**Comment by kcgthb** [comment]
Hi @immarvin 

I wanted to give it a try, but stumbled upon #5313
