### ISSUE TITLE
Several SSL listener processes running

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5153]
Maybe this is related to #4996 , but on some of our machines there are several `SSL listener` processes running:

```
[root@stratton01 xcat]# ps -ef | grep "SSL li" | grep -v color
root       4615      1  0 Apr10 ?        00:38:33 xcatd: SSL listener
root       6698      1  0 09:38 ?        00:00:03 xcatd: SSL listener
[root@stratton01 xcat]#
```

```
[root@briggs01 ~]# ps -ef | grep "SSL li" | grep -v color
root      10167      1  0 Apr13 ?        00:00:00 xcatd: SSL listener
root      11168      1  0 Apr17 ?        00:00:00 xcatd: SSL listener
root      44539      1  0 Apr16 ?        00:00:00 xcatd: SSL listener
root     102160      1  0 09:35 ?        00:00:00 xcatd: SSL listener
[root@briggs01 ~]#
```

I am not able to recreate this, but it also appears to happen during the Travis testing, #5152

**Comment by immarvin** [comment]
hi @robin2008 , any idea on this? seems there is no dangling request process under xcatd

**Comment by robin2008** [comment]
```
# strace -p 44539
strace: Process 44539 attached
waitpid(-1,
```
SSL listener just wait for all children quit, and the children is pending.

```
# strace -p 44541
strace: Process 44541 attached
recv(12,


^Cstrace: Process 44541 detached
 <detached ...>
# strace -p 44550
strace: Process 44550 attached
recv(12, ^Cstrace: Process 44550 detached
 <detached ...>
# strace -p 44540
strace: Process 44540 attached
_newselect(16, [8], NULL, NULL, NULL
```

**Comment by robin2008** [comment]
After `kill 44540`, we can see two DB connection process is quit,  but SSL listener (44539) is 100% CPU, using strace to attach it and see below:
```
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
waitpid(-1, 0x3fffcd2917d4, 0)          = -1 ECHILD (No child processes)
```

**Comment by robin2008** [comment]
After add print message in codes, and found that the `$pid_UDP` does not be set to zero when the UPD child process is quit.  It will case the SSL block at the quit stage.

Check the `ssl_reaper`, fount that the below codes might cause such issue.
```
        if (($CHILDPID == $pid_UDP) && ($udpctl)) {

            # got here because UDP child is gone
            close($udpctl); $udpctl = 0;
            $pid_UDP=0;
```
if the UDP is reaper here and udpctl is 0, `$pid_UDP` will not be clean.

**Comment by robin2008** [comment]
Another possible cause is that the PID is not removed from `%immediatechildren` rightly when do `plugin_reaper`.  It might cause the case process is away but `%immediatechildren`  contains dirty data.

If then, need to check the remaining PID is alive.  But we do Not consider this time.  Here we want to modify:
- using non-block `waitpid` when SSL quit, and add a bit more logs 
- fix the `ssl_reaper` to clean `$pid_UDP`

**Comment by robin2008** [comment]
To address it in #5215

**Comment by robin2008** [comment]
Close it.
