### ISSUE TITLE
updatenode -k  does not check if the passwd is correct, only check if the passwd is input or not.

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#516]
1. After I installed a node, ssh the node, below message always showed up:
[root@c712ems2 setupnic]# ssh c712f5n12
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
e7:ac:1a:26:bf:77:40:93:35:18:80:a4:57:84:c8:45.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:40
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
2. Then I ran ' updatenode c712f5n12 -k'
[root@c712ems2 setupnic]# updatenode c712f5n12 -k
Enter the password for the userid: root on the node where the ssh keys
will be updated:
##(here I entered a wrong passwd)##

c712f5n12: Setup ssh keys has completed.
c712f5n12: xcatdsklspost: downloaded postscripts successfully
c712f5n12: Fri Dec  4 01:07:59 EST 2015 Running postscript: remoteshell
c712f5n12:
c712f5n12: root      25900  0.5  0.0  27136 17792 ?        Ss   01:07   0:00 sshd: root@notty
c712f5n12: root      26112  0.0  0.0  17920 11712 ?        Ss   01:08   0:00 /usr/sbin/sshd -D
c712f5n12: Postscript: remoteshell exited with code 0
c712f5n12: Running of postscripts has completed.
3.  then ssh c712f5n12 again, upper messages in step 1 are still there, no any change. 
What I expect is the messages in step 1 are disappeared after I ran `updatenode -k`.

*So there are 2 problems in this case:
**the updatenode -k doesn't check the passwd's correctness, with a wrong passwd, the progress can still go on. 
**With the wrong passwd input, the output shows everything is successful, but in fact, The same messages in step 1 still shows up  Nothing changed.

**Comment by whowutwut** [comment]
@wwzhubj  can you please try and format the posts that you create.  It just helps the readability overall and it is just a good habit to have.  It's really not hard. 3 back ticks around the code block. 

https://guides.github.com/features/mastering-markdown/

**Comment by wwzhubj** [comment]
# I tried to use star , but looks like it failed, you can see I used one star , two stars in the end#

**Comment by wwzhubj** [comment]
* I will improve the format to help the readability*

**Comment by whowutwut** [comment]
You can always edit your own posts by clicking on the pencil icon on the post: 
![image](https://cloud.githubusercontent.com/assets/10049070/11662176/6a5f0c5c-9da3-11e5-9d2e-e4ab52d5ef84.png)

The most helpful format for readability is to wrap the code block with backticks. 
![image](https://cloud.githubusercontent.com/assets/10049070/11662244/9cc9f134-9da3-11e5-9e3b-99de0e252ea5.png)

**Comment by cxhong** [comment]
If nodes already set up as passwordless, it will not check the password's correctness.  
Pull Request #509 will take care second problem.  
I also added the code to remove hostname from known_hosts file after nodes reset to get rid of "man-in-the-middle attack" message. #542
