### ISSUE TITLE
pcons?

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5167]
Hi!

The documentation mentions a `pcons` tool in  https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/parallel_cmd.html, and the RPMs install a manpage for it, but I can't seem to find it anywhere. Has it been removed from the toolkit?

**Comment by gurevichmark** [comment]
I do not know the history, but perhaps `pcons` got replaced by `wcons` ?

**Comment by chenglch** [comment]
I also do not know the history, `pcons` command is missing, maybe we need to delete the doc and man page about it. I will take action when the investigation is done.
