### ISSUE TITLE
postinstall support run custom scripts from a directory

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5175]
`postinstall` is used when run `genimage`,  user could customize the osimage attribute to specify their own scripts. For easy to use, it is better to specify a directory. For example, 
`/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.postinstall -p /install/xcat/osimages/rhels7.5-alt-rc2-ppc64le-ANSIBLE-netboot-compute/postinstall.d`

the order of script running will depends on alphabetical order.

**Comment by hu-weihua** [comment]
Move to 2.14.x

**Comment by robin2008** [comment]
close it no high priority.
