### ISSUE TITLE
rflash operation cause 100% CPU

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5176]
When doing an rflash to switch back to a previously firmware, Observed 'top' on one service node and the rflash main process is using 100% cpu.  And using `strace -p`, got below:
```
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
waitpid(-1, 0x7fffdedff3b4, WNOHANG)    = 0
```

**Comment by robin2008** [comment]
I think this is caused by 
`while ((my $cpid = waitpid(-1, WNOHANG)) > 0) {` in openbmc.pm plugin

we need to fix the wrong using of NOHANG waitpid.

Pay attention to python version too.

**Comment by zet809** [comment]
Hi, @xuweibj , will you pls help take a look at this issue? Thx!

**Comment by robin2008** [comment]
Now we make some enhancement in #5208, need to verify on the problem environment to see if it is working.

**Comment by robin2008** [comment]
Merged, and not found new issue on rflash, just close it.

**Comment by whowutwut** [comment]
Using May 30 build, this still happens....  

```
# lsxcatd -a
Version 2.14.1 (git commit f10d33f66c449b06104ce734f79af62d55c54564, built Wed May 30 06:15:48 EDT 2018)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=192.168.95.1|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=192.168.95.1
dbadmin=xcatadm
```

`strace -p` on this pid shows: 
```
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
waitpid(-1, 0x7fffce209364, WNOHANG)    = 0
```

**Comment by robin2008** [comment]
https://github.com/xcat2/xcat-core/pull/5274 is to address the missing part.

**Comment by robin2008** [comment]
Verified on Version 2.14.1 (git commit 70d6e7f93cc9714a127c22df2e7ca53d4996a34c, built Fri Jun  1 03:00:53 EDT 2018)

To hack codes to make `rflash_upload` run for long time, and 
run `rflash mid05tor12cn16 /mnt/xcat/iso/openbmc/910.1746.20171213a_1742Eh/obmc-phosphor-image-witherspoon.ubi.mtd.tar -a`

And monitor the rflash main process,  there is no high CPU, and the using `strace -p`, got below
```
waitpid(-1, 0x3fffe62308b4, WNOHANG)    = 0
_newselect(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
waitpid(-1, 0x3fffe62308b4, WNOHANG)    = 0
_newselect(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
waitpid(-1, 0x3fffe62308b4, WNOHANG)    = 0
_newselect(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
waitpid(-1, 0x3fffe62308b4, WNOHANG)    = 0
_newselect(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
```
Ok, the sleep is working in such case too.

**Comment by whowutwut** [comment]
@robin2008 did you inject multiple rflash calls on the same endpoint BMC? I believe this is what caused the problem to get exposed again...  Did we test this on a noderange or just a single node?  

Really we need the re-create process on the old code, then running the same test using the new code...   The above validation you ran does not do the same thing Mark Smith did to create this error case.

**Comment by hu-weihua** [comment]
@robin2008 Could you follow this issue again? FYI,  I will move it to 2.14.2.

**Comment by robin2008** [comment]
@whowutwut   there is no injection here for multiple processes, this issue is only for CPU 100%, we can close this one, and it is already fixed and confirmed by customer.

we can follow the  multiple access to same BMC in https://github.com/xcat2/xcat-core/issues/5276
