### ISSUE TITLE
"packimage -m tar" should be the default option of "packimage" for some sepcific OS

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#5191]
For ``rhels7.5``, ``rhels7.4``, ``ubuntu14.04.4``, must use ``packimage -m tar`` to package image, otherwise some link in the image will in incorrect status, non-root user will failed to run some command, suck like ``ping``. Refer to issue #922, PR #1602 and #1554.

If this is true, ``-m tar`` should be the default option for these kinds of OS.  PR #5187 has made ``-m tar`` as the default option for all kinds of OS. 

For ``sles11.4``, ``rhels6.9`` and ``ubuntu16.4.1``, these os can work well for ``packimage`` with cpio, not sure if they can work well with tar, need further verify. Open this bug to track this problem.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/5187
