### ISSUE TITLE
Ping not working for non root users on nfs based statelite compute node 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#5192]
After provisioning a nfs based statelite compute node, non root users can not run ``ping`` command.

```
[root@f6u13k15 ~]# df /
Filesystem                                                             1K-blocks     Used Available Use% Mounted on
10.6.13.13:/install/netboot/rhels7.5-alternate/ppc64le/compute/rootimg  36496896 13394432  21225472  39% /

[root@f6u13k15 ~]# ls -l /bin/ping
-rwxr-xr-x 1 root root 135976 May 22  2017 /bin/ping

[root@f6u13k15 ~]# su - xcatuser
Last login: Thu May 10 07:38:38 UTC 2018 on pts/0

[xcatuser@f6u13k15 ~]$ ping 127.0.0.1
ping: socket: Operation not permitted
```

**Comment by immarvin** [comment]
hi @bybai , would you please take a look at this? thx

**Comment by hu-weihua** [comment]
refer to #922

**Comment by bybai** [comment]
@hu-weihua , add the following line into `litefile` table, then execute `liteimg <osimage>; rinstall <cn> osimage`, can resolve this issue. let me consider if add notes in statelite doc. 
```
"ALL","/bin/ping","tmpfs",,
```

**Comment by bybai** [comment]
@immarvin, I found if ping permission is "-rwsr-xr-x" in rootimg, ping can work for non-root user in nfs-based statelite system. no need to add "/bin/ping" into litefile table. And add /bin/ping into litefile table is not correct way to resolve the issue.  For nfs-based statelite system,  our design limits many permissions by defaults, for example, when we want to add non-root user, we should use chroot in rootimg to useradd new user, we cannot directly add non-root user by default on nfs-based statelite system. So we can describe this way into doc.

**Comment by bybai** [comment]
In statelite OS scenario, if user want to change permission for one file, for example, /bin/ping. User should do 2 solutions:
**solution 1:**
1, add /bin/ping into `litefile` table like following, then /bin/ping permission is not ro.
```
"ALL","/bin/ping","tmpfs",,
```
2, make changes for /bin/ping after the node is booting, it can work by non-root user:
```
setcap cap_net_raw+ep /bin/ping
```
**solution 2** 
Directly change permission as following for usr/bin/ping under `rootimg`, after node is booting, it can work by non-root user:
```
 -rwsr-xr-x 1 root root 133K 5m  22 2017 usr/bin/ping
```

**Comment by bybai** [comment]
Verified as above steps, close this issue now. This will not be added into auto test bundle.
