### ISSUE TITLE
[Customer]Is xcat2 integrating all the IBM  z/VM 6.3.0 original software code and components?

### ISSUE THREAD

**Issue by topstarnetwork** [xcat2/xcat-core#52]
Hello,
Is xcat2 integrating all the IBM  z/VM 6.3.0 original software code and components?

Please check

http://www.vm.ibm.com/sysman/

http://www-01.ibm.com/support/knowledgecenter/SSB27U_6.3.0/com.ibm.zvm.v630.hcpo1/getlogs.htm

Does xcat has also for exemple the ibm  Backup and Restore Manager for z/VM  component?

For exemple here is a list of components wich I would like to know if htey are already integrated to xcat 2;

 http://www.vm.ibm.com/related/

**Comment by ligc** [comment]
Hello, 

xCAT is now hosted on sourceforge, we are experimenting with github and planning to migrate from sourceforge to github in the future, the github repos are not actively monitored for now, you could send the request to sourceforge xcat-user mailinglist at https://lists.sourceforge.net/lists/listinfo/xcat-user  

Thanks.

**Comment by chuckbrazie** [comment]
The current xCAT on sourceforge does not have the latest z/VM 6.3 built in xCAT code(2.8.3.6). I have to merge in the 2.10 code and verify that things work. The xCAT on z/VM does not come with those extra products you listed.
Chuck

**Comment by whowutwut** [comment]
Assigning this to Chuck as he's responsible for xCAT on Z...   I don't think this would be in the 2.11 release so labeling it future.

**Comment by tingtli** [comment]
@chuckbrazie  Do you have any comments for this issue?
