### ISSUE TITLE
Need a way to disable restarting openibd in configib

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#5200]
https://github.com/xcat2/xcat-core/blob/dfca6c2289b8468fc71a7c7534a1234cf5ef970f/xCAT/postscripts/configib#L670

I believe this line is causing issues during full cluster reboots.  Based on the git history, it has been there quite a while.  Is it still relevant for modern operating systems?  Would it be sufficient to just `start` the service in case it was not previously enabled?  If some people depend on the restart behavior, we need an option to be able to turn it off.

I commented it out for our local install, and nodes still came up with functional IB.

**Comment by neo954** [comment]
@mattaezell, It is great if you can provide detail information about the "causing issues" you met. Any problem reproduce steps, outputs, and error messages are welcome.

The `openibd` init script is used to load all the necessary kernel modules on boot up. While the end user run `configib` with xCAT. There might be a hardware change. Thus `restartservice openibd` might be needed. It should not cause any bad side-effect. If you hit on any bad side-effect/problem. Would you mind share it with us.
[1] http://people.redhat.com/dledford/infiniband_get_started.html

**Comment by hu-weihua** [comment]
It seems this line was already here when this script was first generated.  I though the original author followed the document of Mellanox  to code like this.

**Comment by bybai** [comment]
Hi @mattaezell and @whowutwut , 
`configib` make changes to the configuration file (/etc/rdma/rdma.conf or /etc/infiniband/openib.conf or /etc/modprobe.conf). I think ` restartservice $ib_driver ` is to take effect for changes to the confiuration file.  
So here can add a variable to record if these configuration files are changed or not, if there are changes happen, should execute `restartservice $ib_driver`, or else, do nothing. 

BTW: In `configib`,  here configures "SDP_LOAD" or "ib_ehca", I went through http://www.mellanox.com/related-docs/prod_software/Mellanox_OFED_Linux_User_Manual_v4_3.pdf, there is no any "SDP_LOAD" or "ib_ehca". "configuring SDP" can be found in  http://www.mellanox.com/related-docs/prod_software/Mellanox_OFED_Linux_user_manual_1_5_1.pdf. "ib_ehca" can be found in http://www.redbooks.ibm.com/redbooks/pdfs/sg247351.pdf.

**Comment by mattaezell** [comment]
@neo954 We are working through some CORAL full system boot time/functionality issues.  We are working with Mellanox to debug a problem where so many IB traps are sent to OpenSM that processing ports coming up becomes delayed.  Open one terminal and start tail'ing the OpenSM log (on UFM it's `/opt/ufm/files/log/opensm.log`).  In another terminal, login to an xCAT client node and run `systemctl restart openibd`.  Notice the output in the OpenSM window, OpenSM has to react to the service restart.  Multiply that by the whole cluster restarting the service, and you put a ton of unnecessary load on the subnet manager.

@bybai Correct, you would need to restart the service if any changes were made that removed kernel modules or changed kernel module parameters.  When I went through the script I came to the same conclusion - for RedHat 7 with MOFED, nothing is changing.

**Comment by bybai** [comment]
@mattaezell , we have 2 changes in new code:
1, change default action is to "will not restart ib driver (including openibd) as default"
2, if `/etc/rdma/rdma.conf` or `/etc/infiniband/openib.conf` is changed by `configib` script, will restart ib driver.

**Comment by bybai** [comment]
Hi @mattaezell, I made this enhance for configib, it is merged in  https://github.com/xcat2/xcat-core/pull/5219, could you apply the latest code and have a try in your environment?

**Comment by mattaezell** [comment]
Thanks @bybai 

In our current setup, we just blindly comment out the restart.  I think your fix looks correct, but unfortunately I don't think we will be able to run with your updated version for a while.

**Comment by bybai** [comment]
Got agreement from Mark. I will close it now, can reopen it if needed in future.
I verified on  fake IB env:
1, can restart scenario:
```
[root@bybc0602 postscripts]# updatenode bybc0605 -P "confignetwork --ibaports=2" -V |tee log
Running command on bybc0602: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on bybc0602: chmod -R a+r /install/postscripts 2>&1

  bybc0602: Internal call command: xdsh bybc0605 --nodestatus -s -v -e /install/postscripts/xcatdsklspost 1 -m 10.5.106.2 'confignetwork --ibaports=2' --tftp /tftpboot --installdir /install --nfsv4 no -c -V
Running command on bybc0602: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1
Running command on bybc0602: hostname 2>&1
Running command on bybc0602: /opt/xcat/bin/pping bybc0605 2>&1
bybc0605: Warning: the ECDSA host key for 'bybc0605' differs from the key for the IP address '10.5.106.5'
bybc0605: Offending key for IP in /root/.ssh/known_hosts:21
bybc0605: Matching host key in /root/.ssh/known_hosts:32

bybc0605: Running /tmp/file9HuzTn.dsh 1 -m 10.5.106.2 confignetwork --ibaports=2 --tftp /tftpboot --installdir /install --nfsv4 no -c -V
bybc0605: trying to download postscripts...
bybc0605: trying to download postscripts from http://10.5.106.2/install/postscripts/
bybc0605: postscripts are downloaded from 10.5.106.2 successfully.
bybc0605: postscripts downloaded successfully
bybc0605: trying to get mypostscript from 10.5.106.2...
bybc0605: trying to download http://10.5.106.2/tftpboot/mypostscripts/mypostscript.bybc0605...
bybc0605: mypostscript.bybc0605 is downloaded successfully.
bybc0605: Running //xcatpost/mypostscript
bybc0605: Wed May 16 04:59:12 EDT 2018 Running postscript: confignetwork
bybc0605: [I]: All valid nics and device list:
bybc0605: [I]: ib0,ib1
bybc0605: [I]: NetworkManager is inactive.
bybc0605: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bybc0605: configure nic and its device : ib0,ib1
bybc0605: [I]: Call configib for IB nics: ib0,ib1, ports: 2
bybc0605: [I]: NIC_IBNICS=ib0,ib1 NIC_IBAPORTS=2 configib
bybc0605: restart openibd service
bybc0605: [E]:Error: configib failed.
bybc0605: postscript: confignetwork exited with code 1
bybc0605: //xcatpost/mypostscript return with 1
bybc0605: Running of postscripts has completed.
```

2.  do not restart openibd scenario:
```
... ....
ybc0605: Wed May 16 04:58:21 EDT 2018 Running postscript: confignetwork
bybc0605: [I]: All valid nics and device list:
bybc0605: [I]: ib0,ib1
bybc0605: [I]: NetworkManager is inactive.
bybc0605: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bybc0605: configure nic and its device : ib0,ib1
bybc0605: [I]: Call configib for IB nics: ib0,ib1, ports: 2
bybc0605: [I]: NIC_IBNICS=ib0,ib1 NIC_IBAPORTS=2 configib
bybc0605: [E]:Error: configib failed.
bybc0605: postscript: confignetwork exited with code 1
bybc0605: //xcatpost/mypostscript return with 1
bybc0605: Running of postscripts has completed.
```
