### ISSUE TITLE
Error: Unable to find pxelinux.0 when attempting to use nodeset

### ISSUE THREAD

**Issue by leiocalyx** [xcat2/xcat-core#5209]
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

lsxcatd -a
Version 2.14 (git commit 8c159330c2bedace4bb101945823ba51d9cbdc25, built Thu Apr 19 07:17:16 EDT 2018)
This is a Management Node
dbengine=SQLite
```

With `netboot=pxe` I was trying to assign an image:
```
nodeset node3 osimage=ubuntu16.04.4-x86_64-install-compute
Error: Unable to find pxelinux.0
```
I've dug a bit, and found mentions of `pxelinux.0` in [xCAT-server/lib/xcat/plugins/pxe.pm](https://github.com/xcat2/xcat-core/blob/1ca955a33da60d21f16be84278ffa06f8cf45918/xCAT-server/lib/xcat/plugins/pxe.pm)
It was checking two directories `/usr/lib/syslinux/pxelinux.0` and `/usr/share/syslinux/pxelinux.0` but neither existed on my system. 

I've tried to installing the `syslinux` package, but that didn't help. 

After copying the file directly to one of the above-mentioned directories 
`cp /opt/xcat/share/xcat/netboot/syslinux/pxelinux.0 /usr/share/syslinux/pxelinux.0`
the error disappeared:
```
nodeset node3 osimage=ubuntu16.04.4-x86_64-install-compute
Warning: rcons may not work since no serialport is specified for rainbow3-10.bru
node3: install ubuntu16.04.4-x86_64-compute
```

**Comment by immarvin** [comment]
hi @bybai , would you please take a look at this? thanks

**Comment by robin2008** [comment]
This is covered in #5783
