### ISSUE TITLE
Infrastructure PDU's not responding as expected

### ISSUE THREAD

**Issue by GeoKM** [xcat2/xcat-core#5213]
Hi, 
I have a room full of IBM Switched and Monitored smart PDU's with the following specs and FW level for example .
PDU-R04A: PDU Software Version: "OPDP_sIBM_v01.3_3"
PDU-R04A: PDU Machine Type: "1U"
PDU-R04A: PDU Model Number: "dPDU4500"
PDU-R04A: PDU Part Number: "00AK187"
PDU-R04A: PDU Name: "PDU-R04A"
PDU-R04A: PDU Serial Number: "4CY3DD"
PDU-R04A: PDU Description: "description"

and 

PDU-R10A: PDU Software Version: "OPDP_sIBM_v01.3_3"
PDU-R10A: PDU Machine Type: "1U"
PDU-R10A: PDU Model Number: "dPDU4530"
PDU-R10A: PDU Part Number: "00AK184"
PDU-R10A: PDU Name: "PDU-R10A"
PDU-R10A: PDU Serial Number: "5430B5"
PDU-R10A: PDU Description: "description"

and they do not seem to be responding as expected. They have been discovered and configured apparently correctly in xCAT 2.14 on Ubuntu 16.04 LTS ppc64le.

Yet when I try the command 

"rpower PDU-R04A stat" I get the following for example

PDU-R04A: outlet 1 is
PDU-R04A: outlet 2 is
PDU-R04A: outlet 3 is
PDU-R04A: outlet 4 is
PDU-R04A: outlet 5 is
PDU-R04A: outlet 6 is
PDU-R04A: outlet 7 is
PDU-R04A: outlet 8 is
PDU-R04A: outlet 9 is
PDU-R04A: outlet 10 is
PDU-R04A: outlet 11 is
PDU-R04A: outlet 12 is

ie, there is no actual status for the ports.

Also I have tried defining a node with a pdu with the following attribute.

pdu=PDU-R10A:2

rpower commands to the node with pdustat pduoff etc give.....
root@xCAT-A:~# rpower palm4 pdustat
palm4: PDU-R10A outlet 2 is
palm4: Error: Unsupported command: rpower pdustat
root@xCAT-A:~# rpower palm4 pduoff
palm4: Error: Unsupported command: rpower pduoff
Error: palm4: PDU-R10A outlet 2 has error = (badValue) The value given has the wrong type or length.

So they start to work but then don't.

"rpower PDU-R10A stat" for this pdu gives

PDU-R10A: outlet 1 is
PDU-R10A: outlet 2 is
PDU-R10A: outlet 3 is
PDU-R10A: outlet 4 is
PDU-R10A: outlet 5 is
PDU-R10A: outlet 6 is
PDU-R10A: outlet 7 is
PDU-R10A: outlet 8 is
PDU-R10A: outlet 9 is

The lsdef for PDU-R10A is

root@xCAT-A:~# lsdef PDU-R10A
Object name: PDU-R10A
    community=public
    groups=pdu
    ip=10.61.134.101
    mac=00:18:23:06:8b:75
    mgt=pdu
    nodetype=pdu
    outlet=9
    password=1001
    pdutype=irpdu
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    seclevel=noAuthNoPriv
    snmpuser=xcat2
    snmpversion=SNMPv3
    usercomment="IBM PDU 00AK184(46M4002) OPDP_sIBM_v01.3_3 FreeRTOS_4.2.1 Lwip_1.2.0"

As you can see I am trying SNMPv3 now, but I have had the same results no matter what SNMP version I use. Originally I was just using the defaults with v1. These snmp options have had no effect. 

The only thing I can see that is different from your reference in the Documentation is that the firmware on these PDU's in newer.

Any thoughts??

Have I supplied enough info to help?

Thanks.

**Comment by cxhong** [comment]
can u try this command on the system?
```
snmpwalk -v2c -cpublic -mALL pduname IBM-PDU-MIB::ibmPduOutletState -O n
```
we are supporting `.1.3.6.1.4.1.2.6.223.8.2.2.1.11` and `.1.3.6.1.4.1.2.6.223.8.2.2.1.13`  mibs for PduOutletState

**Comment by GeoKM** [comment]
Hi,

I tried the following
snmpwalk -v2c -cpublic -mALL PDU-R10A IBM-PDU-MIB::ibmPduOutletState -O n 2>&1 |grep IBM

and got the following.

Cannot find module (IBM-PDU-MIB): At line 0 in (none)
IBM-PDU-MIB::ibmPduOutletState: Unknown Object Identifier

Does that mean I have failed to install something on the system and the actual MIB's are not installed?

Thanks for any help you can give?

**Comment by cxhong** [comment]
The mib file should be located in the /usr/share/snmp/mibs, depends version of PDU, the file name will be something like this:  `ibmdpi_v01.3_3.mib`.  xCAT used OID, so I don't think you need to have mib files installed.    can u try this:
```
# snmpwalk -v1 -cpublic  pduname .1.3.6.1.4.1.2.6.223.8.2.2.1.11
```
checked `ibmdpi_v01.3_3.mib` file,  the above OID is for outlet status.

**Comment by cxhong** [comment]
@GeoKM , currently, xCAT only return the state if it is `on` or `off`, all other state return empty string.  
I opened a PR and add more output of PDU outlet status.  those are the state/value defined in the mib file:
```
 ibmPduOutletState defined from mib file
         off(0)
         on(1)
         cycling(2)
         delaySwitch10(3)
         delaySwitch30(4)
         delaySwitch60(5)
````
xcat only display on/off, all other state

**Comment by GeoKM** [comment]
Hi, 8-)

The only files in /usr/share/snmp/mibs are

root@xCAT-A:/usr/share/snmp/mibs# ls
GNOME-SMI.txt                        miblist.txt                NET-SNMP-PASS-MIB.txt             SNMP-TLS-TM-MIB.txt   UCD-IPFWACC-MIB.txt
IANA-ADDRESS-FAMILY-NUMBERS-MIB.txt  NET-SNMP-AGENT-MIB.txt     NET-SNMP-PERIODIC-NOTIFY-MIB.txt  SNMP-TSM-MIB.txt      UCD-SNMP-MIB-OLD.txt
IANAifType-MIB.txt                   NET-SNMP-EXAMPLES-MIB.txt  NET-SNMP-SYSTEM-MIB.txt           UCD-DEMO-MIB.txt      UCD-SNMP-MIB.txt
IANA-LANGUAGE-MIB.txt                NET-SNMP-EXTEND-MIB.txt    NET-SNMP-TC.txt                   UCD-DISKIO-MIB.txt
IANA-RTPROTO-MIB.txt                 NET-SNMP-MIB.txt           NET-SNMP-VACM-MIB.txt             UCD-DLMOD-MIB.txt
LM-SENSORS-MIB.txt                   NET-SNMP-MONITOR-MIB.txt   RFC-1215.txt                      UCD-IPFILTER-MIB.txt


I don’t see any .mib files at all?? that can’t be right?

8-(


> The mib file should be located in the /usr/share/snmp/mibs, depends version of PDU, the file name will be something like this: ibmdpi_v01.3_3.mib. xCAT used OID, so I don't think you need to have mib files installed. can u try this:
> # snmpwalk -v1 -cpublic  pduname .1.3.6.1.4.1.2.6.223.8.2.2.1.11
> checked ibmdpi_v01.3_3.mib file, the above OID is for outlet status.
> 
> 

I tried that on got the following.

Not sure what that means, but I don’t suppose it is correct. 8-)

root@xCAT-A:/usr/share/snmp/mibs# snmpwalk -v1 -cpublic  PDU-R10A .1.3.6.1.4.1.2.6.223.8.2.2.1.11
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.1 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.2 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.3 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.4 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.5 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.6 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.7 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.8 = INTEGER: 9600
iso.3.6.1.4.1.2.6.223.8.2.2.1.11.9 = INTEGER: 9600

Thanks for your help with this. 8-)

**Comment by cxhong** [comment]
the OID of ibmPduOutletState on  my version of `ibmdpi_v01.3_3.mib`  file is  `223.8.2.2.1.11`  :(
xCAT supports `223.8.2.2.1.13`, but only if ibmPduSoftwareVersion  has `sLEN`
````
# snmpwalk -v1 -cpublic f6pdu15 IBM-PDU-MIB::ibmPduSoftwareVersion
IBM-PDU-MIB::ibmPduSoftwareVersion.0 = STRING: OPDP_sIBM_v01.3_8
# snmpwalk -v1 -cpublic f6pdu15 .1.3.6.1.4.1.2.6.223.7.3.0
SNMPv2-SMI::enterprises.2.6.223.7.3.0 = STRING: "OPDP_sIBM_v01.3_8"
````
Can u check above command on your system?
I need to talk to IBM engineer about this issue.   
for now you can use `snmpset` command to power off/on , or you can modify the xCAT on the xCATMN .  change `223.8.2.2.1.11` to `223.8.2.2.1.13` in the `/opt/xcat/lib/perl/xCAT_plugin/pdu.pm`

**Comment by GeoKM** [comment]
Hi again 8-)


> On 18 May 2018, at 11:41 pm, cxhong <notifications@github.com> wrote:
> 
> the OID of ibmPduOutletState on my version of ibmdpi_v01.3_3.mib file is 223.8.2.2.1.11 :(
> xCAT supports 223.8.2.2.1.13, but only if ibmPduSoftwareVersion has sLEN
> 
> # snmpwalk -v1 -cpublic f6pdu15 IBM-PDU-MIB::ibmPduSoftwareVersion
> IBM-PDU-MIB::ibmPduSoftwareVersion.0 = STRING: OPDP_sIBM_v01.3_8
> # snmpwalk -v1 -cpublic f6pdu15 .1.3.6.1.4.1.2.6.223.7.3.0
> SNMPv2-SMI::enterprises.2.6.223.7.3.0 = STRING: "OPDP_sIBM_v01.3_8"
> Can u check above command on your system?
> 

Yep I get the following

root@xCAT-A:~# snmpwalk -v1 -cpublic PDU-R10A IBM-PDU-MIB::ibmPduSoftwareVersion
IBM-PDU-MIB::ibmPduSoftwareVersion.0 = STRING: OPDP_sIBM_v01.3_3
root@xCAT-A:~# snmpwalk -v1 -cpublic PDU-R10A .1.3.6.1.4.1.2.6.223.7.3.0
iso.3.6.1.4.1.2.6.223.7.3.0 = STRING: "OPDP_sIBM_v01.3_3"
> I need to talk to IBM engineer about this issue.
> for now you can use snmpset command to power off/on , or you can modify the xCAT on the xCATMN . change 223.8.2.2.1.11 to 223.8.2.2.1.13 in the /opt/xcat/lib/perl/xCAT_plugin/pdu.pm
> 
> 

So my PDU’s identify as OPDP_sIBM_v01.3_3 and pdu.pm is following the logic path for old old mib rather than newmib 


ie. not executing
if ($session->{newmib}) {
        $oid = ".1.3.6.1.4.1.2.6.223.8.2.2.1.13";
    } 

I changed the lines above this from 1.11 to 1.13 as you suggested and it now seems to work much better. I still get the occasional Usupported Command error but I think that is coming from somewhere else not pdu.pm because the pdu.pm functions themselves now work with the hacked file.

Ofcourse this is not a real fix 8-)

Thanks, though, at least I can move ahead, until the actual bug is sorted out 8-)

**Comment by cxhong** [comment]
@GeoKM , this is the response from engineer:
````
due to new functions added, we add the new OID to the SNMP MIB, which the firmware release was 1.3_3 at that time. Therefore, when your customer checked with the OID in firmware 1.3_3, they saw the OID as their report:

.1.3.6.1.4.1.2.6.223.8.2.2.1.13.1 = INTEGER: on(1) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.2 = INTEGER: on(1)
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.3 = INTEGER: on(1) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.4 = INTEGER: off(0) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.5 = INTEGER: on(1) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.6 = INTEGER: on(1) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.7 = INTEGER: off(0) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.8 = INTEGER: off(0) 
.1.3.6.1.4.1.2.6.223.8.2.2.1.13.9 = INTEGER: on(1) 



   (From implementation perspective, our engineer “INSERT” the two new functions to the similar category, therefore it caused the OID “SHIFT” 2, comparing to original one. 

 

 

  However, late on IBM asked Delta to correct such confusion, since up-level software so hardcode the OID to access PDU data via SNMP. Therefore, we changed the code and MIB file at that time accordingly. 

 

  Such confusion only occurred in firmware release 1.3_3 and Delta had addressed it in firmware 1.3_5 by IBM request and that is the reason you saw the OID in firmware 1.3_2 and 1.3_8 is difference:

 

# snmpwalk -v1 -cpublic f6pdu15 .1.3.6.1.4.1.2.6.223.8.2.2.1.11
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.1 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.2 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.3 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.4 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.5 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.6 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.7 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.8 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.223.8.2.2.1.11.9 = INTEGER: 1

````
our recommendation is upgrade your PDU firmware to 1.3_8

**Comment by GeoKM** [comment]
Hiya again 8-)

Thanks for that info,

Do you happen to have a link where I can get the  1.3_8 firmware from?

I can only find 1.3_3 as the most recent on IBM fix Central? How strange?

Thanks.

**Comment by cxhong** [comment]
@GeoKM , you may need to request IBM(not sure about process) to upload newest firmware to fix Central.
