### ISSUE TITLE
[feature] expect "xcattest -t/-b" can generate a bundle including all the failed cases found on each run

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#5235]
this is a scenario I found during running xcat-inventory regression:
I run `XCATTEST_DSTMN=10.3.5.8 xcattest -b /home/xcat-inventory.bundle.all`,  found 4 error cases,

```
[root@c910f03c05k08 ~]# XCATTEST_DSTMN=10.3.5.8 xcattest -b /home/xcat-inventory.bundle.all
...
------END::xcat_inventory_import_validation_osimage::Passed::Time:Tue May 22 03:16:07 2018 ::Duration::50 sec------
------Total: 1000 , Failed: 20------

xCAT automated test finished at Tue May 22 03:16:07 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180522031513 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180522031513 file for time consumption

```

then I have to look into `/opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180522031513` and find out the failed cases and fix them, then I have to rerun the cases to verify the fix is ok, but I do not want to rerun the whole bundle since it cost a lot of time.
the output of  `xcattest ` just give the number of failed cases, I have to look into `/opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180522031513` again to find out the names of failed cases, then rerun them either with `xcattest -t` or compose a bundle by myself and run `xcattest -b`. Consider when there are around 20 failed cases , this is quite a huge effort to compose a list of the failed cases or a failed case bundle. 

 expect xcattest can generate a bundle if any failed case found, and the output can be something looks like: 

```
[root@c910f03c05k08 ~]# XCATTEST_DSTMN=10.3.5.8 xcattest -b /home/xcat-inventory.bundle.all
...
------END::xcat_inventory_import_validation_osimage::Passed::Time:Tue May 22 03:16:07 2018 ::Duration::50 sec------
------Total: 1000 , Failed: 20------

xCAT automated test finished at Tue May 22 03:16:07 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180522031513 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180522031513 file for time consumption
**see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.bundle.20180522031513 for the bundle including all the failed cases**  
```
with this, I can simply run `xcattest -b /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.bundle.20180522031513` to verify the fix

**Comment by hu-weihua** [comment]
@immarvin every time, we run xcattest, it will generate 3 files under ``/opt/xcat/share/xcat/tools/autotest/result``, they are:
```
failedcases.*******
performance.report.*******
xcattest.log.*******
```
All failed cases are saved in file ``failedcases.*******``. Run below command can get what you want
```
grep -- "--END" failedcases.20180521175133 |awk -F"::" '{print $2}'
```
