### ISSUE TITLE
[FVT]xcat-inventory: provide warning message if provision_mode is not provided for osimage which is exported. 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#5238]
xcat 2.14.1

When execute import for an osimage defition. It gives out that the provision mode is not given in yaml file.  Go back to export command, it should give out warning message that if provision_mode is not given for osimage export. 

```
[root@c910f03c05k08 ~]# xcat-inventory import -t osimage -o test_myimage -d /opt/inventory/site/osimage/
Error: failed to validate attribute [provision_mode] of object "test_myimage", criteria: "value='': True if str(value) in ('install','netboot','statelite') else False"
```
Here is the export command
```
[root@c910f03c05k08 ~]# lsdef -t osimage -o test_myimage
Object name: test_myimage
    exlist=/tmp/exlist
    imagetype=linux
    otherpkglist=/tmp/otherpkglist
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    postinstall=/tmp/postinstall
    synclists=/tmp/synclists
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
[root@c910f03c05k08 ~]# xcat-inventory export -t osimage -o test_myimage --format yaml -d //opt/inventory/site/osimage/
The osimage objects has been exported to directory //opt/inventory/site/osimage/

```

**Comment by immarvin** [comment]
hi @tingtli , `provision_mode ` corresponds to the `provmethod` in osimage definition, this is a mandatory attribute for osimage object. When creating osimage in test cases, we should add the  `provmethod` attribute

**Comment by tingtli** [comment]
@immarvin  But when i use chdef to create an osimage, if provison_mode or  provmethod is not defined, the creation could succeed. 
```
[root@c910f03c05k08 ~]# chdef -t osimage -o test_myimage imagetype=linux pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl otherpkglist=/tmp/otherpkglist synclists=/tmp/synclists postinstall=/tmp/postinstall exlist=/tmp/exlist partitionfile=/tmp/partitionfile
1 object definitions have been created or modified.
New object definitions 'test_myimage' have been created.
[root@c910f03c05k08 ~]# lsdef -t osimage -o test_myimage
Object name: test_myimage
    exlist=/tmp/exlist
    imagetype=linux
    otherpkglist=/tmp/otherpkglist
    partitionfile=/tmp/partitionfile
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    postinstall=/tmp/postinstall
    synclists=/tmp/synclists
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl
```
So, do we consider to give warning message when we create an osimage without provmethod?

**Comment by immarvin** [comment]
hi @tingtli , you can create a osimage by chdef, but can it be used to provision?

**Comment by whowutwut** [comment]
Shouldn't this issue be opened here? https://github.com/xcat2/xcat-inventory/issues 

Or maybe the question is, why is this not part of xcat-core? What was the initial thought there @immarvin ?

**Comment by whowutwut** [comment]
Interesting bug you found @tingtli,  looks like there is more attribute checking during the import using `xcat-inventory`.. should we try to make sure that `import` and `mkdef/chdef` are in sync and checking the same things?

**Comment by immarvin** [comment]
hi @whowutwut , the initial thought is that `xcat-inventory` is a standalone add-on for xcat, we had some discussion on https://github.com/xcat2/xcat-inventory/issues/16. 
yes, issues and PRs for xcat-inventory should be under `xcat2/xcat-inventory`,  but seems we did not make it awake of this inside team. We will reminder this.

**Comment by immarvin** [comment]
`xcat-inventory` is another view of xCAT objects besides `lsdef/mkdef/chdef`although the objects manipulated by`xcat-inventory` is based on the ones of `lsdef/mkdef/chdef`. 

Due to technical debt, `mkdef/chdef` commands does not have sufficient validation against the attributes and the `def` related code logic is too complex , it will cost a lot of effort to keep the 2 in sync(this is also a reason that why we initiate `xcat-inventory` instead of implement the inventory feature based on current `mkdef/chdef` code logic).

In `xcat-inventory`, I think we'd better impose a more strict validation than `mkdef/chdef` , to keep the working objects created by `mkdef/chdef` pass validation, while prohibit the invalid objects created by `chdef/mkdef` like the osimage in this issue
we have tried to keep the both validations consistent to make sure the
