### ISSUE TITLE
kits addpkgs selects packages without respecting versions

### ISSUE THREAD

**Issue by winice-test** [xcat2/xcat-core#5284]
When I build a complete kit tar file, I found buildkit selects the package randomly but not respecting the package versions.

root:~/pvt/kits# ls source_packages/*64.rte*
source_packages/essl.3264.rte_5.3.2-0_ppc64el.deb  source_packages/essl.3264.rtecuda_5.3.2-0_ppc64el.deb  source_packages/essl.6464.rte_5.3.2-0_ppc64el.deb
source_packages/essl.3264.rte_5.3.2-1_ppc64el.deb  source_packages/essl.3264.rtecuda_5.3.2-1_ppc64el.deb  source_packages/essl.6464.rte_5.3.2-1_ppc64el.deb
source_packages/essl.3264.rte_5.3.2-2_ppc64el.deb  source_packages/essl.3264.rtecuda_5.3.2-2_ppc64el.deb  source_packages/essl.6464.rte_5.3.2-2_ppc64el.deb

root:~/pvt/kits# /opt/xcat/bin/buildkit addpkgs essl-5.3.2-2-ppc64el.NEED_PRODUCT_PKGS.tar.bz2 -p source_packages/

root:~/pvt/kits# tar tjvf essl-5.3.2-2-ppc64el.tar.bz2  |grep essl |grep 64.rte
-rw-r--r-- root/root  26969070 2015-07-04 14:20 essl-5.3.2-2-ppc64el/repos/essl-5.3.2-2-ubuntu-14.04-ppc64el/essl.3264.rte_5.3.2-0_ppc64el.deb
-rw-r--r-- root/root  14192890 2016-12-15 02:37 essl-5.3.2-2-ppc64el/repos/essl-5.3.2-2-ubuntu-14.04-ppc64el/essl.3264.rtecuda_5.3.2-1_ppc64el.deb
-rw-r--r-- root/root  25202840 2015-07-04 14:21 essl-5.3.2-2-ppc64el/repos/essl-5.3.2-2-ubuntu-14.04-ppc64el/essl.6464.rte_5.3.2-0_ppc64el.deb

I would expect the complete kit tar file contains the latest 5.3.2-2 version but not the 5.3.2-0 or 5.3.2-1.

**Comment by winice-test** [comment]
xcat-buildkit version 2.9-snap20141208 on Ubuntu1404

**Comment by bybai** [comment]
Hi @winice-test , I looked in your environment, `xcat-buildkit` is 2.9-snap20141208. This issue should be fix in commit f8183abc50e86ab8d7e35ef63f27551c9f3acb74
You can decide to upgrade the xcat-buildkit or give fix to customer.
Thanks.
