### ISSUE TITLE
rflash can not connect to sn02's BMC 

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#5289]
Trying to use rflash to flash SN02 on Austin Coral Combined cluster.  When trying to list out images on the BMC it will not connect 

``` (0) root @ xcat1: /root
# rflash -l sn02
Tue Jun 12 12:09:59 2018 OpenBMC: [openbmc_debug_perl]
sn02: Error: [500] Login to BMC failed: 500 Can't connect to 192.168.85.3:443.
sn02: Error: BMC did not respond. Validate BMC configuration and retry the command.
```

BMC is up and connectable and REST services are up 

```(1) root @ xcat1: /root
# ping sn02-bmc
PING sn02-bmc.hst.ibm.net (192.168.85.3) 56(84) bytes of data.
64 bytes from sn02-bmc.hst.ibm.net (192.168.85.3): icmp_seq=1 ttl=64 time=1.34 ms
64 bytes from sn02-bmc.hst.ibm.net (192.168.85.3): icmp_seq=2 ttl=64 time=0.488 ms
64 bytes from sn02-bmc.hst.ibm.net (192.168.85.3): icmp_seq=3 ttl=64 time=0.315 ms
^C
--- sn02-bmc.hst.ibm.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.315/0.716/1.346/0.451 ms

(0) root @ xcat1: /root
# ssh sn02-bmc
root@witherspoon:~# 

```

**Comment by gurevichmark** [comment]
When this happens the BMC displays this information:
```
root@witherspoon:~# /usr/sbin/phosphor-gevent rest_dbus
Traceback (most recent call last):
  File "/usr/sbin/phosphor-gevent", line 58, in <module>
    server.serve_forever()
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 282, in serve_forever
    self.start()
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 234, in start
    self.init_socket()
  File "/usr/lib/python2.7/site-packages/gevent/pywsgi.py", line 639, in init_socket
    StreamServer.init_socket(self)
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 78, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 89, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 153, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use: ('', 443)
```

**Comment by gurevichmark** [comment]
Asked in openbmc channel what his error means:

![image](https://user-images.githubusercontent.com/16106630/41310482-9b2e1fe2-6e4f-11e8-8217-1a103f091c80.png)

**Comment by whowutwut** [comment]
@gurevichmark So is the problem that changes were made in the REST engine and xCAT is not yet updated to support the changes? Is this an xCAT support issue?

**Comment by robin2008** [comment]
@gurevichmark  Any updates?  Looks like it is what the things need to be done in xCAT rflash side, I think we have already followed their interfaces to do the mandatory things.

**Comment by gurevichmark** [comment]
I think the command `/usr/sbin/phosphor-gevent rest_dbus` just tells us that REST services are running. The command shows that error looking output, but in reality it is just a verification that REST service is not down.
@moralesj told me that this is intermittent problem, so probably not a major logic problem in xCAT. Could be some error condition we are not handling ?

**Comment by gurevichmark** [comment]
@moralesj Since it appears to not happen anymore, do you want to close this issue and reopen if happens again ?

**Comment by moralesj** [comment]
Closing issue, and will reopen if it shows up again.
