### ISSUE TITLE
rspconfig dump does not have a good message in hierarchy environment

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5290]
In Hierarchy environemnt, noticed when doing a `rspconfig dump -d` download of a dump, the message doesn't really help identify the real location of the file. 

The real location of the file is on the service node that managed the compute. 

```
# rspconfig cn11 dump -l
cn11: [2] Generated: 05/24/2018 04:38:54, Size: 6304
cn11: [3] Generated: 06/12/2018 23:24:20, Size: 111940
# rspconfig cn11 dump -d 3
cn11: Downloading dump 3 to /var/log/xcat/dump/20180612-2331_cn11_dump_3.tar.xz
```

On the management node, I can't find it: 

```
(0) root @ xcat1: /root
# cd /var/log/xcat/dump

(0) root @ xcat1: /var/log/xcat/dump
# ls -ltr
total 0
```

It would be better if we could detect this and print a message that references the service node, for example: 

```
# rspconfig cn11 dump -d 3
cn11: Downloading dump 3 to sn02:/var/log/xcat/dump/20180612-2331_cn11_dump_3.tar.xz
```

**Comment by whowutwut** [comment]
This issue probably applies to the framework in general, if we could improve the framework to understand hierarchy when printing these messages, it would be beneficial across the board.

**Comment by whowutwut** [comment]
@hu-weihua Could we have FVT take a look at the hierarchy test cases and look at the usability here in the messages ?

**Comment by hu-weihua** [comment]
@tingtli , Could you help to look at the usability of ``rspconfig dump -d`` in hierarchy environment? thanks.

**Comment by gurevichmark** [comment]
We recently added the PR #5119 to display SN for warning and error messages. Maybe this should be done for all types of messages ?

**Comment by robin2008** [comment]
It might not be good for all messages,  most of the messages does not need an server name. 
only those need the context, so the message raiser need to handle it.

And the framework is already record the server name for each message, so when using callback to print the message, the caller just need to set a flag to notify the framework to show the name if possible.

**Comment by whowutwut** [comment]
@robin2008 Couldn't we also tell if we are running on a MN and the service node executing the command hostname does not match where we execute, and that would indicate a Hierarchy environment so we can print out a different message?   Non hierarchy we can leave the message the same as today.

**Comment by robin2008** [comment]
Actually, command is issued from client side, and the message is also printed to screen on client side,  and it could be a local xcat client or a remote xcat client
( http://xcat-docs.readthedocs.io/en/stable/advanced/security/security.html?highlight=remote%20xcat%20client )

So there might be below scenarios:
Case1: CLI is issued from xCAT client on MN   (the most common scenario)
Case2: CLI is issued from xCAT client on SN (some kinds of CLI still need to run on SN )
Case3: CLI is issued from a remote xCAT client (Just a remote scenario for Case1)

The best is to compare the client hostname and the message source name, if they are the same, then no need to show the server name,  or just print it.  But it introduce a bit more cpu usage when print lots of message (Every message we need a string comparison),  we need a testing for 10k messages to see if the consumption is acceptable.

BTW:  it is not cheap to determine if it is in a Hierarchy environment, must access DB to know it.

**Comment by hu-weihua** [comment]
@whowutwut , I test ``rspconfig f5u14 dump -d all`` on a hierarchy environment today for 2.14.4 release.  It looks like below:

```
[root@f6u13k10 dump]# lsdef f5u14 -i servicenode
Object name: f5u14
    servicenode=f6u13k11
```

* On mn f6u13k10
```
[root@f6u13k10 dump]# rspconfig f5u14 dump -d all
Downloading all dumps...
f5u14: Downloaded dump 147 to /var/log/xcat/dump/20181017-0310_f5u14_dump_147.tar.xz.
f5u14: Downloaded dump 148 to /var/log/xcat/dump/20181017-0310_f5u14_dump_148.tar.xz.

[root@f6u13k10 dump]# ll //var/log/xcat/dump
total 0
```

* On SN f6u13k11
```
[root@f6u13k11 dump]# ll  /var/log/xcat/dump/
total 640
-rw-r--r-- 1 root root 84268 Oct 17 02:26 20181017-0226_f5u14_dump_147.tar.xz
-rw-r--r-- 1 root root 84268 Oct 17 02:31 20181017-0231_f5u14_dump_147.tar.xz
-rw-r--r-- 1 root root 84552 Oct 17 02:31 20181017-0231_f5u14_dump_148.tar.xz
-rw-r--r-- 1 root root 84268 Oct 17 03:10 20181017-0310_f5u14_dump_147.tar.xz
-rw-r--r-- 1 root root 84552 Oct 17 03:10 20181017-0310_f5u14_dump_148.tar.xz
```
Did it work as our design?

**Comment by whowutwut** [comment]
@hu-weihua I don't think anything has changed for this  issue, it's marked as 2.14.x so it looks like it's  in the backlog, not yet in plan for a release.

**Comment by zet809** [comment]
hi, @whowutwut , as the PR #6209 applied by Mark have been merged, do you think we can close this issue? Thx!

**Comment by robin2008** [comment]
We don't want a general changes on existing xcatd,  but to consider such usability issue in `xCATNg` when we implement new CLI.
