### ISSUE TITLE
xCat commands using IPMI (rpower, rcons, ...) fail in xCat 2.14 on RHEL75

### ISSUE THREAD

**Issue by zrlhle** [xcat2/xcat-core#5297]
```
rpower <nodename> status
Error: ipmi plugin bug, pid 74128, process description: 'xcatd SSL: rpower to <nodename> for root@localhost: ipmi instance' with error 'Can't call method "sockopt" on an undefined value at /opt/xcat/lib/perl/xCAT/IPMI.pm line 212, <$sysctl> line 1.
' while trying to fulfill request for the following nodes: <nodename>
```

... found a workaround by avoiding IPV6 selection in /opt/xcat/lib/perl/xCAT/IPMI.pm
```
/# if ($doipv6) {
/# $socket = IO::Socket::INET6->new(Proto => 'udp');
/# } else {
/ $socket = IO::Socket::INET->new(Proto => 'udp');
/# }
```

**Comment by whowutwut** [comment]
@zrlhle Thanks for opening this one. 

I edited your post to format since `<nodename>` won't show if it's not wrapped in markdown. FYI, there's a tip in the comment box for markdown styling. 

Can you grab the output of `lsxcatd -a` so we know the build you are running, I assume it's the GA version of 2.14.

Also, if you can, please post the output of the node definition you are running?

@zet809 @gurevichmark  could you take a look at this? @hu-weihua can we re-create it?

**Comment by zet809** [comment]
So, it means `$socket = IO::Socket::INET6->new(Proto => 'udp')` failed to create an IPV6 socket? The socket is fine in my environment even no IPV6 address configured on any nics.
```
# lsxcatd -a
Version 2.14 (git commit 8c159330c2bedace4bb101945823ba51d9cbdc25, built Thu Apr 19 07:15:45 EDT 2018)
This is a Management Node
dbengine=SQLite
# rpm -aq |grep -i inet6
perl-IO-Socket-INET6-2.69-5.el7.noarch
# ip a | grep inet6
# XCATBYPASS=1 rpower c910f05c01bc06 status
===>Use IO::Socket::INET6 to create UDP connection==
c910f05c01bc06: on
```
So, @zrlhle , will you pls provide more configuration data? Thx!

**Comment by zrlhle** [comment]
sorry for the late reply ... the notification emails got routed to the wrong inbox. here is the output from `lscatd -a` (just updated to 14.3 and had to apply the same fix as before)   
   
`lsxcatd -a
Version 2.14.3 (git commit 7b7d9ab67589afec1ba58cd5138154290c529c0e, built Tue Aug 21 07:16:00 EDT 2018)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=XXX|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=XXX
dbadmin=xcatadm`

**Comment by zrlhle** [comment]
The other two commands you were looking for
`rpm -qa |grep -i inet6
perl-Net-INET6Glue-0.5-3.el7.noarch
perl-IO-Socket-INET6-2.69-5.el7.noarch`
... and ...
`XCATBYPASS=1 rpower zhcc001 status
Can't call method "sockopt" on an undefined value at /opt/xcat/lib/perl/xCAT/IPMI.pm line 212, <$sysctl> line 1.`

**Comment by samveen** [comment]
@zrlhle please confirm that all the IPMI fields are set correctly with:

```
nodels zhcc001 ipmi
```

**Comment by zrlhle** [comment]
nodels zhcc001 ipmi
```
zhcc001: ipmi.bmc: XXX.YYY.ZZZ.AAA
zhcc001: ipmi.node: zhcc001
zhcc001: ipmi.password: XXX
zhcc001: ipmi.username: XXX
zhcc001: ipmi.taggedvlan: 
zhcc001: ipmi.comments: 
zhcc001: ipmi.bmcid: 
zhcc001: ipmi.bmcport: 
```
zhcc001: ipmi.disable:

**Comment by zet809** [comment]
It seems to be an issue with the package perl-IO-Socket-INET6-2.69-5.el7.noarch itself.
Will you pls check the following information in your environment? Thx!
```
# rpm -qa |grep perl-IO-Socket-INET6
perl-IO-Socket-INET6-2.69-5.el7.noarch
# rpm -ql perl-IO-Socket-INET6-2.69-5.el7.noarch
/usr/share/doc/perl-IO-Socket-INET6-2.69
/usr/share/doc/perl-IO-Socket-INET6-2.69/ChangeLog
/usr/share/doc/perl-IO-Socket-INET6-2.69/README
/usr/share/man/man3/IO::Socket::INET6.3pm.gz
/usr/share/perl5/vendor_perl/IO
/usr/share/perl5/vendor_perl/IO/Socket
/usr/share/perl5/vendor_perl/IO/Socket/INET6.pm
# md5sum /usr/share/perl5/vendor_perl/IO/Socket/INET6.pm
f91e3774a58e717c54b94f207d07215d  /usr/share/perl5/vendor_perl/IO/Socket/INET6.pm
```
