### ISSUE TITLE
confignetwork cannot show error when configuration is failed

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5309]
Just found this issue when I made a mistake on the IP for ib0.
```
chdef <> nicips.ib0="20.0.0.05" nicnetworks.ib0="ibnet" nictypes.ib0="Infiniband"
```

After provisioned, the ib0 is not shown its IP address,  and no error reported in `/var/log/xcat/xcat.log`

```
# cat ifcfg-ib0
DEVICE=ib0
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=20.0.0.05
NETMASK=255.255.255.0
# ifup ib0
ipcalc: bad IPv4 address: 20.0.0.05
ipcalc: bad IPv4 address: 20.0.0.05
ipcalc: bad IPv4 address: 20.0.0.05
Error: any valid prefix is expected rather than "20.0.0.05/".
ERROR     : [/etc/sysconfig/network-scripts/ifup-eth] Error adding address 20.0.0.05 for ib0.
bind: Cannot assign requested address
Error: any valid prefix is expected rather than "20.0.0.05/".
RTNETLINK answers: File exists
```

After I fix the IP to `20.0.0.5`,  the configuration is working.

xCAT may need more strict check on input

**Comment by bybai** [comment]
This issue is about "add log for configib scripts", it is the same requirement with issue https://github.com/xcat2/xcat-core/issues/6205, so using #6205 to trace the work, I will close this one.
