### ISSUE TITLE
xCAT postscripts changes scripts to execute permission automatically

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5311]
In our devops framework, trying to use the execute permission to control which scripts should run or not based, but looks like the xCAT postscript processing framework will change all the scripts to have execute permission instead of respecting the permission in the `/install/postscripts` directory on the MGMT node.  

I think this was probably implemented as a courtesy to help run the scripts in case the execute permission is not set by admin, but I don't think this should be done, because it limits our ability to do things like this.. 

`01-sample does not have execute permission`
```
[root@briggs01 xcat_clusters]# ls -ltr /install/postscripts/custom_postscripts/validation.d/
total 8
-rw-r--r-- 1 root root  81 Jun 21 10:56 01-sample.sh
-rwxr-xr-x 1 root root 131 Jun 21 10:56 00-sample.sh
``` 

But after running `updatenode` and the scripts are sent to the compute, it does...
```
[root@briggs01 xcat_clusters]# xdsh mid05tor12cn15 ls -ltr /xcatpost/custom_postscripts/validation.d/
mid05tor12cn15: total 128
mid05tor12cn15: -rwxr-xr-x 1 root root  81 Jun 21 10:56 01-sample.sh  <---- 
mid05tor12cn15: -rwxr-xr-x 1 root root 131 Jun 21 10:56 00-sample.sh
```

**Comment by immarvin** [comment]
hi @whowutwut , not quite understand `01-sample does not have execute permission`,  would you please explain more on this? 

the permission of the files is modified in `xcatdsklspost`:
```
...
568 # To support the postscripts in the subdirectories under /install/postscripts
569 #chmod +x /$xcatpost/*;
570 chmod -R +x `find $xcatpost/ -maxdepth 1 -print | grep -E -v "^($xcatpost/|$xcatpost/_xcat|$xcatpost/_ssh|$xcatpost/ca|$xcatpo    st/hostkeys)$"`
...
```

**Comment by whowutwut** [comment]
01-sample does not have execute permission... it's permission is 644.  It's intended to be 644 in my framework so that I can selectively choose which scripts are executed based on their permission..  

Because xCAT modifies the permission when downloading the postscripts like you show in that code snip,  I can't use permission bit to enable or disable scripts to execute in my postscript framework.

**Comment by immarvin** [comment]
I am afraid wget cannot preserve the file permission, a simple test:

http server side:

```
[root@c910f03c05k21 postscripts]# ll /install/postscripts/remoteshell
-rwxr-xr-x 1 root root 21311 May 21 00:46 /install/postscripts/remoteshell
```

http client side:
```
[root@briggs01 ~]# rm -f  ./remoteshell ; wget  10.3.5.21/install/postscripts/remoteshell
--2018-06-25 08:20:18--  http://10.3.5.21/install/postscripts/remoteshell
Connecting to 10.3.5.21:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21311 (21K) [text/plain]
Saving to: ‘remoteshell’

100%[========================================================================================>] 21,311      --.-K/s   in 0s

2018-06-25 08:20:18 (210 MB/s) - ‘remoteshell’ saved [21311/21311]

[root@briggs01 ~]# ll ./remoteshell
-rw-r--r-- 1 root root 21311 May 21 00:46 ./remoteshell

[root@briggs01 ~]# rm -f  ./remoteshell ; wget --preserve-permissions  10.3.5.21/install/postscripts/remoteshell
--2018-06-25 08:20:46--  http://10.3.5.21/install/postscripts/remoteshell
Connecting to 10.3.5.21:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21311 (21K) [text/plain]
Saving to: ‘remoteshell’

100%[========================================================================================>] 21,311      --.-K/s   in 0s

2018-06-25 08:20:46 (154 MB/s) - ‘remoteshell’ saved [21311/21311]

[root@briggs01 ~]# ll ./remoteshell
-rw-r--r-- 1 root root 21311 May 21 00:46 ./remoteshell
```

and it might be a little tricky and not explicit to `selectively choose which scripts are executed based on their permission`

**Comment by whowutwut** [comment]
@immarvin  I don't think we have to selectively choose which scripts to execute based on their permission.  I don't want to change the behavior of xCAT, except do not change the permissions of the script from the MN to the compute node to `+x`.  That's all. 
 
So if a user creates a postscript `/install/postscript/abc` and runs `updatenode <> -P abc`, and it's not execute permission, an error should be printed saying "cannot execute".  This would be a user error.  

I just opened this because as part of my framework internally to create some gitops/devops scripting, I wanted to be able to control script execution based on execute permission of the script, but because xCAT changes everything to +x, i cannot control this.   NOT asking for xCAT behavior of script processing to change, but simply do not `+x` on all scripts...

**Comment by whowutwut** [comment]
I think this would result in a significant change of behavior, does not seem like we will do  this.
