### ISSUE TITLE
Suggestion re man page for rcons and exit code

### ISSUE THREAD

**Issue by payerle** [xcat2/xcat-core#5327]
The man page for rcons states:
"To exit the console session, enter:  <ctrl>e c ."

While this is correct, it could be confusing.  I.e., it is easy to incorrectly assume that the exit code is only two characters (ctrl-e and c), interpretting the "." as punctuation to the sentence.

Could I suggest something like
"To exit the console session, enter: '<ctrl>e c .' (three characters, ctrl-e, 'c', and '.')."

type:documentation prioirity:low type:enhancement

**Comment by whowutwut** [comment]
@payerle Thanks for this feedback! we will make the documentation more clear.

**Comment by robin2008** [comment]
Fixed the manpage in https://github.com/xcat2/xcat-core/pull/5331
