### ISSUE TITLE
Make improvements to rflash for ipmi managed nodes

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5344]
To help with debugging, add some enhancements to ipmi.pm for `rflash` command

1. When displaying message `The image file doesn't match this machine` also display machines's model number
2. If `-d` option is specified return an error if target machine is not "IBM Power S822LC for Big Data"
3. If possible display "check" data with `-c` option for firmware files in `-d` data directory

**Comment by hu-weihua** [comment]
After verification, only item 2 worked. So open this issue again and move to 2.14.3.

**Comment by gurevichmark** [comment]
@hu-weihua You are right, not everything in this issue was fixed. But I think only item 3 was not implemented. Items 1 and 2 should work. Did you notice item 1 not working ?

**Comment by gurevichmark** [comment]
@hu-weihua Did you get a chance to take another look at this ?

**Comment by hu-weihua** [comment]
@gurevichmark, The bug verification is a task of every release cycle. I got above test result against this issue from @tingtli.   

@tingtli, could you help to verify this issue again? thanks.

**Comment by xuweibj** [comment]
Want to verify "When displaying message The image file doesn't match this machine also display machines's model number" today, but I did find correct P8 machine. 
Tried against P9 with ``mtm=9006-22C``, got msg below:
```
# rflash boston32 -d /mnt/xcat/iso/firmware/supermicro/p8/OP825/v2.20_BMC1.27
boston32: rflash started, Please wait...
Error: [stratton01]: boston32: Error running command /mnt/xcat/iso/firmware/supermicro/p8/OP825/v2.20_BMC1.27/pUpdate -f /mnt/xcat/iso/firmware/supermicro/p8/OP825/v2.20_BMC1.27/SMT_P8_127.bin -i lan -h boston32-bmc -u ADMIN -p ADMIN >/var/log/xcat/rflash/boston32.log 2>&1
```
Hi @gurevichmark , if p9 is not supported for this scenario, could you help to verify it please?

**Comment by gurevichmark** [comment]
@xuweibj I think the code is doing what it is supposed to do.

Since `9006-22C` is a valid model for BigData, we attempt to run `rflash`, for some reason `pUpdate` fails, but I think that is a different issue.

But to verify this issue, if you try to run it against node with `mtm=8335-GTA`, you will get expected error:
```
[root@stratton01 xcat]# rflash frame5u39 -d /mnt/xcat/iso/firmware/supermicro/p8/OP825/v2.20_BMC1.27
Error: [stratton01]: frame5u39: Flashing of 8335-GTA is not supported with pUpdate, supported Model Types: 8001-22C|9006-22C|5104-22C|8001-12C|9006-12C
```

**Comment by xuweibj** [comment]
@gurevichmark I ever tried to against node with ``mtm=8335-GTA``, it worked well. But from your pr, there is another scenario as below: 
```
# rflash stratton01 -d /mnt/xcat/iso/supermicro_firmware/p8/OP825/v2.20_BMC1.27
Error: [c910f02c05p03]: stratton01: The image file doesn't match target machine:
.....
```
I didn't find suitable machine to verify this.

**Comment by gurevichmark** [comment]
@xuweibj Yea, I do not know how to cause that error to be displayed for real.
For the UT, I modified the code to force it through that path.
