### ISSUE TITLE
[FVT]restart xcatd get error message for bugs.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#537]
Restart xcatd on 2.11 will get following message.

Dec 15 01:32:42 c910f03c05k23 xcat[3780]: xcatd: possible BUG encountered by xCAT UDP service: Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /opt/xcat/lib/perl/xCAT/Table.pm line 110.

**Comment by hu-weihua** [comment]
@tingtli , I tried to reproduce this issue on c910f03c05k23, but didn't hit this issue any more.
Could you offer a specific steps to reproduce this issue? thanks

**Comment by chenglch** [comment]
@hu-weihua @tingtli , Seems that this bug as same as the bug I met when I clean up database in the signal handler.  You can see the detail to reprocess this issue.
https://github.com/chenglch/xcat-core/blob/getadapter/xCAT-server/lib/xcat/plugins/getadapter.pm#L227

I think this bug is not just related to xcatd, but also related to the database. If DB access process is down, 'table->new' will cause this problem. How to handle this situation when the DB access process stopped unexpectedly? Currently the plugin process is blocked when trying to connect to the database.

I have already find the root cause and talked this to @daniceexi last week, he knows the details.

**Comment by daniceexi** [comment]
@tingtli, @hu-weihua We waiting for @chenglch 's fix, so see whether it can be fixed.

**Comment by whowutwut** [comment]
@cxhong  and I saw an issue recently where the PostgreSQL DB was running but there was something wrong with it.  The nodeset commands would just time out.  But I restarted postgresql and the commands still worked so I didn't assume it was the DB.  It wasn't until we changed back to SQLite that xCAT started working again.

**Comment by daniceexi** [comment]
@whowutwut maybe the issue not caused by the DB itself isntead of xCAT DB process. So restart xcatd would resolve the problem. If this is the case, the xcat DB process might get into an unknown state.

**Comment by whowutwut** [comment]
@daniceexi  The restart of xcatd did not resolve the problem.  It was very strange.  The only thing that resolved it was changing back to SQLite.  If it happens again , ill try and debug but that environment is not there anymore

**Comment by daniceexi** [comment]
@tingtli Could you verify whether still can recreate this issue in the latest build?

**Comment by tingtli** [comment]
I didn't see the error in log. But why did I see different log information when i restart xcatd  for three times.



Apr 21 14:18:36 c910f03c17k33 xcat[450]:  INFO xcatd: 'Command log writer' process 450 is terminated by TERM or INT signal
Apr 21 14:18:36 c910f03c17k33 xcat[448]:  xcatd udp service 448 quiescing
Apr 21 14:18:39 c910f03c17k33 xcat[5518]:  INFO xcatd: command log process 5518 start
Apr 21 14:20:02 c910f03c17k33 xcat[5515]:  xcatd udp service 5515 quiescing

Apr 21 14:20:02 c910f03c17k33 xcat[5518]:  INFO xcatd: 'Command log writer' process 5518 is terminated by TERM or INT signal
Apr 21 14:20:02 c910f03c17k33 xcat[5516]:  xcatd install monitor 5516 quiescing
Apr 21 14:20:04 c910f03c17k33 xcat[5614]:  INFO xcatd: command log process 5614 start
Apr 21 14:22:20 c910f03c17k33 xcat[5613]:  xcatd install monitor 5613 quiescing

Apr 21 14:22:20 c910f03c17k33 xcat[5614]:  INFO xcatd: 'Command log writer' process 5614 is terminated by TERM or INT signal
Apr 21 14:22:20 c910f03c17k33 xcat[5611]:  xcatd udp service 5611 quiescing
Apr 21 14:22:23 c910f03c17k33 xcat[5710]:  INFO xcatd: command log process 5710 start

**Comment by tingtli** [comment]
Close this bug since it is fixed. Open a new bug #972 to trace the new issue.

**Comment by chenglch** [comment]
[issue_537_xcat_2.9.1.zip](https://github.com/xcat2/xcat-core/files/331420/issue_537_xcat_2.9.1.zip)
This is a patch to fix this issue for xcat 2.9.1. Follow the steps below:

    unzip issue_537_xcat_2.9.1.zip
    cd /opt/xcat
    patch -p1 < issue_537_xcat_2.9.1.patch


@tingtli , Can you help to test this patch?

**Comment by whowutwut** [comment]
@chenglch  Is there a pull request for the changes in the patch so we know exactly the code changes that will go into the 2.9 branch and can review it also?

**Comment by daniceexi** [comment]
@chenglch has made a pull request for 2.9 to include this fix. But looks like the change is huge. Since this issue only happens when restarting xcatd and it's harmless for xcat functionalities, I don't recommend merge this fix for 2.9.

**Comment by tingtli** [comment]
I think this is same problem with bug #1008

**Comment by tingtli** [comment]
@chenglch  use 7/6 build, i still get the error message in /var/log/xcat/cluster.log when I restart xcatd.

```
Jul  7 03:43:59 c910f03c04k05 xcat[11824]: INFO xcatd: command log process 11824 start
Jul  7 03:44:00 c910f03c04k05 xcat[11821]: xcatd udp service 11821 quiescing
Jul  7 03:44:00 c910f03c04k05 xcat[11824]: INFO xcatd: 'Command log writer' process 11824 is terminated by TERM or INT signal
Jul  7 03:44:00 c910f03c04k05 xcat[11823]: xcatd install monitor 11823 quiescing
Jul  7 03:44:02 c910f03c04k05 xcat[11821]: xcatd: xcatd: UDP listener Error happened when receiving data from DB access process Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /opt/xcat/lib/perl/xCAT/Table.pm line 131.
Jul  7 03:44:04 c910f03c04k05 xcat[11957]: INFO xcatd: command log process 11957 start
```

**Comment by tingtli** [comment]
same with defect #1008. close it
