### ISSUE TITLE
CentOS 7.5 tftp pxe issues

### ISSUE THREAD

**Issue by paddyoneill** [xcat2/xcat-core#5395]
Hi, 

I am having a problem with PXE and tftp on CentOS 7.5. When I run nodeset osimage=<image> it doesn't create /tftpboot/pxelinux.0, instead it creates /pxelinux.0.

If I move that to the /tftpboot directory and boot compute nodes they all fail to find pxe configs.

tftpdir is set to /tftpboot in the site table

[root@os1 ~]# tabdump site
.
.
"tftpdir","/tftpboot",,
.
.

This is using xcat Version 2.14.1 (git commit 70d6e7f93cc9714a127c22df2e7ca53d4996a34c, built Fri Jun  1 03:00:53 EDT 2018)
Installed using go-xcat on a clean CentOS 7.5 install

**Comment by immarvin** [comment]
hi @paddyoneill , please provide the node definition by `lsdef <node>`, notice the `tftpdir` attribute by `lsdef <node> -i tftpdir`

**Comment by paddyoneill** [comment]
Hi @immarvin, here is the output of lsdef for a node. I have tried to set tftpdir using chdef but that hasn't made any difference, still seeing the same behaviour.

[root@os1 ~]# lsdef os2
Object name: os2
    arch=x86_64
    currchain=boot
    currstate=install centos7.5-x86_64-compute
    groups=openstack,all
    installnic=mac
    ip=192.168.0.2
    netboot=pxe
    os=centos7.5
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    primarynic=mac
    profile=compute
    provmethod=centos7.5-x86_64-install-compute
    tftpdir=/tftpboot

Note that mac is set, I just removed that for posting here

**Comment by paddyoneill** [comment]
I rolled back to CentOS 7.4 and everything works again. Not sure if something has changed with the tftp setup between the two CentOS releases that would cause this behaviour.

**Comment by whowutwut** [comment]
@gurevichmark was looking into this issue on Friday.. any update?

**Comment by gurevichmark** [comment]
@paddyoneill Have you tried CentOS 7.5 with `netboot=xnba` is there a reason it needs to be `netboot=pxe` ?

**Comment by paddyoneill** [comment]
@gurevichmark No reason for pxe specifically, just more familiar with it. I can test again on 7.5 this week and try xnba.
I will post updates here when I have them.

**Comment by hu-weihua** [comment]
@gurevichmark, Could you close this issue if there is no more issues? thank you very much.
