### ISSUE TITLE
updatenode -F stopped working in 2.14.2

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5403]
`updatenode -F` seems to have stopped working in 2.14.2 and fails with the following message in some cases:

```
# updatenode sh-sl01 -FV
Error: [sh-hn01]: No osimage names specified to process.
The call to CFMUtils to build synclist returned an errorcode=1.
```

Here's the `lsdef` output for that node:
```
# lsdef sh-sl01
Object name: sh-sl01
    arch=x86_64
    bmc=sh-sl01.ipmi
    bmcport=1
    chain=runcmd=bmcsetup,shell
    cons=ipmi
    consoleenabled=1
    cpucount=20
    cputype=Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
    currchain=boot
    currstate=boot
    disksize=sda:800GB
    groups=slurm,svc,srv
    height=1
    ip=10.10.0.11
    mac=18:66:da:7b:de:a6
    memory=64317MB
    mgt=ipmi
    mtm=DELL:PowerEdge R630
    netboot=xnba
    nicaliases.bmc=sh-sl01
    nicips.bmc=10.11.0.11
    nicnetworks.bmc=net_ipmi
    nictypes.bmc=bmc
    ondiscover=nodediscover
    os=centos7.5
    postbootscripts=syncfiles,sherlock/postboot
  postscripts=syslog,remoteshell,syncfiles,otherpkgs,confignetwork,hardeths,setroute,setupntp,sherlock/postinstall
    prescripts-begin=osimage:sherlock/add_shosts.sh,sherlock/slurm_down.sh
    rack=T17
    room=SRCF
    serial=8ZRKMD2
    serialport=0
    serialspeed=115200
    servicenode=sh-hn01
    status=booted
    statustime=07-03-2018 14:26:41
    supportedarchs=x86_64
    switch=sh-ethsw-core
    switchinterface=em1
    switchport=1/0/5
    unit=3
    updatestatus=syncing
    updatestatustime=06-07-2018 11:53:48
```

Any idea what changed and what to look for to fix this?

**Comment by kcgthb** [comment]
@immarvin `sh-hn01` is the Master Node, from which I'm running the `updatenode` command. I don't think it ever had (nor should have) a `osimage` property, should it?

**Comment by immarvin** [comment]
if sh-sl01 is the master node, why you run ` updatenode sh-sl01 -FV` against the master node?

**Comment by kcgthb** [comment]
I am not. Those are different nodes:
* `sh-hn01` is the master node,
* `sh-sl01` is the node I'd like to update files on.

I am on the MN (`sh-hn01`), and I run `updatenode sh-sl01 -F`.

**Comment by robin2008** [comment]
@kcgthb no `provmethod` on `sh-sl01` too, I think it is the  cause.

**Comment by kcgthb** [comment]
Aaah, you're right @robin2008, `provmethod` got removed by mistake after some cleaning in the `nodetype` table.  Adding it back fixes the issue.

Thanks!
