### ISSUE TITLE
SLES12 SP3: xCAT is not honouring bootparams.kcmdline for kdump crashkernel settings

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/xcat-core#5406]
xCAT ignores setting crashkernel kernel parameters for kdump when setting bootparams.kcmdline.
Example:

lsdef node01 -ci kcmdline
node01: kcmdline=biosdevname=1 crashkernel=155M,high crashkernel=72M,low

In this example xCAT only passes the biosdevname=1 option to the node configuration on installation but ignores both the crashkernel settings if you run "cat /proc/cmdline" on the installed node.

You can edit the grub configuration manually and set include the crashkernel options and the system boots correctly.

OS: SLES12SP3
Arch: x86_64

xCAT version: 
lsxcatd -v
Version 2.13.8.lenovo3

**Comment by cxhong** [comment]
instead of kcmdline, can u try to use addkcmdline
```
chdef node01 addkcmdline="biosdevname=1 crashkernel=155M,high crashkernel=72M,low"
```
then run `nodeset` command, it should appear in the `/tftpboot/xcat/xnba/nodes/node01`

**Comment by dbrajendra** [comment]
I have set kcmdline and addkcmdline to be the same run: nodeset osimage=image, rsetboot net -u, rpower boot to reinstall the node but the crashkernel settings are not configured, only biosdevname=1 is configured on the installed system.

you are correct the xCAT places the settings for the installer as we expect.
Output edited:

``# cat /tftpboot/xcat/xnba/nodes/node01
#!gpxe
#install sles12.3-x86_64-os
imgfetch -n kernel http://${next-server}/tftpboot/xcat/osimage/fm/linux
imgload kernel
imgargs kernel quiet autoyast=http://masterip:80/install/autoinst/fm02 install=http://masterip:80/install/sles12.3/x86_64/1 netdevice=mac  console=tty0 console=ttyS0,115200 biosdevname=1 crashkernel=155M,high crashkernel=72M,low  BOOTIF=01-${netX/machyp}
imgfetch http://${next-server}/tftpboot/xcat/osimage/os/initrd
imgexec kernel

"# lsdef node01 -ci addkcmdline,kcmdline
node01: addkcmdline=biosdevname=1 crashkernel=155M,high crashkernel=72M,low
node01: kcmdline=biosdevname=1 crashkernel=155M,high crashkernel=72M,low

On the installed node01 after installation:
"# grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet console=tty0 console=ttyS0,115200 biosdevname=1 resume=/dev/sda3 splash=silent quiet showopts"

"# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.4.126-94.22-default root=/dev/mapper/system-slash ro quiet console=tty0 console=ttyS0,115200 biosdevname=1 resume=/dev/sda3 splash=silent quiet showopts

So you can see xCAT is passing the biosdevname parameter to the node grub configuration but not the crashkernel settings.

"# lsdef node01 (output edited)
Object name: node01
    addkcmdline=biosdevname=1 crashkernel=155M,high crashkernel=72M,low
    arch=x86_64
    bmc=node01bmc
    bmcpassword=bmcpass
    bmcport=1
    bmcusername=bmcuser
    chain=runcmd=bmcsetup,shell
    cons=ipmi
    conserver=ip
    currchain=boot
    currstate=boot
    groups=ipmi
    installnic=mac
    kcmdline=biosdevname=1 crashkernel=155M,high crashkernel=72M,low
    mac=mac
   mgt=ipmi
    netboot=xnba
    ondiscover=nodediscover
    os=sles12.3
    postbootscripts=otherpkgs,postscripta
    postscripts=syslog,remoteshell,setupntp,syncfiles,postscriptb
    primarynic=eth0
    profile=os
    provmethod=os
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=07-17-2018 17:05:37
    supportedarchs=x86,x86_64
    switch=switch1
    switchport=26
    updatestatus=synced
    updatestatustime=07-17-2018 17:23:19
    xcatmaster=ip

node o/s versions:

"# cat /etc/os-release 
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

"# uname -r (we are not using a base sles 12 sp3 kernel but later patched kernel):
4.4.126-94.22-default

**Comment by cxhong** [comment]
@dbrajendra , can u add "R::" ?
```
addkcmdline

User specified kernel options for os provision process(no prefix) or the provisioned os(with prefix “R::”). The options should be delimited with spaces(” “)

```

**Comment by immarvin** [comment]
any update on this @dbrajendra

**Comment by dbrajendra** [comment]
I tried using R:: but it did not help. biosdevname=1 is passed but not the other crashkernel settings. I think I will have to put the parameters into /etc/default/grub and rebuild the grub config. That works if i do it manually so i know what I am trying to add to the kernel boot is legitimate.
xCAT does not like it. Maybe it does not like commas in the kernel parameters or there is something in SLES itself that is blocking it.

**Comment by immarvin** [comment]
hi @dbrajendra , what is the osimage definition after you add `R::`?

**Comment by ChrisPJames** [comment]
as an FYI - the above issue is also true for RHEL/CentOS systems whether its version 6 or 7.

**Comment by immarvin** [comment]
```
[root@boston36 ~]# chdef -t osimage -o sles12.3-ppc64le-install-compute addkcmdline="R::biosdevname=1 R::crashkernel=155M,high R::crashkernel=72M,low"

[root@boston36 ~]# lsdef -t osimage -o sles12.3-ppc64le-install-compute -i addkcmdline
Object name: sles12.3-ppc64le-install-compute
    addkcmdline=R::biosdevname=1 R::crashkernel=155M,high R::crashkernel=72M,low
[root@boston36 ~]#

```

after `nodeset`, the autoyast template file includes the options:
```
[root@boston36 ~]# nodeset mid21tor24cn01 osimage=sles12.3-ppc64le-install-compute
mid21tor24cn01: install sles12.3-ppc64le-compute
[root@boston36 ~]#
[root@boston36 ~]# cat /install/autoinst/mid21tor24cn01|grep kernel_parameters -A5 -B5
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <install>
    <bootloader>
      <write_bootloader config:type="boolean">true</write_bootloader>
      <activate config:type="boolean">true</activate>
      <kernel_parameters>biosdevname=1 crashkernel=155M,high crashkernel=72M,low </kernel_parameters>
      <lba_support config:type="boolean">false</lba_support>
      <linear config:type="boolean">false</linear>
      <location>mbr</location>
    </bootloader>
    <general>
```

**Comment by sujit-jadhav** [comment]
@immarvin I am using xCAT Version 2.16.5 and trying to provision rhel8.8 and given the addkcmdline="R::biosdevname=1 R::crashkernel=155M,high R::crashkernel=72M,low"
But it is not updated in cat /install/autoinst/node1|grep kernel parameters 
neither it is present in /etc/default/grub on compute node after provision of OS.

I want to know does addkcmdline option work for a node. I tried updating node definition and osimage as well, but nothing is helping out. Any suggestion on this?
