### ISSUE TITLE
Specifying osimage for rinstall command

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5427]
xCAT man page and usage indicate that `rinstall <node> <imagename>` is valid.
But it does not appear to start the installation. However `rinstall <node> osimage=<imagename>` works.

After some investigation and discussion the following should be fixed for `rinstall` command:
1. Man page and usage changed to show that `rinstall <node> osimage[=<imagename>]` is valid format.
2. Error should be displayed for `rinstall <node> abc`.
3. Error should be displayed for `rinstall <node> xyz=abc`.
4. Error should be displayed for `rinstall <node> runcmd=abc`, man page says only `runcmd=bmcsetup` is allowed.
5. Better error should be displayed for `rinstall mid21tor24cn01 osimage=abc`, today it displays `Error: [boston36]: abc 'osarch' attribute not defined in 'osimage' table.`

**Comment by zet809** [comment]
Oh, yeah, the `rinstall <node> <imagename>` shall be `rinstall <node> osimage` which means to deploy the osimage object which have been specified to `provmethod` attr of the node.

**Comment by gurevichmark** [comment]
@zet809 Yes, man page should be fixed, but I also think we should catch something like `rinstall <node> abc` and display an error.

**Comment by immarvin** [comment]
hi @gurevichmark , can we close this ticket ? since your fix has been merged
