### ISSUE TITLE
rinstall runcmd can not work correctly as before

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#5446]
xcat version ``Version 2.14.3 (git commit 738e5c8814398225949760471bb28982cf2627a5, built Fri Jul 27 06:15:55 EDT 2018)``

``rinstall`` ``runcmd`` can not work correctly as before

The output like below:
```
[root@f6u13k13 ~]# rinstall f6u13k15  "runcmd=cmdtest,shell"
Error: [f6u13k13]: Invalid option runcmd=cmdtest,shell
Usage:
   rinstall <noderange> [boot | shell | runcmd=bmcsetup] [-c|--console] [-u|--uefimode] [-V|--verbose]
   rinstall <noderange> osimage[=<imagename>] [--ignorekernelchk] [-c|--console] [-u|--uefimode] [-V|--verbose]
   rinstall <noderange> runimage=<task>
   rinstall [-h|--help|-v|--version]
```

It seems the change in PR #5437 trigger this issue.

**Comment by hu-weihua** [comment]
@gurevichmark , could you help to fix this issue? thanks

**Comment by gurevichmark** [comment]
@whowutwut How did it work before ?

The man page and usage show that `runcmd=bmcsetup` is the only valid option. Everything else, I think, should return an error.

**Comment by zet809** [comment]
Hi, @gurevichmark , in fact, `bmcsetup` is not the only valid paramter for `runcmd`, any command supported in genesis kernel can be specified here. For example `runcmd=date`, `runcmd="ls /"` or even `runcmd=dodiscover`.
So, runcmd means run a command supported in genesis kernel, runimage means download a file from server, then run runme.sh inside the file.

**Comment by gurevichmark** [comment]
@zet809 Thanks for clarification, so it seems our man page and usage should be changed. Do you think we should allow multiple commands for the `runcmd=`, like `runcmd=dodiscover,date,ls` ?

**Comment by hu-weihua** [comment]
Have been verified in automation environment, close this issue. thanks @gurevichmark
