### ISSUE TITLE
[DEV]the xcat.log file can't record scripts information when executing run_ps subroutine.

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#547]
In the post.xcat script file, we use the run_ps subroutine to run the other scripts.
In the run_ps subroutine, we use the ``bash -x ./\$@ 2>&1`` to output the information and we record the information to the ``/var/log/xcat/xcat.log`` file.

Using the latest release, this information can't be saved to the ``xcat.log`` file.

There is a workaround for this situation. 
We can use the ``bash -x ./\$@ 2>&1 | tee -a \$logfile`` instead of the ``bash -x ./\$@ 2>&1`` at risk of the xcat.log file conflict since this file is still used to record information.
We need another way to fix it.

**Comment by whowutwut** [comment]
Also, Should we look whether we should be saving the stdout and stderr output into two files? .out and .err? Should there be logging files for postscripts now that we have a directory for xcat? Would that help the user because they could easily see errors that care output in the err output file

**Comment by penguhyang** [comment]
Hi, @whowutwut , thanks for looking.
I think saving the stdout and stderr output into two files is a good idea. @immarvin
Currently, for the compute node, there is a logging file called ``xcat.log`` in ``/var/log/xcat/`` directory which will record stdout and stderr.

**Comment by immarvin** [comment]
@whowutwut , seperating STDERR and STDOUT into different files will make it difficult to position the  root cause of the problem, users have to  make up the time line of entries in 2 files according to the time stamps.

**Comment by whowutwut** [comment]
@immarvin can you give an example of why we need to line up the time stamp?  I think the error should be descriptive enough to identify.. It should be a fatal error that we record in the .err file. If we are using the same message then maybe we need to fix The msg to be more clear? 

I think currently if there is an error we don't stop the postscript process. So it's ok for errors to happen. That makes it also hard to debug

**Comment by penguhyang** [comment]
I will fix this issue using this method ``bash -x ./\$@ 2>&1 | tee -a \$logfile``.
@whowutwut @immarvin I think we can discuss about this topic about  whether we should be saving the stdout and stderr output into two files? .out and .err?
What do you think?
