### ISSUE TITLE
geninitrd.pm looks up wrong key in get_site_attribute() call

### ISSUE THREAD

**Issue by pawsey-kbuckley** [xcat2/xcat-core#5476]
xCAT-server/lib/perl/xCAT_plugin/geninitrd.pm

has code that does this (Lines 182-183)

```
    my $tftpdir = "/tftpboot";
    my @entries = xCAT::TableUtils->get_site_attribute("$tftpdir");
```

but that's wrong, and ``@entries`` will always be empty.

The key in xCAT's ``site`` table is the string ``tftpdir`` **not** the string ``/tftpboot``,
so that ``get_site_attribute`` call should be using the bare string and not the 
value of the variable ``$tftpdir``, of the same name .

I suggest the code should be

```
    my $tftpdir = "/tftpboot";
    my @entries = xCAT::TableUtils->get_site_attribute("tftpdir");
```

Of course, this only trips up people who change the xCAT defaults
for ``tftpdir`` and ``installdir`` so that they are no longer in the root
directory, but it's still a bug.

Pull request coming once I have generated an Issue number to 
use as a branch name.

--
Kevin M. Buckley
Supercomputing Systems Administrator
Pawsey Supercomputing Centre

**Comment by zet809** [comment]
Use #5531 to fix this issue, the fix will be included in 2.14.3 release in Aug 24 2018. So, close this issue. Thx @pawsey-kbuckley
