### ISSUE TITLE
[Customer] Updatenode otherpkgs non-zero return code due to MOFED repository conflicts

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#549]
```
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)
```

After installing Mellanox OFED 3.1-1.0.6.1 on Red Hat 7.2, yum update fails with the following errors:

```
Error: Package: mpitests_openmpi__1_8_8-3.2.16-fe5387c.ppc64le (installed)
           Requires: liboshmem.so.3()(64bit)
           Removing: openmpi-1.8.8-1.ppc64le (installed)
               liboshmem.so.3()(64bit)
           Updated By: openmpi-1.10.0-10.el7.ppc64le (xCAT-rhels7.2rc-path0)
               Not found
Error: Package: libibmad-static-1.3.11.MLNX20150329.b2cb00f-0.1.ppc64le (installed)
           Requires: libibmad = 1.3.11.MLNX20150329.b2cb00f-0.1
           Removing: libibmad-1.3.11.MLNX20150329.b2cb00f-0.1.ppc64le (installed)
               libibmad = 1.3.11.MLNX20150329.b2cb00f-0.1
           Updated By: libibmad-1.3.12-1.el7.ppc64le (xCAT-rhels7.2rc-path0)
               libibmad = 1.3.12-1.el7
Error: Package: libibmad-devel-1.3.11.MLNX20150329.b2cb00f-0.1.ppc64le (installed)
           Requires: libibmad = 1.3.11.MLNX20150329.b2cb00f-0.1
           Removing: libibmad-1.3.11.MLNX20150329.b2cb00f-0.1.ppc64le (installed)
               libibmad = 1.3.11.MLNX20150329.b2cb00f-0.1
           Updated By: libibmad-1.3.12-1.el7.ppc64le (xCAT-rhels7.2rc-path0)
               libibmad = 1.3.12-1.el7
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
```

When we run updatenode ospkgs or otherpkgs, xcat sets up RH72 repositories on the node. Several of the rpm levels from the Red Hat distro are newer versions of the IB rpms from Mellanox.
When xCAT updatenode ospkgs or otherpkgs, "yum upgrade" is run and results in a non-zero return code:     ``Postscript: otherpkgs exited with code 1``

updatenode successfully updates or installs the packages from the pkglist or KIT.
It is not recommended that you use the --skip-broken option because you do not want to install  the distro InfiniBand rpms. It is recommended by Mellanox to use an exclude list to /etc/yum.conf:
"exclude=dapl* libib* ibacm infiniband* libmlx* librdma* opensm* ibutils*" 
This issue being looked at by Mellanox, in the meantime can we add information for a post script or documentation to add this exclude list after installing Mellanox OFED?

**Comment by hu-weihua** [comment]
@markprez, thank you so much for offering us such valuable information. sorry for reply such later at same time.
I will find a appropriate way to resolve this problem.   thanks again

**Comment by hu-weihua** [comment]
@markprez I have updated document, make this problem as a known issue and share your tips for others.  Thank your contribution very much.

**Comment by hu-weihua** [comment]
@markprez, could you review the doc and close this issue? thanks

**Comment by daniceexi** [comment]
@markprez we close this issue now, please reopen this issue if you have comment.
