### ISSUE TITLE
add rinstall option to skip rebuilding initrd when osdistroupdate/netdrivers is used

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5497]
`nodeset` has a `--noupdateinitrd` option to skip rebuilding the `initrd` image when an `osimage` has a `osupdatename` and `netdrivers` attributes, but `rinstall` doesn't.

As a result, each call to `rinstall` will rebuild the initrd, which is quite slow, on *each* Service Node:
1. that could probably be only done on the SN serving the node being deployed,
2. there should be a mechanism to disable this, to speed up operations.

Is there even a need to rebuild `initrd`s via `nodeset`/`rinstall`? Shouldn't that operation be just handled when `geninitrd` is explicitly run by the user?

Ideally, there should be a site-wide option (in the `site` table, for instance) to enable or disabling building `initrd`s at each `nodeset`/`rinstall` invocation. What do you think?

**Comment by gurevichmark** [comment]
Running `nodeset` generates `initrd` for each image. Gets stored in `/tftpboot/xcat/osimage/<image name>`

**Comment by kcgthb** [comment]
Hi @gurevichmark 
I understand this, but my point was that `nodeset` takes a `--noupdateinitrd` option, whereas `rinstall` doesn't. As a result, each time a node is redeployed, the `rinstall` commands takes a very long time to complete, when `netdrivers` is used. For large clusters, this is an issue.

Plus, `initrd`s are per _image_ , not per node, so it makes sense to (re-)generate them with `geninitrd`, which is an image-level command, but I don't think it's useful to generate them at each `nodeset` or `rinstall` invocation, since those are node-level commands.

Even better, why not do this?
1. keep the `geninitrd` command to explicitly generate new `initrd`s,
2. don't generate `initrd` by default in `nodeset`/`rinstall`
3. remove the `--noupdateinitrd` option from `nodeset` and replace it with a `--updateinitrd` option in `nodeset` and `rinstall` (move from the current opt-out to an opt-in approach)

This way, large redeployment of nodes would not be hindered by the need to regenerate the `initrd` for every single node, it could be done just once at the image level, and still keep the possibility to do one-off `initrd` generations from `nodeset` or `rinstall` if needed.

Does that make sense? What do you think?

**Comment by gurevichmark** [comment]
@kcgthb Thanks for bringing up this issue. Will discuss it with the team in the next day or so. My comment above was just a reminder note.

**Comment by kcgthb** [comment]
HI @gurevichmark 
Thanks for the update! 

I understand the decision in 3. and thanks for the suggestion in 2.

For 1., may I ask if it would also be possible to disable the initrd re-generation via an environment variable, in addition to the the command-line option? It's a bit cumbersome to add this option to every `rinstall` call when one's used to just call `rinstall nodename`.
Something like `XCAT_NOINITRDUPDATE` or similar, that would disable initrd generation when defined?

Thanks!

**Comment by gurevichmark** [comment]
Does anyone know why we need to run `nodeset` each time `xcatd` is restarted on SN ?

**Comment by gurevichmark** [comment]
I think this issue can be closed. A `site` table attribute will be added to control initrd regeneration using #5561

**Comment by tingtli** [comment]
@kcgthb  Would you please close this defect since it is resolved.

**Comment by kcgthb** [comment]
Will be glad to do so after testing the feature. Could you please let me know in which PR/commit it's been implemented?

**Comment by zet809** [comment]
It seems PR #5523 include the fix for rinstall.
For `site` table attribute, it can be traced with #5561

**Comment by kcgthb** [comment]
Thanks! #5523 looks great!
For the site attribute though, I know it's been mentioned in #5561, but I can't find any PR implementing it, nor any reference in the master branch.

**Comment by gurevichmark** [comment]
There is no PR for #5561 yet. Is it in my backlog. Hope to work on it for next release.

**Comment by kcgthb** [comment]
@gurevichmark No worries, thanks for the clarification!

**Comment by kcgthb** [comment]
Just tested #5523 in 2.14.4, and can't seem to make it work. Even with `--noupdateinitrd`, the `initrd` are still updated (that is in hierachical mode, I don't know if it makes a difference)

```
# ls -al /tftpboot/xcat/osimage/sherlock-compute_cpu/
total 57740
drwxr-xr-x  2 root root       37 Oct 19 11:40 .
drwxr-xr-x 11 root root     4096 Jul 31 16:31 ..
-rw-r--r--  1 root root 52893200 Oct 19 11:41 initrd.img
-rwxr-xr-x  1 root root  6224704 Oct 19 11:41 vmlinuz

# time rinstall sh-107-37 --noupdateinitrd -V
[sh-hn01]: Provision node(s): sh-107-37
[sh-hn01]: Run command: nodeset sh-107-37 osimage
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/presyncfiles.sh for nodes sh-107-37.
[sh-hn01]: Handle the driver update disk failed. Could not gunzip the initial initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: sh-hn02.SUNet: sherlock/presyncfiles.sh: File synchronization has completed for service nodes: "sh-hn02"
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/event.sh for nodes sh-107-37.
[sh-hn01]: sh-hn02.SUNet: sherlock/event.sh: sending notifications...
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/add_shosts.sh for nodes sh-107-37.
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/slurm_down.sh for nodes sh-107-37.
[sh-hn01]: Handle the driver update disk failed. Could not gunzip the initial initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: All the drivers from: /install/updates/Packages/kernel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-abi-whitelists-3.10.0-862.14.4.el7.noarch.rpm,/install/updates/Packages/kernel-debug-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-debug-devel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-devel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-doc-3.10.0-862.14.4.el7.noarch.rpm,/install/updates/Packages/kernel-headers-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-libs-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-libs-devel-3.10.0-862.14.4.el7.x86_64.rpm have been injected to initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/presyncfiles.sh for nodes sh-107-37.

[sh-hn01]: Handle the driver update disk failed. Could not gunzip the initial initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: sh-hn02.SUNet: sherlock/presyncfiles.sh: File synchronization has completed for service nodes: "sh-hn02"
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/event.sh for nodes sh-107-37.
[sh-hn01]: sh-hn02.SUNet: sherlock/event.sh: sending notifications...
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/add_shosts.sh for nodes sh-107-37.
[sh-hn01]: sh-hn02.SUNet: Running begin script sherlock/slurm_down.sh for nodes sh-107-37.
[sh-hn01]: Handle the driver update disk failed. Could not gunzip the initial initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: All the drivers from: /install/updates/Packages/kernel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-abi-whitelists-3.10.0-862.14.4.el7.noarch.rpm,/install/updates/Packages/kernel-debug-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-debug-devel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-devel-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-doc-3.10.0-862.14.4.el7.noarch.rpm,/install/updates/Packages/kernel-headers-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-libs-3.10.0-862.14.4.el7.x86_64.rpm,/install/updates/Packages/kernel-tools-libs-devel-3.10.0-862.14.4.el7.x86_64.rpm have been injected to initrd.
[sh-hn01]: sh-107-37: install centos7.5-x86_64-cpu
[sh-hn01]: Run command: rsetboot sh-107-37 net
[sh-hn01]: sh-107-37: Network
[sh-hn01]: Run command: rpower sh-107-37 boot
[sh-hn01]: sh-107-37: reset

real    1m27.604s
user    0m0.268s
sys     0m0.050s

# ls -al /tftpboot/xcat/osimage/sherlock-compute_cpu/
total 70656
drwxr-xr-x  2 root root       37 Oct 19 11:40 .
drwxr-xr-x 11 root root     4096 Jul 31 16:31 ..
-rw-r--r--  1 root root 66121650 Oct 19 11:42 initrd.img
-rwxr-xr-x  1 root root  6224704 Oct 19 11:42 vmlinuz
```

**Comment by kcgthb** [comment]
Oh I see that if I use `rinstall <node> osimage=<osimage> --noupdateinitrd`, the `--noupdateinitrd` flag seem tobe working and the `initrd` is not regenerated.

But if `osimage=<osimage>` is omiited, the  `--noupdateinitrd` flag is ignored and the `initrd` is regenerated anyway.

Do you confirm this?

**Comment by gurevichmark** [comment]
Interesting. Can you check if the behavior the same for `nodeset` ? The PR #5523 just passes the `--noupdateinitrd` flag to `nodeset`, expecting it to do the right thing.

**Comment by kcgthb** [comment]
Well I think `nodeset` requires at least a command, so the `osimage` argument can't really be omitted, can it?

But in any case, both commands below properly work and don't regenerate the `initrd`:
* ` nodeset <node> osimage --noupdateinitrd -V`
* ` nodeset <node> osimage=<osimage> --noupdateinitrd -V`

**Comment by zet809** [comment]
hi, @kcgthb , the PR have been merged to master, will you pls help to verify with latest dev build? Thx!

**Comment by kcgthb** [comment]
Hi @zet809 
Yes, just tested it and I can confirm that it works as expected. Thanks!

**Comment by kcgthb** [comment]
Closing #5497 as resolved.
