### ISSUE TITLE
Nodes being provisioned in postbooting, xCAT allows postscripts to be run, causing issues?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5498]
I'm not sure what problems this may have caused....

For nodes that are in postbooting, running `updatenode <> -P` will do some clean up on the machine: 

```
[root@mgt03 consoles]# updatenode f7n09 -P custom.ps/list_software
f7n09: rm: cannot remove '/tmp/postage/192.168.75.124/install/REPO/software/nvidia/cuda-core/9.2.88-396.29/repo/ppc64le': Directory not empty
f7n09: trying to download postscripts...
f7n09: postscripts downloaded successfully
f7n09: trying to get mypostscript from 192.168.75.124...
f7n09: Running postscript: custom.ps/list_software
^C
```

```
[root@mgt03 consoles]# lsdef f7n09 -i status
Object name: f7n09
    status=postbooting
```

**Comment by immarvin** [comment]
hi @whowutwut ,  I agree there maybe potential conflict here, we should add some kind of lock mechanism to prevent the  simultaneous node configuration with either "post configuration" during node deployment or `updatenode` after provisioned node.

**Comment by immarvin** [comment]
I suggest check the status of `xcatpostinit1` service in the beginning of `updatenode`, if it is not `active` or `inactive `, i.e, it is `activating`, means that post booting process is not completed, `updatenode` should complain and let user try latter

**Comment by immarvin** [comment]
hi @neo954 , would you please take a look at this issue ? thanks

**Comment by neo954** [comment]
Okay. I will look into this one.

**Comment by neo954** [comment]
@immarvin, Checking the status of `xcatpostinit` service is fine. But it will not prevent multiple `updatenode` run at the same time.

**Comment by neo954** [comment]
How about create a pid file under `/var/run` or `/var/tmp` or `/tmp` as a lock file? Just like what a regular daemon does.

**Comment by neo954** [comment]
It seems everything calls `xcatdsklspost`. Will implement a lock facility in `xcatdsklspost`.

**Comment by neo954** [comment]
The patch was merged. @whowutwut, It is great if you can verify the patch in your testing environment.

**Comment by whowutwut** [comment]
Closing this issue, if anyone sees this occur in the  future, feel free to reopen
