### ISSUE TITLE
snmpcfg fails to work on Flex System

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#550]
```
[root@mgmt01 ~]# rspconfig cmm,-cmm14 snmpcfg=enable
cmm17: SNMP enable: OK
cmm04: SNMP enable: OK
cmm11: SNMP enable: OK
cmm06: SNMP enable: OK
cmm05: SNMP enable: OK
cmm15: SNMP enable: OK
cmm18: SNMP enable: OK
cmm02: SNMP enable: OK
cmm12: SNMP enable: OK
cmm07: SNMP enable: OK
cmm08: SNMP enable: OK
cmm10: SNMP enable: OK
cmm19: SNMP enable: OK
cmm13: SNMP enable: OK
cmm01: SNMP enable: OK
cmm09: SNMP enable: OK
cmm03: SNMP enable: OK
cmm16: SNMP enable: OK
```

```
[root@mgmt01 ~]# rspconfig cmm,-cmm14 snmpcfg       
cmm10: SNMP: disabled
cmm12: SNMP: disabled
cmm08: SNMP: disabled
cmm06: SNMP: disabled
cmm19: SNMP: disabled
cmm01: SNMP: disabled
cmm02: SNMP: enabled
cmm03: SNMP: disabled
cmm18: SNMP: enabled
cmm07: SNMP: enabled
cmm15: SNMP: enabled
cmm04: SNMP: disabled
cmm05: SNMP: enabled
cmm11: SNMP: disabled
cmm13: SNMP: disabled
cmm09: SNMP: disabled
cmm17: SNMP: disabled
cmm16: SNMP: enabled
```

I am running the following version of xCAT

Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)

Any debugging steps to resolve the problem would be great

**Comment by arif-ali** [comment]
any ideas?

**Comment by arif-ali** [comment]
Any ideas on this, I am still having these issue

```
[root@mgmt01 ~]# rspconfig cmm17 sshcfg=enable snmpcfg=enable
cmm17: SNMP enable: OK
cmm17: SSH enable: OK
[root@mgmt01 ~]# rspconfig cmm17 sshcfg snmpcfg       
cmm17: SSH: enabled
cmm17: SNMP: disabled
```
If someone could help me to diagnose, then I would really appreciate

thanks,
Arif

**Comment by arif-ali** [comment]
/cc @jjohnson42 @daniceexi any ideas? Or do I need to dig into code, and diagnose with print statements or something?

I can SSH onto the cmm without a problem, but for some reason the snmpcfg doesn't want to work

**Comment by cxhong** [comment]
what's your version of net-snmp* ?  It may caused by source of net-snmp* rpms.

**Comment by arif-ali** [comment]
Hi @cxhong, thanks for looking

see below for details

```
net-snmp-perl-5.7.2-20.el7.x86_64
net-snmp-agent-libs-5.7.2-20.el7.x86_64
net-snmp-utils-5.7.2-20.el7.x86_64
net-snmp-5.7.2-20.el7.x86_64
net-snmp-libs-5.7.2-20.el7.x86_64
```

**Comment by arif-ali** [comment]
I have now updated to the latest version of net-snmp-*, and similar issue

```
[root@mgmt01 ~]# rpm -qa | grep snmp
net-snmp-libs-5.7.2-24.el7.x86_64
net-snmp-perl-5.7.2-24.el7.x86_64
net-snmp-agent-libs-5.7.2-24.el7.x86_64
net-snmp-utils-5.7.2-24.el7.x86_64
net-snmp-5.7.2-24.el7.x86_64
[root@mgmt01 ~]# rspconfig cmm17 sshcfg=enable snmpcfg=enable
cmm17: SNMP enable: OK
cmm17: SSH enable: OK
[root@mgmt01 ~]# rspconfig cmm17 sshcfg snmpcfg
cmm17: SSH: enabled
cmm17: SNMP: disabled
```

or do I actually need an older version?

**Comment by daniceexi** [comment]
@arif-ali

Since part of your cmm worked when running 'rspconfig' command to enable the snmp, the code of xcat should work. You may check a failed cmm manually to see whether the snmp setting failed in the cmm command line. 

xCAT run the following command in cmm CLI to enable the snmp: snmp -a3 -on -T system:<cmm>

and then run this command to set the user: users -n $uid  -ap sha -at set -ppw <password> -pp des -T system:<cmm>

**Comment by arif-ali** [comment]
Thanks @daniceexi,

The first command passes
```
system> snmp -a3 -on -T mm[p]  
OK
```
But the second one ...
```
system> users -n USERID -ap sha -at set -ppw -pp des -T mm[1] 
Configuring SNMPv3 failed
: password not compliant
The privacy password must be configured to a minimum length of 8 when enabling privacy protocol or
privacy protocol is enabled.
```
How do I reset the password on these CMMs, without having to insert the old passwod? as I have lost it, and the CLI doesn't allow to change it without it?

**Comment by daniceexi** [comment]
@arif-ali 
Did not you set the password in the **mpa** table for the cmm? 

From the result of rspconfig command **cmm17: SNMP enable: OK**, looks like the command **users** replied correct message like 'OK ...'

**Comment by arif-ali** [comment]
Yeah, it was set originally, and configured as well, but the password was changed a few times due to the nature of these CMMs requiring to do so. So in the process, may have lost the password on some of the chassis over the past 6 months. 

Nevertheless, I would have thought we can change the password on these systems without having to know the previous passwords. But it seems to configure the snmp, this is a sticking point. Seems like a factory reset of the CMMs coming my way :(

**Comment by arif-ali** [comment]
I will look at this, and diagnose what is going on, will let you know what the problem is later
