### ISSUE TITLE
postscript mlnxofed_ib_install failes for ubuntu16.04 + OFED-4.4-1.0.00

### ISSUE THREAD

**Issue by thilo-maurer** [xcat2/xcat-core#5500]
Installing Ubuntu 16.04 (diskful) and using xCAT-provided postscript `mlnxofed_ib_install.v2` to install Mellanox OFED fails. Using method as described at https://xcat-docs.readthedocs.io/en/stable/advanced/networks/infiniband/index.html.

Ubuntu installs successfully, also OFED installs successfully.
However the last lines executed by postscript `mlnxofed_ib_install`
```
#force openibd load all modules in need, restart again
sleep 1
service openibd restart
```
fail with
```
Unloading HCA driver:                                      [  OK  ]
Module mlx4_core does not exist, skipping...               [FAILED]
Module mlx4_ib does not exist, skipping...                 [FAILED]
Module mlx4_core does not exist, skipping...               [FAILED]
Module mlx4_en does not exist, skipping...                 [FAILED]
Module mlx5_core does not exist, skipping...               [FAILED]
Module mlx5_ib does not exist, skipping...                 [FAILED]
Module mlx5_fpga_tools does not exist, skipping...         [FAILED]
Module ib_umad does not exist, skipping...                 [FAILED]
Module ib_uverbs does not exist, skipping...               [FAILED]
Module ib_ipoib does not exist, skipping...                [FAILED]
Loading HCA driver and Access Layer:                       [  OK  ]
Module rdma_cm does not exist, skipping...                 [FAILED]
Module ib_ucm does not exist, skipping...                  [FAILED]
Module rdma_ucm does not exist, skipping...                [FAILED]
```

This happens still inside the ubuntu installer:
```
root       1235  0.0  0.0   3392  2496 hvc0     Ss+  17:55   0:00 /bin/sh /sbin/debian-installer
root       1259  0.0  0.0  27328 25280 hvc0     S+   17:55   0:09  \_ debconf -o d-i /usr/bin/main-menu
root       1265  0.0  0.0   3456  2944 hvc0     S+   17:55   0:00      \_ /usr/bin/main-menu
root      49227  0.0  0.0   3328  2112 hvc0     S+   18:57   0:00          \_ udpkg --configure --force-configure finish-install
root      49228  0.0  0.0   3392  2688 hvc0     S+   18:57   0:00              \_ /bin/sh /var/lib/dpkg/info/finish-install.postinst configure
root      49292  0.0  0.0   3136   960 hvc0     S+   18:57   0:00                  \_ log-output -t finish-install /usr/lib/finish-install.d/07preseed
root      49293  0.0  0.0   3392   768 hvc0     S+   18:57   0:00                      \_ /bin/sh -e /usr/lib/finish-install.d/07preseed
root      49294  0.0  0.0   3392   704 hvc0     S+   18:57   0:00                          \_ /bin/sh -e /bin/preseed_command preseed/late_command
root      49296  0.0  0.0   3136   896 hvc0     S+   18:57   0:00                              \_ log-output sh -c mkdir -p /target/var/log/xcat/; { cat /tmp/pre-install.log >> /target/var/log/xc
root      49297  0.0  0.0   3392  2368 hvc0     S+   18:57   0:00                                  \_ sh -c mkdir -p /target/var/log/xcat/; { cat /tmp/pre-install.log >> /target/var/log/xcat/xcat
root      49308  0.0  0.0   5376  4480 hvc0     S+   18:57   0:00                                      \_ /bin/bash /root/post.script
root      49388  0.0  0.0   5440  4352 hvc0     S+   18:57   0:00                                          \_ /bin/bash /root/post.script
root      49678  0.0  0.0   5632  4736 hvc0     S+   18:57   0:02                                              \_ /bin/bash ./mlnxofed_ib_install -p /install/ofed_iso/MLNX_OFED_LINUX-4.4-1.0.0.0-
root      20838  0.0  0.0   6656  6016 hvc0     S+   23:52   0:00                                                  \_ /bin/bash /etc/init.d/openibd restart
```

I assume - The reason for this failure is that the installer's children, being in a chroot environment seem to have no permissions to run the modules.

Interestingly, modifying the postscript to loop indefinitely until the command succeeds, allows to ssh into the node and one lands (to my surprise) in the chroot environment.
Here's what you get in that case:
```
root@node3:~# systemctl restart openibd.service
Running in chroot, ignoring request.
```

Now, since the node is rebooted anyhow after the completion of all postscripts, there is no need to start the openib deamon, and changing the last lines of the postscript into
```
#enable the service, such that is loads on each boot
systemctl enable openibd.service
```
will be the IMHO best and most performant way to complete the OFED installation.

Question is: Is this special to the combination ubuntu16.04 + ofed-4.4-1, or will this break for other combinations of ubuntu+ofed?

**Comment by immarvin** [comment]
hi @neo954 ,would you please take a look at this?  thx

**Comment by hu-weihua** [comment]
@thilo-maurer , sorry to reply very later. 

Long time ago,  script ``mlnxofed_ib_install.v2`` was developed as a ``postbootscript``, so the script restarts ``openibd`` after MLNX installation. Afterward, we thought ``mlnxofed_ib_install.v2`` as ``postscript`` is better, but did not moved the restart step out just because after test, it was harmless from function point of view in our original support scenarios. 

Yes, you are right, ``there is no need to start the openib deamon...`` inside installer. We plan to enhance  ``mlnxofed_ib_install.v2`` in 2.14.4 development cycle and test it on other supported os distros.  Thanks for your valuable suggestion again.

**Comment by robin2008** [comment]
This should be general, not only for ubuntu, put it high priority.

**Comment by robin2008** [comment]
@thilo-maurer   would you like to verify and close this?

**Comment by thilo-maurer** [comment]
In my production code I additionally have a ```systemctl enable openibd```, but unsure whether this is required or not (it may have be set by the installer?). Looks good otherwise.
