### ISSUE TITLE
Starting xcatd on service node will cause the database high CPU utilization on a large size cluster

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5505]
Starting xcatd on service nodes is different with starting xcatd on MN.
To keep the consistent, here it will re-generate the service configuration for its role. For example, dhcp lease, pxe files, and console configuration.

And we found that with a 4K+ nodes cluster, and a service nodes with only 200+ compute nodes, the generation of console settings take about 1 minutes, and the CPU of database will keep higher for a while.

**Comment by robin2008** [comment]
Setting `XCATRELOAD=1` could bypass the configuration regeneration during xcatd starting.

**Comment by robin2008** [comment]
With code level investigation, we found that even the SN manage 200+ nodes, the codes will still read all 4k+ nodes from DB, it is the root cause.

**Comment by robin2008** [comment]
The reason to loads all nodes from DB might be considering some CNs is behind by `sn1`, but its console server is `sn2`.  I don't think this is useful case.

If user want to do that, he need to set both `sn1` and `sn2` as its service node.

So here I want to modify the codes, when restart xcatd on service nodes, it only generate the console setting on its own compute nodes.  This will greatly reduce the DB accessing.

**Comment by daniceexi** [comment]
Good catch! We need some options for user to skip the useless but time consumption operation in a large cluster.

**Comment by robin2008** [comment]
Finally we find more places to enhance the performance greatly by deep analysis the posgresql query log.  The major two as below:

1,  `getopenbmccons` will fetch whole `nodelist` table twice (it is covered in https://github.com/xcat2/xcat-core/pull/5514)

Without the fix,  for rebooting all SNs for 4k nodes cluster in same time,  it fetch `nodelists` 8k times and each time will fetch all 4k+ records.

After the fix,  it only fetch `nodelist` 4k times and each time only fetch 1 records.

2, A performance design miss in `getAllNodeAttribs` from `Table.pm` module, the method will get a `site` attribute in a big loop.

we can see the below comparison of SQL execution by logs.
without the fix,  there are **28029** queries on DB when restarting xcatd on one SN,  and the `postgesql` daemon keep 60% CPU utilization for many seconds.
```
# grep execute postgresql-Thu.log|wc
  28029  345959 3036831
```
And after fix, there only **122** queries, and not see CPU higher anymore.
```
# grep execute postgresql-Thu.log.good|wc
    122    1626   13884
```

Compared with the above two, limit the SN scope might not a big problem.  Now it will fetch full `nodelist` 5 times for one SN,  ( For 16 SN,  it is 80 and its affordable for the DB ), so we will put this enhancement low priority.

**Comment by robin2008** [comment]
We will continue to check if there any other performance bottleneck when enable other services on SN. For example, dhcp.
