### ISSUE TITLE
when xcatdebugmode=1, non shell (/bin/sh) postscripts will not show output back on MN

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5510]
Was running this postscript and did not see any output: 
```
[root@briggs01 ~]# updatenode mid05tor12cn03 -P custom.ps/list_software
mid05tor12cn03: trying to download postscripts...
mid05tor12cn03: postscripts downloaded successfully
mid05tor12cn03: trying to get mypostscript from 172.12.253.27...
mid05tor12cn03: Running postscript: custom.ps/list_software
mid05tor12cn03: postscript: custom.ps/list_software exited with code 0
mid05tor12cn03: Running of postscripts has completed.
[root@briggs01 ~]#
```

Looking on the compute node, in `/var/log/xcat/xcat.log` I do see the output  of the postscript and executing it from `/xcatpost` is OK. 

I then ran another postscript just to make sure something else ran correctly, and I noticed that `set -x` was turned on in the output.  So this lead me to realize that `xcatdebugmode=1` 

Turning it off, I'm able to see the output of the script: 
```
[root@briggs01 ~]# chdef -t site clustersite xcatdebugmode=0
1 object definitions have been created or modified.
```

And the output appears:
```
[root@briggs01 ~]# updatenode mid05tor12cn03 -P custom.ps/list_software
mid05tor12cn03: trying to download postscripts...
mid05tor12cn03: postscripts downloaded successfully
mid05tor12cn03: trying to get mypostscript from 172.12.253.27...
mid05tor12cn03: Running postscript: custom.ps/list_software
mid05tor12cn03:
mid05tor12cn03: INFO: Listing xCAT information...
mid05tor12cn03:    IMAGENAME=ist.redhat-alt.install.DF
mid05tor12cn03:
mid05tor12cn03: INFO: Listing kernel information...
mid05tor12cn03:    KERNEL: 4.14.0-49.11.1.el7a.ppc64le
mid05tor12cn03:    INSTALLED KERNEL MODULES in /lib/modules
mid05tor12cn03:    --> 4.14.0-49.10.1.el7a.ibmnvidia.7.ppc64le
mid05tor12cn03:    --> 4.14.0-49.11.1.el7a.ppc64le
mid05tor12cn03:...
...
...
```

I would like to note that this `list_software` script is Python.

**Comment by immarvin** [comment]
seems the following complex pipe in run_ps() lost the output

```
 29      else
 30         ./$@ 2>&1 | tee -a $logfile | logger -t xcat.mypostscript -p debug
 31         ret_local=${PIPESTATUS[0]}
 32      fi
```

looking into it...

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/5515 with the help from @neo954

**Comment by immarvin** [comment]
the fix is merged, please take a try

**Comment by whowutwut** [comment]
@immarvin @hu-weihua Should we require or at least consider that fixes also come with some autotest UT that would expose this? It seems like this would be very easy to create an autotest, essentially create  a script that does an stdout/stderr output print and run it with both `xcatdebugmode=1` and `xcatdebugmode=0`, count the error message and make sure we get what we expect...  maybe count is not the best but should consider what changes are required if we add another script language...  maybe count the files and verify the output?? 

Otherwise i think we will not improve the bucket to keep up with this kind of testing.
