### ISSUE TITLE
xcatlib.sh doesn't encode hyphens, breaks confignetwork for devices with hyphenated names

### ISSUE THREAD

**Issue by jralbert** [xcat2/xcat-core#5511]
I ran into this while trying to have xcat configure a bridge called "br-mgmt" with the confignetwork postscript:

```
control101: ./xcatlib.sh: line 10: hashnicdevicesbr-mgmt=-mgmt,ens1f0.1234: command not found
control101: ./xcatlib.sh: line 10: hashnictypesbr-mgmt=-mgmt,bridge: command not found
control101: ./xcatlib.sh: line 10: hashnicipsbr-mgmt=-mgmt,192.168.0.31: command not found
control101: ./xcatlib.sh: line 10: hashnicnetworksbr-mgmt=-mgmt,VLAN1234: command not found
```

Ultimately it appears that confignetwork is relying on the `hashget()` and `hashencode()` functions in xcatlib.sh, which attempts to use the interface name in an `eval()`, resulting in the errors above. I note that `hashencode()` uses `sed` to replace dots, colons, and commas already; adding a similar replacement for hyphens appears to have resolved the issue:

```
         echo `echo $str_map | sed 's/\./xDOTx/g' | sed 's/:/xCOLONx/g' | sed 's/,/:xCOMMAx/g' | sed 's/-/xHYPHENx/g'`
```

Is there a reason why most bash-interacting characters aren't replaced this way? Could hyphens be included in the replacement list so hyphenated device names will work?

**Comment by bybai** [comment]
@jralbert Thanks for your pointing this enhancement, let me do unit test about it.
