### ISSUE TITLE
setupntp postscript warns "chronyd" not found  for  2.14.3 but exits with success RC=0

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5516]
2.14.2-GA  (11 July 2018) my postscript is working fine:
/var/log/xcat/xcat.log snippet on cn02:
```Wed Aug  1 19:50:57 UTC 2018 [info]: xcat.mypostscript: Running postbootscript: setupntp
inactive
syncing the clock ...
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Wed Aug  1 19:51:07 UTC 2018 [info]: xcat.mypostscript: postbootscript setupntp return with 0
...
Wed Aug  1 14:52:42 CDT 2018 [debug]: xcat.mypostscript: node booted successfully, reporting status...
Wed Aug  1 14:52:42 CDT 2018 [info]: xcat.mypostscript: provision completed.(cn01)
```
Since updating to Version 2.14.3 (git commit d1bf861f7bae8e322a8d5b33f0729d5c3fe0a2b7, built Mon Aug 13 06:15:45 EDT 2018), I now see:
-rwxr-xr-x 1 root root 7097 Aug 13 05:15 /install/postscripts/setupntp
-rwxr-xr-x 1 root root 6404 Aug 13 05:15 /install/postscripts/setupntp.traditional

When I run from the updated MGMT node (SN's are also running same 2.14.3 level):
```Tue Aug 14 12:48:51 CDT 2018 [info]: xcat.mypostscript: Running postscript: setupntp
Command "chronyd" not found.
active
systemctl stop ntpd
syncing the clock ...
WARNING: NTP Sync Failed before timeout. ntp server will try to sync...
Tue Aug 14 17:51:13 UTC 2018 [info]: xcat.mypostscript: postscript setupntp return with 0
```

With 2.14.3 builds, am I missing a pre-requisite to add to my pkglist?
collectd-chrony.ppc64le
chrony.ppc64le

It appears to default to ntp instead, but based on this date/time when i run xdsh compute uptime,
I am not sure it is succeeding.  With 2.14.2-GA postscripts these dates would all be the same - not about 3 minutes off.  I confirmed the cnXX-bmc time matches the current reported OS time (some off by 3 minutes), therefore confirming that the setupntp is failing now.
```
cn01:  08:12:38 up 13:44,  1 user,  load average: 440.56, 454.98, 457.07
cn02:  08:12:38 up 13:44,  1 user,  load average: 429.55, 444.58, 444.78
cn03:  08:12:38 up 13:44,  1 user,  load average: 412.89, 427.99, 428.51
cn04:  08:09:39 up 13:44,  1 user,  load average: 440.49, 456.16, 452.47
cn05:  08:09:33 up 13:44,  1 user,  load average: 434.88, 450.93, 452.36
cn06:  08:09:35 up 13:44,  1 user,  load average: 439.60, 454.36, 451.84
cn07:  08:09:43 up 13:44,  1 user,  load average: 428.55, 446.46, 448.27
cn08:  08:09:45 up 13:44,  1 user,  load average: 456.72, 438.64, 436.99
cn09:  08:09:57 up 13:44,  1 user,  load average: 457.05, 467.93, 467.03
cn10:  08:09:58 up 13:44,  1 user,  load average: 447.22, 461.13, 461.73
cn11:  08:09:55 up 10:14,  1 user,  load average: 473.23, 463.50, 462.30
cn12:  08:09:23 up 10:14,  1 user,  load average: 415.62, 389.36, 379.06
```

**Comment by neo954** [comment]
Hello @marksmit-ibm,

You can try [this patch](https://github.com/xcat2/xcat-core/pull/5520/commits/9be1fb0af684cf69d5b1683f462e97656f76dce2) if you have time. I think it may fix your problem. But I do not have enough information to recreate your problem. Thus, it is great if you can try this patch and report your test result back to this issue.

Thanks for your time and effort.

**Comment by marksmit-ibm** [comment]
Interesting: Two things fixed my configuration.
1. My  xcat/MGMT node was rebooted, I failed to run (need to add postscript) `makentp -a` .
I then tested by rebooting my CN's and I still see the 'not found' message, but the ntp.traditional does correct the time.  If I left my configuration this way, I agree, then issue 5520, Hide the 'command "chronyd" not found' error message would be needed.

2. Next I added chrony  to my netboot pkglist for my Compute nodes.  That avoided the xcat.log 
 "chronyd" not found,   error message. 
```# man makentp   (to learn)
# makentp -a
configuring management node: xcat1.
Will configure chronyd instead.
Calling ... /install/postscripts/setupntp 
Daemon chronyd configured.
configuring service nodes: sn02 sn01
sn01: trying to download postscripts...
sn01: postscripts downloaded successfully
sn01: trying to get mypostscript from 192.168.95.1...
sn01: Running postscript: setupntp
sn01: 2018-08-16T17:10:08Z chronyd version 3.2 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SECHASH +SIGND +ASYNCDNS +IPV6 +DEBUG)
sn01: 2018-08-16T17:10:08Z Initial frequency 0.499 ppm
sn01: 2018-08-16T17:10:12Z System clock wrong by -22.004473 seconds (step)
sn01: 2018-08-16T17:09:50Z chronyd exiting
sn01: postscript: setupntp exited with code 0
sn01: Running of postscripts has completed.

sn02: trying to download postscripts...
sn02: postscripts downloaded successfully
sn02: trying to get mypostscript from 192.168.95.1...
sn02: Running postscript: setupntp
sn02: 2018-08-16T17:11:55Z chronyd version 3.2 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SECHASH +SIGND +ASYNCDNS +IPV6 +DEBUG)
sn02: 2018-08-16T17:11:55Z Initial frequency -3.277 ppm
sn02: 2018-08-16T17:11:59Z System clock wrong by -96.312203 seconds (step)
sn02: 2018-08-16T17:10:23Z chronyd exiting
sn02: postscript: setupntp exited with code 0
sn02: Running of postscripts has completed.
```
Please notice that this time chronyd  works.

I think I can close this issue?  Should we have 'readthedocs'  updated to mention putting chrony rpm into the OS pkglist  ?

**Comment by robin2008** [comment]
@marksmit-ibm

**Comment by hu-weihua** [comment]
@marksmit-ibm, Could you help to verify this fix and close this issue? If you need further help, could you move the milestone  of this issue to 2.14.4? thank you very much.

**Comment by hu-weihua** [comment]
@marksmit-ibm, I will close this issue first. If you get further question in the future, feel free to reopen it. thanks.
