### ISSUE TITLE
Comma-separated syncfiles lists not supported by packimage

### ISSUE THREAD

**Issue by khm** [xcat2/xcat-core#5517]
If you have more than one syncfile in your osimage definition, it will work with updatenode and the syncfiles postscript, but not with packimage.

[packimage.pm on line 432](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/packimage.pm#L432) directly executes xdcp with a system() call, explicitly passing a syncfile to the command.  Because the file splitting occurs in [syncfiles.pm on line 122](https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/syncfiles.pm#L122), the splitting code is never called during genimage.

Packimage should support the same syncfiles configuration the rest of xCAT does -- instead of system() calls to run xdcp, packimage should call syncfiles() to update the rootimg.

**Comment by immarvin** [comment]
hi @cxhong , would you please take a look at this if convenient? thanks

**Comment by cxhong** [comment]
@khm ,    I ran few tests,  don't think  deploy syncfiles to compute node via netboot image built by packimage.  It used default postscript defined in the node attribute

````
# lsdef cn01 -i postscripts
Object name: cn01
    postscripts=syslog,remoteshell,syncfiles
````
The rootimg will not be updated during packimage process. 
```
if ( defined($syncfile) && -f $syncfile && -d $rootimg_dir) {
```
that if statement will always failed for `-f $syncfile` checking if has multiple syncfile list.

@immarvin , do u know if there are other reasons to xdcp syncfiles during packimage process?

**Comment by khm** [comment]
Packimage works if there is a single syncfile, for instance `synclists=/install/custom/netboot/centos/compute.synclist` but fails if there are multiple, as in `synclists=/install/custom/netboot/centos/compute.synclist,/install/custom/netboot/centos/aux.synclist`

We can fix it simply by just splitting the value and calling xdcp:
```
        foreach my $syncfile (split(',', $sl)) {
            if ( defined($syncfile) && -f $syncfile && -d $rootimg_dir) {
                # call the xdcp plugin to handle the syncfile operation
                print "Syncing files from $syncfile to root image dir: $rootimg_dir\n";
                system("$::XCATROOT/bin/xdcp -i $rootimg_dir -F $syncfile");
            }
        }
```

but this really should be handled by the existing syncfiles() routines.

**Comment by cxhong** [comment]
@khm  yeh, that piece of code is broken if there are multiple synclist files.   I just wonder if it is necessary to `xdcp` sync files in the packimage process.  the sync file will always processed by postscripts `syncfiles` defined in the node attribute which can handle multiple synclist files.

**Comment by khm** [comment]
@cxhong We've got some files we need present during earlier boot stages than the postscripts can provide.  Currently we're having to copy those over during genimage inside .postinstall, but we'd prefer to let packimage handle this properly.

**Comment by cxhong** [comment]
@khm , OK, I will open a pull request for this.

**Comment by immarvin** [comment]
hi @khm , the PR has been merged in PR https://github.com/xcat2/xcat-core/pull/5524

**Comment by khm** [comment]
Thanks for the fix on this issue.
