### ISSUE TITLE
 skip cumulus discovery if the static dhcp lease of switch already exists #5482 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#5528]
refined the code logic for cumulusztp to skip discovery process if there is already a static lease exists for the mac address of switch on MN, i,e, the node has been defined, the mac address of the switch has been defined and makedhcp has been run against the switch. This covers the upgrade scenario.

in other words, if the switch obtained its dhcp lease from the static lease , there will be host-name option in dhcp lease, will skip the discovery process. If the switch obtained its dhcp lease from dynamic range, there will be no host-name option in the lease, invoke the discovery process

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/5482

**Comment by hu-weihua** [comment]
have been verified in xcat 2.14.3 RC1.
