### ISSUE TITLE
Misconfigured goconserver systemctl service file

### ISSUE THREAD

**Issue by thilo-maurer** [xcat2/xcat-core#5547]
xCAT mangement node shows following error message in journalctl:
```
systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
```

This is because `After` is only allowed in section `[Unit]`.
This is the file:
```
# cat /usr/lib/systemd/system/goconserver.service
[Unit]
Description=goconserver console daemon
Documentation=https://github.com/xcat2/goconserver

[Service]
LimitNOFILE=65535
ExecStart=/usr/bin/goconserver
ExecStop=/bin/kill -TERM $MAINPID
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
After=network.target

[Install]
```

This is what the file should contain:
```
# cat /usr/lib/systemd/system/goconserver.service
[Unit]
Description=goconserver console daemon
Documentation=https://github.com/xcat2/goconserver
After=network.target

[Service]
LimitNOFILE=65535
ExecStart=/usr/bin/goconserver
ExecStop=/bin/kill -TERM $MAINPID
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

[Install]
```

**Comment by thilo-maurer** [comment]
Hm, already fixed in git: 
https://github.com/xcat2/goconserver/blob/0c0d0cb9f399d3ff1c2c9dcb45e0fc923cc07d5c/etc/systemd/goconserver.service

Was working with old version 0.2.2-snap201803292224

Unfortunately
https://xcat.org/files/xcat/repos/apt/latest/xcat-dep/pool/main/g/goconserver/
only contains 0.2.2, not latest 0.3.1. 

Which version of xcat will contain updates goconserver?

**Comment by zet809** [comment]
hi, @thilo-maurer , the latest 0.3.1 can be found at https://github.com/xcat2/goconserver/releases/tag/v0.3.1, it have included the fix about the configuration file. Pls take a try and let me know the result.

**Comment by thilo-maurer** [comment]
Would love to see it in the apt/yum repositories at https://xcat.org/files/xcat/repos/

**Comment by zet809** [comment]
hi, @thilo-maurer , it will be put to the repo you mentioned above this Friday that we will release xCAT 2.14.3.
