### ISSUE TITLE
[fvt]2.12:cmdlog_collectlog() in xcatd needs to be enhanced to cover uninitialized value in response 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#555]
How to reproduce
xcatd -f 
Use of uninitialized value in concatenation
Use of uninitialized value in concatenation (.) or string at /opt/xcat/sbin/xcatd line 3092. 
 ----------------------> the message sends out all the time
-----------------------------------------------------
3092:   
}elsif (ref(\($node->{data}->[0])) eq 'SCALAR') {
                        if(defined($node->{data}->[0])){
                        $desc=$desc.": ".$node->{data}->[0];
                        }
--------------------------------------------------------

**Comment by hu-weihua** [comment]
Due to plugin.pm should guarantees the integrity of "response" send back to xcatd, but it's not always true. For example, the response of ``getcons`` likes below: ::

    $VAR1 = {
          'xcatresponse' => [
                              {
                                'node' => [
                                          {
                                            'name' => [
                                                      'c910f03c05k25'
                                                    ],
                                            'baudrate' => [
                                                          '9600'
                                                        ],
                                            'data' => [
                                                      undef
                                                    ],
                                            'psuedotty' => [
                                                           undef
                                                         ],
                                            'sshhost' => [
                                                         'c910f03c05'
                                                       ]
                                          }
                                        ]
                              }
                            ]
        };

The $xcatresponse->{data}->[0] is undef, that cause ``cmdlog_collectlog()`` using a uninitialized value. Xcatd is a very important part, so it should cover such error.

Modify this defect in pull request #557
