### ISSUE TITLE
[Customer]S822LC will hang after "Send cold reset command to MC" in the case of  "node auto-discovery"

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#556]
Environment: 
RHEL7.2 GA
S822LC(FW_VERSION=2.16.85069.65366)

Issue:
In the case "node auto discovery", the node S822LC will hang after run the command "ipmitool mc reset cold" in the file "bmcsetup". rcons can not connect the node S822LC again, unless run "power reset" when the node hangs.

Workaround:
If change the sleep time to 45s in the file "bmcsetup", the issue will not be reproduced.
```
if [ "$XPROD" = "309" -o "$XPROD" = "43707" ] ; then
    echo "Resetting BMC ..."
    ipmitool mc reset cold
    echo "Waiting for the BMC to appear ..."
    sleep 45
    TRIES=0
    while ! ipmitool lan print $LANCHAN > /dev/null; do
        sleep 5
        let TRIES=TRIES+1
        if [ $TRIES -gt $TIMEOUT ]; then break; fi
    done
fi
```

**Comment by whowutwut** [comment]
@fenggaobj  Yes, we also hit this issue.  I created Pull Request #669 that was already merged.  Commit: f0d96b30ca6d052198d6f033a5e6147dde7cb533 The details are in the pull request. The bottom line is that we don't need to do a ``mc reset cold`` at all when we issue the commands to the bmc.  However, after the bmc applies the fix, I think there is something else that is wrong.  We are trying to get confirmation with the firmware team.   So we do wait 30 seconds for the settings to be applied, then we do a ``mc reset cold`` 

The change should be in the 2.11.1 release
