### ISSUE TITLE
ubuntu18.04.1 test cases failures

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#5560]
xcat core : 2.14.4-snap201808240616
arch: ppc64le and x86_64

Failed test cases need to be enhanced for ubuntu OS.

Failed cases: reg_linux_diskless_installation_flat, packimage_m_cpio_c_gzip, packimage_m_cpio_c_pigz, packimage_m_cpio_c_xz, ubuntu_migration1_p8le, ubuntu_migration2_p8le,

Failed cases: reg_linux_diskless_installation_flat, packimage_m_cpio_c_gzip, packimage_m_cpio_c_pigz, packimage_m_cpio_c_xz, ubuntu_migration1_vm, ubuntu_migration2_vm

**Comment by bybai** [comment]
Hi @neo954, diskless and packimage test cases are passed, migration test cases are still failed: ubuntu_migration1_p8le, ubuntu_migration2_p8le, thanks.

**Comment by hu-weihua** [comment]
All have been verified in automation environment. close this issue
