### ISSUE TITLE
restart goconserver after yum update to prevent > Unknown lvalue ‘After’ in section ‘Service’

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5564]
I noticed this problem on both Service nodes and Mgmt node after `yum update` to 2.14.3 which also updated goconserver.
On the other SN, I restarted the service and it seemed to fix it.

[root@sn02 ~]# lsxcatd -a
Version 2.14.3 (git commit 7b7d9ab67589afec1ba58cd5138154290c529c0e, built Tue Aug 21 07:16:00 EDT 2018)
This is a Service Node

[root@sn02 ~]# rcons cn12
Could not connect to cn12, error: EOF
Connection to sn02 closed.
[root@sn02 ~]# rcons cn12 -f
Could not connect to cn12, error: invalid character '\x00' looking for beginning of value
Connection to sn02 closed.
[root@sn02 ~]# systemctl status goconserver -l
\u25cf goconserver.service - goconserver console daemon
   Loaded: loaded (/usr/lib/systemd/system/goconserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-08-23 04:24:13 UTC; 5 days ago
     Docs: https://github.com/xcat2/goconserver
 Main PID: 5010 (goconserver)
   CGroup: /system.slice/goconserver.service
           \u2514\u25005010 /usr/bin/goconserver

Aug 23 04:24:15 sn02.hst.ibm.net goconserver[5010]: goconserver daemon service
Aug 23 04:25:03 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 04:25:03 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 04:25:08 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 04:25:12 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 06:10:31 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 06:10:31 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 06:10:36 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 23 18:21:06 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
Aug 26 02:58:31 sn02.hst.ibm.net systemd[1]: [/usr/lib/systemd/system/goconserver.service:11] Unknown lvalue 'After' in section 'Service'
[root@sn02 ~]# rpm -qa |grep conserv
goconserver-0.3.1-snap201808202115.ppc64le
conserver-xcat-8.2.1-1.ppc64le

Then apply restart to fix it:
[root@sn02 ~]# systemctl restart goconserver 
[root@sn02 ~]# systemctl status goconserver -l
\u25cf goconserver.service - goconserver console daemon
   Loaded: loaded (/usr/lib/systemd/system/goconserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-08-28 16:31:44 UTC; 8s ago
     Docs: https://github.com/xcat2/goconserver
  Process: 27854 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 27857 (goconserver)
   CGroup: /system.slice/goconserver.service
           \u2514\u250027857 /usr/bin/goconserver

Aug 28 16:31:44 sn02.hst.ibm.net systemd[1]: Started goconserver console daemon.
Aug 28 16:31:44 sn02.hst.ibm.net systemd[1]: Starting goconserver console daemon...
[root@sn02 ~]# rcons cn12 
[Enter `^Ec?' for help]
goconserver(2018-08-28T16:32:03Z): Hello 192.168.95.3:39300, welcome to the session of cn12

**Comment by robin2008** [comment]
The system unit file issue has been fixed in new goconserver package, 
but `goconserver` package does not consider upgrade scriptlet to restart the daemon.

And it will be covered in https://github.com/xcat2/goconserver/issues/49

**Comment by zet809** [comment]
hi, @marksmit-ibm , a new goconserver build with fix for this issue is available at  http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/rh7/ppc64le/goconserver-0.3.2-snap201811080416.ppc64le.rpm, will you pls take a try and let us know the result? Thx!

**Comment by marksmit-ibm** [comment]
@zet809   Successful yum update of *xCAT* and goconserver to devel/ version >=11/14/2018 deps.
First Mgmt node, then both SN's.  Afterwards I am able to start rcons <node> without any trouble.
Thank you!

**Comment by robin2008** [comment]
Ok, to close it.
