### ISSUE TITLE
geninitrd generates an initrd.img of new size each time

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5576]
Something is strange with the `initrd.img` file generated by `geninitrd` or `nodeset`.

To recreate:
* Set osimage attribute `osupdatename=` to some string, for example `osupdatename=abc` 
* Set osimage attribute `driverupdatesrc=` to some rpm path, for example `driverupdatesrc=/install/REPO/os/rhels/rhels7.5-alt-ga/ppc64le/Packages/zip-3.0-11.el7.ppc64le.rpm`
* Run `geninitrd` or `nodeset` command for that osimage

Notice:
1. Message `No driver was injected to initrd.` is displayed. But there is no explanation why.
2. The generated `initrd.img` file size is changed each time `geninitrd` or `nodeset` command is run.

I tried running `geninitrd` command 3 times (with no other changes), and after each run, the size of `initrd.img` was different:
```
[root@boston01 ~]# time geninitrd rhels7.5-ga-ppc64le-install-compute
No driver was injected to initrd.

real    2m30.258s
user    0m0.139s
sys     0m0.000s
[root@boston01 ~]# ls -l /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img
-rw-r--r-- 1 root root 38720428 Aug 30 15:28 /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img

[root@boston01 ~]# time geninitrd rhels7.5-ga-ppc64le-install-compute
No driver was injected to initrd.

real    2m31.144s
user    0m0.137s
sys     0m0.002s
[root@boston01 ~]# ls -l /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img
-rw-r--r-- 1 root root 38718410 Aug 30 15:32 /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img

[root@boston01 ~]# time geninitrd rhels7.5-ga-ppc64le-install-compute
No driver was injected to initrd.

real    2m30.606s
user    0m0.138s
sys     0m0.002s
[root@boston01 ~]# ls -l /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img
-rw-r--r-- 1 root root 38723455 Aug 30 15:35 /tftpboot/xcat/osimage/rhels7.5-ga-ppc64le-install-compute/initrd.img
[root@boston01 ~]#
```

**Comment by zet809** [comment]
hi, @gurevichmark , I remember you have fixed this issue, will you pls append the PR number here and close this issue? Thx!

**Comment by zet809** [comment]
It seems the PR https://github.com/xcat2/xcat-core/pull/5727 fixed this problem, @gurevichmark , pls help to check. Thx!

**Comment by gurevichmark** [comment]
Yes, the problem appears to be fixed.
Verified on 
```
[root@stratton01 ~]# lsxcatd -a
Version 2.14.5 (git commit 7c1eb1901e18ef98c66a7400ddf571ac8414c1bc, built Tue Nov  6 06:16:39 EST 2018)
This is a Management Node
dbengine=SQLite
[root@stratton01 ~]#
```
