### ISSUE TITLE
Documentation: cuda_power9_setup postinstall script as part of genimage postscript. netboot osimage

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5577]
https://xcat-docs.readthedocs.io/en/stable/advanced/gpu/nvidia/osimage/rhels.html#diskless-osimage

in the example, I see this line for creating a diskless image:
```
chroot \$installroot /tmp/cuda_power9_setup
```
Since this is running during genimage, it is already in chroot.  Therefore I found it failed because it was trying to do a double chroot.  I found by modifying it to  not run in chroot, then the 
postscript `cuda_power9_setup`  can run as it is and succeed.
```
> chroot \$installroot /tmp/cuda_power9_setup
becomes
< \$installroot/tmp/cuda_power9_setup
```

**Comment by zet809** [comment]
Thx, @marksmit-ibm , we will update our document for this problem.

**Comment by marksmit-ibm** [comment]
Thank you for considering the doc change.
I would also like to understand the sequencing of postinstall scripts when run with genimage of type  provmethod=netboot.
I observe that during genimage <osimage>:
1. installs pkglist
2. installs otherpkglist
a. nvidia-kmod installs and $rootimgdir/boot/initramfs<version>.img is modified
3. runs -i postinstall  scripts
a. $rootimgdir/usr/lib/modprobe.d/nvidia.conf is created.  I notice the $rootimgdir/boot/initramfs file is NOT modified.
4. creates  stateless and statelite initrd in $rootimgdir/

Later packimage <osimage>  creates $rootimgdir/rootimg.cpio.gz
When I netboot the ComputeNode, rootimg.cpio.gz is loaded and I see the requirements of the nvidia.conf properly loaded in `cat /proc/drivers/nvidia/params`

Question 1: When a netboot image is running, is the $rootimgdir/boot/initramfs  in use?  I am curious why step 3a shows it was not again "dracut" after creating the /lib/modprobe.d/nvidia.conf, but somehow the nvidia.conf parameters are in use.  I suspect that the initrd made in step 4 is used not only at petitboot, but later on as well.  However I'm not sure.

Question 2: I am curious what lead to the decision to put nvidia.conf in /lib/modrobe.d/  versus /etc/modprobe.d/ .   It seems to be important in getting the nvidia.conf  to succeed for netboot, and may be the answer to question 1.   I know when I run the same genimage with nvidia.conf in /etc/modprobe.d/  it fails to load for diskless (but works for diskfull).

**Comment by whowutwut** [comment]
@neo954 @robin2008 Should  we answer the questions above before  closing this issue?

**Comment by robin2008** [comment]
@marksmit-ibm 
The `genimage` working flow :
- installs pkglist
- installs otherpkglist
- runs postscript scripts
- get the installed linux kernel
- injects drivers if specified
- runs postinstall scripts
- creates initrd via "dracut" in $rootimgdir/

So xcat only uses the initrd generated in the last step for netbooting,  instead of $rootimgdir/boot/initramfs

And just as said in https://github.com/xcat2/xcat-core/pull/5137#discussion_r183843572
`/etc/modprobe.d/nvidia.conf` cannot work as no `/run`, `/dev`, and `/proc` available,  so only `/usr/lib/modprobe.d` after `chroot` into `$rootimgdir`
