### ISSUE TITLE
rpm build failed on build xCAT-probe

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#5590]
August 31st: *linux_rpm* build of branch `devel` ==> *FAILED*
    BUILD_MACHINE=`c910f04x33@xcat.build.server`
    BUILD_DIR=`/xcat/build/xcat2_autobuild_daily_builds/20180831.0615/linux_rpm

```
Error:  build of the following RPMs failed:  xCAT-probe
2018-08-31 10:17:51,909 buildxcat WARNING:Wide character in print at /usr/share/perl5/Pod/Html.pm line 435.
error: bad date in %changelog: Thu, 30 Aug 2018 - GONG Jie <gongjie@linux.vnet.ibm.com>
```

**Comment by hu-weihua** [comment]
@xuweibj , could you help to verify this fix? thanks

**Comment by xuweibj** [comment]
September 3rd: *linux_rpm* build of branch `devel` ==> *SUCCESS*
    BUILD_MACHINE=`c910f04x33@xcat.build.server`
    BUILD_DIR=`/xcat/build/xcat2_autobuild_daily_builds/20180903.0615/linux_rpm`

Daily build is success, close this issue.
