### ISSUE TITLE
[fvt]2.12:rhels7.2 hierarchy diskfull install failed 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#562]
How to reproduce:
1.down load the latest build
2. nodeset cn osimage
    rpower boot
    lsdef cn 
-----------------> status is booted but could not ssh 
3. rcons cn -f 
4. ifconfig -a 
    ------------------> no ip here
5.cat /var/log/xcat/xcat.log
    -------------------> no ip for cn ,but log shows the cn status is ok
6. cat / opt/xcat/xcatinfo
    -------------------->
   XCATSERVER=10.4.27.3
   USEFLOWCONTROL=NO
7.yum could not find on cn

**Comment by tingtli** [comment]
@jun xia 
Please update which xCAT version and which os/hardware you used for test

**Comment by junxiawang** [comment]
this bug cannot reproduce so I have close it now .
