### ISSUE TITLE
[OpenBMC] Options may not all work between Perl and Python framework

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5627]
All the options for the OpenBMC command should be run against both Perl and Python in an automated testing framework for UT.    I  think the dev should be responsible for creating simple tests for this.. (FYI @hu-weihua ) 

Here's an example of what we found today when I asked someone to check if they are running the "Python Framework" using the command: 
```
[root@briggs01 ~]# rinv mid05tor12cn03 -V serial
[briggs01]: Running command in Python
[briggs01]: mid05tor12cn03: SYSTEM SerialNumber : 1318D3A
```

It failed....  and I re-created it by removing the `xCAT-openbmc` rpm.. .
```
[root@briggs01 ~]# rpm -qa | grep xCAT-openbmc
xCAT-openbmc-py-2.14.4-snap201809061723.noarch
[root@briggs01 ~]# rpm -e xCAT-openbmc-py-2.14.4-snap201809061723.noarch
[root@briggs01 ~]# rinv -V mid05tor12cn03 serial
mid05tor12cn03: Error: Error parsing arguments.
[root@briggs01 ~]#
```

**Comment by gurevichmark** [comment]
It seems in Perl processing of the options (in `openbmc.pm`) we insist that `-V` be the last parameter:
```
# If command includes '-V', it must be the last one prarmeter. Or print error message.
    if ($verbose) {
        my $option = $$extrargs[-1];
        return ([ 1, "Error parsing arguments." ]) if ($option !~ /V|verbose/);
    }
```

**Comment by whowutwut** [comment]
If that is the case as seems like it is on the man page, we probably need the same behavior on Python...  this just goes to show some UT cases that will ensure that we are consistently implementing the function between Python and Perl.

**Comment by robin2008** [comment]
@xuweibj    This is introduce in #3496 why this needs to be the last one?  It should be a bug.  I didn't see any limitation for other commands with `-V`

**Comment by xuweibj** [comment]
Actually it's our design to just allow ``-V`` to be the last one parameter in perl. In perl we just deal with options based it's order in array, if not set the limitation, we need to find it out from the whole options array and delete it from array to deal with other options. We need to check ``-V`` for command ``rinv``, ``rflash``, so could not deal with it as other commands.

If want to make it the same with python, we need to add much code to deal with it in ``parse_command_status`` and ``parse_args`` functions.

**Comment by robin2008** [comment]
It is hard for me to understand this limitation,  

>  In perl we just deal with options based it's order in array, if not set the limitation, we need to find it out from the whole options array and delete it from array to deal with other options.

And all commands need to check `-V|--verbose` and set the flag, not only for `rinv` and `rflash`. But you can do nothing with `-V` as that plugin has nothing special print with it.

**Comment by robin2008** [comment]
@xuweibj I think we need to update the UT cases for paring `-V`

@hu-weihua  Please finalize the rules for UT cases after we discussion and broadcast to the whole team, we need the `xcattest` to easily query and run UT cases, and every DEV could build/modify their UT or FVT cases after all possible changes.

**Comment by hu-weihua** [comment]
I have verified the fix against ``rinv`` by the latest xcat.

```
[root@f6u13k10 bundle]# lsdef -v
lsdef - Version 2.14.4 (git commit df2fa08ab4fdef2c34e50ce899d25e4947812a01, built Thu Oct 18 05:52:40 UTC 2018)

[root@f6u13k10 bundle]# rinv f5u14 -V serial
[f6u13k11]: Running command in Perl
[f6u13k11]: f5u14: SYSTEM SerialNumber : 1015DEA

[root@f6u13k10 ~]# rinv f5u14 -V serial
[f6u13k10]: Running command in Python
[f6u13k11]: f5u14: SYSTEM SerialNumber : 1015DEA
```

**Comment by whowutwut** [comment]
Thank y ou  @hu-weihua
