### ISSUE TITLE
Mistake for creating install disk logs

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#564]
ENV:
    OS and platform: Lpar PPC64, RH 7.2
xCAT-core and dep:
    20151231.1930-core-rpms-snap.tar.bz2
    xcat-dep-201511181550.tar.bz2
How to reproduce:
    Install the CN then using debugmode to track logs.

Currente: Failed to write some logs for the misktake: tmp/tmp/getinstalldisk_log, which should be /tmp/getinstalldisk_log

Excepted: All logs should be wrote into  /tmp/getinstalldisk_log

**Comment by xuweibj** [comment]
Pull Request #565

**Comment by tingtli** [comment]
@caomengmeng 
when you open a defect, please write down which xcat version you use, which platform you test. How could developer reproduce your defect etc.

**Comment by whowutwut** [comment]
@xuweibj If your pull request fixing this issue is merge, please set to pending state to @caomengmeng  knows that it's ready for verification

**Comment by caomengmeng** [comment]
passed
