### ISSUE TITLE
makedhcp misleading error message

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/xcat-core#5649]
If you do net set `xcatmaster` for your <node> and the node is in a remote network which isn't directly attached to the xCAT server the following error is shown:

```
[root@xcat ~]# makedhcp <node>
Error: [xcat]: Unable to determine the tftpserver for <node>
```
This is misleading because `tftpserver` was set for all networks.
The real issue was the missing `xcatmaster` attribute.

The following code throws this error:
https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/dhcp.pm#L530-L558

This code looks for `xcatmaster`, not `tftpserver`. Therefore, in my opinion the message should include `xcatmaster` instead of `tftpserver`.

**Comment by zet809** [comment]
I have modify the warning message as `Unable to determine the tftpserver for <mynode>, please makesure "xcatmaster" is set correctly` in PR https://github.com/xcat2/xcat-core/pull/5651

**Comment by Obihoernchen** [comment]
cool thanks (Y)

**Comment by Obihoernchen** [comment]
#5651 merged
