### ISSUE TITLE
[Performance]  `lsdef -w` has very bad performance

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5652]
On a 5000+ nodes cluster,  it takes long time to finish a query, this is too bad.
```
[Date]       2018-09-21 02:56:02
[ClientType] cli
[Request]    lsdef -w 'serial=12345678'
[Response]
c99n07  (node)
[ElapsedTime] 292.377 s
```

**Comment by cxhong** [comment]
I created 5000 nodes,  I ran same command, took less time
```
[Date]       2018-09-23 16:49:17
[ClientType] cli
[Request]    lsdef -w 'switch=sw1'
[Response]
cn100  (node)
[ElapsedTime] 25.635 s
````

**Comment by robin2008** [comment]
Yes, cannot recreate it anymore. I guess it might be caused by that time the MN is running in a heavy workload.

To close it first.
