### ISSUE TITLE
Updatenode -f didn't work if servicenode attribute is ip address for compute node definition

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#5661]
I defined servicenode attributes as ip address instead of hostname
````
# lsdef mid08tor03cn01 -i servicenode
Object name: mid08tor03cn01
    servicenode=172.20.254.2
````
the `updatenode` command failed: 
````
# updatenode p9 -f
172.20.254.2 is not responding. No command will be issued to this host.
File synchronization failed for service nodes: "172.20.254.2"
````
looking the code,  `updatenode -f` calls `pping` and `pping` seems only accept the hostname not ip address
````
# pping 172.20.254.2
sn02: ping
172.20.254.2: noping
````

**Comment by gurevichmark** [comment]
Yes, I saw something like this before with `lstree` command. I think we only support SN defined with names, not IP addresses: https://github.com/xcat2/xcat-core/issues/3230#issuecomment-306967476

**Comment by cxhong** [comment]
from pping man page,  it only take noderange, not ip address. so that's working as design.

**Comment by cxhong** [comment]
The definition of `servicenode`  
````
servicenode:	A comma separated list of node names (as known by the management node) that provides most services for this node. 
````
but xCAT will not block if user set servicenode as ip address

**Comment by robin2008** [comment]
@cxhong   Any special consideration for setting an IP address?  if not,  better to follow the document to set the name instead.

**Comment by cxhong** [comment]
I don't have special consideration,  just in case if user use ip address instead of hostname to define servicenode, that will cause issue and error message didn't mention ip address is invalid
