### ISSUE TITLE
prescripts not inherited when set site.hierarchicalattrs

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5663]
Hi!

It looks like listing `prescripts` in `site.hierarchicalattrs` doesn't work as expected: prescripts are not inherited.

For instance, we add `prescripts` to `site.hierarchicalattrs`
```
# tabdump -w key==hierarchicalattrs site
#key,value,comments,disable
"hierarchicalattrs","prescripts,postscripts,postbootscripts,nics",,
```

`sh-101-60` is a node that is a member of 2 groups: `srv` and `compute`
```
# lsdef -c  sh-101-60 -i groups
sh-101-60: groups=base,cpu,compute,srv
```

The prescripts for those 2 groups are as follows:
```
# tabdump  prescripts
#node,begin,end,comments,disable
"compute","script_compute.sh",,,
"srv","script_srv.sh",,,
```

Yes, `sh-101-60`'s prescripts  are only taken from the `compute` group:
```
# lsdef -c sh-101-60 -i prescripts-begin
sh-101-60: prescripts-begin=script_compute.sh
```

Are prescripts not supported as a hierarchical attribute?

**Comment by cxhong** [comment]
I think something to do with node attribute name `prescripts-begin` / `prescripts-end`, and table name is `prescripts`.  will look into this

**Comment by cxhong** [comment]
@robin2008 , can u take look this?

**Comment by kcgthb** [comment]
@robin2008 Aaah, good finding! 
I can confirm that using `begin` in `hierachicalattrs` works.

Thanks!

**Comment by kcgthb** [comment]
I just realized that, although the trick above "works" in that it lets nodes inherit prescripts from relevant groups, it doesn't quite work with the "action:script" syntax.

For instance:
```
# lsdef -t group a,b -i prescripts-begin
Object name: a
    prescripts-begin=osimage:a.sh
Object name: b
    prescripts-begin=all.sh|osimage:b.sh
```
```
# lsdef cn -i groups,prescripts-begin
Object name: cn
    groups=a,b
    prescripts-begin=osimage:a.sh,all.sh|osimage:b.sh
```
The `prescript-begin` for node `cn` should instead be `all.sh|osimage:a.sh,b.sh`, shouldn't it?

**Comment by cxhong** [comment]
the logic in the code is only `append` the value from inherit attribute.

**Comment by cxhong** [comment]
this didn't good.  I think we should fix that
````
# lsdef -t group p9 -i prescripts-begin
Object name: p9
    prescripts-begin=all.sh|osimage:osimage.sh
# lsdef -t group dd20 -i prescripts-begin
Object name: dd20
    prescripts-begin=all.sh|osimage:osimage1.sh|boot:boot.sh
# lsdef mid08tor03cn01 -i prescripts-begin
Object name: mid08tor03cn01
    prescripts-begin=all.sh|osimage:osimage.sh,all.sh|osimage:osimage1.sh|boot:boot.sh
````

**Comment by robin2008** [comment]
Yes, there must be some problems as it cannot distinguish the commas which is used in `[action1:]s1,s2...[|action2:s3,s4,s5...]` or the one used for inheritance. 

This might be a design gap when we do `hierarchicalattrs`,  and xcat has many columns which using  special char as separator, those attributes may not  be supported by `hierarchicalattrs` too.

**Comment by robin2008** [comment]
xCAT need some enhancement on `hierarchicalattrs` feature to support defining its delimiter for that attribute.
The default delimiter is comma,  but you can use `"hierarchicalattrs","begin:|,postscripts,postbootscripts,nics",` to define `|` is the delimiter for `begin` attribute.

with it, `hierarchicalattrs` could support all kinds of column which has its own delimiter different than comma.

**Comment by robin2008** [comment]
This is covered in #5688  @kcgthb

**Comment by robin2008** [comment]
@kcgthb feel free to reopen it if you still has problem.
