### ISSUE TITLE
xcatprobe xcatmn tests NTP with ntpq instead of chrony

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5678]
Even when `chrony` is used by `setupntp`, the `xcatprobe xcatmn` tests still check NTP status by running `ntpq -p`, which fails.

The test should probably be updated to use `chrony` when it's used in place of `ntpd`.

**Comment by hu-weihua** [comment]
@kcgthb, could you help to verify this fix? If it is ok for you, could you close this issue? thanks

**Comment by kcgthb** [comment]
@hu-weihua Looks like I can't apply patches from #5686 directly on my 2.14.3 installation, but I'll test them as soon as 2.14.4 is released.
Thanks!

**Comment by hu-weihua** [comment]
Due to we are clearing the bugs this week and we have verified this fix in our environment. xCAT 2.14.4 will released on Oct 19 depending on plan, so I will close this issue first,  you can reopen this issue if you find the fix does not work in your environment. Thanks.
