### ISSUE TITLE
otherpkgs without yum upgrade

### ISSUE THREAD

**Issue by paddyoneill** [xcat2/xcat-core#5679]
Hi, I have some nodes managed by xcat and want to install some additional RPMs at install. Both the head node and compute nodes run CentOS 7.5 but the RPMs I am trying to install require specific kernel versions, and the latest isn't currently supported. I have setup the osimage to include the required RPMs using the otherpkgs postbootscript but have noticed that it runs yum upgrade, which installs an unsupported kernel version. Is there a way to use otherpkgs without it running yum upgrade, apart from removing that part of the script?

**Comment by paddyoneill** [comment]
Also xcat version being used is 

[root@headnode ~]# lsxcatd -a
Version 2.14.2 (git commit f2090565b1d1b8efa7558d034de0478456c38e4c, built Wed Jul 11 07:15:53 EDT 2018)
This is a Management Node
dbengine=SQLite

**Comment by cxhong** [comment]
have u try from this doc?

https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/use_kernel_patch.html

**Comment by paddyoneill** [comment]
I have tried to make a new directory under /install, and have appended it to pkgdir. If I add packages from this directory to the pkglist, installation fails when selecting software in anaconda. From my understanding this should enable that directory as an additional repo that is used during the install but it doesn't seem to be working. 

I can manually add the repo after node installation and use yum to install the RPMs, so it isn't a problem with repodata. From my understanding of this document it should work.

https://sourceforge.net/p/xcat/wiki/Multiple_pkgdir_support_with_full_installation/

**Comment by paddyoneill** [comment]
I have been able to work around this by adding a yum install command in a postscript to install the package from the repo at the end of the kickstart installation. It was failing before because /sbin/depmod is not available in the anaconda environment.

**Comment by bybai** [comment]
If you try doc: https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/use_kernel_patch.html

Make sure the new RPM kernel package directory name format must be `/install/kernels/<kernelver>` . The `<kernelver>` value is from kernel-<kernelver>.rpm

**Comment by paddyoneill** [comment]
@bybai That worked, thanks. Closing this.
