### ISSUE TITLE
[DEV]Update xCAT 2.10 to xCAT 2.11 will overwrite the site."xcatsslversion" attribute.

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#569]
It's a bug in the xcatconfig that it always overwrite the "xcatsslversion" attribute when do the package update.

**Comment by whowutwut** [comment]
To add some more information about the original problem that was encountered.  The cluster is updated to xCAT 2.11 by changing the yum repo config files and running ``yum update '*xCAT*'`` .  The following problem is seen: 
```
# lsxcatd -a
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: SSL connect attempt failed with unknown error at /opt/xcat/lib/perl/xCAT/Client.pm line 265.
```

xCAT was running fine before with xCAT 2.10 and stops working updating to xCAT 2.11

Upon investigation, the ``xcatsslciphers`` and ``xcatsslversion`` was set at this site according to the Poodle attack security advisory (https://github.com/xcat2/xcat-core/wiki/2014_11_04_Poodle_Attack) 

```
# tabdump site | grep ssl
"xcatsslciphers","kDH:kEDH:kRSA:!SSLv3:!SSLv2:!aNULL:!eNULL:!MEDIUM:!LOW:!MD5:!EXPORT:!CAMELLIA:!ECDH",,
"xcatsslversion","TLSv1",,
```

However the ciphers only is supported with versions higher than TLSv1, so we modified to TLSv12 and things started working again.  @daniceexi  investigated and realized that we are overwriting the value of ``xcatsslversion`` and opened this Issue.

**Comment by daniceexi** [comment]
Code has been checked in:

* 2.12: ec4ce73d5be41c86da62d0b1ff936526fb7d65fd
* 2.11: 3eb292a80f91ef449988b6a2b1558f6b7a019832
* 2.9: 4dd1cd6a128d731ad9958e5e366c87f8a181be53

**Comment by caomengmeng** [comment]
Hi @daniceexi 
I am using the latest build.
1. change xcatsslversion value to be TLSv12
2. run: xcatconfig -f
3. check the xcatsslversion value, it is still the default value TLSv1

```
[root@c910f02c04p07 ~]# rpm -qa | grep -i xCAT
conserver-xcat-8.1.16-10.ppc64
perl-xCAT-2.12-snap201601271530.noarch
xCAT-buildkit-2.12-snap201601271531.noarch
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
xCAT-genesis-base-ppc64-2.11-snap201511160819.noarch
syslinux-xcat-3.86-2.noarch
xCAT-client-2.12-snap201601271531.noarch
xCAT-genesis-scripts-ppc64-2.12-snap201601271531.noarch
xCAT-2.12-snap201601271531.ppc64
ipmitool-xcat-1.8.11-3.ppc64
xCAT-server-2.12-snap201601271531.noarch
xCAT-test-2.12-snap201601271531.noarch
```

**Comment by daniceexi** [comment]
@caomengmeng You should not use **-f** option, instead the '-u' should be used to simulate the update of xcat.

~~~~
 -f|--force
             The force option may  be used after the install to reinitialize the Management Node. This option will  regenerate keys, credential and reinititialize the site table. 
~~~~

**Comment by whowutwut** [comment]
@caomengmeng I think we want to verify the case where we set the ssl attributes and make sure on an xCAT Version upgrade (2.10->2.11, 2.11->2.11,etc) it does not change it on the user
