### ISSUE TITLE
[FVT]：adjust cases list to avoid some cases false failure

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#5724]
In today's regression result, I found that some of the test cases failed because of prior cases failure. e.g. xdsh depends on ssh working between mn/cn， if cn is not in a proper state, the cases will fail. in the bundle list, some packimage test cases will boot cn and reinstall cn. If these cases fail, the cases which depends on cn's state after that will fail. Record this issue to adjust our bundle file.

**Comment by hu-weihua** [comment]
@tingtli Could you open such issues against automation test in xcat-management repo next time? thanks

**Comment by tingtli** [comment]
PR  https://github.com/xcat2/xcat-core/pull/5776
