### ISSUE TITLE
genimage failed for ubuntu 16.04.5 ppc64el and x86

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#5733]
``genimage`` failed for ubuntu 16.04.5 ppc64el and x86

xcat version: snap201810240616

Below file is the detailed log:
[ubuntu16_04_5_geniamge.log](https://github.com/xcat2/xcat-core/files/2517405/ubuntu16_04_5_geniamge.log)

**Comment by hu-weihua** [comment]
link to https://github.com/xcat2/xcat2-task-management/issues/312

**Comment by bybai** [comment]
verified by auto test
