### ISSUE TITLE
[FVT]2.9.2:aix 720 install xcatd could not load some modules after xcat install

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#574]
Error info:

0513-059 The xcatd Subsystem has been started. Subsystem PID is 10813810.
Error loading module /opt/xcat/lib/perl/xCAT_plugin/configfpc.pm  ...skipping
Error loading module /opt/xcat/lib/perl/xCAT_plugin/lsslp.pm  ...skipping
Error loading module /opt/xcat/lib/perl/xCAT_plugin/remoteimmsetup.pm  ...skipping
Error loading module /opt/xcat/lib/perl/xCAT_plugin/slpdiscover.pm  ...skipping
Error loading module /opt/xcat/lib/perl/xCAT_plugin/switch.pm  ...skipping
xCATd: service starting
xCAT: Allowing tabdump site for root from loopback
xCAT is now running.

**Comment by hu-weihua** [comment]
After debug, I found all above plugins which were skipped during xcatd start have the same problem. this AIX environment miss SNMP.pm. It seems we lost SNMP part during dependency  package compiling.  ::

    bash-3.2# /usr/bin/env perl -I /opt/xcat/lib/perl/ -c slpdiscover.pm
    Can't locate SNMP.pm in @INC (you may need to install the SNMP module) (@INC contains: /opt/xcat/lib/perl /usr/opt/perl5/lib/5.8.2/aix-thread-multi /usr/opt/perl5/lib/5.8.2 /usr/opt/perl5/lib/site_perl/5.8.2/aix-thread-multi /usr/opt/perl5/lib/site_perl/5.8.2 /opt/xcat/lib/perl/ /usr/opt/perl5/lib/site_perl/5.8.2/aix-thread-multi  /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi /usr/opt/perl5/lib/site_perl/5.20.1 /usr/opt/perl5/lib/5.20.1/aix-thread-multi /usr/opt/perl5/lib/5.20.1 /usr/opt/perl5/lib/site_perl .) at /opt/xcat/lib/perl/xCAT/MacMap.pm line 24.
    BEGIN failed--compilation aborted at /opt/xcat/lib/perl/xCAT/MacMap.pm line 24.
    Compilation failed in require at slpdiscover.pm line 8.
    BEGIN failed--compilation aborted at slpdiscover.pm line 8.

**Comment by daniceexi** [comment]
OK, we can wait @neo954 to finish the build for SNMP.pm to verify this issue.

**Comment by neo954** [comment]
@daniceexi @junxiawang The new package is built

    # rpm -qpil net-snmp-perl-5.7.3-1.aix7.2.ppc.rpm
    Name        : net-snmp-perl                Relocations: (not relocateable)
    Version     : 5.7.3                             Vendor: Net-SNMP project
    Release     : 1                             Build Date: Tue Jan  5 23:48:47 CST 2016
    Install date: (not installed)               Build Host: c910f03c01p17
    Group       : Development/Libraries         Source RPM: net-snmp-5.7.3-1.src.rpm
    Size        : 813814                           License: BSDish
    Packager    : The Net-SNMP Coders <http://sourceforge.net/projects/net-snmp/>
    URL         : http://www.net-snmp.org/
    Summary     : The perl NET-SNMP module and the mib2c tool
    Description :
    The net-snmp-perl package contains the perl files to use SNMP from within
    Perl.

    Install the net-snmp-perl package, if you want to use mib2c or SNMP with perl.
    /opt/freeware/bin/mib2c
    /opt/freeware/bin/tkmib
    /opt/freeware/man/man1/mib2c.1
    /opt/freeware/man/man1/tkmib.1
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/Bundle
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/ASN.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/OID.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/TrapReceiver.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/agent
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/agent.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/agent/Support.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/agent/default_store.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/agent/netsnmp_request_infoPtr.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/NetSNMP/default_store.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/SNMP.pm
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/Bundle
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/Bundle/NetSNMP
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/ASN
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/ASN/ASN.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/ASN/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/OID
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/OID/OID.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/OID/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/TrapReceiver
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/TrapReceiver/TrapReceiver.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/TrapReceiver/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent/agent.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent/default_store
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent/default_store/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/agent/default_store/default_store.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/default_store
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/default_store/autosplit.ix
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/NetSNMP/default_store/default_store.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/SNMP
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/SNMP/SNMP.so
    /usr/opt/perl5/lib/site_perl/5.20.1/aix-thread-multi/auto/SNMP/autosplit.ix
    /usr/opt/perl5/man/man3/NetSNMP::ASN.3
    /usr/opt/perl5/man/man3/NetSNMP::OID.3
    /usr/opt/perl5/man/man3/NetSNMP::TrapReceiver.3
    /usr/opt/perl5/man/man3/NetSNMP::agent.3
    /usr/opt/perl5/man/man3/NetSNMP::agent::default_store.3
    /usr/opt/perl5/man/man3/NetSNMP::default_store.3
    /usr/opt/perl5/man/man3/NetSNMP::netsnmp_request_infoPtr.3
    /usr/opt/perl5/man/man3/SNMP.3

**Comment by daniceexi** [comment]
@junxiawang Please use the new SNMP build and verify this issue.

**Comment by hu-weihua** [comment]
After talking with @junxiawang, it seems we didn't hit this issue again after installing the new SNMP build.

**Comment by daniceexi** [comment]
@junxiawang Please close this issue.
