### ISSUE TITLE
Installing `xCAT-genesis-base` will remove files provided by `xCAT-genesis-scripts` 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5740]
In our environment we have built a custom xCAT-genesis-base in order to handle support for Power9 hardware in RHEL.  The Fedora image does not always run well with the Power9 processor.  Until the kernel changes are pushed to the linux distro, we will have a work around. 

Known issue: https://xcat-docs.readthedocs.io/en/stable/references/coral/known_issues/index.html

However, when we take an existing xCAT installation and install a pre-built `xCAT-genesis-base` on top, the result is files like `doxcat` is removed from the MN node and running `mknb ppc64` causes a incomplete genesis kernel to be built.

After install of `xCAT-genesis-base` 
```
[root@stratton01 ppc64]# rpm -qll xCAT-genesis-scripts-ppc64-2.14.5-snap201810260616.noarch | grep doxcat
/opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/doxcat
[root@stratton01 ppc64]# ls -ltr /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/doxcat
ls: cannot access /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/doxcat: No such file or directory
[root@stratton01 ppc64]#
```

And when deploying genesis, you would see something like: 
```
[2018-10-26T13:41:45-04:00] There is no screen to be detached matching doxcat.
[2018-10-26T13:41:45-04:00] Cannot exec 'doxcat': No such file or directory
[2018-10-26T13:41:50-04:00] [screen is terminating]^M
```

### Recovery

To recover from this in the meantime while we work on a fix, you can run: 
1. `yum  reinstall xCAT-genesis-scripts-<arch>`
2. `mknb <arch>` where arch is x86_64 or ppc64

**Comment by neo954** [comment]
I will look into this one.

**Comment by neo954** [comment]
The following files were missing after reinstall `xCAT-genesis-base-ppc64`.
```
# rpm -V xCAT-genesis-scripts-ppc64-2.14.5-snap201810260616.noarch
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/allowcred.awk
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/bmcsetup
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/configraid
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/diskdiscover
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/dodiscovery
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/dosysclone
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/doxcat
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/getadapter
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/getcert
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/getdestiny
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/getipmi
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/ifup
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/minixcatd.awk
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/nextdestiny
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/pseries_platform
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/raidcmd
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/raidutils
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/remoteimmsetup
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/restart
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/udpcat.awk
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/update_flash
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/update_flash_nv
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/bin/updateflag.awk
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/sbin/loadmlxeth
missing     /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/usr/sbin/setupimmnic
```

**Comment by neo954** [comment]
I believe this is a side effect cause by pull request #4374.

**Comment by neo954** [comment]
Uninstall and reinstall `xCAT-genesis-base-ppc64` will not cause any problem. Only a upgrade of `xCAT-genesis-base-ppc64` will cause the problem.

**Comment by neo954** [comment]
Do the upgrading with `--noscripts` will avoid the problem.

`rpm -Uvvvh --noscripts --force http://xcat.org/files/xcat/repos/yum/devel/xcat-dep/xCAT-genesis-base-ppc64-2.14-snap201804041553.noarch.rpm`

**Comment by whowutwut** [comment]
@neo954 If it's an upgrade that causes the problem, are we not checking for upgrade path in the RPM and doing the correct things? 

> If the first argument to %preun and %postun is 1, the action is an upgrade

From:  https://www.ibm.com/developerworks/library/l-rpm2/index.html

**Comment by zet809** [comment]
We checked, but the checked is incorrect when the directory is a symbol link.
The fix is, in `pretrans` script, if it check the /bin is a directory, will remove all files, if not, just remove the file /bin.
