### ISSUE TITLE
Make the default setting of site.xcatsslversion contemporary

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#5794]
Currently, xCAT is shipped with `site.xcatsslversion` set to `TLSv1` as the default setting. Which is behind the times.

In xCAT document, [OpenSSL Configuration](https://xcat-docs.readthedocs.io/en/stable/advanced/security/ssl_config.html), the end user was asked to change the default setting to `TLSv12` or `TLSv1_2`.

> By default, xCAT ships with ``TLSv1`` configured.  The current highest SSL version that can be supported is ``TLSv1.2``.
>
> * For rhels7.x and sles12.x and higher: ::
>
>       chtab key=xcatsslversion site.value=TLSv12
>
> * For ubuntu 14.x and higher: ::
>
>       chtab key=xcatsslversion site.value=TLSv1_2
>
> * For AIX 7.1.3.x: ::
>
>       chtab key=xcatsslversion site.value=TLSv1_2

I would like xCAT to revise this part
 1. Provide a contemporary default setting for `site.xcatsslversion`.
    * Use TLSv1.2 when it can be used. The upcoming TLSv1.3 is still in the draft stage
    * TLSv1 and TLSv1.1 should be deprecated
 1.  Provide a constant configuration among RHEL, SLES and Ubuntu

**Comment by neo954** [comment]
In the description of CPAN document, https://metacpan.org/pod/IO::Socket::SSL, there is no difference between the keyword `TLSv1_2`, and `TLSv12`. Thus I believe the xCAT document may wrongly described.

> **SSL_version**
>
> Sets the version of the SSL protocol used to transmit data. 'SSLv23' uses a handshake compatible with SSL2.0, SSL3.0 and TLS1.x, while 'SSLv2', 'SSLv3', 'TLSv1', 'TLSv1_1' or 'TLSv1_2' restrict handshake and protocol to the specified version. All values are case-insensitive. Instead of 'TLSv1_1' and 'TLSv1_2' one can also use 'TLSv11' and 'TLSv12'. Support for 'TLSv1_1' and 'TLSv1_2' requires recent versions of Net::SSLeay and openssl.
>
> Independent from the handshake format you can limit to set of accepted SSL versions by adding !version separated by ':'.
>
> The default SSL_version is 'SSLv23:!SSLv3:!SSLv2' which means, that the handshake format is compatible to SSL2.0 and higher, but that the successful handshake is limited to TLS1.0 and higher, that is no SSL2.0 or SSL3.0 because both of these versions have serious security issues and should not be used anymore. You can also use !TLSv1_1 and !TLSv1_2 to disable TLS versions 1.1 and 1.2 while still allowing TLS version 1.0.
>
> Setting the version instead to 'TLSv1' might break interaction with older clients, which need and SSL2.0 compatible handshake. On the other side some clients just close the connection when they receive a TLS version 1.1 request. In this case setting the version to 'SSLv23:!SSLv2:!SSLv3:!TLSv1_1:!TLSv1_2' might help.

**Comment by robin2008** [comment]
Yes, It’s Time to Disable TLS 1.0 and SSLx for security consideration.  So here is xcat proposal.
- For fresh installed xCAT,  tls1.2 is used by default
- For update xCAT case,  still use the original settings (should we give an warning for version prior to tls 1.2?)

**Comment by neo954** [comment]
I will close this one.
