### ISSUE TITLE
postscripts not run in compute node

### ISSUE THREAD

**Issue by sinoag123** [xcat2/xcat-core#5847]
xcat version is Version 2.14.4 ，install rhel7.2 compute node is ok，but found compute node nic is dhcp ，I want to change nic static 
[root@rhel72 ~]# tabdump postscripts
#node,postscripts,postbootscripts,comments,disable
"xcatdefaults","syslog,remoteshell,syncfiles","otherpkgs",,
"service","servicenode",,,
"compute","hardeths,configRSH,configService,configNFS,syslog,remoteshell,syncfiles,setupntp,reboot",,,
[root@rhel72-client ~]# more /etc/sysconfig/network-scripts/ifcfg-ens192
# Generated by parse-kickstart
DEVICE=ens192
IPV6INIT=yes
BOOTPROTO=dhcp
How to do ？
Thanks

**Comment by cxhong** [comment]
only has one nic for compute node?  can u show output of ` ifconfig -a` on the compute node?
also, can u show `lsdef rhel72-clinet` and 'grep rhel72-client /etc/hosts`  ?
or, checking this doc for config nics 
https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/network/cfg_network_adapter.html?highlight=confignetwork

**Comment by immarvin** [comment]
is ens192 your provision NIC?

**Comment by sinoag123** [comment]
grihpc@126.com
 
From: cxhong
Date: 2018-11-30 02:38
To: xcat2/xcat-core
CC: sinoag123; Author
Subject: Re: [xcat2/xcat-core] postscripts not run in compute node (#5847)
only has one nic for compute node? can u show output of ifconfig -a on the compute node?
also, can u show lsdef rhel72-clinet and 'grep rhel72-client /etc/hosts` ?
or, checking this doc for config nics
https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/network/cfg_network_adapter.html?highlight=confignetwork
