### ISSUE TITLE
[fvt]2.9.2:makenetworks could not write network information into database on aix720

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#585]
How to reproduce:
1.download the latest build
2.install xcat
3.bash-3.2# makenetworks
bash-3.2# hostname
c910f03c01p20.pok.stglabs.ibm.com
bash-3.2# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
bash-3.2# kdb
           START              END <name>
0000000000001000 00000000058E0000 start+000FD8
F00000002FF47600 F00000002FFE1000 __ublock+000000
000000002FF22FF4 000000002FF22FF8 environ+000000
000000002FF22FF8 000000002FF22FFC errno+000000
F1000F0A00000000 F1000F0A10000000 pvproc+000000
F1000F0A10000000 F1000F0A18000000 pvthread+000000
read vscsi_scsi_ptrs OK, ptr = 0xF1000000C0126DF0
(0)> stat
SYSTEM_CONFIGURATION:
CHRP_SMP_PCI POWER_PC POWER_8 machine with 4 available CPU(s)  (64-bit registers)

SYSTEM STATUS:
sysname... AIX
nodename.. c910f03c01p20
release... 2
version... 7
build date Nov  9 2015
build time 09:35:16
label..... 1544E_720
machine... 00F90E054C00
nid....... F90E054C
age of system: 5 day, 3 hr., 18 min., 6 sec.
xmalloc debug: enabled
FRRs active... 0
FRRs started.. 0

**Comment by junxiawang** [comment]
root cause for the bug is no netmask setting about the net so close the bug

**Comment by hu-weihua** [comment]
After debug, the value of network mask is blank, when xcat calculates the network information, it can't read out the value of netmask. so the all rest stuff of ``makenetworks`` went wrong.  then xcat thought itself didn't find out any correct network, so it gave up to write database.

@junxiawang , Could you configure the network completely again? thanks.
