### ISSUE TITLE
[customer]doc mislead user to use kerneldir in osimage definition

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#5864]
This is from xcat-user mailing list :
The document seems to have a problem with the examples —
the description talks about “kerneldir” attribute, but the example uses “pkgdir”. 
When I use pkgdir it clobbers the existing value (/install/rhels7.3/x86_64) 
with new value (/install/kernels/3.10.0-862.14.14.el7.x86_64)

I think it should say chdef -t osimage <> -p kerneldir=<> 
I got further using that format. However, I’m still having trouble with the packimage
command “Error: Cannot find rhels7.3-x86_64-neboot-comp_kup from the linuximage table.
But it’s there:
[root@mgt5 ~]# tabdump linuximage | grep rhels7.3-x86_64-netboot-comp_kup
"rhels7.3-x86_64-netboot-comp_kup",,,,,"/install/kernels/3.10.0-862.14.4.el7.x86_64,/install/rhels7.3/x86_64",,,,,,"/install/kernels/3.10.0-862.14.14.el7.x86_64",,,,,,,,,,,,

Let me fix:
1. document updates
2. if genimage have problem?

**Comment by bybai** [comment]
I think user confused about "kerneldir" and "pkgdir" in the docs. "kerneldir" here is for developer, "pkgdir" here is for user, so the doc should be updated.
... ...
The kerneldir attribute in linuximage table can be used to assign a directory containing kernel RPMs that can be installed into diskless images. The default for kernerdir is /install/kernels. To add a new kernel, create a directory named <kernelver> under the kerneldir, and genimage will pick them up from there.
... ...
```
chdef -t osimage <imagename> -p pkgdir=/install/kernels/3.10.0-229.ael7b.ppc64le/
```

**Comment by robin2008** [comment]
close it as customer find there are some missing attribute in osimage by wrong.

**Comment by bybai** [comment]
@robin2008, `genimage` works well. But I think user confused about "kerneldir" and "pkgdir" in the docs. "kerneldir" here is in `linuximage` table , "pkgdir" here is for user interface, so the doc should be updated clearly.

**Comment by robin2008** [comment]
Ok, need to update the doc

**Comment by bybai** [comment]
The new content shows https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/install_new_kernel.html
