### ISSUE TITLE
Section %packages does not end with %end error in diskful service node install

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5873]
lsxcatd -a
Version 2.14.5 (git commit 0c9bbb1, built Mon Dec 3 06:17:42 EST 2018)

Attempting rhels8.0-ppc64le-install-service 
which has osimage template def:
    template=/opt/xcat/share/xcat/install/rh/service.tmpl

I get error: 
Section %packages does not end with %end

Please determine if /opt/xcat/share/xcat/install/rh/service.tmpl is in error, or if we need a new/custom template for rhels8.0.

comparing to compute.rhels8.tmpl , it seems service.tmpl is needing  %end after  all 3 stanzas:

```
%packages --resolvedeps
#INCLUDE_DEFAULT_PKGLIST#
%pre
#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/pre.rh#
%post
#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/post.rh#
```

**Comment by immarvin** [comment]
hi @marksmit-ibm , the `/opt/xcat/share/xcat/install/rh/service.tmpl` does not work for redhat8, please use `/opt/xcat/share/xcat/install/rh/compute.rhels8.tmpl`  as the `template` as a workaround


hi @neo954 , I think we should create a link `/opt/xcat/share/xcat/install/rh/service.rhels8.tmpl` to `/opt/xcat/share/xcat/install/rh/compute.rhels8.tmpl`

**Comment by robin2008** [comment]
RH8 support is in 2.15, but now we can have the same template for compute node first.

**Comment by neo954** [comment]
Please get the latest xCAT development build with RHEL 8 support from the URL below.
https://github.com/xcat2/xcat2-task-management/issues/443

**Comment by neo954** [comment]
I will just close this one.
