### ISSUE TITLE
[Customer] Formatting issues improvements

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#588]
Hi,

Just using the Rest API to do a few things, and came across the following issue

if `addkcmdline=sshd=1` is set for the node, then this comes out to be `"addkcmdline=sshd":"1"` instead of `"addkcmdline":"sshd=1"`. There's a similar issue with kcmdline as well, and the output I generally get is 

```
<snip>
      "kcmdline=quiet inst.repo":"http://!myipfn!:80/install/centos7.1/x86_64 inst.ks=http://!myipfn!:80/install/autoinst/compute01 ip=dhcp  inst.cmdline  console=tty0 console=ttyS0,19200",
      "power":"ipmi",
      "nicips.enp2s1f0":"10.0.0.4",
<snip>
```

But the key should not be `kcmdline=quiet inst.repo`, but it should be `kcmdline`

I hope that makes sense

feature request:

what about having the group named as a list of attributes, i.e. 

```
"groups":{"ipmi","compute","x3455"}
```

rether than 

```
"groups":"ipmi,compute,x3455"
```

and we have something similar with `postscripts`, and `postbootscripts`

**Comment by arif-ali** [comment]
Commit 6dabd85bfe977c633a35fdb6b59a0bca100e280c, initially tried to fix the issue, but it doesn't solve the case where you have more than 1 equals on the line

**Comment by daniceexi** [comment]
@arif-ali If 6dabd85, does fix your issue, I'll take it back. Thanks.

Two concerns for your new requrest that output value as an **object** like {"ipmi","compute","x3455"}

* If this is changed, old customer will be impacted;
* An error will happen when **comma** is a common char in the value of node attribute. Only if we just handle the 'groups' and 'postscripts' attributes.

**Comment by arif-ali** [comment]
don't worry about the feature request, I have my way of resolving that at the moment

**Comment by tingtli** [comment]
@arif-ali  since we have component lable to indicate this bug is for REST-API. I modify the first key word to indicate this bug is from a xCAT customer

**Comment by daniceexi** [comment]
@arif-ali The fix has been checked in to 2.10, 2.11 and 2.12 branches.

**Comment by whowutwut** [comment]
@daniceexi , can we close this issue? 

You said that  6dabd85 fixes the issue but @arif-ali  said it was overwritten by  b78515b... is this resolved?

**Comment by arif-ali** [comment]
closing, as it has been committed

**Comment by arif-ali** [comment]
re-visiting this again, I am now trying to use the REST API in raw format, and the groups is still  problem, I think, this really needs to be a list, rather than a dict.

It's easier to recursively go through a list, rather than splitting the stuff from the commas, and creating a list yourself.

Unless, we can add another parameter, that can do this for us?

**Comment by whowutwut** [comment]
@chenglch @xuweibj when you get a chance, can you take a follow up look on this?

**Comment by chenglch** [comment]
@arif-ali , do you hope to define the `groups`, `postscripts` and `postbootscripts` as array type? Like below:
```
{
	"groups": ["ipmi", "compute", "x3455"],
	"postscripts": ["syslog", "remoteshell", "syncfiles"],
	"postbootscripts": ["otherpkgs"]
}
```
If this is your requirement, I plan to add a version number parameter to deal with the format changes about this.

**Comment by arif-ali** [comment]
Hi @chenglch, that makes sense. That's how I was converting them in the current code I had. Below is a python excerpt of what I am doing, when I am processing a node definition, and converting stuff

```python
    response = requests.get(
               url + '/nodes/' + nodename,
               params=params,
               headers=headers,
               verify=False,
               )
    result = response.json()[nodename]

    for key, value in result.iteritems():
      if value.count(','):
        result[key] = value.split(',')
      elif value.count('|'):
        result[key] = value.split('|')
      elif key == "groups" or key == "members":
        result[key] = [ value ]
```

And then I am returning the result as part of the json, which then gets processed in my main application

**Comment by chenglch** [comment]
@arif-ali , I have uploaded a pull request #4744 to fix this issue, considering the compatibility, a new url parameter `ver=1.0` should be appended.
If anything missed, please let me know.

**Comment by arif-ali** [comment]
Thanks @chenglch, When I have a new installation, and test it, I will give you my feedback

**Comment by immarvin** [comment]
no response, close this ticket
