### ISSUE TITLE
[FVT]:update lsdef usage.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#5894]
In manpage, we have following description for lsdef
```
2.  To get a list of all the objects that have been defined.

            lsdef
              OR
            lsdef -a
```
But with our code, lsdef could only display the node definition, lsdef -a could display all the objects.

Please update the code or if the  code is correct , please update the document.

**Comment by zet809** [comment]
hi, @tingtli , @gurevichmark have modified lsdef manpage, pls verify and close this issue. Thx!

**Comment by tingtli** [comment]
verified , thanks!
```
2.  To get a list of all the objects that have been defined.

            lsdef -a
```
