### ISSUE TITLE
[FVT] Failed to generate /tmp/install_disk file while reinstall RH7.2 or SLES11.04 on x86_64 

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#591]
ENV:
x86_64, one disk /dev/sda

Reproduce steps:
1. ReInstall Sles11.04 or reinstall Rh7.2 , 
2. ssh to the CN machine and track the /tmp/install_disk file after /tmp/xcat_getinstalldisk_log file created, wait until the node is closed, but no /tmp/install_disk file generated as designed.

**Comment by tingtli** [comment]
@caomengmeng  please give out xCAT build number for this defect.
You can give the contents of the output  of "rpm -qa |grep -i xCAT"
And It's better to give out xcat-dep tar ball name. Thanks!

**Comment by caomengmeng** [comment]
```
c910f04x31:~ # rpm -qa | grep xCAT
xCAT-genesis-scripts-x86_64-2.12-snap201512311931
xCAT-buildkit-2.12-snap201512311931
perl-xCAT-2.12-snap201601121533
xCAT-client-2.12-snap201512311931
xCAT-2.12-snap201601121533
xCAT-genesis-base-x86_64-2.9-snap201504212134
xCAT-server-2.12-snap201512311931
```

**Comment by caomengmeng** [comment]
Hotfix code error, not a bug. Function works well.

**Comment by daniceexi** [comment]
@caomengmeng what did you mean 'Hotfix code error'? Did you mean the new code change has problem?

**Comment by caomengmeng** [comment]
@daniceexi, I did a hotfix in local test machine, and there is something error, so it is a mistake for testing not for production, not a bug.
Maybe this issue should be deleted for invalid.

**Comment by daniceexi** [comment]
@caomengmeng Add a label status:invalid and set the invalid label for this issue.
