### ISSUE TITLE
build xcat  in freebsd

### ISSUE THREAD

**Issue by favoritelotus** [xcat2/xcat-core#5913]
Hello,

Cannot find any information on building xcat under FreeBSD. Is it possible to build xCAT under freebsd and setup management host?

**Comment by immarvin** [comment]
hi @favoritelotus , xCAT does not support FreeBSD officially, i.e, xCAT did not ship packages for freebsd and did not support provision openbsd on servers. 

not sure whether someone in xcat-user mail list tried this, you can subscribe the xcat-user mail list and send a mail to try your luck:) mail list is https://sourceforge.net/projects/xcat/lists/xcat-user

or you can try to complete sth by yourself and contribute to xCAT:)

**Comment by immarvin** [comment]
another option is to use dockerized xCAT,  not sure whether docker is supported well in freebsd. see https://xcat-docs.readthedocs.io/en/latest/advanced/docker/dockerized_xcat/dockerized_xcat.html
