### ISSUE TITLE
makedns does not support "forward only" option

### ISSUE THREAD

**Issue by adambertsch** [xcat2/xcat-core#5958]
For a DNS environment that uses the forwarders= option in named.conf, it would also be good (and in many cases necessary) to support the forward-only option.  Today makedns creates the following named.conf file when forwarders are specified:

```
#generated by xCAT: /opt/xcat/sbin/makedns command
options {
        directory "/var/named/";
        allow-recursion { any; };
        forwarders {
                x.y.z.1;
                x.y.a.1;
        };
        empty-zones-enable no;
};
```

What we would like to do is have another site table option (forward-only=true, or something like that) to enable makedns to generate the following:

```
#generated by xCAT: /opt/xcat/sbin/makedns command
options {
        directory "/var/named/";
        allow-recursion { any; };
        forwarders {
                x.y.z.1;
                x.y.a.1;
        };
        forward only;
        empty-zones-enable no;
};
```

**Comment by immarvin** [comment]
this ticket is somehow similar with a previous ticket https://github.com/xcat2/xcat-core/issues/5897. 

I suggest xCAT provide a general way to specify/preserve user customized options, since named/dhcp has so many options

**Comment by bybai** [comment]
Since `forward` has value `first` and `only`, plan to add `forwardmode` site table option to generate the config file.

**Comment by whowutwut** [comment]
@adambertsch Did you want us to start looking into this issue or did you want to tackle it?  @bybai  assigned it to herself and will start the work unless you tell us otherwise  😸

**Comment by adambertsch** [comment]
I'm on vacation, so I wont be looking at much this week. So if you guys take care of it I'll only be thankful.

**Comment by cxhong** [comment]
Maybe I should post here, instead in the PR
I verified this PR on boston02 with March 26th build.
The service node /etc/named.conf didn't change for whatever values I set to for setupnameserver and dnsforwardmode
```
[root@sn02 etc]# ls -ltr named.conf.ORIG named.conf
-rw-r----- 1 root root  259 Mar 26 13:55 named.conf.ORIG
-rw-r----- 1 root named 259 Mar 26 13:55 named.conf
[root@sn02 etc]# cat named.conf
options {
        directory "/var/named";
        dump-file "/var/named/data/cache_dump.db";
        statistics-file "/var/named/data/named_stats.txt";
        memstatistics-file "/var/named/data/named_mem_stats.txt";
        recursion yes;
        forward only;
        forwarders {
                172.20.253.31;
        };
};
```

**Comment by bybai** [comment]
@cxhong, this issue is about how to customize forward mode in named.conf.
I think your meaning about "forwarders { 172.20.253.31; };" is not changed in SN, this part is our setupnameserver feature control, in your example, it should be "setupnameserver=1" result.
"forward mode" is different function from "setupnameserver" or "customize forwarders" in SN, here our user do not complain about "customize forwarders", so I think support customize "forward mode" is the user requirement, and keep "setupnameserver" function the same as before in SN. Thanks.

**Comment by cxhong** [comment]
Ok,  I just followed your unit testing in the PR #5970.    The results are different from what you showed on the Hierarchy cluster.

**Comment by bybai** [comment]
Hi @cxhong, 
I guess your meaning is that "forwarders" are not changed in ``sn02``? 
I think you do not  run ``makedns -n`` in ``sn02``. And I did not modify "forwarders" actions in PR #5970.  I only add "forward only;" here.

If you run ``makedns -n`` in sn02, the `/etc/named.conf` is changed.
```
[root@sn02 ~]# cat /etc/named.conf
options {
	directory "/var/named";
	dump-file "/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	recursion yes;
	forward only;
	forwarders {
		172.20.253.31;
	};
};

[root@sn02 ~]# makedns -n
Handling localhost in /etc/hosts.
Handling localhost in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
DNS setup is completed

[root@sn02 ~]# cat /etc/named.conf
#generated by xCAT: /opt/xcat/sbin/makedns command
options {
	directory "/var/named/";
	allow-recursion { any; };
	forwarders {
		10.6.29.1;
	};
	forward only;
	empty-zones-enable no;
	notify yes;
	allow-transfer {
		172.20.254.2;
	};
	also-notify {
		172.20.254.2;
	};
};
```

**Comment by cxhong** [comment]
Thanks @bybai
