### ISSUE TITLE
Genesis issues found in 2.14.5

### ISSUE THREAD

**Issue by illmaticone** [xcat2/xcat-core#5964]
We can see the IO nodes get IP from EMS but never boot from xCAT genesis. This is only happening in xCAT version 2.14.5. I debugged it further but didn't find any reason why it's not booting. Looks like xCAT genesis is broken in latest version of xCAT. 

Seems like the nodes get a IP address from DHCP but never leaves petitboot

system type = Power 8 node in OPAL mode (ESS environment)

Please follow up with me for more system information and logs etc.

**Comment by zet809** [comment]
This is a known issue, let's close this and reopen if encountered again.
