### ISSUE TITLE
#4715 Ubuntu MN to provision rhel CN failed

### ISSUE THREAD

**Issue by chudegao** [xcat2/xcat-core#60]
Use Ubuntu MN to provision rhel CN,it can't install the packages in osimage.otherpkgdir.We think that the product didn't consider the cross environment.
When add a kit, xCAT creates the directory for package repo, if the MN's os type is Ubuntu,it directly copies from the source kit, if the MN's os type is Rhel, it makes a link to the source kit.It causes when Ubuntu MN tries to provision rhel CN, MN directly copies the rhel's source directory which should be a link and all the links under the directory can't point to the real source. 
We suggest that the directory-creating progress should depend on osdistro's type other than the MN's OS type.

**Comment by bybai** [comment]
We discussed this defects in http://sourceforge.net/p/xcat/bugs/4715/;
This defect affect PCM use case in mixed cluster. Change owner to Jianbo cui.
From xcat part advise, do not use link in the kit directory itself. 
Another work around, manually make link to the source kit.
