### ISSUE TITLE
xcat on Centos 7.6.1810 - all compute nodes hang overnight

### ISSUE THREAD

**Issue by pcmc** [xcat2/xcat-core#6015]
Dear all,

Again, if this is not the right place to post this question, please kindly redirect me.

Having installed xcat on a small cluster running Centos 7.6.1810, my excitement seems 
to be short-lived when I found out all the compute nodes hang in the early hours of the morning.
The symptoms are:
Ping to any of the compute nodes get no response
Ping to the compute node ipmi port get no response
At the console, there was a steady ongoing display of messages:
[64775.256732] nfs: server main not responding, timed out
[64864.242286] nfs: server main not responding, timed out
No response to any key pressed.

The master node main however is active, no problem in logging in over the network.
showmount -e  main also gives expected resuilt. 

/var/log/messages records some DHCPDiscover messages, but none of the MAC
addresses are from the compute nodes.  So I can assume DHCP was running at the time.

There were a few errors I can see in the /var/log/xcat/compute.log.

One is that it complained the ssh key with permission 0640 being too open.  But I would not have thought this poses a major issue.

Another relates to 
Feb 20 02:50:14 proc01 systemd-udevd: ERR  failed to execute '/usr/lib/udev/sock
et:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': 
No such file or directory
A google search suggests that it comes about when HAL is no longer supported.

I am not sure what that means and if it is the cause of the system hang.
I have uploaded a copy of the compute.log here.

Any idea what could be causing the compute nodes to hang?

Many thanks in advance.

Peter
[computes.log-20190220.txt](https://github.com/xcat2/xcat-core/files/2884613/computes.log-20190220.txt)

**Comment by immarvin** [comment]
hi @pcmc , what is the xcat version?


The following message shows that the boot up process is stuck on the failed nfs mount due to invaliable NFS server `main`
> At the console, there was a steady ongoing display of messages:
```
[64775.256732] nfs: server main not responding, timed out
[64864.242286] nfs: server main not responding, timed out
```

my question is: why there is a NFS mount in the boot up process? what osimage are you using?please provide the osimage definition and node definition to help us to find the root cause.

Another issue I noticed in the `computes.log` you attached is:
```

Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: Permissions 0640 for '/etc/ssh/ssh_host_ecdsa_key' are too open.
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: It is required that your private key files are NOT accessible by others.
Feb 20 02:50:14 proc03 sshd[3247]: ERR  error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: This private key will be ignored.
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: key_load_private: bad permissions
Feb 20 02:50:14 proc03 sshd[3247]: ERR  error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
Feb 20 02:50:14 proc02 sshd[3270]: ERR  error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
```
this seems to be a duplicate issue in https://github.com/xcat2/xcat-core/issues/2617

**Comment by pcmc** [comment]
Many thanks for your reply.

To answer your questions:
1. xCAT version:
[root@main ~]# rpm -q xCAT
xCAT-2.14.5-snap201812062220.x86_64

I used the go-xcat to install the software about a week ago now (14th Feb).
2. NFS Mount on compute nodes:
In the boot image for the compute nodes, I have the following set in /etc/fstab:
main.bnsc.rl.ac.uk:/install             /install        nfs     defaults,tcp,vers=3     0 0
main.bnsc.rl.ac.uk:/home/users    /home/users     nfs     defaults,tcp,vers=3     0 0
main.bnsc.rl.ac.uk:/opt/software  /opt/software   nfs     defaults,tcp,vers=3     0 0
main.bnsc.rl.ac.uk:/usr/local         /usr/local      nfs     defaults,tcp,vers=3     0 0
main.bnsc.rl.ac.uk:/csupport         /csupport       nfs     defaults,tcp,vers=3     0 0

But as mentioned earlier, while the compute nodes were hanging, I have checked
the master node (main.bnnsc.rl.ac.uk) was exporting okay, using showmount and mount.

3. osimage:
[root@main ~]# lsdef -t osimage
centos7.6-x86_64-install-compute  (osimage)
centos7.6-x86_64-netboot-compute  (osimage)
centos7.6-x86_64-statelite-compute  (osimage)
[root@main ~]# lsdef -t osimage centos7.6-x86_64-netboot-compute
Object name: centos7.6-x86_64-netboot-compute
    exlist=/opt/xcat/share/xcat/netboot/centos/compute.centos7.exlist
    imagetype=linux
    netdrivers=dca,ixgbe,igb,e1000e,e1000,forcedeth,tg3
    nodebootif=eth0
    osarch=x86_64
    osdistroname=centos7.6-x86_64
    osname=Linux
    osvers=centos7.6
    otherpkgdir=/install/post/otherpkgs/centos7.6/x86_64
    permission=755
    pkgdir=/install/centos7.6/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/centos/compute.centos7.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/centos/compute.centos7.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/centos7.6/x86_64/compute
[root@main ~]# 

4. Node definitions:
[root@main ~]# tabdump nodelist
#node,groups,status,statustime,appstatus,appstatustime,primarysn,hidden,updatestatus,updatestatustime,zonename,comments,disable
"main","master",,,,,,,,,,,
"proc01","compute,ipmi","booted","02-22-2019 07:29:55",,,,,,,,,
"proc02","compute,ipmi","booted","02-22-2019 07:30:05",,,,,,,,,
"proc03","compute,ipmi","booted","02-22-2019 07:30:06",,,,,,,,,
"proc04","compute,ipmi","booted","02-22-2019 07:30:22",,,,,,,,,
"node-0025905aec91","all",,,,,,,,,,,
"node-0025905aec77","all",,,,,,,,,,,
"node-0025905aeca6","all",,,,,,,,,,,
"node-002590d65c75","all",,,,,,,,,,,
"node-0025905aec73","all",,,,,,,,,,,
[root@main ~]# 
[root@main ~]# lsdef main
Object name: main
    groups=master
    ip=130.246.32.140
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
[root@main ~]# 

The master (management) node:
[root@main ~]# lsdef main
Object name: main
    groups=master
    ip=130.246.32.140
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
[root@main ~]# 
[root@main ~]# 

One of the compute nodes:
[root@main ~]# lsdef proc01
Object name: proc01
    addkcmdline=selinux=0
    arch=x86_64
    bmc=130.246.32.151
    chain=runcmd=bmcsetup,standby
    cpucount=24
    cputype=Intel(R) Xeon(R) CPU E5-4607 0 @ 2.20GHz
    currchain=standby
    currstate=netboot centos7.6-x86_64-compute
    disksize=sda:11176GB
    groups=compute,ipmi
    initrd=xcat/osimage/centos7.6-x86_64-netboot-compute/initrd-stateless.gz
    installnic=eth0
    ip=130.246.32.141
kcmdline=imgurl=http://130.246.32.140:80//install/netboot/centos7.6/x86_64/compute/rootimg.cpio.gz XCAT=130.246.32.140:3001 NODE=proc01 FC=yes ifname=eth0:00:25:90:5a:eb:8a netdev=eth0 
    kernel=xcat/osimage/centos7.6-x86_64-netboot-compute/kernel
    mac=00:25:90:5a:eb:8a
    memory=257932MB
    mgt=ipmi
    mtm=Supermicro:X9QR7-TF+/X9QRi-F+
    netboot=xnba
    nichostnamesuffixes.ipmi=-mng
    nicips.ipmi=130.246.32.151
    nodetype=osi
    os=centos7.6
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    power=ipmi
    primarynic=eth0
    profile=compute
    provmethod=centos7.6-x86_64-netboot-compute
    serial=123456789
    status=booted
    statustime=02-22-2019 07:29:55
    supportedarchs=x86,x86_64
    xcatmaster=130.246.32.140
[root@main ~]# 

5. As to the file permission on /etc/ssh/ssh_host_ecdsa_key, 
I have earlier manually corrected that, ie. changed them to 600.

The compute nodes failed last night again.
But this time, the system log suggested the stopped around 19:30?
21-Feb-2019 Thu 19:30:02 up 11:57, 0 users, load average: 0.0 0.02, 0.05
22-Feb-2019 Fri 07:27:11 up 1 min, 0 users, load average: 2.3 0.94, 0.34
22-Feb-2019 Fri 07:27am Down: 42968 s
22-Feb-2019 Fri 07:28:23 up 2 min, 0 users, load average: 0.7 0.77, 0.33
22-Feb-2019 Fri 07:30:01 up 3 min, 0 users, load average: 0.1 0.56, 0.30

Once again, I have checked the compute.log and messages, no clue why that was so.

I really grateful for your help on this.

Regards,
Peter

**Comment by immarvin** [comment]
hi @pcmc , so this is a NFS issue. You can try to mount the directories with the options in /etc/fstab from a client node to see whether the NFS work.  

```
main.bnsc.rl.ac.uk:/install /install nfs defaults,tcp,vers=3 0 0
main.bnsc.rl.ac.uk:/home/users /home/users nfs defaults,tcp,vers=3 0 0
main.bnsc.rl.ac.uk:/opt/software /opt/software nfs defaults,tcp,vers=3 0 0
main.bnsc.rl.ac.uk:/usr/local /usr/local nfs defaults,tcp,vers=3 0 0
main.bnsc.rl.ac.uk:/csupport /csupport nfs defaults,tcp,vers=3 0 0
```
This is a Redhat Doc to help debug questions like this:  https://access.redhat.com/solutions/28211

I would like to indicate that **it is dangerous to put NFS entries in /etc/fstab of compute nodes, which will cause the boot up process hang without chance to debug**. I suggest you add a postscript to mount the entries, with the  options:
```
       retrans=n      The number of times the NFS client retries a request before it attempts further recovery action. If  the
                      retrans option is not specified, the NFS client tries each request three times.

                      The  NFS client generates a "server not responding" message after retrans retries, then attempts further
                      recovery (depending on whether the hard mount option is in effect).

       timeo=n        The time in deciseconds (tenths of a second) the NFS client waits for a response before  it  retries  an
                      NFS request.

                      For  NFS  over TCP the default timeo value is 600 (60 seconds).  The NFS client performs linear backoff:
                      After each retransmission the timeout is increased by timeo up to the maximum of 600 seconds.

                      However, for NFS over UDP, the client uses an adaptive algorithm  to  estimate  an  appropriate  timeout
                      value  for  frequently  used request types (such as READ and WRITE requests), but uses the timeo setting
                      for infrequently used request types (such as FSINFO requests).  If the timeo option  is  not  specified,
                      infrequently  used  request  types  are  retried  after 1.1 seconds.  After each retransmission, the NFS
                      client doubles the timeout for that request, up to a maximum timeout length of 60 seconds.
```

**Comment by pcmc** [comment]
Hello Yangsong,

I suppose there are two issues here:

1.  nfs mounting  on the compute nodes

     I can remove these mounts and put them into automount in the compute image.
     Maybe I should have added that, the compute nodes can mount the storage from the master node.
     during a normal start up.    

     Say, when the compute nodes are "hang" or down, from the master node

     rpower compute reset    # will be able to bring all the computes back up as normal.

     So I am not too sure the issue on NFS is the major one.
     But as you advised, I shall remove them from /etc/fstab 
     and put them into /etc/auto.misc.   

2.   Why the compute nodes hang after working for a number of hours after a clean restart, 
      and became hang, or tried to reboot itself later on?

      Is it possible to enable some debugging to understand what causes the compute nodes to hang or reboot?   

Many thanks for your help again.

Peter
PS. The fault persists over the past weekend.

**Comment by immarvin** [comment]
> 2. Why the compute nodes hang after working for a number of hours after a clean restart,
    and became hang, or tried to reboot itself later on?

you did not mention this in the initial post, how did this happen? did all the nodes hang or reboot simultaneously? if yes, this might be still the NFS issue, this depends on how the applications are using the NFS mounted directories. Can you ping or ssh them? 

All the logs of compute nodes come to `/var/log/xcat/computes.log` and `/var/log/messages` on master node, you can check them to see whether there is anything suspicious.

**Comment by pcmc** [comment]
Dear all,

Just an update to this problem of my set up.

I believe the fault arises when the compute node dhcp client lease runs out and could not be renewed.

To get round this, I have made the max-lease-time and default-lease-time to be a very number in /etc/dhcp/dhcpd.conf.  The default and maximum settings are 43200s or 12 hours.

The compute nodes have been able to run without the system hang for past few days.

Regards,
Peter
