### ISSUE TITLE
confignics

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#6057]
@ChristopherWalker commented on [Thu Mar 07 2019](https://github.com/xcat2/xcat.org/issues/134)

https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/network/cfg_second_adapter.html

This page points out that confignics is deprecated. It would be useful if it pointed to the new version (which I think is confignetwork).

**Comment by bybai** [comment]
Hi @ChristopherWalker,
Thanks your suggestions.  I made a small enhancements for confignics doc.

We have both docs for ``confignetwork`` and ``confignics``, we recommend using ``confignetwork``.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/6743951/54006066-d7077200-4196-11e9-813e-f62527083a28.png">

**Comment by zet809** [comment]
The document is updated, so close this issue.
