### ISSUE TITLE
SLES12 - xcat-debug.conf - daemon.=debug not working

### ISSUE THREAD

**Issue by floewe** [xcat2/xcat-core#6064]
Hi,

on SLES12 (SP1-4) xcat-debug.conf is not working.
/var/log/messages remains empty.

Changing
daemon.=debug;ftp.*             /var/log/messages
to
daemon.debug;ftp.*             /var/log/messages
will fix it. The term .=debug is not working and unnecessary, because
.debug already is the highest security level.

Best Regards
Frank

**Comment by immarvin** [comment]
hi @floewe , thanks for pointing this out. 
What is the `syslog` version on your SLES12 (SP1-4) MN, would you please provide the following information:
```
# rpm -qa|grep syslog
```

and 
```
# rsyslogd -v
```

thanks

**Comment by immarvin** [comment]
hi @floewe ,`=debug` is a valid rsyslog configuration syntax, only the daemon log entries with "debug" priority will be appended to  `/var/log/messages`. 


The consideration here is:  xCAT only ships the rsyslog configurations to persistent logs for xCAT debugging purpose(https://github.com/xcat2/xcat-core/issues/760), and keep the os shipped and user customized rsyslog configuration untouched. So if the os shipped rsyslog configuration and xCAT shipped rsyslog configuration does not meet you requirement, please feel free to modify `rsyslog.conf` or add new config file under `/etc/rsyslog.d/`, we do not have plan to modify `xcat-debug.conf `.

**Comment by floewe** [comment]
Hi @immarvin,

it is a valid, but unnecessary Syntax, right. Old xCAT 2.13 touches the entry /var/log/messages, that is why we fund an empty /var/log/messages, cause daemon.=debug does not seem to work.

Example SLES12-SP3

x-x:~ # rpm -qa | grep rsyslog
rsyslog-8.24.0-3.19.1.x86_64

x-x:~ # rsyslogd -v
rsyslogd 8.24.0, compiled with:
        PLATFORM:                               x86_64-suse-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

**Comment by immarvin** [comment]
hi @floewe ,  my last comment is based on the behavior of latest xCAT 2.14.x.  xCAT 2.13 will comment all the lines for `/var/log/messages` in rsyslog.conf.

**Comment by immarvin** [comment]
Please modify the rsyslog configuration for your need
