### ISSUE TITLE
rflash of BMC fw needs to power off Host first

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6065]
The new version of BMC firmware fixes some security issues. As a result, running new BMC fw with older Host fw is no longer permitted.

The recommendation from openbmc team is to power off host before activating BMC fw.

For xCAT `rflash` command we should:

1. Power off host before `rflash -a <bmc fw id>` command is issued.
2. Power off host before `rflash -a <bmc fw .tar>` command is issued.
3. Power off host before `rflash -d` command is issued. 
4. Option `--no-host-reboot` should be removed.
5. Usage and man page should be updated.

**Comment by gurevichmark** [comment]
Flashed the latest BMC FW:
```
[root@briggs01 ~]# rflash mid05tor12cn03 -l
mid05tor12cn03: ID       Purpose State      Version
mid05tor12cn03: -------------------------------------------------------
mid05tor12cn03: 376af621 BMC     Active     ibm-v2.1-438-g0030304-r15-0-g19832d3
mid05tor12cn03: 13ff6e72 Host    Active(*)  IBM-witherspoon-ibm-OP9-v2.0.8-2.2
mid05tor12cn03: ff727722 BMC     Active(*)  ibm-v2.3-476-g2d622cb-r26-0-g7fc4a06
mid05tor12cn03:
[root@briggs01 ~]# ping mid05tor12cn03
PING mid05tor12cn03 (172.12.139.3) 56(84) bytes of data.
64 bytes from mid05tor12cn03 (172.12.139.3): icmp_seq=1 ttl=64 time=0.222 ms
^C
--- mid05tor12cn03 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.222/0.222/0.222/0.000 ms

[root@briggs01 ~]# ssh mid05tor12cn03
Last login: Tue Mar 12 10:47:43 2019 from gateway

[root@mid05tor12cn03 ~]#
```

**Comment by gurevichmark** [comment]
Flashed the latest Host FW. Host reboots with new BMC FW and new Host FW:
```
[root@briggs01 consoles]# rflash mid05tor12cn03 -l
mid05tor12cn03: ID       Purpose State      Version
mid05tor12cn03: -------------------------------------------------------
mid05tor12cn03: 376af621 BMC     Active     ibm-v2.1-438-g0030304-r15-0-g19832d3
mid05tor12cn03: 13ff6e72 Host    Active     IBM-witherspoon-ibm-OP9-v2.0.8-2.2
mid05tor12cn03: 5fc4d9ff Host    Active(*)  IBM-witherspoon-OP9_v2.0.11_1.8
mid05tor12cn03: ff727722 BMC     Active(*)  ibm-v2.3-476-g2d622cb-r26-0-g7fc4a06
mid05tor12cn03:

[root@briggs01 consoles]# ssh mid05tor12cn03
Last login: Tue Mar 12 10:55:01 2019 from gateway
[root@mid05tor12cn03 ~]#
```

**Comment by gurevichmark** [comment]
Trying to boot host with new BMC FW but old Host FW.
Host does not boot and gets put into `quiesced` state.
`reventlog` returns entries containing `Software.Version.Error.Incompatible` error.
```
[root@briggs01 ~]# rpower mid05tor12cn03 state
mid05tor12cn03: quiesced
[root@briggs01 ~]#
```
```
[root@briggs01 ~]# reventlog mid05tor12cn03 5
mid05tor12cn03: 03/12/2019 11:40:29 [82]: Firmware/Software Failure, (Critical) Hostboot has become unresponsive (AffectedSubsystem: Systems Management - Core / Virtual Appliance, PID: 7614), Resolved: False
mid05tor12cn03: 03/12/2019 11:41:12 [83]: Not found in policy table: xyz.openbmc_project.Software.Version.Error.Incompatible (PID: 7694), Resolved: False
mid05tor12cn03: 03/12/2019 11:41:56 [84]: Firmware/Software Failure, (Critical) Hostboot has become unresponsive (AffectedSubsystem: Systems Management - Core / Virtual Appliance, PID: 8126), Resolved: False
mid05tor12cn03: 03/12/2019 11:42:39 [85]: Not found in policy table: xyz.openbmc_project.Software.Version.Error.Incompatible (PID: 8208), Resolved: False
mid05tor12cn03: 03/12/2019 11:43:23 [86]: Firmware/Software Failure, (Critical) Hostboot has become unresponsive (AffectedSubsystem: Systems Management - Core / Virtual Appliance, PID: 8644), Resolved: False
[root@briggs01 ~]#
```

**Comment by whowutwut** [comment]
@gurevichmark also can you  check if we have the openbmctool rpm installed on the  MN , and if we do not, what the eventlog message will look like... or is this the message without openbmctool installed for crassd.

**Comment by gurevichmark** [comment]
After some discussion with @whowutwut we decided to only implement items 4 and 5 described above.
* Items 1 and 2 only upload and activate BMC FW but it does not take affect until after the BMC reboot. The admin might be just staging FW updates and would not want to power off Host at that time.
* Item 3 seems unnecessary. Is there any point powering Host *before* BMC FW update if Host will be rebooted *after* BMC FW update ?

**Comment by robin2008** [comment]
@gurevichmark  

> As a result, running new BMC fw with older Host fw is no longer permitted.

Is this only for a specific fw version (from the old to currently patch including security issue),  or even for new firmware in future. 

For example, after I upgrade both HOST and BMC to the latest level, and I want to update a newer level, what's the correct behavior?

**Comment by gurevichmark** [comment]
@robin2008 I think after this version of BMC and HOST FW future upgrades of BMC and HOST should work as before without the need to match. But I feel it would make our code too complicated to decide which versions are allowed to be used with or without the `--no-host-reboot` option.
Perhaps it is easier to remove that option completely from `rflash -d` and user can still use `rflash -a` to upload and activate what they want and reboot host manually as needed.

**Comment by zet809** [comment]
Remove this option from rflash document is good enough in case in the future the limitation is removed, then we don't need to modify our code.
So, I suggest to close this issue, what is your point? @gurevichmark and @robin2008
