### ISSUE TITLE
genimage for redhat8 diskless complains "Detection of Platform Module failed: Cannot open file  <..>/os-release"

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#6069]
The manpage of `yum/dnf` mentions:
```
       --installroot=<path>
              Specifies an alternative installroot, relative to where all packages will be installed. Think of this like doing
              chroot <root> dnf except using --installroot allows dnf to work before the chroot is created.
```
       · cachedir, log files, releasever, and gpgkey are taken from or  stored  in  installroot.  Gpgkeys  are  imported  into
         installroot from path, related to the host, described in .repo file.

       · config file and reposdir are searched inside the installroot first. If they are not present, they are taken from host
         system.  Note:  When a path is specified within command line argument (--config=<config file> in case of config  file
         and --setopt=reposdir=<reposdir> for reposdir) then this path is always related to the host with no exceptions.

       · The pluginpath and pluginconfpath are not related to installroot.
          Note:  You  may also want to use the command-line option --releasever=<release> when creating the installroot other‐
          wise the $releasever value is taken from the rpmdb within the installroot (and thus it is empty at time of creation,
          the transaction will fail). If --releasever=/ is used, the releasever will be detected from host (/) system. The new
          installroot path at time of creation does not contain repository, releasever, and dnf.conf file.

          On modular system you may  also  want  to  use  the  command-line  option  --setopt=module_platform_id=<module_plat‐
          form_name:stream>  when  creating  the  installroot  otherwise   the  module_platform_id  value  is  taken  from the
          /etc/os-release within the installroot (and thus it is empty at time of creation, the modular  dependency  could  be
          unsatisfied and modules content could be excluded).

          Installroot examples:

          dnf --installroot=<installroot> --releasever=<release> install system-release
                 Sets permanently the releasever of the system within <installroot> directory from given <release>.

**Comment by immarvin** [comment]
see https://bugzilla.redhat.com/show_bug.cgi?id=1678596

**Comment by neo954** [comment]
For reference, see https://bugzilla.redhat.com/show_bug.cgi?id=1678596

**Comment by neo954** [comment]
FYI https://docs.fedoraproject.org/en-US/modularity/
