### ISSUE TITLE
[FVT]:update case xcatconfig_u_check_xcatsslversion_rhels_sles and xcatconfig_u_check_xcatsslversion_ubuntu according to xcatsslversion default value is changed to blank 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#6071]
Since xcatsslversion default value is changed in pr https://github.com/xcat2/xcat-core/pull/6061
Need to update case xcatconfig_u_check_xcatsslversion_rhels_sles and xcatconfig_u_check_xcatsslversion_ubuntu

**Comment by hu-weihua** [comment]
link to https://github.com/xcat2/xcat2-task-management/issues/632

**Comment by hu-weihua** [comment]
Have been verified in automation environment, close this issue.
