### ISSUE TITLE
[FVT]: makedns fails for "failed to start named" with rhels8 patch 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#6077]
The xcat-core and xcat-dep tar ball are
```
xcat-core: rhels8_branch_daily_build/20190311.0615

xcat-dep: 
http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201811190436.tar.bz2
http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-201811200025.tar.bz2
```
on mn, run makedns -n and get the following errors
```
root@c910f04x30v02:~# makedns -n
Handling f6u13k18 in /etc/hosts.

Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting bind9
Error: [c910f04x30v02]: failed to start named.

root@c910f04x30v02:~# echo $?
1
```

**Comment by neo954** [comment]
The testing environment runs Ubuntu 18.04.

**Comment by hu-weihua** [comment]
@tingtli I am not sure who changed the dns configuration on control node 10.3.17.10, the local ubuntu mirror dns setting was deleted. It maybe affect your test result. I have changed the configuration back and restart some ubuntu test project. Could you help to check again? thanks.

**Comment by tingtli** [comment]
This is configuration problem, close it.
