### ISSUE TITLE
[DEV] A typo of  coding in InstUtils.pm

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#608]
@xuweibj I found a typo in your check in f2b9f6e94a13fa939f0d5d93e38aa69c0eff7ec1

``@servd[0]`` should be ``$servd[0]``
~~~~
--- a/perl-xCAT/xCAT/InstUtils.pm
+++ b/perl-xCAT/xCAT/InstUtils.pm
@@ -758,7 +758,8 @@ sub get_server_nodes
         else
         {
             #  get ip facing node
-                       $serv = xCAT::NetworkUtils->my_ip_facing($node);
+            my @servd= xCAT::NetworkUtils->my_ip_facing($node);
+            unless (@servd[0]) { $serv = $servd[1];}
         }
~~~~

**Comment by whowutwut** [comment]
@daniceexi, can you provide details how you found this?
Why was this missed by the FVT testing? @tingtli?

**Comment by daniceexi** [comment]
@whowutwut This is unusual usage of array, perl syntax check will give a warning, but it does work. So test did not find this issue.

**Comment by daniceexi** [comment]
I have verified the change.
