### ISSUE TITLE
Error of command fail when run `xcatconfig -u` on RHEL 8

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#6091]
This is a migration problem.

```
# xcatconfig -u
Command failed: /usr/sbin/conserver -V 2>&1. Error message: .
```

That is due to there is no `conserver` on RHEL 8.

**Comment by robin2008** [comment]
Not catch the point,  
- if it is RHEL7 and conserver is used, then upgrade, it should still use conserver.
- if it is RHEL8, then no conserver anymore, so when you upgrade on RH8 MN, only goconserver is covered.

**Comment by neo954** [comment]
@robin2008, you are right. But `xcatconfig` does not handle `gonconserver` things. And `xcatconfig -u` try to regenerate conserver config file anyway.

**Comment by xuweibj** [comment]
The problem was verified on ``Version 2.14.6 (git commit e97e5fa8f9f139cc04fc4e8ee5d794d5e159c17a, built Thu Mar 21 06:18:57 EDT 2019)``
