### ISSUE TITLE
Improve and update xcat.post mini design

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#610]
1. For critical error and plain error logs.
    1.1 the file or folder where the logs will be wrote.
    1.2 which kind of logs will be written when the debugmode is open or not.
2. For planing output section. 
    2.1 issue 5 title and file names should be updated.
    2.2 issue6 and issue11 should be deleted.
3. For plain error section, the issue 6 should be deleted.
4. Add supported OS in design.

**Comment by penguhyang** [comment]
updated mini-design for post.xcat
https://github.com/xcat2/xcat-core/wiki/post.xcat_restructure
