### ISSUE TITLE
Any method to sync normal user accounts from manage node to compute nodes?

### ISSUE THREAD

**Issue by z-gong** [xcat2/xcat-core#6108]
I'm trying to add a new user account to a cluster.

With rocksclusters, I can run `# rocks sync users` so that normal users and groups (uid, gid > 500) in `/etc/passwd, group, shadow` files are spreaded to compute nodes.

Is there similar method in xCat, or I have to write script to do this?

From the document, I can use `MERGE:` command in `synclist` file, and sync these three files using `xdcp`. However, after i did this, the system account in compute nodes are also modified, and I cannot login to compute nodes any more.

**Comment by immarvin** [comment]
hi @z-gong , how did you specify the synclist? Please notice that you can not directly merge `/etc/passwd, group, shadow` files from MN to according files on CN, like 
```
MERGE:
/etc/passwd -> /etc/passwd
```
You have to generate the files to merge first, which only includes the normal users and groups entries in `/etc/passwd`, `/etc/group`, `/etc/shadow` you want to merge, xCAT will merge/update these entries into the according files on CN

for example, you can run the follow command to generate the merge file `/tmp/passwd.sync` for `/etc/passwd`
```
cat /etc/passwd|sort -t: -k3 -n|awk -F: '$3>500' >/tmp/passwd.sync
```

then run the following command to generate the merge file for `/etc/shadow`

```
# for line in $(</etc/shadow); do [ "$(id -u $(echo $line |cut -d: -f1) 2>/dev/null|| echo 0)" -gt 500 ] && echo $line ;done > /tmp/shadow.sync
```

then specify `/tmp/passwd.sync -> /etc/passwd` and `/tmp/shadow.sync -> /etc/shadow` in `MERGE` clause in synclist

**Comment by z-gong** [comment]
@immarvin Thank you. This works.

**Comment by immarvin** [comment]
hi @z-gong , just curious about the background, you mentioned rocks, are you using ROCKS and xCAT simultaneous in your cluster? or trying to move from rocks to xCAT?

**Comment by z-gong** [comment]
@immarvin I was using Rocks6 before. Now I need to update cluster to CentOS7. So I'm moving to xCAT.

**Comment by immarvin** [comment]
got it @z-gong , please feel free to open ticket if any issue during your xCAT journey.
