### ISSUE TITLE
No installing status during redhat8 install

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#6115]
MN 
ARCH: ppc64le
OS: Red Hat Enterprise Linux Server 7.5
xCAT version: Version 2.14.6 (git commit 5e69deaf92ad445faf05f0b70a6b888cd7406715, built Fri Mar 15 06:18:47 EDT 2019)

CN: 
ARCH: ppc64le

ISO: RHEL-8.0.0-RC-1.0/RHEL-8.0.0-20190228.1-ppc64le-dvd1.iso

Install command:
``rinstall c910f03c17k11 osimage=rhels8.0.0-ppc64le-install-compute``

``lsdef <cn>`` when installing os, did not see ``installing`` status. From the console could see ``Installing xxxx``.

**Comment by robin2008** [comment]
@xuweibj   Please check if any ERROR log in `/var/log/xcat/cluster.log`, and append them here.

**Comment by xuweibj** [comment]
@robin2008 No ERROR log in ``/var/log/xcat/cluster.log``.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/6122

**Comment by immarvin** [comment]
there is no python or python3 inside anaconda, 
```
/tmp/ks-script-iwtyik24: /tmp/baz.py: /usr/bin/python3: bad interpreter: No such file or directory
```

only available python is ` /usr/libexec/platform-python`
```
[root@c910f04x27v10 ~]# rpm -qf /usr/libexec/platform-python
platform-python-3.6.8-1.el8.x86_64
[root@c910f04x27v10 ~]# yum info platform-python-3.6.8-1.el8.x86_64
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
xCAT configured yum repository for /install/rhels8.0.0/x86_64/AppStream                            59 MB/s | 5.3 MB     00:00
xCAT configured yum repository for /install/rhels8.0.0/x86_64/BaseOS                               60 MB/s | 2.2 MB     00:00
Installed Packages
Name         : platform-python
Version      : 3.6.8
Release      : 1.el8
Arch         : x86_64
Size         : 41 k
Source       : python3-3.6.8-1.el8.src.rpm
Repo         : @System
From repo    : anaconda
Summary      : Internal interpreter of the Python programming language
URL          : https://www.python.org/
License      : Python
Description  : This is the internal interpreter of the Python language for the system.
             : To use Python yourself, please install one of the available Python 3 packages,
             : for example python36.
```

**Comment by robin2008** [comment]
@xuweibj  Help to verify this when you get new build.

**Comment by xuweibj** [comment]
Verified on Version 2.14.6 (git commit 958ea56e701b17786f0e06a92fe8ea514a3a6723, built Tue Mar 19 06:18:52 EDT 2019)
