### ISSUE TITLE
Need to enter passphrase when install redhat 6.10 on x86_84

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#6119]
MN OS: redhat 8.0
ARCH: x86_64
ISO: rhels6.10-x86_64-install-compute

status: installing

Info from console:
```
Packages completed: 428 of 428
Performing post-installation configuration
Installing bootloader.
Running post-installation scripts
Enter passphrase:
```

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/6120/files

**Comment by xuweibj** [comment]
Tried to verify Version 2.14.6 (git commit 958ea56e701b17786f0e06a92fe8ea514a3a6723, built Tue Mar 19 06:18:52 EDT 2019), got another issue.

After ``booted``, could not ssh to CN:
```
# ssh c910f04x30v13
Connection reset by 10.4.30.13 port 22
```

Got console info:
```
Starting sshd: Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
```

```
# ls -l /etc/ssh/ssh_host_dsa_key
-rw-------. 1 root root 1361 Mar 20 03:28 /etc/ssh/ssh_host_dsa_key
```

**Comment by xuweibj** [comment]
Opened #6133 to trace this ssh issue, so close this issue.
