### ISSUE TITLE
No booted status after install sles11.4 os by redhat7.6

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#6140]
MN: redhat 7.6 x86_64
xCAT version: Version 2.14.6 (git commit 4435960f4a26a87ded6c52732219ddb00d0d6e4d, built Wed Mar 20 06:18:57 EDT 2019)  --- new install

CN: sles11.4 x86
```
#  openssl s_client -quiet -connect 10.4.30.11:3001 -rand /bin/bash <<<"<xcatrequest><command>getpostscript</command></xcatrequest>"
588144 semi-random bytes loaded
write:errno=104
```

CN: sles11.4 ppc64
```
# openssl s_client -quiet -connect 10.4.30.11:3001 -rand /bin/bash <<<"<xcatrequest><command>getpostscript</command></xcatrequest>"
784200 semi-random bytes loaded
write:errno=104
```

**Comment by neo954** [comment]
If run `chdef -t site xcatsslversion=TLSv1`. And restart `xcatd`. It should work. We need to mention this point in xCAT 2.14.6 release notes.

**Comment by xuweibj** [comment]
Verified steps:
1. Install new MN: rhels7.6 xCAT Version 2.14.6 (git commit e97e5fa8f9f139cc04fc4e8ee5d794d5e159c17a, built Thu Mar 21 06:18:57 EDT 2019)
2. Config site table: ``chdef -t site xcatsslversion=TLSv1``
3. restart xcatd
4. Install CN sles11.4 x86 and ppc64

```
# lsdef c910f04x30v13 -i status -c
c910f04x30v13: status=booted
# lsdef c910f02c01p17 -i status -c
c910f02c01p17: status=booted
```
