### ISSUE TITLE
[DEV]Implement documentation changes based on comments in #480 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#615]
I had made some comments to pull request #480 regarding the documentation.  The code and documentation were in the same pull request which is OK but since the code needed to be committed and pulled in for the build, I did not have a chance to make comments to the doc. 

I'd like for the documentation changes mentioned on #480 to get into the latest doc release.

**Comment by gurevichmark** [comment]
Issue fixed by pull request #1050
