### ISSUE TITLE
Kdump does not work on sles and ubuntu.  ONLY works on rhel7

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#6159]
Kdump does not work on sles and ubuntu, even rhel6.  **ONLY** works on rhel7.

Depending on document [Enable kdump Over Ethernet](https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/enable_kdump.html?highlight=kdump), xCAT once supported Kdump in rhel and sles. But depending on the test result of xCAT 20190323.0615 build, ``kdump`` only works on rhel7. 

It seems the document in RTD should be updated.

**Comment by robin2008** [comment]
@cxhong 

Would you like to take a look at  `enablekdump` first on other distro? if there is much effort to make it compatible,  you can update the RTD document to limit our default supporting, and ask user to provide their own `enablekdump` if they want to the feature.

BTW, the document is outdated, in Appendix there are dead url links.

**Comment by hu-weihua** [comment]
has been verified in automation test environment, close this one.
