### ISSUE TITLE
NetworkManager is not installed in Redhat8 diskless compute node

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#6176]
NetworkManager is not installed in Redhat8 diskless compute node.

In real customer scenarios, they can configure static IP in diskless compute node, so NetworkManager should be installed in Redhat8 diskless compute node.

It causes the following auto test cases are failed:

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_secondarynic_updatenode, confignetwork_disable_set_to_yes, confignetwork_disable_set_to_1, confignetwork_niccustomscripts, confignetwork_vlan_false, confignetwork_bond_false, confignetwork_static_installnic, confignetwork_vlan_eth0, confignetwork_bond_eth2_eth3, confignetwork_2eth_bridge_br0

**Comment by zet809** [comment]
hi, @hu-weihua , can this issue be covered by automation? If so, it is passed and can we close this issue? Thx!

**Comment by hu-weihua** [comment]
Have been verified in automation test environment.
