### ISSUE TITLE
[Customer] add support for switched (managed) pdu

### ISSUE THREAD

**Issue by dletai** [xcat2/xcat-core#62]
I'd like to have switched PDUs integrated with xcat, to enable power on/off and outlet load monitoring beyond/in addition to ipmi capabilities.
I believe the base functionality already exists in the switch and switches tables - the tables themselves seem adequate, just have to standardize naming convention for the "interface".

The real work I think, is probably in integrating the specific mibs/snmp capabilities of each pdu with the rpower and possibly renergy/nodestat commands.

The switchtype attribute seems to be the key - how can I create one for IBM switched pdus e.g. DPI PDUs, and let rpower (or a new command) use the info?

**Comment by daniceexi** [comment]
xCAT does not have plan to support PDU. 

In the xCAT 2.10, now we have the switch object type, so that you can define the pdu as a switch object. 

If you want your node can be managed both by ipmi and pdu, you cannot use rpower command for both of them. You have to create a new command to handle request that power control the node with pdu instead of ipmi.

**Comment by mattaezell** [comment]
This feature is also requested for the CORAL systems

**Comment by daniceexi** [comment]
Is there any this kind of PDU that xcat team can use for development?

**Comment by whowutwut** [comment]
@daniceexi  I can check the PDUs that we have in our frames, it looks like they can be connected, but need to investigate.

**Comment by daniceexi** [comment]
@whowutwut Good. Someone can take some investigation first. Is this PDU management required by Coral?

**Comment by mattaezell** [comment]
> Is this PDU management required by Coral?

With all the BMC issues we've been having, I would say yes, this will be required for CORAL to be successful.  We can worry about how to exactly manage the PDUs that we will get later - what I think is important for now is setting up the framework for how this will work in xCAT.

In the _nodehm_ table, should the 'power' column allow a comma-separated list of management plugins?  Should we add a new _hardpower_ column instead?  Then modify rpower to accept commands like:
`rpower cn01 hardoff`
`rpower cn01 hardreset`
or a flag to represent "hard" commands
`rpower -h cn01 off`

**Comment by dletai** [comment]
Don't forget each node has dual power, and conservative links are
      to 2 different PDUs - that means any rpower hardxxx would have to
      control 2 ports - 1 on each pdu.
    
    
    On 15/12//2016 17:41, Matt Ezell wrote:
    
    
      
        Is this PDU management required by Coral?
      
      With all the BMC issues we've been having, I would say yes,
        this will be required for CORAL to be successful. We can worry
        about how to exactly manage the PDUs that we will get later -
        what I think is important for now is setting up the framework
        for how this will work in xCAT.
      In the nodehm table, should the 'power' column allow
        a comma-separated list of management plugins? Should we add a
        new hardpower column instead? Then modify rpower to
        accept commands like:
        rpower cn01 hardoff
        rpower cn01 hardreset
        or a flag to represent "hard" commands
        rpower -h cn01 off
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xcat2/xcat-core","title":"xcat2/xcat-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xcat2/xcat-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mattaezell in #62: \u003e Is this PDU management required by Coral?\r\n\r\nWith all the BMC issues we've been having, I would say yes, this will be required for CORAL to be successful.  We can worry about how to exactly manage the PDUs that we will get later - what I think is important for now is setting up the framework for how this will work in xCAT.\r\n\r\nIn the _nodehm_ table, should the 'power' column allow a comma-separated list of management plugins?  Should we add a new _hardpower_ column instead?  Then modify rpower to accept commands like:\r\n`rpower cn01 hardoff`\r\n`rpower cn01 hardreset`\r\nor a flag to represent \"hard\" commands\r\n`rpower -h cn01 off`"}],"action":{"name":"View Issue","url":"https://github.com/xcat2/xcat-core/issues/62#issuecomment-267359487"}}}

**Comment by cxhong** [comment]
we discussed this on the team meeting today.  xCAT will provide few commands to manage the PDU.
1) add node attribute  to have pdu information which contains pduname and outlet number
   pdu=pdu1:1, pdu2:1
2) rpower cn01 pduoff    ---- will power off outlet 1 off for pdu1 and pdu2  in this case
3) rpower cn01 pduon     ---- will power on outlet 1 on for pdu1 and pdu2 in this case
4) rpower cnm01 pdustat  --- will show status of outlet 1 for pdu1 and pdu2 in this case

let us know if there are something else we should provide.

**Comment by dletai** [comment]
I don't think pdustat should be part of just rpower - logically it belongs to nodestat or perhaps rvitals, as that's where any stats of the node are expected to show.

BTW, I can perform tests on our current PDUs, but unfortunately our cluster is not connected to the internet, so I can't provide direct access to it.

**Comment by hu-weihua** [comment]
@dletai , thanks for your advice, it make sense. 

I think your PDUs should support SNMP. Could you help to collect your produce's MIB for us, we appreciate it very much. If there is some sensitive information, using XXXX to replace it is ok. thanks.

      yum -y install net-snmp-utils
      snmpwalk -v<2c> -c<public> -mALL <pduip> <xxxxmib>

**Comment by dletai** [comment]
Attached the snmpwalk result
[pdu.snmp.txt](https://github.com/xcat2/xcat-core/files/745856/pdu.snmp.txt)

This is the corresponding mib file
[ibmdpi_v01.3_1.mib.txt](https://github.com/xcat2/xcat-core/files/745858/ibmdpi_v01.3_1.mib.txt)

**Comment by hu-weihua** [comment]
@dletai , thanks for your information, it's helpful.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2481
