### ISSUE TITLE
Support CUDA 10.1 in xCAT

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#6212]
For cuda10.1, the "Memory hotadd request" section shall be commented out in /etc/udev/rules.d/40-redhat.rules.

```
## Memory hotadd request
#SUBSYSTEM!="memory", ACTION!="add", GOTO="memory_hotplug_end"
#PROGRAM="/bin/uname -p", RESULT=="s390*", GOTO="memory_hotplug_end"
#
#ENV{.state}="online"
#PROGRAM="/bin/systemd-detect-virt", RESULT=="none", ENV{.state}="online_movable"
#ATTR{state}=="offline", ATTR{state}="$env{.state}"
#
#LABEL="memory_hotplug_end"
```

**Comment by kcgthb** [comment]
Only for POWER 9
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#power9-setup

**Comment by zet809** [comment]
The PR https://github.com/xcat2/xcat-core/pull/6238 fix the cuda10.1.x setup issue on rh7.6, close this issue as the PR is merged.
