### ISSUE TITLE
additional ethernet interface not being configured

### ISSUE THREAD

**Issue by aaronhcarr** [xcat2/xcat-core#6217]
I've added an additional ethernet interface to compute nodes.

[root@hpcmaster ~]# lsdef -t node -o gpu001
Object name: gpu001
    arch=x86_64
    bmc=172.16.4.50
    chain=runcmd=bmcsetup
    currchain=boot
    currstate=boot
    groups=gpu,all
    ip=172.16.0.50
    mac=e4:43:4b:55:df:40
    mgt=ipmi
    netboot=xnba
    nicaliases.bmc=gpu001.dracnet
    nicaliases.p3p1=gpu001.ibnet
    nicips.bmc=172.16.4.50
    nicips.p3p1=172.16.8.50
    nicnetworks.bmc=dracnet
    nicnetworks.p3p1=ibnet
    nictypes.bmc=bmc
    nictypes.p3p1=Ethernet
    os=rhels7.5
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics,hardeths

It's not setting the ip address on p3p1.

I see in the /var/log/xcat/computes.log this line:

Apr 10 12:16:49 gpu001 network: INFO  Determining IP information for p3p1... failed.

The address is defined both in /etc/hosts and in dns.

[root@hpcmaster ~]# cat /etc/hosts|grep gpu001-p3p1
172.16.8.50 gpu001-p3p1 gpu001.ibnet

[root@hpcmaster ~]# nslookup gpu001.ibnet
Server:         127.0.0.1
Address:        127.0.0.1#53

gpu001.ibnet    canonical name = gpu001-p3p1.ibnet.
Name:   gpu001-p3p1.ibnet
Address: 172.16.8.50

What is going wrong here?

EDIT:
To add for clarity...

The p3p1 interfaces are Mellanox 100Gbe cards.  (Mellanox OFED 4.5 is installed, but not required for pure ethernet function)

In the ifcfg-p3p1 files it says BOOTPROTO=dhcp

If I configure the interfaces manually, they work fine.

I added the confignics postscript.

This evening i saw something else.  Should I maybe be using the "confignetwork -s" postscript instead?

**Comment by immarvin** [comment]
hi @bybai , would you please take a look?thx

**Comment by bybai** [comment]
Hi @aaronhcarr,
Sorry for that.  Could you give use more information?
What is your xCAT version?
Could you try to execute  `updatenode gpu001 -P confignetwork` on your xCAT management node try to work around the problem and gave us the output?
If you want to configure both static install NIC IP "172.16.0.50" and p3p1, you can execute `updatenode gpu001 -P "confignetwork -s"` on xCAT management node.

**Comment by aaronhcarr** [comment]
I will try that first thing in the morning and let you know.

ip addresses are already static.  I configured hardeths, so the em1 interface is already static.

**Comment by aaronhcarr** [comment]
In running the command
updatenode gpu001 -p "confignetwork -s"

All it does it spit out the help menu for updatenode.

**Comment by aaronhcarr** [comment]
I went ahead and added it to the node as a postscript:
chdef gpu001 -p postscripts="confignetwork -s"

The re-installed the node.
nodeset gpu001 osimage

After install, it looks good.
[root@gpu001 ~]# ifconfig
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.0.50  netmask 255.255.252.0  broadcast 172.16.3.255
        inet6 fe80::e643:4bff:fe55:df40  prefixlen 64  scopeid 0x20<link>
        ether e4:43:4b:55:df:40  txqueuelen 1000  (Ethernet)
        RX packets 1304993  bytes 1974073422 (1.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 253807  bytes 17603374 (16.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 390  bytes 21190 (20.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 390  bytes 21190 (20.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

p3p1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.8.50  netmask 255.255.252.0  broadcast 172.16.11.255
        inet6 fe80::9a03:9bff:fe7b:f5aa  prefixlen 64  scopeid 0x20<link>
        ether 98:03:9b:7b:f5:aa  txqueuelen 1000  (Ethernet)
        RX packets 5  bytes 1710 (1.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 1016 (1016.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


One final question.

Can I add that chdef to the osimage category so that all nodes of that type will execute that action?

chdef -t osimage -o rhels7.5-x86_64-install-gpu -p postscripts="confignetwork -s"

**Comment by bybai** [comment]
Hi @aaronhcarr,
Answer your questions:
1. You can use ` chdef -t osimage -o rhels7.5-x86_64-install-gpu -p postscripts="confignetwork -s"`, so that all nodes of this type will execute this action.
2.  In `updatenode gpu001 -p "confignetwork -s"`, you should use `-P` instead of `-p`.

Have a fun with xCAT!

**Comment by bybai** [comment]
Hi @aaronhcarr,
Since this issue is resolved, I will close this one, if you hit new issue, you can a new issue. Thanks.
