### ISSUE TITLE
confignetworks -s not creating ifcfg-* files -  xCAT 2.14.6 RHEL6.10

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#6226]
Trying to convert install nic to static addressing by running confignetwork -s as postscript but having problems. Node def:

```
[root@FServ01 ~]# lsdef -t node ws08
Object name: ws08
    arch=x86_64
    cons=nuc
    currstate=netboot rhel6.10-x86_64-compute
    groups=all,compute
    installnic=eth0
    interface=eth0
    mac=94:c6:91:1d:82:08
    mgt=nuc
    monserver=172.16.10.12
    netboot=xnba
    nfsserver=172.16.10.12
    nicextraparams.eth0=DHCPPROTO=none
    nicips.eth0=172.16.40.28
    nictypes.eth0=Ethernet
    os=rhel6.10
    postbootscripts=otherpkgs
    primarynic=eth0
    profile=compute
    provmethod=rhel610
    routenames=NUC
    status=netbooting
    statustime=04-15-2019 07:55:08
    tftpserver=172.16.10.12
    updatestatus=synced
    updatestatustime=04-11-2019 07:17:57
    xcatmaster=fserv01
```
After node boots up, interface is still DHCP.

```
[root@ws08 Desktop]# cat /etc/sysconfig/network-scripts/ifcfg-eth0 
DEVICE=eth0
BOOTPROTO=dhcp
HWADDR=94:c6:91:1d:82:08
ONBOOT=yes
```

Running /xcatpost/confignetworks -s produces:

```
[root@ws08 xcatpost]# ./confignetwork -s
[E]:Error: Can not determine proper install nic.
[I]: NetworkManager is active
[I]: service network stop
[I]: back up /etc/sysconfig/network-scripts to /etc/sysconfig/network-scripts.xcatbak
[I]: There is no other nic device to configure.
```

**Comment by bybai** [comment]
Hi @kjhee43,
I noticed 172.16.40.28 was your install NIC ip;
Install NIC does not need to be defined in `nics` table. `ip=172.16.40.28` in node definition is enough.

Could you have a try to change your node definition using this command:
```
chdef ws08 nicextraparams.eth0= nicips.eth0= nictypes.eth0= ip=172.16.40.28
```
After the node definition is changed, the node definition is like:
```
[root@FServ01 ~]# lsdef -t node ws08
Object name: ws08
    arch=x86_64
    cons=nuc
    currstate=netboot rhel6.10-x86_64-compute
    groups=all,compute
    installnic=eth0
    interface=eth0
    mac=94:c6:91:1d:82:08
    mgt=nuc
    monserver=172.16.10.12
    netboot=xnba
    nfsserver=172.16.10.12
    ip=172.16.40.28                            ----------------> this is the install NIC IP
    os=rhel6.10
    postbootscripts=otherpkgs
    primarynic=eth0
    profile=compute
    provmethod=rhel610
    routenames=NUC
    status=netbooting
    statustime=04-15-2019 07:55:08
    tftpserver=172.16.10.12
    updatestatus=synced
    updatestatustime=04-11-2019 07:17:57
    xcatmaster=fserv01
```
Since your node is deployed already, you can use `updatenode` to configure static IP:
```
updatenode ws08 -P "confignetwork -s"
```

**Comment by kjhee43** [comment]
@by-bai, I made the changes as described but it still doesn't work( I had to use ws04 for the test but same premise) 
```

[root@FServ01 a]# lsdef -t node ws04
Object name: ws04
    arch=x86_64
    cons=nuc
    currstate=netboot rhel6.10-x86_64-compute
    groups=all,compute
    installnic=eth0
    interface=eth0
    ip=172.16.40.24
    mac=94:c6:91:1d:81:eb
    mgt=nuc
    monserver=172.16.10.12
    netboot=xnba
    nfsserver=172.16.10.12
    os=rhel6.10
    postbootscripts=otherpkgs
    postscripts=confignetwork -s
    primarynic=eth0
    profile=compute
    provmethod=rhel610
    routenames=NUC
    status=netbooting
    statustime=04-16-2019 03:24:55
    tftpserver=172.16.10.12
    updatestatus=failed
    updatestatustime=04-15-2019 05:50:12
    xcatmaster=fserv01

I then rebooted ws04 and the node still doesn't get a static IP.
```
[root@ws04 network-scripts]# uptime
 07:28:20 up 3 min,  1 user,  load average: 0.01, 0.02, 0.00
[root@ws04 network-scripts]# 
[root@ws04 network-scripts]# cat /etc/sysconfig/network-scripts/ifcfg-eth0 
DEVICE=eth0
BOOTPROTO=dhcp
HWADDR=94:c6:91:1d:81:eb
ONBOOT=yes
```


```

**Comment by bybai** [comment]
Hi @kjhee43,
I am sorry to hear that. 

I find `postscripts` does not contain `default scripts` in your node `ws04` definition.  The correct postscripts is `postscripts=syslog,remoteshell,syncfiles,confignetwork -s`.

I noticed you used customized osimage, I tried  default diskless RH6.10 using `confignetwork -s`, it can work well. My node  and osimage definitions are as following, you can refer this definition:
```
]# lsdef c910f04x40
Object name: c910f04x40
    arch=x86_64
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=netboot rhels6.10-x86_64-compute
    groups=all
    ip=10.4.40.1
    mac=34:40:b5:b9:d6:4f
    mgt=ipmi
    netboot=xnba
    os=rhels6.10
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignetwork -s
    profile=compute
    provmethod=rhels6.10-x86_64-netboot-compute
    serialport=0
    serialspeed=115200
    status=booted
    statustime=04-16-2019 23:45:40
    updatestatus=synced
    updatestatustime=04-16-2019 23:08:26

]# lsdef -t osimage rhels6.10-x86_64-netboot-compute
Object name: rhels6.10-x86_64-netboot-compute
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels6.10-x86_64
    osname=Linux
    osvers=rhels6.10
    otherpkgdir=/install/post/otherpkgs/rhels6.10/x86_64
    permission=755
    pkgdir=/install/rhels6.10/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels6.10/x86_64/compute
```
You can look into compute node `ws04` log to debug, for example, the log is in management node `/var/log/xcat/computes.log*`

I also found in your above log `NetworkManager` is active, but in xCAT default RH6.10 compute node, it does not use NetworkManager, `NetworkManager` support is in latest code. 
```
[I]: NetworkManager is active
[I]: service network stop
```
If you use `network` service in your `ws04`, you do not need use latest code. 
If you use `NetworkManager` in the compute node, you can download the following 3 files to overwrite the old ones under xCAT management node `/install/postscripts` directory. You can use `service network status` and `service NetworkManager status` on `ws04` to confirm it.
```
https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT/postscripts/configeth
https://raw.githubusercontent.com/xcat2/xcat-core/2.14/xCAT/postscripts/nicutils.sh
https://raw.githubusercontent.com/xcat2/xcat-core/2.14/xCAT/postscripts/confignetwork
```

**Comment by bybai** [comment]
Hi @kjhee43, any progress about this issue?

**Comment by kjhee43** [comment]
@bybai, I dont have an update yet. What is your recommendation on network Manager? I can remove it from the image if necessary?

**Comment by bybai** [comment]
Hi @kjhee43,
If `NetworkManager` is as dependencies by other software, you can just stop it in compute node, you can add the following 2 lines in FServ01 `/install/postscripts/confignetwork`  line 27, then run `updatenode ws04 "confignetwork -s"` can work your problem. It is easiest way.
```
startservice network
stopservice NetworkManager | log_lines info
```
And another way is to remove NetworkManager.
If you do not use NetworkManager on RH6.10 compute node, you can remove it from osimage,  find your pkglist use command `lsdef -t osimage rhel610 -i pkglist`, delete `NetworkManager` from it. Then find the rootimgdir and remove `NetworkManager`, `packimage` image and `rinstall` compute node:
```
lsdef -t osimage rhels6.10-x86_64-netboot-compute -i rootimgdir
Object name: rhels6.10-x86_64-netboot-compute
    rootimgdir=/install/netboot/rhels6.10/x86_64/compute

yum -y remove --installroot=/install/netboot/rhels6.10/x86_64/compute/rootimg/ NetworkManager
packimage rhels6.10-x86_64-netboot-compute
rinstall c910f04x40 osimage=rhels6.10-x86_64-netboot-compute
```

**Comment by kjhee43** [comment]
I removed Network Manager from my package list as well as Network-manager-gnome. I rebuilt the image from scratch and added the default post scripts to the image definition as well as the postscrits "tab" file. I then rebooted a node and unfortunately its still using DHCP.

**Comment by bybai** [comment]
Could you try to use confignetworks,configeth and nicutils.sh from master branch? I fix the issue in master branch.

**Comment by kjhee43** [comment]
@bybai 

From here?

https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT/postscripts/configeth
https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT/postscripts/nicutils.sh
https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT/postscripts/confignetwork

**Comment by bybai** [comment]
Yes.

**Comment by bybai** [comment]
I think the latest code can work, if you still have problems, you can contact @cxhong , thanks.
