### ISSUE TITLE
2.14.6的nodeset无法正常生成RHEL 6的/tmp/partitionfile

### ISSUE THREAD

**Issue by DeLaJSR** [xcat2/xcat-core#6231]
2.14.6生成的autoinst文件中使用了RHEL 6中并不存在的base64decode命令，因此partitionfile文件不会生效，而2.14.5实现同样功能是通过python，工作正常，建议修改回原有版本

如下例子，sghwaw001文件是2.14.5创建的，sghwaw001.bak是2.14.6创建的

```
[root@sghwmn01 autoinst]# diff sghwaw001 sghwaw001.bak 
........
648c648
< python -c 'import base64; print base64.b64decode(open("/tmp/partitionfile.enc","rb").read())' >/tmp/partitionfile
---
> base64decode</tmp/partitionfile.enc >/tmp/partitionfile
```

**Comment by immarvin** [comment]
hi @DeLaJSR , the fix https://github.com/xcat2/xcat-core/pull/6233  has been merge.  please apply the `xCAT-server/share/xcat/install/scripts/pre.rh` in the PR to check whether it fix your issue.

thanks
