### ISSUE TITLE
"confignetwork -s" doesn't configure aliases on installnic

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6246]
When using the `confignetwork` postscript with the `-s` option, which is supposed to configure  both the install NIC and the other NICs, NIC aliases are not configured (at least on the install NIC).

When `confignetwork` is used without `-s` (which is said to "configure nics except install nic"), the NIC aliases are properly configured.

https://github.com/xcat2/xcat-core/blob/396796922645be300f75951d1210d1a1a860fab5/xCAT/postscripts/confignetwork#L9-L12

NIC aliases are defined in the `nics` table, like this:
```
# lsdef sh-hn04 -i nicips.em1
Object name: sh-hn04
    nicips.em1=10.10.0.4|10.11.0.96
```

**Comment by immarvin** [comment]
hi @bybai ,would you please take a look at this?

**Comment by bybai** [comment]
Hi @kcgthb,
`confignetwork -s` is aim to configure the compute node install NIC provision IP and others NICs IP configured in `nics` table.
If you want to configure  aliases for install NIC, suggest you configure install NIC provision IP and its alias IP into `nics` table. and using `confignetwork` without `-s` to configure all IPs.

If the install NIC have multiple IPs including provision IP, we consider its alias IP as secondary IP, so we use `nics` table and `confignetwork` without `-s` to configure all IPs.

Based on you description,  `confignetwork` works as design, its comments confuse you "install nic ip" with "install nic provision IP", thanks your pointing about this, we need to updates the comments and docs.

**Comment by kcgthb** [comment]
Hi @bybai 
I'm not sure I understand the difference between `confignetwork` and `confignetwork -s` very well. 
I'm trying to deploy a node which has an IP alias on its deployment NIC, as well as other NICs that we need to be configured during deployment:
```
Object name: sh-hn04
    nicaliases.em2=sh-hn04
    nicaliases.bmc=sh-hn04
    nicaliases.ib0=sh-hn04
    nicextraparams.em1=MTU=9000
    nicextraparams.em2=MTU=9000
    nicips.em1=10.10.0.4|10.11.0.96
    nicips.em2=10.102.3.104
    nicips.bmc=10.11.0.4
    nicips.ib0=10.9.0.4
    nicnetworks.em1=net_int|net_ipmi
    nicnetworks.em2=net_sunet
    nicnetworks.bmc=net_ipmi
    nicnetworks.ib0=net_ib_100
    nictypes.em1=ethernet
    nictypes.em2=ethernet
    nictypes.bmc=bmc
    nictypes.ib0=infiniband
```

Right now, the only way I found to have all IP addresses configured during deployment is to have `confignetwork`twice in the postscripts list:
```
Object name: sh-hn04
    postscripts=syslog,remoteshell,syncfiles,otherpkgs,servicenode,confignetwork,confignetwork -s,hardeths,setroute add,setupntp
```

If I only use `confignetwork`, I get both IPs on `em1`, but `em2` doesn't get configured. If I use only `confignetwork -s`, `em2` gets configured, but `em1` doesn't get its alias IP set.

**Comment by robin2008** [comment]
@bybai I think there must be some issue if just as @kcgthb pointed.

> Right now, the only way I found to have all IP addresses configured during deployment is to have confignetworktwice in the postscripts list:

`confignetwork -s` should do all tasks in `confignetwork`, and in addition, it will configure install nic as static (including the IP and hostname)

**Comment by bybai** [comment]
@kcgthb, thanks your pointing about it, let me reproduce it in my environment.

**Comment by bybai** [comment]
Hi @kcgthb,
 This issue is fixed in confignetwork need run twice when install NIC has multiple IPs #6261.
You can have a try about it, thanks.

**Comment by kcgthb** [comment]
Thanks @bybai!
I'll give it a try.
