### ISSUE TITLE
xCAT 2.14.5 xcatpostinit1 service can't turn itself off after a sucessfully first run on RHEL 6.10

### ISSUE THREAD

**Issue by DeLaJSR** [xcat2/xcat-core#6249]
xcatpostinit1 service can't turn itself off after a sucessfully first run on RHEL 6.10(xCATd has received install succesful information, and there is chkconfig xcatpostinit1 off command in correlative scripts, but seems not working) , cause xcatpostinit1 try to start on every booting

And if management node's IP is unreachable, starting xcatpostinit1 will hang on console, cause subsequent services don't start, but the node can be connected via ssh because sshd has started before xcatpostinit1, makes this issue hard to be discovered(I discover this via wcons)

**Comment by immarvin** [comment]
hi @DeLaJSR , what is the `lsdef -t site -o clustersite -i nodestatus,runbootscripts`

**Comment by DeLaJSR** [comment]
[root@sghwmn01 ~]# lsdef -t site -o clustersite -i nodestatus,runbootscripts
Object name: clustersite

**Comment by immarvin** [comment]
this issues is rooted from that `systemctl` is used instead of the wrapper function `stopservice/startservice`  in new `setupntp` postscript,  but `systemd` is only available  for rh7+.

So let's add the check for systemd availability in line #256 if we do not want to refine `setupntp` to use the wrapper functions. @neo954 @robin2008  
```
255     # Handle chronyd here,
256     if (-f "/usr/sbin/chronyd") {
257         send_msg(\%request, 0, "Will configure chronyd instead.");
258
259         my $cmd = "/install/postscripts/setupntp " .
260             join(' ', split(',', $ntp_servers));
261         send_msg(\%request, 0, "Calling ... " . $cmd);
262
263         my $result = xCAT::Utils->runcmd($cmd, 0);
264         if ($::RUNCMD_RC != 0) {
265             send_msg(\%request, 1, "Error from command: $cmd\n    $result");
266             return 1;
267         }
268
269         send_msg(\%request, 0, "Daemon chronyd configured.");
270
271         # Cannot find a better way other than use goto statement :-/
272         goto HANDLE_MAKENTP_A;
273     }
274
```

**Comment by immarvin** [comment]
hi @DeLaJSR , in the scenario` management node's IP is unreachable` , please disable the `xcatpostinit1` service manually.

**Comment by DeLaJSR** [comment]
@immarvin 

**On a compute node**
[root@sghwaw006 ~]# service xcatpostinit1 start
[root@sghwaw006 ~]# chkconfig --list xcatpostinit1
xcatpostinit1   0:off   1:off   2:on    3:on    4:on    5:on    6:off
[root@sghwaw006 ~]# service xcatpostinit1 start
[root@sghwaw006 ~]# chkconfig --list xcatpostinit1
xcatpostinit1   0:off   1:off   2:on    3:on    4:on    5:on    6:off
[root@sghwaw006 ~]#

**At the same time, on Management Node**
[root@sghwmn01 x86_64]# tail -f /var/log/xcat/cluster.log
Apr 24 13:50:40 sghwmn01 xcat[10417]: INFO  xcatd: install monitor received a connection request from 192.168.180.6
Apr 24 13:50:40 sghwmn01 xcat[10417]: INFO  xcatd: 192.168.180.6 is matched with node sghwaw006
Apr 24 13:50:40 sghwaw006 xcat: INFO  ready
Apr 24 13:50:40 sghwaw006 xcat: INFO  done
Apr 24 13:50:40 sghwmn01 xcat[10417]: INFO  xcat.updatestatus - sghwaw006: changing status=booted
Apr 24 13:50:40 sghwmn01 xcat[10417]: INFO  xcatd: finish a connection request for sghwaw006 from 192.168.180.6
Apr 24 13:50:53 sghwmn01 xcat[10417]: INFO  xcatd: install monitor received a connection request from 192.168.180.6
Apr 24 13:50:53 sghwmn01 xcat[10417]: INFO  xcatd: 192.168.180.6 is matched with node sghwaw006
Apr 24 13:50:53 sghwaw006 xcat: INFO  ready
Apr 24 13:50:53 sghwaw006 xcat: INFO  done
Apr 24 13:50:53 sghwmn01 xcat[10417]: INFO  xcat.updatestatus - sghwaw006: changing status=booted
Apr 24 13:50:53 sghwmn01 xcat[10417]: INFO  xcatd: finish a connection request for sghwaw006 from 192.168.180.6

**Comment by immarvin** [comment]
@DeLaJSR , this is a designed behavior, some customers request xCAT that the status of the nodes can be updated during normal reboot process

**Comment by DeLaJSR** [comment]
@immarvin So how can I force xcatpostinit1 to turn itself off after the first boot, via some settings in some tables?

/opt/xcat/xcatinstpost
...
155 if [[ $OSVER == ubuntu* ]]; then
    156     if [[ ! "$RUNBOOTSCRIPTS" =~ ^(1|yes|y)$ ]]; then
    157         update-rc.d -f xcatpostinit1 remove
    158     fi
    159     if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
    160         msgutil_r "$MASTER_IP" "debug" "update-rc.d -f xcatpostinit1 remove" "/var/log/xcat/xcat.log" "xcat.xcatinstallpost"
    161     fi
    162 else
    163     if [[ ! "$RUNBOOTSCRIPTS" =~ ^(1|yes|y)$ ]] && [[ ! "$NODESTATUS" =~ ^(1|yes|y)$ ]]; then
    164         **chkconfig xcatpostinit1 off**
    165         if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
    166             msgutil_r "$MASTER_IP" "debug" "service xcatpostinit1 disabled" "/var/log/xcat/xcat.log" "xcat.xcatinstallpost"
    167         fi
    168     fi
    169 
    170 fi

**Comment by immarvin** [comment]
hi @DeLaJSR , try `chdef -t site -o clustersite nodestatus="n" runbootscripts="n"` and provision the node with `rinstall`

**Comment by DeLaJSR** [comment]
@immarvin thanks

so the link https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/post_script.html?highlight=runbootscripts

>  xCAT, by default, for diskful installs only runs the postbootscripts on the install and not on reboot. In xCAT a site table attribute runbootscripts is available to change this default behavior. If set to yes, then the postbootscripts will be run on install and on reboot.

is not correct? it seems their default are YES now

**Comment by immarvin** [comment]
@DeLaJSR , the description is correct,  the `postbootscripts` will not run on normal reboot unless `site.runbootscripts` is yes. The default  value for `nodestatus` is `yes`.

**Comment by DeLaJSR** [comment]
@immarvin Thanks, I understand

BTW, "by **default**, for diskful installs only runs the postbootscripts on the install and **not on reboot**." is not correct XD

**Comment by immarvin** [comment]
hi @immarvin ,  it mentions `postbootscripts ` instead of  `xcatpostinit1` service, so it is correct:)
