### ISSUE TITLE
xCAT version 2.14.6 is having trouble with cumulusztp  - ztp configuration failed

### ISSUE THREAD

**Issue by kkvtran** [xcat2/xcat-core#6268]
I discussed the issue with Casandra.  She said the problem are in documulusdiscovery, cumulusztp and configinterface where the value of XCATMASTER is <xcatmaster-IP>:80.  It should only include the xcatmaster-IP.

**Comment by cxhong** [comment]
when Kim ran ZTP process on the cumulus switches, the `/var/log/autoprovision` file had issues with:
````
xcat.documulusdiscovery: no response from 192.168.192.2:80, wait for 6 seconds
no response from 192.168.192.2:80, wait for 6 seconds
xcat.documulusdiscovery: no response from 192.168.192.2:80, wait for 6 seconds
xcat.documulusdiscovery: Sending the discovery packet to xCAT (192.168.192.2:80:3001) [ RETRY= 1 ]  ...
2019/04/24 19:00:07 socat[2414] E UDP: wrong number of parameters (3 instead of 2)
no response from 192.168.192.2:80, wait for 6 seconds
xcat.documulusdiscovery: no response from 192.168.192.2:80, wait for 6 seconds
no response from 192.168.192.2:80, wait for 6 seconds
xcat.documulusdiscovery: no response from 192.168.192.2:80, wait for 6 seco 
````
The xCAT master is `192.168.192.2:80` instead of `192.168.192.2`  and ztp url also showed master with port number:
```
root@cumulus:/tmp# ztp -s

ZTP INFO:

State                                                   disabled
Version                                                 1.0
Result                                                  success
Date                                                    Thu Apr 25 20:14:03 2019 UTC
Method                                                  ZTP DHCP
URL                                                     http://192.168.192.2:80/install/postscripts/cumulusztp
```
This URL is picked from DHCP responds /etc/dhcp/dhcpd.conf on xCAT MN:
```
option cumulus-provision-url "http://192.168.192.2:80/install/postscripts/cumulusztp";
```
I can able to recreate this issue on our test system.

@immarvin ,  I think this issue is cause by your fixes  #5757,  for the cumulus url, we don't need port number, do you recall why you add http port here?

**Comment by cxhong** [comment]
maybe default http port changed from 80 to something else, is this will failed? if this case, we need to modify postscript for getting MASTER ip address
```
xCAT/postscripts/configinterface:    MASTER=$(cat /var/lib/dhcp/dhclient.eth0.leases|sed -n 's/.*cumulus-provision-url.*http:\/\+\([^\/]\+\)\/.*/\1/p'|tail -1)
xCAT/postscripts/cumulusztp:server_ip="$(grep 'cumulus-provision-url' < <(get_last_lease eth0) | awk -F/ '{print $3}')"
xCAT/postscripts/documulusdiscovery:XCATMASTER=$(cat /var/lib/dhcp/dhclient.eth0.leases |grep cumulus-provision-url|tail -1|awk -F/ '{print $3}')
```

**Comment by immarvin** [comment]
hi @cxhong , yes, the http port number `:80` is mandatory in `cumulus-provision-url ` .  The port part `:80` should be striped when extracting `XCATMASTER ` and `MASTER` from the lease files in the scripts you provided above

**Comment by cxhong** [comment]
well, I don't think this is mandatory,  there was no port number for cumulus-provision-url before your PR.
anyway, I will test it out.
