### ISSUE TITLE
[OpenBMC] rspconfig powersupplyredundancy API changed

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/xcat-core#6270]
Looks like the path the the `rspconfig <node> powersupplyredundancy` setting has changed.

Firmware:
```
r310n18-adm: BMC Firmware Product: ibm-v2.3-476-g2d622cb-r32-0-g9973ab0 (Active)*
r310n18-adm: HOST Firmware Product: IBM-witherspoon-ibm-OP9-v2.0.14-2.6-prod (Active)*
r310n18-adm: HOST Firmware Product: -- additional info: buildroot-2018.05.1-9-gc99f2ee
r310n18-adm: HOST Firmware Product: -- additional info: capp-ucode-p9-dd2-v4
r310n18-adm: HOST Firmware Product: -- additional info: hcode-hw031319a.op920
r310n18-adm: HOST Firmware Product: -- additional info: hostboot-binaries-hw031319a.op920
r310n18-adm: HOST Firmware Product: -- additional info: hostboot-c00d44a-pc8e37c7
r310n18-adm: HOST Firmware Product: -- additional info: linux-4.17.12-openpower1-p88e50e5
r310n18-adm: HOST Firmware Product: -- additional info: machine-xml-2d9c9f0
r310n18-adm: HOST Firmware Product: -- additional info: occ-8fa3854
r310n18-adm: HOST Firmware Product: -- additional info: op-build-v2.0.14-8-g91bf747
r310n18-adm: HOST Firmware Product: -- additional info: petitboot-v1.7.5-p9a906c4
r310n18-adm: HOST Firmware Product: -- additional info: sbe-b6ee17b
r310n18-adm: HOST Firmware Product: -- additional info: skiboot-v6.0.18

```

**xCat** uses: `/xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy/`
for instance: https://github.com/xcat2/xcat-core/blob/master/xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py#L199-L210

This throws:
```
XXXXX: [XXXXX]: Error: 404 Not Found - Requested endpoint does not exist or may indicate function is not supported on this OpenBMC firmware.
```

**now** it seems to be: `/xyz/openbmc_project/control/power_supply_redundancy/`
Example:
```
curl -c cjar -b cjar -k  https://${bmc}/xyz/openbmc_project/control/power_supply_redundancy
{
  "data": {
    "PowerSupplyRedundancyEnabled": false
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

**Comment by gurevichmark** [comment]
This might be related to our discussion here: https://ibm-systems-storage.slack.com/archives/C495B18QZ/p1554239973002500
The thinking was this function was disabled for a specific version of FW. But maybe it was just renamed.

**Comment by gurevichmark** [comment]
Got confirmation in the #openbmc channel: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1556292311071200

**Comment by gurevichmark** [comment]
@xuweibj If you have time, can you fix it ?

**Comment by xuweibj** [comment]
hi @gurevichmark , I discussed little about this issue with @zet809 . We hope we could resolve this easily. 
I think we have 3 solutions:
1. Handle all openbmc version on python
2. Handle new openbmc version on both python and perl
3. Handle all openbmc version on python and perl

I tried to handle all openbmc version, found that for perl the logic is so complex and may trigger other issue. So hope we do not support all openbmc version on perl, how do you think?

**Comment by gurevichmark** [comment]
Yes, Perl logic is very complex and not easy to make changes there. But I do not think many users are using Python yet, so we need to make changes in both places. I talked to Victor about this a little and he felt we should push OpenBMC team to support the old call. If we succeed, and old call is supported, no changes to xCAT will be needed. So for now lets wait a little.

**Comment by gurevichmark** [comment]
More details and slack discussion in https://github.ibm.com/vhu/c910env/issues/685.
It seems that in OP920 FW this setting is read-only. Users will not be allowed to change it.

**Comment by gurevichmark** [comment]
@xuweibj We had a slack discussion today about this issue and here is the summary:

* There will be 2 versions of BMC FW - one for Coral and one for non Coral users. 
* In Coral version, PowerSupplyRedundancy will be disabled by default and users will not be able to change it. 
* In non Coral version, PowerSupplyRedundancy will be enabled by default and users will not be able to change it.
* There might still be users running with older version of BMC FW where old path will work and changes to this attribute is supported.

I added a PR #6282 to handle this change in Perl. Can you work on a similar fix for Python ?

**Comment by xuweibj** [comment]
@gurevichmark Thank you for your help. OK, I will work on it for Python today.

**Comment by immarvin** [comment]
hi @Obihoernchen , seems the fix is in, please try the fix to see whether it clear your issue

**Comment by gurevichmark** [comment]
Closing the issue. Should be in the 2.15 release. Please reopen of needed.
