### ISSUE TITLE
How do I get xCAT db information during %post?

### ISSUE THREAD

**Issue by aaronhcarr** [xcat2/xcat-core#6285]
I've looked through a bunch of scripts in /install/postscripts/, and I don't see how to pull the information.

Specifically, I want to get the bmcuser and bmcpassword from the ipmi table.

I'm doing a custom postscript to configure Dell iDRACs. 

Instead of hard coding it into the script, I'd like the script to get the information directly from the ipmi table.

self=`hostname -s`
idrac_user=`tabdump ipmi|grep ${self}|awk -F , '{print $6}'|sed 's/"//g'`
idrac_password=`tabdump ipmi|grep ${self}|awk -F , '{print $7}'|sed 's/"//g'`

Is there a way to get that during %post?

**Comment by immarvin** [comment]
hi @aaronhcarr , the post(boot)scripts are invoked in a wrapper script called mypostscript(.post), which is generated on the MN and distributed to the CN as a response to an internal xcat request `getpostscript`. The mypostscript(.post) contains 2 parts: all the environment variables required in the postscripts are exported, and the post(boot)scripts are invoked with a wrapper function `run_ps`.

So for you question, I think you need to customized mypostscript.tmpl ,  the steps can be:

1. copy `/opt/xcat/share/xcat/mypostscript/mypostscript.tmpl` to `/install/postscripts/mypostscript.tmpl` on MN
2. add the macro lines to export the expected environment variables to `/install/postscripts/mypostscript.tmpl`:
```
IDRAC_USER=#TABLE:ipmi:$NODE:username#
export IDRAC_USER
IDRAC_PASSWORD=#TABLE:ipmi:$NODE:password#
export IDRAC_PASSWORD
```

the variable `self` you mentioned has already been exported as the variable `NODE`. Then you can refer the variables `IDRAC_USER`, `IDRAC_PASSWORD` and `NODE` in your postscripts



see https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/post_script.html?highlight=mypostscript.tmpl#using-the-mypostscript-template for details.

**Comment by aaronhcarr** [comment]
Ok, so follow up question.

I'm copying /opt/xcat/share/xcat/mypostscript/mypostscript.tmpl to /install/postscripts, adding the ipmi information.

Is that just getting that ipmi information that I need, so that I can call it from another script?

For example: using $IDRAC_USER and IDRAC_PASSWORD from  /install/postscripts/idrac.config ?

Thanks in advance.

**Comment by immarvin** [comment]
yes. You can verify this with `updatenode` before you apply it in provision

**Comment by aaronhcarr** [comment]
I just wanted to be sure I understood the process.

Thank you for the clarification.  Very helpful.

**Comment by immarvin** [comment]
hi @aaronhcarr , please feel free to contact us if any issue on the solution. Please close the ticket if the solutions works well. thanks
