### ISSUE TITLE
[FVT] The postscript confignetwork can create one link aggregation interface only

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#631]
Below are the ``nicdevices`` and ``nictypes`` attributes of node ``c910f02c03p23``.

    [root@c910f02c03p27 ~]# lsdef c910f02c03p23 -i nicdevices,nictypes
    Object name: c910f02c03p23
        nicdevices.bond0=eth2|eth3
        nicdevices.bond1=eth1|eth4
        nictypes.eth4=ethernet
        nictypes.eth2=ethernet
        nictypes.eth3=ethernet
        nictypes.bond0=bond
        nictypes.bond1=bond
        nictypes.eth1=ethernet

Only one link aggregation interface can be defined. All the network adapters belong to the remain link aggregation interfaces are wrongly configured to join the first link aggregation interface.

    # updatenode c910f02c03p23 confignetwork
    c910f02c03p23: xcatdsklspost: updating VPD database
    c910f02c03p23: xcatdsklspost: downloaded postscripts successfully
    c910f02c03p23: Wed Jan 20 06:14:08 EST 2016 Running postscript: confignetwork
    c910f02c03p23: [I]: NetworkManager is inactive.
    c910f02c03p23: [I]: All valid nics and device list:
    c910f02c03p23: [I]: bond0 eth2@eth3
    c910f02c03p23: [I]: bond1 eth1@eth4
    c910f02c03p23: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    c910f02c03p23: configure nic and its device : bond0 eth2@eth3
    c910f02c03p23: [I]: create_bond_interface ifname=bond0 slave_ports=eth2,eth3
    c910f02c03p23: [I]: Pickup xcatnet, "", from NICNETWORKS for interface "bond0".
    c910f02c03p23: [I]: ip link set bond0 down
    c910f02c03p23: [I]: [bond.down] >> 5: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noqueue state DOWN mode DEFAULT
    c910f02c03p23: [I]: [bond.down] >>     link/ether 16:3f:4d:b4:fe:04 brd ff:ff:ff:ff:ff:ff
    c910f02c03p23: [I]: [bond.slavesAft] >> eth1 eth2
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=eth2 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
    c910f02c03p23: ['ifcfg-eth2']
    c910f02c03p23: [I]: >> DEVICE="eth2"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="eth2"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Ethernet"
    c910f02c03p23: [I]: >> SLAVE="yes"
    c910f02c03p23: [I]: >> MASTER="bond0"
    c910f02c03p23: Cannot find device "eth3"
    c910f02c03p23: [I]: ip link set eth3 down
    c910f02c03p23: Device "eth3" does not exist.
    c910f02c03p23: ./nicutils.sh: line 1270: echo: write error: No such device
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=eth3 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
    c910f02c03p23: ['ifcfg-eth3']
    c910f02c03p23: [I]: >> DEVICE="eth3"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="eth3"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Ethernet"
    c910f02c03p23: [I]: >> SLAVE="yes"
    c910f02c03p23: [I]: >> MASTER="bond0"
    c910f02c03p23: [I]: [bond.slavesNew] >> eth1 eth2
    c910f02c03p23: [I]: ip link set bond0 up
    c910f02c03p23: [I]: State of "bond0" was "DOWN" instead of expected "UP". Wait 0 of 200 with interval 1.
    c910f02c03p23: [I]: [ip.link] >> 5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    c910f02c03p23: [I]: [ip.link] >>     link/ether 16:3f:4d:b4:fe:04 brd ff:ff:ff:ff:ff:ff
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=bond0 xcatnet= inattrs=ONBOOT=yes,USERCTL=no,TYPE=Bond,BONDING_MASTER=yes,BONDING_OPTS='mode=802.3ad miimon=100',BOOTPROTO=none,DHCLIENTARGS='-timeout 200'
    c910f02c03p23: ['ifcfg-bond0']
    c910f02c03p23: [I]: >> DEVICE="bond0"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="bond0"
    c910f02c03p23: [I]: >> BONDING_MASTER="yes"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Bond"
    c910f02c03p23: [I]: >> BONDING_OPTS="mode=802.3ad miimon=100"
    c910f02c03p23: [I]: >> DHCLIENTARGS="-timeout 200"
    c910f02c03p23: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    c910f02c03p23: configure nic and its device : bond1 eth1@eth4
    c910f02c03p23: [I]: create_bond_interface ifname=bond0 slave_ports=eth1,eth4
    c910f02c03p23: [I]: Pickup xcatnet, "", from NICNETWORKS for interface "bond0".
    c910f02c03p23: [I]: ip link set bond0 down
    c910f02c03p23: [I]: [bond.down] >> 5: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noqueue state DOWN mode DEFAULT
    c910f02c03p23: [I]: [bond.down] >>     link/ether 16:3f:4d:b4:fe:04 brd ff:ff:ff:ff:ff:ff
    c910f02c03p23: [I]: [bond.slavesAft] >> eth1 eth2
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=eth1 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
    c910f02c03p23: ['ifcfg-eth1']
    c910f02c03p23: [I]: >> DEVICE="eth1"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="eth1"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Ethernet"
    c910f02c03p23: [I]: >> SLAVE="yes"
    c910f02c03p23: [I]: >> MASTER="bond0"
    c910f02c03p23: Cannot find device "eth4"
    c910f02c03p23: [I]: ip link set eth4 down
    c910f02c03p23: Device "eth4" does not exist.
    c910f02c03p23: ./nicutils.sh: line 1270: echo: write error: No such device
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=eth4 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
    c910f02c03p23: ['ifcfg-eth4']
    c910f02c03p23: [I]: >> DEVICE="eth4"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="eth4"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Ethernet"
    c910f02c03p23: [I]: >> SLAVE="yes"
    c910f02c03p23: [I]: >> MASTER="bond0"
    c910f02c03p23: [I]: [bond.slavesNew] >> eth1 eth2
    c910f02c03p23: [I]: ip link set bond0 up
    c910f02c03p23: [I]: [ip.link] >> 5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    c910f02c03p23: [I]: [ip.link] >>     link/ether 16:3f:4d:b4:fe:04 brd ff:ff:ff:ff:ff:ff
    c910f02c03p23: [I]: create_persistent_ifcfg ifname=bond0 xcatnet= inattrs=ONBOOT=yes,USERCTL=no,TYPE=Bond,BONDING_MASTER=yes,BONDING_OPTS='mode=802.3ad miimon=100',BOOTPROTO=none,DHCLIENTARGS='-timeout 200'
    c910f02c03p23: ['ifcfg-bond0']
    c910f02c03p23: [I]: >> DEVICE="bond0"
    c910f02c03p23: [I]: >> BOOTPROTO="none"
    c910f02c03p23: [I]: >> NAME="bond0"
    c910f02c03p23: [I]: >> BONDING_MASTER="yes"
    c910f02c03p23: [I]: >> ONBOOT="yes"
    c910f02c03p23: [I]: >> USERCTL="no"
    c910f02c03p23: [I]: >> TYPE="Bond"
    c910f02c03p23: [I]: >> BONDING_OPTS="mode=802.3ad miimon=100"
    c910f02c03p23: [I]: >> DHCLIENTARGS="-timeout 200"
    c910f02c03p23: [I]: State of "bond0" was "DOWN" instead of expected "UP". Wait 0 of 200 with interval 1.
    c910f02c03p23: Postscript: confignetwork exited with code 0
    c910f02c03p23: Running of postscripts has completed.

Below are the network configuration files for all the four network adapters. As you can see here, all adapters goes to ``bond0``. Which is incorrect.

    # head -n 999 /etc/sysconfig/network-scripts/ifcfg-eth{1,2,3,4}
    ==> /etc/sysconfig/network-scripts/ifcfg-eth1 <==
    DEVICE="eth1"
    BOOTPROTO="none"
    NAME="eth1"
    ONBOOT="yes"
    USERCTL="no"
    TYPE="Ethernet"
    SLAVE="yes"
    MASTER="bond0"

    ==> /etc/sysconfig/network-scripts/ifcfg-eth2 <==
    DEVICE="eth2"
    BOOTPROTO="none"
    NAME="eth2"
    ONBOOT="yes"
    USERCTL="no"
    TYPE="Ethernet"
    SLAVE="yes"
    MASTER="bond0"

    ==> /etc/sysconfig/network-scripts/ifcfg-eth3 <==
    DEVICE="eth3"
    BOOTPROTO="none"
    NAME="eth3"
    ONBOOT="yes"
    USERCTL="no"
    TYPE="Ethernet"
    SLAVE="yes"
    MASTER="bond0"

    ==> /etc/sysconfig/network-scripts/ifcfg-eth4 <==
    DEVICE="eth4"
    BOOTPROTO="none"
    NAME="eth4"
    ONBOOT="yes"
    USERCTL="no"
    TYPE="Ethernet"
    SLAVE="yes"
    MASTER="bond0"

**Comment by neo954** [comment]
The interface name ``bond0`` is hard coded in line 374 of ``confignetwork``.

    374              create_bond_interface ifname=bond0 slave_ports=$base_nic_for_bond

**Comment by neo954** [comment]
This is the version of xCAT used in the testing.

    Version 2.12 (git commit fbd91febf512026bdada2ab10120957b90bf8831, built Mon Jan 18 15:30:50 EST 2016)

**Comment by bybai** [comment]
This defect root cause is duplicate with #636

**Comment by neo954** [comment]
Will close this one.
