### ISSUE TITLE
How to *correctly* change mac address on a node?

### ISSUE THREAD

**Issue by aaronhcarr** [xcat2/xcat-core#6323]
I've read in multiple places that nodechmac is the way to change a mac.

However, I've not yet seen it work.  Using xCAT 2.14.6.

I've received this same error every time.

[root@cs-noles ~]# nodechmac ns10 mac=b0:26:28:24:a9:c6
Error: [cs-noles]: Failed to generate chain string for nodes.

Would "chdef -t node -o ns10 mac=b0:26:28:24:a9:c6" be an acceptable method of changing?

Is there anything that must be done after the change (like makedhcp? or makedns?) , or should it work immediately? 

Thank you.

**Comment by immarvin** [comment]
hi @aaronhcarr , `chdef -t node -o ns10 mac=b0:26:28:24:a9:c6 ` then `makedhcp ns10 `.

**Comment by gurevichmark** [comment]
We should use this issue to either fix `nodechmac` command or remove it from our docs.

**Comment by zet809** [comment]
It seems `nodechmac` is used by PCM, @robin2008 , will you pls help check.
Maybe we can remove the document?

**Comment by robin2008** [comment]
This is only used by PCM, so there are many special prerequiste from PCM.

For xCAT, better to use below steps:

```
makedhcp -d <nodename>
chdef -t node -o  <nodename> mac=<new-mac>
makedhcp <nodename>
```

**Comment by immarvin** [comment]
suggest to mark this command to be `deprecated` instead of removing it
