### ISSUE TITLE
Remove xinetd dependency in Ubuntu packaging

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6325]
I think we moved over to systemd https://github.com/xcat2/xcat-core/issues/2586

But looks like this xinetd "Depends" was missed to be removed.  

In https://github.com/xcat2/xcat-core/blob/master/xCAT/debian/control#L12

![image](https://user-images.githubusercontent.com/10049070/58060943-dd747b80-7b41-11e9-87f7-d9f75c55c511.png)

Was this missed? 

Egan just told me a security scan removed `xinetd` and, thus... removed `xcat`  😄

**Comment by immarvin** [comment]
hi @neo954 , would you please take a look at this? thanks

**Comment by neo954** [comment]
Okay. I will look into this one.

**Comment by immarvin** [comment]
hi @whowutwut , the fix https://github.com/xcat2/xcat-core/pull/6327  from @neo954 is merged. We need to wait for the test result tomorrow to see whether the removal of xinetd introduces any issue

**Comment by whowutwut** [comment]
Thanks. Seems like our build server didn’t upload the daily build this morning

**Comment by robin2008** [comment]
Do they care about the `xinetd` in default package list?

**Comment by whowutwut** [comment]
This has been resolved by the PR above and will be in 2.15

**Comment by whowutwut** [comment]
@robin2008 just to answer your  question, I think xintetd is not supported anymore.
