### ISSUE TITLE
The new xcat dependency tar ball is too large

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#6333]
Download the latest xcat-dep tarball and find it is too large. Please investigate why. Thanks!
```
[root@/]# ls -l xcat-dep-201905170213.tar.bz2
-rw-r--r-- 1 root root 1746467144 May 21 22:05 xcat-dep-201905170213.tar.bz2
```

**Comment by neo954** [comment]
A new tarball was created and uploaded to xcat.org.
http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201905220119.tar.bz2

**Comment by gurevichmark** [comment]
Closing. Current dependency tar files are no longer that large.
