### ISSUE TITLE
[Customer]NVIDIA Driver update on RH72 PPC64LE 

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#634]
NVIDIA introduced a new driver for K80 GPU's and CUDA 7.5 that can be found on http://www.nvidia.com/download/driverResults.aspx/96857/en-us 
We are updating the driver through xdsh with the commands:
yum remove xorg-x11-drv-nvidia\* kmod-nvidia\* -y
/install/Updates/CS15b/CUDA/DRIVER68/NVIDIA-Linux-ppc64le-352.68.run -a --dkms
reboot
After reboot, verify the driver level:
nvidia-smi | grep Driver
This is a request for xCAT CUDA installation to also install the driver updates.

**Comment by markprez** [comment]
Worked with nvidia and installed the driver install.
1) From the NVIDIA download site http://www.nvidia.com/download/driverResults.aspx/96857/en-us
2) To see the source of the update follow the "Related links" in the download page http://developer.download.nvidia.com/compute/cuda/repos/rhel7/ppc64le/
    
3) wget http://developer.download.nvidia.com/compute/cuda/repos/rhel7/ppc64le/cuda-repo-rhel7-7.5-23.ppc64le.rpm

4) rpm -qa | grep cuda
    remove previous cuda rpms from the xcat ems.

5) rpm -i cuda-repo-rhel7-7.5-23.ppc64le.rpm

6) yum install cuda  --downloadonly --downloaddir=/install/cudaga.dr68

7) createrepo /install/cudaga.dr68

**Comment by daniceexi** [comment]
@cxhong I remember you fixed something to support the new cuda, am I right? Is this issue still valid?

**Comment by cxhong** [comment]
This is Documentation update. check for pull request #872.
@whowutwut can u review it?

**Comment by whowutwut** [comment]
Just reviewed and merged, sorry for the delay. 

@markprez  the changes @cxhong made can be viewed here:
http://xcat-docs.readthedocs.io/en/latest/advanced/gpu/nvidia/update_nvidia_driver.html

**Comment by whowutwut** [comment]
Closing issue, @markprez  Please reopen if you see other problems with this.
