### ISSUE TITLE
getinstdisk is not compatible with nvme device names

### ISSUE THREAD

**Issue by buzh** [xcat2/xcat-core#6346]
xcat/share/xcat/install/scripts/getinstdisk line 110:

     disk_part=${partition%%[0-9]*}

This is intended to strip partition numbers from e.g "sda1" to leave it as "sda". However, if using NVMe this breaks installation. The first partition on the first NVMe would be "/dev/nvme0n1p1" and so disk_part should be "nvme0n1", but actually ends up being "nvme"

As a quick fix, I changed the script to this:

                if [[ $partition = nvme* ]]; then
                  disk_part=${partition%%p*}
                else
                  disk_part=${partition%%[0-9]*}
                fi

..and that works for me on HPE XL170 and CentOS 7. I can't vouch for this working on other platforms/OSes, should probably be considered carefully.

**Comment by whowutwut** [comment]
Thanks for opening this issue to let us know and what you did as a work around! appreciate it.

**Comment by whowutwut** [comment]
just talking out loud...  and guessing a little..  That code looks like it's looking for some existing kernel on the partition to select the disk where maybe the OS was previously installed onto to select the disk...   Searching a little on the naming... [from here](https://unix.stackexchange.com/questions/452120/persistent-device-naming-for-nvme-storage-devices)
    * nvme0: first registered device's device controller
    * nvme0n1: first registered device's first namespace
    * nvme0n1p1: first registered device's first namespace's first partition

So looks like we have to figure out at least the namespace..   but not strip off down to `nvme`..  maybe `nvme0` would work.. .

**Comment by buzh** [comment]
This example oneliner should replace most of the logic in the script that tries to figure out what hard drives there are:

    if [ $(lsblk | grep -c disk) = 1 ]; then
     echo "There's just one disk, let's use that one...";
    else
     diskarray=( $(lsblk | grep disk | cut -d\  -f1 | xargs) )
     echo "Found $(echo ${#diskarray[@]}) disks, figure out which to choose"
    fi

This would also eliminate the need for pruning partition names entirely.

I also suggest removing all the extra coded added by "$has_awk".If there is an edge case where awk is not available, why not code just for that instead of replicating the same functionality in case it DOES have awk? However, since the script relies on 'udevadm' anyway, it seems odd that there would ever be a case where the script works AND awk is not available. 

The walking of partitions to find a kernel also seems convoluted and unecessarily complex. Something akin to

   parted $devicename print | grep boot

could further narrow the field of possibilites before moving on. If there's only one partition with the boot flag, install on the drive that holds that.

Lastly, if all else fails I'm unsure if selecting a disk to wipe and install on is best done by looking at which type of disk controller it's connected to. In my mind, it would be better to return an error message and prompt the administrator to select a specific device name (through an attribute in the node table perhaps) or provide a partitionfile.

Last, I noticed a small but potentially nasty bug in the existing script. There's a loop where the script mounts every partition, searches for a kernel and unmounts. Later there's an "rmdir" done on the mount point. Should the unmount fail, there's nothing stopping rmdir from trying to wipe the disk. There should probably be an "exit" in there to abort the script should the umount fail for whatever reason.

**Comment by karcaw** [comment]
please fix.

**Comment by gurevichmark** [comment]
Related internal issue https://github.ibm.com/xcat2/c910env/issues/765
