### ISSUE TITLE
copycds failed to pick correct pkglist and tmpl files

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#6353]
the daily regression test case `Pegas1.2-P9VMs-PostgreSQL-master-daily` failed on `pane is dead` message.  Checking the osimage, it didn't pick up rhels7 pktlist and tmpl file
```
# lsdef -t osimage rhels7.6-alternate-ppc64le-install-service
Object name: rhels7.6-alternate-ppc64le-install-service
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.6-alternate-ppc64le
    osname=Linux
    osvers=rhels7.6-alternate
    otherpkgdir=/install/post/otherpkgs/rhels7.6-alternate/ppc64le
    pkgdir=/install/rhels7.6-alternate/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/service.pkglist
    postscripts=servicenode
    profile=service
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/service.tmpl
```

**Comment by cxhong** [comment]
the issue is caused by this PR: https://github.com/xcat2/xcat-core/pull/6272

The sub routine `get_os_search_list` return list of os names based on specified os name and are used to find proper files for osimage template or pkglist.
```
 Example:
         xCAT::SvrUtils->get_os_search_list("ubuntu18.04.2");
         Will returns
         #   ubuntu18.04.2
         #   ubuntu18.04.1
         #   ubuntu18.04.0
         #   ubuntu18.04
         #   ubuntu18.4
         #   ubuntu18.03
         #   ubuntu18.3
         #   ubuntu18.02
         #   ubuntu18.2
         #   ubuntu18.01
         #   ubuntu18.1
         #   ubuntu18.00
         #   ubuntu18.0
         #   ubuntu18
````
but for the `rhels7.6-alternate-ppc64le-install-service` images, the  `osvers=rhels7.6-alternate`, and this routine didn't take care if `osvers` has letters at the end part.  so, it will just return `rhel7.6-alternate`, since there are no `rhel7.6-alternate`, it picked up default pktlist (`compute.pkglist`) and tmpl file (`compute.tmpl`).

**Comment by whowutwut** [comment]
Testcase added via #6355

**Comment by cxhong** [comment]
PR merged and test cases added.  close this issue
