### ISSUE TITLE
Deployment of diskless nodes on x86_64 results in "Connection timed out (http://ipxe.org/4c0a6012)"

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6357]
This was brought up on the xCAT users mailing list thread: https://sourceforge.net/p/xcat/mailman/message/36693058/  I am opening an  issue  here to document the solution incase others hit the problem as well. 

---------

I am troubleshooting an image load issue on a new install.

When attempting to download the diskless image / hostname.uefi file, the client returns "Connection timed out (http://ipxe.org/4c0a6012)";

In the past we've had this sort of issue with spanning-tree running on the switch.
We have configured the switch with all ports set to "spanning-tree rstp edge-port"

xCAT is running in a VM on a Dell R640 Red Hat Virtualization host.
The client compute node is a Dell C6420
The client NIC is a BRCM GbE 4P 5720-t rNDC

From a Dell R640 on the same network we're able to retrieve the hostname.uefi file:

```
[root@... ~]# wget http://<address>:80/tftpboot/xcat/xnba/nodes/apollo-g-01.uefi
--2019-06-12 16:59:28--  http://<address>/tftpboot/xcat/xnba/nodes/apollo-g-01.uefi
Connecting to <address>:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113
Saving to: 'apollo-g-01.uefi'

100%[===================================================================================================================================>] 113         --.-K/s   in 0s

2019-06-12 16:59:28 (18.9 MB/s) - 'apollo-g-01.uefi' saved [113/113]
[root@... ~]# cat apollo-g-01.uefi
#!gpxe
chain http://${next-server}:80/tftpboot/xcat/elilo-x64.efi -C /tftpboot/xcat/xnba/nodes/apollo-g-01.elilo<http://$%7bnext-server%7d:80/tftpboot/xcat/elilo-x64.efi%20-C%20/tftpboot/xcat/xnba/nodes/apollo-g-01.elilo>;
```
Any suggestions would be appreciated.

**Comment by whowutwut** [comment]
A user responded and suggested: 

> I had what sounds like the same issue on a Dell 6420.  We had to update the bios and use BIOS boot mode instead of UEFI. 

Which resolved the original issue.  Many thanks to the xCAT community!

**Comment by kjhee43** [comment]
@whowutwut was there any fix to the xcat code to address this, or is the solution simply to switch to BIOS mode?

**Comment by whowutwut** [comment]
Hi @kjhee43  humm...  not sure..    I was just helping to bridge this issue that came into the mailing list issue to the public GitHub tracker in case someone else hits the same thing via googling or looking into the issue tracker.   We don't have this particular server in house, so would need to rely on the community for some suggestions here..

@jjohnson42  would you have some more insight on this particular issue?

**Comment by kjhee43** [comment]
@whowutwut, thanks for the reply. I am running into a similar issue. A different timeout in iPXE and different HW, but the fix turned out the be the same. Switching to BIOS mode allows it to boot properly. Just wondering if anything was fixed in xCAT and if an update would allow us to boot in BIOS mode.

**Comment by whowutwut** [comment]
I'm not aware of anything done in the code to fix this... but I'd admit that i don't have much experience in this particular area..    😞

**Comment by adorsey-NOAA** [comment]
I had this issue today on an Intel motherboard, and the following steps resolved the issue for me:

    Ensure BIOS boot mode is set to UEFI, and reboot for that to take effect
    Go to BIOS setup
    Go to Boot Manager Options (not Boot Options)
    Go to "Delete Boot Entries"
    Delete ALL IPv6, HTTPv4 and HTTPv6 entries
    Delete all IPv4 entries that are NOT Baseboard network interfaces
    Save changes and reboot

So, maybe not exactly an xCAT issue, possibly a buggy BIOS issue.
