### ISSUE TITLE
copycds fails with no error message when there's no space left on the device 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6358]
```
# time copycds /path/Linux/RH80/RHEL-8.0.0-20190404.2-ppc64le-dvd1.iso
Copying media to /install/rhels8.0.0/ppc64le

real	0m0.901s
user	0m0.107s
sys	0m0.024s
#
```

After some debug added, seems like it's this line that fails: 
https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/anaconda.pm#L2254

Then trying to execute a mkdir confirms the problem:
```
# mkdir /install/testvictor
mkdir: cannot create directory ‘/install/testvictor’: No space left on device
```

We should do a better job here to push up the error...   even running in XCATBYPASS=1, there's really not debug that comes out to help this, I have to keep adding more...

**Comment by whowutwut** [comment]
I'm not able to re-create this internally, details  here: https://github.ibm.com/xcat2/c910env/issues/772

**Comment by peterwywong** [comment]
```
#df
Filesystem                       1K-blocks        Used  Available Use% Mounted on
devtmpfs                           1750336           0    1750336   0% /dev
tmpfs                              1805120          64    1805056   1% /dev/shm
tmpfs                              1805120      144896    1660224   9% /run
tmpfs                              1805120           0    1805120   0% /sys/fs/cgroup
/dev/mapper/xcatvg-root           57557548    52196680    5360868  91% /
```

**Comment by peterwywong** [comment]
We believe the error message generated by cpio is sufficient.

This issue is not closed.
