### ISSUE TITLE
the `xdsh_c_cn` test cases stuck and wait for user input 

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#6362]
`xdsh_c_cn` test cases stucked more than three hours until I pushed `Enter` key, 
```
RUN:xdsh c910f03c09k17 -c [Mon Jun 24 14:32:21 2019]
ElapsedTime:9711 sec
RETURN rc = 0
OUTPUT:
Do you wish to erase /tmp,/var/xcat/node/syncfiles and all subdirectories?
 Enter Y or N.
CHECK:rc == 0   [Pass]
```
It was ask user to `Enter Y or N`

**Comment by whowutwut** [comment]
Nice catch , was this the cause of the longer running bundle ? Or which test pipeline did this one affect?

**Comment by cxhong** [comment]
caught this from `rhels8.0.0-P8VMs-PostgreSQL-master-weekly` regression test.   the `xdcp_nonroot_user` test case changed ` SNsyncfiledir=/tmp` other than `/var/xcat/syncfiles`, which cause `xdsh -c` command pop up the message and wait for user to input.
