### ISSUE TITLE
xcatd daemon is not starting on AIX

### ISSUE THREAD

**Issue by mishrag07** [xcat2/xcat-core#6364]
somehow my xdsh command stopped working and was getting hung giving no output.  There were lots of process is ps which eventually I killed during troubleshooting.
Stopped xcatd daemon using stopsrc -s xcatd.
Now when trying to start daemon, its not starting at all and giving below error.
Any leads on this?

lssrc -s xcatd
Subsystem         Group            PID          Status
 xcatd                                          inoperative

lssrc -s xcatd
Subsystem         Group            PID          Status
 xcatd                                          inoperative

**Comment by gurevichmark** [comment]
What version of xcat ?
`lsxcatd -a`

**Comment by mishrag07** [comment]
since xcatd is not running below output gives error.

 lsxcatd -a
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: IO::Socket::INET: connect: A remote host refused an attempted connect operation. at /opt/xcat/lib/perl/xCAT/Client.pm line 217.

but if I run below commands it looks to be xcat 2.8

rpm -qa | grep -i xcat
openslp-xcat-1.2.1-1
xCAT-rmc-2.7.7-snap201305132323
xcat-mysql-5.1-37
xCAT-2.8.3-snap201311130137
xCAT-IBMhpc-2.7.7-snap201305132323
perl-xCAT-2.8.3-snap201311130132
xCAT-client-2.8.3-snap201311130132
xCAT-test-2.7.7-snap201305132326
xCAT-server-2.8.3-snap201311130133

**Comment by gurevichmark** [comment]
Filesystem full ?
Anything interesting in `/var/log/xcat/cluster.log` ?

**Comment by mishrag07** [comment]
Filesystem is not full.
My system does not have xcat logs configured under /var/log.
Any other output I can help with?

**Comment by gurevichmark** [comment]
Are you able to start xCAT on the foreground with `xcatd -f` ? Might not work on the older version like yours.

**Comment by mishrag07** [comment]
This looks to be a binary file.
/opt/xcat/sbin/xcatd -f
bash: /opt/xcat/sbin/xcatd: cannot execute binary file

**Comment by gurevichmark** [comment]
Have you tried `startsrc -s xcatd`  or `restartxcatd` ?

**Comment by mishrag07** [comment]
yes I tried and did both, below are the errors.
startsrc -s xcatd
0513-015 The xcatd Subsystem could not be started.
Please check subsystem resources and try again later.



0513-015 The xcatd Subsystem could not be started.
Please check subsystem resources and try again later.
Error: Cannot start the xcatd subsystem correctly.

**Comment by besawn** [comment]
@mishrag07 Are you still having difficulty getting xcatd to start in your environment or were you able to resolve this problem? If you were able to fix the problem, what was the solution?

**Comment by besawn** [comment]
Please re-open if you need additional assistance.

**Comment by mishrag07** [comment]
Thank you for the help.

Regards,
Gaurav Mishra
