### ISSUE TITLE
RHEL 6 stateless boot doesn't fetch image after kernel boots

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#6372]
I have a few nodes booting rhel6 disklessly and they are working fine. New hardware was purchased and I manually (via tabedit) added the new node to the xcat tables. I ran nodeset and makedhcp and it completed. I then tried to boot the node and it started to come up, got it's initrd and kernel, but then stopped. It never tried to get it's image(rpm.cpio.gz) and continue bootup.

My bootparams is empty for all nodes. 

What did I miss? Is this a problem with manually adding the node to the tables? Any help would be appreciated.

**Comment by gurevichmark** [comment]
Perhaps you can compare the `lsdef` output of the node that works with the output of the new manually defined node ?

**Comment by kjhee43** [comment]
@gurevichmark, 

I apologize for leaving it out but I did that and the node definitions are identical. 

I also compared the respective boot files in /tftpboot and saw no differences there either.

**Comment by gurevichmark** [comment]
Which version of xcat ?
What do you use to boot the node ? `rinstall` ?

**Comment by kjhee43** [comment]
@gurevichmark,

Xcat 2.14.6

These are stateless(diskless) nodes. So nodeset <nodename> osimage=<imagename>

**Comment by kjhee43** [comment]
For reference, these are the tables the new node was added to in order for it to get to this state.

Chain
Mac
Nics
Nodelist
Noderes
Nodetype

In all tables a copy of an existing node was made then modified for the new node.

**Comment by gurevichmark** [comment]
Anything interesting in log files, like `/var/log/httpd/access_log` or `/var/log/xcat/cluster.log` ?

**Comment by kjhee43** [comment]
@gurevichmark,

I will have to check and report back. I don't have an OOB management on these nodes(no IPMI or iLO) so i can't get a capture of the console either. 

I don't even see the node trying to do an http request for its image.

**Comment by kjhee43** [comment]
@gurevichmark,

/var/log/xcat/cluster.log is empty.

MY issue appears to be similiar to  [](https://github.com/xcat2/xcat-core/issues/5887)

Buy his resolution appeared to be regenerating the image with the correct drivers. I am already booting this image on the same hardware so that shouldn't be case. It also doesn't mention what was fixed in the code.

**Comment by kjhee43** [comment]
Wanted to provide an update. Turns out that it was an issue with X2APIC and disabling it in the BIOS allowed the boot process to work normally. Thank you for the assistance.

**Comment by cxhong** [comment]
how did u find this?  is there something we can check for X2APIC?   for our knowledge...

**Comment by kjhee43** [comment]
I found it by looking at the kernel messages after boot halted. It stated
`smpboot: weird, boot CPU (#255) not listed by the BIOS.`

some searching revealed that APIC being enabled can cause the CPUs to be enumerated incorrectly. I am assuming its due to having A GPU in this server since the others boot correctly.
