### ISSUE TITLE
Missing node during discovery process

### ISSUE THREAD

**Issue by nirvash404** [xcat2/xcat-core#6378]
Hi,

A discovery has been launched upon 120 nodes.
Nodes are powered up by group of 20.

During the first group discovery process, there was 19 nodes that actually booted up, according to the nodediscoverls cmd.
We identified all the nodes via ipmitool ( with xdsh ) and there was a hitch. The missing node was in fact reachable, and, after checking the hosts file, there was indeed correctly defined.

Have some of you already faced this issue ?

Thanks

**Comment by whowutwut** [comment]
Out of the 120 nodes only 19 were discovered?

**Comment by nirvash404** [comment]
We have powered the nodes by group of 20.
In this particular group ( the first ), only 19 have been detected not 20, according to the nodediscoverls command result.

In fact, when doing xdsh all over these 20 nodes, they all respond..

> 20 nodes were discovered, as exepected, but 1 was not shown by the command.

Some of the scripts I use to automate xcat depends on that result so it is not that convenient...

**Comment by gurevichmark** [comment]
@nirvash404 
* Did other groups of 20 had the same issue ? Or this is the only group of 20 where one node was not listed by `nodediscoverls` ?
* Are you using the sequential discovery process described here: https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/seq_discovery.html ?
* If you do `tabdump discoverydata` on xCAT management node, are the discovered nodes there but not the "missing" one ?
* Are there any entries in `/var/log/messages` or `/var/log/xcat/cluster.log` that match MAC or the IP of the missing node ?

**Comment by gurevichmark** [comment]
Please reopen if this is still a problem.
