### ISSUE TITLE
Deprecation of xCAT Kit Support in 2.15?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6379]
Hi All! 

With the upcoming release of xCAT 2.15, which supports running xCAT on a RHEL 8 Management Node, we have not yet completed xCAT KIT validation process and testing... It seems there's some effort required to continue to support KITS and we're not confident that any users of xCAT are still leveraging kits.  There hasn't been any issues opened against  this feature for a very long time.  Because of this, we feel it might be the  right opportunity to deprecate this function. 

Opening this issue for discussion.  Please let us know if KITS is critical to your deployment. 

Affected Areas: 
* xCAT KIT commands will be removed
* xCAT KIT Documentation will be removed from the  version when we drop support
* No more Compiler partial kits will be provided
* IBM HPC software will no longer provide their software in kit format 

Will also post this to the mailing list to reference this issue.

**Comment by gurevichmark** [comment]
I think this issue can be closed.
Results of UT are in #6382
