### ISSUE TITLE
[FVT] Design Bug: Not Cover RH6.7 for Post.xcat Restructure 

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#638]
The post.xcat restructure design doesn't cover the RH6.7: https://github.com/xcat2/xcat-core/wiki/post.xcat_restructure
As we support the latest two version for each OS, so please take RH6.7 in consideration and make it works.

**Comment by caomengmeng** [comment]
Test xcatdebugmode=1, there are all excepted logs; xcatdebugmode=0, then no xcat.post logs. 
So this issue is passed.

**Comment by daniceexi** [comment]
@caomengmeng I'd like you can draft out the tips of how to use the **xcatdebugmode** feature and add it in xCAT debug doc.
