### ISSUE TITLE
makedhcp node-name is not adding a entry into dhcpd.leases file

### ISSUE THREAD

**Issue by abhijitshintre11** [xcat2/xcat-core#6386]
Hello,
          The command makedhcp nodename is not adding the node entry into /var/lib/dhcpd/dhcpd.leases file. It requires makedhcp -n to be run before running makedhcp nodename. Is it mandatory to run makedhcp -n everytime before running makedhcp nodename or makedhcp -a.

Thanks

**Comment by gurevichmark** [comment]
No, running with "-n" option is not required before "makedhcp <nodename>".

I assume no error are reported after "makedhcp <nodename>".
After running "makedhcp <nodename>", what does "makedhcp -q <nodename>"
show ?
Is there anything interesting in /var/log/xcat/cluster.log or
in /var/log/messages ? Search on "makedhcp" in both.

Mark Gurevich
Poughkeepsie Development Lab
HPC Software Development - xCAT

"If we knew what it was we were doing, it would not be called research,
would it?"
--Albert Einstein

**Comment by gurevichmark** [comment]
@abhijitshintre11 

Which version of xCAT are you using ?

Can you post the output of `makedhcp <nodename>` and `makedhcp -q <nodename>`

**Comment by abhijitshintre11** [comment]
Hello gurevichmark,
             Thank you for your quick reply. Here are the answers to your questions.
1. xcat version - 2.14.6
2. os-version - CentOS Linux release 7.4.1708 (Core)
3. no errors are reported after makedhcp <nodename>
4. output of makedhcp -q <nodename>
gpu05: ip-address = 172.20.1.xx, hardware-address = 24:8a:07:a3:ee:xx
5. There is nothing interesting in /var/log/xcat/cluster.log

But found an error message regarding dhcpd saying 

**Can't start OMAPI protocol: address not available**

So can this be an issue?

I just did a fresh installation of xcat on a machine but still, the problem remains the same.

**Comment by gurevichmark** [comment]
@abhijitshintre11 
Did you look inside the `/var/lib/dhcpd/dhcpd.leases ` and the entry for your node is not there ?
The `makedhcp -q` displays your node, so it must be reading it from somewhere ?

**Comment by abhijitshintre11** [comment]
@gurevichmark 
 Yes I looked into /var/lib/dhcpd/dhcpd.leases, the entry for the node has not been added.

May be makedhcp -q is showing the data from database.

**Comment by cxhong** [comment]
Yes, I think **Can't start OMAPI protocol: address not available** caused this issue.   can u check passwd table?  there should have a entry defined `xcat_key` similar like that:
```
# tabdump passwd
#key,username,password,cryptmethod,authdomain,comments,disable
"omapi","xcat_key","Qld1TTl5ZndVSnY1VW9VeXo1UG1LWDNvRmpPdkRmd1I=",,,,
"system","root","cluster",,,,
````  

`makedhcp -n` will create new dhcpd.conf and include omapi-port.   
```
]# netstat -tulpn | grep 7911
tcp        0      0 0.0.0.0:7911            0.0.0.0:*               LISTEN      29600/dhcpd
```
check if dhcpd failed after `makedhcp -n`

**Comment by abhijitshintre11** [comment]
Hello @cxhong 
               There is an entry in passwd table for omapi with same key as in dhcpd.conf file. The port 7911 is open. Also, If I change an ip for a node its not getting updated in dhcpd.leases file. It also requires a makedhcp -n and makedhcp <nodename> to reflect the new ip in lease file

**Comment by cxhong** [comment]
can u check dhcpd status before you run `makedhcp nodename`?

**Comment by abhijitshintre11** [comment]
dhcpd service is running fine and no errors are shown in the log file

**Comment by cxhong** [comment]
can u able to attach dhcpd.conf and lease file and node definition?

**Comment by gurevichmark** [comment]
Please reopen if still a problem.
