### ISSUE TITLE
xCAT sequential discovery bugs

### ISSUE THREAD

**Issue by onimsha** [xcat2/xcat-core#64]
I'm having problem while running sequential discovery. Below is steps to producing this bugs:

1. nodediscoverystart noderange=AllRackB10 (Which is a group that contains a pool of free nodes)
2. Boot up nodes in this group sequentially.
3. Fews nodes boot up to genesis images, send data back to xCAT, then these things happened:

```
[root@inframgtlivexcatmn1 xCAT-scripts]# nodediscoverstatus
Sequential discovery is running.

    The parameters used for discovery: noderange=AllRackB10
```
=========
```
[root@inframgtlivexcatmn1 xCAT-scripts]# nodediscoverstatus
Sequential Discovery is stopped.
Profile Discovery is stopped.
```
=========
```
[root@inframgtlivexcatmn1 xCAT-scripts]# nodediscoverls
  UUID                                    NODE                METHOD         MTM       SERIAL
  31313636-3938-4753-4835-313758524236    undef               undef                    SGH517XR
  32393636-3735-4753-4835-3137584E534D    undef               undef                    SGH517XN
  32393636-3735-4753-4835-3137584E5434    undef               undef                    SGH517XN
  32393636-3735-4753-4835-3137584E5443    undef               undef                    SGH517XN
```
=========
```
[root@inframgtlivexcatmn1 xCAT-scripts]# nodels AllRackB10
spare01-b10
spare03-b10
spare05-b10
spare08-b10
spare09-b10
spare10-b10
spare11-b10
spare12-b10
spare13-b10
spare14-b10
spare15-b10
spare16-b10
spare19-b10
spare20-b10
```
What i saw is xCAT does not set next destiny to any of free nodes in AllRackB10 pool, instead of that, it stop the Sequential Discovery , and threw this log in /var/log/message:

```
"xCAT[54637]: Sequential Discovery: Auto Stopped because all node names in the specified range have been assigned to discovered nodes. Run 'nodediscoverls -t seq' to display the discovery result."
```
However, is i cleaned up the nodediscovery table, then run the Sequential Discovery again on the same Group, it will do exactly what Sequential Discovery is supposed to be. All nodes was picked up, assign to newly discovered nodes. 

So, is there anything i can do, to find out why this happened?

**Comment by daniceexi** [comment]
If nodediscovery stopped, it meant the nodes in the noderange have been used up. 

The issue you mentioned was no any of node was discovered, or some of the nodes failed to get discovered?

Have all failed nodes been recorded in discoverydata table? Or just part of it?

**Comment by onimsha** [comment]
@daniceexi : My issue was none of my nodes inside noderange was discovered (in this case is spare01-b10 to spare20-b10). 
The discoverydata table was empty at that time also, since it always empty discoverydata table everytime we execute nodediscoverystart ..

**Comment by daniceexi** [comment]
But in your first message that if clean up 'nodediscovery table', the discovery will succeed. I think 'nodediscovery table' you meant there was 'discoverydata' table.

**Comment by onimsha** [comment]
Yes, but it's because it can't assigns the "undef" discovered nodes to the "free" node in the pool. If the Sequential discovery working properly, it's supposed to automatically assigned the 1st "undef" to the 1st "free" node inside the noderange. 

So a short brief for my situation is:

1. Start discovery with a noderange (all node in range are free)
2. Found some discovered node with "undef" method
3. Instead if assigning the "undef" to the "free" node, it stops the Auto Discovery with the message i mentioned before.

**Comment by daniceexi** [comment]
As I mentioned, the sequential discovery will stop automatically when all the free nodes have been used up. If no free node, the discovered node will be assigned with 'undef' in the discoverydata table. 

Be aware that if the mac attribute has been set to a node, the node will be considered as non-free.

**Comment by onimsha** [comment]
As you suggested, i ran it again, and check the mac address. Below is the result:
```
[root@inframgtlivexcatmn1 xCAT-scripts]# nodels AllRackA13-AU135 mac.mac
spare63:
spare64:
spare65:
spare66:
spare67:
spare68:
spare69:
spare70:
spare71:
spare72:
spare73:
spare74:
[root@inframgtlivexcatmn1 xCAT-scripts]# nodediscoverstatus
Sequential Discovery is stopped.
Profile Discovery is stopped.
[root@inframgtlivexcatmn1 xCAT-scripts]# nodediscoverls
  UUID                                    NODE                METHOD         MTM       SERIAL
  31313636-3938-4753-4835-313658435332    undef               undef                    SGH516XC
  31313636-3938-4753-4835-313658435354    undef               undef                    SGH516XC
  31313636-3938-4753-4835-313658435637    undef               undef                    SGH516XC
```
As you can see, none of the node in "free" pool has mac attribute. The Sequential Discovery is just unexpected stop, leave all the "undef" node without any assignment.

**Comment by daniceexi** [comment]
Could you run the nodediscoverstart with '-V' to display the free nodes?

**Comment by onimsha** [comment]
```
Sequential Discovery: Started:
    Number of free node names: 15

====================Free Nodes===================
NODE                HOST IP             BMC IP
spare203            10.34.25.206        10.34.0.222
spare204            10.34.25.207        10.34.0.221
spare205            10.34.25.208        10.34.0.220
spare206            10.34.25.209        10.34.0.219
spare207            10.34.25.210        10.34.0.218
spare208            10.34.25.211        10.34.0.217
spare209            10.34.25.212        10.34.0.216
spare210            10.34.25.213        10.34.0.215
spare211            10.34.25.214        10.34.0.214
spare212            10.34.25.215        10.34.0.228
spare213            10.34.25.216        10.34.0.227
spare214            10.34.25.217        10.34.0.226
spare215            10.34.25.218        10.34.0.225
spare216            10.34.25.219        10.34.0.224
spare217            10.34.25.220        10.34.0.223
```

Then the discovery stopped..

```
nodediscoverstatus
Sequential Discovery is stopped.
Profile Discovery is stopped.
```

nodediscoverls
```
 UUID                                    NODE                METHOD         MTM       SERIAL
  31313636-3938-4753-4835-313658434B39    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658434B59    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658434E31    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658434E37    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658434E59    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658435033    undef               undef                    xxxxxxxx
  31313636-3938-4753-4835-313658435054    undef               undef                    xxxxxxxx
```

**Comment by arif-ali** [comment]
I've had similar sequential discovery problems over a week ago. But I have tended to ignore, and restart the discovery again

**Comment by daniceexi** [comment]
@arif-ali Do you mean that rerun the nodediscoverstart command, the issue will disapare? 
@onimsha Could give me a way to create this issue?

I tried to recreate this issue in my env, but it worked well. Could you run lsdef -v to show me the version of xCAT?

**Comment by samveen** [comment]
[root@inframgtlivexcatmn1 ~]# lsdef -v
lsdef - Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)

**Comment by daniceexi** [comment]
I got a cluster with same xCAT version as yours, but it works well. Could you give me some hits that how to easly recreate this issue?

# nodediscoverstart noderange=testnode[1-10] bmciprange=192.168.0.1-192.168.0.10 hostiprange=192.168.1.1-192.168.1.10 -V
Sequential Discovery: Started:
    Number of free node names: 10
    Number of free host ips: 10
    Number of free bmc ips: 10

====================Free Nodes===================
NODE                HOST IP             BMC IP
testnode1           192.168.1.1         192.168.0.1
testnode10          192.168.1.2         192.168.0.2
testnode2           192.168.1.3         192.168.0.3
testnode3           192.168.1.4         192.168.0.4
testnode4           192.168.1.5         192.168.0.5
testnode5           192.168.1.6         192.168.0.6
testnode6           192.168.1.7         192.168.0.7
testnode7           192.168.1.8         192.168.0.8
testnode8           192.168.1.9         192.168.0.9
testnode9           192.168.1.10        192.168.0.10

# nodediscoverls
Discovered 1 node.
  UUID                                    NODE                METHOD         MTM       SERIAL
  7FC5E0FE-FE8B-3750-8D20-DD247A987CDE    testnode1           sequential     7915AC1   KQ3A48T

**Comment by daniceexi** [comment]
Or you have to debug it by yourself that why the code complained no free 'node' but in fact there was free nodes. You could add some debug message there.

The issue happened in the following code that $node is null since it did not get free node.

/opt/xcat/lib/perl/xCAT_plugin/seqdiscovery.pm
    126     unless ($node) {
    127         # get a free node
    128         @allnodes = getfreenodes($param{'noderange'}, "all");
    129         if (@allnodes) {
    130             $node = $allnodes[0];
    131         }
    132     }

145     if ($node) {
    146         my $skiphostip;
    147         my $skipbmcip;
    148         my $bmcname;

**Comment by onimsha** [comment]
That's exactly my problem, since it's very easy to reproduce in my env, but like you said, we used the same steps for start the sequential discovery.

Debug code will be the last opportunity i think. I will run again with debug mode then revert back to you.

**Comment by daniceexi** [comment]
I did not see more follow up for this issue, so close it first. You can reopen it anyway if you have new find.
