### ISSUE TITLE
[FVT] For link aggregation support of confignetwork, only IEEE 802.3ad is supported, all the other modes are not

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#640]
Below are the `nicdevices` and `nictypes` attributes of node `c910f02c03p23`. With these attributes, a regular link aggregation network interface named `bond0` can be created.

```
[root@c910f02c03p27 ~]# lsdef c910f02c03p23 -i nicdevices,nictypes
Object name: c910f02c03p23
    nicdevices.bond0=eth2|eth1
    nictypes.eth2=ethernet
    nictypes.bond0=bond
    nictypes.eth1=ethernet
```

But, currently, only IEEE 802.3ad, LACP is supported by `confignetwork`. Actually, Linux support a brunch of modes of the link aggregation [1]. All the other modes are not supported yet.

[1] https://en.wikipedia.org/wiki/Link_aggregation#Driver_modes

This issue may looks like a feature request. But I believe this is a useful feature. What if the end user can not afford a fully managed ethernet switch and only want active-backup.

```
[root@c910f02c03p23 ~]# cat /proc/net/bonding/bond0
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: IEEE 802.3ad Dynamic link aggregation
Transmit Hash Policy: layer2 (0)
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

802.3ad info
LACP rate: slow
Min links: 0
Aggregator selection policy (ad_select): stable
Active Aggregator Info:
    Aggregator ID: 5
    Number of ports: 1
    Actor Key: 9
    Partner Key: 9
    Partner Mac Address: 16:3f:42:91:ed:04

Slave Interface: eth1
MII Status: up
Speed: 1000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 16:3f:4d:b4:fe:04
Slave queue ID: 0
Aggregator ID: 5
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    port key: 9
    port priority: 255
    port number: 1
    port state: 61
details partner lacp pdu:
    system priority: 65535
    oper key: 9
    port priority: 255
    port number: 1
    port state: 61

Slave Interface: eth2
MII Status: up
Speed: Unknown
Duplex: Unknown
Link Failure Count: 0
Permanent HW addr: 00:21:5e:a9:54:56
Slave queue ID: 0
Aggregator ID: 6
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    port key: 0
    port priority: 255
    port number: 2
    port state: 69
details partner lacp pdu:
    system priority: 65535
    oper key: 1
    port priority: 255
    port number: 1
    port state: 1
```

**Comment by neo954** [comment]
This is the version of xCAT used in the testing.

    Version 2.12 (git commit fbd91febf512026bdada2ab10120957b90bf8831, built Mon Jan 18 15:30:50 EST 2016)

**Comment by bybai** [comment]
@neo954 , yes, now we just support IEEE 802.3ad, LACP , since it is common used, it was also used by solution team. In the future, we should support nicextraparams in confignetwork from nics table. This mode can be configured in nicextraparams, so I think your issue is a new requirement.  I assigned it into feature type. Thanks.

**Comment by robin2008** [comment]
bond, vlan, bridge is 2.13.6 feature of confignetworks,  move it to 2.13.6
@bybai Please confirm is it covered in current scope?

**Comment by bybai** [comment]
I think #3189 nicextraparam can support customize attribute in ifcfg-* files. It can cover this issue.

**Comment by zet809** [comment]
Hi, @bybai , had this been fixed with latest confignetworks interface?

**Comment by zet809** [comment]
It seems the module can not be supported, so close it.
