### ISSUE TITLE
conserver-xcat package is left after go-xcat uninstall

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6403]
The PR #6243 removed `conserver-xcat` from the installation using `go-xcat`.
However, if the user had older version of xcat installed, one which included `conserver-xcat`, and then uses a recent version of `go-xcat` to uninstall, the `conserver-xcat` will be left over.

This is similar to the root cause of issue #6400, which was fixed by PR #6402

**Comment by besawn** [comment]
Fixed via PR #6404.
