### ISSUE TITLE
[FVT] Wrong link members of the link aggregation interface created by postscript confignetwork, when node definition changed

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#641]
Below were the `nicdevices` and `nictypes` attributes of node `c910f02c03p23` at beginning.

```
# lsdef c910f02c03p23 -i nicdevices,nictypes
Object name: c910f02c03p23
    nicdevices.bond0=eth2|eth1
    nictypes.eth2=ethernet
    nictypes.bond0=bond
    nictypes.eth1=ethernet
    nictypes.eth0=ethernet
```

After created the definition, command `updatenode c910f02c03p23 confignetwork` was run. And it run successfully. A link aggregation interface named `bond0` was created, with `eth2` and `eth1` as its link members.

After that, the following command were run, and changed the node definition a little.

```
# chdef c910f02c03p23 nicdevices.bond0="eth0|eth1"
1 object definitions have been created or modified.
# lsdef c910f02c03p23 -i nicdevices,nictypes
Object name: c910f02c03p23
    nicdevices.bond0=eth0|eth1
    nictypes.eth2=ethernet
    nictypes.bond0=bond
    nictypes.eth1=ethernet
    nictypes.eth0=ethernet
```

And then, command `updatenode c910f02c03p23 confignetwork` was run again.

Here is what happened after all. A link aggregation interface `bond0` is created with all `eth0`, `eth1` and `eth2` as its link members, instead of the correct behavior, just have `eth0` and `eth1` as its link members.

This behavior is incorrect, and should be fixed definitely.

```
[root@c910f02c03p23 ~]# cat /proc/net/bonding/bond0
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: IEEE 802.3ad Dynamic link aggregation
Transmit Hash Policy: layer2 (0)
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

802.3ad info
LACP rate: slow
Min links: 0
Aggregator selection policy (ad_select): stable
Active Aggregator Info:
    Aggregator ID: 2
    Number of ports: 1
    Actor Key: 9
    Partner Key: 9
    Partner Mac Address: 16:3f:42:91:ed:04

Slave Interface: eth0
MII Status: up
Speed: 1000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 16:3f:4d:b4:fe:03
Slave queue ID: 0
Aggregator ID: 1
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    port key: 9
    port priority: 255
    port number: 1
    port state: 77
details partner lacp pdu:
    system priority: 65535
    oper key: 1
    port priority: 255
    port number: 1
    port state: 1

Slave Interface: eth1
MII Status: up
Speed: 1000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 16:3f:4d:b4:fe:04
Slave queue ID: 0
Aggregator ID: 2
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    port key: 9
    port priority: 255
    port number: 2
    port state: 13
details partner lacp pdu:
    system priority: 65535
    oper key: 9
    port priority: 255
    port number: 1
    port state: 5

Slave Interface: eth2
MII Status: up
Speed: Unknown
Duplex: Unknown
Link Failure Count: 0
Permanent HW addr: 00:21:5e:a9:54:56
Slave queue ID: 0
Aggregator ID: 3
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    port key: 0
    port priority: 255
    port number: 3
    port state: 69
details partner lacp pdu:
    system priority: 65535
    oper key: 1
    port priority: 255
    port number: 1
    port state: 1
```

**Comment by neo954** [comment]
It seems the wrong behavior is due to the current state of a link aggregation interface is not checked by ``confignetwork``.

What is the end user just made a typo and want to fix it later. Is it reasonable to ask the user to install the full operating system again? Anyway, this is a usability problem. And I believe it deserve to be fixed.

**Comment by neo954** [comment]
This is the version of xCAT used in the testing.

    Version 2.12 (git commit fbd91febf512026bdada2ab10120957b90bf8831, built Mon Jan 18 15:30:50 EST 2016)

**Comment by bybai** [comment]
@neo954 , currently, we do not delete bond, we just create bond. If user want to recreate nics, he should manually restore all the nics, then re-execute confignetwork.
I know your meaning, if our script can do restore work automatically, all the actions are perfect. In that case, we should backup all the original network configure files, then restore network, then recreate new bond,  it is not just a simple issue, it should be a enhancement if we want to support this case.

**Comment by neo954** [comment]
@bybai , I am not expecting ``confignetwork`` redo all the network interfaces related configurations. I expect ``confignetwork`` check the current state of the compute node before it configure the network interface, and clean all the link members of the link aggregation interface before it re-configure it.

**Comment by robin2008** [comment]
Bonding is considered in 2.13.6 of confignetworks.

**Comment by zet809** [comment]
Have this issue been fixed with latest confignetworks interface?

**Comment by bybai** [comment]
Hi @zet809 ,
There is no undo the network configuration in confignetwork scripts now, confignetwork support -r is in backlog #2804 .

**Comment by bybai** [comment]
Will plan this feature in 2.14.

**Comment by zet809** [comment]
The effort maybe very large and no much value for us, close this issue.
