### ISSUE TITLE
[FVT] Wrong attached ports of the linux bridge interface created by postscript confignetwork, when node definition changed

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#642]
Below were the `nicdevices` and `nictypes` attributes of node `c910f02c03p23` at beginning. Please notice there was a bridge interface named `bar` and `eth2` was the only attached port of `bar`.

```
# lsdef c910f02c03p23 -i nicdevices,nictypes
Object name: c910f02c03p23
    nicdevices.bar=eth2
    nictypes.bar=bridge
    nictypes.eth2=ethernet
    nictypes.eth1=ethernet
```

After created the definition, command `updatenode c910f02c03p23 confignetwork` was run. And it run successfully. A bridge interface named `bar` was created, with `eth2` as its attached port.

After that, the following command were run, and changed the node definition a little.

```
# chdef c910f02c03p23 nicdevices.bar=eth1
1 object definitions have been created or modified.
# lsdef c910f02c03p23 -i nicdevices,nictypes
Object name: c910f02c03p23
    nicdevices.bar=eth1
    nictypes.bar=bridge
    nictypes.eth2=ethernet
    nictypes.eth1=ethernet
```

And then, command `updatenode c910f02c03p23 confignetwork` was run again.

Here is what happened after all. A bridge interface `bar` is created with both `eth1` and `eth2` as its attached ports, instead of the correct behavior, just have `eth1` as its attached port.

This behavior is incorrect, and should be fixed definitely.

```
[root@c910f02c03p23 ~]# brctl show bar
bridge name     bridge id               STP enabled     interfaces
bar             8000.00215ea95456       no              eth1
                                                        eth2
```

**Comment by neo954** [comment]
The same point as issue #641.

What is the end user just made a typo and want to fix it later. Is it reasonable to ask the user to install the full operating system again? This is a usability problem. And I believe it deserve to be fixed.

**Comment by neo954** [comment]
This is the version of xCAT used in the testing.

    Version 2.12 (git commit fbd91febf512026bdada2ab10120957b90bf8831, built Mon Jan 18 15:30:50 EST 2016)

**Comment by bybai** [comment]
There is no undo the network configuration in confignetwork scripts. If we support undo network configuration in confignetwork, this issue will fix.

**Comment by whowutwut** [comment]
If you plan to change `confignetwork` please also look into adding MTU support :+1: !

**Comment by bybai** [comment]
There is no undo the network configuration in confignetwork scripts now, confignetwork support -r is in backlog.
