### ISSUE TITLE
elilo.c(line ):Main_Loop: Retrying-have to rebuild boot params

### ISSUE THREAD

**Issue by johebll** [xcat2/xcat-core#6421]
Hello,

i try to PXE boot a supermicro server to a node-image hosted on a xCat 2.4.16-server.
The node to PXE-boot is configured for UEFI-boot-mode, as the legacy BIOS-boot-mode ended in another issue with a missing boot-partition on a GPT-drive.
I assume UEFI-mode PXE-boot to be more relevant these days and prefer to debug this mode therefore ;-)

### **Error message:**

xCat Network Boot Agent
[ ... ]
ELILO v3.14 for EFI/x86_64
Loading kernel /tftpboot/...vmlinuz... done
Loading file /tftpboot/...initrd.img... done
elilo.c(line 276):
ExitBootSvc: failed, memory map has changed.
elilo.c(line 279):Main_Loop: Retrying,... have to rebuild boot params

### **Expected behaviour: loading kernel**

E.g.:
[    0.000000] Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 (Ubuntu 4.15.0-29.31-generic 4.15.18)
[    0.000000] Command line: BOOT_IMAGE=net0:/tftpboot/xcat/osimage/ubuntu18.04.1-x86_64-netboot-compute/kernel  imgurl=http://ipaddress://install/netboot/ubuntu18.04.1/x86_64/compute/rootimg.cpio.gz XCAT=ipaddress:3001  XCATHTTPPORT= console=tty0 console=ttyS1,115200n8r BOOTIF=01-cc-1f-6a-45-g8-84
[    0.000000] KERNEL supported cpus:

### **Environment:**
xCat 2.4.16
PXE configured in UEFI-mode

There is little reference to be found except for [this](https://sourceforge.net/p/elilo/mailman/elilo-announce/) information about an fixed ELILO bug:

> MAJOR: Fixed Fault crash when EFI memory map changes from under elilo.
      (from an outside interrupt in this case). When the EFI Memory map
      changes after elilo has already built boot params to pass to the
      kernel the EFI call to ExitBootSvcs just prior to boot will fail
      because elilo has the old map key. This is valid EFI behavior, elilo
      retries to pick up the new memory map and key but had already freed
      the start params portion of boot params resulting in a NULL DEREF
      crash reset once it hands the now bogus boot params to the kernel on
      the 2nd successful call to exit efi and boot.
      Thanks to Jerry Hoemann @ HP for reporting this bug.

As the issue and it's fix is from 2013, i guess my issue has other roots, but havn't the faintest idea.
Anyone out there who can give me hints?

**Comment by johebll** [comment]
Hello,

it actually would also help me if someone could point me to what at the point of failure actually is going on.
If i read the screen log right, the following files

/tftpboot/xcat/osimage/centos7.6-x86_64-install-compute/initrd.img
/tftpboot/xcat/osimage/centos7.6-x86_64-install-compute/vmlinuz

have been loaded sucessfully.
So the kernel has been loaded, but this process still is ELILO, right?
Is this then more likely an issue in the realm of CentOS7.6?

Any hint highly appreciated!

**Comment by johebll** [comment]
Hello,
i also wonder whether the issue may be related to the situation, that ELILO apparently is not a maintained project any longer for quite some time... Maybe some sort of incompatibility sneaked in? Is there any official alternative one could use in xCAT for UEFI netboots?

**Comment by johebll** [comment]
Hello,

i think the clues condense that this issue is a behaviour known for ELILO 3.14, and fixed in ELILO 3.16, according to: "https://sourceforge.net/p/elilo/mailman/elilo-announce",
which i already referenced above (Sep 5).

My assumption back then (Sep 5):

> As the issue and it's fix is from 2013, i guess my issue has other roots,

was wrong, as the "xCAT.x86_64 2.15-snap201911041517" i use still features "elilo-xcat.noarch 3.14-4", which according to "https://sourceforge.net/p/elilo/mailman/elilo-announce" would be affectred.

I.o.w.: if i read that right, the described PXE boot failure is exactly that bug, and an update of "elilo-xcat.noarch 3.14-4" as bundled in "xCAT.x86_64 2.15-snap201911041517" to the version "Elilo 3-16 Released 3/29/13" would possibly help to fix this issue, as described in the release notes for 3.16.

Is there any option to file a bug somewhere, so someone more competent then me could have a look, whether my assumption is right?

That would be great, as i depend on UEFI based PXE, as to my understanding there is no other option to workaround ELILO...

Any help would be highly appreciated.

**Comment by bybai** [comment]
@johebll ，I think you can try to modify /tftpboot/xcat/xnba/nodes/<node>.uefi to directly boot from kernel and initrd, it works, since elilo is too old.

**Comment by johebll** [comment]
@bybai  thank you very much, and sorry for being so late. I lost track of this problem, honestly. Your proposal worked perfectly fine for me. Thank you again!
