### ISSUE TITLE
SLES15 support on management node

### ISSUE THREAD

**Issue by paddg** [xcat2/xcat-core#6438]
I noticed, "sles15" disappeared from XCAT_2.15_Release_Notes. Will SLES15 on Management Node be supported in the future? Is there already an estimate of when? Or will SLES support be discontinued in the future? What are the plans?

**Comment by besawn** [comment]
@paddg The xCAT team tries to prioritize features and support based on the needs of our users. We are not currently aware of any users making use of SLES, so we have lowered SLES testing and support in our planning priorities. We do intend to support SLES15 in a future release, but we do not have a specific time line for that support.

If you or any other users of xCAT are using SLES in your clusters, providing us with some additional feedback about your usage of xCAT and SLES will help us to adjust our priorities for future releases. In particular, we are more likely to prioritize items that:

- are requested by users with xCAT support contracts
- are requested by multiple users
- represent a larger number of total installed nodes under management by xCAT

If you would like to see the priority of SLES support increased and you have an xCAT support contract, please open a ticket using your official support channel. If you do not have an xCAT support contract, you can provide some additional information about your SLES requirements directly in this issue.

**Comment by paddg** [comment]
Thank you @besawn, your reply is very useful! We are an ISP and we run a bunch of s SLES servers. We used xcat since many years. It was a recommendation from IBM. However, we weren't aware of the possibility to get a commercial support. I once asked on the mailing list, but didn't get an answer.
Where can we obtain support?

**Comment by besawn** [comment]
@paddg xCAT users can purchase support from IBM through an IBM client representative. 

This link contains some additional information about the IBM Enhanced Support for xCAT and IBM Elite Support for xCAT offerings: https://www.ibm.com/software/passportadvantage/paselectedsupportprograms.html#xcat

However, the support offerings for xCAT only apply to a very strictly defined set of hardware and software combinations. Unfortunately the link above needs updating to reflect the current set of hardware and software combinations for which support is available.

My recommendation is to not to try to purchase xCAT support until we can confirm whether the hardware and software combinations you are using are covered by the support offering.

Can you provide some additional information about your environment? Are you using IBM servers? If so, what are the model numbers? What specific OS versions do you use in your environment?

If you would prefer to discuss these details in a less public forum, we can start an email discussion instead.

**Comment by paddg** [comment]
Thank you @besawn. We have different IBM and Lenovo rack servers. Former model "x", x3550m5 for example. Or model SR in future. It always depends on the requirements and the offers. In the past it was always IBM and Lenovo. But I can't predict future. xCAT worked very well for us for many years. Also on Fujitsu Hardware.

We use xCAT only for the base installation of the OS. On top of that we have another configuration management.

Our OS is Suse Linux Enterprise.

We use the Software from that distribution and other OSS.

It could be possible that we are able to support the xCAT project by purchasing xCAT support. But that depends on the conditions.

In return, we would like to see the SLES support evolve. Right now we were grateful for a SLES15 
 xCAT Dependency Package (xcat-dep) .

**Comment by gurevichmark** [comment]
@paddg Which SLES15 xCAT Dependency Package are you referring to ? 
The https://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-2.14.6-linux.tar.bz2 ?

**Comment by paddg** [comment]
@gurevichmark, yes exactly. There are directories for SLES 10, 11 and 12. But no sles15.

Same here:
http://xcat.org/files/xcat/repos/yum/xcat-dep/

For sles12 I used this repository:
http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/x86_64/

But this one does not yet exist:
http://xcat.org/files/xcat/repos/yum/xcat-dep/sles15/x86_64

**Comment by gurevichmark** [comment]
@paddg So do you use yum repo files to get the SLES dependencies ? Or download individual rpms ?

I assume you are not downloading the `xcat-dep-2.14.6-linux.tar.bz2` from https://xcat.org/files/xcat/xcat-dep/2.x_Linux/ ?

**Comment by paddg** [comment]
Well, yes, we do "zypper ar" because it is Suse and not redhat. To be exact, we mirror that repo and "zypper ar" the mirror.

**Comment by gurevichmark** [comment]
@paddg Our current plans are not to officially support SLES 15 in the next xCAT 2.15 release.
However, our testing has showed that diskfull provisioning of SLES 15 compute node works, but diskless did not.

If you just want to install xCAT Management Node on SLES 15 you can try to just use SLES 12 dependency files.

**Comment by paddg** [comment]
Thank you @gurevichmark, that's good news! We will give it a try! What are the plans for the future support of SLES, d9oes xCAT have a perspective for SLES?

**Comment by besawn** [comment]
xCAT will continue to attempt to support SLES on a best effort basis. We will review the request to include SLES15 support in xCAT during our next release planning cycle. If you do decide to attempt to use the SLES 12 dependencies to attempt diskfull provisioning of SLES 15, any feedback you can provide about your experience will be helpful to the xCAT team. We also understand if you would prefer to wait to attempt to deploy SLES 15 until xCAT officially supports it.

**Comment by paddg** [comment]
> If you just want to install xCAT Management Node on SLES 15 you can try to just use SLES 12 dependency files.

@gurevichmark, we tried it and it works :-)

We have installed the Management Node with SLES15-SP1. And we installed xcat from [repos/yum/devel/core-snap](http://xcat.org/files/xcat/repos/yum/devel/core-snap) and [repos/yum/xcat-dep/sles12/x86_64](http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/x86_64)
With this setup we were able to install our nodes with SLES12-SP1, SLES15 and SLES15-SP1 without any problems.

Thank you very much for your help! We'd be very grateful if your project supports SLES in future and we are happy if we can help somehow!

**Comment by paddg** [comment]
Thanks for the new release https://github.com/xcat2/xcat-core/releases/tag/2.15.1
And especially for the SLES15 support!
