### ISSUE TITLE
[FVT]rsetboot NODE net could not set NextScale node to boot from network

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#644]
Test OS:  SLES11.4
Test xCAT version: xCAT 2.10 GA version , git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7

How to reproduce: 
1. Install and configure MN
2. Define a NextScale node as compute node
3. Prepare to do diskful provision for the NextScale node
4. run rsetboot NODE net to set the node boot from network.
```
c693fxx:~ # rsetboot c693fxx4 net
c693fxx4: Network
c693fxx:~ # echo $?
0
```
5 . run "rpower NODE reset" to let the node reboot and begin installation.

The compute node reboot but the PXE net is not the first boot sequence.

**Comment by immarvin** [comment]
how do you know the network is not the 1st boot order?

**Comment by tingtli** [comment]
This bug is not reproduce. Close it.
