### ISSUE TITLE
CentOS Diskless install hangs due to self-signed certificate encountered

### ISSUE THREAD

**Issue by zephyr213** [xcat2/xcat-core#6463]
Hi,
I am tryting to do a diskless install of CentOS 7.
However, during the installation, the process hangs due to the following error:

[    9.942779] IPv6: ADDRCONF(NETDEV_CHANGE): enp3s0f1: link becomes ready
[   14.709858] dracut-initqueue[567]: ERROR: cannot verify hpc.mtech.edu's certificate, issued by '/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA':
[   14.727710] dracut-initqueue[567]: Self-signed certificate encountered.
[   14.735606] dracut-initqueue[567]: To connect to hpc.mtech.edu insecurely, use `--no-check-certificate'.

The "hpc.mtech.edu" is the address of the headnode (external network).

I am wondering how can I add the "--no-check-certificate" option?

Another issue is that I also tried the diskful installaion. However, the compute node seems to stuck in a installation loop. It keeps reinstalling after reboot. I searched on line, and found someone mentions this might be an DNS issue. Is there a way to fix?

Thanks.

**Comment by cxhong** [comment]
I think there are configuration issue.  Can u check the site table for master, dns service and domain name?  you can issue this command to check the status of xCATmn:  
```
xcatprobe xcatmn -i <interfacename>
```
also, check if this node is defined in the `/etc/hosts` or check the command `nslookup <nodename>`

**Comment by zephyr213** [comment]
Thank you for the reply.
I did the xcatprobe to check the status and found it saying "[mn]: DNS service isn't ready on 10.54.0.1"
The node does exist in the /etc/hosts file. And when I did nslookup,
if I do "nslookup cn0", it complains "** server can't find cn0: SERVFAIL"
However, if I added the domain name (nslookup cn0.localdomain), it is able to find the node. 
Also, once I logged on the cn0 node, I was able to ping "www.google.com", but had problem reach yum repository.
-------------------------------
[root@cn0 ~]# ping www.google.com
PING www.google.com (172.217.3.196) 56(84) bytes of data.
64 bytes from sea15s12-in-f4.1e100.net (172.217.3.196): icmp_seq=1 ttl=51 time=16.3 ms
-------------------------------
[root@cn0 ~]# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#7 - "Failed to connect to 2001:1b48:203::4:10: Network is unreachable"
-------------------------------



Is it because that we had different domain names for internal and external networks? I found on the examples on the documentations use the same domains.


Below is the output from site:
-------------------------------
#key,value,comments,disable
"blademaxp","64",,
"domain","localdomain",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","10.54.0.1",,
"forwarders","10.34.34.2",,
"nameservers","10.54.0.1",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","America/Denver",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"auditskipcmds","ALL",,
"dhcpinterfaces","xcatmn|eno1",,
"precreatemypostscripts","yes",,
"dnsinterfaces","xcatmn|eno1,enp4s0f1;compute|enp3s0f1",,
-------------------------------

**Comment by cxhong** [comment]
maybe there are something wrong with your yum repository.  on the compute node, there should be one repo point to xcatmaster (10.54.0.1),  can u remove the repo with mirrorlist first, then try to `yum update`?

**Comment by zephyr213** [comment]
Thanks for the suggestion. Although all repo files except the one point to headnode was disabled, all repos were shown status=0. So I moved the other repo files and yum update is working now.

When I did "xcatprobe xcatmn -i eno1", it still complains that the DNS is not working. And when I tried to do a stateful installation on a second node, given the first one is working now, I got the "TFT timeout" error from the rcons output. The xcatprobe did confirm TFT is working. Do you think this timeout error is related with DNS?

**Comment by zephyr213** [comment]
Turned out to be something wrong in the firewall setting.

Thanks for the help!
