### ISSUE TITLE
rvitals report wrong power consumption values

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6479]
Hi!

It looks like `rvitals` is converting "Power consumption" values it gets from IPMI somehow when they don't need to be, which results in wrong values being reported.

For instance, `ipmitools` SDR data reports 252W:
```
# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi sdr type 0x03
Pwr Consumption  | 76h | ok  |  7.1 | 252 Watts
Current 1        | 6Bh | ok  | 10.1 | 2 Amps
Current 2        | 6Ch | ok  | 10.2 | 1.80 Amps
Input Current    | 14h | ns  |  7.96 | Disabled
```
while `rvitals` reports close to 400W (both commands are launched at the same time)
```
# rvitals sh-106-01 power
sh-106-01: Current 1: 2 Amps
sh-106-01: Current 2: 1.8 Amps
sh-106-01: Pwr Consumption: 396 Watts (1352 BTUs/hr)
sh-106-01: Power Status: on
```
That's a 1.57x discrepancy between the two values.

The Current numbers match between `ipmitool` and `rvitals`, so the issue seems to be that `rvitals` converts the "Pwr Consumption" value somehow.

Here are the full details about the sensor:
```
# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi sensor get "Pwr Consumption"
Locating sensor record...
Sensor ID              : Pwr Consumption (0x76)
 Entity ID             : 7.1
 Sensor Type (Threshold)  : Current
 Sensor Reading        : 252 (+/- 0) Watts
 Status                : ok
 Lower Non-Recoverable : na
 Lower Critical        : na
 Lower Non-Critical    : na
 Upper Non-Critical    : 1106.000
 Upper Critical        : 1218.000
 Upper Non-Recoverable : na
 Positive Hysteresis   : Unspecified
 Negative Hysteresis   : Unspecified
 Assertion Events      :
 Assertions Enabled    : unc+ ucr+
 Deassertions Enabled  : unc+ ucr+
```

Is there a reason why the sensor value is converted by `rvitals`?

Thanks!

**Comment by gurevichmark** [comment]
When I try it on one of our machines, all the numbers are either the same or very close :
```
[root@c910f03c17k07 ~]# rvitals c910f04x37 power
c910f04x37: AC Avg Power: 215 Watts (734 BTUs/hr)
c910f04x37: CPU Avg Power: 36 Watts (123 BTUs/hr)
c910f04x37: Chassis Fan Pwr: 3 Watts (10 BTUs/hr)
c910f04x37: Domain A AvgPwr: 75 Watts (256 BTUs/hr)
c910f04x37: Domain B AvgPwr: 80 Watts (273 BTUs/hr)
c910f04x37: MEM Avg Power: 18 Watts (61 BTUs/hr)
c910f04x37: Power Status: on


[root@c910f03c17k07 ~]# ipmitool-xcat -I lanplus -U ADMIN -P xxxxxx -H 10.4.37.254 sdr type 0x03
Chassis Fan Pwr  | 29h | ok  | 21.0 | 3 Watts
CPU Avg Power    | 2Ah | ok  | 21.0 | 38 Watts
MEM Avg Power    | 2Bh | ok  | 21.0 | 18 Watts
Domain A AvgPwr  | 2Ch | ok  | 21.0 | 80 Watts
Domain B AvgPwr  | 2Dh | ok  | 21.0 | 80 Watts
AC Avg Power     | 2Fh | ok  | 21.0 | 225 Watts
[root@c910f03c17k07 ~]#
```

However, I do not get `Pwr Consumption`. 
Can you turn on the debug with `chdef -t site clustersite xcatdebugmode=1` to see which IPMI call is used to get `Pwr Consumption`. Debug off with `chdef -t site clustersite xcatdebugmode=0`

**Comment by kcgthb** [comment]
Sure! Here it is:
```
# chdef -t site clustersite xcatdebugmode=1
1 object definitions have been created or modified.

# rvitals sh-106-01 power
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x06=>App), cmd(0x38=>Get Channel Authentication Capabilities), data=[142, 4]
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x06=>App), cmd(0x3b=>Set session privilege level), data=[4]
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x06=>App), cmd(0x01=>Get Device ID), data=[]
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x0a=>Storage), cmd(0x20=>Get SDR Repository Info), data=[]
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x04=>Sensor/Event), cmd(0x2d=>Get Sensor Reading), data=[107]
sh-106-01: Current 1: 2 Amps
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x04=>Sensor/Event), cmd(0x2d=>Get Sensor Reading), data=[108]
sh-106-01: Current 2: 1.8 Amps
sh-106-01: [ipmi_debug] rvitals: power(power), raw_cmd: netfn(0x04=>Sensor/Event), cmd(0x2d=>Get Sensor Reading), data=[118]
sh-106-01: Pwr Consumption: 396 Watts (1352 BTUs/hr)
sh-106-01: [ipmi_debug] rvitals: stat(power), raw_cmd: netfn(0x00=>Chassis), cmd(0x01=>Get Chassis Status), data=[]
sh-106-01: Power Status: on
sh-106-01: [ipmi_debug] rvitals: stat(power), raw_cmd: netfn(0x06=>App), cmd(0x3c=>Close Session), data=[1, 67, 0, 2]
```

**Comment by gurevichmark** [comment]
Have you tried running something like this to see if you get readings with similar deviations from each other ?
```
while true; do ipmitool ... sdr type 0x03 | grep "Pwr Consumption"; done

**Comment by kcgthb** [comment]
That's a good point, but no, readings are stable over time through both commands:

```
# while true; do ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi sdr type 0x03 | grep Pwr; done
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
Pwr Consumption  | 76h | ok  |  7.1 | 210 Watts
```
```
# while true; do rvitals sh-106-01 power | grep Pwr ; done
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
sh-106-01: Pwr Consumption: 330 Watts (1126 BTUs/hr)
```

Another thing that also indicates that the value reported by `rvitals` is somehow converted and not accurate is that we have a power cap set to 300W, so it's very unlikely that the power draw would go over that limit and reach 400+W:

```
# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi dcmi power get_limit

    Current Limit State: Power Limit Active
    Exception actions:   No Action
    Power Limit:         300 Watts
    Correction time:     1000 milliseconds
    Sampling period:     1 seconds

# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi dcmi power reading

    Instantaneous power reading:                   185 Watts
    Minimum during sampling period:                  5 Watts
    Maximum during sampling period:                291 Watts
    Average power reading over sample period:      203 Watts
    IPMI timestamp:                           Wed Nov 13 15:46:51 2019
    Sampling period:                          00000001 Seconds.
    Power reading state is:                   activated
```

**Comment by cxhong** [comment]
what level of firmware on your system?  are those x86_64 nodes, right?

**Comment by cxhong** [comment]
that's the formula we used to calculate the value:
```
$value = (($sdr->M * $reading) + ($sdr->B * (10**$sdr->B_exp))) * (10**$sdr->R_exp);
```
The each value of $sdr is located at the `/var/cache/xcat/sdr_$mfg_id.$prod_id.$device_id.$dev_rev.$fw_rev1.$fw_rev2`,  this file is not readable.
That's the value I got when I add debug code to dump those value
````
use Data::Dumper;
print Dumper($sdr->id_string,$sdr->M,$sdr->B,$sdr->B_exp,$sdr->R_exp);
output:
$VAR1 = 'AC Avg Power';
$VAR2 = 5;
$VAR3 = 0;
$VAR4 = 0;
$VAR5 = 0;
````
The `$reading` value is what we read from ipmitool 
```
# ipmitool-xcat -H 10.4.37.254 -U ADMIN -P ADMIN raw 0x04 0x2d 47   <---- 47 is AC Avg Power
 28 c0 c0
````
hex 28 is 40 for dec.   40 * 5 = 200 Watts
````
]# rvitals c910f04x37 power
c910f04x37: AC Avg Power: 200 Watts (683 BTUs/hr)   <--- looks correct
c910f04x37: CPU Avg Power: 44 Watts (150 BTUs/hr)
c910f04x37: Chassis Fan Pwr: 3 Watts (10 BTUs/hr)
c910f04x37: Domain A AvgPwr: 80 Watts (273 BTUs/hr)
c910f04x37: Domain B AvgPwr: 80 Watts (273 BTUs/hr)
c910f04x37: MEM Avg Power: 14 Watts (48 BTUs/hr)
c910f04x37: Power Status: on
````
Didn't find any nodes has `Pwr Consumption` value.  can u issue a raw command to get the value:
```
ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi raw 0x04 0x2d 118
```

**Comment by kcgthb** [comment]
Hi @cxhong, thanks for following up, and for the explanations!
> what level of firmware on your system? are those x86_64 nodes, right?
Latest available firmware from the vendor. Those are [Dell C6420](https://www.dell.com/en-us/work/shop/povw/poweredge-c6420) x86_64 nodes:
```
# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi mc info
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 3.36
IPMI Version              : 2.0
Manufacturer ID           : 674
Manufacturer Name         : DELL Inc
Product ID                : 256 (0x0100)
Product Name              : Unknown (0x100)
Device Available          : yes
Provides Device SDRs      : yes
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    Bridge
    Chassis Device
Aux Firmware Rev Info     :
    0x00
    0x15
    0x24
    0x24
```

Here are the raw command results:
```
# ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H sh-106-01.ipmi raw 0x04 0x2d 118
 0a c0 c0
```

**Comment by kcgthb** [comment]
Additional information: this discrepancy seems to only happen on specific models, namely C6420 nodes (it works great on Dell C6320s, Dell R630s, R640s, and everything else I could test).

The only issue is with Dell C6320 nodes, and even more interestingly, on just 2 nodes out of those 4-node chassis. Here's an example:

```
# n=sh-106-[01-04]
# for n in $(cluset -e $n); do 
    echo -n "$n: "
    echo -n "$(rvitals $n power | awk '/Pwr/ {print $4}')|"
    ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H $n.ipmi sdr type 0x03 | awk '/Pwr/ {print $10}' done
sh-106-01: 264|168
sh-106-02: 280|280
sh-106-03: 352|224
sh-106-04: 252|252 
```
Those 4 nodes are in the same chassis. For 2 of them (`sh-106-[02,04]`) the values are consistent between `rvitals` and the IPMI SDR sensor value. For the two others (sh-106-[01,03]`), it's not.

Interestingly enough, `ipmitool` is able to produce the right value for all the nodes in the chassis, but `rvitals` doesn't.

**Comment by cxhong** [comment]
can u check `/var/cache/xcat`?  wonder if there are older files left over.  maybe you should clean up all, first time run `rvital` command will create those files again.

**Comment by kcgthb** [comment]
Ooh, very good point!
First, I removed the contents of `/var/cache/xcat` on the Master Node, but it didn't change anything.
Then, because we're running in a hierarchical setup, I went to check and delete the contents of `/var/cache/xcat` on all the service nodes, and that seems to have fixed the issue!
Now:
```
# n=sh-106-[01-04]; 
# for n in $(cluset -e $n); do 
    echo -n "$n: "
    echo -n "$(rvitals $n power | awk '/Pwr/ {print $4}')|"
   ipmitool -I lanplus -U root -P $IPMI_PASSWORD -H $n.ipmi sdr type 0x03 | awk '/Pwr/ {print $10}'
done
sh-106-01: 294|294
sh-106-02: 140|140
sh-106-03: 280|280
sh-106-04: 266|266
```
All the nodes report the correct power consumption value through `rvitals`.

Now that prompts the question: shouldn't old cached file be removed (or at least ignored)  if they're too old? Also more importantly, are those cache files unique for each node? 

I found cache files named `sdr_674.256.32.1.3.36`. I can guess that:
* 674 is the node's manufacturer ID
* 256 is the node's product ID
* 32.1 is the device ID and revision
* 3.36 is the BMC firmware version

But there doesn't seem to be anything unique to the node being queried. Doesn't that mean that all identical nodes that have the same firmware version will end up using the same cache file? Is that intended?

**Comment by cxhong** [comment]
Actually, there is a `site` table  attribute ` ipmisdrcache`, you can set it to `no`, so it will not cache locally.
The default value is `yes` so xCAT will cache the sdr file locally in normal case.  
It doesn't seem to be unique to the node,  hopefully sdr contexts are same for same firmware version with same manufacture ID, product ID and device ID.

**Comment by kcgthb** [comment]
Oh ok, I see: the cache file only contains the sensors list, not the sensor values, so it should be ok to use the same cache file for multiple identical nodes.

Now, it looks like some of the old cache files was causing issues. Meaning it was likely used but shouldn't have.

On the service node for `sh-106-01`, the cache dir contained these files:
```
sdr_10876.2195.32.1.3.113
sdr_674.256.32.1.2.99
sdr_674.256.32.1.3.54
```
But `sh-106-01`'s BMC firmware version is 3.36, so none of the cache files should have been used.
Yet, removing all the cache files from the service node solved the issue.

Is there some sort of substring matching for cache files that could have caused this?

**Comment by cxhong** [comment]
for `sh-106-01`,  the matching file is sdr_674.256.32.1.3.54
`Firmware Revision         : 3.36`
somehow, it treats 36 as Hex,  so decimial is 54

**Comment by kcgthb** [comment]
Ah, that's confusing :)

**Comment by kcgthb** [comment]
Closing this as it was not an xCAT issue.
But still, I'm glad I asked, I learned a lot in the process :)
