### ISSUE TITLE
[FVT] Can't test multi-disks with WWNs for no suitable machine.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#648]
As design: https://github.com/xcat2/xcat-core/wiki/determine_install_disk,
we should test the multi-disks with WWNs to cover the fresh and reinstall checkpoints, but now without suitable machine to test, just open a issue to track it.

**Comment by zet809** [comment]
@caomengmeng Is this still an issue?

**Comment by caomengmeng** [comment]
Find one x86 machine with multi-disks，so close it.
