### ISSUE TITLE
Console logs reset every Sunday at 3:26 logging appears to stop 

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#6485]
Version 2.15 (git commit 86dd65c954220d62eb8d1765b989a63b016d0437, built Tue Nov  5 01:37:14 EST 2019)
We see our logs get reset every Sunday at 03:26am on our clusters running goconserver.
On c685mgt03 I increased gocons logging and see in 

{"file":"github.com/xcat2/goconserver/console/server.go (383)","level":"info","msg":"Handle signal: hangup, reload configuration file\n","time":"2019-11-03T03:36:01-05:00"}

After this all logs are restarted and empty but we believe we are missing data.

**Comment by gurevichmark** [comment]
This appears to the be issue that added log rotation: https://github.com/xcat2/goconserver/issues/11

**Comment by gurevichmark** [comment]
@markprez Do you see the rotated out logs, like `/var/log/consoles/<node>.log-<date>` in addition to `/var/log/consoles/<node>.log` ? Are both logs zero size ?

**Comment by cxhong** [comment]
@markprez , looking the `/var/log/consoles`,   I saw the file rotated every 7 days.
```
[root@mgt03 nodes]# ls -ltr /var/log/consoles/f4n01*
-rw------- 1 root root    113 Oct 17 11:05 /var/log/consoles/f4n01.log-20191020
-rw------- 1 root root      0 Oct 20 03:33 /var/log/consoles/f4n01.log-20191027
-rw------- 1 root root 623925 Nov  2 18:16 /var/log/consoles/f4n01.log-20191103
-rw------- 1 root root 315105 Nov  8 12:06 /var/log/consoles/f4n01.log-20191110
-rw------- 1 root root 309432 Nov 13 21:34 /var/log/consoles/f4n01.log
[root@mgt03 nodes]# ls -ltr /var/log/consoles/c685f8ufm6*
-rw------- 1 root root 1022026 Oct 20 03:32 /var/log/consoles/c685f8ufm6.log-20191020
-rw------- 1 root root 3579206 Oct 27 03:46 /var/log/consoles/c685f8ufm6.log-20191027
-rw------- 1 root root 3587386 Nov  3 03:25 /var/log/consoles/c685f8ufm6.log-20191103
-rw------- 1 root root 3564458 Nov 10 03:19 /var/log/consoles/c685f8ufm6.log-20191110
-rw------- 1 root root 2779200 Nov 15 13:52 /var/log/consoles/c685f8ufm6.log
````
U mean some logs didn't log to above files?

**Comment by gurevichmark** [comment]
@markprez You can use this to list `goconserver` connections:
1. `yum install lsof` if not already there
2. Get the pid of `goconserver` process: `ps -ef | grep goconserver`
3. List all the current connections: `lsof -p <goconserver pid> | grep "TCP" | grep "ESTABLISED"`

The output should look something like:
```
[root@stratton01 ~]# lsof -p 90131 | grep "TCP" | grep "ESTABLISHED"
goconserv 90131 root   12u     IPv4         1486734053        0t0        TCP stratton01.pok.stglabs.ibm.com:36730->f5u16-bmc:ici (ESTABLISHED)
goconserv 90131 root   17u     IPv4         1589845332        0t0        TCP stratton01.pok.stglabs.ibm.com:43924->f5u14-bmc:ici (ESTABLISHED)
goconserv 90131 root   33u     IPv4         1488430899        0t0        TCP stratton01.pok.stglabs.ibm.com:39886->f6u13-bmc:ici (ESTABLISHED)
goconserv 90131 root   49u     IPv4         1487903146        0t0        TCP stratton01.pok.stglabs.ibm.com:58286->f6u07-bmc:ici (ESTABLISHED)
[root@stratton01 ~]#
```

**Comment by gurevichmark** [comment]
There is also a log file `/var/log/goconserver/server.log` that has log of `goconserver`, it appears to contain connect and disconnect attempts.

**Comment by cxhong** [comment]
I found the conf file for logrotate  `/etc/logrotate.conf`.  It configured rotate log files weekly.
```
# cd /etc/logrotate.d/
[root@c910f03c17k07 logrotate.d]# ls -ltr
total 48
-rw-r--r--. 1 root root   32 Dec  9  2013 up2date
-rw-r--r--  1 root root  893 Jun  8  2017 mariadb
-rw-r--r--. 1 root root  160 Sep 15  2017 chrony
-rw-r--r--. 1 root root   91 Jan  8  2018 bootlog
-rw-r--r--. 1 root root  100 Jun  1  2018 wpa_supplicant
-rw-r--r--  1 root root  194 Jun 22  2018 httpd
-rw-r-----  1 root named 514 Jun 24  2018 named
-rw-r--r--. 1 root root  103 Jul 17  2018 yum
-rw-r--r--. 1 root root  224 Jul 30  2018 syslog
-rw-r--r--. 1 root root   71 Jul 30  2018 subscription-manager
-rw-r--r--  1 root root  243 May 12  2019 goconserver
-rw-r--r--  1 root root  442 Nov  4 15:17 xcat
[root@c910f03c17k07 logrotate.d]# cat goconserver
/var/log/consoles/*.log
/var/log/goconserver/server.log
{
    missingok
    sharedscripts
    postrotate
        kill -HUP `systemctl show -p MainPID goconserver.service 2> /dev/null |awk -F= '{print $2}'` 2> /dev/null || true
    endscript
}
```
so, for the goconserver, `/var/log/consoles/*.log` and `var/log/goconserver/server.log` will rotate on weekly base

**Comment by cxhong** [comment]
Here is man page for lograte:  https://linux.die.net/man/8/logrotate
maybe need to add `copytruncate` ?
