### ISSUE TITLE
RHEL 7 stateless boot doesn't fetch image after kernel boots

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#6490]
I am trying to clone an osimage/stateless boot environment from one system to another. I have a the identical HW booting diskless on system A and when i copied the osimage and linuximage definitions over to system B, the image built fine.  I manually (via tabedit) added the node to covnert to diskless on system B to the xcat tables. I ran nodeset and makedhcp -a and -n and all completed. I then tried to boot the node and it started to come up, got it's initrd and kernel via http, but then stopped. It never tried to get it's image(rpm.cpio.gz) and continue bootup. I wiresharked the working side and the tftpget of xnba.kpxe looks the same on both as well as all the http gets. Difference being the working side does an additional httpget for rpm.cpio.gz and extracts it.  The non-working side eventually drops me to a dracut shell. 

My bootparams is empty for all nodes.

I have run into this issue before several times in the past, most notably [here ](https://github.com/xcat2/xcat-core/issues/6372), but x2APIC is disabled in the BIOS already so its not related. Any help would be great and some advice on avoiding this in the future.

**Comment by cxhong** [comment]
is image available for this osimage?  looking for your osimage's `rootimgdir` attribute,  and should be define in the ` linuximage` table.   you can run `tabdump nodetype` and `tabdump linuximage` to check if those are set correctly.
after ran `nodeset` or `rinstall`,  check `tftpboot` dir also, you should see three files relate to this node under `/tftpboot/xcat/xnba/nodes`
```
# ls -ltr /tftpboot/xcat/xnba/nodes
total 36
-rw-r--r-- 1 root root 115 Nov 21 04:40 c910f04x37v09.uefi
-rw-r--r-- 1 root root 394 Nov 21 04:40 c910f04x37v09.elilo
-rw-r--r-- 1 root root  18 Nov 21 04:49 c910f04x37v09
-rw-r--r-- 1 root root 115 Nov 21 06:02 c910f04x37v10.uefi
-rw-r--r-- 1 root root 394 Nov 21 06:02 c910f04x37v10.elilo
-rw-r--r-- 1 root root 502 Nov 21 06:02 c910f04x37v10
# cat c910f04x37v10
#!gpxe
#netboot rhels7.6-x86_64-compute
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/osimage/rhels7.6-x86_64-netboot-compute/kernel
imgload kernel
imgargs kernel imgurl=http://10.4.37.9:80//install/netboot/rhels7.6/x86_64/compute/rootimg.cpio.gz XCAT=10.4.37.9:3001 NODE=c910f04x37v10 FC=0 XCATHTTPPORT=80  console=tty0 console=ttyS0,115200n8r selinux=0  BOOTIF=01-${netX/machyp}
imgfetch http://${next-server}:80/tftpboot/xcat/osimage/rhels7.6-x86_64-netboot-compute/initrd-stateless.gz
imgexec kernel
```

**Comment by kjhee43** [comment]
@cxhong, yes, the rootimg.cpio.gz file is there and available. it is properly defined in osimage and linuximage and looking at lsdef-t node <nodename> compared to the working node looks correct. /tftpboot/xcat/xnba/nodes/ has all the files and their contents looks correct.

**Comment by kjhee43** [comment]
Update: so the node that is working is booting from a 1G copper interface with an "interface=eth1" in the node definition, even though when it finishes booting the interface is named in a RHEL7 style (enp...). The interface that the non-working node is booting from is a 10G NIC also with an "interface=eth1" in the node definition. 

After the node stops trying to boot it drops into a dracut shell, If i do an ifconfig i see the interface enp(something) but it does NOT have an IP on it. This seems like the issue but I am not sure why it is happening.

**Comment by cxhong** [comment]
It should use `installnic=mac`,  that will boot up from whichever interfaces has that mac address.  
in the message.log, did u see DHCP request from this node's mac address?  
check `nslookup <nodename>` also
then `makedhcp -q <nodename>` to verify the dhcp lease

**Comment by kjhee43** [comment]
![Screenshot_20191121-163428](https://user-images.githubusercontent.com/47122186/69378988-79ac4600-0c7d-11ea-864f-a48e7a38432a.jpg)

**Comment by cxhong** [comment]
the provision node and Management node on the different subnet? 
![image](https://user-images.githubusercontent.com/12398836/69380664-f1c83b00-0c80-11ea-9fca-ae783b392e0f.png)
can  ip address resolvable?  

Anyway,  after that, this line `imgargs kernel imgurl=........` defined in the `/tftpboot/xcat/xnba/nodes/cds1` should be run.  make sure `imgurl` is available.
can u issue following command, will be easier for me to check?
```
lsdef cds1
cat /tftpboot/xcat/xnba/nodes/cds1
lsdef -t osimage con-rhel76
ls -ltr <rootimgdir of con-rhel76>
```

**Comment by kjhee43** [comment]
Yes, the management node and provision node are different subnets. This management node provisions a variety of hosts across many different subnets. In fact all the nodes it provisions are in different subnets than the management node. Routing is set up properly. 

I understand the imgurl command should execute, but it doesn't. That is what I am trying to explain.  i will get the command output.

**Comment by kjhee43** [comment]
I was able to get the log from the boot and it appears it is a DHCP error. it dhcp'd the first time successfully but the second DHCP fails

```
[    8.465786] localhost kernel: ixgbe 0000:83:00.0 enp131s0f0: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[    8.466300] localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): enp131s0f0: link becomes ready
[    8.199777] localhost dracut-initqueue[1290]: dhcp: PREINIT enp131s0f0 up
[    8.220778] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 4 (xid=0x5ca7d2ef)
[   12.336427] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 9 (xid=0x5ca7d2ef)
[   20.620826] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 9 (xid=0x5ca7d2ef)
[   30.495590] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 13 (xid=0x5ca7d2ef)
[   43.014521] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 17 (xid=0x5ca7d2ef)
[   59.869592] localhost dhclient[6986]: DHCPDISCOVER on enp131s0f0 to 255.255.255.255 port 67 interval 9 (xid=0x5ca7d2ef)
[   69.301753] localhost dhclient[6986]: No DHCPOFFERS received.
[   69.301990] localhost dhclient[6986]: No working leases in persistent database - sleeping.
[   69.325190] localhost dracut-initqueue[1290]: dhcp: FAIL
```
Why would this happen after it successfully DHCPd the first time?

**Comment by cxhong** [comment]
have you figure out what's wrong with mac address?

**Comment by kjhee43** [comment]
@cxhong, no, i hanve't. I was hoping you or someone else had an idea.  Am i seeing it correctly though?

**Comment by cxhong** [comment]
can u show me `lsdef cds1` and `xcatprobe  detect_dhcpd -i <MN interface name > -m 01:00:e0:ed:91:cd:41` ?

**Comment by kjhee43** [comment]
This makes no sense. you can see above it DHCPs fine but xcatprobe is saying 

``` xcatprobe detect_dhcpd -i br0 -m 00:E0:ED:91:CD:41
Start to detect DHCP, please wait 10 seconds                              [INFO]
++++++++++++++++++++++++++++++++++                                        [INFO]
There are 0 servers replied to dhcp discover.                             [INFO]
++++++++++++++++++++++++++++++++++                                        [INFO]
```
lsdef
```

 lsdef cds1
Object name: cds1
    arch=x86_64
    currstate=netboot rhel7.6-x86_64-compute
    groups=all,cds
    interface=eth1
    mac=00:E0:ED:91:CD:41
    monserver=172.16.10.12
    netboot=xnba
    nfsserver=172.16.10.12
    nicextraparams.eth1=DHCPPROTO=none
    nicips.eth1=192.168.222.5
    nictypes.eth1=Ethernet
    os=rhel7.6
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,confignetwork -s
    primarynic=eth1
    profile=compute
    provmethod=con-rhel76
    routenames=cds
    tftpserver=172.16.10.12
    updatestatus=syncing
    updatestatustime=05-10-2019 10:23:49
    xcatmaster=fserv01
```
/var/lib/dhcpd/dhcpd.leases

```
host cds1 {
  dynamic;
  hardware ethernet 00:e0:ed:91:cd:41;
  uid 00:e0:ed:91:cd:41;
  fixed-address 192.168.222.5;
        supersede server.ddns-hostname = "cds1";
        supersede host-name = "cds1";
        if option user-class-identifier = "xNBA" and option
             client-architecture = 00:00 {
          supersede server.always-broadcast = 01;
          supersede server.filename =
                  "http://172.16.10.12:80/tftpboot/xcat/xnba/nodes/cds1";
        } elsif option user-class-identifier = "xNBA" and option
                client-architecture = 00:09 {
          supersede server.filename =
                  "http://172.16.10.12:80/tftpboot/xcat/xnba/nodes/cds1.uefi";
        } elsif option client-architecture = 00:07 {
          supersede server.filename = "xcat/xnba.efi";
        } elsif option client-architecture = 00:00 {
          supersede server.filename = "xcat/xnba.kpxe";
        } else {
          supersede server.filename = "";
        }
        supersede server.next-server = ac:10:0a:0c;
```

Also, i checked the MAC of the nic that appears when in the dracut shell and it matches what's in the node definition. So maybe those kernel messages are not related. But it still doesn't explain why it can't dhcp when it works in PXE.

**Comment by cxhong** [comment]
I think there are network configure issue.  since compute node and MN node on different subnet, are u sure compute node `192.168.x.x` can talk to MN node `172.16.x.x`?
```
01:00:e0:ed:91:cd:41 - original mac address    <---nic for 192.168.x.x?
     00:e0:ed:91:cd:44  - value seen in kernel     <--- nic for 172.16.x.x?
```
I think provision network should be on 172.16 subnet, and you can use `confignetwork` postscripts to set up `192.168` subnet for compute node.   

To verify if compute node can talk to MN node
```
rinstall computenode shell
rcons computenode
```
the rcons will get into the shell,  you can run ipaddr command to check the interface.

**Comment by kjhee43** [comment]
@cxhong I am 100% sure compute node can talk to MN. there is a disk with on OS installed and i can boot that OS and ping the MN once it is up. Also, the DHCP gets there in PXE, at the beginning of the boot sequence.

**Comment by kjhee43** [comment]
@cxhong, why is xcatprobe reporting "There are 0 servers replied to dhcp discover."?

**Comment by cxhong** [comment]
well, `0 servers` means there are no dhcp server  servers this mac address,   your network must has something wrong with.  the netboot sequence is different for each boot process.  It is very possible It may works before, but can't work know.  

1) Is mac address correctly?
```
lsdef cds1
Object name: cds1
    arch=x86_64
    currstate=netboot rhel7.6-x86_64-compute
    groups=all,cds
    interface=eth1
    mac=00:E0:ED:91:CD:41   <--- did u use `01:00:e0:ed:91:cd:41` ?
    monserver=172.16.10.12
    netboot=xnba
    nfsserver=172.16.10.12
```
2) can u issue xcatprobe command for both `00:e0:ed:91:cd:41` and `00:e0:ed:91:cd:44`?
3) `ip addr show` of MN interface
4) `tabdump networks` output
5) please show me the output from here:
```
rinstall computenode shell
rcons computenode
```
`ip addr show` from rcons  on compute node
6) output of `nslookup cds1`
