### ISSUE TITLE
Document the order of execution for the postscripts in the RTD to help users 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6512]
In 1Q2019, I spent some time to gather information about the order of the postscript running under xCAT...and the differences between diskful and diskless installs.   I never had a chance to get this integrated into our RTD documentation, but this graphic may be helpful for xCAT users to see the flow...  

There has also been changes made to the xCAT logging messages to be able to grep for the postscript processing and see the order of execution.

![image](https://user-images.githubusercontent.com/10049070/71093742-cf3e1a80-2177-11ea-8dba-30161a537fc3.png)

For internal team, issue 145 in our team_process repo contains the back and forth discussion to get to this conclusion.

**Comment by gurevichmark** [comment]
Should probably be inserted somewhere into this section: https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/post_script.html

**Comment by besawn** [comment]
I agree, thanks.
