### ISSUE TITLE
bmcdiscover logs passwords to /var/log/messages

### ISSUE THREAD

**Issue by datakid** [xcat2/xcat-core#6516]
bmcdiscover --version
bmcdiscover - xCAT Version 2.15 (git commit
218c6d3acc8bdbd7f72115e48cda2b1a3613d18a, built Mon Nov  4 15:17:59
EST 2019)

bmcdiscover logs the passwords passed with -p

Looking through /var/log/messages on another mission, I noticed our
root password. Someone had forgotten which pw combo they were meant to
be using with bmcdiscover.

There are two potential solutions, and potentially both could be used.

-  the [bmcdiscover documentation](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man1/bmcdiscover.1.html) [(git)](https://github.com/xcat2/xcat-core/blob/master/docs/source/guides/admin-guides/references/man1/bmcdiscover.1.rst) should note that passwords passed on
the command line will be logged (responsible disclosure) 

- bmcdiscover to redact passwords passed on the command line in logs

**Comment by gurevichmark** [comment]
@datakid  Can you show what entry containing the password that gets logged for you into `/var/log/messages` ? 

Is it something like:
`xCAT: Allowing bmcdiscover --range xxxxx -p xxxxxx -u root -w -z for root from localhost` ?

**Comment by datakid** [comment]
@gurevichmark sorry, only back at work now. It did look something like that. I can't be more specific because the responsible party did a thorough cleaning job on the logs.

**Comment by gurevichmark** [comment]
There are two log files that could have xCAT commands logged with potentially exposed passwords: `messages.log` and `commands.log`. The logging is done from `xCAT-server/lib/perl/xCAT/xcatd.pm` and `xCAT-server/sbin/xcatd` respectively.

The following xCAT commands take password as an option:
* `bmcdiscover -p <passwd>`
* `mkhwconn -P <passwd>`
* `pasu -p <passwd>`
* `rspconfig `
    * `admin_passwd=<passwd,passwd>`
    * `HMC_passwd=<passwd,passwd>`
    * `general_passwd=<passwd,passwd>`
    * `*_passwd=<passwd,passwd>`
    * `USERID=<passwd,passwd>`

Proposed solution is to create a table with command and its flag. A routine will then check the table and redact the option that follows the flag for matching command.
