### ISSUE TITLE
Bad "mlx_en" module load

### ISSUE THREAD

**Issue by arjones85** [xcat2/xcat-core#6523]
When running genimage mlx_en fails to install:

Try to load drivers: tg3 bnx2 bnx2x e1000 e1000e igb mlx_en virtio_net be2net ext3 ext4 to initrd.
chroot /install/osimages/<image>/rootimage/rootimg dracut  -f /tmp/initrd.12252.gz 3.10.0-1062.el7.x86_64
No '/dev/log' or 'logger' included for syslog logging
Turning off host-only mode: '/sys' is not mounted!
Turning off host-only mode: '/proc' is not mounted!
Turning off host-only mode: '/run' is not mounted!
Turning off host-only mode: '/dev' is not mounted!
Failed to install module mlx_en
the initial ramdisk for stateless is generated successfully.

I can see in the genimage code where it tries to push that module into the initrd. My OFED drivers are installed via the postinstall file and complete the installation successfully . 

The mlx4_en driver is loaded properly on nodes when they boot. The genimage code looks like it checks for "mlx4_en.ko" when, after OFED install, it's "mlx4_en.ko.xz" in my rootimage.

**Comment by cxhong** [comment]
you can ignore that message.  It was there for older version of drivers.  If there is a `mellanox/mlx4`, it will be replaced by `mlx4_en`.
