### ISSUE TITLE
SLE 15 insserv-compat dependency missing

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/xcat-core#6525]
Hi,

SLE 15 needs the `insserv-compat` package which provides the `/lib/lsb/init-functions` file needed for xcatd.
Otherwise xCAT fails to start with `Error, don't know how to start on this platform`. See: https://github.com/xcat2/xcat-core/blob/master/xCAT-server/etc/init.d/xcatd#L56-L74

Please add it as a RPM dependency for SLE 15.

**Comment by cxhong** [comment]
the `insserv-compat` is in the Sle15
```
 # zypper info insserv-compat
Loading repository data...
Reading installed packages...


Information for package insserv-compat:
---------------------------------------
Repository     : Basesystem-Module 15-0
Name           : insserv-compat
Version        : 0.1-2.15
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 8.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : insserv-compat-0.1-2.15.src
Summary        : Simple insserv replacement for systemd only systems
Description    :
    insserv is used enable System V init scripts. This package only
    contains a stub implemenation for use on systemd only systems.
```
for sle15, we need to two iso file
```
-rw-r--r--   1 root root  622336000 Jan  2 15:19 SLE-15-Installer-DVD-ppc64le-GM-DVD1.iso
-rw-r--r--   1 root root 5059958784 Jan  2 15:20 SLE-15-Packages-ppc64le-GM-DVD1.iso
```
did u run copycds for both iso?

**Comment by cxhong** [comment]
just checking my branch again,  actually, I put `insserv` to my pkglist.  I will check in the files, should be available tomorrow's dev build.

**Comment by Obihoernchen** [comment]
I know `insserv-compat` is in SLE-15 and I have no issue obtaining it.
I'm talking about adding this as a dependency to the `xcatd` RPM.

**Comment by Obihoernchen** [comment]
`net-tools-deprecated` should be a dependency for SLE15 RPMs, too.

**Comment by cxhong** [comment]
it merged in the PR https://github.com/xcat2/xcat-core/pull/6528

**Comment by Obihoernchen** [comment]
@cxhong no I'm talking about the xCAT RPMs not the pkglists. The main xCAT RPM (for the installation on the master node) needs these dependencies for SLE15, too.

**Comment by cxhong** [comment]
If the packages come with OS , we will not put into xCAT dependencies .  SLE15 has `net-tools-deprecated` package available, we just need to include it into SLE15 pkglist.  it will be installed after node is provisioned.

**Comment by Obihoernchen** [comment]
No I'm not talking about nodes you provision with xCAT. I'm talking about the master management node. This node needs these packages as well and they are not installed by default and also not installed when installing xCAT via `go-xcat` or directly via `zypper`. The xCAT RPMs itself should have both dependencies.

**Comment by cxhong** [comment]
I can add the requirement to xCAT spec file.   currently install `net-tools-deprecated` is a workaround,  we need to work on replace `netstat`, `route`, etc commands in the xcat code.

**Comment by Obihoernchen** [comment]
Yes please add  `net-tools-deprecated` and `insserv-compat` until  xCAT moves to modern net tools and systemd.

**Comment by JunkyDeveloper** [comment]
I also had problems with SLES15.3!
Please fix that! it took to much time to find this issue.
After installing these two packages we had no problems anymore
