### ISSUE TITLE
ifconfig, netstat, route commands are not available on SLE15

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#6527]
xCAT is using some of commands from net-tools package, but in the SLE15, 'net-tools' will move to the so called 'legacy' module. The 'legacy' module is for outdated/deprecated software that still can be installed and used (for some time) but in the end it will fade out of support in SLE15.

commands from `net-tools` package on SLES12
```
c910f03c09k12:~ # rpm -ql net-tools-1.60-764.185.ppc64le | grep bin
/bin/dnsdomainname
/bin/domainname
/bin/hostname
/bin/netstat
/sbin/arp
/sbin/ether-wake
/sbin/ifconfig
/sbin/ipmaddr
/sbin/iptunnel
/sbin/nameif
/sbin/plipconfig
/sbin/rarp
/sbin/route
/sbin/slattach
```
On SLE15, those commands are not avaiable
```
# netstat -i
-bash: netstat: command not found

# ifconfig
-bash: ifconfig: command not found

# route
-bash: route: command not found
```
needs to intestate how many xCAT commands failed due to `net-tools` packages is not available on SLE15

**Comment by Obihoernchen** [comment]
This affects `makedhcp` as well.
Furthermore, please check `/etc/dhcpd.conf`. Looks like xCAT creates `/etc/dhcp/dhcpd.conf` only.
I had to create a symlink `/etc/dhcpd.conf -> /etc/dhcp/dhcpd.conf` manually.

**Comment by cxhong** [comment]
Thanks, @Obihoernchen .  I noticed too.  Will open a PR soon.
