### ISSUE TITLE
How to use xCAT without DHCP?

### ISSUE THREAD

**Issue by MasterGroosha** [xcat2/xcat-core#6532]
Let's say we have multiple clusters around the world. Every cluster would have its own DHCP server, but there will be the one central xCAT management node.
I think it's possible to set MAC addresses for each node beforehand, but I cannot do anything about DHCP on remote clusters.

Sorry if this question sounds to vague, but is it possible to manage xCAT on remote clusters without DHCP? For example, provision nodes via Internet using remote TFTP server and setting Service node IP manually.

**Comment by gurevichmark** [comment]
@MasterGroosha Questions like this are better posted to the xCAT mailing list at https://sourceforge.net/p/xcat/mailman/xcat-user/. You will probably reach a wider audience there.
