### ISSUE TITLE
SLE15 detection is broken

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/xcat-core#6534]
SLE15 replaced `/etc/SuSE-release` with `/etc/os-release`.

Example: https://github.com/xcat2/xcat-core/pull/6533

**Comment by cxhong** [comment]
Thanks, @Obihoernchen ,  there are few more place/commands we need to check too.

**Comment by Obihoernchen** [comment]
confignetwork: https://github.com/xcat2/xcat-core/blob/master/xCAT/postscripts/confignetwork#L42

**Comment by cxhong** [comment]
@Obihoernchen , are u working on hierarchy support for sle15 too?
