### ISSUE TITLE
IC922 node support

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6541]
- [x] Support for IC922 nodes needs to be added to scripts like `bmcdiscover`, `bmcsetup` and `getipmi`.

Currently those scripts assume that the only nodes that are openbmc controlled, are machines with manufacturer id of `42817` and product id of `16975`. However, IC922nodes are also openbmc controlled and have a manufacturer id of `42817` and product id of ` 0x01`

- [ ] Support for IC922 need to be added to commands `rvitals leds` and `rbeacon`. Those commands get data from `/led/physical`, which has different paths for IC922 vs. AC922.

**Comment by gurevichmark** [comment]
Mihawks have their own fw drivers, stored at
https://rchweb.rchland.ibm.com//afs/rchland/projects/esw/op9mihawkPkg/Builds/93m.2001.20200107a/logs/status.html

**Comment by gurevichmark** [comment]
[ ] Currently `ipmitool mc info` returns zeros for manufacturer id and product id. Waiting for a new fw driver to fix that.
[ ] Mihawk does not have `/inventory/system/chassis/motherboard/boxelder/bmc` which is used by bmcdiscover to get model and serial numbers if chassis has not been powered on (`/inventory/system` returns error). It appears to have `/inventory/system/chassis/motherboard/tcm` which returns needed info.

**Comment by gurevichmark** [comment]
With a new driver `mihawk-ga1-0-g1e3741c-dirty` the Mihawk now reports correct `Manufacturer ID` and `Product ID`:
```
ipmitool -H 192.168.95.165 -U root -P 0penBmc -I lanplus mc info
Device ID                 : 0
Device Revision           : 0
Firmware Revision         : 0.00
IPMI Version              : 2.0
Manufacturer ID           : 42817
Manufacturer Name         : Unknown (0xA741)
Product ID                : 1 (0x0001)
Product Name              : Unknown (0x1)
Device Available          : yes
Provides Device SDRs      : yes
Additional Device Support :
    Sensor Device
    SEL Device
    FRU Inventory Device
    Chassis Device
Aux Firmware Rev Info     : 
    0x00
    0x00
    0x00
    0x00
```

This allows `bmcdiscover` to find Mihawk BMC:
```
ipmitool -H 192.168.95.165 -U root -P 0penBmc -I lanplus mc info
Device ID                 : 0
Device Revision           : 0
Firmware Revision         : 0.00
IPMI Version              : 2.0
Manufacturer ID           : 42817
Manufacturer Name         : Unknown (0xA741)
Product ID                : 1 (0x0001)
Product Name              : Unknown (0x1)
Device Available          : yes
Provides Device SDRs      : yes
Additional Device Support :
    Sensor Device
    SEL Device
    FRU Inventory Device
    Chassis Device
Aux Firmware Rev Info     : 
    0x00
    0x00
    0x00
    0x00
```

If BMC is reset, the `bmcdiscover` correctly instructs the user to change the password:
```
# bmcdiscover --range 192.168.95.165 -u root -p 0penBmc -z
192.168.95.165: The password provided for this account must be changed before access is granted
Run script '/opt/xcat/share/xcat/scripts/BMC_change_password.sh' to change default password
Rerun 'bmcdiscover' command with '-p new_bmc_password' flag
Warning: [xcat1]: No bmc found.
(0) root @ xcat1: /root
#
```

**Comment by gurevichmark** [comment]
Verifying `bmcsetup`.

* bmcdiscover create this node definition:
```
# lsdef node-9183-22x-78002ba
Object name: node-9183-22x-78002ba
    bmc=192.168.95.165
    bmcpassword=0penBmc123
    bmcusername=root
    cons=openbmc
    groups=all
    hwtype=bmc
    mgt=openbmc
    mtm=9183-22X
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=78002BA
```

* predefined node definition:
```
# lsdef mihawk-gurevich
Object name: mihawk-gurevich
    arch=ppc64le
    bmc=192.168.95.160
    bmcpassword=0penBmc123
    bmcusername=root
    chain=bmcsetup
    cons=openbmc
    cpucount=96
    cputype=POWER9, altivec supported
    disksize=sda:894GB,sdb:894GB
    groups=all
    ip=192.168.95.161
    memory=261599MB
    mgt=openbmc
    mtm=9183-22X
    netboot=petitboot
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=78002BA
    status=powering-off
    statustime=02-07-2020 14:57:50
    supportedarchs=ppc64le


```

**Comment by krono** [comment]
Hi, it is nice that IC922 support is available.
However `bmcdiscover` does not find our nodes, as they do not seem to repsond with the expected IDs:

```Bash
# /opt/xcat/bin/ipmitool-xcat -I lanplus -H IC922HOST -U OPENBMCUSER -P OPENBMCPASSWD mc info -N 1 -R 1
Device ID                 : 0
Device Revision           : 0
Firmware Revision         : 0.00
IPMI Version              : 2.0
Manufacturer ID           : 0
Manufacturer Name         : Unknown
Product ID                : 0 (0x0000)
Product Name              : Unknown (0x0)
Device Available          : yes
Provides Device SDRs      : no
Additional Device Support :
Aux Firmware Rev Info     :
    0x00
    0x00
    0x00
    0x00
```
It is, indeed an IC922, as the `fru` tells us:
```Bash
# /opt/xcat/bin/ipmitool-xcat -I lanplus -H IC922HOST -U OPENBMCUSER -P OPENBMCPASSWD  fru list
[...]
FRU Device Description : system (ID 3)
 Chassis Type          : Unspecified
 Chassis Part Number   : 9183-22X
 Chassis Serial        : XXXXXXX
 Board Mfg Date        : Wed Apr  8 14:05:00 2020
 Board Mfg             : IBM
 Board Product         : SYSTEM PLANAR
 Board Serial          : XXXXXXXXXXXX
 Board Part Number     : 01EM903
[...]
```

Are we doing something wrong? can we contribute here?
(FW: `IBM-mihawk-ibm-OP9-v2.4-4.37-prod`, BMC FW: `op940.00.mih-5-0-g86f9791c2`)

**Comment by gurevichmark** [comment]
@krono I think you are missing a FW update mentioned in a comment from Feb 10 above. It fixed the `Manufacturer ID` and `Product ID` valued, which are needed by `bmcdiscover`. I do not know if that version has been GAed.

**Comment by krono** [comment]
@gurevichmark Thanks for your reply. yes it seems so. I cannot find an update in the fixcentral, tho...

**Comment by gurevichmark** [comment]
@krono Not sure when this FW update will be available.
xCAT could still control the IC922 node, but you would need to manually create the node definition (without using `bmcdiscover`) and set some network information, like static IP address on the BMC using `ipmitool` (work normally done by `bmcsetup`).

**Comment by krono** [comment]
HI
Yes I think so; I managed  to get xCAT to have the IC922 netboot.
Sadly, the genesis kernel crashes immediately (but that's a different story and happens for the AC922, too, so maybe I have to self-gen the genesis)

**Comment by gurevichmark** [comment]
Instructions here might help: https://xcat-docs.readthedocs.io/en/stable/references/coral/known_issues/genesis_base.html#xcat-genesis-base

**Comment by krono** [comment]
thanks.

**Comment by besawn** [comment]
No additional features are planned for IC922 servers at this time.
