### ISSUE TITLE
[FVT]2.93:aix720  could not get xcat version

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#655]
Test OS: aix720,p8 
Test xCAT version:2.93
How to reproduce:
```
bash-3.2# lsxcatd -v
Version 
```

**Comment by hu-weihua** [comment]
@junxiawang,  I found below things in your environment:

    bash-3.2# ./xcatd -f
    Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
    Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
    Error loading module /opt/xcat/lib/perl/xCAT_plugin/makeknownhosts.pm  ...skipping
    Error loading module /opt/xcat/lib/perl/xCAT_plugin/xdsh.pm  ...skipping
    xCATd: service starting

and 

     bash-3.2#  vi /opt/xcat/lib/perl/xCAT/DSHCLI.pm
     ......
     +5113              foreach my $target_node (@dest_host)
     +5114              {
     +5115  <<<<<<< HEAD
     +5116                  # skip the node if it's not in the permitted list
     +5117  =======
     +5118                  # skip the node if it's NOT in the permitted list
     +5119  >>>>>>> f5d7bdd407a5963b04b8f2943097678f318d507c
     +5120                  if ($dest_node && ! grep /^$target_node$/, @dest_nodes) {
     +5121                      next;
     +5122                  }
    .......

It seems our code in github has problem.  So we need to fix this problem in github, rebuild program and test again.

**Comment by hu-weihua** [comment]
@junxiawang, the version value is calculated from ``${GITREF}built`` and `` $BUILDDATE``, due to there are some problem in the build in your environment( please refer to comment for issue#656), so please rebuild new one and test again.

**Comment by junxiawang** [comment]
Tested in latest xcat build.
Version 2.9.3 (git commit 5345643cf8fd145fb6c66397624445b6538d9d24, built Fri Jan 29 02:25:14 CST 2016)
