### ISSUE TITLE
[FVT]2.93:aix720 xdsh could not work

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#656]
Test ENV: aix720,p8
Test xCAT version:2.93
How to reproduce:
```
bash-3.2# xdsh c910f03c01p07 date
Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
Global symbol "$srcfile" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5126.
syntax error at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5133, near ")
                    {"
Global symbol "$srcfile" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5135.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5138.
Global symbol "$srcfile" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5143.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5159.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5165.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5167.
Global symbol "$srcfile" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5168.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5172.
Global symbol "$target_node" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5174.
Global symbol "$srcfile" requires explicit package name at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5175.
syntax error at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5182, near "}"
/opt/xcat/lib/perl/xCAT/DSHCLI.pm has too many errors.
Compilation failed in require at /opt/xcat/bin/xdsh line 19.
```

**Comment by hu-weihua** [comment]
@junxiawang,  I found below things in your environment:

    bash-3.2# ./xcatd -f
    Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
    Use of bare << to mean <<"" is deprecated at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 5115.
    Error loading module /opt/xcat/lib/perl/xCAT_plugin/makeknownhosts.pm  ...skipping
    Error loading module /opt/xcat/lib/perl/xCAT_plugin/xdsh.pm  ...skipping
    xCATd: service starting

and 

     bash-3.2#  vi /opt/xcat/lib/perl/xCAT/DSHCLI.pm
     ......
     +5113              foreach my $target_node (@dest_host)
     +5114              {
     +5115  <<<<<<< HEAD
     +5116                  # skip the node if it's not in the permitted list
     +5117  =======
     +5118                  # skip the node if it's NOT in the permitted list
     +5119  >>>>>>> f5d7bdd407a5963b04b8f2943097678f318d507c
     +5120                  if ($dest_node && ! grep /^$target_node$/, @dest_nodes) {
     +5121                      next;
     +5122                  }
    .......

It seems our code in github has problem.  So we need to fix this problem in github, rebuild program and test again.

**Comment by daniceexi** [comment]
The build was made just during the code checkin. The problem was fixed just after the build.

**Comment by junxiawang** [comment]
Tested in aix latest build.
