### ISSUE TITLE
/master/xCAT-server/share/xcat/netboot/rh/dracut_033/xcatroot squashfs+overlayfs?

### ISSUE THREAD

**Issue by sventor** [xcat2/xcat-core#6583]
Dear xCAT maintainer,

We're trying to set up a stateless image via squashfs, and while the `rootimg.sfs` is properly created, the nodes fail to boot due to missing 'aufs', the layered fs approach formerly used.

[Since 2015, the patch/change on how to switch to 'overlayfs' ](https://sourceforge.net/p/xcat/mailman/message/34251334/) has been submitted, but even in the most recent version, `/opt/xcat/share/xcat/netboot/rh/dracut_033/xcatroot` still has not been adapted and still tries to use 'aufs'.

As I could not find any open issue to that (pls bear with me): what is the status of this simple change and are there still plans to implement it?

In connection with that, in `lib/perl/xCAT_plugin/packimage.pm` the '**mksquashfs**' command is still incorrectly called with either "-le" or "-be", which are obsolete according to `man mksquashfs`...

**Comment by gurevichmark** [comment]
Resolved by #6698 and #6680
