### ISSUE TITLE
[FVT]: some options for rinv Nextscale node has no output

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#659]
Test platform(including OS and Hardware):  SLES11.4,  Lenovo NeXtScale nx360 M5
Test xCAT version:
Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)
How to reproduce: 

```
c693f3ns02:/etc/sysconfig/network # rinv c693f3ns04 pci
c693f3ns02:/etc/sysconfig/network # echo $?
0

c693f3ns02:/etc/sysconfig/network # rinv c693f3ns04 asset
c693f3ns04: System Asset Number:

c693f3ns02:/etc/sysconfig/network # rinv c693f3ns04 diag
c693f3ns02:/etc/sysconfig/network # echo $?
0

c693f3ns02:/etc/sysconfig/network # rinv c693f3ns04 mparom
c693f3ns02:/etc/sysconfig/network # echo $?
0
```

**Comment by whowutwut** [comment]
@pdlun92  If you have some time to take a look... you can possibly investigate this.

**Comment by daniceexi** [comment]
@jjohnson42 Are the missing parts not supported by Lenovo M5 server again? Or there's a new method to get them?

**Comment by zet809** [comment]
Hi, @daniceexi and @tingtli , do you think we shall keep the issue open or close it and reopen if we have Nextscale node?

**Comment by tingtli** [comment]
Close this one at the moment. Reopen it when it is necessary.
