### ISSUE TITLE
Documentation: network interface confusion

### ISSUE THREAD

**Issue by datakid** [xcat2/xcat-core#6596]
On the [Configure Ethernet Network Interface](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_ethernet_nic.html) page ([git](https://github.com/xcat2/xcat-core/blob/master/docs/source/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_ethernet_nic.rst)) there is a line that looks like this:

```
#. Data NIC ``eth1`` is not install NIC, configure ``eth1`` into ``nics`` table  ::

    chdef cn1 nicips.eth1="13.1.89.7" nicnetworks.eth1="net13" nictypes.eth1="Ethernet" nichostnamesuffixes.eth1=-eth2

Update /etc/hosts
~~~~~~~~~~~~~~~~~
```
But there is no other reference to `-eth2` in the page. I don't think it makes sense - there is either documentation missing, or it should read `-eth1`

**Comment by gurevichmark** [comment]
Fixed by #6598
