### ISSUE TITLE
[dev]rest api for vitals all return "500 Internal Server Error"

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-core#66]
[root@byomc1 xcat-core]# lsxcatd -v
Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)

[root@byomc1 xcat-core]# curl -X GET -k 'https://127.0.0.1/xcatws/nodes/c910f04x23/vitals?userName=root&userPW=teamsun&pretty=1'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 root@localhost and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at 127.0.0.1 Port 443</address>
</body></html>

The rvitals temp can return correct output as following:
[root@byomc1 xcat-core]# curl -X GET -k 'https://127.0.0.1/xcatws/nodes/c910f04x23/vitals/temp?userName=root&userPW=teamsun&pretty=1'
{
   "c910f04x23":{
      "PCI Riser 2 Temp":"34 C (93 F)",
      "PCI Riser 1 Temp":"40 C (104 F)",
      "PCH Temp":"44 C (111 F)",
      "DIMM GH VR Temp":"34 C (93 F)",
      "CPU2 VR Temp":"35 C (95 F)",
      "DIMM AB VR Temp":"31 C (88 F)",
      "DIMM CD VR Temp":"32 C (90 F)",
      "DIMM EF VR Temp":"33 C (91 F)",
      "Ambient Temp":"28 C (82 F)",
      "CPU1 VR Temp":"33 C (91 F)",
      "Mezz Card Temp":"N/A"
   }
}

**Comment by bybai** [comment]
In xcat2.11 master:commit bf4a153287f19cc41037f4db0d18527fc558b5fd

**Comment by whowutwut** [comment]
@bybai  can you wrap the above text for the issues with backticks: ```  ? 
The markdown is interpreting the html output.

**Comment by bybai** [comment]
@whowutwut I used ```now, it looks better now.

**Comment by whowutwut** [comment]
:-)
