### ISSUE TITLE
Documentation: broken link in Configure DHCP

### ISSUE THREAD

**Issue by datakid** [xcat2/xcat-core#6602]
[Configure DHCP](https://xcat-docs.readthedocs.io/en/stable/advanced/hierarchy/configure_dhcp.html) ([git](https://github.com/xcat2/xcat-core/blob/master/docs/source/advanced/hierarchy/configure_dhcp.rst)) has, on line 6 "Add the defined nodes into the DHCP configuration, refer to: XCAT_pLinux_Clusters/#configure-dhcp"

That link is broken. I think it's meant to be a link to https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define.html

```
Add the defined nodes into the DHCP configuration, refer to :doc:`Manually define nodes </guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define>`
```

**Comment by gurevichmark** [comment]
Not seeing it. The latest version of ` xcat-core/docs/source/advanced/hierarchy/configure_dhcp.rst` was last changed on Nov 7 2019 and contains correct link:

![image](https://user-images.githubusercontent.com/16106630/81732889-2615fa80-945f-11ea-9762-12a896e7d20d.png)
