### ISSUE TITLE
xCAT boot manager (boot order on WOL)

### ISSUE THREAD

**Issue by tk9320** [xcat2/xcat-core#6614]
I would like to ask you the following questions regarding Secondary(Wake on LAN) Boot Sequence,
xCAT server boot order.
  
・Is "rsetboot" command on condition that PXE Network is at the top of Boot Order on WOL?
(for example,  1.PXE Network 2.CD/DVD Rom 3.Hard Disk)
 
・Would "rsetboot" command be possible to use on default boot order?
(default order: 1.CD/DVD Rom 2.Hard Disk 3.Network 4.USB Storage)
 
(Question's background)
ThinkSystem is not able to set boot order on WOL individually. So boot order is applied same one on "usual Power On" and "WOL".

Thank you.

**Comment by cxhong** [comment]
I think you can set boot method via `rsetboot` command
```
# rsetboot --help
Usage: rsetboot <noderange> [net|hd|cd|floppy|def|stat] [-u] [-p]
       rsetboot [-h|--help|-v|--version]
```
xCAT only choose one method from `rsetboot`

**Comment by tk9320** [comment]
I greatly appreciate your reply.

My understanding is that individual boot setting isn't required to use "rsetboot" command.
So Wake on LAN setting isn't a prerequisite to use it.

By using "rsetboot -p", users can decide persistent boot mode.
