### ISSUE TITLE
Bash code formatting?

### ISSUE THREAD

**Issue by datakid** [xcat2/xcat-core#6617]
In [xcat-core/xCAT/postscripts/configib](https://github.com/xcat2/xcat-core/blob/master/xCAT/postscripts/configib) lines [195-226](https://github.com/xcat2/xcat-core/blob/master/xCAT/postscripts/configib#L195) seem to be indented one tab too far.

I might be misreading the code.

I thought about making a pull request but I don't know what the bash code formatting convention is for xcat, so here's an issue report.

**Comment by cxhong** [comment]
I think xCAT used `4 spaces`

**Comment by datakid** [comment]
Fixed by above merge
