### ISSUE TITLE
ospkgs postscript not adapted to CentOS 8.x

### ISSUE THREAD

**Issue by conxuro** [xcat2/xcat-core#6625]
Exactly the same behaviour as otherpkgs postscript, reported in issue https://github.com/xcat2/xcat-core/issues/6577

The workarround works exactly the same way: to check if there is repodata as subdirectory.
```
885,887d883
<            result=$(curl -s --fail --retry 20 --max-time 60 http://${OSPKGDIR}/ | grep repodata 2>&1)
<            if [ $? -eq 0 ]
<            then
```

**Comment by gurevichmark** [comment]
Fixed by #7016
