### ISSUE TITLE
Create dynamic group based on node names?

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6629]
Hi, 

How could one create dynamic groups based on node names?
The [documentation](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/basic_concepts/xcat_object/group.html#creating-a-dynamic-node-group) says: 
> The selection criteria for a dynamic node group is specified by providing a list of attr<operator>val pairs that can be used to determine the members of a group. [...] The attr field can be any node definition attribute returned by the lsdef command.

The thing is that the node name does not appear as an attribute returned by `lsdef`, yet it's still a node definition attribute. 

Is there a way to filter node lists based on the node names?

**Comment by gurevichmark** [comment]
Have you tried something like:
```
[root@stratton01 ~]# mkdef -t group mg_vms -d -w node=~"/fs2vm.*"

[root@stratton01 ~]# lsdef -t group -o mg_vms
Object name: mg_vms
    grouptype=dynamic
    members=fs2vm100,fs2vm113,fs2vm114,fs2vm102,fs2vm101,fs2vm104,fs2vm105,fs2vm111,fs2vm110,fs2vm112
    wherevals=node=~/fs2vm.*
[root@stratton01 ~]#
```

**Comment by kcgthb** [comment]
I had not, and that works! 

Thanks a lot for the pointer, that would be a great addition to the documentation.
