### ISSUE TITLE
retrieve hardware information from table via API

### ISSUE THREAD

**Issue by gilbo47** [xcat2/xcat-core#6634]
Is it possible to retrieve hardware information from inventory via the API?  I'd like to get at the info which is retrieved from rinv command via the API.

**Comment by gurevichmark** [comment]
Have you looked at using xCAT REST API ?
https://xcat-docs.readthedocs.io/en/stable/advanced/restapi/index.html

The `rinv` equivalent would be something like:
`curl -X GET -k 'https://<IP>/xcatws/nodes/node1/inventory?userName=root&userPW=xxxx&pretty=1'`

**Comment by gilbo47** [comment]
Thankyou very much.  That is precisley what I'm after.  Much appreciated.
