### ISSUE TITLE
[FVT]xCAT in docker:makedns failed

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#665]
Test OS:ubuntu14.04.3
Test xCAT version:
How to reproduce:
```
root@xcat2-7mn:/# lsxcatd  -v
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:49:07 EST 2015)
root@xcat2-7mn:/# makedns -n
Handling c910f04x20 in /etc/hosts.
Ignoring host c910f04x20, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling xcat2-7mn in /etc/hosts.
Handling localhost in /etc/hosts.
Handling localhost in /etc/hosts.
Handling ip6-allnodes in /etc/hosts.
Ignoring host ip6-allnodes, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c910f04x30v05 in /etc/hosts.
Handling ip6-mcastprefix in /etc/hosts.
Ignoring host ip6-mcastprefix, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling ip6-localnet in /etc/hosts.
Ignoring host ip6-localnet, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling ip6-allrouters in /etc/hosts.
Ignoring host ip6-allrouters, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting bind9
Error: failed to start named.

```

**Comment by immarvin** [comment]
this is due to the apparmor on docker host.

The work around is to turn off the apparmor on Docker host with 
````
/etc/init.d/apparmor teardown
````
Since Apparmor is a security framework on ubuntu like selinux on redhat, considering whether adding "turn off apparmor" as a prerequisite to run xCAT docker image

opened a bug to Docker: 
https://github.com/docker/docker/issues/19709

**Comment by immarvin** [comment]
@junxiawang , you can continue your test with the work-around. I will trace the ticket to Docker

**Comment by daniceexi** [comment]
@immarvin But we did not see apparmor impacts the xCAT which running on an Ubuntu MN, why it impacts the xcat in docker container?

**Comment by immarvin** [comment]
when running ``service bind9 start`` inside the container, the file to access is ``var/lib/docker/aufs/diff/92ec6d044cb3e39ae00500126a88c9ac342678d0591675f2231daafbf0877778/lib/x86_64-linux-gnu/libc-2.19.so`` ,the path is based on the container's filesystem on docker host,  however, the file paths in apparmor policy is based on the "/" on the docker container.

**Comment by daniceexi** [comment]
@immarvin So the basic change is to disable appamror in xCAT image.

**Comment by immarvin** [comment]
@daniceexi , disable apparmor on Docker host

**Comment by immarvin** [comment]
updated the doc to disable AA on Docker host.
https://github.com/xcat2/xcat-core/pull/653
