### ISSUE TITLE
PXE gets IP via DHCP but xNBA doesn't 

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#6650]
I have a node that I am trying to boot that has 2 issues, i suspect they are related. First issue is, sometimes when the node boots, the PXE environment gets its IP no problem, then gets the xNBA bootloader. Then xNBA tries to DHCP, but does not get an IP.

![4CECB498X](https://user-images.githubusercontent.com/47122186/77680167-f3c14400-6f69-11ea-843c-13758432e325.png)

Sometimes it will get past this part, but it will hang when getting its image. 
![2833E66](https://user-images.githubusercontent.com/47122186/77680283-210df200-6f6a-11ea-9a6c-ae4fa855b013.PNG)

Anyone deal with this before and know how to fix it?

**Comment by cxhong** [comment]
which xcatd release is running?  and which OS you are trying to install?
can u also check these two commands?
1) `nslookup <NODENAME>`  to check if name can able  resolved
2) `xcatprobe detect_dhcpd -i <interface_name> -m <node's mac address> ` to check if there are multiple server service this mac address
3) did u see `dhcp` process for this mac address in the  `/var/log/messages`  ?

**Comment by kjhee43** [comment]
@cxhong 

Version 2.14.6 (git commit 7c787c499ebca7a98d6fcdb3577f701ac16d7ab3, built Fri Mar 29 03:19:08 EDT 2019)

Trying to install RHEL7.6.

1. nslookup fails. no DNS server is running. we use hosts files. 
2. "There are 1 servers replied to dhcp discover."
3. Yes, worked fine once, then doesn't work again. Not sure why. 
 `Mar 27 14:22:07 das01 dhcpd: DHCPDISCOVER from 80:30:e0:1a:7a:e0 via eno5
Mar 27 14:22:07 das01 dhcpd: DHCPOFFER on 172.16.20.22 to 80:30:e0:1a:7a:e0 via eno5
Mar 27 14:22:10 das01 dhcpd: DHCPREQUEST for 172.16.20.22 (172.16.20.10) from 80:30:e0:1a:7a:e0 via eno5
Mar 27 14:22:10 das01 dhcpd: DHCPACK on 172.16.20.22 to 80:30:e0:1a:7a:e0 via eno5
`

**Comment by cxhong** [comment]
maybe check dhcp config file and `makedhcp -q <nodename>`
what's output in the `/tftpboot/xcat/xnba/nodes/<nodename>`?

**Comment by kjhee43** [comment]
Turns out i am having an issue similiar to [this](https://github.com/xcat2/xcat-core/issues/6357) one. I followed up in that thread on if there was a fix. 

@cxhong thank you so much for your help.
