### ISSUE TITLE
Externally managed KVM hosts

### ISSUE THREAD

**Issue by holtgrewe** [xcat2/xcat-core#6651]
[Please redirect me if this is not the correct location to ask this.]

I have a cluster of physical nodes that I manage with xCat. This works very well. Now I want to use xCat for installing a few KVM nodes that are managed (with a software called ProxMox). The system definition etc. comes is done with ProxMox (that also takes care of high availability). I would only need to interface xCat with ProxMox in an IPMI-like fashion.

This could be done with some bash scripts taking to my ProxMox server via it's REST interface.

Where can I learn how to do this? Is it possible at all? Where are the correct points to hook this in? Is there anything that I could use as an example?

Thank you very much

**Comment by gurevichmark** [comment]
@holtgrewe Are you trying to use xCAT to provision a node which will act as a KVM host running ProxMox ? Or are you trying to use xCAT to create, remove, etc, the VMs, hosted on the ProxMox KVM host ?

**Comment by holtgrewe** [comment]
@gurevichmark I have a VM in proxmox already that I want to PXE-boot and install with xCAT (DHCP+PXE+anaconda).

**Comment by gurevichmark** [comment]
Did you try following this: https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/manage_vms.html

**Comment by holtgrewe** [comment]
Thanks for the pointers. I ended up defining my host as a kvm virtual machine. I then call makehosts, makedhcp etc. as usually. Then an `rinstall host` generates the appropriate pxe boot files and just fails with the "power" commands. After rebooting the machine in proxmox, it pxe boots and installs properly.

Thanks.
