### ISSUE TITLE
Configuration hint with two networks

### ISSUE THREAD

**Issue by holtgrewe** [xcat2/xcat-core#6653]
Hi,

I need some help with my xCAT configuration for the stateful/diskful installation.

I have two networks. One "backend network" `10_32_100_0-255_255_252_0` is used for the installation and is where xCAT's DHCP should run. One "front-end network" `10_32_96_0-255_255_252_0` is to be used for all communication.

The interface `eno1` is to be used for the backend network, a `bond0` of `ens2f0` and `ens2f1` is to be used for the frontend network. The name of the node should be `cc-node000` in the front-end network.

I have created the node stanza on the bottom. This leads to a working configuration. However, the `/etc/hosts` entry for `cc-node000` refers to the backend network and `cc-node000-bond0` is also created. I would like to change the stanza such that the only effect is the node to be called `cc-node000` in the front-end network and `cc-node000-eno1` being creatted instead of `cc-node000-bond0`.

Is this possible?

Thanks!

```
Object name: cc-node000
    bmc=10.43.1.133
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=boot
    groups=all,compute
    installnic=mac
    ip=10.32.100.110
    mac=08:f1:ea:f3:4c:aa
    mgt=ipmi
    netboot=pxe
    nicdevices.bond0=ens2f0|ens2f1
    nicips.bond0=10.32.96.110
    nicips.eno1=10.32.100.110
    nicnetworks.bond0=10_32_96_0-255_255_252_0
    nicnetworks.eno1=10_32_100_0-255_255_252_0
    nictypes.bond0=bond
    nictypes.eno1=ethernet
    nictypes.eno2=ethernet
    nictypes.ens2f0=ethernet
    os=centos7.7
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignetworkhardeths,setroute,mkresolvconf
    profile=compute
    provmethod=centos7.7-x86_64-install-compute
    routenames=default
    status=failed
    statustime=03-31-2020 09:33:52
    updatestatus=syncing
    updatestatustime=03-31-2020 01:44:15
```

**Comment by cxhong** [comment]
Have you try to use `nichostnamesuffixes` ?

https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_aliases.html

**Comment by gurevichmark** [comment]
@holtgrewe Did the suggestion above help you resolve your question ?
If so, can you please close this issue.

**Comment by gurevichmark** [comment]
No updates in a month. Closing.
