### ISSUE TITLE
Fix XFS as fstype for statelite with localdisk configuration

### ISSUE THREAD

**Issue by blixem** [xcat2/xcat-core#6664]
Localdisk init script points to mke2fs, which does not handle XFS.  mkfs and mkfs.xfs are not available in sysroot.  
https://github.com/xcat2/xcat-core/blob/68e71785428acf1cccb580b5e70a624347aa200d/xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk#L219-L221

I have tried locally modifying this to:
`` `mkfs.$fstype $partdev > /dev/null` ``
As well as:
`` `mkfs -t $fstype $partdev > /dev/null` ``

Both of which fail with messages similar to:

> dracut-pre-pivot: INFO  /sysroot/etc/init.d/localdisk: line 223: mkfs: command not found
> dracut-pre-pivot: INFO  /sysroot/etc/init.d/localdisk: line 223: mkfs.xfs: command not found

**Comment by blixem** [comment]
I am currently on-hold with some buy-in nodes in my cluster waiting for a response.  Any update available?

**Comment by cxhong** [comment]
did u have `util-linux` and `e2fsprogs` packages installed?  

which os you are installed?  make sure those package in the pkglist.

**Comment by blixem** [comment]
> did u have `util-linux` and `e2fsprogs` packages installed?
> 
> which os you are installed? make sure those package in the pkglist.

CentOS 7.7, both util-linux and e2fsprogs are installed.  All of the xfs packages needed are installed as well.  The problem stems from rc.localdisk not being developed to handle XFS, only e2fs file systems.

**Comment by cxhong** [comment]
can u check if you have `xfsprogs` packages?  if not, can u `yum install xfsprogs` then try again?

**Comment by blixem** [comment]
> can u check if you have `xfsprogs` packages? if not, can u `yum install xfsprogs` then try again?

`[root@xcat ~]# rpm -qa |egrep xfs
xfsprogs-4.5.0-20.el7.x86_64`

Yes, they are installed.  We are also loading the xfs drivers into the boot image in the osimage by adding:
`netdrivers=xfs.ko`

**Comment by cxhong** [comment]
Thanks @blixem , I will work on this issues.

**Comment by cxhong** [comment]
@blixem the fixes are in the #6679,  let me know if not working for you or more issues.

**Comment by blixem** [comment]
> @blixem the fixes are in the #6679, let me know if not working for you or more issues.

I'm using CentOS 7.7, not 8.x so I had to make the changes to "xCAT-server/share/xcat/netboot/rh/dracut_033/install.netboot" instead of dracut_047.

This works for CentOS 7.7 except under one condition:
If there is a partition on the disk assigned to be localdisk that was previously the same size, and not xfs, as the one designated in the partitionfile.  
E.g. Disk /dev/sda previously had a partion of /dev/sda1 that was ext3 filling 100% of the drive.  If the partitionfile looks like this...

```
[disk]
dev=/dev/sda
clear=yes
parts=100
ptype=gpt
fstype=xfs

[localspace]
dev=/dev/sda1
fstype=xfs

```
Since parted creates the same exact partition, the previous file system is still intact.  During mkfs.xfs it fails due to not wanting to overwrite the existing filesystem:

```
Apr 22 22:46:42 n367 dracut-pre-pivot: INFO  mkfs.xfs: /dev/sda1 appears to contain an existing filesystem (ext3).
Apr 22 22:46:42 n367 dracut-pre-pivot: INFO  mkfs.xfs: Use the -f option to force overwrite.
```
 
I circumvented this by changing the line in rc.localdisk from:

```
`mkfs.$fstype -q $partdev  > /dev/null`
```
to:
```
`mkfs.$fstype -f -q $partdev  > /dev/null`
```
which forces the filesystem creation.

@cxhong After these changes it works as expected on CentOS 7.7.  I'm assuming with the "-f" change to rc.localdisk in dracut_047 it would be the same for CentOS 8.x

**Comment by cxhong** [comment]
@blixem , thanks.   Centos has symbolic link to redhat.  Any changes made in the redhat will apply to centos.

**Comment by blixem** [comment]
> @blixem , thanks. Centos has symbolic link to redhat. Any changes made in the redhat will apply to centos.

Yes, but dracut_033 does not have a symlink to dracut_047.

**Comment by cxhong** [comment]
oh, centos dracut_033 has a symlink to redhat dracut_033.  I made changes in the `rh/dracut_033` also

**Comment by blixem** [comment]
Thank you @cxhong  Should I close this issue as it is resolved from my side, or do you want to do it when your pull is merged?
