### ISSUE TITLE
Xcat 2.15.1 genesis bmcsetup : ADMIN user disabled

### ISSUE THREAD

**Issue by th-hummel** [xcat2/xcat-core#6666]
Hello,

I've just upgraded from xcat 2.15.0 to 2.15.1 (on CentOS 8.1) and the chain bmcsetup destiny works as before except the ADMIN user is disabled.

- 2.15.0
```
# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : call-in / callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : enabled
```

- 2.15.1

```
# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled
```
Looking at the code
```
+    # automatically find first unlocked user slot
+    for slot in {1..16}; do
+        USERLOCKED=`ipmitool channel getaccess $LANCHAN $slot | grep Fixed | awk '{print $4}'`
+        if [ "$USERLOCKED" == "No" ]; then
+            USERSLOT=$slot
+            break
+        fi
+    done
```
has been added.

On my systems (x86_64 SuperMicro H12DST-B boards), ipmitool shows a user matching this grep which as Fixed set to No AFTER the ADMIN user
```
User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled

User ID              : 3
User Name            : 
Fixed Name           : No
Access Available     : call-in / callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : enabled
```

Thanks for your help

--
Thomas HUMMEL

**Comment by gurevichmark** [comment]
Code change was made in #6380

**Comment by th-hummel** [comment]
On 4/7/20 3:54 PM, Mark Gurevich wrote:
> Code change was made in #6380 <https://github.com/xcat2/xcat-core/pull/6380>

Hello,

thanks for pointing this. I'm not sure I understand the above change.

- what are we supposed to notice between before and after ?
- xcat.genesis.bmcsetup: CURRENTUSER=admin, DISABLEUSERS=1 2  4 5 6 7 8 
9 10 11 12 13 14 15

On my systems ADMIN (upper case) is user #2
Besides it has Fixed == No so I don't understand how bmcsetup can 
configure it as the above issue says "If the user ID is locked, then 
ipmitool cannot change user name, password, etc." (although speaking of 
some workaround)

- finally, I forgot to mention that I see lines like this in log files

2020-04-07T14:34:01+02:00 maestro-1002 screenlog: xcat.genesis.bmcsetup: 
CURRENTUSER=true, DISABLEUSERS=1 2  4 5 6 7 8 9 10#015


CURRENTUSER=true seems odd.

I will update my issue with the latter point.

Thanks for your help.

--
Thomas HUMMEL

**Comment by adorsey-NOAA** [comment]
The intent of that code change was to find the first user slot that wasn't associated with a fixed name, and allow ```bmcsetup``` to set up the IPMI username and password.  User slots with ```Fixed Name           : Yes``` can't be modified by ```bmcsetup``` when it tries to set a specific username and password.

@th-hummel in your initial message, you provided the output from ```ipmitool channel getaccess 1 2``` which shows that ```ADMIN``` is a fixed name on your system, so ```bmcsetup``` can't modify it.

```
# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled
```

**Comment by th-hummel** [comment]
On 4/7/20 5:32 PM, adorsey-NOAA wrote:
> The intent of that code change was to find the first user slot that 
> wasn't associated with a fixed name, and allow |bmcsetup| to set up the 
> IPMI username and password. User slots with |Fixed Name : Yes| can't be 
> modified by |bmcsetup| when it tries to set a specific username and 
> password.
> 
> @th-hummel <https://github.com/th-hummel> in your initial message, you 
> provided the output from |ipmitool channel getaccess 1 2| which shows 
> that |ADMIN| is a fixed name on your system, so |bmcsetup| can't modify it.

I know. I'm not really fluent with ipmi channels and co. So I may have 
provided the wrong outputs. However, genesis, through bmcsetup with xCAT 
2.15.0 did succeed in configuring and enabling the ADMIN BMC user.

Without any change from me 2.15.1 seems to do the same except I have to 
manually enable it running

ipmitool user enable 2

Again,

on a 2.15.0 discovered node :

[root@maestro-1000 ~]# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : call-in / callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : enabled

On a 2.15.1 discovered node (actually re-discovered : I did cleaned and 
recreated the xCAT object) :

[root@maestro-1002 ~]# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled

Thanks.

--
TH

**Comment by gurevichmark** [comment]
@adorsey-NOAA On one of my Power machines, I also see `ADMIN` with `Fined Name: Yes`
```
[root@stratton01 ~]# ipmitool-xcat -H 50.3.31.1 -U ADMIN -P admin channel getaccess 1
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 1
User Name            :
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : disabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : disabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : enabled
```

**Comment by adorsey-NOAA** [comment]
I think I see the issue - the check for unlocked user slots is overwriting information from some special cases in the script.  I believe the solution is to move this code farther up and have it run as a "default" case for systems that don't have special cases already in the script.

Let me put together a test version of the script.

**Comment by adorsey-NOAA** [comment]
Pull request #6667 should fix this issue.  Still working on the best way for testing @th-hummel, you may need to rebuild the genesis boot image.

**Comment by adorsey-NOAA** [comment]
@th-hummel I've attached a modified version of the bmcsetup script with the changes from #6667.  Please try the following steps:
- Download and gunzip [bmcsetup.gz](https://github.com/xcat2/xcat-core/files/4446024/bmcsetup.gz)
- Copy that file to ```/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/usr/bin/bmcsetup```
- Run ```mknb x86_64```
- Reboot a node into genesis with the ```bmcsetup``` destiny and see if the issue persists.

**Comment by th-hummel** [comment]
On 4/7/20 7:20 PM, adorsey-NOAA wrote:
> @th-hummel <https://github.com/th-hummel> I've attached a modified 
> version of the bmcsetup script with the changes from #6667 
> <https://github.com/xcat2/xcat-core/pull/6667>. Please try the following 
> steps:
> 
>   * Download and gunzip bmcsetup.gz
>     <https://github.com/xcat2/xcat-core/files/4446024/bmcsetup.gz>
>   * Copy that file to
>     |/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/usr/bin/bmcsetup|
>   * Run |mknb x86_64|
>   * Reboot a node into genesis with the |bmcsetup| destiny and see if

Hello,

I just dit that but I think it still did not work :

# ipmitool channel getaccess 1 2
Maximum User IDs     : 10
Enabled User IDs     : 1

User ID              : 2
User Name            : ADMIN
Fixed Name           : Yes
Access Available     : callback
Link Authentication  : enabled
IPMI Messaging       : enabled
Privilege Level      : ADMINISTRATOR
Enable Status        : disabled

I still have to manually issue

# ipmitool user enable 2

And I still see in genesis logs lines such as

2020-04-07T19:37:53+02:00 maestro-1002 screenlog: xcat.genesis.bmcsetup: 
CURRENTUSER=true, DISABLEUSERS=1 2  4 5 6 7 8 9 10#015

thanks for your help

--
TH

**Comment by adorsey-NOAA** [comment]
@th-hummel can you try a different method of testing?

On your xCAT management node:
- Backup or make a copy of any existing script at ```/install/postscripts/bmcsetup```
- Copy the script I sent you to ```/install/postscripts/bmcsetup```
- Run ```updatenode <nodename> -P bmcsetup``` where ```<nodename>``` is the name of the node having this issue

Please reply with all of the output from the ```updatenode``` command as well.

**Comment by th-hummel** [comment]
On 4/7/20 8:12 PM, adorsey-NOAA wrote:
> @th-hummel <https://github.com/th-hummel> can you try a different method 
> of testing?
> 
> On your xCAT management node:
> 
>   * Backup or make a copy of any existing script at
>     |/install/postscripts/bmcsetup|
>   * Copy the script I sent you to |/install/postscripts/bmcsetup|
>   * Run |updatenode <nodename> -P bmcsetup| where |<nodename>| is the
>     name of the node having this issue
> 
> Please reply with all of the output from the |updatenode| command as well.

Same issue. Note that the updatenode does not return to the shell.

Please find attached the output I copied/pasted (stdout/err redirect 
does not seem to work - I guess they're passed through the connection).

Thanks for your help

--
Thomas Hummel

**Comment by adorsey-NOAA** [comment]
@th-hummel I'm not seeing an attachment on your response.  Can you try again?  When you attach a file, make sure that the link that is created appears in your reply.

**Comment by th-hummel** [comment]
Sorry, here it is

[updatenode-bmcsetup.log](https://github.com/xcat2/xcat-core/files/4450707/updatenode-bmcsetup.log)

--
TH

**Comment by adorsey-NOAA** [comment]
@th-hummel Please disregard my previous message.  Sorry for the confusion.

I think I found a way to make the script work as it did previously; meaning you should be able to still use the credentials for the ADMIN user if that's what you want to do.

Please try testing with this updated version of [bmcsetup.gz](https://github.com/xcat2/xcat-core/files/4450977/bmcsetup.gz).

**Comment by th-hummel** [comment]
> That basically says "if we haven't set a userslot and we haven't specified which users to lock, just guess and use slot 2." This just happened to work for you since your ADMIN user was slot 2, and I'm assuming you set the BMC username and password in your node definitions to ADMIN and the default password respectively.

ideed but not the default password:

```
"ipmi","ADMIN","XXXX",,,"BMC ADMIN user password",

```
 
> The problem is, after this change, the script sees slot 2 is locked and skips over it, instead selecting user slot 3.

I kind of got that however I'm not sure I understand the concept of user "slot".
Besides, how could the passwd have been changes (at least using the old bmcsetup) if the user was Fixed : Yes as I read above that this would mean the settings were not editable ?

>  However, the node still has the BMC username ADMIN associated with it, and IPMI will not allow duplicate usernames, so the username doesn't get set in slot 3 and we get all these error messages:
> 
> ```
> maestro-1002: Set User Name command failed (user 3, name ADMIN): Invalid data field in request
> ```
Ok. One can have multiple ADMIN users for different channels, right ?

> Can you try changing `bmcusername` for your test node to `admin` (IPMI usernames are case sensitive) and running the script again, either via genesis or via updatenode? That should allow `bmcsetup` to completely configure slot 3, and also tell xCAT to use that set of credentials as well.

I can try that.

**Comment by th-hummel** [comment]
> @th-hummel Please disregard my previous message. Sorry for the confusion.
> 
> I think I found a way to make the script work as it did previously; meaning you should be able to still use the credentials for the ADMIN user if that's what you want to do.

Well I'm not obssessed with this loginanme...But shouldn't it work anyway ? As a user, I just edit the ipmi and/or passwd table, don't I ?

**Comment by adorsey-NOAA** [comment]
> ideed but not the default password:

Thanks, that information helps as well.

> > The problem is, after this change, the script sees slot 2 is locked and skips over it, instead selecting user slot 3.
> 
> I kind of got that however I'm not sure I understand the concept of user "slot".

IPMI has a concept of user slots, where there are a number of fixed entries that may be associated with usernames, passwords and access levels.  Here is an example from one of my systems:
```
[root@j2n01 ~]# ipmitool user list 1
ID  Name	     Callin  Link Auth	IPMI Msg   Channel Priv Limit
1                    false   false      true       ADMINISTRATOR
2   root             false   true       true       ADMINISTRATOR
3   admin            false   true       true       ADMINISTRATOR
4                    true    false      false      NO ACCESS
5                    true    false      false      NO ACCESS
6                    true    false      false      NO ACCESS
7                    true    false      false      NO ACCESS
8                    true    false      false      NO ACCESS
9                    true    false      false      NO ACCESS
10                   true    false      false      NO ACCESS
11                   true    false      false      NO ACCESS
12                   true    false      false      NO ACCESS
13                   true    false      false      NO ACCESS
14                   true    false      false      NO ACCESS
15                   true    false      false      NO ACCESS
```

> Besides, how could the passwd have been changes (at least using the old bmcsetup) if the user was Fixed : Yes as I read above that this would mean the settings were not editable ?

A fixed user can't have the username changed, but can have the password changed.  I didn't explain this well before, sorry.

I also apologize for the confusion so far; it appears that the original change I made stomped on a lot of different cases for different BMCs, and I'm still working through the changes needed.  I didn't consider the case where people would want to use a fixed name with a different password, which affected you specifically.

I've made some more progress, and I think I have a version of the script that will allow you to use the default ADMIN name and your own password.  Please try [bmcsetup.gz](https://github.com/xcat2/xcat-core/files/4451194/bmcsetup.gz) and let me know if that works for you.

**Comment by th-hummel** [comment]
> A fixed user can't have the username changed, but can have the password changed. I didn't explain this well before, sorry.

Ok I think I get your previous message now : it happens (by chance) that on my systems the Fixed user is named ADMIN and
1. I kept this name for bmcusername (passwd table)
2. the code happened to fallback to slot #2 which on my system was ADMIN 

;-)

**Comment by adorsey-NOAA** [comment]
> Ok I think I get your previous message now : it happens (by chance) that on my systems the Fixed user is named ADMIN and
> 
>     1. I kept this name for bmcusername (passwd table)
> 
>     2. the code happened to fallback to slot #2 which on my system was ADMIN
> 
> 
> ;-)

Exactly.  There was existing code to find the userslot for an existing username that should have worked, except my previous change in #6380 stomped all over it.  The new bmcsetup from my previous comment should handle that correctly.

**Comment by th-hummel** [comment]
> Please try [bmcsetup.gz](https://github.com/xcat2/xcat-core/files/4451194/bmcsetup.gz) and let me know if that works for you.

It seems so. Of course LAN, vlan id, and passwd was already configured by previous runs but before discover I could not log in into BMC, after bmcsetup it worked as before with the ADMIN user.

Thanks
--
Thomas HUMMEL

**Comment by adorsey-NOAA** [comment]
That's excellent news, thank you!  

I've updated #6667 to get this merged, but for now you can use that script in ```/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/usr/bin/bmcsetup``` and ```/install/postscripts/bmcsetup``` to work around this issue.

(Make sure to run ```mknb x86_64``` after updating the script in ```/opt/xcat```)

**Comment by th-hummel** [comment]
> I've updated #6667 to get this merged, but for now you can use that script in `/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/usr/bin/bmcsetup` and `/install/postscripts/bmcsetup` to work around this issue.

Ok, cool, thanks.
