### ISSUE TITLE
EFI system partition (ESP) should be fat32

### ISSUE THREAD

**Issue by jabl** [xcat2/xcat-core#6672]
A (pedantic?) reading of the [UEFI spec](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_A_Feb14.pdf#G17.1345080]) says that the EFI system partition (ESP) must be FAT32. 

However, in some cases xcat tries to create the ESP as fat16: https://github.com/xcat2/xcat-core/search?q=fat16&unscoped_q=fat16

**Comment by gurevichmark** [comment]
@jabl I would like to make the change from `fat16` to `fat32`.
How would I test it? How would I cause UEFI boot ?

**Comment by jabl** [comment]
Hmm, take a bare metal or VM system, set it to boot in UEFI mode, see if installation succeeds?

FWIW, I've tested both with the default and with FAT32 on one system, and both worked, but that's just one datapoint.

**Comment by gurevichmark** [comment]
@jabl Thank you.
How do I set it to boot in UEFI mode ?
After installation succeeds, how do I verify it really did boot in UEFI mode ?

**Comment by jabl** [comment]
That's system specific, but somewhere in the BIOS you should be able to find some setting where you can choose either UEFI or legacy mode. Choose UEFI.

As for verifying, if the system boots and installs successfully, the UEFI bootloader stuff should be found under /boot/efi, and running `df -T` you should see that /boot/efi is a fat32 (or vfat) partition. Also check that the directory /sys/firmware/efi exists and is non-empty.

**Comment by gurevichmark** [comment]
@jabl I tried using `rinstall` with `-u` flag to boot RHEL 8.0 in UEFI mode.
```
[root@c910f04x40 ~]# rinstall c910f04x16 osimage=rhels8.0.0-x86_64-install-compute -u -V
[c910f04x40]: Provision node(s): c910f04x16
[c910f04x40]: Run command: nodeset c910f04x16 osimage=rhels8.0.0-x86_64-install-compute
[c910f04x40]: c910f04x16: install rhels8.0.0-x86_64-compute
[c910f04x40]: Run command: rsetboot c910f04x16 net -u
[c910f04x40]: c910f04x16: Network
[c910f04x40]: Run command: rpower c910f04x16 boot
[c910f04x40]: c910f04x16: reset
[root@c910f04x40 ~]#
```

However, when the system gets booted, I could not tell the difference between booting with or without the `-u` flag. The output below was identical:
```
[root@c910f04x16 ~]# df -T
Filesystem              Type     1K-blocks    Used Available Use% Mounted on
devtmpfs                devtmpfs  24534032       0  24534032   0% /dev
tmpfs                   tmpfs     24549208       0  24549208   0% /dev/shm
tmpfs                   tmpfs     24549208    9092  24540116   1% /run
tmpfs                   tmpfs     24549208       0  24549208   0% /sys/fs/cgroup
/dev/mapper/xcatvg-root ext4      20511312 1154688  18291664   6% /
/dev/mapper/xcatvg-var  ext4       8191416  126108   7629496   2% /var
/dev/mapper/xcatvg-tmp  ext4       8191416   36968   7718636   1% /tmp
/dev/sda2               ext4        999320  123992    806516  14% /boot
/dev/sda1               vfat        261868    6744    255124   3% /boot/efi
/dev/mapper/xcatvg-home ext4      37494200   49176  35510688   1% /home
tmpfs                   tmpfs      4909840       0   4909840   0% /run/user/0
[root@c910f04x16 ~]#

[root@c910f04x16 ~]# ls /sys/firmware/efi/
config_table  fw_platform_size  runtime      systab
efivars       fw_vendor         runtime-map  vars
[root@c910f04x16 ~]#

[root@c910f04x16 ~]# parted /dev/sda1 -l
Model: IBM ServeRAID M5110e (scsi)
Disk /dev/sda: 439GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:
Number  Start   End     Size    File system  Name                  Flags
 1      1049kB  269MB   268MB   fat16        EFI System Partition  boot, esp
 2      269MB   1343MB  1074MB  ext4
 3      1343MB  439GB   437GB                                      lvm
```

**Comment by jabl** [comment]
Yeah, that looks like a UEFI install. I don't know why leaving out the `-u` flag doesn't change the result.

That being said, the RHEL 8 default xcat templates don't use fat16 anywhere, so the fact that parted reports the partition type as fat16 is either a bug in parted or in the RHEL installer, not in xcat. See the query https://github.com/xcat2/xcat-core/search?q=fat16&unscoped_q=fat16

**Comment by gurevichmark** [comment]
@jabl 

1. Perhaps leaving out the `-u` flag does not reset the boot mode and just keeps UEFI mode from the previous provision.
2. Yes, I was surprised to see `fat16` for RHEL 8 since xcat does not explicitly set it. So a a bug in parted or in the RHEL installer.
3. For Ubuntu, however, xCAT does specify `fat16` in `pre.ubuntu` which during provisioning, 
```
[root@c910f04x40 xcat]# rinstall c910f04x14 osimage=ubuntu18.04.2-x86_64-install-compute -u -V
[c910f04x40]: Provision node(s): c910f04x14
[c910f04x40]: Run command: nodeset c910f04x14 osimage=ubuntu18.04.2-x86_64-install-compute
[c910f04x40]: c910f04x14: install ubuntu18.04.2-x86_64-compute
[c910f04x40]: Run command: rsetboot c910f04x14 net -u
[c910f04x40]: c910f04x14: Network
[c910f04x40]: Run command: rpower c910f04x14 boot
[c910f04x40]: c910f04x14: reset
[root@c910f04x40 xcat]#
```
eventually generates this `/tmp/partitionfile` file:
```
ubuntu-efi ::
    512 512 1024 fat16
    $iflabel{ gpt } $reusemethod{ } method{ efi } format{ }
    .
500 10000 1000000000 ext4
    method{ format } format{ } use_filesystem{ } filesystem{ ext4 } mountpoint{ / }
    .
2048 512 300% linux-swap
    method{ swap } format{ }
    .
```
 But when the node provisions, `parted` shows `fat32`. 
```
root@c910f04x14:~# parted -l
Model: IBM ServeRAID M5110e (scsi)
Disk /dev/sda: 439GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End    Size    File system     Name  Flags
 1      1049kB  512MB  511MB   fat32                 boot, esp
 2      512MB   437GB  436GB   ext4
 3      437GB   439GB  2048MB  linux-swap(v1)
root@c910f04x14:~#
```
If I change the `pre.ubuntu` to specify `fat32`, when the node provisions, `parted` still shows `fat32`, but this time `Name` column is filled in:
```
root@c910f04x14:~# parted -l
Model: IBM ServeRAID M5110e (scsi)
Disk /dev/sda: 439GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End    Size    File system     Name                  Flags
 1      1049kB  512MB  511MB   fat32           EFI System Partition  boot, esp
 2      512MB   437GB  436GB   ext4
 3      437GB   439GB  2048MB  linux-swap(v1)
root@c910f04x14:~#
```
Does that make sense to you ?

**Comment by jabl** [comment]
Yup, looks good AFAICS.
