### ISSUE TITLE
Should use ext4 instead of ext3 when formatting node partitions

### ISSUE THREAD

**Issue by jabl** [xcat2/xcat-core#6673]
It's 2020, and there's no reason to use ext3 anymore. The ext3 driver itself was even removed from the kernel 5 years ago: https://github.com/torvalds/linux/commit/e31fb9e00543e5d3c5b686747d3c862bc09b59f3

In many places scripts, templates, documentation still use ext3, e.g. https://github.com/xcat2/xcat-core/search?q=ext3&unscoped_q=ext3

**Comment by gurevichmark** [comment]
Resolved by #6684
