### ISSUE TITLE
switchdiscover fails to discover switches with SNMP

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6693]
Hi,

It looks like `switchdiscover` assumes that the `entPhysicalDescr` SNMP OID is always present for switches. In practice that doesn't seem to be the case, and in particular, Dell Ethernet switches don't have anything in that `1.3.6.1.2.1.47.1.1.1.1.2.1` OID: 
```
$ snmpwalk -Os -v1 -c public 10.35.1.211 1.3.6.1.2.1.47.1.1.1.1.2.1
mib-2.47.1.1.1.1.2.1 = ""
```
They do have the correct information in the more common `sysDescr` OID, though, like most of the switches and PDUs out there:
```
$ snmpwalk -Os -v1 -c public 10.35.1.211 1.3.6.1.2.1.1.1
sysDescr.0 = STRING: Dell Networking N1548, 6.3.3.10, Linux 3.6.5
```

The OID choice is here: https://github.com/xcat2/xcat-core/blob/6c8bd56fc2137d62e984699de02ee654741646b0/xCAT-server/lib/xcat/plugins/switchdiscover.pm#L990

Shouldn't `sysDescr` be used for all switches and PDUs, rather than the less common `entPhysicalDescr`, to ensure maximal compatibility?

**Comment by cxhong** [comment]
I think we used `entPhysicalDescr` to have more description for the switches. 
Example of Edgecore switch:
```
# snmpwalk -Os -v1 -c public 172.21.208.6 1.3.6.1.2.1.1.1
sysDescr.0 = STRING: Cumulus Linux 3.5.3 (Linux Kernel 4.1.33-1+cl3u12)
# snmpwalk -Os -v1 -c public 172.21.208.6 1.3.6.1.2.1.47.1.1.1.1.2.1
mib-2.47.1.1.1.1.2.1 = STRING: "Edgecore arm-accton_as4610_54-r0 4610-54T-O-AC-B Chassis"
```
since we used `vendor` information to determine the `switchtype`, and xCAT switchinfo data file included enough strings to match the switch type.  I will change OID to `sysDescr`,  and I also add `Dell` to switchinfo data file.
