### ISSUE TITLE
Using Xcat in Virtualbox - rpower error

### ISSUE THREAD

**Issue by aolloh** [xcat2/xcat-core#6697]
Hello everyone,
i'm using xcat in virtualbox 6.1.6

I installed phpvirtualbox, i xcat on my master, it works perfectly
********************************************************************************************************
[root@master1 ~]# lsxcatd -a
Version 2.15.1 (git commit ab6295bdc1deb1827922d47755bfc68adec12389, built Wed Mar  4 16:43:16 EST 2020)
This is a Management Node
dbengine=SQLite
**********************************************************************************************
[root@master1 ~]# lsdef compute1
Object name: compute1
    arch=x86_64
    bmc=10.0.103.1
    bmcpassword=admin
    bmcusername=ADMIN
    groups=all,x86_64
    ip=10.0.3.1
    mac=08:00:27:18:67:bc
    mgt=ipmi
    netboot=xnba
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    provmethod=rhels7.1-x86_64-install-compute

[root@master1 ~]# nodels
compute1

*******************************************************************************************
I also installed phpvirtualbox (vboxweb-service, vboxdrv) on my compute1, it works well.

when i'm trying to poweron my compute, i have this error

_[root@master1 ~]# rpower compute1 on
compute1: [master1]: Error: ERROR: timeout_

Please someone has already configured xcat on a master and compute with virtualbox?
Please someone has a step by step procedure to set xcat properly in the virtual environment?

Thanks in advanced

**Comment by cxhong** [comment]
can u able to run use `ipmitool`?  
```
ipmitool -H 10.0.103.1 -U ADMIN -P admin chassis status
```
also, you can turn `xcatdebugmode` on in the site table, then run `rpower` on again to see which cmd failed.
```
# tabdump site | grep debug
"xcatdebugmode","1",,
```

**Comment by aolloh** [comment]
[root@master1 ~]# ping 10.0.103.1
PING 10.0.103.1 (10.0.103.1) 56(84) bytes of data.
64 bytes from 10.0.103.1: icmp_seq=1 ttl=64 time=0.744 ms
64 bytes from 10.0.103.1: icmp_seq=2 ttl=64 time=0.555 ms


[root@master1 ~]# ipmitool -H 10.0.103.1 -U ADMIN -P admin chassis status
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session


[root@master1 ~]# xcatdebug -f enable
Enabled the subroutine calling trace.
  Get the trace log from the /var/log/xcat/subcallingtrace

[root@master1 ~]# rpower compute1 on
compute1: [master1]: Error: ERROR: timeout


tail -f /var/log/xcat/subcallingtrace

....
Calling stack:
        at /opt/xcat/sbin/xcatd line 0.
        eval {...} called at /opt/xcat/sbin/xcatd line 0


***************Calling of subroutine *main::ssl_reaper***************
Thu May  7 17:55:38 2020
Arguments:
$VAR1 = 'CHLD';

Calling stack:
        at /usr/lib64/perl5/IO/Select.pm line 111.
        eval {...} called at /usr/lib64/perl5/IO/Select.pm line 111
        IO::Select::can_read('IO::Select=ARRAY(0x3fd33e8)', 30) called at /opt/xcat/sbin/xcatd line 1486

**Comment by cxhong** [comment]
this didn't look good 
```
[root@master1 ~]# ipmitool -H 10.0.103.1 -U ADMIN -P admin chassis status
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
```
Can u able ssh to the `10.0.103.1` with ADMIN/admin?  is this correct username/password?
try again with `lanplus` options.
```
ipmitool -I lanplus -H 10.0.103.1 -U ADMIN -P admin mc info
ipmitool -I lanplus -H 10.0.103.1 -U ADMIN -P admin chassis status
```

**Comment by aolloh** [comment]
This is what i did

[root@master1 ~]# mkdef -t node compute1 groups=all,x86_64 arch=x86_64 ip=10.0.3.1 bmc=10.0.103.1 bmcusername=ADMIN bmcpassword=admin mac=08:00:27:18:67:bc mgt=ipmi netboot=xnba provmethod=rhels7.1-x86_64-install-compute -f


*****************************************************************************
[root@master1 ~]# ssh 10.0.103.1
Warning: Permanently added '10.0.103.1' (ECDSA) to the list of known hosts.
Last login: Thu May  7 17:57:48 2020
[root@compute1 ~]#
***************************************************************************
[root@compute1 ~]# ip a s

2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:18:67:bc brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/16 brd 10.0.255.255 scope global noprefixroute dynamic enp0s3
       valid_lft 454sec preferred_lft 454sec
    inet6 fe80::a00:27ff:fe18:67bc/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

...
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:28:18:67:ba brd ff:ff:ff:ff:ff:ff
    inet 10.0.103.1/16 brd 10.0.255.255 scope global noprefixroute dynamic enp0s9
       valid_lft 401sec preferred_lft 401sec
    inet6 fe80::a00:28ff:fe18:67ba/64 scope link
       valid_lft forever preferred_lft forever
*************************************************************************************

[root@master1 ~]# ipmitool -I lanplus -H 10.0.103.1 -U ADMIN -P admin mc info
Error: Unable to establish IPMI v2 / RMCP+ session


[root@master1 ~]# ipmitool -I lanplus -H 10.0.103.1 -U ADMIN -P admin chassis status
Error: Unable to establish IPMI v2 / RMCP+ session

**Comment by cxhong** [comment]
virtualbox is managed via ipmi?  I am not familiar with virtualbox ,  but should be more like VMs, right?  who is manage or host the `compute1`?   check this doc for VMs
  https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/manage_vms.html?highlight=VM%20

**Comment by aolloh** [comment]
i have my physical machine where i installed Virtualbox.
On virtualbox, i created two virtual machines, one called master1 and the second compute1.
My goal is to use xcat on my master1 to power on and manage compute1.

**Comment by cxhong** [comment]
example of VM definition
```
# lsdef c910f04x35v02
Object name: c910f04x35v02
    arch=x86_64
    cons=kvm
    groups=all,vm35,computenode
    ip=10.4.35.2
    mac=42:11:0a:04:0e:02
    mgt=kvm
    netboot=xnba
    os=sle15
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,setupntp
    profile=compute
    provmethod=sle15-x86_64-install-compute
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=booted
    statustime=05-07-2020 02:27:44
    updatestatus=failed
    updatestatustime=04-17-2019 04:38:03
    vmcpus=1
    vmhost=c910f04x35
    vmmemory=4096
    vmnicnicmodel=e1000
    vmnics=br097,br4091,br4093
    vmstorage=dir:///var/lib/libvirt/images/
```

**Comment by aolloh** [comment]
[root@master1 ~]# lsdef compute1
Object name: compute1
    arch=x86_64
    bmc=10.0.103.1
    bmcpassword=admin
    bmcusername=ADMIN
    groups=all,x86_64
    ip=10.0.3.1
    mac=08:00:27:18:67:bc
    mgt=ipmi
    netboot=xnba
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    provmethod=rhels7.1-x86_64-install-compute


i have to add some parameters?

**Comment by cxhong** [comment]
yes,  please check above the doc.  
1) remove all the bmc attributes
2) change `mgt=ipmi` to `mgt=kvm`
3) add all those VM attributes.

**Comment by aolloh** [comment]
Hi cxhong
I did what you said, it worked

[root@master1 ~]# lsdef vm1
Object name: vm1
    groups=vm,all
    ip=192.168.122.1
    mac=42:59:c0:a8:7a:01
    mgt=kvm
    netboot=xnba
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    status=powering-on
    statustime=05-07-2020 22:38:55
    vmcpus=1
    vmhost=vm1
    vmmemory=1024
    vmnicnicmodel=virtio
    vmnics=virbr0
    vmstorage=dir:///var/lib/libvirt/images

***********************************************************************************
[root@master1 ~]# rpower vm1 on
vm1: on

*************************************************************************************************
[root@master1 ~]# virsh console vm1
Connected to domain vm1
Escape character is ^]

*************************************************************************************************
But this is not what a need.
My gool is to manage using xcat, another compute (already installed) which is on the same network with my master but not a vm installed on my master.

**Comment by cxhong** [comment]
VituralBox has hostname or ip address?  xCAT needs to know where hosts the `compute1`, like `kvm`, `bmc` or `hmc`  

in my example, `c910f04x35` is a KVM,   VMs are located in this host.
```
vmcpus=1
    vmhost=c910f04x35
    vmmemory=4096
    vmnicnicmodel=e1000
    vmnics=br097,br4091,br4093
    vmstorage=dir:///var/lib/libvirt/images/
```

**Comment by gurevichmark** [comment]
@aolloh Do you still need assistance with this issue ?

**Comment by gurevichmark** [comment]
Closing. Please reopen if problem persists.
