### ISSUE TITLE
confignics for RHEL8 creating invalid network-script

### ISSUE THREAD

**Issue by robers97** [xcat2/xcat-core#6714]
This network configuration:

# tabdump nics | grep launchgr
"launchgr","ib0!192.168.100.100,ib1!192.168.100.101,enp1s0f1!10.41.168.21",,,"ib0!Infiniband,ib1!Infiniband,enP9p7s0f1!Ethernet,enp1s0f0!Ethernet,enp1s0f1!Ethernet",,"ib0!192_168_100_0-255_255_255_0,ib1!192_168_100_0-255_255_255_0,enp1s0f1!pub",,,,,,

Creates this file for RHEL:

[root@launchgr network-scripts]# more ifcfg-enp1s0f1
DEVICE=enp1s0f1
BOOTPROTO=none
NM_CONTROLLED=no
IPADDR=10.41.168.21
NETMASK=255.255.252.0
ONBOOT=yes

This is now defunct with RHEL8.    It works if you remove the NM_CONTROLLED=no line.

**Comment by cxhong** [comment]
for the rhel8 ifcfg file, we should not see `NM_CONTROLLED=no`,  I looked around our test cluster, I  didn't see this in the `ifcfg-*` files.  xCAT will add this line if `network` or `wicked` service is running.

**Comment by cxhong** [comment]
@robers97 ,  did u use `confignics` for the postscripts on the node definition?  if it is,  change to use `confignetwork`

**Comment by robers97** [comment]
I did...  and will make that change.
Is this a general recommendation?

**Comment by cxhong** [comment]
yes
![image](https://user-images.githubusercontent.com/12398836/82482820-6bf94100-9aa5-11ea-9ee6-d9532b564056.png)
