### ISSUE TITLE
xcat does not remove old configuration

### ISSUE THREAD

**Issue by Hoeze** [xcat2/xcat-core#6724]
Hi, I'm trying the whole morning now to fix a problem with xCAT network configuration.
I tried to reset a host configuration because xcat did not delete some parameters:
```bash
# rmdef cn01
# cat servers.stanza | chdef -z
Error: [xcatmaster]: Could not find a node named 'cn01', skipping to the next node.
Error: [xcatmaster]: Attribute 'groups' is not specified for node 'cn01', skipping to the next node.
Error: [xcatmaster]: One or more errors occured when attempting to create or modify xCAT object definitions.
```

**Comment by gurevichmark** [comment]
Can you show the contents of `servers.stanza` ?

**Comment by Hoeze** [comment]
Thanks for your answer @gurevichmark.
It looks like this:
```
cn:
        objtype=group
        members=cn[01-05,90]
        hostnames=|cn(\d+)|cn($1)|

        ip=|192.168.2.($1+10)|
        otherinterfaces=|cn(\d+)|cn($1)-ipmi:192.168.3.($1+10)|
        nodetype=osi
        profile=cn-SL7
        provmethod=SL7x-x86_64-cn

# 
# node definitions
cn01:
        objtype=node
        interface=p5p1
        mac=24:5e:be:38:86:44!cn01|E0:DB:55:02:6F:02!cn01-idrac|
        nictypes.bond1=bond
        nicdevices.bond1="p5p1|p5p2"
```

**Comment by gurevichmark** [comment]
@Hoeze So is your concern here that since `cn01` definition was removed, the `chdef -z` should have failed ?

**Comment by gurevichmark** [comment]
@Hoeze Are you still seeing this problem ?

**Comment by Hoeze** [comment]
yes, still no solution.
We plan to set up a new xcat anyways now but it would be nice if I would know the solution to this problem.

**Comment by gurevichmark** [comment]
@Hoeze Can you please explain the problem in a little more detail ?
In your issue description, you said "xcat did not delete some parameters".
Do you mean when you ran `rmdef cn01` some things you expected to be removed, were not ?

**Comment by Hoeze** [comment]
@gurevichmark I do not quite remember but there was some error message with "cn01 already exists" or similar.
Unfortunately, I cannot reproduce it any more. I only get the error message from the first post all the time.

**Comment by gurevichmark** [comment]
@Hoeze When you say "group problem" do you mean the message that is displayed saying "Attribute 'groups' is not specified for node 'cn01', skipping to the next node." ?

**Comment by Hoeze** [comment]
Yes, exactly - sorry for the inaccuracy.

My expectation was that I can `rmdef` the node and then re-define it with `chdef`.
However, due to these two errors (as shown in the first post) this is not working:
```
Error: [xcatmaster]: Could not find a node named 'cn01', skipping to the next node.
Error: [xcatmaster]: Attribute 'groups' is not specified for node 'cn01', skipping to the next node.
```

**Comment by gurevichmark** [comment]
@Hoeze I think the problem here is that your node definition for `cn01` is missing the required attribute `groups`. If you add `groups=cn` to your stanza, it should work.

![image](https://user-images.githubusercontent.com/16106630/86602940-61213f80-bf71-11ea-9461-3a1b20196837.png)

**Comment by Hoeze** [comment]
Thanks a lot for this hint, this solved my problems.

Strangely, this was not required when I added an additional node... 
Is there also some kind of automatic group inheritance to nodes?

**Comment by gurevichmark** [comment]
Odd. The only inheritance I can think of is using `mkdef --template` option.
