### ISSUE TITLE
elilo-xcat-3.14-4.noarch can't netboot a kernel >8MB

### ISSUE THREAD

**Issue by traviswparker** [xcat2/xcat-core#6742]
ELILO can't boot a kernel larger than 8 MB. This is a known issue, see https://sourceforge.net/p/elilo/patches/19/

unfortunately Centos 8.2-2004 comes with an 8.9 MB kernel and my nodes all fail to boot after generating a new image.

Switching the firmware to BIOS to netboot using GRUB2 is a workaround for now.

**Comment by bybai** [comment]
@traviswparker ,
I think you can try to modify some code, and use xnba directly, skip ELILO.

**Comment by bybai** [comment]
@traviswparker ，you can edit "/tftpboot/xcat/xnba/nodes/xxxx.uefi" directly boot from kernel and initrd, do not use elilo, I got  success.

**Comment by cxhong** [comment]
@bybai  `nodeset` and `rinstall ` will  modify `/tftpboot/xcat/xnba/nodes/xxxx.uefi`  file.

I downloaded patch and working on `elilo` rpm now.

**Comment by bybai** [comment]
@cxhong, you can modify nodeset to change /tftpboot/xcat/xnba/nodes/xxxx.uefi to use ipxe scripts directly boot kernel and initrd, so that, it is no need to use elilo again.  
What is your patch for elilo?

**Comment by cxhong** [comment]
installed `gnu-efi` rpm to the rhels7.6 system
```
# rpm -qa | grep gnu-efi
gnu-efi-devel-3.0.8-2.el7.x86_64
gnu-efi-3.0.8-2.el7.x86_64
gnu-efi-utils-3.0.8-2.el7.x86_64
```
tried to build elilo rpm and hit this issue:
```
/usr/bin/gcc -I. -I/root/rpmbuild/BUILD/elilo/fs/.. -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol -I/root/rpmbuild/BUILD/elilo/fs/../efi110 -O2  -fno-stack-protector -fno-strict-aliasing -fpic -fshort-wchar -Wall -DENABLE_MACHINE_SPECIFIC_NETCONFIG -DCONFIG_LOCALFS -DCONFIG_NETFS -DCONFIG_CHOOSER_SIMPLE -DCONFIG_CHOOSER_TEXTMENU -DEFI_FUNCTION_WRAPPER -DCONFIG_x86_64  -c localfs.c -o localfs.o
In file included from /root/rpmbuild/BUILD/elilo/fs/../elilo.h:47:0,
                 from localfs.c:33:
/root/rpmbuild/BUILD/elilo/fs/../strops.h:30:16: error: conflicting types for 'StrnCpy'
 extern CHAR16 *StrnCpy(OUT CHAR16 *dst, IN const CHAR16 *src, UINTN count);
                ^
In file included from localfs.c:31:0:
/usr/include/efi/efilib.h:317:1: note: previous declaration of 'StrnCpy' was here
 StrnCpy (
 ^
localfs.c: In function 'localfs_infosize':
localfs.c:135:24: warning: variable 'lfs' set but not used [-Wunused-but-set-variable]
  localfs_priv_state_t *lfs;
                        ^
make[1]: *** [localfs.o] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/elilo/fs'
make: *** [fs] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.rUoNDp (%build)
```

**Comment by cxhong** [comment]
I downloaded old version of gnu-efi:  `gnu-efi-3.0g-2.el6.x86_64.rpm',  add `elilo-big-bzimage-limit.patch`.  I can able to build new version of elilo rpm `elilo-xcat-3.14-5.noarch.rpm`
tried to rinstall a node with osimage `rhels8.2.0-x86_64-netboot-compute` 
```
# ls -ltr /install/netboot/rhels8.2.0/x86_64/compute
total 379480
-rwxr-xr-x  1 root root   8913760 Jul  7 14:28 kernel
-rw-------  1 root root  44560650 Jul  7 14:29 initrd-stateless.gz
-rw-------  1 root root  42466485 Jul  7 14:30 initrd-statelite.gz
dr-xr-xr-x 20 root root       274 Jul  7 14:31 rootimg
-rw-r--r--  1 root root 292638013 Jul  7 14:31 rootimg.cpio.gz
```
the image loaded and node provisioned successfully.  

with `elilo-xcat-3.14-4.noarch.rpm` (8MB size limit),  I also can provision the node successfully.  maybe I did something wrong?

**Comment by cxhong** [comment]
@traviswparker 
I just provisioned centos8.2 osimage with current elilo-xcat-3.14.4,  had no issues:
```
]# ls -ltr /install/netboot/centos8/x86_64/compute/
total 372628
-rwxr-xr-x  1 root root   8913656 Jul  7 15:46 kernel
-rw-------  1 root root  44598894 Jul  7 15:47 initrd-stateless.gz
-rw-------  1 root root  42506648 Jul  7 15:47 initrd-statelite.gz
dr-xr-xr-x 20 root root       274 Jul  7 15:49 rootimg
-rw-r--r--  1 root root 285543034 Jul  7 15:49 rootimg.cpio.gz
```

**Comment by cxhong** [comment]
@traviswparker , @bybai 
I opened a PR https://github.com/xcat2/xcat-dep/pull/39,  and put newly elilo rpm in the `xcat-dep/elilo`, can you try it before I put into xcat-dep builds.

**Comment by jbd** [comment]
Hello everybody,

I ran into this problem while trying to boot a stateless 8.2.2004 centos image. The 3.14-5 elilo rpm did the trick for me !
