### ISSUE TITLE
How to disable genesis discovery when trying to install a node

### ISSUE THREAD

**Issue by urielrosen** [xcat2/xcat-core#6746]
Hi ,

I am running the below version of xcat , recently genesis  module was implemented on our server by an IT person that 
left the organization , My problem is that when trying to deploy a server with "rinstall cnxxx"
the server sometimes boots into genesis discovery mode and not to a regular os install , 
How can I disable the genesis mechanism without harming its settings and installation and install my node regularly
without being directed to genesis ? 

lsxcatd -a
Version 2.14.6 (git commit 7c787c499ebca7a98d6fcdb3577f701ac16d7ab3, built Fri Mar 29 03:19:08 EDT 2019)

**Comment by gurevichmark** [comment]
Can you show the output of `lsdef cnxxx` ?

**Comment by urielrosen** [comment]
Hi,

Output is bellow .



Object name: cn227
    arch=x86_64
    bmc=cnXXXX
    bmcpassword=XXXXX
    bmcusername=wexac-ilo
    cons=ipmi
    currchain=boot
    currstate=install centos7.6-x86_64-compute
    groups=DELL_C6420_Centos7.6
    initrd=xcat/osimage/centos7.3/initrd.img
    installnic=p4p1
    interface=eth0
    kcmdline=quiet inst.repo=http://132.76.220.21:80/install/centos7.3/x86_64 inst.ks=http://10.0.0.100:80/install/autoinst/cn227 ip=eth4:dhcp
    kernel=xcat/osimage/centos7.3/vmlinuz
    mac=3C:FD:FE:75:AC:50
    mgt=ipmi
    netboot=xnba
    nfsserver=10.0.0.100
    os=centos7.6
    postbootscripts=syncfiles,net_DELL_C6420-p3p1,NTP,LSF
    postscripts=remoteshell,otherpkgs,gmond,POST,centos7.3/wexac.post,sssd,wexac_7.post,install_MLNX_OFED_LINUX-4.6-1.0.1.1_Centos7.6,fstab,Dell_supportassist.sh,install_gpfs_client.sh
    primarynic=p4p1
    profile=compute
    provmethod=centos7.6
    status=powering-on
    statustime=06-11-2020 12:59:46
    tftpserver=10.0.0.100
    updatestatus=failed
    updatestatustime=05-07-2020 17:20:36


Thanks,
Uriel.

**Comment by urielrosen** [comment]
My main question is how to disable the discovery feature while keeping it intact .


Thanks,
Uriel.


From: Uriel Rosen
Sent: Thursday, June 25, 2020 7:45 AM
To: 'xcat2/xcat-core' <reply@reply.github.com>; xcat2/xcat-core <xcat-core@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [xcat2/xcat-core] How to disable genesis discovery when trying to install a node (#6746)

Hi,

Output is bellow .



Object name: cn227
    arch=x86_64
    bmc=cnXXXX
    bmcpassword=XXXXX
    bmcusername=wexac-ilo
    cons=ipmi
    currchain=boot
    currstate=install centos7.6-x86_64-compute
    groups=DELL_C6420_Centos7.6
    initrd=xcat/osimage/centos7.3/initrd.img
    installnic=p4p1
    interface=eth0
    kcmdline=quiet inst.repo=http://132.76.220.21:80/install/centos7.3/x86_64 inst.ks=http://10.0.0.100:80/install/autoinst/cn227 ip=eth4:dhcp
    kernel=xcat/osimage/centos7.3/vmlinuz
    mac=3C:FD:FE:75:AC:50
    mgt=ipmi
    netboot=xnba
    nfsserver=10.0.0.100
    os=centos7.6
    postbootscripts=syncfiles,net_DELL_C6420-p3p1,NTP,LSF
    postscripts=remoteshell,otherpkgs,gmond,POST,centos7.3/wexac.post,sssd,wexac_7.post,install_MLNX_OFED_LINUX-4.6-1.0.1.1_Centos7.6,fstab,Dell_supportassist.sh,install_gpfs_client.sh
    primarynic=p4p1
    profile=compute
    provmethod=centos7.6
    status=powering-on
    statustime=06-11-2020 12:59:46
    tftpserver=10.0.0.100
    updatestatus=failed
    updatestatustime=05-07-2020 17:20:36


Thanks,
Uriel.

**Comment by gurevichmark** [comment]
@urielrosen Can you run some config verifications:

`xcatprobe xcatmn`
`xcatprobe osimagecheck --osimage=centos7.6`
`nslookup cn227`
`cat /tftpboot/xcat/xnba/nodes/cn227`

Also, your node definition has `tftpserver=10.0.0.100` is that the same IP as the xCAT management node ?

**Comment by urielrosen** [comment]
Hi ,

Output of the commands you requested to run is below , please note that ip address
Were manipulated by me because of information security ,
Please advice .



nslookup cn227
Server:         X.Y.22.1
Address:        X.Y.22.1#53

Name:   cn227.wexac.weizmann.ac.il
Address: X.Y.214.47

[root@xcat MLNX]# cat /tftpboot/xcat/xnba/nodes/cn227
#!gpxe
#install centos7.6-x86_64-compute
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/osimage/centos7.6/vmlinuz
imgload kernel
imgargs kernel inst.repo=http://10.0.0.100:80/install/centos7.6/x86_64 inst.ks=http://10.0.0.100:80/install/autoinst/cn227 ip=p4p1:dhcp  inst.loglevel=debug inst.syslog=10.0.0.100 BOOTIF=01-${netX/machyp}
imgfetch http://${next-server}:80/tftpboot/xcat/osimage/centos7.6/initrd.img
imgexec kernel



xcatprobe osimagecheck --osimage=centos7.6
==> Checking for duplicate usage of the rootimgdir in diskless images...                                          [INFO]
No diskless osimages with identical root image directories were found.                                            [ OK ]
==> Checking for valid osimage template attribute ...                                                             [INFO]
==> Checking that valid files are specified in osimage attributes ...                                             [INFO]
Files specified in the osimage attributes seem to be valid.                                                       [ OK ]
[root@xcat MLNX]# xcatprobe osimagecheck --osimage=centos7.3
==> Checking for duplicate usage of the rootimgdir in diskless images...                                          [INFO]
No diskless osimages with identical root image directories were found.                                            [ OK ]
==> Checking for valid osimage template attribute ...                                                             [INFO]
==> Checking that valid files are specified in osimage attributes ...                                             [INFO]
Files specified in the osimage attributes seem to be valid.




xcatprobe xcatmn


[mn]: Checking all xCAT daemons are running...                                                                    [ OK ]
[mn]: Checking xcatd can receive command request...                                                               [ OK ]
[mn]: Checking 'site' table is configured...                                                                      [ OK ]
[mn]: No interface provided by '-i' option, detected site table IP attribute 10.0.0.100, checking xCAT confi...[WARN]
[mn]: If this is incorrect, rerun with -i <ifname> option                                                         [WARN]
[mn]: Checking provision network is configured...                                                                 [ OK ]
[mn]: Checking 'passwd' table is configured...                                                                    [ OK ]
[mn]: Checking important directories(installdir,tftpdir) are configured...                                        [ OK ]
[mn]: Checking SELinux is disabled...                                                                             [ OK ]
[mn]: Checking HTTP service is configured...                                                                      [ OK ]
[mn]: Checking TFTP service is configured...                                                                      [WARN]
[mn]: TFTP service based on xCAT is not running
[mn]: Checking DNS service is configured...                                                                       [ OK ]
[mn]: Checking DHCP service is configured...                                                                      [ OK ]
[mn]: Checking NTP service is configured...                                                                       [FAIL]
[mn]: Unexpected ntpq output <localhost: timed out, nothing received>, please contact xCAT team
[mn]: Checking rsyslog service is configured...                                                                   [FAIL]
[mn]: rsyslog service is not running! Please check on current node
[mn]: Checking firewall is disabled...                                                                            [ OK ]
[mn]: Checking minimum disk space for xCAT ['/var' needs 1GB;'/install' needs 10GB;'/tmp' needs 1GB]...           [ OK ]
[mn]: Checking Linux ulimits configuration...                                                                     [ OK ]
[mn]: Checking network kernel parameter configuration...                                                          [ OK ]
[mn]: Checking xCAT daemon attributes configuration...                                                            [ OK ]
[mn]: Checking xCAT log is stored in /var/log/xcat/cluster.log...                                                 [ OK ]
[mn]: Checking xCAT management node IP: <10.0.0.100> is configured to static...                                [ OK ]
[mn]: Checking dhcpd.leases file is less than 100M...                                                             [ OK ]
=================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [FAIL]
    No interface provided by '-i' option, detected site table IP attribute 10.0.0.100, checking xCAT configu...[WARN]
    If this is incorrect, rerun with -i <ifname> option                                                           [WARN]
    Checking TFTP service is configured...                                                                        [WARN]
        TFTP service based on xCAT is not running
    Checking NTP service is configured...                                                                         [FAIL]
        Unexpected ntpq output <localhost: timed out, nothing received>, please contact xCAT team
    Checking rsyslog service is configured...                                                                     [FAIL]
        rsyslog service is not running! Please check on current node


Thanks,
Uriel.

**Comment by gurevichmark** [comment]
@urielrosen The `xcatprobe` seems to indicate that `tftp` service is not running.

This might explain what is happening. The compute node gets the genesis kernel, and then requests the OS image from the management node. But since tftp service is not running on the management node, the OS image never gets sent to the compute node.

Also in your original problem description, you said _the server sometimes boots into genesis discovery mode_. Does that mean that sometimes it does boot into the OS ?

**Comment by urielrosen** [comment]
Yes , it is strange only in some cases it goes into genesis , in most cases I am able to provision a regular diskfull image of centos .
What is the easiest way to disable genesis , I don’t need it running now at all ?


Thanks,
Uriel.

**Comment by gurevichmark** [comment]
I do not think there is a way to disable that.

My understanding is that when node is being provisioned, it always gets the genesis kernel. Then, the compute node requests the OS image from the tftp server, usually the management node. In your case, tftp server is not running on management node, so the compute node does not receive the OS image and remains in genesis.

**Comment by urielrosen** [comment]
Hi,

This makes no sense because I can provision most nodes , only in particular cases the genesis screen appears .
Is there a way to remove genesis without harming the rest of xcat operation ?


Thanks,
Uriel.

**Comment by bybai** [comment]
@urielrosen , 
I guess your node IP is within one of DHCP dynamic range.
You can delete your DHCP dynamic range, so that it will not enter genesis discovery any more.

**Step**:
1,  delete dynamicrange in networks table, you can use "tabedit networks", edit it like vim.
2, edit "/etc/dhcp/dhcpd.conf", comment lines like:
range dynamic-bootp xx.xx.xx.xx yy.yy.yy.yy;
3, restart dhcpd and xcatd:
service dhcpd restart
service xcatd restart
4, if you want to use genesis to discover, you need to add dynamic range again and restart dhcpd and xcatd.

Hope this can help you.

**Comment by urielrosen** [comment]
Hi ,

Will this not affect my regular server provisioning ?


Thanks,
Uriel.

**Comment by gurevichmark** [comment]
@bybai Thank you for trying to help with this issue. Since the `xcatprobe` indicated that `tftpd` is not running. Do you think that could be a problem ?

@urielrosen Before trying the changes @bybai suggested. Can you show the output of the following:
* `tabdump networks`
* `makedhcp -q cn227`
* `xcatprobe detect_dhcpd -i <NIC> -m <MAC>` where \<NIC\> is the interface facing the network and \<MAC\> is the cn227 mac returned by the `makedhcp -q command`. On my system, it is `xcatprobe detect_dhcpd -i enP2p1s0f0 -m 0c:c4:7a:d2:cf:f7`

We want to verify that only one DHCP server is on the network and that the IP assigned to the cn227 does not appear in the `dynamicrange` field of `networks` table.

**Comment by bybai** [comment]
@gurevichmark , I do not know if they use another tftp server or not. Since genesis is also under tftp, nodes can download the genesis kernel and ramfs, I guess the DHCP dynamic range affect the results or there is another DHCP server.

**Comment by urielrosen** [comment]
Hi,

Output is below , I edited some IP addresses due to information security ,  I noticed that “makedhcp -q cn227”
Gave me wrong ip and mac address compared to lsdef cn227 but regardless of that I would like to understand how to stop the operation of the genesis system which now
Is harming some of my deployments.



  *   tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"x_x_220_0-255_255_252_0","x.x.220.0","255.255.252.0","eth0","<xcatmaster>",,"<xcatmaster>",,,,"x.x.223.130-x.x.223.199",,,,,,,"1500",,
"Managment","x.x.208.0","255.255.252.0","eth1","x.x.211.245",,"x.x.211.100",,,,,,,,,,,,,
"ib-network","10.1.220.0","255.255.252.0",,,,,"x.x.220.21",,,,,,,,,,"4092",,



  *   makedhcp -q cn227
makedhcp -q cn227
cn227: ip-address = x.x.221.2, hardware-address = 00:1e:68:2f:bf:fa



·        xcatprobe


Start to detect DHCP, please wait 10 seconds                                                                      [INFO]
++++++++++++++++++++++++++++++++++                                                                                [INFO]
There are 1 servers replied to dhcp discover.                                                                     [INFO]
    Server:x.x.220.21 assign IP [x.x.223.184]. The next server is [132.76.220.21]!





Thanks,
Uriel.

**Comment by gurevichmark** [comment]
@bybai 
1. Looking at the node definition `tftpserver=10.0.0.100` which I assume is MN, but running `xcatprobe` showed that "TFTP service based on xCAT is not running"
2. My understanding is that there is no way to prevent genesis kernel from being initially sent to the node. Since the user is just doing `rinstall`, we will always send genesis kernel via DHCP and then OS image via TFTP.

@urielrosen 
1. It is very strange that `makedhcp -q` returns values for that node that are different from the node definition. Is this the only node that is sometimes booting into genesis, or are there others ? 
2. One other thing you can try is: kickoff `rinstall cn227 osimage=....` and then right after that, issue `xcatprobe osdeploy -n cn227 -V`.

**Comment by gurevichmark** [comment]
@urielrosen Is this still a problem that needs to be resolved ?

**Comment by gurevichmark** [comment]
Closing. Please reopen if problem persists.

**Comment by urielrosen** [comment]
Ok thanks ,
Had no time to check this , if I reencounter this will contact you.


Thanks,
Uriel.
