### ISSUE TITLE
Difficulty getting KVM VM to pick up bootp image from xcat control node

### ISSUE THREAD

**Issue by AndyDevman** [xcat2/xcat-core#6758]
Hi All,

I have been attempting to setup VMs on a remote KVM host controlled by an xCAT management node.
I have managed to define the VM correctly, with the ability to create a VM and its disk file on the remote KVM host.
I have been experiencing issues however when attempting to 'install' an OS on the VM - i,e when running rinstall vm1.
When monitoring the serial console of the vm1, you can see the process start but the pxe process seems to fail with the following error;
No configuration methods succeeded (http://ipxe.org/040ee119).

When simultaneously running 
xcatprobe osdeploy -n vm1   -p phase -V

the system records that the vm1 node is receiving an IP address as expected but doesn't seem to go beyond getting an IP.

I have been monitoring the management nodes tcp stack on the cluster NIC using the tcpdump command and can see that there is a reference to bootp as follows;
18:36:27.301444 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 42:15:c0:a8:00:04 (oui Unknown), length 400
18:36:27.301653 IP xcat-control-node.bootps > vm1.bootpc: BOOTP/DHCP, Reply, length 330

I am not sure where I am going wrong with this.  
Do I need to specify the initrd field for the vm ?

Thanks in advance for any suggestions

**Comment by gurevichmark** [comment]
@AndyDevman 
Can you show your node definition for `vm1` ?

**Comment by AndyDevman** [comment]
Hi @gurevichmark ,

here's the node definition for vm1
Object name: vm1
    arch=x86_64
    cons=kvm
    consoleenabled=1
    currchain=boot
    currstate=netboot centos8.1-x86_64-compute
    groups=vm,all
    ip=192.168.2.85
    mac=42:15:c0:a8:00:04
    mgt=kvm
    netboot=xnba
    os=centos8.1
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos8.1-x86_64-netboot-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=07-06-2020 18:35:48
    vmcpus=1
    vmhost=xcat-openbmc-node
    vmmemory=512
    vmnicnicmodel=virtio
    vmnics=virbr1
    vmstorage=dir:////virtual-machines/xCAT/vm1

**Comment by gurevichmark** [comment]
The `vmmemory` seems a bit low. Try `vmmemory=4096`
Also, set `tftpserver` and `xcatmaster` attributes to be your xCAT management node.

**Comment by AndyDevman** [comment]
Hi @gurevichmark , thanks for the suggestions.

I've upped the vmmemory and, set the tftpserver and xcatmaster attributes for the vm1 node.  The PXE process seems to still be getting stuck.  The DHCPOFFER is made from the xcat server to the vm1 node with an IP, but the vm1 node sends another DHCPREQUEST after the offer is made.  I dont think the vm1 is receiving the image to boot from

**Comment by gurevichmark** [comment]
@AndyDevman 
When you run `makedhcp -q vm1` do you get back the correct MAC and IP back ?

Also, can you run this, to make sure only one DHCP server is serving IPs on your network ?
`xcatprobe detect_dhcp -i <interface> -m 42:15:c0:a8:00:04`

**Comment by AndyDevman** [comment]
Hi @gurevichmark 

I do get the correct MAC and IP back  when running the following command (in case you're wondering why the IP is different - i changed the address of the VM to .44 to be outside the dynamic range from the networks table)

makedhcp -q vm1
vm1: ip-address = 192.168.2.44, hardware-address = 42:15:c0:a8:00:04

When running the xcatprobe command, the server only discovers the xcat control node as the DHCP server - excerpt from output below;
There are 1 servers replied to dhcp discover.                                                                                         [INFO]
    Server:192.168.2.10 assign IP [192.168.2.56]. The next server is [192.168.2.10]!                                 [INFO]

**Comment by gurevichmark** [comment]
@AndyDevman There seems to be a mismatch of IPs ?

`makedhcp -q` returns `192.168.2.44`
`xcatprobe` returns `192.168.2.56`
`lsdef vm1` returns `192.168.2.85`

Try making them all the same, verify that `/etc/hosts` has the wanted IP for `vm1`.
Then run `makedns` and `makedhcp -a`
After that verify with `nslookup vm1`,  `makedhcp -q vm1` and `xcatprobe detect_dhcpd` again.

**Comment by AndyDevman** [comment]
Hi @gurevichmark , thanks for your help with this.
I did change the vm1 IP settings as it was originally part of the xcat dhcp range and it was failing to create its record when running the makedhcp command due to the conflict.  

 **lsdef vm1**
Object name: vm1
    arch=x86_64
    cons=kvm
    consoleenabled=1
    currchain=boot
    currstate=install centos8.1-x86_64-compute
    groups=vm,all
    ip=192.168.2.44
    mac=42:15:c0:a8:00:04
    mgt=kvm
    netboot=xnba
    os=centos8.1
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=centos8.1-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=07-07-2020 16:48:52
    tftpserver=xcat-control-node
    vmcpus=1
    vmhost=xcat-openbmc-node
    vmmemory=4096
    vmnicnicmodel=virtio
    vmnics=virbr1
    vmstorage=dir:////virtual-machines/xCAT/vm1
    xcatmaster=xcat-control-node


**nslookup**
[root@xcat-control-node ~]# nslookup vm1.ironman.cluster
Server:         192.168.2.10
Address:        192.168.2.10#53

Name:   vm1.ironman.cluster
Address: 192.168.2.44


**makedhcp**
[root@xcat-control-node ~]# makedhcp -q vm1
vm1: ip-address = 192.168.2.44, hardware-address = 42:15:c0:a8:00:04

**xcatprobe**
xcatprobe detect_dhcpd -i ens224 -m 42:15:c0:a8:00:04
Start to detect DHCP, please wait 10 seconds                                                                      [INFO]
++++++++++++++++++++++++++++++++++                                                                                [INFO]
There are 1 servers replied to dhcp discover.                                                                     [INFO]
    Server:192.168.2.10 assign IP [192.168.2.44]. The next server is [192.168.2.10]!                              [INFO]
++++++++++++++++++++++++++++++++++



**tcpdump - running on the control node**

16:49:31.121318 IP (tos 0x0, ttl 64, id 1246, offset 0, flags [none], proto UDP (17), length 428)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 42:15:c0:a8:00:04 (oui Unknown), length 400, xid 0x1b93744b, secs 16, Flags [none] (0x0000)
          Client-Ethernet-Address 42:15:c0:a8:00:04 (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            MSZ Option 57, length 2: 1472
            ARCH Option 93, length 2: 0
            NDI Option 94, length 3: 1.2.1
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
            User-Class Option 77, length 4:
              instance#1: ERROR: invalid option
            Parameter-Request Option 55, length 23:
              Subnet-Mask, Default-Gateway, Domain-Name-Server, LOG
              Hostname, Domain-Name, RP, MTU
              Vendor-Option, Vendor-Class, TFTP, BF
              Option 119, Option 128, Option 129, Option 130
              Option 131, Option 132, Option 133, Option 134
              Option 135, Option 175, Option 203
            T175 Option 175, length 48: 2969895194,4094689515,50397184,385941794,16847617,17891585,654377241,16846849,35717377,352387352,16852481,17957121
            Client-ID Option 61, length 7: ether 42:15:c0:a8:00:04
            GUID Option 97, length 17: 0.17.177.243.106.183.184.17.234.155.48.66.68.192.168.0.4
16:49:31.121477 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 358)
    xcat-control-node.bootps > vm1.bootpc: [udp sum ok] BOOTP/DHCP, Reply, length 330, xid 0x1b93744b, secs 16, Flags [none] (0x0000)
          Your-IP vm1
          Server-IP xcat-control-node
          Client-Ethernet-Address 42:15:c0:a8:00:04 (oui Unknown)
          file "xcat/xnba.kpxe"[|bootp]

**Comment by gurevichmark** [comment]
@AndyDevman 
Can you 
* verify that `xcat-control-node` resolves to `192.168.2.10`
* show contents of `/tftpboot/xcat/xnba/nodes/vm1`
* run `xcatprobe xcatmn -i <install_nic>` to verify MN is configured correctly.

**Comment by AndyDevman** [comment]
Hi @gurevichmark , here are the outputs requested.  thanks

[root@xcat-control-node ~]# ping xcat-control-node
PING xcat-control-node (192.168.2.10) 56(84) bytes of data.
64 bytes from xcat-control-node (192.168.2.10): icmp_seq=1 ttl=64 time=0.026 ms
64 bytes from xcat-control-node (192.168.2.10): icmp_seq=2 ttl=64 time=0.044 ms
64 bytes from xcat-control-node (192.168.2.10): icmp_seq=3 ttl=64 time=0.041 ms
64 bytes from xcat-control-node (192.168.2.10): icmp_seq=4 ttl=64 time=0.054 ms


**xcatprobe xcatmn**
[root@xcat-control-node ~]# xcatprobe xcatmn -i ens224
[mn]: Checking all xCAT daemons are running...                                                                    [ OK ]
[mn]: Checking xcatd can receive command request...                                                               [ OK ]
[mn]: Checking 'site' table is configured...                                                                      [ OK ]
[mn]: Checking provision network is configured...                                                                 [ OK ]
[mn]: Checking 'passwd' table is configured...                                                                    [ OK ]
[mn]: Checking important directories(installdir,tftpdir) are configured...                                        [ OK ]
[mn]: Checking SELinux is disabled...                                                                             [ OK ]
[mn]: Checking HTTP service is configured...                                                                      [ OK ]
[mn]: Checking TFTP service is configured...                                                                      [ OK ]
[mn]: Checking DNS service is configured...                                                                       [ OK ]
[mn]: Checking DHCP service is configured...                                                                      [ OK ]
[mn]: Checking NTP service is configured...                                                                       [ OK ]
[mn]: Checking rsyslog service is configured...                                                                   [ OK ]
[mn]: Checking firewall is disabled...                                                                            [ OK ]
[mn]: Checking minimum disk space for xCAT ['/var' needs 1GB;'/install' needs 10GB;'/tmp' needs 1GB]...           [ OK ]
[mn]: Checking Linux ulimits configuration...                                                                     [ OK ]
[mn]: Checking network kernel parameter configuration...                                                          [ OK ]
[mn]: Checking xCAT daemon attributes configuration...                                                            [ OK ]
[mn]: Checking xCAT log is stored in /var/log/xcat/cluster.log...                                                 [ OK ]
[mn]: Checking xCAT management node IP: <192.168.2.10> is configured to static...                                 [ OK ]
[mn]: Checking dhcpd.leases file is less than 100M...                                                             [ OK ]
=================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [ OK ]



**[root@xcat-control-node compute]# cat /tftpboot/xcat/xnba/nodes/vm1**
#!gpxe
#netboot centos8.1-x86_64-compute
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/osimage/centos8.1-x86_64-netboot-compute/kernel
imgload kernel
imgargs kernel imgurl=http://192.168.2.10:80//install/netboot/centos8.1/x86_64/compute/rootimg.cpio.gz XCAT=192.168.2.10:3001 NODE=vm1 FC=0 XCATHTTPPORT=80  console=tty0 console=ttyS0,115200 BOOTIF=01-${netX/machyp}
imgfetch http://${next-server}:80/tftpboot/xcat/osimage/centos8.1-x86_64-netboot-compute/initrd-stateless.gz
imgexec kernel

**Comment by gurevichmark** [comment]
@AndyDevman Can you look into `/var/log/xcat/cluster.log` to see if any interesting errors logged when doing the `rinstall`
Can you also send the serial console output just before the error ?

**Comment by AndyDevman** [comment]
@gurevichmark thanks for this - here are the outputs

**Serial output from the VM**
_iPXE (http://ipxe.org) 00:03.0 CB00 PCI2.10 PnP PMM+BFF90840+BFED0840 CB00
                                                                               


Booting from ROM...
iPXE (PCI 00:03.0) starting execution...ok
iPXE initialising devices...ok



iPXE 1.0.0+ -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP VLAN AoE ELF MBOOT PXE bzImage Menu PXEXT

net0: 42:15:c0:a8:00:04 using virtio-net on 0000:00:03.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 42:15:c0:a8:00:04)............................................
................ No configuration methods succeeded (http://ipxe.org/040ee119)
No more network devices

Booting from Hard Disk...                
Boot failed: not a bootable disk

No bootable device._


**output from cluster.log file** [this is just todays]
Jul  8 17:10:49 xcat-control-node xcat[71219]: INFO xCAT: Allowing rinstall to vm1 for root from localhost
Jul  8 17:11:01 xcat-control-node xcat[71266]: INFO xcat.updatestatus - vm1: changing status=powering-on

**Comment by gurevichmark** [comment]
Perhaps it is a problem configuring the network adapter ?
Can you try `ip addr show virbr1` on the `xcat-openbmc-node`

**Comment by AndyDevman** [comment]
Hi @gurevichmark .  Not sure if it is a is config of the adapter. 
Heres the output below.

xCAT-OpenBMC-Node ~]$ ip addr show virbr1
4: virbr1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:50:56:b2:ce:cc brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.95/24 brd 192.168.2.255 scope global dynamic noprefixroute virbr1
       valid_lft 40491sec preferred_lft 40491sec
    inet6 fe80::fc15:c0ff:fea8:4/64 scope link
       valid_lft forever preferred_lft forever

**Comment by gurevichmark** [comment]
@AndyDevman 
Have you tried installing diskless ?

**Comment by AndyDevman** [comment]
@gurevichmark , do you mean with the netboot type image selected ? ie.

centos8.1-x86_64-netboot-compute

**Comment by gurevichmark** [comment]
Yes. You will need to run `genimage` and `packimage` on `centos8.1-x86_64-netboot-compute`

**Comment by AndyDevman** [comment]
Unfortunately the PXE process finishes with the same error,
'No configuration methods succeeded'

**Comment by gurevichmark** [comment]
Hmm, I am out of ideas here.
The last thing you could try is to set `vmnicnicmodel=e1000`

**Comment by gurevichmark** [comment]
By the way, after making any changes, like above, to the node definition, you should `rmvm` and then `mkvm`.

**Comment by AndyDevman** [comment]
@gurevichmark thanks very much for all the help and suggestions.
Unfortunately , i have tried a few other nic models but none of them seem to make a difference.
I have manually created a VM on the same network on the openbmc host and can see it is also having issues with networking, so I'm wondering if the issue is more of a general config issue. 
This is despite the DHCPDISCOVER and DHCPOFFER messages successfully getting through.

**Comment by AndyDevman** [comment]
The OpenBMC host has 2 NICs.  One is sort of access network - ens224.  The other is the network through which XCAT control node and the OpenBMC node are talking.  It is also the network which I want the vm1 to connect to - ens192 - via the bridge br0.
I created a bridge network br0, and set the ens192 NIC as a slave on the bridge.  A new virtual network has been defined using virsh called br0-virsh and is set bridged to br0. 

Just wondering if I have been going about this the wrong way ?  Should I be defining which virtual virsh network the vm sits on rather than defining the vmnic parameter?

**Comment by AndyDevman** [comment]
Hi @gurevichmark .   Just a quick update on this.
I have managed to resolve the issue I was seeing.  The solution was to enable 'promiscuous mode' for the vSwitch on the ESX host.
For anyone else that is testing out xCAT through management of a QEMU/KVM nested hypervisor within a VMware environment, you need to enable 'promiscuous mode' for the vSwitch/network as follows;
-Select the host where the network resides
-Go to the Configure area
-Select Networking > Virtual Switches
-Select the network you are using for communication between your KVM hypervisor and the xCat management node
-Edit the network , choose Security and set 'Promiscuous mode' to accept.

**Comment by gurevichmark** [comment]
Glad to hear you got this resolved.

**Comment by besawn** [comment]
@AndyDevman Thanks for contributing your solution back for the benefit of others. I'm glad you were able to find a solution.
