### ISSUE TITLE
Cloning feature don't work Centos 7.8

### ISSUE THREAD

**Issue by alexnovik** [xcat2/xcat-core#6766]
On management node:

[root@servicenew xcat]# cat /opt/xcat/share/xcat/install/rh/sysclone.rhels7.x86_64.otherpkgs.pkglist 
xcat/xcat-dep/rh7/x86_64/systemimager-client

[root@servicenew xcat]# chdef -t osimage -o centos7.8-x86_64-install-compute otherpkglist=/opt/xcat/share/xcat/install/rh/sysclone.rhels7.x86_64.otherpkgs.pkglist 
1 object definitions have been created or modified.

[root@servicenew xcat]# chdef -t osimage -o centos7.8-x86_64-install-compute -p otherpkgdir=/install/post/otherpkgs/centos7.8/x86_64/
1 object definitions have been created or modified.

[root@servicenew xcat]# updatenode cn34 -S
Performing software maintenance operations. This could take a while, if there are packages to install.
cn34: bash: /tmp/3Uc_VxWDr2.dsh: No such file or directory
cn34: rm: cannot remove '/tmp/3Uc_VxWDr2.dsh': No such file or directory
Error: [servicenew]:  cn34 remote shell had exit code 1.

[root@servicenew xcat]# ls /opt/xcat/share/xcat/install/rh/
compute_ad.rhels6.tmpl         compute.rhels8.tmpl                 service.ppc64.pkglist                     service.rhels8.tmpl
compute.pkglist                compute.tmpl                        service.ppc64.tmpl                        service.rhels8.x86_64.otherpkgs.pkglist
compute.ppc64.pkglist          cudafull.rhels7.ppc64le.pkglist     service.raid1.multipath.rhel6.ppc64.tmpl  service.tmpl
compute.ppc64.tmpl             cudaruntime.rhels7.ppc64le.pkglist  service.raid1.rhel6.ppc64.tmpl            storage.pkglist
compute.rhel4.pkglist          hpc.rhels6.pkglist                  service.rhels5.ppc64.otherpkgs.pkglist    storage.rhels6.pkglist
compute.rhel4.tmpl             hpc.rhels6.tmpl                     service.rhels5.x86_64.otherpkgs.pkglist   storage.rhels6.tmpl
compute.rhel5.ppc64.tmpl       iscsi.pkglist                       service.rhels5.x86.otherpkgs.pkglist      storage.tmpl
compute.rhel5.s390x.pkglist    iscsi.ppc64.pkglist                 service.rhels6.ppc64.otherpkgs.pkglist    sysclone.rhels5.x86_64.otherpkgs.pkglist
compute.rhel5.s390x.tmpl       iscsi.ppc64.tmpl                    service.rhels6.ppc64.pkglist              sysclone.rhels6.ppc64.otherpkgs.pkglist
compute.rhelhpc6.pkglist       iscsi.rhels6.tmpl                   service.rhels6.ppc64.tmpl                 sysclone.rhels6.x86_64.otherpkgs.pkglist
compute.rhelhpc6.tmpl          iscsi.tmpl                          service.rhels6.x86_64.otherpkgs.pkglist   sysclone.rhels7.ppc64le.otherpkgs.pkglist
compute.rhels6.pkglist         kvm.pkglist                         service.rhels6.x86_64.pkglist             sysclone.rhels7.ppc64.otherpkgs.pkglist
compute.rhels6.ppc64.pkglist   kvm.rhel6.pkglist                   service.rhels6.x86_64.tmpl                sysclone.rhels7.x86_64.otherpkgs.pkglist
compute.rhels6.ppc64.tmpl      kvm.rhel6.tmpl                      service.rhels7.ppc64le.otherpkgs.pkglist  xen.pkglist
compute.rhels6.s390x.pkglist   kvm.rhels5.pkglist                  service.rhels7.ppc64le.pkglist            xen.rhels6.tmpl
compute.rhels6.s390x.tmpl      kvm.rhels5.tmpl                     service.rhels7.ppc64.otherpkgs.pkglist    xen.tmpl
compute.rhels6.tmpl            kvm.rhels6.pkglist                  service.rhels7.ppc64.pkglist              zfcp.rhel5.s390x.pkglist
compute.rhels6.x86_64.pkglist  kvm.rhels6.tmpl                     service.rhels7.tmpl                       zfcp.rhel5.s390x.tmpl
compute.rhels6.x86_64.tmpl     kvm.rhels7.pkglist                  service.rhels7.x86_64.otherpkgs.pkglist   zfcp.rhels6.s390x.pkglist
compute.rhels7.pkglist         kvm.rhels7.tmpl                     service.rhels7.x86_64.pkglist             zfcp.rhels6.s390x.tmpl
compute.rhels7.tmpl            kvm.tmpl                            service.rhels8.pkglist
compute.rhels8.pkglist         service.pkglist                     service.rhels8.ppc64le.otherpkgs.pkglist

[root@servicenew xcat]# cat /opt/xcat/share/xcat/install/rh/sysclone.rhels7.x86_64.otherpkgs.pkglist 
xcat/xcat-dep/rh7/x86_64/systemimager-client

On compute "Golden Node":

[root@cn34 ~]# yum list installed | grep systemimager-client
systemimager-client.noarch                4.3.0-0.1                    installed

Back to management node:

**[root@servicenew xcat]# imgcapture cn34 -t sysclone -o computeimage
Checking if systemimager packages are installed on servicenew.
Checking if systemimager packages are installed on cn34.
Error: [servicenew]: systemimager-client is not installed on the cn34.
Error: [servicenew]: Can not prepare Golden Client on cn34.**

Both nodes:

[root@cn34 ~]# uname -r
3.10.0-1127.el7.x86_64

[root@cn34 ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

**Comment by gurevichmark** [comment]
Can you run `imgcapture` with `-V` flag ?
It should display the error we get when checking if `systemimager-client` is installed on the compute node.

**Comment by alexnovik** [comment]
> Can you run `imgcapture` with `-V` flag ?
> It should display the error we get when checking if `systemimager-client` is installed on the compute node.

Thank you Mark! -V resolved the issue. It was bad path variable in .bashrc, which returned missing library on rpm -qa request from service node.

**Comment by alexnovik** [comment]
Now i get this:

[root@servicenew ~]# imgcapture cn34 -t sysclone -V -o computeimage
[servicenew]: Checking if systemimager packages are installed on servicenew.
[servicenew]: the output of rpm -qa|grep systemimager-server on servicenew is:
[servicenew]: systemimager-server-4.3.0-0.3.noarch
[servicenew]: Checking if systemimager packages are installed on cn34.
[servicenew]: the output of rpm -qa|grep systemimager-client on cn34 is:
[servicenew]: cn34: systemimager-client-4.3.0-0.1.noarch
[servicenew]: Preparing osimage computeimage on cn34.
[servicenew]: the output of export PERL5LIB=/usr/lib/perl5/site_perl/;LANG=C si_prepareclient --server servicenew --no-uyok --yes on cn34 is:
[servicenew]: cn34: Using "parted" to gather information about disk:
cn34:     /dev/sda
[servicenew]: cn34: Starting or re-starting rsync as a daemon.....
cn34: done!
[servicenew]: cn34: 
cn34: This client is ready to have its image retrieved.  You must now run 
cn34: the "si_getimage" command on your imageserver.
cn34: 
cn34: Automatically create configuration file for systemconfigurator:
cn34:   >> /etc/systemconfig/systemconfig.conf
[servicenew]: cn34: WARNING: unable to auto-detect kernel file!
cn34: WARNING: coulnd't create file /etc/systemconfig/systemconfig.conf (needed by systemconfigurator)
[servicenew]: Getting osimage "computeimage" from cn34 to servicenew.
[servicenew]: rsync: write failed on "/install/sysclone/images/computeimage/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/benchmarks/linpack/xlinpack_xeon64": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
rsync error: error in file IO (code 11) at io.c(1633) [sender=3.1.2]
si_getimage: Failed to retrieve image computeimage from cn34.
Error: [servicenew]: export PERL5LIB=/usr/lib/perl5/site_perl/;LANG=C si_getimage -golden-client cn34 -image computeimage -ip-assignment dhcp -post-install reboot -quiet -update-script YES failed on the servicenew.
Error: [servicenew]: Can not get image computeimage from cn34.
