### ISSUE TITLE
[Customer] updatenode failed against Ubuntu node

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#679]
A customer found the updatenode command failed to run against Ubuntu node, the root cause was the default /bin/sh links to the /bin/dash. xCAT updatenode framework script **xcatdsklspost** is running with **/bin/sh**, then for Ubuntu the **/bin/dash** will be used to run the script. But the script **xcatdsklspost** was designed to run with general shell or bash. 

xCAT has discussion before that all the postscript will only support bash. All the postscript is using **/bin/dash** as sha-bang. So my thought to fix this issue is to change the sha-bang for **xcatdsklspost** to **/bin/dash**. Customer has verified this fix and it worked. xCAT team needs to consider whether there's side-effect of this change.

**Comment by immarvin** [comment]
on ubuntu, "/bin/sh" is a symbol link to "/bin/bash" or "/bin/dash", so I think modify the she-bang to "/bin/bash" is ok. The autotest can cover it

**Comment by whowutwut** [comment]
@immarvin ...A little confused, above @daniceexi  mentions his thought to change the #!/bin/sh -> #!/bin/dash for xcatdkslspost..  but in the pull request, you are changing to #!/bin/bash. 

However, I think we should **not** use #!/bin/sh and use #!/bin/bash like you made... so @daniceexi why do you want to use #!/bin/dash?

**Comment by daniceexi** [comment]
@whowutwut my typo, should use bash in static for the xcatdskless.

**Comment by daniceexi** [comment]
I have verified this change, thanks.
