### ISSUE TITLE
[FVT]aix720 computernode not passwd set after provision

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#680]
Test OS: aix720
Test xCAT version:2.9.3
How to reproduce:
```
bash-3.2# lsdef c910f03c01p07
Object name: c910f03c01p07
    cons=hmc
    groups=lpar,all
    hcp=c910hmc02
    hidden=0
    hwtype=lpar
    id=7
    mac=ba60855b1803
    mgt=hmc
    nodetype=ppc,osi
    os=AIX
    parent=c910f03fsp01
    postscripts=syslog,remoteshell,syncfiles
    pprofile=c910f03c01p07
    profile=autotest
    provmethod=autotest
    status=booting
    statustime=01-28-2016 02:34:21
bash-3.2# 
 rnetboot c910f03c01p07
```
------------------>after provision no passwd set and not scripts run

**Comment by hu-weihua** [comment]
@junxiawang,  after debug in your environment, it seems CN didn't get any scripts from MN.  Got below error message  ::

    bash-3.2# lsnim -l c910f03c01p07
    c910f03c01p07:
    class          = machines
    type           = standalone
     ......
    Cstate_result  = success
    err_info       = mount: c910f03c01p20.pok.stglabs.ibm.com not in hosts database mount: giving up on: c910f03c01p20.pok.stglabs.ibm.com:/install/nim/lpp_source/autotest_lpp_source No route to host
    0042-175 c_installp: An unexpected result was returned by the "/usr/sbin/mount" command:
    mount: c910f03c01p20.pok.stglabs.ibm.com not in hosts database mount: giving up on: c910f03c01p20.pok.stglabs.ibm.com:/install/nim/lpp_source/autotest_lpp_source No route to host

But login your CN,  I found it can't resolve the hostname ``c910f03c01p20.pok.stglabs.ibm.com``.  In your MN, it's mess for resolving MN's hostname.  please keep consistent for naming resolving in your MN and try again.

**Comment by hu-weihua** [comment]
@junxiawang, it seems after keeping consistent for naming resolving in your MN, the installation has been successful.  

One more suggestion, depending on NIM manual, it doesn't recommend using a mix of long names and short names in NIM master. It will trigger unexpected problem. 

I will set this issue to ``pending``. thanks.
