### ISSUE TITLE
cannot run updatenode on a node

### ISSUE THREAD

**Issue by urielrosen** [xcat2/xcat-core#6802]
updatenode cn650  echo
Error: [xcat]: Could not find xcatmaster for cn650. Will skip this node.

Hi , 
this new node is in different vlan from xcat but there is an passwordless ssh connection to this node ,
how can I get this to work ?

Thanks .

**Comment by gurevichmark** [comment]
@urielrosen 
* Is `echo` a name of the postscript you are trying to run on the `cn650` node ?
* Can you run `xcatprobe xcatmn` on the xCAT management node

**Comment by urielrosen** [comment]
Hi ,

Echo is a test script ,  output xcatprobe xcatmn is below :




xcatprobe xcatmn
[mn]: Checking all xCAT daemons are running...                                                                    [ OK ]
[mn]: Checking xcatd can receive command request...                                                               [ OK ]
[mn]: Checking 'site' table is configured...                                                                      [ OK ]
[mn]: No interface provided by '-i' option, detected site table IP attribute 192.76.220.21, checking xCAT confi...[WARN]
[mn]: If this is incorrect, rerun with -i <ifname> option                                                         [WARN]
[mn]: Checking provision network is configured...                                                                 [ OK ]
[mn]: Checking 'passwd' table is configured...                                                                    [ OK ]
[mn]: Checking important directories(installdir,tftpdir) are configured...                                        [ OK ]
[mn]: Checking SELinux is disabled...                                                                             [ OK ]
[mn]: Checking HTTP service is configured...                                                                      [ OK ]
[mn]: Checking TFTP service is configured...                                                                      [WARN]
[mn]: TFTP service based on xCAT is not running
[mn]: Checking DNS service is configured...                                                                       [ OK ]
[mn]: Checking DHCP service is configured...                                                                      [FAIL]
[mn]: makedhcp xcatmntest failed
[mn]: Run 'makedhcp -n' if it has not been ran before.
[mn]: Checking NTP service is configured...                                                                       [FAIL]
[mn]: Unexpected ntpq output <localhost: timed out, nothing received>, please contact xCAT team
[mn]: Checking rsyslog service is configured...                                                                   [FAIL]
[mn]: rsyslog service is not running! Please check on current node
[mn]: Checking firewall is disabled...                                                                            [ OK ]
[mn]: Checking minimum disk space for xCAT ['/var' needs 1GB;'/install' needs 10GB;'/tmp' needs 1GB]...           [ OK ]
[mn]: Checking Linux ulimits configuration...                                                                     [ OK ]
[mn]: Checking network kernel parameter configuration...                                                          [ OK ]
[mn]: Checking xCAT daemon attributes configuration...                                                            [ OK ]
[mn]: Checking xCAT log is stored in /var/log/xcat/cluster.log...                                                 [ OK ]
[mn]: Checking xCAT management node IP: <192.76.220.21> is configured to static...                                [ OK ]
[mn]: Checking dhcpd.leases file is less than 100M...                                                             [ OK ]
=================================== SUMMARY ====================================
[MN]: Checking on MN...                                                                                           [FAIL]
    No interface provided by '-i' option, detected site table IP attribute 192.76.220.21, checking xCAT configu...[WARN]
    If this is incorrect, rerun with -i <ifname> option                                                           [WARN]
    Checking TFTP service is configured...                                                                        [WARN]
        TFTP service based on xCAT is not running
    Checking DHCP service is configured...                                                                        [FAIL]
        makedhcp xcatmntest failed
        Run 'makedhcp -n' if it has not been ran before.
    Checking NTP service is configured...                                                                         [FAIL]
        Unexpected ntpq output <localhost: timed out, nothing received>, please contact xCAT team
    Checking rsyslog service is configured...                                                                     [FAIL]
        rsyslog service is not running! Please check on current node
You have new mail in /var/spool/mail/root


Thanks,
Uriel.

**Comment by gurevichmark** [comment]
@urielrosen 
Can you also show the output of the following:
* `lsdef cn650`
* `tabdump site`
* `cat /etc/resolv.conf`
* `ip addr show <interface>` for the interface to `cn650` and for the interface to the ip of `master` attribute in `site` table

**Comment by bybai** [comment]
@urielrosen, I think you can add "chdef cn650 xcatmaster=<your xcat master ip>", after that, it should be work.

**Comment by urielrosen** [comment]
Thanks a lot ,

That worked.


Thanks,
Uriel.
