### ISSUE TITLE
xcat instalaltion on centos 7.7

### ISSUE THREAD

**Issue by jeyarajsiddhu** [xcat2/xcat-core#6808]
Hi Everyone,

I have installed a xcat cluster Master node on centos 7.7 . How can i install compute node through PXE boot network. 
Please help me..

Please find the attached Master node installed screenshots.
![1](https://user-images.githubusercontent.com/22903798/90724620-76adb700-e2dc-11ea-86c9-38e3070d6f3d.png)
![3](https://user-images.githubusercontent.com/22903798/90724622-78777a80-e2dc-11ea-9b92-e011b4fc05d2.png)

Regards,
Jeyaraj.M

**Comment by gurevichmark** [comment]
@jeyarajsiddhu 

If you are planning to install xCAT as a standalone product, you can check the Quick install guide here: https://xcat-docs.readthedocs.io/en/stable/guides/get-started/quick_start.html 
If you are planning to install xCAT as part of OpenHPC, there might be OpenHPC documentation out there.

Are you planning to manage Power or x86 compute nodes with xCAT ?
Are your compute nodes going to be bare metal or VMs ?

**Comment by jeyarajsiddhu** [comment]
Thank you for replying.. I'm planning to install compute node on VM's.

**Comment by gurevichmark** [comment]
If your compute nodes are going to be VMs and you already have VM hypervisor setup, you can follow instructions on how to setup, provision and manage VMs with xCAT: https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/manage_vms.html

**Comment by jeyarajsiddhu** [comment]
OK Sure.. I will try..
