### ISSUE TITLE
Unsupport Attribute Install

### ISSUE THREAD

**Issue by Jamchan1006** [xcat2/xcat-core#6814]
xCAT Version: 2.14.4
OS Version: CentOS 7.5
I want to install MLNX OFED into CentOS 7.5 netboot image, but show the error "Unsupport Attribute Install".
The command in the postscritps is "/install/postscripts/mlnxofed_ib_install -p /install/mlnx/MLNX_OFED_LINUX-4.4-1.0.0.0.-rhel7.5-x86_64.iso install -i $1 -n genimage"

**Comment by cxhong** [comment]
I think this is user error, the command doesn't include `install`  .   
the newest version of xCAT doc:  
```
/install/postscripts/mlnxofed_ib_install -p /install/<path-to>/<MLNX_OFED_LINUX.iso> \
    -m --without-32bit --without-fw-update --add-kernel-support --force -end-
```
