### ISSUE TITLE
Syncfiles not working during diskfull install

### ISSUE THREAD

**Issue by nealep** [xcat2/xcat-core#6832]
Howdy! We're having some trouble with file synchronization during a diskfull installation of CentOS 7.8. The server is running XCat version 2.16. When we run `rinstall node` the installation process runs to completion but after the reboot, the files aren't synced and we get the following in the /var/log/xcat/xcat.log file:

```
RCP=
'[' '!' -e /usr/bin/rsync ']'
logger -t xcat.deployment.postscript -p local4.info 'Performing syncfiles postscript'
uname
osname=Linux
xcatpostdir=/xcatpost
logger -t xcat.deployment.postscript -p local4.info 'syncfiles: the OS name = Linux'
quit=no
count=5
returncode=0
'[' no = no ']'
cat /etc/os-release
greip -i cumulus
'[' Linux = Linux ']'
/xcatpost/startsyncfiles.awk -v RCP=
returncode=1
```

Running `updatenode node -F` after the installation does distribute the files correctly though. 

The `syncfiles` file contains: 

```
/etc/hosts -> /etc/hosts
/etc/passwd -> /etc/passwd
```
I thought it might be related to https://github.com/xcat2/xcat-core/issues/5252 but `/var/xcat/syncfiles` and `/var/xcat/nodes/syncfiles` both exist on the master node and this setup is not hierarchical. Furthermore, the `synclists` value for the osimage is set to a correctly formatted file that exists. 

Any thoughts would be appreciated!

**Comment by nealep** [comment]
Looks like the root cause of the issue was that SSH was not starting due to permissions on private keys. That prevented rsync from doing its thing for whatever reason. Fixing those permissions appears to have fixed the problem.

**Comment by besawn** [comment]
@nealep Different versions of SSH appear to require different permissions for the private keys. We originally had to change from `0600` to `0640` due to this earlier issue: https://github.com/xcat2/xcat-core/issues/2617 

Which version of SSH did you have installed when you encountered this issue?
