### ISSUE TITLE
install of RHEL8.2.0 via install-compute is missing perl

### ISSUE THREAD

**Issue by dombrowa** [xcat2/xcat-core#6835]
rinstall of the default osimage rhels8.2.0-x86_64-install-compute results in errors shown in xcat.log because perl is not installed anymore in the package list

post.xcat is using this code w/o checking if perl executable is available:
```
RAND=$(perl -e 'print int(rand(50)). "\n"')
if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
   msgutil_r "$MASTER_IP" "debug" "sleep $RAND" "/var/log/xcat/xcat.log" "$log_label"
fi
sleep $RAND
```
xcat version
```
Version 2.16 (git commit 7fc773bd8e82ff9270bd7832558422dd17e23e66, built Tue Jun 16 16:07:25 EDT 2020)
```

suggested fix is either to add perl to the installation or edit post.xcat*
```
if which perl 1>/dev/null 2>&1; then
 RAND="$(perl -e 'print int(rand(50)). "\n"')"
else
  msgutil_r "$MASTER_IP" "warn" "perl not found or installed "/var/log/xcat/xcat.log" "$log_label"
 ((RAND=RANDOM % 50 +1))
fi
```

**Comment by cxhong** [comment]
Thanks, @dombrowa .

checking the package list,  I don't think xcat ever add `perl` to `packagelist`.  The error message maybe always there, just ignored.  anyway, here is the output of `perl` command results.
```
Fri Sep 25 10:30:27 EDT 2020 [info]: xcat.deployment: Executing post.xcat to prepare for firstbooting ...
++ perl -e 'print int(rand(50)). "\n"'
+ RAND=4
+ case "$XCATDEBUGMODE" in
+ msgutil_r 10.4.40.1 debug 'sleep 4' /var/log/xcat/xcat.log xcat.deployment
+ local logserver=10.4.40.1
+ local msgtype=debug
+ local 'msgstr=sleep 4'
+ local logfile=/var/log/xcat/xcat.log
+ local logtag=xcat.deployment
+ '[' -z debug ']'
+ '[' -z xcat.deployment ']'
+ '[' -n 10.4.40.1 ']'
+ logger -n 10.4.40.1 -t xcat.deployment -p local4.debug 'sleep 4'
```

**Comment by dombrowa** [comment]
During provisioning  of vanilla rhels8*-install-compute the postscript post.xcat.ng emits (ran with set -x)
```
+ echo 'Fri Sep 25 12:40:59 EDT 2020 [info]: xcat.deployment: Executing post.xcat to prepare for firstbooting ...'
Fri Sep 25 12:40:59 EDT 2020 [info]: xcat.deployment: Executing post.xcat to prepare for firstbooting ...
++ perl -e 'print int(rand(50)). "\n"'
/tmp/ks-script-sh8_6vy3: line 140: perl: command not found
+ RAND=
```
I think this has never been a problem prior to RHE distros prior to RHEL8. Its install image contains perl only in the pre section 
```
[anaconda root@netsres46 ~]# which perl
/bin/perl
```
But there is no perl during the post section under chroot
```
anaconda root@netsres46 ~]# chroot /mnt/sysimage/
[anaconda root@netsres46 /]# which perl
/usr/bin/which: no perl in (/bin:/sbin:/usr/bin:/usr/sbin:/mnt/sysimage/sbin:/mnt/sysimage/usr/sbin:/mnt/sysimage/bin:/mnt/sysimage/usr/bin)
```
and xCAT uses perl in the post section without checking if the command exists
Previous versions of RedHat OS must have had had perl available when anaconda runs its post tasks.

Btw: The default pkglist on RHEL8 shows no perl
```
[dombrowa@dccxcat2]$ cat /opt/xcat/share/xcat/install/rh/compute.rhels8.pkglist
@^minimal-environment
chrony
net-tools
nfs-utils
openssh-server
rsync
util-linux
wget
python3
tar
bzip2
```

**Comment by cxhong** [comment]
The previous OS didn't include `perl` package in the default package list.  It must picked up from other packages.
Anyway, I have no problem to add `perl` to rhel8 package list  and will open a PR for this. 
 I think it's good to make `perl` command available on compute nodes.
