### ISSUE TITLE
Provisioning RHEL8.2 on x86_64 fails after downloading initrd.img

### ISSUE THREAD

**Issue by rer-ccc** [xcat2/xcat-core#6839]
xCAT 2.16.0 running on RHEL7.6 x86_64
Attempting to install rhels8.2.0 on x86_64
After rinstall and DHCP Offer and Request, it gets:

```
[cctxc007] 14:53:14 Via HTTP get /tftpboot/xcat/xnba/nodes/cctxc007.uefi
[cctxc007] 14:53:14 Via HTTP get /tftpboot/xcat/elilo-x64.efi
[cctxc007] 14:53:14 Via HTTP get /tftpboot/xcat/xnba/nodes/cctxc007.elilo
[cctxc007] 14:53:14 Via HTTP get /tftpboot/xcat/osimage/rhels8.2.0-x86_64-install-compute-cct/vmlinuz
[cctxc007] 14:53:14 Via HTTP get /tftpboot/xcat/osimage/rhels8.2.0-x86_64-install-compute-cct/initrd.img
```

... and then it reboots. No other messages.

osimage has:
rhels8.2.0-x86_64-install-compute-cct:
    objtype=osimage
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels8.2.0-x86_64
    osname=Linux
    osvers=rhels8.2.0
    otherpkgdir=/install/post/otherpkgs/rhels8.2.0-cct/x86_64
    otherpkglist=/install/custom/install/rh/rhels8.2.0-cct/x86_64/otherpkgs.pkglist
    pkgdir=/install/rhels8.2.0/x86_64
    pkglist=/install/custom/install/rh/compute.rhels8.2.0.x86_64_cct.pkglist
    profile=compute
    provmethod=install
    synclists=/install/custom/install/rh/rhels8.2.0-cct/x86_64/syncfiles.Allnodes8
    template=/install/custom/install/rh/compute.rhels8-cct.tmpl

I have another configuration that is effectively identical, for rhels8.1.0, and that works ok.

xcatdebug=2  doesn't give me any useful info.

**Comment by cxhong** [comment]
can u install this rpm on the MN then rerun again ?  `https://xcat.org/files/xcat/repos/yum/devel/xcat-dep/elilo-xcat-3.14-5.noarch.rpm`

If above didn't work,  can u able to upgrade `xcatd` to development build,  there was `PR` https://github.com/xcat2/xcat-core/pull/6772 to skip elilo and use iPXE boot.

**Comment by cxhong** [comment]
Well, if `initrd.img` downloaded,  maybe not elilo issue.  
worth to check if `pkgdir=/install/rhels8.2.0/x86_64` is correct path   and make sure all the packages defined in the `compute.rhels8.2.0.x86_64_cct.pkglist` can be installed from `pkgdir`

**Comment by rer-ccc** [comment]
The new elilo-xcat-3.14-5.noarch.rpm fixed it.  Thanks!

**Comment by besawn** [comment]
I'm glad the new package resolved your problem, closing.
