### ISSUE TITLE
XCAT requires cpio, but go-xcat doesn't install it

### ISSUE THREAD

**Issue by MrBr-github** [xcat2/xcat-core#6844]
There are 2 issues:
1. cpio is required, but not installed with other dependencies
2. cpio absence silently ignored, in [debian.pm](https://github.com/xcat2/xcat-core/blob/1532e476ea38d1fa1679e2f65827cb42d1810290/xCAT-server/lib/xcat/plugins/debian.pm)

**Scenario**:
ubuntu docker started via `docker run --privileged -it docker_name /bin/bash`

Running copycds fails
```
root@528d5c46acf2:/#  copycds ubuntu-18.04.4-server-amd64.iso
Copying media to /install/ubuntu18.04.4/x86_64
Error: [528d5c46acf2]: Media copy operation failed, status -1
```
After cpio installation ` apt-get install cpio`
```
root@528d5c46acf2:/#  copycds ubuntu-18.04.4-server-amd64.iso
Copying media to /install/ubuntu18.04.4/x86_64
Media copy operation successful
```

**Comment by besawn** [comment]
This issue was resolved via https://github.com/xcat2/xcat-core/pull/6857. The fix is available in the current development builds and will be included in the next xCAT release (2.16.1).
