### ISSUE TITLE
Does xCAT support SLES 15 SP2?

### ISSUE THREAD

**Issue by jonathanmills** [xcat2/xcat-core#6856]
I'm running the latest xcat 2.16.  But I've had all manner of problems working with SLES 15 SP2 (which is also the OS I'm running xCAT on).  Happy to share the gory details, but figured I'd just start with this simple question.

Thank you,

Jonathan Mills

**Comment by cxhong** [comment]
we are supporting SLES15, this is latest one we verified.    Feel free to open pull request and make necessary changes.  We are appreciated if you are willing to contribute xCAT project.
