### ISSUE TITLE
Unable to boot x86_64 KVM VMs off xNBA

### ISSUE THREAD

**Issue by ceckhoff** [xcat2/xcat-core#6859]
Environment: 2 x86_64 Test clusters
One Running CentOS 8.2 other cluster running CentOS 7.8 attempting to provision VM the systems go through normal pxe with xNBA netboot but get to the point to download vmlinuz or kernel get to ~50-55% of downloading and hangs hard.  VM will reboot several times and get to around the same point and fail over and over.

Tried several option including attempting to get the VM to boot in uEFI mode by passing boot:uefi to vm.othersettings and VM would never boot to uefi mode.

Found workaround but breaks bare metal provisioning of the VM hosts.
Replacing xnba with ipxe in dhcp.pm will allow for the provisioning of the VMs but breaks baremetal installs.
[dhcp_pm.zip](https://github.com/xcat2/xcat-core/files/5378908/dhcp_pm.zip)

xCAT Version:
Version 2.16.0.lenovo1 (git commit 06d7097f42eca03db70c9eb93b8abeaf8ca1c2be, built Wed Sep 23 12:29:22 UTC 2020)

VM Stanza:
vm14:
    objtype=node
    arch=x86_64
    consoleenabled=1
    currchain=boot
    currstate=boot
    groups=vm,kvm
    ip=192.168.1.144
    mac=42:a1:c0:a8:01:90
    mgt=kvm
    nameservers=xcat-hs
    netboot=xnba
    nfsdir=/install
    nfsserver=xcat-hs
    os=centos8.2
    postscripts=vmserver/disableCentos
    profile=compute
    provmethod=centos8.2-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=booted
    statustime=10-13-2020 12:50:24
    tftpserver=xcat-hs
    updatestatus=failed
    updatestatustime=10-14-2020 09:56:41
    vmcpus=8
    vmhost=compute4
    vmmemory=32768
    vmnicnicmodel=virtio
    vmnics=br0
    vmstorage=dir:///vms/
    xcatmaster=xcat-hs

**Comment by cxhong** [comment]
are you using lenovo version of xcatd?   `Version 2.16.0.lenovo1 `

can u check if `xnba.pm` has updates from this PR:  https://github.com/xcat2/xcat-core/pull/6772/files

if not,  worth to try to download https://xcat.org/files/xcat/repos/yum/devel/xcat-dep/elilo-xcat-3.14-5.noarch.rpm   and rerun it again.

**Comment by ceckhoff** [comment]
Yes we have the pre-req installed and currently at 3.16.1 on elilo-xcat

Listing of xcat rpm installed on one of the test clusters:
elilo-xcat-3.16-1.noarch
xCAT-client-2.16.0.lenovo1-1.noarch
syslinux-xcat-3.86-2.noarch
xCAT-genesis-scripts-x86_64-2.16.0.lenovo1-1.noarch
ipmitool-xcat-1.8.18-0.x86_64
xCAT-genesis-base-x86_64-2.16.0.lenovo2-1.noarch
xCAT-confluent-2.13.8-snap201711020715.noarch
perl-xCAT-2.16.0.lenovo1-1.noarch
xCAT-probe-2.16.0.lenovo1-1.noarch
conserver-xcat-8.2.1-1.x86_64
xCAT-server-2.16.0.lenovo1-1.noarch
xCAT-2.16.0.lenovo1-1.x86_64
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch

Chris

**Comment by cxhong** [comment]
@ceckhoff ,  If you use lenovo branch, you may need to ask them.  I am not sure what's in the `elilo-xcat-3.16-1.noarch`,  and what's different between their branch and ours.
