### ISSUE TITLE
makegocons --cleanup ignore all hosts

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6870]
Hi!

I tried to run `makegocons -C` on the MN in a hierarchical system, but got the following error for all the nodes defined in xCAT:
```
<node>: ignore, the host for conserver could not be determined.
```

All the nodes have a valid conserver definition:
```
# lsdef sh03-01n01 -i conserver
Object name: sh03-01n01
    conserver=sh03-sn02
```
yet:
```
# makegocons -C | grep sh03-01n01
sh03-01n01: ignore, the host for conserver could not be determined.
sh03-01n01: ignore, the host for conserver could not be determined.
```
(yes, it's also displayed twice).

Any idea what the problem may be?

Thanks!

**Comment by cxhong** [comment]
I changed to use group
```
[root@c910f03c09k18 xCAT]# tabdump nodehm
#node,power,mgt,cons,termserver,termport,conserver,serialport,serialspeed,serialflow,getmac,cmdmapping,consoleondemand,consoleenabled,comments,disable
"c910f03c09k19",,"kvm","kvm",,,,"0","115200","hard",,,,"1",,
"c910f03c09k20",,"kvm","kvm",,,,"0","115200","hard",,,,"1",,
"compute",,,,,,"c910f03c09k19",,,,,,,,,
[root@c910f03c09k18 xCAT]# makegocons -C
c910f03c09k19: ignore, the host  for conserver could not be determined.
```

**Comment by kcgthb** [comment]
Yes, that's the same here:
```
# lsdef sh03-01n01 -i conserver
Object name: sh03-01n01
    conserver=sh03-sn02
```
I also tried to set conserver directly in the node's definition in `nodehm`, but that doesn't change the issue. I also tried to change the conserver name, or use an IP address, but still the same issue. If anything, it makes the error appears a 3rd time in the the `makegocons -C` output:
```
# # chdef sh03-01n01 conserver=10.19.0.11
1 object definitions have been created or modified.

# makegocons -C | grep sh03-01n01
sh03-01n01: ignore, the host for conserver could not be determined.
sh03-01n01: ignore, the host for conserver could not be determined.
sh03-01n01: ignore, the host for conserver could not be determined.
```

**Comment by cxhong** [comment]
show up 3 times now?  how many nodes in your cluster?  I may need to add debug code to there and check out.  
on my cluster,  it seems the message showed up only when node is SN.

**Comment by kcgthb** [comment]
I got that message roughly twice per node, for every single node in the cluster

```
# nodels | wc -l
1734

# makegocons -C | grep -c "conserver could not be determined"
3308
```

**Comment by cxhong** [comment]
how many service node in the cluster?
`makegocons -C` will get attributes for all the nodes,  since both MN and SN are running goconserver,  
`makegocons -C` will return message from MN and SN
```
 [root@c910f03c09k18 xCAT]# makegocons -C
get all node attributes
c910f03c09k19: has conserver , isSN=0
c910f03c09k20: has conserver c910f03c09k19, isSN=0
get all node attributes
c910f03c09k19: has conserver , isSN=1
c910f03c09k19: ignore, isSN=1, the host  for conserver could not be determined.
c910f03c09k20: has conserver c910f03c09k19, isSN=1
```

on your system, the message `sh03-01n01: ignore, the host for conserver could not be determined.` maybe come from other SN.

**Comment by kcgthb** [comment]
There are 12 service nodes in the cluster:
```
# nodels service | wc -l
12
```
The conserver defined for most of the compute nodes is a service node different from the MN, so I guess having the message twice per compute node makes sense, then.

Having additional debug info would be helpful indeed!
