### ISSUE TITLE
line 840: /usr/bin/logger: Argument list too long

### ISSUE THREAD

**Issue by ChrisPJames** [xcat2/xcat-core#6877]
Noticed this in xcat.log after install of centos7.6 using xcat 2.16.1:

Cleaning repos: xCAT-centos7.6-path0 xCAT-centos7.6-path1 xcat-otherpkgs0
./otherpkgs: line 840: /usr/bin/logger: Argument list too long
Fri Nov 13 16:42:21 UTC 2020 [info]: xcat.deployment.postscript: postscript end...: otherpkgs return with 0

**Comment by cxhong** [comment]
The default for logger size is 1KiB characters.  In this case, output of `yum upgrade`  may exceed this limit.  
```
835         result=`eval $envlist yum -y upgrade 2>&1`
    836         R=$?
    837         if [ $R -ne 0 ]; then
    838               RETURNVAL=$R
    839         fi
    840         logger -p local4.info -t $log_label "$result"
```

**Comment by ChrisPJames** [comment]
Roger that - thanks for getting back.

Cheers
Chris

Chris James
________________________________
