### ISSUE TITLE
dhcp does not have anything in /var/lib/dhcpd/dhcpd.leases

### ISSUE THREAD

**Issue by cjcawley** [xcat2/xcat-core#6878]
Greetings and I hope that you are all well.

I am looking into a statefull build and the domain name
has been changed.  The static lease files are not getting
generated at all.

mkdef -f -t node hop073 groups=compute,all \
ip=172.16.0.0 mac=0C:42:A1:00:00:00 \
netboot=xnba arch=x86_64
###wwsh -y node set hop073 --netdev=ib0 --ipaddr=172.16.0.0 --netmask=255.255.240.0

chtab key=system passwd.username=root passwd.password="<NOTHINGHERE>"
chdef -t site domain="xcat.local"
chdef compute -p postbootscripts=confignics

makehosts
makenetworks
makedhcp -n
makedns -n

Any thoughts are appreciated.

Thanks
Chris

PS I blanked out the password and ip

**Comment by cxhong** [comment]
try `makedhcp -a`,  this is the command to add the node's mac address to the lease file.

**Comment by vandah** [comment]
We have the same issue and the `makedhcp -a` doesn't generate the leases. Also, sometimes the `omshell` which the `makedhcp` command is using starts running and just runs for a really long time (got to 3 hours before we killed it). The `omshell` is also consuming 100% of one CPU so it's not waiting for anything. After running the `makedhcp -n`, `makedhcp -a` sequence a lot of times, it sometimes does generate the leases.

**Comment by gurevichmark** [comment]
What version xCAT ?
What is the OS of xCAT MN ?

**Comment by vandah** [comment]
xcat 2.16
ubuntu 20.04

**Comment by besawn** [comment]
@vandah Currently Ubuntu 18.04.2 is the newest Ubuntu release supported by xCAT. If you or anyone else in the xCAT community debugs this issue related to makedhcp on Ubuntu 20.04, please update this issue with your findings to benefit anyone else experiencing similar problems.

**Comment by besawn** [comment]
@cjcawley Are you also running Ubuntu 20.04?

**Comment by cjcawley** [comment]
No and we ended up going with warewulf stateless w/local mounts

Chris

Christopher J. Cawley

Systems Engineer/Linux Engineer, Information Technology Services

223 Aquia Building, Ffx, MSN: 1B5

George Mason University


Phone: (703) 993-6397

Email: ccawley2@gmu.edu

​

________________________________

**Comment by vandah** [comment]
It really seems to be an issue with ubuntu 20.04. It works with 18.04.

**Comment by besawn** [comment]
I am going to close this issue as the original author has opted to use warewulf rather than xCAT and it is not clear to me if the issue described by @cjcawley and @vandah are related.

@vandah As noted above, Ubuntu 20.04 is not currently supported by xCAT. Feel free to open a new issue specific to the problem you are experiencing on Ubuntu 20.04 if you would like so we can collect information specific to that problem in a fresh issue.

**Comment by dombrowa** [comment]
Suggestions:
Check connections to port 7911 where dhcp server runs
Try to find out (e.g. tcpdump) if the xml requests are sent via omshell to the Ubuntu isc-dhcp-server

I noticed that the xCAT function **send_request** in /opt/xcat/lib/perl/xCAT/Client.pm returns zero even if nothing was actually sent successfully to the omapi interface on port 7911.
Maybe some error checking after
```
       print $sock $msg;
        $sock->flush();
```
would help.
