### ISSUE TITLE
initrd and kcmdline not generate

### ISSUE THREAD

**Issue by iamdhakrey** [xcat2/xcat-core#6879]
i use following command to add compute node 

> mkdef -t node compute groups=all bmc="172.16.16.12" cons=ipmi mgt=ipmi mtm="" serial="" ip="10.10.10.2"
chdef compute chain="runcmd=bmcsetup"
chdef compute bmc="172.16.16.21"
lsdef compute
makehosts
makedns -n
makedhcp -n
makedhcp -a
chdef compute netboot=pxe installnic=mac primarynic=mac mac="mac address"
rspconfig compute alert=on
nodeadd compute groups=all,compute
copycds /opt/iso/Centos8.0.iso -n centos8
lsdef -t osimage
chdef -t osimage centos8-x86_64-install-compute partitionfile=/install/custom/partition
chdef -t osimage centos8-x86_64-install-compute partitionfile=/install/custom/partition imagetype=linux
chdef -t osimage centos8-x86_64-netboot-compute partitionfile=/install/custom/partition imagetype=linux provmethod=netboot
chdef -t osimage centos8-x86_64-install-compute pkglist=/install/custom/compute_centos8.pkglist
chdef -t osimage centos8-x86_64-netboot-compute pkglist=/install/custom/compute_centos8.pkglist
nodeset compute osimage=centos8-x86_64-netboot-compute

when i use ```lsdef compute```  and ```lsdef -t osimage centos8-x86_64-install-compute``` it  shows

> [root@master]# lsdef compute
Object name: compute
    arch=x86_64
    bmc=172.16.16.21
    chain=runcmd=bmcsetup
    cons=ipmi
    currchain=boot
    currstate=install centos8-x86_64-compute
    groups=all,compute
    installnic=mac
    ip=10.10.10.2
    mac=mac address
    mgt=ipmi
    mtm=
    netboot=pxe
    os=centos8
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    primarynic=mac
    profile=compute
    provmethod=centos8-x86_64-install-compute
    serial=serial number
    status=powering-on

> [root@master]# lsdef -t osimage centos8-x86_64-install-compute
Object name: centos8-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos8-x86_64
    osname=Linux
    osvers=centos8
    otherpkgdir=/install/post/otherpkgs/centos8/x86_64
    partitionfile=/install/custom/partition/partition
    pkgdir=/install/centos8/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.centos8.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.centos8.tmpl

**Comment by cxhong** [comment]
The `initrd`  and `kcmdline` should be in the `/tftpboot/xcat` dir.  
Those two attributes are no longer defined on the node definition.

**Comment by iamdhakrey** [comment]
thanks brother
