### ISSUE TITLE
Need to Stop SSL/TLS Server supports TLSv1.0 for XCAT 

### ISSUE THREAD

**Issue by nikatgithub** [xcat2/xcat-core#6881]
Hi, 

We are using XCAT on one of our server and we need to block TLS version 1 for it and enable TLS V2.

As per this link we can do this by changing some parameters https://xcat-docs.readthedocs.io/en/stable/advanced/security/ssl_config.html which I have also done.

(0)[root]# tabdump site
#key,value,comments,disable
"xcatsslversion","TLSv1_2",,
"xcatsslciphers","kDH:kEDH:kRSA:!TLSv1:!SSLv3:!SSLv2:!aNULL:!eNULL:!MEDIUM:!LOW:!MD5:!?????EXPORT:!CAMELLIA:!ECDH",,
(0)[root~]#

Restarted the service but still it is supporting TLSv_1. Any suggestion??

SSL-Session:
    Protocol  : TLSv1

**Comment by besawn** [comment]
There is a minor typo in the ssl_config documentation related to the syntax of the service xcatd restart.
Did you restart the xcatd service on the management node with:
```
# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]
```

In the SSL-Session output above, do you see a message like this:
```
140735501601696:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1493:SSL alert number 70
140735501601696:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:659:
```
If you see that message and the connection is closed immediately, you have successfully disabled TLSv1, even though this still appears in the s_client output:
```
SSL-Session:
Protocol : TLSv1
```

Here is an example, can you confirm this example works on your management node:
```
[root@mn ~]# tabdump site | grep ssl
"xcatsslversion","TLSv1_2",,

[root@mn ~]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]

# Try to connect using TLS1_1
# Error message is printed, connection is closed immediately by the server side
[root@mn ~]# openssl s_client -connect 127.0.0.1:3001 -tls1_1
CONNECTED(00000003)
140735501601696:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1493:SSL alert number 70
140735501601696:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:659:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1607435625
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
[root@mn ~]#

# Try to connect without specifying explicit TLS version
# Protocol is set to TLSv1.2 
# Connection stays open until user types control-C or timeout occurs
# Output edited for clarity
[root@mn ~]# openssl s_client -connect 127.0.0.1:3001
CONNECTED(00000003)

...

SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384

...
---
closed
[root@mn ~]# 
```

**Comment by nikatgithub** [comment]
Hi Beswan,

Thanks for your response.

Yes. I did try to restart the service in the same way:

(0)[root ~]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]
(0)[root ~]#

No errors:

(0)[root ~]# openssl s_client -connect 127.0.0.1:3001 -tls1
CONNECTED(00000003)
depth=1 CN = xCAT CA
verify error:num=19:self signed certificate in certificate chain
---
---
---
SSL handshake has read 1951 bytes and written 519 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA

Connection does not close immediately and there is no error when I run openssl with tls1 or tls1_1

 (0)[root~]# tabdump site | grep ssl
"xcatsslversion","TLSv1_2",,
"xcatsslciphers","kDH:kEDH:kRSA:!TLSv1:!SSLv3:!SSLv2:!aNULL:!eNULL:!MEDIUM:!LOW:!MD5:!?????EXPORT:!CAMELLIA:!ECDH",,

Is there anything else. I can try?

**Comment by besawn** [comment]
What version of xcat do you have installed?
`lsxcatd -v`

What operating system is this?

What openssl version?

**Comment by nikatgithub** [comment]
Hi Besawn,

Here are the details:

(0)[root~]# lsxcatd -v
Version 2.7.3 (svn r13117, built Mon Jun 18 05:12:28 EDT 2012)
(0)[root ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
(0)[root ~]# uname -an
Linux ***** 3.10.0-1160.6.1.el7.ppc64le #1 SMP Wed Oct 21 17:49:47 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux

openssl-1.0.2k-19.el7.ppc64le

**Comment by besawn** [comment]
That is a very old version of xCAT that does not support the "xcatsslversion" option in the site table.

Is this an existing cluster or a new installation?

If this is a new installation, I would suggest starting over and installing the latest version of xCAT, 2.16.1.

If this is an existing cluster that is in production, you have the option of either upgrading xCAT to a newer version or possibly patching your existing installation as a workaround.

**Comment by nikatgithub** [comment]
Yes. This is an old cluster. We patch this server every quarter. This server was OS patched in November. So, only solution to this issue to is to upgrade the XCAT.

Is there any link you can share to upgrade the XCAT?

**Comment by besawn** [comment]
If xcat hasn't been upgraded on this cluster since 2012, it may be easier to patch your existing xcat rather than upgrade.
If you want to try to patch xcatd to force TLSv1_2, you can add a single line to /opt/xcat/sbin/xcatd:
```
                SSL_version     => "TLSv1_2",
```

Note: you can select any SSL_version string using this same method, if you want something other then TLSv1_2.

Relevant section before the change:
```
            $connection = IO::Socket::SSL->start_SSL($cnnection,
                SSL_key_file    => $xcatdir . "/cert/server-cred.pem",
                SSL_cert_file   => $xcatdir . "/cert/server-cred.pem",
                SSL_ca_file     => $xcatdir . "/cert/ca.pem",
                SSL_server      => 1,
                SSL_verify_mode => 1,
            );
```
after the change:
```
            $connection = IO::Socket::SSL->start_SSL($cnnection,
                SSL_key_file    => $xcatdir . "/cert/server-cred.pem",
                SSL_cert_file   => $xcatdir . "/cert/server-cred.pem",
                SSL_ca_file     => $xcatdir . "/cert/ca.pem",
                SSL_server      => 1,
                SSL_verify_mode => 1,
                SSL_version     => "TLSv1_2",
            );
```

Example of the patching process:
```
# Save the current file
[root@mn ~]# cp /opt/xcat/sbin/xcatd /opt/xcat/sbin/xcatd.orig

# Edit the xcatd file:
[root@mn ~]# vi /opt/xcat/sbin/xcatd

[root@mn ~]# diff /opt/xcat/sbin/xcatd /opt/xcat/sbin/xcatd.orig
1573d1572
<                 SSL_version     => "TLSv1_2",

[root@mn ~]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]

# Confirm TLSv1 is rejected
[root@mn ~]# openssl s_client -connect 127.0.0.1:3001 -tls1
CONNECTED(00000003)
140735400545184:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1493:SSL alert number 70
140735400545184:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:659:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1607454502
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

# Verify normal behavior 
[root@mn ~]# openssl s_client -connect 127.0.0.1:3001
...
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
...
```

If you need to undo the patch:
```
[root@mn ~]# cp /opt/xcat/sbin/xcatd.orig /opt/xcat/sbin/xcatd

[root@mn ~]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]

```

**Comment by nikatgithub** [comment]
Thanks. I did try this as well.

(0)[root~]# diff /opt/xcat/sbin/xcatd /opt/xcat/sbin/xcatd.orig
892d891
<       SSL_version=> "TLSv1_2",

Restarted the service but still TLSv1 and TLSv1_1 is supporting !!

(0)[root ~]# openssl s_client -connect 127.0.0.1:3001 -tls1
CONNECTED(00000003)
depth=1 CN = xCAT CA
verify error:num=19:self signed certificate in certificate chain
---
Certificate chain

---
Server certificate
-----BEGIN CERTIFICATE-----
---
---

New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    
---
closed

**Comment by besawn** [comment]
With the patch applied, does the connection close immediately when you run:
```
openssl s_client -connect 127.0.0.1:3001 -tls1
```
does the connection stay open longer or is the output different when you run:
```
openssl s_client -connect 127.0.0.1:3001
```

The output could be different when disabling with the simple patch above.
If the connection closes immediately, I think you have successfully disabled TLSv1. 
If the connection stays open for the same amount of time and the output is similar for the two tests above, then it is most likely still enabled.

**Comment by nikatgithub** [comment]
Yes. The output is same like we were getting before applying the change. There is no different in output.

No error it is exactly the same. So, it is still enabled.
