### ISSUE TITLE
Passing QEMU commandline to KVM plugin

### ISSUE THREAD

**Issue by dajiji** [xcat2/xcat-core#6885]
Dear xCAT developer,
Is there a method to pass QEMU commandline to xCAT provisioned KVM VM?

I'd like to pass the following parameters when provisioning KVM, but not sure what vm.othersettings shall I use to do so..
- kvm=off,hv_vendor_id=null
- machine q35,kernel_irqchip=on
- os-variant=rhel8.3

The virt-install parameters for such request is as follows:
```
virt-install \
--qemu-commandline="-cpu kvm=off,hv_vendor_id=null -machine q35,kernel_irqchip=on" \
--os-variant=rhel8.3
```

**Comment by gurevichmark** [comment]
@dajiji Did you have a chance to read description of `othersettings` under https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/vm.5.html ? There might be some additional parameters you could pass.

**Comment by dajiji** [comment]
Thank you very much! @gurevichmark
