### ISSUE TITLE
Management node is not passing the packages through PXE to ubuntu

### ISSUE THREAD

**Issue by mherreral** [xcat2/xcat-core#6886]
I've been having some troubles trying to boot a node with an ubuntu iso. I found an iso which can be booted through PXE, the management node gives it the identity, but when the node tries to download the packages it fails, apparently, the node can't access to the "mirror" which is the mn.

- Ubuntu info: ubuntu16.04.7
- xCAT info: Version 2.16
- management node OS: Centos 8.2
- Osimage information:
Object name: ubuntu16.04.7-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osname=Linux
    osvers=ubuntu16.04.7
    otherpkgdir=/install/post/otherpkgs/ubuntu16.04.7/x86_64
    pkgdir=/install/ubuntu16.04.7/x86_64
    pkglist=/opt/xcat/share/xcat/install/ubuntu/compute.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/ubuntu/compute.tmpl

Notice that it is diskful installation

**Comment by cxhong** [comment]
For the Ubuntu installation without access to internet. you may need to create local mirror.

https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/ubuntu_os_other_pkg.html?highlight=local%20mirror#compute-nodes-can-not-access-the-internet

**Comment by gurevichmark** [comment]
@mherreral Is this still an issue ?
