### ISSUE TITLE
node status failed xcat 2.16 deployment

### ISSUE THREAD

**Issue by marseaplage** [xcat2/xcat-core#6893]
Hello guys.

I would like you to help me because I got this error: 

Wed Feb  3 14:16:06 EST 2021 [info]: xcat.deployment.postbootscript: postbootscript confignetwork return with 0
Wed Feb  3 14:16:06 EST 2021 [debug]: xcat.deployment.postbootscript: node boot failed, reporting status...
Wed Feb  3 14:16:06 EST 2021 [error]: xcat.deployment.postbootscript: provision completed with error.(nodename)

But it is no clear why it fails and when I run:

 xcatprobe osdeploy -n quinde-2-8

I got this message:

The install NIC in current server is eno2                                                                         [INFO]
All nodes to be deployed are valid                                                                                [ OK ]
-------------------------------------------------------------
Start capturing every message during OS provision process....
-------------------------------------------------------------

60 minutes have expired, stop monitoring                                                                          [INFO]
======================  Summary  =====================
There is 1 node provision failures
nodename : stop at stage ''                                            

The node was successfully installed but when I check the status I got it as failed but I do not why. I have already try the postbootscripts:

updatenode nodename  -P "otherpkgs"
updatenode nodename -P "confignetwork"

But I couldn't find any error.

**Comment by gurevichmark** [comment]
@marseaplage Are you doing diskless or diskfull deployment ?
Which OS are you installing ?

**Comment by marseaplage** [comment]
> @marseaplage Are you doing diskless or diskfull deployment ?
> Which OS are you installing ?

Hello @gurevichmark 

It is a diskfull deployment with Centos 8.2 as it is explained in the openhpc v2.0 guide. But I am reading the xcat guide too.
Thank you in advance for any suggestion.

**Comment by gurevichmark** [comment]
@marseaplage Have you checked the `/var/log/xcat/xcat.log` on the compute node ?

**Comment by marseaplage** [comment]
> @marseaplage Have you checked the `/var/log/xcat/xcat.log` on the compute node ?

Yes I check it out and it is the result:

Wed Feb 3 14:16:06 EST 2021 [info]: xcat.deployment.postbootscript: postbootscript confignetwork return with 0
Wed Feb 3 14:16:06 EST 2021 [debug]: xcat.deployment.postbootscript: node boot failed, reporting status...
Wed Feb 3 14:16:06 EST 2021 [error]: xcat.deployment.postbootscript: provision completed with error.(nodename)

**Comment by marseaplage** [comment]
@gurevichmark in addition to that I disvored this error in this log /var/log/xcat/cluster.log in the management node:

# egrep error /var/log/xcat/cluster.log
Feb  1 16:36:36 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  1 18:19:38 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  2 11:38:51 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  2 12:02:34 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  2 19:11:23 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  3 12:47:22 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E '<error>' /tmp/ssh_dsa_hostkey
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|/{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E '<error>' /tmp/ssh_rsa_hostkey
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|/{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E '<error>' /tmp/ssh_ecdsa_hostkey
Feb  3 13:31:54 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|/{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:31:55 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E '<error>' /tmp/ssh_root_pub_key
Feb  3 13:31:55 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|</{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:31:55 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|</{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:31:55 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E '<error>' /tmp/ssh_root_key
Feb  3 13:31:55 <nodename> xcat.updatenode.postscript[21426 DEBUG  + grep -E -v '</{0,1}errorcode>|/{0,1}data>|</{0,1}content>|</{0,1}desc>'
Feb  3 13:51:45 <nodename> xcat.updatenode.postscript[22122 DEBUG  + errorcode=0
Feb  3 14:16:06 <nodename> xcat.deployment.postbootscript ERR provision completed with error.(<nodename>)

**Comment by gurevichmark** [comment]
@marseaplage Can you show the osimage definition of the image you are deploying ?

**Comment by marseaplage** [comment]
@gurevichmark 

La imagen es la siguiente:

Object name: custom_centos8-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos8-x86_64
    osname=Linux
    osvers=centos8
    otherpkgdir=/install/post/otherpkgs/centos8/x86_64
    otherpkglist=/opt/xcat/share/xcat/install/centos/compute.otherpkgs.pkglist
    partitionfile=/install/custom/partitions/parts-quinde-2
    pkgdir=/install/centos8/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.centos8.pkglist
    profile=compute
    provmethod=install
    template=/root/backups/configfiles/compute.centos8custom.tmpl

I have also tried the remoteshell script and apparently everything is ok, I would like to know how to change the status failed to synced or sthg else.

updatenode <nodename> -P remoteshell

<nodename>: + local svcd=
<nodename>: + local svcd=
<nodename>: + '[' -n sshd ']'
<nodename>: + cmd='systemctl restart sshd'
<nodename>: + '[' -z 'systemctl restart sshd' ']'
<nodename>: + local retmsg
<nodename>: ++ systemctl restart sshd
<nodename>: + retmsg=
<nodename>: + retval=0
<nodename>: + '[' 0 = 0 ']'
<nodename>: + echo ''
<nodename>: + grep -i 'Running in chroot,\s*ignoring request.*'
<nodename>: + return 0
<nodename>: + '[' 0 '!=' 0 ']'
<nodename>: + kill -9 22086
<nodename>: postscript end....: remoteshell exited with code 0
<nodename>: Running of postscripts has completed.
<nodename>: =============updatenode ending====================

**Comment by gurevichmark** [comment]
@marseaplage Can you also show node definition ?

You can manually change the `status` attribute with `chdef <node> status=<value>`

**Comment by marseaplage** [comment]
@gurevichmark but hahah that's not the proper way to solve this problem. The idea is try to discover why the status is failed. Any ideas to discover that?

**Comment by gurevichmark** [comment]
@marseaplage Can u post the node definition, want to see if there other postscirpts listed.

**Comment by marseaplage** [comment]
> @marseaplage Can u post the node definition, want to see if there other postscripts listed.

Hello @gurevichmark 

The node definition is this one:

lsdef <nodename>

Object name: <nodename>
    arch=x86_64
    bmc=172.31.168.26
    bmcpassword=mgmtIpmi2021
    bmcusername=adminhpe
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=install centos8-x86_64-compute
    groups=compute,all
    ip=10.50.1.249
    mac=00:17:a4:77:04:18
    mgt=ipmi
    netboot=xnba
    nicips.ib0=192.168.0.245
    nicnetworks.ib0=ib0
    nictypes.ib0=InfiniBand
    os=centos8
    postbootscripts=otherpkgs,confignetwork
    postscripts=delete_centos_public_repo,addsiteyum,syslog,remoteshell,syncfiles
    profile=compute
    provmethod=custom_centos8-x86_64-install-compute
    status=installing
    statustime=02-04-2021 17:24:56
    updatestatus=failed
    updatestatustime=02-04-2021 12:14:50

**Comment by cxhong** [comment]
`postbootscripts=otherpkgs,confignetwork`,  I suggest the `confignetwork` script should be in the `postscripts`.
`confignetwork` script will restart network,  it will affect the network communication between the management node and compute node which may cause compute node failed to send notification to management node to update the `boot status`.

**Comment by marseaplage** [comment]
> `postbootscripts=otherpkgs,confignetwork`, I suggest the `confignetwork` script should be in the `postscripts`.
> `confignetwork` script will restart network, it will affect the network communication between the management node and compute node which may cause compute node failed to send notification to management node to update the `boot status`.

Hello @cxhong 

You are totally right and I did it and the update status is synced but the status is still failed. How can I discover the reason?

**Comment by gurevichmark** [comment]
@marseaplage Can you check the `xcat.log` file on compute node to verify that all scripts specified in `postscripts` and in `postbootscripts` exited with rc=0 ?

**Comment by marseaplage** [comment]
Hello @gurevichmark 

Yes I did it and I discovered the error with the script configib but the infiniband interfaces is well configured with the ip and also when I run the script with update node the exit code is 0 (which is succesfull execution) and the -1 exit is due to a log thar doesn't exist as you can see below:

![2](https://user-images.githubusercontent.com/49536604/107054526-411f5c00-679e-11eb-994f-68fa0d49a32d.png)
![3](https://user-images.githubusercontent.com/49536604/107054530-41b7f280-679e-11eb-8c9e-6359646691ec.png)
![1](https://user-images.githubusercontent.com/49536604/107054531-41b7f280-679e-11eb-9912-82a8acb8454f.png)

updatenode <nodename> -P configib

<nodename>: =============updatenode starting====================
<nodename>: trying to download postscripts...
<nodename>: postscripts downloaded successfully
<nodename>: trying to get mypostscript from 10.50.1.224...
<nodename>: postscript start..: configib
<nodename>: ++ uname -s
<nodename>: ++ tr A-Z a-z
<nodename>: + '[' linux = linux ']'
<nodename>: ++ dirname ./configib
<nodename>: + str_dir_name=.
<nodename>: + . ./xcatlib.sh
<nodename>: ++ declare -a array_nic_params
<nodename>: ++ declare -a array_extra_param_names
<nodename>: ++ declare -a array_extra_param_values
<nodename>: + '[' -n xcat.updatenode.postscript ']'
<nodename>: + log_label=xcat.updatenode.postscript
<nodename>: + nmcli_used=0
<nodename>: + '[' -n '' ']'
<nodename>: + portnum=1
<nodename>: + '[' -n '' ']'
<nodename>: + '[' -z '' ']'
<nodename>: + echo 'nothing to do.'
<nodename>: nothing to do.
<nodename>: ++ uname
<nodename>: + PLTFRM=Linux
<nodename>: + [[ centos8 == rhels5* ]]
<nodename>: + [[ centos8 == rhels6* ]]
<nodename>: + [[ centos8 == ubuntu14* ]]
<nodename>: + ib_driver=openibd
<nodename>: + restart_ib_driver=0
<nodename>: + '[' Linux == Linux ']'
<nodename>: + '[' -f /etc/rdma/rdma.conf ']'
<nodename>: ++ md5sum /etc/rdma/rdma.conf
<nodename>: ++ cut '-d ' -f1
<nodename>: + md5f1=e72dbb2cccc517116dec00b819d068e0
<nodename>: ++ sed s/SDP_LOAD=yes/SDP_LOAD=no/g /etc/rdma/rdma.conf
<nodename>: + TMP1='# Load IPoIB
<nodename>: IPOIB_LOAD=yes
<nodename>: # Load SRP (SCSI Remote Protocol initiator support) module
<nodename>: SRP_LOAD=yes
<nodename>: # Load SRPT (SCSI Remote Protocol target support) module
<nodename>: SRPT_LOAD=yes
<nodename>: # Load iSER (iSCSI over RDMA initiator support) module
<nodename>: ISER_LOAD=yes
<nodename>: # Load iSERT (iSCSI over RDMA target support) module
<nodename>: ISERT_LOAD=yes
<nodename>: # Load RDS (Reliable Datagram Service) network protocol
<nodename>: RDS_LOAD=no
<nodename>: # Load NFSoRDMA client transport module
<nodename>: XPRTRDMA_LOAD=yes
<nodename>: # Load NFSoRDMA server transport module
<nodename>: SVCRDMA_LOAD=no
<nodename>: # Load Tech Preview device driver modules
<nodename>: TECH_PREVIEW_LOAD=no'
<nodename>: + echo '# Load IPoIB
<nodename>: IPOIB_LOAD=yes
<nodename>: # Load SRP (SCSI Remote Protocol initiator support) module
<nodename>: SRP_LOAD=yes
<nodename>: # Load SRPT (SCSI Remote Protocol target support) module
<nodename>: SRPT_LOAD=yes
<nodename>: # Load iSER (iSCSI over RDMA initiator support) module
<nodename>: ISER_LOAD=yes
<nodename>: # Load iSERT (iSCSI over RDMA target support) module
<nodename>: ISERT_LOAD=yes
<nodename>: # Load RDS (Reliable Datagram Service) network protocol
<nodename>: RDS_LOAD=no
<nodename>: # Load NFSoRDMA client transport module
<nodename>: XPRTRDMA_LOAD=yes
<nodename>: # Load NFSoRDMA server transport module
<nodename>: SVCRDMA_LOAD=no
<nodename>: # Load Tech Preview device driver modules
<nodename>: TECH_PREVIEW_LOAD=no'
<nodename>: ++ md5sum /etc/rdma/rdma.conf
<nodename>: ++ cut '-d ' -f1
<nodename>: + md5f2=e72dbb2cccc517116dec00b819d068e0
<nodename>: + '[' e72dbb2cccc517116dec00b819d068e0 '!=' e72dbb2cccc517116dec00b819d068e0 ']'
<nodename>: + '[' -f /etc/modprobe.conf ']'
<nodename>: + enableservice openibd
<nodename>: + sysctl -p
<nodename>: + '[' Linux == Linux ']'
<nodename>: + '[' -f /etc/redhat-release ']'
<nodename>: + OS_name=redhat
<nodename>: + '[' redhat '!=' ubuntu ']'
<nodename>: + '[' redhat == suse ']'
<nodename>: + dir=/etc/sysconfig/network-scripts
<nodename>: ++ echo ''
<nodename>: ++ tr , '\n'
<nodename>: + goodnics=
<nodename>: ++ echo ''
<nodename>: ++ tr , '\n'
<nodename>: + '[' Linux == Linux ']'
<nodename>: + '[' 0 = 1 ']'
<nodename>: ++ echo ''
<nodename>: ++ tr , '\n'
<nodename>: ++ sort -u
<nodename>: postscript end....: configib exited with code 0
<nodename>: Running of postscripts has completed.
<nodename>: =============updatenode ending====================

What do you think is the cause of the failed status in the node definition?

**Comment by gurevichmark** [comment]
@marseaplage Yes, my guess is that failure of `configib` script is what is causing `status=failed`.

Did you reprovision the node after making `postbootscripts` and `postscripts` changes as @cxhong suggested ? The `status` attribute is not updated if you just run `updatenode`.

You can also try to provision the node without any of your own postscript and postbootscripts and see if that makes a difference. Or try to provision the node non-"custom" OS image.

**Comment by marseaplage** [comment]
Hi guys,

I have just restarted the node and as you can see in the image below. the node status has changed to "booted" is that ok for the normal status of the node definition?

![4](https://user-images.githubusercontent.com/49536604/107067074-c7db3580-67ac-11eb-8ea6-c2c6c555d5a8.png)

**Comment by gurevichmark** [comment]
Yes, `booted` is a "normal" status for successful node provisioning.
You can use `chdef` command with `--minus` flag to remove a postscript from `postbootscripts` attribute.

**Comment by marseaplage** [comment]
> Yes, `booted` is a "normal" status for successful node provisioning.
> You can use `chdef` command with `--minus` flag to remove a postscript from `postbootscripts` attribute.

Thank you so much guys for all your help so I will add a command to restart the node after running the postscripts in order to get the status booted.
