### ISSUE TITLE
32bit linux app can not run on rhelhpc 6.x compute node.

### ISSUE THREAD

**Issue by coldbloodx** [xcat2/xcat-core#69]
Some applications needs 32 bit run time, like JRE(32bit)

The root cause of the problem is that the glibc.i686 and libgcc.i686 is not installed on compute node.
check the package list, above packages are not included,below is my fix.

leo@office[xcat-xcat-core]:$git diff
leo@office[xcat-xcat-core]:$git diff --cached
diff --git a/xCAT-server/share/xcat/install/rh/compute.rhelhpc6.pkglist b/xCAT-server/share/xcat/install/rh/compute.rhelhpc6.pkglist
index 40b8f7e..3056be8 100644
--- a/xCAT-server/share/xcat/install/rh/compute.rhelhpc6.pkglist
+++ b/xCAT-server/share/xcat/install/rh/compute.rhelhpc6.pkglist
@@ -4,3 +4,5 @@ net-snmp
 rsync
 openssh-server
 util-linux-ng
+glibc.i686
+libgcc.i686
diff --git a/xCAT-server/share/xcat/netboot/rh/compute.rhelhpc6.pkglist b/xCAT-server/share/xcat/netboot/rh/compute.rhelhpc6.pkglist
index e235bfa..018213d 100644
--- a/xCAT-server/share/xcat/netboot/rh/compute.rhelhpc6.pkglist
+++ b/xCAT-server/share/xcat/netboot/rh/compute.rhelhpc6.pkglist
@@ -20,3 +20,5 @@ rsync
 rsyslog
 e2fsprogs
 parted
+glibc.i686
+libgcc.i686

Thanks,
Xian

**Comment by daniceexi** [comment]
Generally, xx.pkglist is just a template for user to reference. If your cluster need some specific packages, you can add it by yourselves. 

Mostly, we recommend customer to make a copy of your osimage and change it according to your requirement.

**Comment by samveen** [comment]
@coldbloodx , you can alternately create a post-script to install the 32bit packages required on your compute nodes and add the script to node's `postscripts`:
```
chdef -t node $node -p postscripts='install_32_bit_packages.sh'
```
