### ISSUE TITLE
xCat 2.14.6 on RHEL 7.9

### ISSUE THREAD

**Issue by gujjaai1** [xcat2/xcat-core#6902]
Hello,

We are currently using xCat version 2.14.6 on RHEL 7.7 and want to upgrade to RHEL 7.9.

Will xCat 2.14.6 support on RHEL 7.9? Will there be an error or we are good to go?

**Comment by gurevichmark** [comment]
@gujjaai1 RHEL7.7 is officially supported with xCAT 2.15.1, but it looks like it works for you with 2.14.6 also.
We have internally tried RHEL7.9 with xCAT 2.16.1 and it appears to work in our environment.
While xCAT does not officially support RHEL7.9, my guess is that it will probably work for you on 2.16.4
You might want to try one node experiment, before switching the whole cluster.

**Comment by gujjaai1** [comment]
Thanks for the response. 
As we do not have a work environment over here to test, as it is a live cluster.
Could you please confirm if we can go ahead with xCAT 2.14.6 version on RHEL 7.9?

**Comment by gurevichmark** [comment]
RHEL 7.9 is not officially supported by xCAT.
You could try posting a question on the `xcat-user` mailing list (https://sourceforge.net/projects/xcat/lists/xcat-user) to see if anyone had success with that version of OS.

**Comment by viniciusferrao** [comment]
As @gurevichmark said, it's not officially supported. I have 7.9 working with 2.16.1 too, no issues.
