### ISSUE TITLE
[FVT] xCAT migration from 2.9.2 on aix71R to 2.9.3 on aix720 failed 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#691]
Test OS : AIX 71R migration to AIX 720
Test xCAT version: xCAT2.9.2 migration xCAT 2.9.3
How to reproduce:

1. install xCAT 2.9.2 on AIX71R
2. update AIX 71R to AIX720
3. migration xCAT to 2.9.2
```
bash-3.2# ./instoss 
Running updtvpkg. This could take a few minutes.
Please wait...
updtvpkg has completed.
package unixODBC-2.2.15-32bit is already installed
rpm -Uvh --ignoreos bash-3.2-1.aix5.2.ppc.rpm
package bash-3.2-1 is already installed
rpm -Uvh --ignoreos conserver-8.1.16-2.aix5.3.ppc.rpm
package conserver-8.1.16-2 is already installed
rpm -Uvh --ignoreos curl-7.46.0-1ssl.aix7.2.ppc.rpm
curl                        ##################################################
rpm -Uvh --ignoreos expat-2.0.1-2.aix5.1.ppc.rpm
package expat-2.0.1-2 is already installed
rpm -Uvh --ignoreos fping-2.4b2_to-1.aix5.3.ppc.rpm
package fping-2.4b2_to-1 is already installed
rpm -Uvh --ignoreos libxml2-2.6.21-4.aix5.2.ppc.rpm
package libxml2-2.6.21-4 is already installed
rpm -Uvh --ignoreos openslp-xcat-1.2.1-1.aix5.3.ppc.rpm
package openslp-xcat-1.2.1-1 is already installed
rpm -Uvh --ignoreos perl-Crypt-SSLeay-0.57-3.aix7.2.ppc.rpm
package perl-Crypt-SSLeay-0.57-3 is already installed
file /opt/freeware/doc/perl-Crypt-SSLeay-0.57/eg/lwp-ssl-test from install of perl-Crypt-SSLeay-0.57-3 conflicts with file from package perl-Crypt-SSLeay-0.57-3
file /opt/freeware/doc/perl-Crypt-SSLeay-0.57/eg/net-ssl-test from install of perl-Crypt-SSLeay-0.57-3 conflicts with file from package perl-Crypt-SSLeay-0.57-3
rpm -Uvh --ignoreos perl-DBD-SQLite-1.48-1.aix7.2.ppc.rpm
package perl-DBD-SQLite-1.48-1 is already installed
rpm -Uvh --ignoreos --nodeps perl-DBI-1.634-1.aix7.2.ppc.rpm
perl-DBI                    ##################################################
rpm -Uvh --ignoreos perl-Debug-Trace-0.05-1.aix7.2.ppc.rpm
package perl-Debug-Trace-0.05-1 is already installed
rpm -Uvh --ignoreos perl-Digest-HMAC-1.03-1.aix7.2.ppc.rpm
package perl-Digest-HMAC-1.03-1 is already installed
rpm -Uvh --ignoreos perl-Digest-MD5-2.54-1.aix7.2.ppc.rpm
package perl-Digest-MD5-2.54-1 is already installed
rpm -Uvh --ignoreos --nodeps perl-Digest-SHA-5.95-1.aix7.2.ppc.rpm
perl-Digest-SHA             ##################################################
cannot remove /usr/share/man/man1 - directory not empty
removal of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/auto/Digest/SHA/SHA.so failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/auto/Digest/SHA failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/auto/Digest failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/Digest/SHA.pm failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/Digest failed: A file or directory in the path name does not exist.
rpm -Uvh --ignoreos perl-Digest-SHA1-2.13-1.aix7.2.ppc.rpm
package perl-Digest-SHA1-2.13-1 is already installed
rpm -Uvh --ignoreos perl-Expect-1.21-3.aix7.2.ppc.rpm
package perl-Expect-1.21-3 is already installed
file /opt/freeware/doc/perl-Expect-1.21/tutorial/2.A.ftp from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/2.B.rlogin from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/3.A.debugging from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/4.A.top from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/5.A.top from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/5.B.top from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/6.A.smtp-verify from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/tutorial/6.B.modem-init from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/examples/kibitz/kibitz from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
file /opt/freeware/doc/perl-Expect-1.21/examples/ssh.pl from install of perl-Expect-1.21-3 conflicts with file from package perl-Expect-1.21-3
rpm -Uvh --ignoreos perl-IO-Socket-SSL-1.38-1.aix7.2.ppc.rpm
package perl-IO-Socket-SSL-1.38-1 is already installed
rpm -Uvh --ignoreos perl-IO-Stty-0.03-2.aix7.2.ppc.rpm
package perl-IO-Stty-0.03-2 is already installed
file /usr/opt/perl5/man/man3/IO::Stty.3 from install of perl-IO-Stty-0.03-2 conflicts with file from package perl-IO-Stty-0.03-2
rpm -Uvh --ignoreos perl-IO-Tty-1.12-1.aix7.2.ppc.rpm
package perl-IO-Tty-1.12-1 is already installed
rpm -Uvh --ignoreos perl-Net-DNS-1.04-1.aix7.2.ppc.rpm
package perl-Net-DNS-1.04-1 is already installed
rpm -Uvh --ignoreos --nodeps perl-Net-IP-1.26-1.aix7.2.ppc.rpm
perl-Net-IP                 ##################################################
rpm -Uvh --ignoreos perl-Net-Telnet-3.04-1.aix7.2.ppc.rpm
package perl-Net-Telnet-3.04-1 is already installed
rpm -Uvh --ignoreos perl-XML-Simple-2.22-1.aix7.2.ppc.rpm
package perl-XML-Simple-2.22-1 is already installed
rpm -Uvh --ignoreos perl-version-0.82-2.aix7.2.ppc.rpm
package perl-version-0.82-2 is already installed
file /opt/freeware/doc/perl-version-0.82/vutil/lib/version/vxs.pm from install of perl-version-0.82-2 conflicts with file from package perl-version-0.82-2
rpm -Uvh --ignoreos popt-1.7-2.aix5.1.ppc.rpm
package popt-1.7-2 is already installed
rpm -Uvh --ignoreos rsync-3.0.6-1.aix5.3.ppc.rpm
package rsync-3.0.6-1 is already installed
rpm -Uvh --ignoreos unzip-5.51-1.aix5.1.ppc.rpm
package unzip-5.51-1 is already installed
rpm -Uvh --ignoreos wget-1.9.1-1.aix5.1.ppc.rpm
package wget-1.9.1-1 is already installed
net-snmp                    ##################################################
ln: 0653-421 /lib/libperl.a exists.
    Specify -f to remove /lib/libperl.a before linking.
execution of net-snmp-5.7.3-3 script failed, exit status 1
net-snmp-perl               ##################################################
cannot remove /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/auto - directory not empty
bash-3.2# 
```

**Comment by neo954** [comment]
@junxiawang , if you have time, it is great if you can try the command below. And then try to re-install the xCAT dependency packages again. Thanks for your time.

    rpm -e --nodeps unixODBC bash conserver expat fping libxml2 openslp-xcat perl-Crypt-SSLeay perl-DBD-SQLite perl-Debug-Trace perl-Digest-HMAC perl-Digest-MD5 perl-Digest-SHA1 perl-Expect perl-IO-Socket-SSL perl-IO-Stty perl-IO-Tty perl-Net-DNS perl-Net-Telnet perl-XML-Simple perl-version popt rsync unzip wget

**Comment by whowutwut** [comment]
Am I reading the above correct?  Why does instoss install the RPMs with ``--ignoreos`` flag in there? 
Also it looks like it's failing on the AIX package update.. NOT xCAT? 
```
execution of net-snmp-5.7.3-3 script failed, exit status 1
net-snmp-perl               ##################################################
cannot remove /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/auto - directory not empty
```
@neo954 , why do you suggest we try installing using ``--nodeps``??

**Comment by junxiawang** [comment]
@neo954 
# rpm -e --nodeps unixODBC conserver expat fping libxml2 openslp-xcat perl-Crypt-SSLeay perl-DBD-SQLite perl-Debug-Trace perl-Digest-HMAC perl-Digest-MD5 perl-Digest-SHA1 perl-Expect perl-IO-Socket-SSL perl-IO-Stty perl-IO-Tty perl-Net-DNS perl-Net-Telnet perl-XML-Simple perl-version popt rsync unzip wget
error: package perl-XML-Simple is not installed
cannot remove /usr/local/bin - directory not empty
cannot remove /usr/lib - directory not empty
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/auto/Crypt/SSLeay/SSLeay.so failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/auto/Crypt/SSLeay failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/auto/Crypt failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Net/SSL.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay/X509.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay/MainContext.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay/Err.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay/Conn.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay/CTX.pm failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay.pm failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt/SSLeay failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/site_perl/5.10.1/aix-thread-multi/Crypt failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/auto/Digest/MD5/MD5.so failed: A file or directory in the path name does not exist.
rmdir of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/auto/Digest/MD5 failed: A file or directory in the path name does not exist.
removal of /usr/opt/perl5/lib/5.10.1/aix-thread-multi/Digest/MD5.pm failed: A file or directory in the path name does not exist.
exec(): 0509-036 Cannot load program /usr/opt/freeware/bin/rpm because of the following errors:
        0509-150   Dependent module libpopt.so could not be loaded.
        0509-022 Cannot load module libpopt.so.
        0509-026 System error: A file or directory in the path name does not exist.
rpm_share: 0645-007 ATTENTION: get_rpm_inst_root_list() returned an unexpected result.
rpm_share: 0645-007 ATTENTION: update_inst_root() returned an unexpected result.
# bash
bash-3.2# exit
exit
# bash
bash-3.2# rpm -h
exec(): 0509-036 Cannot load program /usr/opt/freeware/bin/rpm because of the following errors:
        0509-150   Dependent module libpopt.so could not be loaded.
        0509-022 Cannot load module libpopt.so.
        0509-026 System error: A file or directory in the path name does not exist.
------>now rpm could not work using your suggestion

**Comment by junxiawang** [comment]
My steps:
```
1. rpm -e perl-Expect-1.21-3 perl-Digest-SHA-5.48-3 perl-IO-Stty-0.03-2 net-snmp-5.7.2-3 net-snmp-devel-5.7.2-3 net-snmp-perl-5.7.2-3  perl-version-0.82-2 perl-Crypt-SSLeay
2. rm /lib/libperl.a
   Note: If we get such information duing update xcat-dep " ln: 0653-421 /lib/libperl.a exists.
            Specify -f to remove /lib/libperl.a before linking."  ,we have to remove file using "rm   /lib/libperl.a".
3. Then update xcat-dep ./instoss
4. Then update xcat-core ./instxcat
Then the xcat will update to 2.9.3 from 2.9.2 
bash-3.2# lsxcatd  -v
Version 2.9.3 (git commit 5345643cf8fd145fb6c66397624445b6538d9d24, built Fri Jan 29 02:25:14 CST 2016)

```

**Comment by junxiawang** [comment]
test it
