### ISSUE TITLE
r* commands (rpower, rsetboot, rinv, etc...) end up becoming timeout error.

### ISSUE THREAD

**Issue by tk9320** [xcat2/xcat-core#6913]
Please advise me that what should I check when r~~ commands (rpower, rsetboot, rinv, etc...) is timeout error on one of compute nodes.
This compute node seem to be no problems (at least, error lamps is not put on.) and is able to ssh from management node. 
I found the problem about last week. These commands can be used until then. On other nodes, similar error is not occurred. 

```
[root@management node ~]# rpower compute node stat
compute node: [management node]: Error: ERROR: timeout
```

Although it have problems on the compute node, is there anything I can check on the management node side?

**Comment by gurevichmark** [comment]
What version of xCAT ?
What is the value of `mgt` attribute of the compute node ?

**Comment by tk9320** [comment]
The version is 2.15.1.

> What is the value of mgt attribute of the compute node ?

mgt=ipmi
All compute nodes are the same regardless of whether it is problem or not.

**Comment by gurevichmark** [comment]
@tk9320 You can try setting xCAT debug mode on with `chdef -t site clustersite xcatdebugmode=2` and run one of the r* commands again. The debug output might show which specific ipmi call causes the timeout.

**Comment by tk9320** [comment]
I found there is a defect in `ipmi table` compared to other servers.
r* commands became able to run normally.

Thank you for your support.
