### ISSUE TITLE
getinstdisk erroneously stated to have found kernel files where there are none

### ISSUE THREAD

**Issue by dombrowa** [xcat2/xcat-core#6923]
the getinstdisk script from
```
xCAT.x86_64                            2.16.1-snap202011041655    @xcat-core
```
contains code which does not function.  In /opt/xcat/share/xcat/install/scripts/getinstdisk the code block 
```
           for i in $ker_dir/vmlinu*; do
                disk_part=${partition%%[0-9]*}
                touch "$tmpfile$disk_part"
                disk_array=$disk_array"$disk_part "
                echo "[get_install_disk]    The partition $partition has kernel file."
                break
            done
```
Evaluates   $ker_dir/vmlinu* to a string. Therefore the 
```
echo "[get_install_disk]    The partition $partition has kernel file."
```
is always true.
This caused provisioning of the first found device in /proc/partitions which in our case was a nvme device  and not a nvme partition
```
cat /proc/partitions
major minor  #blocks  name

 259        1 3125616984 nvme0n1
 259        2 3125615616 nvme0n1p1
   8       32  976762584 sdc
   8       33  976761560 sdc1
   8       16  976762584 sdb
   8       17  976761560 sdb1
   8        0  976762584 sda
   8        1     248832 sda1
   8        2          1 sda2
   8        5  974511104 sda5
   8        6    1998848 sda6
   8       48  468851544 sdd
   8       49  468850520 sdd1
   8       80  468851544 sdf
   8       81  468850520 sdf1
   8       96  468851544 sdg
   8       97  468850520 sdg1
   8       64  468851544 sde
   8       65  468850520 sde1
```

The offending line can be changed to
```
            for i in `ls -1 "$ker_dir/vmlinu*" 2>/dev/null`; do
```

**Comment by besawn** [comment]
@dombrowa Thanks for the detailed information.

**Comment by gurevichmark** [comment]
@dombrowa Which OS are  you installing ?

When I tried installation of RH8 and SLES15, the current existing code in `/opt/xcat/share/xcat/install/scripts/getinstdisk` worked correctly for me. On Ubuntu18, I did see the problem as you reported with `$ker_dir/vmlinu*` always evaluating to true.

**Comment by dombrowa** [comment]
It was Ubuntu 18. The busy box shell of the debian installer is so
mediocre that the shell expansion does not work the same as in a "real
shell".
Better check on the existence of the files inside the for loop.
