### ISSUE TITLE
Get information from passwd table in mypostscript.tmpl?

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#6925]
Hi!

Is it possible to get information from the `passwd` table in `mypostscript.tmpl` without having to dump it all with `tabdump(passwd)`?

I tried a few variations around this:
```
#TABLE:passwd:ipmi:username#
```
to try to retrieve the IPMI username defined in the `passwd` table (some of my postscripts would need that), but it comes out empty.

For reference, the `passwd` table looks like this:
```
#key,username,password,cryptmethod,authdomain,comments,disable
"ipmi","foo","bar",,,,
```

Any suggestion?

Thanks!

**Comment by gurevichmark** [comment]
The `#TABLE` is only supported for tables that use nodename as a key.
Documentation will be updated to explicitly state that in #6999
