### ISSUE TITLE
xdsh ssh alternative port number

### ISSUE THREAD

**Issue by rderooy** [xcat2/xcat-core#6946]
It seems xdsh completely ignores the Port setting  in ``~/.ssh/config``

I have devices on a different port, and while ssh and psh is fine, since I set the port in the ssh config, it fails for xdsh.
```
$ psh nfs01 true
$ xdsh nfs01 true
[xcat]: nfs01: ssh: connect to host nfs01 port 22: Connection refused
```

**Comment by rderooy** [comment]
Ok, found that it does not use the users ``~/.ssh/config``, but rather the one you create in ``/etc/ssh/ssh_config.d/``. After setting the port there, I got further.

**Comment by peterwywong** [comment]
In an experiment of changing the SSH port number, I provided the same port number (e.g., 7822) in /etc/ssh/ssh_config (for an SSH client) and /etc/ssh/sshd_config (for the SSH server). (Make sure that "#" is removed.) No file under /etc/ssh/ssh_config.d was modified. 
To make it effective, run **service sshd stop** and **service sshd start** on the server side.
xCAT has a page of port usage on https://xcat-docs.readthedocs.io/en/stable/advanced/ports/xcat_ports.html?highlight=port .
xCAT makes use of SSH whose default port number is 22. 
The above method of changing the SSH port number is not tied to xCAT.
