### ISSUE TITLE
Add support for Rocky Linux

### ISSUE THREAD

**Issue by buzh** [xcat2/xcat-core#6966]
After the Red Hat announcement that CentOS as we know it will be discontinued later this year, Rocky Linux has sailed up as a major candidate to take over the throne of being the foremost "binary and bug for bug compatible" RHEL clone.

They recently released RC1 for x86_64 and ARM64, available here: https://rockylinux.org/download

Will you please add support for Rocky Linux in xCAT?

Best regards

**Comment by besawn** [comment]
The xCAT core team does not have sufficient resources to add official support for Rocky Linux to xCAT, but we welcome contributions from any xCAT community members that are able to contribute to this effort.

Another CentOS alternative that users may want to consider is Oracle Linux.
 @viniciusferrao recently contributed some code changes for Oracle Linux here:
https://github.com/xcat2/xcat-core/pull/6919
with some additional updates made by @gurevichmark here:
https://github.com/xcat2/xcat-core/pull/6948
(Thanks @viniciusferrao and @gurevichmark.)

For anyone interested in adding Rocky Linux support, studying the two pull requests above will likely make the process easier.

**Comment by desnij** [comment]
> For anyone interested in adding Rocky Linux support, studying the two pull requests above will likely make the process easier.

Consider me interested, but busy... if anyone is working on this let me know else, I will likely look into it around November. 
I had already looked at the ISO and its lacking the features to automate the copycds script, but I didn't go much farther...

**Comment by besawn** [comment]
Initial support for Rocky Linux 8.4 was included with xCAT 2.16.3.
