### ISSUE TITLE
Issue in `remoteshell` Postscript when Deploying RHELS 8.2 Stateless Image

### ISSUE THREAD

**Issue by nicolas-tallet** [xcat2/xcat-core#6974]
Dear Colleagues,

We are facing a weird issue when trying to deploy a RHELS 8.2 stateless image from our xCAT 2.16.1 Management Node:
```
[root@xcatmn /]# lsxcatd -a
Version 2.16.1 (git commit a85566c8be85ee7eec991b0840e53295de686e49, built Wed Nov  4 16:55:06 EST 2020)
This is a Management Node
dbengine=SQLite
```

The following postscripts are to be executed right after boot:
```
[root@xcatmn /]# lsdef r211n09-adm -i postscripts
Object name: r211n09-adm
    postscripts=syslog,remoteshell,syncfiles,custom/postinstall_stateless_node_2
```

According to the debug log:
* The `syslog` postscript properly completes
* The `remoteshell` postscript  exists with a 0 return code but it actually loops until its 10th retry so that looks like a silent failure:
```
May 12 16:05:39 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + sleep 12
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + RETRY=9
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + '[' 9 -eq 10 ']'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + '[' 0 = 1 ']'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + sed -e 's/&lt;/</' -e 's/&gt;/>/' -e 's/&amp;/&/' -e 's/&quot/"/' -e 's/&apos;/'\''/'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + grep -v '<'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + getcredentials.awk ssh_root_key
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  ++ cat /root/.ssh/id_rsa
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + MYCONT=
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + '[' -z '' ']'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + '[' 0 = 0 ']'
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + let SLI=8656%10
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + let SLI=SLI+10
May 12 16:05:51 r211n09-adm xcat.deployment.postbootscript[6 DEBUG  + sleep 16
May 12 16:06:07 r211n09-adm.p3.hq.ep.corp.local xcat.deployment.postbootscript INFO postbootscript end...:remoteshell return with 0
```

The guilty guy is apparently the `getcredentials.awk` script that probably fails to open an SSL connection to the xCAT Master Node, but we don't have any clue on what the root cause of the issue could be.

Would you have any suggestion on how to troubleshoot this issue?

Thanks a lot in advance.

**Comment by besawn** [comment]
There is a common issue related to having an explicit value set for `xcatsslversion` or `xcatsslciphers` in the `site` table that is not compatible with the SSL cipher versions supported by the version of openssl that ships with RHEL 8. Most likely you have `xcatsslversion` set to `TLSv1`, which was needed at one point for an older OS, but is not supported by the updated version of openssl included with RHEL 8.

Check to see if you have anything set for `xcatsslversion` or `xcatsslciphers` in the site table using:
```
tabdump site | egrep "xcatsslversion|xcatsslciphers"
```

If you have those attributes set, as an experiment, remove the `xcatsslversion` and `xcatsslciphers` from the site table using tabedit and repeat the installation to see if getcredentials.awk succeeds.

If things are now working, you can leave `xcatsslversion` and `xcatsslciphers` out of the site table if you do not require specific SSL versions or ciphers; xCAT will choose default values if those attributes are not set.

If you require specific `xcatsslversion` or `xcatsslciphers` settings, you will need to adjust the settings to be compatible with the versions of OpenSSL installed on the management node and compute node to produce a working combination.
I can provide more information on how to check these settings, but let's confirm whether this is the problem first.

**Comment by nicolas-tallet** [comment]
Hi @besawn ,

Thanks a lot for your reply.

We stumbled on a post that was mentioning that resetting the `xcatsslversion` / `xcatsslciphers` was a way to solve this kind of issue, but that apparently didn't help in our case.

So for now, we are back to the following settings:
```
# tabdump site | egrep "xcatsslversion|xcatsslciphers"
"xcatsslversion","TLSv1_2",,
```

We'll make another try with an empty `xcatsslversion`attribute as instructed, though, in order to double check.
Do we need to regenerate the OS image after changing the attribute value, or redeploying the current image is enough?

Thanks.

Nicolas.

**Comment by besawn** [comment]
You do not need to regenerate the OS image, redeploying the current image is sufficient.

Another common problem that can interfere with `getcredentials.awk` is having the firewall up on either the management node or compute node.

What OS version is installed on your management node?

**Comment by besawn** [comment]
You do need to restart xcatd on the management node after making changes to the `xcatsslversion`/`xcatsslciphers` settings:
`restartxcatd`

**Comment by nicolas-tallet** [comment]
> You do need to restart xcatd on the management node after making changes to the xcatsslversion/xcatsslciphers settings:
restartxcatd

Well noted - we always do so.

> What OS version is installed on your management node?

RHELS 8.2 as well, as I've been told by @gurevichmark that RHELS 8 was required on the xCAT Management Node for generating a RHELS 8 image.

**Comment by nicolas-tallet** [comment]
After making a couple of adjustments both on our Management Server (which is hosted inside a Docker container) and our OS Image (`firewalld` systemd unit was enabled by default and required to be disabled to allow proper communication between MN and CN after reboot), it looks like the above issue is gone.

However, we now hit a new issue that makes it impossible to open an SSH session on the Compute Node, though the SSH keys have been apparently properly deployed:

* From the Remote Console: `root: no shell: Permission denied` error message:
```
r211n09 login: root
Password:
Last login: Tue May 18 11:12:52 on hvc0
 -- root: no shell: Permission denied
```

* Through SSH: `Broken pipe` error message:
```
debug1: Next authentication method: publickey
debug1: Offering public key: /root/.ssh/id_rsa RSA SHA256:MpJN0aafIl0Ph6iLW7JQfwC4LmTSoPqwRHX4a2Rdlg0
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: /root/.ssh/id_rsa RSA SHA256:MpJN0aafIl0Ph6iLW7JQfwC4LmTSoPqwRHX4a2Rdlg0
debug1: Authentication succeeded (publickey).
Authenticated to r211n09-adm ([172.17.2.209]:22).
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
client_loop: send disconnect: Broken pipe
```

Could you please advise on what could be attempted to fix this issue?

**Comment by nicolas-tallet** [comment]
All right, we could finally fix the problem.

So as a global summary for people having similar issues and landing on this page, the recommandation is:

* The `firewalld` systemd unit must be properly disabled during the `postinstall` stage of the OS Image generation:
```
$ systemctl disable firewalld.service
```

* `SELinux` must be set to `disabled` inside its configuration file during the `postinstall` stage of the OS Image generation (either through Postscript or file synchronization):
```
$ cat /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
```

Hope this helps.

**Comment by nicolas-tallet** [comment]
@gurevichmark : No, we haven't tried using the `xcatprobe xcatmn` command to diagnose the issue. We'll give it a try whenever we have the opportunity to do so.
