### ISSUE TITLE
[Customer]Default permissions on commands.log are 644

### ISSUE THREAD

**Issue by sjtbham** [xcat2/xcat-core#698]
Default permissions on the commands.log file are 644, this means that any user able to login to the system is able to view the commands.log file, which may contain passwords - for example an xcat user running 'tabdump passwd', this is logged in the commands.log and will enumerate all passwords into the log file.

Other users of the system may then be able to view passwords from this file.

**Comment by daniceexi** [comment]
We'll consider that.
   
    Gong Jie, consider this.
  
  Using IBM Verse, send from my iPhone.
  
  在 2016年2月4日，20:28:05，"Simon Thompson" <notifications@github.com> 写道：
  
     Default permissions on the commands.log file are 644, this means that any user able to login to the system is able to view the commands.log file, which may contain passwords - for example an xcat user running 'tabdump passwd', this is logged in the commands.log and will enumerate all passwords into the log file.
   
   
   Other users of the system may then be able to view passwords from this file.

**Comment by neo954** [comment]
@hu-weihua How about change the umask to 0077 or 0007 before open() the ``commands.log`` file.

**Comment by hu-weihua** [comment]
@neo954, I have changed the permissions of commands.log to 600. Could you review the pull request #741 for this issue?

**Comment by neo954** [comment]
Verified and closed.
