### ISSUE TITLE
InfiniBand Interfaces Definition in RHELS 8 Miss `TYPE` Parameter and Say `NM_CONTROLLED=no`

### ISSUE THREAD

**Issue by nicolas-tallet** [xcat2/xcat-core#6988]
Dear Colleagues,

When deploying our RHELS 8.2 OS Image, the 4 InfiniBand interfaces of the Compute Nodes fail to enable at boot time.

The configuration files that have been generated look like the following:
```
$ cat /etc/sysconfig/network-scripts/ifcfg-ib0
DEVICE=ib0
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=172.18.2.209
NETMASK=255.255.0.0
```

Attempting to perform an `ifup` command in such a configuration results in the following error message:
```
$ ifup ib0
Error: Connection activation failed: No suitable device found for this connection (device enP5p1s0f0 not available because profile is not compatible with device (mismatching interface name)).
```

By comparing the content of the configuration files with the one of the install NIC interface, we came to the conclusion that there were two parameters that needed to be adjusted:
* The parameter `TYPE` is missing and needs to be set to `InfiniBand`: `TYPE=InfiniBand`
* The parameter `NM_CONTROLLED=no` needs to either be specified to `yes` or to be simply removed

Once the two changes above have been applied to their configuration files, the InfiniBand interfaces can be properly enabled:
```
$ ifup ib0
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/4)
$ ip a
[...]
4: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc mq state UP group default qlen 256
    link/infiniband 20:00:0c:ef:fe:80:00:00:00:00:00:00:ec:0d:9a:03:00:cc:a0:b6 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 172.18.2.209/16 brd 172.18.255.255 scope global noprefixroute ib0
       valid_lft forever preferred_lft forever
[...]
```

Is there anything wrong in our configuration that could lead to this situation?
Obviously, we could apply a quick fix through a custom postscript but we would prefer to stay on the standard path here.

Thanks.

**Comment by besawn** [comment]
@nicolas-tallet How are you configuring your IB devices currently? On RHEL8, the `confignetwork` postscript is provided to configure all of the network interfaces (including IB) in your nodes using the associated definitions from the `nics` table.

Documentation is available here:
https://xcat-docs.readthedocs.io/en/stable/advanced/networks/infiniband/network_configuration.html

**Comment by nicolas-tallet** [comment]
@besawn : We do use the standard `confignetwork` Postscript to perform configuration of our network interfaces (including InfiniBand ones).

Here is how the NICs table record pertaining to our Compute Nodes currently looks:
```
"p3cngpu","|r(\d+)n(\d+)-adm|enP5p1s0f0!172.17.($1/100).((($1-1)%100)*20+$2),ib0!172.18.(0*16+$1/100).((($1-1)%100)*20+$2),ib1!172.18.(1*16+$1/100).((($1-1)%100)*20+$2),ib2!172.18.(2*16+$1/100).((($1-1)%100)*20+$2),ib3!172.18.(3*16+$1/100).((($1-1)%100)*20+$2)|",,,"enP5p1s0f0!ethernet,ib0!infiniband,ib1!infiniband,ib2!infiniband,ib3!infiniband",,"enP5p1s0f0!management,ib0!infiniband,ib1!infiniband,ib2!infiniband,ib3!infiniband","|r(\d+)n(\d+)-adm|ib0!r($1)n($2)-ib0,ib1!r($1)n($2)-ib1,ib2!r($1)n($2)-ib2,ib3!r($1)n($2)-ib3|",,,,,
```
and here is how it translates to the node definition:
```
    nicaliases.ib0=r211n09-ib0
    nicaliases.ib1=r211n09-ib1
    nicaliases.ib2=r211n09-ib2
    nicaliases.ib3=r211n09-ib3
    nicips.enP5p1s0f0=172.17.2.209
    nicips.ib0=172.18.2.209
    nicips.ib1=172.18.18.209
    nicips.ib2=172.18.34.209
    nicips.ib3=172.18.50.209
    nicnetworks.enP5p1s0f0=management
    nicnetworks.ib0=infiniband
    nicnetworks.ib1=infiniband
    nicnetworks.ib2=infiniband
    nicnetworks.ib3=infiniband
    nictypes.enP5p1s0f0=ethernet
    nictypes.ib0=infiniband
    nictypes.ib1=infiniband
    nictypes.ib2=infiniband
    nictypes.ib3=infiniband
```

This works well in our current RHELS 7.6 Alternate environment.

One thing worth noting: we currently build the OS Image inside a RHELS 8.2-based container, but keep deploying it with our standard, RHELS 7.6 + xCAT 2.15-based Management Server (reason being: we don't want to break anything on the production platform by performing an update on-the-fly).
Could it be linked to the fact that the `confignetwork` script has evolved between xCAT 2.15 and xCAT 2.16?

**Comment by besawn** [comment]
Can you provide the output from the `confignetwork` postscript? You should be able to find it in `/var/log/xcat/xcat.log` on the compute node.

**Comment by nicolas-tallet** [comment]
Here is what relates to the `confignetwork` Postscript output inside the logs of the Compute Node:
```
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 DEBUG  + /xcatpost/confignetwork
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 DEBUG  [I]: NetworkManager is active
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 INFO  NetworkManager is active
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 DEBUG  [I]: back up /etc/sysconfig/network-scripts to /etc/sysconfig/network-scripts.xcatbak
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 INFO  back up /etc/sysconfig/network-scripts to /etc/sysconfig/network-scripts.xcatbak
May 21 10:06:45 r211n09-adm xcat.deployment.postbootscript[1 DEBUG  [I]: All valid nics and device list:
```

Looks kind of truncated, don't you think?

**Comment by nicolas-tallet** [comment]
All right - after thoroughly checking the script, it appeared that what could be seen in the log was slightly different from what was expected.
It finally turns out that Postscripts on our Service Nodes are not at the same xCAT level as the ones on our Management Node.
As the xCAT packages are on par with the 2.15 expected version, it remains unclear to us why the Postscripts could still look like they are in version 2.14.6 on the Service Nodes...

Anyway: by retrieving the latest, 2.16.1 version of the Postscripts, and making them available on the Service Nodes, it appears that the InfiniBand interfaces are properly configured.
