### ISSUE TITLE
RH84 diskful install of rainier fails

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#6994]
We have  a system with four 1TB nvme cards and no standard diske.

Our RH84 install  fails to find a valid disk. I tracked it down to the /install/autoinst/c643n07rh1 file:

DEVSIZE=$(udevadm info --attribute-walk --name=$entry|grep size | sed -e 's/[^"]*"//' -e 's/"//'|tail -n 1)
        if [ -z "$DEVSIZE" -o $DEVSIZE -lt 262144 ]; then

On the rainier with RH84 the DEVSIZE is incorrectly set:
[root@c643n07rh1 ~]# udevadm info --attribute-walk --name=$entry|grep size
    ATTR{size}=="3125627568"
    ATTRS{sqsize}=="1023"
    
Because sqsize is -lt 262144 we incorrectly decide the disk is not big enough.

I worked around by grepping out sqsize
        DEVSIZE=$(udevadm info --attribute-walk --name=$entry|grep size| grep -v sqsize| sed -e 's/[^"]*"//' -e 's/"//'|tail -n 1)

**Comment by gurevichmark** [comment]
@markprez Which version of xCAT ?

**Comment by markprez** [comment]
Version 2.16.1 (git commit a85566c8be85ee7eec991b0840e53295de686e49, built Wed Nov  4 16:55:06 EST 2020)

**Comment by gurevichmark** [comment]
This problem has been fixed by #6816 in xCAT 2.16.2
