### ISSUE TITLE
Stuck With Package Dependencies for Image

### ISSUE THREAD

**Issue by electronsandstuff** [xcat2/xcat-core#6995]
Hey all, let me know if this is the wrong place to ask.  I came here from the documentation site.

I run an xcat install for an academic cluster.  One management node and 32 compute nodes.  The compute nodes are diskless installs and I have one image that they all boot off of.  Everything has been working great until I tried adding a package to the image today.

The offending package is `devtoolset-7-toolchain` and is only available in the CentOS SCLo RH repository.  I used yumdownloader to get the package and all of its dependencies and then added it to my "other packages" file.  However, now when I generate the image yum fails with an error about selinux.

```
Error: Package: libselinux-devel-2.5-14.1.el7.x86_64 (@centos7.6-x86_64-0)
           Requires: libselinux(x86-64) = 2.5-14.1.el7
           Removing: libselinux-2.5-14.1.el7.x86_64 (@centos7.6-x86_64-0/$releasever)
               libselinux(x86-64) = 2.5-14.1.el7
           Updated By: libselinux-2.5-15.el7.x86_64 (otherpkgs1)
               libselinux(x86-64) = 2.5-15.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
yum invocation failed.
```

I've been trying to get it to work by commenting out other installed packages with no luck.  I guess I have two questions: am I adding the package in the correct way (through by downloading the RPMs) and how should I go about fixing this?  I'm not even sure how to globally update the packages inside my image which seems like it would at least help.

**Comment by gurevichmark** [comment]
It appears you are doing it correctly.

Have you ran `rmimage` before rerunning `genimage` with the added `devtoolset-7-toolchain` ?

**Comment by electronsandstuff** [comment]
Thanks!

Whelp, unfortunately that made things worse.  Now I have two conflicts.

```
Error: Package: libselinux-devel-2.5-14.1.el7.x86_64 (@centos7.6-x86_64-0)
           Requires: libselinux(x86-64) = 2.5-14.1.el7
           Removing: libselinux-2.5-14.1.el7.x86_64 (@centos7.6-x86_64-0/$releasever)
               libselinux(x86-64) = 2.5-14.1.el7
           Updated By: libselinux-2.5-15.el7.x86_64 (otherpkgs1)
               libselinux(x86-64) = 2.5-15.el7
Error: Package: nscd-2.17-260.el7.x86_64 (@centos7.6-x86_64-0/$releasever)
           Requires: glibc = 2.17-260.el7
           Removing: glibc-2.17-260.el7.x86_64 (@centos7.6-x86_64-0/$releasever)
               glibc = 2.17-260.el7
           Updated By: glibc-2.17-324.el7_9.x86_64 (otherpkgs1)
               glibc = 2.17-324.el7_9
```

By commenting out packages, I was able to find out that openssl-devel is what's causing issues with selinux.  I noticed that my management node (where I'm running yumdownloader) is centos 7.7, but the compute image is centos 7.6.  Do you think that could cause the error?

**Comment by gurevichmark** [comment]
You should be able to run `genimage` on centos 7.7 to generate 7.6 image.
Have you tried to install centos 7.6 without any of your `devtoolset-7-toolchain` related packages and then manually installing them ? Note which versions of  `libselinux` and `glibc` are there before and after this manual install.

Can you also show the osimage definition and contents `otherpgslist` file ?

**Comment by electronsandstuff** [comment]
OK, here's my osimage definition.

```
Object name: centos7.6-x86_64-netboot-compute
    exlist=/opt/xcat/share/xcat/netboot/centos/compute.centos7.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.6-x86_64
    osname=Linux
    osvers=centos7.6
    otherpkgdir=/install/post/otherpkgs/centos/x86_64
    otherpkglist=/opt/xcat/share/xcat/netboot/centos/compute_custom_other.centos7.pkglist
    permission=755
    pkgdir=/install/centos7.6/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/centos/compute_custom.centos7.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/centos/compute.centos7_custom.postinstall
    postscripts=ldap,slurm,ntp
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/centos7.6/x86_64/compute
```

and here is my otherpkgs list

```
slurm
slurm-libpmi
slurm-slurmctld
slurm-contribs
slurm-openlava
slurm-slurmd
slurm-devel
slurm-pam_slurm
slurm-slurmdbd
slurm-example-configs
slurm-perlapi
slurm-torque
munge
munge-libs
munge-devel
hwloc-devel
lua-devel
rrdtool-devel
perl-Switch
iperf3
htop
pmix
pmix-devel
ucx
atlas-devel
devtoolset-7-toolchain
```

So, I was able to finally get it to work today.  The issue was that devtoolset-7-toolchain has like 20 out of repo dependencies and so instead of going through the list and manually running yumdownloader on them I ran repotrace to pull them down all at once.  I guess this pulled in things that were already installed (and newer versions of them) and that somehow upset things.  I started a new local repository and just manually downloaded everything and now it seems to work.

Is there a recommended way of downloading the RMP of a package with all of its dependencies that xcat won't have access to during genimage?
