### ISSUE TITLE
/xcatpost not cleared after diskfull installation

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#7002]
Hi!

I just noticed that the `/xcatpost` folder doesn't seem to be cleared after a diskfull installation anymore, despite having `cleanupxcatpost` set to `1` in the `site` table.

This is with xCAT  2.16.2. 

Is this a know issue, or did the required configuration change?

**Comment by gurevichmark** [comment]
@kcgthb What OS are you on ?

Looking at the code, the `cleanupxcatpost` attribute only gets looked at on AIX.
Most likely documentation needs to be updated to state that.

**Comment by kcgthb** [comment]
@gurevichmark I'm running CentOS 7.x.
And indeed, it looks like the only references to `cleanupxcatpost` are in `xCAT/postscripts/xcataixpost` and `xCAT/postscripts/xcatdsklspost`.

Is there any particular reason why this is limited to AIX and diskless installs? Couldn't that be generalized to all deployments?

**Comment by gurevichmark** [comment]
Oh, I see. I missed the references in `xCAT/postscripts/xcatdsklspost`. So it should work on any OS for diskless install.
But I can not find any explanation why it is limited to diskless.

**Comment by kcgthb** [comment]
Do you think it could be added to other deployment methods as well?

**Comment by kcgthb** [comment]
Would something like PR #7003 work for this?

My initial testing seems to indicate that it's working as intended for diskfull CentOS deployments, but I haven't tested other scenarios.

**Comment by gurevichmark** [comment]
@kcgthb I am trying to understand the use case for this.
What is the benefit to cleaning up `/xcatpost` after the postscrips are run ?

**Comment by kcgthb** [comment]
Well, the feature exists for both AIX and diskless deployments, so I guess someone thought it could be beneficial at some point. And since it's there, it's probably better to make it work in all cases, right? :)

But more seriously, all of `/xcatpost` is currently 755, meaning that every user on the node can read all of its contents. Post-installation scripts may contain sensitive information (such as credentials, tokens or passwords) and keeping that information world-readable on the node after it's been installed is a security risk.
In particular, sone of our postscripts need access to the IPMI credentials stored in the `passwd` table, so we have to dump those credentials in the template file so they could be accessible from the postscripts (worse than that, we actually have to dump the whole `passwd` table, cf. #6925). So cleaning up the `/xcatpost` directory after deployment is necessary to remove world-readable credentials from the local disk.

Hope this makes sense. Thanks!

**Comment by TheWitness** [comment]
I would suggest that this directory only be removed if the post activities return a zero exit code.  I've used this directory to test post scripts when there are failures.  It's quite convenient.  I think changing the permissions is more critical though.  That could be a big deal as you said @kcgthb
