### ISSUE TITLE
On RHEL8 stateless network post appears to rely on `NetworkManager`, but `NetworkManager` is not included by default

### ISSUE THREAD

**Issue by TheWitness** [xcat2/xcat-core#7015]
Ran across an issue where I took the same `pkglist` from a diskful image and attempted to use on the diskless image.  What happened is that the network would not come up.  Upon further inspection, I found that the system was half attempting to use the old SystemV network services, but they were not entirely installed.

As a workaround, I added `NetworkManager*` to the pkglist, and after that, the Network services came up as expected.

**Comment by gurevichmark** [comment]
@TheWitness Which diskful `pkglist` did you use. Did it contain `@minimal-environment` ?

The `pkglist` for both diskful (`/opt/xcat/share/xcat/install/rh/compute.rhels8.pkglist`)  and diskless (`/opt/xcat/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist`)  images should contain `minimal-environment` group, which contains `NetworkManager`

**Comment by TheWitness** [comment]
Let's close this one.  The customer was using a custom pkglist.
