### ISSUE TITLE
Could not boot: Error 0x7f048281 (http://ipxe.org/7f048281)

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#7036]
Hi!

We're running xCAT 2.16.2 (with xnba-undi-1.20.1-0 and elilo-xcat-3.14-6), and we recently started to see situations where brand new servers (still undiscovered, with their factory UEFI boot settings) were failing to boot the discovery image.

The error is:
```
ELILO v3.14 for EFI/x86_64
util.c(line 134):waitkey WaitForEvent failed Unsupported

ELILO boot: util.c(line 134):waitkey WaitForEvent failed Unsupported
Could not boot: Error 0x7f048281 (http://ipxe.org/7f048281)
Could not boot image: Error 0x7f048281 (http://ipxe.org/7f048281)
```

![rpviewer (3)](https://user-images.githubusercontent.com/186807/133666076-3d81ce1c-d01a-46e3-99a5-817be9b84a4b.png)

We tried previous versions (`xnba-undi-1.0.3-131028.noarch`), but then the node crashes during the PXE boot phase, with the following trace:

![rpviewer (2)](https://user-images.githubusercontent.com/186807/133664171-686470a3-afdf-476e-9935-5f3bc3e7a6c1.png)

This problem seems to already have been reported on the mailing-list: https://www.mail-archive.com/xcat-user@lists.sourceforge.net/msg08181.html but without any clear resolution.

Any idea on how to fix this?
Thanks!

**Comment by gurevichmark** [comment]
@kcgthb  can you try the following:

In file `/opt/xcat//lib/perl/xCAT_plugin/dhcp.pm` change line 2729 or thereabouts to remove ".uefi":

From:  
`push @netent, " filename = \"http://$tftp:$httpport/tftpboot/xcat/xnba/nets/" . $net . "_" . $maskbits . ".uefi\";\n";`

To: 
`push @netent, " filename = \"http://$tftp:$httpport/tftpboot/xcat/xnba/nets/" . $net . "_" . $maskbits . "\";\n";`

Then run `makedhcp -n` and `makedhcp -a`. That should generate a new `/etc/dhcp/dhcpd.conf` which will send 
`http://<xCAT MN>:80/tftpboot/xcat/xnba/nets/<network>` instead of `http://<xCAT MN>:80/tftpboot/xcat/xnba/nets/<network>.uefi`
My assumption that you server matches this line in `/etc/dhcp/dhcpd.conf`:
`else if option user-class-identifier = "xNBA" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent`

Finally, remove the node's mac and try another normal discovery.

Also can you show what `/tftpboot/xcat/xnba/nets/<network>` file contains on your management node ?

**Comment by kcgthb** [comment]
Thanks @gurevichmark !

I tried that, it progressed a bit further and managed to load `genesis.kernel` and `genesis.fs`, but then it hangs there:

![rpviewer (4)](https://user-images.githubusercontent.com/186807/133679588-7655095d-764a-4dff-abb4-64cd3dde6929.png)

After a power cycle, the server loaded the discovery kernel and crashed (sorry the top of the stack is missing):

![rpviewer (5)](https://user-images.githubusercontent.com/186807/133681346-f0968e39-7c5d-46aa-8bee-e76c94c8392e.png)




Here are the contents of the `/tftpboot/xcat/xnba/nets/10.16.0.0_12` file:
```
#!gpxe
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/genesis.kernel.x86_64 quiet xcatd=10.16.0.1:3001  BOOTIF=01-${netX/machyp}
imgfetch -n nbfs http://${next-server}:80/tftpboot/xcat/genesis.fs.x86_64.gz
imgload kernel
imgexec kernel
```
`/tftpboot/xcat/xnba/nets/10.16.0.0_12.uefi` had this:
```
#!gpxe
chain http://${next-server}:80/tftpboot/xcat/elilo-x64.efi -C /tftpboot/xcat/xnba/nets/10.16.0.0_12.elilo
```

**Comment by gurevichmark** [comment]
Try replacing the contents of `/tftpboot/xcat/xnba/nets/10.16.0.0_12` file with:
```
#!gpxe
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/genesis.kernel.x86_64
imgload kernel
imgargs kernel quiet console=tty0 console=ttyS0,115200 xcatd=10.16.0.1:3001 BOOTIF=01-${netX/machyp}
imgfetch -n initrd http://${next-server}:80/tftpboot/xcat/genesis.fs.x86_64.gz
imgexec kernel
```
Then, remove the node's mac and try another normal discovery.

**Comment by kcgthb** [comment]
Thanks for the suggestion. Unfortunately, same result: the kernel crashes with the exact same [stack](https://user-images.githubusercontent.com/186807/133681346-f0968e39-7c5d-46aa-8bee-e76c94c8392e.png) :(

**Comment by kcgthb** [comment]
Well, I guess it's the iPXE binary again... I was able to resolve the problem following the same steps outlined in https://github.com/xcat2/xNBA/issues/2 and summarized by @Hoeze in https://github.com/Hoeze/ipxe to update the `xnba.efi` image with iPXE v1.21.1.

Here are the steps I followed to compile a new iPXE version:
```
$ git clone https://github.com/ipxe/ipxe.git
$ cd ipxe
$ git checkout v1.21.1
$ # download the XCAT customization patch from Hoeze's repo
$ wget https://github.com/Hoeze/ipxe/commit/d6b2d798221a2d03dfcba05a8866ba17b3dba16c.patch
$ patch -p1 -i d6b2d798221a2d03dfcba05a8866ba17b3dba16c.patch
$ cd src
$ make -j bin-x86_64-efi/ipxe.efi
```
and then to install the updated version:
```
# cp bin-x86_64-efi/ipxe.efi /tftpboot/xcat/xnba_1.21.1.efi
# cd /tftpboot/xcat
# chmod 644 xnba_1.21.1.efi
# mv xnba.efi xnba_1.0.3.efi
# ln -s xnba_1.21.1.efi xnba.efi
```

And then the same undiscovered server boots the genesis kernel right away.

Will it be possible to update iPXE to 1.21.1 in the next xCAT release?
Thanks!

**Comment by gurevichmark** [comment]
@kcgthb I have placed an updated version of `xnba-undi` based on iPXE 1.21.1 at https://www.xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xnba-undi-1.21.1-1.noarch.rpm
Can you verify it works for you ? If it does we can publish it for the next xCAT release.

**Comment by kcgthb** [comment]
Hi @gurevichmark 

Thanks for packaging it! I gave it a quick test (unknown UEFI host discovery) and it looks like it's working fine. So it looks good to me for inclusion in the next release.

**Comment by gurevichmark** [comment]
An updated version of `xnba-undi` based on iPXE 1.21.1 currently available at https://www.xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xnba-undi-1.21.1-1.noarch.rpm will be published with next xCAT release.
