### ISSUE TITLE
[Security] xCAT REST API non-root user does not work as expected

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/xcat-core#7049]
Hi,

it looks like there is a security issue with the xCAT REST API. If a non-root API user is used, the commands are still executed as root user.

### Steps to reproduce

1. Set-up HTTPS and SSL certificate as described https://xcat-docs.readthedocs.io/en/latest/advanced/restapi/restapi_setup/restapi_setup.html
2. Create a non-root API user in policy table: `mkdef -t policy name=test rule=allow`
3. Add credentials for this user in passwd table: `chtab key=xcat passwd.username=test passwd.password=test`
4. Do **not** create a local user
```
[root@obi-xcat ~]# grep test /etc/passwd
[root@obi-xcat ~]# 
``` 
5. Execute some xdsh command via REST API and check UID:
```
curl -k -X POST 'https://10.0.0.1/xcatws/nodes/login5/nodeshell?userName=test&userPW=test' -H Content-Type:application/json --data '{"command":["id"]}'
{"login5":[" uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023"]}
```

### Issue

As you can see you are still able to execute commands as root via the API even though, the unix user `test` does not exits. According to the [documentation](https://xcat-docs.readthedocs.io/en/latest/advanced/restapi/restapi_setup/restapi_setup.html#use-non-root-account) I would expect all commands to be executed as `test` user. The documentation says you should create the `test` user, but even without this, the commands are simply executed as root. I thought it was a security feature to use a non-root user, but with this behaviour I think the opposite is the case. Maybe I'm misunderstanding the documentation?

**Comment by besawn** [comment]
@gurevichmark Can you investigate this when you have time?

**Comment by gurevichmark** [comment]
The problem appears to be in the way `userName` from the REST call gets passed to `xdsh`. The REST call `curl -k -X POST 'https://10.0.0.1/xcatws/nodes/login5/nodeshell?userName=test&userPW=test'  --data '{"command":["id"]}` should get translated into `xdsh login5 --user test id`.

The `xdsh.pm->process_request()` get the `userName` from `$request->{username}->[0]` and stores it in `$ENV{DSH_FROM_USERID}`. Later `DSHCLI.pm->parse_and_run_dsh()` builds a `xdsh` command to execute, but it only looks at `$ENV{DSH_FROM_USERID}` if processing `ssh-setup` or `-K` option. For all other commands `$ENV{DSH_TO_USERID}` to pass to `xdsh` for `--user` flag.

The solution should either make `xdsh.pm->process_request()` to store `$request->{username}->[0]` in `$ENV{DSH_TO_USERID}`. OR make `DSHCLI.pm->parse_and_run_dsh()` use `$ENV{DSH_FROM_USERID}` when processing all commnds, not just `ssh-setup` or `-K` option.
