### ISSUE TITLE
[Customer]Advanced Recovery BMC Tool to tunnel into BMC via IPv6 from an xCAT EMS

### ISSUE THREAD

**Issue by david-shapiro** [xcat2/xcat-core#707]
Advanced Recovery BMC Tool to tunnel into BMC via IPv6 from an xCAT EMS
--------------------------------------------------------------------------
Once a node is defined into xCAT, c712f1n01, ( for this example )
can determine the bound MAC address of the associated BMC
via 'lsdef' and 'tabdump' commands as shown:

lsdef -o c712f1n01  -i bmc
Object name: c712f1n01
    bmc=c712f1bmc01
"c712f1bmc01",,"70:e2:84:14:01:aa",,

tabdump  -w 'node==c712f1bmc01' mac
#node,interface,mac,comments,disable
"c712f1bmc01",,"70:e2:84:14:01:aa",,

This shows that the MAC address of the BMC is
70:e2:84:14:01:aa

The following transformations are well known and IPv6
IPv6 calculators appear on the internet.
However, in the interest of xCAT producing an advanced tool
I go thru the steps to convert the IPv4 MAC into a pingable IPv6 IP address:
[1} Rewrite IPv6 BMC address with spaces (instead of colons)
70 e2 84 14 01 aa
[2] Insert FF FE into the fixed location as shown
70 e2 84 ff fe 14 01 aa
[3] Write the first two bytes to bits : 7 -> 0111  and 0 -> 0000
0111 0000 e2 84 ff fe 14 01 aa
[4] Invert the 7th bit
0111 0010 e2 84 ff fe 14 01 aa
[5] Convert the leading doubleword to hex; that is 0111 -> 7 and 0010 -> 2 . Result is 72
72 e2 84 ff fe 14 01 aa
[6] Insert IPv6 style colons
72e2:84ff:fe14:01aa
[7] Prepend the link-local prefix fe80:: to form the completed IPv6 address
fe80::72e2:84ff:fe14:01aa
[8] Attempt to ping the IPv6 address along the private interface (enP2p1s0f1)

[root@EMS]# ping6 -w 1 -c 1 -I enP2p1s0f1 fe80::72e2:84ff:fe14:01aa
PING fe80::72e2:84ff:fe14:01aa(fe80::72e2:84ff:fe14:1aa) from fe80::9abe:94ff:fe00:db89 enP2p1s0f1: 56 data bytes
64 bytes from fe80::72e2:84ff:fe14:1aa: icmp_seq=1 ttl=64 time=0.266 ms

--- fe80::72e2:84ff:fe14:01aa ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.266/0.266/0.266/0.000 ms

Advantages of creating an advanced BMC recovery tool using IPv6 are
[A] Once the IPv4 BMC address is discovered the conversion to IPv6 is mechanical
[B] No routing nor ROUTE statements needed
[C] DHCP not required
[D] IPv6 address is as persistent as a MAC address. Indeed IPv6 MAC=IPv6 IP

**Comment by markprez** [comment]
Addtional information: We have used IPv6 to recover a BMC that lost connectivity with the ipv4 address.
"rpower node status" times out and ping of the bmc fails.
It does not happen frequently when it happens this is a way to try to get control of the server.
Not all systems will have the BMC mac in xcat but may be able to recover it from the dhcp.leases file if the IP address for the node bmc object is the last current. 
https://sourceforge.net/p/ipmitool/patches/81/ shows an example of using the IPv6 address with ipmitool.

**Comment by daniceexi** [comment]
Move this feature to next release.

**Comment by whowutwut** [comment]
There's actually issues in RHEL and Ubuntu where the inteterface name is case sensitive so we're not able to ssh -6 ... let's close this now and revisit this in the future.
