### ISSUE TITLE
Travis CI actions no longer running

### ISSUE THREAD

**Issue by asdorsey** [xcat2/xcat-core#7070]
While working on PR #7064 I noticed that the Travis CI check wasn't running.  It looks like they recently migrated from using travis-ci.org to travis-ci.com.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by besawn** [comment]
We noticed this issue awhile ago... we just haven't come up with a good solution yet. Migrating to travis-ci.com is possible, but travis-ci.com is not free and will require a new source of funding.

Options that have been/are being considered:
- Move to travis-ci.com - will require new funding of some kind
- Migrate to a private CI tool - would prefer to keep the CI results public for ease of use by contributors
- Migrate to public IBM CI tool - may be a possible

**Comment by kcgthb** [comment]
Have you considered using [GitHub Actions](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration)? 
That seems to be becoming the _de facto_ standard for CI.

**Comment by gurevichmark** [comment]
GitHub Action added by #7214
