### ISSUE TITLE
Postscript `mlnxofed_ib_install` Fails to Properly Identify OS Image Architecture under RHEL 8

### ISSUE THREAD

**Issue by nicolas-tallet** [xcat2/xcat-core#7074]
We are facing an issue with the `mlnxofed_ib_install` Postscript when trying to generate a stateless RHEL 8-based OS Image.

The Postscript uses a specific function named `hack_uname` in order to identify the architecture of the OS Image:
```
function hack_uname()
{
    mv "$1/bin/uname" "$1/bin/uname.save"
    cat <<-EOF >"$1/bin/uname"
                #!/bin/sh
                case "\$1" in
                "-m")
                        ARCH="\$(dpkg --print-architecture 2>/dev/null || rpm -q kernel-\$("\$0" -r) --qf '%{arch}' 2>/dev/null)"
                        case "\$ARCH" in
                        "amd64")
                                ARCH="x86_64"
                                ;;
                        "ppc64el")
                                ARCH="ppc64le"
                                ;;
                        esac
                        echo "\$ARCH"
                        ;;
                "-r")
                        cd /lib/modules && for d in * ; do : ; done && echo \$d
                        ;;
                "-s"|"")
                        echo "Linux"
                        ;;
                esac
                exit 0
                EOF

    chmod 0755 "$1/bin/uname"
}
```

However, under RHEL 8, on the contrary to RHEL 7.6, the `/lib/modules` directory contains multiple subfolders, which seems to make the Kernel version detection fail:
```
$ chroot /install/netboot/compute/21.11.1/rootimg
$ ls -l
total 24
drwxr-xr-x 7 root root 4096 Nov 22 16:51 4.18.0-305.19.1.el8_4.ppc64le
lrwxrwxrwx 1 root root   11 Apr 29  2021 kabi-current -> kabi-rhel84
drwxr-xr-x 2 root root 4096 Nov 22 16:12 kabi-rhel80
drwxr-xr-x 2 root root 4096 Nov 22 16:12 kabi-rhel81
drwxr-xr-x 2 root root 4096 Nov 22 16:12 kabi-rhel82
drwxr-xr-x 2 root root 4096 Nov 22 16:12 kabi-rhel83
drwxr-xr-x 2 root root 4096 Nov 22 16:12 kabi-rhel84
$ cd /lib/modules && for d in * ; do : ; done && echo $d
kabi-rhel84
```
(while the above command should return: `4.18.0-305.19.1.el8_4.ppc64le`)

Are we missing something?

**Comment by besawn** [comment]
@nicolas-tallet What version of xCAT are you using? I think this issue is fixed in the latest version of `mlnxofed_ib_install`.

Can you try the latest version of `mlnxofed_ib_install` from here:
https://github.com/xcat2/xcat-core/blob/cacd973043295c6235d47dcfc970fa8ac8808818/xCAT-server/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install

and see if it resolves your issue?

**Comment by nicolas-tallet** [comment]
We are running version 2.16.2 (we are planning to upgrade to version 2.16.3 but haven't done so yet).

Indeed, I can see that the Postscript has been updated in 2019 in order to cope with such a situation. That will definitely fix our issue.

Not clear to me why the Postscript we are using in our environment is so outdated. Will do a comprehensive check to see if other Postscripts need an update as this one.

**Comment by besawn** [comment]
Note that the `mlnxofed_ib_install` script ships in the directory `/opt/xcat/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install`, but to make use of it requires copying it into `/install/postscripts`. It may just be an issue of needing to refresh the active copy with the copy from the shipped location.

**Comment by nicolas-tallet** [comment]
Thanks a lot for the tip @besawn , this is a trick I had missed.
