### ISSUE TITLE
rpower command fails with ERROR: Unauthorized name but ipmitool command succeeds

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#7079]
running:
`rpower <CN> reset `

gives error:
`<CN>: [<MN>]: Error: ERROR: Unauthorized name`

But running :
`ipmitool -v -I lanplus -H <CN BMC IP> -U <username> -P <passwd> -k gkey mc info`

returns  the correct response.  

There are 2 issues

1. xCAT doesn't seem to be using the BMC username and password. The UN and PW were put into the passwd tab using the "ipmi" key. The username and password were also added to the ipmi tab with the bmc hostname . Same error with both methods.
2. xCAT doesn't seem to have a provision to enable using the -k switch of ipmitool which our hardware requires. Without this switch, ipmitool returns
`> RAKP 4 message has invalid integrity check value `

Hardware is ATCA blades
OS is RHEL 8.4
xCAT version is 2.16.2

**Comment by gurevichmark** [comment]
@kjhee43 Is it possible your <CN> node definition has its own `bmcpassword` or `bmcusername` attributes defined ?

**Comment by kjhee43** [comment]
> @kjhee43 Is it possible your node definition has its own `bmcpassword` or `bmcusername` attributes defined ? Can you show your node definition ?

@gurevichmark we tried putting a bmcusername and bmcpassword in theipmi table first. When that didn't work, we cleared that and put an ipmi key in the passwd table. Didn't work either.

**Comment by gurevichmark** [comment]
`bmcpassword` and `bmcusername` attributes, if defined for <CN>, would overwrite definitions in `ipmi` or `passwd` tables.

Most likely, I think, `rpower` command fails because xCAT does not use `-k` flag, so we can not connect to the BMC.

Can you enable debug with `chdef -t site clustersite xcatdebugmode=1` and run the `rpower` command again. It might show in more detail where `Unauthorized name` is returned.

**Comment by kjhee43** [comment]
@gurevichmark 

> `bmcpassword` and `bmcusername` attributes, if defined for CN, would overwrite definitions in `ipmi` or `passwd` tables.

Dont bmcpassword and bmcusername come from the ipmi tables? Where else would they be defined? According to the docs, attributes in the impi table take precedence over attributes in the passwd table, but those appear to be the only 2 places to define them

> 
> Most likely, I think, `rpower` command fails because xCAT does not use `-k` flag, so we can not connect to the BMC.

I don't think this is the case. When the - flag is omitted in my ipmitool command, a completely different error is thrown.

> 
> Can you enable debug with `chdef -t site clustersite xcatdebugmode=1` and run the `rpower` command again. It might show in more detail where `Unauthorized name` is returned.

I enabled the flag, but no other debug information was output.

**Comment by gurevichmark** [comment]
> Dont bmcpassword and bmcusername come from the ipmi tables? Where else would they be defined? According to the docs, attributes in the impi table take precedence over attributes in the passwd table, but those appear to be the only 2 places to define them

Yes, you are right, so if you do `lsdef <CN>` you can see the expected `bmcpassword` and `bmcusername` from `ipmi` table ?
Have you tried purposely setting `bmcusername` to something invalid and running `power` ? Do you get the same `Unauthorized name` error ?

**Comment by kjhee43** [comment]
@gurevichmark , thanks for the help. We determined this issue is a combination of our one-off hardware and needing a more custom plugin to get it working. Thank you for the support. Closing.
