### ISSUE TITLE
[Customer] confignics -s, sets up config files, but interface loses IP after dhcp lease expire

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#708]
Hi,

I have started to use `confignics -s` as a way to configure the install nic. But as the lease of the IP still exists in DHCP on the server and on the client, it is still not configured on the live system to be static. When the lease expires, it no longer grabs the IP anymore, and lose all connectivity. We then have to login via `rcons`, or reboot the machines to get the network on the machine back up again.

Maybe we need to setup the `configeth` such that the `bool_restart_flag` is set to 1, if we are configuring the install nic. It probably makes sense with the section that restarts the nic, that we do a ifdown before we do a ifup, to cover all scenarios, such as this one as well.

I will test this later, in the next few days, and see if I can do a PR

**Comment by arif-ali** [comment]
setting bool_restart_flag to 1, did not resolve the problem

I also amended the last part of `configeth` to add ifdown, before the ifup, but still had the dhclient running on the interface.
```
    #restart the nic
    if [ $bool_restart_flag -eq 1 ];then
        if [ "$str_os_type" = "debian" ];then
            ifup -a -i /etc/network/interfaces.d/$str_nic_name
        else
            echo "bring up ip"
            ifdown $str_nic_name
            ifup $str_nic_name
        fi
    fi
```

Any ideas on this would be grateful. The only other thing I think of, is to do a `service network restart`, or check for dhclint processes, and kill it for the process?

**Comment by daniceexi** [comment]
@arif-ali Someone mentioned it might be helpful that the nic should be stopped before change the configuration file.

**Comment by bybai** [comment]
I think you can check for dhclient processes.   I am curious why ifdown/ifup cannot work here.

**Comment by arif-ali** [comment]
@daniceexi, I would have suspected that by doing an ifdown, would in essence stop the interface? which is why I went that route

@bybai As you can understand, I have been tested this for almost 2 weeks, and that was the conclusion, I came to, that the ifdown/ifup didn't work on the interface. So would it make sense, that I kill the dhclient service, that is attached to the interface, as part of the `configeths` script, test, and submit that as a PR?

**Comment by arif-ali** [comment]
What's the suggestion here then, how could we resolve this, do we look for a dhclient process, and kill it, if it is the installnic, an then configure the interfaces?

@daniceexi, how do you suggest stopping the nic, in your previous comment, wouldn't ifdown and ifup do this?

**Comment by daniceexi** [comment]
@arif-ali Yes, using the ifdown to stop the nic before changing the nic configuration file. 
It was reasonable that ifdown did not stop the dhclient since the nic configuration file has been changed to static in your scenario.

**Comment by whowutwut** [comment]
@arif-ali  which OS are you using in your environment?  When the node cannot get the environment and you run dhclient, does it get the IP address or does the dhcp server say "no free leases"?  I think we are also seeing something similar in our environment where nodes are losing IP address.. I will try and debug.

**Comment by arif-ali** [comment]
OS: rhels7.2
arch: ppc64le

@daniceexi thanks, that makes sense, I will update the script, to see if we do a if down first, change the config, and then do the ifup, and see if that resolves the problem

@whowutwut dhclient would work, that's not the problem, running `confignics -s` sets up the static configuration in `/etc/sysconfig/network-scripts/` but the changes do not actually get applied. The suggestion from @daniceexi may work here

A similar issue was reported on the IRC channel as well, that the person added MTU=9000 to the installnic, but didn't apply it, but rebooting the node, the config was applied. I think these are similar issues, where, the config file is written, but it is not applied.
