### ISSUE TITLE
 Rocky 8.5: makentp replaces /dev/null with a regular file 

### ISSUE THREAD

**Issue by ruixingw** [xcat2/xcat-core#7091]
Hello, it seems that with xcat 2.16.3 on Rocky 8.5, `makentp` wrongly replaces `/dev/null` with a regular file. 
```
[root@localhost ~]# ls -l /dev/null
crw-r--r--. 1 root root 1, 3 Jan 15 01:22 /dev/null
[root@localhost ~]# makentp
configuring management node: master.
Will configure chronyd instead.
Calling ... /install/postscripts/setupntp
Daemon chronyd configured.
[root@localhost ~]# ls -l /dev/null
-rw-r--r--. 1 root root 7 Jan 15 01:22 /dev/null
```
can you check where's the problem?

P.S.: A fix for those who also met this problem: `rm /dev/null; mknod /dev/null c 1 3; chmod 666 /dev/null`

**Comment by Obihoernchen** [comment]
Fixed in upstream already https://github.com/xcat2/xcat-core/commit/82801016ac95898cd4fb8109dc233af995ec7291

**Comment by ruixingw** [comment]
Thanks for pointing that out. I've modified `/install/postscripts/setupntp` accordingly and the problem is gone. I will close this.
