### ISSUE TITLE
RHEL8.5 updatenode -F failed on random nodes

### ISSUE THREAD

**Issue by URZ-HD** [xcat2/xcat-core#7118]
Since we are using RHEL8.5 on our xCAT MN, we are seeing the problem, that `updatenode -F` will fail on some nodes, if we are using a xCAT group like `updatenode -F lsdf02`

```
[root@xcatmn1 otherpkgs]# lsdef -t group lsdf02 -i members
Object name: lsdf02
    members=lsdf02e1,lsdf02e2,lsdf02e3,lsdf02e4,lsdf02e6,lsdf02e7,lsdf02gw1,lsdf02gw2,lsdf02gw3,lsdf02gw4,lsdf02gw5,lsdf02k2,lsdf02n14,lsdf02n15,lsdf02n16,lsdf02n17,lsdf02n18,lsdf02n19,lsdf02n20,lsdf02n21,lsdf02n22,lsdf02n23,necadm1,necadm2,q10i04,q10i06,y23e11,y23e12,y23i08,y25a01,y25a02,y25a03,y25a04,y25n01,y25n02

```
The failing nodes are random and changes on every run:

```
[root@xcatmn1]# updatenode lsdf02 -F
File synchronization failed for nodes: "lsdf02gw5"
[root@xcatmn1]# updatenode lsdf02 -F
File synchronization failed for nodes: "lsdf02e3,lsdf02gw1"
[root@xcatmn1]# updatenode lsdf02 -F
File synchronization failed for nodes: "lsdf02e1"
```
Using `-V` does not show any usefull hints (even not with xcatdebugmode=2):
```
[root@xcatmn1 otherpkgs]# updatenode lsdf02 -F -V
Running command on xcatmn1: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on xcatmn1: chmod -R a+r /install/postscripts 2>&1

  xcatmn1: Internal call command: xdcp lsdf02k2 --nodestatus -F /install/custom/syncfiles/recovery.synclist -T
Running internal xCAT command: xdcp ... 

Running command on xcatmn1: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

TRACE:Default context is XCAT.
TRACE:Fanout Value is 64.
TRACE:Timeout Value is .
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_lsdf02k2
lsdf02k2: + /usr/bin/ssh lsdf02k2 '/bin/mkdir -p /usr/local'
lsdf02k2: + /usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz -X /install/custom/syncfiles/all/usr/local/sbin/self-healing lsdf02k2:/usr/local/bin
  xcatmn1: Internal call command: xdcp lsdf02e1,lsdf02e2,lsdf02e3,lsdf02e4,lsdf02e6,lsdf02e7,lsdf02gw1,lsdf02gw2,lsdf02gw3,lsdf02gw4,lsdf02gw5,lsdf02n14,lsdf02n15,lsdf02n16,lsdf02n17,lsdf02n18,lsdf02n19,lsdf02n20,lsdf02n21,lsdf02n22,lsdf02n23,necadm1,necadm2,q10i04,q10i06,y23e11,y23e12,y23i08,y25a01,y25a02,y25a03,y25a04,y25n01,y25n02 --nodestatus -F /install/custom/syncfiles/lsdf02.synclist -T
Running internal xCAT command: xdcp ... 

Running command on xcatmn1: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

TRACE:Default context is XCAT.
TRACE:Fanout Value is 64.
TRACE:Timeout Value is .
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_lsdf02e1
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_lsdf02e2
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_lsdf02e3
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_lsdf02e4
 [...]
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_y25a04
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_y25n01
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_y25n02
File synchronization failed for nodes: "lsdf02e4"
```

Because the problem only occurs if more than one node will be used, i tried to increase the timeout via `-t 20` but this makes no difference. Single-Node Run on `updatenode -F` works as expected.

Our xCAT Version:
```
[root@xcatmn1 otherpkgs]# xcatconfig -v
Version 2.16.3 (git commit d6c76ae5f66566409c3416c0836660e655632194, built Wed Nov 10 09:58:20 EST 2021)
```

Because the single-node version and also the manual rsync calls works for all nodes, i'm not sure how to debug this problem any further ...

best,
Sven

**Comment by gurevichmark** [comment]
@URZ-HD 

Is this a hierarchical environment with service nodes or flat ?
Have you tried using a list of individual nodes for `updatenode` command instead of group name ?

**Comment by URZ-HD** [comment]
Yes, if i use the nodenames directly (and also reduce the number of nodes), the same error occured (randomly)

```
updatenode lsdf02e1,lsdf02e2,lsdf02e3,lsdf02gw1 -F
File synchronization failed for nodes: "lsdf02e1"
```

Currently we use only the MN, and no SNs in our cluster

**Comment by URZ-HD** [comment]
I've just take a close look on the client side ... an the problem does not occur on RHEL8.5 client (stateless):

```
[root@xcatmn1 ~]# updatenode o03c01,o03c02,p01c01,p01c02,p02c01,p02c02,p03c01 -F
File synchronization has completed for nodes: "p01c01,o03c01,p02c02,p02c01,o03c02,p01c02,p03c01"
```

So currently the problem showed up only with RHEL7.9/CentOS7.7 clients (statefull). But i've no idea why this have an impact on the rsync calls ...

**Comment by gurevichmark** [comment]
@URZ-HD Can you show the contents of your synclist file? Are the files there very large ?

Also, after you get a failure when running `updatenode -F` for the group, 
can you run the `/bin/sh -c /tmp/rsync_<failed node name>` for the node that failed ?

**Comment by gurevichmark** [comment]
@URZ-HD 
Have you tried commenting out all entries from `EXECUTE` section ?
Perhaps the problem is running one of those `.post` scripts on the RHEL7.9/CentOS7.7 client and not the copying of the files ?

**Comment by URZ-HD** [comment]
@gurevichmark When i disable all EXECUTE `.post` Files the problem could not be solved.
On the nodes itself, there are also no error messages in the logs

**Comment by URZ-HD** [comment]
@gurevichmark Thanks for the hint about the logfile ... 

The failed nodes showing these errors:

```
2022/03/04 13:33:46 [3523117] building file list
2022/03/04 13:33:46 [3523117] symlink has no referent: "/install/custom/syncfiles/export/usr/local/bin/fpart"
2022/03/04 13:33:46 [3523117] symlink has no referent: "/install/custom/syncfiles/export/usr/local/bin/kdirstat-cache-writer"
2022/03/04 13:33:46 [3523117] symlink has no referent: "/install/custom/syncfiles/export/usr/local/sbin/afmmount"
2022/03/04 13:33:46 [3523117] symlink has no referent: "/install/custom/syncfiles/export/usr/local/sbin/afmumount"
2022/03/04 13:33:46 [3523117] symlink has no referent: "/install/custom/syncfiles/export/usr/local/sbin/compile_filelist"
2022/03/04 13:33:46 [3523117] .d..t...... etc/
2022/03/04 13:33:46 [3523117] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```

Because the symlinks are not valid on the MN, but on the provisioned nodes, and because rsync uses -L instead of -l option the errors seems to be correct. If i remove the invalid symlinks, the `updatenode` is successfull.

But i'm wondering why `updatenode` fail only randomly on some nodes, even if the symlinks are not vaild in all cases ...

thanks,
Sven

**Comment by gurevichmark** [comment]
Yes, that is strange. If you run `updatenode` against a single node, not errors appear in log file ?
