### ISSUE TITLE
Compute node deployment failed in the new xCAT environment

### ISSUE THREAD

**Issue by bkbcm** [xcat2/xcat-core#7132]
Hi,

This is my first time setting up xCAT. I went through the installation process and completed it per the online install guides. I started the diskful OS deployment for the computing node and it failed to deploy. The installation dropped into Dracut Emergency shell. I have exhausted my troubleshoot skill and I couldn't figure out where the problem lies. Can you please advise or help pointing me in the right direction?

Thank you most kindly for your help and your time.

Regards,
BK

1. Here's the out from the console:

>>Checking Media Presence......
>>Media Present......
 Downloading NBP file...
  Succeed to download NBP file.
xNBA initialising devices...ok
xCAT Network Boot Agent
xNBA 1.21.1-1 -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE EFI Menu
net0: 7c:d3:0a:e1:86:30 using NII on NII-0000:09:00.0 (Ethernet) [open]
  [Link:down, TX:0 TXE:1 RX:0 RXE:0]
  [Link status: Unknown (http://ipxe.org/1a086194)]
  [TXE: 1 x "Network unreachable (http://ipxe.org/28086090)"]
Configuring (net0 7c:d3:0a:e1:86:30)...... ok
net0: 172.17.1.18/255.255.255.0 gw 172.17.1.33
net0: fe80::7ed3:aff:fee1:8630/64
Next server: 172.17.1.66
Filename: http://172.17.1.66:80/tftpboot/xcat/xnba/nodes/cmp18.uefi
http://172.17.1.66:80/tftpboot/xcat/xnba/nodes/cmp18.uefi... ok
cmp18.uefi : 515 bytes [script]
http://172.17.1.66:80/tftpboot/xcat/osimage/rhels7.2-x86_64-install-compute/vmlinuz... ok
http://172.17.1.66:80/tftpboot/xcat/osimage/rhels7.2-x86_64-install-compute/initrd.img... ok
[    0.000000] Detected CPU family 6 model 85
[    0.000000] Warning: Intel CPU model - this hardware has not undergone testing by Red Hat and might not be certified. Please consult https://hardware.redhat.com for certified hardware.
[    0.000000] tsc: Fast TSC calibration failed
[    6.557610] i8042: No controller found
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
GGG[   11.903629] dracut-initqueue[1721]: cat: /sys/class/net/eno1/carrier: Invalid argument
<...snip...>
[   42.633594] dracut-initqueue[1721]: cat: /sys/class/net/eno1/carrier: Invalid argument
[   42.735058] dracut-initqueue[1721]: Warning: No carrier detected on interface eno1
[  168.173490] dracut-initqueue[1721]: Warning: dracut-initqueue timeout - starting timeout scripts
<...snip...>
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
GGG[   11.903629] dracut-initqueue[1721]: cat: /sys/class/net/eno1/carrier: Invalid argument
<...snip...>
[   42.633594] dracut-initqueue[1721]: cat: /sys/class/net/eno1/carrier: Invalid argument
[   42.735058] dracut-initqueue[1721]: Warning: No carrier detected on interface eno1
[  168.173490] dracut-initqueue[1721]: Warning: dracut-initqueue timeout - starting timeout scripts
<...snip...>
[  229.972738] dracut-initqueue[1721]: Warning: Could not boot.
[  234.433850] dracut-initqueue[1721]: Warning: /dev/root does not exist
         Starting Dracut Emergency Shell...
Warning: /dev/root does not exist
Generating "/run/initramfs/rdsosreport.txt"
Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.
dracut:/# exit
logout
[ 1847.853600] dracut-initqueue[1721]: Warning: Not all disks have been found.
[ 1847.863540] dracut-initqueue[1721]: Warning: You might want to regenerate your initramfs.
         Starting Switch Root...
[FAILED] Failed to start Switch Root.
See 'systemctl status initrd-switch-root.service' for details.
         Starting Emergency Shell...
[  OK  ] Started Show Plymouth Boot Screen.
Warning: /dev/root does not exist
Generating "/run/initramfs/rdsosreport.txt"
Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.
:/# 

2. Below is the information on my setup.

# lsxcatd -a
Version 2.16.3 (git commit d6c76ae5f66566409c3416c0836660e655632194, built Wed Nov 10 09:58:20 EST 2021)
This is a Management Node
dbengine=SQLite

# lsdef cmp18
Object name: cmp18
    addkcmdline=rd.net.timeout.carrier=30
    arch=x86_64
    bmc=172.20.1.18
    bmcpassword=XXXXX
    bmcusername=XXXXX
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=install rhels7.2-x86_64-compute
    getmac=ipmi
    groups=all
    ip=172.17.1.18
    mac=7c:d3:0a:e1:86:30
    mgt=ipmi
    netboot=xnba
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels7.2-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=03-23-2022 09:45:26
    usercomment=the system X node definition

 # xcatprobe detect_dhcpd -i eno2 -m 7c:d3:0a:e1:86:30
Start to detect DHCP, please wait 10 seconds                                                                      [INFO]
++++++++++++++++++++++++++++++++++                                                                                [INFO]
There are 2 servers replied to dhcp discover.                                                                     [INFO]
    Server:172.17.1.66 assign IP [172.17.1.18]. The next server is [172.17.1.66]!                                 [INFO]
    Server:172.20.1.201 assign IP [172.17.1.18]. The next server is [172.17.1.66]!                                [INFO]
++++++++++++++++++++++++++++++++++                                                                                [INFO]

# cat /tftpboot/xcat/xnba/nodes/cmp18
#!gpxe
#install rhels7.2-x86_64-compute
imgfetch -n kernel http://${next-server}:80/tftpboot/xcat/osimage/rhels7.2-x86_64-install-compute/vmlinuz
imgload kernel
imgargs kernel quiet inst.repo=http://${next-server}:80/install/rhels7.2/x86_64 inst.ks=http://${next-server}:80/install/autoinst/cmp18 ip=dhcp  inst.cmdline  console=tty0 console=ttyS0,115200 rd.net.timeout.carrier=30  BOOTIF=01-${netX/machyp}
imgfetch -n initrd http://${next-server}:80/tftpboot/xcat/osimage/rhels7.2-x86_64-install-compute/initrd.img
imgexec kernel

 # tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"172_17_1_0-255_255_255_0","172.17.1.0","255.255.255.0","eno2","172.17.1.33",,"<xcatmaster>",,,,,,,,,,,"1500",,
"172_20_1_0-255_255_255_0","172.20.1.0","255.255.255.0","eno2:0","<xcatmaster>",,"<xcatmaster>",,,,,,,,,,,"1500",,

# lsdef -t osimage rhels7.2-x86_64-install-compute
Object name: rhels7.2-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels7.2-x86_64
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/x86_64
    pkgdir=/install/rhels7.2/x86_64
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

# ls -ltr /tftpboot/xcat/osimage/rhels7.2-x86_64-install-compute/
total 43832
-rw-r--r-- 1 root root  5154912 Mar 23 09:53 vmlinuz
-rw-r--r-- 1 root root 39725808 Mar 23 09:53 initrd.img

**Comment by gurevichmark** [comment]
@bkbcm 

What hardware is this ?
Have you tried installing RH 8.0 or newer ?

**Comment by bkbcm** [comment]
Hi Mark,

Thank you so much for reaching out to me. 

This is for a small 4 nodes HPC cluster and the computing node is

BMC Firmware: 1.08 (CDI306X 2017-10-23 08:32:56)
System Manufacturer: LENOVO
Manufacturer ID: Lenovo (19046)
System Description: ThinkSystem SR630
System Model/MTM: 7X02CTO1WW

It has RH6.10 running on it and was installed/configured by a former support admin. The business requirement is to go to RH 7.x since there are some apps/bin that won't work on RH8. I'm doing a fresh install on the MN with RH 7 with the latest version of xCAT. All the services (DNS, DHCP, TFTP, NTP, etc...) seems to be working but I'm having issue with OS deployment. I'm not sure if I'm missing some config or something. I could try to install RH 7 or 8 directly on the computing node if that's what you are referring?

Thanks,
BK

**Comment by gurevichmark** [comment]
If you have access to RH7.6, try deploying it to the compute node.
That is the oldest version of RH that we have been doing regression testing.

One possibility is that your compute node has a network adapter, for which RH7 does not include a driver ?

**Comment by bkbcm** [comment]
Hi Mark,

Thank you for your recommendation. You are absolute right. RH7.2 probably didn't have the correct driver for the NIC on this Lenovo ThinkSystem SR630.

I deployed RH7.6 as you've suggested and the installation completed successfully.

Just a side note. I was also looking at the /run/initramfs/rdsosreport.txt yesterday and noticed these NICs were down.

dracut:/run/initramfs# less /run/initramfs/rdsosreport.txt

<...snip...>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host 
valid_lft forever preferred_lft forever
3: eno1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
link/ether 7c:d3:0a:e1:86:30 brd ff:ff:ff:ff:ff:ff
4: eno2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
link/ether 7c:d3:0a:e1:86:31 brd ff:ff:ff:ff:ff:ff
5: enp6s0f0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
link/ether 00:10:9b:25:f5:86 brd ff:ff:ff:ff:ff:ff
6: enp6s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
link/ether 00:10:9b:25:f5:8e brd ff:ff:ff:ff:ff:ff
7: enp0s20f0u1u6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
link/ether 7e:d3:0a:e1:86:37 brd ff:ff:ff:ff:ff:ff
<...snip...>

After doing some googling on this error "dracut-initqueue[1721]: cat: /sys/class/net/eno1/carrier: Invalid argument", it seems to suggest that interface has to be up or you will get an invalid argument error. (https://unix.stackexchange.com/questions/132621/check-for-plugged-in-network-cable-on-startup)

Sure enough, when I tried to manually bring it up, it failed miserably.

dracut:/run/initramfs# ip link set eno1 up
RTNETLINK answers: Device or resource busy
dracut:/run/initramfs# ip link set eno2 up
RTNETLINK answers: Device or resource busy

Again, you were right.

One last question if you don't mind. What is the best way to remove the rhels7.2-x86 from the osimage now that I have the rhels7.6-x86 working? If it's too much trouble, I can just leave it like it is.

# lsdef -t osimage
rhels7.2-x86_64-install-compute (osimage)
rhels7.2-x86_64-install-service (osimage)
rhels7.2-x86_64-netboot-compute (osimage)
rhels7.2-x86_64-stateful-mgmtnode (osimage)
rhels7.2-x86_64-statelite-compute (osimage)
rhels7.6-x86_64-install-compute (osimage)
rhels7.6-x86_64-install-service (osimage)
rhels7.6-x86_64-netboot-compute (osimage)
rhels7.6-x86_64-statelite-compute (osimage)


Thank you again for your time and for sharing your invaluable knowledge.

Regards,
BK

**Comment by gurevichmark** [comment]
To remove the `netboot` and `statelite` image definitions and their contents, use:
`rmimage rhels7.2-x86_64-netboot-compute --xcatdef`
`rmimage rhels7.2-x86_64-statelite-compute --xcatdef`

To remove the `install` image contents, use:
`rmosdistro rhels7.2-x86_64 -f`

To remove the `install` image definitions for compute and service nodes, use:
`rmdef -t osimage rhels7.2-x86_64-install-compute`
`rmdef -t osimage rhels7.2-x86_64-install-service`

**Comment by bkbcm** [comment]
That's perfect. Thanks for your help on this case, Mark.
Have a wonderful day.

Regards,
BK
