### ISSUE TITLE
OpenBMC Python Framework with xCAT 2.16.3 / RHEL 8.4

### ISSUE THREAD

**Issue by nicolas-tallet** [xcat2/xcat-core#7138]
We have just updated our OpenPOWER client platform to HPC Service Pack 4.3 based on RHEL 8.4.

In our previous RHEL 7.6 environment, we used to have the OpenBMC Python framework enabled because the number of nodes of the platform (~600) made it a great improvement in terms of performance over the standard Perl framework.

However, we are having difficulties in enabling the Python framework in the new RHEL 8.4 environment because the dependencies of the `xCAT-openbmc-py` package are getting rather outdated.
The two direct dependent packages (`python2-gevent` and `python2-greenlet`) are still available from the Fedora Core 28 archive repository but it looks like a lot of other dependencies are now broken and these two packages do not install on RHEL 8.4.

```
# yum --enablerepo=fc28 install xCAT-openbmc-py

Last metadata expiration check: 1 day, 16:00:22 ago on Mon Mar 28 19:31:26 2022.
Error: 
 Problem: conflicting requests
  - nothing provides python-requests needed by xCAT-openbmc-py-1:2.16.3-snap202111100958.noarch
  - nothing provides python-scp needed by xCAT-openbmc-py-1:2.16.3-snap202111100958.noarch
  - nothing provides python2-docopt needed by xCAT-openbmc-py-1:2.16.3-snap202111100958.noarch
  - nothing provides python-paramiko >= 2.0.0 needed by xCAT-openbmc-py-1:2.16.3-snap202111100958.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

In particular, the requested packages exist for Python 3 under RHEL 8.4 but not for Python 2.

Would you have any recommendation?

**Comment by gurevichmark** [comment]
@nicolas-tallet Where did you find Fedora Core 28 archive ?
Can you show the `.repo` file you used to install `python2-geven`t and `python2-greenlet` ?

**Comment by nicolas-tallet** [comment]
Hi @gurevichmark , the Fedora Core 28 repository archive is available under the following location:
https://archives.fedoraproject.org/pub/archive/fedora-secondary/releases/28/Everything/ppc64le/

As instructed by the documentation, I have downloaded specifically the `python2-geven` and `python2-greenlet` packages locally on the platform (which has no direct access to the Internet), and put them in their own repository.

Maybe downloading the whole FC28 repository could help solve the broken dependencies, but I am not sure that would be sufficient.

I think the OpenBMC Python Framework needs a refresh, with a shift from Python 2 to Python 3.

**Comment by gurevichmark** [comment]
@nicolas-tallet 
There is already `openbmc` rpm built with Python 3 prereqs at
`www.xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-openbmc-py3-2.14.6-snap201903270354.noarch.rpm`

You will first need to install RH8 EPEL, if you do not already have that configured
` yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`

Then download and install `www.xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-openbmc-py3-2.14.6-snap201903270354.noarch.rpm`

And finally `alternatives --set python /usr/bin/python3`

If you run `r` commands with `-V` flag it will show you if Perl or Python is being used:
```
[root@f6u13k19 ~]# rpower f5u14 -V stat
[f6u13k19]: Running command in Python
[f6u13k19]: f5u14: on
[root@f6u13k19 ~]#
```

**Comment by gurevichmark** [comment]
Answered by https://github.com/xcat2/xcat-core/pull/7143 and
https://github.com/xcat2/xcat-core/pull/7150

**Comment by nicolas-tallet** [comment]
@gurevichmark : Thanks a lot for that.
We have successfully installed the version 2.14.6 of the OpenBMC Python framework, as you suggested, and we are going to update to the version 2.16.3 now that there is an updated package.
