### ISSUE TITLE
question with copycds & Rocky Linux ISO image

### ISSUE THREAD

**Issue by techie879** [xcat2/xcat-core#7188]
Hi, 
this is specific to using copycds command with Rocky Linux distro.
I have Rocky linux 8.5 running in a test environment.
and the layout in the /install directory for rocky linux is just "rocky8".  With CentOS 7 , and it version releases it would look like /install/centos7.8 , /install/centos7.9 . With Rocky linux every ISO file that copycds unpacks, it will overwrite everything in the /install/rocky8 directory.  

For version differentiation, I would like to keep the installation directories and osimage definitions  separate.  Currently, it looks like this: 
```
rocky8-x86_64-install-compute  (osimage)
rocky8-x86_64-install-service  (osimage)
rocky8-x86_64-netboot-compute  (osimage)
rocky8-x86_64-statelite-compute  (osimage)
```

Is there something that could be done that will keep Rocky 8.5 separated from Rocky 8.6 ? I would like to see the following: 

In the install directory, 
```
for rocky 8.5  - /install/rocky8.5
for rocky 8.6 - /install/rocky8.6
```

for the osimages: 

```
for rocky 8.5 :
rocky8.5-x86_64-install-compute  (osimage)
```

```
for rocky 8.6: 
rocky8.6-x86_64-install-compute  (osimage)

```

Any help or/and ideas are greatly appreciated!
thanks.

**Comment by techie879** [comment]
You can close this issue.  I have fixed the ISO , and that fixed the issue.  thanks

**Comment by gurevichmark** [comment]
Great. Can you close this issue if the problem has been resolved.
