### ISSUE TITLE
[DEV] Failed migration of kvm115 from c910f05c33 to c910f05c35 message: unable to connect to server at 'c910f05c35:49152': No route to host

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#720]
arch:ppc64le (x86_64 works fine)
MN: c910f02c09p16 VMhost1:c910f05c33 VMhost2:c910f05c35
VM: kvm115
how to procedure
MN:
```
mkdir /install/kvm115
vi /etc/exports #add kvm115
exportfs -r
```
VMhost1 and VMhost2
```
mkdir /install/kvm115
mount c910f02c09p16:/install/kvm115 /install/kvm115
```
MN
```
mkdef -t node kvm115 arch=ppc64le groups=kvm,vm,all mgt=kvm netboot=grub2 profile=compute serialport=0 serialspeed=115200 vmcpus=2 vmhost=c910f05c33 vmmemory=1024 vmnicnicmodel=virtio vmnics=br0 vmstorage=nfs://10.2.9.16/install/kvm115
mkvm kvm115 -s 20G
rpower kvm115 on
rmigrate kvm115 c910f05c35
```
error msg:
```
[root@c910f02c09p16 install]# rmigrate kvm115 c910f05c35
kvm115: Error: libvirt error code: 38, message: unable to connect to server at 'c910f05c35:49152': No route to host: Failed migration of kvm115 from c910f05c33 to c910f05c35
```

**Comment by whowutwut** [comment]
@penguhyang  Please associate this issue with a milestone, is this present in 2.11?

**Comment by gurevichmark** [comment]
I was not able to recreate this issue on May 9 2016 xCAT build. Similarly to #722, I had to turn off firewall and `rmigrate` worked for me. Also, it is not necessary to mount the NFS filesystem on VMhost1 and VMhost2. When `vmstorage=nfs://<host>/<dir>` specified for the VM definition the mounting is done automatically.

I would like to keep this issue open to update the xCAT documentation to tell the user to turn of firewall when using `rmigrate` command.

**Comment by daniceexi** [comment]
@gurevichmark So looks like the issue was the libvert has problem to connect to one of the kvmhost. Before your disable the firewall, could you use xcat command to manipulate the vm on this kvmhost?

**Comment by gurevichmark** [comment]
@daniceexi As far as I can tell, xcat has no problem controlling the VMs on kvmhost with firewall running. It appears that when kvmhost CN is provisioned, the firewall is active, but when non-kvmhost CN is provisioned, the firewall is turned off.
Should we try to disable firewall for kvmhosts automatically, or just add another section to KVM troubleshooting chapter and `rmigrate` man page to advise the user to disable firewall manually, if they see `No route to host:` message ?

**Comment by daniceexi** [comment]
@gurevichmark Doc the necessary operation to disable firewall on kvmhost before the running of ``rmigrate`` sounds good. But I suggest to add the restriction in the man page of ``rmigrate``.

**Comment by whowutwut** [comment]
I think @gurevichmark tried to modified the template file to disable SELINUX similar to how we are doing it in the other operating systems and it does not seem to apply for PKVM OS.  Anyone have an idea why it would not take the value passed to it from the kickstart file? Something we should open a ticket to in LTC?

**Comment by daniceexi** [comment]
PowerKVM is a customized system from Fedora, base on our experience that IBM made some configuration changes against the original system. So they might restrict the disable of SElinux for security consideration.

**Comment by gurevichmark** [comment]
Ok, I will use this issue to update the xCAT documentation and tell the user to check firewall and SELinux settings when things fail.
