### ISSUE TITLE
RH86 /dev/null permissions incorrect in diskless image after boot.

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#7220]
I have 2 RH84 management nodes c90csm02 and c685csm05.
I have checked in several RH86 DL images and when they boot the permissions on /dev/null are incorrect. 
Show
ls -l /dev/null
-rw-r--r-- 1 root root 0 Jul 21 12:11 /dev/null
Should be
ls -ltra /dev/null
crw-r--r-- 1 root root 1, 3 Jul 19 21:42 /dev/null
The most common problem seen is general users get permission denied when ssh'ing to a node.
I fix this by running "rm -f /dev/null; mknod -m 666 /dev/null c 1 3" on the nodes after boot 

[root@csm02 xcat_clusters]# lsxcatd -v
Version 2.16.3 (git commit 616cef1484b97b00051420ea1d88146cfbb332aa, built Sat Oct 30 00:17:16 EDT 2021)[root@csm02 custom]# lsxcatd -v
Version 2.16.3 (git commit 616cef1484b97b00051420ea1d88146cfbb332aa, built Sat Oct 30 00:17:16 EDT 2021)
[root@c685csm05 custom]# lsxcatd -v
Version 2.16.3 (git commit ce7f4146f84802cab1915ece2e4756c4ebb0fd76, built Wed Oct 20 00:16:54 EDT 2021)

Genned latest ist.redhat.8.6.netboot.CORAL.DL and ist.redhat.8.5.netboot.container.DL and booted. All had the same result.

**Comment by Obihoernchen** [comment]
This is fixed in 2.16.4 check: https://github.com/xcat2/xcat-core/pull/7080

**Comment by besawn** [comment]
@markprez I agree with @Obihoernchen's assessment. Thank you, @Obihoernchen.

@markprez Can you please upgrade to xCAT 2.16.4 GA version and confirm it resolves this issue for you?

**Comment by besawn** [comment]
This issue should be fixed in 2.16.4. Please re-open if you are still having problems on 2.16.4 or newer.
