### ISSUE TITLE
ipv6 provisioning support

### ISSUE THREAD

**Issue by negregg** [xcat2/xcat-core#7221]
Hello All,

I know xCAT support ipv6 but is ipv4 still required for provisioning?  I suspect the answer is yes, ipv4 is required, but want to verify.  I found in the older sourceforge docs that ipv4 is required but wanted to make sure that hasn't changed.

Thanks in advance.

**Comment by besawn** [comment]
@negregg That is correct, ipv4 is required for provisioning.

**Comment by negregg** [comment]
@besawn thanks for confirming.   I will close out this issue.
