### ISSUE TITLE
[Customer] The sound device should be included in vm xml

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#723]
Hello,
 
  I am working on a VDI project using KVM for hosting the virtual machines and SPICE to provide GUI/Sound access to the VMs.  Between the 2.10 and 2.11 releases, the kvm.pm module had sound support removed.  See:
 
https://github.com/xcat2/xcat-core/commit/c5f1075aeed48907b3a9f4cc9302f723f08d4eba
https://github.com/xcat2/xcat-core/commit/fa3f96a94029d659116cd24c2307137393fafbf3
 
Is there a plan to re-introduce sound support?  Were there any technical reasons for removing the support?
 
Thank you,
 
Michael Moore
HPC Systems Engineer
Nuance Communications
Michael.Moore@Nuance.com
 -----------------------------------

**Comment by immarvin** [comment]
hi @penguhyang , would you please take a look at this?

**Comment by whowutwut** [comment]
I think the resolution here is just to re-enable the ac97 xml line.   If we can fix this for 2.11 and 2.12, would be good..
