### ISSUE TITLE
sles15.3 autoinstallation broken

### ISSUE THREAD

**Issue by wrussian** [xcat2/xcat-core#7230]
After upgrading from 2.16.3 to version 2.16.4 the autoinstallation process isn't working. The osimage definition reads as
# lsdef -t osimage -o plato-sles15.3-x86_64
Object name: plato-sles15.3-x86_64
    imagetype=linux
    osarch=x86_64
    osdistroname=sle15.3-x86_64
    osname=Linux
    osvers=sle15.3
    otherpkgdir=/install/Images/sles15.3-x86_64/plato-0.0.1/otherpkgs
    otherpkglist=/install/HPC-Image/buildDef/compute-sles15.3-x86_64/plato/otherpkg.list
    partitionfile=/install/HPC-Image/buildDef/compute-sles15.3-x86_64/common/partitiondisk
    pkgdir=/install/sle15.3/x86_64,/install/Images/sles15.3-x86_64/kernels
    pkglist=/install/HPC-Image/buildDef/compute-sles15.3-x86_64/plato/pkglist
    postscripts=compute
    profile=compute
    provmethod=install
    synclists=/install/HPC-Image/buildDef/compute-sles15.3-x86_64/plato/synclist
    template=/opt/xcat/share/xcat/install/sle/compute.sle15.tmpl
# lsxcatd -a
Version 2.16.4 (git commit bb7a4bbbc8bde7e6613558d8d039fe43d49d2079, built Mon Jun 13 08:53:10 EDT 2022)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=XX.YY.ZZ.AA|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=XX.YY.ZZ.AA
dbadmin=xcatadm

The installation process stops with error messages in autoyast-error-{1,2,3}.png. For the first two errors the installation can be continued 'manually', but the installation breaks on the 3rd error.
Checking the autoyast xml file on a existing sles15.3 node with help of jing the following error is shown:
~ # jing /usr/share/YaST2/schema/autoyast/rng/profile.rng /tmp/pnsd12 
/tmp/pnsd12:33:40: error: element "partitioning" not allowed here; expected the element end-tag or element "drive"

At the line specified for the expanded autoyast template:
    <partitioning config:type="list">
        < partitioning config:type="list">
  <drive>
. . .
. . .
  </drive>
</partitioning>
    </partitioning>

This code section maps to 
    <partitioning config:type="list">
      
      <drive>
        <device>XCATPARTITIONHOOK</device>
        <initialize config:type="boolean">true</initialize>
        <use>all</use>
      </drive>
      
    </partitioning>

inside the /opt/xcat/share/xcat/install/sles/compute.sle15.tmpl  template file. Aka the partioning - xml tags are expanded twice upon running the nodeset - command.

Removing the duplicate start and stop partitioning - tags solve the problem (at least in my environment)
Please let me know if you need further details concerning image, pkglist,...
Many thanks in advance fixing this issue

**Comment by wrussian** [comment]
sorry I forgot to add the screenshot error messages
<img width="228" alt="autoyast-error-1" src="https://user-images.githubusercontent.com/63357131/183386669-f69a7355-b255-4457-9688-81f63537ec6d.PNG">
<img width="226" alt="autoyast-error-2" src="https://user-images.githubusercontent.com/63357131/183386699-85e8e5c0-78a9-4dda-924e-8b5342d6cf0b.PNG">
<img width="253" alt="autoyast-error-3" src="https://user-images.githubusercontent.com/63357131/183386721-bda0b2ad-583f-4c2f-a9e3-501c93143663.PNG">
.

**Comment by wrussian** [comment]
for some reason the code section of the sles15.3 template file isn't displayed correctly. Here's another try:

    <partitioning config:type="list">
      
      <drive>
        <device>XCATPARTITIONHOOK</device>
        <initialize config:type="boolean">true</initialize>
        <use>all</use>
      </drive>
      
    </partitioning>

**Comment by gurevichmark** [comment]
@wrussian Can you check your `/install/HPC-Image/buildDef/compute-sles15.3-x86_64/common/partitiondisk` to make sure it does not add `<partitioning>` and `</partitioning>` tags.

From https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_partition.html

![image](https://user-images.githubusercontent.com/16106630/183483017-202e9a37-df89-4e89-a26c-e9d3e23f19ed.png)

**Comment by wrussian** [comment]
yes, indeed the file contained the <partitioning> - tags. I think I was confused by the documentation I found here:

https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/raid_cfg.html?highlight=partitioning#deploy-diskful-nodes-with-raid1-setup-on-sles

I am sorry, I overlooked the documentation (page) you specified above. you can close the ticket.

**Comment by wrussian** [comment]
I successfully re-checked installation taken you hint into account.
