### ISSUE TITLE
[Customer]p-flex lsslp giving inconsistent results

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#724]
I am getting inconsistent results running lsslp on p-flex ems:
[root@c865mgrs2 ~]# lsxcatd -a
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)

This occurred running xcat version 2.10
GOOD RUN:
[root@c865mgrs2 ~]# lsslp -V
08:24:07 20678
--------  Wed Feb 17 08:24:07 2016
Time     PID
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 12 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
08:24:13 20678 Total SLP Time: 5.737 sec

4 requests with 12 responses.  Now processing responses.  This will take 0-1 minutes...
08:24:13 20678 Now lsslp begin to parse its response...
08:24:13 20678 Discover node 10.0.0.3:type is fsp, mtm is 7895-22X,
                        sn is 105B57B, side is A-0,parent is Server-7895-22X-SN105B57B,ip is 10.0.0.3,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:24:65,
                        otherinterfaces is 10.0.0.3
08:24:13 20678 Discover node 10.0.0.9:type is fsp, mtm is 7895-42X,
                        sn is 105B5AB, side is A-0,parent is Server-7895-42X-SN105B5AB,ip is 10.0.0.9,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:13:a5,
                        otherinterfaces is 10.0.0.9
08:24:13 20678 Discover node 10.0.0.11:type is fsp, mtm is 7895-42X,
                        sn is 105B5BB, side is A-0,parent is Server-7895-42X-SN105B5BB,ip is 10.0.0.11,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:1b:2b,
                        otherinterfaces is 10.0.0.11
08:24:18 20678 Discover node c865hmc1: type is hmc,
                        mtm is 7042CR5,sn is 1035C9C,  ip is 9.114.26.154,
                        mac is e4:1f:13:68:09:5a, otherinterfaces is 9.114.26.154
08:24:18 20678 Discover node 10.0.0.7:type is fsp, mtm is 7895-42X,
                        sn is 105B58B, side is A-0,parent is Server-7895-42X-SN105B58B,ip is 10.0.0.7,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:28:77,
                        otherinterfaces is 10.0.0.7
08:24:18 20678 Discover node 10.0.0.13:type is fsp, mtm is 7895-42X,
                        sn is 102016B, side is A-0,parent is Server-7895-42X-SN102016B,ip is 10.0.0.13,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:1a:be,
                        otherinterfaces is 10.0.0.13
08:24:18 20678 Discover node 10.0.0.4:type is fsp, mtm is 7895-22X,
                        sn is 105B54B, side is A-0,parent is Server-7895-22X-SN105B54B,ip is 10.0.0.4,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:24:6d,
                        otherinterfaces is 10.0.0.4
08:24:18 20678 Discover node 10.0.0.200:type is fsp, mtm is 7895-42X,
                        sn is 10F697A, side is A-0,parent is Server-7895-42X-SN10F697A,ip is 10.0.0.200,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:01:28,
                        otherinterfaces is 10.0.0.200
08:24:18 20678 Discover another node 11.0.0.4:type is fsp, mtm is 7895-42X,
                                sn is 10F697A, side is A-1,parent is Server-7895-42X-SN10F697A,ip is 11.0.0.4,
                                cec id is 0 , frame id is 0,mac is ,
                                otherinterfaces is 10.0.0.200
08:24:18 20678 Discover node c865cmm1: type is cmm,
                        mtm is 789392X, sn is 10078AA, side is 1,
                        ip is 10.0.0.108, mac is 34:40:b5:df:13:04, mname is SN#Y014BG27T02S,
                        mpa is c865cmm1, otherinterfaces is 10.0.0.108
08:24:18 20678 Discover node 10.0.0.1:type is fsp, mtm is 7895-22X,
                        sn is 105B56B, side is A-0,parent is Server-7895-22X-SN105B56B,ip is 10.0.0.1,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:1c:d5,
                        otherinterfaces is 10.0.0.1
08:24:18 20678 Discover node 10.0.0.2:type is fsp, mtm is 7895-22X,
                        sn is 105B55B, side is A-0,parent is Server-7895-22X-SN105B55B,ip is 10.0.0.2,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:1c:91,
                        otherinterfaces is 10.0.0.2
08:24:18 20678 Discover node 10.0.0.5:type is fsp, mtm is 7895-42X,
                        sn is 105B59B, side is A-0,parent is Server-7895-42X-SN105B59B,ip is 10.0.0.5,
                        cec id is 0 , frame id is 0,mac is 5c:f3:fc:84:1f:1d,
                        otherinterfaces is 10.0.0.5
08:24:18 20678

Begin to find find frame's hostname
08:24:18 20678

Begin to find cec's parent
08:24:18 20678

Begin to find cec hostname
08:24:18 20678

Begin to find fsp/bpa's hostname and parent
08:24:18 20678 10.0.0.11 found parent
08:24:18 20678 10.0.0.3 found parent
08:24:18 20678 10.0.0.1 found parent
08:24:18 20678 10.0.0.7 found parent
08:24:18 20678 10.0.0.200 found parent
08:24:18 20678 11.0.0.4 found parent
08:24:18 20678 10.0.0.4 found parent
08:24:18 20678 10.0.0.9 found parent
08:24:18 20678 10.0.0.2 found parent
08:24:18 20678 10.0.0.5 found parent
08:24:18 20678 10.0.0.13 found parent
08:24:18 20678

Begin to adjust fsp/bpa's id
08:24:18 20678

Begin to find cmm hostname in switch table
device  type-model  serial-number  side  ip-addresses  hostname
fsp     7895-22X    105B56B        A-0   10.0.0.1      10.0.0.1
fsp     7895-42X    105B5BB        A-0   10.0.0.11     10.0.0.11
fsp     7895-42X    102016B        A-0   10.0.0.13     10.0.0.13
fsp     7895-22X    105B55B        A-0   10.0.0.2      10.0.0.2
fsp     7895-42X    10F697A        A-0   10.0.0.200    10.0.0.200
fsp     7895-22X    105B57B        A-0   10.0.0.3      10.0.0.3
fsp     7895-22X    105B54B        A-0   10.0.0.4      10.0.0.4
fsp     7895-42X    105B59B        A-0   10.0.0.5      10.0.0.5
fsp     7895-42X    105B58B        A-0   10.0.0.7      10.0.0.7
fsp     7895-42X    105B5AB        A-0   10.0.0.9      10.0.0.9
fsp     7895-42X    10F697A        A-1   11.0.0.4      11.0.0.4
hmc     7042CR5     1035C9C              9.114.26.154  c865hmc1
cmm     789392X     10078AA        1     10.0.0.108    c865cmm1

BAD RUNS:
[root@c865mgrs2 ~]# lsslp
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 1 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
4 requests with 1 responses.  Now processing responses.  This will take 0-1 minutes...
device  type-model  serial-number  side  ip-addresses  hostname
hmc     7042CR5     1035C9C              9.114.26.154  c865hmc1

[root@c865mgrs2 ~]# lsslp -V
09:02:20 20827
--------  Wed Feb 17 09:02:20 2016
Time     PID
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 1 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
09:02:26 20827 Total SLP Time: 5.535 sec

4 requests with 1 responses.  Now processing responses.  This will take 0-1 minutes...
09:02:26 20827 Now lsslp begin to parse its response...
09:02:31 20827 Discover node c865hmc1: type is hmc,
                        mtm is 7042CR5,sn is 1035C9C,  ip is 9.114.26.154,
                        mac is e4:1f:13:68:09:5a, otherinterfaces is 9.114.26.154
09:02:31 20827

Begin to find find frame's hostname
09:02:31 20827

Begin to find cec's parent
09:02:31 20827

Begin to find cec hostname
09:02:31 20827

Begin to find fsp/bpa's hostname and parent
09:02:31 20827

Begin to adjust fsp/bpa's id
09:02:31 20827

Begin to find cmm hostname in switch table
device  type-model  serial-number  side  ip-addresses  hostname
hmc     7042CR5     1035C9C              9.114.26.154  c865hmc1

[root@c865mgrs2 ~]# lsslp -V -s CMM
09:05:56 20866
--------  Wed Feb 17 09:05:56 2016
Time     PID
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
Sending SLP request on interfaces: 10.0.0.252,9.114.26.136 ...
Received 0 responses.
09:06:02 20866 Total SLP Time: 5.348 sec

4 requests with 0 responses.  Now processing responses.  This will take 0-1 minutes...
No responses

**Comment by tingtli** [comment]
@zet809  Er tao, would you please take a look at this issue?

**Comment by tingtli** [comment]
@zet809  I have the same problem when I use lsslp to discover IMM for NextScale node. Sometimes it gives out the correct result, but sometimes it does not.

**Comment by zet809** [comment]
@markprez The logic of SLP is like this: the client send out a broadcast or multicast service request, then the server that support SLP will reply. Then, on client side, for the IPs that have replied SLP response, send out attribute request and wait for and then deal with their response.
So, if the timeout is not long enough, or the network delay is large, or the network traffic is heavy, the client won't be able to get all the service replying. 
If possible, you can use our unicast function for your environment which is much more stable. The usage is like this:
lsslp -s CMM/CEC/HMC -u --range <ip-range>
