### ISSUE TITLE
2.16.4: Add BMC MAC to a node definition 

### ISSUE THREAD

**Issue by ahmedfathymahmoud** [xcat2/xcat-core#7243]
Hello,

Is there a way to add BMC MAC to a node definition to obtain a specific IP address instead of obtaining a random IP address from a dynamic range?

I know I can use ```bmcdiscover``` but the issue here is that every node has a different default BMC user and password plus we already have a table of all MACs in the cluster so it makes sense to define the cluster directly without using any discovery method.
 
 xCAT version:
 ```
#xcatconfig -v
Version 2.16.4 (git commit bb7a4bbbc8bde7e6613558d8d039fe43d49d2079, built Mon Jun 13 08:53:10 EDT 2022)
```

Thanks in advance!

**Comment by besawn** [comment]
Yes, the simplest way is to define a new object for each BMC that includes the mac and IP address you want to assign to the BMC and run `makehosts <noderange>`, `makedns <noderange>`, `makedhcp <noderange>` to add it to the DHCP configuration.

Some additional information here: 
https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define.html
You will need to modify the objects you create for your specific situation.

I'm not sure how far into your cluster set up you are. Once you have a working recipe, you can define all of your compute nodes and associated BMCs in a single stanza file and create all of the objects at once.

Assuming you already have a working node object (`f1n1`, for example) and you just want to create a BMC object to assign a fixed IP address to the BMC via dhcp, you can do something like:
```
# mkdef -t node f1n1-bmc mac=11:22:33:44:55:66 ip=172.168.1.1 groups=bmc
1 object definitions have been created or modified.

# lsdef f1n1-bmc
Object name: f1n1-bmc
    groups=bmc
    ip=172.168.1.1
    mac=11:22:33:44:55:66
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles

# makehosts f1n1-bmc

# makedns f1n1-bmc
Handling f1n1-bmc in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
DNS setup is completed

# makedhcp f1n1-bmc

# makedhcp -q f1n1-bmc
f1n1-bmc: ip-address = 172.168.1.1, hardware-address = 11:22:33:44:55:66
```
After you change the DHCP configuration you will have to reboot the BMC or wait until the lease expires for the new address to get assigned. Also, make sure to update the `bmc` attribute of your associated compute node object to match the new IP address or hostname of your BMC if it has changed.

**Comment by besawn** [comment]
The method described above is how I would approach setting reserved DCHP addresses for each BMC. If you want to set static IP addresses for each BMC and not rely on DHCP at all, a different approach is needed.

**Comment by ahmedfathymahmoud** [comment]
Dear @besawn,
We have tested this solution and it seems to be the optimal solution that we need. 
Many thanks for your help.
