### ISSUE TITLE
Unsufficient check in credentials.pm

### ISSUE THREAD

**Issue by salben21** [xcat2/xcat-core#7246]
Hi,
I recognize that one can request the ssh_root_key's of every zone from every client independently of its zone affiliation by a simple script using getcredentials.awk and allowcred.awk. This is a security issue if you use multiple zones with sshbetweenodes=no to avoid a privilege escalation to other nodes.

It seems that in credentials.pm of the xcatd following checks are missing:

If a ssh_root_key was requested check 
 - if the client is in the zone of the requested key's zone otherwise reject the request.
 - if the sshbetweennodes is set to yes in the requested zone, otherwise reject the request
 
best

**Comment by salben21** [comment]
Workaround for xCAT-server/lib/xcat/plugins/credentials.pm from my side


        if ((($parm =~ /^ssh_root_key/) || ($parm =~ /^ssh_root_pub_key/)) && ($foundkeys == 0)) {
            my ($rootkeyparm, $zonename) = split(/:/, $parm);
            my $client_zonename=xCAT::Zone->getmyzonename($client);
            
            if ($zonename) {
                $parm = $rootkeyparm;           # take the zone off
                xCAT::MsgUtils->trace(0, 'I', "credentials: The node ($client) is asking for sshkeys of zone: $zonename.");
                if ($client_zonename eq $zonename) {
                  my $sshbetweenodes_allowed = xCAT::Zone->enableSSHbetweennodes($client);
                  if (($sshbetweenodes_allowed == 1) || ($parm =~ /^ssh_root_pub_key/)) { # check if sshbetweennodes is allowed or pub key is requested
                    $sshrootkeydir = xCAT::Zone->getzonekeydir($zonename);
                    if ($sshrootkeydir == 1) {      # error return
                        xCAT::MsgUtils->trace(0, 'W', "credentials: The zone: $zonename is not defined.");
                    } else {
                        $foundkeys = 1;    # don't want to read the zone data twice
                    }
                  } else {
                      xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key because sshbetweennodes is disabled.");
                      $sshrootkeydir = 1;
                  }
                } else {
                    xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key of different zone.");
                    $sshrootkeydir = 1;
                }
            } elsif ($client_zonename) { # check if no zonename is submitted but node is in a zone
                xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key of default zone.");
                $sshrootkeydir = 1;
            }
        }


instead of

        if ((($parm =~ /^ssh_root_key/) || ($parm =~ /^ssh_root_pub_key/)) && ($foundkeys == 0)) {
            my ($rootkeyparm, $zonename) = split(/:/, $parm);
            if ($zonename) {
                $parm = $rootkeyparm;           # take the zone off
                xCAT::MsgUtils->trace(0, 'I', "credentials: The node ($client) is asking for sshkeys of zone: $zonename.");
                $sshrootkeydir = xCAT::Zone->getzonekeydir($zonename);
                if ($sshrootkeydir == 1) {      # error return
                    xCAT::MsgUtils->trace(0, 'W', "credentials: The zone: $zonename is not defined.");
                } else {
                    $foundkeys = 1;    # don't want to read the zone data twice
                }
            }
        }

**Comment by salben21** [comment]
By the way: The argument in the description of the function enableSSHbetweennodes in the file [https://github.com/xcat2/xcat-core/tree/master/perl-xCAT/xCAT/Zone.pm] is _nodename_ and not _zonename_

=head3    enableSSHbetweennodes
      Arguments:
      <del>zonename</del>nodename
      Returns:
       1 if the  sshbetweennodes attribute is yes/1 or undefined
       0 if the  sshbetweennodes attribute is no/0
       Example:
        xCAT::Zone->enableSSHbetweennodes(<del>$zonename</del>$nodename);
=cut

**Comment by jjohnson42** [comment]
BTW, I would be interested on your feedback on the confluent ssh design.

In confluent, no user private keys for root or any other user are ever shared.  Same for private host keys, nodes generate their own.

Instead, confluent grants host certificates, sets up host based authentication based on the host certificates, and uses shosts.equiv to implement a variant of 'zones' (in confluent, it's "trustnodes", meaning that you can have asymettric zoning where, for example, the compute could trust the storage without storage trusting the compute).

Further, it implements a context aware where once a node security token is granted, it locks down the interface so that it can't be used, and getting ssh certs requires the initial token.

**Comment by jjohnson42** [comment]
Oh, and you may want to make this a pull request, it seems straightforward enough to me.

**Comment by salben21** [comment]
Hi Jarrod,
thanks for the fast reply. If you can make a pull request it would be fine (otherwise I have to fill out the papers). Attached is the latest version of my patch for credetials.pm (I've improved the check when the zone is empty)  in a zip file.

have a nice weekend,

Dr. Stefan Albensoeder
Senior Expert High-Performance-Computing

WRD Wobben Research and Development GmbH
Teerhof 59
D- 28199 Bremen
Germany

Phone: +49-421-24415-306
Mobile: +49-151-44668760
Fax: +49-421-24415-119
mailto: ***@***.******@***.***>
www.enercon.de<http://www.enercon.de/>

[https://teams.enercon.de/sites/marketing/public/de/PublishingImages/youtube_social_icon_red_30px.png]<https://www.youtube.com/channel/UCNiZXEFGLjap3rvziYRLtpw>  [https://teams.enercon.de/sites/marketing/public/de/PublishingImages/LI-In-Bug_30px.png] <https://de.linkedin.com/company/enercon-gmbh>  [https://teams.enercon.de/sites/marketing/public/de/PublishingImages/XNG_Sharebutton_v02_30px.png] <https://www.xing.com/companies/enercon>
Follow us on Social Media! We look forward to meeting you there!
[https://teams.enercon.de/sites/marketing/public/de/PublishingImages/ThinkBeforeYouPrint.gif]
Bitte beachten Sie: Im Rahmen der Durchführung unserer Kundenbeziehung oder eventuell auch eines damit zusammenhängenden Verwaltungsverfahrens erheben und verarbeiten wir im erforderlichen Umfang Ihre personenbezogenen Daten. Aufgrund der am 25.05.2018 wirksam gewordenen Europäischen Datenschutzgrundverordnung (DSGVO) sind wir verpflichtet, Sie über die in Art. 13 DSGVO genannten Angaben zur Datenerhebung zu informieren (soweit für Sie anwendbar). Wir haben daher unseren Datenschutzhinweis unter www.enercon.de/Datenschutz<http://www.enercon.de/Datenschutz> aktualisiert.  Dort finden Sie nähere Informationen.
Please note: In the setting of the performance of our customer relationship or, as the case may be, a related administrative procedure, we collect and process your personal data to the extent required. Under the European General Data Protection Regulation (GDPR), which has become effective on 2018-05-25, we are obliged to notify you of the data collection information mentioned in Article 13 GDPR (if applicable to you). We have therefore updated our privacy statement at www.enercon.de/en/privacy-policy/<http://www.enercon.de/en/privacy-policy/>. Please visit this page for more detailed information.
Diese E-Mail und mögliche Anhänge enthalten vertrauliche Informationen, die rechtlich besonders geschützt sein können. Wenn Sie nicht der beabsichtigte Empfänger bzw. Adressat dieser E-Mail sind und diese E-Mail etwa aufgrund eines technischen Fehlers oder eines Versehens erhalten haben, informieren Sie uns bitte sofort und löschen Sie anschließend die E-Mail. Das unbefugte Kopieren dieser E-Mail, etwaiger Anhänge sowie die unbefugte Weitergabe der enthaltenen Informationen an Dritte ist nicht gestattet.
This e-mail message together with its attachments, if any, is confidential and may contain information subject to legal privilege (e.g. attorney-client-privilege). If you are not the intended recipient or have received this e-mail in error, please inform us immediately and delete this message. Any unauthorised copying of this message (and attachments) or unauthorised distribution of the information contained herein is prohibited.

Wobben Research and Development GmbH - Sitz: Borsigstraße 26, 26607 Aurich - Registergericht: Amtsgericht Aurich, HRB 1062 - Geschäftsführer: Dipl.-Kfm. Hans-Dieter Kettwig · Jörg Scholle
Wobben Research and Development GmbH - Registered office: Borsigstraße 26, 26607 Aurich - Registration court: Amtsgericht Aurich, Commercial register number 1062 - Managing Director: Dipl.-Kfm. Hans-Dieter Kettwig · Jörg Scholle


Von: Jarrod Johnson ***@***.***>
Gesendet: Freitag, 9. September 2022 15:28
An: xcat2/xcat-core ***@***.***>
Cc: Stefan Albensoeder ***@***.***>; Author ***@***.***>
Betreff: Re: [xcat2/xcat-core] Unsufficient check in credentials.pm (Issue #7246)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Oh, and you may want to make this a pull request, it seems straightforward enough to me.

-

**Comment by salben21** [comment]
Here the latest release of the changes:

        if ((($parm =~ /^ssh_root_key/) || ($parm =~ /^ssh_root_pub_key/)) && ($foundkeys == 0)) {
            my ($rootkeyparm, $zonename) = split(/:/, $parm);
            my $client_zonename = xCAT::Zone->getmyzonename($client);
            my $default_zonename = xCAT::Zone->getdefaultzone();
            
            if ($zonename) {
                $parm = $rootkeyparm;           # take the zone off
                xCAT::MsgUtils->trace(0, 'I', "credentials: The node ($client) is asking for sshkeys of zone: $zonename.");
                if ($client_zonename eq $zonename) {
                    my $sshbetweenodes_allowed = xCAT::Zone->enableSSHbetweennodes($client);
                    if (($sshbetweenodes_allowed == 1) || ($parm =~ /^ssh_root_pub_key/)) { # check if sshbetweennodes is allowed or pub key is requested
                        $sshrootkeydir = xCAT::Zone->getzonekeydir($zonename);
                        if ($sshrootkeydir == 1) {    # error return
                            xCAT::MsgUtils->trace(0, 'W', "credentials: The zone: $zonename is not defined.");
                        } else {
                            $foundkeys = 1; # don't want to read the zone data twice
                        }
                    } else {
                        xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key because sshbetweennodes is disabled.");
                        $sshrootkeydir = 1;
                    }
                } else {
                    xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key of different zone.");
                    $sshrootkeydir = 1;
                }
            } elsif ($client_zonename ne $default_zonename) { # check if no zonename is submitted but node is not in default zone
                xCAT::MsgUtils->trace(0, 'E', "credentials: Not allowed to read root's private ssh key of default zone.");
                $sshrootkeydir = 1;
            }
        }

**Comment by salben21** [comment]
Regarding confluent: I didn't dig in the code of confluent. Sorry.

**Comment by jjohnson42** [comment]
Ok, my attempt of incorporating changes as a pull request:
https://github.com/xcat2/xcat-core/pull/7247

Broadly speaking, at least for my part I'm working towards a broadly more hardened design in confluent for these features, and if there is interest in discussion of those security design points, let me know.  I hope it is found to be a broadly more secure approach.

**Comment by besawn** [comment]
This issue is fixed in xCAT 2.16.5.
