### ISSUE TITLE
[Customer]MAC address not found

### ISSUE THREAD

**Issue by SirRollen** [xcat2/xcat-core#725]
I'm building a new cluster MN from scratch, I went through all the XCAT_iDataPlex_Cluster_Quick_Start and also did a few builds on a VM (RHEL 7.2) from other tutorial sites. I feel I have a good understanding and just to give you an idea on what I'm working with physically I have a asrock c2750d4i motherboard for testing this process and a Lenovo x3650 M5 2 for testing the pre-made templates on the quick start.

I have successfully installed xCAT, DHCP, DNS, NTP, disabled firewall, disabled SELINUX and I'm using a Cisco 3850 switch with all the SNMP settings placed. No matter what I do though I cannot seem to get the nodes to be discovered or have the makedhcp -d (node) find the mac address for the associated node. 

I have to manually add the MAC address to the 'tabedit mac' table and then I'm able to use 'rinstall (node)'.

Can any one help me find what I could possibly be missing to get this to work properly?

**Comment by whowutwut** [comment]
Hi @SirRollen, You may have modified the initial post, but I saw something about the documentation in the email I got.  I understand the frustration... We have been working on improving the documentation for the xCAT 2.11 release and it's hosted over on RTD, (http://xcat-docs.readthedocs.org/) We are continuously trying to fix some of the doc to make it more complete but most of the focus has been on IBM OpenPower systems.   We are always looking for feedback.  The latest doc has some of the changes we have been adding in which will be flipped in the 2.12 release. The install guide sections and admin guide section do have some commonality between p and x, but we have not added in the pages for x86_64 machines.  

@daniceexi  can you help address some of the other issues ?

**Comment by SirRollen** [comment]
@whowutwut  Thanks! That's a big relief knowing that I'm not alone about the documentation. I've heard nothing but great things about xCAT but I have yet to get over this wall to achieve these success stories.  I removed it because I didn't want to be unfair to you guys, hopefully with the new release and the docs you mention it'll relieve a lot of the headaches.

If you need any dumps let me know and I'll get the specifics ones you need. I'll review the docs link and see if I can find some thing different.

**Comment by daniceexi** [comment]
@SirRollen Could you follow the doc to make sure that the switch has been configured correctly. http://xcat-docs.readthedocs.org/en/latest/advanced/networks/ethernet_switches/ethernet_switches.html

Finally running the 'snmpwalk -v 3 ...' which mentioned in the above doc to verify the snmp v3 has been configured correctly.

Additionally, please monitor the logs in /var/log/message (2.10 and ealier) or /var/log/xcat/cluster.log (2.11) to see the message has the keyword 'discover'

**Comment by SirRollen** [comment]
@daniceexi I followed all of the instructions and 'snmpwalk-v 3'  command string works. I'm still not seeing any discoveries happening besides the manual ones I've done. I enabled lldp as well, I can see the switch using switchdiscover --range and I can see the node using bmcdiscover --range. 

xdsh works and I'm able to send commands to the switch. 

```
lsdef node-ac1d6501
object name: node-ac1d6501
bmc=172.29.101.1
cons=ipmi
groups=all
hwtype=bmc
mgt=ipmi
nodetype=mp
postbootscripts=otherpkgs
postscripts=syslog,remoteshell,syncfiles
status=booting
status=02-18-2016 09:35:15

lsdf switch1
object name: switch1
groups=switch,all
ip=172.30.50.1
mgt=switch
nodetype=switch
password=cisco
postbootscripts=otherpkgs
postscripts=syslog,remoteshell,syncfiles
protocol=ssh
snmpauth=sha
snmppassword=passw0rd
snmpusername=xcat
snmpversion=3
switchtype=Cisco
usercomment=Cisco
username=admin

lsdef cn1
object name: cn1
bmc=50.0.101.1
chain=runcmd=bmcsetup
cons=ipmi
groups=x86_x64,all
installnic=mac
ip=172.29.101.1
mgt=ipmi
netboot=pxe
postbootscripts=otherpkgs
postscripts=syslog,remoteshell,syncfiles
primarynic=mac
provmethod=install

object name: x86_x64
members=cn1

object name: all
members=switch1,cn1,node-ac1d6501,node-ac1d6502
```

**Comment by daniceexi** [comment]
Could you confirm that there was the message like 'Processing discovery request from' in the log file? If no, I doubt that the server has got in the genesis (the diskless system to run the discovery process). Then you can check the dhcp log and http log to see whether the genesis has been loaded.
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: SirRollen <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Xiao Peng Wang/China/IBM@IBMCNSubject: Re: [xcat-core] [Customer]MAC address not found (#725)Date: Thu, Feb 18, 2016 10:47 PM 
@daniceexi I followed all of the instructions and 'snmpwalk-v 3' command string works. I'm still not seeing any discoveries happening besides the manual ones I've done. I enabled lldp as well, I can see the switch using switchdiscover --range and I can see the node using bmcdiscover --range.
xdsh works and I'm able to send commands to the switch.
lsdef node-ac1d6501object name: node-ac1d6501bmc=172.29.101.1cons=ipmigroups=allhwtype=bmcmgt=ipminodetype=mppostbootscripts=otherpkgspostscripts=syslog,remoteshell,syncfilesstatus=bootingstatus=02-18-2016 09:35:15lsdf switch1object name: switch1groups=switch,allip=172.30.50.1mgt=switchnodetype=switchpassword=ciscopostbootscripts=otherpkgspostscripts=syslog,remoteshell,syncfilesprotocol=sshsnmpauth=shasnmppassword=passw0rdsnmpusername=xcatsnmpversion=3switchtype=Ciscousercomment=Ciscousername=adminlsdef cn1object name: cn1bmc=50.0.101.1chain=runcmd=bmcsetupcons=ipmigroups=x86_x64,allinstallnic=macip=172.29.101.1mgt=ipminetboot=pxepostbootscripts=otherpkgspostscripts=syslog,remoteshell,syncfilesprimarynic=macprovmethod=installobject name: x86_x64members=cn1object name: allmembers=switch1,cn1,node-ac1d6501,node-ac1d6502

**Comment by SirRollen** [comment]
@daniceexi  I checked the DNS log and see the IP and the MAC address of the target node. I don't see any HTTP logs though. I haven't seen any mentions of genesis. Can you please link some reference materials on what I need to do to make sure genesis is installed/running properly?

**Comment by daniceexi** [comment]
@SirRollen You can check whether your target node sent dhcp request to the xCAT MN, I am afraid it did not boot from network. 

If your node did boot from network, the dhcp server on the xCAT MN will instruct it to download the files /tftpboot/xcat/xnba.* which is installed by xnba-undi. Please check the rpm **xnba-undi** has been installed.

**Comment by SirRollen** [comment]
xnba-undi is installed currently. The target node sends a DHCP request and receives it from the xCAT MN. I can use commands like rpower and rinstall to manually effect the node.

 I can't help but feel that there is something simple that I'm missing but I've done several new virtualboxes clean installs for the xCAT MN and everything works up until I get to the point of discovery and rinstall does not do anything besides reboot the node. The node doesn't netboot and it gives me the generic attempting to boot using PXE but nothing happens.

**Comment by daniceexi** [comment]
@SirRollen There were must issues in the dhcpd configuration or xnba configuration.

Did you run the 'makedhcp -n'? Show out the content of /etc/dhcp/dhcpd.conf.

Could you search the tftp keyword in the syslog? You should see the download of xcat/xnba.* file through tftp if the dhcp configuration was correct.

BTW, if your compute node is Lenovo M5 machine, you maybe should use the 'rsetboot <node> net -u' to start the OS deployment via UEFI mode.

**Comment by SirRollen** [comment]
Below is the whole DHCPD config file. 

`#xCAT generated dhcp configuration

option conf-file code 209 = text;
option space isan;
option isan-encap-opts code 43 = encapsulate isan;
option isan.iqn code 203 = string;
option isan.root-path code 201 = string;
option space gpxe;
option gpxe-encap-opts code 175 = encapsulate gpxe;
option gpxe.bus-id code 177 = string;
option user-class-identifier code 77 = string;
option gpxe.no-pxedhcp code 176 = unsigned integer 8;
option tcode code 101 = text;
option iscsi-initiator-iqn code 203 = string;
ddns-update-style interim;
ignore client-updates;
option client-architecture code 93 = unsigned integer 16;
option tcode "America/New_York";
option gpxe.no-pxedhcp 1;

omapi-port 7911;
key xcat_key {
  algorithm hmac-md5;
  secret "SzA4dXFaekVONWk4WDRMclRvNEtBUEl6cVF6NURUVzA=";
};
omapi-key xcat_key;
class "pxe" {
   match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
   ddns-updates off;
    max-lease-time 600;
}
shared-network enp0s3 {
  subnet 172.16.0.0 netmask 255.240.0.0 {
    authoritative;
    max-lease-time 43200;
    min-lease-time 43200;
    default-lease-time 43200;
    option routers  172.20.0.1;
    next-server  172.20.0.1;
    option log-servers 172.20.0.1;
    option ntp-servers 172.20.0.1;
    option domain-name "cluster";
    option domain-name-servers  172.20.0.1;
    option domain-search  "cluster";
    zone cluster. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 16.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 17.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 18.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 19.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 20.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 21.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 22.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 23.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 24.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 25.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 26.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 27.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 28.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 29.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 30.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
zone 31.172.IN-ADDR.ARPA. {
   primary 172.20.0.1; key xcat_key; 
 }
    if option user-class-identifier = "xNBA" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent
       always-broadcast on;
       filename = "http://172.20.0.1/tftpboot/xcat/xnba/nets/172.16.0.0_12";
    } else if option user-class-identifier = "xNBA" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent
       filename = "http://172.20.0.1/tftpboot/xcat/xnba/nets/172.16.0.0_12.uefi";
    } else if option client-architecture = 00:00  { #x86
      filename "xcat/xnba.kpxe";
    } else if option vendor-class-identifier = "Etherboot-5.4"  { #x86
      filename "xcat/xnba.kpxe";
    } else if option client-architecture = 00:07 { #x86_64 uefi
       filename "xcat/xnba.efi";
    } else if option client-architecture = 00:09 { #x86_64 uefi alternative id
       filename "xcat/xnba.efi";
    } else if option client-architecture = 00:02 { #ia64
       filename "elilo.efi";
    } else if option client-architecture = 00:0e { #OPAL-v3
       option conf-file = "http://172.20.0.1/tftpboot/pxelinux.cfg/p/172.16.0.0_12";
    } else if substring(filename,0,1) = null { #otherwise, provide yaboot if the client isn't specific
       filename "/yaboot";
    }
    range dynamic-bootp 172.29.101.1 172.29.101.255;
  } # 172.16.0.0/255.240.0.0 subnet_end
} # enp0s3 nic_end
#definition for host cn1 aka host cn1 can be found in the dhcpd.leases file (typically /var/lib/dhcpd/dhcpd.leases)

`

**Comment by daniceexi** [comment]
The dhcpd configuration file looks good. Then you need check whether the tftp server works well on your MN, and check the tftp messages in syslog.

You also need to confirm that the firewall on your MN has been disabled, otherwise the tftp port is blocked by the firewall.

**Comment by SirRollen** [comment]
Doesn't look like TFTP is running at all. Checked my syslogs and could only find it in Yum.log showing that it was installed. I'm going to attempt to install tftp-server and xinetd and manually configure this. I saw that in the iDataplex instructions that TFTP gets configured/installed automatically by xCAT. 

Is this still true and how can I confirm the correct xCAT has correctly configured the TFTP server?

**Comment by daniceexi** [comment]
I meant the tftpd on your xCAT MN.

The tftpd is enabled xcatd automatically when starting the xcat service. 

# ps -elf | grep tftp
1 S root      9931     1  0  80   0 -  2729 poll_s Feb01 ?        00:00:00 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf

**Comment by SirRollen** [comment]
Checked TFTP and it is running. I want to start this from scratch and I have a deadline to meet on thursday. Is it possible I could acquire a dev that can help me run through the initial setup process and answer questions related to the hardware we are working with? If not can you the most up to date document on BMC server board systems for arch x86_x64? 

Our goal is to do a stateless boot for diagnostic of the hardware. I've managed to get to the point where I can manually control a node by manually entering the mac address but this is too time consuming.

**Comment by daniceexi** [comment]
@SirRollen You already got the correct doc we have now.

Continue to discuss your issue, see my question.  I need the information whether the xnba has been downloaded to your compute node.
~~~~
Could you search the tftp keyword in the syslog? You should see the download of xcat/xnba.* file through tftp if the dhcp configuration was correct.
~~~~

**Comment by SirRollen** [comment]
I'm gonna follow all the steps from scratch and If that problem persists I'll come back to it. Do I need to permanently set a domain name before installing xCAT? I tried domainname my.domain and everytime I reboot I lose the domainname. What is the preffered method to set it permanently so xCAT configures correctly.

**Comment by daniceexi** [comment]
Try the setting in /etc/hostname or /etc/sysconfig/network.

**Comment by SirRollen** [comment]
/etc/sysconfig/network

1. NETWORKING=yes
2.HOSTNAME="mgt.cluster"
3.NISTDOMAIN=cluster

/etc/hostname

1. mgt.cluster


Is this correct syntax for these?

**Comment by SirRollen** [comment]
- [root@mgt ~]# tabdump site
- [root@mgt ~]# tabdump site
- #key,value,comments,disable
- "blademaxp","64",,
- "fsptimeout","0",,
- "installdir","/install",,
- "ipmimaxp","64",,
- "ipmiretries","3",,
- "ipmitimeout","2",,
- "consoleondemand","no",,
- "master","192.168.70.254",,
- "nameservers","192.168.70.254",,
- "maxssh","8",,
- "ppcmaxp","64",,
- "ppcretry","3",,
- "ppctimeout","0",,
- "powerinterval","0",,
- "syspowerinterval","0",,
- "sharedtftp","1",,
- "SNsyncfiledir","/var/xcat/syncfiles",,
- "nodesyncfiledir","/var/xcat/node/syncfiles",,
- "tftpdir","/tftpboot",,
- "xcatdport","3001",,
- "xcatiport","3002",,
- "xcatconfdir","/etc/xcat",,
- "timezone","America/New_York",,
- "useNmapfromMN","no",,
- "enableASMI","no",,
- "db2installloc","/mntdb2",,
- "databaseloc","/var/lib",,
- "sshbetweennodes","ALLGROUPS",,
- "dnshandler","ddns",,
- "vsftp","n",,
- "cleanupxcatpost","no",,
- "dhcplease","43200",,
- "auditnosyslog","0",,
- "xcatsslversion","TLSv1",,
- "domain","cluster",,
- "forwarders","192.168.70.254",,
- "dhcpinterfaces","mgt|enp0s3",,
- [root@mgt ~]# tabdump networks
- #netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
- "192_168_70_0-255_255_255_0","192.168.70.0","255.255.255.0","enp0s3","192.168.70.253","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.1-192.168.70.150",,,,,,,,
- "192_168_122_0-255_255_255_0","192.168.122.0","255.255.255.0","virbr0","<xcatmaster>",,"192.168.122.1",,,,"192.168.122.1-192.168.122.254",,,,,,,,
- [root@mgt ~]# tabdump passwd
- #key,username,password,cryptmethod,authdomain,comments,disable
- "hmc","hscroot","abc123",,,,
- "blade","USERID","PASSW0RD",,,,
- "ipmi","USERID","PASSW0RD",,,,
- "omapi","xcat_key","MlZxU0N4Rnc1V3RTNWZtWGJBS1BSdVdjMkRiYnpXblA=",,,,
- [root@mgt ~]# cat /etc/resolv.conf
- # Generated by NetworkManager
- search 192.168.70.254 cluster
- nameserver 192.168.70.254
- [root@mgt ~]# cat /etc/dhcp/dhcpd.conf
- #xCAT generated dhcp configuration
- 
- option conf-file code 209 = text;
- option space isan;
- option isan-encap-opts code 43 = encapsulate isan;
- option isan.iqn code 203 = string;
- option isan.root-path code 201 = string;
- option space gpxe;
- option gpxe-encap-opts code 175 = encapsulate gpxe;
- option gpxe.bus-id code 177 = string;
- option user-class-identifier code 77 = string;
- option gpxe.no-pxedhcp code 176 = unsigned integer 8;
- option tcode code 101 = text;
- option iscsi-initiator-iqn code 203 = string;
- ddns-update-style interim;
- ignore client-updates;
- option client-architecture code 93 = unsigned integer 16;
- option tcode "America/New_York";
- option gpxe.no-pxedhcp 1;
- 
- omapi-port 7911;
- key xcat_key {
-   algorithm hmac-md5;
-   secret "MlZxU0N4Rnc1V3RTNWZtWGJBS1BSdVdjMkRiYnpXblA=";
- };
- omapi-key xcat_key;
- class "pxe" {
-    match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
-    ddns-updates off;
-     max-lease-time 600;
- }
- shared-network enp0s3 {
-   subnet 192.168.70.0 netmask 255.255.255.0 {
-     authoritative;
-     max-lease-time 43200;
-     min-lease-time 43200;
-     default-lease-time 43200;
-     option routers  192.168.70.253;
-     next-server  192.168.70.254;
-     option log-servers 192.168.70.254;
-     option ntp-servers 192.168.70.254;
-     option domain-name "cluster";
-     option domain-name-servers  192.168.70.254;
-     option domain-search  "cluster";
-     zone cluster. {
-    primary 192.168.70.254; key xcat_key; 
-  }
- zone 70.168.192.IN-ADDR.ARPA. {
-    primary 192.168.70.254; key xcat_key; 
-  }
-     if option user-class-identifier = "xNBA" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent
-        always-broadcast on;
-        filename = "http://192.168.70.254/tftpboot/xcat/xnba/nets/192.168.70.0_24";
-     } else if option user-class-identifier = "xNBA" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent
-        filename = "http://192.168.70.254/tftpboot/xcat/xnba/nets/192.168.70.0_24.uefi";
-     } else if option client-architecture = 00:00  { #x86
-       filename "xcat/xnba.kpxe";
-     } else if option vendor-class-identifier = "Etherboot-5.4"  { #x86
-       filename "xcat/xnba.kpxe";
-     } else if option client-architecture = 00:07 { #x86_64 uefi
-        filename "xcat/xnba.efi";
-     } else if option client-architecture = 00:09 { #x86_64 uefi alternative id
-        filename "xcat/xnba.efi";
-     } else if option client-architecture = 00:02 { #ia64
-        filename "elilo.efi";
-     } else if option client-architecture = 00:0e { #OPAL-v3
-        option conf-file = "http://192.168.70.254/tftpboot/pxelinux.cfg/p/192.168.70.0_24";
-     } else if substring(filename,0,1) = null { #otherwise, provide yaboot if the client isn't specific
-        filename "/yaboot";
-     }
-     range dynamic-bootp 192.168.70.1 192.168.70.150;
-   } # 192.168.70.0/255.255.255.0 subnet_end
- } # enp0s3 nic_end
- [root@mgt ~]# nslookup mgt
- Server:		192.168.70.254
- Address:	192.168.70.254#53
- 
- Name:	mgt.cluster
- Address: 192.168.70.254
- 
- [root@mgt ~]# 
- 
- 
-

**Comment by SirRollen** [comment]
```
[root@mgt ~]# tabdump site
[root@mgt ~]# tabdump site
#key,value,comments,disable
"blademaxp","64",,
"fsptimeout","0",,
"installdir","/install",,
"ipmimaxp","64",,
"ipmiretries","3",,
"ipmitimeout","2",,
"consoleondemand","no",,
"master","192.168.70.254",,
"nameservers","192.168.70.254",,
"maxssh","8",,
"ppcmaxp","64",,
"ppcretry","3",,
"ppctimeout","0",,
"powerinterval","0",,
"syspowerinterval","0",,
"sharedtftp","1",,
"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,
"tftpdir","/tftpboot",,
"xcatdport","3001",,
"xcatiport","3002",,
"xcatconfdir","/etc/xcat",,
"timezone","America/New_York",,
"useNmapfromMN","no",,
"enableASMI","no",,
"db2installloc","/mntdb2",,
"databaseloc","/var/lib",,
"sshbetweennodes","ALLGROUPS",,
"dnshandler","ddns",,
"vsftp","n",,
"cleanupxcatpost","no",,
"dhcplease","43200",,
"auditnosyslog","0",,
"xcatsslversion","TLSv1",,
"domain","cluster",,
"forwarders","192.168.70.254",,
"dhcpinterfaces","mgt|enp0s3",,
[root@mgt ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"192_168_70_0-255_255_255_0","192.168.70.0","255.255.255.0","enp0s3","192.168.70.253","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.254","192.168.70.1-192.168.70.150",,,,,,,,
"192_168_122_0-255_255_255_0","192.168.122.0","255.255.255.0","virbr0","<xcatmaster>",,"192.168.122.1",,,,"192.168.122.1-192.168.122.254",,,,,,,,
[root@mgt ~]# tabdump passwd
#key,username,password,cryptmethod,authdomain,comments,disable
"hmc","hscroot","abc123",,,,
"blade","USERID","PASSW0RD",,,,
"ipmi","USERID","PASSW0RD",,,,
"omapi","xcat_key","MlZxU0N4Rnc1V3RTNWZtWGJBS1BSdVdjMkRiYnpXblA=",,,,
[root@mgt ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search 192.168.70.254 cluster
nameserver 192.168.70.254
[root@mgt ~]# cat /etc/dhcp/dhcpd.conf
#xCAT generated dhcp configuration

option conf-file code 209 = text;
option space isan;
option isan-encap-opts code 43 = encapsulate isan;
option isan.iqn code 203 = string;
option isan.root-path code 201 = string;
option space gpxe;
option gpxe-encap-opts code 175 = encapsulate gpxe;
option gpxe.bus-id code 177 = string;
option user-class-identifier code 77 = string;
option gpxe.no-pxedhcp code 176 = unsigned integer 8;
option tcode code 101 = text;
option iscsi-initiator-iqn code 203 = string;
ddns-update-style interim;
ignore client-updates;
option client-architecture code 93 = unsigned integer 16;
option tcode "America/New_York";
option gpxe.no-pxedhcp 1;

omapi-port 7911;
key xcat_key {
  algorithm hmac-md5;
  secret "MlZxU0N4Rnc1V3RTNWZtWGJBS1BSdVdjMkRiYnpXblA=";
};
omapi-key xcat_key;
class "pxe" {
   match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
   ddns-updates off;
    max-lease-time 600;
}
shared-network enp0s3 {
  subnet 192.168.70.0 netmask 255.255.255.0 {
    authoritative;
    max-lease-time 43200;
    min-lease-time 43200;
    default-lease-time 43200;
    option routers  192.168.70.253;
    next-server  192.168.70.254;
    option log-servers 192.168.70.254;
    option ntp-servers 192.168.70.254;
    option domain-name "cluster";
    option domain-name-servers  192.168.70.254;
    option domain-search  "cluster";
    zone cluster. {
   primary 192.168.70.254; key xcat_key; 
 }
zone 70.168.192.IN-ADDR.ARPA. {
   primary 192.168.70.254; key xcat_key; 
 }
    if option user-class-identifier = "xNBA" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent
       always-broadcast on;
       filename = "http://192.168.70.254/tftpboot/xcat/xnba/nets/192.168.70.0_24";
    } else if option user-class-identifier = "xNBA" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent
       filename = "http://192.168.70.254/tftpboot/xcat/xnba/nets/192.168.70.0_24.uefi";
    } else if option client-architecture = 00:00  { #x86
      filename "xcat/xnba.kpxe";
    } else if option vendor-class-identifier = "Etherboot-5.4"  { #x86
      filename "xcat/xnba.kpxe";
    } else if option client-architecture = 00:07 { #x86_64 uefi
       filename "xcat/xnba.efi";
    } else if option client-architecture = 00:09 { #x86_64 uefi alternative id
       filename "xcat/xnba.efi";
    } else if option client-architecture = 00:02 { #ia64
       filename "elilo.efi";
    } else if option client-architecture = 00:0e { #OPAL-v3
       option conf-file = "http://192.168.70.254/tftpboot/pxelinux.cfg/p/192.168.70.0_24";
    } else if substring(filename,0,1) = null { #otherwise, provide yaboot if the client isn't specific
       filename "/yaboot";
    }
    range dynamic-bootp 192.168.70.1 192.168.70.150;
  } # 192.168.70.0/255.255.255.0 subnet_end
} # enp0s3 nic_end
[root@mgt ~]# nslookup mgt
Server:		192.168.70.254
Address:	192.168.70.254#53

Name:	mgt.cluster
Address: 192.168.70.254

[root@mgt ~]# 



```

**Comment by SirRollen** [comment]
Here's the entire configuration of the management. Am I missing anything before I move on? Should I check any other outputs? DNS is working and DHCP is confirmed as well. SELINUX is disabled.

**Comment by SirRollen** [comment]
```
[root@shimgt ~]# ps -elf | grep tftp
1 S root      2308     1  0  80   0 -  2735 poll_s 11:24 ?        00:00:00 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf
0 R root      4693  3343  0  80   0 - 28161 -      11:33 pts/0    00:00:00 grep --color=auto tftp
[root@shimgt ~]# 

```

**Comment by SirRollen** [comment]
```
[root@mgt xcat]# cat cluster.log
Mar 16 10:07:47 mgt xcat: Install: syslog setup
Mar 16 10:07:49 mgt xcat[7254]: Error on restart xinetd
Mar 16 10:07:49 mgt xcat[7280]: INFO xcatd: command log process 7280 start
Mar 16 10:07:56 mgt xcat[7522]: xCAT: Allowing mknb x86_64 for root from localhost
Mar 16 10:17:10 mgt xcat[9597]: xCAT: Allowing lsxcatd -a for root from localhost
Mar 16 10:18:10 mgt xcat[9617]: xCAT: Allowing tabdump site for root from localhost
Mar 16 10:19:16 mgt xcat[9638]: xCAT: Allowing chdef -t site domain=cluster for root from localhost
Mar 16 10:19:36 mgt xcat[9656]: xCAT: Allowing chdef -t site forwarders=192.168.70.253 for root from localhost
Mar 16 10:19:45 mgt xcat[9666]: xCAT: Allowing chdef -t site forwarders=192.168.70.254 for root from localhost
Mar 16 10:19:53 mgt xcat[9684]: xCAT: Allowing tabdump site for root from localhost
Mar 16 10:20:16 mgt xcat[9701]: xCAT: Allowing makedns -n for root from localhost
Mar 16 10:24:39 mgt xcat[9932]: xCAT: Allowing tabdump networks for root from localhost
Mar 16 10:31:14 mgt xcat[10931]: xCAT: Allowing makedhcp -n for root from localhost
Mar 16 10:31:43 mgt xcat[10974]: xCAT: Allowing tabdump networks for root from localhost
Mar 16 10:35:10 mgt xcat[11053]: xCAT: Allowing tabrestore for root from localhost
Mar 16 10:35:15 mgt xcat[11064]: xCAT: Allowing makedhcp -n for root from localhost
Mar 16 10:37:57 mgt xcat[11127]: xCAT: Allowing chdef -t site dhcpinterfaces=mgt|enp0s3 for root from localhost
Mar 16 10:38:14 mgt xcat[11137]: xCAT: Allowing makedhcp -n for root from localhost
Mar 16 10:41:53 mgt xcat[11286]: xCAT: Allowing tabdump passwd for root from localhost
Mar 16 10:42:55 mgt xcat[11314]: xCAT: Allowing rpower for root from localhost
Mar 16 10:46:12 mgt xcat[11342]: xCAT: Allowing nodegrpch flex hosts.ip=|192.168.70.($1)| for root from localhost
Mar 16 10:47:03 mgt xcat[11386]: xCAT: Allowing lsdef -t flex for root from localhost
Mar 16 10:47:08 mgt xcat[11396]: xCAT: Allowing lsdef -t group flex for root from localhost
Mar 16 10:47:13 mgt xcat[11406]: xCAT: Allowing lsdef -t node flex for root from localhost
Mar 16 11:22:46 mgt xcat[12776]: xCAT: Allowing tabdump site for root from localhost
Mar 16 11:24:11 mgt xcat[2313]: INFO xcatd: command log process 2313 start
Mar 16 11:24:38 mgt xcat[3394]: xCAT: Allowing tabdump site for root from localhost
Mar 16 11:26:49 mgt xcat[3849]: xCAT: Allowing tabdump network for root from localhost
Mar 16 11:26:52 mgt xcat[3859]: xCAT: Allowing tabdump networks for root from localhost
Mar 16 11:27:29 mgt xcat[3991]: xCAT: Allowing tabdump passwd for root from localhost
[root@mgt xcat]# 

```

**Comment by daniceexi** [comment]
Could you send me (wxp@cn.ibm.com) the log file /var/log/messages, /var/log/httpd/access_log and /var/log/httpd/error_log?

**Comment by SirRollen** [comment]
I just e-mailed them to you.

**Comment by SirRollen** [comment]
Hello daniceexi have you been able to take a look at this?...

**Comment by daniceexi** [comment]
@SirRollen Sorry for the later response. From the syslog message that you enabled the dnsmasq on your xCAT MN. dnsmasq does similar as dhcpd, so it used the dhcp port. Then I guess your dhcpd does not work. What could you see when run **systemctl restart dhcpd** and **systemctl status dhcpd**?

I also saw a dynamic ip range was configured for dnsmasq, was there any specific reason to do that?

**Comment by daniceexi** [comment]
No update from the @SirRollen, move it to 2.13.

**Comment by whowutwut** [comment]
No response for some time, will close.  Feel free to re-open if needed.
