### ISSUE TITLE
Where is the description of partitionfile within man pages?

### ISSUE THREAD

**Issue by astrophys** [xcat2/xcat-core#7263]
I am trying to follow the instructions on [Configuring Disk Partition ](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_partition.html).  I'm using xcat-2.16.3 and my osimages are RHEL-8.4.  One of the suggested commands is 

`chdef -t osimage <osimagename> partitionfile=/install/custom/my-partitions`

QUESTION : 
1. When I look at the man page for either `osimage` or `chdef`, I see no mention of the `partitionfile` option.  Where would `partitionfile` be documented in the man pages?

**Comment by gurevichmark** [comment]
You will find it in the `osimage` object definition by `man 7 osimage`

**Comment by astrophys** [comment]
That's exactly what I wanted.  Thanks!
