### ISSUE TITLE
hostname mentioned in node object not set in pxe boot node

### ISSUE THREAD

**Issue by abhishek-sa1** [xcat2/xcat-core#7288]
`hostnames` mentioned `node1.dev.cluster` in node object `node1` not set in pxe booted server. Refer to screenshot below

**Node object:**
![image](https://user-images.githubusercontent.com/94038029/202626683-b1ef268a-a52e-40bb-be0d-0ead456641cd.png)

**PXE booted server where hostname not changed(domain name not added):**
![image](https://user-images.githubusercontent.com/94038029/202626718-57186c44-984f-40e6-96ec-348e96942925.png)

**Comment by jdo13** [comment]
See this link:
(https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html)
