### ISSUE TITLE
Deployment hangs and then reboots

### ISSUE THREAD

**Issue by urielrosen1981** [xcat2/xcat-core#7305]
Hi ,

I am having issues with installing rocky linux 8.5 on fujitsu PRIMERGY RX2540 M6 server.
after pxe boot is successful and deployment starts install hangs and reboots at various places in anaconda installer  such as 
"started  service enabling compressing RAM with zRam" and "started pre-anaconda logging service" , I am using the follwing xcat version,
any help will be highly appreciated.
 

lsxcatd -a
Version 2.16.4 (git commit bb7a4bbbc8bde7e6613558d8d039fe43d49d2079, built Mon Jun 13 08:53:10 EDT 2022)
This is a Management Node
dbengine=SQLite

**Comment by urielrosen1981** [comment]
Hi , 
I was able to access the node's log (/tmp/anaconda.log ) and this is what I see(link below)
https://drive.google.com/file/d/14y1EvMogxgYxW5Nhni1DvvByq-dbEjq-/view?usp=share_link

I see failure with downloading packages like wget and python , is this the reason for the failure of all deployment?
if not please direct me where to look while deployment is being committed.

**Comment by urielrosen1981** [comment]
update:

I was able to install the os using Rocky-8.5-x86_64-dvd1.iso but not the minimal iso .

**Comment by besawn** [comment]
I'm glad you were able to diagnose the root cause of your problem. Can this issue be closed now that the problem has been resolved?

**Comment by urielrosen1981** [comment]
Hi ,

closed , thanks for your reply.
