### ISSUE TITLE
Upgrade to RHEL8.5 on computes

### ISSUE THREAD

**Issue by Wasimwani1** [xcat2/xcat-core#7308]
Greetings

We have a cluster of 2500 nodes. The management node on the cluster is running RHEL 7.7 and xCAT 2.15.1. The computes are on RHEL7.9. We are no planning to upgrade the OS on computes to RHEL8.5 0r later. My question is will the xCAT version on the management node support this change and what changes are required in xCAT to do this.

Our blades are mostly intel S2600BP with 32 nodes being from Supermicro which have Nvidia GPU’s in them. Also will the blades support this change. Thank You

Regards
Wasim

**Comment by gurevichmark** [comment]
@Wasimwani1 RHEL8.5 support was added with xCAT 2.16.4
https://xcat-docs.readthedocs.io/en/latest/overview/xcat2_release.html

If your compute nodes are diskfull, your management node running RHEL 7.7 and xCAT 2.16.4 most likely be able to provision RHEL8.5 compute nodes. If your compute nodes are diskless, your management node will need to be RHEL 8.0 or later in order to generate a diskless image.

With a cluster of that size, we would recommend doing a small scale experiment first, if possible.

**Comment by Wasimwani1** [comment]
> @Wasimwani1 RHEL8.5 support was added with xCAT 2.16.4 https://xcat-docs.readthedocs.io/en/latest/overview/xcat2_release.html
> 
> If your compute nodes are diskfull, your management node running RHEL 7.7 and xCAT 2.16.4 most likely be able to provision RHEL8.5 compute nodes. If your compute nodes are diskless, your management node will need to be RHEL 8.0 or later in order to generate a diskless image.
> 
> With a cluster of that size, we would recommend doing a small scale experiment first, if possible.

**Comment by Wasimwani1** [comment]
> @Wasimwani1 RHEL8.5 support was added with xCAT 2.16.4 https://xcat-docs.readthedocs.io/en/latest/overview/xcat2_release.html
> 
> If your compute nodes are diskfull, your management node running RHEL 7.7 and xCAT 2.16.4 most likely be able to provision RHEL8.5 compute nodes. If your compute nodes are diskless, your management node will need to be RHEL 8.0 or later in order to generate a diskless image.
> 
> With a cluster of that size, we would recommend doing a small scale experiment first, if possible.



> @Wasimwani1 RHEL8.5 support was added with xCAT 2.16.4 https://xcat-docs.readthedocs.io/en/latest/overview/xcat2_release.html
> 
> If your compute nodes are diskfull, your management node running RHEL 7.7 and xCAT 2.16.4 most likely be able to provision RHEL8.5 compute nodes. If your compute nodes are diskless, your management node will need to be RHEL 8.0 or later in order to generate a diskless image.
> 
> With a cluster of that size, we would recommend doing a small scale experiment first, if possible.

@gurevichmark thank you for your response so do you mean we should first upgrade xCAT to 2.16.4 from 2.15.1 then move the compute nodes to RHEL8.5. I tried to test one blade and changed its kickstart file and definitions in Xcat but the node just stalls.

**Comment by Wasimwani1** [comment]
> @Wasimwani1 RHEL8.5 support was added with xCAT 2.16.4 https://xcat-docs.readthedocs.io/en/latest/overview/xcat2_release.html
> 
> If your compute nodes are diskfull, your management node running RHEL 7.7 and xCAT 2.16.4 most likely be able to provision RHEL8.5 compute nodes. If your compute nodes are diskless, your management node will need to be RHEL 8.0 or later in order to generate a diskless image.
> 
> With a cluster of that size, we would recommend doing a small scale experiment first, if possible.

Also our nodes are disk full not disk less.

**Comment by gurevichmark** [comment]
@Wasimwani1 Is this a hierarchical cluster with service nodes ?

**Comment by Wasimwani1** [comment]
> @Wasimwani1 Is this a hierarchical cluster with service nodes ?

@gurevichmark  yes it is. Sorry for the late response.

**Comment by gurevichmark** [comment]
@Wasimwani1 
Are the service nodes also running RHEL 7.7 and xCAT 2.15.1

**Comment by Wasimwani1** [comment]
@gurevichmark  Hi, Thank You for all the help you provided. so i upgraded the main management node from xCAT 2.15.1 to 2.16.4 running RHEL 7.7 did not upgrade the OS and upgraded RHEL on compute/service on one service node for test from RHEL7.9 to RHEL8.5 and it worked perfectly fine since my nodes have 8TB HDD in them. I will now schedule this upgrade one by one on all my computes once they are free. Answering your question no by service nodes i mean computes are on RHEL7.9 they dont have xCAT installed on them. We only have xCAT on two management nodes which are redundant.

Regards
Wasim

**Comment by gurevichmark** [comment]
@Wasimwani1 
Glad to hear it all worked for you.

Maybe we had a terminology miscommunication. Hierarchical cluster refers to a cluster with a management node and several service nodes where each service node installs/manages a specific set of compute nodes (https://xcat-docs.readthedocs.io/en/stable/advanced/hierarchy/index.html). It sounds like you do not have that configuration and in your cluster the management node directly installs/manages compute nodes.

You have done the right steps of upgrading. Please close this issue if all your questions have been resolved.
