### ISSUE TITLE
RFC: `bmcport` meaning for Dell servers doesn't match documentation

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#7316]
In [`bmcsetup`](https://github.com/xcat2/xcat-core/blob/master/xCAT-genesis-scripts/usr/bin/bmcsetup), the meaning of `bmcport` for Dell servers is not the same as for the rest of IBM hardware, and doesn't match the documentation.

The [docs](https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/ipmi.5.html?highlight=ipmi#ipmi-attributes) state:
> **bmcport**
> In systems with selectable shared/dedicated ethernet ports, this parameter can be used to specify the preferred port. 0 means use the shared port, 1 means dedicated, blank is to not assign.

but in the `bmcsetup` script, we have this:
https://github.com/xcat2/xcat-core/blob/43c3a768919ccea0352aadeb5ddaa47ca9f08c7e/xCAT-genesis-scripts/usr/bin/bmcsetup#L262-L267
where 0 means dedicated, and 1 means shared with LOM1.

In a sense, the current script is more specific and flexible, as it allows sysadmins to specify more fine-grained options for their BMC config, but on he other hand, it's opposite to the default 0=shared, 1=dedicated meaning.

What would be the best approach to resolve this contradiction? Include the special case for Dell servers in the documentation, or change the `bmcsetup` script to use the same meaning for `bmcport` everywhere?

I believe it would be better to have a consistent way to configure a shared interface across multiple node types, rather than having nodes using `bmcport=1` and `bmcport=0` for the same configuration, and let users with more specific requirements handle the BMC port configuration separately. It would also make easier to include support for more node types / manufacturers.

What do you think?
In both cases, I can submit a PR.

**Comment by kcgthb** [comment]
A PR to realign the meaning of `bmcport` on Dell servers with other system types is in #7317

**Comment by Obihoernchen** [comment]
Merged #7317
