### ISSUE TITLE
genimage on SLES 15.4 fails to build initrd files

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/xcat-core#7340]
When testing an upgrade from SLES 15.3 to 15.4 we found `genimage` would not create the disk-less initrd files.
xCAT version is: 2.16.3.
When we examined the genimage output we could see:

```dracut: Executing: /usr/bin/dracut -N --compress "/usr/bin/pigz -p 48 " -f /tmp/initrd.29026.gz 5.14.21-150400.24.38-default
dracut: dracut module 'xcat' cannot be found or installed.
Error: failed to generate the initial ramdisk for stateless.
Error: [xcat001]: Command failed: cd /opt/xcat/share/xcat/netboot/sles; ./genimage -a x86_64 -o sles15.4 -p compute-2023-01-11 --permission 755 --srcdir "/install/sles15.4/x86_64" --pkglist /install/custom/netboot/sles/compute-2023-01-11.pkglist --otherpkgdir "/install/post/otherpkgs/sles15.4/x86_64" --postinstall "/install/custom/netboot/sles/compute-2023-01-11.postinstall" --rootimgdir /var/xcat/osimage/custom/netboot/compute-2023-01-11 --tempfile /tmp/xcat_genimage.28977 --timezone Europe/Berlin compute-2023-01-11 2>&1. Error message: Adding repository 'sles15.4-0-Product-SLES' [......done]
```

When we looked at the code we found the `/opt/xcat/share/xcat/netboot/sles/genimage` script is failing in the chroot command to determine the dracut version in the disk-less image, specifically in the awk command part.

```
    # get dracut version
    $dracutver = `chroot $rootimg_dir rpm -qi dracut | awk '/Version/{print \$3}'     `;
    chomp($dracutver);
    if ($dracutver =~ /^\d\d\d$/) {
        if ($dracutver >= "033") {
            $dracutdir = "dracut_033";
        } else {
            $dracutdir = "dracut";    # The default directory
        }
    }
```

Only the `dracut_033` directory exists in /opt/xcat/share/xcat/netboot/sles/ and as the script fails to determine the correct  dracut version no files from the correct "dracut" directory are copied into the initrd directory file thus the initrd build fails.
(looking for the genimage error `dracut module 'xcat' cannot be found or installed.` is the hint these files are missing from the initrd build).

The dracut rpm version in the disk-less image is a bit strange: `dracut-055+suse.323.gca0e74f0-150400.3.13.1.x86_64`

As a workaround you can alter the genimage script to hard-code the dracut version but we also found a slight alteration to the awk command works :
Old command:  `chroot $rootimg_dir rpm -qi dracut | awk '/Version/{print \$3} `
New command: `chroot $rootimg_dir rpm -qi dracut | awk '/Version/ {print $3}' | awk -F[.+] '{print $1}'`

**Comment by gurevichmark** [comment]
@dbrajendra 
Thank you for your contribution.
Your suggested fix will be added under #7344
