### ISSUE TITLE
otherpkgs with rhel9 overrides the OS packages repo wrongly (xCAT 2.16.5)

### ISSUE THREAD

**Issue by bermang** [xcat2/xcat-core#7346]
Hello,

Simple bug - otherpkgs looks specifically for rhel8* to create the BaseOS and AppStream repositories. For rhel9 it treat the repo similar to earlier rhel versions and creates a single repo like below - 
```
# cat /etc/yum.repos.d/xCAT-rhels9.1.0-path0.repo
[xCAT-rhels9.1.0-path0]
name=xCAT-rhels9.1.0-path0
baseurl=http://11.11.32.53:80/install/rhels9.1.0/x86_64
enabled=1
gpgcheck=0
skip_if_unavailable=True
```

The fix is easy, just by adding rhel9 to the code blocks like below. Happy to do it and submit a pull request, but since my ability to test is very limited, maybe such easy fixes better done by the xCAT team (also the complicated ones, but this is obvious) 

  ```
elif ( pmatch "$OSVER" "rhels8*" ||
                       pmatch "$OSVER" "centos8*" ||
                       pmatch "$OSVER" "rocky8*" ||
                       pmatch "$OSVER" "alma8*" ||
                       pmatch "$OSVER" "ol8*"); then
                     # for rhels8, centos8, ol8, alma8 and rocky8 the repodata is in ./BaseOS, ./AppStream, not in ./
                     for arg in "BaseOS" "AppStream"
```

**Comment by gurevichmark** [comment]
@bermang Thank you for reporting this.

I think this is a problem with `otherpkgs` and `ospkgs` postscripts ?
I will make a PR to fix them both;

**Comment by bermang** [comment]
THX!! I have not looked into ospkgs honestly, but after standard install the OS repo looks ok (one for BaseOS and one for AppStrem).
