### ISSUE TITLE
[Customer]SLES12.1 issue

### ISSUE THREAD

**Issue by JBBIntel** [xcat2/xcat-core#735]
I have been trying to build an osimage for SLES12.1. genimage was failing, because zipper couldn't find gcc-fortran. Apparently that rpm is in the Software Development version of SLES 12.1. When copycds loads that DVD image, it calls the resulting directory sdk1, instead of just 1. genimage hard-codes the 1 directory name, and does not see the sdk1 directory.
I was able to get around this, by running copycds on both the Server and Software devel DVDs, and modifying genimage so that it loads both as repos. But I am wondering why you did not encounter this problem in your testing.
I am running xCAT 2.9.1 under RHEL 7.0.

**Comment by daniceexi** [comment]
Looks like it's the issue of installing package from sdk media when run genimage. @cxhong Could you take a look of this issue?

**Comment by tingtli** [comment]
Does genimage for SLES12.1 on RH7 work?  I am wondering that?

**Comment by daniceexi** [comment]
@JBBIntel You said you worked around it by change something in genimage, I guess the server to run the genimage is sles too, right?

**Comment by whowutwut** [comment]
@cxhong, @pdlun92 made some fixes to copycds in the 2.11/2.12 branch that allowed us to copy the SLES 12 SDK isos correctly.  pull request: #404  We also want to verify that genimage does the right thing for the SDK in the latest release... then potentially fix this in the 2.9 branch.

@JBBIntel , do you have plans to upgrading the xCAT to a more recent release? It seems like you have patched your system already....  We could make a fix for 2.9 branch but there currently is no plan to refresh the code for Linux.. only for AIX.

**Comment by cxhong** [comment]
on the current release, copycds sles12.1 server will create
```
/install/sles12.1/ppc64le/1
```
and copycds sles12.1 SDK will create
```
/install/sles12.1/ppc64le/sdk1 
```
'Then genimage will created two repository
```
1) file:/install/sles12.1/ppc64le/1
2) file:/install/sles12.1/ppc64le/sdk1
```
After I added gcc-fortran to package list,  It found  this package, but failed at:
```
Problem: nothing provides gcc48 = 4.8.5-24.1 needed by gcc48-fortran-4.8.5-24.1.ppc64le
 Solution 1: do not install gcc-fortran-4.8-6.189.ppc64le
 Solution 2: break gcc48-fortran-4.8.5-24.1.ppc64le by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
zypper invocation failed with rc: 4.
```
will looking into this.

**Comment by JBBIntel** [comment]
Thanks for the quick response.

Yes, I am running the genimage on a virtual machine running SLES 12.

Thinking about the matter further, it occurs to me that one way of looking at it is that SLES has moved gcc-fortran out of the Server install package. That means that from an xCAT perspective, gcc-fortran is now an “otherpackage”, and should be treated accordingly. So, xCAT works as designed.

On the other hand, gcc-fortran is a part of the Software Development flavor of SLES 12.1, so it should load as part of the base package. I guess the SLES folks have chosen a path that does not precisely fit the xCAT model.

In any case, it seemed to me that genimage should not hard-code the directory to 1 if copycds is building a directory called sdk1. Even if SLES assigned the directory name, xCAT is treating it inconsistently. This is not a show-stopper for us, but I wanted to bring it to your attention.

Thanks again for the quick response.

   Jerome

**Comment by cxhong** [comment]
@JBBIntel    
if  the osimage defined 
```
pkgdir=/install/sles12.1/ppc64le
```
and  if you ran copycds for both server and SDK iso files,  and those two dir should be created:
```
 # ls -ltr /install/sles12.1/ppc64le
total 64
drwxr-xr-x 1 root root 520 Oct 21 15:23 1
drwxr-xr-x 1 root root 442 Feb 23 10:42 sdk1
```
then genimage will created both repository,  one for the base server and one for SDK.  gcc-fortran is in the SDK.

**Comment by JBBIntel** [comment]
I do not recognize ppc641e, but copycds made those directories in sles12.1/x86_64. Different architecture.

But genimage does not read sdk1. It only looks for 1.

My xCAT is version 2.9.1. Has this been fixed in a later version?

From genimage;

       # To support multiple paths for osimage.pkgdir
       foreach $dir (@pkgdirs) {
           if( -d "$dir/1") {
               $dir .= "/1";
           }
           system("zypper -R $rootimg_dir $non_interactive ar file:$dir $osver-$i");
           $i++;
       }

**Comment by cxhong** [comment]
oh, sorry.  ppc64le is power little endian system.  I will looking sles12.1 for x86_64.

**Comment by cxhong** [comment]
@JBBIntel , we didn't official support sles12.1 for xcat 2.9.1 release.  There was copycds issue we fixed at later release as @whowutwut mentioned.  when you ran copycds for SDK iso, it went into /install/sles12/x86_64/sdk1
````
 # copycds SLE-12-SP1-SDK-DVD-x86_64-GM-DVD1.iso
Copying media to /install/sles12/x86_64/sdk1
Media copy operation successful
# copycds SLE-12-SP1-Server-DVD-x86_64-GM-DVD1.iso
Error: copycds could not identify the ISO supplied, you may wish to try -n <osver>
````
if you used -n options for Server iso, make sure SDK and Server package are under same /install/<osver>/x86_64 as pkgdir defined for the osimage.
````
# copycds SLE-12-SP1-SDK-DVD-x86_64-GM-DVD1.iso -n sles12.1
Copying media to /install/sles12.1/x86_64/sdk1
Media copy operation successful
# copycds SLE-12-SP1-Server-DVD-x86_64-GM-DVD1.iso -n sles12.1
Copying media to /install/sles12.1/x86_64/1
Media copy operation successful
````
I verified genimage to install gcc-fortran on the x86_64 system with xcat 2.9.1 release.  it worked fine.

**Comment by JBBIntel** [comment]
I have loaded the disk images using copycds;
[root@sfs-head x86_64]# ls
1  2  sdk1  sdk2

And restored the original version of genimage, before I made changes to use sdk1. When I run it, I get the error below. We are installing on a virtual machine running a stripped-down SLES12. Is it possible, that when you run genimage, it is finding gcc-fortran already installed on the machine you are using? If I modify genimage to explicitly include sdk1, it runs successfully.

Building repository 'sles12-0' cache [....done]
All repositories have been refreshed.
zypper -R /install/netboot/sles12.1/x86_64/wfrifs_10_0_0_0_697/rootimg --non-interactive --no-gpg-checks --gpg-auto-import-keys install -l --no-recommends --download-in-advance   aaa_base coreutils bash nfs-kernel-server keyutils lvm2 openssl dhcp-client openssh procps psmisc wget sysconfig rsyslog vim rsync timezone bc ntp gzip binutils tar open-iscsi curl plymouth btrfsprogs cryptsetup dmraid mdadm multipath-tools gpg2 which cifs-utils open-lldp fcoe-utils kernel-firmware util-linux-systemd kernel-default perl python python-xml python3 ypbind rpm-build zypper git-core autoconf automake libtool libltdl7 sudo perf libgfortran3 gdb ca-certificates ca-certificates-mozilla gcc-fortran gcc-c++ flex expect sysfsutils libpsm_infinipath1 tcsh libstdc++-devel rdma libibmad5 libibverbs1 pciutils librdmacm1 opensm-libs3
Loading repository data...
Reading installed packages...
Package 'gcc-fortran' not found.
chroot: failed to run command 'zic': No such file or directory

**Comment by cxhong** [comment]
what's your pkgdir defined in your osimage?  did u see sdk repository build from genimage output?
output will something like that:
```
# genimage sles12.1-x86_64-netboot-compute
Generating image:
cd /opt/xcat/share/xcat/netboot/sles; ./genimage -a x86_64 -o sles12.1 -p compute --permission 755 --srcdir "/install/sles12.1/x86_64" --pkglist /opt/xcat/share/xcat/netboot/sles/compute.sles12.x86_64.pkglist --otherpkgdir "/install/post/otherpkgs/sles12.1/x86_64" --postinstall /opt/xcat/share/xcat/netboot/sles/compute.sles12.x86_64.postinstall --rootimgdir /install/netboot/sles12.1/x86_64/compute --tempfile /tmp/xcat_genimage.4307 --timezone America/New_York sles12.1-x86_64-netboot-compute
..............
.................
Building repository 'sles12.1-0' cache [....done]
Retrieving repository 'sles12.1sdk1' metadata [.done]
Building repository 'sles12.1sdk1' cache [....done]
`````

**Comment by JBBIntel** [comment]
What I see is building repo sles12-0. Which does not surprise me, based on what I see in the genimage script. I think maybe you and I have different genimage scripts. Would you like me to e-mail my genimage to you?

….
Adding repository 'sles12-0' [......done]
Repository 'sles12-0' successfully added
Enabled: Yes
Autorefresh: No
GPG check: Yes
URI: file:/install/sles12.1/x86_64/1

Reading custom repositories
Retrieving repository 'sles12-0' metadata [.

Automatically importing the following key:

  Repository:       sles12-0
  Key Name:         SuSE Package Signing Key <build@suse.de>
  Key Fingerprint:  FEAB5025 39D846DB 2C0961CA 70AF9E81 39DB7C82
  Key Created:      Thu Jan 31 16:06:03 2013
  Key Expires:      Mon Jan 30 16:06:03 2017
  Rpm Name:         gpg-pubkey-39db7c82-510a966b


done]
Building repository 'sles12-0' cache [....done]
All repositories have been refreshed.
zypper -R /install/netboot/sles12.1/x86_64/wfrifs_10_0_0_0_

**Comment by cxhong** [comment]
well, I am not sure if we need to chase this issue.  sles12.1 is not support on xcat 2.9.1 release. and we had fixes for later release, and you had workaround too. anyway, this is my genimage on the system:
````
# ls -ltr genimage
-rwxr-xr-x 1 root root 82779 Mar 19  2015 genimage
# sum genimage
01896    81

 # lsxcatd -a
Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)
This is a Management Node
dbengine=SQLite
````

**Comment by JBBIntel** [comment]
You are correct, this is a rabbit hole ☺ I have a workaround, I just thought you might want more info. But if you are good, so am I.

**Comment by cxhong** [comment]
Thanks @JBBIntel .  I will close issue.
