### ISSUE TITLE
xcat2 version 2.9.4 on AIX with vulnerability on TLS

### ISSUE THREAD

**Issue by capacho66** [xcat2/xcat-core#7351]
Hello, 

I know we don't have more new version of xCAT2 for AIX. The last one was version 2.9.4. We are having issue with the xcatd daemon running with TLSv1.0 but our security team is requiring us to use TLSv1.2 at least
I have two option, compiling the latest release of xcat in AIX (no sure if this possible) or finding another solution

any help ?

**Comment by besawn** [comment]
Assuming the version of openssl on your system supports TLSv1.2, you can change the SSL version used by xCAT by changing the `xcatsslversion` in the site table following the instructions here:
https://xcat-docs.readthedocs.io/en/stable/advanced/security/ssl_config.html

If xCAT 2.9.4 is too old to support changing the versions using the site table, you could manually change the version by modifying `/opt/xcat/sbin/xcatd` to use the TLS version string you want to use.

The section that sets up the SSL configuration is located around this line:
`           $connection = IO::Socket::SSL->start_SSL($cnnection,`

**Comment by capacho66** [comment]
Thank you.. Let me try this..

**Comment by capacho66** [comment]
Hello besawn, 

I followed the instructions from the link you posted (Thank you) and I requested a security scan looking for the vulnerability in TLSv1.  Waiting for the report now. In the meantime, I would like to ask you one more question. The command that I ran was:

chtab key=xcatsslversion site.value=TLSv1_2

and to see if this was taken, I ran this command

gettab -H key=xcatsslversion site.value 

and the output is

site.valure: TLSv1_2

Great, right ? 

However, both command below respond ok 

openssl   s_client    -connect    localhost:3001  -tls1_2 < /dev/null 

openssl   s_client    -connect    localhost:3001  -tls1 < /dev/null 

Talking to IBM, I was told that it's up to the application to use either TLSv1 or TLSv1.2 on a system. So, I am assuming that with the change made to the xcatsslversion in the site table it is telling xcatd to use TLSv1.2 and not TLSv1. I will see if this is true once I see the report from the security scan. 

Now, one thing that I noticed since our HMC changed to TLSv1.2 is that rscan failed as follow

rscan hmc -z

hmc: The command entered is either missing a required parameter or a parameter value is invalid. The parameters that are missing or have an invalid value are -r. Please check your entry and retry the command

I looked at the man pages for rscan and there is no flag '-r'. So, I have not idea why rscan is failing but it started when the HMC updated to another version of SSL/TLS

while waiting for the security scan to finish, I wonder if you can help me with this last question *(why rscan is giving that message)?

Thanks a lot in advance...

**Comment by besawn** [comment]
@capacho66 xCAT 2.9.4 may not have support for using the `xcatsslversion` to override the default SSL version configuration.

To confirm whether it is supported on your system, look in `/opt/xcat/sbin/xcatd` and see if you can find this section that enables the `xcatsslversion` option:
https://github.com/xcat2/xcat-core/blob/master/xCAT-server/sbin/xcatd#L1553-L1569

If you don't have that section of code, you may need to patch your local copy of `/opt/xcat/sbin/xcatd` by saving a copy of the file somewhere safe so you can undo if necessary, then adding the few lines from above that enable `xcatsslversion`. Also, did you restart xcatd after changing the `xcatsslversion`? You need to restart xcatd for that change to become active.

For the HMC rscan issue, it sounds like you may have upgraded your HMC to HMC v10. This pull request may contain a fix that you need in your environment to use HMC v10:
https://github.com/xcat2/xcat-core/pull/7011

If you need to add the patch to your system, save a copy of `/opt/xcat/lib/perl/xCAT/PPCcli.pm` somewhere safe so you can undo if necessary, then add the new code from the pull request to your copy of `PPCcli.pm` and restart xcatd.

**Comment by capacho66** [comment]
Hello besawn

I got the report back from the security team and the command "chtab key=xcatsslversion site.value=TLSv1_2"  DID NOT fix the issue. See below all vulnerabilities associated with TLC and SSL ... My concern is TLC... 

![image](https://user-images.githubusercontent.com/126806841/223533985-640ebe6b-c59f-43d3-a83f-184734b98b4f.png)

SO, per your recommendations, I am going to try to modify /opt/xcat/sbin/xcatd as follow: 

----------------------------------------------------------
/start_SSL
    populate_site_hash();
    my %extrasslargs;

# --------- CHANGE - Begin


if ($::XCATSITEVALS{xcatsslversion}) { $extrasslargs{SSL_version} = $::XCATSITEVALS{xcatsslversion}; }
        $extrasslargs{SSL_version} = "SSLv23:!SSLv2:!SSLv3:!TLSv1" unless length $extrasslargs{SSL_version};

        if ($::XCATSITEVALS{xcatsslciphers}) { $extrasslargs{SSL_cipher_list} = $::XCATSITEVALS{xcatsslciphers}; }
        use Data::Dumper;

        $SIG{ALRM} = sub { $ssltimeout = 1; die; };
        eval {
            alarm(10);
            $connection = IO::Socket::SSL->start_SSL($cnnection,
                SSL_key_file    => $xcatdir . "/cert/server-cred.pem",
                SSL_cert_file   => $xcatdir . "/cert/server-cred.pem",
                SSL_ca_file     => $xcatdir . "/cert/ca.pem",
                SSL_server      => 1,
                SSL_verify_mode => 1,
                %extrasslargs,
            );

#
# ---------- CHANGE - END
    alarm(0);
    };
------------------------------


And I am requesting the scan again ...  Sorry that I don't have a clue of what those lines are... Hope you can help me ...
I really like xcat2 on AIX..

I regards to the HMC, the patch in /opt/xcat/lib/perl/xCAT/PPCcli.pm DID not help either. Here is how do they look like (see below). Do I need to recycle all xCAT ? reboot the server ? I just recycled xcatd ...

----------------------------

        if ($1 != 0) {

#
# ----------- PATCH begin
#
            return ([ RC_ERROR, $result[3] ]);
            if ($cmd =~ "lssyscfg -r frame -F") {
                # On HMC V10 the "lssyscfg -r frame -F" command returns error,
                # ON HMC V9 the same command returns "No results were found"
                # Try to catch that command here and return
                # "No results were found" like we would on V9
                return ([ NR_ERROR, "No results were found" ]);
            } else {
                return ([ RC_ERROR, $result[3] ]);
            }
#
# ----------- PATCH ends
#
        }

**Comment by besawn** [comment]
@capacho66 

> Do I need to recycle all xCAT ? reboot the server ? I just recycled xcatd
For either of these patches, just restarting xcatd should be sufficient.

For the TLS patch, you will need both the patch and the change to the site table (`chtab key=xcatsslversion site.value=TLSv1_2`), then restart xcatd.

Do you still get the same error as before for the `rscan hmc -z` command?

**Comment by capacho66** [comment]
Hello again..

Both the TLS patch and the change to the site table (**chtab key=xcatsslversion site.value=TLSv1_2**) are in place. I also re-started the xcatd and not only that, I rebooted the AIX server and the vulnerabilities (see table below) are still active. It has been a while since I made a Perl code, but I wonder if the line below doesn't need TLSv2 in it ? Also, is there a way to disable TLSv1 at all ? 

 $extrasslargs{SSL_version} = "**SSLv23:!SSLv2:!SSLv3:!TLSv1"** unless length $extrasslargs{SSL_version};

**----- vulnerabilities listening on port 3001 for TLSv1 --------------**

Secure Sockets Layer/Transport Layer Security (SSL/TLS) Server Supports Transport Layer Security (TLSv1.1)	Active	Port 3001	tcp	over ssl

Birthday attacks against TLS ciphers with 64bit block size vulnerability (Sweet32)	Active	Port 3001 	tcp	over ssl
Secure Sockets Layer/Transport Layer Security (SSL/TLS) Server supports Transport Layer Security (TLSv1.0)	Active	Port 3001	tcp	over ssl

SSL Server Has SSLv3 Enabled Vulnerability	Active	Port 3001	 tcp	over ssl

SSLv3 Padding Oracle Attack Information Disclosure Vulnerability (POODLE)	Active	Port 3001 	tcp	over ssl

Secure Sockets Layer/Transport Layer Security (SSL/TLS) Use of Weak Cipher Rivest Cipher 4 (RC4/ARC4/ARCFOUR)	Active	3001	Port tcp	over ssl

X.509 Certificate SHA1 Signature Collision Vulnerability	Active	Port 3001	 tcp	over ssl

SSL Certificate - Self-Signed Certificate	Active	Port 3001 	tcp	over ssl

----------------------------------------------

On the other hand, the command "rscan hmc -z " is still showing errors, even with patch to PPCcli.pm 

**--------- error -----**
hmcb: The command entered is either missing a required parameter or a parameter value is invalid. The parameters that are missing or have an invalid value are -r. Please check your entry and retry the command.
---------------------------

I would greatly appreciated your help.   My security department is not allowed me to use xCAT2 with these vulnerabilities. Also, the issue with rscan is prohibited me to scan the HMCs, which is a big thing..

**Comment by gurevichmark** [comment]
@capacho66 For the `rscan` command....
What version of HMC are you running ? (`lshmc -v`)

If it is V10 or later, most likely `lssyscfg -r` command is the problem.
If you look in the file `/opt/xcat/lib/perl/xCAT/PPCcli.pm` around line 30, you will see an array of `lssyscfg -r ` commands. I think one of them gets used during `rscan` and results in an error you are seeing.

Prior to V10 `-r` flag was used to indicate type of resource to list:
```
hscroot@c910hmc02:~> lssyscfg
Usage: lssyscfg -r lpar | prof | sys | sysprof | cage | frame
                [-m <managed system> | -e <managed frame>]
                [--lastvalidcfg]
                [--osrefresh]
                [--filter "<filter data>"]
                [-F [<attribute names>]]
                [--header]
                [--help]

Lists partitions, partition profiles, system profiles, managed system
information, managed frame cages, or managed frame information.

    -r                       - the type of resources to be listed:
                                 lpar    - partitions
                                 prof    - partition profiles
                                 sys     - managed systems
                                 sysprof - system profiles
                                 cage    - managed frame cages
                                 frame   - managed frames
    -m <managed system>      - the managed system's name
:
:
:
```

As an experiment, you can try to figure out what flag replaces `-r` on V10 and modify `PPCcli.pm` to use it.

**Comment by capacho66** [comment]
@gurevichmark ---  Thank you so much for your suggestions. The fixes were:

(*) for the TLS stuff, I implemented firewall in AIX and I disabled port 3001 
(*) for the issues with rscan command, I did what you suggested and I was able to modify /opt/xcat/lib/perl/xCAT/PPCcli.pm around line 30 with the proper new flags for  lssyscfg 
Thank you again !!

**Comment by gurevichmark** [comment]
Glad to hear that. Can you please close this issue if all problems have been resolved.

**Comment by capacho66** [comment]
Problem resolved.  Thanks a lo @gurevichmark
