### ISSUE TITLE
[FVT]nodeset returns grub2 plugin bug for  Ubuntu 14.04.03 on ppc64le

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#736]
xCAT 2.12 2/22 build Ubuntu 14.04.03 on ppc64le
Steps:
1) Install xCAT and configure mn
2) define compute node
3) run commands to prepare for the os provision
4) run nodeset and get the error.
root@c910f03fsp03v06:~# nodeset c910f03fsp03v07 osimage=ubuntu14.04.3-ppc64el-install-compute
Error: grub2 plugin bug, pid 5022, process description: 'xCATd SSL: nodeset to c910f03fsp03v07 for root@localhost: grub2 instance: destiny instance: debian instance' with error 'Died at /opt/xcat/sbin/xcatd line 1856.
root@c910f03fsp03v06:~# echo $?
1

**Comment by daniceexi** [comment]
@tingtli This is the duplicated issue of #728 .

**Comment by caomengmeng** [comment]
Reproduced, but the return message is not exactly the same.

```
root@c910f03fsp03v06:~# nodeset c910f03fsp03v07 osimage=ubuntu14.04.3-ppc64el-install-compute
Error: grub2 plugin bug, pid 5054, process description: 'xCATd SSL: nodeset to c910f03fsp03v07 for root@localhost: grub2 instance: destiny instance: debian instance' with error 'Died at /opt/xcat/sbin/xcatd line 1856.
' while trying to fulfill request for the following nodes: c910f03fsp03v07
root@c910f03fsp03v06:~# echo $?
1
root@c910f03fsp03v06:~# lsxcatd -a
Version 2.12 (git commit add2c075e4c8eebadf3ae1976c0f38172a632b5d, built Sun Feb 21 15:31:57 EST 2016)
This is a Management Node
dbengine=SQLite
root@c910f03fsp03v06:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

```

**Comment by caomengmeng** [comment]
@daniceexi As the https://github.com/xcat2/xcat-core/issues/728 is fixed yesterday, but this issue still happens, do just make a comments here.

**Comment by junxiawang** [comment]
@caomengmeng  the build for autotest used is Monday's  and build server will do the build after both new code check in and  autotest yesterday .So may be new code is not checked in the build autotest used.

**Comment by tingtli** [comment]
Verified by autotest. Close it
