### ISSUE TITLE
Login node /etc/shadow

### ISSUE THREAD

**Issue by nsonoda** [xcat2/xcat-core#7369]
Hi,

I have a Login node provisioned by xCAT on Headnode, and I wanted to know if there is some way to update my /etc/shadow from Headnode, after the user reset the password in Login node. Because, from Headnode to Login node, I use updatenode login -F, but I don't know about Login node to Headnode.

I tried to mount Headnode /etc on /opt/etc in Login node and create a symbolic link, but the link breaks after running passwd.

**Comment by gurevichmark** [comment]
@nsonoda 
* Which version of xCAT ?
* Do you have `/etc/shadow` listed in your "synclist" file ?
* Have you seen the `MERGE` section in the "synclist" file `Advanced synclist file features` documentation ? https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html#advanced-synclist-file-features

**Comment by nsonoda** [comment]
Hi Mark,

Thanks for response.

The version of xCAT is 2.16.5.

Yes, I have /etc/shadow in my synclist file, using the MERGE option, but in this situation I need to sync the /etc/shadow from my Login node to my management node, in that way: Login node -> management node. Is it possible to do? Because the users of cluster will reset the password in the Login node.

Thank you.
