### ISSUE TITLE
Use xCat for server provisioning on bare-metal server

### ISSUE THREAD

**Issue by snowcake7** [xcat2/xcat-core#7377]
Hi, Good day. I am new to xCat and was trying to use this for server provisioning.
I am able to install the xCat Management node to a RHEL 8 OS using the manual installation.
Version 2.16.5 (git commit XXXXXXXXXXXXXX, built Fri Mar  3 09:07:13 EST 2023)
This is a Management Node
dbengine=SQLite

I am now trying to follow the "Prepare the xCAT Management Node for Support Sysclone" but having an issue when trying to install the systemimager-server. The error says python is required for systemimager-server, in which python rpm is not available for RHEL8 only python2 or python3, already tried the alternatives pointing python to python2 but still same error. Also tried, rebuilding the systemimager-server rpm and removed the python require but got conflict with systemimager-common. 

Any idea how to fix this?

I also tried SystemImager v5 but having issue on si_getimage :(

**Comment by samveen** [comment]
@snowcake7 would you please post the command that is failing, and the error you get?

**Comment by snowcake7** [comment]
Hi, Samveen. Good day.
Below are the steps I have done and the error output.
xCat installation
# mkdir -p ~/xcat
# cd ~/xcat/
# wget https://xcat.org/files/xcat/xcat-core/2.16.x_Linux/xcat-core/xcat-core-2.16.5-linux.tar.bz2
# tar jxvf xcat-core-2.16.5-linux.tar.bz2
# cd ~/xcat/xcat-core
# ./mklocalrepo.sh
# cd ~/xcat
# wget http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-2.16.5-linux.tar.bz2
# tar jxvf xcat-dep-2.16.5-linux.tar.bz2
# cd ~/xcat/xcat-dep/rh8/x86_64
# ./mklocalrepo.sh
# yum install xCAT
# source /etc/profile.d/xcat.sh
# lsxcatd -a
Version 2.16.5 (git commit XXXXXX, built Fri Mar  3 09:07:13 EST 2023)
This is a Management Node
dbengine=SQLite

Because systemimager-server is not available in the default /root/xcat/xcat-dep/rh8/x86_64.
I moved the systemiamger* perl* from /root/xcat/xcat-dep to /root/xcat/xcat-dep/rh8/x86_64 then recreate the repodata.
# cd /root/xcat/xcat-dep
# cp systemimager-* perl-* rh8/x86_64/
# cd rh8/x86_64/
# rm -rf repodata/
# createrepo .
# yum clean all
# yum  install systemimager-server
Updating Subscription Management repositories.
xCAT 2 depedencies                                                                                                            2.9 MB/s | 3.0 kB     00:00
xCAT 2 depedencies                                                                                                             59 MB/s | 159 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides python needed by systemimager-server-4.3.0-0.3.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate pack

**Comment by snowcake7** [comment]
Hi, @samveen. Good day.
I have installed epel and python2 but still the same.

```
# yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
# yum repolist
Updating Subscription Management repositories.
repo id                                                            repo name
epel                                                               Extra Packages for Enterprise Linux 8 - x86_64
rhel-8-for-x86_64-appstream-rpms                                   Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                                      Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
xcat-core                                                          xCAT 2 Core packages
xcat-dep                                                           xCAT 2 depedencies

# yum install python2
# rpm -q python2
python2-2.7.18-11.module+el8.7.0+15681+7a92afba.x86_64
# alternatives --config python

There are 2 programs which provide 'python'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/libexec/no-python
   2           /usr/bin/python2

Enter to keep the current selection[+], or type selection number: 2

# python -V
Python 2.7.18


# yum  install systemimager-server
Updating Subscription Management repositories.
Last metadata expiration check: 0:03:16 ago on Fri 28 Apr 2023 10:28:40 AM +08.
Error:
 Problem: conflicting requests
  - nothing provides python needed by systemimager-server-4.3.0-0.3.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

**Comment by samveen** [comment]
A few observations I have about the package for `systemimager-server`:

- It's _very_ old:
```
[samveen@xcat-test ~]$ rpm -qip systemimager-server-4.3.0-0.3.noarch.rpm |grep 'Build Date'
warning: systemimager-server-4.3.0-0.3.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID ca548a47: NOKEY
Build Date  : Monday 27 October 2014 01:31:10 PM UTC
```

The `systemimager` process of provisioning is old and deprecated, as per the docs.

With that in mind, would you care to describe the problem wanting to solve using `systemimager`  and maybe we can help you decide on a better solution?

**Comment by snowcake7** [comment]
Hi @samveen.
We are planning to use the systemimager for creating a golden image of a bare-metal server and use this to provision several bare-metal servers. Do you have a better solution using xcat?

Thank you!

**Comment by snowcake7** [comment]
systemimager source we follow was from xcat documentation
https://xcat-docs.readthedocs.io/en/latest/advanced/sysclone/sysclone.html

**Comment by samveen** [comment]
@snowcake7 My experience with bare metal provisioning on xCAT has been using osimages of Centos 7 using RH anaconda kickstart , using copycds on the ISOs. It worked very well for our infras (4 DCs with a cumulative set of 2K servers). Further, if you use some kind of configuration management system like puppet , it can be hooked to the postinstall scripts of the osimages/nodes to automatically deploy and set up all required applications, configurations and services on the nodes.

**Comment by snowcake7** [comment]
Hi @samveen .
Do you mean with osimage we can create an OS image (ISO) then use copycds (xcat) to import to xcat then use these when deploying to bare-metal? 

As I am reading the osimage, it seems you are creating configuration files to be able to customize the OS and create an ISO from this?

Is there a way to create an image from an existing/running bare-metal? because they are planning to install the OS first, do all customizations manually before creating the OS image of itself for golden image.

**Comment by samveen** [comment]
The process is roughly as follows:
- Download the ISO image for your OS of choice (I am assuming RHEL8u7 i.e. rhel-8.7-x86_64-dvd.iso or something similar) on the MN
- run `copycds rhel-8.7-x86_64-dvd.iso`  which will do the following:
   - Copy the ISO contents into `/install` as a repository tree.
   - Copy the network boot/install files required int /install
   - Create  `osimage` definitions for booting or installing nodes from these files.
- Once this has run successfully, you can test with `lsdef -t osimage` to see the list of osimage definitions (in particular the ones that contain `-install` in their names.
- Finally you can configure xcat to install the selected osimage by using `nodeset $NODE $OSIMAGE_NAME` and the powering on the node with `rpower $node on` . This will initiate a network based install using the RHEL8.7 files and a kickstart template generated by xcat for this node. 

Please note that while the OSimage and the kickstart file will work OK, you will need to modify the osimage a tiny bit to make everything an exact fit for your requirements. For example, in our environment, we used a hook in the kickstart template to pull information from our CMDB system to customize the disk partitioning of the servers during the osimage network install process.

**Comment by snowcake7** [comment]
Hi, @samveen.
We will first try to create a dummy RPM package as the systemimager-server already have the step by step guide to image an existing OS. Thank you very much for your help!

**Comment by samveen** [comment]
@snowcake7 Please note that the imaging method for provisioning has been deprecated in xCAT for more than 8 years (the last systemimager-* packages were built in October 2014), and osimage based provisioning is where you'll get better documentation and support.

**Comment by snowcake7** [comment]
Hi, Samveen.
Thank you for your time and help.
We will be using the "Relax-and-Recover (ReaR) utility" from RHEL instead for the imaging and provisioning :)
We will try to figure out on how to integrate it with xcat.
