### ISSUE TITLE
[DEV]The rsyslog.conf file disables message logging in /var/log/messages

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#739]
Starting from the xCAT 2.11 release, changes were made to the rsyslog configuration file.  The xCAT related logs are stored in ``/var/log/xcat/`` subdirectory.

In commit 1219fdd2, we commented out the debug information going to /var/log/messages.  

@neo954 , I think this is a bug, but would like to first understand why we decided to comment that line out? 

Should be fixed 2.11 and 2.12 and onwards

**Comment by whowutwut** [comment]
I did notice on my xCAT 2.11 GA machine, that the DHCP messages are being logged into ``/var/log/xcat/computes.log`` . .  I don't think dhcp messages should be going into xcat logs.  We manage dhcp on behalf of the user, but we do not own dhcp, so moving the messages to computes.log will cause confusion to the admins.

**Comment by immarvin** [comment]
hi @whowutwut , I think it's not easy to filter the xCAT related logs out of the system logs, since xCAT operations rely on other system services, such as  dhcp,dns,syslog...., the log entries generated by these services are not tagged with "xcat" but they are important part of xCAT logs. 

According to my debugging experience, it caused some trouble to lookup the log entries related to one xCAT operation in different files. Personally, I prefer the previous way of dropping all the logs into /var/log/messages and I can filter out the concerned messages by myself.

**Comment by tingtli** [comment]
@neo954  Would you please take a look at victor's question and give some comments for the logs change.  I think there is a design for that to describe why we do that change.

**Comment by neo954** [comment]
@whowutwut, if your xCAT management node was installed by another xCAT management node, you will suffer the problem. In this situation, the node was first installed as a compute node (installed by another xCAT management node), in this stage, the entire log will be disabled and redirected to the management node used for the operating system installation.

After this stage, if xCAT server was installed on this node, the new xCAT installation will collect all logs from its compute nodes to another place, but will not restore the disabled and redirected logs.

Conclusion, do not install xCAT management node with another xCAT management node. Since it is not customer scenario. In a customer scenario, the first node, usually the xCAT management node, is always installed by hand, manually.

As a workaround, if you insist installed xCAT management with another xCAT management node, do not run the postscript ``syslog`` during the operating system installation. The postscript ``syslog`` will run by default.

And, if you do run the postscript ``syslog`` already, you may restore the default ``rsyslogd`` configuration manually. After that, you can do ahead to the normal xCAT server installation procedure, and everything will be fine.

**Comment by daniceexi** [comment]
@neo954 

Currently, in the rh7.2 MN, the /etc/rsyslog.conf has the configuration like following 

~~~~
# xCAT settings
#*.debug  /var/log/messages
~~~~

That means the dhcp log in the xCAT won't be logged. This should be handled.

**Comment by daniceexi** [comment]
@neo954 

Another problem was I found the rsyslog configuration files which were introduced by you did take affect on sles MN. You can take look of this in 10.2.1.14.

**Comment by whowutwut** [comment]
Ralph pinged me with the same issue today and suggested the following configuration for rsyslog.d: 
```
$ cat xCAT/etc/rsyslog.d/xcat-management.conf
:fromhost-ip, isequal, "127.0.0.1" /var/log/messges 
```

I did a small test with this...  
- systemctl stop rsyslogd
- rm -rf /var/log/messages*
- rm -rf /var/log/xcat/*
- create the file above
- systemctl start rsyslogd


After restarting syslog, the dhcp messages are now re-appear in ``/var/log/messages``, then the xCAT compute nodes messaging are going into /var/log/xcat/computes.log, etc...  This is what I would expect as the behavior.  

@immarvin  Yes, xCAT uses services like dhcp/dns/syslog, but it does not own it.  So redirecting the logs out of their _normal_ location will cause confusion to system administrators.  So I think those should remain in /var/log/messages

@neo954  I was just wondering why we even do ``*.debug /var/log/messages`` before...   By commenting that out, we get 0 messages in ``/var/log/message``.  I think this is not what we should be doing?

**Comment by whowutwut** [comment]
Anyone have some comments on the changes above?

**Comment by neo954** [comment]
@whowutwut, Did you ever play with any Red Hat / SuSE / Ubuntu machine which was installed manually, without xCAT?

The main idea of the new xCAT ``rsyslogd`` policy is leave the upstream Linux distro rsyslogd configuration as is. That means, for all the logs come from the xCAT management node itself, we try to maintain the default log behavior came from the upstream Linux distro, as if xCAT it not there.

And, as a side effect, if the system administrator changed the default rsyslogd configuration before he / she installed xCAT server, we leave all his/her changes there as well.

@whowutwut, I am not sure if you realized there are different "default" ``rsyslogd`` settings for different Linux distros. And there is no "right" or "wrong" settings for the ``rsyslogd`` settings. Based on the role of the system and the payloads of the system, a system administrator may have his / her own choice.

Before the ``rsyslogd`` changes I made, xCAT used to disable all the ``rsyslogd`` settings cames from the upstream Linux distro and put all the logs into one place, ``/var/log/messages``. The benefit of this policy, is that xCAT server provided a constant log behavior across all the Linux distros.

But, for the weakness, this log behavior may break all the other log facilities, such as log rotate, and log analysis system. Most Linux distos ship these kind of facilities to match up their default ``rsyslogd`` settings. If we change the default ``rsyslogd`` settings, we may break the other log facilities.

Furthermore, put all the logs into a single log file is not a good idea. On a quite busy server system, it will produce dozens gigabytes of logs. Without log rotate, it will fill up ``/var`` file system quickly. And if ``/var`` directory is not on a separate file system, it will fill up the root file system in the end. Which is even worse. In addition, treat a log file tens of gigabytes is a pain as well. It is hard to read, search and / or analysis such a log file.

Again, there is no "right" or "wrong" settings for the ``rsyslogd``. In real productive environment, the system administrator has to find out his / her own settings. That is why the new xCAT ``rsyslogd`` policy tries to leave the default settings come from the upstream Linux distros there.

**Comment by daniceexi** [comment]
@neo954 I agree with the basic principles of how to config rsyslog which mentioned by you. But xCAT's original rule was to enable all the logs to one log file /var/log/messages. And it was accepted by customer, even some customers may change the xCAT default configuration after xCAT installl immediately.
I think we need to keep the original rule for rsyslog configuration in xcat, which is what mentioned by Ralph.

**Comment by whowutwut** [comment]
I'm debating this issue as well...  Maybe need to come up with a mini design...   I think there should be a variable introduced to control log forwarding.  Looking at rsyslog documentation, they seem to refer to this as log consolidation.   Perhaps this keyword.. 

``site.logconsolidation`` or ``site.log_consolidation``

valid options may be one of the following: 
```
* "1"              <== set true, turn on forwarding, using defaults from rsyslog. 
* "1;udp"       <== set true, uses udp, configured by xCAT
* "1;tcp"         <== set true, use tcp,  configured by xCAT
* "0" or unset   <== off (default)
```
So the default would be unset, and there would be no changes to log consolidation, so the behavior to existing xCAT users is the same.  We activated this in 2.11 and the behavior changed which I think will confuse some of the users.  Maybe in 2.11.1 we should revert back to the original config and add in these tuning parameters. 

I need to investigate this more, but I think we should not make any changes to the file  ``/etc/rsyslog.conf`` but rather put all related changes into files shipped by the xCAT under the  ``/etc/rsyslog.d/`` directory...

**Comment by daniceexi** [comment]
@whowutwut Refer to the pull request #826 which owned by @xuweibj to control the syslog configuration for node specific (customer request). In the pull request, it only support to skip the rsyslog config in the xCAT **syslog** script.

I think the final decesion should include both of your ideas:
* the syslog control should be global + individual
* control to do the consolidation or not

**Comment by daniceexi** [comment]
The original logs in /var/log/messages have been taken back. 
I also opened a story in RTC to track the requirement that add a site/node attribute to control how to generate the rsyslog for CN.
