### ISSUE TITLE
xcatd services not starting automtically after server reboot

### ISSUE THREAD

**Issue by abhishek-sa1** [xcat2/xcat-core#7390]
xcatd services not starting automtically after server reboot
![image](https://github.com/xcat2/xcat-core/assets/94038029/2ff0c19f-3b35-4740-b668-e4b87d964cf0)

xcatd services start only after a manual restart of postgresql and xcatd services
![image](https://github.com/xcat2/xcat-core/assets/94038029/b93712bc-772f-4e61-8d39-ed291a641046)

Is there any way to start xcatd services automatically after reboot of server?

**Comment by samveen** [comment]
This can be done by adding a `systemd` config addin for `xcatd.service` to start after `postgresql.service` as below:

```
sudo mkdir /etc/systemd/system/xcatd.service.d
cat <<__ENDL | sudo tee /etc/systemd/system/xcatd.service.d/require_pg.conf
[Unit]
Requires=postgresql.service
After=postgresql.service
__ENDL
```
