### ISSUE TITLE
Custom Partions not working with nvme drive

### ISSUE THREAD

**Issue by hhslax2** [xcat2/xcat-core#7393]
I'm having an issue with kickstart not working with a custom partition with two drives.  It works without the nvme drive installed in the server.  I've tried various iterations with the partition file including --disklabel=gpt and ignoredisk --drives=nvme0n1.  Here is my custom partition file for the nodes.  The error chain is:
Starting automated install..Saving storage configuration...
.Failed to save storage configuration
.The following prblem occurred on line7 of the kickstart file:
device is too large for new format

# System bootloader configuration
bootloader --location=mbr --driveorder=sda --append="rhgb novga console=ttyS0,115200 console=tty0"

# Partition clearing information
zerombr
clearpart --all --initlabel --drives=sda
clearpart --all --initlabel --drives=nvme0n1

# Disk partitioning information
part biosboot --fstype=ext2 --ondisk=sda --size=1024
part /boot --fstype=ext2 --ondisk=sda --size=512
part swap --fstype=swap --ondisk=sda --size=16384
part pv.01 --fstype=lvmpv --ondisk=sda --size=1 --grow
volgroup vg_rocky --pesize=4096 pv.01
logvol /tmp --fstype=xfs --size=20480 --name=lv_tmp --vgname=vg_rocky
logvol /var  --fstype=xfs --size=81920 --name=lv_var --vgname=vg_rocky
logvol /  --fstype=xfs --size=1 --grow --name=lv_root --vgname=vg_rocky
part /local --fstype=xfs --ondisk=nvme0n1 --size=1 --grow

**Comment by samveen** [comment]
Just a small correction: for serial terminals connected to the Out-Of-Band Management (usually `ttyS0`) to be the primary target of boot up logging (particularly systemd based systems), please re-arrange the kernel command line passed to have `ttyS0` as t he last of the consoles i.e.:

```
--append="rhgb novga console=tty0 console=ttyS0,115200"
```

**Comment by hhslax2** [comment]
Thanks.  Ended up being the pesize due to the hard drive size.
