### ISSUE TITLE
The Kickstart stuck in every provisioning process as the following picture that attached (prov redhat 9.1) attach auto install file 

### ISSUE THREAD

**Issue by tomers007** [xcat2/xcat-core#7395]
![Capture1](https://github.com/xcat2/xcat-core/assets/99538034/5c6b6c76-5144-4672-b64c-7a23a6937374)
[cn52.txt](https://github.com/xcat2/xcat-core/files/12139708/cn52.txt)

**Comment by gurevichmark** [comment]
xCAT does not have official support for RH9.
xCAT community contributors made some contributions to improve the xCAT support for RH9, but additional
effort is needed to make it work in a seamless fashion.
You can see which OSes should be expected to work without additional effort:
https://xcat-docs.readthedocs.io/en/stable/overview/xcat2_release.html

**Comment by tomers007** [comment]
It's happened also on redhat 8.5

**Comment by tomers007** [comment]
![xcatprobe osdeploy -n cn56 -V](https://github.com/xcat2/xcat-core/assets/99538034/17461e2f-a27f-4848-a4fa-3171cd6e846e)
adding the xcatprobe osdeploy -n cn56 -V

**Comment by tomers007** [comment]
xcat is installed & running on 8.5

**Comment by gurevichmark** [comment]
@tomers007 Are there other nodes in your cluster that have successfully provisioned with this osimage ?

**Comment by tomers007** [comment]
Yes,but after few times I issued the provisioning

**Comment by tomers007** [comment]
attaching auto install of success node (cn48) and the failed one cn56 
[48.txt](https://github.com/xcat2/xcat-core/files/12162228/48.txt)
[cn.56.txt](https://github.com/xcat2/xcat-core/files/12162240/cn.56.txt)

**Comment by tomers007** [comment]
any reason why thats happened ? its drive me crazy
