### ISSUE TITLE
while installing compute node 

### ISSUE THREAD

**Issue by vikaskaprwan333** [xcat2/xcat-core#7396]
hi 
i am getting this issue while installing compute node after xcat configuration.

**error an error occurred during reading the kickstart file** 
**unrecognized arguments: yes**

**pane is dead**

**Please help** 

 i have attached error snaps.

![image](https://github.com/xcat2/xcat-core/assets/97095264/16ebed71-4adc-4d42-a030-e29fc53088e2)

**Comment by samveen** [comment]
@vikaskaprwan333 please change to the shell tab ( `switch tab` as listed in the screenshot) to check the contents of the kickstart file.


![image](https://github.com/xcat2/xcat-core/assets/1241434/473a6d33-880a-490d-8287-157fff89b803)
