### ISSUE TITLE
[Customer]Node filters in synclists are not documented

### ISSUE THREAD

**Issue by Aethylred** [xcat2/xcat-core#740]
Since at least xCAT 2.9.2 the synclist file format includes filters that restrict the deployment of files to a list of node ranges.

For example:

```
/syncfiles/authldap/etc/sssd/sssd.conf -> (authldap,login,test-1,test-2) /etc/sssd/sssd.conf
```

Only distributes this file for nodes in the authldap and login groups, as well as the nodes test-1 and test-2.

However this feature is not documented in the xCAT documentation.

**Comment by daniceexi** [comment]
@Aethylred Hi Aaron, nice to see you again!

xCAT team will update this to the sourceforge doc for aix.

**Comment by daniceexi** [comment]
@tingtli Please update the interface change in the https://xcat-docs.readthedocs.org/en/2.11/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html#the-synclist-file

And to the sourceforge https://sourceforge.net/p/xcat/wiki/Sync-ing_Config_Files_to_Nodes/ for AIX.

**Comment by Aethylred** [comment]
Will this feature also be available in Linux versions?

**Comment by daniceexi** [comment]
Yes, it has been checked in to the latest xcat version for Linux.

**Comment by tingtli** [comment]
Merge pull request #773 from tingtli/defect740
