### ISSUE TITLE
hardeths scripts does not update both GATEWAY information when there are 2 active NIC present on target nodes

### ISSUE THREAD

**Issue by abhishek-sa1** [xcat2/xcat-core#7403]
`hardeths` postscripts which is configuring hostname and converting dhcp ip to static ip does not store both GATEWAY information details 2 active NIC present on target nodes.

As mentioned in the screenshot below, it is always taking first default route present and updating the same in `/etc/sysconfig/network` file.
```
defgw=`ip route | grep default | awk '{print $3}' | head -n1`

    if [ ! -z "$defgw" ]; then
        grep -qw GATEWAY /etc/sysconfig/network && \
            sed -i "s/^GATEWAY.*/GATEWAY=$defgw/" /etc/sysconfig/network || \
            echo "GATEWAY=$defgw" >> /etc/sysconfig/network
    fi
```

I can see following updates in individual NIC interface:

```
 sed -i s/BOOTPROTO=dhcp/BOOTPROTO=static/ $NICFILE
 sed -i s/BOOTPROTO=\'dhcp\'/BOOTPROTO=static/ $NICFILE
  sed -i s/BOOTPROTO=\"dhcp\"/BOOTPROTO=static/ $NICFILE
  grep ^IPADDR= $NICFILE >/dev/null
  if [ $? -eq 0 ]
  then
      sed -i '/IPADDR=/d'  $NICFILE
  fi
  echo IPADDR=$IPADDR >> $NICFILE
  grep ^NETMASK= $NICFILE >/dev/null
  if [ $? -eq 0 ]
  then
      sed -i '/NETMASK=/d' $NICFILE
  fi
  echo NETMASK=$NETMASK >> $NICFILE

```

BOOTPROTO,IPADDR and NETMASK only getting updated in each ifcfg-nic file in the folder `/etc/sysconfig/network-scripts/`.

```
cat /etc/sysconfig/network-scripts/ifcfg-eno2
# Generated by parse-kickstart
TYPE=Ethernet
DEVICE=eno2
UUID=4a8871ce-e5dc-465e-a6f1-9ae6d2fc12a7
ONBOOT=yes
BOOTPROTO=static
IPV6INIT=yes
PROXY_METHOD=none
BROWSER_ONLY=no
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME="System eno2"
IPADDR=10.27.0.4
```
Due to this if server reboots, both the NICs are getting same GATEWAY address in route table. (Since network config contains only one GATEWAY information)
![image](https://github.com/xcat2/xcat-core/assets/94038029/498d3a15-f608-4209-bdb2-2bb988f197e1)

Server won't be reachable from management node(where xCAT installed) after update of GATEWAY.

I have found solution for this by updating GATEWAY information of individual NIC in ifcfg files. Refer screenshot below:
```

for nic in `ip link |grep "BROADCAST" |awk '{print $2}'   | sed s/://`; do
    IPADDRMASK=`ip -4 -o a sh dev $nic | awk '/inet/{print $4}' | head -n 1`
    IPADDR=`echo $IPADDRMASK | awk -F'/' '{print $1}'`
    GATEWAY=`ip route | grep default | grep $nic | awk '{print $3}'`
   grep ^GATEWAY= $NICFILE >/dev/null
        if [ $? -eq 0 ]
        then
            sed -i '/GATEWAY=/d' $NICFILE
        fi
        echo GATEWAY=$GATEWAY >> $NICFILE
```

After update of the script, GATEWAY information will be stored in ifcfg file mentioned below:
```
IPADDR=10.27.0.4
NETMASK=255.255.0.0
GATEWAY=10.27.255.254

```
**Any suggestion on this or can I raise PR for this issue?**
@samveen @gurevichmark

**Comment by samveen** [comment]
@abhishek-sa1 By definition. there should only be one default gateway in the system. If the node is getting 2 default gateways, then there is some misconfiguration happening , with respect to networks config. 

Please check on the DHCP server configuration for the secondary NIC. How is that DHCP server configuration controlled?

Once again, please copy and paste text output  (using ` ``` ` for formatting) instead of pasting screenshots.

**Comment by abhishek-sa1** [comment]
@samveen there are 2 active NIC in the node in our case. One is assigned IP from xCAT server and another is for public NIC IP to access the node outside. It will be login node for the user.

**Comment by abhishek-sa1** [comment]
https://docs.oracle.com/en/operating-systems/oracle-linux/6/admin/about-etc-sysconfig.html - as per doc `/etc/sysconfig/network `file is default config for all networks. If individual NIC has different gateway that's not handled by `hardeths` postscript

**Comment by abhishek-sa1** [comment]
@samveen Updated issue with text

**Comment by samveen** [comment]
@abhishek-sa1 what is the output of the `ip r` command on the node?

**Comment by abhishek-sa1** [comment]
@samveen Please find below `ip r` command command output before and after reboot of server

Before reboot:
```
default via 100.96.x.y dev eno1 proto static metric 102
default via 10.27.255.254 dev eno2 proto static metric 103
10.27.0.0/16 dev eno2 proto kernel scope link src 10.27.0.4 metric 103
100.96.x.y/23 dev eno1 proto kernel scope link src 100.96.x.z metric 102
```

After reboot:
```
default via 10.27.255.254 dev eno1 proto static metric 102
default via 10.27.255.254 dev eno2 proto static metric 103
10.27.0.0/16 dev eno2 proto kernel scope link src 10.27.0.4 metric 103
100.96.x.y/23 dev eno1 proto kernel scope link src 100.96.x.z metric 102
```

x.y and x.z added in above example by replacing the last 2 digits of IP which is in public network.

**Comment by samveen** [comment]
@abhishek-sa1 please also give me the output of the following commands:

- `uname -a`
- `grep -E . /etc/*-release`

**Comment by abhishek-sa1** [comment]
@samveen  we are using RHEL OS and x86_64 architecture. Please find below details for command output:
```
[root@springnode00002 ~]# uname -m
x86_64
```

```
[root@springnode00002 ~]# grep -E  . /etc/*-release
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.7 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.7"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
/etc/redhat-release:Red Hat Enterprise Linux release 8.7 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.7 (Ootpa)

```

**Comment by samveen** [comment]
@abhishek-sa1 From the master, please show me the network definition for the network which provides the internal network addresses for the secondary interface (you said it was eno2 (NIC 2 INTERFACE) ).

**Comment by abhishek-sa1** [comment]
@samveen there is no network definition for the public Network in the range 100.96.x.y. Only private network has definition in network table. Public DHCP is controlled by another server. By default when we provision a server all the active NICs will be UP by default with postscripts. 

https://github.com/xcat2/xcat-core/blob/6b8c669171efde0ada1b8d966f7765e04c66811a/xCAT-server/share/xcat/install/scripts/post.rhels8#L9-L21

```
[root@springcp ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"bmc_network","10.29.0.0","255.255.0.0","eno1","10.29.255.254","10.29.255.254",,,,,"10.29.246.1-10.29.250.253","10.29.0.1-10.29.0.10",,,,,,,,
"host_network","10.27.0.0","255.255.0.0","eno1","10.27.255.254","10.27.255.254","10.27.255.254",,,,,"10.27.0.1-10.27.255.253",,,,,,,,


```

**Comment by abhishek-sa1** [comment]
@samveen https://omnia-doc.readthedocs.io/en/latest/Overview/NetworkTopologies/dedicated.html

Please refer above link for our network connections. There is public connection for Head and Login Node other than control plane(where xCAT installed)

**Comment by samveen** [comment]
@abhishek-sa1 can you confirm the following statements
For all cluster nodes:
- eno1 gets IP from a DHCP server not controlled by xCAT and is public IPs
- eno2 gets IP from the network configuration as listed by host_network (`lsdef -t network -o host_network`), and is cluster only network.

**Comment by abhishek-sa1** [comment]
@samveen The statement is true. Just one correction eno1 will not be connected to all nodes. It will be only for few nodes like head and login node as mentioned in architecture.

**Comment by samveen** [comment]
@abhishek-sa1 
- Does that mean that the issue with `hardeths` occurs only for the few nodes like head, login and similar external facing nodes?
- Do the non-external facing nodes in the cluster have or required outgoing internet access?

**Comment by abhishek-sa1** [comment]
- Does that mean that the issue with hardeths occurs only for the few nodes like head, login and similar external facing nodes?
Yes
- Do the non-external facing nodes in the cluster have or required outgoing internet access, or for that matter, access to any other network outside of host_network ?
Other nodes will have internet access via DHCP routing using host_network

I have found solution by using confignetwork scripts. Thanks for the support @samveen
