### ISSUE TITLE
Why does the latest documentation branch reference 2.16.6?

### ISSUE THREAD

**Issue by billglick** [xcat2/xcat-core#7414]
If you visit any of the documentation under the `v:latest` it shows `xCAT 2.16.6 documentation` in the page name.

As far as I know there is no xCAT version `2.16.6` available.

I found this confusing because Google searches are showing me this `v:latest` documentation with `2.16.6` in search results. e.g. https://www.google.com/search?q=xcat+osimage+exlist

**Comment by besawn** [comment]
xCAT follows the standard readthedocs conventions regarding `v:latest` and `v:stable` described here:
https://docs.readthedocs.io/en/stable/versions.html

The current development version of xCAT is version 2.16.6, which has not been released yet. The `v:latest` references this version of the documentation.

The current `v:stable` tag points to xCAT version `2.16.5`, which is the newest released version of xCAT.

If you navigate to `https://xcat-docs.readthedocs.io/`, it will automatically point you to the `v:stable` version of the documentation.

Once you are on the xcat-docs documentation, you can change the version of the documentation you are referencing at any time by selecting the version you wish to view on the lower left area of the page:
![image](https://github.com/xcat2/xcat-core/assets/38794505/cbc19ef6-4958-41d9-a205-bd6e4c45b67a)

**Comment by besawn** [comment]
@billglick Hopefully, the explanation above resolves your question. If you have additional questions, feel free to re-open this issue.
