### ISSUE TITLE
genimage command failed 

### ISSUE THREAD

**Issue by ManshiMuskan** [xcat2/xcat-core#7432]
I am trying the setup on alma linux couple of times it worked but now not able to generate image

[root@testmachine install]# genimage alma8.7-x86_64-netboot-compute
Generating image: 
cd /opt/xcat/share/xcat/netboot/alma; ./genimage -a x86_64 -o alma8.7 -p compute --permission 755 --srcdir "/install/alma8.7/x86_64" --pkglist /opt/xcat/share/xcat/netboot/alma/compute.alma8.x86_64.pkglist --otherpkgdir "/install/post/otherpkgs/alma8.7/x86_64" --postinstall "/opt/xcat/share/xcat/netboot/alma/compute.alma8.x86_64.postinstall" --rootimgdir /install/netboot/alma8.7/x86_64/compute --tempfile /tmp/xcat_genimage.7613 alma8.7-x86_64-netboot-compute
143 blocks
/opt/xcat/share/xcat/netboot/alma
143 blocks
/opt/xcat/share/xcat/netboot/alma
 yum -y -c /tmp/genimage.7628.yum.conf --installroot=/install/netboot/alma8.7/x86_64/compute/rootimg/ --disablerepo=* --enablerepo=alma8.7-x86_64-0  install  chrony kernel net-tools nfs-utils openssh-server rsync tar util-linux wget python3 tar bzip2 bc dracut dracut-network rsyslog hostname e2fsprogs ethtool parted openssl dhclient openssh-clients bash vim-minimal rpm iputils perl-interpreter
Unable to detect release version (use '--releasever' to specify release version)
alma8.7-x86_64-0                                3.6 MB/s | 3.7 kB     00:00    
Error: Failed to download metadata for repo 'alma8.7-x86_64-0': repomd.xml parser error: Parse error at line: 1 (Document is empty
)
Ignoring repositories: alma8.7-x86_64-0
No match for argument: chrony
No match for argument: kernel
No match for argument: net-tools
No match for argument: nfs-utils
No match for argument: openssh-server
No match for argument: rsync
No match for argument: tar
No match for argument: util-linux
No match for argument: wget
No match for argument: python3
No match for argument: bzip2
No match for argument: bc
No match for argument: dracut
No match for argument: dracut-network
No match for argument: rsyslog
No match for argument: hostname
No match for argument: e2fsprogs
No match for argument: ethtool
No match for argument: parted
No match for argument: openssl
No match for argument: dhclient
No match for argument: openssh-clients
No match for argument: bash
No match for argument: vim-minimal
No match for argument: rpm
No match for argument: iputils
No match for argument: perl-interpreter
Error: Unable to find a match: chrony kernel net-tools nfs-utils openssh-server rsync tar util-linux wget python3 bzip2 bc dracut dracut-network rsyslog hostname e2fsprogs ethtool parted openssl dhclient openssh-clients bash vim-minimal rpm iputils perl-interpreter
yum invocation failed

**Comment by samveen** [comment]
Did the `copycds` complete successfully when run on the install media images of `alma8.7-x86_64` ?

**Comment by ManshiMuskan** [comment]
> Did the `copycds` complete successfully when run on the install media images of `alma8.7-x86_64` prior to running the `genimage`? The error line about `repomd.xml` seems to imply that the repository structure that should have been created by `copycds` isn't in place correctly.


Thank you so much for your response, It was problem of that file only..once I changed the iso and run the commands again it, worked.

**Comment by samveen** [comment]
@Obihoernchen  Please mark this  issue closed, as it's solved. This could also use the label `Support`
