### ISSUE TITLE
nodeset command failed with error randomly, and works after sometime

### ISSUE THREAD

**Issue by abhishek-sa1** [xcat2/xcat-core#7446]
nodeset command failed with error randomly

command: `nodeset all osimage=ubuntu22.04.3-x86_64-install-compute` 

Error mentioned below:
```
Usage: nodeset [COMMAND] [OPTIONS] [ns1 [-ixX] ns2|...]
nodeset: error: No command specified.
```

Same command works after sometime in same terminal.

@samveen @Obihoernchen

**Comment by abhishek-sa1** [comment]
I have observed the issue due to xcat environment variables are not set. Command worked after configuring environment variables. Can we use xcat environment variables in .bashrc file?

**Comment by samveen** [comment]
@abhishek-sa1 That is usually the case for me. I set up environment variables via ~/.bashrc

**Comment by Obihoernchen** [comment]
Do you mean xcat environment variables defined in `/etc/profile.d/xcat.sh` ?

**Comment by abhishek-sa1** [comment]
Yes..commands worked after setting envirornment variables
