### ISSUE TITLE
Server unknown cache

### ISSUE THREAD

**Issue by kinkcamp** [xcat2/xcat-core#7458]
Hello, help, I found a problem when using xcat. After configuring the network table, I tried makedhcp, and an unknown IP segment appeared. I don’t know where it came from, and I can’t delete it. What should I do? The following is log
---------------------------------------------------------------------------------------------------------------------
[root@xcat ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"192_168_101_0-255_255_255_0","192.168.101.0","255.255.255.0","eno1","192.168.101.254",,"<xcatmaster>",,,,,,,,,,,"1500",,
"192_168_103_0-255_255_255_0","192.168.103.0","255.255.255.0","remote","192.168.103.254","192.168.101.10","192.168.101.10","192.168.101.10","192.168.101.10","192.168.101.10",,,,,,,,,,
[root@xcat ~]# makedhcp -n
Renamed existing dhcp configuration file to  /etc/dhcp/dhcpd.conf.xcatbak

Warning: [xcat]: No dynamic range specified for 192.168.101.0. If hardware discovery is being used, a dynamic range is required.
Warning: [xcat]: No dynamic range specified for 192.168.122.0. If hardware discovery is being used, a dynamic range is required.
[root@xcat ~]#

**Comment by Obihoernchen** [comment]
`192.168.122.0` might be a network on your management node?
What does `ip a s` show?

**Comment by kinkcamp** [comment]
We will provide you with information on whether or not there is a loss, and a means to determine whether or not there is a loss.，1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 38:68:dd:19:37:b8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.101.10/24 brd 192.168.101.255 scope global noprefixroute eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::d679:d572:a31e:9395/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 38:68:dd:19:37:b9 brd ff:ff:ff:ff:ff:ff
4: ens3f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 74:9d:8f:86:b1:23 brd ff:ff:ff:ff:ff:ff
5: ens3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 74:9d:8f:86:b1:24 brd ff:ff:ff:ff:ff:ff

**Comment by kinkcamp** [comment]
And there is no
-------------------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 38:68:dd:19:37:b8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.101.10/24 brd 192.168.101.255 scope global noprefixroute eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::d679:d572:a31e:9395/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 38:68:dd:19:37:b9 brd ff:ff:ff:ff:ff:ff
4: ens3f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 74:9d:8f:86:b1:23 brd ff:ff:ff:ff:ff:ff
5: ens3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 74:9d:8f:86:b1:24 brd ff:ff:ff:ff:ff:ff

**Comment by samveen** [comment]
@kinkcamp What was the issue and solution?
