### ISSUE TITLE
Ubuntu20.04LTS

### ISSUE THREAD

**Issue by zhhmzz** [xcat2/xcat-core#7466]
Hello, I want to deploy Ubuntu20.04LTS with my rhel7.9. But I don't know how to modify the configuration file (template = / opt/xcat/share/xcat/install/ubuntu/compute subiquity. TMPL), please help me to modify it

**Comment by Obihoernchen** [comment]
Ubuntu 20.04 is not yet supported.

But there are existing issues for 20.04 please check:
https://github.com/xcat2/xcat-core/issues/6681
https://github.com/xcat2/xcat-core/issues/7105
https://github.com/xcat2/xcat-core/issues/7147
