### ISSUE TITLE
[Customer] xCAT v2.11 GA cannot copycds pkvm v2.1.1 and v3.1.1

### ISSUE THREAD

**Issue by dillonfzw** [xcat2/xcat-core#752]
I downloaded pkvm v2.1.1 and v3.1.1 from IBM passport advantage web site. Here is the file names and checksum.

```
fuzhiwen@llmaster:~/Downloads/tc_packages$ ls pkvmv211/* pkvmv311/* -la | sed -e 's/fuzhiwen/root/g'
-rw-r--r-- 1 root root 1060767744  4月 30  2015 pkvmv211/POWERKVM_V2.1.1.1_03_2015.iso
-rw-r--r-- 1 root root         72  4月 30  2015 pkvmv211/POWERKVM_V2.1.1.1_03_2015.iso.SHA1SUM
-rw-rw-r-- 1 root root       4827  4月 30  2015 pkvmv211/README
-rw-r--r-- 1 root root 1380421632  3月  1 09:07 pkvmv311/POWERKVM_V3.1_11_2015.iso
-rw-rw-r-- 1 root root         68  3月  1 12:51 pkvmv311/POWERKVM_V3.1_11_2015.iso.SHA1SUM

fuzhiwen@llmaster:~/Downloads/tc_packages$ cat {pkvmv211,pkvmv311}/*.SHA1SUM
4F9C92AF7C4AFA96F258314D9E20891702E9E2C6 *POWERKVM_V2.1.1.1_03_2015.iso
50C9C7FF8563929287D95DC2337EDAE793249F6E *POWERKVM_V3.1_11_2015.iso

```

copycds failed to import any of them

```
[root@xcatmn pkvmv311]# copycds pkvmv311/POWERKVM_V3.1_11_2015.iso
Error: copycds could not identify the ISO supplied, you may wish to try -n <osver>
```

When greped code in xCAT, I did not see any token which related to "pkvm3".
The pkvm v2.1.1 diskinfo token in my downloaded GA iso is "1422984872.740208" instead of "1413749127.352649" which hardcoded in xCAT.

```
[root@xcatmn pkvmv211]# grep -nr pkvm /opt/xcat 
/opt/xcat/lib/perl/xCAT/data/discinfo.pm:117:                 "1394111947.452332" => "pkvm2.1", # ppc64, PowerKVM
/opt/xcat/lib/perl/xCAT/data/discinfo.pm:118:                 "1413749127.352649" => "pkvm2.1.1", # ppc64, PowerKVM
/opt/xcat/lib/perl/xCAT/Utils.pm:4611:          }elsif($osv =~ /pkvm/i){
/opt/xcat/lib/perl/xCAT/ProfiledNodeUtils.pm:1056:    if ($osdistroname and $osdistroname =~ /^pkvm/ ) {
/opt/xcat/lib/perl/xCAT/ProfiledNodeUtils.pm:1388:    # groups like '__Hypervisor_pkvm' means this node is Power KVM hypervisor
/opt/xcat/lib/perl/xCAT/ProfiledNodeUtils.pm:1481:# 2        |  ppc64      | pkvm    | *                | *                 | petitboot        |
/opt/xcat/lib/perl/xCAT/ProfiledNodeUtils.pm:1492:                                        'pkvm'                                => 'petitboot',
/opt/xcat/lib/perl/xCAT_plugin/geninitrd.pm:204:        if ($osvers =~ /(^ol[0-9].*)|(centos.*)|(rh.*)|(fedora.*)|(SL.*)|(pkvm.*)/) {
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:43:            mkinstall => "nodetype:os=(pkvm.*)|(esxi4.1)|(esx[34].*)|(^ol[0-9].*)|(centos.*)|(rh(?!evh).*)|(fedora.*)|(SL.*)",
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:1316:        my $pkvm = 0;
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:1317:        if ($os =~ /^pkvm/) {
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:1318:            $pkvm = 1;
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:1425:            if ($pkvm) {
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:1612:            #}elsif ($pkvm) {
/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm:2145:        and $distname !~ /^pkvm/
/opt/xcat/share/xcat/install/pkvm/compute.pkvm2.ppc64.tmpl:28:#partition / --ondisk=/dev/mapper/ibmpkvm_vg_root-ibmpkvm_lv_root
/opt/xcat/share/xcat/install/pkvm/compute.pkvm3.ppc64le.tmpl:43:#INCLUDE:#ENV:XCATROOT#/share/xcat/install/scripts/pre.pkvm3#
/opt/xcat/share/xcat/install/scripts/pre.pkvm3:56:echo "volgroup ibmpkvm_rootvg PV.01" >> /tmp/partitioning
/opt/xcat/share/man/man1/nodeimport.1:272:\&     vmhost=pkvm1
/opt/xcat/share/doc/man1/nodeimport.1.html:158:     vmhost=pkvm1
```

I used xCAT v2.11 GA.

```
[root@xcatmn pkvmv311]# nodels --version
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)
[root@xcatmn pkvmv311]# xdsh --version
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)
```

**Comment by daniceexi** [comment]
@immarvin Please confirm the disc keys added by xCAT for PowerKVM 2.1 and 3.1 are the same as the release iso.

**Comment by whowutwut** [comment]
To extend some of the debug.... @pdlun92  and I also saw something similar on 2.11 GA code where the copycds didn't like a ``-n pkvm31`` and it worked OK using ``-n pkvm3.1`` 

But yes, I think there is something missing with detecting the name of the iso....

**Comment by neo954** [comment]
@dillonfzw, The ISO file named ``POWERKVM_V2.1.1.1_03_2015.iso`` is version 2.1.1.1, it is not version 2.1.1.

**Comment by daniceexi** [comment]
@dillonfzw The root cause for xCAT had not the powerKVM 3.1 in the discinfo.pm was the PowerKVM 3.1 was not GAed when the xCAT 2.11 was released. Even the PowerKVM 3.1 works well in xCAT 2.11.

The release notes for 2.11 has been changed accordingly.

**Comment by whowutwut** [comment]
@daniceexi  I made the following changes in my sandbox to test this out.  I still don't know why we don't just dynamically detect the version of the pkvm from the .discinfo file instead of relying on the entries that we add into the ``discinfo.pm`` file?   Take a look at 7b56c3d134deb83bfe71c796d6791eb70d18e05d

With the change:
```
# copycds ibm-powerkvm-3.1.0.1-43.0-ppc64le-service-201512021523.iso 
Copying media to /install/pkvm3.1.0/ppc64le
Media copy operation successful

# lsdef -t osimage | grep pkvm
pkvm3.1.0-ppc64le-install-compute  (osimage)
```
I can create a pull request if acceptable...

**Comment by daniceexi** [comment]
@whowutwut The change 7b56c3d134deb83bfe71c796d6791eb70d18e05d looks good if the .discinfo has the fixed IBM_PowerKVM keyword and version number.

I am a little curious that how can you create this commit 7b56c3d134deb83bfe71c796d6791eb70d18e05d in xcat-core without a pull request?

**Comment by whowutwut** [comment]
Right, I searched for the whole string, so at least if PowerKVM is using "IBM_PowerKVM" we will take the version number.  If not, then we just behave like we do today.  

Interesting that the commit looks like it's on xcat-core.. . It's actually this https://github.com/whowutwut/xcat-core/commit/7b56c3d134deb83bfe71c796d6791eb70d18e05d but I took out the beginning URL, let me update the other posts...

**Comment by whowutwut** [comment]
@daniceexi  for PowerKVM 2.1.1 and 3.1.0 (latest version) they both have the IBM_PowerKVM tag in the .discinfo, so i think it's OK to integrate this..  will create the pull request

**Comment by whowutwut** [comment]
Verified on the daily build for 3/16
```
[root@c910f02c05p03 ~]# lsxcatd -v
Version 2.12 (git commit 4c2c870ca2e831157f33caa8c69895c119528635, built Wed Mar 16 15:30:49 EDT 2016)
```
It should be in this weeks Thurs build that will be updated to xcat.org and onwards , will close out this issue.
```
[root@c910f02c05p03 ~]# copycds POWERKVM_V3.1_11_2015.iso 
Copying media to /install/pkvm3.1.0/ppc64le
Media copy operation successful
```
