### ISSUE TITLE
ubuntu 14.04.2 installation boot loop when one more pkglist is added

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#756]
**Issue: **When I added below pkglist, the location is at  9.114.39.157: /install/custom/install/compute.pkglist.full, the installation can not 100% finish, when it goes to 95% , system reboots and goes back to start from xCAT installation, in an endless loop(install, reboot, install reboot...)
When I removed the pkglist, only use the /opt/xcat/share/xcat/install/ubuntu/compute.ubuntu14.04.2.ppc64le.pkglist, it can be installed successfully. 
```
_root@c656ems2:~# cat /install/custom/install/compute.pkglist.full
# nfs and automountd
#nfs-common
autofs
# package management
apt-file
dpkg
debhelper
dkms
dpatch
# useful tools
lsvpd
curl
libcurl4-gnutls-dev
# Debug
apport
gdb
kdump-tools
crash
# make, compile and development tools
autotools-dev
autoconf
libtool
automake1.10
automake
m4
tcl
tcl8.4
chrpath
swig
graphviz
tcl-dev
tcl8.4-dev
tk-dev
tk8.4-dev
bison
flex
zlib1g-dev
python
libxml2
libvirt-bin
libvirt0
libnl-dev
libglib2.0-dev
libgfortran3
gcc
make
# Performance
numactl
libnuma1
hugepages
#linux-tools
ksh
at
build-essential
#linux-headers-generic
#linux-image-generic
zlib1g-dev
cpufrequtils

```

**Comment by wwzhubj** [comment]
the ems is 9.114.39.157
the image I use is: oldcompilers
cn is :c656f6n01

**Comment by daniceexi** [comment]
@penguhyang Please take a look of this issue in @wwzhubj 's environment.

**Comment by immarvin** [comment]
hi, I looked into this problem on @wwzhubj 's env. There are 2 problems here:
1) the size of "/var/lib/dhcpd/dhcpd.leases" file was around 60M+, this made the dhcp response from MN too slow and caused timeout on the dhcp request from compute nodes. In the /var/log/message:
````
...
und
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDISCOVER from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPOFFER on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPREQUEST for 9.114.39.101 (9.114.39.157) from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPACK on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDECLINE of 9.114.39.101 from 00:0a:f7:73:7d:d0 via eth0: not found
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDISCOVER from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPOFFER on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPREQUEST for 9.114.39.101 (9.114.39.157) from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPACK on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDECLINE of 9.114.39.101 from 00:0a:f7:73:7d:d0 via eth0: not found
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDISCOVER from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPOFFER on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPREQUEST for 9.114.39.101 (9.114.39.157) from 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPACK on 9.114.39.101 to 00:0a:f7:73:7d:d0 via eth0
Mar  2 01:59:10 c656ems2 dhcpd: DHCPDECLINE of 9.114.39.101 from 00:0a:f7:73:7d:d0 via eth0: not found
...
````
``makedhcp -n`` will solve this.

2) The pkglist attribute of osimage only support 1 pkglist file specified,otherwise, xCAT will leave a line in preseed file after ``nodeset``:
````
d-i pkgsel/include string #INCLUDE_DEFAULT_PKGLIST_PRESEED#
````
which makes no sense, if user want to use multiple pkglist files, they should create a new pkglist file including all the pkglist files with ``#INCLUDE:#``:
````
cat /tmp/pkglist 
#INCLUDE:/opt/xcat/share/xcat/install/ubuntu/compute.ubuntu14.04.2.ppc64le.pkglist#
#INCLUDE:/install/custom/install/compute.pkglist.full#
````
There is no statement in ``tabdump -d linuximage``  mentions this ,we should add the info and should better output some error message when multiple pkglist files are specified

**Comment by daniceexi** [comment]
@immarvin Thanks for your investigation. 

For the issue 1, if this issue will encounter in customer's cluster, we need to add a tip in xCAT doc;
For the issue 2, yes, we need to update usage message and add error message;

**Comment by whowutwut** [comment]
Can we get the version of xCAT being used documented into this issue?

**Comment by immarvin** [comment]
hi @whowutwut ,
root@c656ems2:~# XCATBYPASS=1 lsxcatd -v 
Version 2.10 (git commit 1176909e54841a4c9ccad2838e959c7e4391d9d8, built Mon Jul  6 23:54:22 EDT 2015)

**Comment by immarvin** [comment]
@wwzhubj , is there any update?

**Comment by wwzhubj** [comment]
I think the error message should be given to user if xCAT don't support multi pkglist, since it cause the installation failed.

**Comment by immarvin** [comment]
fix https://github.com/xcat2/xcat-core/pull/843

**Comment by whowutwut** [comment]
@immarvin  Since there are two problems described in this issue
- Pull Request #843 fixes the 2nd problem described in this issue.

**Comment by immarvin** [comment]
hi @whowutwut , add a tip in https://github.com/xcat2/xcat-core/pull/844
