### ISSUE TITLE
file not found on tftpboot server

### ISSUE THREAD

**Issue by JBBIntel** [xcat2/xcat-core#758]
I am trying to use node discovery to set up a machine on our cluster. I enter the command
nodediscoverstart noderange f072 on the server, and reboot the new machine. I never see the prompt [xCAT Genesis running on f072 /] on the new machine. However, after a while, I enter the nodediscoverstop command, and the server says that it has discovered f072. lsdef f072 shows the correct MAC address, and IP address. However, when I reboot the new machine, it fails trying to read the file /tftpboot/xcat/xnba/nodes/f072, which is not there.

Any suggestions?

**Comment by daniceexi** [comment]
If you did not see the genesis message on the screen but the discovery did finish, you can take a look the system log to confirm whether the discovery happened.

The /tftp/boot/xcat/xnba/nodes/f072 is generated by the 'nodeset' command. If you want to do the OS deployment after the discovery, running the 'nodeset <node> osimage=<osimage name>' before reboot the node.

**Comment by JBBIntel** [comment]
Hi, thanks for the quick response.

I think I see the problem I am having. We have our nodes defined with “chain=runcmd=bmcsetup,shell”. However, this particular node does not have a bmc. So, probably, bmcsetup is failing or hanging.

We will need to manually reboot this node, but we would like it to load its image from xCAT. Will it work OK if I simply set  “chain=runcmd=shell”?

**Comment by daniceexi** [comment]
**runcmd=bmcsetup** is an action, so you need to remove the whole string. **shell** is also an individual action.

**Comment by whowutwut** [comment]
@JBBIntel  To clarify what @daniceexi  said... 

You don't need to run the chain command unless you want to execute the ``bmcsetup`` script and then have genesis enter a shell prompt afterwards.  If the node looks good with the MAC address, the discovery should be complete. 

To remove the whole string:  ``chdef -t node -o f072 chain=""``

You can use xCAT to provision the OS by running:

- ``lsdef -t osimage``  to view the OS images you have, select one of those 
- ``nodeset f072 osimage=<osimage selected>``  This will set up the files in ``/tftpboot`` directory
- ``rsetboot f072 net``  Set the next boot from network
- ``rpower f072 off``
- ``rpower f072 on`` (or ``rpower r072 boot`` to do reset)

If you have the conserver set up , you can ``rcons`` on the node to see the installation progress

**Comment by JBBIntel** [comment]
Thanks, this helps. One question;

  *   rsetboot f072 net Set the next boot from network
  *   rpower f072 off
  *   rpower f072 on (or rpower r072 boot to do reset)
Does this mean that xCAT can bring a system up, when it is powered off, without a BMC? How does that work?

**Comment by whowutwut** [comment]
@JBBIntel  Can you show me the node definition of f072?  ``lsdef f072``   I was making some assumptions in my reply...

**Comment by JBBIntel** [comment]
Object name: f072
    arch=x86_64
    bmc=f072-bmc
    bmcpassword=xxxxxxxxx
    bmcport=1
    bmcusername=root
    chain=runcmd=shell
    cpucount=32
    cputype=06/57
    currchain=boot
    currstate=install rhels7.0-x86_64-compute
    groups=compute,ipmi,knl,all
    initrd=xcat/osimage/rhels7.0-x86_64-install-compute/initrd.img
    installnic=eth0
    ip=192.168.33.72
    kcmdline=quiet inst.repo=http://192.168.33.253:80/install/rhels7.0/x86_64 inst.ks=http://192.168.33.253:80/install/autoinst/f072 ip=eth0:dhcp  inst.cmdline  console=tty0 console=ttyS0,19200n8r
    kernel=xcat/osimage/rhels7.0-x86_64-install-compute/vmlinuz
    mac=90:49:fa:01:41:1d
    memory=32102MB
    mgt=ipmi
    netboot=xnba
    nfsserver=192.168.33.253
    nicips.ib0=192.168.133.72
    nicips.ib1=192.168.134.72
    nicnetworks.ib0=mlxib
    nicnetworks.ib1=tsib
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    ondiscover=nodediscover
    os=rhels7.0
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    primarynic=eth0
    profile=compute
    provmethod=rhels7.0-x86_64-install-compute
    serial=SPRO03200016
    serialflow=hard
    serialport=0
    serialspeed=19200
    supportedarchs=x86,x86_64
    tftpserver=192.168.33.253

**Comment by whowutwut** [comment]
@JBBIntel  From what you posted above the particular node does not have a BMC, but yet the node definition configured in xCAT does show a bmc defined.  And ipmi is used as the mgt.  
```
Object name: f072
...
    bmc=f072-bmc
    bmcpassword=xxxxxxxxx
    bmcport=1
    bmcusername=root
...
    mgt=ipmi
...
```

If you do ``rpower f072 stat`` , does that not return status? 
If it does have communication to the bmc, then it should return. 

But xCAT needs to have some management channel to the BMC/FSP/HMC in order to do hardware control.

**Comment by JBBIntel** [comment]
Victor,

   The node was created using a script that sets various default values for the bmc. However, this particular type of device does not actually have a bmc. It appears that those settings do not cause any major problems, as I am able to reboot it manually, and PXE loads the chosen osimage. But no, rpower f072 stat does not return status. It times out.

Thanks, I think I now understand the process. What I was missing was the role of nodeset.

   Jerome

**Comment by whowutwut** [comment]
Closing this issue, please re-open if you have more comments!
