### ISSUE TITLE
[FVT] CA cert ERROR:  SSL connect attempt failed with unknown error

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#761]
Env:ppc64le rhels7.2
xcatbuild:latest xcatcode
How to reproduce:
```
1.down the latest build
2.[root@c910f03fsp03v02 /]# lsdef
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /opt/xcat/lib/perl/xCAT/Client.pm line 256.
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: SSL connect attempt failed with unknown error at /opt/xcat/lib/perl/xCAT/Client.pm line 266.
[root@c910f03fsp03v02 /]# cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Comment by junxiawang** [comment]
still errors 
-----------------
```
[root@c910f03fsp03v02 ~]# lsdef
*******************************************************************
Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
together with SSL_ca_file|SSL_ca_path for verification.
If you really don't want to verify the certificate and keep the
connection open to Man-In-The-Middle attacks please set
SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
at /opt/xcat/lib/perl/xCAT/Client.pm line 256.
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
Connection failure: SSL connect attempt failed with unknown error at /opt/xcat/lib/perl/xCAT/Client.pm line 266.
```
------------------

**Comment by whowutwut** [comment]
@junxiawang  I think we should change the process reporting bugs to show a xCAT version.   ``lsxcatd -a`` for example...  "Download the latest build" will change depending on when someone looks at the problem and won't identify the build that you used.

**Comment by junxiawang** [comment]
@whowutwut : command could not work according to the bug so I could not run "lsxcatd -a"

**Comment by whowutwut** [comment]
@junxiawang  that makes sense! Thanks for the explanation, can we get the build date of xcat-core?

**Comment by junxiawang** [comment]
@xuweibj 
still errors:
  Updating   : xCAT-2.12-snap201603071531.ppc64                                                                                                                                                 7/14 
Restarting xcatd (via systemctl):  Warning: xcatd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for xcatd.service failed because a timeout was exceeded. See "systemctl status xcatd.service" and "journalctl -xe" for details.
[FAILED]
Running '/opt/xcat/sbin/mknb ppc64', triggered by the installation/update of xCAT-genesis-scripts-ppc64 ...
Connection failure: IO::Socket::INET: connect: Connection refused at /opt/xcat/lib/perl/xCAT/Client.pm line 237.
Unable to open socket connection to xcatd daemon on localhost:3001.
Verify that the xcatd daemon is running and that your SSL setup is correct.
The 'mknb ppc64' command returned error code: 111.

**Comment by xuweibj** [comment]
I tried to update xCAT from 2.11 to 2.12, I did not met this problem. Maybe environmental problem.
Wait for whether reproduce.

**Comment by junxiawang** [comment]
tested
