### ISSUE TITLE
[FVT]: Update SNMP V3 Configuration Example in document  XCAT_iDataPlex_Cluster_Quick_Start

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#766]
In the document 
https://sourceforge.net/p/xcat/wiki/XCAT_iDataPlex_Cluster_Quick_Start/

There is an example of how to configure the snmp v3 configuration on cisco switch. There is a wrong command.
```
  Switch(config)# access-list 10 permit 192.168.0.20    # 192.168.0.20 is the IP of MN
    Switch(config)# snmp-server group xcatadmin v3 auth write v1default
    Switch(config)# snmp-server community public RO 10
    Switch(config)# snmp-server community private RW 10
    Switch(config)# snmp-server enable traps license?
```
Need to modify the last command to "snmp-server enable traps ". So the section should be

```
  Switch(config)# access-list 10 permit 192.168.0.20    # 192.168.0.20 is the IP of MN
    Switch(config)# snmp-server group xcatadmin v3 auth write v1default
    Switch(config)# snmp-server community public RO 10
    Switch(config)# snmp-server community private RW 10
    Switch(config)# snmp-server enable traps 
```

**Comment by whowutwut** [comment]
@tingtli  The change also needs to be done for our RTD documentation.   The documentation you pointed out is also copied into RTD from Issue #432.  

http://xcat-docs.readthedocs.org/en/latest/advanced/networks/ethernet_switches/ethernet_switches.html

I am working on bringing this document over to 2.11 branch, so you don't need to make the change there.

**Comment by whowutwut** [comment]
@tingtli  I updated the typo to remove ``license?`` directly, will set to pending

master: 7ae8361209eb0fa28757fa0601ead8b9d98d0896
2.11: 3fd95c1dcde9e5ead9c81999b6700fed48d2d06f
