### ISSUE TITLE
[Customer]need to set kernel args on netboot

### ISSUE THREAD

**Issue by JBBIntel** [xcat2/xcat-core#776]
I have an osimage which is hanging in boot. I need to debug the boot process. To do so, I need to modify the kernel command line. Is there any way to do this in xCAT?

**Comment by cxhong** [comment]
you can use addkcmdline.  ex:
chdef cn1 addkcmdline="rdloaddriver=scsi_dh_rdac"

**Comment by immarvin** [comment]
hi @JBBIntel , besides the "addkcmdline" mentioned by @cxhong , xCAT also provides a "xcat debug mode" to debug the os installation process, please see https://sourceforge.net/p/xcat/wiki/Debugging_xCAT_Problems/#collect-information-and-logs-from-the-installer-during-os-installation for details

**Comment by daniceexi** [comment]
@JBBIntel 
xcatdebugmode which will be released in 2.12 can meet your requirement. Refer to the doc: http://xcat-docs.readthedocs.org/en/latest/troubleshooting/index.html
