### ISSUE TITLE
[DEV] need to logging the getinstdisk script log to xcat.log properly

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#783]
Currently, the getinstdisk script log can't be logging to the xcat.log properly. 
We need to improve the readability of xcat.log.

**Comment by whowutwut** [comment]
Does the fix now allow the getinstdisk output to be in /var/log/xcat/xcat.log on the compute node?

**Comment by penguhyang** [comment]
Yes, the getinstdisk output can be viewed in /var/log/xcat/xcat.log for redhat,sles,ubuntu.
Also there is a pr for PowerKVM: https://github.com/xcat2/xcat-core/pull/1100
