### ISSUE TITLE
[DEV] site.xcatdebugmode need a fixed value (0 1 blank)

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#787]
Currently, xcatdebugmode can be any value.If xcatdebugmode=0 or xcatdebugmode value is blank, that means xcatdebugmode is off. Using other values turns on xcatdebugmode.
However, most scripts have a verification between 0 and 1. It's necessary to make a fixed value scope for xcatdebugmode.

**Comment by daniceexi** [comment]
@penguhyang Do you plan to support the valid value like '1|Y|y|yes, 0|N|n|no' for site.xcatdebugmode attribute?

**Comment by penguhyang** [comment]
@daniceexi Yes, these valid value will be supported.
