### ISSUE TITLE
[fvt]2.12:Bareword "SSL_VERIFY_PEER" not allowed while "strict subs" in use at docker.pm 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#825]
env:ubuntu14.04.3
build:lsdef - Version 2.12 (git commit 08bac0d779d04a59a4e6397bb13b50bb89be17b2, built Mon Mar 21 15:32:19 EDT 2016)
How to reproduce:
```
 perl -c /opt/xcat/lib/perl/xCAT_plugin/docker.pm
Bareword "SSL_VERIFY_PEER" not allowed while "strict subs" in use at /opt/xcat/lib/perl/xCAT_plugin/docker.pm line 1052
```

**Comment by zet809** [comment]
Merged directly in master branch. Pls verify.

**Comment by zet809** [comment]
@junxiawang If this defect is verified, pls close.
