### ISSUE TITLE
[FVT] Please update the executed message for xcatd start/stop

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#836]
On redhat7.2, while execute the "service xcatd start/stop" the message are "xcatd" not "xCATd" as sles and Ubuntu. Please make them unified.

RH7.2
```
[root@c910f02c01p13 ~]# lsxcatd -a
Version 2.12 (git commit 4a340b3a84e03fdff895b18870e12b8e0f170d7d, built Tue Mar 22 09:30:38 EDT 2016)
This is a Management Node
cfgloc=mysql:dbname=xcatdb;host=10.2.1.13|xcatadmin
dbengine=mysql
dbname=xcatdb
dbhost=10.2.1.13
dbadmin=xcatadmin
[root@c910f02c01p13 ~]# service xcatd status
xCAT service is running
[root@c910f02c01p13 ~]# service xcatd stop
Stopping xcatd (via systemctl):                            [  OK  ]
[root@c910f02c01p13 ~]# service xcatd start
Starting xcatd (via systemctl):                            [  OK  ]
```

Ubuntu:
```
root@c910f03fsp03v06:~# service xcatd stop
Stopping xCATd  *
root@c910f03fsp03v06:~# service xcatd start
Starting xCATd Error loading module /opt/xcat/lib/perl/xCAT_plugin
 *
root@c910f03fsp03v06:~# service xcatd status
xCAT service is running
```

Sles:
```
c910f02c01p14:~ # service xcatd status
xCAT service is running
c910f02c01p14:~ # service xcatd stop
Stopping xCATd                                         done
c910f02c01p14:~ # service xcatd start
Starting xCATd                                         done
c910f02c01p14:~ #
```

**Comment by daniceexi** [comment]
I am thinking in the doc, we use 'xCAT', but in the code, to simplify the coding, message searching, I'd like it can be 'xcat' and 'xcatd'.  @hu-weihua what do you think?

**Comment by whowutwut** [comment]
Just my opinion, if we look at something like rsyslog. the program is "rsyslog" but the daemon running is ``rsyslogd`` on RHEL.  Ubuntu is similar, the process is ``rsyslogd`` but when you query status , it's ``rsyslog``

So maybe if we wanted to be consistent with the naming, we can do like @daniceexi suggested, in the docs we use xCAT but in the code we use lower case, ``xcat`` or ``xcatd``. 

I think the message should be... 

Start: ``starting xcat...``
Stop: ``stopping xcat...``
Status: ``xcat is running`` or ``xcat is not running``

**Comment by hu-weihua** [comment]
@daniceexi  and @whowutwut, I agree with you for the uniform naming, using xCAT in doc and using xcat in code.

But as far as this defect opened by @caomengmeng be concerned, I double checked our code, I found in our /etc/init.d/xcatd, we use "xCAT" always.  Maybe you have noticed in RH7.2 scenario, ``systemctl`` is involved. I think below information come from ``systemctl``, not our code:

    [root@c910f02c01p13 ~]# service xcatd stop
    Stopping xcatd (via systemctl):                            [  OK  ]
    [root@c910f02c01p13 ~]# service xcatd start
    Starting xcatd (via systemctl):                            [  OK  ]

So it can explain why just above 2 command's output use "xcatd", the rest commands, not matter RH7.2, SLES  or ubuntu, use "xCAT".  ``systemctl`` uses the program name in its output.

But we also can uniform our naming in code, using "xcat" instead of "xCAT".

**Comment by daniceexi** [comment]
Yes, there are a lot places using **xCAT**. Maybe we can just unify the usage of **xcatd** to be low-case **xcatd** instead of having both **xcatd** and **xCATd** in the messages.  Change the sbin/xcatd and /etc/init.d/xcatd should be enough.

**Comment by whowutwut** [comment]
I mentioned this in #492 ... I think we should look into supporting systemd.  sysVinit is going to eventually go away and we should have the xcat start/stop/restart functionality into a xcat.service file somewhere under ``/etc/systemd/``

**Comment by daniceexi** [comment]
@whowutwut we had an investigation before, the systemd has problem to support current 'xcatd quick restart' function. And we did not see the goodness to move xcatd.service. This is way we still keep using the sysV start file. 
If someday we must move to xcatd.service, we may need to leverage xcat command **restartxcatd** to offer the function **xcatd quick restart**.

**Comment by caomengmeng** [comment]
It is "xcatd" now, tested in automation regression and  passed.
