### ISSUE TITLE
[DEV] Update the default compute node templates with a more real world partitioning scheme

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#842]
The default partitioning scheme provided by xCAT should not only use a single / partition. 

There are recommended partitioning schemes out there.. just one example: 
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s2-diskpartrecommend-x86.html

At a minimum, I think we should have partitions for the following: 

```
/boot
/var
/tmp
/
```

maybe even add `/home`

I am seeing scenarios where we are using xCAT to provision nodes and then run some service on it only to find that the file system gets filled up to 100% and the machine has other problems.  

While, yes, it is up to the admin to define their customer partition scheme, xCAT should do better in providing a generic compute server that can be used as as long running machine "out of the box"

**Comment by daniceexi** [comment]
The change needs a lot of effort, move this issue to 2.13.

**Comment by whowutwut** [comment]
@daniceexi  I think if this change requires too much effort, Instead of doing all or nothing, maybe we can at least create a few pull request that would work us towards this end goal.  The first being...  partition `/var` to something like 4GB so that we cannot fill the entire filesystem from entries in /var/logs

**Comment by daniceexi** [comment]
Looking forward the input from @immarvin

**Comment by zet809** [comment]
Adding @neo954 to get more input.

**Comment by zet809** [comment]
We can include this issue for rh8.0 support.

**Comment by immarvin** [comment]
hi @neo954 , would you please take a look at this ticket when you work on rh8 support? thx

**Comment by neo954** [comment]
In pull request #5341 for RHEL 8 support, there is a new default partitioning scheme which is similar to the RHEL 8 default partitioning scheme.

* A separate `/boot` partition, size 512MB.
* All the remain disk space will be used as LVM physical volume. Inside which, one volume group will be created.
* Root file system will be inside the LVM volume group.
* A swap partition will be created inside the LVM volume group with the Red Hat recommended size.

**Comment by whowutwut** [comment]
@neo954 should we also put /var in its own partition. This way messages won’t fill up the root file system

**Comment by immarvin** [comment]
@neo954 revised the partition schema for rh8 in PR https://github.com/xcat2/xcat-core/pull/6219
