### ISSUE TITLE
[DEV]xCAT mknb command needs update in the docs 2.11 and onwards 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#846]
Should fix this in 2.11 branch and cherry pick forwards. 

We should clean up some of the text formatting and update to support ppc64. 
http://xcat-docs.readthedocs.org/en/2.11/guides/admin-guides/references/man8/mknb.8.html

Another issue we see is that if the management node changes IP address, there are some static things build into the genesis kernel that would require mknb to be rerun.

**Comment by zet809** [comment]
@whowutwut For the issue you mentioned, it is correct that mknb will create default petitboot configuration file. If the MN ip is changed especially changed to another subnet, mknb need to be rerun to create a new petitboot configuration file for the new subnet.

**Comment by daniceexi** [comment]
Two places should be checked

* in the MN IP mgmt doc, run **mknb** if changing the ip of MN
* in the mixed cluster doc, make sure the genesis is installed.

**Comment by zet809** [comment]
@xuweibj Hi, xu wei, will you pls help to update document? Thx!

**Comment by xuweibj** [comment]
Hi @whowutwut , I have updated the docs. Could you help to check this issue?

**Comment by whowutwut** [comment]
@xuweibj sorry for the delay.  I tried to cherry pick the changes to 2.11 and it did not work so i cannot direct cherry pick for you.  

Can you make the changes for 2.11 branch and create a pull request for 2.11 branch.  The pull request #1263 is incorrect because you need to fetch the upstream and update your 2.11 branch.   Let me know if you need some clarifications. Thanks!

**Comment by xuweibj** [comment]
Hi @whowutwut , I did not pull request for 2.11 about this issue. I pushed my commit directly to 2.11 branch. The modified docs are mknb.8.pod and mknb.8.rst. In 2.11 branch, for docs folder, you can see "Fix issue 846, update mknb doc". Please help to check. Thanks.

**Comment by whowutwut** [comment]
@xuweibj  thanks, I found the commit ID and added it to the pull request notes.  Thanks!
