### ISSUE TITLE
[DEV]Consider deprecating the man pages over on SourceForge

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#847]
We have man pages that are hosted on SourceForge, one example:
http://xcat.sourceforge.net/man8/mknb.8.html

Should we replace all the man pages there with redirect to the read the docs man page reference? 
@tingtli @daniceexi ?

**Comment by daniceexi** [comment]
Since xCAT's policy is to support two major versions, my idea is after release of xcat 2.12, we can just block the whole manpage page and prompt a message that RTD should be used. Then people wil be pushed to use RTD and github if they were still using SF.

**Comment by tingtli** [comment]
I agree that we redirect all the docs to read docs. That's easy for customers to covert to the new location

**Comment by whowutwut** [comment]
Some of the SF site is still valid though. For example, the AIX info... HMC support.. FSP... At this time RTD only focused on OpenPower mgmt servers.. 

But the man pages I think we can redirect them to http://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/references/index.html#xcat-man-pages

**Comment by daniceexi** [comment]
I am OK with that.

**Comment by whowutwut** [comment]
Taking this page as an example: http://xcat.sourceforge.net/man1/addkit.1.html

We can replace each html file to be a redirect to the RTD latest man page, click on this link new_addkit.1.html.   http://xcat.sourceforge.net/man1/new_addkit.1.html

Thoughts?

**Comment by daniceexi** [comment]
It's looks good. But do we really want to put effort to do that?

**Comment by whowutwut** [comment]
It's a one time effort and can be scripted to generate the html redirection

**Comment by daniceexi** [comment]
Then I am OK to do that.

**Comment by pdlun92** [comment]
script sf_redirect.pm created on sourceforge server, run against docs.  All sourceforge docs now redirect to readthedocs counterparts.  Replaced files with broken links (do not exist on readthedocs) to original html

**Comment by whowutwut** [comment]
Thanks @pdlun92!   It looks like we could attach the script to here so if we needed it in the future, it would be helpful.  Can you try and upload it or attach it to a comment... then I'll close out this issue or feel free to close this one out.

**Comment by pdlun92** [comment]
Contents of sf_redirect.pm
```
#!/usr/bin/perl

#store all .html files (excluding index's) in array
my @files = `find . -name "*.*.html" ! -name "*index*" | grep "man*"`;
foreach(@files){
  chomp($_);
  write_file($_);
}

sub write_file {
  my $new_file = shift;
  open(my $file_handler, '>', $new_file);
  print $file_handler "<!DOCTYPE html>\n";
  print $file_handler "<html>\n";
  print $file_handler "<head>\n";
  print $file_handler "   <!-- HTML meta refresh URL redirection -->\n";
  print $file_handler "   <meta http-equiv=\"refresh\"\n";
  print $file_handler "      content=\"0; url=http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/references/".substr($new_file,2)."\">\n";
  print $file_handler "</head>\n";
  print $file_handler "<body>\n";
  print $file_handler "    <p>The page has moved to:\n";
  print $file_handler "        <a href=\"http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/references/".substr($new_file,2)."\">this page</a></p>\n";
  print $file_handler "</body>\n";
  print $file_handler "</html>\n";
  close $file_handler;

}
```
