### ISSUE TITLE
[FVT] [21 Apr 2016] Need verify Ubuntu 16.04 final release support against the latest xCAT master build

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#859]
Ubuntu 16.04 will be released on April 21st, 2016. Please refer the Ubuntu 16.04 release schedule [1].

[1] https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule

**Comment by immarvin** [comment]
Can some one in  FVT perform the verification ? @tingtli

**Comment by neo954** [comment]
Verified basic diskfull/diskless provisioning on PowerKVM guest.
Verified bare metal operating system installation on PowerNV 8335-GTA.
Everything worked fine.

**Comment by neo954** [comment]
Latest GA build verified. Will close this one.
