### ISSUE TITLE
[FVT] On Ubuntu 16.04, rsa1 is unsupported key type

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#861]
# /usr/bin/ssh-keygen -t rsa1 -f /etc/xcat/hostkeys/ssh_host_key -C '' -N ''
    Generating public/private rsa1 key pair.
    Saving key "/etc/xcat/hostkeys/ssh_host_key" failed: unknown or unsupported key type

The original problem came from an E-mail report. Please see below for the details.

> After trying to run nodeset on a Ubuntu 16.04 MN, I came across these errors:

>     Error: /install/postscripts/hostkeys/ssh_host_key.pub is missing. Run xcatconfig (no force)
>     Error: /etc/xcat/hostkeys/ssh_host_key.pub is missing. Run xcatconfig (no force)

> After doing some exploring in xcatconfig, it seems that four types of keys should be generated: SSH1 RSA, SSH2 RSA, SSH2 DSA, and SSH2 ECDSA.  All were present except for the rsa1 key which should have been generated by the "/usr/bin/ssh-keygen -t rsa1 -f /etc/xcat/hostkeys/ssh_host_key -C '' -N ''" command in xcatconfig.  

> My questions are: 
> What is the purpose of each of the 4 different key types? Do we need to be generating all 4?
> Is it possible that Ubuntu 16.04 doesn't support rsa1 any more?  Or perhaps it is a beta issue?

**Comment by neo954** [comment]
The ``nodeset`` command will print out two lines of error messages. But beside these error messages, no other side effect was observed. 

    # nodeset c910f03c17k07 osimage=ubuntu16.04-ppc64el-install-compute
    Error: /install/postscripts/hostkeys/ssh_host_key.pub is missing. Run xcatconfig (no force)
    Error: /etc/xcat/hostkeys/ssh_host_key.pub is missing. Run xcatconfig (no force)
    c910f03c17k07: install ubuntu16.04-ppc64el-compute

**Comment by daniceexi** [comment]
@neo954 on my ubuntu 14.04.4, in the man page of ssh-keygen, it list the **rsa1** is support. What are  the valid value in your ubuntu 16.04?

~~~~
     -t type
             Specifies the type of key to create.  The possible values are "rsa1" for protocol version 1 and "dsa",
             "ecdsa", "ed25519", or "rsa" for protocol version 2.
~~~~

**Comment by whowutwut** [comment]
The error that comes out at runtime is from TableUtils.pm, and at this line: 

```
1574     # ssh hostkeys
1575     $dir = "$installdir/postscripts/hostkeys";
1576     if (-d $dir)
1577     {
1578         my $file = "$dir/ssh_host_key.pub";
1579         if (-e $file)
1580         {
1581             my $file2  = "$dir/*.pub";                     # all public keys
1582             my $cmd    = "/bin/chmod 0644 $file2";
1583             my $outref = xCAT::Utils->runcmd("$cmd", 0);
1584             if ($::RUNCMD_RC != 0)
1585             {
1586                 my $rsp = {};
1587                 $rsp->{data}->[0] = "Error on command: $cmd";
1588                 xCAT::MsgUtils->message("I", $rsp, $cb);
1589 
1590             }
1591         }
1592         else
1593         {                                                  # hostkey missing
1594             my $rsp = {};
1595             $rsp->{data}->[0] = "Error: $file is missing. Run xcatconfig (no force)";
1596             xCAT::MsgUtils->message("I", $rsp, $cb);
1597         }
1598     }
```

We are checking for the ssh_host_key.pub being present, then doing a chmod on all the .pub files in that directory...  so it's just by coincidence that we hit this problem because if we checked one of the other 3 keys, we would not see it. 
 
So the question is, do we use the rsa1 type key anywhere in the xCAT code or just created for convenience?  ( @pdlun92 FYI )

**Comment by daniceexi** [comment]
From @neo954 that on Ubuntu 16.04, the **rsa1** was still supported. But the execution failed. @neo954 will continue to dig what was the problem, the code or man page.

Poeple said the **rsa1** is not safe now, the **rsa** is recommened. so do NOT check the **rsa1** is acceptable.

**Comment by whowutwut** [comment]
Yes, I think we should just stop using rsa1.  

If we don't want to make that change now and stop creating the keys, for Ubuntu  16.04, there will only be 3 keys generated because the rsa1 one will fail.  We can at least change the code to not check for ssh_host_key.pub and just check ssh_host_rsa_key.pub.  (type=rsa)

If agreed, @pdlun92  can make that change.

**Comment by daniceexi** [comment]
Yes, I agree with removing the check for **rsa1** key **ssh_host_key.pub**.

**Comment by neo954** [comment]
This bug is verified and will be closed.
