### ISSUE TITLE
[FVT]Blocked to provision stateless CN using xcat-core-rpms-2.11GA build on RHEL7.2 LE env

### ISSUE THREAD

**Issue by bhbai** [xcat2/xcat-core#862]
Steps to reproduce:
1. Install MN, using the xcat-core-rpms-2.11.1110.tar.bz2 build( which intergrated in PCM ppc64 LE 0322 build.)

2. After try to provision stateless CN, you can see below: 

> /install/osimages/rhels7.2-ppc64le-stateless-compute/rootimage/rootimg/etc/rc.d/init.d/localdisk:LOGDIR="/.sllocal/log"
**Above operation failed because folder :/.sllocal/log not exist**

Test ENV:
MN:

> [root@ppc803c ~]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
IBM Spectrum Cluster Foundation Advanced Edition 4.2.2 (build 160322)

Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by daniceexi** [comment]
I think the path **/install/osimages/rhels7.2-ppc64le-stateless-compute/rootimage/rootimg** is the location for your rootimg. Could you check the path **.sllocal/log** in this rootimg path? The file etc/rc.d/init.d/localdisk does try to mount **.sllocal/log**, but even if it failed, it would not impact the diskless boot.

**Comment by bhbai** [comment]
1. This issue blocked provision diskless image in PCM on LE/BE-rhel 7.2 env.
2. -     Pass while provision diskfull image in PCM on LE/BE/-rhel 7.2 env 
    -     Pass while provision diskless/diskfull image in PCM on x86_64/-rhel 7.2 env

3. The file etc/rc.d/init.d/localdisk NOT  create .sllocal/log before use. We have tried to **mkdir** before mount, but sill block with other similar folder missing.(So we think maybe missing package a folder structure in diskless mode ...)
4. In RTC tracking [defect id is 95028](https://jazz07.rchland.ibm.com:21443/jazz/web/projects/pc-management#action=com.ibm.team.workitem.viewWorkItem&id=95028)

---we modified file localdisk as following:----
`# Create a tmpfs for log (this is necessary for nfs-based statelite)`
`mkdir -p ${MNTDIR}/$LOGDIR`
`mount -t tmpfs rw ${MNTDIR}/$LOGDIR`



detail info refer to attachment.
![2016-03-30 12_51_33-xcatstatelessblocked](https://cloud.githubusercontent.com/assets/18112233/14132287/ca18ca6c-f676-11e5-84bc-1044defc7c49.png)

**Comment by daniceexi** [comment]
@bhbai From the error message: **No space left on device**, it looked like there were no enough space for the system to continue. Since it was a diskless, I guess the node had not enough memory.

**Comment by bhbai** [comment]
After increase CN memory from 4GB to 8GB , now provision OK now.
Now ego3.3 size increase from 100M to 700M,so stateless memory min requirement changed from 4GB to 8GB

[root@cnless002 ~]# cd /opt/pcm/
[root@cnless002 pcm]# ls
ego log properties
[root@cnless002 pcm]# du -sh
1.2G .
 
[root@ppc803c pcm]# cd /opt/pcm/ego
[root@ppc803c ego]# du -sh
1.2G  4:37:36 PM

**Comment by daniceexi** [comment]
OK, then I close this issue.
