### ISSUE TITLE
[DEV]Support ipmitool-xcat version 1.8.17

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#871]
I noticed there is ipmitool-1.8.16 available for download.   Opening this issue to keep as a reminder to see whether we specifically need to upgrade the ipmitool-xcat version to be at this 1.8.16 level...  Maybe needed for NGS?  https://sourceforge.net/projects/ipmitool/

@zet809 @pdlun92 @chenglch

**Comment by daniceexi** [comment]
check whether this 1.8.16 is helpful to fix the rcons breaking issue, if no, moving to 2.13 branch.

**Comment by whowutwut** [comment]
Agreed, let's move this to 2.13

**Comment by pdlun92** [comment]
https://github.com/xcat2/xcat-dep/pull/12

**Comment by whowutwut** [comment]
Closing this issue, we are shipping 1.8.17 with xCAT 2.12.3
