### ISSUE TITLE
[Customer]Merge one patch into 2.11-PCM to support pKVM3.1

### ISSUE THREAD

**Issue by xiangzhzh** [xcat2/xcat-core#880]
PCM need to support power KVM 3.1, so will you please apply the latest patch into 2.11-PCM branch to support this feature?
Patch link:
https://github.com/xcat2/xcat-core/commit/becc0312cc1729d7cce1455cb2c49cc4b4e3b466

**Comment by daniceexi** [comment]
@xiangzhzh Please talk with someone who familar with **github pullrequest** and submit a pull request for this change.

**Comment by whowutwut** [comment]
@daniceexi  I committed that change.. do we want a pull request created for this or I can just cherry pick it into the 2.11-PCM branch...  I don't think a pull request is needed because it's not a new code.

**Comment by tingtli** [comment]
@Victor, when you cherry pick this fix to 2.11-PCM, do you cherry pick other fixes in 2.11.1 to 2.11-PCM?

Do we just provide 2.11.1 to PCM?

**Comment by whowutwut** [comment]
@tingtli , No I have not cherry picked other fixes into the 2.11-PCM branch. Maybe that's why @daniceexi suggested that @xiangzhzh  should create a pull request that contains the fixes that they feel they want in the 2.11-PCM brach...

**Comment by daniceexi** [comment]
@whowutwut It's OK to cherry-pick the change for pkvm copycds support to PCM branch. But I still want the PCM team to cover the changes by themselves so that they know what the change will impact their build.

**Comment by whowutwut** [comment]
@xiangzhzh I cherry picked this change directly to the 2.11-PCM branch : 7b56c3d134deb83bfe71c796d6791eb70d18e05d

However, like Xiao Peng suggested.  For future, a pull request should be made by the PCM team to cherry pick the fixes they want to the 2.11-PCM branch and xCAT team can review and help merge. This should be the process moving forward.
