### ISSUE TITLE
[FVT]: Update test cases  and configuration files in autotest to process Baremetal machines 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#885]
In our old test cases bucket, we only support virtual machines provision such as LPAR, vm etc.
Now, we add bare metal machines support.  We need to updates following files.
```
updates diskful provision cases to process the node's mgt attribute  Judge if mgt=ipmi, if yes, run this case with baremetal specific steps, otherwise, use virtual machine steps. 
```

**Comment by hu-weihua** [comment]
I think we can use node attribute ``mgt`` directly

**Comment by tingtli** [comment]
fixed with pull request 939
