### ISSUE TITLE
[FVT] Messed up output of rscan against PowerKVM host

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#894]
Below is the output of command ``rscan`` against a PowerKVM host.

First of all, the column of the name of PowerKVM guest and the column of the name of hypervisor are mixed.

Second, the first line of the output is unmeaningly.

    # rscan c910f03c17
    type    name      id      host
    type    name     hypervisor     id     cpu     memory     nic     disk
    kvm     c910f03c17k03c910f03c17     163    8       6144       brenP3p9s0f0
    kvm     c910f03c17k37c910f03c17     113    4       6144       brenP3p9s0f0
    kvm     c910f03c17k43c910f03c17     196    4       6144       brenP3p9s0f0
    kvm     c910f03c17k38c910f03c17     114    4       6144       brenP3p9s0f0
    kvm     c910f03c17k09c910f03c17     146    2       6144       brenP3p9s0f0
    kvm     c910f03c17k28c910f03c17     104    4       6144       brenP3p9s0f0
    kvm     c910f03c17k14c910f03c17     162    4       6144       brenP3p9s0f0
    kvm     c910f03c17k25c910f03c17     211    4       6144       brenP3p9s0f0
    kvm     c910f03c17k27c910f03c17     103    4       6144       brenP3p9s0f0
    kvm     c910f03c17k04c910f03c17     80     2       6144       brenP3p9s0f0
    kvm     c910f03c17k16c910f03c17     92     4       6144       brenP3p9s0f0
    kvm     c910f03c17k13c910f03c17     212    4       6144       brenP3p9s0f0
    kvm     c910f03c17k39c910f03c17     115    4       6144       brenP3p9s0f0
    kvm     c910f03c17k26c910f03c17     102    4       6144       brenP3p9s0f0
    kvm     c910f03c17k18c910f03c17     94     4       6144       brenP3p9s0f0
    kvm     c910f03c17k40c910f03c17     116    4       6144       brenP3p9s0f0
    kvm     c910f03c17k22c910f03c17     98     4       6144       brenP3p9s0f0
    kvm     c910f03c17k36c910f03c17     112    4       6144       brenP3p9s0f0
    kvm     c910f03c17k20c910f03c17     96     4       6144       brenP3p9s0f0
    kvm     c910f03c17k10c910f03c17     156    2       6144       brenP3p9s0f0
    kvm     c910f03c17k30c910f03c17     203    4       6144       brenP3p9s0f0
    kvm     c910f03c17k19c910f03c17     95     4       6144       brenP3p9s0f0
    kvm     c910f03c17k34c910f03c17     110    4       6144       brenP3p9s0f0
    kvm     c910f03c17k07c910f03c17     125    2       6144       brenP3p9s0f0
    kvm     c910f03c17k42c910f03c17     118    4       6144       brenP3p9s0f0
    kvm     c910f03c17k23c910f03c17     99     4       6144       brenP3p9s0f0
    kvm     c910f03c17k11c910f03c17     157    2       6144       brenP3p9s0f0
    kvm     c910f03c17k21c910f03c17     97     4       6144       brenP3p9s0f0
    kvm     c910f03c17k29c910f03c17     105    4       6144       brenP3p9s0f0
    kvm     c910f03c17k33c910f03c17     109    4       6144       brenP3p9s0f0
    kvm     c910f03c17k17c910f03c17     93     4       6144       brenP3p9s0f0
    kvm     c910f03c17k35c910f03c17     111    4       6144       brenP3p9s0f0
    kvm     c910f03c17k41c910f03c17     117    4       6144       brenP3p9s0f0
    kvm     c910f03c17k06c910f03c17     82     2       6144       brenP3p9s0f0
    kvm     c910f03c17k12c910f03c17     160    2       6144       brenP3p9s0f0
    kvm     c910f03c17k05c910f03c17     81     2       6144       brenP3p9s0f0
    kvm     c910f03c17k15c910f03c17     91     4       6144       brenP3p9s0f0
    kvm     c910f03c17k24c910f03c17     100    4       6144       brenP3p9s0f0
    kvm     c910f03c17k08c910f03c17     164    2       6144       brenP3p9s0f0

Please refer the output below for the detail revision number of the xCAT.

    # lsxcatd -v
    Version 2.12 (git commit 15db4f31e05657c27f8143e042272839ba6f8dc9, built Wed Apr  6 09:32:22 EDT 2016)

**Comment by neo954** [comment]
Will verify it later.

@immarvin, please do not close the issue directly. Instead, please use the ``pending`` label.

**Comment by daniceexi** [comment]
The rscan issues will be moved to 2.12.1

**Comment by penguhyang** [comment]
This bug has been fixed in #897

**Comment by neo954** [comment]
Will close this one.
