### ISSUE TITLE
[FVT] rscan against PowerKVM host cannot detect vmstorage with block device

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#895]
Below is part of output of command ``rscan``. As you can see, the ``vmstorage`` attribute is empty.

    # rscan c910f03c17 -z
    # <xCAT data object stanza file>

    c910f03c17k22
        arch=ppc64le
        mac=42:05:0a:03:11:16
        mgt=kvm
        vmcpus=4
        vmhost=c910f03c17
        vmmemory=6144
        vmnicnicmodel=virtio
        vmnics=brenP3p9s0f0
        vmstorage=
    c910f03c17k43
        arch=ppc64le
        mac=42:35:0a:03:11:2b
        mgt=kvm
        vmcpus=4
        vmhost=c910f03c17
        vmmemory=6144
        vmnicnicmodel=virtio
        vmnics=brenP3p9s0f0
        vmstorage=

Actually, these PowerKVM guests use block devices as the ``vmstorage``s.

    # lsdef c910f03c17k22
    Object name: c910f03c17k22
        arch=ppc64el
        currchain=boot
        currstate=boot
        groups=all
        id=22
        initrd=xcat/osimage/ubuntu14.04.4-ppc64el-install-compute/initrd.img
        kcmdline=nofb utf8 auto url=http://!myipfn!/install/autoinst/c910f03c17k22 xcatd=!myipfn! mirror/http/hostname=!myipfn! netcfg/choose_interface=42:05:0a:03:11:16 console=tty0 console=hvc0,115200 locale=en_US priority=critical hostname=c910f03c17k22 live-installer/net-image=http://!myipfn!/install/ubuntu14.04.4/ppc64el/install/filesystem.squashfs
        kernel=xcat/osimage/ubuntu14.04.4-ppc64el-install-compute/vmlinuz
        mac=42:05:0a:03:11:16|42:03:0a:03:11:16!*NOIP*
        mgt=kvm
        netboot=grub2
        os=ubuntu14.04.4
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles
        profile=compute
        provmethod=ubuntu14.04.4-ppc64el-install-compute
        serialport=0
        serialspeed=115200
        status=booted
        statustime=03-22-2016 05:02:37
        vmcpus=4
        vmhost=c910f03c17
        vmmemory=6144
        vmnics=brenP3p9s0f0,brenP3p9s0f1
        vmstorage=phy:/dev/mapper/vdiskvg03-vdisk01n22

**Comment by neo954** [comment]
This is the bottom line of the ``rscan`` against PowerKVM feature. With all the shaped of PowerKVM guest machines created by xCAT. Command ``rscan`` can get the node definitions back, and then end user can definition the same PowerKVM guest machines with the same shape on another xCAT management node.

If this ``rscan`` feature lost any support of node attributes we already have against PowerKVM guest machines. I don't think this feature can be considered as "done".

Thus, the bottom line is support what we already supported.

**Comment by daniceexi** [comment]
The rscan issues will be moved to 2.12.1
