### ISSUE TITLE
[FVT]: No hierarchy support for sles12 and sles12.1

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#898]
When i setup test environment on Jenkins, I setup cluster to run regression on sles12 and sles12.1. 
I found there is no service image. And the old way to install mysql is not correct. Please take a look at the hierarchy support on sles12 and sles12.1.

**Comment by cxhong** [comment]
@immarvin, @tingtli  I will take look this issue.

**Comment by whowutwut** [comment]
we want to check the 2.11 branch to see if it also exist, we should fix since hierarchy is considered basic function for RHEL  & SLES

**Comment by daniceexi** [comment]
This feature will be done in 2.12.1

**Comment by whowutwut** [comment]
@hu-weihua  can we have someone verify on behalf of Ting Ting and close out?

**Comment by hu-weihua** [comment]
@junxiawang , Could you help to take look at this issue? thank you very much.

**Comment by junxiawang** [comment]
@whowutwut @daniceexi @cxhong 
sles12.1 on ppc64le could work for hierarchy
But sles12 on x86_64 could not work

**Comment by cxhong** [comment]
since mysql is running on the system before we ran "mysqlsetup -i" , xcat will not run initialization again.
`````
c910f03c04k04:~ # mysqlsetup -i
MySQL is running.  Database initialization will not take place.
``````
so if password is not matched, it will exit with "Wrong MySQL root password".   

For debian and sles12.1,   after install mysql/mariadb server, the mysql will running, so we will stop mysql first, then run initialization.  

I don't think mysql is running after installation for sles12.  so, this is correct behavior for our current design.  

@daniceexi @immarvin ,  do we need to change the code to stop DB service for any OS if it is "-i" flag ?

**Comment by immarvin** [comment]
hi @cxhong , I think we do not need to stop mysql in the "mysqlsetup" code for the linux distributions except debian and sles12.1 since the mysqlsetup manpage has  mentioned this. I still have 2 questions on this:
1. when the message "MySQL is running.  Database initialization will not take place." is raised, why does "mysqlsetup -i" not return? 
2. the message "MySQL is running.  Database initialization will not take place." is raised, why does "mysqlsetup -i"  is not instructive enough for user, how about modify it to be "MySQL is running. Please stop it first"?

**Comment by cxhong** [comment]
@immarvin , looking the code, if mysql is already running,  we are not going to initialize the database again, like setup my.cnf, chkconfig on and set mysql root password.  xCAT will assume root password is already set in this case and will get to verify mysql root password step.   
we can change that message to: "MYSQL IS RUNNING.  please stop it first, otherwise Database initialization will not take place"

**Comment by immarvin** [comment]
@cxhong , ok

**Comment by whowutwut** [comment]
I'm going to move this to 2.12.2 and remove pending since it seems like there is some additional work required.

**Comment by whowutwut** [comment]
@immarvin  I think we agree that we should not stop MySQL. The user could be using the DB for something other than xCAT and if it's running, we just want to put the xCAT data into the database.  I think the `Database initialization will not take place` just means that we will not initialize the database with a password.  The admin already initialized the DB so they need to provide xCAT with the right password... .  @junxiawang  I'm not understanding the comment you have above. Did you enter the correct password for mysql?  @cxhong  said she went onto the machine and entered the correct password and it continued on.

So are there still any issues or is this verified?

**Comment by immarvin** [comment]
hi @junxiawang @tingtli , regarding to the comments by @cxhong ans @whowutwut , would you please verify the issue whether this issue still exist? thanks

**Comment by tingtli** [comment]
@immarvin @cxhong 
I provision a fresh sles12 node, configure it as mn, and install the mariadb packages. Then run mysqlsetup -i to initialize the db. there still has issue.

```
c910f03c04k03:~ # mysqlsetup -i
Input the alpha-numberic  password for xcatadmin in the MySQL database:
Input the password for root in the MySQL database:
Command failed: /usr/bin/mysql_install_db --user=mysql 2>&1. Error message: .

 /usr/bin/mysql_install_db --user=mysql failed.
```
This node is in problem state, please login this node to take a look.

**Comment by cxhong** [comment]
/usr/bin/mysql_install_db is not available in the system,
````
c910f03c04k03:/usr/bin # /usr/bin/mysql_install_db --user=mysql
-bash: /usr/bin/mysql_install_db: No such file or directory
```````
 you didn't install mariadb package on your system
````
c910f03c04k03:/usr/bin # rpm -qa | grep mariadb
mariadb-errormessages-10.0.11-6.4.ppc64le
mariadb-client-10.0.11-6.4.ppc64le
`````
that's the required packages to running on mariadb on sles and documented on xcat doc..
````
MariaDB - Using zypper, ensure that the following packages are installed on the management node:

mariadb-client-10.*
mariadb-10.*
mariadb-errormessages-10.*
libqt4-sql-mysql-*
libmysqlclient18-*
perl-DBD-mysql-*
``````

anyway, I will open a pull request to add the code to check if this command exists.

**Comment by tingtli** [comment]
That's weird. I check the packages before I install.
I will go ahead to verify the sn provision.

**Comment by caomengmeng** [comment]
@tingtli 
With latest daily build, after SN is booted successfully, failed to boot CN after retry for several times, CN is booting status, and rcons CN, messages in screen are below:
···
 If using -m squashfs did you include aufs.ko with geninitrd?
  e.g.:  -n tg3,squashfs,aufs,loop
* If using -m nfs did you export NFS and sync rootimg?  And
  did you include the aufs and nfs modules in the proper order:
  e.g.:  -n tg3,aufs,loop,sunrpc,lockd,nfs_acl,nfs


/usr/sbin/xcatroot: line 254: /bin/dash: No such file or directory


[   42.868252] dracut Warning: Could not boot.
dracut Warning: Could not boot.


Generating "/run/initramfs/rdsosreport.txt"
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

To get more debug information in the report,
reboot with "rd.debug" added to the kernel command line.

Dropping to debug shell.
···

**Comment by immarvin** [comment]
what is the node definition ang osimage definition of the cn?

**Comment by tingtli** [comment]
@caomengmeng @immarvin 
 I take a look at the CN. The issue is because the CN get dhcp reply from other node, not SN. I login the node and delete the CN in dhcp release, then rerun the provision. It succeeded.
I run both diskful and diskless provision. All passed. I will close this issue.
I find another small issue, i will open another defect to trace that.
