### ISSUE TITLE
[FVT]ubuntu16.04 could not set up mariadb according document

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#908]
env:ubuntu 14.04.4 ppc64le
build:lsdef - Version 2.12 (git commit c2418b67d774dec567dab489b2168d8f89b8f4ae, built Mon Apr  4 09:34:16 EDT 2016)
How to reproduce:
```
root@c910f03fsp03v120:~# apt-cache search  libmariadbclient 
libmariadb-client-lgpl-dev - MariaDB Client Library for C, development files
libmariadb2 - MariaDB Client Library for C
 
 root@c910f03fsp03v120:~#  apt-get install libmariadbclient18 mariadb-client  mariadb-common mariadb-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmariadbclient18
```

**Comment by whowutwut** [comment]
@junxiawang can you point out the URL for the document on RTD that does not work?

**Comment by cxhong** [comment]
for ubuntu 16.04,  libmariadbclient is replaced by libmariadb2.  I will take this issue to verify and will need to update the documentation.

**Comment by cxhong** [comment]
For ubuntu 16.04 mariadb, libmariadbclient18 is not required,  **apt-get install mariadb-server** will pull in all the needed packages for setup mariadb.

**Comment by cxhong** [comment]
For ubuntu 16.04.4 mariadb, **apt-get install mariadb-server** will pull in all the needed packages and included libmariadbclient18
