### ISSUE TITLE
[DEV] rsetboot -p option didn't work

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#918]
How to reproduce this scenario.
```
rsetboot c910f04x20 net -p
nodeset c910f04x20 osimage=rhels6.7-x86_64-install-compute
rpower c910f04x20 boot
```
after the provision.
```
nodeset c910f04x20 osimage=rhels6.7-x86_64-install-compute
rpower c910f04x20 boot
```
The node boot from the disk not from the net.
The environment:
```
[root@c910f04x21 ~]# lsxcatd -v
Version 2.12 (git commit 4cea60a61466f5cab33f76afffe55544633de677, built Thu Apr  7 09:30:57 EDT 2016)
[root@c910f04x21 ~]# lsdef -t node c910f04x20
Object name: c910f04x20
    arch=x86_64
    bmc=10.4.20.254
    cons=ipmi
    conserver=c910f04x21
    currchain=boot
    currstate=install rhels6.7-x86_64-compute
    getmac=ipmi
    groups=compute
    hcp=10.4.20.254
    hosttype=kvm
    initrd=xcat/osimage/rhels6.7-x86_64-install-compute/initrd.img
    installnic=mac
    ip=10.4.20.1
    kcmdline=quiet repo=http://c910f04x21:80/install/rhels6.7/x86_64 ks=http://c910f04x21:80/install/autoinst/c910f04x20 ksdevice=40:f2:e9:0a:8c:64  cmdline  console=tty0 console=ttyS0,115200
    kernel=xcat/osimage/rhels6.7-x86_64-install-compute/vmlinuz
    mac=40:f2:e9:0a:8c:64
    mgt=ipmi
    monserver=c910f04x21
    netboot=xnba
    nfsserver=c910f04x21
    os=rhels6.7
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,xHRM bridgeprereq virbr0
    primarynic=mac
    profile=compute
    provmethod=rhels6.7-x86_64-install-compute
    serialport=0
    serialspeed=115200
    status=booted
    statustime=04-12-2016 22:32:47
    tftpserver=10.4.21.1
    updatestatus=failed
    updatestatustime=03-25-2016 04:09:27
    xcatmaster=10.4.21.1
```

**Comment by zet809** [comment]
While I monitoring the boot option parameter of the CN, it seems either OS installer or firmware clear the boot flag set by rsetboot. We may not be able to operate more.

The boot option parameter after "rsetboot <node> net -p"
# ipmitool -I lanplus -H <bmc> -U <username> -P <password> chassis bootparam get 5
Boot parameter version: 1
Boot parameter 5 is valid/unlocked
Boot parameter data: c004000000
 Boot Flags :
   - Boot Flag Valid
   - Options apply to all future boots             =======> To be persistent
   - BIOS PC Compatible (legacy) boot
   - Boot Device Selector : Force PXE          =======> To boot from network
   - Console Redirection control : System Default
   - BIOS verbosity : Console redirection occurs per BIOS configuration setting (default)
   - BIOS Mux Control Override : BIOS uses recommended setting of the mux at the end of POST

The boot option parameter after reboot
# ipmitool -I lanplus -H 10.4.20.254 -U USERID -P PASSW0RD chassis bootparam get 5
Boot parameter version: 1
Boot parameter 5 is valid/unlocked
Boot parameter data: 0000000000
 Boot Flags :
   - Boot Flag Invalid
   - Options apply to only next boot                        ====> The persistent flag is cleared 
   - BIOS PC Compatible (legacy) boot
   - Boot Device Selector : No override                   ====> The boot flag is also cleared
   - Console Redirection control : System Default
   - BIOS verbosity : Console redirection occurs per BIOS configuration setting (default)
   - BIOS Mux Control Override : BIOS uses recommended setting of the mux at the end of POST
