### ISSUE TITLE
[fvt]after set xcatdebugmode=1 compute node's log could not fully saved in management node log 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#92]
1.download the latest build
2.xatdebugmode=1
3.nodeset compute node osimage
rpower compute node boot
4.env
[root@c910f04x27v02 ~]# uname -a
Linux c910f04x27v02 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@c910f04x27v02 ~]# cat /etc/*-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Red Hat Enterprise Linux Server release 6.5 (Santiago)
[root@c910f04x27v02 ~]#

5.
on computenode :
cat /var/log/xcat/xcat.log
++ uname -s
++ tr A-Z a-z
+ '[' linux = linux ']'
++ dirname ./syslog
+ str_dir_name=.
+ . ./xcatlib.sh
++ declare -a array_nic_params
++ declare -a array_extra_param_names
++ declare -a array_extra_param_values
+ master=c910f04x27v03
+ conf_file=/etc/syslog.conf
+ sysconfig=/etc/sysconfig/syslog
+ init=/etc/init.d/syslog
on management node:
---------> could not find log in management node

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/344
