### ISSUE TITLE
[Customer]initrd stuck in loop and fails to get rootimg.gz for stateless image.

### ISSUE THREAD

**Issue by delhub** [xcat2/xcat-core#921]
While trying to provision a centos 6.6 stateless node, I ran into an issue where the node would proceed just fine with downloading the kernel and initrd images, but hung at getting the rootimg.gz.  After a long process of hacking the initrd-stateless.gz image to determine the root cause, I finally arrived at the /sbin/xcatroot call of /tmp/updateflag.

updateflag is an awk script found at /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag.  I noticed, however, that there are two versions of this script found in the  /opt/xcat/share/xcat/netboot subdirectories.  I found these via md5sum $(locate updateflag | grep opt).  By replacing that script with the alternate script, I was then able to get past the hang and the node booted fine.

Which of these scripts is the true script?  If the original script should have worked, why didn't it?  Is the problem elsewhere?

**Comment by delhub** [comment]
I failed to point out that the issue seems to be isolated to RH and (possibly?) SLES OS'es.  So, it's possible the fix was realized at some earlier point in time, but the change got missed for the RH directories.

 md5sum $(locate updateflag | grep opt)
75f73c60ee564ce8b4c26cb00f28befc  /opt/xcat/share/xcat/netboot/SL/dracut/xcat-updateflag
75f73c60ee564ce8b4c26cb00f28befc  /opt/xcat/share/xcat/netboot/fedora/dracut/xcat-updateflag
75f73c60ee564ce8b4c26cb00f28befc  /opt/xcat/share/xcat/netboot/fedora/dracut_009/xcat-updateflag
75f73c60ee564ce8b4c26cb00f28befc  /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/updateflag.awk
75f73c60ee564ce8b4c26cb00f28befc  /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag
f045edad352dff88086516208603bbf3  /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag.sav
f045edad352dff88086516208603bbf3  /opt/xcat/share/xcat/netboot/rh/dracut_033/xcat-updateflag
f045edad352dff88086516208603bbf3  /opt/xcat/share/xcat/netboot/sles/dracut_033/xcat-updateflag

**Comment by immarvin** [comment]
hi, 
for centos 6.6, the `` /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag`` is used.

you mentioned that "By replacing that script with the alternate script, I was then able to get past the hang and the node booted fine.",   several questions:

1. what is "the alternate script" you mentioned?

2. please check the status of the diskless of your booted node after your workaround, please paste the output of ``lsdef <node>`` if convenient

3. which xcat release you are using(the output of ``lsxcatd -v``)?

**Comment by delhub** [comment]
So, the alternate script I copied is from:
/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/updateflag.awk

Here is the diff between the files.  The latter is the original file that was replaced.

diff /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag /opt/xcat/share/xcat/netboot/rh/dracut/xcat-updateflag.sav
1,3c1,2
< #!/usr/bin/awk -f
< # IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
< 
---
> #!/bin/awk -f
> #script to feedback the node provision status to xcatd
5,20d3
<     xcatdhost = ARGV[1]
<     xcatdport = ARGV[2]
<     flag = ARGV[3]
<     
< 	if (!flag) flag = "next"
< 
< 	ns = "/inet/tcp/0/" ARGV[1] "/" xcatdport
< 
< 	while(1) {
< 		if((ns |& getline) > 0)
< 			print $0 | "logger -t xcat -p local4.info"
<         else {
<             print "Retrying flag update" | "logger -t xcat -p local4.info"
<             close(ns)
<             system("sleep 10")
<         }
22,26c5,6
< 		if($0 == "ready")
< 			print flag |& ns
< 		if($0 == "done")
< 			break
< 	}
---
>         xcatdhost = ARGV[1]
>         xcatiport = ARGV[2]
28d7
< 	close(ns)
30,31c9,13
< 	exit 0
< }
---
>         ns = "/inet/tcp/0/" xcatdhost "/" xcatiport
>         print "xCAT_xcatd" |& ns
> 
>         while(1) {
>                 ns |& getline
32a15,24
>                 if($0 == "ready")
>                         print ARGV[3] |& ns
>                 if($0 == "done")
>                         break
>         }
> 
>         close(ns)
> 
>         exit 0
> }


lsdef es01
Object name: es01
    arch=x86_64
    bmc=10.181.4.101
    bmcpassword=xcatRoot
    bmcusername=xcatPassord.
    currstate=netboot centos6.6-x86_64-eng
    groups=ipmi,engrack01,eng,all
    initrd=xcat/osimage/centos6.6-x86_64-netboot-eng.20160331/initrd-stateless.gz
    installnic=14:18:77:49:60:41
    kcmdline=imgurl=http://!myipfn!:80//install/netboot/centos6.6/x86_64/eng/20160331/rootimg.gz XCAT=!myipfn!:3001 NODE=es01 FC=0  LOGSERVER=!myipfn!  syslog.server=!myipfn! syslog.type=rsyslogd syslog.filter=*.*  xcatdebugmode=1 BOOTIF=14:18:77:49:60:41  console=tty0 console=ttyS0,115200n8r
    kernel=xcat/osimage/centos6.6-x86_64-netboot-eng.20160331/kernel
    mac=14:18:77:49:60:41!es01-1814
    mgt=ipmi
    netboot=xnba
    os=centos6.6
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=eng
    provmethod=centos6.6-x86_64-netboot-eng.20160331
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=04-01-2016 13:08:52
    updatestatus=failed
    updatestatustime=04-13-2016 23:56:50


lsxcatd -v
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)

**Comment by immarvin** [comment]
hi, would you please make sure the dns server on MN is running and it is well configured for node es01.

you can check this with ``nslookup`` 

I am afraid this is related to a issue https://github.com/xcat2/xcat-core/issues/712, which was found on diskfull installation

**Comment by immarvin** [comment]
since there is no feedback from the creator, this issue will be put off to 2.12.1

**Comment by delhub** [comment]
Sorry for the delay (too many fires to put out up here).  I'm not sure what other info you need from me.  What I can tell you is that once I replaced the script as described above, the rootimg was delivered.  So that fixed the issue.  

However, what may be related to  issue #712, is the fact that it is stuck at completion of the /etc/rc3.d/S61xcatpostinit script as you can see in the following pstree snippet

  |-rc,2937 /etc/rc.d/rc 3
  |   `-S61xcatpostinit,3757 /etc/rc3.d/S61xcatpostinit start
  |       `-xcatdsklspost,3761 /opt/xcat/xcatdsklspost
  |           `-xcatdsklspost,3905 /opt/xcat/xcatdsklspost
  |               `-updateflag.awk,6010 -f //xcatpost/updateflag.awk 140.208.192.26 3002 installstatus\040booted
  |                   |-logger,6011 -t xcat -p local4.info
  |                   `-sleep,6982 10

I'm not sure how to proceed here.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/1454
