### ISSUE TITLE
[FVT]: sync up test cases in 2.12 with 2.11

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#923]
I run regression on 2.11 branch and found some cases is out-dated. Please sync up test cases in 2.12 with 2.11
1. ubuntu_full_installation_p8le
2. ubuntu_diskless_installation_p8le
3. makentp
Add following case in 2.11
1. reg_linux_statelite_installation_hierarchy_by_ramdisk
2. reg_linux_statelite_installation_hierarchy_by_nfs

**Comment by tingtli** [comment]
@caomengmeng  How about the progress?

**Comment by caomengmeng** [comment]
Already updated, so close it
