### ISSUE TITLE
[DEV] some vm commands do not exit if errors are detected.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#932]
Some vm commands do not exit if errors are detected. For example mkvm without specifying -s option will display an error message and hang. CTRL-C is needed to break out.
Most likely "die" is used to exit from the Perl module instead of returning to the caller with "return".

**Comment by whowutwut** [comment]
Moving the KVM virtualization support/cleanup/enhancements to 2.13 release

**Comment by samveen** [comment]
Another example:
```[samveen@xcatmn1 ~]# mkvm prometheus1 -m kvm1 -s 10G --mem 1024 --cpus 1
Error: kvm plugin bug, pid 57609, process description: 'xCATd SSL: mkvm to prometheus1 for samveen@localhost: kvm instance' with error 'Unable to find any persistent disks at dir:///data/vms/ at /opt/xcat/lib/perl/xCAT_plugin/kvm.pm line 505.
' while trying to fulfill request for the following nodes: prometheus1
(... command doesn't exit ...)
```

**Comment by whowutwut** [comment]
moving this back to 2.12.1 to see if we can fix it before 2.13.

**Comment by samveen** [comment]
@gurevichmark Yeah, your observation about the use of `die(...)` is bang on target:
```
[samveen@catmn1 ~]# tail -n +505 /opt/xcat/lib/perl/xCAT_plugin/kvm.pm |head -n1 
                    die "Unable to find any persistent disks at ".$disk_parts[0];
```

**Comment by daniceexi** [comment]
Looks like ``Sys::Virt`` is not safe to run directly. We should use ``eval`` to run and check the result from ``$@``;

~~~~
eval {  manipulate kvm };

if ($@) {
   # handle the error;
}

**Comment by whowutwut** [comment]
@daniceexi  👍   We need to gracefully return instead of die otherwise the commands will hang and ctrl-c needs to be used to get out of the plugin...

**Comment by gurevichmark** [comment]
Noticed that if XCATBYPASS is set, the `die` exits gracefully, but if XCATBYPASS is not set, the kvm.pm plugin is called through the xcatd daemon. In that case, `die` hangs.
I do not see a value of exiting using a `die` when some error is detected. I think we should just print an error message and exit with `exit 1`. Unlike `die`, exiting with `exit` would not print a line number where error has occurred. But who would care about a line number if we print a good error message ?

**Comment by daniceexi** [comment]
@gurevichmark ``XCATBYPASS`` makes the command does not go through the xcatd. 

* Does kvm process hang when die is called in any place of the kvm.pm?
* Generally speaking, return to the parent call is good idea even when failure happens.

**Comment by gurevichmark** [comment]
@daniceexi After some further debugging, I found the following:

In kvm.pm there is a function **dohyp()** containing this block of code:

     eval {    #Contain Sys::Virt bugs that make $@ useless
        if ($hyp eq '!@!XCATDUMMYHYPERVISOR!@!') { #Fake connection for commands that have a fake hypervisor key
            $hypconn = 1;
        } elsif (not $offlinehyps{$hyp}) {
            $hypconn = Sys::Virt->new(uri => "qemu+ssh://root@" . $hyp . "/system?no_tty=1&netcat=nc");
        }
    }

If I call `die` right before this block, it exist as you would normally expect, but if I call `die` right after this block, it hangs.

I also tried removing the `eval`. In that case calling `die` before `$hypconn = Sys::Virt->new()`, exits normally, but calling `die` after, hangs.

**Comment by daniceexi** [comment]
@gurevichmark 
The Sys::Virt tries to handle the exceptions by itself. But  ``die`` sentence also tries to hanel the exception. So there might be conflict.

**Comment by gurevichmark** [comment]
I think I found the problem:
In `dohyp()` we call `$hypconn = Sys::Virt->new(uri => "qemu+ssh://root@" . $hyp . "/system?no_tty=1&netcat=nc");` to create a Sys::Virt class instance and assign it to a **GLOBAL** variable `$hypconn`
It appears that hang happens when we try to `die` without releasing the `$hypconn`. However if before `die` we call `undef $hypconn`, then `die` exits as one would expect.

**Comment by daniceexi** [comment]
@gurevichmark then we can use a simple script to create this die issue, right? I mean, after ``Sys::Virt->new``, if we die immediately, it would hang, right?

**Comment by gurevichmark** [comment]
Yes. If I put `die` right after the call to `Sys::Virt->new`, it hangs. I am not sure if I can make a simple script to test because the hang only happens if kvm.pm is called through `xcatd`. If I set `XCATBYPASS`, hang does not happen.

I am also questioning if `die` is the right way to exit for this particular error. The user issues `mkvm` command and forgets to specify `-s` flag for the storage space needed. With a `die` they will see this message:

```Error: kvm plugin bug, pid 25035, process description: 'xcatd SSL: mkvm to mgXgeneratedvm2 for root@localhost: kvm instance' with error 'Unable to find any persistent disks at dir:///var/lib/libvirt/images
' while trying to fulfill request for the following nodes: mgXgeneratedvm2```

The message makes it look like xCAT has a bug in kvm.pm plugin. If instead of `die` we do `exit`, we can just display this message which seems a lot friendlier:

```Unable to find any persistent disks at dir:///var/lib/libvirt/images```

**Comment by daniceexi** [comment]
I agree that we should replace all the ``die`` with a correct return.
