### ISSUE TITLE
[FVT] updatenode -S  do not support  local directory  

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#94]
How to reproduce:
root@c910f04x27v08:~# lsdef -t osimage -o ubuntu14.04.2-x86_64-install-compute
Object name: ubuntu14.04.2-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osname=Linux
    osvers=ubuntu14.04.2
    otherpkgdir=/install/post/otherpkgs/ubuntu14.04.2/x86_64
    pkgdir=/install/ubuntu14.04.2/x86_64
    pkglist=/opt/xcat/share/xcat/install/ubuntu/compute.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/ubuntu/compute.tmp
Here using  updatenode -S  only could generate valid path in CN sourses.list.d xCAT..path0.list if pkgdir is using http ,but we should support directory here.

**Comment by bybai** [comment]
Investigate results:
ospkgs will run in compute node. If we use directories in pkgdir like "pkgdir=/install/ubuntu14.04.2/x86_64,/install/post/test", it is not wise to check if these directories are correct ubuntu packages mirror from compute node to management node; If these directories are invalid mirror, "apt-get update" will failed from compute node.
After discussed with team, the agreement is "pkgdir format only support multiple local/remote http mirror, its format cannot be directory, invalid format like /install/ubuntu14.04.1/x86_64/". This is updated/fixed into ubuntu quick start doc. The code will not be changed.

**Comment by whowutwut** [comment]
Re-opening, FVT should verify and close once verified

**Comment by daniceexi** [comment]
Jun Xia has verified fix.
