### ISSUE TITLE
[PCM] CN IP loss after 12 hours due to the dhcp.lease timeout value 43200

### ISSUE THREAD

**Issue by xyzcaoli** [xcat2/xcat-core#942]
1. after PCM installation under rhel 7.2, one setting is here
[root@pcmrhe72 ldap]# tabdump site | grep lease
"dhcplease","43200",,

2. Then add node and provision PCM compute node, after node provision, everything goes well for compute node getting and keeping IP addr

3. but after 12 hours, the PCM compute node will lost IP info, those node will lost connection from PCM Management Node

4. the xcat/OS version is below
[root@pcmrhe72 ldap]# lsxcatd -v
Version 2.11 (git commit c3bb309ccf5dc70d4261a96a40dcf55a3b3e3a74, built Tue Dec 22 23:57:00 EST 2015)
[root@pcmrhe72 ldap]# rpm -qa | grep -i xcat  
xCAT-genesis-base-x86_64-2.9-snap201503060727.noarch
xCAT-buildkit-2.11-snap201512222357.noarch
perl-xCAT-2.11-snap201512222357.noarch
conserver-xcat-8.1.16-10.x86_64
elilo-xcat-3.14-4.noarch
xCAT-genesis-scripts-x86_64-2.11-snap201512222357.noarch
ipmitool-xcat-1.8.15-1.x86_64
xCAT-client-2.11-snap201512230028.noarch
xCAT-2.11-snap201512230028.x86_64
xCAT-vlan-2.11-snap201512222357.noarch
xCAT-server-2.11-snap201512230028.noarch

5.  OS info
[root@pcmrhe72 ldap]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID:    RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:    7.2
Codename:    Maipo

6. The issue only could be encountered under rhel7.2, for example w/ the save PCM and xCAT, the issue can not be encountered SLES11.3, also the setting on site table is "43200". Seems under rhel7.2, when DHCPD IP leasing time, expired, the lease could not be renewed.

**Comment by xyzcaoli** [comment]
@zet809

**Comment by zet809** [comment]
It is found that the dhclient process is stopped later after the CN is rebooted after installation. The dhclient is triggered by NetworkManager service. 
We have stoped the NetworkManager about reboot, and then the dhclient is terminated by the service. That is why the IP address is missing when using DHCP.
We are discussing how to fix it without affect other functions. Will update once there is a result.

**Comment by whowutwut** [comment]
@zet809 Thanks for this analysis! it makes sense..   My initial guess would have also been NetworkManager, i see many new OS using this and we disable it.

**Comment by daniceexi** [comment]
The issue has been fixed.

#966 for 2.11 branch
commit 52061dd6623a8bf81dd9145653759428c1b89fd5 for 2.12 branch

**Comment by daniceexi** [comment]
It has been fixed, so close it now.
