### ISSUE TITLE
7.2 node can not renew dhcp lease

### ISSUE THREAD

**Issue by coldbloodx** [xcat2/xcat-core#944]
Hi all:

I've found an issue on a node that is provisioned by xCAT on RHEL 7.2

When the node is provisioned, and after 12 hours, the IP address of the node disappeared.

The node can not renew the dhcp lease.

Please help to check this issue.

Both my MN and CN are RHEL 7.2.

Thanks,
Xian

**Comment by whowutwut** [comment]
This issue is duplicate to #942
