### ISSUE TITLE
#168 Allow use of parallel implementations of gzip and bzip2 in xCAT

### ISSUE THREAD

**Issue by chrissamuel** [xcat2/xcat-core#95]
Created: 2014-02-04 on SourceForge.

It would save a lot of time when building stateless/statelite images if xCAT could use one of the parallel gzip/bzip2 implementations in (for instance) RHEL6 EPEL if it were present.

Possibly the most unintrusive way would be to have an entry in the site file to define the gzip and bzip2 commands to use (and if not present default to the tried and true standard versions), that way if a site choses to use a parallel version they have to make a conscious decision to do so and if it breaks they get to keep both parts (and can rapidly undo the damage).

For the record in EPEL there are currently pigz (Parallel Implementationg of GZip), lbzip2 and pbzip2.

Thanks!
Chris

Follow up - I'm currently building a new cluster and doing a lot of osimage rebuilds this would have been *really* useful to have had..

**Comment by daniceexi** [comment]
You point is to make a choice for user to choose the 'pigz' or 'pbzip2' to compress the 'rootimg.gz' and decompress it during the network boot? 

How many time it can save for you?

**Comment by chrissamuel** [comment]
For a real osimage we're building it was almost 4 minutes (3m 55s) with gzip versus about 11 seconds with pigz on this Haswell box (32 cores).

I re-ran the gzip test again straight after the pigz run to make sure I wasn't seeing things and it took 3m 53s instead.

[root@snowy-m tmp]# time gzip -9 rootimg-statelite 

real    3m55.407s
user    3m54.316s
sys     0m0.931s

[root@snowy-m tmp]# time pigz -9 rootimg-statelite 

real    0m11.317s
user    4m46.560s
sys     0m1.198s

[root@snowy-m tmp]# time gzip -9 rootimg-statelite 

real    3m53.785s
user    3m52.760s
sys     0m0.837s


Testing on a Sandybridge box (8 cores) with a production osimage shows that was 6m 34s with gzip -9 versus 51s with pigz -9.

It's a pretty substantial improvement (depending on how many cores you have).

**Comment by chrissamuel** [comment]
@daniceexi Sorry I forgot to address the first part of your question - I was thinking this would be a config option for building osimages, not necessarily for uncompressing on compute nodes, that's actually not too bad (and as pigz is in EPEL not base RHEL it's probably a bit much of an ask to push it out in the PXE image).

**Comment by daniceexi** [comment]
@chrissamuel Lost your point that rootimg.gz will be used by the compute node, in this case the compue node must can uncompress it. Is there any way that rootimg.gz is not used by compute node?

**Comment by chrissamuel** [comment]
@daniceexi pigz = "Parallel Implementation of GZip - it's completely compatible with gzip on the compute node and so the compute node doesn't need pigz at all.

This feature is purely for the management node to make it much quicker to compress the images for diskless nodes.

**Comment by arif-ali** [comment]
I like the idea of this, this will make it much quicker to do for stateless and statelite ramdisk creation, so :+1:  from me

**Comment by immarvin** [comment]
hi,

I did some investigation in this idea on sles12, redhat 7.1 and ubuntu14.04.3, some points:
1. the packages of pigz:
   sles12 and ubuntu 14.04.3: shipped in the base iso or official mirror, pigz can be specified in the spec file of xcat-server 
   redhat 7.1:  shipped in epel, need to install  "epel-release" and "pigz"  as the dependency of xcat-server, or ship pigz as a xcat dependency

2. the compress and decompress(only dracut case):
   during genimage,  the initrd can be generated with dracut option " --compress pigz"
   during packimage, the rootimage can be compressed with pigz
   just as @chrissamuel pointed out, the file compressed with pigz is compatible with gzip , so we do not need to care the uncompress process

3. the compress/uuncompress speed:
   on a management node with multi-cpus, the compress speed can be greatly improved, here is some test result on a Redhat7.1 x86_64 machine with  7 cpus:

[root@c910f04x18 rootimg]# time find . -xdev |cpio -H newc -o | pigz -c - > ../rootimg.gz
1292340 blocks

real    0m7.398s
user    0m53.896s
sys     0m2.487s
[root@c910f04x18 rootimg]# time find . -xdev |cpio -H newc -o | gzip -c - > ../rootimg.gz
1292340 blocks

real    0m55.236s
user    0m55.125s
sys     0m3.094s

the optimum compress performance appears when the number of processes specified with "-p" equals the cpu number. 
for genimage, there is no /proc/cpuinfo in the chrooted rootimage, we need to copy the /proc/cpuinfo of the management node into the rootimage to improve the compress speed.
for kvm, it seems that the optimum compress speed   appears when the process count equals the cpu number  of kvmhost

**Comment by zet809** [comment]
1. If no '-p' specified, how many CPUs will pigz choose?
    From your test result, seem it will choose all the physical CPUs to compress, right?
2. For genimage, if just mount /proc into chroot works? I think it will be used by pigz to find out how many CPUs there.
3. For kvm, I agree with you. But if the CPUs are in dedicate mode, will this kind of configuration affect other VMs?

**Comment by chrissamuel** [comment]
@zet809 regarding what happens without -p, the manual page says:

`The number of compress threads is set by default to the number of online processors, which can be changed using the -p option.`

**Comment by immarvin** [comment]
hi, 
the code is ready for review here
 “use pigz to improve the performance of genimage/packimage #128“

the document will be ready soon
