### ISSUE TITLE
[FVT]genimage for sles11.4 has some warning output

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#950]
xCAT 2.11.1
sles11.4 ppc64
When run "genimage sles11.4-ppc64-netboot-compute", get some tricky warnings. Please take a look.

WARNING: Couldn't find /etc/security/pam_unix2.conf{.rpmsave} (No such file or directory).
WARNING: Couldn't find /etc/security/pam_pwcheck.conf{.rpmsave} (No such file or directory).
WARNING: Couldn't load old config files.

**Comment by immarvin** [comment]
if it does not affect the provisioned diskless node or halt the "genimage",  it is ok to just ignore them

**Comment by daniceexi** [comment]
@immarvin Which package gives this warning message? And why the file ** /etc/security/pam_unix2.conf** does not exist? Missed dependency packages?

**Comment by daniceexi** [comment]
Since it's an issue caused by the install in chroot env, we cannot do too much. Close it.
