### ISSUE TITLE
[FVT]Failed to find expected logs while site.xcatdebugmode=1 for ubuntu on ppc64le

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#954]
Description:
According to the design doc:　https://github.com/xcat2/xcat-core/wiki/support%20new%20values%20for%20site.xcatdebugmode
while the site.xcatdebugmod=1/2 for ubuntu installation, the Y3: installation logs can be forwarded to the MN in /var/log/xcat/computes.log file without export to subsequent commands.
But there isn't this kind of file in MN:/var/log/xcat, only the below two logs:
```
root@c910f03fsp03v10:/var/log/xcat# ls
commands.log  xcat.log
```
And failed to find most of the excepted logs in the two files.
ENV.
```
root@c910f03fsp03v10:/opt/xcat/share/xcat/tools/autotest# lsxcatd -a
Version 2.12 (git commit 641af3c6a0fcec382c4482d8c0abc6717c06af3d, built Thu Apr 14 09:32:00 EDT 2016)
This is a Management Node
dbengine=SQLite
```

**Comment by penguhyang** [comment]
This bug is not only related to permission but also the chroot environment.
The pull request #984 make the logger can save info to MN after provision.
But the log can't be forwarded to MN when provisioning node.
I think it's related to the chroot. The reason for this is that the chroot’ed process can not open /dev/log as this is not within the chrooted filesystem.

**Comment by daniceexi** [comment]
So looks like @penguhyang thinks the issue has not been fixed and I don't see the possibility to fix in 2.12. Since it's a log related issue, move it to 2.12.1

**Comment by whowutwut** [comment]
I'm a little confused. Why does chroot come into play here? Is this related to diskless?

**Comment by daniceexi** [comment]
@whowutwut I think @penguhyang meant the phase that run the post script in the Ubuntu diskful installer. In that phase the installer needs chroot to the new installed file system to run script.
