### ISSUE TITLE
[FVT]2.11.1 could not configure  xCAT to MariaDB on rhels7.2

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#957]
env:rhels7.2
build:lsdef - Version 2.11.1 (git commit b6e4c8ca1847bf574d7e86687d74a7f2576d428a, built Thu Apr 14 09:32:27 
How to reproduce:
```
[root@c910f03fsp03v140 ~]# mysqlsetup -i
Input the alpha-numberic  password for xcatadmin in the MySQL database: 
Input the password for root in the MySQL database: 
Command failed: /usr/bin/mysql_install_db --user=mysql 2>&1. Error message: .

 /usr/bin/mysql_install_db --user=mysql failed.

```

**Comment by immarvin** [comment]
please refer to the http://xcat-docs.readthedocs.org/en/latest/advanced/hierarchy/databases/mysql_install.html and make sure the mariadb related packages have been installed

**Comment by immarvin** [comment]
checked with @junxiawang , the packages mentioned in the doc were not installed, so this is a usage error.
