### ISSUE TITLE
[Customer]getmacs returns wrong MAC address in flex blade environment. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#958]
MN: .9.114.26.136
the MAC address via getmacs is not the address for the blade, which cause the installation failed. 

[root@c865mgrs2 ~]#  lsdef c865bc03fb01
Object name: c865bc03fb01
    arch=ppc64
    cons=fsp
    currstate=netboot rhels6.7-ppc64-compute
    getmac=blade
    groups=all,bc3,blade
    hcp=10.0.0.31
    hwtype=blade
    id=1
    initrd=xcat/osimage/ww32compute_rh67/initrd-stateless.gz
    installnic=mac
    kcmdline=imgurl=http://!myipfn!:80//install/netboot/rhels6.7/ppc64/ww32compute_rh67/rootimg.gz XCAT=!myipfn!:3001 NODE=c865bc03fb01 FC=0  LOGSERVER=!myipfn!  syslog.server=!myipfn! syslog.type=rsyslogd syslog.filter=*.*  xcatdebugmode=1 BOOTIF=00:10:18:e6:ad:58
    kernel=xcat/osimage/ww32compute_rh67/kernel
    mac=00:90:fa:08:0a:ce
    mgt=fsp
    mpa=c865cmm3
    mtm=789542X
    netboot=yaboot
    nodetype=ppc,osi
    os=rhels6.7
    parent=c865cmm3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=ww32compute_rh67
    serial=06610BB
    slotid=1

[root@c865mgrs2 ~]# lsslp -u --range 10.0.0.31 -s FSP
Processing range 10.0.0.31...
Begin to do unicast to 1 nodes...
1 requests with 1 responses.  Now processing responses.  This will take 0-1 minutes...
device  type-model  serial-number  side  ip-addresses  hostname
fsp     7895-42X    06610BB        A-0   10.0.0.31     10.0.0.31

[root@c865mgrs2 ~]# lsdef c865bc03fb01 -i mtm,serial
Object name: c865bc03fb01
    mtm=789542X
    serial=06610BB
[root@c865mgrs2 ~]# getmacs c865bc03fb01
c865bc03fb01: mac.mac set to 00:10:18:e6:ad:58
when we interrupt into SMS while installation, we can see the MAC is 00:90:fa:08:0a:ce.

**Comment by wwzhubj** [comment]
After I reset the cmm3, the MAC address is correct via getmacs.

**Comment by zet809** [comment]
@wwzhubj Thx!.
