### ISSUE TITLE
[DEV]Does nodeset block when it cannot create the /tftpboot files?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#964]
I hit some problems today because my management node was not configured right. Opening this issue as a reminder to have someone investigate this to see the behavior.  

I did not run `makedns` or `makedhcp` yet on the xCAT management machine and tried to provision a node.   The nodeset command did flag an error 

```
# nodeset c910f05c29 osimage=ubuntu14.04.3-ppc64el-install-compute
Warning: rcons my not work since no serialport specified
c910f05c29: install ubuntu14.04.3-ppc64el-compute
Error: The c910f05c29 can not be resolved
```

I missed that error and did a `rsetboot <> net` and then `rpower off/on`. 

The `/tftpboot/petitboot` files were missing but it still allowed me to provision the machine.  So it wasn't until I started debugging this that I realized /tftpboot was empty and then started working backwards..   

Should we have blocked the rsetboot net command if we do not find any files in /tftpboot directory.. or if we are unable to create the files from the nodeset command ,we should error 

Of course, maybe we do have the errrors, but my test machine already passed so I wanted to open this to investigate if we block if we cannot create the /tftpboot files  Maybe someone can easily answer it.

**Comment by daniceexi** [comment]
@whowutwut 
From the design of the command **rsetboot** and **rpower** that they don't know the current context is **hw control** or **OS deployment**. So I'd like something else to cover this usage error.

I am thinking to enhance the **rinstall** command to make it applicable for all the Arch. This command will cover the failure of nodeset. If nodeset failed, it will stop.

**Comment by immarvin** [comment]
hi Victor,

the rsetboot and rpower are hardware control commands, without the 
context, we cannot determine what the user want to do with them. The user 
might want to issue a node provision, or just want to reset the power of 
the node.

------------------------------------------------------------------------------
 YANG Song (杨嵩)
 IBM China System Technology Laboratory
 Tel: 86-10-82452903
 Email: yangsbj@cn.ibm.com
 Address: Building 28, ZhongGuanCun Software Park,
          No.8, Dong Bei Wang West Road, Haidian District Beijing 100193, 
PRC

北京市海淀区东北旺西路8号中关村软件园28号楼
邮编: 100193

**Comment by daniceexi** [comment]
This issue will be covered by the new **rinstall** command.

**Comment by daniceexi** [comment]
This issue will be covered by the new **rinstall** command.

**Comment by whowutwut** [comment]
Looking at this a little more, are we able to block this line from printing out? 
`c910f05c29: install ubuntu14.04.3-ppc64el-compute`

This way if we have an error, it's more clear.  I think this above line indicates that things are OK?

**Comment by immarvin** [comment]
duplicate with https://github.com/xcat2/xcat-core/issues/2492

**Comment by whowutwut** [comment]
Since this is duplicate, closing
