### ISSUE TITLE
[FVT]2.12 switchdiscover's node's name is invalid

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#970]
env:[root@c910f04x30 7.1]# cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
build:
[root@c910f04x30 7.1]# lsdef -v
lsdef - Version 2.12 (git commit 750e82f4f2a77a9e2c870b1776169b2a33110300, built Mon Apr 25 09:31:08 EDT 2016)
How to reproduce:
```
switchdiscover --range 10.4.25.0/24,192.168.0.0/24 -s snmp -w
lsdef 
[root@c910f04x30 7.1]# lsdef
Juniper_01  (node)
[root@c910f04x30 7.1]# makedns -n
Ignoring line 10.4.25.1 Juniper_01 Juniper_01.pok.stglabs.ibm.com  in /etc/hosts, names  Juniper_01 Juniper_01.pok.stglabs.ibm.com  contain invalid characters (valid characters include a through z, numbers and the '-', but not '_'
Handling c910f04x30v12 in /etc/hosts.
```

**Comment by cxhong** [comment]
User or Admin define the switch name , should we prompt this as error and ask user to change the name or should xCAT accept host name has '_' ?

**Comment by daniceexi** [comment]
Generally, it's not necessary to add the switch in the dns system. So if the switch name was named by user, I think it's ok to keep it. But we need to add a warning message in the output of **switchdiscover** command.

BTW, what the name will be for a manufacture default switch?

**Comment by junxiawang** [comment]
@cxhong  ,@daniceexi  I think the switch name discovered by snmp should be same with switch name discovered by nmap

**Comment by cxhong** [comment]
the hostname is based what the snmp/nmap command returned.  if xcat didn't see the hostname from command output, it will create a hostname based on ip address, ex: switch-10-5-23-1.
Sometime nmap_scan will not find hostname.  snmp_scan is more reliable for this case.

**Comment by daniceexi** [comment]
So for this switch, the **-s nmap** will get the switch name to be 'switch-10-5-23-1', but the **-s snmp** will get the 'Juniper_01', am I right?

If this is the case, I am fine with this. And also since the name like **Juniper_01** was named by user instead of xCAT. xCAT cannot correct this name through code automatically.

**Comment by cxhong** [comment]
yeh, user pick up the name, xCAT cannot correct that.  I will close this issue.
