### ISSUE TITLE
[FVT]2.12:could not  discover switch using switchdiscover -s snmp on sles 11.4 environment

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#971]
env:
c910f02c01p14:~ # cat /etc/*-release
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64"
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
SUSE Linux Enterprise Server 11 (ppc64)
VERSION = 11
PATCHLEVEL = 4
c910f02c01p14:~ # 
build:
lsdef - Version 2.12 (git commit b908019a59bcb53fbb758ae99e1f0cb4a13d648d, built Sun Apr 24 09:30:54 EDT 2016)
How to reproduce:
```
c910f02c01p14:~ # switchdiscover --range 10.4.25.0/24,192.168.0.0/24 -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.4.25.0/24 192.168.0.0/24 | grep 'open port 161' 
 No switch found 
c910f02c01p14:~ # echo $?
1
In fact we could find switch 10.4.25.1 on rhels7 env
```

**Comment by cxhong** [comment]
works fine on sles12:
`````
# switchdiscover --range 10.4.25.0/24,192.168.0.0/24 -s snmp
Discovering switches using snmpwalk.....
ip              name            vendor                                          mac
------------    ------------    ------------                                    ------------
10.4.25.1       Juniper_01      test juniper switch                             2c:6b:f5:37:45:7f
``````

on sles12.1:

````
 # switchdiscover --range 10.4.25.0/24,192.168.0.0/24 -s snmp
Discovering switches using snmpwalk.....
ip              name            vendor                                          mac
------------    ------------    ------------                                    ------------
10.4.25.1       Juniper_01      test juniper switch                             2c:6b:f5:37:45:7f

````

I don't have sles11.4 system available right now, 
@junxiawang can u able to rerun this command again on your sles11.4 node?

**Comment by junxiawang** [comment]
@cxhong 
c910f02c01p14:~ # switchdiscover --range 10.4.25.0/24,192.168.0.0/24 -s snmp
Discovering switches using snmpwalk.....
Could not process this command: /usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.4.25.0/24 192.168.0.0/24 | grep 'open port 161' 
 No switch found 
c910f02c01p14:~ # c910f02c01p14:~ # cat /etc/*-release
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64"
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
SUSE Linux Enterprise Server 11 (ppc64)
VERSION = 11
PATCHLEVEL = 4

**Comment by cxhong** [comment]
on sles11.4,  the command ```/usr/bin/nmap -P0 -v -sU -p 161 -oA snmp_scan 10.4.25.1``` had different output than other OS,  the output string  : ````Discovered open port 161/udp on 10.4.25.1````  used to grep is not there.    
Need to modify the code to use different method to check if port 161 is opened.
