### ISSUE TITLE
[FVT]2.12 switchdiscover could not find switch Ubuntu using snmp

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#973]
env:
root@c910f04x30v14:~# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@c910f04x30v14:~# 
buid：lsdef - Version 2.12 (git commit 750e82f4f2a77a9e2c870b1776169b2a33110300, built Mon Apr 25 09:32:19 EDT 2016)
How to reproduce:
```
root@c910f04x27v08:~#  switchdiscover --range 10.4.25.1 -s snmp
Discovering switches using snmpwalk.....
 No switch found 
root@c910f04x27v08:~# echo $?
0
root@c910f04x27v08:~# 
------------------------> in fact there are a switch named 10.4.25.1 
```

**Comment by cxhong** [comment]
snmpwalk common on the ubuntu didn't return object name, it only return OID, so I can't use following command:
`````
snmpwalk -Os -v1 -c public $ip sysDescr.0
snmpwalk -Os -v1 -c public $ip ipNetToMediaPhysAddress | grep $ip
snmpwalk -Os -v1 -c public $ip sysName
`````
for sysDescr.0,  the command has to replace like:
````
snmpwalk -Os -v1 -c public 10.4.25.1 1.3.6.1.2.1.1.1
`````

**Comment by junxiawang** [comment]
@cxhong  your means we do not support switchdiscover on ubuntu using snmp?

**Comment by cxhong** [comment]
@junxiawang , I will modified the code to use OID instead of object name
