### ISSUE TITLE
IBM P FLEX RH67 updates

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#975]
For support of RH67 on Power7 flex in HPC the following updates need to be made:
For Mellanox IB support
    add libsysfs.ppc numactl.ppc to otherpkgs list for MOFED
    Need to install MOFED with  ./mlnxofedinstall --with-32bit --force (this level of MOFED does not install 32-bit by default)
IBM PE requires 32-bit kernel, to enable this add the following to your pckglist:
libsysfs
libnl
pciutils
libsysfs.ppc
libnl.ppc
pciutils.ppc

If you install numactl, add numactl.ppc to the package list as well.

In my opinion this could be documented in https://sourceforge.net/p/xcat/wiki/XCAT_system_p_support_for_IBM_Flex/ and/or in the HPC README.

**Comment by hu-weihua** [comment]
@markprez , thanks for your contribution.  I think xCAT IB support framework can work in this scenario. But because this is scenario is not belong to the ones we have verified, so we didn't ship ``pkglist`` for this scenario by default.  I will merge what you contribute to our document.  thanks again.

**Comment by daniceexi** [comment]
Looks like there's no good place to add this doc change, need to talk with @markprez more. Since this is a doc issue and has not relationship with 2.12 release, move it to 2.12.1.

**Comment by markprez** [comment]
I added the information to the HPC Power7 Flex README:
https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Welcome%20to%20High%20Performance%20Computing%20%28HPC%29%20Central/page/IBM%20HPC%20Clustering%20with%20the%20InfiniBand%20Switch%20and%20IBM%20Flex%20System%20p260%20and%20p460%20Compute%20Node%20-%20Service%20Pack%205.0?section=Red%20Hat%206.7%20Installation%20Infor
If you think that info is adequate, we can close the issue.

**Comment by hu-weihua** [comment]
@markprez , thank you for all what you have done, this doc is fine for us.  So I think we can close this issue. thanks again.

**Comment by zet809** [comment]
Since @markprez have updated the corresponding document, we close this defect.
