### ISSUE TITLE
[FVT]:update xCATreg.pl to resolve the miniiso replacement issue

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#978]
We found that when we run xCATreg.pl on ubuntu ppc64le platform,  the MINIISO attribute is replaced by another value.  Need to update xCATreg.pl  

        send_msg(2, "[$mn->$confkeys{$mn}][copy_code] copy ISO $iso to $mn successfully");
        system ("sed -i 's|ISO=/\\S*|ISO=/$iso|g' $configfiledir/$regconf");

**Comment by hu-weihua** [comment]
@tingtli, I have fixed this issue by pull request #979 . Cloud you please review?

**Comment by tingtli** [comment]
This was fixed and worked in the old autotest.
