### ISSUE TITLE
[fvt]2.11.install xcat on sles12 failed for missing /etc/xcat/ca/openssl.cnf

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#98]
How to reproduce:
1.download the latest build
2.c910f04x27v06:/ # cat /etc/*-release
NAME="SLES"
VERSION="12"
VERSION_ID="12"
PRETTY_NAME="SUSE Linux Enterprise Server 12"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12"
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
c910f04x27v06:/ # uname -a
Linux c910f04x27v06 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) x86_64 x86_64 x86_64 GNU/Linux
c910f04x27v06:/ # 
zypper install xcat
dded updates to the /root/.ssh/config file.
Copied /root/.ssh/id_rsa.pub to /install/postscripts/_ssh/authorized_keys.
NFS has been restarted.
/opt/xcat/share/xcat/scripts/setup-dockerhost-cert.sh xcatdockerhost
cp: cannot stat '/etc/xcat/ca/openssl.cnf': No such file or directory
cp: cannot stat '/etc/xcat/ca/private/ca-key.pem': No such file or directory
/etc/xcatdockerca/ca/openssl.cnf not existCould not create xCAT dockerhost certificate in /etc/xcatdockerca/cert.
/root/.xcat already exists, delete and start over (y/n)?grep: /etc/xcat/ca/index: No such file or directory
Generating RSA private key, 2048 bit long modulus
...+++
...............................+++
e is 65537 (0x10001)
error on line -1 of /etc/xcat/ca/openssl.cnf
140220240688784:error:02001002:system library:fopen:No such file or directory:bss_file.c:173:fopen('/etc/xcat/ca/openssl.cnf','rb')
140220240688784:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:176:
140220240688784:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:197:
cp: cannot stat 'client-req.pem': No such file or directory
/
Using configuration from openssl.cnf
error loading the config file 'openssl.cnf'
140311566562960:error:02001002:system library:fopen:No such file or directory:bss_file.c:173:fopen('openssl.cnf','rb')
140311566562960:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:176:
140311566562960:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:197:
cp: cannot stat 'root.cert': No such file or directory
cat: /root/.xcat/client-cert.pem: No such file or directory
/
Created xCAT certificate.
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /opt/xcat/lib/perl /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.18.2 /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.18.2 /usr/lib/perl5/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/5.18.2 /usr/lib/perl5/site_perl .) at (eval 15) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, SQLite, Sponge.
 at /opt/xcat/lib/perl/xCAT/Table.pm line 800.

**Comment by zet809** [comment]
It seems this is a packaging issue, and it is disappeared. So close it.
