### ISSUE TITLE
The node status won't be updated to Powering-on after the running of [rpower on]

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-core#980]
In the latest xCAT code, when running **rpower on** to perform an OS deployment, the node **status** attribute won't be updated until the installer is running. So that means in the scenario the original status is **powering-off**, then user run **rpower on** to start the OS deployment. If the OS deployment process failed to start, the node still keeps as **powering-off** even the node has been in power-on state.

I'd like node **status** can be updated to **powering-on** immediately after running **rpower on** command.

**Comment by immarvin** [comment]
hi @penguhyang , please take a look at this feature

**Comment by daniceexi** [comment]
@xuweibj has done the basic code change for mgt=ipmi/blade/hmc/kvm, will change for mgt=fsp in next release. And also @xuweibj will improve the performance of rpower.

**Comment by daniceexi** [comment]
The change has been verified.
