### ISSUE TITLE
[FVT]:update xcattest log recording time

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#982]
xcattest writes log. The log time is system time, but when we write each test case's log in xcatlog, the case  time greenwich time. Need to make the time log file time and the case time the same to use system time.

**Comment by hu-weihua** [comment]
@tingtli , I have fixed this bug by pull request #981. Could you please verify it? thanks

**Comment by tingtli** [comment]
According to daily regression result. This was fixed.
