### ISSUE TITLE
Allow PostGreSQL DB to be configured and used at the time of xCAT install

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#992]
Currently xCAT configured the SQLite DB out of the box.  To convert to PostGreSQL, the user needs to do the following:
1. install xCAT 
2. install PostGreSQL packages and dependencies
3. Run the pgssqlsetup script to convert SQLite to PostGres

I want to be able to have PostGres DB used as the xCAT database when installing xCAT.  So the process is... 
1. Install PostGreSQL packages and Dependencies
2. export XCAT_DATABASE=pgsql
3. install xCAT

**Comment by daniceexi** [comment]
It's a good idea to for customer could choose a commercial DB instead of sqlite. But I am a little concerning that the incorrect configuration of Postgresql would cause the failure of xcat install.

**Comment by whowutwut** [comment]
@daniceexi  What if we only do this on a new install of xCAT where there is no existing instance of postgres running?  This way we do not trample over existing Postgres configurations?

**Comment by daniceexi** [comment]
@whowutwut I am good with your idea. Is Postgresql packages included in the ISO by default for all the xCAT supported OS?

**Comment by whowutwut** [comment]
@robin2008 I think this initially was a requirement from PCM , do you recall anything about that?  I thought when I had asked PCM team, they said it wasn't working, so they just run the `pgsqlsetup` command manually. 

It's been  a while since I had looked at this issue and I thought I had hit some technical problem with this.. but maybe i'm just forgetting.

**Comment by robin2008** [comment]
This feature is required to reduce the time to install xCAT with postgresql out of box (no required the data migration). And it works with the time reduction but not stable enough. Sometime, the PG database setup will fail (it might be related to PG itself, but xcatconfig error handling is not good enough) in spec script (xcatconfig), then it will fall back to sqlite but some key data in site table are missing.  It cause that xCAT cannot be installed successfully even you run 'pgsqlsetup' again.

So, I think it is a good method to if we can improve it with better error handling.

**Comment by zet809** [comment]
Hi, @whowutwut and @robin2008 , what is the conclusion for this requirement? I think it is needed in CRL.

**Comment by robin2008** [comment]
Not seen high priority on it,  it is just small enhancement. And if we support PGSQL for it, then the MYSQL/MariaDB is required too.

**Comment by whowutwut** [comment]
@robin2008 Bringing up a old thread.. I don't necessarily agree with that comment above... 

The focus right now is PostGres... and that's where the requirement comes from.  In order to be quick to get function implemented in a short sprint time window, we need to always reduce scope and only work on things that has a requirement, not what we think everyone wants, that would make the item take a long time to implement if we had to test on all platforms/all databases.... 

If we want to simplify the scope even further to achieve the function, only support this if we detect running on ppc64le RHEL ...  and block otherwise...

**Comment by robin2008** [comment]
Let's close this one first.
