### ISSUE TITLE
[FVT] Need verify MLNX_OFED driver with Ubuntu 16.04 final release against the latest xCAT master build 

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#993]
Since at this time, there is no MLNX_OFED driver for Ubuntu 16.04 released yet. Will verify it later when such a driver is available.

Check the latest MLNX_OFED driver from the link below.
[1] http://www.mellanox.com/page/products_dyn?product_family=26&mtag=linux_sw_drivers

**Comment by whowutwut** [comment]
I am trying to get a beta version of the driver for us to use internally

**Comment by neo954** [comment]
Opened issue #1029

**Comment by daniceexi** [comment]
@neo954 Besides the new opened bug #1029, the verification of Ubuntu 16.04 has been done, right? So I closed this bug.
