### ISSUE TITLE
［FVT]xcattest does not support vmstorage=dir:///var/lib/libvirt/images/  in default.conf

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#995]
When we define vmstorage=dir:///var/lib/libvirt/images/  in default.conf, we found xcattest will read this line but define vmstorage=dir: in node defintion. This is not correct. Need to correct.

**Comment by hu-weihua** [comment]
@tingtli,  I have fixed this issue by pull request #997 . Could you please review #997 ?

**Comment by tingtli** [comment]
This is fixed and we use it in our daily autotest regression.
