### ISSUE TITLE
[FVT]Ubuntu14.04.4 is dash now, so automation test cases should be updated.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#998]
As Ubuntu 14.04.r is using dash by default now,  automation test cases default using bash, which caused so many cases failed in ubuntu 14.04.4, so we need to make changes.

**Comment by hu-weihua** [comment]
@caomengmeng , I have fixed this bug by pull request #1007 .

**Comment by caomengmeng** [comment]
As we discussed, we still use the bash to avoid unexpected issue maybe caused by existed cases.
